### ISSUE TITLE
utility not updated ):

### ISSUE THREAD

**Issue by sajaddp** [uikit/uikit#1002]
Hi
'docs/utility.html' in source code not updated!
![capture](https://cloud.githubusercontent.com/assets/3147493/6290025/54c48876-b939-11e4-8934-30198818de3e.PNG)

**Comment by aheinze** [comment]
please try to clear the browser cache

**Comment by PixelT** [comment]
Progress is moved to the components, but is still visible in menu, when display anything from core menu
