### ISSUE TITLE
Broken Tooltip on Chrome for Mac

### ISSUE THREAD

**Issue by MacWordPress** [uikit/uikit#1003]
Tooltip with position "top", "top-left" or "top-right" has 1px gap above the arrow on Chrome for OS X (Version 40.0.2214.115). On PC Chrome and other PC/Mac browsers it displays correctly.

![tooltip](https://cloud.githubusercontent.com/assets/7726588/6314675/b7ae76e0-b9e8-11e4-8f81-2c61af486411.png)

**Comment by luetn** [comment]
Zoom in or out to remove/reappear the one px gap (also in Firefox)

**Comment by MacWordPress** [comment]
You are right! I did not have 100% zoom.
