### ISSUE TITLE
How To Keep The Footer At The Bottom of the Page? ):

### ISSUE THREAD

**Issue by sajaddp** [uikit/uikit#1005]
Hi
I using .uk-height-1-1 exactly like the example in docs.
but when page not have scroll footer not keep at the bottom.
how can fix it?
(sorry i can't speak english very well.)
![capture](https://cloud.githubusercontent.com/assets/3147493/6318271/54ce1f38-ba9e-11e4-9e0e-733de998cd81.PNG)

**Comment by saschadube** [comment]
Please ask for help in the [UIkit Google+ community](https://plus.google.com/communities/114238665434626719878)
