### ISSUE TITLE
Feature request: Mobile friendly datepicker

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1006]
http://i.stack.imgur.com/SzmcI.png

**Comment by aheinze** [comment]
```<input type="date">```

**Comment by zslabs** [comment]
@aheinze This does not work. If you set the input to a "date" type then Chrome's native datepicker kicks in and doesn't allow the datepicker to work. Here's the relevant discussion https://plus.google.com/+GoogleChromeDevelopers/posts/hTcMLVNKnec

**Comment by zslabs** [comment]
Looks like setting the input to `readonly` when `text` type is used should work. Disables the native iOS keyboard, but click events still work
