### ISSUE TITLE
Alert when resource not found

### ISSUE THREAD

**Issue by malles** [uikit/uikit#1007]
When a resource is not found in the lightbox component, an alert is fired saying so. https://github.com/uikit/uikit/blob/master/src/js/components/lightbox.js#L167
Isn't there a more subtle way to communicate that?

**Comment by zslabs** [comment]
I agree -- think this could be done with a content-box within the lightbox that says the resource wasn't found. That way, they could still interact with the lightbox without the obstruction.

**Comment by aheinze** [comment]
done https://github.com/uikit/uikit/commit/5d12bb9a0968f8adf8ae98dae8aa9a4b14a69d68
