### ISSUE TITLE
DatePicker does not show properly on Firefox

### ISSUE THREAD

**Issue by ItachiSan** [uikit/uikit#1009]
As in title.
The exact code (with some part hidden) is:
```html
<form class="uk-form uk-form-horizontal" method="SOME_METHOD" action="SOME_ACTION">
...
    <fieldset data-uk-margin>
        <div class="uk-form-row">
        	<label class="uk-form-label">Scadenza iscrizioni</label>
        	<div class="uk-form-controls">
        	<form class="uk-form">
			    <input type="" data-uk-datepicker="{format:'DD.MM.YYYY'}">
            </form>
        	<input type="" data-uk-datepicker="{format:'YYYY-MM-DD'}" name="scadenza" placeholder="Scadenza iscrizioni">
        	<input type="date" name="scadenza" placeholder="Scadenza iscrizioni">
        	</div>
        </div>
...
    </fieldset>
</form>
```
This is how it results in Firefox:
![schermata da 2015-02-23 20 10 53](https://cloud.githubusercontent.com/assets/1223421/6335048/f1a21d0a-bb98-11e4-864e-9a33852d2c04.png)
Instead, in Chromium, as you can see, works fine:
![schermata da 2015-02-23 20 10 26](https://cloud.githubusercontent.com/assets/1223421/6335058/092afe2e-bb99-11e4-8b4c-c985df81960f.png)
... Well, somehow, as I can't get why DatePicker does not work properly, while *date input* does.
I'm fine with *date input*, so why it does not work properly in Firefox?

**Comment by zslabs** [comment]
The one you're seeing in Chrome is the native browser datepicker, not UIkit's. I'd make sure you're loading the correct assets. I also wouldn't use `date` as the type for the datepicker. See [this discussion](https://github.com/uikit/uikit/issues/1006) on why.

**Comment by malles** [comment]
You're nesting a `form` in a `form`, that's never a good idea.. Are you sure you loaded all js and css correctly?

**Comment by ItachiSan** [comment]
Somehow solved, I had to clean up cache (Both of Firefox and Chromium), update UIKit, rewrite all the "imports" and it worked.
DatePicker works in Firefox.
![cattura di schermata 30](https://cloud.githubusercontent.com/assets/1223421/6351170/8fd07c6a-bc39-11e4-99e2-ecb002e28143.png)
Also, seems that setting the input as *text* type works fine, while using *date* shows in Chrome/ium the built-in date picker (as pointed by) by @zslabs.

As a tip, you could put a warning in doc to not use *date* as input while using DatePicker :)
