### ISSUE TITLE
Disable scrolling possibility when modal window open?

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1011]
I have long website (they have a scroll):
- when I open modal window, I can scroll the site in the background (using mouse wheel)
- when I open lightbox, I can't scroll the site in the background

Open the modal ( http://getuikit.com/docs/modal.html ) and the lightbox ( http://getuikit.com/docs/lightbox.html ) to see the difference

It should not work on the same rule (disable scroll  possibility by mouse wheel when the modal is open - as well as the lightbox component now) ?

**Comment by luetn** [comment]
Did you refresh (new version 2.17.0, same html page)
I think that issue is fixed! => ?

**Comment by PixelT** [comment]
@luetn I don't think... go to http://getuikit.com/docs/modal.html , open some modal and try to scroll - they still can scroll the background

**Comment by luetn** [comment]
@PixelT In my environment - no scrolling:
- OsX Firefox
- OsX Chrome
- Win7 IE9
- Win7 Firefox

**Comment by PixelT** [comment]
@luetn - I tested it now on Win8 - they doesn't work only on Chrome / Opera (I think this problem is only in webkit browsers), on FF & IE it's OK.

**Comment by PixelT** [comment]
Update:
On android default browser this also occurs (on android google chrome is OK)

**Comment by florianletsch** [comment]
I see the following behaviour: 

- Background doesn't scroll on Desktop devices. (Mac OS, Chrome + FF)
- Background scrolls on touch devices. (iOS8 Safari) 

Anyone's got an idea where to start looking into this issue?

The following lines in `modal.less` should prevent scrolling. Somehow this doesn't work on iOS.

```css
.uk-modal-page,
.uk-modal-page body { overflow: hidden; }
```

**Comment by zslabs** [comment]
I'm actually testing out the following to see if it helps:

    .hook-modal-misc() {

    	.uk-modal-page body {
    		position: fixed;
    		top: 0;
    		left: 0;
    		right: 0;
    		bottom: 0;
    		height: 100%;
    		width: 100%;
    	}
    }

**Comment by latestpost** [comment]
if (state.visibility === true) {
                document.body.classList.add('modalScrollLock');
                document.body.style.top = this.scrollTop + 'px';
                this.oldTop = this.scrollTop * -1;
            }

            if (state.visibility === false) {
                document.body.classList.remove('modalScrollLock');

                if (this.oldTop) {
                    document.body.scrollTop = this.oldTop;
                }
            }

**Comment by latestpost** [comment]
.modalScrollLock {
    overflow:hidden;
    position:fixed; 
}

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
