### ISSUE TITLE
Define horizontal / vertical gutter in dynamic grid

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1012]
Now when I define the gutter:
```
data-uk-grid="{gutter: 5}"
```
I create a grid width this same padding value in horizontal and vertical side between each container.
I suggest to add possibility to defined individually / different vertical and horizontal gutter in the dynamic grid, e.g:
```
data-uk-grid="{gutter: 5 15}"
```
I think this option increases the ability to create custom grid, and allows to create a different grid by easy & fast way.

**Comment by aheinze** [comment]
implemented here: https://github.com/uikit/uikit/commit/dfe8f581e49f2b3f06177da3871fc5dcc6de8bdb

**Comment by PixelT** [comment]
Seems doesn't work at this moment....
