### ISSUE TITLE
Modal Problem

### ISSUE THREAD

**Issue by ek378996** [uikit/uikit#1013]
I'm using yootheme Stage and when the modal opens, it pulls the modal all the way to the top of the page and pushes the menu to the right about 10 pixels. I've tried to find the error but can't. 

The modal will not open directly over where it is clicked like in the demo.

**Comment by gregbtm** [comment]
Care to share a live link? I'll try and debug for you.

**Comment by ek378996** [comment]
http//:inventusnetmarketing.com.

I'm trying to mock the front page of getuikit in order to see how this thing works and then change it to fit my design. Any help would be appreciated.

**Comment by saschadube** [comment]
Please try to ask for help in the [UIkit Google+ community](https://plus.google.com/communities/114238665434626719878)
