### ISSUE TITLE
Slideshow Not appearing

### ISSUE THREAD

**Issue by lmrex** [uikit/uikit#1014]
Hello,

Im not sure what im doing wrong but the uikit slideshow in not appearing:

The only time i was able tho show something was with the markup with background but i really do not ant them.

Can someone please help?

http://www.dreambookspro.pt/responsive/slideshow

<div data-uk-slideshow>
<ul class="uk-slideshow">
        <li class="uk-active"><img title="" alt="book &amp; box" src="http://www.dreambookspro.pt/images/slider_home/4.jpg"></li>
        <li><img title="" alt="book &amp; box" src="http://www.dreambookspro.pt/images/slider_home/3.jpg"></li>
    </ul>
    <a href="" data-uk-slideshow-item="previous"></a>
    <a href="" data-uk-slideshow-item="next"></a>
</div>

**Comment by vuchl** [comment]
So just to make sure everything is working do the following:
- Make sure jQuery is loaded before `js/uikit.js`
- add the stylesheets `js/uikit.css` and `css/components/slideshow.css`
- add the JavaScript files for the component too: `js/component/stylesheet.js`

**Comment by jjaylad** [comment]
I'm having the same issue. I've tried linking to a local download of jQuery, putting script prior to body tag, etc., but uikit slideshow just won't work. Any ideas? link to code. https://www.dropbox.com/sh/tvozfdtig5hgvw7/AADzYKAwmS3QVfIEGOGXiSAxa?dl=0

**Comment by jjaylad** [comment]
see screenshot also, file referenced is called slideshowtext2july2510pm.html ... thanks for any feedback

https://www.dropbox.com/s/hwb60rn77ys83s3/Screenshot%202015-07-26%2000.33.40.png?dl=0

**Comment by malles** [comment]
http://www.pastekit.com/j2KBzz
Here is your exact html-code, with only the links to js and css replaced with those from the cdn. The slideshow works fine there. 
It must be in the including of your local files. Open the browser console (F12) and check for loading errors.﻿
