### ISSUE TITLE
Feature request: An optional class for fullscreen modal

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1015]
trying to recreate http://tympanus.net/codrops/2014/07/30/fullscreen-form-interface/ , realized something like .uk-modal-dialog-fullscreen would be helpfull in future

**Comment by mktcode** [comment]
:+1: Why is this closed? Can't find this feature.

**Comment by windvlaag** [comment]
Would love to see this feature, have it on several sites hacked in, native
support  from uikit would be real nice.

>
