### ISSUE TITLE
Color classes for modal header/footer

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1016]
I'd like to be able to apply color classes (`primary`, `success`, `warning` and `danger`) to modal header/footer or entire container.
Something like `uk-modal-dialog-primary`, `uk-modal-header-success` and `uk-modal-footer-warning`.

**Comment by zslabs** [comment]
You should be able to just fine without additions -- just add the `uk-text-primary` class (for example) to the content within the header/footer.

**Comment by robertotremonti** [comment]
I'm talking about backgrounds and borders, sorry.
Text color is not enough.

**Comment by zslabs** [comment]
Background classes have been proposed for 3.0 https://github.com/uikit/uikit/issues/560

**Comment by robertotremonti** [comment]
Oh, thank you.
