### ISSUE TITLE
uikit autocomplete custom template in twig

### ISSUE THREAD

**Issue by arj-196** [uikit/uikit#1017]
I am working on Symfony. I read the documentation for the UIkit autocompleter at [documentation Autocomplete Custom Template][1]

And the syntax for custom templating that is provided in the example is:

     <div class="uk-autocomplete uk-form" data-uk-autocomplete="{source:'my-autocomplete.json'}">
        <input type="text">
        <script type="text/autocomplete">
            <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
                {{~items}}
                <li data-value="{{ $item.value }}">
                    <a>
                        {{ $item.title }}
                        <div>{{{ $item.text }}}</div>
                    </a>
                </li>
                {{/items}}
            </ul>
        </script>
    </div>

But the problem i am facing is that, i am **using TWIG** for templating, and in twig curly brackets '**{{ }}**' are for calling twig functionalities. Thus when i use the code for the Custom templating, i get **Compilation Errors**.

I tried putting the code for custom templating in a javascript file, and 'importing' the script right after the form but it didnt work ex:

**Javascript file: header_autocomplete.js**

    <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
        {{~items}}
        <li data-value="{{ $item.value }}">
            <a>
                {{ $item.title }}
                <div>{{{ $item.text }}}</div>
            </a>
        </li>
        {{/items}}
    </ul>

And i imported the script in the twig template as follows:

**html.twig file: index.html.twig**

    <div class="uk-form uk-autocomplete" data-uk-autocomplete="{source:'tmp/header_autocomplete.json'}" id="form-search"> 
        <input class="uk-form-width-large" type="text" placeholder="Search">
        <script type="text/autocomplete" src="header_autocomplete.js"></script>
        <button class="uk-button"><i class="uk-icon-search"></i></button>
    </div> 

But this didnt seem to work, i just get an empty dropdown menu for results.

Appreciate any help. 

  [1]: http://getuikit.com/docs/autocomplete.html

**Comment by vuchl** [comment]
@aheinze There should be an option for the (https://github.com/uikit/uikit/blob/e38cfbbb12287c7db18c6f87149636fd142580e1/src/js/core/core.js#L281)[`UI.Utils.template`] function to set a different enclosing tags

maybe extend the function to look like 
```javascript
UI.Utils.template = function(str, data, useSquareBrackets)
    ...
    ...
```

and then match against [[[, ]]], [[ and ]]? Unfortunately I can not provide a PR. Too dumb to make it look good.

**Comment by malles** [comment]
If you're calling the template function manually from a script, you could replace brackets to curly's before you put the string in. In this case the option would have to be brought back to the autocomplete options. 
I was looking at https://github.com/uikit/uikit/blob/master/src/js/core/core.js#L283 as well, and I was wondering why the `{{{...}}}` are valid and used, but act the same. In the example above and in docs only `{{{ $item.text }}}` has three curlys. Any reason for that?

**Comment by malles** [comment]
Nevermind, I read the code a bit more carefully. `{{{varname}}}` == `{{!varname}}`, not escaped.

**Comment by arj-196** [comment]
ah, i didnt know that. but then again still doesnt solve my problem

**Comment by arj-196** [comment]
@malles are you saying that i edit the replace code? ex, i edit : 
         var tokens = str.replace(/\n/g, '\\n').replace(/\{\{\{\s*(.+?)\s*\}\}\}/g, "{{!$1}}").split(/(\{\{\s*(.+?)\s*\}\})/g),
 
But will that affect anything else ?

**Comment by arj-196** [comment]
@vuchl i really hope there already exists a manner of changing. All i need is to use any other kind of brackets, Only the curly brackets are Specific to Twig. If i could replace it by '()' or '[]' or ';;'. Anything.

**Comment by malles** [comment]
You could change that line to ` var tokens = str.replace(/\n/g, '\\n').replace(/\[\[\s*(.+?)\s*\]\]/g, "{{$1}}").replace(/\{\{\{\s*(.+?)\s*\}\}\}/g, "{{!$1}}").split(/(\{\{\s*(.+?)\s*\}\})/g)`, wich I think could work for you. It's just a bit of a nasty way to go about it.
Or you could change it in https://github.com/uikit/uikit/blob/master/src/js/components/autocomplete.js#L76, where that function is called. `this.template = UI.Utils.template((this.template || this.options.template).replace(/\[\[\s*(.+?)\s*\]\]/g, "{{$1}}"));`
@vuchl It would be nice to have it as an option, but I guess it would have to be globally set, like the prefix. I think quite a big change if done properly.

**Comment by malles** [comment]
One way you could work around all this, is to put the template in via the `options` of the autocomplete component.
If you don't provide a template override in `script` tags, the template is picked from the options. So if you set the template option [(like so)](http://getuikit.com/docs/documentation_javascript.html#js-override), you wouldn't have your `{{...}}` in the markup.

**Comment by vuchl** [comment]
@malles Still if you override the template it won't be parsed by the `UI.Utils.template` since the pattern matching is against {{.}},{{{ and }}}. the idea for a global enclosing/escaping tag isn't that bad though. Allthough I am not aware where this function is used.

**Comment by malles** [comment]
No, but you can create your own template, and pass it in UIkit via strings, so TWIG won't pick it up.

**Comment by vuchl** [comment]
Ah, after thinking about it it makes sense since the JavaScript files are not parsed by twig. So yeah that is a working solution.

**Comment by hanlan** [comment]
just add "template" option
```
var AC = UIkit.autocomplete($("#searchwrap"), {
  source: result,
  minLength:1,
  template: '<ul class="@-nav @-nav-autocomplete @-autocomplete-results">{{~items}}<li data-value="{{$item.value}}"  data-id="{{$item.id}}"><a>{{$item.value}}</a></li>{{/items}}</ul>'
});
```

**Comment by malles** [comment]
@hanlan The `@-` is deprecated from 2.17

**Comment by hanlan** [comment]
@malles what? ok.... thanks for the info, but I will never spend any extra time on the new 2.1.7 for now. you guys already have a solution for this issue?

**Comment by malles** [comment]
I guess this issue is kinda solved...

**Comment by saschadube** [comment]
So it is solved?
