### ISSUE TITLE
uk-nestable on chrome windows 8 64

### ISSUE THREAD

**Issue by eduardasm** [uikit/uikit#1018]
Hello,
it is strange, but I see, that nestable component is not working using mouse on Chrome browser when touch screen device is enabled. I am using Windows 8 64bit and Chrome 40.0.2214.115 version.
When I disable HID-copmpliant touch screen from Device manager, everything works fine, but when it is enabled, trying to drag nestable element just selects the element, but not drags.

**Comment by Namek** [comment]
I can confirm that. Got Windows 10 64b, Chrome "Version 45.0.2454.101 m" and ThinkPad T440p. When I use laptop's touchpad the text is being selected, drag&drop is not working at all.

Not sure if that helps but on my laptop `navigator.maxTouchPoints` = 2. Although it doesn't have touch screen, just multi touch on touchpad.

**Comment by GlennNZ** [comment]
This may be useful info; I noticed that when viewing http://getuikit.com/docs/nestable.html in Chrome using the 'mobile' view in developer tools, none of the dragging functionality works (Windows, Chrome 43.0.2357.134 m). I'm trying to solve related dragging issues on a Galaxy S4 using Chrome (fine on iOS)

**Comment by aheinze** [comment]
closed because duplicate issue: https://github.com/uikit/uikit/issues/1105
