### ISSUE TITLE
Move from Gitter to Slack

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1019]
As dev chat, Gitter is really limited and desktop app doesn't work very well.
I suggest to move to Slack that offers various improvements and is really well supported.

www.slack.com

**Comment by robertotremonti** [comment]
For not working well I mean that Gitter notifications are not reliable, new messages are often not highlitghted, when app is hidden it seems to go "offline" (no refresh, no notifications), it frequently reloads, no direct messages and powerful search.

**Comment by saschadube** [comment]
How can people easily join a Slack chat without being invited?

**Comment by zslabs** [comment]
@robertotremonti You can have one-off conversations with people in Gitter.

**Comment by robertotremonti** [comment]
@saschadube Honestly I don't know.
@zslabs Ok.

**Comment by alexadark** [comment]
i am on several gist channels, and i don't pay anything...
Also i have found uikit play but i tried to register, and after registering i have a message in german that i don't understand...
