### ISSUE TITLE
Custom core in theme

### ISSUE THREAD

**Issue by Grigory90** [uikit/uikit#1020]
### Hello everyone!
Do a custom theme **gulp -t my-theme-name**, but in a manner going all the elements of the kernel. And how to collect, for example, only a **button.less**, **form.less** and **offcanvas.less**?
> P.S. Thanks in advance!

**Comment by aheinze** [comment]
you have to create a custom theme (http://getuikit.com/docs/documentation_create-a-theme.html) and just and include the components you like
