### ISSUE TITLE
Trigger scrollToElement() manually?

### ISSUE THREAD

**Issue by jjmpsp** [uikit/uikit#1021]
As per the source code of:

https://github.com/uikit/uikit/blob/master/src/js/core/smooth-scroll.js

Is it possible to use the scrollToElement() function without binding to an actual link on the page? E.g. I'd like to scroll to a certain element within the DOM after an event has completed from another callback.

I've looked at the source code for the function, but can't see to figure out the correct syntax...

UIkit.smoothScroll.scrollToElement() is undefined?

Can anyone help?

Thanks

**Comment by malles** [comment]
The function `scrollToElement ` on [line 33](https://github.com/uikit/uikit/blob/master/src/js/core/smooth-scroll.js#L33) is indeed the one you're trying to call.
As it is within the closure of the files' "iife", you cannot call it directly. A so called protected function in javascript.
For our convinience the function is bound to an accessible variable [on line 55](https://github.com/uikit/uikit/blob/master/src/js/core/smooth-scroll.js#L55).
`UIkit.Utils.scrollToElement(UIkit.$('#go-to-this-div'));` should do the trick.

**Comment by jjmpsp** [comment]
@malles Aha! That makes sense. Thank you so much :+1:

**Comment by toobbi** [comment]
@jjmpsp How about a hint in the official documentation, that the "smooth scroll" animation can be triggered manually?  (See #2020)
