### ISSUE TITLE
Proposal for columns max width classes or data attributes

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1023]
When displayed in large grids, columns always respect what specified in `uk-width-medium-*` and `uk-width-large-*` classes.

`uk-width-medium-max-*` and `uk-width-large-max-*` classes or data attributes (`data-uk-width-medium-max="250"`) should be introduced to specify the max width of a column beyond which a new column is created.

Useful when working with images (like panel teasers or thumbnails) to avoid stretched images and other too large elements.

**Comment by aheinze** [comment]
we would suggest to use a custom class in this case
