### ISSUE TITLE
Button: Padding instead of line-height for top/bottom

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1025]
I'd much rather prefer a button's top/bottom padding to be set than by line-height. If your text wraps to two lines... it's pretty darn ugly.

**Comment by mcraiganthony** [comment]
Using line-height and min-height to set the heights of buttons is problematic. As @zslabs mentioned, if text wraps within a button you are screwed.

With unitless line-height and top/bottom padding, buttons will be significantly more flexible. This allows the button heights to fall where they may ... based on font and font-size.

Below is a comparison between Bootstrap and UIKit. Stylistic differences aside, you can see that the stacked text inside of the Bootstrap button is more presentable.

![btns](https://cloud.githubusercontent.com/assets/1093578/6416540/ddd75d4c-be74-11e4-837e-c18f4d8ac3be.png)

Thanks!

**Comment by zslabs** [comment]
Good point @mcraiganthony 

I think this also brings us back to the point of https://github.com/uikit/uikit/issues/461

We should have a consistent line-height throughout the system.

**Comment by malles** [comment]
+1

**Comment by mcraiganthony** [comment]
"Unitless line heights are recommended due to the fact that child elements will inherit the raw number value, rather than the computed value. With this, child elements can compute their line heights based on their computed font size, rather than inheriting an arbitrary value from a parent that is more likely to need overriding."

https://css-tricks.com/almanac/properties/l/line-height/

**Comment by PixelT** [comment]
+1

**Comment by MacWordPress** [comment]
+1

**Comment by zslabs** [comment]
This something I can jumpo on to get it knocked out?

**Comment by saschadube** [comment]
We will do that for UIkit 3. But I don't think we can introduce it for UIkit 2 because it would break existing themes and it would take a lot of work to fix it. Please put it on the [UIki 3 feature list](https://github.com/uikit/uikit/issues/560).

**Comment by heyfellows** [comment]
Hi, The issue is still there almost 10 years after this issue was reported.
Can you please plan to fix it with UIkit 4?
