### ISSUE TITLE
Using JQuery to change slideshow content

### ISSUE THREAD

**Issue by arj-196** [uikit/uikit#1028]
I am using a simple slideshow ex:

	  <div class="uk-slidenav-position" data-uk-slideshow="  
	             {animation:'swipe',height:500}" id="pd_slideshow">
                        <ul class="uk-slideshow" > 
                            <li> <img src="bundles/app/img/1.jpg" /></li>
                            <li><img src="bundles/app/img/2.jpg" /></li>
                            <li><img src="bundles/app/img/3.jpg" /></li>
                        </ul>
                        <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-
                                    previous" data-uk-slideshow-item="previous"></a>
                        <a href="" class="uk-slidenav uk-slidenav-contrast 
			                        uk-slidenav-next" data-uk-slideshow-item="next"></a>
       </div>
I would like to know how to **change the slideshow content with jQuery**

I tried the following but i think the slideshow needs to be **re-initialized** every time the list contents are changed. I couldn't find the code to re-initializing in the documentation. 

I tried doing:

	ref = { gallery: '#pd_slideshow > ul'};
	function updateGallery(json){    
	    $(ref.gallery).empty();
	    var i;
	    for(i in json.images){
	        $(ref.gallery).append(
	            '<li><img src="'+ json.images[i].path +'" /></li>'
	        );
	    }    
	}

Appreciate any help!

**Comment by saschadube** [comment]
Maybe someone in the [UIkit Google+ community](https://plus.google.com/communities/114238665434626719878) can help you? Try to post custom issues which are not bugs there.
