### ISSUE TITLE
uk-scrollspy in group

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1029]
This code work OK:
```
<section class="uk-grid">
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box" data-uk-scrollspy="{cls:'uk-animation-fade', delay:0, repeat: true}">
        	sdasda
        </div>
    </div>
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box" data-uk-scrollspy="{cls:'uk-animation-fade', delay:500, repeat: true}">
        	sdasda
        </div>
    </div>
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box" data-uk-scrollspy="{cls:'uk-animation-fade', delay:1000, repeat: true}">
        	sdasda
        </div>
    </div>
</section>
```
but if I want put the animation in the groups ( http://getuikit.com/docs/scrollspy.html#groups ), the animation is break...
```
<section class="uk-grid" data-uk-scrollspy="{cls:'uk-animation-fade', target:'.uk-panel', delay:500, repeat: true}">
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box">
        	sdasda
        </div>
    </div>
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box">
        	sdasda
        </div>
    </div>
    <div class="uk-width-1-3">
        <div class="uk-panel uk-panel-box">
        	sdasda
        </div>
    </div>
</section>
```

**Comment by malles** [comment]
It's a bit tricky, because the example code on the docs page does not resemble the example shown.
Since you're `.uk-panel` is nested in a div, the target would have to be `> div > .uk-panel`.
![screenshot_38](https://cloud.githubusercontent.com/assets/5442402/6426790/956b7c44-bf6b-11e4-9269-50cdeb732a53.png)

As shown on the screenshot, the example is not the same as the actual code. That happens more on the docs, and I can understand the confusement.

**Comment by PixelT** [comment]
I watched in the source. I tried also usage the code from docs...
I don't know which classes should be add in the code, or which are added dynamically in the background - I think the docs is incomplete in this case or this is a bug (but on the page the demo work ok)....

**Comment by franziskaschulz** [comment]
It's understandable that without reading the instructions, the code examples might feel misleading. But we always make a point of keeping them as simple as possible, only showing the actual component without the additions we use for better visualization and trust on our instructions to explain the rest. I've updated the instruction text, so it is now clearer on what you need to target.
