### ISSUE TITLE
Overflow content in uk-height-viewport

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1032]
I have much content inside e.g. 3 columns panels in container which has class .uk-height-viewport.
In big resolutions, all content display OK
In small resolution (e.g. on phone or tablet), especially when the panels go into 1 columns, they extend beyond the container.... (the total height of the content > height of container with .uk-height-viewport...)

Current solution isn't fluid / flexible
I think the .uk-height-viewport class properties should look like this:
```
.uk-height-viewport {
min-height: 100vh;
height: auto;
}
```
instead of:
```
.uk-height-viewport {
height:100vh;
min-height:600px
}
```
Update: The solution above works fine, but in IE breaks layout when we use flexbox (uk-flex-middle)
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

But the problem in topic (overflow content) it still exist :P

**Comment by saschadube** [comment]
Yes, that's why we have a min-height set. There is currently no solution because if IE11/10. Maybe use a custom class.
