### ISSUE TITLE
How to customize Animation in sticky ?

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1035]
Hi Please tell me how can i Customize sticky Animation ?
for in and out animation like speed and other options

thx

**Comment by PixelT** [comment]
```
<div data-uk-sticky="{animation: 'uk-animation-slide-top'}">...</div>
```
First method:
in animation parameter you put animation class from http://getuikit.com/docs/animation.html

Second method:
In animation parameter you put your own class name, and define the options of the animation itself inside your CSS

The second method is just my theory, I haven't tested this (if anyone knows about this method, let me correct :))

**Comment by aheinze** [comment]
as @PixelT you can use any uk-animation-* class. just override animation-duration for your sticky in your css fo custom speed
