### ISSUE TITLE
Problem with upload component for Version 2.17.0

### ISSUE THREAD

**Issue by Kasendwa** [uikit/uikit#1036]
I got a copy of v2.17.0 from the website. But ran into a couple of challenges with the upload component. First of all, the minified version (upload.min.js) is way hard to debug, so I moved on to the production version (upload.js). Note: Both files refused to work for me.

After a couple of hours of troubleshooting, Firefug pointed me to Line 96 with

<code>UI.$.event.props.push("dataTransfer");</code>

and next was line 105 with 

<code>settings = UI.$.extend({}, xhrupload.defaults, settings);</code>

I changed both those lines and removed the UI at the end and remained with 

<code>$.event.props.push("dataTransfer");</code>

<code>settings = $.extend({}, xhrupload.defaults, settings);</code>

That worked like charm.

**Comment by malles** [comment]
I'm using 2.17.0 with the uploader, no problems like that for me at all. Is your main uikit.js up-to-date?

**Comment by Kasendwa** [comment]
Very embarassing! It wasn't. Now things are great.
