### ISSUE TITLE
Separate grid/widths as different components

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1037]
Since flexbox is becoming more of a standard in the framework, it'd be nice for those not even using the grid system (and relying solely on flexbox) to be able to only include the widths of UIkit as they see fit and not the extra grid stuff. Other than an extra import, this would allow for better customization of the platform. 

Another item to think about is if you really don't need the medium or large grid widths -- being able to selectively remove those from what's passed down. The use-case here would be a mobile app or site that doesn't have additional breakpoints higher than what is assumed with UIkit. Thanks!

**Comment by saschadube** [comment]
Yes, good idea! Like I wrote [https://github.com/uikit/uikit/issues/1139#issuecomment-92336163](here) we are thinking of a gutter, width and flex component to replace the grid.
