### ISSUE TITLE
Dropdown "justify" options incompatible with "uk-push-*" and "uk-pull-*" classes.

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1039]
When `data-uk-dropdown="{justify:'#container'}"` is used inside a grid that uses `uk-push-*` and `uk-pull-*` classes, options list is not aligned with the dropdown but shown at far left of the page.

**Comment by saschadube** [comment]
Please provide a [JSFiddle](https://jsfiddle.net/)
