### ISSUE TITLE
Scrollspy in IE9 - the elements are not displayed at all

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1040]
The scrollspy component using CSS animations which isn't support in IE9
At this moment, when we use scrollspy, in IE9 the **elements doesn't display at all** ( e.g. when we put scrollspy to grid, we have see blank page! )

I think, the fix for this case is delete the data-uk-scrollspy attribute in IE9:
```
    if(document.all && document.addEventListener && !window.atob) {
        $('*').removeAttr('data-uk-scrollspy');
    }
```

Example - you don't need to look far: open this url in IE9: http://getuikit.com/docs/scrollspy.html :)

**Comment by aheinze** [comment]
yes, the scrollspy toggles animation classes in the , which use css animations which aren't supported by IE9. so if you want to support IE9, don't use scrollspy in combination with css animation based classes. scrollspy itself works without any problems wit IE9. 

Alternative fix for IE9:

```html
<!--[if IE 9]>

<style>
    [data-uk-scrollspy*='uk-animation-'] { opacity: 1 !important; }
</style>

<![endif]-->
```

**Comment by MartiranS** [comment]
Hello, I have same problem in IE 9, 10, 11 and Edge.
I use: 
`data-uk-scrollspy="{cls:'uk-animation-fade', repeat: true, delay:300}"`
And the content is hidden in IE and Edge

I tried to fix this

```
<!--[if gte IE 9]>
<style>
    [data-uk-scrollspy*='uk-animation-'] { opacity: 1 !important; }
</style>
<![endif]-->
```
But it does not working
My site with problem: [http://hra.kctricany.cz/](http://hra.kctricany.cz/)
