### ISSUE TITLE
Terms / taxonomy

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1041]
From the changelog of 2.17.0:
```Added thumbnav component```
Checking the Components, I didn't find this. It appears to be in the Core, not Components.

Could you please make a definition of terms and use that in the documentation and in the folder structure consistently? What now is called Components in the menu used to be called Add-ons. That was clear. But the folders for JS files were called core and components. And the core CSS was not in core but in a root folder.

Maybe a section on **each** Core Components and Add-on Components page to let the user know which JS and CSS to include? This is not always clear. All Core Components use uikit.js / uikit.min.js, but Form Advanced - is that formadvanced.js or form-advanced.js?

**Comment by PixelT** [comment]
http://getuikit.com/docs/thumbnav.html

**Comment by jerry1970** [comment]
I found the documentation, that was not the problem. The problem was that the changelog says it's a component, so I looked under Components. I have that problem many times, so my request is to make a better and consistent difference between Core Components (sometimes called Core, sometimes Components) and Add-on Components (used to be called Add-ons, now also called Components).

**Comment by adaniello** [comment]
I agree too

**Comment by PixelT** [comment]
@jerry1970 I understand. IMO the naming Core / Components are better than old Components / Add-ons. But about changelog you're right - it can be confusing...

**Comment by jerry1970** [comment]
I could live with Core and Components, but then the changelog, the documentation, the javascript folder names and the css folder names should be named accordingly.

And I still think it's a good idea to give the full proper name of the JS and CSS files on the documentation pages of all the Components.

**Comment by PixelT** [comment]
Yes, I partly agree with you, that the documentation should show the filename, but the other side the name of the files are this same as component name, so it's easy to choose which file(s) (by name) should be included ( it's very logic :))
I always be confused, when I must include some component - that they have only CSS file to include, only JS or both.... (Such information would also handy)

As for me - the documentation missing information about a version of UIkit, in which the current component was added ( I already suggest this case here: https://github.com/uikit/uikit/issues/669 )

**Comment by jerry1970** [comment]
If the names would be completely logical you're right, but like I said in my original post, the add-on component Form Advanced could be formadvanced.js, form-advanced.js, uikit.formadvanced.js, uikit.form-advanced.js, formadvanced.uikit.js, or form-advanced.uikit.js (plus the minified versions). So it's not completely clear.

**Comment by malles** [comment]
I agree on this, but @jerry1970 how would you call a single core piece of code without calling it a component? Throughout the docs there those pieces of code are called components, and that seems ok to me. Eg the [panel page](http://getuikit.com/docs/panel.html) refers to the Grid component and Badge component, which are both cores.
In a way I think add-on was more distinctive to separate 'core components' and 'add-on components'. Maybe it would be best to consistently refer to core components as "core component".

**Comment by jerry1970** [comment]
I completely agree, @malles - they're all components. I don't care *how* the distinction is made, so long as there *is* a proper and consistent distinction in the changelog, documentation, and folder structure.

Core Components and Add-on Components are the clearest names for this. So the documentation menu bar should have "Core" and "Add-on", the changelog and documentation should speak of core components and add-on components, and the folder structure for JS and CSS should have folders "core" and "addon". That would be consistent. But like I said, I don't care how, as long as it is consistent.

**Comment by MacWordPress** [comment]
+1

**Comment by saschadube** [comment]
We will try to be more clear next time.
