### ISSUE TITLE
Autoplay in slideshow

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1043]
Autoplay stops when user change the slide manually ( using arrows )
This is intended effect or it's a bug?

**Comment by jerry1970** [comment]
I would prefer that to be the default behaviour. I've never seen it act differently anywhere so I assume it's intended behaviour.

**Comment by malles** [comment]
It's intended: https://github.com/uikit/uikit/blob/master/src/js/components/slideshow.js#L160
And as @jerry1970 said, default behaviour on most slideshows. I wouldn't want an autoplay interfering with me clicking the arrows...

**Comment by PixelT** [comment]
OK, thanks guys :)

**Comment by miladmeidanshahi** [comment]
many thanks malles my problem solved.
