### ISSUE TITLE
Ugly loading slideshow component

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1045]
I have the impression that the slider component is loading in 2 stages
In first stage (after open site) slider display a small piece of slide (20-30 px height)
After a few seconds (2-3) the slider loading properly
Between 1 and 2 steps, you can be seen an ugly 'jump' effect...

Preview: http://i.imgur.com/ndPFxEp.png
Demo: http://getuikit.com/docs/slideshow.html

**Comment by malles** [comment]
+1
I think this is directly related to #1027

**Comment by aheinze** [comment]
this should be fixed with the upcoming release

**Comment by PixelT** [comment]
@aheinze - this issue is still exist :(

**Comment by PixelT** [comment]
@up...
The slideshow component is useless at the moment....
