### ISSUE TITLE
Slideshow Placeholder or loading animation for large image slideshow

### ISSUE THREAD

**Issue by mardaw** [uikit/uikit#1046]
Is there a way to add an image loading animation or place holder to the slideshow instead of the content jumping around on load? I've tried everything! Thanks!

**Comment by aheinze** [comment]
the jumping issue should be fixed in the upcoming UIkit release

**Comment by mardaw** [comment]
Thanks for the reply Artur. I made the Gplus post hoping someone may have
already addressed it with a javascript loading animation. Hope I didn't
make you mad because I really like your work and it has been easier as I
get more familiar with it.

Thank you for the awesome stuff!

Marty

On Fri, Apr 17, 2015 at 4:14 AM, Artur <notifications@github.com> wrote:

> Closed #1046 <https://github.com/uikit/uikit/issues/1046>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uikit/uikit/issues/1046#event-283729751>.
>



-- 
Marty DeMichele
mdemichele@gmail.com
