### ISSUE TITLE
SCSS Sample Themes / Problem Converting

### ISSUE THREAD

**Issue by christianmagill** [uikit/uikit#1047]
Hi guys,

I'm having some trouble converting the sample themes to Sass.

I was able to convert the default theme with less2sass and all works well.

Unfortunately, when I try and convert the almost-flat theme, I get unbound variable errors, the first being $panel-box-primary-color on line 41 of panel.scss

I am compiling with the latest gulp-sass and importing files as described here: http://getuikit.com/docs/documentation_less-sass.html 

Any suggestions?

Does anyone have any more advanced SCSS themes I could take a look at. Thanks.

**Comment by christianmagill** [comment]
I managed to solve the issue by also including "uikit-variables.scss" before my customizations

**Comment by christianmagill** [comment]
I also ran into a small issue beyond this that caused a hiccup.

https://github.com/uikit/uikit/blob/master/themes/gradient/comment.less
https://github.com/uikit/uikit/blob/master/themes/almost-flat/comment.less

Both of these files use the variable "@comment-primary-color" before it is assigned. This causes issues in Sass. Altering the line order solved the problem.

**Comment by jerry1970** [comment]
Providing both Less and Sass would be wonderful...

**Comment by ApfelUser** [comment]
:+1: for SASS/SCSS

**Comment by christianmagill** [comment]
After playing with the themes in both sass and less it seems there are some big limitations in sass.

Mainly these have to do with variable scoping.

Less' variable scope is fairly loose, which allows it to use variables before they are created. As such if I'm creating a theme I can use variables from the core and components of uikit. In sass however I can only use the variables from my theme itself. 

I'm not sure how best to solve this problem other than separating/duplicating the core/componented variable declarations into separate files that could be imported before the custom theme

**Comment by jerry1970** [comment]
I don't follow you completely, but I can't imagine sass doesn't have an import like you need without duplicating. But my IDE (NetBeans) deals with Less as well as Sass (change a file, save it, NetBeans runs the compiler right away), so I don't complain.

**Comment by saschadube** [comment]
Please take a look [http://getuikit.com/docs/documentation_less-sass.html](Embedding Sass in your project)

@christianmagill Yes, the current themes need to be updated so they can converted to Sass. But I think if you have a Sass project to start with your own custom theme anyway, right?
