### ISSUE TITLE
run js in autocomplete !

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1048]
hi how can in run js in autocomplete like this :

    <input type="text">
    <script type="text/autocomplete">
        <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
            {{~items}}
            <li data-value="{{ $item.value }}">
                <a>
                    {{ $item.title }}
// run some js code hear for example
                    <div>{{{ $item.text }}}</div>
                </a>
            </li>
            {{/items}}
        </ul>
    </script>

**Comment by malles** [comment]
The template engine allows some simple logic in the templates [source](https://github.com/uikit/uikit/blob/master/src/js/core/core.js#L281).
Basicly this is possible:

operator | function | example
------------ | -------------| -------------
 {{..}} | code separator |  Separates the template logic from the markup. You can display the value of a variable `{{varname}}` or use it for logic `{{^block}}{{/block}}`. Using spaces is optional, `{{ varname }}` works the same.
{{{..}}} | unescaped code separator | Use this when you want to display a variable that must not be escaped, eg html-markup `{{{myHtmlString}}}`.
/ | terminate |Terminates block opened before `{{^block}}<p>Some text</p>{{/block}}`
~ | forEach loop | Iterates over an array of items. `{{~items}}<li>{{ $item.value }}</i>{{/items}}`
~ | for..in loop | Iterates over an object of items. `{{:items}}<li>{{key}}: {{ $item.value }}</i>{{/items}}`
# | If condition | Checks for positive value `{{#value}}<span>It's {{value}}</span>{{/value}}` 
^ | If not condition | Checks for negative value `{{#value}}<span>It's empty</span>{{/value}}` 
! | Don't escape | Displayed value is not escaped. Same as `{{{ ... }}}`.  `{{!myHtmlString}}`

Make sure the data you put in matches the functions you use. Errors are displayed in the template until you get rid off them.
As an example a snippet where a list of files dat have an image/icon is displayed:
```
<h3>{{fileName}}</3>
{{#hasImage}}
	{{#isIcon}}
	<div class="uk-float-right uk-thumbnail">
		<img src="{{thumb.url}}" width="{{thumb.width}}" height="{{thumb.height}}" alt="{{fileName}}"/>
	</div>
	{{/isIcon}}
	{{#isThumb}}
	<a href="{{thumb.lbox}}" data-uk-lightbox="" class="uk-overlay">
		<img src="{{thumb.url}}" width="{{thumb.width}}" height="{{thumb.height}}" alt="{{fileName}}"/>
	
		<div class="uk-overlay-area"></div>
	</a>
	{{/isThumb}}
{{/hasImage}}
{{^hasImage}}
<i class="uk-icon-cloud-upload uk-icon-medium uk-text-muted"></i>
{{/hasImage}}
```
Example data:
```
{
	files : [{
			fileName: 'file.pdf'
			thumb : {
				url : 'thumb.jpg',
				width : 64,
				height : 64,
				lbox : 'image.jpg'
			},
			hasImage : true,
			isThumb : true,
			isIcon : false,
			}
	]
}
```

**Comment by miladmeidanshahi** [comment]
many thx malles but how can i add this code there ? 

        <script type="text/Javascripts">
            (function test($){
                $(window).load(function(){
                    $(".vir-list-scroll").mCustomScrollbar({theme:"dark-thin"});
                });
            })(jQuery);
        </script>

i want add this code to the results box  to change scroll bar

**Comment by miladmeidanshahi** [comment]
nobody cant help me ?
please someone show me the way

**Comment by miladmeidanshahi** [comment]
malles this line " Terminates block opened before {{^block}}<p>Some text</p>{{/block}} " does not work says block is  not defined !

how can i fix that ?

**Comment by malles** [comment]
As I said, only some simple logic is allowed. You can't put that code there. You'll have to use an event to attach that to.
The `{{#varname}}...{{\varname}}` blocks refer to vars in the data. See the example.

**Comment by miladmeidanshahi** [comment]
many thx malles  :+1: 

but someone show me how can i import that with data please tell me step by step many thx ; )

**Comment by malles** [comment]
Here are some examples for autocomplete: http://codepen.io/malles/pen/qEyEZr?editors=101
I added the click-listener. I think that is what you need.

**Comment by miladmeidanshahi** [comment]
nice example malles you are the best many thx i will test my solution and say th reasult
