### ISSUE TITLE
Flex conflicts with previous flex on an img 

### ISSUE THREAD

**Issue by qicongchen** [uikit/uikit#1049]
Hi I was trying to overlay an img with two links, one on right-top and one on center-middle. 

```
<li>
    <img src="../img/brew.jpg" width="" height="" alt="">
    <div class="uk-overlay-panel uk-flex uk-flex-top uk-flex-right">
        <div>
            <a href="http://google.com"><i class="uk-icon-medium uk-icon-cog uk-margin-left"></i></a>
            <a href="http://google.com"><i class="uk-icon-medium uk-icon-envelope-o uk-margin-left"></i></a>
        </div>
    </div>
    <div class="uk-overlay-panel uk-flex uk-flex-center uk-flex-middle">
        <div>
        <a class="uk-button uk-button-large uk-button-success uk-border-rounded" href="http://google.com"><i class="uk-icon-institution"></i> Start a class</a>
        </div>
    </div>
</li>
```
Although it displays properly, the links in the first uk-overlay-panel cannot be clicked. I check several times to find only those in the last uk-overlay-panel can still be clicked.

Are we  restricted to use only one flex on a img? And any other ways in uikit could realize my function?

Thank you so much!

**Comment by saschadube** [comment]
Please provide a [https://jsfiddle.net/](JSFiddle)
