### ISSUE TITLE
Feature request: split colours and elements

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1051]
While ```uk-text``` has ```uk-text-muted```, ```uk-text-primary```, ```uk-text-success```, ```uk-text-warning```, ```uk-text-danger```, and ```uk-text-contrast```, the ```uk-badge``` only has no modifier (which is the same as ```primary``` on other elements), ```uk-badge-succes```, ```uk-badge-warning```, and ```uk-badge-danger```. There is no ```uk-button-danger```.

This is not very consistent.

Isn't it more natural to split the elements and colours so we could have ```uk-text uk-color-danger```, ```uk-button uk-color-warning```, or ```uk-badge uk-color-muted``` as well?

I think this would mean less CSS, also easier to maintain, as well as easier to expand (I have added ```myown-color-black```, ```myown-color-grey```, ```myown-color-white```).

**Comment by saschadube** [comment]
I don't think it is a good idea to remove the color from the ```uk-badge``` rules. But I see what you mean. UIkit 3 will be more consistent.
