### ISSUE TITLE
Dropdown out of viewport

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1052]
Dropdown should detect the viewport edges and automatically add the appropriate class
For example below, they should add uk-dropdown-up class etc.
http://i.imgur.com/Ga7Blhm.png

**Comment by saschadube** [comment]
Mmh, it is a matter of taste. I like how it is now.

**Comment by UnrulyNatives** [comment]
I have run into issue with this. 
My dropdown is at the very bottom of my page - it makes the page to jump, when I open it.

**Comment by malles** [comment]
Well, you gotta scroll down before you drop down :)
