### ISSUE TITLE
Firefox Grid Problem

### ISSUE THREAD

**Issue by cartz** [uikit/uikit#1056]
Ahoi,
on older Versions of Firefox i get problems with the grid, as firefox is not detecting the edges of my viewport. for example if i have a row of five items which should be shown with 1-4 width (the line should collapse), it will get a scrollbar to the side...

nearly nothing, what should be responsive does work. (position of the menu too)

you can view my problem live @ www.schulcomputer.org/html/

**Comment by malles** [comment]
"Works fine on my machine"
Upgrade Firefox would be your best solution here.

**Comment by cartz** [comment]
This is not possible. As this site is used for work at school, I have to deal with the system I find over there. Updates are not in my reach and the person, who could care about does not. I know that the sites works well with newer Browsers (even IE), but at school I am stuck at Firefox 22 ;(

**Comment by malles** [comment]
Then I guess you can't create a responsive site for the school. Just fallback to the era the school is in, and use tables for your layout.

**Comment by zslabs** [comment]
@cartz http://caniuse.com/#feat=css3-boxsizing They're way behind the times unfortunately.

**Comment by malles** [comment]
@cartz Yeah, for the safety of the schools network, and the souls of the poor children, UPGRADE!
