### ISSUE TITLE
Make tabs stack on medium screens

### ISSUE THREAD

**Issue by duckboy1981** [uikit/uikit#1058]
With the tabs, currently they only stack on small screens.

In my case, on medium screens (such as Samsung tablets) some of the tabs are wrapping and it doesn't look good.  Is there a way to change behaviour so that tabs also stack on medium screens?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
