### ISSUE TITLE
Responsive tabs acting weird

### ISSUE THREAD

**Issue by stell** [uikit/uikit#1059]
Testing responsive UIkit tabs in joomla backend area of our compo resulting in strange behaviour:

![uikit](https://cloud.githubusercontent.com/assets/701298/6579954/c0ce9238-c74d-11e4-9ba8-0cd32ad2b04f.gif)

We are working with custom prefixed uikit.
```
<ul class="b01-tab cookietab" data-b01-switcher="{connect:'#display_config'}" data-b01-tab>
<li><a href="#">' . JText::_(strtoupper($title)) . '</a></li>
</ul>

<ul id="display_config" class="b01-switcher b01-margin">	
<li>
...
```

Added some cokkie setting to the tab:
```
var switcher = b01UIkit.switcher($('.cookietab'));﻿
switcher.show($('a[href="'+BOI.getCookie("activetab")+'"]').parent());			
$(".cookietab").on("change.uk.tab", function(event, area) {
BOI.setCookie("activetab", $(area).children(0).attr("href"), 7);
});
```

**Comment by florianletsch** [comment]
Did you ever manage to resolve this or at least narrow down the issue?

**Comment by florianletsch** [comment]
And please provide a JSfiddle or Codepend with the issue. Seems to be related to combining tabs and dropdown?

**Comment by pavlosadovyi** [comment]
Same problem here
