### ISSUE TITLE
Lightbox fails to play embedded video in iPhone portrait mode

### ISSUE THREAD

**Issue by travelfilmproductions** [uikit/uikit#1060]
Steps to reproduce:
1. On an iphone 5 or 6+ (those are the two I tested it on) in portrait, visit [http://getuikit.com/docs/lightbox.html](http://getuikit.com/docs/lightbox.html)
2.  Click the Youtube, Vimeo or MP4 buttons to load up a lightbox.
3.  Attempt to play the video.

Should close the lightbox instead, but the video DOES work in landscape mode.

**Comment by spotd** [comment]
I see have posted the same issue recently, this not fixed yet?!

**Comment by messagedj** [comment]
why no fixes?

**Comment by spotd** [comment]
I found a work around, just use the large modal window as a lightbox with the Vimeo embed, this doesn't have the problem.

**Comment by messagedj** [comment]
thnx, i just think it should be fixed, ;) but thanks for the workaround.

**Comment by messagedj** [comment]
it is getting frustrating guys!  your and my clients are waining for answers!

**Comment by spotd** [comment]
I agree. I like uikit for a lot of reasons, but this is an often used feature for playing video. It really needs to be addressed, as iOS is a big percentage. A response would also be useful.

**Comment by messagedj** [comment]
Mark, of you update to the latest widgetkit or update uikit to the latest version it is fixed

**Comment by spotd** [comment]
Great! i can confirm it now works. Thanks
