### ISSUE TITLE
Request: add "js" body class if JavaScript is available

### ISSUE THREAD

**Issue by rolandtoth** [uikit/uikit#1061]
Since uikit adds "no-touch" class to body already, it would be handy if it would add "js" class if JavaScript is available. This would help writing selectors like "body.js .myClass" in CSS.

Possible implementation (borrowed from the Nette PHP framework):
```html
<script>document.documentElement.className+=' js'</script>
```

**Comment by zslabs** [comment]
Along the same lines of what Modernizr does.

**Comment by PixelT** [comment]
A small thing, but it can be very useful
+1

**Comment by vuchl** [comment]
+1

**Comment by aheinze** [comment]
UIkit just adds classes which are needed by UIkit itself. to have a an extended support class list. I would recommend to use modernizer.js if needed.
