### ISSUE TITLE
gulp watch -t THEME does not compil uikit.THEME.css

### ISSUE THREAD

**Issue by dagatsoin** [uikit/uikit#1062]
I have a custom/THEME and when I modify the less files Gulp compiles a uikit.css but not from the custom/THEME (Of course I launched `gulp watch -t THEME`)

I already have this [problem with the customizer](https://github.com/uikit/uikit/issues/945) and `gulp -a` is not a solution vs `gulp watch -t THEME`...

I find out that when I go to http://localhost:3000/tests/overview.html and select the custom THEME, then Gulp compiles the right files...

So I think there is a real issue with it, is not ?

**Comment by thealexbaron** [comment]
Any word on this?

**Comment by dagatsoin** [comment]
The only workaround I know is to keep a tab opened on the "test" page of your custom theme. Then gulp will compile the right files.

**Comment by thealexbaron** [comment]
Apparently not many people using custom themes, eh?

**Comment by malles** [comment]
`gulp dist -t Themename` will compile the custom themes. The watch function has to be looked at, as well as the docs

**Comment by dagatsoin** [comment]
fixed since.

**Comment by fbarrento** [comment]
Not working
