### ISSUE TITLE
Release styles without Base

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1063]
When included in a theme, UIkit seems quite aggressive in overriding base styles, like links and heading.
I suggest to include a "base-less" version of default styles in your releases.

**Comment by krzksz** [comment]
+1

There is to much styling going on in base styles which have to overwrite in every project so far, especially in navbars. Spliting it to `theme.base.less` would just allow to exclude it from bulild stylesheet.

**Comment by saschadube** [comment]
Just don't include the base.less in your custom UIkit theme.
