### ISSUE TITLE
How to make 2 'sticky' elements stack on the right of the screen

### ISSUE THREAD

**Issue by akcreation** [uikit/uikit#1065]
Hi there, I love the 'sticky' component - but I cannot get it to do what I want.
On the examples shown on the getuikit website, it is possible to have 2 sticky elements stack on top of each other, for instance:
<div style="margin: 0px;" class="uk-panel uk-panel-box" data-uk-sticky=""></div>
<div style="margin: 0px;" class="uk-panel uk-panel-box" data-uk-sticky="{top:100}"></div>
However, I can only get this to work when the elemens are on the left side of the screen.
Lets say I want to have 2 elements which float on the right side of the screen, I cannot get this to work. I apply 'uk-float-right' or 'uk-align-right' to my elements, and it displays all messy. It works with 1, but as soon as I want 2 elements stacked it breaks.
I am tearing my hair out trying to get this to work, can anyone offer any assitance?
Also, rather than have things stick to the top of the screen, is it possible to get them to stick to the bottom also?
Thanks very much :)

**Comment by saschadube** [comment]
Please take a look in the docs or tests, and provide a [https://jsfiddle.net/](JSfiddle).
