### ISSUE TITLE
Documentation inconsistent on Progress

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1068]
While the core documentation http://getuikit.com/docs/core.html talks about the progress bar being in the Common section, it's not there. It appears that the progress bar has been moved to the Add-ons section (which is still called Components). Please have someone look at the documentation, it's becoming increasingly inconsistent.

**Comment by malles** [comment]
I think this really was the last one... :)

**Comment by jerry1970** [comment]
:+1:
