### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by macinchik** [uikit/uikit#1069]
Is this an error? http://getuikit.com/docs/modal.html

This:

$('.modalSelector').on({

    'show.uk.modal': function(){
        console.log("Modal is visible.");
    },

    'hide.uk.modal': function(){
        console.log("Element is not visible.");
    }
});

should be:

$('.modalSelector').on({

    'uk.modal.show': function(){
        console.log("Modal is visible.");
    },

    'uk.modal.hide': function(){
        console.log("Element is not visible.");
    }
});

**Comment by malles** [comment]
No, but it used to be. Upgrade your UIkit and it all will match again.

**Comment by macinchik** [comment]
Ah. Ok. Thank you. ☺
