### ISSUE TITLE
Lightbox > Youtube | Not able to calculate size if video is set to autoplay

### ISSUE THREAD

**Issue by milos-aleksic** [uikit/uikit#1070]
This is easily reproducible on [Lightbox Component page](http://getuikit.com/docs/lightbox.html).

If youtube's URL contains the autoplay variable with value 1, once the lightbox is opened it is not able to calculate frame's size, giving as result a very small lightbox and video. Attached are screenshots as visual example.

As neither youtube's video and lightbox have size params I deduce the size should be calculated by lightbox, same way it is if video is not set to autoplay.

- Am I missing something?

![screenshot from 2015 03 12 18 50 53](https://cloud.githubusercontent.com/assets/2932588/6630660/6a2062de-c8e9-11e4-9152-f139008382e6.png)

![screenshot from 2015 03 12 18 51 20](https://cloud.githubusercontent.com/assets/2932588/6630689/ab17bad0-c8e9-11e4-842f-8a2e6ba07275.png)

**Comment by aheinze** [comment]
I can't reproduce that. could you please provide a [jsfiddle](http://jsfiddle.net/)?

**Comment by esedic** [comment]
I can confirm that this issue still exists.
Here is an example with autoplay parameter in iframe URL: http://jsfiddle.net/esedic/ywmr8o3w/embedded/result/

And here is an example of iframe URL without autoplay parameter: http://jsfiddle.net/esedic/decq3xv2/embedded/result/
