### ISSUE TITLE
Pass line breaks to tooltip

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1074]
it'd be really usefull to handle line breaks as br in a tooltip

i've made a simple hack, but I think it can be a core functionalitity 

line 73 in tooltip.js
insert line
```javascript
this.tip = this.tip.replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '<br>');
```

**Comment by MacWordPress** [comment]
+1

**Comment by malles** [comment]
+1
Although I'd rather have a tooltip that would take full html. That would have to be some modified dropdown I guess.

**Comment by jerry1970** [comment]
I remember I once used an actual line-break for a regular tooltip:
``` html
<a href="..." title="This is line one.
And this is line two">...</a>
```
Not sure if that would work with this one.

I'd like the suggestion @malles gave: full html. I once did that with hidden elements, something like this:
``` html
<div data-uk-tooltip-target="#my-tooltip">Something</div>
<div id="my-tooltip" data-uk-tooltip-source>This is <b>the</b> tooltip.</div>
```

**Comment by Dmatafonov** [comment]
> I'd like the suggestion @malles gave: full html. 

imho it's not a job for uikit, it's a seprate job for qtip2 which is beautifull and powerfull library for html tooltips

when I need simple "title" tooltip, I use uikit tooltip, but when I want interactive, adjustable, ajax-powered tooltip, I use qtip

**Comment by jerry1970** [comment]
Hm, qipt2 only adds a little bit, namely the HTML and iframe. So I would need the uikit tooltip (to be in style with the rest of uikit) and qtip for a few html tooltips? Uikit is already loading CSS and JS and showing HTML for the regular tooltip. Needing qtip2 is duplicating code.

**Comment by Dmatafonov** [comment]
>Needing qtip2 is duplicating code.
If you want just to show tipsy-style tooltips, yes. 

uikit tooltip by now is far far from qtip, trust me

qtip adds a lot - events, methods, styling. imo qtip is one of the most powerfull js libraries out there

just simple example of what qtip is able (from my website)

![1](https://cloud.githubusercontent.com/assets/8863854/6813938/914083ba-d282-11e4-970b-29e11ba802c0.gif)

It gets html from ajax and real time data from websockets

**Comment by malles** [comment]
@Dmatafonov This would be done in a `uk-dropdown` with some observers. 
In this example I created a slideshow that comes in on hover.
![zoom-hover](https://cloud.githubusercontent.com/assets/5442402/6822899/7dd13174-d2e3-11e4-8869-adc403692453.gif)
(Still waiting on proper content)

**Comment by aheinze** [comment]
linebreaks in tooltips isn't something common. why don't you just use <br> instead. looks also cleaner.

**Comment by Dmatafonov** [comment]
<br> in the title attribute? don't think so
