### ISSUE TITLE
Duplicate Issue: Nestable change does not trigger if you drag a node to the first place of its grand-parent #685

### ISSUE THREAD

**Issue by InteLigent** [uikit/uikit#1080]
Issue #685 is back.

Issue on line https://github.com/uikit/uikit/blob/master/src/js/components/nestable.js#L413

if remove row 
```js
this.tmpDragOnSiblings[1] &&
```
then it is ok.

**Comment by aheinze** [comment]
sorry, but I can't confirm the issue. could you please provide a [jsfiddle](http://jsfiddle.net/)?
