### ISSUE TITLE
Disable list-item in dropdown doesn't work.

### ISSUE THREAD

**Issue by theother1** [uikit/uikit#1081]
I need to disable (grey out) an item in the dropdown list.

I added .uk-disabled to the li, but it doesn't work. Please check screenshot.
How can I disable an item in the dropdown with uikit? (grey out/not selectable)

thanks

URL: http://bhantugh.com/en/home/about/steve-rhodes/ce
![disabled](https://cloud.githubusercontent.com/assets/10718044/6676595/13fa1608-cc21-11e4-979a-5acfdcb1fc28.jpg)

**Comment by malles** [comment]
Use `uk-subnav` for your `ul`
![screenshot_60](https://cloud.githubusercontent.com/assets/5442402/6676889/95cfc484-cc2b-11e4-8785-af844ab31ea0.png)

**Comment by theother1** [comment]
Thanks. This didn't work for the dropdown. I need a button/dropdown menu, but able to disable some of the items at times.

By adding replacing the <ul> class with uk-subnav, it was all messed up.

**Comment by malles** [comment]
If you can, replace the `a` with a `span` for the disabled, then they will be muted as will I think

**Comment by theother1** [comment]
looks terrible and is not very practical either, because it's not greyed out.

So there is no default solution to disable dropdown menu items within uikit? That's seems to me like quite an oversight... it wasn't mentioned for dropdowns only subnavs. and of course that doesn't seem to work. shame... I probable have to hide the whole row then from the menu with jQuery.

![2](https://cloud.githubusercontent.com/assets/10718044/6678171/0a4e3cfc-cc2f-11e4-98ef-34c0ee02a65c.jpg)

**Comment by malles** [comment]
No, that is not the effect I was hoping for.
Off course you can just use the class `uk-text-muted`, and you'll have to surpress the link as well somehow.
It is weird that `uk-disabled` works in `uk-subnav', but not in `uk-dropdown-nav`

**Comment by theother1** [comment]
yes, shame. I just hide the items I don't need. no problem. thanks

**Comment by malles** [comment]
By the looks of it, that looks a YOOtheme template. Create a default menu with a separator. See how that's made up and copy that markup.
