### ISSUE TITLE
Can't empty the input of autocomplete

### ISSUE THREAD

**Issue by esrch** [uikit/uikit#1082]
I have an autocomplete component on my page, and I use it to add new items to a table. Once I select a value in the autocomplete, I use jQuery to add a row in the table, which works very well.

However, once the row is added, I would like to empty the autocomplete input, so that I can add a new value. Unfortunately and contrary to my expectation, `$("#ac-input").val("")` (where #ac-input is the input tag of the autocomplete component) doesn't work. Is there a way to programmatically empty the input of an autocomplete?

**Comment by malles** [comment]
Yes, that is possible, but not as easy as it seems.
https://github.com/uikit/uikit/blob/master/src/js/components/autocomplete.js#L201
Here you see that the event `select.uk.autocomplete` is triggered before the value is placed in the input. It does give you the opportunity to alter the value that is placed in the input. 
```
UIkit.$('#autocomplete4').on('select.uk.autocomplete', function (e, data, ac) {
    UIkit.$('#clickResult').text('You clicked ' + data.value + ' and I erased that again!').addClass('uk-alert');
    ac.input.val('');
    data.value = null;
  });
```
will do the trick, as shown in example 4 in http://codepen.io/malles/pen/qEyEZr

**Comment by esrch** [comment]
Thanks for the quick answer, that's really helpful!
