### ISSUE TITLE
Capital letters for jpeg file extension (.JPG) don't work in lightbox

### ISSUE THREAD

**Issue by Form2Content** [uikit/uikit#1083]
Seems like a issue in the UIkit lightbox javascript. Capital letters for jpeg files extensions don't work, So .jpg works fine, .JPG doesn't load. Tested in latest version 2.18.0.

See issue here. Same pictures loaded with .jpg instead of .JPG do load.
http://www.enroute.nl/fietsreizen/trainingsweken-clinics/132-clinics-ardennen

**Comment by malles** [comment]
Lightbox tries to detect the type of data it has to show. You can force the type by putting `data-lightbox-type="image"` in your lightbox tag. http://getuikit.com/docs/lightbox.html#different-content-sources

**Comment by malles** [comment]
@aheinze maybe the Regex could be passed the `i` modifier to be a bit more flexible?
`(data.type == 'image' || data.source && data.source.match(/\.(jpg|jpeg|png|gif|svg)$/i))`

**Comment by Form2Content** [comment]
Thank you!! This has solved the problem. Like you suggest I think a bit more flexibility could solve people running into this. Especially for those who are used to the Yootheme Widgetkit which "just worked" ;).

**Comment by malles** [comment]
And it will work without the extra tag as well soon: https://github.com/uikit/uikit/commit/07ced8e9fd41c68c20d2aaec1329abd6e030c21b
Thanks @aheinze !
