### ISSUE TITLE
htmleditor.js - error in plugin code

### ISSUE THREAD

**Issue by unagi2020** [uikit/uikit#1084]
I am getting following error at line 176, col 12
TypeError: UI.$.extend is not a function   
UI.$.extend(this.buttons, buttons);

following is my file addition sequence and I am working on latest build
```
<link rel="stylesheet" href="/styles/theme.css">
<script src="/js/jquery.min.js"></script>
<script src="/js/uikit.js"></script>
<link rel="stylesheet" href="/js/codemirror/codemirror.css">
<link rel="stylesheet" href="/js/codemirror/show-hint.css">
<script src="/js/codemirror/codemirror.js"></script>
<script src="/js/marked.js"></script>
<link rel="stylesheet" href="/js/uikit/htmleditor.css">
<script src="/js/uikit/htmleditor.js"></script>
```

**Comment by malles** [comment]
It would help to know in what file on line 176 this occurs...

**Comment by unagi2020** [comment]
Sorry for not being explicit ... it is in the htmleditor.js file

**Comment by aheinze** [comment]
this pretty strange, which UIkit version do you use=
