### ISSUE TITLE
Off-Canvas links

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#1087]
If I use a link like href="#user/3" with off-canvas a jquery error occurs (Error: Syntax error, unrecognized expression: #user/3)
Same with href="#user|3" 
No problems with href="#user-3" 
I tested it on getuikit.com/docs/offcanvas.html with href "injection"
Is ist forbidden to use href="#user|3" or href="#user/3"?
Thanks for all answers

**Comment by malles** [comment]
as a href it is not forbidden, a link can contain those characters. You're referring to other element on the page that would have to have an id like `user/3`, and that is forbidden.
The error you get comes from selectors trying to find that element like `$('user/3')`, which throws an error.
If you're trying to link to another page, just make the href `user/3`

**Comment by luetn** [comment]
@malles Thank you
I just want to change hashtags
I now ended up with href="./#user/3" (since my page is index.php)
With the official off-canvas page it would be href="offcanvas.html#user/3"
right?

**Comment by malles** [comment]
I'm not sure this is an issue. As @luetn said, just make sure the link doesn't start with `#`, and make it a valid link
