### ISSUE TITLE
scrollspy and grid-match to not play together?

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1088]
Hi, I cannot make data-uk-grid-match play well together with data-uk-scrollspy animation.
I tried to apply data-uk-observe and also data-uk-check-display (just that I tried it) but no change.
The blocks animate flawlessly,  but they to not align their height. Without animation, they do.

A simplified example:
```
<div class="uk-grid" data-uk-grid-match="{target:'.align_height'}">
	<div class="uk-width-large-1-2 align_height">
		<div data-uk-scrollspy="{cls:'uk-animation-scale-down'}">
			TEXT
		</div>
	</div>					
	<div class="uk-width-large-1-2 align_height">
		<div data-uk-scrollspy="{cls:'uk-animation-scale-down'}">
			TEXT<br>
			TEXT<br>
			TEXT
		</div>
	</div>
</div>
```

**Comment by malles** [comment]
Try adding the `uk-match-height` class to your grid. http://getuikit.com/docs/grid.html#match-column-heights

**Comment by tbba** [comment]
was it THAT simple?

**Comment by malles** [comment]
Nope
The conflict with scrollspy seems valid: http://codepen.io/malles/pen/XJomQq
One other issue with your code, you should apply the `align_height` class to the div inside the grid you want to match, your scrollspy divs in this case. I made it panels in my example, to see the edges better.
The actual grid-divs are matched fine, it's the animated content that is not adjusted after animation.
When I let `UIkit.Utils.checkDisplay();` run after the animation, the heights are set properly.
I think you should reopen this, as it's a valid issue.

**Comment by tbba** [comment]
ok, I reopen it for you so this can be investigated further :-)

Your comment lead to a solution in a slightly different direction, using panels. 
This works here:
```
<div class="uk-grid uk-grid-match" data-uk-grid-match="{target:'.align_height'}">
	<div class="uk-width-large-1-2 align_height">
		<div class="uk-panel uk-panel-box" data-uk-scrollspy="{cls:'uk-animation-scale-down'}">
			TEXT
		</div>
	</div>
        ....
```
Don't ask me why ;-)

**Comment by aheinze** [comment]
this is because ```element.is(':visible')``` returns false if opacity is 0. use .uk-grid-match as a workaround suggested by @malles
