### ISSUE TITLE
Component 'Sticky' z-index issue

### ISSUE THREAD

**Issue by dommm** [uikit/uikit#1089]
I'm having an issue, when scrolling down and Sticky is hidden behind the blocks. Actually, all other content, that is not within `uk-panel` are hidden behind sticky.

I just found out, that `position:relative` in `uk-panel` makes that issue. I kinda need have relative for other block positions.

Is there any way to modify It?

**Comment by malles** [comment]
did you load the sticky css file?

**Comment by dommm** [comment]
I've just finished playing with it and  eventually found out, that the file path for compiling was set wrong.
It runs smoothly now.

Also, When I run `Audits` from Chrome's console, It suggests that I should combine our `Components` files into as few files as possible. 

Wouldn't be the page loaded faster, if the server mustn't access all necessary our `Components` style files?

**Comment by malles** [comment]
Yes, it would.
For that, you can compile your own minified theme file and include the components you need there. http://getuikit.com/docs/documentation_create-a-theme.html

**Comment by dommm** [comment]
I'm working on my own theme from the beginning. Didn't occurred me until now, you've confirmed it.

Thank you Malles for your help and advice!
