### ISSUE TITLE
Disable touch-support for Tab + Switcher in IE11

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#1092]
Hi, 

I'm using uikit 2.17.0 and I recently regognized, that you can "scroll" through switcher-tabs by swiping. I have a few text-boxes inside the tabs and when a user trys to mark the text inside a text-boxe, it triggers that touch-effect. That only happens in IE 11 as far as I know.

So I'm trying to disable the touch-support for all switcher-tabs by setting

```
.uk-switcher {
    touch-action: none !important;
    -ms-touch-action: none !important;
}
```

but it doesn't work. Does anyone know, how to disable the touch-support for switchers?

**Comment by stebeg** [comment]
I've found a solution:

```
$(window).load(function () {  
    $('.uk-switcher').off('swipeRight swipeLeft');
  });
```

It would be nice, if the switcher would have an option to turn in on/off.

**Comment by florianletsch** [comment]
Fix will be included in the next release.
