### ISSUE TITLE
"uk-active" class always stays on the first menu item

### ISSUE THREAD

**Issue by owingruters** [uikit/uikit#1094]
Hi,

I have a menu with 5 menuitems. I notice that the class "uk-active" is always set on the first menu-item does not get set on another menuitem after I clicked it. Result is that the first menuitem is always active, even if another menuitem is active as well..

Any idea why that is, what I can do?

(the site is on http:/www.odd-software.nl. It is using kotoba2 template for Joomla)

**Comment by vuchl** [comment]
You need to define the logic which menu item has the ```uk-active``` class yourself. It's not Uikits jo to do your logic/templating stuff. It's just fpor decoration as it is a CSS frontend framework.

**Comment by owingruters** [comment]
Thanx four the answer. So I probably should contact the creator of the template, since that should be in (and partiallly is) in the template. Unfortunately kotoba2 does not have any support...
