### ISSUE TITLE
Wrong gutter in grid

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1095]
Demo: http://jsfiddle.net/d8wxnvv9/
This code work fine in UIkit 2.16.2
After update to 2.18.0, the layout is break...
I think, the grid doesn't have the proper gutter (after change uk-grid-preserve to uk-grid-medium (UIkit 2.17.0)

**Comment by saschadube** [comment]
Please don't use the ```fieldset` not as grid cell. Just use a ```div``` http://jsfiddle.net/d8wxnvv9/1/
