### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by PhentomPT** [uikit/uikit#1096]
Hey.

I'm using http://getuikit.com/docs/upload.html and can't get the file uploaded to any where.
The loading bar works, the file drop / select file works, success message appears, but file does not get uploaded.

Thanks.

**Comment by zslabs** [comment]
You have to handle the actual upload of files yourself. That's what the `action` param is for.

**Comment by PhentomPT** [comment]
Made the php script and works fine, but is there a limitation of size? (in the upload.js) i can't upload big files.

**Comment by zslabs** [comment]
Not that I can see in the script -- could be a server-upload issue.

**Comment by vuchl** [comment]
https://www.drupal.org/node/97193

**Comment by PhentomPT** [comment]
Thanks for the help!
