### ISSUE TITLE
Utility Documentation page is down!

### ISSUE THREAD

**Issue by akcreation** [uikit/uikit#1097]
Hi guys, I need to see the docs for the utlility component, please can you urgently get this fixed?

http://getuikit.com/docs/utility.html

Many thanks,

Keith

**Comment by vuchl** [comment]
Up and running for me

**Comment by akcreation** [comment]
Hi vuchl, I've just checked again (and cleared my cache) and it is not running, please see the attached screenshot. How is that possible - unless you have a cached version?
![screen shot 2015-03-20 at 17 53 15](https://cloud.githubusercontent.com/assets/5363440/6757602/2e2f2412-cf2a-11e4-853c-765f3068a25f.png)

**Comment by vuchl** [comment]
Just checked with FF and IE (ugh) again and I don't see the down message. Do you use VPN or a roxy?

**Comment by akcreation** [comment]
just checked again and it is now working for me?! Really strange. Oh well, whatever it is it is now fixed - thank you so much for your help anyway :)
