### ISSUE TITLE
Print CSS in Firefox

### ISSUE THREAD

**Issue by MacWordPress** [uikit/uikit#1104]
I noticed problems when printing from Firefox (both Mac and PC) in all websites, that use UIkit. Firefox prints only one page, the rest is thrown away. Try print preview of any page - i.e. UIkit docs http://getuikit.com/docs/core.html in Firefox.

**Comment by florianletsch** [comment]
Hm, when I print in Firefox, it doesn't seem to throw anything away. Some of the content gets pushed to the second page however, so there's definetly something going on. Not sure if this is a core UIkit issue or the getuikit.com custom css that's messing things up.

Do you have a link to one of your pages where this is happening?

**Comment by MacWordPress** [comment]
Try to print i.e. this page in Firefox:
http://yootheme.com/demo/themes/wordpress/2015/salt/?page_id=781
Almost any of YouTheme sites is affected by this print issue.

**Comment by Sulkazi** [comment]
I have run into this problem as well... I see it was closed without posting any solution of what to fix in the CSS so firefox Print CSS will work properly.  Is this to be ignored?

**Comment by webers-technikum-wien** [comment]
thats an issue with one of the many div containers in uikit. 

i fixed it by using @media print query in CSS to reset the properties for all the containers, especially for the class .uk-grid, to {display: inline !important}

**Comment by Wingpilot** [comment]
> i fixed it by using @media print query in CSS to reset the properties for all the containers, especially for the class .uk-grid, to {display: inline !important}
You are awesome! That's exactly what fixed the issue. Just added the following to CSS file:
`@media print
{
	.uk-grid {
		display: inline !important
	}
}`
