### ISSUE TITLE
Sortable doesn't work on touch display

### ISSUE THREAD

**Issue by meriturva** [uikit/uikit#1105]
I have a dell xps with a touch screen.
On chrome drag action doesn't work.
See:
https://yootheme.com/support/question/79590

**Comment by saschadube** [comment]
Can you provide a [JSFiddle](http://jsfiddle.net/)?

**Comment by meriturva** [comment]
This is not related to a script...it is just related to the "display" touch capabilities.....just get the widgetkit interface...and try to order it by a dell xps with touch screen.

**Comment by florianletsch** [comment]
On pure touch devices this seems to work without any issue (tested on iOS at least). I guess the issue relates to mixed devices (click + touch capabilities). We'll somehow need to get our hands on a test device to figure this out.

@meriturva Have you tested on a smartphone or tablet if you get the same issue there?

**Comment by meriturva** [comment]
I have now tested the "sortable" example on uikit page http://getuikit.com/docs/sortable.html with my nexus 10 and chrome and it dosen't work.

**Comment by tzd** [comment]
Sortable component (and nestable also) not working for me either on android touch devices (samsung galaxy s3 i9300 and samsung galaxy note 10 n8000). On ipad (iOS) works ok.

**Comment by miladmeidanshahi** [comment]
not working on galaxy s4 i9500

**Comment by spee65** [comment]
doesnt work on my dell xps with a touch screen - chrome

**Comment by meriturva** [comment]
The same on windows 10!
Please fix!

**Comment by stefanpkc** [comment]
With chrome on Sony Xperia z2 and nexus 5 latest  android it doesn't work.

**Comment by VizuaaLOG** [comment]
Can confirm this also, One Plus One with Android 5.1.1 Cyanogen OS 12.1. Latest version of Chrome on Android.

**Comment by ccasallas** [comment]
Hi All,

We are working with sortable component, but it seems does not work on chrome mobile browser. Even, We test official demo example (http://getuikit.com/docs/sortable.html) but it does not work on chrome mobile for Android. We use a Nexus 5 device.

regards.

**Comment by meriturva** [comment]
I confirm that issue persists in UiKit 2.24.0 version.
Check here: http://getuikit.com/tests/components/sortable.html

**Comment by luetn** [comment]
Just tested on windows phone, windows 8.1
Does not work either.

**Comment by stefanpkc** [comment]
after almost a year, no solution yet? :-(

**Comment by stefanpkc** [comment]
@saschadube,
Here is a codepen for testing: http://s.codepen.io/stefanpkc/debug/LGeLVr
Edit here: http://codepen.io/stefanpkc/pen/LGeLVr?editors=100
try this out on an android device. Or with google chrome and toggle the mobile device mode. Everything that uses UIkit has this bug as far as I know.

**Comment by gornycreative** [comment]
An interesting anomaly. When starting a drag operation from inside a draggable object on android chrome, the sortable/draggable doesn't move, but the page itself can also not be scrolled. It appears that there is a conflict between the event listeners initialized by uikit and the listener that scrolls the page on drag.

**Comment by lucil** [comment]
Last night I worked on this problem and I came out with a solution for the problem. 
I noticed the hasTouch variable. 
I think it is not correct to behave differently based on the touch support of the client. 
This is a problem if  there is a mouse event firing in a client with touch screen support.
Instead it would be better to control each event containing touches. 
I also fixed some other little things.
You can find my sortable.js version here: https://jsfiddle.net/xte51scL/

**Comment by tzd** [comment]
@lucil 
Thank you for your contribution.
For basic sortable grid It works well on my android devices but it seems that on multiple lists http://getuikit.com/docs/sortable.html#group it doesn't work.
I was trying to make it work but without success, could you check why it's not working?

**Comment by lucil** [comment]
@tzd I will debug it asap.

**Comment by lucil** [comment]
@tzd fixed it.

**Comment by tzd** [comment]
@lucil 
Thank you very much. Now it works as expected.

**Comment by razvanioan** [comment]
Are you sure this is fixed ?

I have Toshiba Satellite with touch screen, windows 10 x64, and on latest Chrome this is still not working (on Firefox is working), testing on [your component page on your site](http://getuikit.com/docs/nestable.html), not my script

or it is not implemented on your website yet ?

**Comment by lucil** [comment]
@razvanioan my fix is not on the official master branch, the one you see on the website. 
You can find it on sortable.js on my pull request.

**Comment by scott-orleman** [comment]
Can confirm this bug on the main page using Android Galaxy S4 and Microsoft Surface 3

**Comment by SaphiLC** [comment]
im in a surface pro 2 and this happens to me too, also the hover menus become click only, the overlays bug horribly too (if you hover them you need to move the mouse outside the window for the overlay effect to dissapear)... im surprised one year passed and they didnt fix this yet... :(

**Comment by xpd** [comment]
Seems to be a problem when text are selected too.

**Comment by SaphiLC** [comment]
any news about the touch enabled devices bugs? even pagekit is not usable because im using a surface pro 2 ... :S

**Comment by websterz** [comment]
The quick fix is to add JQuery punch http://touchpunch.furf.com/

**Comment by julianotheiss** [comment]
for me this worked good:

.uk-sortable > li {
    touch-action: none;
    @media (max-width: 480px)
    {
        touch-action: initial;
    }
}

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
