### ISSUE TITLE
Placeholder off-center with Chrome 42.XX

### ISSUE THREAD

**Issue by andrewkdesigns** [uikit/uikit#1106]
Input placeholders seem to be aligned-top in the new version of Chrome 42.xx

Screenshot: http://imgur.com/mN1yCxA

**Comment by malles** [comment]
Can't confirm that on Chrome Canary 43
Can you pinpoint the problem in the console?

**Comment by andrewkdesigns** [comment]
I can't seem to pinpoint it. I looked for any new browser styles, couldn't find any. I'm just gonna leave it. Hopefully it fixes itself in an upcoming version of Chrome.

**Comment by ahallicks** [comment]
Previous experience of this bug says this is something to do with line-height:

http://stackoverflow.com/questions/5208418/the-placeholder-text-in-my-text-boxes-is-mis-aligned-in-chrome
