### ISSUE TITLE
Same width of Icons ..

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#1107]
.. is much more readable (see tooltip in the screenshot)
Just to illustrate -> see my screenshot (of course: in my environment there is not the same data for the event and the tooltip)
Maybe a class for same_width_of_icons would be desirable??
![bildschirmfoto 2015-03-24 um 18 40 48](https://cloud.githubusercontent.com/assets/6003040/6808716/e81d6bbc-d255-11e4-8cb3-66f19a09cff5.png)

**Comment by vuchl** [comment]
I'm bugged by this too.

**Comment by malles** [comment]
Icon with fixed width has been requested. https://github.com/uikit/uikit/issues/885
I'm all for it!

**Comment by saschadube** [comment]
It's on our todo list
