### ISSUE TITLE
add links to cdnjs in the core and components pages

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1108]
so that developers can test out uikit easily

**Comment by malles** [comment]
easiest link to latest release is http://getuikit.com/dist/js/uikit.js, might be usefull to show that. 
What is the status on cdnjs?

**Comment by Pandahisham** [comment]
+1

**Comment by seanfrasure** [comment]
https://cdnjs.cloudflare.com/ajax/libs/uikit/2.18.0/js/uikit.min.js
↗↖so u mean add this?

**Comment by PixelT** [comment]
https://cdnjs.com/libraries/uikit :P

**Comment by seanfrasure** [comment]
@PixelT that's the CDN list for if you only want certain parts of the kit.

**Comment by Pandahisham** [comment]
i think , the link for latest release is the best as @malles mentioned , i like to play around without downloading stuff , like in codepen , so it helps if the link is visible nearby , also The best thing about Uikit is it's test pages , i learned more inspecting the code of the test pages than the docs , also serves as a stealing ground :p
