### ISSUE TITLE
z-index issue with animated elements overlapping sticky navbar

### ISSUE THREAD

**Issue by florianletsch** [uikit/uikit#1115]
Elements with `uk-animation-*` class seem to result in a higher z-index than a sticky navbar.

![uikit-zindex](https://cloud.githubusercontent.com/assets/1116784/6885659/29f2c06e-d62a-11e4-9c74-120bdd06aed0.gif)

**Comment by saschadube** [comment]
Please provide a [https://jsfiddle.net/](JSfiddle) :stuck_out_tongue_closed_eyes:

**Comment by florianletsch** [comment]
Can't seem to reproduce anymore. Will reopen in case I encounter this issue again.
