### ISSUE TITLE
Slideset - Responsive Features

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1124]
Hey @aheinze,
Saw the work on [Slideset](https://github.com/uikit/uikit/tree/feature/slideset) so far (great job!), is there work ahead for changing the number of slides shown based on a media query? Would ideally be based around the component's width itself and not window, since the slideset could be used in multiple contexts.

**Comment by PixelT** [comment]
+1
additionally:
- autoplay option
- set number of item in step

**Comment by aheinze** [comment]
```data-uk-slideset="{visible:{default: 4, medium:3, small: 1}}“```

**Comment by zslabs** [comment]
Awesome thanks man!
