### ISSUE TITLE
UIKIT Datepicker on touch screen devices 

### ISSUE THREAD

**Issue by Sabroson** [uikit/uikit#1127]
I'm submitting an issue here as suggested by kayhan from yootheme support. This is the issue:

I was using the datepicker provided by UIKIT which looks very nice but I was very disappointed to see that it does not work on touch screens. When you touch on the input field that triggers the datepicker, the touch screen device (I'm using an android based Samsung S3) triggers the keypad and the datepicker disappears :(

However the standard Joomla datepicker (not so nice looking) remains on touch screen devices even if the keypad is triggered.

I can see this behaviour on the UIKIT sample site:
http://getuikit.com/docs/datepicker.html

Is there a way to fix this? at least to behave the same as the Joomla datepicker...

thanks

**Comment by zslabs** [comment]
Had the same issue, see https://github.com/uikit/uikit/issues/1006 for what worked for me.

**Comment by Sabroson** [comment]
great, that does the trick. thank you!
