### ISSUE TITLE
Use :before to add dot to example code classes

### ISSUE THREAD

**Issue by rolandtoth** [uikit/uikit#1129]
Using `:before {content: "."}` to indicate classes would allow selecting the whole class name without the dot. This would improve usabilty of the example codes in the docs because currently copying the class name the starting dot also gets copied.

E.g. instead of this:
Add the `.uk-container` class to a block element (...)

this:
Add the `uk-container` class to a block element (...)
(+ `:before {content: "."}` in CSS to add non-selectable dot)

**Comment by florianletsch** [comment]
Good point

**Comment by saschadube** [comment]
Thanks, we will keep it in mind.
