### ISSUE TITLE
help in right aligning

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1130]
i am trying to right align the comment block , but the comment meta keeps floating up ,

http://codepen.io/Pandahisham/pen/PwgQMK

can anyone help ?

**Comment by vuchl** [comment]
put a ```<div class="uk-clearfix"></div>``` between the header and the meta div

**Comment by Pandahisham** [comment]
i tried , it works but now it goes under the avatar , may be i should use a grid here

**Comment by Pandahisham** [comment]
got it working with a grid , thank for helping @vuchl
