### ISSUE TITLE
IE11: uk-text-truncate have no right paddings

### ISSUE THREAD

**Issue by YuliaGrigorieva** [uikit/uikit#1131]
I have observed that uk-text-truncate has different behavior in IE11 than in other browsers.
Screenshots from: http://getuikit.com/docs/text.html
Mozilla Firefox:
![capture3](https://cloud.githubusercontent.com/assets/8545374/6963848/47b25978-d94c-11e4-9685-6f05ee7a10a0.PNG)
IE11:
![capture4](https://cloud.githubusercontent.com/assets/8545374/6963854/592ad496-d94c-11e4-8ab2-750aefac3291.PNG)

I suppose that there should be a right padding and "..." in IE11

**Comment by saschadube** [comment]
Thanks! Seems that the element needs a specified width and not just on the container element. I fixed it. 4e8b322babd25912e9802a7df0c86381b9ea5262
