### ISSUE TITLE
Triggers for modals within sortable objects do not fire.

### ISSUE THREAD

**Issue by christianmagill** [uikit/uikit#1132]
Despite assigning handles, triggers for modals do not fire when inside sortable elements.
```
<div class="uk-sortable" data-uk-sortable="{handleClass:'uk-icon-bars'}">
   <div class="ut-sortable">
      <div class="uk-panel uk-panel-box uk-margin-bottom">
         <i class="uk-icon-bars"></i>
         <a href="#"><i class="uk-icon-file-pdf-o"></i> Document 1</a>
         <a href="#modal-edit-document" data-uk-modal><i class="uk-icon-edit uk-float-right"></i></a>
      </div>
   </div>
 <div class="ut-sortable">
      <div class="uk-panel uk-panel-box uk-margin-bottom">
         <i class="uk-icon-bars"></i>
         <a href="#"><i class="uk-icon-file-pdf-o"></i> Document 2</a>
         <a href="#modal-edit-document" data-uk-modal><i class="uk-icon-edit uk-float-right"></i></a>
      </div>
   </div>
</div>
```

**Comment by christianmagill** [comment]
Additionally my own events do not trigger on the sortable objects. Any ideas?

**Comment by christianmagill** [comment]
Resolved! There was an issue with my trigger element html.

**Comment by christianmagill** [comment]
So far the only workaround I've found is adding my own event handler for the link to trigger the modal through the show() method

**Comment by aheinze** [comment]
or define a drag handle element, the everything should work fine again.

**Comment by christianmagill** [comment]
Haven't I done that with data-uk-sortable="{handleClass:'uk-icon-bars'}"?

I'm still having issues.

**Comment by malles** [comment]
Here is an example of the same issue with lightbox: http://codepen.io/malles/pen/jEvooV
