### ISSUE TITLE
UIkit 2.18.0 timepicker.min.js error

### ISSUE THREAD

**Issue by hstung11** [uikit/uikit#1134]
There is an error in UIkit 2.18.0 timepicker.min.js.
Uncaught TypeError: undefined is not a function

**Comment by zslabs** [comment]
@hstung11 That's an extremely vague error as it gives no context to the issue at-hand. If you look at the [demo page](http://getuikit.com/docs/timepicker.html), there are no errors, so you'll need to provide information about your setup and make sure you have the right dependencies for the timepicker.

**Comment by hstung11** [comment]
@zslabs hi, I using timepicker.min.js and I using latest jquery 2.1.3. and what else dependency needed?

**Comment by hstung11** [comment]
Ahh..It still need autocomplete component. Sorry my bad, I miss the part in the document.

**Comment by hstung11** [comment]
And the timepicker cannot scroll in chrome browser, but can be scroll in safari.

**Comment by hstung11** [comment]
Fix it by placing theme on it. it without theme then cannot be scroll in chrome. safari and firefox can.
