### ISSUE TITLE
Can't get gender icons to work

### ISSUE THREAD

**Issue by theother1** [uikit/uikit#1135]
I can see all the other icons, but the moment I replace the icon class with one from the Gender group I don't see anything. The only one from this group that shows is "circle-thin", but it's not strictly from the Gender group, since it's in another group too.

Any idea what's going on? I played around with this for an hour and I'm totally stuck. I need the Mars/Venus icons. How is it possible that all other icons work but not this class?

```
<div><i id="maleicon" class="uk-icon-mars"></i><i id="femaleicon" class="uk-icon-venus"></i></div>
```
shows nothing

```
<div><i id="maleicon" class="uk-icon-circle-thin"></i><i id="femaleicon" class="uk-icon-car"></i></div>
```
shows the icon

I run it within Joomla/Yootheme (Frequency). Could there be some kind of conflict?

**Comment by malles** [comment]
Those fonts are relatively new in FontAwesome. maybe an old version of the font is loaded. Check the dev-tools to see which font is loaded (from what location) and make sure you update those font-files to the latest UIkit font versions.

**Comment by theother1** [comment]
Yes, they must be new. For now I use the font awesome css until I have time to sort the uikit out... it works. not the most efficient way of course.. thanks!

**Comment by malles** [comment]
Hint: YOOtheme uses UIkit in folder `warp/vendor/uikit`. Update the `fonts` folder, replace `less/core/icon.less` with latest from this repo. Recompile less and you're good to go.

**Comment by theother1** [comment]
Thanks. I tried this but I get:
The uploaded file exceeds the upload_max_filesize directive in php.ini.

when compiling LESS.

what about all the other files in the repo for less? Do I not need to replace these too? animated. less, font-aweesome.less, etc.
