### ISSUE TITLE
.uk-grid breaks Safari display

### ISSUE THREAD

**Issue by bobrocke** [uikit/uikit#1136]
This definition for .uk-grid breaks Safari display of grids:
```
.uk-grid {
	display: -ms-flexbox;
	display: -webkit-flex;
	display: flex;
	-ms-flex-wrap: wrap;
	-webkit-flex-wrap: wrap;
	flex-wrap: wrap;
	/* 1 */
	margin: 0;
	padding: 0;
	list-style: none;
}
```
This definition fixes it:
```
.uk-grid {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    -ms-flex-wrap: wrap;
    -webkit-flex-wrap: wrap;
    flex-wrap: wrap;
    /* 1 */
    margin: 0;
    padding: 0;
    list-style: none;
}
```
I'm working with Grav and I hit this bug. Andy Miller, at RocketTheme, helped me find the problem and he offered the solution.

Do you want this as a PR, or will you roll it in a different way?

**Comment by florianletsch** [comment]
Thanks for reporting! In which scenario does this break the grid in Safari? Could you provide an example in a CodePen or similar?

**Comment by florianletsch** [comment]
Ok I see. The reason this breaks is because old versions of Safari Mobile do not support the *new* flex syntax. Here's the support chart from http://caniuse.com/#search=flex 
![screen shot 2015-04-07 at 18 15 01](https://cloud.githubusercontent.com/assets/1116784/7027855/4e0595b0-dd52-11e4-9734-78b4c5621fbb.png)

We will not include this fix, because UIkit only supports mobile Safari 7.1 and later.

If you need to support older versions of mobile Safari, you should include this fix yourself. To do this, you should probably create your custom UIkit theme to keep the UIkit core and your customizations separate. Here's how you can do that: http://getuikit.com/docs/documentation_create-a-theme.html (just start by copying the default theme and working from there).

I hope this resolves the issue. Thanks for taking the time to look into the grid issue.

**Comment by bobrocke** [comment]
Don't assume I'm using an old version of Safari; I see the problem with 8.0.4. I'll shoot to get a CodePen up tonight.

**Comment by florianletsch** [comment]
Oops, sorry. Sometimes it just looks easy in the beginning. ;)
Thanks, a Codepen would be great then.

**Comment by bobrocke** [comment]
Instead of a CodePen, here's my broken site example:
http://stage.bobrockefellerphotography.com

To fix it, switch off `display: -webkit-box;`

![home bob rockefeller photography](https://cloud.githubusercontent.com/assets/2962426/7028568/a76753e2-dd24-11e4-939c-1da18ac93f47.jpg)

**Comment by saschadube** [comment]
If I get it right, now ```display: -webkit-box;``` is breaking your site in Safari 8. But you added this property/value manually. So everything is working if you use the default UIkit grid?

**Comment by bobrocke** [comment]
I'm using the default UIKit grid. Safari's inspector reports that `display: -webkit-box` is being set in `grid.scss` line 67:
![home bob rockefeller photography](https://cloud.githubusercontent.com/assets/2962426/7033243/b31a72b0-dd46-11e4-89c2-91df2bb696ac.jpg)

But that line in my copy of `grid.scss` is:
```
.uk-grid {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -ms-flex-wrap: wrap;
    -webkit-flex-wrap: wrap;
    flex-wrap: wrap;
    /* 1 */
    margin: 0;
    padding: 0;
    list-style: none;
}
```
So I wonder where `display: -webkit-box` is coming from?

**Comment by bobrocke** [comment]
Continuing to dig, it appears that Autoprefixer might be to blame. If I turn it off, `display: -webkit-box;` is not longer generated.

Can anyone independently confirm that?

**Comment by saschadube** [comment]
Yes, I bet it's because of the Autoprefixer

**Comment by bobrocke** [comment]
Do you think it would be a good thing to move UIKit's LESS and Sass versions to requiring Autoprefixer as a part of the build process? It's becoming such a widely used tool, it might make sense and keep UIKit somewhat future proof as browsers evolve their support for un-prefixed properties.

**Comment by zslabs** [comment]
I had also brought this up so the YooTheme team doesn't have to worry about prefixing their src code -- let Autoprefixer do that in the build-step.

**Comment by saschadube** [comment]
But at the moment the autoprefixer seems to break stuff, right? So this needs to be solved first...

**Comment by zslabs** [comment]
I've never had that `-webkit-box` show up -- I'd make sure your Autoprefixer is up to date.

**Comment by bobrocke** [comment]
I'm running Autoprefixer 5.0.0 via CodeKit. Could that be the problem?

**Comment by zslabs** [comment]
I use the gulp-autoprefixer version, so I unfortunately can't comment on the Codekit build tools; though I imagine they should be the same as the creator of Codekit is pretty good about keeping those up to date. Wonder if there's some config out there causing it.

**Comment by bobrocke** [comment]
Maybe a configuration problem. Where would I want to look?

**Comment by zslabs** [comment]
Don't use Codekit, so can't help you there.

On Mon, Apr 13, 2015 at 4:13 PM, Bob Rockefeller <notifications@github.com>
wrote:

> Maybe a configuration problem. Where would I want to look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uikit/uikit/issues/1136#issuecomment-92484471>.
>



-- 

Zach Schnackel
*Web Developer*
http://zslabs.com

**Comment by rgbink** [comment]
This is a pretty old thread but I'm having this grid breakage in Safari Version 10.1 (12603.1.30.0.34) using UIKit v2. I'm use CodeKit with auto-prefixer on my SCSS, but not to generate any UIKit files, just custom CSS. I'm also not seeing the `-webkit-box` in the inspector, so this doesn't seem to be the issue for breaking the grid, which, of course, occurs only in Safari.

Any ideas on this yet? Never seemed to arrive at any definitive answers above.
