### ISSUE TITLE
How to set dropdown delay and remaintime globally?

### ISSUE THREAD

**Issue by qahar** [uikit/uikit#1138]
Right now I use lot of data-uk-dropdown="{remaintime:500, delay:200}"

Is there a way to change the default globally? Can't found it on docs

If not available, please consider to add. May be something like this

    $.extend(UIkit.components.dropdown, {
        options: {
           'remaintime' : 500,
           'delay'      : 200
        }
    });

**Comment by PixelT** [comment]
http://getuikit.com/docs/documentation_javascript.html#js-override

**Comment by qahar** [comment]
Thank you!
