### ISSUE TITLE
Switcher toggle >

### ISSUE THREAD

**Issue by lekoala** [uikit/uikit#1140]
Hi!

Not sure of the issue because it's only happening on my project, not on online demo (maybe because I'm using an old version of jquery?), but the default toggle for the switcher does not work if set to
">li" . instead, I have to use "li".

**Comment by malles** [comment]
Which version of UIkit are you using?

**Comment by lekoala** [comment]
the latest. but it's only happening on old jquery version (1.7.3) not the latest one

**Comment by malles** [comment]
The problem is probably there.. https://github.com/uikit/uikit/blob/master/bower.json#L9 UIkit requires >= 1.9.0
