### ISSUE TITLE
Create a theme not working

### ISSUE THREAD

**Issue by csch0** [uikit/uikit#1141]
This [documentation](http://getuikit.com/docs/documentation_create-a-theme.html) seems to be out of date, incomplete or the guplfile has an issue. But after creating a new template in /custom/THEME-NAME nothing happens after running gulp indexthemes -a

**Comment by florianletsch** [comment]
The gulp task is working fine for me. I've added to the docs to explain how to actually build the theme. The docs will go online with the new release.

If this still doesn't work for you, please report back with a more detailed description of your folder structure and the steps you're executing.
