### ISSUE TITLE
Activate Flex on different screen-sizes

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1144]
Is there any breakdown of Flex we can use to disable the default column structure on smaller devices? For example:

	<div class="uk-grid uk-flex-middle" data-uk-grid-margin>
		<div class="uk-flex-item-none">
			Image
		</div>
		<div class="uk-flex-item-1">
			<p>Text</p>
		</div>
	</div>

Works great on desktop, but I want this to break down to single columns on smaller screens.

**Comment by saschadube** [comment]
Maybe ´´´uk-flex-wrap´´´ works? If not, we should come up with something. A (JSfiddle)[https://jsfiddle.net/] would be nice to play around.

**Comment by zslabs** [comment]
Yeah, I did a combo of that and added on my own modifier class:

	.uk-flex-medium {
		@media (max-width: @breakpoint-small-max) {
			.uk-flex-wrap;

			> * {
				width: 100%;
			}
		}
	}

Can see how this could get a bit messy with all the modifier classes that come with Flex already, but the one above is pretty minimal.

**Comment by saschadube** [comment]
I will keep it in mind for the next Grid update.
