### ISSUE TITLE
Timepicker dropdown doesn’t close when selected another field.

### ISSUE THREAD

**Issue by DarkGreg** [uikit/uikit#1148]
If you have several dropdown fields on page (such as timepicker, datepicker) when you select one and after that select another timepicker, first dropdown doesn’t close.
Look directly on http://getuikit.com/docs/timepicker.html.
If you second select datepicker or autocomplete field all work right.

Windows 7, Chrome 41.0.2272.118, Firefox 37.0.1, IE 11.0.17
Linux,  Firefox 37.0
But Safari & Chrome on IOS7 fork fine.

**Comment by uikid** [comment]
This is still not fixed in version 2.20.3
