### ISSUE TITLE
Incorrect positioning of cursor in htmleditor element

### ISSUE THREAD

**Issue by p3k** [uikit/uikit#1149]
I often find it difficult to correctly position the cursor for the insertion point.

Actually, this happens even with [UIkit’s demo editor](http://getuikit.com/docs/htmleditor.html). 

Here is how:

1. Open the URL http://getuikit.com/docs/htmleditor.html#tab-mode
2. Position the cursor between the letters **t** and **a** of the word `exercitation` in the second paragraph (the one after `## Heading`)
3. Click, and the insertion mark starts blinking after the letter **d** of the word `ad` (same line, third from the left)
4. Press the delete key, and the letter **g** disappears from the aforementioned `## Heading` – instead of the letter **t** where the cursor was (thought to be) placed, initially.

This way I can reproduce the issue at least after every reload using Chrome 41.0.2272.118 as well as Firefox under OS X 10.10.2.

Sometimes it stops “working” after a while. It definitely stops after switching to preview mode and back. (So far for a work-around.)

Any idea what could cause this irritating behavior of the cursor and how to prevent it?

**Comment by aheinze** [comment]
Do you have tested it against the latest Codemirror release? The demo uses a pretty outdated version. We'll updated Codemirror for the next UIkit release

**Comment by p3k** [comment]
Yes, I tested it against Codemirror 5.1.0.

As a work-around I found out that calling `editor.fit()` after the page has loaded fixes the cursor position. 

However, it is not working if I put it in the `jQuery.ready()` method, but it works e.g. using `setTimeout()` with a delay of ~1000ms.

Could it be there is something asynchronously going on in CodeMirror even after the document has loaded?

**Comment by aheinze** [comment]
thanks for the hint, I committed a fix.

**Comment by p3k** [comment]
Thank you, too. Works like a charm :smile_cat:
