### ISSUE TITLE
Serialize form?

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1150]
How do I serialize uk-form data?

```html
<form class="uk-form uk-form-stacked" id="clientEnvelopeForm">
            <fieldset data-uk-margin="">
                <div class="uk-form-row">
                    <label class="uk-form-label" for="envelopeSize">Размер конверта</label>
                    <select class="uk-form-width-large" id="envelopeSize">
                        <option value="DL">DL (стандартный размер в 1/3 от А4)</option>
                        <option value="A4">A4 (стандартный размер в А4)</option>
                    </select>
                </div>
                <div class="uk-form-row uk-margin-small-top">
                    <label class="uk-form-label" for="envelopeIndex">Индекс</label>
                    <input id="envelopeIndex">
                </div>
                <div class="uk-form-row uk-margin-small-top">
                    <label class="uk-form-label" for="envelopeCity">Область, район, город, населенный пункт</label>
                    <input class="uk-form-width-large" id="envelopeCity">
                </div>
                <div class="uk-form-row uk-margin-small-top">
                    <label class="uk-form-label" for="envelopeStreet">Улица, дом, корпус, квартира</label>
                    <input class="uk-form-width-large" id="envelopeStreet">
                </div>
            </fieldset>
        </form>
```

```javascript
var data = $('#clientEnvelopeForm').serialize();
console.log(data); //undefined
```

**Comment by malles** [comment]
UIkit has no helpers for that. I use https://github.com/macek/jquery-serialize-object for that

**Comment by Dmatafonov** [comment]
Well, it's not that difficult to write own method, since input, select and textarea have val() method.

But I'd prefer native uikit method - because to serilize about 10 buttongroups, I had to write 10 seperate checkers. And it's booooring :)

Consider this a feature request guys. Forms are fine, but leper is needed.

**Comment by malles** [comment]
I guess that depends on how you write it :)
I think formhandling and validation should stay apart from the UI. It's too specific for each application.

**Comment by Dmatafonov** [comment]
Formhandling and validation is the UI. And as soon as uikit provided uk-form-row element, which prevents regular serialization, they shoul make a helper. Same for buttongroup, which is not radio.

**Comment by aheinze** [comment]
I agree with @malles this is not and won't be part of UIkit. The browser already provides multiple tools to validate and serialize a form. HTML5 forms + FormData object (https://developer.mozilla.org/en-US/docs/Web/API/FormData). I don't see a need to implement something custom for UIkit.

**Comment by schinckel** [comment]
JQuery .serialize() only works if your elements have a name and a value: which makes sense, when you consider that is also the data that would be sent when you submit a form normally in a browser.

**Comment by Dmatafonov** [comment]
@aheinze 
>  The browser already provides multiple tools to validate and serialize a form. 

Which one works with uikit buttongroup?
