### ISSUE TITLE
Offcanvas does not compensate for sticky elements.

### ISSUE THREAD

**Issue by christianmagill** [uikit/uikit#1151]
Offcanvas does not compensate for sticky elements. So if you use both together the sticky elements stay in their position horizontally as well as vertically, which is normally not what you want.

Another issue has a good jsfiddle of this...

http://jsfiddle.net/52umna8c/

**Comment by aheinze** [comment]
yes, right. for now we leave it to a custom solution e.g. http://jsfiddle.net/52umna8c/2/ . But we'll discuss a solution intern. thanks.
