### ISSUE TITLE
Touch.js not behaving correctly in IE11

### ISSUE THREAD

**Issue by bassmanpaul** [uikit/uikit#1152]
Hi,

In **IE11** touch events are being fired where as they aren't in **Firefox** (as expected).

Your test page shows the issue:

http://getuikit.com/tests/core/touch.html

- **Firefox** - `UIkit did not detect touch support on your device! :(` - Does **not** fire taps *(correct)*
- **IE11** - `UIkit did not detect touch support on your device! :(` - **Does** fire taps *(incorrect)*
- **IE10** - `UIkit did not detect touch support on your device! :(` - Does **not** fire taps *(correct)*

Regards,

Paul

**Comment by nstaeger** [comment]
Hi,

so here is the deal: Using IE 11 on a Windows 8.1 machine, that does not support touch, you get the message ```UIkit did not detect touch support ...``` which is correct. If your Windows 8.1 device does have a touch interface you get the message ```UIkit detected touch support ...```which is correct, too.

But there may be touch events detected (like swipe and tap) in IE11 on Windows 8.1, although they do not come from a touch input but a mouse. This is due to the [pointer-events](http://www.w3.org/TR/pointerevents/) we are listening on. IE11 fires them, no matter if you use touch or mouse. And this exactly how those events are designed.

Best,
Nicolai

**Comment by bassmanpaul** [comment]
Hi Nicolai,

Thanks for your informative response.

From a developer pointer of view I can see why the *touch.js* listens to the **"touch support"** of a device as to whether it fires of a touch event.
But from a user/behaviour point of view why would they expect a tap to be fired when they click a mouse?

If that is how pointer-events are designed in **IE11** then surely the *touch.js* framework should make sure that the behaviour is the same for all browsers shouldn't it?
Because now **IE11** works different from every other browser including **IE10**, which now makes working with touch events really difficult.

Moreover, I could understand if the message was `UIkit detected touch support ...` and a touch event was fired but it actually says the opposite; `UIkit did not detect touch support on your device! :(` but still fires a touch event which suggests unexpected behaviour.

Regards,

Paul

**Comment by nstaeger** [comment]
Hi Paul,

But I think this is a basic problem with touch input on devices which also support mouse AND touch input. You are merely not able to find out, if the current input comes from a touch or a mouse input. Especially in IE11 :)

If you look at the source code of the tests, you can see the following:

```javascript
jQuery(window).bind('swipeRight', 'body', function(e) {
    jQuery('#output').prepend('<li>swipe right</li>');
});
jQuery(window).bind('swipeLeft', 'body', function(e) {
    jQuery('#output').prepend('<li>swipe left</li>');
});
jQuery(window).bind('tap', 'body', function(e) {
    jQuery('#output').prepend('<li>tap</li>');
});
```

You can see, that we are listening to normal tap and swipe events... If the browser (IE11) fires those events, when a mouse is used, we cant do nothing against this :) Those events are not manipulated by UIkit. However you can use those information (if touch was detected), to handle those events accordingly. We do this in our JavaScript code at some points...

At the end, also remember that this is just a test, where you can see, if UIkit detected touch support on your device and if some touch-gestures are working...

Best,
N
