### ISSUE TITLE
Lightbox regexp for image

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1154]
Some image not load in lightbox. After diagnostic was revealed that some image contain additional symbol after extension. Remove additional symbol for various reasons can not be.
For example: http://www.1zoom.ru/big2/640/325558-svetik.jpg?m=1

Rex exp for image contain $.
Need remove & in reg exp and was all great.

data.source.match(/\.(jpg|jpeg|png|gif|svg)$/i)    ===>   data.source.match(/\.(jpg|jpeg|png|gif|svg)/i)

**Comment by malles** [comment]
If the filenames that are used are likely not to pass the regex, you can add the [`data-lightbox-type="image"`](http://getuikit.com/docs/lightbox.html#different-content-sources) to force the lightbox to an image mode.

**Comment by Intiligent** [comment]
ok. thanks

**Comment by aheinze** [comment]
@malles thanks!
