### ISSUE TITLE
Trigger Autocomplete on focus

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1155]
As the title says, I'm looking to enable the auto-complete on-focus with certain data (almost a "here's what you can use"). Right now I"m doing:

```
$("#query").on('focus', function(){ $(this).trigger('keyup'); });
```

Which I'm not too keen on. Any other thoughts? Thanks!

**Comment by jjunior187** [comment]
I had the same problem right yesterday. My solution was to add 
```js
"focus": trigger
```
right behind
```js
"keyup": trigger,
```
After I made that, I just had a problem with the fact that the value didn't systematically change in the input between two focus (as it is the case with the keyup event), and this prevented the triggering of $this.request() in the handle function. 

So in the handle function I replaced 
```js
if (this.value != old) {
  $this.request();
}
```
by
```js
$this.request
```
and get rid of the "old" variable.
So far, it works pretty fine and fits my needs.

Hope it helps...

**Comment by zslabs** [comment]
I'd prefer not to hack the core, so think I'll stick with my trigger for now :) Thanks though.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Autocomplete has not been released yet but we are working on this component. 

Thanks for your understanding,
Your UIkit Team
