### ISSUE TITLE
uk-navbar-nav dropdown

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1156]
There is a font family setting for .uk-navbar-nav > li > a
Since this is the only occurrence where a font family is set - is this a bug or  feature?
I expected to see the global font that I set everywhere else in the menus.

Also it appears that the navbar dropdown has a fixed width of 200px;
Extreme long menu items (e.g. "Suchmaschinenoptimierung") show as overflow visible and reach out of the box. - Wouldn't it be better to have a min-with there instead of a fixed width?

**Comment by pcout** [comment]
+1

**Comment by aheinze** [comment]
thanks for your suggestion. this will be adressed for the next major release, to change this now would break too many sites.

**Comment by bgarrant** [comment]
If anyone wants to make the dropdown menu adjust per width of the items within, this override should work.

```
.uk-nav-navbar>li>a {
  white-space: nowrap;
}
.uk-dropdown {
    width: auto;
}
```

**Comment by baer95** [comment]
This still seems to be a problem in Version 3.0.0-beta.35 and I also encountered the same problem with uk-drop which is fixed to `width: 300px`.

The fix by @bgarrant works in both cases.

For the dropdown:

```css
.uk-navbar-dropdown {
    min-width: 200px;
    width: auto;
}
```

For the drop:
```css
.uk-drop {
    min-width: 300px;
    width: auto;
}
```
@aheinze will this be addressed in the release of version 3?
