### ISSUE TITLE
Accordion attribute showfirst not working. 

### ISSUE THREAD

**Issue by mediafish** [uikit/uikit#1158]
Hi, 

I added the accordion component to my site (customer references). http://new.flowerpower-lanzarote.es/en/garden-centre

The accordion shows up and works but not like on your demo site where the first content is open mine - is closed. 
So I added the attribute: <div class="uk-accordion" data-uk-accordion="{showfirst: true}">  the first content stays closed - do you have any explanation for that?

Thanks

**Comment by malles** [comment]
I see the accordion on your site now shows the first content. Did you find out what the problem was?

**Comment by mediafish** [comment]
Make sure you have a link to your script in the head: 
<script src="/templates/yoo_peak/warp/vendor/uikit/js/components/accordion.js"></script>

you don't need to add {showfirst: true}, as this is the default value. The first item will be open in default in the accordion.
<h3 class="uk-accordion-title" >...</h3>

**Comment by malles** [comment]
Loading the script always helps :). Thanks for the feedback.
