### ISSUE TITLE
Offline visibility / hide / disable utility 

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1159]
sometimes in a web app , some functions are disabled while offline this may help

**Comment by malles** [comment]
There are various `muted`, `disabled` and `hidden` classes available. See [text](http://getuikit.com/docs/text.html#text-styles), [button](http://getuikit.com/docs/button.html#usage), [utils](http://getuikit.com/docs/button.html#usage)

**Comment by aheinze** [comment]
@malles thanks!
