### ISSUE TITLE
Pagination navigation

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1163]
Find bug in pagination navigation (prev and next label).
Label render its ok, but:
- on init pagination prev label generate as span instead of tag a. 
- prev label at once has class uk-active
- on label click (prev or next) link a transform to span and can`t repeatedly click
- for navigation label need add class, for example: uk-pagination-prev, uk-pagination-next
- Incorrect jump to the page. For example current page 3, on click next we jump to page 5

``` javascript
<ul class="uk-pagination" data-uk-pagination="{items:80, itemsOnPage:4, currentPage:3}"></ul>
```
- not update current page

``` javascript
...
lblPrev        : '<',
lblNext        : '>'
...
```

**Comment by florianletsch** [comment]
Could you pack this into a CodePen or JSfiddle? Makes it easier to reproduce on the same code. Thanks.

**Comment by Intiligent** [comment]
sorry for the long answer.
http://codepen.io/Intiligent/pen/PqPYmK

**Comment by Intiligent** [comment]
+ add style for uk-pagination-prev, uk-pagination-next.
and would be great instead of text label make icon.
for example: uk-icon-chevron-left and uk-icon-chevron-right

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
