### ISSUE TITLE
Where Is The Version # in Sass?

### ISSUE THREAD

**Issue by bobrocke** [uikit/uikit#1164]
Where is the UIKit version known shown in the Sass source files?

**Comment by saschadube** [comment]
You mean the bower repo with the [https://github.com/uikit/bower-uikit/tree/master/scss](Sass files)?

**Comment by bobrocke** [comment]
Yes. Is there a reference to the version number in the code or comments somewhere?

Bob
-------------------
Robert J. Rockefeller
Richmond Hill, GA
www.bobrockefeller.com

**Comment by saschadube** [comment]
You mean a version number set in a Sass variable? Sorry, there isn't one. But sure, there is the version number in the [bower.json file](https://github.com/uikit/bower-uikit/blob/master/bower.json).

**Comment by bobrocke** [comment]
Perfect! Somehow I missed it there. Sorry.
