### ISSUE TITLE
HTML editing or visual editor for UIkit?

### ISSUE THREAD

**Issue by abushmanov** [uikit/uikit#1167]
Hello! I setup UIkit with Nano3 theme for my Wordpress site.
How can I use it?
Must I generate HTML in UIkit and paste it into Wordpress page or can I use any visual editor for it?﻿

![l0c2q](https://cloud.githubusercontent.com/assets/12035059/7239514/35e35c36-e7b3-11e4-932a-00bd9cf7d68b.jpg)

**Comment by aheinze** [comment]
hi, please visit http://yootheme.com/support , this is not a direct UIkit related issue. thanks!
