### ISSUE TITLE
Feature request: image cropping tool

### ISSUE THREAD

**Issue by acaron** [uikit/uikit#1171]
I would be nice to offer a cropping tool like such: http://deepliquid.com/content/Jcrop.html

It should:
- resize large image;
- can display a preview;
- touch support for mobile;
- min/max size support;
- aspect ratio locking;
- keyboard support for pixel perfect cropping;
- callbacks.

**Comment by malles** [comment]
This might be something for Widgetkit development, but far beyond the scope of UIkit.

**Comment by aheinze** [comment]
thank you for the suggestion, but as @malles said, this is way out the scope of UIkit.
