### ISSUE TITLE
Feature request: colorpicker

### ISSUE THREAD

**Issue by acaron** [uikit/uikit#1172]
A color picker like this: http://mjolnic.com/bootstrap-colorpicker/

With the datepicker and timepicker, a colorpicker is missing!

**Comment by aheinze** [comment]
thank you for the suggestion. we'll consider it for future releases.

**Comment by ikabod** [comment]
+1 for a color picker. All the stuff out there I tried is not working perfectly.

A date picker is probably more urgent, but please do not forget a color picker. I know this is much work, but I guess it should be part of any user interface kit.
