### ISSUE TITLE
Feature request: modal options

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1173]
- draggable modal
- .uk-modal .uk-open without background 
- optionally do-not-close on outside click (only on closer or by function)

So it can be used as regular draggable window.

**Comment by ZeGregg** [comment]
You can make modal draggable with jQueryUI and a piece of JS

    $(“#myModal").draggable({
        handle: ".uk-modal-header",
    });

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We decided to not add this features by default, so you would need to add this manually via jQuery as suggested above. 

Thanks for your understanding,
Your UIkit Team
