### ISSUE TITLE
toggle doesn't fire when page content change

### ISSUE THREAD

**Issue by jjunior187** [uikit/uikit#1174]
toggle component work just fine right after the document is loaded.

the problem is, when I change my page content with an ajax call (without reloading the entire document), it doesn't work anymore.
after taken a look at the toggle component in uikit.js, I found that the click event is bound here 

    this.on("click", function(e) {
                    if ($this.element.is('a[href="#"]')) e.preventDefault();
                    $this.toggle();
    });

It seems that the event is bound right at the document load (when uikit.js is loaded), but it does not listen to any change in the DOM afterwards.

**Comment by malles** [comment]
Place the [`uk-dom-observe` attribute](http://getuikit.com/docs/documentation_javascript.html#dom-observe) on the element with the ajax-loaded data, that should work.

**Comment by jjunior187** [comment]
Just perfect, thank you for the quick answer.

I'll read the doc more carefuly next time ^^
