### ISSUE TITLE
Feature request: mini and regular selects and inputs needed

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1176]
Inputs, selects and buttons (and buttonsets) are often combined.

Uikit offers great ability to change button size, which is really neat.
But no option (class) to change select and input size as well.

uk-button-mini combined with select and input:
![1](https://cloud.githubusercontent.com/assets/8863854/7255278/e4a42438-e850-11e4-8e0c-c67d5d4c214a.png)

uk-button combined with select and input:
![2](https://cloud.githubusercontent.com/assets/8863854/7255323/26d7d3c2-e851-11e4-8a9d-5ed65f876d29.png)

The only one combination that looks ok (but not perfect), is uk-button-small:
![3](https://cloud.githubusercontent.com/assets/8863854/7255345/55484a5c-e851-11e4-9ef9-1ca15c07642e.png)

**Comment by malles** [comment]
+1

**Comment by PixelT** [comment]
http://getuikit.com/docs/form.html#control-modifiers

**Comment by aheinze** [comment]
can I close this issue, or is any question left?

**Comment by malles** [comment]
I guess close it, it looks to fit all fine on the default theme, even the ones without size modifiers. 
![image](https://cloud.githubusercontent.com/assets/5442402/7318179/43540d92-ea89-11e4-8057-60df73a41e7a.png)
http://codepen.io/malles/pen/vOYMwx?editors=100
I struggled with this before, but I guess that was some external CSS messing about.

**Comment by aheinze** [comment]
:+1:
