### ISSUE TITLE
Improvements in slideset & slider

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1177]
In slideset - http://getuikit.com/docs/slideset.html :
- add step for next / prev slidenav - how much items change ( I know there will be a conflict with the dotnav... )

In slider - http://getuikit.com/docs/slider.html
- add filter option

**Comment by PixelT** [comment]
Update:
* add possibility to change the slider by mouse / touch drag

**Comment by aheinze** [comment]
slider dragging is fixed now on touch devices in the current develop branch. we'll consider your suggestions for future releases, thanks.

**Comment by arrowthemes** [comment]
> In slider - http://getuikit.com/docs/slider.html

add filter option
