### ISSUE TITLE
Delay initialization of accordian

### ISSUE THREAD

**Issue by davidsnelling** [uikit/uikit#1183]
I am ajax loading a set of items on page initialization to fill the accordion. No matter where I load the accordion.js, it seems to still be trying to initialize before I insert the items so it can't find them to add to the collection.

How can I delay initialization/boot or run initialization/boot again manually once they are loaded?

**Comment by malles** [comment]
All components can be initialized manually by JS as followed: `var component = UIkit.accordion($('#elementID'), {option: 'value'});`.
Omit the `data-uk-accordion` attribute to prevent the component from booting before you want it to.

**Comment by davidsnelling** [comment]
Thank you, that was simple and a huge help. Working on a large project and
am really happy I found this toolkit!
One more question, how to I subscribe to the expand event? I am going to
load data from a web service to fill the content on expand.

Oh, and thank you so much for the quick response. That is really rare for
most toolkits and makes me happier with my decision.

**Comment by malles** [comment]
No problems,  I need the distractions :)
The best JS-documentation for UIkit is the source-code I'm afraid. It is very good usable as a JS toolkit, but you need to find your way. 
I think you mean the [`toggle.uk.accordion`](https://github.com/uikit/uikit/blob/master/src/js/components/accordion.js#L107) trigger. [docs](http://getuikit.com/docs/accordion.html#javascript-options)
```
var component = UIkit.accordion($('#elementID'), {option: 'value'}).on({
    'toggle.uk.accordion': function (event, active, toggle, content) {
        //do stuff
    }
});
```
would fix that.
Also try the [gitter chat](https://gitter.im/uikit/uikit) and [Google+](https://plus.google.com/u/0/communities/114238665434626719878) for more code help.

**Comment by davidsnelling** [comment]
Excellent, thank you.
Any chance of a plugin for PyCharm like the one for Sublime? Last question
today :)
So happy to be done with Bootstrap!

**Comment by malles** [comment]
Not that I know of I'm afraid... Shouldn't be hard to fix I suppose

**Comment by davidsnelling** [comment]
Was just a hope, is really handy in Sublime with autocomplete for classes,
etc...
Not critical. Thanks!

**Comment by davidsnelling** [comment]
In that event handler, is there a way to get the ID of the Content object?
I am trying to store the ID of the item I want to retrieve and insert into
the content object (for lack of better approach)...

I know I'm just missing something simple, been up for 48 hours trying to
get this done...

$.getJSON("/services/owners", function (data) {
    $.each(data.results, function () {
        $('#owners-list').append(
            $('<div class="uk-accordion-title">' +
                this.people[0].last_name + ', ' +
                this.people[0].first_name +
                '</div><div id="' + this.computed_id + '"
class="uk-accordion-content">test</div>')
        );
    });
    var owners = UIkit.accordion($('#owners-list'), {showfirst: 'true'});

 $('#element').bind('display', function(e) {
        alert( "display has changed to :"+$(this).attr('style') );
    });
 var component = UIkit.accordion($('#owners-list'), {}).on({
        'toggle.uk.accordion': function (event, active, toggle, content) {
        alert(content.id);
     //content.text(ShowOwnerInformation(content.id));
    }});
});

**Comment by davidsnelling** [comment]
ignore the experiment one...

 $('#element').bind('display', function(e) {
        alert( "display has changed to :"+$(this).attr('style') );
    });

**Comment by aheinze** [comment]
@malles thanks! can we close that issue now?

**Comment by davidsnelling** [comment]
Yes. Thank you for your help. Will figure out the rest. You were verity
helpful, thank you!
