### ISSUE TITLE
Table header sticky / fixed

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1185]
Examples:
http://jsfiddle.net/jmosbech/stFcx/
http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html
http://laertejjunior.github.io/freezeheader/

**Comment by ThomasChatenet** [comment]
useful ;)

**Comment by aheinze** [comment]
thank you for your suggestion, we'll discuss this.

**Comment by drodil** [comment]
Any news on this one?

**Comment by marcelgeratsch** [comment]
We need this. Please implement. You cant even use the usual method to fix head, becuase display block destroys the layout.

**Comment by RyanSusana** [comment]
Any news on this? It would be really handy.
