### ISSUE TITLE
IE11 offcanvas background

### ISSUE THREAD

**Issue by MaierGrem** [uikit/uikit#1188]
In component offcanvas IE11 not correctly displays the property RGBA (0,0,0,0.1). Problem div.uk-offcanvas - position fixed. If you do so, it all comes back to normal
```css
.uk-offcanvas:after {
    content: '';
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: rgba(0,0,0,0.1);
}

**Comment by aheinze** [comment]
Sorry but I can't confirm the issue. do you have a custom styled build of UIkit?

**Comment by MaierGrem** [comment]
Well, You can not check or a decision not correct ? I just re-write some of the classes and don't have custom build.

**Comment by aheinze** [comment]
so can you confirm that getuikit.com has the same issue?

**Comment by MaierGrem** [comment]
Yes, one moment!

**Comment by MaierGrem** [comment]
![2015-04-24 22 59 08](https://cloud.githubusercontent.com/assets/9076117/7325033/e9fed3c0-ead4-11e4-85a0-9933508341e1.png)
![2015-04-24 22 59 55](https://cloud.githubusercontent.com/assets/9076117/7325035/ea014ff6-ead4-11e4-92aa-cf1dcfd9c071.png)
![2015-04-24 23 00 09](https://cloud.githubusercontent.com/assets/9076117/7325034/e9ff1f7e-ead4-11e4-8d8c-fe4abbd97d83.png)

**Comment by MaierGrem** [comment]
And with fix
![2015-04-24 23 04 10](https://cloud.githubusercontent.com/assets/9076117/7325125/8788ef40-ead5-11e4-9b8c-4d057aad2602.png)
![2015-04-24 23 04 24](https://cloud.githubusercontent.com/assets/9076117/7325123/878565d2-ead5-11e4-9983-cbaa767c7ba0.png)
![2015-04-24 23 04 36](https://cloud.githubusercontent.com/assets/9076117/7325124/87889f90-ead5-11e4-90ba-d54988bcdcec.png)

**Comment by malles** [comment]
I cannot confirm that. The transparency works fine in IE11 and I can change it to any `rgba(0,0,0,.x)` value.
