### ISSUE TITLE
Multiple Open Modal Boxes

### ISSUE THREAD

**Issue by ahallicks** [uikit/uikit#119]
It would be nice to be able to have more than one modal open at a time. I have a modal that shows information loaded via ajax, and in the response there is a link to open another modal with extra information. The trouble is, the second modal overwrites the first so that when you close it you're taken to the original page, not the first modal.

For example:
1. button opens box1
2. box 1 appears including a link to open box 2
3. click on link and box 2 opens above box 1
4. close box 2 and box 1 still shows
5. close box 1 to return to the page

Thank you!

**Comment by ZeGregg** [comment]
It basically depend on what your are trying to achieve. Saying "multiple modals are leading to bad user experience and are just bad practice" is a quick shortcut.

**Comment by ZeGregg** [comment]
Check Opening multiple dialogs on https://nakupanda.github.io/bootstrap3-dialog/  The second and the third dialog are draggable.
