### ISSUE TITLE
Autocomplete is no more filtering output

### ISSUE THREAD

**Issue by ekaradon** [uikit/uikit#1191]
As you can see below, autocomplete does not filter anymore the output nor highlight matching results.  
![snapshot122](https://cloud.githubusercontent.com/assets/9439390/7328328/e6cb53ea-ead4-11e4-9d43-bd5e97cae15e.png)
I have tested it on firefox (37.0.2) & chrome (42.0.2311.90 (64-bit)).

**Comment by malles** [comment]
It never has :) See #851 #791 , #714, #704
Here some examples for working with autocomplete: http://codepen.io/malles/pen/qEyEZr

**Comment by ekaradon** [comment]
Oh thanks. Not the first one to be wrong. Maybe not the last. Thanks for the answer. :+1:
