### ISSUE TITLE
Feature request: Hamburger menu component 

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1192]
hi; please add hamburger menu component same of windows 10 for phones that easy show menu when click or touch hamburger menu and show menu items with slide form left or right(for RTL) over of current page.

**Comment by malles** [comment]
That would be the [offcanvas component](http://getuikit.com/docs/offcanvas.html), wouldn't it?

**Comment by mojtabakaviani** [comment]
Offcanvas  component push page to right/left but hamburger component show over of page 
and can show menu with icons and titles or just icons

**Comment by mojtabakaviani** [comment]
![responsive-animated](https://cloud.githubusercontent.com/assets/1667525/7509136/81ec1682-f441-11e4-9603-956cb305b8d6.gif)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The new Offcanvas component has now different animations to push, slide, reveal or none. 

Thanks for your understanding,
Your UIkit Team
