### ISSUE TITLE
Even after assigning handles, triggers for modals within sortable objects do not fire.

### ISSUE THREAD

**Issue by christianmagill** [uikit/uikit#1193]
I'm creating a new issue as my previous one was closed in error.
https://github.com/uikit/uikit/issues/1132

When you have modal triggers within a sortable component they don't fire, even when assigning a handle class for your sortable component.

Here is an example provided by @malles of the same issue with lightbox http://codepen.io/malles/pen/jEvooV

**Comment by malles** [comment]
The codepen works now on the newer versions of UIkit.
