### ISSUE TITLE
Tooltips position is not correct in SVG elements on IE11

### ISSUE THREAD

**Issue by Yves57** [uikit/uikit#1194]
Tooltips are always on the screen left in SVG elements in IE11.
The expression `this.element[0].offsetWidth` returns `undefined`. Of course there is the same problem for the `offsetHeight`.
But the following code fixes the bug :

```
var eloffsetwidth = this.element[0].offsetWidth;
if (!eloffsetwidth) {
   eloffsetwidth = this.element[0].getBoundingClientRect().width;
}
var eloffsetheight = this.element[0].offsetHeight;
if (!eloffsetheight) {
   eloffsetheight = this.element[0].getBoundingClientRect().height;
}
....
pos = UI.$.extend({}, this.element.offset(), { width: eloffsetwidth, height: eloffsetheight }),
```

**Comment by fudanglp** [comment]
Same issue here.
Seems that IE11 do not support svg getBoundingClientRect() correctly.
Fuck M$

**Comment by malles** [comment]
Also see #1184

**Comment by worblehat** [comment]
I have the same issue with Firefox 43.0.1.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
