### ISSUE TITLE
Need help with Source ordering

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1195]
Hello everyone,

I have 4 columns.

uk-width-medium-2-10
Navigation

uk-width-medium-1-10
Pictures 1

uk-width-medium-6-10
Main

uk-width-medium-1-10
Pictures 2

With max-width: 959px the main column shall go under the navigation,
so that Picture 1 and Picture 2 stand one below the other.

I tried it with push and pull but it destroys me the complete layout.

I am very grateful for any help!

Hans

**Comment by PixelT** [comment]
Push and pull works only with medium classes.
http://getuikit.com/docs/grid.html#source-ordering

**Comment by malles** [comment]
`uk-push` and `uk-pull` do the job:
```
<div class="uk-container uk-container-center">
  <div class="uk-grid">
    <div class="uk-width-medium-2-10">
      Navigation
    </div>
    <div class="uk-width-medium-6-10 uk-push-1-10">
      Main
    </div>
    <div class="uk-width-medium-1-10 uk-pull-6-10">
      Picture 1
    </div>
    <div class="uk-width-medium-1-10">
      Picture 2
    </div>
  </div>
</div>
```
See http://codepen.io/malles/pen/waBgEK?editors=101

There might be a better way using the flex-ordering, but I haven't looked into that really.

**Comment by malles** [comment]
Hmmmm... I've been [fiddling with the flex ordering] (http://codepen.io/malles/pen/waBgEK/?editors=100) and it seems hard to get the same result using flex, unless I'm doing it all wrong.

@saschadube Can you shed some light on the flex item-ordering? If `uk-pull` and `uk-push` might become deprecated, how would one order a column that is not first or last? Nesting the grids like I did messes up the column-widths...

**Comment by saschadube** [comment]
@malles Everything looks alright for me in your example. You can't get the exact same result with the flex classes like you did with the push/pull classes. But I think the first example is very unlikely. At least we never had such a case :grimacing:

**Comment by hansnolte** [comment]
@PixelT 
As you can read in my first posting, I used medium classes.

@malles 
Fantastic!
It works great.

Many thhanks
Hans
