### ISSUE TITLE
Components list in alphabetical order

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1196]
I suggest to order the items in components in alphabetical order.
The menu:

Accordion
Autocomplete
Datepicker
HTML editor
Lightbox
Nestable
Notify
Parallax
Search
Slider
Slideset
Slideshow
Sortable
Sticky
Timepicker
Tooltip
Upload

is better & more readable than current: 

Lightbox
Autocomplete
Datepicker
HTML editor
Slider
Slideset
Slideshow
Parallax
Accordion
Notify
Search
Nestable
Sortable
Sticky
Timepicker
Tooltip
Upload

The same applies to other sections.

**Comment by MacWordPress** [comment]
+1

**Comment by malles** [comment]
I agree to this, just was staring a minute to find the Accordion I expected on top..
I don't think your pull-request covers it, it will have to be changed on every page of the components section. I think this is easier done as an internal refactoring job.

**Comment by Pandahisham** [comment]
+1

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has been changed within the new UIkit3 docs. 

Thanks for your understanding,
Your UIkit Team
