### ISSUE TITLE
Bug: modal freezes window, when no modal holder present

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1199]
When trying to call modal, that should fit to non-existent div, overflow:hidden css sets to body and nothing else.

```javascript
var modal = UIkit.modal("#no-such-element-on-page");
                modal.show();
```

Same happens clicking on button with target for non-existent div
```html
<div class="uk-button data-uk-modal="{target:'#no-such-element-on-page'}" >Button</div>
```

Same happens when target element is removed from dom while modal is open.

This class is never removed in these cases:
![1](https://cloud.githubusercontent.com/assets/8863854/7352251/2710d8b8-ed13-11e4-8c9d-3d145d0adb15.png)

**Comment by aheinze** [comment]
thanks!
