### ISSUE TITLE
data-uk-grid-match + data-uk-grid-margin - stop worked?

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1200]
In all my sites when I use in grid
```data-uk-grid-match="{target:'.uk-panel'}" + data-uk-grid-margin```
the margin between each row stop working...
met someone with something like that? or can check it / confirm?

**Comment by PixelT** [comment]
Simple use data-uk-grid-margin also doesn't work...

**Comment by saschadube** [comment]
It's working in the [http://getuikit.com/tests/core/grid.html](tests). Please provide a [http://jsfiddle.com](JSfiddle).
