### ISSUE TITLE
Feature request: navbar - vertical nav items on mobile

### ISSUE THREAD

**Issue by rolandtoth** [uikit/uikit#1201]
I couldn't find anything that could turn a horizontal (nav) menu to a vertical menu on smaller screen sizes. 

For example, I found no way to turn a footer menu like this on desktop size:
About Us ● Terms ● Privacy ● Contact

to this, using built-in classes only:
About Us
Terms
Privacy
Contact

Here is a quick visual mockup:
![Image footer nav menu](http://rolandtoth.hu/pic/uikit-footer-menu.png)

Am I missing something? If it's unavailable, I would love to see such a feature in a future release.

**Comment by saschadube** [comment]
The currently preferred solution is to hide the navbar and provide an offcanvas menu with toggler instead.

**Comment by rolandtoth** [comment]
Yes I know that, thanks. But isn't it strange having multiple offcanvas menu for top and bottom menus?

As a workaround, using helper classes like "uk-display-small-inline-block"  and "uk-display-medium-inline" (etc), so one could easily solve this. Unfortunately no such classes are available.
