### ISSUE TITLE
truncate options

### ISSUE THREAD

**Issue by pcout** [uikit/uikit#1205]
It should be possible to define the number of lines when truncating.
Can it be done ?

Thanks

**Comment by aheinze** [comment]
truncate what?

**Comment by malles** [comment]
I think the effect he means is for `uk-text-truncate` to only truncate after eg 3 lines:
```
Lorem ipsum dolor sit amet, consetetur er
sadipscing elitr, sed diam nonumy eirmod 
tempor invidunt. Lorem ipsum dolor alk ...
```
But I don't think that is even possible in css...

**Comment by zslabs** [comment]
@pcout The closest thing I can think of would be using something like [Succinct](http://mikeking.io/succinct/)

**Comment by pcout** [comment]
Succinct only truncates by number of chars.
I mean like this: [Fewlines](http://sergeir82.github.io/fewlines/), or even this plugin: [Threedots](http://tpgblog.com/2009/12/21/threedots-the-jquery-ellipsis-plugin/)

With these you can truncate by number of lines.

Any ideas to implement this on UIKit ?

Thanks

**Comment by aheinze** [comment]
Thank you for the suggestion but I don't see a need to implement this in UIkit. Please use existing js solutions if ```uk-text-truncate``` is not enough.

**Comment by pcout** [comment]
You don´t see the need to truncate more than 1 line in UIkit ? Really ?

**Comment by zslabs** [comment]
@pcout Think you'd get the same answer from just about every other CSS/JS framework out there, so yes. There's plenty of alternatives that UIkit (or any other framework) would just be reinventing the wheel for.

**Comment by pcout** [comment]
I see what you mean, but i really don't agree. You have plenty of alternatives to several elements and components of UIkit like tooltips, modals, sliders, datepickers, and many many others. Having an option to truncate as many lines a user wants just seems natural and thus avoiding loading other library.

**Comment by zslabs** [comment]
I realize it may seem like a very common use-case since you may be trying to use something like that in a current project perhaps, but it is a rather specialized case. I've never had the need for this myself as the programming language can handle truncating this for me before the final output. Since this issue is closed there's no need to beat this into the ground anymore.

**Comment by pcout** [comment]
ok. thanks anyway.
