### ISSUE TITLE
Abstract class names and selectors as options in js

### ISSUE THREAD

**Issue by timkelty** [uikit/uikit#1206]
This is a really nice thing Semantic UI does.
It allows a developer to use JS components with their own CSS/HTML naming conventions if desired.

Example:
See **Module → Dom Settings** http://semantic-ui.com/modules/sidebar.html#/settings

**Comment by malles** [comment]
All UIkit javascript components have their options, most of them are in the docs.
You can override them [like so](http://getuikit.com/docs/documentation_javascript.html#js-override), set them in the `data` attribute, or use JS to initialize the elements.

**Comment by timkelty** [comment]
I'm not just talking about the initialization, but the actual selectors used within the component.
E.g. https://github.com/uikit/uikit/blob/master/src/js/core/offcanvas.js#L49

Classes are used directly `$body.removeClass("uk-offcanvas-page")`, but it would be nice if any selectors used in components were overridable as settings.

This really lets users take full control if they want to, and swap out any CSS framework they might already be using.

Example:
```
var opts = {
  className: {
     page: uk-offcanvas-page,
     active: uk-active
  },
  selector: {
    panel   : '.uk-offcanvas',
    body : 'body',
    pusher  : '.pusher',
    sidebar : '.ui.sidebar'
 }
}
...
var $body = $(opts.selector.body);
$body.removeClass(opts.className.page)
```

**Comment by malles** [comment]
I see what you mean. Already done in eg sortable: https://github.com/uikit/uikit/blob/master/src/js/components/sortable.js#L41
I think it will work its way in the code.

**Comment by timkelty** [comment]
Great to hear, thanks!

**Comment by aheinze** [comment]
thanks for the suggestion. we'll consider it for UIkit 3.0
