### ISSUE TITLE
Switcher effect "Scale" doesn't work

### ISSUE THREAD

**Issue by udatabox** [uikit/uikit#1207]
I was checking the effects of Switcher into the website and got the bug is not whether it is for Google Chrome Browser jQuery or something but gets stuck without making any effect nor fulfills the function of switcher.

sry or my badly english.

![screenshot_2](https://cloud.githubusercontent.com/assets/7569847/7380592/110aa310-edfd-11e4-8840-15d9a28087ab.png)

**Comment by malles** [comment]
Most of them work fine, only `Scale` is not working. I've been looking at it for quit some time now, and can't figure out why not. Tests work fine, and all works fine [in the codepen](http://codepen.io/malles/pen/waBgEK?editors=100)

**Comment by malles** [comment]
Okay, I've been fighting with this for some time now, and I officially give up. :confounded:
The scale switcher fails at https://github.com/uikit/uikit/blob/master/src/js/core/switcher.js#L170, the promise is not returned, `.then()` i snot executed, nor is the [release of the animation](https://github.com/uikit/uikit/blob/master/src/js/core/switcher.js#L264). The event [`UI.support.animation.end`](https://github.com/uikit/uikit/blob/master/src/js/core/switcher.js#L285) is never fired.
Only on the scale switcher. I switched the markups, order of examples, animations, even element-ids, nothing helps.
Weirdest thing is, tests and my codepen work fine. Only on the docs' markup this fails.

**Comment by malles** [comment]
Of Course I didn't give up... Just took a bit longer.
It's not in the switcher or tabs. Nor in any javascript. It's a typo in the docs' css! :smirk:
![image](https://cloud.githubusercontent.com/assets/5442402/7400010/182fed5e-eeba-11e4-817c-dc8618c5f973.png)
I can't make a PR for the docs' less, so it will have to be fixed in Hamburg.

**Comment by aheinze** [comment]
this should be fixed with the upcoming release. thanks!
