### ISSUE TITLE
Feature request: Color Picker (not with hex values)

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#1211]
Most color picker offer the possibility to select a color and then you get the value.

What I want to suggest here as feature is more simple.

Example: Drop-Down list where different colors are available to select (a simple selector where the entries have different background colors).

Demo: http://bootstrap-colorselector.flaute.com/

```
A colorselector for Twitter Bootstrap which lets you select a color from a predefined set of colors only.

In contrast to many other colorpickers found on Github this one is reduced to a predefined set of colors. This is why it is called "colorselector" rather than "colorpicker".
```

**Comment by uikid** [comment]
This is also a nice way to give some color options:

http://maxmackie.github.io/jquery.swatches/

**Comment by zslabs** [comment]
Could see something like that working well with a generic pop-over component

**Comment by mojtabakaviani** [comment]
+1

**Comment by philoest** [comment]
The problem with this is, that the functionality seen above is, as we see it, not enough for the common use. But a fully integrated color picker is quite a heavy project. So here we would recommend to use other JS projects that are dedicated to this component. Here you could take a look into [spectrum](http://bgrins.github.io/spectrum/) which we often use.
