### ISSUE TITLE
Undefined variable: "$text-primary-color" 

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1216]
hi when i want to compile uikit.sass i get this error "  sass/framework.scss (Line 415 of sass/Uikit/uikit-variables.scss: Undefined variable: "$text-primary-color".) "

please some body help me.

**Comment by edmedo** [comment]
Having the same problem since the last release. The simplest way to hack round it for now is to define `$text-primary-color` prior to parsing the uikit-variables.scss file.

**Comment by miladmeidanshahi** [comment]
When this problem solve ? 
which update will fix this issue ?

**Comment by juicyfish** [comment]
I am getting `Sass Compilation Failed!: unbound variable $text-primary-color`. As @edmedo points out,  define this in your custom sass, then sass will compile.

**Comment by CinKon** [comment]
Still in current release 2.20.3...

**Comment by miladmeidanshahi** [comment]
this problem does not fix yet still in current version

**Comment by malles** [comment]
Issue is picked up in #1308
