### ISSUE TITLE
data-uk-grid-margin

### ISSUE THREAD

**Issue by udoewich** [uikit/uikit#122]
First of all, thanks for UIKit - it's a pleasure to work with!

Now to my problem:

Is it possible to get a grid to re-format the margins after the page has already been rendered?  I'm dynamically adding and removing items from a grid that is set up as in your "Wrap multiple rows" example, and would like to use JavaScript to correct the margins after these changes are made.

Thanks,
Ulrich

**Comment by john052** [comment]
Is this fix implemented in UIkit 2.17?

My dynamically added grid elements don't have the correct margins applied.
I still have to manually update the margins using:
```php
var sm = grid.data('stack-margin');
sm.columns = grid.children();
sm.process();
```

**Comment by malles** [comment]
put a `data-uk-observe` attribute in your parent element, and you should be good to go. http://getuikit.com/docs/documentation_javascript.html#dom-observe

**Comment by john052** [comment]
@malles Thank you. That does the trick.
