### ISSUE TITLE
Manual Init nestable

### ISSUE THREAD

**Issue by ntanas72** [uikit/uikit#1220]
I am using uikit nestable and it's working fine.

My problem is that while the nestable lists are init when the page is loaded, if use JavaScript to dynamic create a new list I don't know how to init the uikit nestable for this new list.

Init element manually from the manual http://getuikit.com/docs/nestable.html

var nestable = UIkit.nestable(element, { /* options */ });
but its not working for me.

**Comment by malles** [comment]
That is the way it is supposed to work. Can you create a codepen or live example of the code you are trying?

**Comment by ntanas72** [comment]
Here is the codepen http://codepen.io/anon/pen/OVVzJP

I have 2 lists.The first is auto init form the nestable.js (and drag n drop is working fine)
When you click addList i append a new list that i am trying to manual init but its not working

Please advise me to fix this issue

Thanks

**Comment by malles** [comment]
Include your element like this `$('#manualInitNested')`, and it works fine http://codepen.io/malles/pen/OVVzKm?editors=101

**Comment by ntanas72** [comment]
Yes, its working fine.

Does this mean that i can init with an id and not with a class?

Because in my script i will create dynamically a lot of lists, so i need to know if i can init with a class or i have to create unique ids for each new list i append.

Thanks for your quick reply.

**Comment by malles** [comment]
I was wondering that myself. On the other hand, it's logical that one instance of the nestable can handle one ul. And indeed, [only the first element of the selector is used](https://github.com/uikit/uikit/blob/develop/src/js/components/sortable.js#L119).
If you init the jQuery object on the template you create, you can pass that. [See fiddle](http://codepen.io/malles/pen/OVVzKm?editors=101)

**Comment by ntanas72** [comment]
Very clean explanation and very Interesting approach.

Thanks for your reply
