### ISSUE TITLE
Dynamic Grid doesn't update when using Toggle

### ISSUE THREAD

**Issue by staticwave** [uikit/uikit#1224]
I am using Dynamic Grid with panels that each have a div inside that is hidden by default and expands using Toggle but when the div is toggled the panel below doesn't move down to show the expanded panel. If I click the 'All' tab after it's expanded, everything shifts and looks as it should.

![toggle-off](https://cloud.githubusercontent.com/assets/2489765/7439239/92ade470-f039-11e4-85d3-e55a978e3c67.JPG)

![toggle-on](https://cloud.githubusercontent.com/assets/2489765/7439241/a315a9d8-f039-11e4-8e67-fdc7eb54163e.JPG)

**Comment by aheinze** [comment]
please try to add ```data-uk-check-display``` to the grid root element  - http://getuikit.com/docs/documentation_javascript.html#data-check-display

**Comment by staticwave** [comment]
Thanks, I could not get that to work either. When implemented, if I expand one 'card' the others still do not adjust, but if I expand a second 'card' and then close it or the first card, then the items adjust around the remaining expanded 'card'. Hope that makes sense.

**Comment by malles** [comment]
Try `UIkit.$html.trigger('changed.uk.dom');` after you toggled the div. That should force the grid to update. See https://github.com/uikit/uikit/issues/1348
