### ISSUE TITLE
Both 'Scale up' animation examples in the docs do not seem to work

### ISSUE THREAD

**Issue by 526avijitgupta** [uikit/uikit#1226]
Tested on Ubuntu 14.04 in both google chrome as well as Mozilla Firefox.
There are 2 examples of 'scale up' animation styles, and both of them are non functional.

http://getuikit.com/docs/animation.html

**Comment by malles** [comment]
Yeah, it's a bug in the docs. Should work fine in the releases. See #1207

**Comment by aheinze** [comment]
thanks for the hint. this will be fixed with the upcoming release.
