### ISSUE TITLE
Animations not working in Chrome

### ISSUE THREAD

**Issue by Aesine** [uikit/uikit#1227]
The animations from http://getuikit.com/docs/animation.html don't work in Chrome (Version 41.0.2272.118 m on Windows 8.1). I think it's because I have a touch-screen laptop. When clicking by mouse, nothing happens. When touching the screen, everything is fine.

**Comment by Aesine** [comment]
The same issue was solved here : https://github.com/gantry/gantry5/issues/39

**Comment by nstaeger** [comment]
Thanks you. Fixed by 2413b0ac0088c7e06c2db1b4139591876db8ff18.
