### ISSUE TITLE
Datepicker Component: minDate/maxDate -- Disable selection

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1230]
Currently setting `minDate` or `maxDate` on the datepicker component doesn't seem to negate the actual selection of a date that is not within those bounds http://codepen.io/zslabs/pen/rVONje Am I mis-understanding the use of that? Thanks as always.

**Comment by uikid** [comment]
you forgot to close the minDate value.

```html
      <input type="" data-uk-datepicker="{format:'DD.MM.YYYY', minDate:'04.06.2015'}">
```

working example: http://codepen.io/anon/pen/oXbQRG

**Comment by zslabs** [comment]
Thanks, appreciate it!
