### ISSUE TITLE
Opening more than one modal window

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1232]
Target/purpose: do not close the open modal at the opening of another modal.

if you want open modal from another modal now it impossible.
Now if open another modal, then closed opened modal.

http://codepen.io/Intiligent/pen/jPbPyK - issue variant
my propose to fix it.
on my opinion nothing not broke.
http://codepen.io/Intiligent/pen/mJeJVr - work variant

**Comment by aheinze** [comment]
this is implemented in the current dev version, just pass ```modal:false``` as option

**Comment by Intiligent** [comment]
oh, it's great. i am waiting new update
