### ISSUE TITLE
Tooltip text not updated after changing title text

### ISSUE THREAD

**Issue by goorpy** [uikit/uikit#1233]
**Setup:** Element is created with `data-uk-tooltip`, `title='foo'` and `data-cached-title='foo'` attributes assigned. User hovers over element, and initial "foo" tooltip appears as expected.

**Action:** Via JS or devtools, `title` and `data-cached-title` are changed to have value `='bar'`

**Expected result:** When user hovers over Element again, tooltip will appear with text "bar" inside, respecting the change title attribute.

**Actual result:** When user hovers over Element again, tooltip appears with text "foo" still inside, ignoring the changed title attribute.

This still happens in the presence of two elements with tooltips where I can see the HTML contents of the UK Tooltip element being updated/refreshed to switch between the two. However when it switches the contents back to those for the first Element, the text remains as the old "foo" text.

CodePen example with jq work around: http://codepen.io/goorpy/pen/EjVdYO
First button tooltip does not update. Second button does because I wipe out the `cached-title` and `tooltip` `data()` entries with `$.removeData()`.

My proposed change to the tooltip component code to handle this automatically: http://codepen.io/goorpy/pen/mJezde (see lines 55 - 59)

**Description of patch:** when we get a `mouseenter` event and the `ele.data("tooltip")` already exists, we should check to make sure the `ele.attr("data-cached-title")` still matches `ele.data("cached-title")' before proceeding. If there is a mismatch, destroy the existing tooltip data and let it get rebuilt.

*Note:* In my production code, I'm modifying `title` & `data-cached-title` via AngularJS templating, but the result is the same `attr` change without a matching `data` change and the patch works just as well.

**Comment by goorpy** [comment]
My pull request with the corresponding patch applied: https://github.com/uikit/uikit/pull/1234

**Comment by goorpy** [comment]
Pull Request to develop branch, per @malles request: https://github.com/uikit/uikit/pull/1236
Sorry about PR to wrong branch.

**Comment by aheinze** [comment]
this is fixed in the current dev branch.
