### ISSUE TITLE
Feature request: Responsive Panel component

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1235]
Responsive panel same other panel or side bar but when resize page or on the table or mobile screen access panel with hamburger menu.
![responsive-animated](https://cloud.githubusercontent.com/assets/1667525/7509206/5841ea4a-f442-11e4-9e66-99adc100de82.gif)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. I think this can be achieved with the new animations of the offcanvas in UIkit3. 

Thanks for your understanding,
Your UIkit Team
