### ISSUE TITLE
Feature request: Slideshow whith clickable  thumbnail slider + controlNav pattern

### ISSUE THREAD

**Issue by averuga** [uikit/uikit#1237]
Hello friends! Please, add to the UIkit Slideshow new effect whith clickable  thumbnail slider + controlNav pattern like this - http://taverina.ru/svadebnaya-fotosessiya-na-kipre.html 
This is a very popular and friendly effect. 
Another example: FlexSlider 2 http://flexslider.woothemes.com/thumbnail-slider.html
Thank you! It will be waiting! You are a big rock!

**Comment by malles** [comment]
This van be done already by combining the slidenav/slider with a switcher.
It would be nice to have a good example of this, indeed.

**Comment by averuga** [comment]
Matthijs, if I ve  translated correctly, it can already be done? I'm not very good at English, sorry. Is it possible to add a sample implementation in the documentation here http://getuikit.com/docs/slideshow.html ?

**Comment by malles** [comment]
It works almost with default UIkit code: http://codepen.io/malles/pen/qdOvJP
Problem is that the copies of the images in the slider have the wrong index. Adding a data attribute and a small fix to the switcher code makes it work.

**Comment by averuga** [comment]
Thank you very much!

**Comment by malles** [comment]
Suddenly seeing you refer to the slideshow. That of course is much better, and works out of the box!
http://codepen.io/malles/pen/bdVJXg
So forget the switcher :)

**Comment by malles** [comment]
And works with slider as well: codepen.io/malles/pen/qdOvJP

**Comment by averuga** [comment]
Big Thanks! 
It seems to be a similar opportunity was in Widgetkit, if I'm not mistaken. 
http://yootheme.com/demo/widgetkit/joomla/index.php/home/gallery
Preview above or below of the target image. Right?

**Comment by malles** [comment]
Right. Widgetkit is made with and by UIkit (YOOtheme), so it is all the same in essence.

**Comment by florianletsch** [comment]
Great answer malles!

**Comment by malles** [comment]
@florianletsch No probs, I'll publish it to G+ as well. You can make the video :wink:

**Comment by PixelT** [comment]
@malles great example :)
I think that can be very useful to put this example as a demo on http://getuikit.com/docs/thumbnav.html

**Comment by averuga** [comment]
@PixelT I will support you, it's great to complement the documentation.

**Comment by aheinze** [comment]
thanks @malles !

**Comment by raganello1** [comment]
Hi there, I am trying to use http://codepen.io/malles/pen/qdOvJP on joomla web site withno success.
uikit is correctly installed, I did copy js css and html but I only see thumbnail and no slider image, I tried everything, any suggestion? thanks!

**Comment by Lutidza** [comment]
Hi!
http://codepen.io/malles/pen/qdOvJP
When I switch the main image, thumbnails remain in place. How to make that the focus fell on the active thumbnail ?
