### ISSUE TITLE
Navbar does not open on hover (UIKit 2.20.3) in Chrome and IE

### ISSUE THREAD

**Issue by gpb61** [uikit/uikit#1238]
Hi. I noticed that on Chrome and IE (Win 8.1), the Navbar component (UIKit 2.20.3) does not opens the submenu by hovering the parent (while it opens it on click). On the contrary on Mozilla it still works.
Looks like it is something related to the uikit.js, because switching back to previous js versions the problem disappear.﻿

**Comment by nstaeger** [comment]
Hey there,

may it be, that your device supports Touch? The "hover" behavior is disabled, if UIkit [detected touch support](http://getuikit.com/tests/core/touch.html) on the device.

Best,
Nicolai

**Comment by gpb61** [comment]
Yes, that's correct. I am working on a desktop PC with touchscreen display. However, I am wondering on which line of the js code I can switch back to the hover behaviour (enabling it) since I am using this PC for website presentations to the customers.
Thanks a lot and keep on going with your great work
Gianpaolo

**Comment by malles** [comment]
You can override the value of the touch-detector I guess. It would be kind of a hack though..
```
UIkit.on('beforeready.uk.dom', function () {
    UIkit.support.touch = false;
});
```

**Comment by gpb61** [comment]
Yes, it is indeed a hack, but I tried and it works. I will use it for presentational purposes only, while on the production website it will be the non-hacked one.
Thanks a lot for all the support!
