### ISSUE TITLE
Each click on Tab Menus in Dropdowns closes the dropdown

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1240]
Hello,
is it possible to prevent a justified (or any) dropdown menu from closing, if theres a tab menu inside?
Each click on one of the tabs lets the dropdown disappear.

The Accordion Menu on the other hand, which is in the same dropdown, works perfect, without closing the dropdown menu.

**Comment by aheinze** [comment]
it is possible by adding ```.js-uk-prevent``` to the anchor element e.g. ```<a href="#" class="js-uk-prevent">My Link</a>```
