### ISSUE TITLE
Upload not working in IE9

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#1241]
Hi,

it seems, that the upload component is not working in IE9. I used the example from the docs:
http://getuikit.com/docs/upload.html

In IE10+, Firefox, Opera and Chrome, it works fine. In IE9, nothing happens, when I drop a file in the marked area or when I choose a file via file browser. No error or warning is thrown. Pretty strange.

A standard upload form works without any issues.
```html
<form action="file-upload.jsp" method="post" enctype="multipart/form-data">
  <input name="Datei" type="file" accept="text/*" style="width: 100%;"><br />
  <button type="submit" class="uk-margin-small-top">Upload</button>
</form>
```
Any ideas, what the problem could be?

**Comment by christianmagill** [comment]
IE9 does not support dataTransfer.files which may be the reason for this http://caniuse.com/#feat=dragndrop

**Comment by stebeg** [comment]
That explains, why it's not working when I drop a file in the marked area. But why doesn't it work by selecting a file with the file browser?

```html
<div id="upload-drop" class="uk-placeholder">
    Info text... <a class="uk-form-file">Select a file<input id="upload-select" type="file"></a>.
</div>
```

```javascript
var select = UIkit.uploadSelect($("#upload-select"), settings),
      drop   = UIkit.uploadDrop($("#upload-drop"), settings);
```
I thought, UIkit.uploadSelect doesn't use e.dataTransfer.files, so it could be used as a fallback. But It's not working either.

**Comment by aheinze** [comment]
the upload component uses the xhr2 transfer component which is only available for IE >= 10, sorry.

**Comment by stebeg** [comment]
No problem. But it would be nice, if this limitation would be documented on the upload doc page.
