### ISSUE TITLE
"Get CSS" customizer button doesn't work on Safari

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1242]
"Get CSS" button on http://getuikit.com/docs/customizer.html doesn't work on Safari.
No CSS file is downloaded.
On Chrome the button works correctly.

**Comment by robertotremonti** [comment]
The problem seems related to a failed HREF assignment in `downloadCSS` JS function.

**Comment by florianletsch** [comment]
You're right. Browser support for the `download` attribute doesn't include Safari or IE. Guess we'll need to find another solution. http://caniuse.com/#feat=download
