### ISSUE TITLE
horizontal rule doesn't exist anymore but is still in the docs? (not even showing there)

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#1246]
take a look:

http://getuikit.com/docs/base.html

the horizontal rule is not visible (no height or whatever the problem is).

why did 2.20.3 get so cracked up?!

**Comment by uikid** [comment]
I found out that this is only in the minifed version the case!

version: 2.20.3
uikit.gradient.css works (there is 1 hr css selector)
uikit.gradient.min.css not visible (there are 2 hr css selectors, one only with the border-top that doesn't get applied)

**Comment by uikid** [comment]
I think I know why:
in the minified version of the gradient theme (probably the other theme too) the hr border-top definition is not combined in one hr css selector.
the second hr css selector has border: 0 in it, which overrides the first definition.

so there is something wrong with your minification process here, because in the unminified version everything is correct!

**Comment by aheinze** [comment]
thanks for reporting! this is already fixed in the dev branche.
