### ISSUE TITLE
datepicker doesn't close when using tab key

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#1247]
version: 2.20.3

the datepicker only closes when clicking somewhere else, not when you're using the tabulator key on the keyboard.

example:

input
input with datepicker
input <- when hitting tab from the previous field the datepicker won't hide, only a mouseclick will hide it (doesn't matter where you click)

**Comment by uikid** [comment]
I created this codepen example to demonstrate the issue:

http://codepen.io/anon/pen/waWWdP

**Comment by malles** [comment]
I see your point. When skipping through a form with tab, the datepicker stays open.
Problem is that the datepicker can't be hidden on the `blur` of the input when navigating away. The input also blurs when interacting with the datepicker itself, and it would hide the picker just before you click it :).

**Comment by DanielStuttgart** [comment]
This limits the possible resolutions. For e.g. a function that closes the datepicker could be called when a specific input is selected.

**Comment by malles** [comment]
This issue should be solved by this commit. https://github.com/uikit/uikit/commit/c52eeaf4531b0dde2e249e1c625b5aa92f39d849
It was referenced to #1342, similar to this one
