### ISSUE TITLE
Filter by input value - how?

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1248]
How dynamic filter in [Dynamic Grid](http://getuikit.com/docs/grid-js.html) by type value in input?
Sometimes ago I [request this feature](https://github.com/uikit/uikit/issues/1085)
In commits I see that are already done - https://github.com/uikit/uikit/commit/e4349bbdbcd478c0b2e4e6c17b216e5b1721d8f0
But how to use it? In documentation I don't see any example, and my knowledge about JS is in basic level ;)
Could someone provide me some demos how to use it?
I have an input + dynamic grid - what next?

**Comment by rolandtoth** [comment]
For example (untested):

```javascript
// initialize
var myGrid = UIkit.grid($('#mySelector'));

$("#myTextbox").keyup(function(){

	// get user entered text
    var textinput = $('#myTextbox').val();

	// filter grid items
    myGrid.filter(textinput);
});
```

**Comment by PixelT** [comment]
@rolandtoth work great, but if I want to filtered by each char - It's possible?
I write 'p' then display all elements which have p char in the data-uk-filter

**Comment by rolandtoth** [comment]
I don't see a way it is possible currently. As a workaround you could build an array of all your available filters and check user entered text against it. Then filter the grid with the matched elements.

But perhaps someone can suggest a smarter solution.

**Comment by malles** [comment]
@rolandtoth Seems to be the only way indeed, and a good workaround.

**Comment by Pandahisham** [comment]
+1 @rolandtoth

**Comment by aheinze** [comment]
this is a special use case, thanks @rolandtoth for providing a custom solution.

**Comment by dimitrilongo** [comment]
@PixelT I have a solution using https://github.com/DeuxHuitHuit/quicksearch

here's the fiddle for people who are interested
http://jsfiddle.net/dimitrilongo/0mt9pu78/

in the Javascript if you remove line 30 ```myGrid.filter('show');```
All div unmatch with the input search string, i set an opacity, it coud be used also like this, but i prefer with @rolandtoth  solution ```myGrid.filter('show');```
Please feel free to correct if there is mistake in my code (for example when you enter a string and select a filter) or improve it.

Thanks

**Comment by triooleg** [comment]
Filter only world
https://jsfiddle.net/triooleg/0aawfd5s/
