### ISSUE TITLE
 v2.17.0-2.20.3 : "uk-responsive-width" class problem if added dynamically with jquery

### ISSUE THREAD

**Issue by Wizard13** [uikit/uikit#1250]
Hi!
I'm using youtube iframes with dimensions 640x360 and up until uikit v2.16.2 I would add the uk-responsive-width class with jquery like the following and it would work:
```javascript
$(function() {
	$('iframe[src*="www.youtube.com"],iframe[src*="player.vimeo.com"]').each(function() {
		$(this).addClass('uk-responsive-width');
	});
});
```
However, with v2.17.0 and later, it is not working any more. Instead of 640x360, the iframe becomes 640x115. It works correctly however, if class="uk-responsive-width" is written inside iframe tag.
I have created a temporary test page: http://users.sch.gr/vandr/uikit.php

**Comment by aheinze** [comment]
this will be possible with the upcoming UIkit release:

```
$(function() {
    $('iframe[src*="www.youtube.com"],iframe[src*="player.vimeo.com"]').each(function() {
        UIkit.responsiveElement(this);
    });
});
```

**Comment by Wizard13** [comment]
Even with v2.21.0 and UIkit.responsiveElement(this), it doesn't work correctly (see http://users.sch.gr/vandr/uikit.php)
