### ISSUE TITLE
TypeError: this.element is null uikit-983b8e2d.js:3:11582

### ISSUE THREAD

**Issue by ispanets** [uikit/uikit#1251]
Hi!

I am unable to make uikit work. I get the following error in all of my pages (gutenberginstitute.com)

TypeError: this.element is null uikit-983b8e2d.js:3:11582

Here is the call stack:

.init@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:3:11583
n.component/o@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:5826
n.component/this[t]@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:7123
.init/<@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:15:1909
.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:374:14jQuery.prototype.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:139:10.init@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:15:1026
n.component/o@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:5826
n.component/this[t]@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:7123
.boot/</<@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:15:537
.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:374:14jQuery.prototype.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:139:10.boot/<@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:15:451@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:8289
@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:8254
jQuery.event.dispatch@http://gutenberginstitute.com/media/jui/js/jquery.min.js:4434:15jQuery.event.add/elemData.handle@http://gutenberginstitute.com/media/jui/js/jquery.min.js:4121:6jQuery.event.trigger@http://gutenberginstitute.com/media/jui/js/jquery.min.js:4350:5
e.event.trigger@http://gutenberginstitute.com/media/jui/js/jquery-migrate.min.js:2:6730
.trigger/<@http://gutenberginstitute.com/media/jui/js/jquery.min.js:4901:4
.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:374:14
jQuery.prototype.each@http://gutenberginstitute.com/media/jui/js/jquery.min.js:139:10
.trigger@http://gutenberginstitute.com/media/jui/js/jquery.min.js:4900:1
n.trigger@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:7867
@http://gutenberginstitute.com/cache/widgetkit/uikit-983b8e2d.js:2:9115
jQuery.Callbacks/fire@http://gutenberginstitute.com/media/jui/js/jquery.min.js:3099:10
jQuery.Callbacks/self.fireWith@http://gutenberginstitute.com/media/jui/js/jquery.min.js:3211:7
.ready@http://gutenberginstitute.com/media/jui/js/jquery.min.js:3417:1
completed@http://gutenberginstitute.com/media/jui/js/jquery.min.js:3433:2

Can anybody help?

Thanks in advance.

Jose

**Comment by malles** [comment]
You've got versions mixed up. Make sure all your js-files are of the same (current) version

**Comment by ispanets** [comment]
Hi, malles.

Thank you for answering.

Actually, I have 2 script links to jquery, but both are pointing to the same version, 2.1.4. I have overwritten them to ensure myself it's not a jquery version problem, but no way...

* <script src="/media/jui/js/jquery.min.js" type="text/javascript"></script> *
  <script src="/media/jui/js/jquery-noconflict.js" type="text/javascript"></script>
  <script src="/media/jui/js/jquery-migrate.min.js" type="text/javascript"></script>
  <script src="/media/modals/js/jquery.colorbox-min.js" type="text/javascript"></script>
  <script src="/media/modals/js/script.min.js" type="text/javascript"></script>
  <script src="/cache/widgetkit/uikit-9c472795.js" type="text/javascript"></script>
  <script src="/cache/widgetkit/scripts-93454441.js" type="text/javascript"></script>

</script><script type="text/javascript" src="http://gutenberginstitute.com/components/com_comprofiler/js/jquery/jquery.cbtabs.min.js?v=32aae74232919654"></script>
  <script type="text/javascript" src="http://gutenberginstitute.com/components/com_comprofiler/js/jquery/jquery.migrate.min.js?v=69228f9b5c9d9997"></script>

*<script type="text/javascript" src="http://gutenberginstitute.com/components/com_comprofiler/js/jquery/jquery.min.js?v=cabf52a648178fa6"></script>*

<script src="/templates/yoo_venice/warp/vendor/uikit/js/uikit.js"></script>
<script src="/templates/yoo_venice/warp/vendor/uikit/js/components/autocomplete.js"></script>
<script src="/templates/yoo_venice/warp/vendor/uikit/js/components/search.js"></script>
<script src="/templates/yoo_venice/warp/vendor/uikit/js/components/cover.js"></script>
<script src="/templates/yoo_venice/warp/vendor/uikit/js/components/sticky.js"></script>
<script src="/templates/yoo_venice/warp/js/social.js"></script>
<script src="/templates/yoo_venice/js/theme.js"></script>

**Comment by malles** [comment]
Not the jQuery version, but the UIkit version. Make sure the loaded components are of the same version as the core.

**Comment by malles** [comment]
Nope the WK Uikit 2.18 that is loaded is overwritten by the templates 2.20.3, you have an old `cover.js` file that's messing it up. It's probably called in `templates/yoo_venice/layouts/template.config.php`

**Comment by ispanets** [comment]
Him malles!
     
    Thank you very much. You were completelly right. I have done the following:

1) Update all files to UIKit2.20.3 in´´´ templates/yoo_venice/warp/vendor/uikit´´´
2) Update all files to UIKit2.20.3 in ´´´administrator/components/com_widgetkit/vendor/assets/uikit´´´
3) Commented the related line to cover.js in ´´´templates/yoo_venice/layouts/template.config.php´´´

With this, I have the same version of UIKIT everywhere, 2.20.3 (in  <script src="/cache/widgetkit/uikit-9c472795.js" type="text/javascript"></script>    and in   <script src="/templates/yoo_venice/warp/vendor/uikit/js/uikit.js"></script>)

However, I can't see the widget working. Now I simply don't get any info in the javascript console, but no showing at all :(

More ideas?   :(

Thanks again in advance, you are being very helpful.

Jose

**Comment by malles** [comment]
The lightbox component is not loaded. Widgetkit should do that. Better revert the WK's UIkit to what it was, loading the template's UIkit will replace it anyway. Your problem was mostly in the old cover being loaded.
If reverting WK doesn't work, add lightbox component manually (by changing the line you just commented out :)) or ask support at WK/YOOtheme

**Comment by ispanets** [comment]
Thanks malles, I close this.
