### ISSUE TITLE
tab component (click switch change to hover switch)?

### ISSUE THREAD

**Issue by amlioneye** [uikit/uikit#1252]
![2015-05-12_122017](https://cloud.githubusercontent.com/assets/12405091/7580127/57b65134-f8a1-11e4-8950-181b84393c2c.png)
please help me, thank you!

**Comment by malles** [comment]
Is this a sudoku?

**Comment by amlioneye** [comment]
No,this is a tab..I want the tab click switch change to hover switch.And click or hover control switch?
![1](https://cloud.githubusercontent.com/assets/12405091/7581967/80e74aa8-f8bb-11e4-96bf-59c0e1afe15c.jpg)

**Comment by malles** [comment]
This should work:
```
jQuery(function($) {
    $('[data-uk-tab] >li:not(.uk-tab-responsive, .uk-disabled)').hover(function () {
        $(this).trigger('click.uikit.tab');
    });
});
```

**Comment by amlioneye** [comment]
Thank you very very much. Sorry,I'm Jquery and English is terrible. Your example is  "all tabs"  hover show. But now, i need a Data attribute, some tab hover show and others tab click show.
For example:
click show:data-uk-dropdown="{mode:'click'}"
hover show:data-uk-dropdown="{mode:'hover'}"

**Comment by malles** [comment]
Just add the class `uk-tab-hover` to the tab you want to work on hover, and change the selector in the code
```
jQuery(function($) {
    $('.uk-tab-hover >li:not(.uk-tab-responsive, .uk-disabled)').hover(function () {
        $(this).trigger('click.uikit.tab');
    });
});
```

**Comment by amlioneye** [comment]
Wow, it's very good!  Thank you hlep me, wish you good luck!

**Comment by malles** [comment]
Yeah, both jQuery and English are nice languages to understand in this business. jQuery most importantly :)

**Comment by aheinze** [comment]
thanks @malles
