### ISSUE TITLE
Issue with custom styling tooltip

### ISSUE THREAD

**Issue by InteLigent** [uikit/uikit#1256]
Example on the fiiddle: https://jsfiddle.net/8p8a7zp8/

The first show incorrect position, for the second time is ok.

**Comment by zslabs** [comment]
Can you try adding `box-sizing: border-box` to your custom tooltip styles? This is another reason why `border-box` should be the default cc @aheinze @saschadube but that should help for now.

**Comment by malles** [comment]
Most of the jumping seems related to the padding. If I disable that, the position is almost right, I think the negative margin and border might influence it. Adding `box-sizing: border-box` does not help.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
