### ISSUE TITLE
100% classes in uk-grid-width-*

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1257]
I still don't geht, why there are no classes for 100% width in uk-grid-width-* rules. I.e. uk-grid-width-large-1-1.
A larger total breakpoint doesn't mean, the column also is used in larger width. Se often could use this.

**Comment by aheinze** [comment]
in general you add ```uk-width-1-1``` as the default width, and add columns for larger screens. I can't imagine that someone goes from ```uk-width-medium-1-4``` to  ```uk-width-large-1-1``` on large screens.
could you please try to explain a use case?

**Comment by uundh** [comment]
I did previously. We use uk-grid-width-* in sidebars for examples. Which are wider on small screens then in large displays, because they wrap in the main column on small devices. Thus we would need to set multiple columns on smaller screens, but reset it to 100% on larger screens, when the sidebar is again besides and there smaller in width

**Comment by saschadube** [comment]
@uundh They are added in the latest release https://github.com/uikit/uikit/commit/cc80972fdf7db5bc7c520087bb2dd79508f69d9e
