### ISSUE TITLE
subnav items can still be accessed with keyboard when hidden

### ISSUE THREAD

**Issue by adamwoodnz** [uikit/uikit#1259]
We have an offcanvas nav with subnav menus. When a subnav is hidden it is only visibly hidden with `overflow:hidden;height:0;position:relative;` and as a result a user can still tab to the menu items with their keyboard.

To be truly hidden the subnav menu needs `display: none`

It seems this is done so that height can be calculated for revealing the subnav but it isn't good for accessibility. Do you have any plans to improve this, or suggestions as to how to work around it?

**Comment by samueljseay** [comment]
+1 for this issue

**Comment by florianletsch** [comment]
Any suggestion on how to approach this? Haven't had a look at the `display: none` solution, but you're right, it might be solved differently to account for the calculation of the height.

How about setting `tabindex="-1"` on those elements? Would that solve the issue?
