### ISSUE TITLE
(Range) input slider?

### ISSUE THREAD

**Issue by kvetoslavnovak** [uikit/uikit#126]
Is there any way how UIkit can be used to code a range input slider which would work also in older IE versions?
Thank you very much

**Comment by malles** [comment]
@Jogai Times have changed.. https://github.com/uikit/uikit/blob/develop/src/js/components/slider.js
Is in develop branche now!

**Comment by malles** [comment]
My bad...  Totally different kind of slider :)

**Comment by datalynk** [comment]
I need this also!!! Range Sliders are very useful when filtering results...

**Comment by hack-r** [comment]
I need this also. This is what I'm using for now so that I don't have to have 2 sliders to do the job of 1:
https://github.com/sgwilly/RangeSlider
http://www.raywenderlich.com/76433/how-to-make-a-custom-control-swift
