### ISSUE TITLE
Autocomplete/Timepicker clash with icon

### ISSUE THREAD

**Issue by kevinresol** [uikit/uikit#1260]
```html
<div class="uk-form-icon">
	<i class="uk-icon-clock-o"></i>
	<input type='text' class="uk-form-controls" data-uk-timepicker/>
</div>
```

after clicking the timepicker, html becomes
```html
<div class="uk-form-icon">
	<i class="uk-icon-clock-o"></i>
	<div class="uk-autocomplete uk-open">
		<input type="text" class="uk-form-controls data-uk-timepicker="" autocomplete="off">
		...
	</div>
</div>
```

causing the icon not being shown correctly

**Comment by zslabs** [comment]
A [CodePen](http://codepen.io) would be more helpful so we can see it visually and try to help debug.

**Comment by malles** [comment]
http://codepen.io/malles/pen/NqXZwg?editors=101

It takes a little tweaking, but in this way the icon and picker work fine together!
