### ISSUE TITLE
Misleading Examples and Documentation

### ISSUE THREAD

**Issue by OwenMelbz** [uikit/uikit#1261]
Hi guys, firstly great work with everything you've done with UIKit its a great framework, however my team have got a little niggle with it that we were hoping you could address.

Simply put the examples on the documentation pages don't represent the HTML snippets given, making it confusing for beginners to pick up the mark up correctly.

For example http://getuikit.com/docs/upload.html we see

![image](https://cloud.githubusercontent.com/assets/1094740/7637931/5a156d74-fa69-11e4-9034-f8c1ff3f0ef5.png)

This to most users would suggest that the rendered examples can be achieved with the following code, as most over services do - yet when they copy/paste the code they notice it looks nothing like the examples, and I've seen several people getting highly frustrated by this and resorting to copying the code from the code inspector rather than using the printed documentation.

I believe it would be extremely useful to see an example pair that actually represent each other in the documentation, for example SemanticUI allows users to see exactly how the outcome has been achieved with great ease http://semantic-ui.com/collections/breadcrumb.html

![example](https://cloud.githubusercontent.com/assets/1094740/7638290/9eade932-fa6b-11e4-8388-a0714a45b993.gif)

Excuse the crude example gif.

Do you guys think you could move forwards to documentation more similar to this?

**Comment by malles** [comment]
+1 on this, as stated in #1077

**Comment by pcout** [comment]
+1 on this

**Comment by Pandahisham** [comment]
+1 on this  , maybe even a codepen link for examples too , so someone can get their hand messy instantly while learning uikit

**Comment by csakis** [comment]
+1 I agree with this, too. I have to use **Inspect element** to see how the code is written, which beats the purpose of documentation.

**Comment by stebeg** [comment]
OwenMelbz said:
>and I've seen several people getting highly frustrated by this and resorting to copying the code from the code inspector rather than using the printed documentation.

That's exactly what I've always done. 
+1 on this

**Comment by Kasendwa** [comment]
Aah, finally someone talks about this. I always hate picking code from Code Inspector to try it out.

**Comment by adityak2190** [comment]
+1

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The docs of UIkit3 has been changed that way that the examples now have a codebox where you directly can see how the example has been build. 

Thanks for your understanding,
Your UIkit Team
