### ISSUE TITLE
Slideshow and slider does not Connect together !

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1264]
Hi i have slideshow and one slider under that slideshow when i click the slider item the slide show does not work. how to connect them work together ?

**Comment by malles** [comment]
It should work like this: http://codepen.io/malles/pen/qdOvJP

**Comment by miladmeidanshahi** [comment]
malles THANKS BRO I LOVE U. You Are The Best  ;)

Please add this feature to uikit by default .

**Comment by miladmeidanshahi** [comment]
malles just one thing can you add just one feature, if i click on next and previous the large slideshow the slider (uk-adtive) move or chnage and slide with that  ?

THX

**Comment by malles** [comment]
That should be possible by listening to the focus event. I tried to set that up in that pen, but the event does not seem to bubble through somehow. I'll create an issue for that.

**Comment by malles** [comment]
As seen at #1266, the problem is solved in the current develop branch.
I updated the codepen, so it should work when the new version is released. A bit more patience..

**Comment by florianletsch** [comment]
Thanks @malles :+1:
