### ISSUE TITLE
Modal header and footer properties problem !

### ISSUE THREAD

**Issue by pcout** [uikit/uikit#1265]
"uk-modal-header" and "uk-modal-footer" classes in the default theme (on both uikit.css and uikit.min.css) doesn't have the full properties. As a consequence the backgoriund, padding, margins, etc.., are not being applied.

Can you correct this ?

Thanks.

**Comment by malles** [comment]
By default the `modal-header` and `modal` footer only provide margin from the rest of the content. Any styling or backgrounds should be done in a custom theme, by using the less-hooks `.hook-modal-header` and `.hook-modal-footer`.

**Comment by aheinze** [comment]
@malles thanks!

**Comment by pcout** [comment]
Aren't there 3 themes ?

-> UIkit with the basic style
-> UIkit with Gradient style
-> UIkit with Almost flat style

Why doesn't  the basic style (flat style) have the same CSS properties ?

Even if I customize the flat theme (basic style) there are no options to the modal header and footer properties. I wonder if more core elements or components are missing something.
