### ISSUE TITLE
Event '' slider component not working

### ISSUE THREAD

**Issue by malles** [uikit/uikit#1266]
As demonstrated in this codepen:http://codepen.io/malles/pen/MwevpY?editors=101
I can see in debug that the event is triggered on the correct element, de bound function just won't fire.
Can anyone see what is going on here?

edit: misfired empty issue, sorry

**Comment by aheinze** [comment]
this is fixed in the dev branch: https://github.com/uikit/uikit/blob/develop/src/js/components/slider.js#L266 . ```focus``` seems to work only with inputs. so ```focusitem``` ist the new event name.

**Comment by malles** [comment]
Ah, that explains these eventname changes. I actually missed that commit. Thanks as always!
