### ISSUE TITLE
How to changing pages of Dynamic Pagination

### ISSUE THREAD

**Issue by terrymmx** [uikit/uikit#1267]
I try to add a Dynamic Pagination manually by this
var pagination = UIkit.pagination('#myid', { pages:20 });
It works fine,but I do not know how to change the option:pages dynamically.
I tried like this:
var MyPage = 20;
var pagination = UIkit.pagination('#myid', { pages:MyPage  });//it created a Dynamic Pagination of 20 pages.
.........
MyPage = 15;
pagination = UIkit.pagination('#myid', { pages:MyPage  });//it's not working,still 20 pages

**Comment by malles** [comment]
The components instance stays connected to the element, and trying to set it up again won't work. Try changing the options on the var you have.
```
var MyPage = 20;
var pagination = UIkit.pagination('#myid', { pages:MyPage });
...

pagination.options.pages = 15;
```

**Comment by terrymmx** [comment]
Thanks a lot.

**Comment by davidtim** [comment]
how can i reset it?

**Comment by fhouenou** [comment]
Hi terrymmx,
Can u give help for one stuff like what you did?
I'm trying to use uikit pagination but it is not working...

**Comment by jerry1970** [comment]
How about adding some paragraphs to the documentation?
