### ISSUE TITLE
Initialize slideshow after AJAX content load

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1268]
We need to load the slideshow content depending on several conditions.
As I found out, with no content available on page load, the slideshow does not show up. I didn't find a documentation to initialize the slideshwo per JS after the AJAX load has finished. Is that possible?
Or will it become possible in future releases?

**Comment by malles** [comment]
You can initialize all components via JS: `var slideshow = UIkit.slideshow('#yourEl', {option:'value'});`. This returns the current instance already initialized, or inits new instance. Omit the data-attribute to keep auto-initialisation on domready.
You could try placing the `data-uk-observe` attribute on a parent element. It attaches a DOM-observer that inits UIkit components when DOM changes. That might do the trick already.

**Comment by florianletsch** [comment]
Thanks malles. :+1:

**Comment by uundh** [comment]
That worked perfect! Thank you!
Am 18.05.2015 21:58 schrieb Matthijs Alles <notifications@github.com>:You can initialize all components via JS: var slideshow = UIkit.slideshow('#yourEl', {option:'value'});. This returns the current instance already initialized, or inits new instance. Omit the data-attribute to keep auto-initialisation on domready.
You could try placing the data-uk-observe attribute on a parent element. It attaches a DOM-observer that inits UIkit components when DOM changes. That might do the trick already.

**Comment by anushac243** [comment]
Hey, I'm creating my `<li>` components through AngularJS's `ng-repeat` and assigning a lost of objects to it on success of the AJAX call but I don't see the images. I also initialise the slideshow on success of the AJAX call. Any idea why the images aren't loading? I see the relevant code when I "inspect" the page.

**Comment by andykenobi** [comment]
anushac243, i have the same problem :(

**Comment by anushac243** [comment]
@andykenobi I just switched to Bootstrap carousel. Couldn't find the solution to this.

**Comment by Marjani** [comment]
i have the same problem with angular 2 component, any solution?

**Comment by harshsanghani** [comment]
I have same problem, I could not initialize lightbox on pictures that are loaded using AJAX. Is there any solution for this?
