### ISSUE TITLE
Meteor: "uk-grid-margin" does not get added on wrapped elements if inside {{#each}} helper

### ISSUE THREAD

**Issue by jaypanares** [uikit/uikit#1269]
Hi,

I'm using the Meteor package "zcurtis:uikit" and noticed a bug.  I couldn't find the author's repo for the package so I decided to post the issue here.

Apparently, when using "data-uk-grid-margin" when wrapping grid elements, the class "uk-grid-margin" does not get added to the wrapped elements if inside an {{#each}} helper to iterate elements.  This results to no padding between rows (padding between columns work fine).

Hopefully the package author sees this and addresses the issue.

Thanks!

**Comment by aheinze** [comment]
try to add the attribute ```data-uk-observe``` to the grid element

**Comment by jaypanares** [comment]
@aheinze - Using uikit with Meteor and when you refresh, it reverts back to no spaces within rows even though `data-uk-observe` is in the tags.
