### ISSUE TITLE
SmoothScroll doesn't change browser hash on click

### ISSUE THREAD

**Issue by Varyen** [uikit/uikit#1270]
It was actually changed in https://github.com/uikit/uikit/issues/418 , but don't you think it should be configurable?

For example, I'm using `UIkit.smoothScroll( jQuery('a[href^="#"') );` for all links just with hash. It's good for landing pages and I would like to have oportunity to copy my URL **with hash** and send it to someone.

I just commented `e.preventDefault();` in click handler and `return false;` in boot.

**Comment by Varyen** [comment]
P.S. Rewrited my initialization to `jQuery('a[href^="#"').attr('data-uk-smooth-scroll', '');`

**Comment by Semmu** [comment]
Please make it configurable, permalinking with hash should be available.

**Comment by aheinze** [comment]
the smoothscroll is just an effect thing, this makes sure that you don't mess up with all the js based routers. but we'll bring it back to discussion. thanks!
