### ISSUE TITLE
uk-vertical-align work only in firefox

### ISSUE THREAD

**Issue by Tuning-Soft** [uikit/uikit#1272]
Hello! 
Guys, help please, I do not understand, why doesn't work the vertical alignment? Work only in firefox
https://monosnap.com/file/vmEARBquAa0KGSuZovgn4yNIWi7KtB.png

Site: http://www.steelie-car.ru/

**Comment by malles** [comment]
Forget `uk-vertical-align`. Meet mister [Flex](http://getuikit.com/docs/flex.html)!
Try `uk-flex uk-flex-middle` on that panel and remove the class from the child div.
![image](https://cloud.githubusercontent.com/assets/5442402/7720986/679c177c-fed3-11e4-8e97-18ac662a38ea.png)

**Comment by Tuning-Soft** [comment]
@malles, thank you very much!!!
But, the Flex does not work in latest Safari and EI9 >=?

For me dos't work
https://monosnap.com/file/vIH6tHNPsZ6GITMl4q9XYS25EnrwWB.png

**Comment by malles** [comment]
Should in Safari. http://caniuse.com/#feat=flexbox

**Comment by Tuning-Soft** [comment]
Oh my God, on Windows latest 5 version Safari)) 
I understand everything, thanks again!)
