### ISSUE TITLE
Slideshow extra animations do not work with content

### ISSUE THREAD

**Issue by MartinJBates** [uikit/uikit#1273]
Hi,

I was hoping to use the slideshow component for a big wallboard using the advanced transitions, however with non-image related content such as generic text etc, these do not work. 

I have a basic codepen http://codepen.io/anon/pen/LVZMzL here which is 5 slides with alternate backgrounds which I expected to transition with the advanced transitions available, but only seems to be able to use the basic ones.

Any ideas on how to make it support the advanced ones?

**Comment by aheinze** [comment]
that's right, the extra animations only support image based slides. to support content based slides would be too much effort and overhead + I don't think it will look nice. thank you for your suggestion.
