### ISSUE TITLE
Margin uk-container-center overruled by uk-grid-divider

### ISSUE THREAD

**Issue by wswebcreation** [uikit/uikit#1274]
Hello,

I don't know if this is an issue or that I'm not using the code in a correct way, but when I use this code

```
<div class="uk-grid uk-container-center uk-container uk-grid-divider">
    ....
</div>
```

Then

```
.uk-grid-divider:not(:empty) {
    margin-left: -35px;
    margin-right: -35px;
}
````

will overrule

```
.uk-container-center {
    margin-left: auto;
    margin-right: auto;
}
```

causing the grid content not to center.

Possible solution is to wrap it in a `container` div, or is this the way it should be used?

I'm working with 2.20.3

**Comment by malles** [comment]
You can't combine the container and grid this way.
If you want to center the page around the grid, place a grid element inside a container element.
If you just want to center the content in the div, use flex `uk-grid uk-grid-divider uk-flex-center`.

**Comment by wswebcreation** [comment]
Tnx for your quick response. I'll close this
