### ISSUE TITLE
uikit not working at all

### ISSUE THREAD

**Issue by aaychat** [uikit/uikit#1276]
I read through the uikit documentation and proceeded to try it on a simple page which consists of a toggle image(the three bars) that hides/un-hides a navigation bar. 
Yet, when I opened the page in Chrome, what came out was nothing like what i was expecting.
I don't know what i'm doing wrong.
Below is the code I wrote:
![screen shot 2015-05-20 at 9 59 14 pm](https://cloud.githubusercontent.com/assets/4549434/7731062/85c52d20-ff3b-11e4-9e7f-ddaf94a47995.png)

This is the uikit folder path (to make sure I did not write the path wrong.). The uikit folder is in the same folder as the webpage (index2.html).
![screen shot 2015-05-20 at 9 46 10 pm](https://cloud.githubusercontent.com/assets/4549434/7730959/f33e2d58-ff3a-11e4-8166-928c0108bd38.png)

Here is how it turned out when opened in Chrome.
![screen shot 2015-05-20 at 9 59 00 pm](https://cloud.githubusercontent.com/assets/4549434/7731071/8e7a5378-ff3b-11e4-807c-ea111a247ec0.png)

**Comment by zslabs** [comment]
That looks exactly how it should. I think what you are trying to do is show the navigation in an off-canvas menu -- you don't have any of the required DOM to do so. Please read through the documentation again. If you're just trying to toggle the menu, you'd want to apply a different style to the UL than what you have -- otherwise it'll still look how you have it.

**Comment by aaychat** [comment]
You were right. I want people to click on the (horizontal bars) image to reveal/unreveal the menu (so I added the toggle to the image as you can see in the code). What additional classes do I need to add and where for that to happen?
Also, my modal box does not appear when I click on about.

I really appreciate all the help. A newbie coder here hoping to become a good one someday.

**Comment by zslabs** [comment]
Of course, always happy to help. To be perfectly honest on what you're missing, I'd just be regurgitating what the docs mention, so I'd recommend just running through those again for each individual component. The docs are quite good, so just start with copying the HTML examples that are there and then start modifying to your needs.

**Comment by aheinze** [comment]
@zslabs thanks!
