### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by pcout** [uikit/uikit#1277]
I'm loading some graphs into a modal and the browser almost crashes. The performance is drasticly reduced, and the UI becomes extremely laggy and unstable.

I've tried [morris.js] (http://morrisjs.github.io/morris.js/) and [c3.js](http://c3js.org/).

Do you know what is happening ?

**Comment by pcout** [comment]
Well, I've tried inserting the graph in page (inline) without using the Modal and the issue still exists.

Any issue with UIkit and graphs ??

**Comment by malles** [comment]
Did you try the graph without loading UIkit?

**Comment by ffuentes** [comment]
Hi, I have tried 3 graphs libraries for a personal project a few daya ago:
First tried [nvd3.js](http://www.nvd3.org) with no issues, just code inline. 
After that, tried [dimple.js](http://www.dimplejs.org) inside non-actívated tab, and got the issue that the graph get the entire viewport width, bypaasing the error creating a button to manually create the svg. 
Then tried [c3.js](http://www.c3js.org) inside active tab and got no issue.

Didn't tried inside modal, but for me uikit+c3.js works good. Maybe you can send a code, or the data for the example, could be a c3.js issue.

**Comment by aheinze** [comment]
could you please provide a [jsfiddle](http://jsfiddle.net/)?

**Comment by pcout** [comment]
I've tried again (both inline and in modal) with c3.js and I'm not getting any errors now.
Maybe a "stressed" browser issue.
