### ISSUE TITLE
How can i compile almost-flat theme myself using less ?

### ISSUE THREAD

**Issue by JSoon** [uikit/uikit#1278]
Here is the thing, i want to customize the almost-flat theme myself, but i only found the defaults theme import in the uikit.less bellow:
![image](https://cloud.githubusercontent.com/assets/7589350/7741380/b41b0efe-ffb0-11e4-9e1a-533a48f0a874.png)

Hoping this could be solved, cause i don't wanna customize theme in the http://getuikit.com/docs/customizer.html, thx.

**Comment by malles** [comment]
That `Defaults` is not about the theme, it says that `core/base.less` is a default less file.

**Comment by florianletsch** [comment]
You could either:

1. Duplicate the `almost-flat` folder and use it as a starting point for your own theme
2. Create your own less file and import the uikit.less of the almost-flat theme, then add your customizations below:

```less
@import "path/to/themes/almost-flat/uikit.less";

// your customizations here
```

**Comment by JSoon** [comment]
Thanks guys, i saw what i missed actually is that i used bower to install UIKIT and there was no theme folder. Now i've got the right version, thanks anyway :)
