### ISSUE TITLE
Delay of dropdowns in navbar

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#1279]
Hi, 

I just upgraded from 2.17.0 to 2.20.3 and recognized, that the dropdowns in the navbar got a 1 second delay. When I move the cursor from one parent item to another, I have to wait a second, till the sub menu becomes visible. That's really annoying.

How can I remove that delay?

**Comment by malles** [comment]
You can with the timing with the options `hoverDelayIdle`, `remaintime` and `delay`.  `hoverDelayIdle` is relatively new, so I'd bet that's the one you want to change, it has a default of 250ms.

**Comment by stebeg** [comment]
Thanks. That was the option, that caused the delay. I guess, the documentation for hoveDelayIdle is missing on the website.
