### ISSUE TITLE
Refreshing ScrollSpy

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1282]
Hi all,
Attempting to use scrollspy to lazy load images, using the following:

    lazyLoad = UIkit.scrollspy($('img[data-src]'), UIkit.Utils.options(
      repeat: true
    ))
    lazyLoad.on 'inview.uk.scrollspy', ->
      $(this).attr 'src', $(this).attr('data-src')
      $(this).removeAttr 'data-src'
      return

This works fine on server-side loads, but in a client-side driven application, I'm struggling to find a way to "refresh" the checks for the elements currently on the page. I've tried dispatching the event tied to checkScroll():

    window.dispatchEvent new Event 'scrolling.uk.document'

But that hasn't proven to re-start the check. Any tips would be greatly appreciated. Thanks!

cc @aheinze

**Comment by zslabs** [comment]
I've also tried manually re-initting scrollspy with no luck on this AJAX'd content:

    if $('img[data-src]').data 'sticky'
      $('img[data-src]').data('sticky').check
    else
      UIkit.scrollspy($('img[data-src]'), UIkit.Utils.options(
        repeat: true
      ))
    return

**Comment by malles** [comment]
Are you using placeholders in the loaded images?
I've been studying this for a bit in a [codepen](http://codepen.io/malles/pen/RPGBgW) and I get the correct behaviour with injected content using this script:
```
(function($, UI) {
  function lazyLoad(context) {
    UI.scrollspy(context, {
        repeat: true
      })
      .on('inview.uk.scrollspy',
        function() {
          $(this).attr('src', $(this).attr('data-src'));
          $(this).removeAttr('data-src');
        });
  }
  UI.ready(function() {
    lazyLoad($('img[data-src]'));
    $('#inject').click(function() {
      $('#newcontent').html('<img src="http://getuikit.com/docs/images/placeholder_200x100.svg"  data-src="http://getuikit.com/docs/images/placeholder_800x400_2.jpg">');
      lazyLoad($('img[data-src]'));
    });
  });
}(UIkit.$, UIkit));
```
![lazyload](https://cloud.githubusercontent.com/assets/5442402/7769883/905c083c-0088-11e5-90fd-398b100e1ade.gif)
If I inject the image without a placeholder, scrollspy judges it as not in view, since it has no dimensions.
Hope this helps you.

**Comment by malles** [comment]
PS. Setting the option to `topoffset: 50` makes the image load 50px below the viewport. Repeat is not necessary. You can pass a plain js-object in the constructors, `UIkit.Utils.options( 'repeat: true' )` takes a long road returning the same.

**Comment by malles** [comment]
I took an even different approach, where you don't have to manually refire the lazyload.
```
(function($, UI) {
  //set component default values so you can use default `data-uk-scrollspy` tag
  UI.on('beforeready.uk.dom', function() {
    $.extend(UIkit.components.scrollspy.prototype.defaults, {
      topoffset: 50
    });
  });
  UI.ready(function() {
    //bind listener to images to load source
    $('img').on('inview.uk.scrollspy',
      function() {
        $(this).attr('src', $(this).attr('data-src'));
        $(this).removeAttr('data-src');
      });
    //simple dom injection
    $('#inject').click(function() {
      $('#newcontent').html('<p style="min-height:400px">scroll down more..</p><img src="http://getuikit.com/docs/images/placeholder_200x100.svg" data-uk-scrollspy data-src="http://getuikit.com/docs/images/placeholder_800x400_2.jpg">');

    });
}(UIkit.$, UIkit));
```
Reinitializing the scrollspy is done by adding the `data-uk-observe` attribute to the parent div of the injected content.
http://codepen.io/malles/pen/vOXzxZ?editors=101

**Comment by zslabs** [comment]
Nice! Appreciate the writeup @malles I'll be digging into this more today and let you know what comes of it.

**Comment by zslabs** [comment]
The second one you mentioned is working great --- but obviously fails for browsers that don't support MutationObservers. Working on a fallback for ones that don't with https://gist.github.com/stucox/5231211 Will let you know if anything comes of it.

**Comment by malles** [comment]
I take UIKit standard as a benchmark here.
You could of course use `UI.init($(#newcontent')` after adding to the Dom instead of the observer.

**Comment by zslabs** [comment]
@malles Completely forgot about trying `UI.init()` because I was on an older version. Thanks for the heads up with that, seems to be working well!
