### ISSUE TITLE
figcaption for Lightbox

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1284]
how can I make a valid (functioning) figcaption for the Lightbox.

Many thanks in advance.
Hans

**Comment by malles** [comment]
The lightbox component takes the images `title` attribute and places it as a caption under the lightbox image, see http://getuikit.com/docs/lightbox.html.

**Comment by hansnolte** [comment]
Ja, thats right, but I can not format the Title-Text.
I have helped me with "uk-modal-caption"

See
http://www.rpm-factories.de/htm/vorentwicklungsphase.htm

**Comment by malles** [comment]
That would be the correct way. Thanks
