### ISSUE TITLE
Table inside Panels

### ISSUE THREAD

**Issue by Skymidt** [uikit/uikit#1286]
If we have a table inside a panel, don't work any class in it (hover, stripped...), like exemple bellow:

<div class="uk-panel uk-panel-box uk-panel-box-secondary">
    <div class="uk-overflow-container">
        <table class="uk-table uk-table-hover uk-table-striped">
            <thead>
                <tr>
                    <th width="180">Action</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th width="120"><button class="uk-button" data-function="New"><i class="uk-icon-plus"></i> New</button></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="uk-button-group">
                            <button class="uk-button" data-function="edit" data-id=""><i class="uk-icon-edit"></i></button>
                            <button class="uk-button" data-function="delete" data-id=""><i class="uk-icon-trash"></i></button>
                        </div>
                    </td>
                    <td>ID</td>
                    <td colspan="2">Name</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

**Comment by malles** [comment]
That is when the `@table-hover-background`, `@table-striped-background` and `@panel-box-background-color` are (almost) the same color, which is the case in the default theme.

**Comment by Skymidt** [comment]
NOP malles! Striped change colors of rows. Hovered makes this a little darker. Any of this colors can't be seen in the table, even hovered.

**Comment by uikid** [comment]
What are you talking about?

Take a look at this: http://codepen.io/anon/pen/YXpvzY

**Comment by malles** [comment]
I think he means it like that, in panel box. http://codepen.io/anon/pen/eNBjjj
Zebra is gone, hover is lightly visible.

**Comment by Skymidt** [comment]
Exactly @malles  for you hover still showing, for me nothing changes, in the same code you show.

**Comment by Skymidt** [comment]
Exactly @malles, but  in your test hover still showing, for me nothing change or can be seeing.
At least even lines should be lighter instead no color, because panel box have the same background color. Or some css that change this colors inside panelBox.

**Comment by florianletsch** [comment]
@Skymidt Can you provide a live example (codepen, jsfiddle) for us to have a look at your particular code? As you can see in the example by malles, it should actually work.
