### ISSUE TITLE
uikit should have this

### ISSUE THREAD

**Issue by lichtensteinberlin** [uikit/uikit#1287]
uikit should have something like this (taken from the jeet grid system):

@mixin grid-edit($color: black, $important: false) {
  @if $important {
    * {
      background: rgba($color, .05) !important;
    }
  } @else {
    * {
      background: rgba($color, .05);
    }
  }
}

i really like to work with it to check how elements are positioned, sized and so on.

**Comment by florianletsch** [comment]
Thanks for your suggestion.

You can use the hooks in less to inject styles like this in the grid css. If you need it, just add it to your own theme. Here is how you do that: http://getuikit.com/docs/documentation_create-a-theme.html

I think that is a good solution already, so I don't think we need to add this to the uikit core.

**Comment by lichtensteinberlin** [comment]
ok thanks. already did :) all the best.
