### ISSUE TITLE
Unable to load UIKit using SystemJS

### ISSUE THREAD

**Issue by schinckel** [uikit/uikit#1289]
It seems that because `UI.Utils.matchHeights` is defined after the place it is used.

When I moved it to be defined before, then it loaded fine.

**Comment by malles** [comment]
It is only used in the file `core/grid.js`, which is compiled after utils.js, where it is defined. 
Can you be more specific?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
