### ISSUE TITLE
Slideshow stops autoplay when next or previous button is clicked

### ISSUE THREAD

**Issue by tdelpih81** [uikit/uikit#1290]
I have identified that an autoplay enabled slide show stops getting next slide automatically when user clicks next or previous button. My current code is below;

```
<div id="w0" class="uk-slidenav-position" data-uk-slideshow='{autoplay:true,kenburns:true}'>
	<ul class="uk-slideshow">
		<li><img src="/image01.jpg" alt=""></li>
		<li><img src="/image02.jpg" alt=""></li>
		<li><img src="/image03.jpg" alt=""></li>
		<li><img src="/image04.jpg" alt=""></li>
		<li><img src="/image05.jpg" alt=""></li>
		<li><img src="/image06.jpg" alt=""></li>
		<li><img src="/image07.jpg" alt=""></li>
		<li><img src="/image08.jpg" alt=""></li>
	</ul>
	<a class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" href="" data-uk-slideshow-item="previous"></a>
	<a class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" href="" data-uk-slideshow-item="next"></a>
</div>
```
I prefer that autoplay continues after clicking the next or previous button.

**Comment by malles** [comment]
It is the default behaviour. If I click back to a slide, to read it or look at the picture, I wouldn't want it to slide away again on it's own...

**Comment by PixelT** [comment]
https://github.com/uikit/uikit/issues/1043 :)

**Comment by josueadelima** [comment]
Any option to change the default behavior? My case doesn't apply as you said to read the slide, so, a way to change that would be nice, maybe its not an issue but it should be added as a feature.

Thanks

**Comment by piotr-cz** [comment]
As @malles pointed out, it makes sense to keep default behaviur

However it's possible to start autoplay again after animation has ended with slight delay given that `$element` is the slideshow element:

```js
$element.on('click', '[data-uk-slideshow-item]', function(event) {
    $element.one('show.uk.slideshow', function(event, next, current, uikitSlideshow) {
        window.setTimeout(function() {
            uikitSlideshow.start();
        }, uikitSlideshow.option('autoplayInterval'));
    });
});
```
