### ISSUE TITLE
Sortable error using handleClass 

### ISSUE THREAD

**Issue by bellonicola** [uikit/uikit#1291]
In sortable.js, row 313:

var handle = target.hasClass($this.options.handleClass) ? target : target.closest('.'+$this.options.handleClass, element);

throws an error: "element is undefined".
Resolved replacing 'element' with '$this.element'

**Comment by malles** [comment]
That is an error! But if I look in the current develop branch, it already [has been fixed](https://github.com/uikit/uikit/commit/900aca06c73ccdad7947b17a61c5e2723d4bb431).
The line is fine now: https://github.com/uikit/uikit/blob/develop/src/js/components/sortable.js#L307
