### ISSUE TITLE
Navigations list with bars 

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1292]
In the bootstrap framework easy can create navigations list with bars for responsive mode. please add same capability to UIKit 
```
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Application Name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </div>
        </div>
    </div>
```

**Comment by zslabs** [comment]
I believe that's the point of `uk-icon-bars` (the icon font)

**Comment by mojtabakaviani** [comment]
Yes, we can use ```uk-icon-bars``` instead div bars, but need toggle mode for show/hide navbar in responsive pages

**Comment by zslabs** [comment]
Do you mean [this](http://codepen.io/stevenfabre/pen/LGvzk) kind of animation?

**Comment by mojtabakaviani** [comment]
No,  same [this](http://codepen.io/anon/pen/EjZVQe) demo

**Comment by zslabs** [comment]
I've been doing the exact same thing with `.uk-hidden-small` `.uk-visible-medium` etc classes for the icon itself. if you need extra borders, or highlights, then just attach a modifier class to it and add it yourself. IMHO it really doesn't make sense to add this to the core because you can use existing visibility classes to do this yourself.

**Comment by malles** [comment]
http://codepen.io/malles/pen/ZGLLgj
This comes close to it, needs a bit of customization, but is close enough from core.
Biggest difference is the the menu is twice in the DOM, I can see that a a downside. Visually it's the same.

**Comment by mojtabakaviani** [comment]
thanks.
