### ISSUE TITLE
<hr> invisible with minified css

### ISSUE THREAD

**Issue by florianletsch** [uikit/uikit#1295]
Apparently, the minified CSS is lacking some styles, i.e. `border-top`. 

Source: https://plus.google.com/u/0/116878259968600698348/posts/7KeQGpsk1z5

**Comment by malles** [comment]
As seen in inspector:
![image](https://cloud.githubusercontent.com/assets/5442402/7815398/5ddd0c92-03c8-11e5-91bb-53d800718fac.png)
No border, so no visible `hr` in minified version:
![image](https://cloud.githubusercontent.com/assets/5442402/7815414/7aa8df7c-03c8-11e5-8621-cabe5485c971.png)

**Comment by uikid** [comment]
This has already been mentioned here:
https://github.com/uikit/uikit/issues/1246

It will be fixed in the next version.
