### ISSUE TITLE
HHVM - make it compatible with UIkit, WARP etc

### ISSUE THREAD

**Issue by xetorixik** [uikit/uikit#1296]
Dear,

Please make your themes UIkit, WARP etc compatible with HHVM (https://github.com/facebook/hhvm).
HHVM won't work with any of your Yootheme products at this time.
Result showing a white page if HHVM is enabled.

The log displays the following message when using HHVM 3.7:

'[Tue May 26 17:21:58 2015] [hphp] [1304:7f68873ff700:1:000001] [] \nFatal error: Call to undefined method DOMElement::text() in /var/www/website.com/htdocs/wp-content/themes/website/warp/systems/wordpress/src/Warp/Wordpress/Helper/SystemHelper.php on line 124'

Getting things working on HHVM shouldn't be that hard for experts like @saschadube @aheinze  and @steffans 

Regards,

**Comment by aheinze** [comment]
thanks, but this is only releated to uikit. please visit http://yootheme.com/support. thank you!

**Comment by xetorixik** [comment]
I use the master theme so your support channel is not working about that.
It is about the fact that HHVM is not working c.q. compatible out of the box for all your Warp based themes. So do whatever you want with it. It's now come to your attention and you are aware of the fact that you can't run HHVM with your themes.

**Comment by Boozoo996** [comment]
I confirm the issue, totally destroyed one of my website yesterday, had to make a quick backup recover to fix this...
