### ISSUE TITLE
Autocomplete's Dropdown Bug

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1297]
Hi Autocomplete's Dropdown Closed when click in any Area but Dropdown Components it's doesn't like this how can i solve this problem ?

Many Thanks.

**Comment by miladmeidanshahi** [comment]
i found the problem that is 
```
// register outer click for autocompletes
    UI.$html.on("click.autocomplete.uikit", function(e) {
        if (active && e.target!=active.input[0] && !$.contains($('.divelement')[0], e.target)) 
            active.hide();
        });
```

please fix this in auto complete components

**Comment by malles** [comment]
This is desired behaviour for autocompletes. They should close when the user navigates away.
