### ISSUE TITLE
Check display in nav-accordion

### ISSUE THREAD

**Issue by malles** [uikit/uikit#1298]
I'm dynamically adding items to a open nav-accordion. They of course disappear in the list-containers overflow. Could the nav listen to the `check.uk.display` event and recalculate height when triggered?
Now I have to do
```
            var li = $('#offcanvas-user [data-uk-nav] .uk-open').removeClass('uk-open');
            UIkit.nav($('#offcanvas-user [data-uk-nav]')).open(li);
```
to fit it to the right content.

**Comment by aheinze** [comment]
should be fixed in the dev branch now.

**Comment by malles** [comment]
Thanks!
