### ISSUE TITLE
Add option to show Off-canvas bar on the page

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1300]
please add option show Off-canvas on the page instead of push page.

**Comment by malles** [comment]
+1

**Comment by Intiligent** [comment]
+1

**Comment by MacWordPress** [comment]
+1

**Comment by miladmeidanshahi** [comment]
+1

**Comment by malles** [comment]
You seem to come a long way with existing components grid, sticky, button and some css/js: http://codepen.io/malles/pen/YXNLJN

Would be great to have a more solid solution in the core!

**Comment by mojtabakaviani** [comment]
what deference between your example and off-canvas? I need toggle icon to show off-canvas **on the page** and when click any point of page hide off-canvas bar.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has been added with the different modes of the new Offcanvas-Bar ( Push, Slide, Reveal, None )

Thanks for your understanding,
Your UIkit Team
