### ISSUE TITLE
issue with slideset

### ISSUE THREAD

**Issue by arasdesign** [uikit/uikit#1302]
hi Yootheme team
i got a problem with slideset component that its styles won't load , and this is because of there isn't any slideset.less file in your package ? what should i do ?

**Comment by aheinze** [comment]
the slideset component, doesn't have any less file, but re-uses the grid component.

```html

<div data-uk-slideset="{default: 4}">
    <ul class="uk-grid uk-slideset">
        <li><img src="" alt=""></li>
        <li><img src="" alt=""></li>
        ...
    </ul>
</div>

```

**Comment by arasdesign** [comment]
tnx @aheinze  but it won't add any uk-grid classes to my div ? its only add uk-width-1-4 to my divs and no anything else

**Comment by florianletsch** [comment]
Yes, please add the `uk-grid` yourself like in the example above. Please also checkout the source code of the examples located at: http://getuikit.com/tests/components/slideset.html

Replicating those should work in your own code. If not, can you please prepare a codepen or jsfiddle for us to inspect the issue? Thanks.

**Comment by arasdesign** [comment]
@florianletsch i do it and its work perfectly now , tnx you my friend
