### ISSUE TITLE
Switcher is broken with jQuery 3.0

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#1303]
Breaking change happened here: https://github.com/jquery/jquery/commit/86419b10bfa5e3b71a7d416288ab806d47a31d1f
It will not be reverted until release, so it is time to be prepared.

I've spent few hours but still didn't figure out how to fix it yet.

**Comment by nazar-pc** [comment]
Finally figured out how to fix this, look at PR #1304

**Comment by aheinze** [comment]
should be fixed in the develop branch. thanks!
