### ISSUE TITLE
slidenav better contrasts?

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1306]
Couldn't there be a modifier that adds a background to the button so it has a better contrast in situations were there are bright and dark images mixed in a slideshow?

My current workaround (so you get the idea):

.uk-slidenav:before {
    margin-top: -30px;
    display: inline-block;
    width: 60px;
    height: 60px;
    text-align: center;
    line-height: 1;
    background-color: rgba(255,255,255,0.7);
    border-radius: 50%;
}

Ot is the feature there and I just did not find it?

**Comment by safrick** [comment]
+1 for background; navs get lost in pictures.
Another option is to locate the navs outside of the image.

**Comment by Jellygnite** [comment]
You can also try adding text-shadow. e.g.

.uk-slidenav-contrast	{ opacity: 1;  color: rgba(240, 240, 240, 0.9); text-shadow: -1px 1px 0 rgba(0, 0, 0, 0.5); }

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
