### ISSUE TITLE
Get/set data from radio & checkbox button group

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1309]
![checkbox-radio-button](https://cloud.githubusercontent.com/assets/2857625/7932004/c6c28714-091d-11e5-8e50-4674d4997013.jpg)
my task more look like to question/proposition.
Radio buttons group and checkbox group look very nice, but:
- how to get data from them ?
- how to set data to them ?

I know that isset only one way to get data - use default input with attribute **name**.
According to this markup of button group must have default input (radio/checkbox).
After searching found that bootstrap already do it:

```
<div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary">
        <input type="radio" name="options" id="option1"> Option 1
    </label>
    <label class="btn btn-primary">
        <input type="radio" name="options" id="option2"> Option 2
    </label>
    <label class="btn btn-primary">
        <input type="radio" name="options" id="option3"> Option 3
    </label>
</div>
```
http://getbootstrap.com/javascript/#buttons-checkbox-radio

UIKit must have the same or even better functional.

**Comment by malles** [comment]
Here are some examples withe the buttons: http://codepen.io/malles/pen/YPjLpr That might help you.

**Comment by Intiligent** [comment]
**malles** thanks for your answear and work)
but it look like on huck/hook and hard to get data from big form where many input (it was so much excess js code)
I would like to get/set data by default method (change only input).
now it work with radio button but not with checkbox.
http://codepen.io/Intiligent/pen/zGZGPq?editors=101

**Comment by malles** [comment]
Yeah, it won't get into the regular form-fields. You could off course create a hidden field and put the value there.
I agree, a good module for native radio's as buttons is not in UIkit. Form modules are so specific, that I think it's better to find a custom solution per project.

**Comment by Intiligent** [comment]
i think its not take a lot of code (add two-way binding).
Used form its very daily funtionality to use custome bicycl, on my mind)

**Comment by aheinze** [comment]
I would also recommend to use a "binding" framework , like angular, react etc for that.
