### ISSUE TITLE
UIkit.responsiveElement needs "max-width: 100%" stylesheet

### ISSUE THREAD

**Issue by Wizard13** [uikit/uikit#1310]
UIkit.responsiveElement does not resize width if browser is shrinked because it doesn't apply "max-width: 100%" stylesheet. Please see http://users.sch.gr/vandr/uikit.php and script below:
```javascript
$(function() {
	$('iframe[src*="www.youtube.com"],iframe[src*="player.vimeo.com"]').each(function() {
		UIkit.responsiveElement(this);
	});
});
```
If I add it manually, it works:
```javascript
$(function() {
	$('iframe[src*="www.youtube.com"],iframe[src*="player.vimeo.com"]').each(function() {
		$(this).css('max-width', '100%');
		UIkit.responsiveElement(this);
	});
});
```
Shouldn't UIkit.responsiveElement do that by itself?

**Comment by aheinze** [comment]
the iframe needs to have the class ```uk-responsive-width``` ... btw, the script auto-init all iframes with that class ```iframe.uk-responsive-width```, so no need to manually init them
