### ISSUE TITLE
Timepicker dropdown is in wrong position

### ISSUE THREAD

**Issue by vhoangvu** [uikit/uikit#1311]
I use the timepicker in a horizontal form. The dropdown is in wrong position, seem because of the padding of .uk-form-controls.
![capture](https://cloud.githubusercontent.com/assets/6416714/7981263/f298c1da-0ad7-11e5-8d6a-550ecdbee001.PNG)

**Comment by malles** [comment]
Make sure you include the autocomplete component and it's css/less files.

**Comment by vhoangvu** [comment]
Thanks! It works correctly now.
