### ISSUE TITLE
remove grey background on link clicked in ios safari

### ISSUE THREAD

**Issue by lichtensteinberlin** [uikit/uikit#1312]
hi there,

could this be best practice or is there a better solution?

@mixin hook-base-body {
&#42; {
     -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
   }
}

all the best,
sascha

**Comment by malles** [comment]
The `@mixin` is not used for Less, I suppose it's Scss
The hook `hook-base-body` is added to the `html` tag actually. (see https://github.com/uikit/uikit/blob/master/src/less/core/base.less#L99)
This would result in css like 
```
html * {
-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```
which should do the trick.
