### ISSUE TITLE
uk-responsive-width iframe and firefox

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1313]
<  iframe class="t_iframe uk-responsive-width" height="300" width="940" scrolling="no" frameborder="no" src="iframe.html" data-uk-check-display></iframe

...works well with SAFARI and CHROME but not at all with Firefox yet in my setup.

**Comment by malles** [comment]
Have you tried it with the responsive element as in #1310 ?

**Comment by tbba** [comment]
Thanks malles, I just tried this, and not even adding "!important" helped:
< iframe class="t_iframe uk-responsive-width" height="300" width="940" style="max-width:100% !important;" frameborder="no" src="<?=$showtime_complete_url ?>" data-uk-check-display></iframe...
No improvement, unfortunately.

**Comment by hansnolte** [comment]
Hi  tbba,

try this.
https://gist.github.com/malles/423a1eb266f169d01edc

Works for me in Firefox 38.05

data-lightbox-type="iframe" data-uk-lightbox="{width:740,height:630}"

**Comment by tbba** [comment]
thank you... I am not using the lightbox here, my iframe contains an Adobe Edge Animate element and it is a header element with 100% width on top of a page.

**Comment by tbba** [comment]
from the changelog, which came with the firefox update today, there seems to be a knownm jet unresolved problem with responsive images under Firefox right now:
https://www.mozilla.org/en-US/firefox/38.0.5/releasenotes/

**Comment by malles** [comment]
AFIK these issues have been resolved now.
