### ISSUE TITLE
Uncorrect position of tooltip when body style position is set to "relative".

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1314]
When body CSS style contains `position: relative` tooltip is incorrectly positioned over the element that generates it.

**Comment by malles** [comment]
Even if the element that generates it has `position: relative` as well?

**Comment by robertotremonti** [comment]
Yes, even with `position: relative`.
Tooltip element is not child of the element that generates it, it's appended directly to body element.

**Comment by malles** [comment]
I don't think this can be prevented then. You'd have to create a custom css solution or try not to use a relative position on the body.
