### ISSUE TITLE
uk-list with icons and for list items with multiple lines of text.

### ISSUE THREAD

**Issue by skaysurfer** [uikit/uikit#1315]
if i display an icon in my list and have muliple lines of text the text in 2. line is under the icon instead of under the 1. line.
![uklist](https://cloud.githubusercontent.com/assets/12763924/8008370/052fc6a2-0ba2-11e5-8759-a27a9d31f73c.jpg)

**Comment by zslabs** [comment]
This doesn't sound like a bug - that's exactly how the icons should display; you're expecting them to work as a "table-cell" element instead of the inline element they are. If you want something like what you pictured, then you'll either want to use the Flex component or create a custom list class that adds in left padding to each list item and uses the :before pseudo selector to add-in the icon.

**Comment by MacWordPress** [comment]
FontAwesome has better solution for list items wrapped into multiple lines:
http://fortawesome.github.io/Font-Awesome/examples/#list
https://github.com/FortAwesome/Font-Awesome/blob/v4.3.0/less/list.less

This sholud be incorporated into UIkit.

**Comment by malles** [comment]
+1

**Comment by skaysurfer** [comment]
Thank you for the hint @MacWordPress 
this helps me but even it is not the preferred solution. because after the "border" the text will be under the icon. but it is enough for a second line, not enough if there are 3 ore more lines of text.

with the base html list (even with the outdated dots ant not icons) the handling is very easy.
<ul>
<li>first row</li>
<li>second row</li>
<li>...</li>
</ul>
It does not matter if the text is in one line or in multiple lines.

i would love to have a ul class (example: <ul class="uk-list uk-icon-check"> in wich i can select the icons for all the <li> </li> lines
i rarely use different icons in one list.

**Comment by MacWordPress** [comment]
I would prefer individual icons on every list item. I use this i.e. for contacts:
![picture 2015-06-09 at 12 36 18](https://cloud.githubusercontent.com/assets/7726588/8055976/27cb1bda-0ea4-11e5-8d06-403368d1f0ce.png)

**Comment by jerry1970** [comment]
I did this several times but it's too easy to do by yourself that I don't really need extra UIKit classes.
Have a look here:
http://jsfiddle.net/Lrdsu1oo/

```
This is a list with asterisks:
<ul class="charlist">
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>
Here one with an exception:
<ul class="charlist">
    <li>Item 1</li>
    <li class="charlistitem-at">Item 2</li>
    <li>Item 3</li>
</ul>
<style>
ul.charlist {
    list-style: none;
}
ul.charlist li:before {
    content: '* ';
}
ul.charlist li.charlistitem-at:before {
    content: '@ ';
}
</style>
```
It's easy to use FontAwesome characters (and add a fixed width) instead of the * and @.

**Comment by malles** [comment]
Problem with this is the behaivour over multiple lines: http://jsfiddle.net/Lrdsu1oo/1/, the reason this issue is opened. The FA css accounts for that.

**Comment by jerry1970** [comment]
Ah, of course, sorry about that...

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
