### ISSUE TITLE
[RTL-MODE] .uk-align-left & .uk-align-right

### ISSUE THREAD

**Issue by corbacode** [uikit/uikit#1316]
// Margin has been wrong preview in RTL Orginal CSS
.uk-align-left{margin-left:15px;float:left;}
.uk-align-right{margin-right:15px;float:right;}

// Changed Like This  
.uk-align-left{margin-right:15px;float:left;}
.uk-align-right{margin-left:15px;float:right;}

Thanks

**Comment by malles** [comment]
This is what I get from the generated RTL-css from the UIkit customizer:
```
uk-align-left {
  margin-left:15px;
  float:right;
}
.uk-align-right{
  margin-right:15px;
  float:left;
}
```
Which is the correct reverted behaviour.
