### ISSUE TITLE
Hardcoded px in select.uk-form-width-mini

### ISSUE THREAD

**Issue by roll** [uikit/uikit#1317]
https://github.com/uikit/uikit/blob/master/src/less/core/form.less#L462

**Comment by malles** [comment]
That is accounting for the width of the pulldown arrow.

**Comment by roll** [comment]
Uikit is 100% rem-ready except this line. I suppose there is a workaround to remove hardcoding.

**Comment by malles** [comment]
The em/px issue shall be addressed in UIkit 3, it will break too much existing code to change that now.
