### ISSUE TITLE
How could I disable the parallax on mobile only ?

### ISSUE THREAD

**Issue by danygiguere** [uikit/uikit#1320]
How could I disable the parallax on mobile only ? In other words, I would like to change the bg (data-uk-parallax="{bg: '-200'}") to data-uk-parallax="{bg: '0'}" on mobile.

Thanks for your help !!

**Comment by malles** [comment]
There is the [option `media`](https://github.com/uikit/uikit/blob/master/src/js/components/parallax.js#L133) you can pass into the parallax, simular to [sticky](http://getuikit.com/docs/sticky.html#responsive-behavior).
I don't know why it's not documented.

**Comment by danygiguere** [comment]
Thank malles.

I case someone comes here for an answer, this is how you do it:

<div data-uk-parallax="{media: '(min-width: 1200px)', bg: '-200'}" style="height: 400px; background-image: url('img/parallax.jpg');">

**Comment by malles** [comment]
Technically this should work too, judging form [these lines](https://github.com/uikit/uikit/blob/master/src/js/components/parallax.js#L136):
`<div data-uk-parallax="{media: 1200, bg: '-200'}" style="height: 400px; background-image: url('img/parallax.jpg');">`
Didn't test it though.

**Comment by danygiguere** [comment]
Hi Malles.

It works but now my image is far from full height on mobiles.

This is what it looks like with the parallax effect active on mobile: ![screen shot 2015-06-08 at 2 50 58 pm](https://cloud.githubusercontent.com/assets/5892397/8042550/feb746c6-0ded-11e5-86f0-d905278200ee.png)
Once I deactivate it, it looks like this: ![screen shot 2015-06-08 at 2 51 10 pm](https://cloud.githubusercontent.com/assets/5892397/8042555/084dc98a-0dee-11e5-8828-4c254c7b9dfb.png)

Anyway now to fix this (render the image properly) ?

**Comment by malles** [comment]
Okay. wild shot. try
```
@media (max-width: @breakpoint-small-max) {
  [data-uk-parallax]:extend(.uk-height-viewport):extend(.uk-overlay) {
   }
}
```
In your less

**Comment by danygiguere** [comment]
Thanks a lot for your help Malles.

Any ways to do this without less ? (I'm not using less on this project)

**Comment by malles** [comment]
I'm not sure. I'd check out the declarations for `.uk-height-viewport` and `.uk-overlay` and go from there.

**Comment by CesarRotela** [comment]
Thank Danygiguere and Malles... it works!!
