### ISSUE TITLE
Styling Form Submit Button

### ISSUE THREAD

**Issue by nikkon226** [uikit/uikit#1321]
I've tried to style a submit button for a form, but it does not seem to work right:

    <!DOCTYPE html>
    <html>
    <head>
    <link href="uikit.almost-flat.min.css" media="all" rel="stylesheet"></link>
    </head>
    <body>
      <form class="uk-form" method="get" action="#">
      <input class="uk-button uk-button-primary" type="submit" value="Search" name="commit"></input>
    </form>
    </body>
    </html>

The button is this:
![Form Submit Button](https://cloud.githubusercontent.com/assets/7243866/8046321/8ca9747a-0dff-11e5-9c85-a3c71331cb0f.png)

Is there a way to get styling to the input for a submit button similar to other buttons?

**Comment by malles** [comment]
Use a `button` element as a button. See #805, #671.
