### ISSUE TITLE
"data-uk-grid-margin" when you add items via ajax

### ISSUE THREAD

**Issue by thrash87** [uikit/uikit#1325]
Hello everyone!
Create container "<div class="uk-grid uk-grid-small uk-grid-width-small-1-2 uk-grid-width-medium-1-2 uk-grid-width-large-1-2 uk-grid-width-xlarge-1-3" data-uk-grid-margin=""></div>", then make the ajax request and the response is added to the container. But the attribute "data-uk-grid-margin" does not work and classes "uk-grid-margin" are not added.
Is there a way to add classes "uk-grid-margin" to the elements in the container with the class "uk-grid uk-grid-small uk-grid-width-1-2" when dynamically adding elements?

**Comment by thrash87** [comment]
container "div" with classes "uk-grid uk-grid-small uk-grid-width-small-1-2 uk-grid-width-medium-1-2 uk-grid-width-large-1-2 uk-grid-width-xlarge-1-3" and attribute "data-uk-grid-margin"

**Comment by malles** [comment]
Just [add the `data-uk-observe` attribute to the parent element.](http://getuikit.com/docs/documentation_javascript.html#dom-observe)

**Comment by thrash87** [comment]
It's not working. When I write an empty "div" with the attributes "data-uk-grid-margin data-uk-observe and dynamically insert the other elements "div", does not work. And when I write "div" with the attributes "data-uk-grid-margin data-uk-observe" with one empty child "div" and then the parent is cleaned and dynamically insert other elements "div", then it works.
What my error is?

**Comment by malles** [comment]
The `data-uk-observe` should be in a parent of `data-uk-grid-margin`.
```
<div data-uk-observe>
  <div class="uk-grid uk-grid-width-medium-1-2" data-uk-grid-margin>
    <div></div>
    <div></div>
    <div></div>
    ... inject dynamically
  </div>
</div>
```

**Comment by thrash87** [comment]
thank you very much

**Comment by jaypanares** [comment]
@malles - Using uikit with Meteor and when you refresh, it reverts back to no spaces within rows even though `data-uk-observe` is in the tags.

**Comment by malles** [comment]
To force the grid to update via JS you have some options:
See https://github.com/uikit/uikit/blob/master/src/js/components/grid.js#L86
Trigger display check event on grid element or instance
```
var myGrid = UIkit.grid('#grid-el', {...});
//when redraw is needed
myGrid.trigger('display.uk.check');
//or just trigger it on the element itself, or one if its parents
$('#grid-el').trigger('display.uk.check');
```
See https://github.com/uikit/uikit/blob/master/src/js/components/grid.js#L90
Trigger dom changed on $html
```
UIkit.$html.trigger('changed.uk.dom');
```
When you add entire components to the dom, you can init UIkit on a part of the DOM via:
```
UIkit.init('#updated-dom-el');
```
