### ISSUE TITLE
Error occurred while processing Dash

### ISSUE THREAD

**Issue by drinkmaker** [uikit/uikit#1326]
When we use sivol "—"(not "-") in comments, in less files, we got error:
https://goo.gl/cIofoM
Insert this line:
/* Some example — test String */
in theme.less and try to compile.

I tested on:
Joomla! 3.4.1
Warp Framework	7.3.5
UIkit 2.20.3

**Comment by malles** [comment]
Can't you avoid using those in the comments?
Try commenting like `//Some example — test String`

**Comment by drinkmaker** [comment]
This works: //Some example — test String 
This not works: /* Some example — test String */

**Comment by malles** [comment]
Yeah, the wonderful world of computing! :confused: 
I think this is an issue for the less-compile scripts used by gulp, not a UIkit issue.

**Comment by drinkmaker** [comment]
Probably.
