### ISSUE TITLE
Autocomplete limit

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1328]
how can to limit count result items?
```javascript

var ac = $.UIkit.autocomplete('#element', {
    limit: 5, // that's what I meant or something like this
    source: function(release) {
        ...
    }
});

```

**Comment by luetn** [comment]
why not limiting the server side response instead of cropping from ALL results?

**Comment by Intiligent** [comment]
for big data need use server side cropping i fully agree (& do it), but for greater customization and convenience would be great too control data from front end depending on the internal needs.

for example on server side cropping data to 20 items, and already on front end side control limit items max to 20 if required by the design

**Comment by malles** [comment]
You can override the renderer for the autocomplete, and control your limits there.
For examples, see http://codepen.io/malles/pen/qEyEZr
