### ISSUE TITLE
New automatic "uk-active" class for form select components doesn't fit with style guidelines

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1330]
"uk-active" class must be applied only when the user actually presses the select component, not when a value is selected.
That's definitely odd when filling in a form. It seems that you are actually handling that component.

**Comment by quasiperfect** [comment]
any feedback on this ?
is there any way to remove the active class after the user selected something ?

**Comment by malles** [comment]
This was done in favour of the filters in Pagekit. It makes sense in that case. If this would be made optional in UIkit, it would need refactoring in Pagekit. It'll have to be discussed there.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
