### ISSUE TITLE
Slider focus bug

### ISSUE THREAD

**Issue by Dmatafonov** [uikit/uikit#1332]
When slider is set to `{infinite: false}` elements at the end of sequence cant be focused.

Say I have 10 slides, and 4 of them fit on screen. The leftmost slide is in focus. 

Last three slides will never get in focus.

**Comment by syborg0** [comment]
Hello, I have almost the same problem too, a good example is in the doc page : 
http://getuikit.com/docs/slider.html#scrolling

The non infinite slider have 12 slides, but it ends at the 11th slide.

I'm sorry, this is my all first post (and I'm french, so sorry for the bad english), and I don't know very well on how to proceed but I resolved the problem by replacing in **slider.js, line 254** :
`idx = 1;` by `idx = i+1;`

**Comment by florianletsch** [comment]
The off-by-1 error should have been fixed since you reported this.

I not exactly sure what kind of focus you talk about. I will close this for now, but please report back with more details, if the focus issue still exists.
