### ISSUE TITLE
How do I add custom changes UIKit to css and JS, and merge it with a new UIKit release?

### ISSUE THREAD

**Issue by yairpe** [uikit/uikit#1334]
What is the best way to merge local changes with new UIKit releases?

I've made some changes (colors, padding, radius and such, about 30-40 changes), mostly to UIKit.css.

Now every time a new UIKit version rolls, I need to merge them manually.

Doing these changes in the less files and core js does not help because a new release overrides them and it still needs tedious manual merging.

I'm sure there is a better way to handle it. 

**Any help is appreciated**

**Comment by malles** [comment]
If you choose to change and maintain your own style of Uikit, really the best way to do it is to handle it with the less/sass source files, and compile your own uikit.css. http://getuikit.com/docs/documentation_less-sass.html

**Comment by yairpe** [comment]
Thanks. I've read this info but still as I've mentioned, it does not solve the basic issue.

Suppose I've made minor changes in 25 LESS files. Every few months, a new and improved version of UIKit rolls out. Now I need to manually synchronize the changes I've made to the old LESS files into possibly  25 newer files....

I wonder if there is a more elegant solution?

**Comment by malles** [comment]
If you set up your less files as done in the [themes](https://github.com/uikit/uikit/tree/master/themes/almost-flat) you have your own variables and custom style in the override files and hooks. You can update the core and leave your modifications in place.

**Comment by yairpe** [comment]
Thanks. I'll take a look
