### ISSUE TITLE
How to keep offcanvas always open to left side?

### ISSUE THREAD

**Issue by jQsafi** [uikit/uikit#1335]

**Comment by PixelT** [comment]
Offcanvas by default is open on the left side...

**Comment by zslabs** [comment]
Do you mean have the off-canvas open as the main desktop menu and then hide it on mobile? If so -- you'd have to style it specifically on your own for your use-case as it wasn't designed to be used like that.

**Comment by stanleyxu2005** [comment]
I have similar question. I want the offcanvas sidebar not to close when it loses focus. Expect only to close it when I close the close button.
