### ISSUE TITLE
Search Autocomplete behavior

### ISSUE THREAD

**Issue by tropet123456** [uikit/uikit#1337]
I'm passing an array object in data-uk-search="{ source: {{vm.items}} }", and it seems that it doesn't work with autocomplete feature, I'm not sure if I missed something, for now I have added some coalesce in components/search.js which is "items":  (data.results || data) (please refer below) . I'm not sure how it will affect the process but fortunately, it displays the result after putting this code. 

```
            renderer: function(data) {

                var $this = this, opts = this.options;

                this.dropdown.append(this.template({"items":  (data.results || data)  || [], "msgResultsHeader":opts.msgResultsHeader, "msgMoreResults": opts.msgMoreResults, "msgNoResults": opts.msgNoResults}));
                this.show();
            }
``` 

another problem is when I clicked one of the item inside the autocomplete dropdown, it uses the default behavior of <a href="#"></a>.I'm using it inside modal so when I clicked an item, it redirects to the same page. Maybe we can put a template options for this search component. In order to modify that listing.

**Comment by malles** [comment]
There is nothing wrong with that change, it's only in the wrong place :)
That function is in the defaults object of the search component. you can override it with the options. You can also override the template there.
```
UIkit.on('beforeready.uk.dom', function(){

    $.extend(UIkit.components.search.prototype.defaults, {
        renderer: function(data) {

                var $this = this, opts = this.options;

                this.dropdown.append(this.template({"items":  (data.results)  || [], "msgResultsHeader":opts.msgResultsHeader, "msgMoreResults": opts.msgMoreResults, "msgNoResults": opts.msgNoResults}));
                this.show();
            },
            template: '<ul>....</ul>'
    });
});
```
