### ISSUE TITLE
Content doesn't expand when window is resize and offcanvas is open

### ISSUE THREAD

**Issue by acaron** [uikit/uikit#1338]
When you open the offcanvas menu, you can resize the window but the content doesn't follow. When you close the offcanvas menu, the content reajust to the current width.

**Comment by PixelT** [comment]
It's not a bug ;)
https://github.com/uikit/uikit/issues/589

**Comment by acaron** [comment]
Well, I think it should. If I put my browser window size at half of my screen size, it trigger the bug. I just have to stretch it a little bit to see the bug and it often happens that I switch from half to full screen (with keyboard commands). And I have a 15 inch retina Macbook Pro so it means that my screen resolution is not small or weird.

Also, what if the off-canvas is use as the main menu even for desktop website? It happens often in admin panels where you can have big graph with statistics so you want to have a minimal menu and a more complete one hidden.

**Comment by malles** [comment]
This is indeed not a bug, the overhead of remeasuring on resize is not worth it for these corner cases.
Try this setup for a sidebar on large screens: http://codepen.io/malles/pen/YXNLJN
