### ISSUE TITLE
uk-grid-divider problem

### ISSUE THREAD

**Issue by ubafay** [uikit/uikit#134]
I have the following code

   <div class="uk-grid uk-grid-divider" data-uk-grid-margin>
    <div class="uk-width-1-10">a </div>
    <div class="uk-width-8-10">b </div>
    <div class="uk-width-1-10">c </div>
  </div>

But, with the divider included, the width of the page increases so much that the horizontal scrollbar appears. Following is the image of my test page in chrome.

![1](https://f.cloud.github.com/assets/5506143/1416003/b65da90e-3f2e-11e3-8275-93943f340077.gif)

If I remove the uk-grid-divider, the scrollbar disappears and all my content fits in the available width. I want to use uk-grid-divider but without this horizontal scrollbar. Can anyone guide me where I am doing wrong ?

**Comment by catalin-enache** [comment]
@saschadube thanks, good hint !
