### ISSUE TITLE
First item in flex container is different height than the rest

### ISSUE THREAD

**Issue by chrisscaresme** [uikit/uikit#1340]
..when I put the flex container inside a grid container. What's causing this?

https://jsfiddle.net/mru0sc0L/

Thanks!

**Comment by malles** [comment]
It's because two panels in a grid get margin applied:
```
.uk-grid+.uk-grid, .uk-grid-margin, .uk-grid>*>.uk-panel+.uk-panel {
  margin-top: 25px;
}
```
https://github.com/uikit/uikit/blob/master/src/less/core/grid.less#L134

Solve it by not using `uk-grid` or add `uk-margin-remove` to your panel. https://jsfiddle.net/mru0sc0L/2/

**Comment by chrisscaresme** [comment]
Thanks!
