### ISSUE TITLE
Datepicker doesn't close on focusOut

### ISSUE THREAD

**Issue by drschreaber** [uikit/uikit#1342]
Related to bug https://github.com/uikit/uikit/issues/713 which fixed popping the datepicker when focused with the tab key; however, the dickerpicker doesn't hide when it loses focus using the tab key.

workaround is:
````javascript
$('.datepicker').each(function () {
    var datepicker = $.UIkit.datepicker(this);
    $(this).focusout(function () {
      setTimeout(function() {datepicker.hide();}, 100);
    });
});
````

[EDIT]: note, however, this workaround makes the dropdown hide when you try to change months, which makes it a pretty bad solution...

JSFiddle here: 
http://jsfiddle.net/dr_schreaber/y4snvyjm/1/

**Comment by malles** [comment]
Is solved in next version. Thank you.
