### ISSUE TITLE
The accoridon effect of uk-nav doesn't work

### ISSUE THREAD

**Issue by dotamin** [uikit/uikit#1343]
I am new to Uikit. maybe i missed something, but adding "data-uk-nav" tag doesn't work. i tried to copy the example code of docs, but the problem remains.
here is my code:

```
<head>
    <title>Index Page</title>
    <link rel="stylesheet" href="uikit/css/uikit.css" />
    <link rel='stylesheet' href='css/custom.css' />
    <script type="text/javascript" src="uikit/js/uikit.min.js" /></script>    
</head>
.
.
<ul class="uk-nav uk-nav-side uk-nav-parent-icon" data-uk-nav="">
	<li class="uk-parent uk-active"><a href="#">Network</a>
		<ul class="uk-nav-sub">
			<li>WAN</li>
            		<li>LAN</li>
                </ul>
	</li>
	<li class="uk-parent">
		<a href="#">Security</a>
		<ul class="uk-nav-sub">
			<li>Firewall</li>
			<li>Content filter</li>
		</ul>
	</li>
</ul>
```

im using firefox 36 and Uikit 2.21. is this my code or a bug ?
thanks

**Comment by malles** [comment]
Just pasting your code in a default uikit codepen works fine: http://codepen.io/malles/pen/waBgEK

**Comment by malles** [comment]
You are missing jquery in your example. Make sure you include it before Uikit. 
Check out the developer console when in doubt.

**Comment by dotamin** [comment]
ah, so easy ! thank you
this mistake took me a day and a half. actually, the Uikit doc didn't mention that jquery is needed ! ( maybe i didnt see ! )

thanks again :)

**Comment by malles** [comment]
In that case especially, keep your javascript console (F12) open when you have trouble. It sais in big red warnings that UIkit need jQuery. But it's always useful to look there.
It is [in the docs](http://getuikit.com/docs/documentation_get-started.html#html-page-markup), but easy to miss.
Good luck!
