### ISSUE TITLE
Sticky boundary don't work correctly

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1344]
I have a problem with the sticky component. everything works totally fine, except the elements that were bound to the parent (or anything else) container.

The bound element does not move until the bottom of the parent container. It stops much earlier.

I know it could be a problem on my side, but i have no idea what it could be. Deactivation of all non UIkit or jQuery Javascripts hasn't solved the problem. You can see it on the following pictures. First one is a scrollspy menu, which stops too early and the other pics shows a copy of the sticky-component test site. As you can see the bound elements don't scroll to the end.

![scrollspy](https://cloud.githubusercontent.com/assets/5873526/8239278/2750987a-15fb-11e5-9929-edbcd9847287.png)
![scrollspy1](https://cloud.githubusercontent.com/assets/5873526/8239280/27559398-15fb-11e5-8bcc-b1415626a46e.png)
![scrollspy2](https://cloud.githubusercontent.com/assets/5873526/8239279/2753c0ea-15fb-11e5-9199-bbf940f60ffe.png)

**Comment by malles** [comment]
Are the parent containers that the stickies are bound to the full height? Try `uk-grid-match` on your grids.

**Comment by Riddler84** [comment]
Yes, both div's in the grid (left + right) has the same height. Unfortunately, `uk-grid-match` doesn't change anything. It stops before it reaches the end of the parent container, i can see this very clearly with the elements inspector in Chrome.

**Comment by malles** [comment]
I'd really need a live example to inspect it. Can you recreate it in a codepen, or make it public?
You van use [this pen](codepen.io/malles/pen/qdjXRM) as a base, it already has a sticky panel.

**Comment by Riddler84** [comment]
Ok, finally i found the error (or my mistake ;))

http://codepen.io/anon/pen/bdorLb?editors=110

As you can see, the menu doesn't scroll to the bottom of the parent container. It's because of the wrapping `.site-container`, which has a relative positioning. It seems that the height of the first panel on top is then added to the calculation.
