### ISSUE TITLE
data-uk-grid-match almost works with Slider component, but not quite

### ISSUE THREAD

**Issue by ericbrissette** [uikit/uikit#1347]
It looks like infinite scrolling duplicates the Slider items twice.  For example, if you have a 6 slides, 18 elements end up in the code.  data-uk-grid-match works on the initial set of items (the first 6 in this example), but not the duplicates (the final 12).  It works fine with infinite scrolling disabled, of course.

Here's a Pen to illustrate:
http://codepen.io/anon/pen/PqKbEp

**Comment by malles** [comment]
The slider would need a big rewrite to fix this and other issues. It is on our todo list.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Slider has not yet been released for UIkit3, we are already working on that.

Thanks for your understanding,
Your UIkit Team
