### ISSUE TITLE
Provide `large` option for alerts

### ISSUE THREAD

**Issue by dunal** [uikit/uikit#1351]
Would be nice if UIkit.modal.alert(text, { large: true }); show a modal dialog with `uk-modal-dialog-large` class.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has not been added to the new modal component and would be needed to be done via custom CSS code.

Thanks for your understanding,
Your UIkit Team
