### ISSUE TITLE
form password component and jquery validator

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1353]
Hi, I could not make the form password component play nicely with the well-known jquery.validator (with default settings) (at http://jqueryvalidation.org/validate/)

I could only use one of the scripts, not both of them.

**Comment by tbba** [comment]
Same problem is with the great new validation plugin, formvalidation.io.
There is a jsfiddle there, which shows the problem:
https://github.com/formvalidation/support/issues/256

**Comment by nghuuphuoc** [comment]
The problem isn't caused by UIKit.
Here are [2 solutions](https://github.com/formvalidation/support/issues/256#issuecomment-130261999) including the working jsfiddles show how to integrate FormValidation with UIKit form-password component.

**Comment by malles** [comment]
@nghuuphuoc Great, thanks!
