### ISSUE TITLE
Off-canvas open trigger

### ISSUE THREAD

**Issue by Genett** [uikit/uikit#1354]
Hi! I'm going to make custom parallax component in my UIkit project. It works well but if someone will open off-canvas then my parallax will become very bad. I have found a solution when I wrote something in the JS console but I want do it when off-canvas will be opening.

Now it's question: have UIkit a off-canvas open/click trigger?

**Comment by malles** [comment]
Yes, there are triggers: http://getuikit.com/docs/offcanvas.html#javascript

Use them like
```
$('#offcanvas').on('show.uk.offcanvas', function () {
    //do your magic
});
```

**Comment by Genett** [comment]
OK, Thank you!
But it haven't solved my problem because this component resets the scrollbar and the parallax plugin thinks that you are in top of a page and shows another part of the parallax image (even UIkit parallax component does the same)

Off-canvas is a really bad component because I have more problems with it. Attached Navbar, for example, doesn't shifts with the main content (you can see it at some YOOTheme themes: http://goo.gl/EPWHZb). Are you going to fix it?
Thanks =)

**Comment by malles** [comment]
The offcanvas component will be completely reworked in UIkit 3. For now you'd have to work with the current design with it's limitations.
