### ISSUE TITLE
Date picker doesn't scroll inside independent scroll block

### ISSUE THREAD

**Issue by philbuchanan** [uikit/uikit#1357]
When using `overflow-y: scroll;` on a div, the date picker dropdown doesn't scroll with the content. It instead remains positioned relative to the body element. The result is that the date picker dropdown isn't connected to the form input.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Datepicker has not been released yet please take a look as soon as it is launched if this problem still occurs.

Thanks for your understanding,
Your UIkit Team
