### ISSUE TITLE
Switcher item feature

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1358]
HELLO ;) 
Switcher items doesn't have this feature:

i want to create a Switcher that just work with buttons ``` data-uk-switcher-item ``` attributes and all of ``` <ul data-uk-switcher="{connect:'#my-id'}"> ``` children get ``` uk-disabled ``` and when i click on button to next or previous that ``` li ``` get ``` uk-active ``` and other again get ``` uk-disabled ```.

how to create this feature.

many thanks.

**Comment by zslabs** [comment]
This seems like a rather specific request -- you can build this yourself using sortable's event system:

    $('[data-uk-switcher]').on('show.uk.switcher', function(event, area){
        console.log("Switcher switched to ", area);
    });

With the `area` attribute being mapped to your specific button, you could toggle all other buttons to be `uk-disabled` and the active one removing that class.

**Comment by miladmeidanshahi** [comment]
the main problem is that when ``` uk-disabled ``` added to ``` li ``` the buttons doesn't work their functions stopped.

**Comment by zslabs** [comment]
Right - you'd fall down into the specific selector you want to modify and only add/remove the `uk-disabled` class there. The `area` param returns the current item, but you can still map that to a select and go inside the DOM further.

**Comment by malles** [comment]
@zslabs Thanks!
