### ISSUE TITLE
Header not correctly displayed

### ISSUE THREAD

**Issue by NightFalcon650** [uikit/uikit#1362]
I installed moodle and the uikit theme.
Everything works fine and i selected a picture as a background for my header.
But when i call the page you see the header but its not showed the correct way.
Like u can see on the picture.

![screendump header issue](https://cloud.githubusercontent.com/assets/7109209/8377331/b3f9739e-1c10-11e5-9358-1e04a0f9ddad.png)

The picture start left and ends almost at the end and there they start over again. (the beginning part that is)

Whats wrong and how can i correct this, so the picture is over the total length of the header???

**Comment by malles** [comment]
You can try the [cover component](http://getuikit.com/docs/cover.html) to spread the background image over the header.

**Comment by NightFalcon650** [comment]
i'm going to try that, but the strange part is that this should work, i only installed the theme, changed the background of the header through the menu's and didn't changed or made code of my own.

So why is it projected like this?

**Comment by malles** [comment]
Default behaviour of [css background properties](http://www.w3schools.com/cssref/css3_pr_background.asp) would be the answer to that. 
I don't know in what menu you changed the background of the header, but that seems not to do the trick properly.

**Comment by NightFalcon650** [comment]
i added the line:
background-size: 100% 100% 
And got the background image like it suposed to be.
But i'm not that fermiliar with this, so it doesn't save the changes, because i did it in chrome.

![screendump header issue 2](https://cloud.githubusercontent.com/assets/7109209/8387652/a03ed8b8-1c5a-11e5-9409-ffc1630da991.png)

In wich file should i add this line, so that it's stays this way????

**Comment by malles** [comment]
That really depends on the framework you're working on. This is really a question for them to answer.
