### ISSUE TITLE
Links in the sortable are triggered twice

### ISSUE THREAD

**Issue by assimovt** [uikit/uikit#1363]
I have noticed that any link inside the sortable element is triggered twice. This causes problems with, for example, confirmation dialog links. What's the purpose of [this line of code](https://github.com/uikit/uikit/blob/master/src/js/components/sortable.js#L169).

**Comment by malles** [comment]
Those lines prevent the anchor from navigating away when you pick it up to move. Then on mouseup the click is triggered when there was no move and the click was intended to click the link.
The _event_ `click` is triggered twice because of that, but the actual link is only triggered once.

**Comment by malles** [comment]
Best way to prevent trouble with this double triggering of links inside sortable elements is to use [Sortable handles](http://getuikit.com/docs/sortable.html#sortable-handle) in your sortables, or mark the elements (' parents) you don't want to fire the drag-events with the `uk-sortable-nodrag` class.

**Comment by assimovt** [comment]
Thanks, I have tried it. However, as soon as I add the handle I am getting this error:

```Uncaught ReferenceError: $link is not defined``` triggered by ths line:

```$link   = $target.is('a[href]') ? $target:$target.parents('a[href]');```

**Comment by malles** [comment]
Do you have an example in codepen for that? You could fork [this one](http://codepen.io/malles/pen/pvLOyb) as a setup.
