### ISSUE TITLE
Use requestAnimationFrame for resize listeners

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1366]
I think we should kill the normal resize listener as proposed by https://developer.mozilla.org/en-US/docs/Web/Events/resize and use their requestAnimationFrame() function. This one even provides a setTimeout fallback, but we should obviously recommend IE9 users use a [requestAnimationFrame polyfill](https://gist.github.com/paulirish/1579671). So --- no backwards compatibility breaks, with more responsive resize events since they would not be done alongside DOM manipulations. cc @saschadube @aheinze 

    var optimizedResize = (function() {

        var callbacks = [],
            running = false;

        // fired on resize event
        function resize() {

            if (!running) {
                running = true;

                if (window.requestAnimationFrame) {
                    window.requestAnimationFrame(runCallbacks);
                } else {
                    setTimeout(runCallbacks, 66);
                }
            }

        }

        // run the actual callbacks
        function runCallbacks() {

            callbacks.forEach(function(callback) {
                callback();
            });

            running = false;
        }

        // adds callback to loop
        function addCallback(callback) {

            if (callback) {
                callbacks.push(callback);
            }

        }

        return {
            // public method to add additional callback
            add: function(callback) {
                if (!callbacks.length) {
                    window.addEventListener('resize', resize);
                }
                addCallback(callback);
            }
        }
    }());

    // start process
    optimizedResize.add(function() {
        console.log('Resource conscious resize callback!')
    });

**Comment by zslabs** [comment]
@aheinze Just to append onto the requestAnimationFrame scroll listener push, it seems like this would be a good time to implement a better throttle/debounce core method by using the above as well as a replacement.

**Comment by aheinze** [comment]
done for UIkit 2.23.0

**Comment by zslabs** [comment]
Awesome thanks man!
