### ISSUE TITLE
Slider is missing autoplay feature

### ISSUE THREAD

**Issue by pimduijst** [uikit/uikit#1367]
All the slide-'ish' components like slideset and slideshow have an autoplay feature. Why is slider not having one? Is this a feature easily to be added to this amazing lib?

Kind regards,

Pim

**Comment by windvlaag** [comment]
+1

2015-06-30 21:07 GMT+02:00 pimduijst <notifications@github.com>:

**Comment by malles** [comment]
Will be in next release!

**Comment by pimduijst** [comment]
Is this already enabled?

**Comment by malles** [comment]
No it is not released yet. If you can't wait, replace the contents of your slider.js with the [develop version](https://raw.githubusercontent.com/uikit/uikit/develop/src/js/components/slider.js).

**Comment by pimduijst** [comment]
ah yes I can do that, I saw it already in the dev version but wasn't sure it was also merged in the master. When will it offically be released?
