### ISSUE TITLE
UIkit.modal.alert not blocking when used with jQuery AJAX

### ISSUE THREAD

**Issue by inet2800** [uikit/uikit#1368]
It appears UIkit.modal.alert has a bug when called from jquery $.post. It simply does not block and wait for the user to click "OK". The code below the UI alert displays briefly and quickly goes to the redirection. 

Standard Javascript alert works fine. 

For example:

$.post('test.php', post_data, function(response) {
UIkit.modal.alert(response.text);
$(location).attr('href', '/home');
}, 'json');

**Comment by malles** [comment]
Pass code you want to execute when user clicks OK to the second argument of alert as a function.
```
$.post('test.php', post_data, function(response) {
  UIkit.modal.alert(response.text, function () {
    $(location).attr('href', '/home');
  });
}, 'json');
```

**Comment by inet2800** [comment]
malles,

Thank's just tried it, same result. 

You can see the alert, but it does not block. It works fine everywhere else but inside a $.post

**Comment by malles** [comment]
Ah I see now. `UIkit.modal.alert` is not meant to be blocking. Use `UIkit.modal.confirm` instead.
```
$.post('test.php', post_data, function(response) {
  UIkit.modal.confirm(response.text, function () {
    $(location).attr('href', '/home');
  });
}, 'json');
```

**Comment by aheinze** [comment]
what is ```$(location).attr('href', '/home');``` ? do you want to go to another url? then the correct code would be ```location.href = '/home';```

**Comment by inet2800** [comment]
$location.attr('href', '/home') is a destination URL. The thought was to use alert to confirm the transaction and then re-direct. Unfortunately confirm will not work for our requirement since the user has no option to cancel. We solved the issue by simply redirecting to an info page.

**Comment by malles** [comment]
Pasting this snippet in the console on any UIkit-docs page gives the desired behaviour, it only redirects when the OK button is clicked, dismisses without redirect when cancelled:
```
UIkit.modal.confirm('Make a choice!!', function () {
    console.log('only when ok');
    location.href = '/';
});
```
