### ISSUE TITLE
Dropdown with Multiple checkbox select

### ISSUE THREAD

**Issue by sadashivm** [uikit/uikit#1371]
Hi UiKit Team,
         u did awesome framework for developers and compared to bootstrap ur given full feature and functionality. and one more i request to you pls develop Dropdown with Multiple checkbox select option, for example find bellow one link
http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

i dont want to use external plugin for developement. i want to use only one that is your file . so pls develeop it

**Comment by miladmeidanshahi** [comment]
+1

**Comment by Intiligent** [comment]
+1

**Comment by fahimshahriyer** [comment]
+2

**Comment by jackswei** [comment]
+1

**Comment by Pandahisham** [comment]
+1

**Comment by ZeGregg** [comment]
+1

**Comment by CoalaWeb** [comment]
+1

**Comment by chagamkamalakar** [comment]
+10

**Comment by seemsindie** [comment]
+1

**Comment by Litvinenko** [comment]
+1

**Comment by nblackburn** [comment]
+1

**Comment by yaelduckwen** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by daniakbar** [comment]
+1

**Comment by Septdir** [comment]
+1

**Comment by 3vi21** [comment]
+1

**Comment by devalentino** [comment]
+1

**Comment by ukrainecmk** [comment]
+1

**Comment by sjys** [comment]
+1

**Comment by giovannimazzuoccolo** [comment]
+ 1

**Comment by luetn** [comment]
+1

**Comment by kartik7153** [comment]
+1

**Comment by yashkudalkar** [comment]
+1

**Comment by bojanpejanovic** [comment]
+1

**Comment by zidski** [comment]
+1

**Comment by unpoetic-circle** [comment]
+1

**Comment by philoest** [comment]
This is quite a big component JS from the JavaScript side, here we would recommend to use on of the existing JavaScript projects that dedicated to that. As an example there is [Select2](https://select2.github.io/examples.html) and [Chosen](https://harvesthq.github.io/chosen/).

**Comment by ruchern** [comment]
@philoest Chosen breaks the whole "UIKit" looks.
