### ISSUE TITLE
Question: Is it possible to have equally spaced (rather than equal width) columns in a table?

### ISSUE THREAD

**Issue by pdomzal** [uikit/uikit#1374]
uikit is great! Thank you in  advance for your help!

**Comment by malles** [comment]
I don't think you question is clear. What do you mean exactly? Do you have an example?

**Comment by pdomzal** [comment]
Hi Matthijs, in other words, in a grid, is it possible to have columns that adjust automatically to the width of the content and are equally spaced (have the same gutter). Somewhat like the navbar-nav items, that are different widths but equally spaced.

**Comment by malles** [comment]
Ah, that would need the [flex classes](http://getuikit.com/docs/flex.html). Play around with the classes and modifiers. You'll need `uk-flex-space-between` for a start.
