### ISSUE TITLE
panel resize and out text from box

### ISSUE THREAD

**Issue by spouk** [uikit/uikit#1375]
When you change the size of the screen text, if together, leaving the text comes out of the block. I think it's a bug. Fix - add style
break-word: break-all;
----
```
<div class="uk-panel uk-width-1-1">
    <div class="uk-panel-box uk-width-1-10">
        uk-width-1-2
    </div>
</div>
```
----
fix
--
```
<style> 
.break {
    word-break: break-all;
}
</style>
<div class="uk-panel uk-width-1-1">
    <div class="uk-panel-box uk-width-1-10 break">
        uk-width-1-2
    </div>
</div>
```

**Comment by malles** [comment]
I don't think this is desired default behaviour. You can use the `.uk-text-break` class from the [text component](http://getuikit.com/docs/text.html) to break long words.

**Comment by spouk** [comment]
ok. tnx fast answer
