### ISSUE TITLE
Supporting only Woff and Woff2 fonts

### ISSUE THREAD

**Issue by anthony-redFox** [uikit/uikit#1376]
Why are you using eot and ttf fonts?
Woff font support browsers - http://caniuse.com/#feat=woff
And remove FontAwesome.otf.
@font-face {
    font-family: 'FontAwesome';
    src: url("@{icon-font-path}/fontawesome-webfont.eot"); /* IE9 Compat Modes */
    src: url("@{icon-font-path}/fontawesome-webfont.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */
         url("@{icon-font-path}/fontawesome-webfont.woff2") format('woff2'),
         url("@{icon-font-path}/fontawesome-webfont.woff") format("woff"),
         url("@{icon-font-path}/fontawesome-webfont.ttf") format("truetype"); /* Old Safari <5.1, Old Android <4.4, Old iOS <5.1 */

**Comment by aheinze** [comment]
android < 4.4 is pretty common, so ttf won't removed but eot could be removed.
