### ISSUE TITLE
Feature Request - Category View options.

### ISSUE THREAD

**Issue by nsheehan** [uikit/uikit#1377]
Love the Theme, we use a YooTheme on the main site, having the same kit for Moodle makes things much easier. 

The one area that could use some updates is the Category layout (main page for example). The Essential Theme does a nice job with the Icon view, it's clean an uncluttered. The Uikit has ZERO options, I can't even seem to change the default view from Show All to Collapse All, or a way of limiting the number of Categories displayed to keep things manageable.

If there is a work around to display the list collapsed, that would help, however the best option would be to allow the user to have some control over how Categories are displayed on the Front Page.

Thank you/

**Comment by malles** [comment]
This question does not seem UIkit related.
