### ISSUE TITLE
Modal Window - body scrolls to top when body or html height is 100%

### ISSUE THREAD

**Issue by DerBeni** [uikit/uikit#1379]
Hi,
...i'm trying to use the modal window on a single page which different sections have an height of 100% each. To do so i'm unsing the uikit-tag "uk-height-1-1" for body and html containers too. So far so good.

...but the whole page is skipping to the top of the page when opening the uikit modal window and thats's really "not nice".

Does somebody know how to prevent this? A fix for the modal window?

**Comment by malles** [comment]
It's caused by a conflict between the modal's overlay and the 100% height on the body element. 
Prevent it by using the `uk-height-viewport` on the actual elements you want to have the full height. Remove the height classes from body and html.

**Comment by DerBeni** [comment]
Hi Malles,
...thats was my conclusion too but theres a small advantage for the "100% height method". When scrolling on iPad or iPhone and using uk-height-viewport, full size sections do resize when the tabs of the browsers dissapear from scrolling. Anyway... thanks for your advice...

**Comment by xthukuh** [comment]
Just in case anyone else goes through what I went through, just set the css as follows:

```
body {
	overflow: hidden;
}
html {
	overflow-y: auto;
}
```

**Comment by xthukuh** [comment]
and use css height: 100vh; instead of uk-height-1-1

**Comment by douglashb** [comment]
You can find the solution here:

https://github.com/uikit/uikit/issues/590#issuecomment-430676248

Good luck
