### ISSUE TITLE
Close offcanvas from javascript

### ISSUE THREAD

**Issue by pankappa** [uikit/uikit#138]
There is a way to close offcanvas from javascript?

I try this but don't work

< a onclick="jQuery('#my-offcanvas-id').hide()" > 
   close
< /a >

thanks!

**Comment by chisholmd** [comment]
I don't understand the solution.  In your example that you said did not work you reference the element id #my-offcanvas-id
In your solution you said this worked:
jQuery.UIkit.offcanvas.offcanvas.hide()

So did you change the ID of your element to 'offcanvas'? Or does calling that close all off canvas items?  Or does it automatically close parent offcanvas items so you can only call it from within?

**Comment by pankappa** [comment]
This solution is for old version of uikit
jQuery.UIkit.offcanvas.offcanvas.hide ()

try this
jQuery.UIkit.offcanvas..hide ()

**Comment by chisholmd** [comment]
jQuery.UIkit.offcanvas.hide('#my-offcanvas-id')

**Comment by malles** [comment]
I'd go for `UIkit.offcanvas(UIkit.$('#offcanvas')).hide()`.

But why the sudden interest in this issue?

**Comment by SC-74** [comment]
UIkit.offcanvas('#my-offcanvas').hide();
