### ISSUE TITLE
Dynamic Grid in Tab have Layout error

### ISSUE THREAD

**Issue by jackswei** [uikit/uikit#1380]
Dynamic Grid in Tab have Layout error
![lyerror](https://cloud.githubusercontent.com/assets/6355204/8611998/2558e81c-26fc-11e5-8344-5a558049ef44.png)
 ,The first presentation will be wrong population, ordered after the normal filter

**Comment by malles** [comment]
Do you have a live example of this? Or can you reproduce it in a [codepen](http://codepen.io)?

**Comment by jackswei** [comment]
http://codepen.io/weichich/pen/mJKLgE

SEE LayoutError,tks

**Comment by malles** [comment]
The main solution is to put a `data-uk-check-display` attribute on the element that has `data-uk-grid`: 
`<div id="example" data-uk-grid="{gutter: 20, controls: '#filter'}" data-uk-check-display>`. This forces it to recalculate the dimensions when it becomes visible.
Check out this codepen: http://codepen.io/malles/pen/rVrNzM. I did quite some cleanup. Remove all `aria-*`, `data-uk-grid-prepared` and `style` attributes from your elements. These are added by the javascript later.

**Comment by jackswei** [comment]
Thank you, has been resolved, thank you very much.
