### ISSUE TITLE
Accordion Active a panel by default

### ISSUE THREAD

**Issue by naumanahmed19** [uikit/uikit#1381]
I want to make Accordion 3rd panel active by default. 
I set   ```showfirst  : false``` and added  ```uk-active``` class but its not working

**Comment by malles** [comment]
That is not possible with the accordion. maybe it should in the future, since switcher, menu and tabs do have that option.
For now you can select the correct content-element with some javascript:
```
UIkit.on('afterready.uk.dom', function() {
  var accordion = UIkit.accordion(UIkit.$('#my-accordion')),
      wrapper = accordion.find('[data-wrapper]').get(2); //2 as index of the content
  accordion.toggleItem(UIkit.$(wrapper), true, true);
});
```
Demo in this codepen: http://codepen.io/malles/pen/bdMMGB?editors=101

**Comment by mdversion01** [comment]
Is there a way to get the above working in ReactJS when using UIkit with React?
