### ISSUE TITLE
Option to disable swipe handling in Switcher

### ISSUE THREAD

**Issue by roll** [uikit/uikit#1382]
For now it breaks maps, responsive tables etc inside the tab.

**Comment by ffuentes** [comment]
+1

Using uk-overflow-container to display an extended table, should override swipe behaviour in small touch screens.

**Comment by roll** [comment]
As a workaround something like:
```
$('#switcher').off('swipeLeft').off('swipeRight');
```

**Comment by zslabs** [comment]
+1 didn't even realize this was happening until you mentioned it.

**Comment by zslabs** [comment]
I actually needed to override the function entirely due to the dynamic nature of my application. Would really appreciate a more reliable solution @aheinze 

    UIkit.on('beforeready.uk.dom', function() {
      return $.extend(UIkit.components.switcher.prototype.init = function() {
        var $this, active, toggles;
        $this = this;
        this.on('click.uikit.switcher', this.options.toggle, function(e) {
          e.preventDefault();
          $this.show(this);
        });
        if (this.options.connect) {
          this.connect = UIkit.$(this.options.connect);
          this.connect.find('.uk-active').removeClass('.uk-active');
          if (this.connect.length) {
            this.connect.children().attr('aria-hidden', 'true');
            this.connect.on('click', '[data-uk-switcher-item]', function(e) {
              var item;
              e.preventDefault();
              item = UIkit.$(this).attr('data-uk-switcher-item');
              if ($this.index === item) {
                return;
              }
              switch (item) {
                case 'next':
                case 'previous':
                  $this.show($this.index + (item === 'next' ? 1 : -1));
                  break;
                default:
                  $this.show(parseInt(item, 10));
              }
            });
          }
          toggles = this.find(this.options.toggle);
          active = toggles.filter('.uk-active');
          if (active.length) {
            this.show(active, false);
          } else {
            if (this.options.active === false) {
              return;
            }
            active = toggles.eq(this.options.active);
            if (active.length) {
              this.show(active, false);
            } else {
              this.show(toggles.eq(0), false);
            }
          }
          toggles.not(active).attr('aria-expanded', 'false');
          active.attr('aria-expanded', 'true');
          this.on('changed.uk.dom', function() {
            $this.connect = UIkit.$($this.options.connect);
          });
        }
      });
    });

**Comment by zslabs** [comment]
Thanks @aheinze

**Comment by plotnikov-maxym** [comment]
Could You add this option for data-uk-tab also? Because it's the same issue itself and swiping='false' doesn't work here!

**Comment by harebuus** [comment]
I find this solution for uikit 3:
`var slider = UIkit.slider('.uk-slider');`
`slider._events[2](function (unbind) {return unbind();});`

**Comment by bilal1112** [comment]
> I actually needed to override the function entirely due to the dynamic nature of my application. Would really appreciate a more reliable solution @aheinze
> 
> ```
> UIkit.on('beforeready.uk.dom', function() {
>   return $.extend(UIkit.components.switcher.prototype.init = function() {
>     var $this, active, toggles;
>     $this = this;
>     this.on('click.uikit.switcher', this.options.toggle, function(e) {
>       e.preventDefault();
>       $this.show(this);
>     });
>     if (this.options.connect) {
>       this.connect = UIkit.$(this.options.connect);
>       this.connect.find('.uk-active').removeClass('.uk-active');
>       if (this.connect.length) {
>         this.connect.children().attr('aria-hidden', 'true');
>         this.connect.on('click', '[data-uk-switcher-item]', function(e) {
>           var item;
>           e.preventDefault();
>           item = UIkit.$(this).attr('data-uk-switcher-item');
>           if ($this.index === item) {
>             return;
>           }
>           switch (item) {
>             case 'next':
>             case 'previous':
>               $this.show($this.index + (item === 'next' ? 1 : -1));
>               break;
>             default:
>               $this.show(parseInt(item, 10));
>           }
>         });
>       }
>       toggles = this.find(this.options.toggle);
>       active = toggles.filter('.uk-active');
>       if (active.length) {
>         this.show(active, false);
>       } else {
>         if (this.options.active === false) {
>           return;
>         }
>         active = toggles.eq(this.options.active);
>         if (active.length) {
>           this.show(active, false);
>         } else {
>           this.show(toggles.eq(0), false);
>         }
>       }
>       toggles.not(active).attr('aria-expanded', 'false');
>       active.attr('aria-expanded', 'true');
>       this.on('changed.uk.dom', function() {
>         $this.connect = UIkit.$($this.options.connect);
>       });
>     }
>   });
> });
> ```

thanks, it solves my problem
