### ISSUE TITLE
Problem with sortable and select

### ISSUE THREAD

**Issue by key4625** [uikit/uikit#1383]
Hi! 

I've a problem with a select option placed in a div that is a sortable items. 

I can't open the combo box. 

My code is like this..,.

`<div class="uk-sortable" data-uk-sortable>
  <div style="margin:10px; height:32px;">
           <select name="..."><option></option><option></option></select>
  </div>
</div>`

Can you help me? I've tested with Chrome browser and explorer...

Thank you.

**Comment by malles** [comment]
Try to add a separate handle for the sortable, that usually solves these issues.
http://getuikit.com/docs/sortable.html#sortable-handle

**Comment by key4625** [comment]
Perfect! Now it is ok! Thank you so much!
