### ISSUE TITLE
uk-tab-bottom don't work with uk-tab-center

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1384]
If i use `uk-tab-bottom` in a centered tab menu, it won't work as expected.

Look here:
http://codepen.io/Riddler84/pen/aOKOKZ

**Comment by malles** [comment]
Place the `uk-tab-center` class on the `uk-tab`-ul itself: `<ul class="uk-tab uk-tab-center uk-tab-bottom" data-uk-tab="{connect:'#my-id'}">`. You can remove the surrounding div.

**Comment by Riddler84** [comment]
Ok thanks, but it's nevertheless a bug in UIKit or am i wrong?
It's not an problem to me personally. I have found it more or less accidentally.

I only used the code from the UIkit Docs in the codepen example and it don't work as it should be. You can't combine uk-tab-center with uk-tab-bottom. The border-line is then on the wrong side.

**Comment by malles** [comment]
Great! Use the both on the parent div, and it works fine:
```
<div class="uk-tab-center uk-tab-center-bottom">
    <ul class="uk-tab uk-tab-bottom" data-uk-tab="{connect:'#my-id'}">
      <li><a href="">Tab 1</a></li>
      <li><a href="">Tab 2</a></li>
      <li><a href="">Tab 3</a></li>
      <li><a href="">Tab 4</a></li>
    </ul>
</div>
```
No need for the change in the PR then. Docs need to be more clear here.

**Comment by Riddler84** [comment]
Shame on me ;) I hadn't thought on this simple solution.. thanks!
