### ISSUE TITLE
Responsive datepicker

### ISSUE THREAD

**Issue by gtcole** [uikit/uikit#1386]
Possibly a silly question, should the datepicker be responsive?

I have added it to a site where the input field is on the right of the screen, this works fine on my screen but as soon as i resize to a standard user screen (1024x768 here) the datepicker seems to fall out of the right creating a scroll bar, if not, would it be possible to add additional positions such as bottom left, or top left etc?

Thanks in advanced

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Datepicker has not been released yet please take a look as soon as it is launched if this problem still occurs.

Thanks for your understanding,
Your UIkit Team
