### ISSUE TITLE
Slideshow: Performance Question

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#1387]
Should slideshow in autoplay mode be paused when it is outside the viewport?
Just thinking about performance issues. But that is maybe not an issue at all => ?

**Comment by malles** [comment]
Interesting question. The images in the slideshow are loaded anyways, so that should make no difference. 
It would be the difference between checking if the element is visible or not and sliding the slideshow.
My 10 cents says it makes no difference in the end.

**Comment by aheinze** [comment]
should be no difference
