### ISSUE TITLE
Slideshow fade animation not working on Safari

### ISSUE THREAD

**Issue by juliuslaas** [uikit/uikit#1389]
The slideshow seems to be not working on Safari when the "fade" animation is selected, it only displays the first slide. However, when I changed the animation to "scroll" the slider functionality will work except for the animation.

**Comment by luetn** [comment]
Just tested "fade" with Safari Version 8.0.7 on OS X 10.10.4.
Seems to work as it should

**Comment by juliuslaas** [comment]
On OS X, yes it will work, but it's not working on Safari for Windows. Even the other animation is not working smoothly.

**Comment by luetn** [comment]
I would suggest to stop testing the windows version of safari.
As far as I know Apple stopped updating the windows version of safari back in 2012.

**Comment by malles** [comment]
@luetn Thanks!
