### ISSUE TITLE
Question: How to remove data-uk attributes on mobile devices?

### ISSUE THREAD

**Issue by DerBeni** [uikit/uikit#1390]
Hi,
...what's the best way to remove data-uk Attributes on mobile devices? 

For example: I want to remove animations from the scrollspy on mobile devices and i don't want to use different html containers with "uk-visible" and "uk-hidden" classes.

I found a jQuery code and thought myself it could solve the problem:

jQuery(document).ready(function(){  
    if (jQuery(window).width() < 767) {   
        jQuery('*').removeAttr('data-uk-scrollspy');
    }  
});

...but it doesn't.

Has anyone a working solution?

**Comment by malles** [comment]
The scrollspy component does not have a media option (yet). 
Try this:
```
Uikit.on('', function () {
  if (UIkit.$win.width() < 767) {
    UIkit.$('[data-uk-scrollspy]').removeAttr('data-uk-scrollspy');
  }
});
```

**Comment by DerBeni** [comment]
Hi malles,
...where do i have to put it exactly? I always get  an "Uncaught ReferenceError: Uikit is not defined" ...

**Comment by malles** [comment]
ow sorry, I made a typo, it must be `UIkit.on...`. I edited the post now.

**Comment by DerBeni** [comment]
Thanks a lot, it works!

**Comment by piotr-cz** [comment]
Duplicate of #740

For UIkit 3:
```js
window.addEventListener('DOMContentLoaded', () => {
  if (screen.width < 640) {
    document
      .querySelectorAll('[uk-scrollspy]')
      .forEach($image => $image.removeAttribute('uk-scrollspy'))
  }
})
```
