### ISSUE TITLE
Dynamic pagination

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1391]
Is it possible dynamic change pagination (items) and redraw pagination?

**Comment by Intiligent** [comment]
Oh, i find the same issue #1267 and its was very useful for me. But for render need to init component:

```javascript

var pagination = UIkit.pagination('.uk-pagination');
pagination.options.currentPage = 1;
pagination.options.items = 180;
pagination.init();

```

**Comment by tomis0302** [comment]
bad approach!! for every init()-call an additional event 'select.uk.pagination' is thrown

**Comment by Intiligent** [comment]
Isset other solution?

**Comment by giolf** [comment]
@tomis0302 you're wrong! no additional event 'selekt.uk.pagination' are trhown.

**Comment by dwSun** [comment]
>pagination.init();
this is not documented in official docs.

**Comment by cueball6118** [comment]
@tomis0302 you're correct, @giolf  you are wrong.

Each time you "init()" the events stack up. Try their simple example 
        $('[data-uk-pagination]').on('select.uk.pagination', function(e, pageIndex){
            alert('You have selected page: ' + (pageIndex+1));
        });

you will start to get multiple alerts.

I need a way to re-init without stacking up events for a neat solution.

**Comment by Queueue0** [comment]
If anyone is still using an old enough version of UIkit for this issue to be relevant and like me finds cueball's solution unsatisfactory, first I'd like to offer my condolences. Second, here's what I ended up doing: Don't use `pagination.init()`. Instead, you can do this:

```
pagination.options.items = numberOfItems;
pagination.render(Math.ceil(numberOfItems / itemsPerPage));
```

I think this looks cleaner, and it doesn't cause events to stack up. It does require you to keep track of the total number of items and the number of items to display per page, but I personally was already doing that anyway and I suspect it's the same for a lot of people using pagination in general.
