### ISSUE TITLE
Responsive Tab gets the wrong caption when opening the dropdown

### ISSUE THREAD

**Issue by Hamcha** [uikit/uikit#1392]
Video: http://files.fromouter.space/videos/uikitbug.mp4

I don't know if this is a proper bug or just some kind of weird thing that happened because of my messy setup (and since this is work related stuff I don't have time to investigate it further or even make a "working" example).

The problem seems to lie in [/src/js/core/tab.js:85](https://github.com/uikit/uikit/blob/master/src/js/core/tab.js#L85).

Mainly in what "tab" is, which in my case is the holder of the dropdown:
!["tab" in the Webkit inspector](http://i.imgur.com/7l5HxF4.png)
!["tab" in the element viewer](http://i.imgur.com/AodkOX5.png)

So when that line invokes `.text()` on it, it gets the content of the dropdowns as well (in addition to what's currently already there, thus appending with each click).

I fixed the bug on my end by changing the previous line to

    $this.responsivetab.caption.html(tab.find("a:first").text());

Let me know if there's something (possibly not time consuming) I can do to help you fix it (or if it's just my fault and I should go to hell, that's fine too).

**Comment by malles** [comment]
Do you have it setup with a dropdown in the tabs, like this: http://codepen.io/malles/pen/oXMXPY?editors=101?
That setup as some problems when responsive, and shows the behaviour you get when you resize the screen to a small viewport when the fourth tab is active.

I think you have the responsive dropdown in your markup. You don't need to do that, it's done by the js.

**Comment by Hamcha** [comment]
No, all tabs are text with an optional badge (and the issue was present even before I added the badge)

This is what it looks on a wide enough screen:
![Tabs without the responsive takeover](http://puu.sh/j1r8N/4b490f17b9.png)

This is the code I use for generating the tabs:
```jsx
let badge = <div />;
if (typeof that.state.permissionCounter[group.Category] !== "undefined" 
		&& that.state.permissionCounter[group.Category] > 0) {
	badge = <div className="uk-badge uk-badge-notification uk-mini-badge">
		{that.state.permissionCounter[group.Category]}
	</div>;
}
return <li key={group.Category}>
		<a href="">
			{i18n.get("permission-types", group.Category)}
			{badge}
		</a>
</li>;
```

**Comment by malles** [comment]
I can't reproduce the error in the pen: http://codepen.io/malles/pen/oXMXPY?editors=101
![image](https://cloud.githubusercontent.com/assets/5442402/8728509/c55ccb2e-2be5-11e5-9022-80e7259f020e.png)
The `tab` that is passed on that breakpoint is the correct `li`, that is hidden and active, not the responsive tab.

I might have to do with the order of rendering the markup with React in play.
How and when do you init the tabs/switcher?
