### ISSUE TITLE
Progress bars: multiple bars with different coloring

### ISSUE THREAD

**Issue by whitelynx** [uikit/uikit#1394]
The Progress component already has support for changing the style of the bar with the `uk-progress-success`, `uk-progress-warning`, `uk-progress-danger`, `uk-progress-striped`, and `uk-active` classes.

It also does currently support multiple `uk-progress-bar` elements inside a single `uk-progress` (though this support seems unintentional):
```html
<div class="uk-progress">
    <div class="uk-progress-bar" style="width: 40%;">40%</div>
    <div class="uk-progress-bar" style="width: 30%; background: #ff0000">30%</div>
</div>
```

I'd like the ability to change the style on a _per-bar_ basis without manually setting style options; basically, modifying the LESS rules for `.uk-progress-success .uk-progress-bar`, etc. to also match bar-specific classes. (e.g. `.uk-progress-bar-success`) This is useful for things like showing percentages of background jobs that have succeeded, failed, or generated warnings.

**Comment by malles** [comment]
I don't see why you just shouldn't create separate bars for separate progresses;
```
<div class="uk-progress uk-progress-danger">
    <div class="uk-progress-bar" style="width: 40%;">40%</div>
</div>
<div class="uk-progress uk-progress-warning">
    <div class="uk-progress-bar" style="width: 30%;">30%</div>
</div>
```

**Comment by whitelynx** [comment]
Because the total of the bar is still 100%; it represents the same set of jobs, but some jobs may have warnings or errors, while some may succeed. When the bar fills, all jobs have completed, and you can tell by the size of each segment how many jobs had warnings or errors. Making them separate bars would just make it harder to gauge overall progress, unless you had yet _another_ bar to track that.

**Comment by whitelynx** [comment]
Also, [Bootstrap supports this](http://getbootstrap.com/components/#progress-stacked).

**Comment by aheinze** [comment]
Thank you for the suggestion, we'll discuss that.
