### ISSUE TITLE
Slideshow stutters with kenburns effect and fx-animations

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1395]
Not a big problem but also not very pretty ;)
If you use the slideshow component with a fx-animation and kenburns effect, it stutters everytime after the fx-animation is complete.

maybe the kenburns animation shouldn't start before the fx-animation is complete..

http://codepen.io/Riddler84/pen/NqBMQg?editors=110

**Comment by luxlogica** [comment]
I think this is a more serious issue in the latest version of UIKit: when a full-screen slideshow is using Ken Burns, even if just the default fade effect is being used, the slides have a 'pause' of about 20 seconds after loading for the first time. So, it happens like this:

  1. page opens, slideshow opens with first slide, and ken burns effect animates nicely.
  2. when ken burns effect finishes, the slide image 'reloads', and stays fixed on screen for about 20 seconds - no animation.
  3. the next slide starts playing, with ken burns animation going nicely. 
  4. as the animation finishes, it reloads the image and displays it statically with no animation for about 20 seconds, again.
  5. the same thing happens to every slide, as it is being shown the first time.
  6. once all slides have been shown once, then it starts again from the beginning, but this time it plays nicely all the way through - no more 20-sec pauses.

This is happening even in the UIKit slideshow test page - scroll down to the last couple of full-screen slideshows, and you will see it there:

http://getuikit.com/tests/components/slideshow.html

**Comment by luxlogica** [comment]
Ok, I checked and noticed that I was (unnecessarily) loading the 'slideshow-fx.js' file in my `<head>`. Removing it helped a lot. There still seems to be a glitch - the slides pause for an unusually long time after the animation - but at least they don't reload, so it's acceptable. But the 'slideshow-fx.js' file seems to be definitely causing some issue with Safari.

**Comment by malles** [comment]
The kenburns effect cannot work with most special effects, that is indeed true. The nature of the two animations don't allow each other.

**Comment by luxlogica** [comment]
Perhaps switching to using Velocity.js, as suggested [in this issue](https://github.com/uikit/uikit/issues/1823), would provide more flexibility, as well as better performance.
