### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'animations' of undefined" issue

### ISSUE THREAD

**Issue by davidrouten** [uikit/uikit#1400]
I'm not sure what else I need to post to get to the bottom of this, but I'm using the `gem 'uikit-sass-rails'` version 1.4.1, `//= require uikit` in `application.js`, and `*= require uikit` in `application.scss`. I'm not using the slideshow anywhere in the application.

in `development` this is the error:

    "use strict";

        var Animations = UI.slideshow.animations;

In `production` this is a piece of the error:

function(t){var e;window.UIkit&&(e=t(UIkit)),"function"==typeof define&&define.amd&&define("uikit-slideshow-fx",["uikit"],function(){return e||t(UIkit)})}(function(t){"use strict";var e=t.slideshow.animations;t.$.extend(t.slideshow.animations,{slice:function(i,n,o,s){if(!i.data("cover"))return e.fade.apply(this,arguments);for(var a,r=t.$.Deferred(),l=Math.ceil(this.element.width()/this.options.slices),u=n.data("cover").css("background-image")...

Any help would be hugely appreciated as this is breaking my app.js in production!

**Comment by andrewkdesigns** [comment]
+1 Also getting this issue, specifically from slideset.js:300

**Comment by zslabs** [comment]
Did you happen to remove the slideshow-animations file as well? That's separate from the slideshow JS file.

**Comment by andrewkdesigns** [comment]
@zslabs if I add in that file then I get two errors:

Uncaught TypeError: Cannot read property 'animations' of undefined
Uncaught TypeError: Cannot read property 'slide-horizontal' of undefined

Note, I'm using script.js.

**Comment by andrewkdesigns** [comment]
Anything new on this?

**Comment by zslabs** [comment]
Are you talking about https://github.com/cworreschk/uikit-sass-rails ? We can only support the repo here itself -- if you are getting issues with that repo you need to file an issue there.

**Comment by andrewkdesigns** [comment]
No, I'm getting the same issue as the title of this thread but am not using Sass-rails.

My Developer tools Js console log is showing the following error from slideset.js:300
```
"Uncaught TypeError: Cannot read property 'animations' of undefined" issue
```

![2015-08-05 14_08_33-action center](https://cloud.githubusercontent.com/assets/3876981/9093692/8e0d50da-3b7b-11e5-9c08-8f659381f922.png)

**Comment by zslabs** [comment]
Can you show me your complete JS tree in the order you are compiling them together?

**Comment by andrewkdesigns** [comment]
```javascript
		$script([
			'//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js',
			'/bower_components/js-cookie/src/js.cookie.js',
		], 'site-dependencies');
		$script.ready('site-dependencies', function() {
			$script('/js/main.js');
			$script('/bower_components/uikit/js/uikit.js', 'uikit');
		});
		$script.ready('uikit', function() {
			$script([
				'/bower_components/uikit/js/components/notify.js',
				'/bower_components/uikit/js/components/slideshow.js',
				'/bower_components/uikit/js/components/slideset.js',
				'/bower_components/uikit/js/components/slideshow-fx.min.js',
				'/bower_components/uikit/js/components/sticky.js',
				'/bower_components/uikit/js/components/tooltip.js',
			]);
		});
```

**Comment by zslabs** [comment]
As long as you're loading the core utils in that `uikit.js` file, then there'd be no reason to receive those errors, as I cannot dupe any errors. I agree the docs could be better on what components depend on what, but I'm not seeing anything from what you've provided that would lend to the idea of there being an issue with UIkit. If you wanted to create a [CodePen](http://codepen.io) with your setup, we could try to troubleshoot from there.

**Comment by andrewkdesigns** [comment]
I can do you one better... Here is the link to the development server: http://specialolympics.dev01.1over0.com/

**Comment by zslabs** [comment]
That's not one better... that's one worse ;)

I'd want to see the setup in the simplest case possible. Looking at it amongst everything else you have going on isn't helpful.

**Comment by andrewkdesigns** [comment]
http://codepen.io/anon/pen/ZGPzxp

There is the codepen, but really it doesn't help as there are lots of resources that can't be served off the server.

**Comment by zslabs** [comment]
Sorry if I haven't explained myself better, but if you want help with open-source tools, it's best to dumb everything down to a bare minimal example -- take anything else out of the way and recreate what with UIkit, is pretty simple to do via the docs and match them up to what you're trying. In this case, take the slideset example from the docs, put in some dumby text if needed and load the scripts as you have been (but from a CDN so we don't run into potential conflict issues) and from there, we can determine if it's user error or a potential issue with UIkit.

**Comment by denoteit** [comment]
I know this is closed, but just as an FYI I was getting the exact same issue. I'm using a custom build of JS, but the JS files were in the wrong order. I had slideshow-fx.js loading before slideshow.js.

Creating a new build of script file with **slideshow.js** followed by **slideshow-fx.js** fixed it for me.
