### ISSUE TITLE
Multiple datepickers for check-in / check-out form

### ISSUE THREAD

**Issue by wdebusschere** [uikit/uikit#1403]
We have a hotel booking form and want to limit the selectable daterange by adding a dynamic minDate and maxDate. We do this on the input field change event. It works perfect for the first run of the change event, but after the first time, minDate and MaxDate do not get updated anymore, nothing happens, change event function is executed

jQuery:
$('#date1').on('change', function() {
var minDate = moment($(this).val(), "DD/MM/YYYY").add(1,'days' );
var datepicker2 = UIkit.datepicker($('#date2'), { minDate: minDate.format("DD/MM/YYYY"),format:'DD/MM/YYYY' });
});
    
 $('#date2').on('change', function() {
var maxDate = moment($(this).val(), "DD/MM/YYYY").subtract(1,'days' );
var datepicker1 = UIkit.datepicker($('#date1'), { minDate:0, maxDate: maxDate.format("DD/MM/YYYY"),format:'DD/MM/YYYY' });
});

**Comment by malles** [comment]
`UIkit.datepicker($('#date1'), { minDate:0, maxDate: maxDate.format("DD/MM/YYYY"),format:'DD/MM/YYYY' });` initializes an instance of the datepicker, or returns the already existing instance. So calling that on change would return the existing datepicker with its options. You'll need to keep a reference to the datepickers and change their options.

See this codepen for an example: http://codepen.io/malles/pen/BNOemW?editors=101

**Comment by wdebusschere** [comment]
One word: Perfect!

**Comment by malles** [comment]
Can always be better :)
https://github.com/uikit/uikit/pull/1404
Makes the current value available in the datepicker instance. So you can do:
```
UIkit.ready(function() {
  var date1 = UIkit.datepicker(UIkit.$('#date1'), { minDate: 0, format:'DD/MM/YYYY' }),
      date2 = UIkit.datepicker(UIkit.$('#date2'), { format:'DD/MM/YYYY' });
  date1.on('change.uk.datepicker', function () {
    date2.options.minDate = date1.current.add(3,'days').format('DD/MM/YYYY');;
    date2.update();
  });
 });
```
