### ISSUE TITLE
Off Canvas and -webkit-overflow-scrolling

### ISSUE THREAD

**Issue by michaelcrosbie** [uikit/uikit#1407]
I am using GetUIKit as a framework for this website. To get scrolling on touch devices to have a bit of momentum to it, I've added the -webkit-overflow-scrolling style to the html and body tags of my CSS. However, this seems to disable the off-canvas function of GetUIKit. The menu flys out but can't be seen.

http://crvs.crosbiedesign.com

Any ideas? I'm stuck!

**Comment by alanmcginnis** [comment]
I am having the same issue with the Foundation 5 off-canvas element. I fix one thing and another one breaks. I am actively looking for  a solution to my issue which may resolve yours.

**Comment by michaelcrosbie** [comment]
Found that the solution to this was to only attribute the WebKit property to body, not to html. Give that a whirl and see if that works

**Comment by malles** [comment]
Does this issue still occur in the latest version?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
