### ISSUE TITLE
UiKit => PSD

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1409]
PSD version: https://drive.google.com/file/d/0B4sTRNAGk2yrYV9wamxKY0Jxd1k/view?usp=sharing

![uikit](https://cloud.githubusercontent.com/assets/2857625/8878132/2a8eb2e4-3232-11e5-80d5-69bad0f43c08.png)
If it was popular, I could continue...

**Comment by adaniello** [comment]
:+1: 

Thanks

**Comment by ddasevero** [comment]
OMG <O>
Tks a lot

2015-07-24 12:59 GMT-03:00 adaniello <notifications@github.com>:

> [image: :+1:]
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uikit/uikit/issues/1409#issuecomment-124566417>.
>



-- 


*Dyego Severo*
*</front-end dev>*
*www.dyegosevero.com.br <http://www.dyegosevero.com.br/>*

**Comment by vuchl** [comment]
@Intiligent Did you make the wizard yourself? Looks really cool and fits the theme very well. Maybe you can share that? with a fork or something?

**Comment by Intiligent** [comment]
@vuchl What does it mean yourself? Yes, its all my work.
Link to the source is in the beginning of the article. Also i create own fork: https://github.com/Intiligent/uikit

**Comment by vuchl** [comment]
@Intiligent I meant if you have the markup + css for the wizard? Or is it just photoshopped? Because the official Uikit doesn't have a wizard component.

**Comment by Intiligent** [comment]
@vuchl Now its only psd design. Markup + css for the wizard not yet, maybe later i do it. 
If you need markup, you can see example and convert it to UiKit:

http://semantic-ui.com/elements/step.html
http://getfuelux.com/javascript.html#wizard-examples

**Comment by Pandahisham** [comment]
+1 keep going @Intiligent awesome work

**Comment by vuchl** [comment]
@Intiligent Ah I see where you got it from. I like it! Thanks for sharing!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
