### ISSUE TITLE
Modal inherits properties from surrounding html

### ISSUE THREAD

**Issue by wdebusschere** [uikit/uikit#1411]
We added modals to our website for the logged in users to manage the content, but the modal is inheriting css properties from the surrounding html..

Example1: modal close button is not allways visible, depending on the place of the modal.
Example2: H1 in modal header is not aligned left, but has a sort of 100px padding-left.
Example3: text gets a white color...

FYI: modal code is added just after the modal link

**Comment by malles** [comment]
Because the modal element is already set on the page, it will inherit the css from its environment. Place the modals in a neutral place in the DOM, eg at the bottom.
