### ISSUE TITLE
Custom build

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1412]
Hello,
"bootstrap" allows to create a custom build javascript containing only components you need.
Is this also possible with "uikit" and if yes, how?
Thanks a lot!

**Comment by malles** [comment]
It's not possible through a interface, but you can compile your own stripped down themes with the gulp-tools from the repository. See http://getuikit.com/docs/documentation_create-a-theme.html#how-to-start for how to. Here an example of the `uikit.less` file https://github.com/Bixie/uikit-bixie-theme/blob/master/big/uikit.less. If you need more help, give a shout here or on the [Gitter chat](https://gitter.im/uikit/uikit).
