### ISSUE TITLE
Is it possible to have a menu be either off-canvas or as a 1-4 column?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1413]
I have a site with a menu on the left side. On small screens this is an off-canvas, on medium and larger screens it's a 1/4th width.

I am trying to prevent having the same HTML for a menu in the same page twice (both as the off-canvas and as the 1/4th width and make one of them invisible). Is this possible?

It's a menu, nothing too much so if it's not possible I am not worried, but I was just wondering...

Thanks

**Comment by nstaeger** [comment]
Hi,

at the moment there is no UIkit-way to generate a offcanvas-menu out of a menu or vice versa. However, if this is not a static site, you can of course use the same renderer for both menus and only need to change one CSS class.

**Comment by jerry1970** [comment]
I haven't tested it yet, but I was thinking along those lines.

However, setting the class by default on uk-offcanvas (mobile first) will trigger the javascript and then removing the off-canvas class and adding the 3/4 width class, wouldn't that screw up the layout somehow? Like I said, I need to see it work, but I was just wondering what would happen if I only removed the class. Does uikit set any listeners, perhaps?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
