### ISSUE TITLE
slideshow stop after click on items or arrows

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1414]
hi 
how can i remove this https://github.com/uikit/uikit/blob/master/src/js/components/slideshow.js#L198 line without edit slideshow.js core i want to do this script in my index page for example.

**Comment by malles** [comment]
This example may help you: http://codepen.io/malles/pen/qdOvJP
The autoplay is controlled by a separate button.
TLDR;
```
UIkit.on('init.uk.component', function(e, name, component) {
  if (name === 'slideshow') {
    UIkit.$('#autoplay').on('change.uk.button', function(e, active) {
      component[(active ? 'start' : 'stop')]();
    });
  }
});
```

**Comment by malles** [comment]
Reading your title better, the slideshows autoplay is by default set to pasue when the user hovers the slideshow, and stops when he clicks the navigation buttons.
See [the javascript options](http://getuikit.com/docs/slideshow.html#javascript-options)

**Comment by miladmeidanshahi** [comment]
malles i don't want to stop slideshow when click on items slideshow ore arrows without editing slideshow.js.
not work on autoplay

**Comment by aheinze** [comment]
hi, sorry I don't think this is common behavior of a slideshow, and to be honest it feels somehow wrong. 
I would suggest you t add a custom snippet, that restarts the autoplay after some time without interacting.
