### ISSUE TITLE
Dynamic Grid Filtering

### ISSUE THREAD

**Issue by chiotis** [uikit/uikit#1418]
Is there any way to show a particular filter when page loads and not all of the dynamic grid items?

referring to this component
http://getuikit.com/docs/grid-js.html#filtering

**Comment by malles** [comment]
That can be done with:
```
UIkit.ready(function() {
    UIkit.$('#yourGrid').filter('filter-a');
});

```

**Comment by Utsira** [comment]
Apologies for reopening a closed issue, but I find the solution here, instead of filtering the grid itself, filters the controls for the grid. Is it possible to filter the grid itself in javascript (not the grid controls?)
