### ISSUE TITLE
Behavior of render with custom renderer

### ISSUE THREAD

**Issue by wallaceicy06** [uikit/uikit#1422]
I've been working on a personal project with ember-cli and UIkit. I've been using the autocomplete component for one of my forms, and attempting to develop a component for that.

The behavior I'm aiming for is to have the user specify the autocomplete component in the template like this:

``` handlebars
{{#uikit-autocomplete}}
  {{#each results as |result|}}
    <li data-value={{result.value}}>
      <a>{{result.name}}<div>{{result.desc}}</div></a>
    </li>
  {{/each}}
{{/uikit-autocomplete}}
```

My component's template looks like this:

``` handlebars
<div class="uk-autocomplete uk-form">
  {{input type="text" autocomplete="off" value=search}}

  <div class="uk-dropdown">
    <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
      {{yield}}
    </ul>
  </div>
</div>
```

Instead of using the autocomplete component's `template` property, I am trying to go for a more "ember" approach and allow the user to specify the template for the results themselves using handlebars, and then my component will yield to that custom template.

The problem is that the UIkit autocomplete component assumes that any time `render` is called, it empties all DOM elements under the `.uk-dropdown` div. This leads to my user's custom template being wiped every time results populate, even though I specify a custom renderer.

FYI, my renderer function looks like this:

``` javascript
renderer: function(stuff) {
  that.set('results', stuff);
  this.show();
}
```

For my purposes, I feel like it would make sense for the `this.dropdown.empty();` line to be moved inside of the if/else block for the condition where a custom renderer is **not** specified. Then, it would be up to the custom renderer to decide how it wants to re-render the results. It can empty the DOM itself, since the call passes the `this` parameter, or in my case it would not do that.

Anyways, I realize that my purpose is not necessarily best for everyone, and I wanted to ask if this seems like a reasonable change or if there is a specific design decision for why the DOM elements are emptied every time. Thanks, and keep up the good work!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
