### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1423]
Please update Font Awesome to 4.4.0
http://fortawesome.github.io/Font-Awesome/whats-new/

**Comment by malles** [comment]
It's ready for the next release: https://github.com/uikit/uikit/pull/1427

**Comment by jerry1970** [comment]
Are there plans to move fontawesome to the add-ons to make it easier to choose between fontawesome and icomoon, for example?

**Comment by aheinze** [comment]
@jerry1970 yes, for UIkit 3
