### ISSUE TITLE
More documentation on autocompletion / search markup

### ISSUE THREAD

**Issue by btrscott** [uikit/uikit#1430]
I'd like to have more documentation on the markup language used to create autocomplete / search dropdown boxes.  Particularly in the flow of control.  It's kind of hard to be guessing at the available syntax based on the one or 2 examples provided in the documentation.

My current issue is that I have some fields coming back from my json request as 'null' and that's how they are showing up as 'null' in the text.  How can I do a form of 'if null' check to then print something else.

If the markup is some kind of standard language with documentation elsewhere I'm not sure exactly what that is so I can go look.

**Comment by malles** [comment]
You luck out, I made some docs about out in this pen earlier: http://codepen.io/malles/pen/qEyEZr

**Comment by btrscott** [comment]
It is my lucky day.  Thanks.

I think the example for if not condition is incorrect (seems to be copied from the if condition).  Otherwise would be nice to be printable but that's a nit.

You should add that page to the regular doc.  Maybe I should play contributor and I should do it.

**Comment by malles** [comment]
Thanks, fixed it.
