### ISSUE TITLE
DOCS: Medical Icons

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#1432]
Is there a reason why the medical icon section does not exist anymore in the docs?
Since I do not know how to make a PR following code (from an earlier version) should be added if whished
```
<hr class="uk-article-divider">
<h3>Medical Icons</h3>
<ul class="uk-grid tm-icons">
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-ambulance"></i> ambulance</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-h-square"></i> h-square</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-hospital-o"></i> hospital-o</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-medkit"></i> medkit</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-plus-square"></i> plus-square</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-stethoscope"></i> stethoscope</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-user-md"></i> user-md</li>
<li class="uk-width-1-2 uk-width-medium-1-4"><i class="uk-icon-wheelchair"></i> wheelchair</li>
</ul>
```
Some are available in other sections (ambulance, wheelchair and plus-square)
The others are missing

**Comment by Pandahisham** [comment]
+1

**Comment by malles** [comment]
Thanks! They will be back: https://github.com/uikit/uikit/commit/c38e8e888a2f4da5f50d67ec1606fd7a8369f787

**Comment by luetn** [comment]
@malles Thanks! Tried to find a stethoscope today. I was utterly unsuccessful :sweat_smile:

**Comment by malles** [comment]
@luetn A stethoscope :scream: I hope everything is allright?

**Comment by luetn** [comment]
@malles Tank you! uk-icon-user-md managed it with an emergency exploratory fileotomy :pill:
