### ISSUE TITLE
Is it possible Tooltip not hidden and always visible without mousover? 

### ISSUE THREAD

**Issue by allogos** [uikit/uikit#1433]

**Comment by miladmeidanshahi** [comment]
i don't think so.
I had already been working but does not answer, Of course I do not say one hundred percent, maybe there is a way.

**Comment by malles** [comment]
This is indeed impossible since UIkit uses only one DOM element to show all tooltips. Only the content and position changes. So by definition, only one tooltip can be shown at a time.

**Comment by Uranbold** [comment]
Is there any way to use this?
