### ISSUE TITLE
tooltip undefined?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1435]
This used to work:

```javascript
	UIkit.on('beforeready.uk.dom', function(){
		$.extend(UIkit.components.tooltip.prototype.defaults, {
			pos: 'top',
			delay: 500,
			animation: true
		});
	});
```

But now I get the error ```TypeError: UIkit.components.tooltip is undefined```. I can't search the documentation and I can't find anything on this.

**Comment by malles** [comment]
It should work. Tooltip has moved from core to a component. Do you have it's js- file included?

**Comment by jerry1970** [comment]
Ah, that explains... Sorry, I should have noticed that myself!
