### ISSUE TITLE
Focus remains on button after dialog overlay is shown

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1436]
When I have a button with an onClick that opens a modal dialog with an overlay, the focus remains on the button, so when I press Enter again, the dialog is shown again and again.

It's easy to move the focus away from the button on opening a dialog (for example to the primary button), but it would be nice if this was in the uikit code itself.

**Comment by malles** [comment]
Simular to https://github.com/uikit/uikit/issues/1420, we'll look into that
