### ISSUE TITLE
radio buttons as list

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1438]
Looks like UIKIT cannot handle yet radio buttons that have long labels and need to be presented like a list (not next to each other but each in a separate row - with correct indents):
![bildschirmfoto](https://cloud.githubusercontent.com/assets/652879/9108489/cd93ebe8-3c2e-11e5-8ca5-b304dbaa1728.png)

**Comment by zslabs** [comment]
You could always wrap some additional markup with a `<label>` to include a flex property that could take care of the indention. You could also attach `.uk-text-nowrap` to the label, so there would be no overflow if space wasn't available.

**Comment by tbba** [comment]
Yes, I could tweak UIKIT to my needs by adding some of my own CSS on top. :-)
I just thought that this is such a standard task that I wanted to mention this here. I.m.h.o. this could be included as a UIkit standard behavior (option?) - or at least it would be useful to have a solution illustrated in the docs, don't you think?

**Comment by zslabs** [comment]
Not sure what you mean by your own styles as the [Flex](http://getuikit.com/docs/flex.html) and [Utility](http://getuikit.com/docs/utility.html) components are already in there, so there isn't a need for custom styles. There wouldn't be anything added for this because the functionality is available in at least the two different ways as I mentioned.

**Comment by tbba** [comment]
Cool. Do you have a rough example how you would do this with Flex and Utility? 
I solved this for me using a custom class for radio-input and -label - but using UIKIT would be preferable to adding my own stuff. This is what solved my problem right now (on top of UIKIT):

. radio_input {
     float: left;
}
. radio_label {
      margin: -9px 10% 20px 20px;
      display: block;
      line-height: 1.3;
}
.radio_label:after {
      content: "";
      clear: both;
      display: table;
}

**Comment by zslabs** [comment]
Sure http://codepen.io/zslabs/pen/waOwrb

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team
