### ISSUE TITLE
Allow multiple filters at once for dynamic grid

### ISSUE THREAD

**Issue by fheinrich** [uikit/uikit#1439]
Hi, i'm using the filter function with dynamic grid. I have 3 control categories and I want to combine the filters, so for example:

    Filter-Buttons:
    ========================================================================
    = Filter-Category 1              ABC          DEF          GHI
    = Filter-Category 2              JKL         MNO
    = Filter Category 3              PQR          STU          VWX
    ========================================================================

And I have one div where all the items are in that i want to filter. And I want them for example not only to match "JKL" but to match "ABC", "JKL" and "STU" at the same time.

Thats not possible currently, is it? Can you add this feature?

**Comment by fheinrich** [comment]
Not possible?

**Comment by malles** [comment]
Yes, that can be done with some extra javascript. I created this Codepen as a demo:
http://codepen.io/malles/pen/xweBge

**Comment by st90** [comment]
This does not actually work - if one selects "Box Primary" and then "Badge danger" the very first item is a Box Primary with a Badge warning
