### ISSUE TITLE
Auto Complete - Control 'More Results'

### ISSUE THREAD

**Issue by sfmedia** [uikit/uikit#1440]
I've setup the Autocomplete to work using a php file / mysql search, outting JSON which all works great. The issue i'm having is with the 'more results' link at the bottom of the dropdown. Is there anyway i can control this?

Its a nice feature and i don't want to use a custom template and just drop it all together, but can't find any docs / information on how to control it.

I've limited my results to 8 in the dropdown, so if the seach returns <= 8 results i don't want the final 'more results' link.

Thanks for your help.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The autocomplete component has not been released yet, so please check later if this problem still occurs there.

Thanks for your understanding,
Your UIkit Team
