### ISSUE TITLE
Slideshow events

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1441]
Hello,

The slideshow initializes after loading all the images. If you have a hundreds of images - this could be quite slow.
My idea was to create dummy pages and load the images as soon as the page appears.

My question: Is there an event which fires "on page changes"?

Thanks a lot
Markus

**Comment by zslabs** [comment]
It'd be far better to implement a progressive lazy-loader for images instead of putting this much bandwidth hogging the server. @aheinze
