### ISSUE TITLE
Sticky nav scrolls over sticky navbar instead of under. Z-index problem?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1442]
I have a navbar (used for title and status and a user menu dropdown, not for the main menu) attached to the top of the page and on the left of the page is a nav (all menu items) that is sticky to the bottom of the navbar:
``` html
<nav class="uk-navbar uk-navbar-attached uk-margin" data-uk-sticky>
   ...
</nav>
<div class="uk-grid uk-grid-small" data-uk-grid-margin style="margin-top: 15px">
   <div id="team-menu" class="uk-hidden-small uk-width-medium-1-5 uk-width-large-1-6 uk-width-xlarge-1-7">
      <ul class="uk-nav uk-nav-side" data-uk-nav data-uk-sticky="{top:40}">
```
Scrolling down perfectly lets the nav stick to the bottom of the navbar. When the nav is too long for the page, scrolling down also scrolls the nav. This is good, because people would want to see the other menu items in the nav as well.

But the nav is scrolling **over** the navbar instead of **under** the navbar. I tried to fix this with a z-index somewhere but could not get it to work.

Any ideas?

Using UIkit 2.21.0, by the way.

Cheers,
Jerry

**Comment by jerry1970** [comment]
Ooh, I found something... Sticky elements seem to have z-index 980, so both the ```uk-navbar``` and the ```ul.uk-nav``` get a ```z-index: 980;```. When I change the z-index of the nav to 970, it looks OK. (I was setting the z-index to the wrong elements.)

Is this something for a setting?

**Comment by malles** [comment]
As you can see in [this demo](http://codepen.io/malles/pen/qdjXRM) it takes a bit of adjustments on the z-index to get it all right. 
The z-index is a variable in the less code, so you can change the value in your style's variable settings.
