### ISSUE TITLE
 scrollspy="{cls:'uk-animation-scale', repeat: true}" and uk-animation-shake remain with 0 opacity 

### ISSUE THREAD

**Issue by wannaco** [uikit/uikit#1444]
Using Scrollspy mostly with regular scale animation and shake will remain at
`` [data-uk-scrollspy='uk-animation-']:not([data-uk-scrollspy='target']) { opacity: 0; }``

Looking for other people experiencing this issue I found the following unresolved/not responded thread
http://yootheme.com/support/question/78397

"version": "2.21.0"

**Comment by wannaco** [comment]
Adding a target scrollspy="{cls:'uk-animation-scale', target , repeat: true}" fixes the issue. but definitely a bug.

**Comment by robertotremonti** [comment]
Still experiencing this issue in latest 2.22.0.
The problem seems related to Firefox only.
It works correctly in Chrome and Safari.

`target` option make the element appear but without animation on Firefox.

**Comment by wannaco** [comment]
I was experiencing the issue in chrome and firefox

**Comment by malles** [comment]
The tests of scrollspy do not show this. The first three panels are exactly as your example.
http://getuikit.com/tests/core/scrollspy.html

**Comment by wannaco** [comment]
Well. it was not me the only one. I found a workaround. I thought it'd be worth reporting the issue. If the issue is not present  which is good for all of us. hope this issue can be closed

**Comment by robertotremonti** [comment]
Don't know if it's your case, but I was using a modded minified CSS that added quotes to `animation` effects.
This prevented Firefox to apply effects.
Removing the quotes fixed the problem.

Firefox was acting correctly.
It's Chrome and Safari that apply effects even when they are quoted in CSS.
Here's the bug report.
https://code.google.com/p/chromium/issues/detail?id=423424

And here's a test for all browsers.
http://codepen.io/rupl/pen/nIbEa?editors=110

**Comment by malles** [comment]
Thanks @robertotremonti
