### ISSUE TITLE
bad ubication for dynamic elements added to dynamic grid

### ISSUE THREAD

**Issue by cocodrino** [uikit/uikit#1445]
Hi, I'm having some problems using the dynamic grid component, I'm using this with react but when I add new elements to my grid these are not displayed in the correct place, instead they're stacked over the other elements and doesnt flow to the correct place, then I need resize my screen and this fits the problem, are there any function which force to recalculate the correct place for the grid elements?.thanks.

**Comment by malles** [comment]
Simular to https://github.com/uikit/uikit/issues/1325
