### ISSUE TITLE
Bug Report: uikit slideshow and sliders can't work in android device

### ISSUE THREAD

**Issue by liuxinqiang** [uikit/uikit#1446]
Hi , the slideshow and sliders can't work on android device, I can't slipe left or right to switch images , but on iphone it worked as well

**Comment by malles** [comment]
The docs pages of both components work fine on my Android. Do you have an example?

**Comment by neromaki** [comment]
I'm getting the same thing, on the stock Android Internet browser (running 5.0.1) - You cannot swipe left or right on the Slideshows (even on UIKit's docs) to change slide, can only use the navigation elements.

**Comment by malles** [comment]
Stock Android browser has been dropped by Android, and is no longer supported. Use Chrome.
