### ISSUE TITLE
Bug when using Tab component in responsive conditions

### ISSUE THREAD

**Issue by Arkantalis** [uikit/uikit#1449]
Hi, I'm using uikit for the first time in a joomla template (Gavick Katana).
I just add some tabs in articles to show the ingredients, analysis, or advices for each of my products.
![uikit1](https://cloud.githubusercontent.com/assets/13216151/9210726/37237e4a-407e-11e5-8e12-3bfcd0fb414c.JPG)
As you can see all is ok but in responsive conditions I thought that all was ok...
![uikitresponsive1](https://cloud.githubusercontent.com/assets/13216151/9210749/55fbf342-407e-11e5-9717-c534bc04b9d3.JPG)
... and then i clicked on the burger button and here it is...
![uikitresponsive2](https://cloud.githubusercontent.com/assets/13216151/9210821/ab0cfffc-407e-11e5-9b82-1deb80d433db.JPG)
And when i click again on the responsive menu it's worst and worst...
![uikitresponsive3](https://cloud.githubusercontent.com/assets/13216151/9210846/c7da87bc-407e-11e5-8398-dc1112518948.JPG)
Here is my html tab for the example :

``` html
<ul class="uk-tab" data-uk-tab="" data-uk-switcher="{connect:'#1'}">
    <li class="uk-active"><a>Ingrédients</a></li>
    <li><a>Analyses nutritionelles</a></li>
    <li><a>Conseils d'utilisation</a></li>
    <li><a>Démarche environnementale</a></li>
</ul>
<ul id="1" class="uk-switcher">
    <li>
        <p>Tofu*<sup>(1)</sup> (eau, <strong>soja</strong>* décortiqué 27%, gélifiants : sulfate de calcium, nigari).</p>
        <p><span style="font-size: 10pt;"><em>*Ingrédients issus de l'agriculture biologique.</em></span><br /><span style="font-size: 10pt;"><em><sup>(1)</sup>Soja français sans OGM issu d'une filière Bio Solidaire contrôlée par Ecocert Environnement.</em></span>
        </p></li>
    <li>
        <table class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
            <tbody>
                <tr>
                    <td>Valeur énergétique</td>
                    <td>605 kJ/145 kcal</td>
                </tr>
                <tr>
                    <td>Matières Grasses</td>
                    <td>9,0 g</td>
                </tr>
                <tr>
                    <td>- dont acides gras saturés</td>
                    <td>1,5 g</td>
                </tr>
                <tr>
                    <td>Glucides</td>
                    <td>0,7 g</td>
                </tr>
                <tr>
                    <td>- dont sucres</td>
                    <td>0,6 g</td>
                </tr>
                <tr>
                    <td>Fibres alimentaires</td>
                    <td>2,5 g</td>
                </tr>
                <tr>
                    <td>Protéines</td>
                    <td>14 g</td>
                </tr>
                <tr>
                    <td>Sel</td>
                    <td>0,01 g</td>
                </tr>
                <tr>
                    <td>Magnésium</td>
                    <td>59,1 mg</td>
                </tr>
                <tr>
                    <td>Calcium</td>
                    <td>188 mg</td>
                </tr>
            </tbody>
        </table></li>
    <li>
        <p>Coupé en petits cubes : dans une salade ou une poêlée<br />Emietté : dans une farce ou un gratin<br />Mixé : dans une sauce ou un dessert</p>
        <ul>
            <li class="frais"><span style="background-color: transparent;">A conserver à +4° C / Après ouverture, à consommer dans les 3 jours.</span>
            </li>
        </ul></li>
    <li>
        <p><strong>Eco-concevoir</strong> un produit, c'est le fabriquer en pensant à <strong>son impact environnemental</strong>. A chaque étape de<strong> l'éco-conception</strong> (récolte et acheminement des matières premières, fabrication du produit, transfert, utilisation et élimination) nous limitons<strong> l'empreinte environnementale.</strong>
        </p>
        <p>Soy est <strong>partenaire</strong> de l'organisme <strong>Eco-emballage</strong>, et ensemble nous travaillons :</p>
        <ul>
            <li>à la<strong> réduction des emballages</strong> à la source (moins d'énergie et de matière à la création du produit = moins de déchets à éliminer)</li>
            <li>à l'<strong>amélioration de la recyclabilité</strong> (les métariaux utilisés pour concevoir nos emballages sont en adéquation avec les procédés des filières de recyclage)</li>
            <li>à la <strong>sensibilisation</strong> du consommateur (les <strong>conseils de tri</strong> figurent sur nos emballage, pour vous aider à adopter les bons gestes)</li>
        </ul>
        <p> <strong>Vous souhaitez en svoir plus sur le tri des déchets ?</strong>
        </p>
        <table>
            <tbody>
                <tr>
                    <td style="text-align: center;"><a href="http://www.quefairedemesdechets.fr"><img alt="triman" src="images/produits/triman.png" height="155" width="200" /></a><br /><a href="http://www.quefairedemesdechets.fr">www.quefairedemesdechets.fr</a>
                    </td>
                    <td style="text-align: center;"><a href="http://www.consignesdetri.fr"><img alt="ecoemballage" src="images/produits/ecoemballage.png" height="155" width="200" /></a><br /><a href="http://www.consignesdetri.fr">www.consignesdetri.fr</a>
                    </td>
                </tr>
            </tbody>
        </table></li>
</ul>
```

If someone can help me to find where is the problem it could be very cool because i really don't understand what's happening...
Thanks a lot.

**Comment by liuxinqiang** [comment]
Hi, I think you should readl carefully of the documents……
" The data-uk-tab attribute is required for two purposes. Firstly, it enables the responsive behaviour. If the parent container is too small to accomodate all tabs, they will be combined into a dropdown, toggled by a single tab, which represents the active tab item. This also requires the Dropdown component in order to work.

And secondly, its functionality is coupled to the Switcher component, which is necessary to dynamically transition through different contents using tabbed navigation. "

if you don't want this responsive behaviour ,just delect  " data-uk-tab="" " in your code……

**Comment by richmilns** [comment]
Hey, I think I see what the problem actually is - in your markup you need to change:
`<ul class="uk-tab" data-uk-tab="" data-uk-switcher="{connect:'#1'}">` to be:
`<ul class="uk-tab" data-uk-tab="{connect:'#1'}">`

I had a similar issue and realised that having **data-uk-switcher** as well as the **data-uk-tab** attribute made things go crazy... Seems that when you have tab and switcher requirements you only need to use the **data-uk-tab** attribute to connect up the tab with the tab content.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
