### ISSUE TITLE
modal not appearing without JS

### ISSUE THREAD

**Issue by jaydenrussell** [uikit/uikit#1450]
I have found that using the data-uk-modal is great but the stock android browsers seem to have JavaScripting disabled. It seems that without JavaScript that data-uk-modal will not display.

Tested with Android 2.2 and 5.1 using stock browsers.

**Comment by DerekTBrown** [comment]
That is the correct behavior- Javascript is required to make the data-uk-modal display.  Any time you see a data-* attribute, this means that javascript is involved in manipulating the DOM somehow.

**Comment by malles** [comment]
As far as I know, Javascript is enabled in all web browsers since the late nineties. (That is previous century :) )
Please check your local settings.
