### ISSUE TITLE
Datepicker Focus Error

### ISSUE THREAD

**Issue by DerekTBrown** [uikit/uikit#1451]
When using a datepicker on mobile, the calendar window appears briefly, and then disappears automatically when the focus is shifted to the input by default.  Take a look:

https://video.googleusercontent.com/s_GbJqbinXu56iVCCQu5tzVboR1lr8aIMgVp50qiXlwkJYKWwMfZs_MYY0Ou23dNs2Bi90XU09_ONocmx8IL4H9UDpV838hPizeeSPP_kQ59zZUVMe90Fp-P0OF9yQSOZWGVRrPmPc6atJ9csfQLekaPsQ

**Comment by aheinze** [comment]
sorry, but the video doesn't load/exist

**Comment by malles** [comment]
I can confirm the behaviour on my adriod device, opening the datepicker [in the docs](http://getuikit.com/docs/datepicker.html).

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The datepicker has not yet been released but will be released in one of the next mayor updates. If the problem still occurs then please open up a new issue 

Thanks for your understanding,
Your UIkit Team
