### ISSUE TITLE
Adding Additional Events for a Finer Degree of Control

### ISSUE THREAD

**Issue by admgrn** [uikit/uikit#1452]
It would be very useful to add additional events to give a finer degree of control to developers. For example, the offcanvas hide event 'hide.uk.offcanvas' only fires after the animation completes. It would be very useful to have an event fire before the animation begins as well. 'hide.uk.offcanvas.start'? I can go through and identify other areas that could benefit from additional events if anybody else likes this idea. I'll be happy to submit a pull request with these changes.

**Comment by janschoenherr** [comment]
This has been added in UIkit 3: https://getuikit.com/docs/offcanvas#javascript
