### ISSUE TITLE
Offcanvas as overlay layer

### ISSUE THREAD

**Issue by vinoth3v** [uikit/uikit#1453]
Could you please add a new modifier to offcanvas component, so that it displays as 'overlay' offcanvas instead of changing margin to body?
Because if body contains many contents, browser lags when opening offcanvas menus. 
Possible?

**Comment by miladmeidanshahi** [comment]
+1

**Comment by lupuxyz** [comment]
+1

**Comment by TomS-** [comment]
Easily done, I've already done this on my local environment by using the modifier "uk-offcanvas-bar-over". 

I can push to this branch and see if it gets merged.

**Comment by TomS-** [comment]
Had some trouble getting Github to do a pull request right. The above #1467 should be what you are looking for.

**Comment by Intiligent** [comment]
+1

**Comment by o15s19** [comment]
+1

**Comment by vinoth3v** [comment]
any update?

**Comment by TomS-** [comment]
I did a pull request. However it hasn't been looked at or merged. That's as far as I know.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has been added with the different modes of the Offcanvas, check them out [here](https://getuikit.com/docs/offcanvas#animation-modes).

Thanks for your understanding,
Your UIkit Team
