### ISSUE TITLE
Infinite scroll with scrollspy

### ISSUE THREAD

**Issue by vinoth3v** [uikit/uikit#1454]
Is it possible to build the Infinite scroll feature with scrollspy component?

**Comment by malles** [comment]
Yes, it is. Here is an example!
http://codepen.io/malles/pen/NqmLLX?editors=101

**Comment by vinoth3v** [comment]
@malles  Thank you very much.

**Comment by j2studio** [comment]
@malles Thanks for this - but it seems to me that it is just repeating the 6 <li>'s.

I have an UL with nearly 100 <li>'s and they don't seem to show the scrollSpy effect until the list repeats?

**Comment by rvalitov** [comment]
The example above doesn't work anymore, because UIKit 3 is released, so some links don't work. Fixed example is here http://codepen.io/rampen/pen/MJmqmw
