### ISSUE TITLE
Make sure top of accordion element content is visible after opening

### ISSUE THREAD

**Issue by Ilya-Zhulin** [uikit/uikit#1456]
Hello, friends
If Accordion has option `collapse:true`, as default you can see this trouble:
http://jsfiddle.net/5gpb3npq/
If the first title is opened and I click to second title, my second title goes up iver the screen. Can we do something with it?
Thanks!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
