### ISSUE TITLE
accordion all open on init

### ISSUE THREAD

**Issue by fluctusz** [uikit/uikit#1459]
hi, 
is there an easy way to get all accordion items open on page-load (not just the first one)?
thanks,
martin

**Comment by malles** [comment]
Yes, that's possible with a bit of code, see http://codepen.io/malles/pen/bdMMGB?editors=101
```
   var accordion = UIkit.accordion(UIkit.$('#my-accordion'), {collapse:false, showfirst: false});
   accordion.find('[data-wrapper]').each(function () {
      accordion.toggleItem(UIkit.$(this), true, false); // animated true and collapse false
   });
```

**Comment by fluctusz** [comment]
thank you malles, works perfect!
