### ISSUE TITLE
Syntax error in uikit.js

### ISSUE THREAD

**Issue by colmsjo** [uikit/uikit#1462]
I got this error in uikit.js when installing with bower. 

Safari 8.0.7

`[Error] SyntaxError: Unexpected identifier 'document'. Expected a ';' following a return statement.
	(anonym funktion) (uikit.js, line 148)`

**Comment by aheinze** [comment]
which uikit source do you use? (e.g. bower uikit, or cdn)

**Comment by colmsjo** [comment]
bower



—

**Comment by aheinze** [comment]
I can't verify this, do you have still the issue with UIkit 2.22?
