### ISSUE TITLE
datepicker.js contains copy of moment.js

### ISSUE THREAD

**Issue by istr** [uikit/uikit#1464]
Currently datepicker.js contains a hard copy of moment.js. This leads to having two copies of moment.js in a bundle using non-patched uikit and a differently configured moment.js build in a project. This should be resolved for 3.0 ("Custom dist builder") with an option to rely on an externally loaded moment.js or to compile it into the uikit build.

**Comment by zslabs** [comment]
I have also mentioned this, UIkit shouldn't be afraid to have a dependency set as long as their documentation lays out "how" to install these, whether it be via Bower or NPM

**Comment by aheinze** [comment]
It is already planned to remove moment for UIkit 3.0
