### ISSUE TITLE
Two fixes for slider.js

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1468]
Two bugs in "slider.js"

First: slider.js line 76: "undefined variable slide"
````
switch(item) {
    case 'next':
    case 'previous':
        $this[item=='next' ? 'next':'previous']();
        break;
    default:
        $this.updateFocus(parseInt(slide, 10));
}
````
Fix "slide" -> "item":
````
        $this.updateFocus(parseInt(item, 10));
````

Second: slider moves to first item on resize event (e.g. orientation change).
Replace line 191:
````
            this.updateFocus(0);
````
Fix:
````
            this.updateFocus(this.focus);
````

**Comment by malles** [comment]
Thanks! It is fixed.

**Comment by doublex** [comment]
Hi malles,

Thanks a lot!
Maybe there is an issue in the this commit:
 https://github.com/uikit/uikit/commit/8bf244ec3d9b8c542c1da1c1b913b0f071873e7f
````
if (focus) this.updateFocus(this.focus);
````
a) focus does not exist so the condition is false
b) "this.updateFocus()" should be called even if "this.focus == 0"
So maybe better:
````
this.updateFocus(this.focus);
````

**Comment by malles** [comment]
`focus` is passed into the function as a parameter. It prevents focussing twice when called from within itself for infinite sliders.

**Comment by malles** [comment]
I must admit, it was not implemented properly before, it should already have been `if (focus) this.updateFocus(0);` in that line.

**Comment by doublex** [comment]
Hi malles,
You are right - sorry for disturbing.
Thanks for fixing!
