### ISSUE TITLE
How to extend modal?

### ISSUE THREAD

**Issue by jsieler** [uikit/uikit#1469]
Hello eveyone, i'm trying to extend modal windows by adding new type. I want a prompt type, but instead of input i would like to put textarea inside. Sure, i can just copy the prompt code withing uikit.js, but i don't like messing in core of. How can i extend it within my own "script.js" ?

**Comment by aheinze** [comment]
just override the prompt in your custom script.js:

```js
UIkit.modal.prompt = function() {
  // ...
}
```
