### ISSUE TITLE
Default Form Password to Show

### ISSUE THREAD

**Issue by kraymitchell** [uikit/uikit#1472]
Maybe I'm missing something, but is there a way to have Form Password default to showing the HIDE button and displaying the password.

**Comment by malles** [comment]
I had to figure it out myself too, but it's easy to do; just setup the input the way you want it to start. The form-password component just toggles text in toggler and the input type from `text` to `password` and reverse.
```
    <div class="uk-form-password">
        <input type="text">
        <a href="" class="uk-form-password-toggle" data-uk-form-password>Hide</a>
    </div>
```

**Comment by kraymitchell** [comment]
Thanks @malles !
