### ISSUE TITLE
Line 148 of non-minimized JS is showing Á character

### ISSUE THREAD

**Issue by RowdyRocko** [uikit/uikit#1473]
This is causing tabs to function incorrectly. Not visible in text editor but if you check through browser it appears. Simple fix of a few backspaces and retype the line. Using latest version

**Comment by malles** [comment]
I can't see it on the source in Chrome..
![image](https://cloud.githubusercontent.com/assets/5442402/9430060/25805ad8-49e7-11e5-8b5a-500ece77ab3b.png)
nor in a normal tab;
![image](https://cloud.githubusercontent.com/assets/5442402/9430071/58e2e418-49e7-11e5-86a1-035e82daf938.png)
Do you have a printscreen of the exact location?

**Comment by aheinze** [comment]
maybe related to issue #1462

**Comment by aheinze** [comment]
@RowdyRocko do the issue still exists in UIkit 2.22?
