### ISSUE TITLE
Uikit 2.22.0 - missing documentation

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1475]
There are missing documentation about:
- Added dropdown overlay mode
- Added animation duration variables to sticky

**Comment by Intiligent** [comment]
i find example for dropdown overlay mode: http://getuikit.com/tests/core/dropdown.html

**Comment by PixelT** [comment]
I also found there, but it is a test page.
It will be nice to found the example in the doc, as other things.

**Comment by robertotremonti** [comment]
Uk-panel-teaser has been updated but I can't find it in documentation.
Any suggestions?
Thanks.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team
