### ISSUE TITLE
Icon in form inputs not aligned properly in 2.22.0

### ISSUE THREAD

**Issue by orestisioakeimidis** [uikit/uikit#1478]
Hi all,

the `margin-top` property of the `.uk-form-icon > [class*='uk-icon-']` selector should have the following value: 

`margin-top: round(@form-icon-font-size / -2);`

If I am not mistaken...

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
