### ISSUE TITLE
Datepicker select month & year

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1481]
Hi guys, is it possible to do another method select month and year, something like this?
![datepicker](https://cloud.githubusercontent.com/assets/2857625/9489097/1f74011a-4be7-11e5-9e9f-1632cea2c78f.jpg)
its very convinion and was able select only month || year || month && year

**Comment by acaron** [comment]
+1 and also add a view mode option like this: https://eonasdan.github.io/bootstrap-datetimepicker/#view-mode

So we can start with the year first, etc.

**Comment by bourgeois** [comment]
+1

Having multiple view modes would be great.

**Comment by ethanpil** [comment]
+1

**Comment by aheinze** [comment]
thanks for the suggestion, we'll consider it for future releases
