### ISSUE TITLE
Dropdown closing behavior

### ISSUE THREAD

**Issue by aartek** [uikit/uikit#1482]
In 2.21.0 there was a difference between dropdown behavior and its documentation.

Documentations said:

> Opens the dropdown by clicking the toggle. The dropdown closes again on the next click`

But it was closed on the first click. 

In 2.22.0 you have "fixed" this behavior and now dropdown disappear after next click, but I liked the previous behavior. Is there a way to turn it on? Now my application behaves different in some places and my QA team complains..

**Comment by QuantumKing** [comment]
I'm having the same problem.

**Comment by aartek** [comment]
It seems that adding class `uk-dropdown-close` to dropdown container helps. This could be documented.


    <div class="uk-button-dropdown uk-dropdown-close" data-uk-dropdown="{mode:'click'}">
        <button type="button">Dropdown</button>
        <div class="uk-dropdown uk-dropdown-small">
            <ul>
                <li><a href="">One</a></li>
                <li><a href="">Two</a></li>
            </ul>
        </div>
    </div>

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team
