### ISSUE TITLE
New section for addon & plugins

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1484]
Isset small addons and plugins that was useful, but not contain to UI components. How you like the idea to create new section "Addons" where was list of addons and each of them was independent and be able to download only necessary?

For example:
- **star rating** - http://codepen.io/Intiligent/pen/gaYYjg
- **text limiter** - http://codepen.io/Intiligent/pen/xwKKyv
- **custom CSS form element** - http://codepen.io/Intiligent/pen/NGKKJy
- **auto height (textarea)** - http://codepen.io/Intiligent/pen/RWbNmz
- **popover** - http://codepen.io/Intiligent/pen/BoBapx
- **lazy load** - http://codepen.io/Intiligent/pen/WQexVB
- **input clear** - http://codepen.io/Intiligent/pen/pbyjeN
- cookie for remember tab

**Comment by luetn** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by miladmeidanshahi** [comment]
+1

**Comment by adaniello** [comment]
+1

**Comment by hansnolte** [comment]
+1

**Comment by peterbrinck** [comment]
Well done!
All looks great

+1

**Comment by Pandahisham** [comment]
+1 awesome dude , loved your css only star rating !!

**Comment by davidlb** [comment]
Great!

+1

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team

**Comment by Intiligent** [comment]
its a global recomendation, not only for v2.
Why are you close all issues???
its a terrible(
