### ISSUE TITLE
Real code of examples please !

### ISSUE THREAD

**Issue by StribogKonsult** [uikit/uikit#1487]
Hi, this is awesome UI.
But let me suggest you something, on DOCS page there are "Markup" boxes after examples - this is very helpful, but WHY YOU DON'T PUT "REAL" CODE !!! instead this "Pseudo code" .
I'll be very happy if can just select "example code" and put it into my source for testing.

**Comment by aheinze** [comment]
Thank you for your suggestion, we already put this on our todo list for future UIkit releases
