### ISSUE TITLE
Compiling with compass breaks contrast component

### ISSUE THREAD

**Issue by wefixitgr** [uikit/uikit#1489]
contrast.scss has variables like `fade($base-color, 70%)` that get parsed by LESS properly but are not recognised by compass compiler resulting in invalid css rules like this: `color: fade(#fff, 70%);`

**Comment by wefixitgr** [comment]
@florianletsch If it helps I managed to solve it using a custom function and the rgba function built into sass:
```scss
@function fade($color,$opacity){
    @return rgba($color,($opacity/100));
};
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
