### ISSUE TITLE
how to get scrollspy to work with links such as /this/#that

### ISSUE THREAD

**Issue by javaporter** [uikit/uikit#1490]
My subnavs are in a few places, so they're in a partial. Because of that, the links are done in such a way: `a(href='/this/#that')`. If this were simply `a(href='#that')` everything works dandy. I love the plugin, it's so easy to use (one data-attribute — seriously doesn't get more elegant), is there an easy way to tell it to also watch for links that don't start with `#`? 

I'm not sure how much this will clarify things as it's tough to illustrate in a codepen, but just in case: http://codepen.io/javaporter/pen/BoBOQb

Any help would be much appreciated, thanks.

**Comment by aheinze** [comment]
did you try ```data-uk-scrollspy="{target:'#that'}"``` ?

**Comment by javaporter** [comment]
just to clarify, this is what you mean? 

`  li: a(href='/about/#mission' data-uk-scrollspy="{target:'#mission'}") Mission and Vision`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
