### ISSUE TITLE
Slider not aligned in RTL mode

### ISSUE THREAD

**Issue by malles** [uikit/uikit#1493]
The slider is calculated the wrong way in RTL mode.
https://github.com/uikit/uikit/blob/master/src/js/components/slider.js#L343
Left should be right in RTL...
![image](http://i.imgur.com/VcoAmBe.jpg)

![image](https://cloud.githubusercontent.com/assets/5442402/9587412/bd319554-5022-11e5-9551-b23810299623.png)

**Comment by miladmeidanshahi** [comment]
+1

**Comment by madjidyousefi** [comment]
Except this there is same bug in Slider plugin

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The slider component has not yet been released but we are working on releasing it within the next mayor updates. Please let us know if the problem still consists there. 

Thanks for your understanding,
Your UIkit Team
