### ISSUE TITLE
New component: step/wizard

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1494]
Welcome very simple new component: step/wizard -> http://codepen.io/Intiligent/pen/JYjrqV?editors=110

![wizard](https://cloud.githubusercontent.com/assets/2857625/9599415/7de39dd2-509c-11e5-8042-e2f56b46a3ad.jpg)

**Comment by adaniello** [comment]
Well done! Thanks for sharing

+1

**Comment by luetn** [comment]
+1

**Comment by miladmeidanshahi** [comment]
+1

**Comment by bdthemes** [comment]
+1

**Comment by mojtabakaviani** [comment]
+1

**Comment by Pandahisham** [comment]
+1

**Comment by rolandtoth** [comment]
+1

**Comment by philoest** [comment]
We think this is a really nice idea but currently we see this as out of scope, please take a look if there are other JS project dedicated to this which can be used in addition to UIkit
