### ISSUE TITLE
Datepicker component embeds Moment.js

### ISSUE THREAD

**Issue by adamwoodnz** [uikit/uikit#1496]
Is there a reason for embedding moment in the datepicker and not depending on it?

UIkit depends on jQuery, specifying a dependency for the datepicker doesn't seem any different.

Apart from the extra maintenance burden incurred it adds a lot of weight to what would otherwise be a very lightweight component.

We already use moment in some of our products and we don't want to download it again, especially on mobile.

**Comment by luetn** [comment]
Duplicate of #1464 
It is already planned to remove moment for UIkit 3.0

**Comment by adamwoodnz** [comment]
Great, sorry should have searched.
