### ISSUE TITLE
docs - switcher animation with overflow 

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1500]
I think it would be useful to have an example of the animated switcher used together with uk-overflow container. Much more beautiful effect in many cases, i.m.h.o. (Some people might not know this is possible.)

**Comment by malles** [comment]
I can't really picture what it looks like tbh. Sounds good though. Do you have an example/codepen of this?

**Comment by nblackburn** [comment]
Fully agree with this as it keeps the animation contained within the switcher rather than animating across the entire window.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
