### ISSUE TITLE
Documentation bug: .uk-panel-box-secondary background color

### ISSUE THREAD

**Issue by adamwoodnz** [uikit/uikit#1503]
The documentation for [Panel](http://getuikit.com/docs/panel.html) states "Add the .uk-panel-box-secondary class to modify the box panel and give it a white background."

This appears to be incorrect. The default background color for a secondary panel in panel.scss is `#eee`.

**Comment by malles** [comment]
Fised with https://github.com/uikit/uikit/commit/d95cae413f2b09ab99bf794bfaa06765b7570c78
