### ISSUE TITLE
Prevent value change in datepicker and timepicker when input is read only

### ISSUE THREAD

**Issue by orestisioakeimidis** [uikit/uikit#1505]
Hi,

Even when an input is read only, you can change its value using the datepicker and timepicker. In my opinion this should be prevented.

Cheers!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The datepicker has not been released yet, but we are working on that. Please let us know if this still consists when it is released.

Thanks for your understanding,
Your UIkit Team
