### ISSUE TITLE
Datepicker ux problem 

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1508]
The date picker supports year selection , but there no visual indicator that there is a year dropdown

**Comment by nblackburn** [comment]
Agreed, there should be an indicator showing they are expandable.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The datepicker has not been released yet but we are working on the component, please let us know if this still consists in the new version as soon as it is released.

Thanks for your understanding,
Your UIkit Team
