### ISSUE TITLE
slideshow, get actual slide (index)

### ISSUE THREAD

**Issue by fluctusz** [uikit/uikit#1510]
how do i get the actual shown item of a slideshow in $(".uk-slideshow").on('show.uk.slideshow', function(){}); ?

**Comment by andrewjdmartin** [comment]
Use the *next* and *current* vars:

    $( _selector_ ).on( 'show.uk.slideshow', function( event, next, current ) {

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team

**Comment by rosibabystiupida** [comment]
Hi,
need this script for uikit 3! I read the documentation of uikit 3 but i can't get "next" and "current" slide. In the documentation of uikit 3 there isn't the description of how to use event and relative parameters as the documentation of uikit 2 do.

Example of uikit 2 documentation description:
Name: beforeshow.uk.slideshow
Parameter: event, next slide, current slide
Description: Before showing a new slide (before animation is finished)

This if my old code that work for uikit 2.
```
    jQuery(".slideshowevento").on('beforeshow.uk.slideshow', function(event, nxt_slide, cur_slide){
    jQuery(nxt_slide).children('video')[0].currentTime = 0;
    });
```

This is my try to covert for uikit 3:
```
  jQuery(".slideshowevento").on('beforeitemshow', function(event, nxt_slide, cur_slide){
    jQuery(nxt_slide).children('video')[0].currentTime = 0;
    });
```
It doesn't work. Maybe the parameter "event, nxt_slide, cur_slide" now need a different name:

Any ideas?
thank you very much

**Comment by malcalevak** [comment]
@rosibabystiupida I think your best bet is to create a new ticket; as this one is closed, they aren't going to be watching it.
