### ISSUE TITLE
Reinit slideshow

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [uikit/uikit#1514]
Is there a way to reinit slideshow with new options? For example we want to change autoplay or animation transition dynamically.

**Comment by whitelynx** [comment]
I'd also be curious about this. I wanted to add a "pause slideshow" button, but it seems calling `UIkit.slideshow()` multiple times with different arguments doesn't actually change anything. (I expected it to at first, given my experience with Semantic UI.

**Comment by whitelynx** [comment]
Not sure what to do about the animation transition, but I found the answer to toggling autoplay in another issue: #1263

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
