### ISSUE TITLE
form-select component and dynamically built select

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#1515]
Hello
when building a select dynamically inside the document.ready function, the select looks empty - the first option is not shown automatically on the page. When clicking on the select, all options are listed and can be selected.
When not using the  form-select component, with the same javascript, the select presents automatically the first option, as I expect.
here is the html

     <html><head>
     <link rel="stylesheet" href="uikit/css/uikit.css">
     <link rel="stylesheet" href="uikit/css/components/form-select.css">
     <script src="vendor/js/jquery-2.1.4.min.js"></script>
     <script src="uikit/js/uikit.min.js"></script>
     <script src="uikit/js/components/form-select.js"></script>
     <script src="./form_test.js"></script>
     </head><body>
     <p>planets:</p>
     <form>
     <div data-uk-form-select="" class="uk-form-controls uk-button uk-form-select">
     <span></span><div class="uk-icon uk-icon-caret-down"></div>
     <select name="ceplanetid" id="ceplanetid"></select>
     </div></form></body></html>

and the js:

    $(document).ready(function() {
     $('#ceplanetid').append($("<option/>").val("").text("hello universe"));
     $('#ceplanetid').append($("<option/>").val("1") .text("Earth "));
     $('#ceplanetid').append($("<option/>").val("2").text("Moon"));
    });

Is this normal behaviour ? what must be added so that the component behaves like standard select ?
tahnks

**Comment by aheinze** [comment]
you have then to manually initialize it after  you appended the options, ```UIkit.formSelect(element)```

**Comment by prtome** [comment]
Thank you but, how do I  do that ? I tried UIkit.formSelect($('#ceplanetid')) or 
UIkit.formSelect($('#ceplanetid').val(1)); 
since it does not work , I don't know how to do it. 
I couldn't find it in the docs .

**Comment by Omar-Faramawi** [comment]
how to manually reinitialize it after appending new options ?
