### ISSUE TITLE
multiple sticky elements 

### ISSUE THREAD

**Issue by fluctusz** [uikit/uikit#1516]
hi,
is ist possible to have multiple sticky elements with increasing offsets to stack them on top when scrolling down? 
2nd question: ist there a javacript event that can be used to do some actions when an element reaches its sticky position?
thanks for all this great uikit stuff at this point!
martin

**Comment by malles** [comment]
Check the [test page of the sticky element](http://getuikit.com/tests/components/sticky.html) and [its source](https://github.com/uikit/uikit/blob/master/tests/components/sticky.html).
See the [javascript options](http://getuikit.com/docs/sticky.html#javascript-options) for the events fired by the element.
