### ISSUE TITLE
Notify position changes when Modal is opened

### ISSUE THREAD

**Issue by Carobit** [uikit/uikit#1520]
Hi,
I just met a problem using Notify+Modal components.
I use the notify element for displaying confirmation/error messages. However in some cases the forms and other contents are in modals. When a modal window appears, then the notification is shifted to the right (by the width of the scroll bar).

If I change the overflow property, then the notification remains fixed, but then 2 scrollbars appear and the content of the page is scrollable in an odd way. Not a great solution..
Perhaps another way could be to calculate the scrollbar width and dynamically change the stylesheet..

demo:
http://jsfiddle.net/tmftr4fj/3/

Any idea, how may I fix it?

**Comment by malles** [comment]
The notification is centered in the page. The modal does influence that. I don't see an easy workaround for this that would not cause more trouble than the initial problem.
