### ISSUE TITLE
Delay when `data-uk-grid-margin` gets applied to dynamic content

### ISSUE THREAD

**Issue by jaypanares** [uikit/uikit#1523]
There seems to be a delay when `data-uk-grid-margin` gets applied to a grid with dynamic content.  The horizontal grid margins appear half a second late which causes jerky looking behavior.  Is this a bug?  I'm using a Meteor package with version 2.22.0.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
