### ISSUE TITLE
uk-slidenav-next won't show up

### ISSUE THREAD

**Issue by raganello1** [uikit/uikit#1524]
Hi I am using a code taken from getuikit web site, everthing works fine except for the next arrow that doesn't show up. The prev arrow works fine, and in the code with the inspector I see it but where is it?

**Comment by pixelcrash** [comment]
Same here - any update on that?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
