### ISSUE TITLE
Dialog/Modal collection instances & their status

### ISSUE THREAD

**Issue by fursid** [uikit/uikit#1525]
Is there a way to find if a dialog/modal already open(show) on the page? Perhaps a collection object that returns the Dialog/Modal instance available on the current view with their status (shown/hidden)?

Scenario: If a dialog is already open, don't open another dialog with same text/content. or queue dialogues to show after one is closed? Would like to have this functionality to handle multiple dialogues/modals that are fired pragmatically from different sections of the code.

**Comment by fursid** [comment]
*bump*

**Comment by malles** [comment]
The modals are not kept in a collection. You could keep that collection for your self, by setting up the modals manually via js;
```
var modals;
UIkit.$('.uk-modal').each(function () {
   modals.push(UIkit.modal(UIkit.$(this), {options}));
});
```
Each modal instance has a method to check if it's opened `modal.isActive()`.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
Thanks for your understanding,
Your UIkit Team
