### ISSUE TITLE
form-icon is not compatible with form-large

### ISSUE THREAD

**Issue by marshallds** [uikit/uikit#1529]
When using the `form-large` class on an input element a `form-icon` does not have the proper `margin-top`.

![image](https://cloud.githubusercontent.com/assets/1408713/10087836/be75908c-62d3-11e5-9bfe-5feb0baeca52.png)

It seems like this line is unnecessarily subtracting the icon height from the input height:
https://github.com/uikit/uikit/blob/master/src/less/core/form.less#L594

**Comment by zslabs** [comment]
Couldn't we also just use the vertical-align trick?

```
.container {
  position: relative;

  > .child {
    position: absolute;
    transform: translateY(-50%);
    top: 50%;
  }
}
```

**Comment by Pandahisham** [comment]
+1

**Comment by 8va76** [comment]
I experience this before, i change my jquery version to the latest and it works fine. :)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
