### ISSUE TITLE
Switcher component and Firefox lag.

### ISSUE THREAD

**Issue by dacevedove** [uikit/uikit#1530]
Hi, im having a trouble with the switcher component, in chrome the page works perfect but in Firefox for some reason the hole tab become too slow (i mean REALLY slow) and unstable. Any idea why? Im using warp. 

The page with the problem is this (in case you have some spare time) www.greencleansteamwash.com (the services section)

**Comment by florianletsch** [comment]
Wow, this is really unusable. However, I already seem to be having these issues just when scrolling. Firefox seems to take some really long time for redrawing. 

I opened the run time analysis tab in the Firefox web tools. It seems like this actually isn't related to UIkit, or at least not exclusively? 

The browser seems to be taking most time in the code from the slider script you have included. I have attached the screenshot (sorry it's in German). I guess you will need to look into that a bit further yourself. Good luck!

![screen shot 2015-10-30 at 17 11 01](https://cloud.githubusercontent.com/assets/1116784/10851049/407155aa-7f29-11e5-9f85-e68021a0a77d.png)
