### ISSUE TITLE
Ajax request headers

### ISSUE THREAD

**Issue by rockymontana** [uikit/uikit#1531]
Hiello'

I'm trying to get autocomplete results from a service.

```
    var autocomplete = $.UIkit.autocomplete($('#landlord'), {
        'source': '/landlords/search',
        'param': 'q'
    });
```

But since I do work with Laravel on the server end I need to send extra params (such as token).
But it seems like the autocomplete have no support for sending either headers or any post data other than just defining what param should be pass the query data.

Any thoughts on this?

**Comment by vuchl** [comment]
Maybe you can use [`jQuery.ajaxSetup()`](https://api.jquery.com/jquery.ajaxsetup/) before sending the request to the laravel backend. I think you could use it maybe like
```javascript
Ui.$.ajaxSetup(...);
```

**Comment by Pandahisham** [comment]
+1

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The autocomplete component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
