### ISSUE TITLE
uk-nav-side problem with uk-contrast

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1533]
when add ```uk-contrast``` to slide panel with ```uk-nav-slide``` on hover show shadow and move up

**Comment by malles** [comment]
Do you mean slide or side? Can you provide a example?

**Comment by mojtabakaviani** [comment]
```uk-nav-side````

**Comment by malles** [comment]
http://codepen.io/malles/pen/EVzKQo

It seems to work fine here.

**Comment by mojtabakaviani** [comment]
problem when add ``` uk-contrast ``` to ``` uk-nav-side ``` class

**Comment by malles** [comment]
Always apply `uk-contrast` to the container: http://getuikit.com/docs/contrast.html#usage
