### ISSUE TITLE
uk-container uk-container-center not centering on Internet Explorer and Firefox

### ISSUE THREAD

**Issue by ghost** [uikit/uikit#1534]
Just need to go to your documentation Utility page to see the result not being centered

http://getuikit.com/docs/utility.html

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
