### ISSUE TITLE
Feature request: control where widgets get rendered into

### ISSUE THREAD

**Issue by colmbrady** [uikit/uikit#1535]
Some UIKit widgets (e.g. datepicker) render themselves into the DOM by appending to the body element. This assumes that the body has UIKit styles applied. My code is running inside a portal environment, and the UI Kit styles are namespaced and applied only to a div element inside the body. Therefore, when the datepicker (and other widgets) are rendered, they do not have the correct styling applied as appending to the body will be outside of my container DOM

Please see example code:
1. UIKit CSS has been wrapped in custom namespace so only DOM elements with class of "my-namespace" will be able to get the datepicker styling. (This is a custom build step not supported by UIKit)

``` css
.my-namespace {
.uk-datepicker .... This is the UIKit CSS
}
```
1. Declare the date picker markup.

``` html
<body>
<div class="my-namespace">
<form class="uk-form">
    <input type="" data-uk-datepicker="{format:'DD.MM.YYYY'}">
</form>
</div>
</body>
```
1. When page is loaded, date picker appends to BODY. Unfortunately it is unstyled as it renders outside "my-namespace" div. 

``` html
<body>
<div class="my-namespace">
<form class="uk-form">
    <input type="" data-uk-datepicker="{format:'DD.MM.YYYY'}">
</form>
</div>

<div class="uk-datepicker">
etc...
</div>
</body>
```

I am proposing that components with this render behaviour have an default attribute called container added, which has a default value of 'body' - but a developer can decide to override that selector with a custom one, e.g. #my-uikit-widgets-container.

The change in datepicker.js would be something like this:

``` javascript
defaults: {
            ...
            container: 'body',
};
...

dropdown.appendTo($this.opts.container);
```

If this is a useful feature you guys would like to support - I would be happy to contribute it to UIKit.

**Comment by philoest** [comment]
This has been added in UIKit3 https://getuikit.com/docs/modal#component-options
