### ISSUE TITLE
On small screen, grids can't get full width due to default padding left to all grid element

### ISSUE THREAD

**Issue by shoumma** [uikit/uikit#1536]
![startup template](https://cloud.githubusercontent.com/assets/10725804/10185719/e2916bec-676c-11e5-9f27-d54034c9cf6a.png)
On small screen, grid elements can't get full width. This is because by default grid have the following code:
```sh
.uk-grid > * {
  padding-left: 25px;
}
```

**Comment by shoumma** [comment]
It can be fixed by using the following code:
```sh
@media (max-width: 479px) {
	.uk-grid > * {
	  padding-left: 0px;
	}
}
```

**Comment by TomS-** [comment]
Hi Shoumma, I believe this is intended so text doesn't sit flush again the side of the screen. I very much doubt that this will change in the core.

**Comment by malles** [comment]
When used correctly, the grid does not behave that way. Make sure you use the correct syntax and nesting for your grid elements.
