### ISSUE TITLE
Timepicker does not support seconds

### ISSUE THREAD

**Issue by drodil** [uikit/uikit#1537]
It would be nice to have timepicker component also support seconds input. As you are already using the moment.js in datepicker component I think the re-factoring should not be too hard to do for the timepicker as well. Please consider this, thanks!

**Comment by plotnikov-maxym** [comment]
And maybe You can add the timepicker functionality to datepicker? I mean selects with months and years. It would be very handy!

**Comment by aheinze** [comment]
thanks for the suggestion, but I don't see an often scenario for this (timepicker with seconds).
