### ISSUE TITLE
Chromium Version 45.0.2454.101 (64-bit)  uk-grid-match with <img uk-responsive-width> doesn't work

### ISSUE THREAD

**Issue by yousry** [uikit/uikit#1539]
The following example keeps the aspect ration for the image in firefox.The same code does not work with chromium:

``` html
            <div class="uk-grid  uk-grid-match">
                <div class="uk-width-1-2">
                    <img src="img/female.png">
                </div>
                <div class="uk-width-4-10">
                    <div class="uk-panel uk-panel-box uk-panel-box-secondary">
                    Dies ist ein Test
                    </div>
                </div>
                 <div class="uk-width-1-10">
                </div>
            </div>
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
