### ISSUE TITLE
add Scrollbar style

### ISSUE THREAD

**Issue by faan11** [uikit/uikit#1541]
Hi guys, is it possible to add some class for styling the scrollbar?
Something like this in each theme:
http://ginva.com/2012/08/21-useful-scrollbar-css-javascript-styling-tutorials/

**Comment by zslabs** [comment]
I'm going to strongly suggest this is not added - there's plenty of existing solutions out there to get the job done and this is very seldom used nowadays. https://github.com/Diokuz/baron is a decent choice if you're looking for something like this.

**Comment by aheinze** [comment]
I fully agree with zslabs on this topic.
