### ISSUE TITLE
Nested Accordion Component

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1542]
Is it possible to have nested Accordions? So that, inside the accordion-content another accordion is functional? I tried it, but the inner accordion-title closes the outer panel.

**Comment by plotnikov-maxym** [comment]
uundh it is possible with uk-nestable elements. I did it but some dirty hacks were needed:)

**Comment by aheinze** [comment]
sorry but this needs a custom solution -  maybe someone from the community can help: https://plus.google.com/communities/114238665434626719878
