### ISSUE TITLE
data-uk-observe doesn't work

### ISSUE THREAD

**Issue by CihanAksoy** [uikit/uikit#1544]
Hi, I have a dynamic created html. 

http://prntscr.com/8n4fjm

Ajax content

http://prntscr.com/8n4fne

Result;

http://prntscr.com/8n4fqp

Should be;

http://prntscr.com/8n4fss

What can i do ?

**Comment by zslabs** [comment]
`data-uk-observe` auto inits UIkit components, it doesn't do anything with 3rd party ones. You'd have to hook into:

```
UIkit.domObserve('#element', function(element) { /* apply on dom change within element */ })
```

**Comment by aheinze** [comment]
@zslabs thanks!
