### ISSUE TITLE
Remove jQuery as dependency (BLOAT)

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#1547]
jQuery brings a lot of bloat to projects that isn't used at all.

AngularJS or VueJS make jQuery total bloatware for uikit, please exchange the needed functions with native JS.

Bringing up the whole jQuery library to a project just for UiKit is too much.

**Comment by zslabs** [comment]
That'd be a huge rewrite at this point - not sure I personally see the big advantage compared to the time it would take to make that transition. We're talking about 30kb gzipped, which is smaller than most images you'd also have on your site. Maybe you could start a branch and the transition to compare the effort involved?

**Comment by uikid** [comment]
@zslabs are you sure about the huge rewrite?

you only mentioned the size, the performance boost would be also noticeable. things could run smoother. for some cool devs, jquery is going to die.

better now than later.

**Comment by zslabs** [comment]
@uikid Ha not sure I get what "for some cool devs" means, are you saying jQuery isn't cool? Certainly no need to use jQuery if it's not needed, but remember that UIkit is built by YooTheme, a company that builds commercial Joomla/WordPress themes, both of which depends on jQuery. So -- the reasoning behind using jQuery was most likely a business and familiarity decision - one that I don't see the need of spending a huge amount of time on for little to no gain for their end-goals of the framework. Let's also not forget, https://twitter.com/paul_irish/status/431584056883429376

**Comment by uikid** [comment]
@zslabs what I mean with cool devs is: Layers like Angular or Vue are way more better to get things done, people will move away from jquery because it won't be needed anymore. Get it?

And guess what, YooTheme is starting too: Pagekit uses Vue! The only reason they need jquery is for some UiKit stuff that could be replaced with simple vanilla JS functions.

I really loved jquery, but now I only need it for some UiKit stuff. If you haven't used Angular or Vue then try it, you will see that your 30 kb compressed stuff is a bit much for some functions that easily could be replaced.

Angular startet with jquery too, now they moved away from that. It's starting to get too heavy.

**Comment by zslabs** [comment]
@uikid Totally get it and a good conversation to have. I'm all for anything that'll push UIkit to new levels, we just always have to weigh the benefits of a restructure/rewrite while there's lots of other moving pieces in the framework.

**Comment by uikid** [comment]
The benefits are huge! And for marketing you can place another checkmark for "No jQuery dependency" on comparison lists. How cool is that?

Better now than later.

**Comment by aheinze** [comment]
sorry but it is not that simple as you think it is to remove jQuery, it has its reasons to stay (for now)

**Comment by ericboehs** [comment]
It's too bad this was closed. I too would like to see this. I'm not in the position to do it myself so I'll just leave this hopeless comment.

**Comment by mahmoudmy** [comment]
Please REMOVE jQuery dependency! It's a `must` for today front-end development.

**Comment by stefanpkc** [comment]
@aheinze probably a lot of reasons. But which ones? Care to share them with us?

I also would rather see Vuejs. However, everybody wants their own favorite.
YOOtheme uses uikit and also relies on jQuery, that might be a reason as well.

**Comment by skattabrain** [comment]
+1 for no jQuery and rewritten to use plain JavaScript.

Where UIkit is great for writing apps, those of us using React, Angular or Vue would not need to include jQuery. By not including a framework, you essentially open up UIkit to anyone using any framework.

**Comment by davidrouten** [comment]
I love uikit and *finally* convinced a few other devs to use this to build our most recent project. Love the look and feel of it, but since we just recently switched to Vue, I'm sadly having to remove the uikit markup and am now looking for a (not-as-good) replacement framework, due to it's dependency on jQuery. I'd love to see the dependency removed, however from reading the comments above, I understand that it would be a significant time sink and is unlikely to happen, just wanted to add my two cents.

Thanks for building such a killer project!

**Comment by DanijelH** [comment]
I must agree with the most common opinion here. I just spent few hours comparing different frameworks. The final decision was between Bulma and UiKit and I went with UiKit only to see now that it has a Jquery dependency. It would mean a lot if it would be removed. It is really unnecessary in 2017. 
You have done an amazing job and UiKit was my first choice but this is a deal breaker.

**Comment by yedderson** [comment]
Could UIkit use the slim version of jQuery instead ? I tried that, but it didn't work. from the [Release note ](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) of jQuery, the slim build is shipped without Ajax and animiation modules, I don't know if UIkit depends on it.

**Comment by muhajirframe** [comment]
Agree with @yedderson

**Comment by zzseba78** [comment]
Seems that things are going in this way.... stay tuned 💪 

![bildschirmfoto-2017-09-14-um-08 15 44](https://user-images.githubusercontent.com/5558563/30437039-0bd52330-9944-11e7-9452-71aad93a82e9.png)

**Comment by YassineGherbi** [comment]
FINALLYYYYY🎉🎉🎉🎉🎉🍕🍕

**Comment by vuchl** [comment]
Fuck. now I am hungry for pizza
