### ISSUE TITLE
Component Search docs missing options flipDropdown

### ISSUE THREAD

**Issue by qahar** [uikit/uikit#1548]
The component search docs at Javascript options, flipDropdown is not listed.
And the "Search in navbars" markup should be:

    <form class="uk-search" data-uk-search="{flipDropdown:true, source:'my-results.json'}">

**Comment by aheinze** [comment]
this setting is mentioned in the autocomplete docs now, and as the search component inherits from the autocomplete component... I hope that it is clear now. thanks!
