### ISSUE TITLE
Parent Item not a usable link in an offcanvas menu?

### ISSUE THREAD

**Issue by JJCDesign** [uikit/uikit#1550]
In my main menu, my parent items link to a page - this isn't a problem as the dropdown is triggered by a hover (and on touch devices the first press seems to trigger the dropdown and the second executes the link). When the menu is moved to the offcanvas element on smaller touch devices, those parent items just link straight to the page instead of triggering the reveal of child pages (it seems to show the child pages you have to have just "#" as the href, which removes the link to the parent page).

Can I get this to: click to reveal all children, then if they click on the parent item again, it launches that page?﻿

(I am a designer rather than a developer, so it might be that I'm doing something wrong - if there are any solutions please be thorough with any explanations :-) )

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
