### ISSUE TITLE
Is it possible to stop looping in the slideshow?

### ISSUE THREAD

**Issue by mariehua** [uikit/uikit#1551]
Is it possible to stop looping in the slideshow?  I am using the slideshow component for content purpose with a nav, i don't want it to loop.  There are 3 content panels, the 2nd one is the start panel (middle panel), so it will just swipe right and left to navigate.  when i'm at the left panel, swiping right, shouldn't go anywhere.  Thanks.

**Comment by aheinze** [comment]
no, sorry ... we'll discuss this. thanks for your suggestion.
