### ISSUE TITLE
OffCanvas + fixed Navbar breaks Navbar on IPhone 6 with IOS 9

### ISSUE THREAD

**Issue by joomlaproffs** [uikit/uikit#1561]
We have been testing the offcanvas cart on mobiles recently (VMuikit.com). We have noticed an issue which plagues Iphone 6 with IOS9 (but also Iphone 5 with IOS8, independently of the browser used.

The problem does not manifest itself when using recent Android-based phones.
This is a problem with we believe Uikit in general (it becomes apparent when using the uk-offcanvas-bar-flip modifier, as is done by the OffCanvas Cart module)

The Problem: using Fixed Navbar (in several Yootheme templates, we have tried Moreno and EAT, where it is particularly apparent) + Right Offcanvas causes the navbar to break.
Specifically:
1. scroll down a page, open the right offcanvas/cart
2. close the cart then the navbar gets "stuck" halfway through the screen

Examples / Videos of the problem in action (Iphone 6 / IOS 9.0.2)

EAT with Empty Cart - https://www.dropbox.com/s/bhud4x943jiklrn/EAT%20-%20Empty%20Cart%20Break.mp4?dl=0

EAT with full Cart - https://www.dropbox.com/s/lr7s6cfqbvv0hm6/EAT%20-%20full%20cart%20Break.mp4?dl=0

MORENO with full Cart - https://www.dropbox.com/s/5516lp1doxmqg60/MORENO%20-%20full%20cart%20Break.mp4?dl=0

We wrote about this issue on the Yootheme forum a number of times, but received unsatisfactory answers:

yootheme.com/support/question/84817
yootheme.com/support/question/85106

**Comment by TomS-** [comment]
Hi, 

I don't use Yootheme however I do use UiKit. I have this trouble with the websites I build using UiKit. 

The off-canvas and sticky seems a little buggy. For example if you resize the browser when it's open, it doesn't work out the new width. However most of these problems can be fixed with CSS overrides. 

Here are the CSS declaration I use:

Apply this CSS to the sticky header 
(if it's right aligned)
left: auto !important;
width: 100% !important;

(if it's left aligned)
right: auto !important;
width: 100% !important;

**Comment by joomlaproffs** [comment]
Any comment on this YOOtheme/UIkit team?

**Comment by joomlaproffs** [comment]
Ok, a client of ours have found CSS fixes for Moreno and EAT template for these issúes:

Could you PLEASE YOOtheme have a look at them, test them and see if you can make your sticky-navbar more caompatible with UIkit Offcanvas things from the right. Its an important thing! 

From our Client: 
I seem to have found a solution to the breaking sticky-navbar problem; similar css overrides will work for both

YOO_MORENO
- add the following lines to custom.css :

.tm-sticky-navbar .tm-block-top {
position: fixed;
top: 0;
left: auto !important;
right: 0;
z-index: 1000;
width: 100%;
mox-box-sizing: border-box;
box-sizing: border-box;
}

the important lines are :
left: auto !important;
right: 0;

YOO_EAT:

add the following lines to custom.css:

[data-uk-sticky].uk-active.tm-navbar {
position: fixed;
top: 0;
left: auto !important;
right: 0;
}

again

left: auto !important;
right: 0;

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.
