### ISSUE TITLE
Body prevent scroll?

### ISSUE THREAD

**Issue by phavlo** [uikit/uikit#1566]
$("[data-uk-slider]").find('.uk-slider').on({
        'touchstart': function(evt) {
            $('body').on('touchmove', function(e){e.preventDefault();});
        },
        'touchend': function(evt) {
            $('body').off('touchmove');
        }
    });

**Comment by florianletsch** [comment]
Can you please elaborate? What is your question, what is your issue?

**Comment by phavlo** [comment]
In all component on drag or swipe, document scroll in Y.

No hablo ingles! Perdon!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
