### ISSUE TITLE
Combo Component: Dropdown & Toggle

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1567]
Hey @aheinze & @saschadube,
With the release of 2.23.0, the dropdown component is getting crazy powerful by abstracting away bigger parts of the hard-coded logic about "how" a dropdown should act; which is awesome. One thing that made me move away form the dropdown component earlier on was a fundamental issue between mobile and desktop experiences. For example, let's say you had a regular dropdown menu on desktop, but that same DOM need to be switched to a "toggle" on mobile -- the current way the dropdown component is setup doesn't allow something like that to work. 

So - I built my own "combo component" to handle being a dropdown when I need it to be and a toggle when I didn't. You can see this in action by visiting http://www.thecassinagroup.com/results-gallery You'll notice (on a larger screen - 768 and up, the search filters at the top (Price, Type, Beds, etc) act like normal dropdowns. No biggy. As you resize your window smaller, you'll notice the searchbar disappears. If you click the "Filter" button, you'll notice a panel slide-out which then has those same dropdown labels, but now they act as toggles. This is done by switching a simple data-attribute and some simple CSS/JS watchers that change the UI around it. 

Do you think this would be something we could work together on to join both a toggle and dropdown component together? The reason behind this again is mobile vs desktop experiences. This would involve making the DOM markup a little more abstract, but in doing so, think we could have a really powerful component. Thanks!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
