### ISSUE TITLE
Sticky with negative top?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1568]
I have a website with a menu which has an image at the top. I would like the menu items to be sticky with a top of 40px (to keep room for a navbar) but not the image. The menu can become rather long and I don't want people to have to scroll down to the bottom of the page before they can see the bottom menu items. So I tried to set a sticky on a div containing only the menu items and a few bits and pieces below the menu.

But when scrolling down, the image at the top of the menu keeps on scrolling when the menu itself is stuck at 40px from the top. (I know, when setting the sticky top to 0, nobody would notice the image is still scrolling.)

Setting a negative value for the sticky top means a top of 0px with a delay. In my opinion, this is a matter of incorrect semantics. I'd expect a property delay:100 separate from a top:-40.

Any ideas on how to solve this?

Or is there a way to make the menu column scrollable without an ugly scroll bar?

Thanks!

**Comment by TomS-** [comment]
Hi Jerry, I'm struggling to visualise your problem. Are you able to link to me to a live example? It sounds like you are on the right tracks however you will not need to use a sticky with negative top.

**Comment by aheinze** [comment]
closed because of overdue reply
