### ISSUE TITLE
datepicker default format

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1570]
Default format for "datepicker" is German: "DD.MM.YYYY"
International would be: "YYYY-MM-DD"

**Comment by zslabs** [comment]
Is this a question or request? You can already extend and override defaults with something like the following:

    UIkit.on('beforeready.uk.dom', function() {
      $.extend(UIkit.components.datepicker.prototype.defaults, {
        format: 'DD.MM.YYYY'
      });
    });

**Comment by doublex** [comment]
A request: The default should be ISO 8601: "yyyy-mm-dd"

**Comment by aheinze** [comment]
default is now changed to "YYYY-MM-DD"
