### ISSUE TITLE
Widgetkit2 and latest Yootheme Salt hides scrollbar after a few modals shown

### ISSUE THREAD

**Issue by joomlaproffs** [uikit/uikit#1572]
http://cnorin.com/renovering/

Im testing on Windows 7 latest Firefox. 

Go to URL above. Simple site with Widgetkit 2 and Salt template. After clicking a few images to make them big suddenly after usually 3 the scrollbar of the main page gets lost and its no longer possible to scroll on a PC/Mac with a mouse. 

Seems fine in a ipad but not on normal Desktop/laptop Browser. 

I think its UIkit related.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
