### ISSUE TITLE
Themes in Sass

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#1574]
Along with the core UIkit core/component library, I also think the themes should be run through Sass and available through the bower repo -- I've brought this up concerning the Less version before, but believe these should be included as well so users can have a good starting point.

This again speaks to the unneeded complexity of having multiple themes compared to making smart defaults out of the box and allowing the other "themes" to just extend properties as they see fit.

@saschadube @aheinze

**Comment by giovannicandido** [comment]
+1

**Comment by philoest** [comment]
As soon as UIkit3 is available for SASS the themes will be within the bower repo as well. But this will not be changed for UIkit2.
