### ISSUE TITLE
Autocomplete events not being fired

### ISSUE THREAD

**Issue by tjomk** [uikit/uikit#1576]
I'm trying to subscribe to the select event for autocomple component. Using the simplest possible code doesn't work:
```
<html>
	<head>
		<link type="text/css" rel="stylesheet" href="/static/css/uikit.almost-flat.css" />
		<link type="text/css" rel="stylesheet" href="/static/css/components/autocomplete.almost-flat.min.css" />
		<script type="text/javascript" src="/static/js/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="/static/js/uikit.min.js"></script>
		<script type="text/javascript" src="/static/js/components/autocomplete.js"></script>
	</head>
	<body>
		<div class="uk-autocomplete uk-form" data-uk-autocomplete="{source:'res.json'}">
		    <input id="someinput" type="text">
		</div>
		<script>
			$("#someinput").on("selectitem.uk.autocomplete", function(a, b, c) { console.log(b); });
		</script>
	</body>
</html>
```
I am not particularly good with JavaScript. I tried to look at the source code, and when the library's [trigger function](https://github.com/uikit/uikit/blob/master/src/js/components/autocomplete.js#L201) is called, it returns the element instead of executing the code. Swapping it with the jQuery's [trigger function](https://github.com/uikit/uikit/blob/master/src/js/components/autocomplete.js#L204) with the correct event executes my callback without the problem.

So is this a bug or am I doing something wrong here?

**Comment by malles** [comment]
The `selectitem.uk.autocomplete` event is triggered on the `data-uk-autocomplete` element, not the input.
` $("[data-uk-autocomplete]").on("selectitem.uk.autocomplete", function(a, b, c) { console.log(b); })`
