### ISSUE TITLE
Datepicker add position left and right.

### ISSUE THREAD

**Issue by bukinoshita** [uikit/uikit#1577]
Now datepicker only accepts `pos: top, bottom and auto`. As you can see on the image bellow, the datepicker is off screen. Would be great to have the feature to adjust it to the right or left.

![screenshot 2015-10-22 08 48 05](https://cloud.githubusercontent.com/assets/6929565/10665506/b1580250-7899-11e5-8063-65e6a4ac911d.png)

**Comment by catalin-testenv** [comment]
+1

**Comment by FrantisekVrab** [comment]
+1

**Comment by FrantisekVrab** [comment]
@BuKinoshita
@catalin-testenv 
Some quick fix


```
	$('.uk-datepicker-input-right').on('show.uk.datepicker', function(){
		$('.uk-datepicker').addClass('uk-datepicker-right');
	});
	$('.uk-datepicker-input-right').focusout(function(){
		$('.uk-datepicker').removeClass('uk-datepicker-right');
	});
```

need to style ```uk-datepicker-right``` with negative margin-left...

**Comment by sanex3339** [comment]
ping

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team

**Comment by brianpeat** [comment]
Well this bites. "we're not going to fix it, but we also aren't done with the new one" well crap.

**Comment by brianpeat** [comment]
@FrantisekVrab any chance you can give more detail on your fix? I'm trying to implement it and not having any luck.

**Comment by brianpeat** [comment]
aha, I got it, I put it in the datepicker.js file, just after this line:
template: function(data, opts) {
