### ISSUE TITLE
Autocomplete/search dropdown after v2.23.0

### ISSUE THREAD

**Issue by maxlysenko** [uikit/uikit#1579]
Since version 2.23.0 `uk-dropdown-flip` class became deprecated.
What to do now with autocomplete and search dropdowns?
Setting `{flipDropdown: true}` adds `uk-dropdown-flip` class, but the class is deprecated.
So how to flip autocomplete and search dropdowns and how to set boundaries for them?

**Comment by aheinze** [comment]
you can still use uk-dropdown-flip etc, the will be available in all 2.x releases but will be removed in 3.x.
