### ISSUE TITLE
Loading issue when using dynamic grid

### ISSUE THREAD

**Issue by webchun** [uikit/uikit#1580]
I have an issue when using dynamic grid. 
Please have a look on this http://jsfiddle.net/2s5Ljon2/ to see what I mean. The grids looks ugly (they are overlapped each other) when the page is loading.
You can see what I mean in here http://i.imgur.com/RPPp3y9.jpg

![ugly](http://i.imgur.com/RPPp3y9.jpg)

Is there any workaround for this issue?
Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
