### ISSUE TITLE
Nestable & Sortable Scroll Problem

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1581]
Hi, I have noticed a problem with scrolling of sortable and nestable items. If I drag the items and move them to the border of my browser, it scrolls very fast to the bottom. The larger the item, the faster it scrolls.

In this codepen you can test it. Drag the big item with the text and move it to the bottom and it will scroll almost instantly to the bottom of the page.

http://codepen.io/Riddler84/pen/VvQEJe

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 
The ###### component has not been released yet 

Thanks for your understanding,
Your UIkit Team
