### ISSUE TITLE
dotnav and slidenav do not get initialized using data-uk-observe

### ISSUE THREAD

**Issue by stefanpkc** [uikit/uikit#1587]
When using data-uk-observe with slideshow the dotnav and slidenav do not get initialized. They are visible because of the css. But when you click on them it will refresh the page due to href=""

**Comment by aheinze** [comment]
do you add the ```data-uk-slideshow-item``` attribute? e.g.: ```<li data-uk-slideshow-item="1"><a href=""></a></li>```

**Comment by stefanpkc** [comment]
yes.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
