### ISSUE TITLE
Autocomplete-problem in Callback and Custom Layout (SOLVED but with some questions)

### ISSUE THREAD

**Issue by 8va76** [uikit/uikit#1588]
Hi, im playing with this code and the drop down says "undefined".

This is my JS code:
``` javascript
(function ($, UI) {
 
function getAutocompleteData (release)

    $.get(
        'application/ajax/autocomplete.php',
        {search: this.value},
        function(data){		
             release(data);
             $("#message").html(data);
        }
     );   
}
    
 UIkit.on('domready.uk.dom', function(){
    UI.autocomplete($('#autocomplete'), {
      source: getAutocompleteData
    });
  });
}(jQuery, UIkit));
```
This is the JSON from my source as shown in "#message":
```
[{"vendor_id":"127","vendor_name":"JC Company","vendor_address":"NY"},{"vendor_id":"33","vendor_name":"SPC Telecom","vendor_address":"Canada"},{"vendor_id":"4","vendor_name":"JKL Shipping","vendor_address":"Africa"}]
```
and in my HTML code:
```
        <div class="uk-autocomplete uk-form" id="autocomplete">
                <input type="text" id="autocomplete-input" placeholder="Action when clicked"/>
                <input type="text" id="data-value"/>
                <script type="text/autocomplete">
                  <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
                    {{~items}}
                        <li data-value="{{ $item.vendor_name }}"  data-id="{{ $item.vendor_id }}"">
                               <a>{{ $item.vendor_name}}</a>
                        </li>
                    {{/items}}
                  </ul>
                </script>
            </div>
```
I can't figure out where is my mistake. Many thanks for the help! :)

**Comment by 8va76** [comment]
I have found the solution for my problem above, Now, what i wanna know if this is acceptable and how can i make my code simplier or any other coding that will give the same result? Thanks! :)

JS Code:

<script>
(function ($, UI) {

function getAutocompleteData (release) {
    var search = this.value, items = [];

    // autocomplete.php creates a json file (vendor.json)
    $.get(
        'application/ajax/autocomplete.php',
        {q: this.value},
        function(data){
           // just to see if it returns a json data 
           $("#message").html(data);           
  
            $.getJSON("application/ajax/vendor.json", function(result){
                result.forEach(function(item){
                    if(item.vendor_name && item.vendor_name.toLowerCase().indexOf(search.toLowerCase())!=-1) {
                        items.push(item);
                    }
                });
                release(result);
            });   
        }
    );
}    
            
 UIkit.on('domready.uk.dom', function(){
    UI.autocomplete($('#autocomplete'), {
      source: getAutocompleteData
    });
  });
      
}(jQuery, UIkit));

UIkit.ready(function() {
  UIkit.$('#autocomplete').on('selectitem.uk.autocomplete', function (e, data, ac) {
    UIkit.$('#data-value').val(data.id);
    ac.input.val(data.value);
    data.value = null;
  });
});

</script>

The HTML:

 <div class="uk-panel uk-panel-box uk-panel-box-primary">
            <div class="uk-autocomplete uk-form" id="autocomplete" >
                <input type="text" id="autocomplete-input" placeholder="Action when clicked"/>
                <input type="text" id="data-value"/>
                <script type="text/autocomplete">
                  <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
                    {{~items}}
                        <li data-value="{{ $item.vendor_name }}" data-id="{{ $item.vendor_id }}"><a>{{$item.vendor_name}}</a></li>
                    {{/items}}
                  </ul>
                </script>
            </div>
        </div>

**Comment by aheinze** [comment]
you can use chaining here:

```
UI.autocomplete($('#autocomplete'), {
      source: getAutocompleteData
}).on('selectitem.uk.autocomplete', function (e, data, ac) {...;
 });
```

**Comment by 8va76** [comment]
Thanks aheinze, :)
