### ISSUE TITLE
Navbar Submenu / Dropdown full width

### ISSUE THREAD

**Issue by julianorth** [uikit/uikit#1590]
Hi,

this is i guess an easy question but i couldnt find an answer.
What i want to do is, make the navbar submenus look like on Apple's website (http://www.apple.com/ipad/).
So the first task is to stretch the submenu container to full width like here:
https://yootheme.com/demo/themes/joomla/2015/helios/index.php?style=silver
Right now my Submenu fits the content ( 1 col ).

The second task would be to make the submenu entries next to each other , inline (with an Image / Ico above)

Cheers

**Comment by aheinze** [comment]
did you try: ```data-uk-dropdown="{justify:'body'}"``` ?

**Comment by julianorth** [comment]
Fixed, my bad. There is a preference for this in the template settings.
