### ISSUE TITLE
Dropdown doesn't hide/disappear after click (even in tutorial pages)

### ISSUE THREAD

**Issue by davedawkins** [uikit/uikit#1594]
Try opening any of the dropdown menus at this page http://getuikit.com/docs/dropdown.html
and clicking the menu items; I'm expecting the dropdown menu to close when the menu item
is clicked, but nothing happens

I'm also seeing the same behaviour in my own application.

I've tried Chrome, Edge and Firefox. I've tried reverting to jquery 2.1.1. 

I've tried using "click" event to do a removeClass("uk-open"); this hides the dropdown momentarily but it reappears. Here is my code (but keep in mind that the examples at http://getuikit.com/docs/dropdown.html don't work either):

```
  <nav class="uk-navbar uk-margin-bottom">
        <a class="uk-navbar-brand" href="#!"><i class="uk-icon-desktop"></i> Brand</a>
        <ul class="uk-navbar-nav">
            <li class="uk-parent" data-uk-dropdown="{mode:'click'}" id="exampleDropdown">
                <a href="#!">Examples  <i class="uk-icon-caret-down"></i></a>
                <div class="uk-dropdown uk-dropdown-navbar uk-dropdown-buttom">
                    <ul class="uk-nav uk-nav-dropdown">
                        <li><a class="exampleAsm">HelloWorld</a></li>
                        <li><a class="exampleAsm">Squares</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <a id="compileButton" href="#!">Compile</a>
            </li>
            <li>
                <a id="runButton" href="#!">Run</a>
            </li>
            <li>
                <a id="resetButton" href="#!">Reset</a>
            </li>
        </ul>
    </nav>
```

**Comment by aheinze** [comment]
try to add the ```uk-dropdown-close``` class to the anchor:

```<a class="uk-dropdown-close">Compile</a>```

**Comment by davedawkins** [comment]
Thank you!
