### ISSUE TITLE
Feature Request - Image Cropper

### ISSUE THREAD

**Issue by 8va76** [uikit/uikit#1595]
Please add a feature that can crop selected image. Thank you.

**Comment by aheinze** [comment]
Thank you for your suggestion, but I think this is too special for a css frontend framework.

**Comment by 8va76** [comment]
Thanks aheinze for the reply, i'm not pertaining to image cropper as an photo editor, it just load the image and select what part of the photo will be shown. it will just get the x-y coordinates. :)
