### ISSUE TITLE
how to display specific <div> when filter return no results (Dynamic Grid)

### ISSUE THREAD

**Issue by dimitrilongo** [uikit/uikit#1597]
Hello

I'm trying to display a div when dynamic grid filter return no results and hide it when the filter return results.
maybe with jquery when you click on filter button, and check if all children div are css display property set to none.

Thanks for advices

**Comment by gabrielholley** [comment]
Try checking the grid children after update. Something similar to:
```
$('[data-uk-grid]').on('afterupdate.uk.grid', function(e, children) {
    var isVisible = false;
    children.each(function() {
        if($(this).is(':visible')) {
            isVisible = true;
        }
    });
    if(isVisible == false) {
        // nothing is visible, do something
    }
});
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
