### ISSUE TITLE
upload.js multipart upload

### ISSUE THREAD

**Issue by Smeaven** [uikit/uikit#1598]
I want to upload files to an authenticated onedrive via the new `onedrive rest api`, using uikit's provided component. I am not very experience with ajax and the hole javascript behind this uikit.

I have do to a such request:

```
POST /drive/items/{folder-id}/children
Content-Type: multipart/related; boundary="A100x"

--A100x
Content-ID: <metadata>
Content-Type: application/json

{
  "name": "newfile.txt",
  "file": {},
  "@content.sourceUrl": "cid:content",
  "@name.conflictBehavior": "rename"
}

--A100x
Content-ID: <content>
Content-Type: text/plain

Contents of the file to be uploaded.

--A100x--
```

On which event do I have to manipulate the request, and how, that I create an ajax request like above?

**Comment by aheinze** [comment]
sorry, but uikits upload component just supports/uses the Formdata object, you need a custom solution.
