### ISSUE TITLE
Decelerated Parallax

### ISSUE THREAD

**Issue by suntrop** [uikit/uikit#1599]
I only see how to accelerate items with parallax, but not how to decelerate them … i.e. make it slower than scroll speed. Maybe it is not possible!? :-)

**Comment by TomS-** [comment]
1 = Scroll speed
0.4 = Less than scroll speed

**Comment by suntrop** [comment]
1 and 0.4 have no impact … I have to use 200 to see a little effect. The docs have 200 as an example too

<div data-uk-parallax="{bg: '-200'}">...</div>
See first example http://getuikit.com/docs/parallax.html

**Comment by TomS-** [comment]
You are using velocity right? velocity: '0.5'? It's working fine for me on Chrome.

**Comment by florianletsch** [comment]
Please provide an example (Codepen or JSfiddle) if this doesn't work for you. Thanks
