### ISSUE TITLE
form-select data attribute

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1600]
form-select:
The down below js-file writes the selected filename next to the "Browse" button (onChange event).

Markup:

```
<div class="uk-form-file" data-uk-form-file>
    <button class="uk-button">Select</button>
    <input id="form-file" type="file">
    <span class="uk-form-file-name"></span>
</div>
```

https://gist.github.com/doublex/02a9488273a9b70f276a

or with "filesize" next to the filename:
https://gist.github.com/doublex/bfa96563a47cadb1ab6f

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
