### ISSUE TITLE
Dropdown issue

### ISSUE THREAD

**Issue by torvalamo** [uikit/uikit#1601]
Uncaught TypeError: f.getClientRects is not a functionn.
    fn.extend.offset @ jquery.min.js:4
    t.component.checkDimensions @ uikit.min.js:2
    t.component.show @ uikit.min.js:2

Stops dropdown inside nav from working (showing). It toggles the parent "button" correctly, but no submenu is shown.

Version is 2.23.0 from CDN. **Using JQuery 3.0.0-alpha1 (I suspect this might be the issue?)**

Also, in normal dropdowns:

    Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    t.component.checkDimensions @ uikit.min.js:2
    t.component.show @ uikit.min.js:2

**Comment by torvalamo** [comment]
Actually I found the issue. It was as I suspected, jQuery 3.

But you should check this, because it's a breaking change to passing $(window)

https://github.com/jquery/jquery-ui/commit/b3a9b13a218cd90b7cf67be5d5f8ad6e76c557b0

**Comment by aheinze** [comment]
thanks! we'll check this

**Comment by aheinze** [comment]
jQuery 3 is still alpha ... please don't use it in production, as we also won't put any effort into it before it isn't in beta.
