### ISSUE TITLE
UIKit installation downloads on website and github differ. Should the website mention that?

### ISSUE THREAD

**Issue by ThinkALot** [uikit/uikit#1603]
I'm just trying out UIKit, and I'd like to suggest a way to make it easier to evaluate the framework for newcomers like me.

I think the website should mention that downloading the zip file from github provides a different folder structure -- without the css file -- than downloading from the blue button on the website, which is here: http://getuikit.com/docs/documentation_get-started.html. The latter download comes *without* the jquery file. The former comes *without* the css file. At least that was my experience. 

Initially, I downloaded the zip package from github, and then was puzzled that the folder structure did not match the one being discussed on the tutorial videos ( https://www.youtube.com/playlist?list=PL2SfpsC7cy0gv9O7nNKyQZBrFjhi3LH-V ) 

I stumbled on the solution -- to download from the website -- but other newcomers might feel frustrated, and just move on to another framework. 

So if you just mention this on the UIKit website and github, you could save some frustration, and attract more users.

**Comment by florianletsch** [comment]
Hey,

good observation and thanks for the suggestion. The reasoning here is that there are 2 packages: A "Quickstart" package with just the compiled CSS and JS files. And a "source" package which is available in the Github repository.

Actually, every release on Github has a .zip file attached to it, which also only includes the compiled files.

I guess you pressed the "Download Zip" button on Github? That will simply download the repository as a zip file.

I understand this could be explained bit clearer. Do you have any good suggestion for this? Thanks!
