### ISSUE TITLE
Problem with font awesome

### ISSUE THREAD

**Issue by dorastamenova** [uikit/uikit#1604]
Hi, this is my first experience with uikit and I like very much the concept. it is well documented and easy to start, too, which I appreciate. 
Unfortunately, something went wrong with font awesome and I am not able to solve it myself. I put an "@" icon in a form field and it displayed properly, but after some changes I made (and unfortunately I am not able of reconstructing them), instead of "@" I get "f1fa" - the numeric code of the icon, specified in uikit.css. It seams that a link is broken somewhere. Could someone give me a hint, please?
Thanks a lot!

**Comment by zslabs** [comment]
Your reference to the FontAwesome files is probably wrong. If you open up the "Network" tab in Chrome, you'll probably see an issue with FontAwesome not finding the correct files.

**Comment by dorastamenova** [comment]
I actualy figured this out and the problem was not in the wrong reference. In the css style the backslash before the icon ASCII code was omitted in the minimized file, probably due to a mistake in the minimizing script (I used online servis). I added back the backslashes and everything works just fine. Anyhow, thanks for the help.
