### ISSUE TITLE
Parallax Bug

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1605]
I've had quite a few problems with the parallax module (things like content jumping around) when it starts in the viewport. 
"http://www.andrewgeoghegan.com/" - See the first box chocolate 

However the most obvious one is when you want to animate the background downwards rather than upwards, you will often be left with a white space at the top where the image doesn't fill the div.

This pretty much means I have to avoid the parallax module. I wouldn't mind seeing a fix for this though.

**Comment by aheinze** [comment]
try give the element an initial ```style="transform: translate3d(0px, 50px, 0px);"```  parallax starts on dom ready, this explains the jump

**Comment by TomS-** [comment]
Hi aheinze,

I'm not entirely sure if that's the problem. By jump, I mean https://vid.me/98ix

Also any comments on the image bug with parallaxing the background image downwards? I'm just wondering if I'm doing something wrong. 

Thanks,
Tom

**Comment by choppe3766** [comment]
Hi TomS,
it seems, that the "bug" comes with the sticky navigation and only if the navigation is is sticky on top.
Maybe the problem is, that javascript need too long time to calculate the height of the parallax div for content positing. 
But i have no solution for that, sorry.

**Comment by TomS-** [comment]
Hi choppe, 
I've taken out the sticky nav, however the problem persists. Good guess, however it seems that this isn't the problem.

**Comment by TomS-** [comment]
Bump - This problem still exists. Still avoiding Parallax so far because of elements jumping around. I would really like to use the Parallax plugin.

**Comment by annedorko** [comment]
@TomS- Have you found any solutions? I'm running into the same problem.

**Comment by TomS-** [comment]
@annedorko I'm sorry, no solution as of yet.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Parallax component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
