### ISSUE TITLE
Request: Full page center spinner with simple bg overlay

### ISSUE THREAD

**Issue by ethanpil** [uikit/uikit#1606]
Would love to be able to trigger a spinner/loader on the center of the page without having to embed in a modal or element.

Take a look here for some great ideas on execution:
http://demos.jquerymobile.com/1.4.2/loader/

What do you think?

**Comment by ffuentes** [comment]
+1

**Comment by aheinze** [comment]
this is a special case and should stay a custom solution, but maybe as as suggestion:

```
UIkit.modal.blockUI('<div class="uk-text-large uk-text-center"><i class="uk-icon-spinner uk-icon-spin"></i></div>', {center:true});
```

**Comment by ethanpil** [comment]
I am surprised that you think a page centered spinner is a special case. Its quite common.

**Comment by kkinder** [comment]
I tend to agree. Centering an icon as an overlay is a very common thing, especially for client-wide apps.

**Comment by Jiab77** [comment]
Thanks for your code @aheinze but I can't agree with you, that's not a special case and that's a required component when you want to load big resources with a nice loading effect.
