### ISSUE TITLE
Form icon alignement

### ISSUE THREAD

**Issue by ThierryA** [uikit/uikit#1607]
`.uk-form-icon > [class*='uk-icon-']` margin top changed from `margin-top: round(@form-icon-font-size / -2);` to `margin-top: round((@form-height - @form-icon-font-size) / -2);` which is causing issue when increasing the @form-height variable.

**Comment by saschadube** [comment]
Thanks, it is already fixed in the developer branch. https://github.com/uikit/uikit/commit/f15889e4fd37f75b72d68a391a854758a6ef888f#diff-f73e8197ecb1b37b0f7496ac3a901f4b

f15889e4fd37f75b72d68a391a854758a6ef888f
