### ISSUE TITLE
Modal not displaying without additional css

### ISSUE THREAD

**Issue by 82rules** [uikit/uikit#1609]
I'm not sure why it started having this problem but Ive tested on empty html pages and keep getting the same result. 

.uk-modal has a property display:none 
.uk-open sets opacity to 1 but does not change the display to something visible. Therefore displays are not shown and modals do not behave as expected. 

here is the JSFiddle https://jsfiddle.net/h269cjgL/

its easy enough to add display:block to .uk-open but I wanted to know if I'm missing something obvious?

**Comment by zslabs** [comment]
The JS should be doing that for you when it's attached to a "trigger". If you manually call the `show()` method attached to the modal it'll do what it needs to do for visibility and classes.

**Comment by aheinze** [comment]
@zslabs thanks!
