### ISSUE TITLE
jQuery Global Dependency

### ISSUE THREAD

**Issue by arcticShadow** [uikit/uikit#1610]
Hey All,
I wanted to approach the topic of moving the global dependency on jQuery into an amd dependency (If using the amd loader) 

Would there be any objection to doing this?

**Comment by aheinze** [comment]
thank you for your suggestion, we'll consider this for future major releases

**Comment by dteirney** [comment]
@aheinze we (Orion Health) are using UIKit for an enterprise deployment alongside a series of other JS modules pulled in via a module loader. We are looking to package up UIKit for that module loader as well and it would be easier if there wasn't a reliance on global jQuery.

We are happy to contribute a PR for this change but want some assurance that it would be accepted / reviewed if we started that work. We believe it can be done in a backwards compatible way (although probably needs a bit more work towards the PR before that can be confirmed).

Should we start this work with an initial PR to help show what the changes would encompass?
