### ISSUE TITLE
Datepickers work only once with turbolinks

### ISSUE THREAD

**Issue by acaron** [uikit/uikit#1612]
My datepickers work once then stop working after page change with turbolinks. All other librairies are working except UIkit. I use turbolinks and jquery-turbolinks. I tried to use `data-uk-observe` but it is not working (the dom is not "changing") as proposed here: https://github.com/uikit/uikit/issues/560#issuecomment-51619160

Here is my init code:

```
$(document).on('ready page:load', function(event) {
  $('input.datepicker').each(function() {
    UIkit.datepicker($(this), {
      format: 'YYYY-MM-DD'
    });
  });
  [...]
```

**Comment by aheinze** [comment]
try ```UIkit.init()```

**Comment by acaron** [comment]
@aheinze it does not work

**Comment by acaron** [comment]
Also, timepicker is working (no need to add init()) so only datepicker does not work.

**Comment by aheinze** [comment]
could you please provide an example via jsfiddle?

**Comment by acaron** [comment]
How? It is on page change (a Ruby on Rails application) so I can't reproduce it with JSFiddle. Do you have a way to simulate page change?

**Comment by kirushi** [comment]
disable turbolinks

**Comment by acaron** [comment]
@kirushi that is not an option. That is also why the bug mention: with turbolinks. Datepicker is the only one not working and it must work if it really use MutationObservers

**Comment by acaron** [comment]
@aheinze I had the time to investigate today and I found out the problem. It is line 209:
` dropdown.appendTo("body");`

Since turbolinks don't reload JavaScript but change layout, the appended content is delete. `init()` is call but `dropdown` is already setup so it is not append again. Here is my fix until this case is solve:
```
if ($('body').find('.uk-datepicker').length === 0) {
  dropdown.appendTo("body");
}
```

I added this after this condition: `if (!dropdown) {` on line 181.

I can do a pull request but it seems that UIkit doesn't accept a lot of them. I think one of the admin should do a commit and apply a solution that suit UIkit mindset. What do you think?

**Comment by acaron** [comment]
@aheinze Tooltip have the same problem, I must do this to make it work:
```
if (!$tooltip) {
  $tooltip = UI.$('<div class="uk-tooltip"></div>');
}

if ($('body').find('.uk-tooltip').length === 0) {
  $tooltip.appendTo("body");
}
```

**Comment by chrisvidal** [comment]
i got same issue with the switcher, the layout is changed and the new switcher from the new layout is not called. so it seems it is a global problem.

**Comment by keyeh** [comment]
Same issue with data-uk-dropdown

**Comment by petermumford** [comment]
@dsignr - solution also works with Turbolinks, with Rails 5.0.0.

**Comment by reardestani** [comment]
On my side

```
jQuery(document).on('turbolinks:render', function() {
  UIkit.init();
});
```

works fine. Not a rail app, though.
