### ISSUE TITLE
Sortable errors

### ISSUE THREAD

**Issue by csakis** [uikit/uikit#1616]
I am using sortable as recommended in the documentation. Everything works in normal html/css/js environment. As soon as I move my code to XPages, I get errors. These errors do not mean anything to me: I paste here the errors from Firefox and Chrome, I hope somebody can tell em where to look for  the fix.
![firefox](https://cloud.githubusercontent.com/assets/2583367/11171915/49f54fae-8bb9-11e5-915b-4a0e6f802cac.PNG)
Chrome errors in sortable.js: 
![sortable2](https://cloud.githubusercontent.com/assets/2583367/11171923/7ed90418-8bb9-11e5-9cf9-1a490f3c7a95.PNG)

![sortable3](https://cloud.githubusercontent.com/assets/2583367/11171925/81c6b972-8bb9-11e5-9f0f-00377a7a7ae4.PNG)

**Comment by aheinze** [comment]
what is xpages?

**Comment by csakis** [comment]
Sorry for the late reply, I wanted to host my application on IBM cloud and it took a while to arrange it. Anyways. Here is the link to the application:
[UIkit panels](http://uikitpanels.mybluemix.net/)

It's a simple page with three panels that you can drag around. Everything works fine until you let go of the panel over another one, then you will get lots of errors in the console. Please help me debug this.

And to answer your question, [XPages](https://en.wikipedia.org/wiki/XPages) are IBM's implementation of webpages. It's a variation on Java Server Faces. I am trying to bring UIkit to the XPages community, and it goes pretty nicely, until I found this bug. And I am not sure how to handle it. I hope my sample application will help diagnosing the problem. Let me know if you need me to test things.

**Comment by aheinze** [comment]
you've forgotten to add the ```uk-sortable``` class to the sortable element, e.g.:

```html
<div class="uk-grid uk-grid-small uk-grid-width-1-3 uk-sortable" data-uk-sortable="{handleClass:'uk-sortable-handle'}">
...
```

**Comment by csakis** [comment]
Oh, man. How did I miss that, duh!!!
Thanks, Arthur
