### ISSUE TITLE
Popup & Multi modal

### ISSUE THREAD

**Issue by ZeGregg** [uikit/uikit#1617]
Adding a advanced popup feature like http://semantic-ui.com/modules/popup.html#flowing would be useful. A multi modal also will be nice.

**Comment by aheinze** [comment]
take a look here: http://getuikit.com/docs/dropdown.html#grid

**Comment by ZeGregg** [comment]
@aheinze the very interesting part in the ability to movePopup http://semantic-ui.com/modules/popup.html#/settings. Popup does not usually works like dropdown.

**Comment by aheinze** [comment]
thanks for the suggestions we'll discuss this for the next major release.
