### ISSUE TITLE
Overlay inactive on hover

### ISSUE THREAD

**Issue by ZeGregg** [uikit/uikit#1618]
Hi, Is there anyway to make an overlay active by default and remove overlay on hover?﻿

**Comment by aheinze** [comment]
don't use the ```uk-overlay-hover``` class

**Comment by ZeGregg** [comment]
Works fine like http://jsfiddle.net/Greggg/1jwtm1Ly/3/. Any simplest way?

**Comment by aheinze** [comment]
sorry but no, a "reversed" overlay functionality is not supported.
