### ISSUE TITLE
uk-position-bottom doesn't get fixed to the bottom when scrolling

### ISSUE THREAD

**Issue by ffuentes** [uikit/uikit#1622]
Hi,
I'm trying to set a fixed footer to the bottom of the page. It works good without content (no scrolling), but when the page has content, the fixed bar scroll too. It' seems to be an issue when the html and body tag have uk-height-1-1, so they got a fixed height. I've tryed to set a border to the html or body tag but get the same result.

Here is an demo: http://codepen.io/anon/pen/WQmXaa

**Comment by aheinze** [comment]
I think this is a wrong approach. more correct would be a custom class :

```
.fixed-bottom {
   position:fixed
   bottom: 0;
   left:0;
   right: 0;
}
```

**Comment by ffuentes** [comment]
Thanks @aheinze, solved my problem!

But I thought that the uk-position-bottom was for that intention, It seems to fix an element but only to the bottom of her parent, no to the entire viewport.
