### ISSUE TITLE
Delay and other stuff on mobiles

### ISSUE THREAD

**Issue by reramjiawan** [uikit/uikit#1624]
Hey guys great stuff UIKit! Love it! Way better than any other frameworks i have used so far just to name a few, bootstrap, foundation, semantic. Love everything especially the JavaScript components you make it look so easy! 

Guys the issue is that every action on mobile browsers is delayed because prevent default is not being used. Is there a way you guys could make this native? 

Also on another note, the offcanvas is causing issues when resizing the browser f.e. the navbar is being shrunk down and is not returning to its original state when using the responsive Developer Tools in FireFox f.e. The sticky component does the same thing sadly and is causing the height that is set via inline styles to remain as is and not returning to its state when the offcanvas is open and there is a resize. Is there a way we could get more freedom into components such as resizing so we can force resizing or so? 

Also is there a way to disable animations on different screen sizes ( disable on uk-hidden-small or through javascript data-uk="{uk-animation-disable: '300px'}" )  that would be awesome since mobiles dont really have the power to do all that fancy stuff that looks so great on more powerful devices. (parallax very laggy probably because of the refresh rates / update frequency on mobile browsers). CSS transitions / animations seems to be doing fine in terms of performance. We all want to achive the native feel and it is kind of sad to have such an user experience on mobiles when the name is UIKit! Anyway i am nit picking now.

EDIT:
Ah i almost forgot, the lightbox is causing the browser to go to the top and then back to the original point where it was openend when closed. This is not the case on mobiles so the user is back at the top of the page.
Very annoying.

 Thank you guys so much for all your hard work and this awesome framework!

**Comment by ifsNet** [comment]
I have exactly same problem and could not find a solution

**Comment by reramjiawan** [comment]
@ifsNet 

To fix the standard delays on smartphones im using an external script to remove it. Its not ideal i find but it does the job.

https://github.com/ftlabs/fastclick

Hope it helps.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
