### ISSUE TITLE
how to change language in  modal alert button

### ISSUE THREAD

**Issue by zsj1029** [uikit/uikit#1625]
the word of button is "ok"
i want to change it
how?
thx

**Comment by zsj1029** [comment]
ok
i found it

UIkit.modal.alert("账号或密码不能为空!", {
						center: true,labels:{Ok:'确认'}
					});

**Comment by ffuentes** [comment]
This should be in the Documentation page.

**Comment by SirFaenor** [comment]
In 3.0.3 keys must be lowercase
`            labels: {
                ok: 'Ok',
                cancel: 'Annulla'
            }
`
