### ISSUE TITLE
Feature Request - responsive 'Panel' classes

### ISSUE THREAD

**Issue by akcreation** [uikit/uikit#1628]
Hi there, I often find that when I have panels in my content, when I am viewing on small devices, the extra padding provided by the panel can cause the content inside to be a little bit crushed on such a small device.
So, what would be good is if we could have responsive panel classes, such as 'uk-panel-box-large', which would then mean that the panel is applied only on large devices for example, then on anything smaller it does not apply and therefore the content becomes the full width of the parent container.
Thanks guys, keep up the great work!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 in the cards component which have replaced the `uk-panel-boxes` and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
