### ISSUE TITLE
UIkit 2.24.0 parallax issue

### ISSUE THREAD

**Issue by ZeGregg** [uikit/uikit#1629]
Background image don´t animate on http://getuikit.com/docs/parallax.html, only see the text animation. Don´t work in Chrome, Firefox, Safari, Opera. I´m using OS X El Capitan.

**Comment by aheinze** [comment]
seems to happen only on the documentation site, the test is working fine: http://getuikit.com/tests/components/parallax.html

**Comment by ZeGregg** [comment]
Thanks you Arthur :)
