### ISSUE TITLE
Install Customizer on local

### ISSUE THREAD

**Issue by iPaoo** [uikit/uikit#1631]
Hi

It seems customizer does not work locally. I have a static server running with node. I get some 404 error for the proxima fonts but also for http://localhost:8888/uikit/tests/holder.js/300x110/auto

Also a TypeError: undefined is not an object (evaluating 'style.less') on customizer.js:88

Customizer.html is not loading overview.html and the theme select is empty

Regards
Greg

**Comment by mixmode** [comment]
Hi Greg,

here is a tutorial "Creating a Custom UIkit Theme with Gulp and Less"
http://www.sitepoint.com/custom-uikit-theme-with-gulp-less/

paul

**Comment by xklake** [comment]
the same issue for me, no theme are available for on local side. thanks.

**Comment by hannaofsweden** [comment]
I have this issue too.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We haven't released a customizer for the new version but it is on our TODO-list

Thanks for your understanding,
Your UIkit Team
