### ISSUE TITLE
Sticky width calculated wrong

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1632]
In the new release, the calculated width of sticky elements now seems to be fixed to a maximum value. When resizing the window, the width remained at fixed size less than 100%. I installed the sticky.min.js from 2.23.0 and the width is now again 100%.

**Comment by TomS-** [comment]
I'm having this issue, on window resize it doesn't recalculate it's width. I've downgraded to 2.23.0 for now.

**Comment by PixelT** [comment]
+1
I have this same issue.

**Comment by aheinze** [comment]
Thanks, fixed in the develop branch
