### ISSUE TITLE
Nestable on table

### ISSUE THREAD

**Issue by ntanas72** [uikit/uikit#1634]
Hi i am trying to make nestable work with table but no luck.

I have create a jsfiddle to make it clear

https://jsfiddle.net/sL1zun7c/

Let me know if is possible nestable to work with tr tables

**Comment by ntanas72** [comment]
found the solution myself

**Comment by ThiagoAnunciacao** [comment]
@ntanas72 Hi I am trying to use this component on a table and it's not working, my code is almost the same your jsfiddle that you post in this issue. Can you share how you fixed it?

Tks
