### ISSUE TITLE
add uk-grid-width-*-1-1 classes

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1638]
I have to open this again, for I don't understand why there are no 
.uk-grid-width-small-1-1
.uk-grid-width-medium-1-1
...
classes. We often have the case that the appearance on mobile would have to be larger than on a bigger screen, where the element is for example nested in a sidebar and thus smaller.

![image](https://cloud.githubusercontent.com/assets/862447/11500805/c5b7cc0c-982f-11e5-9b33-745919827412.png)

I alreay had an issue with that case here: https://github.com/uikit/uikit/issues/813

**Comment by willthemoor** [comment]
The *-1-1 classes exist as of 03/16 (in the bower version anyway). Good idea and thank you to whomever implemented it.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
