### ISSUE TITLE
'bug' after restore from sticky navbar (Version 2.24.00)

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#1642]
![image](https://cloud.githubusercontent.com/assets/16114000/11525288/e0c1d91c-98e2-11e5-8261-4553d7bef197.png)
![image](https://cloud.githubusercontent.com/assets/16114000/11525298/f5cfef88-98e2-11e5-902d-1e5c3a65c785.png)
![image](https://cloud.githubusercontent.com/assets/16114000/11525302/fea4cb10-98e2-11e5-8303-68ca76fed764.png)
![image](https://cloud.githubusercontent.com/assets/16114000/11525308/0917b666-98e3-11e5-8d26-f35f3e0f1930.png)

**Comment by TomS-** [comment]
This has been fixed in version 2.24.1
