### ISSUE TITLE
Sticky does not recalculate height on resize

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1643]
Hello, 

There is still a bug in the sticky header in 2.24.0 + that it doesn't recalculate the height on uk-sticky-placeholder when the browser is resized. So after resize, the content will jump when it becomes attached. 

Thanks.

**Comment by birdkiwi** [comment]
Yep, problem still exists

**Comment by prtome** [comment]
Hello, 
did you found a solution ? I am using 2.27.1 and still see the problem, wondering if I am doing something wrong in my html
Thanks

**Comment by TomS-** [comment]
No solution I'm afraid.

**Comment by zzseba78** [comment]
Hi! I think i have something like this to deal with, i end up setting the height of the placeholder with media queries, and force it with !important

**Comment by prtome** [comment]
I thought about that the problem is that when doing that,  when you resize the page, then a space appears between the navbar (with fixed size) and the next element (in my case an image so it is not nice looking)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
