### ISSUE TITLE
dropdown close on click

### ISSUE THREAD

**Issue by cauburtin** [uikit/uikit#1644]
I was reading http://getuikit.com/docs/dropdown.html#css-options and tried https://jsfiddle.net/crl/zhhcnh6m/ (with the class on the DD button) https://jsfiddle.net/crl/jetkgvtk/ (with the class on the DD div) is that supposed to auto-close the dropdown when we click in it? (both are not working on Chrome/windows for me)

**Comment by cauburtin** [comment]
moreover when doing this https://jsfiddle.net/crl/av5pzn7e/ 

    $('.uk-dropdown').click(function(e){
      if (!e.target.classList.contains('uk-nav-header', 'uk-nav-divider')){
        $(this).hide();
      }
    })

there are issues, as soon as hidden the dropdown is not immediately reopenable, you have to click in the page to be able to reopen it

**Comment by cauburtin** [comment]
Does https://github.com/uikit/uikit/blob/develop/CHANGELOG.md fixes it?

**Comment by aheinze** [comment]
Hi! Yes should be fixed now!
