### ISSUE TITLE
Button Group With Dropdown Issues in Off Canvas

### ISSUE THREAD

**Issue by skytider** [uikit/uikit#1645]
When I add a button group with drop-downs inside an off canvas section, the drop down list doesn't render properly. Seems to not work in the list items or in a panel.

Btw, great framework!

**Comment by zslabs** [comment]
Create a [CodePen](http://codepen.io) to show the issue.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
