### ISSUE TITLE
html editor  content presence textarea

### ISSUE THREAD

**Issue by iaceob** [uikit/uikit#1647]
``` html
<textarea name="content" id="content" data-uk-htmleditor>
 <article data-ng-controller="guestbook as c">
        <form data-ng-submit="c.postGuestbook()">
            <div>
                <textarea name="content" id="content" data-ng-model="c.comment"></textarea> 
            </div>
           <div>
                <button>Submit</button>
            </div>
        </form>
  </article>
</textarea>
```

Resulting in incorrect rendering

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The HTMLEditor component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
