### ISSUE TITLE
Sound in youtube iframes

### ISSUE THREAD

**Issue by Madebym** [uikit/uikit#1653]
What is the deal with sound in youtube iframes?  My video is muted, from what I know there is no youtube API parameter that turns the sound on/off.

Even the videos on your page http://getuikit.com/docs/cover.html don't have sound, but sometimes the sound is there for a few moments, then it all goes silent again :)

**Comment by gabrielholley** [comment]
Try <iframe src="<url>" data-uk-cover="{automute: false}"></iframe>

The controls for the video player will likely be out of view using covers, and having sound play through without being able to mute it would suck.

**Comment by Madebym** [comment]
@gabrielholley Thanks!! I have no controls shown for this particular video, just needed sound to be heard. Thanks again.

**Comment by bladesman** [comment]
Yes, I had this exact problem but be sure to put in the correct place which is at the start of the iframe:

`<iframe data-uk-cover="{automute:false}" class="uk-position-absolute" width="560" height="315" src="https://www.youtube.com/embed/<?=$slide->featured_video?>?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>`
