### ISSUE TITLE
Documentation error (misleading)

### ISSUE THREAD

**Issue by yairpe** [uikit/uikit#1654]
The docs of scrollspy 
http://getuikit.com/docs/scrollspy.html

has

``` javascript
$('[data-uk-scrollspy]').on('inview.uk.scrollspy', function(){
    // custom code...
});
```

but it does not work.

the actual working code is:

``` javascript
$('[data-uk-scrollspy]').on('uk.scrollspy.inview', function(){
    // custom code...
});
```

All the events names there are wrong too:

```
init.uk.scrollspy   Triggered when the element is initially in the viewport.
inview.uk.scrollspy Triggered when the element is in the viewport.
outview.uk.scrollspy    Triggered when the element leaves the viewport.
```

should be

```
uk.scrollspy.init   Triggered when the element is initially in the viewport.
uk.scrollspy.inview Triggered when the element is in the viewport.
uk.scrollspy.outview    Triggered when the element leaves the viewport.
```

It took me couple of hours to figure that out

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This shouldn't appear in the new Docs.

Thanks for your understanding,
Your UIkit Team
