### ISSUE TITLE
Dynamically added elements to an accordion don't work.

### ISSUE THREAD

**Issue by orszaczky** [uikit/uikit#1659]
I'm trying to add new accordion sections to my UIKit data-uk-accordion dynamically, and when I click on the title, it throws the following error:

TypeError: wrapper is undefined, on line 73 of accordion.js in UIkit 2.24.2: wrapper.data('toggle').toggleClass(this.options.clsactive);

I tried adding data-uk-observe to the accordion div, or its parent divs but didn't have any effect, and also tried to reinit the accordion manually by adding it an id, and running UIkit.accordion('#id'), but no change.

There seem to be two related issues on stackoverflow, both unanswered:
http://stackoverflow.com/questions/34189220/uikit-accordion-and-ng-repeat-doesnt-work
http://stackoverflow.com/questions/33731080/how-to-correctly-append-dynamic-getuikit-accordions

Is this a bug, or is there a the proper way of reinitializing the accordion?

**Comment by ZeGregg** [comment]
All components can be initialized manually by JS as followed UIkit.accordion($('#elementID'), {option: 'value'});

Omit the data-uk-accordion attribute to prevent the component from booting before you want it to.

https://jsfiddle.net/Greggg/mp0ksw63/

**Comment by whitelynx** [comment]
@ZeGregg: That helps for controlling initialization time, but it doesn't help if you need to add more elements after you've already initialized. Omitting `data-uk-accordion` and instead doing `UIkit.accordion($('#elementID'), {collapse: false})` instantly gives me the error the OP described:
```
Uncaught TypeError: Cannot read property 'data' of undefined
UI.component.toggleItem	@	VM475 /home/dbronke/devel/personal/querytron/node_modules/uikit/dist/js/components/accordion.js:73
(anonymous function)	@	VM475 /home/dbronke/devel/personal/querytron/node_modules/uikit/dist/js/components/accordion.js:59
jQuery.event.dispatch	@	/home/dbronke/devel/personal/querytron/node_modules/jquery/dist/jquery.js:4732
elemData.handle	@	/home/dbronke/devel/personal/querytron/node_modules/jquery/dist/jquery.js:4544
```

Adding `showfirst: false` to the options delays that error until the first time you try clicking an accordion title, but then it shows the same exact error.

**Comment by whitelynx** [comment]
In poking at the return value of `UIkit.accordion()`, it seems that the correct solution is to call `.update()` on that returned object. _This should really be documented somewhere;_ I haven't found any mentions of what to do with the return value of any `UIkit.*()` function call. (and even using a site search, I can't find any mention of the `.update()` method in the docs)

```js
var accordion = UIkit.accordion($('#elementID'), {collapse: false});
// ...later...
accordion.update();
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
