### ISSUE TITLE
[Feature Request] Push-Pull Large

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1660]
Now screens are getting much much larger, I think push and pull should allow for more breakpoints. At the moment I need a break to happen at large however that's currently not a feature. 

With the introduction of xlarge, which I can see myself using a lot. I wouldn't mind seeing the push and pull allow for larger scale websites. 

:+1:

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. With UIkit3 a new XLarge breakpoint is added, please take a look if this is working for you. 

Thanks for your understanding,
Your UIkit Team
