### ISSUE TITLE
off canvas menu based on main navbar items

### ISSUE THREAD

**Issue by msharp1** [uikit/uikit#1661]
Hi,
When looking at the source of http://getuikit.com/docs/layouts_documentation.html, I notice that the off canvas items definitions are duplicated in a `#offcanvas` id : can't we create a hamburger/off canvas navigation based on the same source of links as the regular  `uk-navbar` (which the possibility to show off/on some on the item on small screens) ?

Thanks

**Comment by zslabs** [comment]
That's not how the offcanvas works unfortunately. Even if the DOM could be duplicated, each "type" of menu requires different HTML to structure the menu items as they need to be for each.

**Comment by calimou** [comment]
I understand it's a design choice ? What's the reasons behind ? When I look at the bootstrap's navbar, the default navbar consists of the same list of <li> elements both for hamburger and regular mode.
So you build your items list one time then the navigation works for every platform.

**Comment by zslabs** [comment]
Correct, but if I'm not mistaken, even with Bootstrap you need to duplicate the DOM, even if it is the same in that case. I do agree however while duplicated, the DOM for the menu should be able to inherit off of something a bit more generic found in other components cc @aheinze

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
