### ISSUE TITLE
Slideset filtering / nav stop working after try to drag item using mouse

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1664]
After try to drag by mouse the items in the slideset, the filter options / nav stop working (on desktop)

**Comment by PixelT** [comment]
Today I'm still testing the slideset. 
The don't filter anyway (not only try to drag)
Try to filter in doc page
http://getuikit.com/docs/slideset.html

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideset component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
