### ISSUE TITLE
Scrollspy sliding animation problem at iphone 5s ios 9.1

### ISSUE THREAD

**Issue by ifsNet** [uikit/uikit#1665]
Hi,

The content slide animation is coming with delay at ios 9.1 iphone 5s on chrome mobile browser.
How to fix it please ?

http://getuikit.com/docs/scrollspy.html
http://erdemygz.com

Thank you

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
