### ISSUE TITLE
Feature request: Custom button label for modals.

### ISSUE THREAD

**Issue by tranduyhung** [uikit/uikit#1666]
At the present time we have Cancel and Ok buttons for Prompt and Confirm dialogs.

I think it is better if we have options to set our own button labels for closing the dialog (Cancel) and process (Ok).

I prefer the Yes and No answers for the question "Are you sure?", instead of "Ok" and "Cancel", or clicking "Process" or "Submit" button after I enter my name in Prompt dialog instead of clicking "Ok" button.

Yes, we can build own old modals, but why not make all of this possible with just 1 line of JavaScript code instead of many lines of HTML for UI and many lines of JavaScript for handling the events?

Thank you for considering this feature!

**Comment by luetn** [comment]
+1

**Comment by tranduyhung** [comment]
Well, I looked into the source code of modal component and found out that we can put our own options to override the labels.

    UIkit.modal.confirm('Are you sure?', function(){ // do some thing if click Yes }, {labels: {'Ok': 'Yes', 'Cancel': 'No'}});

This is not mentioned in the docs. If it was, it had saved me hours of research and building my own modals to achieve this :(

**Comment by rvalitov** [comment]
Almost one year passed since this question. Still the documentation of UIKit lacks this information. Thank you for posting your findings here.

**Comment by Uhelliton** [comment]
In version 3 does not work!!!

**Comment by mSoftMS** [comment]
Anyone know how to add stack option to dialog?

**Comment by xavero** [comment]
@mSoftMS 
`UIkit.modal.confirm('Are you sure', { labels: { ok: 'Yeah', cancel: 'Nope' } })`

'ok' and 'cancel' properties are all lowercase now.

**Comment by mSoftMS** [comment]
To add "stack" option:

UIkit.modal.confirm('Are you sure', { stack: true })

**Comment by mSoftMS** [comment]
And complete confirm modal example:

UIkit.modal.confirm('Are you sure', { labels: { ok: 'Yeah', cancel: 'Nope' }, stack: true }).then(function() {
    console.log('Confirmed.')
}, function () {
    console.log('Rejected.')
});

**Comment by htkcodes** [comment]
UIKIT 2 Documentation is lacking for this. Thank you.

**Comment by Flimm** [comment]
What if you want to have more than just two buttons?

**Comment by aarongerig** [comment]
@Flimm Then you'd probably create your own modal or extend it with a custom "confirm" function. ;)

**Comment by harsh863** [comment]
> At the present time we have Cancel and Ok buttons for Prompt and Confirm dialogs.
> 
> I think it is better if we have options to set our own button labels for closing the dialog (Cancel) and process (Ok).
> 
> I prefer the Yes and No answers for the question "Are you sure?", instead of "Ok" and "Cancel", or clicking "Process" or "Submit" button after I enter my name in Prompt dialog instead of clicking "Ok" button.
> 
> Yes, we can build own old modals, but why not make all of this possible with just 1 line of JavaScript code instead of many lines of HTML for UI and many lines of JavaScript for handling the events?
> 
> Thank you for considering this feature!


This works fine:     `UIkit.modal.labels = { ok: 'Push', cancel: 'Cancel' };`

**Comment by amilano9** [comment]
> In version 3 does not work!!!

For version 3, from documentation:
"To translate the button labels, the dialog functions accept an optional options object parameter. This has a key **i18n** and two properties ok and cancel."

```
const modal = UIkit.modal.confirm('UIkit confirm!', {i18n: {ok: 'okay'}}).dialog; // The modal component
const el = modal.$el; // The modal element
```
Setting options before calling 'confirm' work also: `UIkit.modal.i18n = { ok: 'Confirm', cancel: 'Cancel' };`
