### ISSUE TITLE
Modal opened by off-canvas link not working on iPhone/iPad

### ISSUE THREAD

**Issue by Madebym** [uikit/uikit#1667]
I have two links to FAQ section on my site. FAQ section is based on the same exact setup as http://getuikit.com/docs/modal.html#modal-blank

If I open it from a normal link(not off-canvas) it displays as it should. Two 100% width columns stacked on each other.

But if I open it from the link in off-canvas navigation, it is all messed up. Text is cut-off, no words to describe it really :)) Just all messed up.

So, I know that I am not crazy because it works with normal link, just not when opened from off-canvas.

My first thoughts were that it is something with `z-index`, but the `.uk-modal` that holds the FAQ section has a higher `z-index` value.

Is it maybe something with the `transform:translateZ()` and position fixed? Anyone encountered anything similar?

p.s. Works in all desktop browsers, Windows Phone 10 and Android devices I tested on.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
