### ISSUE TITLE
scrollspy problem

### ISSUE THREAD

**Issue by ifsNet** [uikit/uikit#1669]
Hi,
Chris Rebert why you are closing my issue report ?? I do not understand !!!

the scrollspy slide effect animation does not work properly ! It is coming with delay on iphone at google chrome !!!
www.erdemygz.com or http://getuikit.com/docs/scrollspy.html

How can I fix it please ?

CHRIS DO NOT REMOVE MY MESSAGE

**Comment by anthony-redFox** [comment]
@ifsNet your issue is closed because it is duplicate the issue uikit/uikit#1665.
This issue the same duplicate uikit/uikit#1665 and should be close.
Why did you create so many issue on the same bug?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
