### ISSUE TITLE
UIKIT Dynamic Grid +Paul Irishs Infinite Scroll + ImagesLoaded

### ISSUE THREAD

**Issue by Lumartist** [uikit/uikit#1670]
Hey there,

I was just wondering, if someone managed to combine the "Dynamic Grid", Paul Irishs "Infinite Scroll" and "ImagesLoaded". I am working on a Tumblr-theme right now and tryed to use those plugins/scripts, but had some problems. I finaly added masonry, but I rather would like to use UIKIT.

I managed to combine "dynmaic grid" and infinite scroll, but it didn't work as expected. It loaded the next "page" once, but stopped working after it. On mobiles or tablets (Chrome) in some cases it didn't even load the next page.

So I was wondering, if someone is having a working example or if it is possible to load content like with Infinite Scroll through UIKIT itself?

If needed I can add my (not working) setup to the issue.

Thanks for you help in advance and thanks for UIKIT!

**Comment by ZeGregg** [comment]
A fiddle would be a good thing for getting some help. BTW infinit Scroll form Pail Irishs seems to be [unmaintained](https://github.com/infinite-scroll/infinite-scroll)

**Comment by Lumartist** [comment]
Hey ZeGregg,

thanks for your answer. Appreciate it!

I will add a fiddle tommorow (it's 5:30pm here), as I can't manage it today!

Yes, Paul Irishs Infinite Scroll is unmaintained and probably somewhat outdated, but it is, as far as I know, the only working solution so far or at least one of the few working ones. Especially when it comes to Tumblr, it is somewhat the standard and about 50 and more percent of the Thumblr themes are using it in combination with Masonry or Isotope.

It wouldn't be a problem to use masonry and UIKIT together with Infinite Scroll, but as UIKIT is coming with the Dynamic Grid, it would be Good to have everything coming from one source. Also my personal experience is, that UIKITs Dynamic Grid is faster and less ressource hungry as masonry is. But that might just be me.

Thanks for your help so far!

**Comment by ZeGregg** [comment]
You should use Dynamic Grid for making a Masonry like content and Scrollspy for the infinite scroll see #1454

**Comment by Lumartist** [comment]
That would be great, but I don't think, that I am able to adept it. I am mainly a frontend dev. I saw that example before, but it just repeats the list. For Tumblr you need some ajax-call to get the next page, and add the next items to the list.

Tumblr is using a pagination like this.

```
        {block:Pagination}<ul id="pagination">
        <li><a href="{PreviousPage}"></a></li>
        {/block:PreviousPage}
        {block:JumpPagination length="5"}
        {block:CurrentPage}
        <li><span class="current_page numbersNav"><strong>{PageNumber}</strong></span></li>
        {/block:CurrentPage}
        {block:JumpPage}
        <li><a class="jump_page numbersNav" href="{URL}">{PageNumber}</a></li>
        {/block:JumpPage}
        {/block:JumpPagination}
        {block:NextPage}
        <li><a id="nextPage" href="{NextPage}"></a></li>
        {/block:NextPage}
        </ul>{/block:Pagination}
```

With Infinite Scroll you do somethink like this:

```
$(window).load(function () {
        var $content = $('.maingrid');
        $content.infinitescroll({
              navSelector    : '#pagination',  
              nextSelector   : '#pagination a#nextPage',
              itemSelector   : '.item_container, .loading',
              loading: {
                finished: undefined,
                finishedMsg: "<em>Congratulations, you've reached the end of the internet.</em>",
                img: null,
                msg: null,
                msgText: "",
                selector: null,
                speed: 'fast',
                start: undefined
              },
              bufferPx       : 200,
              debug          : true,
        });
        });
```

I am sure, from what I saw, It would be possible with Scrollspy, but as I said for me it is too hard to adept. Also I don't expect anyone to do my work, I thought, that maybe someone is having a working example.

**Comment by Lumartist** [comment]
I decided to stick with Masonry and Infinite Scroll for the moment. The scripts are the same in size as the ones from UIKIT and as I don't know how to adapt Scrollspy with Tumblrs pagination, nor I know how to use Infinite Scroll with UIKITs Dynamic Grid, I think it's best to stick with the one I know.

I want to thank you for your help so far. I I come up with a solution at any time, I will add it here. Until then I'll close this issue.
