### ISSUE TITLE
Offcanvas navbar duplicated

### ISSUE THREAD

**Issue by caub** [uikit/uikit#1671]
Do you think it's feasable to have only one `<ul>` for the navbar and offcanvas navbar http://jsfiddle.net/crl/asxfrkt6/? i.e. no duplication of the list

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
