### ISSUE TITLE
Switcher with data-uk-scrollspy

### ISSUE THREAD

**Issue by 6feferonka9** [uikit/uikit#1672]
Hey, 
I have a problem with using animations along the switcher. I know there exist data-uk-switcher="{connect:'#my-id', animation: 'fade'}" but i want to animate each object inside div differently. This does work, when the page load, but after i click on button, to switch the content, nothing is displayed.
Here is my code : 

```
        <div id="home" class="uk-width-1-2 panel-left uk-panel uk-switcher">
            <div ng-repeat="obsah in obsah">
                <h1 class="uk-margin-large-top" data-uk-scrollspy="{cls:'uk-animation-slide-left', delay:100}">{{ obsah.h1 }}</h1>
                <h2 data-uk-scrollspy="{cls:'uk-animation-slide-left', delay:300}">{{ obsah.h2 }}</h2>
                <h3 class="uk-text-muted" data-uk-scrollspy="{cls:'uk-animation-slide-left', delay:500}">{{ obsah.h3 }}</h3> 
                <p data-uk-scrollspy="{cls:'uk-animation-fade', delay:900}">{{ obsah.text }}</p>
            </div>                                                                   
       </div>
```

and the switcher

```
           <nav class="uk-navbar uk-margin-large-top uk-navbar-flip">
                <ul class="uk-navbar-nav" data-uk-switcher="{connect:'#home'}">
                    <li><a href="#" class="active">DOMOV</a></li>
                    <li><a href="#">SNAKE</a></li>
                    <li><a href="#">NEVIEM</a></li>
                    <li><a href="#">O MNE</a></li>
                </ul>
           </nav>
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Switcher component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
