### ISSUE TITLE
Offcanvas dropdown

### ISSUE THREAD

**Issue by AleZork** [uikit/uikit#1673]
Hi,
I'm trying to add a dropdown submenu in an offcanvas panel, but I still haven't found a way to achieve it.
I've looked at the code of a couple of pages of the UIkit site like:
http://getuikit.com/docs/core.html

But I can't make it work yet.

When I click on the parent I get the chevron turn down, but it doesn't trigger the nested div showing.

Any hint would be appreciated!
Thanks  in advance.
Alessandro

**Comment by ucandoit1010** [comment]
[https://jsfiddle.net/taiwanhotdog/yh4904g9/](url)

an example for you

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
