### ISSUE TITLE
Slideshow: Swipe transition directions switched with slidenav

### ISSUE THREAD

**Issue by CinKon** [uikit/uikit#1674]
Hi,

i just updated to 2.24.2. Finally, the Swipe-Slideshow is infinite, but now the transition-direction goes in the wrong direction, when i use the slideshow-arrows. You can see it on your own website: http://getuikit.com/docs/slideshow.html

When you click the "Next"-Arrow, the Image moves from left to right, but it should move from right to left, just like it does, when you use the Slideshow-Dots for navigation.

Best regards.

**Comment by aheinze** [comment]
will be fixed with the next release, thanks!
