### ISSUE TITLE
Slidenav not visible on fullscreen slideshow

### ISSUE THREAD

**Issue by Lumartist** [uikit/uikit#1675]
Hey there,

I am having problems with the slidenav and the fullscreen slideshow. I added it as described, at least that's what I am thinking. But maybe my syntax/markup is wrong. I don't have any problems with the slidenav and a "normal" slideshow, but with a fullscreen one.

Here's my code:

```
   <div class="uk-slidenav-position" data-uk-slideshow="{kenburns:true,autoplay:true,animation:'scale',autoplayInterval:5000,duration:1000}">
                <ul class="uk-slideshow uk-slideshow-fullscreen">
                    <li>
                        <img src="img/***.jpg">
                        <div class="uk-overlay-panel uk-flex uk-flex-center uk-flex-middle uk-text-center">
                            <div class="custom_panel">
                                <h1>...</h1>
                                <p>....</p>
                            </div>
                        </div>
                    </li>      
                    <li>
                        <img src="img/***.jpg">
                        <div class="uk-overlay-panel uk-flex uk-flex-center uk-flex-middle uk-text-center">
                            <div class="custom_panel">
                                <h1>...</h1>
                                <p>....</p>
                            </div>
                        </div>
                    </li>
                </ul>
            <a href="" data-uk-slideshow-item="previous"></a>
            <a href="" data-uk-slideshow-item="next"></a>           
   </div>
```

If I check the live code, then it appears, that the nav is outside of the slide and it doesn't have any width or height. I tryed different setups, but wasn't able to make it work.

Is there anything I am doing wrong here? Btw: the slidenav.css is included, as well as the other dependant scripts.

Thanks for your help in advance!

**Comment by Lumartist** [comment]
Noone there, who is able to tell me what I am doing wrong or if this is by purpose?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
