### ISSUE TITLE
data-name="{a:1, b:2}" to data-name-a="1" data-name-b="1"

### ISSUE THREAD

**Issue by cauburtin** [uikit/uikit#1676]
Hi, I'm trying to make a CMS, the content (each component) is configurable

The way you've put components options in one data-* makes things hard to bind them (in react, it would probably be also hard in angular). I guess it's not too hard to change, and make it configurable at building,  wanted also your opinion on that

**Comment by aheinze** [comment]
hi,

I see your issue, but ```data-name-a="1"``` won't happen....maybe the possibility to make { and } obsolete, so you can just use ```data-name="a:1, b:2"```
