### ISSUE TITLE
Possibility to not duplicate content in offcanvas

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1677]
now to create menu in desktop / mobile I must write it 2 times
- one time for desktop (hide on mobile devices)
- one time for mobile (in offcanvas, hide on desktop devices)

It will be better, if I write the menu (or another content) only one time, and:
- display it normal on desktop devices + hide on mobile devices
- automatically put this menu (or container/containers) in offcanvas

This same way as [sidr](http://www.berriart.com/sidr/) works

**Comment by hansnolte** [comment]
Hi PixelT,

https://github.com/uikit/uikit/issues/1661

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team

**Comment by franklang** [comment]
[UIkit 3 offcanvas navigation menu - no duplicate content](https://codepen.io/franklang-devfrontend/full/NWpPjgZ).
