### ISSUE TITLE
Compiling custom theme does not generate component CSS

### ISSUE THREAD

**Issue by adamwoodnz** [uikit/uikit#1678]
`gulp dist -t THEME-NAME` generates the core CSS files for the theme but not the components.

This is caused by line 427 of the gulpfile:

`if (theme.path.match(/custom/)) return;`

Is there a reason for exiting here?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
