### ISSUE TITLE
New Offcanvas Navigation Suggestion

### ISSUE THREAD

**Issue by reramjiawan** [uikit/uikit#1679]
Hey guys been a while,

I have some issues regarding the offcanvas menu. If we have a heavily nested menu and make the dropdown parent link clickable aswell, this is not achievable since it can only trigger as a dropdown. To solve this problem at the moment is to keep the parent menu open by default so the parent can be clicked and the children are visible at all times, not very user friendly. My suggestion is to somehow incorporate the following functionality ( see example link ) which will lead to a much better user experience!

EXAMPLE: 
http://mmenu.frebsite.nl/demo/index.html?demo=menu-behavior-3

This plugin allows the parent to be clickable and keeping the toggle an seperate button for the dropdown trigger like the current functionality of the button group with dropdowns in UIKit. If there was a way to incorporate this within the offcanvas that would be awesome.

Thank you for reading and hoping to see this implemented!

**Comment by minthemiddle** [comment]
Yes, `parent` in the current off-canvas menu is a lost item. I could not find any way to make it clickable as well.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
