### ISSUE TITLE
uk-nav-side need uk-disabled

### ISSUE THREAD

**Issue by qahar** [uikit/uikit#1680]
Navbar and subnav have uk-disabled, but it's not work for uk-nav-side

Please add and thank you for your awesome works

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
