### ISSUE TITLE
select2 Theme

### ISSUE THREAD

**Issue by ecmel** [uikit/uikit#1682]
Are there any plans to include a select2 theme? (https://github.com/select2/select2)

**Comment by mojtabakaviani** [comment]
+1

**Comment by anthony-redFox** [comment]
@ecmel and @mojtabakaviani look at #560
In consideration:
* Tags component for forms (Like select2)

**Comment by joomla-ua** [comment]
+1
best IDEA!!!!!!

**Comment by zzseba78** [comment]
+1

**Comment by friendofdog** [comment]
+1

**Comment by worstinme** [comment]
+1

**Comment by philoest** [comment]
Select2 should work perfectly next to UIkit, but a specific theme for that seems out of scope from our point of view.

**Comment by velogonshik** [comment]
https://codepen.io/yiannistaos/pen/vXqzMw
