### ISSUE TITLE
Close dropdown when opened modal

### ISSUE THREAD

**Issue by Linfuby** [uikit/uikit#1683]
Close dropdown when opened modal.
When you open a modal, it remains open dropdown
Example:

```
<div class="uk-button-group">
    <button class="uk-button">
        User
    </button>
    <div data-uk-dropdown="{mode:'click'}">
        <a href="" class="uk-button">
            <i class="uk-icon-caret-down"></i>
        </a>
        <div class="uk-dropdown uk-dropdown-small">
            <ul class="uk-nav uk-nav-dropdown">
                <li>
                    <a id="logout">
                        Logout
                    </a>
                </li>
            </ul>
            <script>
                $('#logout').on('click', function(){
                    UIkit.modal.confirm("Are you sure?", function(){
                        // Logout
                    }
                });
            </script>
        </div>
    </div>
</div>
```

**Comment by mojtabakaviani** [comment]
use uk-dropdown-close same this:
```<div class="uk-dropdown uk-dropdown-small uk-dropdown-close">```

**Comment by Linfuby** [comment]
It is not right. When you open a modal window, the interaction with the page should not be. And if I do not close my hand, it turns out that a modal window does not perform its function.

**Comment by ZeGregg** [comment]
Works fine on my end http://jsfiddle.net/Greggg/s9wzje49/

**Comment by paul-muckypuddle** [comment]
@mojtabakaviani that solution worked for me.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
