### ISSUE TITLE
autocomplete js not working on joomla 3.4.6 or 3.4.7

### ISSUE THREAD

**Issue by barrycox** [uikit/uikit#1684]
there were security changes to the uri.php and router.php code that has caused autocomplete to top working with any url that passes parameters to a component to stop working.

for example on www.skyrun.com, you can type 'buffalo' which passess parameters only but when you type '8401' which sets url to 'index.php?option=com_jomholiday&view=item&id=1' the url gets changed to 'www.skyrun.com/index.php' only (nothing beyond the ?) somewhere along the line.  typing the url www.skyrun.com/index.php?option=com_jomholiday&view=item&id=1 directly into the browser works, but not when it's the result of the autocomplete.

this stopped working in joomla 3.4.6.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The Autocomplete component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
