### ISSUE TITLE
Slider breeds pictures

### ISSUE THREAD

**Issue by Ilya-Zhulin** [uikit/uikit#1685]
Everybody hello. 
It isn't secret that we use UIKit in CMS with dinamic content/ So. I use `slider` in Related Articles module. This module can consist several articles, but it can consist only one article. The problem is that slider shows three similar articles when I have one in relality. Live example is here http://codepen.io/anon/pen/xZOqpw
I can't delete `uk-width-1-4` because it is universal module and count of articles id dinamic.

Thanks for pay your attention.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
