### ISSUE TITLE
Switcher with active options

### ISSUE THREAD

**Issue by chrisvidal** [uikit/uikit#1686]
the 'active' does not seems to work>

```
<ul class="uk-nav uk-nav-side" data-uk-switcher="{connect:'#data-details', animation: 'fade', active: 2">
```

</ul>

It is always the first item in the list that is activated per default as we expected to activate the item no 2

**Comment by anthony-redFox** [comment]
@chrisvidal Could you please create example on https://jsfiddle.net/. Thanks.

**Comment by chrisvidal** [comment]
here : https://jsfiddle.net/yhcjb74b/7/

actually i managed to find out the issue, there is a conflict of interest between the data control option and the html markup.
if there is already a 'uk-active' class in the markup then it seems that the 'active' is ignored by the javascript - it is jsut a choice a priority i guess.

**Comment by anthony-redFox** [comment]
"uk-active" class more priority then active. 
In your example remove class "uk-active", all should work. https://jsfiddle.net/yhcjb74b/8/

**Comment by chrisvidal** [comment]
yes exactly

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
