### ISSUE TITLE
brand text don't fit the navbar ?

### ISSUE THREAD

**Issue by msharp1** [uikit/uikit#1687]
Hi,
Is someone could provide a hint how do I solve this issue ?

![selection_001](https://cloud.githubusercontent.com/assets/5676327/11963131/083a6fe2-a8e5-11e5-805e-d25e83fd4485.png)

**Comment by Linfuby** [comment]
+1

**Comment by kshitijpurwar** [comment]
Try to change the width of the navbar using ui-width-1-@.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
