### ISSUE TITLE
lightbox caption - use something else than the title tag

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1688]
The lightbox gets the caption info currently from the title text of the link.
This is bad for me because I do not want to see the standard yellow title tooltip on hovering the link. I may have an overlay element there already or a uk tooltip, both elements I can style nicely.
Can there be an alternative way like a data- element for providing the info for the caption?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The Lightbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
