### ISSUE TITLE
No text lowercase or uppercase styles

### ISSUE THREAD

**Issue by largod** [uikit/uikit#1690]
Please add uk-text-lowercase, text-uppercase classes.

**Comment by viocassel** [comment]
+1

**Comment by o15s19** [comment]
+1

**Comment by piotr-cz** [comment]
See PR #1782

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has been added to the UIkit3 Text component.

Thanks for your understanding,
Your UIkit Team
