### ISSUE TITLE
variables in uikit-variables.scss

### ISSUE THREAD

**Issue by turuto** [uikit/uikit#1691]
Hi everyone;

Whileusing the sass version of uikit, I've seen that the variables file in SASS (and in LESS) it's not quite DRY.
Let me explain myself:

Instead of having the the same value(for instance, the color  #00a8e6) repeated multiple times across the file, and its variations (lighter o darker version), wouldn't it be much simpler if we had on the top of the file the main variable values, i.e. "blue", "red",etc.  and their variations (could be hardcoded or calculated); and after that, they could be applied. 
I think in this way, the theme creation that I have seen being asked could be much more easier.

$blue: #00a8e6 !default;
$blue--light:#35b3ee !default; //even it could be calculated via lighten or darken functions
$red: #da314b !default;
.... // more colors

$primary-color: $blue;

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
