### ISSUE TITLE
Should UiKit Consider People Who Have TouchScreen Computers While Using a Mouse?

### ISSUE THREAD

**Issue by skytider** [uikit/uikit#1694]
I have a touchscreen laptop, and I use a mouse and keyboard most of the time. This creates some confusing situations such as with the Lightbox and SlideNav. I don't see the SlideNav (even in the getuikit.com examples) when I look at the lightbox images. It was very confusing, since I had a lightbox on my website as well, and I did add the slidenav CSS file. Finally, after digging through the code, I realized the uk-hidden-touch class was being added since I was on a touch device.

I'm not sure what other situations this happens on, but as touchscreens become more and more the norm (even for laptops and desktop computers), should we keep certain things still visible (such as the slidenav)? Or maybe the documentation can be updated to say that we need to override the uk-touch css if we want the slidenav to show on touch devices.

Just a thought. Maybe this will help other people who are wondering why their slidenav isn't appearing.

Thanks! Btw, I really love the GetUiKit framework!

**Comment by SaphiLC** [comment]
all the drag and drop events dont work on touch enabled devices, even the dropdowns default to click instead of hover if im on a touch enabled deviced while using mouse... i LOVE uikit but this bug is a bit frustrating

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
