### ISSUE TITLE
Sticky component slide on window resize

### ISSUE THREAD

**Issue by refschool** [uikit/uikit#1695]
i applied this class to a menu bar (a div) :
data-uk-sticky="{showup:true, animation:'uk-animation-slide-top', clsactive:'no-offset' }

the menu works perfectly, however when i resize the window, it triggers the menu to disappear then reappear with animation.
Is it possible to not make it behave that way?
thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
