### ISSUE TITLE
Bug with sticky.min.js file

### ISSUE THREAD

**Issue by nigeljoy** [uikit/uikit#1697]
I couldn't get navigation menu sticky feature working with sticky.min.js file from  https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.3/js/components/sticky.min.js

I replaced it with the unminified version and it worked fine.
Unminified versionf rom cdnjs - https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.3/js/components/sticky.js

Please fix the issue with minified version.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
