### ISSUE TITLE
Smooth Scroll not working

### ISSUE THREAD

**Issue by lenchantin** [uikit/uikit#1698]
I've used Smooth Scroll many times and it's always worked as needed. Set it up for this new page I'm working on, and clicking on the link does nothing. Tried it both with and without linking to the smooth-scroll.js file, but usually I don't.

http://159.203.124.123 -- click on the scroll icon on the lower left side of the main screen.

Any ideas?

Thanks!

**Comment by lenchantin** [comment]
Kind of figured it out. As I'm using a container for the content, and the container is what scrolls, how would I go about modifying the smooth scroll code in uikit.js? I've tried to change it to my container name with no luck.

**Comment by lenchantin** [comment]
Feel like I'm close, but so very far away. All the content is in a wrapper, which is what scrolls. I've tried everything I can think of. I'm still learning jQuery.

```javascript
    UI.component('smoothScroll', {

        boot: function() {

            // init code
            UI.$html.on("click.smooth-scroll.uikit", "[data-uk-smooth-scroll]", function(e) {
                var ele = UI.$(this);

                if (!ele.data("smoothScroll")) {
                    var obj = UI.smoothScroll(ele, UI.Utils.options(ele.attr("data-uk-smooth-scroll")));
                    ele.trigger("click");
                }

                return false;
            });
        },

        init: function() {

            var $this = this;

            this.on("click", function(e) {
                e.preventDefault();
                scrollToElement(UI.$(this.hash).length ? UI.$(this.hash) : UI.$(".content-wrap"), $this.options);
            });
        }
    });

    function scrollToElement(ele, options) {

        options = UI.$.extend({
            duration: 1000,
            transition: 'easeOutExpo',
            offset: 0,
            complete: function(){}
        }, options);

        // get / set parameters
        var target    = ele.offset().top - options.offset,
            docheight = UI.$doc.height(),
            winheight = window.innerHeight;

        if ((target + winheight) > docheight) {
            target = docheight - winheight;
        }

        // animate to target, fire callback when done
        UI.$("html,body,.container,.content-wrap").stop().animate({scrollTop: target}, options.duration, options.transition).promise().done(options.complete);
    }
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
