### ISSUE TITLE
Progress bar not working

### ISSUE THREAD

**Issue by alexdbz94** [uikit/uikit#1699]
uk-progress uk-progress-bar not working 

Show no result on 2.24.3 while it is working with 2.23 release

**Comment by aheinze** [comment]
Hi! sorry can't confirm this: http://getuikit.com/tests/components/progress.html ... did you include the compnent, e.g. ```css/components/progress.css``` ?

**Comment by alexdbz94** [comment]
Hi, thanks for the answer. I actually didn't but when I downloaded a custom version of the css from the Customizer (http://getuikit.com/docs/customizer.html) it fixed the issue.

**Comment by ZeGregg** [comment]
Please close the issue :)
