### ISSUE TITLE
Show specific tab using id target

### ISSUE THREAD

**Issue by arrowthemes** [uikit/uikit#17]
With most HTML tabs you can be able to focus on a tab on a page by adding the #id of the tab to the url. It would be nice to see this feature on uikit.

Example:
If my site is http://www.mysite.com and I have a tab with id = "mytab", the url http://www.mysite.com#mytab should make the tab active

regards

**Comment by addept** [comment]
I also really need this feature

**Comment by addept** [comment]
My solution. I set the specific id () for needed li element:

`<ul class="uk-tab" data-uk-tab="{connect:'#tab-content'}">
	<li><a href="#">TITLE 1</a></li>
	<li **id="anchor"**><a href="#">TITLE 2</a></li>
	<li><a href="#">TITLE 3</a></li>
</ul>`

Then, an external link added an anchor with this id:

> site.com/link#anchor

Finally, a small js code on a page with a tab:

```
jQuery(document).ready(function(){
 var hash = location.hash.substr(1);
  if (hash === 'reviews') {
   jQuery('#reviews').addClass('uk-active');
}});
```
It works!
