### ISSUE TITLE
switcher in ajax loaded content not working in IE9 and IE10

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#1703]
Hi,

I'm using a switcher with a button group inside an ajax loaded div. In IE11, Firefox, Opera and Chrome, it's working as expected. In IE9 and IE 10, it's not working. I used the following code with uikit 2.24.3:

``` html
<ul id="details-tabs" class="uk-tab" data-uk-tab="{connect:'#details-tabs-content'}">
  <li class="uk-active"><a href="#">Tab 1</a></li>
  <li><a href="#">Tab 2</a></li>
</ul>
<ul id="details-tabs-content" class="uk-switcher">
  <li class="uk-active">
    <!-- the div which is populated via ajax -->
    <div data-uk-observe id="my-content" class="uk-text-center"></div>
  </li>
  <li>TODO</li>
</ul>

<!-- the content loaded via ajax -->
<div class="uk-button-group" data-uk-switcher="{connect:'#button-group-content'}">
  <button class="uk-button" type="button">Button</button>
  <button class="uk-button" type="button">Button</button>
</div>
<ul id="button-group-content" class="uk-switcher uk-margin">
  <li class="uk-active">Hello!</li>
  <li>Hello again!</li>
</ul>
```

Any ideas why it's not working in IE10 and IE9?

**Comment by kidmeke** [comment]
I know this question is a few months old, but I ran into the same problem today and thought I'd comment on what worked for me in case somebody else stumbles across this post.

The solution was as simple as adding data-uk-observe attribute to an outer div. This forces uikit to observe the DOM and auto-init any newly added components.

See: [http://getuikit.com/docs/documentation_javascript.html#dom-observe](url)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
