### ISSUE TITLE
modal.confirm fired but code execution continues

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#1705]
hello - I need a little bit f help for a modal behavior I do not understand
I might be doing this completely the wrong way.Here is what I want to do.
My user clicks on the submit button , and i control the data.
In some cases, values are not mandatory, but  i need to make sure the user did not forget to fill them. So I put a modal.confirm . If answer is OK I can continue with my submission, if answer is cancel, I stay on the page. 
This is what I am doing

```
-- some code checks the data, then I fire the modal
```

   if(msgparamstext) {
             UIkit.modal.confirm("Missing data you want to continue?", function(){
               for(k = 0; k < jsonAction.params.length; k++) {
             console.log("Oh yes I am here");
             -- I modify some values, and say it is ok to continue
      }, {labels: {'Ok': "SI", 'Cancel': "NO"}});
          }
   -- I continue with my code

My problem is that while the modal is on, my code continue to be executed and the page is submitted.
I am obviously doing something extremely wrong, but cannot understand where.
All my other confirm modals are fired after user clicks a button, and work as they should, but are simpler. 

Thanks for ay tip and directions
p.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
