### ISSUE TITLE
Add uk-text-uppercase/lowercase

### ISSUE THREAD

**Issue by jsieler** [uikit/uikit#1706]
That would be nice to see some classes to set text uppercase/lowercase. Currently I'm using:

```stylesheet
.uk-text-uppercase {
  text-transform: uppercase;
}
.uk-text-lowercase {
  text-transform: lowercase;
}
```

Thanks!

**Comment by rgeber** [comment]
+1

**Comment by FlinkK** [comment]
+1

**Comment by adamwoodnz** [comment]
+1
Also:
```
.uk-text-capitalize {
  text-transform: capitalize;
}
```

**Comment by adamwoodnz** [comment]
Pull request created: https://github.com/uikit/uikit/pull/1773

**Comment by joshgilson** [comment]
+1

**Comment by apacheloco** [comment]
+1

**Comment by adamwoodnz** [comment]
My PR has been merged so I assume these will be available in the next release: https://github.com/uikit/uikit/pull/1773
