### ISSUE TITLE
font awesome inside of li list

### ISSUE THREAD

**Issue by marktwigg** [uikit/uikit#1707]
when building a menu and using the bars icon inside of a li list it returns a square image, this is due to uikit applying a font to .uk-navbar-nav>li>a

the code for my menu item is:

```
<li><a href="" class="uk-icon-hover uk-icon-bars"></a></li>
```

**Comment by marktwigg** [comment]
this can be overwritten by putting font-family: FontAwesome !important; in your own stylesheet to override the uikit behavior, but for me it seems silly to be injecting fonts at this level

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
