### ISSUE TITLE
Mobil navigation - Link remains at the same position

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1708]
An Example:
I started from the Home-Site, open the Off-Canvas-Menu, scroll down to the Download-Link and oben it.
From the Download-Site I open the Off-Canvas-Menu and the Download-Link is out of sight.

How can I make it, that the Download-Link remains at the same position.

I have a relatively high navigation and I want to prevent that you have to scroll a lot on mobile devices.

Thanks in advance

**Comment by jsieler** [comment]
Look, is that probably what you mean?
https://uikitplay.com/plays/FXsr

**Comment by hansnolte** [comment]
Hi jsieler,

many thanks for your answer.

The "view" is blank.
Must I register?

Tested with Firefox, Chrome and IE (The current version of each)

**Comment by jsieler** [comment]
@hansnolte sorry, was small bug in async script loading. Should be okay now!

**Comment by hansnolte** [comment]
Now it works.

I need to test it.

I'll show you exactly what I mean.

Please go to http://www.rpm-factories.de

Change in the mobile view of your browser.

Open the Navigation and go for example to  "Kontakt zu uns -> Datenaustauschformate"

![mobile](https://cloud.githubusercontent.com/assets/7922627/14489232/4cb28e36-016c-11e6-9c45-30cddb30a96c.jpg)



Now you are on the Datenaustauschformate-Site. Open the Navigation and it stay on top.
You have to scroll down again to see where you are.

If I am on the Datenaustauschformate-Seite and open the Navigation, the active link should be to be seen.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
