### ISSUE TITLE
Developer: Using style to generate css for a theme

### ISSUE THREAD

**Issue by fheinrich** [uikit/uikit#1711]
Hi!

So I cloned uikit from git and created my own theme. Them I wanted to use a google font instead of the default font so I set up a style (/custom/THEME-NAME/styles/STYLE-NAME/). Before, I added all google fonts to the customizer.json of course.

So but now if I build my theme with gulp, the style is untouched. This may be the default behaviour but how am I intended to use the created style? It cant be just generating the .css from the customizer, can it?

**Comment by arcticShadow** [comment]
Hi @fheinrich,
We are building a custom theme with UIkit. Although I am not sure if our use cases are the same, so the following may not be what you're looking for. 

We found that the build system won't  build your theme by default. You need to run `gulp build -t <theme-name>`, and have your theme stuff in /custom/<theme-name>

**Comment by fheinrich** [comment]
Yep, thats what I thought should work. But I created the theme and built it like you said and it didnt work as aspected.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
