### ISSUE TITLE
http://getuikit.com/docs/upload.html - misleading Markup

### ISSUE THREAD

**Issue by RichTeaTime** [uikit/uikit#1713]
The first markup example in the Upload docs doesn't correspond to what's displayed above it. Currently it says:

```
<div id="upload-drop" class="uk-placeholder">
    Info text... 
    <a class="uk-form-file">Select a file<input 
                            id="upload-select" type="file"></a>.
</div>
```

But should be

```
<div id="upload-drop" class="uk-placeholder uk-text-center">
    <i class="uk-icon-cloud-upload uk-icon-medium 
                          uk-text-muted uk-margin-small-right"></i>
       Attach binaries by dropping them here or 
        <a class="uk-form-file">selecting one
        <input id="upload-select" type="file"></a>.
</div>
```

If the more simple example is required, then maybe it should be shown first, before the more attractive version.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We updated the docs for UIkit3 that way that you always have the HTML code that created the example to see more easily how to get the same result. 

Thanks for your understanding,
Your UIkit Team
