### ISSUE TITLE
Idiomatic Global Font

### ISSUE THREAD

**Issue by calben** [uikit/uikit#1714]
hullo all,

Is there an idiomatic, documented method of setting up a global default font?
I'd like to have a base heading font (google font) and a global default font (system font) and got as far as defining the following in my customizer.json:
```
{
    "type": "font",
    "vars": [
        "*-font-family"
    ],
    "options": {
      "System Fonts": [
          {"name": "Arial", "value": "\"Helvetica Neue\", Helvetica, Arial, sans-serif"},
          {"name": "Consolas", "value": "Consolas, monospace, serif"}
      ],
      "Google Fonts": [
        {"name": "Montserrat", "value": "'Montserrat'", "url":"http://fonts.googleapis.com/css?family=Montserrat"},
      ]
    }        
}
```

But I haven't figured out a good way to set up such global settings and none of it feels like I'm doing things idiomatically, assuming there is a very straightforward way to set up fonts with UIKit that I've missed.
What should I be doing instead and is there any documentation for the topic of setting up global fonts?

**Comment by jcs224** [comment]
This is how I set it up with the SASS version:

```sass
@import "../bower_components/uikit/scss/uikit-mixins.scss";
// Start custom
@import url(https://fonts.googleapis.com/css?family=Lato);

$base-body-font-family:                          "Lato", Helvetica, Arial, sans-serif !default;
$base-heading-font-family:                       "Lato", Helvetica, Arial, sans-serif !default;
$navbar-nav-font-family:                         "Lato", Helvetica, Arial, sans-serif !default;

// End custom
@import "../bower_components/uikit/scss/uikit-variables.scss";
@import "../bower_components/uikit/scss/uikit.scss";
```

**Comment by calben** [comment]
Looks like that's how I'll do it!
Thanks!

Are there any plans to make a more idiomatic global font?
Something like a global `$header-font-family`, `$paragraph-font-family`, `$code-font-family` or were these not included as part of keeping the framework light?

**Comment by aheinze** [comment]
In general you should create a custom theme, where you set e.g a global font variable and reuse it for all components
