### ISSUE TITLE
Nestable - disable a single item from being able to nest any subitems

### ISSUE THREAD

**Issue by jcs224** [uikit/uikit#1715]
Hello,

I'm wondering if we can add a feature that prevents only one item within a nested list from being nestable itself.

Here is an example of an item category list. The items in dark gray are the items being categorized, and should not be able to nest other categories underneath them. This image represents what SHOULD NOT be able to happen:

![screen shot 2016-01-18 at 12 56 03 am](https://cloud.githubusercontent.com/assets/6226188/12385948/57117248-bd7e-11e5-9e9b-f313e18827d6.png)

Thanks!

**Comment by aheinze** [comment]
PR merged.
