### ISSUE TITLE
AMD support And RequireJS

### ISSUE THREAD

**Issue by minhcanhdn** [uikit/uikit#1717]
I use Wordpress with UiKit. 
My CSS and JS

```
assets
__css
____component/
____uikit.min.css    
__fonts
__js
____core
____component
```

After load jQuery.js and requere.js
Try to load JS by ADM
```javascript
requirejs.config({
        paths: {
            "uikit": '/assets/js/uikit.min'
        },
        config: {
            "uikit": {
                "base": '/assets/js'
            }
        }
    });
    require(['uikit!notify.min.js,sortable.min.js'], function (UI) {
        console.log('Đã load xong');
    });
```
And I get this error
Uncaught Error: Script error for "jquery", needed by: uikit
Uncaught Error: Load timeout for modules: uikit!notify.min.js,sortable.min.js_unnormalized2

Please help

**Comment by asparagino** [comment]
Looking at the docs here, you don't need the .js suffixes when you do the final require statement.

http://getuikit.com/docs/documentation_javascript.html

**Comment by anemdhana** [comment]
I see it is still an issue.
I were not successful in the html page for the code below.
Getting error that
`Uncaught Error: Script error for "/webjars/uikit/2.26.3/js/components/sortable"
Uncaught Error: Script error for "/webjars/uikit/2.26.3/js/components/notify"`

I have tried by suffixing with .js, but takes as directory path by requirejs.

`<script type="text/javascript">
            require(['uikit!notify,sortable'], function (UI) {
                console.log('hello');
            });
            </script>`
And here is the requirejs config in my main.js file.

`requirejs.config({
	baseUrl: contextPath,
	
    paths: {
    	"jquery" : '/webjars/jquery/3.0.0/jquery.min',
        "uikit"	 : '/webjars/uikit/2.26.3/js/uikit.min'
    },

    config: {
        "uikit": {
            base: "/webjars/uikit/2.26.3/js"
        }
    },
    
	shim: {
    	uikit: {
      	deps: ['jquery']
    }
  }

});`

**Comment by davidlb** [comment]
In your config, paths should point to the path of your js file not to the file
```
paths: {
    "jquery" : '/webjars/jquery/3.0.0',
    "uikit"  : '/webjars/uikit/2.26.3/js'
},
```
