### ISSUE TITLE
TypeError: wrapper is undefined in accordion

### ISSUE THREAD

**Issue by abhijeetshah** [uikit/uikit#1719]
I am getting following error when I try to expand the accordion in a dynamically added section.

    TypeError: wrapper is undefined
    wrapper.data('toggle').toggleClass(this.options.clsactive);
    @ accordion.js (line 73, col 13)

I saw couple errors issues submitted for dynamically section addition but I am not sure if they were ever resolved. Following is my test code for issue replication

     <div class="uk-accordion" data-uk-accordion>
       <div id="sectionBlock"></div>
     </div>
    <div id="addrow">Add</div>

     <div id="sectionRow" style="display:none">
      <h3 class="uk-accordion-title">Title</h3>
      <div class="uk-accordion-content">Content</div>
    </div>

Jquery Code

    $(document).on("click", "#addrow", function(){
      var newRow = $('#sectionRow').clone();
      $('#sectionBlock').append(newRow);
    })

**Comment by ZeGregg** [comment]
Did you try data-uk-observe http://getuikit.com/docs/documentation_javascript.html#dom-observe

**Comment by aheinze** [comment]
you need to call ```update``` on the accordion object after adding dynamic markup: https://github.com/uikit/uikit/blob/develop/src/js/components/accordion.js#L115
