### ISSUE TITLE
Sticky Navbar + Right Offcanvas (with 'flip' modifier) : Navbar 'breaks'  in Iphone (IOS) on all browsers (Safari/Chrome/Firefox)

### ISSUE THREAD

**Issue by gbruzzo** [uikit/uikit#1720]
Dear all

I am trying to focus developer's attention on a serious issue, which I described several times in great detail, but does not seem to have received any attention (or little).

On Github : https://github.com/uikit/uikit/issues/1561
On Yootheme Support forums: 
January 2016 : http://yootheme.com/support/question/93709
July 2015 http://yootheme.com/support/question/84817
October 2015 http://yootheme.com/support/question/89526

The issue is : when using Sticky Navigation (tried EAT, Moreno and Nano themes) and using a RIGHT Offcanvas (with the flip-modifier), opening and closing of the right offcanvas will cause the sticky navbar to be shifted towards the left; closing the offcanvas leaves the navbar "stuck" halfway across the screen.

This behaviour has been observed on recent Iphones (6) with IOS 9 and seems to happen across different browsers (Safari, Chrome to a lesser extent, and the new Firefox browser).

Android based mobiles running recent OS do not seem to suffer from this problem (the offcanvas moves across the screen from right to left OVER the navbar, leaving the same unaffected - Chrome was used as a browser).

Could someone in the community or among the developers please let us know if any work is being done on this problem? It is a very serious one, as we need the right offcanvas to work correctly. Please view the links above for images and a video of the problem in action.

Thank you in advance

Giacomo Bruzzo

**Comment by TomS-** [comment]
For now you can apply left: auto !important on the sticky menu item. It's a frustrating bug that I've come across many times. I've seen it reported many, many times also.

**Comment by gbruzzo** [comment]
Hello there TomS - I believe you may have been so kind as to reach out with a similar answer in the past. I will try again, and will report back with any findings. It truly seems to be an Iphone only problem.

**Comment by gbruzzo** [comment]
Hello there TomS - I have implemented your suggested css "hacks" (adding also right:0; to the override of the sticky navbar) - it worked! thank you very much for the suggestion.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
