### ISSUE TITLE
dependency clarification missing datepicker

### ISSUE THREAD

**Issue by LostKobrakai** [uikit/uikit#1725]
The datepicker module does have a dependency on the dropdown core module. It would be nice if such dependencies would be documented.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This will be changed in the new DatePicker Component in UIkit3.

Thanks for your understanding,
Your UIkit Team
