### ISSUE TITLE
[question] Is it reliable and futur proof to use only the grid system ?

### ISSUE THREAD

**Issue by dagatsoin** [uikit/uikit#1726]
I love the markup of UIkit grid system. But for my actual project I don't need the rest of core/components and I don't want to use the uikit.js main file. I only need a grid system.

If I make a custom build, could Uikit work this way? Is there a plan to modularize the features?

**Comment by nblackburn** [comment]
If you use [bower-uikit](https://github.com/uikit/bower-uikit), everything is broken up into modules (_less_ or _sass_) so you can include only what you need.
