### ISSUE TITLE
uk-scrollspy-inview reporting completely incorrect

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1727]
I have no idea why I'm submitting an issue, as I don't think these even get looked at; however I'm getting a bug where uk-scrollspy-inview is added to objects that are not in view. 

Like, nowhere near in view. Adding repeat:true seems to remedy the problem, however I don't want the animations to happen again when scrolling up the website.

**Comment by malles** [comment]
Sorry for the backlog in issues. I don't see the issue on the test-page. http://getuikit.com/tests/core/scrollspy.html. Are you still having issues? If so can you provide an example in a codepen/jsfiddle?

**Comment by TomS-** [comment]
Apologies, it was fixed here: https://github.com/uikit/uikit/blob/develop/CHANGELOG.md#2250-february-17-2016 

Completely forgot to close the issue.
