### ISSUE TITLE
[CDN 404] uikit cdn 404 not found ?

### ISSUE THREAD

**Issue by LadwaAditya** [uikit/uikit#1728]
![uikit](https://cloud.githubusercontent.com/assets/4971240/12635484/cb2f74a8-c5a9-11e5-8201-5d8542581878.png)

Are there any alternative cdn other than these below?

https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/css/uikit.min.css
https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/js/uikit.min.js

**Comment by luetn** [comment]
Just use the correct version values
`https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.3/css/uikit.min.css`
`https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.3/js/uikit.min.js`

**Comment by LadwaAditya** [comment]
Thank you @luetn
