### ISSUE TITLE
Custom link to uikit modal

### ISSUE THREAD

**Issue by skigo** [uikit/uikit#1730]
I need to create custom links(ex. index.html#modal-1) to uikit modals so i can share the link. Can anyone help?

**Comment by nblackburn** [comment]
This should really be asked in the forum as it's not an issue with the framework.

**Comment by malles** [comment]
You have to create some javascript logic to open the modal. http://getuikit.com/docs/modal.html#javascript

It is indeed not an issue for this framework.
