### ISSUE TITLE
uk-animation not working with uk-dropdown

### ISSUE THREAD

**Issue by qahar** [uikit/uikit#1731]
I use UIKit v2.24.3 and able to use Dropdown as "Popover". Everything is good except for simple issue .uk-animation-x is not work when I put with .uk-dropdown

Please make uk-animation work with uk-dropdown. Right now I need to add extra rule to .uk-dropdown to add the animation

And a suggestion for the docs, make it clear that dropdown container must be position relative

```
<!-- This is the container enabling the JavaScript -->
<div data-uk-dropdown> <!-- Must position relative -->

    <!-- This is the element toggling the dropdown -->
    <div>...</div>

    <!-- This is the dropdown -->
    <div class="uk-dropdown">...</div>
</div>
```

And may be it's good to have example Dropdown as popover effect. My simple test that works

```
Some
<span data-uk-dropdown="{pos:'right-center'}" style="position:relative;">
    <span> Dummy</span>
    <div class="uk-dropdown">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi atque amet quam voluptatibus expedita.</div>
</span>
text
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
