### ISSUE TITLE
uk-grid>* issue in Safari < 8

### ISSUE THREAD

**Issue by b3ns** [uikit/uikit#1732]
Hi there,

I'm using UIKit based in a predefined customer project and ran into some issues reported by users using Safari around version 8 or below.
When using:
`
uk-grid
`

with 2 columns within using
`
float: left;
`

the columns will get switched and even if using float right it's not showing up correctly.
I checked some documentation about flexbox and older browser versions and noticed that there is a prefix parameter which is not used by UIKit but needed for these older versions. So I added it and got rid of the issue. Maybe it's something to implement in UIKit to enhance compatibility with older browsers:

```
.uk-grid > * {
    -webkit-box-flex: none;
    -moz-box-flex: none;
}
```

Cheers!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
