### ISSUE TITLE
Subnav variables and hooks need a bit of clean up

### ISSUE THREAD

**Issue by samueljseay** [uikit/uikit#1733]
I just noticed that theming subnav isn't quite as smooth as some of the other components.

the top level element .uk-sub-nav has no hook.

Also the subnav items and the subnav itself all reuse one set of variables for margins:

`$subnav-margin-horizontal`
`$subnav-margin-vertical`

Would be ideal if there were separate variables for both subnav and subnav items.

I'd be happy to submit a PR for this if there is some agreeance.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
