### ISSUE TITLE
Make It Easy to Use Google Fonts with UIKit

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#1736]
UIKit is fantastic, but no one designs a site using 'Arial', 'Trebuchet' or 'Verdana' - not if you're a professional designer. Google Fonts have opened up a world of typographical possibilities on the web, and designers have taken to it with gusto. 

Right now, there doesn't seem to be an 'easy' way to switch the default fonts in UIKit to use custom choices from 3rd-party webfont providers - like Google. My request, therefore is:

1) please update the Customiser on the UIKit website, enabling us to (perhaps manually) enter a Google font - ie., by entering the css `@include` line Google gives us when selecting a font from their website. That would be awesome.

The programming for this may take a while. In the meantime, you could already do this:

2) put documentation on the site - perhaps a new video tutorial? - showing how to switch the default fonts used by UIKit to alternative Google fonts (Lato, Roboto, etc.), using CSS/LESS (perhaps even include a downloadable snippet that could be used in every project). 

Right now, doing this manually is a chore, and I'm never 100% certain I've covered the default font for *all* elements...

Many thanks, and please keep up the good work with UIKit - it's truly appreciated.

**Comment by luxlogica** [comment]
BTW: in regards to item `2)` above, what I currently do to configure a new, 'basic' default set of fonts, is to redefine the following variables in my `_base.less` file:

``` less
@base-body-font-family: "My New Body Font", Arial, sans-serif;
@base-heading-font-family: "My New Heading Font", Arial, sans-serif;
@base-code-font-family: "My New Monospaced Font", Courier, serif;
@navbar-nav-font-family: "My New Navbar Font", Arial, sans-serif;
```

These variables are based on the output of the Customiser - these are the fonts the Customiser allows you to change, in 'Advanced' mode... Am I covering everything with these, or are there other variables I should be changing?...

Many thanks in advance for any guidance.

**Comment by malles** [comment]
The best way to do this, is to clone a local copy of this UIkit repo, and create a [custom theme](http://getuikit.com/docs/documentation_create-a-theme.html) and [customizer](http://getuikit.com/docs/documentation_customizer-json.html). This is a big chore for once, and will give you much more development and design power once set up.

**Comment by luxlogica** [comment]
is this the official recommendation from UIKit for users who wish to use Google fonts? - that it's easier to go and build a whole new theme, or a whole new customizer? That doesn't sound very encouraging.

**Comment by peterbrinck** [comment]
Just create a new stylesheet, import the Google font, make a class and you're good to go.
It's even easier than to use the customizer

**Comment by malles** [comment]
UIkit is a lightweight framework, meant to be included in projects or larger systems. In order to keep that lightweight and non-bloated property, these kind of additions are up to the implementation of the framework.

**Comment by imsanjeev** [comment]
Due to font missing this happen.Add below cdns for resolved this issue.
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

**Comment by imsanjeev** [comment]
Due to font missing this happen.Add below cdns for resolved this issue.
http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css

**Comment by jsdevtom** [comment]
This is quite old but I'll post the current working answer anyway incase anyone else needs it for version 3 as [documented here][1]: 




    // 1. Your custom variables and variable overwrites. If you are using google fonts,
    //follow their instructions as normal as well. (add a link in the html for example).
    $global-font-family: 'Ubuntu', sans-serif;
    
    // 2. Import default variables and available mixins.
    @import "../../node_modules/uikit/src/scss/variables-theme.scss";
    @import "../../node_modules/uikit/src/scss/mixins-theme.scss";
    
    // 3. Import UIkit.
    @import "../../node_modules/uikit/src/scss/uikit-theme.scss";


  [1]: https://getuikit.com/docs/sass#create-a-uikit-theme
