### ISSUE TITLE
Customiser's 'Get CSS' & 'Get Less' Buttons Fail in Safari

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#1737]
I'm using the latest version of Safari (9.0.3) on a Mac with El Capitan. If I access the Customiser, change some settings, and try to 'get css' or 'get less', the buttons don't work. Clicking the buttons does nothing - you do not get an error, it simply doesn't work.

I had to download Chrome to be able to use it...

**Comment by malles** [comment]
This is a known issue, and we have not been able to fix this. Using another browser for this task is the best workaround for now.

**Comment by luxlogica** [comment]
Shouldn't this issue remain opened, until it's resolved? - this way others users will know you're aware of the issue, and won't file it again. Closing it may seem like you've decided not to resolve it.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Currently we have not released the Customizer for UIkit3 but this will come in the future.


Thanks for your understanding,
Your UIkit Team
