### ISSUE TITLE
Lightbox & Bootstrap: opening Lightbox -> always go to top

### ISSUE THREAD

**Issue by WokInKempen** [uikit/uikit#1738]
Dear,

im using ur latest version of UIKIT. Im using bootstrap / html5.

I want using the lightbox - everything is working fine. If i close the lightbox the page scrolling to top. I could stop the movement by opening the lightbox using JS via onClick and href to same location.

U can see an example on: www.wokin-kempen.de/_develop/index.php#story (Klick on: Bildergallerie: Restaurant WokIn in Kempen).

Any idea to stop the movement to top? Maybe i can catch the close/hide-event of the lightbox for location redirect?

thx in advance for ur answer & help.

Kr,
Mark

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The LightBox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
