### ISSUE TITLE
Bordered tables confusion in documentation / missing feature?

### ISSUE THREAD

**Issue by DataTables** [uikit/uikit#1739]
The [table documentation page](http://getuikit.com/docs/table.html) shows a table with a border between rows (`border-bottom: 1px solid #e5e5e5;` from uikit.docs.css). It looks great.

However, if you just apply `.uk-table` to a table you don't get any border, as would be suggested by the example in the documentation. Indeed, there doesn't appear to be a way to get a table border at all. Only the documentation appears to have this.

I might be wrong, but I would have expected the documentation examples to render using the UIKit that is available for download.

Can the documentation be updated to show the table as it would be generated by the distribution code, or preferably (particularly since it is used in the documentation, and therefore must be useful) an option to show table borders be added.

Possibly related to #342 and #1146 but these are closed now and it still appears to be an issue.

**Comment by DataTables** [comment]
It looks like the paging is similar - if you follow the code on the [pagination page](http://getuikit.com/docs/pagination.html) you don't get the same result.

The documentation page has a gradient background and border on the `a` tag, but that appears to be unique to the documentation and not in the distribution file.

I get the feeling I might be missing something?

**Comment by stebeg** [comment]
The styles depend on the selected theme. There are no borders in the standard theme. Try out the gradient or almost-flat them. You can see the differences between the themes in the customizer:

http://getuikit.com/docs/customizer.html

**Comment by DataTables** [comment]
I see - thanks for the clarification. Would it make sense to note that the documentation does not use the same theme as the default download somewhere? I was confused when the table didn't look the same as the documentation.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
