### ISSUE TITLE
modal does not show again after submit

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#1741]
hello
here is the JSFIDDLE that shows my problem: https://jsfiddle.net/prtome/2enpLbnt/1/
Normal behavior (for me):  I click on the search button, the modal is shown. If I click on cancel (uk-modal-close) , modal is closed, I click on search again , modal is open. this works perfectly

abnormal: click on search, modal opens, click on submit, function is called, modal is closed (ok until now)
click on search again, modal does not open. No error in console

reload page - modal opens again. 
Is this normal behavior ? and if yes, what should I use to have the search button active again without reloading the page?
Thanks
(tested on chrome, firefox and safari, all updated  on mac 10.11.2)

**Comment by malles** [comment]
You are hiding the modal element, not only the modal. `$("#searchModal").hide();`

See this example for controlling the modal: http://getuikit.com/docs/modal.html#javascript
