### ISSUE TITLE
Proposal to solve problems with sticky navbar+offcanvas breaking on mobile IOS: Changes to uikit.js to keep body fixed when showing/hiding offcanvas

### ISSUE THREAD

**Issue by gbruzzo** [uikit/uikit#1743]
Dear All

for quite some time I have tried to encourage Yootheme devs and/or community to help address an issue I think is quite important, that is the fact that sticky navbar + right offcanvas seem to not work very well in IOS (on all mobile browsers).

The last post on the matter was https://yootheme.com/support/question/93897
and
https://github.com/uikit/uikit/issues/1720

a quick fix suggested, e.g to force the navbar to have right:0; left:0; 

e.g in the case of YOO_MORENO to add the following lines to custom.css

.tm-sticky-navbar .tm-block-top {
left: 0;;
right: 0;
}

This was though not enough - it got me thinking. Why require the whole canvas/body to move (by shifting when the offcanvas bar moves from the left or right? could try and keep the site canvas fixed?

The shift in the site canvas as well as the offcanvas bar is triggered by a single file, uikit.js I proceeded to make modifications to uikit.js (and add some css) to both keep the offcanvas page fixed and add some animations to the navbar, specifically :
1. to keep the canvas fixed when the offcanvas bar moves in from the right or from the left
2. to add a class to the navbar (uk-active) when the show offcanvas function is triggered; I also add css to hide the navbar when the offcanvas is opened (see below)
3. to remove the class uk-active from the navbar when the hide offcanvas function is triggered
4. to add a fade in animation to the bar when the hide offcanvas function is triggered
   code changes to uikit.js :

n = {
show: function(n) {
if (n = t.$(n), n.length) {
var o = t.$("body"),
g = t.$(".tm-block-top:first"), // NEW LINE to identify where to put the new class for the navbar
s = n.find(".uk-offcanvas-bar:first"),
a = "right" == t.langdirection,
r = s.hasClass("uk-offcanvas-bar-flip") ? -1 : 1,
l = r \* (a ? -1 : 1),
c = window.innerWidth - o.width();
i = {
x: window.pageXOffset,
y: window.pageYOffset
}, n.addClass("uk-active"), o.css({
width: window.innerWidth - c,
height: window.innerHeight
}).addClass("uk-offcanvas-page"),
o.css(a ? "margin-right" : "margin-left", (a ? -1 : 1) \* 0).width(), // NEW LINE - body left margins = 0, so it does not move
e.css("margin-top", -1 \* i.y), s.addClass("uk-offcanvas-bar-show"),
g.removeClass("uk-animation-fade"), // NEW LINE - the uk-animation-fade class (which is added when closing the bar is removed
g.addClass("uk-active"), // NEW LINE - the uk-active class is added
this._initElement(n), s.trigger("show.uk.offcanvas", [n, s]), n.attr("aria-hidden", "false")
}
},
hide: function(n) {
var o = t.$("body"),
s = t.$(".uk-offcanvas.uk-active"),
g = t.$(".tm-block-top.uk-active"), // NEW LINE to identify the navbar
a = "right" == t.langdirection,
r = s.find(".uk-offcanvas-bar:first"),
l = function() {
o.removeClass("uk-offcanvas-page").css({
width: "",
height: "",
"margin-left": "",
"margin-right": ""
}),
g.removeClass("uk-active"), // NEW LINE to remove the uk-active class
g.addClass("uk-animation-fade"), // NEW LINE to add a fade-in animation to the navbar when the offcanvas closes
s.removeClass("uk-active"), r.removeClass("uk-offcanvas-bar-show"), e.css("margin-top", ""), window.scrollTo(i.x, i.y), r.trigger("hide.uk.offcanvas", [s, r]), s.attr("aria-hidden", "true")
};

code changes to custom.css to make the navbar vanish

.tm-block-top.uk-active{
display:none;
}

You can check results on www.newrarenoise2.rarenoise.com

PS:

Some issues that are template dependent remain
1. some of the YOO templates use the class .tm-top-block (Yoo_Moreno, for example), some use .tm-block-top (Yoo_Eat for example).
   This is a BUG, in my opinion, which should be addressed whatever you think of this proposal; the class should be called the same name across all of your templates.
2. the animation I used to fade the navbar in when closing the offcanvas (uk-animation-fade) does now work well on, for example, Yoo_Eat. (still investigating, but a minor issue).
3. You use a lot of transform:translateX(..%) for your transforms of moving parts. You should honestly use transform:translate3d(...%,0,0) to leverage 3d acceleration and make your animations smoother.

I truly hope someone will respond to this proposal, as I think it offers a way to completely decouples the issues of fixed (sticky) navbars and offcanvas and is more robust. It is also general enough to be implemented across the whole spectrum of your templates (with minor modifications), or at least to serve as a basis for a rethink.

Giacomo Bruzzo

**Comment by philoest** [comment]
Hi Giacomo,
I had a look into this problem, we are sorry that this took so long!
I tried it firstly with the Moreno template and added the flip modifier to the offcanvas bar and set the navbar to sticky. 
But neither in the online emulator or on a real device I saw the problem you described. In my case the sticky navbar didn't get shifted to the left at all and the offcanvas bar was just displayed above the sticky navbar. So that when the offcanvas closed the sticky navbar did not have to move back. 
The same result happend by using the eat template. 
Did you have other customizations, so that we can rebuild the problem to find a proper solution?!
I saw that you said in your forum posts that you are using the following system setup:
IPhone & with IOs 9 as the customer 
Joomla 3.44
Warp 7 ( newest? )
PHP 5.4.41

Are these information still correct?
You mentioned that you are using the plugins from vmuikit, which normally doesn't cause any problem with our widgets, but did you tried to deactivate them and see if the problem lasts?

The solution you provided seems to work fine, but in our case it seems not to be the correct way since we want to have the effect of the offcanvas sliding in from the left/right with the page still visible.

I will talk with the designer about the other 3 issues you pointed out and hope this will be fixed soon :)

Hope we will find a solution for this soon! 
Kind Regards
Philipp

**Comment by gbruzzo** [comment]
Dear Phllipp

Our current testing setup : 

Joomla 3.4.8
Virtuemart 3.0.12
PHP 5.4.45
Yoo_Moreno 1.0.14	
Warp 7.3.18

no 

thank you for your response. I read what you say, but do not agree. 

In order to show you my point in practice / make things comparable I have prepared two setups 

both with standard / unmodified uikit.js
both with unmodified custom.css

**Setup 1: Two offcanvases, two menus**

Yoo Moreno with _two Offcanvases (left and right), both show the same menu. _
I attach the theme.php file (saved as .txt file to attach it) and called "theme_rightoffcanvasMenu.txt" with a new position defined (rightcart) and all the appropriate menu and widget modifications. This is as per your own instructions on Yootheme. 

[theme_rightoffcanvasMenu.txt](https://github.com/uikit/uikit/files/121629/theme_rightoffcanvasMenu.txt)

Here is the recording of what happens on my Iphone 6. 
https://www.dropbox.com/s/j7bwq88o79l4n3m/YooMoreno_RightOffcanvasMenuOnly.mp4?dl=0
The recording was generated using Reflector 2

You will notice that when on top of the page, the offcanvas slides over the navbar. As you scroll lower the behaviour becomes erratic, with the navbar moving partially across the screen under the moving offcanvas. The return action is jerky, and the bar sometimes gets locked half way. 

I experienced_ exactly the same kind of behaviour when using the IOS simulator_ (Version 9.2 (SimulatorApp-643 CoreSimulator-201.3) for mac osx

**Setup 2: Two offcanvases, one menu, one offcanvas cart**

Yoo_Moreno with two offcanvases, _the left is the menu, while the right  is the offcanvas cart developed by VMUikit 

I attach the corresponding theme.php file 
[theme_rightCart.txt](https://github.com/uikit/uikit/files/121639/theme_rightCart.txt)

Here is the recording of what happens on my Iphone 6. 
https://www.dropbox.com/s/bap4mlngghkv3no/YooMoreno_RightOffcanvasCART.mp4?dl=0

Again, You will notice that when on top of the page, the offcanvas slides over the navbar. As you scroll lower the behaviour becomes erratic, with the navbar moving partially across the screen under the moving offcanvas. The return action is jerky, and the bar sometimes gets locked half way. 
This time I moved to the shop / VM page and added to cart. The behaviour of the navbar is consistently erratic. 

Again, I experienced_ exactly the same kind of behaviour when using the IOS simulator_ (Version 9.2 (SimulatorApp-643 CoreSimulator-201.3) for mac osx

NOTES: 
- This problem occurs on All IOS devices : Ipad(s), IPhones etc across different browsers (though the issue seems more marked on the Safari browser, rather than on Chrome and Firefox. The offcanvas bar sometimes covers (depending on where one is situated on the page, it seems, sometimes moves the sticky navbar, which itself remains halfway across the screen).

- Contrast this with the following observation : on Android devices (Chrome browser), the offcanvas and site canvas work like they do on the desktop, they both move synchronously and smoothly across the screen. 

GENERAL QUESTION: 
Is there a conceptual / philosophical reason why you want the main page canvas to be shifted when the offcanvas opens/closes? I do not understand the value of shifting the whole canvas. Looking at gmail and facebook apps online, it seems they keep the main page canvas fixed and allow the offcanvases to slide on top. 

I hope you can agree, the problem is real and requires attention. 

Please let me know if you need further informations/clarifications 

Kind regards 

Giacomo Bruzzo

**Comment by hendrikbehncke** [comment]
Hi,

We have updated the sticky component, it doesn't add a 'left' value anymore which was causing an issue where the sticking element did not shift when the offcanvas opened/closed.
Now the sticking element will shift when the offcanvas opens/closes. This is the desired effect and it is not wanted to be changed to the offcanvas overlaying the body.

Unfortunately Safari and IOs do behave different from Chrome, Firefox and IE and the sticking element will always stay in its position.

Please note that the Moreno template does not utilize the UIkit sticky component. It is a custom implementation as the sticky component didn't exist when the template was developed.

Best regards

**Comment by gbruzzo** [comment]
Hi there

thank you for your response. 

Premise: I am aware that Yoo_Moreno does not use the sticky component / does not call sticky.js, as, for example, Yoo_Eat does. 

Given this premise, could you please clarify what you mean by 

"Please note that the Moreno template does not utilize the UIkit sticky component. It is a custom implementation as the sticky component didn't exist when the template was developed."?

Are you saying there is nothing you can do for Yoo_Moreno? 

I just checked the Yoo_Moreno download page on the YooTheme website, and the template for download is still v 1.0.14. (dated Jan 13, 2016). Has that been modified? 

Please advise 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
I tried using the modified sticky.js on our test Yoo_Eat site. 

It kind of works, but is a very stodgy solution. The top navbar now behaves erratically in the desktop chrome browser. People will play around with their browser edge and the following behaviour would be grossly unacceptable: 

https://www.dropbox.com/s/tecs7ohmllcc7oj/Untitled%20Screencast.webm?dl=0 

look at how the top navbar breaks when moving the screen around! To me, it is a gross nono. 

Here is a suggestion

_Assume now you really need (for whatever reason) the whole site canvas to move_ 
 You still could apply minor code changes to Uikit.js or sticky.js to add a class, say "uk-active" to the navbar when the show.offcanvas function is triggered, and add css so that on that event, the navbar vanishes. This way 

1. your main canvas is moving
2. there is no navbar there to (but who cares, the main page is covered with an opaque layer now). 

you then add an appropriate animation class when the hide.offcanvas function is triggered to make it reappear when the canvas closes. 

specifically, this means that the code segment of uikit.js which I changed to  

o.css(a ? "margin-right" : "margin-left", (a ? -1 : 1) * 0).width()

remains instead 

o.css(a ? "margin-right" : "margin-left", (a ? -1 : 1) * (s.outerWidth()*l)).width()

See this video of how the desktop page is not affected anymore by the navbar being there 

https://www.dropbox.com/s/z8miyx3bss7ipzy/Untitled%20Screencast%20-%20vanish%20navbar.webm?dl=0

Please let me know your thoughts about this 

Giacomo Bruzzo

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by tatenalan** [comment]
Hello all, have you found a solucion to this issue? Im using push left offcanvas with sticky bar and got the same problem. Only on ios, I tried with safari and chrome and both crash.
