### ISSUE TITLE
"{target: '#id'}" doesn't work on iPhone

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1744]
Another bug that probably wouldn't get looked at. Yet again, I have no idea why I'm still reporting these. 

target: '#id' doesn't work on modal or off-canvas on iPhone 6s. I know you guys use browserstack and I've tried it on there and the problem still exists.

Tested on iPhone 6s

**Comment by aheinze** [comment]
Hi,

I've tested it with an iPhone 6 with IOS 8/9 , without any issues. :-/

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
