### ISSUE TITLE
Dropdown hover not working, even on http://getuikit.com/

### ISSUE THREAD

**Issue by BenoitGD** [uikit/uikit#1747]
Hi,

On Edge 25.10586.0.0 and Chrome 48.0.2564.103 m, the hover feature of dropdown buttons doesn't work on my website and on http://getuikit.com/docs/dropdown.html

Am I the only one with this problem?

Thanks!

Benoit

**Comment by aheinze** [comment]
Hi, can't confirm this. Do you have a touch enabled screen? if yes, then it is possible, that UIkit thinks, that you're on a touch device, which doesn't support hover.

**Comment by BenoitGD** [comment]
That is probably a good guess, I'm using a Surface Pro 3, which is touch enabled! Anyway I can make it works?

**Comment by malles** [comment]
The touchscreen can't detect your finger hovering over the screen, you will have to touch it :)
