### ISSUE TITLE
Uikit ios keyboard and modal

### ISSUE THREAD

**Issue by luisbmemorandum** [uikit/uikit#1757]
Hello, good morning I have a problem with modal UIKit when I open the virtual keyboard on the tablet pressing to write about a textarea me opens the virtual keyboard tablet, but I changed to the top of the page, it is possible to avoid that problem.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
