### ISSUE TITLE
Timepicker and class="form-icon" hide icon after getting focus

### ISSUE THREAD

**Issue by vuchl** [uikit/uikit#1759]
Hey Uikit guys!

I'm currently building a UI and have a problem which I can't seem to solve.

See this [JSFiddle](https://jsfiddle.net/r2hg69ot/) and this gif:
![uk-form-icon](https://cloud.githubusercontent.com/assets/4921147/13154946/aa6080a4-d67b-11e5-8b0a-b179c82b5d2c.gif)

When I click/set focus to the timepicker component the icon is getting hidden. the datepicker works as intended and still shows the icon.

I'm using 2.25.0 as in the JSFiddle.

Regards Sebastian

**Comment by vuchl** [comment]
Also reproduced here again:https://uikitplay.com/plays/FXsG
UiKit version as of today is 2.26.2

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
