### ISSUE TITLE
Tooltip not working correctly in switcher

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#1760]
Hi,

I guess it's some kind of a bug. I used the tooltip component inside 2 tabs of a switcher. If I hover over the element, the tooltip is show as expected. If a switch to another tab and the back to the first one, the tooltip is not display anymore. Any ideas, how to fix this?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
