### ISSUE TITLE
Linking to specific areas inside blog layouts:

### ISSUE THREAD

**Issue by Megsie212** [uikit/uikit#1761]
Hello,
Does anybody know how to link to specific articles inside the blog layout? Like on the tutorials page? You click on what you want on the left hand menu and it scrolls down to the correct film. I'm trying to do the same on my website but not sure how...
![screen shot 2016-02-19 at 13 06 53](https://cloud.githubusercontent.com/assets/17297630/13176385/c7390b72-d709-11e5-97c7-151c567fc58c.png)

**Comment by vuchl** [comment]
Give the section you want to link to an id like
```html
<section id="firstsection">
...
</section>
```
and use the standard link with the pound sign:
```html
<a href="#firstsection">Link to the first section</a>
```

**Comment by Megsie212** [comment]
Thank you!
