### ISSUE TITLE
uk-link-muted is not tweaked for uk-navbar-nav

### ISSUE THREAD

**Issue by yojique** [uikit/uikit#1763]
both of these links look same
`<div class='uk-navbar'>`
`<ul class='uk-navbar-nav'>`
`<li><a><i class='uk-icon-tags'></i></a></li>`
`<li><a class='uk-link-muted'><i class='uk-icon-tags'></i></a></li>`
`</ul>`
`</div>`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
