### ISSUE TITLE
 uk-vertical-align uk-vertical-align-bottom not work on chrome & safari mac

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#1764]
Hello
I have this jsfiddle https://jsfiddle.net/kxh9t77j/2/
I am on mac osX10.11, all updates done.
On safari and Chrome, the button is on the top right
On Firefox it is at the bottom right - where I want it to be.
Any idea why ? what can can I do so it works also on safari and chrome ?
thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
