### ISSUE TITLE
Pointer events problem with youtube video controls inside slideshow component

### ISSUE THREAD

**Issue by stell** [uikit/uikit#1765]
How is it possible to access the youtube controls or/and pause a video while it's playing inside a slideshow component? Here is an example:
https://jsfiddle.net/y5ppcy2y/4/

Removing
`if(!UI.support.touch) media.css('pointer-events', 'none');`
from the slideshow component fixes the problem on a desktop pc, but there must be a problem with detecting touch devices.

**Comment by aheinze** [comment]
Hi,

the controls are not accessible by design because the videos are meant to play in the background. If you want to have full control over the buttons, just wrap the iframe in a div:

```html

<li>
   <div>
        <iframe width="100%" height="300"></iframe>
   </div>
</li>

```

the slideshow won't try to handle it as background video anymore. and you can click the buttons again :-)

**Comment by stell** [comment]
Using controls in videos is rather practical i would think.
When surrounding the iframe with div the scaling fails. the iframe is no longer scaled properly. also the creation of a transparent img tag securing the dimensions is gone.

**Comment by aheinze** [comment]
One possible approach could be:

https://jsfiddle.net/y5ppcy2y/12/

**Comment by stell** [comment]
Thanks. I activated pointer events for this one. Seams the cleaner solution for my case.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
