### ISSUE TITLE
scrollspy in IE and Edge - elements are invisible

### ISSUE THREAD

**Issue by MartiranS** [uikit/uikit#1766]
Hello, I have problem in IE 10, 11 and Edge.
I use UIkit 2.24.3 with code: 
`data-uk-scrollspy="{cls:'uk-animation-fade', repeat: true, delay:300}"`
And the content is hidden in IE and Edge

I tried to fix this

```
<!--[if gte IE 9]>
<style>
    [data-uk-scrollspy*='uk-animation-'] { opacity: 1 !important; }
</style>
<![endif]-->
```

But it does not working in IE 10 and later
My site with problem: [http://hra.kctricany.cz/](http://hra.kctricany.cz/)
How can I solve this problem?

**Comment by MartiranS** [comment]
temporarily resolved with:
```
`@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) 
{[data-uk-scrollspy*='uk-animation-']{opacity:1 !important}}`
```

is there any way for the functioning of the animation in IE?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
