### ISSUE TITLE
Dropdown 'cannot read offsetWidth of undefined'

### ISSUE THREAD

**Issue by Tramvai** [uikit/uikit#1767]
Hi. I cannot seem to get dropdown working. I ge the following error:

`uikit.min.js:2 Uncaught TypeError: Cannot read property 'offsetWidth' of undefined`

Using jQuery 2.2.1 and UIKit 2.25.

This is my whole code:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Travo</title>

        <link rel="stylesheet" href="uikit/css/uikit.min.css" media="screen" charset="utf-8">
        <link rel="stylesheet" href="css/main.css" media="screen" charset="utf-8">
    </head>
    <body>
        <div id="header-wrap">
            <div class="uk-grid" id="header">
                <div class="uk-width-2-10">
                    <div data-uk-dropdown="{mode:'click'}">
                        <button class="trv-header-dropdown-btn">travo</button>
                        <div class="uk-dropdown"><p>fsdfsdf sdf sfd sfsd</p></div>
                    </div>
                </div>

                <div class="uk-width-6-10">
                    <p>contents</p>
                </div>

                <div class="uk-width-2-10">
                    <p>contents</p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="uikit/js/uikit.min.js"></script>
    </body>
</html>
```

**Comment by Tramvai** [comment]
Needed `position relative;` on dropdown wrapping div.

**Comment by Satchmo37** [comment]
I'm having the same issue, which div are you calling the 'dropdown wrapping div?'

`<nav class="uk-navbar">
        <div class='uk-grid uk-navbar-nav'>
            <li><img src="img/native_rank_logo-1.png"></li>
            <div data-uk-dropdown>
                <div><a href="#">Our Services</a></div>
                <div class="uk-dropdown">
                    <li><a href="#">Local SEO</a></li>
                    <li><a href="#">SEO</a></li>
                </div>`

I've added ```
.uk-navbar .uk-grid div .uk-dropdown {
    position: relative;
}
```
but still have had no luck with the dropdown.

**Comment by Tarpsvo** [comment]
The one with the 'data-uk-dropdown' attribute.

`<div data-uk-dropdown="{mode:'click'}" style="position: relative;">`

**Comment by Satchmo37** [comment]
Awesome, thanks!

**Comment by julianotheiss** [comment]
Thanks! I have the same problem and just add style="position: relative; to the data-uk-dropdown and now works!
