### ISSUE TITLE
Parallax flicker on load

### ISSUE THREAD

**Issue by marcc1213** [uikit/uikit#1768]
When using parallax on a background image there is a noticeable flicker/shift on page load. Anyone find a fix for that?

**Comment by marcc1213** [comment]
I commented out the line below and reduced the flicker somewhat. Parallax seems to work fine, though have not tested in all browsers.

if ((prop == 'bg' || prop == 'bgp') && !this._bgcover) {

                    /**
                     * Remove this seems to fix the problem with flicker on page load:
                     * */
                    //this._bgcover = initBgImageParallax(this, prop, opts);
                }

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Parallax component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
