### ISSUE TITLE
Centered modal via CSS

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#1769]
Instead of calculating the modals position via JavaScript you could instead do the following...

``` css
top: 50%;
left: 50%;
position: absolute;
transform: translate(-50%, -50%);
```

Which has the benefit of decoupling style from logic and continuing to work when the modal content changes height or width.

**Comment by joykuang** [comment]
great idea

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
