### ISSUE TITLE
data-uk-switcher with <options>

### ISSUE THREAD

**Issue by pas9x** [uikit/uikit#1770]
Hi. I would like to apply data-uk-switcher for `<options>` tag and it works fine in Opera 12, Firefox and IE. But Chrome does not call onclick event for `<options>` element. To reproduce a bug you can open this code in chrome:

```
<select class='uk-margin-top' data-uk-switcher="{connect:'#os'}">
  <option value='1'>FreeBSD</option>
  <option value='2'>Debian</option>
  <option value='3'>Windows</option>
</select>

<ul id='os' class='uk-switcher uk-margin-top'>
  <li class='uk-active'>You selected: freebsd</li>
  <li>You selected: debian</li>
  <li>You selected: windows</li>
</ul>
```

I found that switcher.js attaches onclick event for all switcher elements and it is a cause of problem. As solution i made a following modification of this script:

Original code:

```
            this.on("click.uikit.switcher", this.options.toggle, function(e) {
                e.preventDefault();
                $this.show(this);
            });
```

Replacement:

```
            var callbackSelect = function(e) {
                e.preventDefault();
                $this.show(this.options[this.selectedIndex]);
            }

            var callbackOther = function(e) {
                e.preventDefault();
                $this.show(this);
            }

            for (var j=0; j<this.element.length; j++) {
                var elem = this.element[j];
                if (elem.tagName.toUpperCase() == 'SELECT') UI.$(elem).change(callbackSelect);
                else UI.$(elem).on('click.uk.switcher', this.options.toggle, callbackOther);
            }
```

After patching this problem has been resolved. I will be glad if you make appropriate changes and fix it :)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Switcher component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team

**Comment by bobural** [comment]
Hello,

I know you guys are working on uikit3 but some of us area still using uikit2 because uikit3.min.css it has 255,9k  comparing with uiki2 - uikit.almost-flat.min.css which it as 111.6 k.
I am in such of need for this update..could it be possible to add it please ?

Thank you all and specially to pas9x for putting this out... grate man!
