### ISSUE TITLE
 lightbox vimeo served over https is not working

### ISSUE THREAD

**Issue by chrisvidal** [uikit/uikit#1774]
My website is served over https and wont load the vimeo lightbox

Mixed Content: The page at 'https://smartbuild.asia/' was loaded over HTTPS, but requested an insecure script 'http://vimeo.com/api/oembed.json?url=http://vimeo.com/156813878&callback=jQuery1110020709940465167165_1456730984672&_=1456730984673'. This request has been blocked; the content must be served over HTTPS.

**Comment by jimiero** [comment]
I confirm this also

**Comment by entonbiba** [comment]
@chrisvidal the vimeo lightbox video worked fine on your site. Where are you using the following code? Just change the http to https.
````
https://vimeo.com/api/oembed.json?url=https://vimeo.com/156813878&callback=jQuery1110020709940465167165_1456730984672&_=1456730984673
````

![image](https://cloud.githubusercontent.com/assets/5193884/17873786/9e1fc8c0-6895-11e6-94d0-675a78298e33.png)

**Comment by chrisvidal** [comment]
i change the core code of the lightbox.js component making headless the call.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Lightbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
