### ISSUE TITLE
Dropdown is not working correctly on Tabs

### ISSUE THREAD

**Issue by usukhbayar** [uikit/uikit#1775]
When click on dropdown it display dropdown first item's content, and dropped down all items but they does not work(no event). Is not that each element of dropdown supposed to be as tab element? Like, click on dropdown would drop all items without displaying first item's content then pick one element to display tab-content.

**Comment by usukhbayar** [comment]
@aheinze , @saschadube  any help?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
