### ISSUE TITLE
Custom Prefixed uikit error

### ISSUE THREAD

**Issue by stell** [uikit/uikit#1777]
OK i reduced the issue to a small example here:
http://docs.prime-real.de/_/test.html

When switching the tabs following error gets dropped and the tabs stop working:

`Uncaught TypeError: Cannot read property '0' of null`

This only happens if the "kenburns" option is active in the slideshow.

When using a not custom prefixed uikit this error is not dropped.

Whats happening here?

**Comment by florianletsch** [comment]
Looks like the `uk-` prefix is not correctly replaced in the build process. Probably because of the escaped `\-` in that line: `https://github.com/uikit/uikit/blob/3ad8015e68124d66f9cd72316fa3b6b471fcf9c8/src/js/core/core.js#L249`

**Comment by stell** [comment]
Yes that's the trouble. Can this be fixed? We are building and using custom prefixed uikit all the time.

**Comment by florianletsch** [comment]
Did you confirm that replacing the prefix manually in that line fixed it? If that's the case we need to fix the build process.

**Comment by stell** [comment]
Yes i confirm that. You can check it in the example above too.

**Comment by stell** [comment]
Still not fixed.
