### ISSUE TITLE
Sketch or psd kit file

### ISSUE THREAD

**Issue by ButuzGOL** [uikit/uikit#1781]
Do you have sketch or psd kit file ?

**Comment by peterbrinck** [comment]
@Intiligent has made a PSD file

https://github.com/uikit/uikit/issues/1409

**Comment by ButuzGOL** [comment]
Cool

**Comment by ziyafenn** [comment]
What about sketch? Would be very useful for designers as well

**Comment by hmontes** [comment]
+1. Sketch for v3

**Comment by PCDotFan** [comment]
Sketch +1
