### ISSUE TITLE
Reload New Modal 

### ISSUE THREAD

**Issue by allogos** [uikit/uikit#1783]
Hi my modal getting value by selecting dropdown: 

`jQuery(document).ready(function($) {
$('#Floor').on('change', function(e) {

```
$('#fp_aa1_b1').attr("data-uk-modal", "{target:'#modal-"+ $(this).val() +"'}");
```

}); 
});`

But modal is loading only one time, for example if my i select dropdown item1 so modal-1 is loading and by click on button ('fp_aa1_b1') modal is loading, by changing dropdown to item2 button attribute is changing to modal-2 which is correct but when i click on button modal-1 is showing, unless i'm refreshing the page and selecting directly the second item in dropdown.

What would be the solution.?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
