### ISSUE TITLE
Unexpected issue cloning dropdown

### ISSUE THREAD

**Issue by bribar** [uikit/uikit#1784]
When cloning an element with the dropdown its works, but it always accesses the first uk-dropdown.

https://jsfiddle.net/bribar/wax7keL4/7/

If you just click "add" a bunch the dropdown's seem to work correctly. But if you rollover the X first, then click "add" a bunch the issue pops up

**Comment by bribar** [comment]
Tooltip seems to have similar issue too

**Comment by malles** [comment]
When cloning, destroy the UIkit component when already initialized, or it will keep a reference to the created dropdown/tooltip.

`$('$my-dropdown').data('dropdown', null),clone();`

**Comment by bribar** [comment]
That seemed to do the trick. Appreciate the help!

If anyone needs to see it working,

https://jsfiddle.net/bribar/wax7keL4/15/
