### ISSUE TITLE
multi-level dropdown in navbar

### ISSUE THREAD

**Issue by csakis** [uikit/uikit#1785]
I am trying to create a navbar that contains a dropdown menu and inside the dropdown there should be another dropdown.
However, the second level dropdown does not seem to work. Furthermore, if I use the uk-navbar-flip class to have a dropdown on the right side of the navbar, as soon as I add the second level dropdown, the first dropdown menu drops outside of the screen. Here is a CodePen to demonstrate

http://codepen.io/csakis/pen/XddOJq

Is there a work around these problems?

**Comment by ZeGregg** [comment]
Did you try with [nav](http://getuikit.com/docs/nav.html) in your dropdown?

**Comment by csakis** [comment]
Thanks. I solved my problem using a nav element in the drop down menu. 

http://codepen.io/csakis/pen/bpgogy
