### ISSUE TITLE
Modal prevent close on esc

### ISSUE THREAD

**Issue by davidedellai** [uikit/uikit#1787]
Hi, i need to prevent that the modal closes when i press the "Esc" button. Is it possible?

**Comment by nblackburn** [comment]
If you set modal to true in the options, it will disable this functionality, failing that i believe their is also a keyword setting which you can set to true which should do the same.

**Comment by davidedellai** [comment]
Well i open the modal using `data-uk-modal="{target:'#myDialog', bgclose:false}"`  is it the same? Can i add the same options after `bgclose`?

**Comment by nblackburn** [comment]
Sure, you can add as many options as required.

**Comment by davidedellai** [comment]
Is there somewhere a list of all options? Thank you for the help

**Comment by nblackburn** [comment]
Your best bet is to checkout the code as documentation of lacking.

https://github.com/uikit/uikit/blob/develop/src/js/core/modal.js#L15:L21

**Comment by malles** [comment]
Although most options are reviewed in the page, I think an overview would make sense, as most components have it.

https://github.com/uikit/uikit/pull/1828
