### ISSUE TITLE
Add css class for table row highlight

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1791]
It was great to add some css class to table row for highlighting:
uk-table-row-success, uk-table-row-danger, uk-table-row-warning, uk-table-row-primary 
![table-highlight](https://cloud.githubusercontent.com/assets/2857625/13814224/86fdeafe-eb96-11e5-99c8-d180ac6fcab5.png)
very forward uikit 3.0 ))

**Comment by Intiligent** [comment]
maybe -table is unnecessary and enough be: uk-row-***

**Comment by mojtabakaviani** [comment]
+1

**Comment by entonbiba** [comment]
something like this?

![image](https://cloud.githubusercontent.com/assets/5193884/17875832/56f0face-68a3-11e6-9b7f-b93b20130122.png)

**Comment by philoest** [comment]
In UIkit3 we added the uk-active modifier for the table giving it a highlighting color. More default color modifier are not necessary from our point of view, if there is need for that you can easily add this via a custom class.
