### ISSUE TITLE
Form select inout target

### ISSUE THREAD

**Issue by ZeGregg** [uikit/uikit#1792]
Hi

It seems we can't target input with Advanced Form Select

> You can use any element, **like** an `<a>` as a select form. Just add the {target:'a'} option to the data-uk-form-select attribute and use an `<a>` instead of a `<span>` element.

Like an `<a>` does not mean it is the only alternative as `<span>`:)

```
<div class="uk-form-icon uk-form-icon-flip uk-form-select" data-uk-form-select="{target:'input'}">
  <i class="uk-icon-caret-down"></i>
  <input type="text" placeholder="Select" class="uk-width-1-1">
  <select>
    <option value="en-EN">English</option>
    <option value="fr_FR">French</option>
  </select>
</div>
```

[Fiddle here](https://jsfiddle.net/Greggg/chktmfxy/)

Any help would be appreciated

**Comment by vuchl** [comment]
What are you asking for exactly? 
![input_select](https://cloud.githubusercontent.com/assets/4921147/13838466/9c6165c8-ec14-11e5-93e8-c6d5f1d61a27.png)

The `caret-down` is on the right side i both exapmles.

**Comment by ZeGregg** [comment]
Sorry my fiddle was confusing. Here is [updated](https://jsfiddle.net/Greggg/chktmfxy/) one

`data-uk-form-select="{target:'a'}"`=> WORKS

`data-uk-form-select="{target:'input'}"`=> DO NOT WORKS

**Comment by vuchl** [comment]
A now i understand. I bet it's because the `target`option will save the selected text/value to the inner html of the target. and since `<input>`doens't have inner html it's not shown.

**Comment by ZeGregg** [comment]
+1 works fine. Thanks
