### ISSUE TITLE
Sticky don't sticky when navigate by smooth scroll

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1795]
I have navbar which is sticky
In this navbar I have some links which brings me to different section on current page (landing page)
Links usage smooth scroll
When I scroll mouse up / down - navbar is sticky and work OK
When I click on link, they bring me to current section, but the navbar isn't sticky - they stay at (also after page scroll, try scroll by mouse but the navbar isn't sticky too)

This situation is only on mobile view (tested on newest chrome)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
