### ISSUE TITLE
Duration doesn't work with Slideshow animation Swipe

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1798]
use animation swipe, set during to something like 5000, the animation will just cut instead of smoothly animate over the period of the transition.

**Comment by TomS-** [comment]
bump

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
