### ISSUE TITLE
Markdown editor toolbar not setting

### ISSUE THREAD

**Issue by nicksmetBagaar** [uikit/uikit#1799]
```
UIkit.htmleditor($(this), {
    mode: 'split',
    maxsplitsize: 600,
    toolbar: [ "bold", "italic", "strike", "link",]
});
```

According to the documentation the above code should set the toolbar options in the markdown editor. Now this is not the case, the other options like mode work fine but the toolbar configuration options are always default.

Is this a bug or a problem on my end ?

**Comment by pscheit** [comment]
works for me in 2.26.3

**Comment by pscheit** [comment]
oh it does not 
```
          toolbar: [
          'bold',
          'italic',
          'blockquote',
          'listUl',
          'listOl'
          ],
``` 
will be merged to 

```
          toolbar: [
          'bold',
          'italic',
          'blockquote',
          'listUl',
          'listOl',
          'blockquote',
          'listUl',
          'listOl'
        ],
```
when it's merged with the defaults.

**Comment by deviprsd21** [comment]
Fix this, this is irritating. Way to long too long for a minute problem

**Comment by lucas-wade** [comment]
I am trying to use uikit2 and when i go into markdown mode for the html editor it shows no toolbar... it this really still an open issue for months now?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The HTMLEditor component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
