### ISSUE TITLE
Browser support info

### ISSUE THREAD

**Issue by durasj** [uikit/uikit#18]
I think it is good idea to put some information about browser support somewhere on home page or documentation as I can not see it anywhere.

**Comment by TomS-** [comment]
bump

**Comment by dteirney** [comment]
+1

**Comment by dteirney** [comment]
@aheinze has this browser support documentation been put somewhere? I've just been looking at the website and I couldn't find anything specific. Perhaps I was looking in the wrong place though.

**Comment by kubik101** [comment]
+1 for docs

**Comment by saschadube** [comment]
Take a look here https://github.com/uikit/uikit#browser-support
