### ISSUE TITLE
parallax.min.js insertBefore breaks on IE10

### ISSUE THREAD

**Issue by paul-muckypuddle** [uikit/uikit#1800]
I was using Widgetkit 2.5.3 on J3.4.8 and found that the cached version of uikit.js was failing on IE10. I narrowed down the issue to the `insertBefore` call made in parallax.min.js. The page didn't actually have any widgets, but thought I'd log here for further investigation.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Parallax component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
