### ISSUE TITLE
Uikit form not responsive at chrome ok on firefox ( link with dropdown menu)

### ISSUE THREAD

**Issue by daniakbar** [uikit/uikit#1802]
![screenshot from 2016-03-26 23-16-04](https://cloud.githubusercontent.com/assets/8470509/14060753/d205ca70-f3a8-11e5-9ead-41df5b71bbaf.png)
## Chrome :

![chrome](https://cloud.githubusercontent.com/assets/8470509/14060700/24a546ae-f3a7-11e5-995c-6f0c7c66deb3.png)
## Firefox : 

![firefox](https://cloud.githubusercontent.com/assets/8470509/14060707/2f1a9b34-f3a7-11e5-83b8-c8c1b9b15515.png)

thnks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
