### ISSUE TITLE
Clear input field from autocomplete after select

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#1805]
Hello,

I'm using the autocomplete component for selecting e. g. articles.

To make it quicker to select multiple articles in a row I delete the input search field after an item was selected and focus it again.

Unfortunatly this does not work as expected since the component checks for the old value which is still hold by the javascript.

Is there a workaround for this problem or can this functionallity be included in a future version?

I guess the problem can be solved if there would be a possibility to "remove" the script from the dom and then init it again. But I do not know how to do that.

Thanks,
Peter

**Comment by entonbiba** [comment]
@ikabod Here you go,

Preview:
http://codepen.io/entonbiba/pen/xONPbr 

Code:
https://github.com/entonbiba/examples/blob/master/uikit/autocomplete-clear-input-after-select.html

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
