### ISSUE TITLE
Smooth scroll is not compatible with jQuery 3.x

### ISSUE THREAD

**Issue by cajoy** [uikit/uikit#1806]
Smooth scroll is not compatible with jQuery 3.x

Please update bower.json dependencies or make it compatible with jQuery 3

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
