### ISSUE TITLE
Customizer on getuikit.com broken

### ISSUE THREAD

**Issue by wecosystem-trentm** [uikit/uikit#1807]
A similar issue was closed - but the Customizer doesn't seem to be working.

```
http://getuikit.com/themes.json?nocache=0.47029818829827974 Failed to load resource: the server responded with a status of 404 (Not Found)
http://getuikit.com/tests/holder.js/300x110/auto Failed to load resource: the server responded with a status of 404 (Not Found)
http://getuikit.com/tests/holder.js/50x50/auto Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by aheinze** [comment]
Hi,

sorry but I can't verify that the customizer doesn't work. Do you have more details? Browser, version etc?

**Comment by wecosystem-trentm** [comment]
I've tried again today and the themes.json 404 error has gone and the customizer now works. The two holder.js 404s still exist, but don't seem to affect it.

**Comment by rstudner** [comment]
@aheinze 
https://getuikit.com/docs/customizer.html

This is broken once again.  Tried in 4 browsers.. lots of 404's.
