### ISSUE TITLE
Scrollspy nav wrong set active in 2.26.*

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1810]
I use scrollspy nav in sticky bar at the top of the site (menu)
In this menu I also use the smooth scroll

After click in the menu option, the smooth scroll work OK, but the active class in sticky bar is wrong (Its ok when I scroll 1px down)

This bug is on 2.26.* - in 2.25.0 and below they are work OK...

**Update:**
I revert the changes which was in this commit:
https://github.com/uikit/uikit/commit/1467a8fcb9702250efd36af08afd7c375ab2a03b
and now the active class again work OK...
could someone look into this?
@janschoenherr @aheinze

**Comment by aheinze** [comment]
Hi,

could you please provide an example on jsfiddle? Thanks!

**Comment by PixelT** [comment]
@aheinze, @janschoenherr 
I create a demo:
http://codepen.io/anon/pen/BKdeWR

Click on red, but the blue option is still active.

Another things is - I used sticky in the navbar:
- Click on the 'blue' option
- I should be on the top, but I still can scroll some pixels to the top (offset of the sticky placeholder?)
