### ISSUE TITLE
How to show off canvas without button and hidde whit button

### ISSUE THREAD

**Issue by daniakbar** [uikit/uikit#1811]
i want to show off canvas sidebar menu whitout button and can hide with button at uikit 
how to ?

**Comment by freedomlang** [comment]
Please read the documents first!

```
// Show an off-canvas matching the passed CSS selector
UIkit.offcanvas.show('#my-id');

// Hide any active offcanvas. Set force to true, if you don't want any animation.
UIkit.offcanvas.hide([force = false])
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
