### ISSUE TITLE
Error on the page Scrollspy

### ISSUE THREAD

**Issue by sashatexb** [uikit/uikit#1813]
Error on the page http://getuikit.com/docs/scrollspy.html

Groups

You can also group scrollspy elements, so you won't have to apply the data attribute to each of them. Just add the data-uk-**scollspy**"{target:'MY-CLASS'}" attribute to a container element, targetting the selector the items you want to animate within the container. When using a delay it will be applied cumulatively to the items within the row that scrolls into view. The delay will be resetted for the next row within the group when it scrolls into view.

**Comment by aheinze** [comment]
Thanks!
