### ISSUE TITLE
"Load More" functionality for Dynamic Grid

### ISSUE THREAD

**Issue by JoomFX** [uikit/uikit#1814]
Hey guys,

First of all, thank you very much for the awesome framework. The more I use it, the more I love it!

I'd like to ask you if you are planning to implement a "Load More" functionality to the Dynamic Grid component, so the user can specify how many items should be loaded at once and then when the user clicks on the "Load More" button, the same number of items is loaded again. I imagine it to be a JS option for the data attribute, for example `data-uk-grid="{items: 20}`

If you are not willing to implement this, can you please let me know what would be the best way I can achieve it (the more details you give me, the better).

Thanks a lot :wink:

**Comment by Intiligent** [comment]
this is not exactly what you asked, but maybe it will be useful (it is lazy load component)
http://codepen.io/Intiligent/pen/WQexVB

**Comment by jsieler** [comment]
Also available here too: https://uikitplay.com/plays/FXsp

**Comment by JoomFX** [comment]
@Intiligent @jsieler thanks a lot for the suggestion guys but it's not really what I'm looking for (and sorry for replying after half an year 😄 this feature just became important again).

@aheinze @saschadube @malles guys, can you please implement this additional JS option in the Dynamic Grid component? If not in UIkit 2.x than at least in UIkit 3.x? Thanks 😉

**Comment by motionpixelsnl** [comment]
I like to support @JoomFX request to add a "Load More" functionality to the Dynamic Grid.

Thanx

**Comment by jsieler** [comment]
Why not just to implement it by yourself? It's only few lines of code...

28 сент. 2016 г. 18:14 пользователь "motionpixelsnl" <
notifications@github.com> написал:
>
> I like to support @JoomFX request to add a "Load More" functionality to
the Dynamic Grid.

**Comment by jsieler** [comment]
@JoomFX @motionpixelsnl smallest ever example: https://uikitplay.com/plays/FXu2
Add some AJAX and you're done!

**Comment by JoomFX** [comment]
@jsieler Thank you for the reply and for the snippet.

In my particular case I do not need to add AJAX as I'm not pulling the data dynamically, it is not in a DB, not in array or anything.
I'm generating the whole output at once, via Twig. In means that I already have all Grid elements available in the DOM. So I just need to handle it from the front-end.
Instead of appending the elements (as in your example) I might just hide most of them and reveal them when the user clicks the button. And this is what I'll do if the UIKit guys refuse to implement this feature.

But since UIkit is a front-end framework, it will be really nice to have such JS option, such Data Attr (for example `data-uk-grid="{items: 20}"`) that will handle this in the front-end only. And since UIkit 3.x gets so many nice improvements like 3 different Offcanvas animations, universal Transitions component (that will replace the overlays), many nice little additions to the Navbar, improvements to the Tabs and Buttons styling, etc.... I really do not see any reason why this very nice addition to the Dynamic Grid component shouldn't be added as well.

**Comment by jsieler** [comment]
@JoomFX my snippet was just a small example of proof, that it's possible to make it in few lines of code. Concept is there, you can extend it to what ever you want, ajax or twig possible.

UIkit is not a complete frontend framework, like AngularJS or similar. Dynamic grid is just a structure component, not a component which handles data itself. I don't think that it will be implemented in UIkit 3 too.

**Comment by JoomFX** [comment]
@jsieler I know mate, everything can be done with few (or more) lines of code.
Of course UIkit cannot (and should not) handle all possible scenarios. As a framework, it is the starting point, the backbone of a project and should be extended and customized for the specific needs by the user.

That being said, I do believe that my request is very reasonable and it will be a great addition to the framework.

I do have a great respect for the Open Source projects, I am involved in few myself, therefore I very well understand that not everything can be implement, that there are different priorities and that if you want something to get added the best way is to log a new PR and contribute to the project.

I just want to see what the UIkit developers think about it and what's their take on this.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The dynamic Grid component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
