### ISSUE TITLE
Storage tabs state by hash

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1815]
Previously, there was a proposal to keep the state with the help of cookies, but this idea was rejected because there need to use additional plugin for cookies, and this is beyond the scope of UIKit.

Why not make storage tabs state by hash.
By clicking on tab was change hash URL: http://site.loc/#tab-main=first
It was abble storage more than one tab on page: http://site.loc/#tab-main=first&tab-foo=bar

When UiKit tab init fire some function, checkHash for example, will look for matches hash in address bar and existing tab on page. if was match fire function to set() for activate tab.

```
<ul data-uk-tab="{connect: '#tab-main'}" class="uk-tab uk-tab-flip">
    storage in href attr:
    <li><a href="#foo">Active</a></li>
    or in data-uk-tab-name attr:
    <li><a data-uk-tab-name="bar" href="#">Item</a></li>
</ul>

<ul class="uk-switcher uk-margin" id="tab-main">
    <li>Tab-1</li>
    <li>Tab-2</li>
</ul>
```

In tab option add option item, `hash: true` or `storage: true` or something like this and activate this mode by need.

This exemplary operation mechanism, the precise implementation of the name attribute to the discretion of UiKIt team developers :)

**Comment by Intiligent** [comment]
the same mechanism can be used for modal windows, if need open a window by link

**Comment by malles** [comment]
These kind of storage and state logic really should be in the code of the app controlling the UIkit components, not in the component itself. Here are some examples on how to control the UIkit switcher: http://codepen.io/malles/pen/BNXrmO

**Comment by Intiligent** [comment]
@malles thanks. It was very useful for me)

**Comment by Intiligent** [comment]
thanks for good example, store mechanism work fine, but i have some difficults and propose. 
clicking by tab not record hash in url, i understand that is default state and even comment line https://github.com/uikit/uikit/blob/develop/src/js/core/tab.js#L40 
its whatever not change hash by tab click.
only this record hash to url: location.hash = $(e.currentTarget).find('a').attr('href');
but this look like on hack.
how to enable tab record hash from href attributes.
it was perfect add option **hash** with boolean param and if hash: true then 
`<l><a href="#tab-foo">Tab foo</a></li>` 
record href to url for store, else if hash: false then default 
behavior

**Comment by Intiligent** [comment]
```javascript
e.preventDefault();
if($this.options.hash) {
    location.hash = $(e.currentTarget).find('a').attr('href');
}
```
