### ISSUE TITLE
Font not well formed in Sass

### ISSUE THREAD

**Issue by antoniocanas** [uikit/uikit#1817]
In base.scss, this line
`font: $base-body-font-weight $base-body-font-size unquote("/") $base-body-line-height ...`
is 'compiled' to
`html{font:normal 14px 20px \/Helvetica Neue,Helvetica,Arial,sans-serif; ...`
which is incorrect CSS

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The SASS version has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
