### ISSUE TITLE
uk-hidden-small not working on mobile with v2.26 -downgraded to v2.24 and it works

### ISSUE THREAD

**Issue by MarthaMegarry** [uikit/uikit#1818]
uk-hidden-small was not hiding the grid items on mobile while I had v2.25 or v2.26 running but then when I brought it back to 2.24 it started working. It does work responsively with browser resizing on the desktop with all versions.

I am testing on a Droid Turbo with a display resolution of 2560/1440 running Android 5.1 and it happened with mobile FireFox 45.0.1 and Chrome 49.0.2623

The first thing I tried was changing the version of jquery I was using from v2.2.3 to v2.1.4 but it didn't seem to make a difference which version of jquery I used with any version of UiKit.

Thanks!

**Comment by rocketpages** [comment]
I'm noticing the same behaviour. My whole page is stuck in "large viewport" mode even on mobile (Android 6.0.1), making the text to small to be readable.

**Comment by malles** [comment]
Do you have an example url or preferable jsfiddle/codepen that shows the issue?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
