### ISSUE TITLE
Markdown in Modal not working properly

### ISSUE THREAD

**Issue by jfosnight** [uikit/uikit#182]
When placing a Markdown box in a Modal window, it displays in tabbed view, even when explicitly told to use split view.

Also any text that is preloaded into the textarea shows up as blank.

The height of the preview side is not 100% as it should be.

If the window size is changed at all, then the Markdown area will switch back to split view, and the invisible text becomes visible. The height of the preview side does not correct itself, causing anything more than one line to be hidden. 

Tested in Chrome and Firefox on Windows 7.

Code used: 

``` html
<button class="uk-button" data-uk-modal="{target:'#modal'}">Open</button>

<div id="modal" class="uk-modal">
    <div class="uk-modal-dialog uk-modal-dialog-frameless" style="width:1050px;">
        <a class="uk-modal-close uk-close uk-close-alt"></a>
        <form method='post' action='test.post.php'>
        <textarea name='markDown'  data-uk-markdownarea=\"{mode:'split'}\">This is some *sample* text</textarea>
        <input type='text' name='goalId' value='45'/>
        <input type='Submit' name='updateGoal' value='Save'/>
        </form>
    </div>
</div>
```

When first opened:
![markdownarea bug](https://f.cloud.github.com/assets/3527971/1770612/af20a22e-6795-11e3-8dcd-03e5f14b388e.png)

After resizing browser slightly:
![markdownarea corrected after window slightly resized](https://f.cloud.github.com/assets/3527971/1770613/b4a8e030-6795-11e3-8c75-999e34d6f1d2.png)

Also when applying the "data-uk-markdownarea" using ajax after the page is loaded causes nothing to happen.  As a temporary fix, I am just using jQuery "$.getScript("/js/addons/js/markdownarea.js");" to reload the script, which fixes the problem, but is a very inefficient way to do it.

**Comment by nguyenducdn87** [comment]
ergege

**Comment by nguyenducdn87** [comment]
ddddddd
