### ISSUE TITLE
sliders inside tab stop to work

### ISSUE THREAD

**Issue by valentinabarbieri** [uikit/uikit#1820]
I put inside the tab component 3 slider, in the active tab the slider works, but when I switch the tabs the others sliders are not visible,

how can I solve this problem ?

http://www.zfactor.it/acelity1/info.html

**Comment by webalm** [comment]
For me works with data-uk-check-display near uk-data-slider

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
