### ISSUE TITLE
Off canvas without overlay?

### ISSUE THREAD

**Issue by oknoorap** [uikit/uikit#1821]
Is off canvas without overlay and always sticky when user scrolling on possible?

**Comment by luxlogica** [comment]
If you want an element that is "on-canvas" (on the screen) all the time, then you don't really need an "off-canvas"! It may be simpler to just use a fixed-position `div`, and then style it.

**Comment by oknoorap** [comment]
okay, I was with foundation 6 before, they have off canvas toggle reveal class, maybe uikit will add this feature too in the next release
http://foundation.zurb.com/sites/docs/off-canvas.html#reveal-on-larger-screens

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. In the new Off-canvas component you have the `overlay` option which makes the page still scrollable if it is set to `false`. 

Thanks for your understanding,
Your UIkit Team

**Comment by oknoorap** [comment]
@philoest awesome thanks...
