### ISSUE TITLE
Is it possible to update the options of a component?

### ISSUE THREAD

**Issue by cauburtin** [uikit/uikit#1822]
If I have an accordion `var accordion = UIkit.accordion(element, {collapse:true});` and dynamically in js, want to change the option to `collapse:false`. 

Is it possible without removing and re-inserting a new component? I haven't managed to do it

(Same question for `animate` option also)

There would probably need a 'destructor' method or something

**Comment by malles** [comment]
You can access the initialized component via the UIkit function you use. It will return the existing instance if exists. If you init the component as you showed, the instance will be in the `accordion` var.

```
var accordion = UIkit.accordion(element, {collapse:true});
//change options
accordion.collapse = false;
```

**Comment by cauburtin** [comment]
ok thanks
