### ISSUE TITLE
[Feature Request] Switch to Velocity.js for All Animation

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#1823]
UIKit components are elegantly designed, but its animated components often trigger [layout](https://developer.chrome.com/devtools/docs/demos/too-much-layout) [trashing](http://wilsonpage.co.uk/preventing-layout-thrashing/) - noticed by users when animation movement is 'jerky' or step-motion like, instead of smooth. As a consequence, because of the libraries used by UIKit, many of its animations do not perform well in all browsers - specially in complex layouts, that use many overlapping animated components. Try, for instance, placing a slideshow on a page that uses overlays, and then add an off-canvas component to the page, with an accordion in it. This problem is specially noticeable on mobile devices.

This is not a problem that is particular of UIKit - indeed, even CSS-based animation libraries (like Animate.css) suffer from this, as most browsers do not fully optimise their own animation for all situations. Javascript frameworks like jQuery - and its `'animate()'` function - are notoriously known for being worse.

This is not a new issue, its an old, common one, that has been well-documented, and proper techniques for smooth animation, that avoid layout trashing - as well as other issues - have been around for a few years. The problem is, that for most frameworks, jerky animation is "good enough": it's easier to keep the sub-optimal animation functions, than to write the extra code needed to make it smooth and professional.

To overcome this issue, a couple of years ago [Julian Shapiro](http://julian.com), founder of [Libscore](https://en.wikipedia.org/wiki/Libscore), created **[Velocity.js](http://julian.com/research/velocity/)**: a javascript library whose primary purpose is to replace jQuery's `animate()` function, as well as perform even better than CSS-based transform and keyframe-based animation. It succeeded.

Velocity is extremely well-documented, and very easy to use - and outperforms not only jQuery, but also Animate.css and Transit. It also adds spring-based easing functions, and make it extremely easy for the developer to create complex animations. 

Julian Shapiro also wrote [an excellent book on web animation](http://amazon.com/Web-Animation-using-JavaScript-Develop/dp/0134096665), which covers raw UI animation theory, and shows many interesting techniques for animation of UI items, whether you use Velocity or not.

My experience with UIKit has been, that as I become more familiar with the framework, my layouts become increasingly more complex, and animation becomes ever present - a necessity. As we build more complex nested components, with more complex and taxing animation, it is important for UIKit to provide a solid performance. Velocity.js might the way to future-proof UIKit's animations, by providing this needed performance.

**Comment by malles** [comment]
I think the key here is the trade-off between being light-weight and being robust in all situations.I think it would be great if velocity could be used as an option. The UIkit default animations for basic usage, and velocity when more performance is needed on complex pages.

**Comment by luxlogica** [comment]
Velocity.js enables us to do *more* with less coding: instead of having to use several jQuery plugins and third-party libraries, all the animations could be done using just Velocity.js. In this sense, Velocity *is* the 'lightweight' option. ;-)

**Comment by kelsh** [comment]
Velocity.js isn't even the best at that tho. GSAP.  Most of the animations are trivial if they bother you re-write them IMO.

**Comment by xpd** [comment]
This should be reopened.
