### ISSUE TITLE
[Feature Request] Rewrite Components Using Vue.js

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#1824]
I understand that this would require a major rewrite of _all_ components in UIKit, but please bear with me, as it may indeed be worth considering as a long-term project.

What if instead of having to learn to write...:

``` html
<!-- sample markup for a MODAL -->
<div id="my-id" class="uk-modal uk-modal-dialog-large" data-uk-modal="{center:true}">
    <div class="uk-modal-dialog">
        <a class="uk-modal-close uk-close"></a>
        <div class="uk-modal-header"><h2>My Modal</h2></div>
        <div class="uk-overflow-container">
            <div class="my-modal-body">
               <p> Lorem ipsum dolor sit amet, consectetuer aqipiscing elit...</p>
            </div>
        </div>
    </div>
</div>
```

...a new UIKit user had to learn just this:

``` html
<!-- sample markup for a MODAL -->
<modal size="large" pos="center" close>
    <h2 slot="modal-header">My Modal</h2>
    <div slot="overflow-body" class="my-modal-body">
        <p>Lorem ipsum dolor sit amet, consectetuer aqipiscing elit...</p>
    </div>
</modal>
```

Frameworks like Angular, React and Ember make it possible for us to create modular, customised HTML elements that greatly simplify our markup. The issue with all these frameworks is that they are not merely UI frameworks: they are geared towards giving you tools to create an entire application, and contain much functionality for dealing with the requests and data, as well as handling the application view. As a consequence, they are 'monsters': large and complex, difficult and time-consuming to learn, and often requiring you to learn and adopt several other technologies in the process - i.e., TypeScript for better working with Angular, etc.

As a solution to this problem, **[Vue.js](http://vuejs.org)** was created. It is a UI-creation and manipulation javascript library, made to work nicely _on top of_ other libraries, like jQuery. It is small, extremely well-documented, and amazingly quick to learn - spend a weekend with it, and you're done.

Vue would allows us, for instance, to create a 'slideshow' component, that users could define in HTML with the following code:

``` html
<slideshow slidenav="contrast" dotnav="contrast" kenburns="15" fullscreen>
    <slide>
        <img src="myimg1.jpg">
        <overlay background fade>Some overlay content goes here...</overlay>
    </slide>
    <slide>
        <img src="myimg2.jpg">
        <overlay background fade>More overlay content can go here...</overlay>
    </slide>
</slideshow>
```

Compare this with the HTML that is required to achieve the same result currently: a cacophony of nested divs, ul and lis, littered with data attributes everywhere, which often causes problems and confusion, specially for newbies.

What Vue.js does behind-the-scenes is "translate" the custom HTML tags into regular HTML elements that the browser recognises, using 'templates' that we previously define. It's not just easier for users to learn, it also reduces the probability of error, as we're basically 'writing the code' behind the scenes for the user.

This would make UIKit the **easiest** and **fastest** framework for any developer to learn, and implement!

**Comment by nblackburn** [comment]
This is a bad idea as it locks people to using Vue which they might not want or even be able to use.

**Comment by luxlogica** [comment]
@nblackburn Just like a UIKit user doesn't have to know jQuery - or any of its plugins - in order to use UIKit, they also wouldn't have to know Vue. If the UIKit team changes the libraries they use in the engine, that doesn't make it harder for us to use the frameworks - we wouldn't even have to know about it.

One of the great features of UIKit is enabling developers to create components - new HTML elements - which simplify syntax for markup. Look at the first example I gave above, for the modal. It shows what the current syntax is for implementing a modal, and what the syntax would be if implementing it as a Vue component. AFAIK there is no UI framework that makes it *this easy*, so this could be a great boost to UIKit.

But the advantages of Vue don't stop there. If you're offering to help me with Vue, you've probably already checked it out, so you know that it has its own Transition implementation, as well as the interface two-way data binding - which might help simplify and speed up some of UIKit's code, and open even more possibilites for UIKit - it would be easier to offer more features for existing elements, as well as build new elements from scratch. And all of this would be presented to users with a syntax that would be much simpler, easier to remember, and less prone to error.

**Comment by nblackburn** [comment]
I use Vue frequently and back the project financially so you really don't need to sell it to me as i know how good it is. That being said, i still feel as though my point remains the same.

> Just like a UIKit user doesn't have to know jQuery - or any of its plugins - in order to use UIKit, they also wouldn't have to know Vue.

**They would because it's using Vue's templating language which requires you to know at least it's syntax whereas jQuery is used behind the scenes which you only really come into contact with when developing extensions for UIkit.**

---

I honestly get your excitement for Vue but when building a frontend framework, you need to design things in a way that works for everyone.

**Comment by luxlogica** [comment]
@nblackburn I do apologise, but I'm not really getting your point. You seem to be saying, that if UIKit were to start using Vue, then UIKit users (web developers using UIKit) would also need to learn Vue, and Vue's templating language. That is not true.

If what you're saying, is that they'd have to learn a new syntax for using UIKit's elements - a simpler syntax that you'd have control over - then yes, I agree there: that is the whole point. A web developer getting started with UIKit right now *already* has to learn a "syntax" of sorts (every 'recipe' for using a core element or component is a 'syntax' that has to be learned), and that syntax is often nested in multiple levels, complex, full of caveats and prone to errors. It could be greatly simplified using Vue - meaning that there would be *less* syntax for newbies to learn.

> I honestly get your excitement for Vue but when building a frontend framework, you need to design things in a way that works for everyone.

I totally agree: the more approachable we can make UIKit to newcomers, the wider an audience it can have.

**Comment by saschadube** [comment]
@luxlogica Yes, this is a good idea. I don't know if you are aware that we are also the creators of [Pagekit](https://pagekit.com), a new CMS which user interface is completely built with Vue.js :wink:

We are in the middle of planning UIkit 3.0 and we will see what the best Vue integration will be :smile:

**Comment by nblackburn** [comment]
@saschadube This is great but i do hope it's optional for the people that are not using Vue (_which was the point i have being trying to get across_).

**Comment by luxlogica** [comment]
@nblackburn just like you have the freedom to choose to use jQuery - and tell your users to include it in their project along with UIKit - you also have the freedom to use Vue. Just like the end-user does not have to know anything about jQuery now, then wouldn't have to know (or use) anything about Vue.

The ones who have to know and use Vue are the UIKit team - and it seems they are already doing it! 

Yay!

**Comment by jods4** [comment]
-1 if not optional, i.e. for _Rewrite components using Vue_.

Creating and distributing the required code to enable the lovely code examples given in this issue is great. I'm totally fine with an _optional_ Vue plugin. 👍 

Just don't make it mandatory please!

I am building my apps with Aurelia. It is capable of such things as well and I have created my own `<modal>` custom elements that does pretty much what was shown by @luxlogica. If UIKit was _built on top_ of Vue:
- It would make my page heavier and all those frameworks are heavy enough already, thanks. 
- I fear the friction and bugs that may appear with several frameworks fighting to process custom elements.

**Comment by nblackburn** [comment]
@jods4 This was the point i was trying to raise but gave up in the end.

**Comment by saschadube** [comment]
@nblackburn @jods4 Yes, of course it would be optional / its own project. UIkit itself should work great with any JS framework.

**Comment by philoest** [comment]
as @saschadube already mentioned, we love VueJS and the new UIkit3 page and also Pagekit are good example how well UIkit works with it. But we don't see the rewriting of all the components with the same doubts @nblackburn already mentioned. Please if you encounter problems using VueJS with UIkit let us know, but a completely Vue-based UIkit version is currently out of scope.
