### ISSUE TITLE
Angular.js support

### ISSUE THREAD

**Issue by kunagpal** [uikit/uikit#1826]
As is the case with [Bootstrap](https://angular-ui.github.io/bootstrap/), [Foundation](http://pineconellc.github.io/angular-foundation/), and [Material CSS](https://material.angularjs.org/latest/) design, UIKit could / should also be adapted to Angular.js.

**Comment by philoest** [comment]
UIkit3 should work fine with AngularJS and [other JS frameworks](https://getuikit.com/docs/javascript) the new UIkit3 page is a great example how it works with VueJS. But there will be no Angular-based UIkit version, this is currently out of scope.
