### ISSUE TITLE
Removed data-uk-observe

### ISSUE THREAD

**Issue by tbba** [uikit/uikit#1827]
Hi, the latest changelog says: Removed data-uk-observe

This option is (still) featured in your official doc. Can you explain what this is about?

**Comment by malles** [comment]
We had noticed the discrepancy in the docs. They have been adjusted in the develop branch already: https://github.com/uikit/uikit/commit/efc5a52c0b3e0f09ed8f3ae38feb8d350d716cb3
They will go live on the next release.
