### ISSUE TITLE
Please Add Load/Instal Instructions for Each Component

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#1829]
More developers are starting to use CDNs - we use it exclusively for all libraries and frameworks in our projects. UIKit's guide contains instructions on how to load its core css+js from CDN, but it has no instructions for Components. To make matters more complicated, some components require us to load css+js, but others only require js. Some components have 'almost-flat' and 'gradient' stylesheet variations, but not all. Right now, the only solution is for us to always download a copy of the UIKit instal - even if only using UIKit from CDN. That way we can keep searching through its folders, to see which files we have to load for the needed components - and then 'translate' that to the needed CDN URL. Its an annoying chore, and an unnecessary bloat in our project folders.

It would be incredibly helpful if at the top of every Component entry in the guide, there were just a couple of instruction lines that already stated which files need to be added, from which sub-directories - i.e.:

> ### Installation
> 
> To start using the Accordion component, add its stylesheet and its javascript to your page:
> 
>    `<link rel="stylesheet" href="(your/uikit/folder/)css/components/accordion.min.css">`
>    `<script src="(your/uikit/folder/)js/components/accordion.min.js"></script>`
> 
> If using the 'gradient' theme, use the _'accordion.gradient.min.css'_ stylesheet instead.
> If using the 'almost flat' theme, use _'accordion.almost-flat.min.css'_.

That would specially help developers like us, who always load UIKit from CDN.

**Comment by nblackburn** [comment]
The benefit of downloading UIkit is that you can use it with build tools which can compress everything into one file saving on requests which can slow the application down.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
