### ISSUE TITLE
Why not use standard FontAwesome classes?

### ISSUE THREAD

**Issue by beruic** [uikit/uikit#1830]
Instead of using `.uk-icon-*`, why not just include FontAwesome, and use `fa-*` instead?
What is the reasoning behind this?
Isn't it just a source of extra work?

**Comment by emanwebdev** [comment]
my 2 cents 

might be coz the stylesheet of FA is ... **HUGE**

**Comment by beruic** [comment]
It's only 33 KB (22 KB minified) of which more than 90% is of the form:

```css
.fa-[icon name]:before {
  content: "[icon code]";
}
```

And how about the corresponding stylesheet part in _uikit_?
Since _uikit_ uses longer class names, it must be bigger.

**Comment by websam101** [comment]
+1

FontAwesome should be removed from uikit or make it as an optional component.

Few reasons why:
- It open the possibilities to use another icon pack.
- If we dont use icon or we use another icon pack, we dont get a huge pack of useless css classes.
- F.A. class support stacked icons and more options natively than uikit does for the same icons.
- ...

Thanks :+1:

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. FontAwesome has been removed from the new UIkit3, we build our own SVG icons here.

Thanks for your understanding,
Your UIkit Team
