### ISSUE TITLE
Vimeo lightbox wont play in portrait on iOS (same on your site)

### ISSUE THREAD

**Issue by spotd** [uikit/uikit#1832]
I am using data-uk-lightbox a lot to showcase vimeo videos. All light boxes are opened as expected but they wont play the video in portrait on iOS. Strangely they do play fine in landscape.

I checked and this problem also applies to your documentation page (on an iphone) http://getuikit.com/docs/lightbox.html

**Comment by spotd** [comment]
Any progress on this issue? or should i roll back to a previous version.
Thanks

**Comment by spotd** [comment]
I see this is a known bug - https://github.com/uikit/uikit/issues/1060

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Lightbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
