### ISSUE TITLE
Almost Flat and Gradient Theme for UIKit Sass?

### ISSUE THREAD

**Issue by cpannwitz** [uikit/uikit#1833]
Hey,
I'm missing the possibility to get Sass version of UIKit with the both mentioned themes. 
The sass version (apparently, if I didn't missed something?) only comes with the default, un-themed, way.
I often work with UIKit and this would make a lot of things easier.

**Comment by opendivision** [comment]
I've done the Almost Flat-Theme for UIKit in Sass by hand.
Included is everything, core and components, based on UIKit 2.26.2.
[Forked here.](https://github.com/opendivision/uikit/tree/develop/themes/almost-flat-sass)

Any comments are appreciated. :)

**Comment by nakamuraagatha** [comment]
good..awesome. i think u need publish to bower independent repo...

**Comment by core01** [comment]
@cpannwitz hello, will you publish Almost Flat-Theme to bower?

**Comment by philoest** [comment]
UIkit2 themes will not be published via bower, but this will be changed in UIkit3 here this will be added soon.
