### ISSUE TITLE
Slider "data-uk-slider-item" doesn't add uk-active

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1834]
Title, latest version, data-uk-slider-item doesn't add class uk-active. I've done a temp fix:

`$("[data-uk-slider]").on("focusitem.uk.slider", function(e,i) { 
    $(this).find("[data-uk-slider-item]").removeClass("uk-active").eq(i).addClass("uk-active"); 
});`

**Comment by dumitru05** [comment]
you working correctly?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
