### ISSUE TITLE
Getuikit uk-slideshow generated with ng-repeat not showing images

### ISSUE THREAD

**Issue by munkhtsogt** [uikit/uikit#1835]
I have a problem with uikit slideshow + angularjs. When I using ng-repeat trying to bring all images to uk-slideshow then images not showing. Is there someone has similar problems? When I removing ng-repeat tag from div images are coming back. I am very confused right now.

 `<div class="uk-width-1-2" ng-repeat="property in properties">`
`<div class="uk-slidenav-position" data-uk-slideshow="{animation: 'scroll'}">`
        `<ul class="uk-slideshow">`
           `<li ng-if="property.pictures.length > 0" ng-repeat="pp in property.pictures">`
              `<img src="../img/2_wide.jpg" />`
           `</li>`
        `</ul>`
        `<a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-slideshow-item="previous"></a>`
        `<a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slideshow-item="next"></a>`
   `</div>`
`</div>`

**Comment by anushac243** [comment]
I have the same issue with one small difference. When I have the object list declared as static, it works perfectly. But when I make an AJAX call to assign values to the object list, the images don't show up.

The code is being generated correctly though. I see all the <li> tags created with the relevant info in them when I "inspect" the page.

Does this mean that the images are loaded on page load? If so, is there a way to reload the slideshow once the AJAX call is complete?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
