### ISSUE TITLE
Lightbox opens twice

### ISSUE THREAD

**Issue by fheinrich** [uikit/uikit#1836]
Hi,

on this page you can see that if you click an image, the lightbox opens twice:
http://dev3.von-der-see.de/sh/hotel/indoor-spielanlage/

I dont know if this is related but i GUESS it happen since the update to WordPress 4.5.

Can you think of a solution? Thanks :)

**Comment by fheinrich** [comment]
No one has a solution? :/

**Comment by C-Lodder** [comment]
Maybe because you're importing 2 different versions of jQuery. Multiple instances can cause conflicts

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Lightbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
