### ISSUE TITLE
Lightbox space problem on right side

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#1837]
body keep 17px space (http://prntscr.com/atop58) on right side after close the lightbox (http://prntscr.com/atonfd). i check firefox and chrome both browser. i also tested on getuikit website same problem there.

**Comment by viocassel** [comment]
+1

**Comment by fheinrich** [comment]
+1

**Comment by PixelT** [comment]
+1

**Comment by arysom** [comment]
Body is getting style padding-right: 15px; after closing lightbox. I have many uk-grid uk-grid collapse in my layout, I use offcanvas, and uk-cover elements. I call lightbox dynamically: 
```
            var lightbox = UIkit.lightbox.create([
                {'source': imageSrc, 'type':'image'}
                ]);
            lightbox.show();
```

**Comment by miladmeidanshahi** [comment]
you can change your direction via this code bellow
`$.UIkit.langdirection = UIkit.$html.attr("dir") == "rtl" ? "left" : "right";
`
in this way you can change your direction generally

i think because you set your `html` to `ltr` you have to modifie your direction.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Lighbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
