### ISSUE TITLE
Mobile scrolling to bottom of page

### ISSUE THREAD

**Issue by andrewbanchich** [uikit/uikit#1838]
I noticed that on my Nexus 5X on Chrome that scrolling relatively fast to the bottom of a PageKit site (which uses UIkit) makes it snap up a little. Here are screen capture videos of the issue both on my personal site and on the official PageKit homepage.

https://goo.gl/photos/ej3x6MKqMTmT5HVt5

I've also noticed this happens (actually worse) on UIKit's homepage as well, so I am pretty sure it's a UIkit issue.

**Comment by Emadkhanqai** [comment]
http://stackoverflow.com/questions/7408100/can-i-change-the-scroll-speed-using-css-or-jquery

That's your solution.

**Comment by arisbanach** [comment]
That isn't related to what I'm talking talking about. Did you look at the linked videos? Look at where the bottom of the page is when I scroll down.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
