### ISSUE TITLE
Selected radio button not centered in Chrome 49 (OSX)

### ISSUE THREAD

**Issue by zulhfreelancer** [uikit/uikit#1839]
Looks like it a little bit right. It should be centered.

![screen shot 2016-04-19 at 9 16 54 am](https://cloud.githubusercontent.com/assets/3416976/14624634/08404f0c-060f-11e6-947b-6e3223d88dcf.png)

[View my browser info here](http://whatsmybrowser.org/b/Q9FJX0K)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
