### ISSUE TITLE
Firefox jumps horizontal Slideset to vertical

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1840]
Each page view or during a refresh the Slideset for a short moment is only shown vertically and then horizontally.

This happens only in Firefox.

Versions:
Uikit 2.26.2
Firefox 45.02
Win7 Pro 64 Bit

www.experimente.bplaced.net/test/seite/3d-grafik.php

Wrong
![wrong-vertical](https://cloud.githubusercontent.com/assets/7922627/14633166/b07c41fa-061c-11e6-87a1-3debee673d33.jpg)

Correct
![correct-horizontal](https://cloud.githubusercontent.com/assets/7922627/14633175/ba4ae51a-061c-11e6-97fe-1907efafe766.jpg)

**Comment by hansnolte** [comment]
A small success.

<div class="uk-slidenav-position">
<ul class="uk-grid uk-grid-width-1-1 uk-slideset uk-flex-center ">

If I delete the uk-grid-width-1-1, the Thumbnails no longer jumps vertical.

Still not perfect.
Hoping for a solution.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
