### ISSUE TITLE
Lazy Load/Infinite Load Component

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1842]
Concerns the Component from https://uikitplay.com/plays/FXsp

Hello everyone,

can anyone please tell me if and how it works.
A small example of how I can lazy load all pictures of a side, would be really helpful.

Thank you in advance

Hans

**Comment by paulmcrobb** [comment]
I have also been looking at this component and wondering how I get it working, have you had any luck?

**Comment by hansnolte** [comment]
Hi paulmcrobb,

unfortunately, no.

It does not work for me

I hope that Jan Sieler answers on your Comment.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
