### ISSUE TITLE
Is there a way to de-initialize accordion

### ISSUE THREAD

**Issue by silviali** [uikit/uikit#1845]
Hi,

I wonder if there is a way to de-initialize a component that is already initialized on page load?

Thanks.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
