### ISSUE TITLE
Inline css + uikit

### ISSUE THREAD

**Issue by afontcu** [uikit/uikit#1846]
Hi there,

Are there some best practices about inlining CSS (you know, embedding some CSS on the head tag while loading all the other stuff on footer to speed up the site) with uikit?
I don't want to embed the whole uikit code (obviously) but I find myself replicating too much CSS to mantain structure.

Thanks in advance.

**Comment by Emadkhanqai** [comment]
Create a new CSS file and add your modifications there. That simply overrides the existing finishing.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team
