### ISSUE TITLE
Problem with UIKIT upload component 

### ISSUE THREAD

**Issue by jmbolanos** [uikit/uikit#1847]
Hi

I have the upload component .js and .css loading on my page. I have set the upload directory to 'uploads/' - when dropping an image or manually selecting one, the progress bar reaches 100% and all seems successful.

The form has
action='proc_update_container.php' method='post' enctype='multipart/form-data'

The element has
input id='fileToUpload' type='file' name='fileToUpload'

The script has
var select = UIkit.uploadSelect($('#fileToUpload'), settings

With the settings as:
action: 'proc_update_container.php/', // upload url

and the php script that the form submit button calls to process the image upload server-side is:

$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $target_file);

When I submit the form, the php scrip does not receive a filename, so fails. If I use a simple html form using the same form action and a standard HTML input type="file" name="fileToUpload" id="fileToUpload"
then the image file is placed in the uploads/ folder perfectly.

Where am I going wrong?

Thanks in advance

John

**Comment by setonek** [comment]
Hi
Please try this code

$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"][0]);
move_uploaded_file($_FILES["fileToUpload"]["tmp_name"][0], $target_file);

or even default like
$_FILES["files"]["name"][0] etc.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
