### ISSUE TITLE
Placeholder for sticky get wrong height, when element have img inside

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1848]
``` html
<div data-uk-sticky>
    <img src="path/to/image">
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, saepe.</p>
```

The placeholder (uk-sticky-placeholder) for div give height before the image will be loaded - after that, the content below sticky element (in example above is paragraph) can't be visible - it will be cover by the image

**Comment by prtome** [comment]
Hello
I have the same problem exactly, did you found a solution ? I am using the latest UIKIT
thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
