### ISSUE TITLE
Form-Select component in Firefox doesn't popup options list using keyboard

### ISSUE THREAD

**Issue by leik** [uikit/uikit#1849]
Hi there,

I've tested it in Firefox, Firefox ESR and Firefox Developer Edition, the form-select component doesn't pop up the options list when using keys: "enter", "space", "up/down". It seems that the options list is invisible and up/down key + enter can actually change the selection and the button label changes accordingly.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
