### ISSUE TITLE
Scrollspy on scrollable elements

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#1851]
As it stands scrollspy only works via the `uk.document.scrolling`, it would be nice if this could be changed to work on scrollable elements like `uk-scrollable-text` too.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
