### ISSUE TITLE
sticky animated -  glitch on Chrome for android

### ISSUE THREAD

**Issue by maxjf1** [uikit/uikit#1852]
The sticky animated component is very odd on chrome for android:
creating something like: 
`<header data-uk-sticky="{top:-100, animation: 'uk-animation-slide-top'}">
content
</header>`
the animation works fine on Desktop browsers.
but on android chrome, when i scroll up and down, the animation triggers before it reaches the top:-100. this happens maybe because the chrome bar.
i notice something, the animation triggers when the screen size changes (window resize). the chrome bar is hidden scrolling down, but it appears scrolling up and changes the window size.
this don't happen when the sticky has no animation.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
