### ISSUE TITLE
Dropdown hide() should clear hoverIdle timeout

### ISSUE THREAD

**Issue by unodgs** [uikit/uikit#1854]
Could you add:

```
if (hoverIdle) {
     clearTimeout(hoverIdle);
}
```

in dropdown hide function? Otherwise if I manually call hide() dropdown appears anyway because timeout function triggered by mouseenter is not cleared.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
