### ISSUE TITLE
unable to play uikit lightbox on mobile iPhone

### ISSUE THREAD

**Issue by messagedj** [uikit/uikit#1855]
it is not possible to play a the Youtube lightbox at http://getuikit.com/docs/lightbox.html on an iPhone with the latest IOS. 

the movie opens, then closes immediately

**Comment by entonbiba** [comment]
@messagedj which iphone and ios version did you try?
I just tested on latest ios version 9.3.4, it works fine on my end.

**Comment by messagedj** [comment]
issue has been solved a few month ago by UiKit, see https://github.com/uikit/uikit/issues/1060#issuecomment-227386847
