### ISSUE TITLE
Toggle uk-hidden class not added by default

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#1857]
There's no .uk-hidden class added to the element by default. Both are visible upon page load.

My code is like this:

```
<a class="dm-show-form" href="#review-form-bottom" data-uk-smooth-scroll="" data-uk-toggle="{target:'#dm-comment-form-toggle', animation:'uk-animation-fade'}"><?php esc_html_e( 'Show/Hide form', 'twentysixteen' ); ?></a>

<div id="dm-comment-form-toggle">Form contents </div>
<a id="review-form-bottom"></a> // smoothscroll
```

This is what happens:
- both elements are visible, while the form contents should be hidden
- after clicking on the toggle button, it still shows.
- after a second click it hides.
- after a third click it shows and from then on, it works the way I'd like to see it working.

If I manually add the _uk-hidden_ class, it doesn't get better either.
- it hides upon page load
- after the first click, it stays hidden
- after second click it stars to show.

Is this a bug or a fault in my code?

**Comment by miladmeidanshahi** [comment]
i don't think it's a bug it's normal if you want to use toggle you have to add `uk-hidden` manually works fine.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
