### ISSUE TITLE
Dropdown close animation

### ISSUE THREAD

**Issue by FrantisekVrab** [uikit/uikit#1858]
Hi there,

it would be nice to have an animation when closing a dropdown. I'm not sure if it is possible now.

**Comment by stevesobol** [comment]
+1 to this suggestion. Plus, I'd like to be able to change the delay that occurs on mouseout. I'm using a dropdown in a navbar, it's triggered by hovering over one of the navbar's items, and I'd like to control how quickly it goes away when I move the mouse away from the navbar item and the dropdown.

**Comment by smartclash** [comment]
@FrantisekVrab It's easy to add one. Please check out animate.css and you can implement it with just 12 lines of css. Simple as it is!

**Comment by stevesobol** [comment]
Can the mouseout delay be changed via animate.css as well, @smartclash ?

**Comment by smartclash** [comment]
@FrantisekVrab Unfortunately, mouse delays can't be done via css. you need to use some javascripts to make it work

**Comment by stevesobol** [comment]
Was that meant for FrantisekVrab or me?

There is already a mouseout delay... I want to get rid of it.

**Comment by smartclash** [comment]
@stevesobol ,Yup, it was for you. Sorry for that

**Comment by stevesobol** [comment]
Well, I need to read more carefully next time. Mouseout delay can be controlled using "remaintime" and for no mouseout delay I can just set remaintime to zero. http://getuikit.com/docs/dropdown.html Apologies for not catching that earlier.

**Comment by smartclash** [comment]
@stevesobol Wow, even i didn't come across that one. Still now, i used animate.css and it worked perfectly well. Thanks for this

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
