### ISSUE TITLE
Nestable and Sortable not working in Chrome [Version 50.0.2661.75 (64-bit)]

### ISSUE THREAD

**Issue by seemsindie** [uikit/uikit#1861]
Well as the title says nestable are not working in the docs in chrome. When i switch to Firefox everything is OK. There is no error message in the console.

http://getuikit.com/docs/nestable.html

EDIT: Sortable are not working also http://getuikit.com/docs/sortable.html

**Comment by viocassel** [comment]
Chrome Version 50.0.2661.94 (64-bit) - Nestable and Sortable works fine.

**Comment by seemsindie** [comment]
@viocassel Well i don't know how else to show it to you. Here is a video of it https://goo.gl/photos/mUtvHUU62YggWU7s9

I have to add that i have touchscreen display. I have Dell E7240.

**Comment by adripanico** [comment]
Same issue here with Chrome 51.0.2704.84 for Windows (no touchscreen). It was working fine and suddenly it stop working.

In the same computer, with Firefox everything works like a charm. Tested in other computers with Chrome and also working fine. It is weird because I don't see any console error or warning.

**Comment by afflicto** [comment]
Same here. I happen to have a touch-enabled device connected. Maybe it's that? I don't know...

Chrome Version 51.0.2704.103 m (64-bit) on Windows 10.

**Comment by seemsindie** [comment]
Still not working in Version 52.0.2743.116 (64-bit)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
