### ISSUE TITLE
Problem with Datepicker

### ISSUE THREAD

**Issue by ioszhuk** [uikit/uikit#1862]
I use last version of UIKit (2.26.2) and I found 1 issue that refers to "datapicker".

Datapicker doesn't work only in Google Chrome at iOS and Android devices.

**Comment by nblackburn** [comment]
It works for me but the keyboard covers it up creating the impression of it not being there.

**Comment by zzseba78** [comment]
Same problem here, when you focus the field, the calendar shows but inmediatly it hides, you have to focus again to see it ( if you don´t close the android keyboard ).

**Comment by eleumas** [comment]
i have same issue with datepicker. Some news?

**Comment by nblackburn** [comment]
@eleumas As you can see by their issue list, they aren't the most responsive so it might be a wait.

**Comment by marshad-allshore** [comment]
I have fixed that issue by changing this line # 162 and # 163 in init: function
if (active!==$this) $this.pick(this.value ? this.value:($this.options.minDate ? $this.options.minDate :''));
to 
if (active!==$this) $this.pick(jQuery(this).val() ? jQuery(this).val():($this.options.minDate ? $this.options.minDate :''));

and adding a line just before it  jQuery(this).trigger("blur"); so it will be 
```
this.on("click focus", function(e){
    if (active!==$this){
        e.stopPropagation();
        e.preventDefault();
        var currEle = jQuery(this);
        currEle.trigger("blur");
        $this.pick(currEle.val() ? currEle.val() : ($this.options.minDate ? $this.options.minDate :''));
  }
})
```

**Comment by eleumas** [comment]
sorry but i haven't understood where change the second snippet.
`this.on("click", function(e){
    if (active!==$this){
        e.stopPropagation();
        e.preventDefault();
        var currEle = jQuery(this);
        currEle.trigger("blur");
        $this.pick(currEle.val() ? currEle.val() : ($this.options.minDate ? $this.options.minDate :''));
  }
})`

Please, can you explain better? Thanks.

**Comment by marshad-allshore** [comment]
File : https://github.com/uikit/uikit/blob/v2.26.4/src/js/components/datepicker.js
modify line # 162, # 163  and # 164 (  **})**  closing part of function started on # 162) according to above mentioned script.

**Comment by eleumas** [comment]
@marshad-allshore  Thanks for have help me, but your code doesn't work. 

I have:
1) deleted all code on original file datepicker.js
2) pasted your full code 
so i have replaced the code.

In the head of my site i have inserted: <script src="uikit/js/components/datepicker.js"></script>

On my phone (nexus 6P with google chrome) the datepicker doesn't work :(

**Comment by marshad-allshore** [comment]
@eleumas 
Please have a look into this URL here are two calendars that I have tested on GOOGLE CHROME / ANDROID 5.1 and IPHONE 4,6 

http://test.skyrun.com/

If that works for you then you may look the code of that file.
http://test.skyrun.com/templates/yoo_moustache/warp/vendor/uikit/js/addons/datepicker.js

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
