### ISSUE TITLE
Slider component doesn't work correctly inside a switcher content.

### ISSUE THREAD

**Issue by chrism4111** [uikit/uikit#1863]
Slider component don't work correctly as a switcher content.
I tried to add a trigger to resize window when switcher content shows and all worked perfectly, but not worked when switcher has a transition effect.

This is my case:

```
<ul  data-uk-switcher="{connect:'#my-id'}">
    <li><a href="#">Slider 1</a></li>
    <li><a href="#">Slider 2</a></li>
</ul>

<ul id="my-id" class="uk-switcher">
       <li>
           <div data-uk-slider>
                  <div class="uk-slider-container">
                   <ul class="uk-slider uk-grid-width-medium-1-4">
                     <li><img src="" /></li>
                     <li><img src="" /></li>
                     <li><img src="" /></li>
                  </ul>
                </div>
            </div>
          </li>
          <li>"Another Slider"</li>
</ul>
```

Thnks

**Comment by TomS-** [comment]
Have you tried adding data-uk-check-display to the switcher?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team

**Comment by xonixmx** [comment]
philoest ,
Aug 2019 -- the same issue with Slidershow inside Switcher, Even in UIKit documentation with Slideshow demonstration if you click on Markup tab then click on Peview tab. Nothing changes with UIKit. And nothing result when I try fix it by javascript update code.
