### ISSUE TITLE
uk-width-small-* do not work

### ISSUE THREAD

**Issue by biapar** [uikit/uikit#1864]
Hi,
when I use uk-width-small-*, I see that this don't work. 
Is there some bug?

**Comment by Frique** [comment]
Got a code example?

**Comment by biapar** [comment]
Like:

`<footer id="footerzone">
    <div class="uk-container uk-container-center margintop50 uk-margin-bottom">
        <div class="uk-grid">
            <div class="uk-width-small-1-2 uk-width-medium-4-10">
                
                    <div class="uk-float-left"> 
				 
					
					</div>
              
                
            </div>
			<div class="uk-hidden-small uk-width-medium-2-10"> 
            </div>
			<div class="uk-width-small-1-2 uk-width-medium-4-10">
                 
                    <div class="uk-float-right"> 
	 
				  
                </div>
            </div>
        </div>
    </div>
</footer>`

The div are not on the same "row" on small devices or medium devices.

![image](https://cloud.githubusercontent.com/assets/661517/15240407/b434d084-18e9-11e6-9bb6-03f5b760065e.png)

**Comment by Frique** [comment]
Not sure why that wouldn't work, but in this case you can leave the small out, and use ```uk-width-1-2 uk-width-medium-4-10```
That way it will be 1-2 until the medium size kicks in.

**Comment by biapar** [comment]
As you suggest works. Uhm..why?

**Comment by Frique** [comment]
```uk-width-1-2``` = Generally the width should be 1/2.
```uk-width-medium-4-10``` = Only on medium size and larger, it should be 4/10.

**Comment by Siton-Design** [comment]
I think you do some "**salad**" :)
In any responsive grid you will find two main parts. rows & cols (mix with media queries)

Basic tutorial: http://www.w3schools.com/css/css_rwd_grid.asp 

## **Part 1 - "Equal Height Columns" = Rows effect (This is not really a tr table rows)**

The "rows" are really evolution of the "fauxcolumns" problem:
fauxcolumns - Old article:
http://alistapart.com/article/fauxcolumns
Very simple example:
http://codepen.io/bwangila/pen/zlbEJ/

> You will find endless "Equal Height Columns" tutorials and ideas. Google it

Of course in uiKit the solution is "build-in" in the core code (uk-grid) or the "Next-generation-solution " flexBox (uk-flex).
> In flexbox By default, all flex items will be aligned to the left and equally matched in height and width. cool :)

Or "uk-grid":
```
/* part of the code */
.uk-grid:before,
.uk-grid:after {
  content: "";
  display: block;
  overflow: hidden;
}
.uk-grid:after {
  clear: both;
}
```

## **Part two. Control the Widths** 
uk-width-1-2 its like saying:
```
uk-width-1-2 {
  width: 50%;
}
```
### For the "responsive" grid your grid should also use Media Quarries:
```
/* Phone landscape and bigger */
@media (min-width: 480px) {
.uk-width-small-1-2{
  width: 50%;
}
}
```
**Summary:** Your code example only talk about width. You **must** add the uk-grid (or uk-flex) class for the "Equal Height Columns" effect.
```
<div class="uk-grid">
    <div class="uk-width-1-2">...</div>
    <div class="uk-width-1-2">...</div>
</div>

```
I hope this answer will help you.
This is close issue :) You dont have any "bug".

**Comment by biapar** [comment]
Thank you for your reply but I don't made any salad and I know what mean responsive, row, column and so. Maybe that this is the first time that I use uikit after a lots of Bootstrap.

**Comment by Siton-Design** [comment]
OK, sorry :)  I think the best approach is to use the live ui-kit examples to learn about the framework. And the official docs

**Comment by biapar** [comment]
No problem. Thx.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
