### ISSUE TITLE
Galaxy S5 Mobile View

### ISSUE THREAD

**Issue by mrdunster** [uikit/uikit#1865]
My website looks just fine when it is on the normal desktop version of google chrome. If I make the window narrow, the offnav activates and everything works fine. When I open my website on my Samsung Galaxy S5 or any other mobile device, it only appears as the desktop version. How can I get uikit to change when it is on a mobile device compared to a desktop?

**Comment by philoest** [comment]
Have you tried this:

http://www.w3schools.com/css/css_rwd_viewport.asp
