### ISSUE TITLE
htmleditor: toolbar cut off on small screens

### ISSUE THREAD

**Issue by C-Lodder** [uikit/uikit#1867]
If you have a look at the last HTML Editor block here:

http://getuikit.com/docs/htmleditor.html#tab-mode

You'll see the `Markdown`, `Preview` `Fullscreen` buttons on the right hand side.

Now when you reduce you browser size down, the buttons stack normally, as shown below:

![screeny1](https://cloud.githubusercontent.com/assets/2019801/15184965/265d1d44-178f-11e6-9fbe-1485b8934535.png)

However, if you then go into fullscreen mode, you'll see that these 3 buttons disappear and you can only see the top border of a button, as shown here:

![screeny2](https://cloud.githubusercontent.com/assets/2019801/15184997/4adc8132-178f-11e6-8ebd-089b20507828.png)

I believe this is due to the absolute positioning for the `.uk-htmleditor-content` class:

```
.uk-htmleditor-fullscreen .uk-htmleditor-content {
    position: absolute;
    top: 41px;
    left: 0;
    right: 0;
    bottom: 0;
}
```

**Comment by C-Lodder** [comment]
cc/: @aheinze

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
