### ISSUE TITLE
appears some spacing between images/ modal-element issue in Js

### ISSUE THREAD

**Issue by san8383** [uikit/uikit#1869]
Appears some spacing between images in a dynamic grid after closing lightbox.
its before
![image](https://cloud.githubusercontent.com/assets/19327440/15216677/c89237e4-1860-11e6-8645-106a3ce6e822.png)
and after closing lightbox image
![image](https://cloud.githubusercontent.com/assets/19327440/15216722/f96e6b12-1860-11e6-9cfc-c973e182da0a.png)
Also aded to the BODY element padding. body style="padding-right: 17px;" by webkit engine.
The same on crome and mozilla
Its a modal-element issue in js. WHen modal window is opened scroll is dissapering, body transform to +17 pixels (width of scrollbar). Then scrollbar appears and in the body style webkit add padding 17 pixels after closing modal window. As a temporary solvation can be added padding-right: 0 !important; to body element in uikit.css. But its work not perfect when modal window is opened (design is shifting in that moment)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
