### ISSUE TITLE
CSS not working with Sticky

### ISSUE THREAD

**Issue by mikerockett** [uikit/uikit#1870]
I sincerely hope this is reproducable, and that I'm not going mad and overseeing something ever so simple here.

I have the following markup:

``` html
<div role="container" class="uk-container uk-container-center">
    <div data-uk-sticky>
        <nav class="uk-navbar uk-navbar-attached">
            ...
        </nav>
    </div>
</div>
```

And the following SASS:

``` sass
div[role=container] {
    ...
    nav {
        margin-top: 2rem;
        background-color: white !important;
        border-bottom: 2px solid $colPrimary;
        ...
    }
    ...
}
```

There's no direct descendant operator being used here, but my `nav` loses its styles when inside `data-uk-sticky`, which works as expected (albeit I need to add `z-index`), and reverts to the default `.uk-navbar` styling.

Is Sticky somehow removing my styles? Or am I missing something here?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
