### ISSUE TITLE
Ruby gem and Sass

### ISSUE THREAD

**Issue by afuno** [uikit/uikit#1871]
When do you plan to release a gem for Ruby?

**Comment by samueljseay** [comment]
I would suggest there is no need for a ruby gem. Use bower or npm to include the assets in your project. This isn't really an issue that should be the responsibility of the UIkit team anyway.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
