### ISSUE TITLE
programatically expand/collapse accordion?

### ISSUE THREAD

**Issue by dvulanov** [uikit/uikit#1873]
Hello, 

Is there a way to programatically open/close specific accordion titles?

Looking at UIkit.accordion($('#id')), there doesn't seem to be any accessible functions like: expand or collapse?  Perhaps I'm missing something?

Thanks

**Comment by alejoar** [comment]
Hi, I was looking into doing this same thing.

This is how I achieved it:

```
<div class="uk-accordion" id="accordion" data-uk-accordion>
    <h3 class="uk-accordion-title uk-hidden-small">...</h3>
    <div id="accordion_content" class="uk-accordion-content">...</div>
</div>
```

And then:
```
UIkit.$("#accordion_content").toggle()
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by newjie** [comment]
The Joomla template I am using still insist on using UIkit 2, so I have to stick with UK2 for now, and this is about the only place I can find talking about this issue.
@alejoar How do you make
` UIkit.$("#accordion_content").toggle()`
work? On my end when you do that it just sets the accordion-content element to `display:block`, but it's wrapper's height is still 0, so it doesn't work for me.
![image](https://user-images.githubusercontent.com/12814040/127874363-cd280fd9-17c0-4637-a0ad-5037301970de.png)

**Comment by alejoar** [comment]
@newjie it's been a long time since I last used uikit, but just for the sake of trying to help I went into your demo site and `UIkit.$("#year2021").toggle()` works just fine when the site loads.

Once you start mixing accordion clicks with the programmatical toggle is where I start to see some problems. I suggest you try to address this with an `onClick` event in your accordions instead of letting UIKit handle the clicks.

**Comment by newjie** [comment]
@alejoar Thanks for your answer. I put a "debugger" on my document ready function so you can see that it doesn't work for me.

It seems to me `UIkit.$("#year2021").toggle()` is just the original jQuery function(instead of a UIkit function) which only show or hide the element.

**Comment by alejoar** [comment]
Don't put a debugger. I tested straight on the console with the site loaded and it worked. 

Sorry I can't be of much more help.

**Comment by newjie** [comment]
Maybe you can teach me how to simulate "site loaded" in the console so I can see how it'd work for myself? Thank you!
