### ISSUE TITLE
How to disable @media in CSS uikit ?

### ISSUE THREAD

**Issue by dimaasdzxc** [uikit/uikit#1876]
Hi! How to disable @media in CSS uikit ? How to disable responsive layout when using the uikit?

**Comment by dimaasdzxc** [comment]
Наблюдается проблема с адаптивными шрифтами на сайте при просмотре на мобильных устройствах ( http://kolestorg.ru )

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
