### ISSUE TITLE
UIkit .scss variables file always gets overwritten

### ISSUE THREAD

**Issue by ThomasTesla** [uikit/uikit#1877]
The variables (`uikit-variables.scss`) for the SCSS version are getting imported at the top of the index file (`uikit.scss`).

This is fine so far, you have one variables files where you can set everything.

The problem is that it's completely useless because everything gets overwritten from each single imported file.

Even when importing the `uikit-variables.scss` at the bottom of the `uikit.scss` file, everything gets compiled with the variables at the top of each imported core or components file.

Is the variables file just there to confuse developers or what is the purpose? Do I have to delete all the definitions of variables by hand at the top of the core and components files?

**Comment by Siton-Design** [comment]
You can look at like "Default" and inside each file you have more structure variables "by file" (Like override idea). 

> "Even when importing the uikit-variables.scss at the bottom of the uikit.scss"

Its like "remove"  This file and use only the "per-file" variables ("your uikit-variables.scss its like the "yellow" deceleration for the [p] in this example) 
```
//scss
$color: red;   // i am from uikit-variables
$color: blue; // i am from some  single imported file 
p{
  color: $color; //You must declare the var before you use it. OK :) i am blue
  
}
$color: yellow; 
.yellow{
  color: $color; //You must declare the var before you use it. OK :) now i am yellow
}
```
OUTPUT:
//css
```
p{ 
  color: blue;
}
.yellow{
color: yellow;
}
```
### IMPORTANT - less VS sass
Sass not use "lazy-loading" (like less). So you must **declare** the var before you use it - work like  most programing languages. 
http://lesscss.org/features/#variables-feature-lazy-loading

In Sass This for example will throw error (in less this is ok):
```
p{
  color: $color;
  
}
$color: red;
```
> Undefined variable: "$color".

Same idea in php
```
<?php
echo $hello;
$hello = "hello";
```
>  Undefined variable: hello

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
