### ISSUE TITLE
Datepicker current date same as min and max.

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#1878]
There is currently a bug in the datepicker code where if the current day is equal to both the minDate and the maxDate, the day is disabled from being selected.

https://github.com/uikit/uikit/blob/develop/src/js/components/datepicker.js#L312

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
