### ISSUE TITLE
Timepicker increment

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#1879]
It would be nice if it was possible to set the increment in which the timepicker values are populated with as it's currently hard coded to 30min intervals.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Timepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
