### ISSUE TITLE
Scrollspy nav topoffset not working on mobile

### ISSUE THREAD

**Issue by prusayn** [uikit/uikit#1881]
I try to make top offset for scrollspy nav, but unfortunately it's not working on mobile.
There is a code in data:
`data-uk-scrollspy-nav="{closest:'li', smoothscroll:true, topoffset:300}"`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
