### ISSUE TITLE
Custom prefix missed in core.js

### ISSUE THREAD

**Issue by bassmanpaul** [uikit/uikit#1882]
Hi Team,

First off, great job with uikit!

When I compile a custom prefixed version of uikit I noticed that one original `uk-` prefix still remains.

The file & line in question is:

https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L735

Is this a bug or an intentional omission?

Thanks

**Comment by stell** [comment]
This must be a bug because after manual correction auto-init works on our custom prefixed app.

**Comment by aheinze** [comment]
Hi,

this is fixed now : https://github.com/uikit/uikit/commit/f86d6b1ca73ba56f055bbfb4cf7aec577ac5a9ce
