### ISSUE TITLE
How to use UIKit with Browserify ?

### ISSUE THREAD

**Issue by chrisvidal** [uikit/uikit#1883]
Hi
after installing jquery and uikit trough npm,
i have my app.js with some code like

`var $ = window.jQuery = require('jquery'),
    UI = require('UIkit');`

then later on i try to use the different UI core functions like
UI.toggle() or try to access UI.Utils object

but i got ' UI.toggle is not a function' or undefined for any UIKit object.

Any ideas please ?
thank you

**Comment by nixgadget** [comment]
Isnt it require('uikit') ?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
