### ISSUE TITLE
Slider component wont work well at RTL mode

### ISSUE THREAD

**Issue by Siton-Design** [uikit/uikit#1884]
Screenshot from the customizer:
![slider-rtl](https://cloud.githubusercontent.com/assets/16711871/15480342/b8fd27d2-212d-11e6-8f68-6c63f92c8d46.jpg)

**Comment by miladmeidanshahi** [comment]
yes i have same problem it's very necessary to fix it as soon as possible

**Comment by miladmeidanshahi** [comment]
you can solve this temporary just add `dir="ltr"` to element that has slider attributes

**Comment by Siton-Design** [comment]
Fix in the new UIKIT VERSION! :) thanks!!!!!!!!!!!!!!!!!

**Comment by arasdesign** [comment]
but the problem isn't fixed yet ... @siton-systems  how you say its fixed in the new version ?
