### ISSUE TITLE
Parallax and animation on the same element stops parallax effects working

### ISSUE THREAD

**Issue by stu177** [uikit/uikit#1890]
It seems putting a parallax data tag and an animation CSS class on the same elements stops the parallax effects from working. For example:

`<div class="uk-animation-slide-top" data-uk-parallax="{opacity: '1,0', scale: '1,0'}">`
`</div>`

The above should animate in and then parallax out but only seems to animate in.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Parallax component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
