### ISSUE TITLE
How do you pass options to a UIkit modal through javascript?

### ISSUE THREAD

**Issue by danishiqbal4** [uikit/uikit#1891]
HTML:
`<div id="myModal" class="uk-modal">
    <div class="uk-modal-dialog">
        <p>hello</p>
    </div>
</div>`

Javascript:
`UIkit.modal("#myModal").show();`

How would you pass multiple options like keyboard: false, modal: false etc while initiating the modal through js

**Comment by danishiqbal4** [comment]
After wasting hours I finally got it to work

`UIkit.modal('#myModal', {modal: false, keyboard: false, bgclose: false, center: true}).show();`

For God's sake would you mind adding it to the [Documentation](http://getuikit.com/docs/modal.html)

**Comment by zzseba78** [comment]
I agree, the documentation should be more complete.

**Comment by jlove73071** [comment]
> I agree, the documentation should be more complete.

Documentation? UIKit 2's documentation is little more than an FAQ.
