### ISSUE TITLE
Request: slideshow ability to display portrait images "properly"

### ISSUE THREAD

**Issue by Notanotherdotcom** [uikit/uikit#1894]
"Properly" is a strong word :)

I have a slideshow where there are mostly landscape images along with some portrait ones. The portrait ones get cut off because all images are forced to cover the slideshow area.

Removing this bit of CSS from the slideshow.js file line 115 allowed them to display properly:

`width: '100%',`

Along with changing the background size to "auto" in the CSS file instead of "cover":

`.uk-cover-background {
        background-size: auto;
}`

It would be nice to have this as an option for the slideshows. There are other considerations though - since the background of the slideshow behind is white, the contrast slidenav next/prev icons aren't visible, but you can obviously style around that minor issue.

I don't think this would be a particularly difficult option to add (hopefully!)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
