### ISSUE TITLE
Modal Gives Body Padding when changed

### ISSUE THREAD

**Issue by maxjf1** [uikit/uikit#1896]
I was inserting content dynamically on a modal with js, but everytime i insert something on it, it gives de `<body>` 17px padding left. this padding is to hide the scrollbar or something like that, i guess. The problem is, it ADD 17 px paddin. If i insert 10 times, the `<body>` will have 170px padding left!
My temporally fix was giving the `<body>` a css property `padding left: 0px !important`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by claudchan-alyka** [comment]
This css should fix the issue:
`
html.uk-notouch:not(.uk-modal-page) body {
    padding-right: 0 !important;
}
`
