### ISSUE TITLE
Font Import is generated wrong (Added Google Fonts to customizer)

### ISSUE THREAD

**Issue by fheinrich** [uikit/uikit#1897]
Hi,

so I followed the instructions @ getuikit. I cloned uikit from Github, created an own theme and edited the customizer.json like this:

`{
            "type": "font",
            "vars": [
                "*-font-family"
            ],
            "options": {
                "System Fonts": [
                    {"name": "Arial", "value": "\"Helvetica Neue\", Helvetica, Arial, sans-serif"},
                    {"name": "Consolas", "value": "Consolas, monospace, serif"},
                    {"name": "Georgia", "value": "Georgia, \"Times New Roman\", Times, serif"},
                    {"name": "Lucida", "value": "\"Lucida Grande\", \"Lucida Sans Unicode\", Arial, Verdana, sans-serif"},
                    {"name": "Times New Roman", "value": "\"Times New Roman\", Times, serif"},
                    {"name": "Trebuchet", "value": "\"Trebuchet MS\", Verdana, Arial, sans-serif"},
                    {"name": "Verdana", "value": "Verdana, Arial, sans-serif"}
                ],
                "Google Fonts": [
                    {"name": "Dosis", "value": "Dosis, sans-serif", "url":"https://fonts.googleapis.com/css?family=Dosis"},
                    {"name": "Open Sans", "value": "'Open Sans', sans-serif", "url":"https://fonts.googleapis.com/css?family=Open+Sans"},
                    {"name": "Oswald", "value": "Oswald, sans-serif", "url":"https://fonts.googleapis.com/css?family=Oswald"},
                    {"name": "Droid Sans", "value": "'Droid Sans', sans-serif", "url":"https://fonts.googleapis.com/css?family=Droid+Sans"},
                    {"name": "Oxygen", "value": "Oxygen, sans-serif", "url":"https://fonts.googleapis.com/css?family=Oxygen"},
                    {"name": "Source Sans Pro", "value": "'Source Sans Pro', sans-serif", "url":"https://fonts.googleapis.com/css?family=Source+Sans+Pro"}
                ]
            }
        },`

I think and hope I havent done any mistake here.

Then, I go "gulp sync", go to the customizer and choose my fonts. When clicking "get CSS" and watching the file, I get something like this:

`@import '../fonts/.googleapis.com/css?family=Open+Sans';
@import '../fonts/.googleapis.com/css?family=Dosis';`

Which of course leads to errors when trying to load the font.

Does anyone have an idea?

**Comment by fheinrich** [comment]
Crazy :( 18 days, no answer?

**Comment by fheinrich** [comment]
So, is there no solution for my problem?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The Customizer has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
