### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Musiphilos** [uikit/uikit#1902]
Hi All,

Just started using UIkit and I'm impressed.
It seems the smooth-scrool.js documentation is not up to par with its features. Besides "offset" there seems to be a "duration" parameter that is not discussed.

Also, it could be very useful to expand the transitions available since it seems only 

`easeOutExpo=function(t,o,i,n,s){return o==s?i+n:n*(-Math.pow(2,-10*o/s)+1)+i}`

Is available.

A few selection from: https://api.jqueryui.com/easings/ would be great

Cheers

**Comment by beruic** [comment]
In addition I can mention under the same headline that there is no documentation mentioning that you can stack progress bars.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if there are problems with the new Docs regarding this :)

Thanks for your understanding,
Your UIkit Team
