### ISSUE TITLE
The problem with the Button group and Dropdown Blank

### ISSUE THREAD

**Issue by afuno** [uikit/uikit#1903]
If the inside of Button Group put Dropdown Blank, then the text size will be: 0.001px;

To this effect: https://github.com/uikit/uikit/blob/master/src/less/core/button.less#L358

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
