### ISSUE TITLE
Active checkbox adds indoor tag input

### ISSUE THREAD

**Issue by Fartuna** [uikit/uikit#1904]
Why indoor tag appears when you view the source code? It should not be? This is mistake?
![40](https://cloud.githubusercontent.com/assets/17340780/15829037/942c5642-2c1a-11e6-917f-10aff308af9e.png)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
