### ISSUE TITLE
Grid.js - Uncaught TypeError: _getSize is not a function

### ISSUE THREAD

**Issue by DanielNemanic** [uikit/uikit#1905]
If I use the "data-uk-grid" with the js File, I receive the following error:

Uncaught TypeError: _getSize is not a function.

Coming from this Function:
`function getElementSize(ele) {
        return _getSize(ele);
    }`

**Comment by pavlosadovyi** [comment]
I'm here with the same problem and have no idea what to do

**Comment by pavlosadovyi** [comment]
Ok, I perform a little debug here and the reason why it's not working in different function declaration, as you could know function written in function expression style:
```js
var _getSize = (function(){...})();
```
is  computed during to script interpretation, in other hand function declaration style which like:
```js
function getSize() {...}
```
is prepare the scope and all stuff before script interpretation. So in original script we calling _getSize function which is undefined at those moment when we need it. I rewrite a bit this stuff and it working as designed now:

grid.js:line:525
```js
function getElementSize(ele) { return _getSize(ele); }
// replaced to: 
function getElementSize(ele) { return _getSize()(ele); }
```
then rewrite _getSize in function declaration style:
grid.js:line:306
```js
var _getSize = (function(){
// replaced to:
function _getSize() {
```

and finally:
grid.js:line:522
```js
})();
// replaced to:
}
```

**Comment by pavlosadovyi** [comment]
#1930

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
