### ISSUE TITLE
outview.uk.scrollspy not working on scrollspy nav

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#1906]
inview.uk.scrollspy works fine, outview.uk.scrollspy doesn't work. 

This maybe true for all scrollspy's

**Comment by oscar26** [comment]
Hi @TomS- , I could get this to work by adding <code>{repeat: true}</code> to the element, like this:

<code> &lt;div id="my-id" data-uk-scrollspy='{repeat: true}'&gt;...&lt;/div&gt; </code>

Maybe it can help you.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
