### ISSUE TITLE
When the switch is not received within the slider height change

### ISSUE THREAD

**Issue by bariskrdrl** [uikit/uikit#1907]
example : 

file:///C:/Users/karad/Desktop/doga-seni-cagiriyor/cities-more.html

They slider in the mobile view is distorted by the switcher switches are modified.
help please

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Switcher component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
