### ISSUE TITLE
Sticky elements temporarily disappear on mobile 

### ISSUE THREAD

**Issue by markzegarelli** [uikit/uikit#1909]
I've run into a problem testing on mobile devices.

It seems when the sticky element becomes "active", the element disappears until scrolling stops. This leads to a choppy user experience.

[here](https://drive.google.com/file/d/0B5m0i0SGzsYgYnh5RmE5ZDJkRWc/view?usp=sharing) is a recording of the issue.

Is there any way to smooth this out?

**Comment by shrpne** [comment]
I noticed this only in safari. Mobile chrome and mobile firefox are ok.

**Comment by proweb** [comment]
have same issue on ipad
two-column design with left viewport-height
when scroll right-content column sticky elements (menu) just disappear 

Thanks for @shrpne helped your "hack"

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
