### ISSUE TITLE
Request: add slides to slideshow

### ISSUE THREAD

**Issue by vinikey** [uikit/uikit#1910]
Hello,
Is in your plans to add more features in sliders ( slider, sliderset, slideshow )?
I really love the way you construct the sliders, but I believe that should be an add / remove / update action, in order to add dynamically more slides in slideshow.

Thank you!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We are currently working on the slideshow in UIkit3 and here this will be possible. But also in UIkit2 this should be possible if you add the HTML structure to the Slideshow.

Thanks for your understanding,
Your UIkit Team
