### ISSUE TITLE
i use pjax load content, it contain uikit component, but the uikit js not work, how to fix it?

### ISSUE THREAD

**Issue by leeboo** [uikit/uikit#1911]
i use pjax load content, it contain uikit component; the uikit.js has loaded at first page load; 
and then pjax just load html content, no js file;

and then the uikit not bind component event, like nav menu etc.

so how can i rebind or re init uikit; what's the api?

**Comment by leeboo** [comment]
no body know？

**Comment by zzseba78** [comment]
Did you check this? 
http://getuikit.com/docs/documentation_javascript.html#dom-observe
