### ISSUE TITLE
Ukit autocomplete for Coda Editor?

### ISSUE THREAD

**Issue by roterkater** [uikit/uikit#1912]
any chance?
thanks.

**Comment by tbba** [comment]
works here already just fine!
In your coda2 project settings make sure the last 2 checkmarks are checked (index all and auto-suggestions from all page data...)

**Comment by roterkater** [comment]
thanks for your reply.
I'm working on a remote FTP (one reason why i'm using coda rather than sublime + plugin) so I'd need to setup a site on local machine and place at least the Ukit files there to index. Indexing seems to work on local files only.
Still, it will not suggest uk-* classes like with the sublime plugin. Am i doing it wrong?
thanks.

**Comment by roterkater** [comment]
thanks for your reply.
i was thinking of some autocomplete plugin for classes / attributes / snippets.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
