### ISSUE TITLE
New component: input clear

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#1913]
Hi guys. Welcome new component **input clear**.
Its very simple component but maybe for someone was helpful.

![clear](https://cloud.githubusercontent.com/assets/2857625/15991309/eaab44a0-30b7-11e6-9c69-6f6f9b8df441.png)

Use: add `data-uk-clear` to `input`.
`<input type="text" name="search" data-uk-clear="" />`

Example: http://codepen.io/Intiligent/pen/pbyjeN

**Comment by jsieler** [comment]
@Intiligent might you please share this component on https://uikitplay.com/ ?
Thanks!

**Comment by zzseba78** [comment]
Well done!! very useful

**Comment by hiren1610** [comment]
@Intiligent 
First of all thank you. It saved my time a lot as I really needed this component in my project.

I have noticed a little issue though, if I right click and paste data in input box, it doesn't trigger the clear button until I actually press any key.

I just made some changes to bind paste event and a little hack to make it work though.
`this.element.on("keyup", function(){`
	`$this.update();`
`});`
`// Binding the paste event, right click paste event now works.`
`this.element.on("paste", function(){`
	`setTimeout(function() {`
		`$this.update();`
	`}, 100);`
`});`

Please see if its possible for your to update your code if this seems legit or please reply if there is any better way to improve this.

**Comment by Intiligent** [comment]
welcome)
i update code, check it now

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
