### ISSUE TITLE
there is no translation for message in upload.js

### ISSUE THREAD

**Issue by progreccor** [uikit/uikit#1914]
Hi!
You hardcoded the message 'Only the following file types are allowed' in the function
https://github.com/uikit/uikit/blob/develop/src/js/components/upload.js#L241

There is no language constant for that message. Please add it!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
