### ISSUE TITLE
Dropdown is not accessible

### ISSUE THREAD

**Issue by adamwoodnz** [uikit/uikit#1915]
**Steps to reproduce**
- focus the activating element by using the tab key
- press spacebar/enter/down arrow

**Expected outcome**: the menu opens and the first interactive item is focused
**Actual outcome**: the menu doesn't open

Once the menu has been opened by clicking or hovering (depending on configuration) the enter and space keys do work.

The behaviour of the menu once opened with the keyboard is also not consistent and depends on whether hover or click has been configured. If hover then focus remains on the activating element. If click then the focus moves off the activating element, but not onto the first menu item. In both cases it should move to the first menu item according to the [WAI-ARIA authoring practices for accessible menus](https://www.w3.org/TR/wai-aria-practices/#menu)

Other features missing are:
- using the arrow keys to navigate menu items
- using the escape key to close the menu

Tested on http://getuikit.com/tests/core/dropdown.html and http://getuikit.com/docs/dropdown.html using latest Chrome and Firefox ESR

**Comment by leik** [comment]
We also notices this issue. Our workaround is to use JavaScript to construct. 
```
UIkit.dropdown(SOME_DOM_NODE, {
       mode: 'click'
});
```
It's been handy and convenient to only use the data attributes to initialise though.

**Comment by leik** [comment]
We also found another accessibility issue while testing this widget using screen readers. It manages to change the aria attributes on the wrapper level DOM which are not picked up by screen readers, instead the relevant aria attributes should be applied onto trigger element and the div.uk-dropdown element.

BTW in IE11, it looses focus back to the first focusable element on the page when the dropdown menu is expanded.

**Comment by adamwoodnz** [comment]
Related to @leik's comment above: the aria attributes on the dropdown wrapper generate severe accessibility warnings in the Chrome devtools accessibilty audit tool.
![screen shot 2016-07-19 at 3 18 32 pm](https://cloud.githubusercontent.com/assets/1017872/16937593/793e8a64-4dc4-11e6-80c3-436820fb29a0.png)

**Comment by aheinze** [comment]
some work is done in the current dev branch to optimize the behaviour

**Comment by adamwoodnz** [comment]
Great! Look forward to seeing it. If you need help with code review or behaviour please let me know. Orion Health would be happy to help.

**Comment by adamwoodnz** [comment]
Update: the recent work undertaken has fixed the first issue of activating the menu with enter/space.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
