### ISSUE TITLE
Dynamically change tooltip cls & Add Feature

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#1916]
Hey, looking for a way to dynamically change the tooltip background-color during email validation

```
function checkEmail(email) {
  var reg = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
  if (email.value.match(reg)) {
    email.setAttribute("data-uk-tooltip", "{cls: 'app-tooltip-valid’}");
    email.setAttribute("title", "Email valid!");
    return true;
  } else {
    email.setAttribute("data-uk-tooltip", "{cls: 'app-tooltip-error'}");
    email.setAttribute("title", "Invalid email!");
  }
}
```

Unfortunaltely class does not change once applied. Any help would be appreciated

BTW it could be nice to have the ability to choose click or hover mode (like for Dropdown). In [input example](http://getuikit.com/tests/components/tooltip.html), tooltip appears on hover then re-appears on click which not nice. And for form use case click mode seems better way to display tooltip.

**Comment by whitelynx** [comment]
In response to your second suggestion, I think it'd be best for it not to ever re-play the "show" animation if the tooltip is already shown, but that's probably best to put in a separate issue.

**Comment by Landish** [comment]
@gregBerthelot I had the same problem and I solved it with @whitelynx 's solution:

```
UIkit.tooltip('.your-tooltip-selector').show();
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
