### ISSUE TITLE
Feature Request: Show calendar week in Datepicker component

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#1917]
Customer wants to see the calendar week in the datepicker. Is this much effort to include?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Datepicker component has not been released yet but we are working on that, it might be added there, please check this when it is released :)

Thanks for your understanding,
Your UIkit Team
