### ISSUE TITLE
uk-icon link is not aligned without text (Version 2.26.3)

### ISSUE THREAD

**Issue by Akaris1973** [uikit/uikit#1919]
Hi guys, the icon is not aligned correctly on the on the link version of a button when no text is entered.

![bildschirmfoto 2016-06-15 um 15 53 31](https://cloud.githubusercontent.com/assets/19953303/16082373/55b2d794-3311-11e6-965b-3cf10040540b.png)

![bildschirmfoto 2016-06-15 um 15 53 16](https://cloud.githubusercontent.com/assets/19953303/16082383/5ddada3e-3311-11e6-83c8-23b25dc43977.png)

Any idea for a quick hand fix? :)
Thanks & Best Ralf

Just seen that the line-height is 1 instead of 23.

**Comment by C-Lodder** [comment]
Working perfectly fine for me on my own website and the officicial UIKit site when I inject the HTML you provided.

Tested on FF and Chrome

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
