### ISSUE TITLE
Mozilla Browser Dropdown Hover Does Not Work

### ISSUE THREAD

**Issue by bariskrdrl** [uikit/uikit#1920]
http://getuikit.com/docs/dropdown.html 

mouse hover on dropdown not working.

**Comment by hansnolte** [comment]
Works for me.

Win 7
Firefox 47

**Comment by zzseba78** [comment]
Works for me, OSX El Capitán, Firefox 47.0

**Comment by C-Lodder** [comment]
@bariskrdrl - What version of FF? I'm using 48-beta and have the same issue as you.

**Comment by bariskrdrl** [comment]
@C-Lodder Me and my friend's version of mozilla 47.B'm not working on my browser, but you do not have problems in its browser.All plug-ins are closed this problem is gideremedim.b my friends also experienced the same problem.

**Comment by nathangustafson** [comment]
Is there a nested dropdown by any chance?

**Comment by bariskrdrl** [comment]
no. I do not understand the problem. In the dropdown menu in the UIKit s hover site does not work.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
