### ISSUE TITLE
Keyboard input text

### ISSUE THREAD

**Issue by VictorDeBlas** [uikit/uikit#1921]
Maybe it's a stupid question...

Is it possible to set the date with the keyboard and have the same behaviour than with the click event? 

Thanks!!!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
