### ISSUE TITLE
Uploader - Since i'm not a developer...

### ISSUE THREAD

**Issue by inseldesign** [uikit/uikit#1922]
Hey there,

has somebody an working example for the drag'n'drop uploader? Not only the JS also the "action" which is triggered after file is uploaded? Would be great. I found nothing in the world wide web about it.

Cheers
Sascha

**Comment by C-Lodder** [comment]
This is what I have used (basic concept):

**Html:**
```
<div id="upload-drop" class="uk-placeholder uk-text-center">
	<i class="uk-icon-cloud-upload uk-icon-medium uk-margin-small-right"></i>
	Drag and drop a file or 
	<form class="form" action="" method="post" enctype="multipart/form-data">
		<a class="uk-form-file">select one<input id="upload" name="upload" type="file"></a>
	</form>
</div>
<div id="progressbar" class="uk-progress uk-hidden">
	<div class="uk-progress-bar" style="width: 0%;">...</div>
</div>
````


**JS:**
```
<script>
	$(function() { 

		var progressbar = $('#progressbar'),
		bar         = progressbar.find('.uk-progress-bar'),
		settings    = {
		
			action: 'http://example.com/upload.php',
			
			allow : '*.(html)',
			
			loadstart: function() 
			{
				bar.css('width', '0%').text('0%');
				progressbar.removeClass('uk-hidden');
			},

			progress: function(percent) 
			{
				percent = Math.ceil(percent);
				bar.css('width', percent+'%').text(percent+'%');
			},

			allcomplete: function(response) 
			{
				bar.css('width', '100%').text('100%');
				
				setTimeout(function()
				{
					progressbar.addClass('uk-progress-success');
				}, 500);			
			},
			
			error: function(response)
			{								
				progressbar.addClass('uk-progress-danger');
				bar.text('error');							
			}
		};

		var select = $.UIkit.uploadSelect($('#upload'), settings),
			drop   = $.UIkit.uploadDrop($('#upload-drop'), settings);
			
	});
</script>
````

Then in your `upload.php` file, you can find script anywhere on the web. When testing the upload, be sure to have your browser's developer toolbar open to check for console log errors.

**Comment by inseldesign** [comment]
Ok since i'm not a developer, i need also some hint in php. The upload seems to be working but the $FILE in the PHP is empty. The documentation with the html and js code is good and i can work with but i can't get the point why the $FILE array is empty in the php file. Therefore it would be could to have a working example with HTML, JS and PHP (or what else) file. :-)

**Comment by C-Lodder** [comment]
Please ask your question on Stackoverflow

**Comment by inseldesign** [comment]
OK.

**Comment by C-Lodder** [comment]
@inseldesign - Reason why I suggested Stackoverflow:

1. This isn't really the sort of place to be asking this
2. Stackoverflow is a brilliant website where you'll get **much** more attention ;)

**Comment by inseldesign** [comment]
That's ok. But a i am able to read the documentation your answer (which nearly was the code out of documentation) was not helpful. But thanks anyway. A good answer could also be: "Please ask god and pray." or something like that ;-)

**Comment by azjezz** [comment]
maybe its too late, but here's a testing script, may be useful for future viewers.

**_NOTE: THIS SCRIPT IS FOR TESTING ONLY DON'T USE IT ANYWHERE OUTSIDE LOCAL-HOST , ITS NOT SECURE , ANYONE CAN UPLOAD ANYTHING TO YOUR SERVER INCLUDING PHP FILES THIS IS FOR TESTING ONLY INSIDE A CONTROLLED ENVIRONMENT_** 

```php
if(!isset($_FILES['upload']) {
   echo 'error';
   die(0);     
}

file_put_contents('uploaded/'.$_FILES['upload']['name'],$_FILES['upload']['tmp_name']);

echo 'uploaded';
die(1);
```
