### ISSUE TITLE
Bullets in list placed inside uk-column-* not shown correctly.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#1923]
The bullets in a ul or ol list placed inside css3 columns are not display correctly in some browsers ( Chrome, Safari ).
Possible fix:
ul,
ol {
  **list-style-position: inside;**
}

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
