### ISSUE TITLE
data-uk-button-radio attribute causes button click event fires twice

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#1926]
Adding `data-uk-button-radio` to a button group causes the first click event to be fired twice.

Here's the link to a test page.
https://jsfiddle.net/robtrem/oLz9o61p/

**Comment by miladmeidanshahi** [comment]
try this code

``` 
$('.uk-button-group button').each(function(i, button) {

	$(button).one('click', function() {
	
		$('#console').val($('#console').val() + $(this).text() + '\n');
	
	});

}); 
```

**Comment by robertotremonti** [comment]
@miladmeidanshahi Your code works for a single click on each button. Once you click a button, event is removed.
So no, that's not a solution.

Anyway the problem is within UIkit not jQuery code. If you remove `data-uk-button-radio` attribute, the code works correctly.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
