### ISSUE TITLE
Add classes to table element with mixins

### ISSUE THREAD

**Issue by gmmedia** [uikit/uikit#1927]
Hello,
I try to add the classes uk-table and uk-table-striped to the table element, using LESS mixins.

```
table {
    .uk-table;
    .uk-table-striped;
}
```

It is not working for me. Should it work?

I am using the Beans Wordpress Framework, which is using uikit.

thank you
Jochen

**Comment by miladmeidanshahi** [comment]
As I know about that you can't add class in less & scss in mixins

**Comment by gmmedia** [comment]
But the less documentation is showing exactly that: http://lesscss.org/features/#mixins-feature

**Comment by miladmeidanshahi** [comment]
@gmmedia this article shows that you can extend defined class not new class you can call it as ``` extend ``` in less & sass

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
