### ISSUE TITLE
No spoilers in Markdown?

### ISSUE THREAD

**Issue by afuno** [uikit/uikit#1931]
Does not work:
```
>! this
```

http://stackoverflow.com/editing-help#spoilers

How to add spoilers?

**Comment by florianletsch** [comment]
Markdown rendering is done by marked.js which is only used by uikit, but it is a separate project. You could request the feature there: https://github.com/chjj/marked

However, I don't think spoilers are part of the implemented markdown specification, they are probably only added by stackoverflow for their needs.

But checkout the _marked_ project, maybe there is an easy way to add additional syntax features easily, I am not familiar with the project.
