### ISSUE TITLE
Button text is very small now

### ISSUE THREAD

**Issue by btrscott** [uikit/uikit#1932]
Button text seems to have gotten very small.  Font size is now set as 1 rem.  This is especially noticeable if I'm mixing in some rails native buttons where the text size is much larger.

I thought using rem's was going to be delayed until uikit version 3 but I am using 2.26.3

<img width="192" alt="screenshot 2016-06-24 11 25 13" src="https://cloud.githubusercontent.com/assets/798434/16363004/ce74ebe6-3b8a-11e6-906b-061996f1a2d4.png">

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
