### ISSUE TITLE
What caused this error to Dynamic Grid?

### ISSUE THREAD

**Issue by afuno** [uikit/uikit#1933]
Screenshot: https://habrastorage.org/files/286/a6a/15f/286a6a15f5c348b5a5cb6fa5b1177b96.png

When moving to the next page (for example, on page 3), the dynamic grid breaks down.

```
$(document).on "page:change", ->
    grid = UIkit.grid('#js-names-list', {
        gutter: 20
    })
    return
```

```
<div id="js-names-list">
    <% @names.each do |name| %>
        <div class="uk-width-small-1-2 uk-width-medium-1-4">
            <figure class="uk-overlay">
                <img src="<%= name.cover.small %>" width="" height="" alt="<%= name.full_name %>">
                <figcaption class="uk-overlay-panel uk-overlay-background uk-overlay-bottom">
                    <!-- -->
                </figcaption>
                <%= link_to '', name_path(name), class: 'uk-position-cover' %>
            </figure>
        </div>
    <% end %>
</div>
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The DynamicGrid component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
