### ISSUE TITLE
datepicker doesn't work on mobile

### ISSUE THREAD

**Issue by eleumas** [uikit/uikit#1934]
Datepicker doesn't work on mobile on android 6 with Google Chrome and Samsung Note 4 with android 6 and browser stock.

**Comment by rknonchalance** [comment]
How did you insert the datepicker on the page? Just curious. In my case it technically works but it has another issue of easily disappearing when you click to change the month or year or just simply clicking the textbox input.

**Comment by eleumas** [comment]
@rknonchalance i have the same issue! :(
I have tested this code (https://github.com/uikit/uikit/blob/v2.26.4/src/js/components/datepicker.js), but for me hasn't work. The problem isn't solved.

Can you try and write me your feedback? Thanks.

**Comment by rknonchalance** [comment]
Hey! Sorry if it's been a while. What happened? I haven't bothered fiddling with the DatePicker code yet (I wonder if I'd actually find the issue either for mobile lol), so I decided I would have no choice but to let it be as it is and notify mobile users instead that they have to type the date. I sincerely hope this issue gets fixed though.

**Comment by slackerzz** [comment]
Since Android and iOS provide a datepicker, maybe in mobile we could switch to a standard `<input type="date" ...>`disabling the uikit datepicker. This can allow the browser to use the built-in date picker
What do you think?

**Comment by wesleycsj** [comment]
I'll try to look about this. Maybe datapicker.js don't have support to mobile, maybe in framework code is possible to set this automatically, setting to run it as native in mobile and handling the datepicker.js on desktop.

**Comment by wesleycsj** [comment]
I think that found the problem,it's because in datepicker.js has a 'mobile' property setted as false. I will do a test if setting it to true it will work fine on mobile.

**Comment by eleumas** [comment]
@wesleycsj have you tried? it work if set on: true?

**Comment by wesleycsj** [comment]
@eleumas I'll try....because i have a bug that datapicker work but don't renderize correctly, i think that is some problem on css. i don't know exatly what.

**Comment by wesleycsj** [comment]
Ok, I made some fixes and now datepicker.js is working without triggering a native keyboard after a touch, I have no glitches after that fix like i had before. Mobile support is default, all what you need is to set normally the component. My PR is #2080

I'm using Android 4.4 with Firefox 48.0

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
