### ISSUE TITLE
Bug slider.js

### ISSUE THREAD

**Issue by jack-theripper** [uikit/uikit#1935]
Hi. Problem with duplicating of slides on devices with screens of different width.
I use chain of classes "uk-grid-width-*" (values "-1-6" or "-1-10" generate more duplicate).
I made an example [http://codepen.io/dmitryarhitector/pen/OXpQEN](http://codepen.io/dmitryarhitector/pen/OXpQEN) and I tried to explain a problem.

This plug-in works correctly? Thanks!

**Comment by zzseba78** [comment]
Hi! I think the good place for ask this is here:
https://gitter.im/uikit/uikit
If you apply this it fixes this problem `data-uk-slider="{infinite:false}"`
But, if you want 4 items per row, but if you have only 2 elements to show, the desired behavior would be only show those two, and not repeat them. It looks like an error.

**Comment by jack-theripper** [comment]
@zzseba78, thanks for the reply
