### ISSUE TITLE
How to handle multiple stickys so they group together at the top instead of covering over each subsequent sticky

### ISSUE THREAD

**Issue by starbuilder** [uikit/uikit#1936]
Im looking to group two stickys together which are separated by some elements on the page so that each  one stays on the page. For instance, I have a header which contains my logo and top level navigation and slideshow beneath it, then another div which contains subnavigation beneath that. I want both the header and subnavigation to be sticky but since they are separated by the slideshow I cant make their parent div sticky. when I try to make each element sticky, the bottom one covers up the top one which is my logo and I want to keep that on the page all the time.

**Comment by kelsh** [comment]
this is pseudo code but:
elTwo top offset = elOne.offset().top + elOne.height()

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
