### ISSUE TITLE
Offer: Off-canvas without the shift of content

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#1939]
optionally, it would be convenient
like
![image](https://cloud.githubusercontent.com/assets/16114000/16492362/2c04889a-3eea-11e6-9356-0be75a91e5d0.png)

**Comment by zzseba78** [comment]
I think it will be rewrited in v3

**Comment by kelsh** [comment]
you can just do .uk-offcanvas-page{
margin-{whichever side the theme does}:0 !important
}

**Comment by philoest** [comment]
This has been added to the [Off-Canvas Component in UIkit3](https://getuikit.com/docs/offcanvas#animation-modes), here you can choose the different modes like: slide, push, reveal and none.

Thanks for your understanding,
Your UIkit Team
