### ISSUE TITLE
Problem on grid.js

### ISSUE THREAD

**Issue by clementhadrot** [uikit/uikit#1943]
Hi,

I have a problem with dynamic grid. 
I need make a sub menu width dynamic grid. 

You can show the result here : http://www.vessiere-cristaux.fr/

My sub menu "Nos produits" not working on MacOs.

Have you a idea?  
Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The DynamicGrid component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
