### ISSUE TITLE
how to use the navigation buttons instead of the scroll bar?

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#1947]
Hello, is it possible to do this for a

```
<div class="uk-panel uk-margin-small-right uk-margin-small-top uk-overflow-container" style="height: 250px">
  <!--ul class="uk-nav uk-nav-side" data-uk-switcher="{connect:'#<?=$value["ID"].'-product-info'?>'}"-->
  <ul class="uk-list uk-list-striped" data-uk-switcher="{connect:'#<?=$value["ID"].'-product-info'?>'}">
    <?foreach($value["PRODUCTS"] as $key1 => $value1){?>
      <li class="">
        <a href="#" class="uk-icon-caret-right"> <?=$value1["NAME"]?></a>
      </li>
    <?}?>                                                           
  </ul>
</div>
```

instead of scroll bars (uk-overflow-container) to display the portion (for example, as data-uk-slideset="{default: 5}") of the list rows + navigation buttons (uk-pagination or uk-slidenav) for vertical scrolling list
(as the picture)
![image](https://cloud.githubusercontent.com/assets/16114000/16586491/dfb8de30-42ce-11e6-8fa1-aa00c50c89f7.png)
if can do... - please, show an example
?
ps
Version 2.26.3

**Comment by AlexandreZaytsev** [comment]
comment
the list is generated (for example 25 rows), I show the first 5 rows, then the buttons to scroll to the next 5 rows etc. (4 of iteration here, then in a circle)...

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
