### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#1952]
I noticed a responsive menu is based on a side panel (uk-offcanvas). Is it possible to have a normal repsonsive menu like we see inside bootstrap? Like a toggle/accordion of some sort?

Kind regards, 
Kiarashi

**Comment by arrowthemes** [comment]
Kiarashi,

You can easily achieve that with the [toggle](http://getuikit.com/docs/toggle.html) and [nav](http://getuikit.com/docs/nav.html)

**Comment by kiarashi** [comment]
Care to share an example?

My code is as follows:
```
<nav class="uk-navbar">
<a href="#mobile" class="uk-navbar-toggle uk-hidden-large"></a>
<?php wp_nav_menu(array('... 'items_wrap' => '<ul class="uk-nav uk-nav-parent-icon" data-uk-nav="{multiple:true}">%3$s</ul>' ));  ?>
</nav>
```

**Comment by entonbiba** [comment]
Something like this?

<a href="http://codepen.io/entonbiba/pen/kXdWPy">preview</a>

````
<button class="uk-button" data-uk-toggle="{target:'#toggleNavBarID'}">View NavBar</button>

<div id="toggleNavBarID">
  <nav class="uk-navbar">
  <a href="#mobile" class="uk-navbar-toggle uk-hidden-large"></a>
  <?php wp_nav_menu(array('... 'items_wrap' => '<ul class="uk-nav uk-nav-parent-icon" data-uk-nav="{multiple:true}">%3$s</ul>' ));  ?>
  </nav>
</div>
````

**Comment by kiarashi** [comment]
Doesn't quite work the way I'd like it to be. 
If used like that, I need to add two `wp_nav_menu` (one for the smaller screens which will be a toggle and one for desktop sizes where it will simply be a uk-navbar)

Is there no `navbar-collapse` option as seen in Bootstrap inside UIkit?

**Comment by entonbiba** [comment]
are you trying to achieve something like this with uikit? http://getbootstrap.com/components/#navbar-default

**Comment by kiarashi** [comment]
Yes, that's right. 

The UIkit menu should automatically become a dropdown menu on smaller screens, just like we see inside bootstrap. 

So far this option doesn't seem to be automatically present inside the UIkit framework. 
Right now there's only two solutions I could think off; 
1. Creating two menus; one with `uk-navbar-nav` and the other with `uk-nav`. And then using the responsive visibility classes.
2. Or using additional jquery code to switch classnames depending on the screen resolution.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by hkalexling** [comment]
I think using [responsive visibility](https://getuikit.com/docs/visibility#responsive) + [off-canvas nav](https://getuikit.com/docs/offcanvas#nav-in-off-canvas) is the best solution for this.

Here's what I end up with (in pug):

```pug
.uk-offcanvas-content
	.uk-navbar-container.uk-navbar-transparent(uk-navbar)
			#mobile-nav(uk-offcanvas='overlay: true')
				.uk-offcanvas-bar.uk-flex.uk-flex-column
					ul.uk-nav.uk-nav-primary.uk-nav-center.uk-margin-auto-vertical
						li#ideas-item
							a(href='#') Home
						li#about-item
							a(href='#') About

.uk-position-top
	.uk-navbar-container.uk-navbar-transparent(uk-navbar)
		div(class='uk-navbar-left uk-hidden@s')
			.uk-navbar-toggle(uk-navbar-toggle-icon uk-toggle='target: #mobile-nav')
		div(class='uk-navbar-left uk-visible@s')
			ul.uk-navbar-nav
				li#ideas-item
					a(href='#') Home
				li#about-item
					a(href='#') About
```

**Comment by MilenFrom** [comment]
Thanks for sharing Ankur, your code did the job for me.

**Comment by tech-tt** [comment]
See my experience here https://thetechremix.com/2018/01/19/uikit-collapsible-and-toggle-dropdown-menu-on-mobile/

**Comment by frumbert** [comment]
@tech-tt and @hkalexling  - in both these solutions  you are recreating all the menu items twice. Probably ok when there's only a few items. More problematic when the nav items have dropdowns.

**Comment by tech-tt** [comment]
@frumbert I want to agree with you. Does it not show properly? Any suggestions how to avoid this? I will make a note to test this out myself.
