### ISSUE TITLE
Error in swipe effect.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#1955]
The swiper effects have a black overlay that animate over the image that is behind giving a shadow effect transition. This overlay effect it´s not animated anymore after all images are viewed and the new cycle of repeated images begin, the overlay just shows and dissapears without animation.
You can see this behavior here: http://getuikit.com/docs/slideshow.html#animations
Swipe transition.

**Comment by anybany** [comment]
Hi, i've got a similar error with the slideshow animation "swipe".
you can see it here: http://athletia.net/ on the left side.
the image "swipes" down but the next image "jupms" right in. it appears to be some kind of flickering. 
Can anyone please help me with this? i dont know what to do...
I only changed direction.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
