### ISSUE TITLE
small domObserve documentation error

### ISSUE THREAD

**Issue by rolfboom** [uikit/uikit#1957]
As I understand from the [domObserve](http://getuikit.com/docs/documentation_javascript.html#dom-observe) documentation, I can do:
`UIkit.domObserve('#element', function(element) {console.log('observed element:', element);});`

But as I found in your your [master branch](https://github.com/uikit/uikit/blob/master/src/js/core/core.js#L607), I can only do:
`UIkit.domObserve('#element', function() {console.log('observed element:', this);});`

**Comment by aheinze** [comment]
fixed in the dev branche, thanks!
