### ISSUE TITLE
data-uk-button-checkbox attribute doesn't work with label

### ISSUE THREAD

**Issue by Ilya-Zhulin** [uikit/uikit#1958]
Good day everybody!
I see `data-uk-button-checkbox` attribute is to show checkboxes like a buttons. It works but a little bit strange. Normally, checkbox field contains of label and input. I tried to use it in variants:
1) Label.uk-button warps input - in one click we click input and label - input is checked but label hasn't class `uk-active` and `area-checked="false"`
2) Label.uk-button before or after the input - after first click label has class `uk-active`, `area-checked="true"`, but input isn't checked. Since second click label and input changes their state but on the contrary - label is active but input isn't checked.
3) label with input.uk-button - it works good, but I can't place ;abe; on input to looks loke button.
Please, I see that behaviour need a little bit correction - it's almost good - can you finish it to be understandable?
You can play with it here
http://codepen.io/Ilya_Zhulin/pen/VjAxyk

Thank you!

**Comment by miladmeidanshahi** [comment]
same issue

**Comment by Ilya-Zhulin** [comment]
Hello, everybody!
Is it bug or feature?

**Comment by Ilya-Zhulin** [comment]
Also, after page reload I need to click to first checkbox twice. After first checkbox checked it works good. Please pay a little bit of your attention to this attribute.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
