### ISSUE TITLE
jquery 3.0

### ISSUE THREAD

**Issue by brody182** [uikit/uikit#1959]
is uikit jQuery v3.1.0 Ready?

**Comment by arysom** [comment]
Upload, progress, offcanvas, accordion components seem to work from my experience.

**Comment by arrowthemes** [comment]
Version 2.26.4 fixed issues with jQuery 3 compatibility. I'm using the latest version with jQuery 3.1.0 and haven't noticed any issue. As always, you can always hit the devs up incase you notice something amiss.
