### ISSUE TITLE
Error with Off-canvas and Sticky

### ISSUE THREAD

**Issue by afuno** [uikit/uikit#1963]
It's about navigation.

If navigation is at the top in the standard form, then all is well: [Screenshot 1](https://habrastorage.org/files/911/7cf/aae/9117cfaae8f843bdb0ebaa1d2558fad2.png)

But if you add Sticky navigation and go down the page, the ugly things happen: [Screenshot 2](https://habrastorage.org/files/833/1a0/893/8331a089333f4c7f9ccbe793535fc719.png)

I will explain what is happening. The second screenshot Off-canvas navigation does not shift to the right. This is slightly unpleasant moment...

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
