### ISSUE TITLE
Update Instagram FontAwesome icon on 

### ISSUE THREAD

**Issue by jayagonoy** [uikit/uikit#1964]
Hi, 

The FontAwesome pack that UIKit has is an outdated version of Instagram. I'd like to file a minor issue for the font icon pack that we have to be updated. [Here are other icons that are added in version 4.6](http://fontawesome.io/icons/).

Thanks!

**Comment by joshgilson** [comment]
+1

**Comment by aheinze** [comment]
done in dev branche
