### ISSUE TITLE
Uikit Datepicker Month and Year appearance

### ISSUE THREAD

**Issue by badcoder28** [uikit/uikit#1965]
Hello, I can't understand why this is happening to me.

![untitled](https://cloud.githubusercontent.com/assets/20513403/16911686/8831e140-4d12-11e6-8755-1ef68987a5a6.png)

**Comment by ahallicks** [comment]
It looks like you don't have the form select component styles:
http://getuikit.com/docs/form-select.html

The second paragraph here explains about it http://getuikit.com/docs/datepicker.html#usage

**Comment by badcoder28** [comment]
Oh! You are right this solved my problem i did checked both my styles and scripts

I include this:
```
css/uikit.almost-flat.min.css
css/components/datepicker.almost-flat.min.css
css/components/form-select.almost-flat.min.css
```
Big help thanks a lot
