### ISSUE TITLE
[bug] occur error when load the latest version of upload component

### ISSUE THREAD

**Issue by beisu** [uikit/uikit#1966]
![image](https://cloud.githubusercontent.com/assets/11241488/16912986/42d162f8-4d1a-11e6-958b-ece47fd05199.png)
![image](https://cloud.githubusercontent.com/assets/11241488/16912992/4fa34cbc-4d1a-11e6-9ab5-e2ab104a0f83.png)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
