### ISSUE TITLE
Slideshow component index/current/next bug?

### ISSUE THREAD

**Issue by stell** [uikit/uikit#1967]
Check this fiddle out:
https://jsfiddle.net/Honkoman/vmj8ekyc/4/

When combining next/prev buttons with manual slide switching there seems to be a problem.
For example two slides are active ("uk-active") at the same time.

**Comment by aheinze** [comment]
I updated you code to work correctly: https://jsfiddle.net/vmj8ekyc/9/

**Comment by stell** [comment]
Hey thanks for the help, but it's not exactly what i needed. I simplified the example, so some deeper logic is gone.
I need to switch when hovering based on the li sibling order, not the oid value. Thats why i used the index. The data-oid value can be every possible number.

**Comment by aheinze** [comment]
```UIkit.slideshow(UIkit.$('.uk-slideshow'))``` you've selected the wrong element. the js object is always on data-uk-* elements

**Comment by stell** [comment]
Of course. Thanks Artur!
