### ISSUE TITLE
Navbar .uk-parent class. Parent indication.

### ISSUE THREAD

**Issue by truetamtam** [uikit/uikit#1968]
Navbar .uk-parent class.
Seems to be no indication, that menu item is a parent, and has items in it.
Observable in docs.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
