### ISSUE TITLE
Nav list navigation. First link is unreachable.

### ISSUE THREAD

**Issue by truetamtam** [uikit/uikit#1969]
First link is unreachable in nav list navigation.
Should be like 
| link to | ^ |

I mean expander is separate from link.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
