### ISSUE TITLE
Lightbox: request complete example!

### ISSUE THREAD

**Issue by stetod** [uikit/uikit#1970]
Hi,
I do not have great programming experience. I wish I could make a Lightbox.
Precisely I'd link multiple images to the same lightbox and switch between them from within the lightbox, thus creating a gallery. 
I understand the general logic but not having a complete example of html and javascript I can not create my example.
Would you be so kind as to create one, many programmers to help beginners like me?
Thank you

**Comment by zzseba78** [comment]
Here you have an example of a thumbnail gallery and lightbox grouped images with navigation
https://uikitplay.com/plays/FXsR

And here is the place where uikit developers chat:
https://gitter.im/uikit/uikit

Hope this help

**Comment by stetod** [comment]
Thanks a lot! It was what I was looking!!!

Stefano Todaro
Instructional Designer Unconventional
www.4mareciak.it


Date: Fri, 22 Jul 2016 06:24:34 -0700

**Comment by zzseba78** [comment]
Glad it helps.
Please close the issue.
