### ISSUE TITLE
How to close the offcanvas with animation via javascript

### ISSUE THREAD

**Issue by freedomlang** [uikit/uikit#1971]
I've read the document, but it doesn't help at all! I tried the code below, the offcanvas just close without animation.
```
UIkit.offcanvas.hide('#my-id');

UIkit.offcanvas.hide([force = false])
```

**Comment by dobaniashish** [comment]
The default `UIkit.offcanvas.hide([force = false])` did not work properly for me too. So here is an alternative jquery approach. Just trigger a click on your offcanvas.

`$( "#my-id" ).trigger( "click" );`

Hope this helps.

**Comment by freedomlang** [comment]
It works, thanks!

**Comment by brbaso** [comment]
UIkit.offcanvas.hide([force = false]) still does not work  (2018 !) ...
Thanks for alternative
