### ISSUE TITLE
uk-table body scroll and fixed header when row items overflow

### ISSUE THREAD

**Issue by badcoder28** [uikit/uikit#1972]
Is there any feature for `uk-table` when the row items is overflowing in the parent content then the vertical scrollbar appears and the header is fixed when scrolling the body content?

Here is the [link](http://www.cssplay.co.uk/menu/tablescroll.html) of an example and i want it to look like the **method 2**.

**Comment by ahallicks** [comment]
There is nothing built into uikit for this, as far as I know, but it's pretty custom and very simple to implement.

Have a look at the source code. All Stu has done is wrap an inner table in a div, given it a height and added `overflow: auto`.

**Comment by badcoder28** [comment]
It would be great if uikit add this stuff in the future. I guess i have to do your suggestion. well thanks.

**Comment by RyanSusana** [comment]
Hello guys is this possible?
