### ISSUE TITLE
Dynamic Grid doesn't work with v 2.26.4

### ISSUE THREAD

**Issue by agneseragucci** [uikit/uikit#1973]
I've successfully used grid.min.js (v 2.26.3) to implement the dynamic grid in a project. Once updated to 2.26.4 it stops working properly. All the items were displayed in a single column.

**Comment by C-Lodder** [comment]
Have you tried clearing your browser cache? Works fine on their [Docs](http://getuikit.com/docs/grid-js.html) page so will work with 2.26.4

**Comment by agneseragucci** [comment]
Yep! I've also tried on a brand new project. Once changed with the previous version, everything starts working properly.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The DynamicGrid component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
