### ISSUE TITLE
Slideshow not working when DOM is changed through ng-repeat on AJAX call

### ISSUE THREAD

**Issue by anushac243** [uikit/uikit#1974]
Hi,

I am using `ng-repeat="imgObj in imgList` to populate the `<li>` objects in my DOM. The first load is not an issue at all. But after receiving certain input, I change `$scope.imgList` from an AJAX call and then the slideshow stops working. 

I've tried the following steps:
1. Re-initialized using `var slideshow = UIkit.slideshow("div#imgSlideShow");`
2. Added `data-uk-check-display`
3. Added `data-uk-observe`
4. Added `UIkit.domObserve('#imgSlideShow', function(element) {
		var slideshow = UIkit.slideshow("#imgSlideShow");
	});` to my JS

None of them have worked. Been working on this for weeks now and haven't been able to crack it. Posting it here as a last ditch effort - Please help!

**Comment by aheinze** [comment]
should work in dev branche, thanks!
