### ISSUE TITLE
Tabs with .show() Function

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#1976]
I have to implement Tabs functionality and did it with the Switcher-Version, which has a .show() function I use to call the tabs from a url-hash. We now need to enable the responsive behavior of the Tabs-Version, which seems to lack this .show() functionality. Could eihter the responsive behavior beimplemented in the switcher or the .show() functionality be implemented in the tabs in future releases?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
