### ISSUE TITLE
Stackable Modals

### ISSUE THREAD

**Issue by zhaoyao91** [uikit/uikit#1978]
I have tried to call another modal while some is opened, the effect is, new one is opened, but the old one dismisses. this mean that for uikit, only one modal can be shown at a time.

How about support stackable modals? e.g. while some is opened, another one can be opened over the old one, and the close order is FILO.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
