### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by zhaoyao91** [uikit/uikit#1979]
uikit has great sticky navbar, why not include a sticky footer?

**Comment by peterbrinck** [comment]
You can use the sticky component on all elements
It doesn't have to be on the navbar

The docs are here: http://getuikit.com/docs/sticky.html

**Comment by zhaoyao91** [comment]
@peterbrinck the sticky component can only sticky to top, but sticky footer should have different effect.

here is my workaround

```
// app-layout.js
const AppLayout = props=> {
    const {content} = props;
    return <div className="app-layout">
        <header>
            <AppBar/>
        </header>

        <main>
            {content}
        </main>

        <footer>
            <AppFooter/>
        </footer>
    </div>
};
```

```
// app-layout.scss
.app-layout {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  main {
    flex-grow: 1;
  }
}
```

**Comment by arrowthemes** [comment]
+1

**Comment by jerry1970** [comment]
@peterbrinck 's answer is not enough, the docs don't tell us how to stick to the bottom of the page/viewport. If it's possible it's a limitation of the documentation, but a working example would be nice.

**Comment by briandk** [comment]
+1

**Comment by philoest** [comment]
I will close this, there is already a feature request ( #1121 ) please follow up there to get the news regards the sticky footer.
