### ISSUE TITLE
arrows in lightbox gallery 

### ISSUE THREAD

**Issue by breakeur** [uikit/uikit#1981]
Hi,

I'm a beginner in web coding and i'm trying to do a gallery with lightbox.
so far so good everything is okay but my issue is when i open images from the gallery i can't find how to put the navigation arrows appear, i followed the example made here :

https://uikitplay.com/plays/FXsR

and still can't find out what i'm missing, if someone can help me on this it would be really kind !

Thanks !

**Comment by arysom** [comment]
embed slidenav in your code

**Comment by breakeur** [comment]
I've had it from the beginning but did a stupid error....

<script src="uikit/css/components/slidenav.css"></script>

instead of : 

<link rel="stylesheet" href="uikit/css/components/slidenav.css">

thanks for your help !
