### ISSUE TITLE
Dropdown menu using Multi Columns: Better control over menu items in Columns

### ISSUE THREAD

**Issue by WilkoRietveld** [uikit/uikit#1983]
If you use Dropmenu with options for 3 columns these will be filled automatically this makes ordering impossible if you have 12 items this will be presented as: 4 -4 -4 for UX you might want to order 4 - 3 - 5. 
![schermafbeelding 2016-08-04 om 19 16 52](https://cloud.githubusercontent.com/assets/11089156/17411494/d331072a-5a78-11e6-9327-1d518a83a3ae.png)
![group](https://cloud.githubusercontent.com/assets/11089156/17411549/09d17238-5a79-11e6-9e21-499f27b4e5ae.jpg)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
