### ISSUE TITLE
Sortable and Nestable doesn't work on touch devices

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1984]
The sortable and nestable component doesn't work for touch? devices (testing on mobile phone)
Tested on chrome (all examples does'nt work) and default android browser (some examples works ok, some doesn't works)

**Comment by almibe** [comment]
The demos on the main site work fine for me with Chrome 52 on Android 6.0.1.

**Comment by SaphiLC** [comment]
they dont work (surface pro 2 tablet, windows 10, any browser, not even in the demo page or any woothemes and pagekit)

**Comment by windvlaag** [comment]
I can confirm this for nestable on ipad on the demo page.

Sortable seems to work fine.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
