### ISSUE TITLE
Dynamic Grid does not re-arrange the items in RTL mode

### ISSUE THREAD

**Issue by JoomFX** [uikit/uikit#1985]
Hey guys,

Is it (somehow) the expected behavior or is it a bug?
It really looks like a bug, since the Slideset for example, re-arranges the items in RTL mode.
The Slider also re-arranges the items in RTL mode (after [the fix implemented in 2.26.4](https://github.com/uikit/uikit/pull/1954/commits/2d27f946a69fa546eda096375a747dc208e42523)).

So, it is just the Dynamic Grid that does not re-arrange the items in RTL mode.

All of the above is reproducible with UIKit Customizer as well. Have a look at [this video](https://youtu.be/Hua7KB6Kogo), it shows everything.

Thanks for looking into it!

EDIT: I just found [this issue](https://github.com/uikit/uikit/issues/1803). It was opened more than 4 months ago and nobody has replied to it yet.
Sorry guys, I do not want to push anybody, but I'll ping you on Gitter so I can point your attention to this issue, so you can just drop a quick comment here so we know that you are actually aware of the problem.

**Comment by aheinze** [comment]
Thanks, should be fixed in the dev branch now!

**Comment by JoomFX** [comment]
Thanks a lot for the quick turnaround Artur!
It's really much appreciated :wink:
