### ISSUE TITLE
[bower-uikit] Ember.js and bower-uikit

### ISSUE THREAD

**Issue by bmalum** [uikit/uikit#1986]
Hi, just wanted to file that issue to `bower-uikit` but just saw I have to do it here. 

My problem ist, I would love to use `uikit` with ember-js so I added bower-uikit to the dependencies and imported with `app.import('bower_components/uikit/js/uikit.min.js');` and also the `min.css`. 

I tried to find a solution to get `uikit` but I have now clue why the JS part does not work. 

Anyone solved this?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
