### ISSUE TITLE
Lightbox.js on mobile the "back" button of the phone should close the modal

### ISSUE THREAD

**Issue by Siton-Systems** [uikit/uikit#1987]
In uikit the "back" ===> "go to prev link (real back)" in the url (from page2 to page1). I find this pattern in a lot of lightbox galleries. 

But look at **booking.com** or **ebay, amazon** (some product) or even google images on mobile this is the correct pattern (back = close the modal). 

"THE PROBLEM"::: I find my self a lot of times want to "close" the modal with the "<" arrow of my android and instead back in the URL. 

In desktop anyway you close the modal by the dark overlay (its rare to click "back" in the browser when image zoom) - so this will be 100% solution for all screens.

![download](https://cloud.githubusercontent.com/assets/16711871/17527841/a142dee0-5e75-11e6-8553-f032b9e181d8.png)

**Comment by eblive** [comment]
Something like this will work,


```
// init lightbox element
var lightbox = UIkit.lightbox(element, { /* options */ });

document.addEventListener('backbutton', onBackBtn, false);

function onBackBtn(event) {
    // stop default behaviour
    event.preventDefault();
    
    // close the lightbox
    lightbox.hide();

}

```

I'll submit a pull request for the modal.js file.

**Comment by Siton-Design** [comment]
Thanks i will try - if i install the lightbox by " attributes on HTML element" how i can use this code?....

**Comment by eblive** [comment]
@Siton-Design see above, I've updated the code.

**Comment by Siton-Design** [comment]
**Thanks!!!!!! Its work (no "back").** 
In this code also the "back" close the modal in your phone / broswer ? (in my test its only "not go back")

**Comment by eblive** [comment]
updated and working, check the links above.

**Comment by Siton-Design** [comment]
THANKS A LOT!!!!!!!!! this is the way the modal should react (I hope this idea will merge in the next uikit version. Even as an option). You help me a lottttttttttttttttttttttt :)!!

**Comment by entonbiba** [comment]
@Siton-Design done :)

**Comment by Siton-Design** [comment]
Thanks. Add pull Req :) Very good and useful code. I will now use this in all of my projects. Thanks again!

**Comment by entonbiba** [comment]
@Siton-Design  it now checks for Esc, backbutton, F4 and Delete keys ;)

**Comment by Siton-Design** [comment]
**One more "small bug"** The "back" button is "always" **unavailable** 

(So if you go From A to B and in B you have this code you can not go back). In google searches this is really a problem (The user want to use "back" to go back to search results in desktop and mobile), but also in general (The back is important BTN)
