### ISSUE TITLE
why parallax is adding a background-size larger than the original image or the container?

### ISSUE THREAD

**Issue by newjie** [uikit/uikit#1988]
In the first example of parallax, the container's width is 822px, and the background image's size is 800*400, why is there an inline style "background-size:1223px 612px"? This make the background-image unwantedly scaled. If this is on purpose, how do I stop it?

**Comment by wayneharbar** [comment]
Hi newjie, I had the same problem, I solved it by copying the parallax.min.js file from an older version of uikit, creating a new folder in my project and placing and linking to the old js file. Hope it works for you.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The Parallax component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
