### ISSUE TITLE
Remove core transitions 

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#1992]
Hi @saschadube, @aheinze,

in the core there are transitions hard coded all over the place, like the [Modal ones](https://github.com/uikit/uikit/blob/develop/src/less/core/modal.less#L89). That makes it harder to apply custom transitions or completely remove them.

Transitions are like styles and should not be in the core, reason I am rising this ticket hoping you will agree with. Anyhow thanks for considering.

**Comment by miljan-aleksic** [comment]
I saw dropdown transitions were scoped all under `.uk-open >` and by not using uk-open at all one could set up custom transitions. At least it could become a standard and use the same approach for modal and any other.

**Comment by philoest** [comment]
HI Miljan,
I thinks some of this has been fixed in UIkit3 please let us know in a new Issue if there are still transition which call these problems
