### ISSUE TITLE
@utility-height-viewport-min-height

### ISSUE THREAD

**Issue by mjauvin** [uikit/uikit#1993]
Hello, when I add the _uk-height-viewport_  and _uk-overflow-container_ classes to a div it won't scroll all the way to the bottom and I found that the _uk-height-viewport_ has the following in it's definition:

`min-height: @utility-height-viewport-min-height
`

and **@utility-height-viewport-min-height** is set to 600px but on mobile devices with screen height less than 600px in landscape mode, it prevents scrolling all the way down.

What is the reason for setting the min-height to 600px !?

**Comment by entonbiba** [comment]
@mjauvin yea I noticed the 600px min-height as well, should be 300px or 320px to support landscape mode on mobile devices.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
