### ISSUE TITLE
How to just use almost-flat theme in my web application

### ISSUE THREAD

**Issue by maxpavlov** [uikit/uikit#1996]
I've installed uikit via `bower i uikit` to my assets folder. My application references less files and I already have a decent amount of markup wired up to uikit styling. 

Which is the easiest way for me to switch what I have to almost-flat theme? Thanks.

**Comment by philoest** [comment]
UIkit2 themes are not published via bower, so here you would need to add these from another source. This will change in UIkit3. Here the themes will also be available via bower soon.
