### ISSUE TITLE
Uk-slideshow not visible without JS (SEO/SPEED issue)

### ISSUE THREAD

**Issue by Siton-Systems** [uikit/uikit#1997]
**"The blink problem"** - i want to put the hero slideshow with  google Speed recommends "avoid render-blocking".
https://developers.google.com/speed/docs/insights/BlockingJS

I want the page to load faster - and than load slideshow (after i load the entire html). When i do this i get a "blink" (The first slide is hidden after the JS is loaded the slideshow is visible) .
And/or use: async or defer (performance by google insight).

I think it would be better by default even "without waiting to JS" (jquery + uikit.js + slideshow component) the first slider should be visible and than will play auto and so on (next/prev)

I find this "blink" also in poor connection wifi and/or hi res pics (slow pages).

**Comment by entonbiba** [comment]
@Siton-Design do you have code I can test?

**Comment by Siton-Design** [comment]
First if you disable JS the slideshow will be hidden. 

Look her for example (for really really short time the slider is hidden and than appear)
https://uikitplay.com/plays/FXss

This problem is in most of the slideshow js plugins i test (Again in the past this was not an issue)
