### ISSUE TITLE
Dropdown-Hover works only on Firefox

### ISSUE THREAD

**Issue by guptaghost** [uikit/uikit#2000]
The Dropdown on Hover functionality works only in Firefox. In Chrome, Edge, and IE, the menu works only on click.

Steps to reproduce:
Open the UIKit docs (http://getuikit.com/docs/dropdown.html) in Chrome/IE11/Edge.

**Comment by zzseba78** [comment]
Working for me in Chrome latest.

**Comment by guptaghost** [comment]
![dropdown](https://cloud.githubusercontent.com/assets/7393136/17892491/2e2b23fa-695f-11e6-876f-1d67b3c4fb4b.png)
![chrome](https://cloud.githubusercontent.com/assets/7393136/17892492/2e2d23d0-695f-11e6-8cc1-8ac700f6f90b.png)

That's odd. I've tried on Chrome 52 and have had a few others try it as well, just in case something was wrong in my PC. All of them confirm it works in FF, but not in Chrome/IE11/Edge.

**Comment by zzseba78** [comment]
![captura de pantalla 2016-08-23 a las 10 08 46 a m](https://cloud.githubusercontent.com/assets/5558563/17892862/ba80866a-6919-11e6-90a4-284b3a4cb945.png)
![captura de pantalla 2016-08-23 a las 10 09 10 a m](https://cloud.githubusercontent.com/assets/5558563/17892865/bd323f3e-6919-11e6-86ac-74c449059e57.png)

**Comment by guptaghost** [comment]
looks like it may be a temporary build issue. I downloaded a portable version Chrome in Win10 and the dropdowns dont work in that too. However, when I installed Chromium on Ubuntu (VM), it worked perfectly on that.

Not sure what's going on with their Windows build. Also, the functionality is not working on Edge and IE11.

**Comment by ericboehs** [comment]
I think this may be related to https://github.com/uikit/uikit/issues/2008.

Try my solution there.

**Comment by guptaghost** [comment]
This issue is actually related to #2032 . I later figured out that I was using a touch laptop, and the browser was sending in the device type as a Tablet in the request headers. Which is why it was defaulting to a click-mode instead of hover. Dropdown worked in all the browsers mentioned above inside of VM, which did not have the touch-support.

**Comment by guptaghost** [comment]
Marking the issue as closed, since the component is behaving as intended. It was an issue on my PC.
