### ISSUE TITLE
uk-overlay performance issues

### ISSUE THREAD

**Issue by Rawlings** [uikit/uikit#2002]
The combination of forced hardware acceleration in the overlay component together with multiple highres images causes heavy load to the GPU which results in stutter/sluggishness when scrolling. Perhaps I am not the only one who have noticed this?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
