### ISSUE TITLE
Resizable  column width (with mouse / touch control)

### ISSUE THREAD

**Issue by WilkoRietveld** [uikit/uikit#2004]
In the Apple and MS browser you can resize the width of the columns to gain more width for a text / have more character visible. Would be great to have this function for tables etc with UIKit.
![imgres](https://cloud.githubusercontent.com/assets/11089156/18007934/5cd66b94-6ba6-11e6-95fa-ed7974a1b243.jpg)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This hasn't been added to UIkit3 by default, you would need to use custom JS to add this functionality. 

Thanks for your understanding,
Your UIkit Team
