### ISSUE TITLE
Option for inline tooltips

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#2005]
I think it would better if you could define tooltips as the direct sibling to the data-uk-tooltip via an inline option like so...

``` html
<div data-uk-tooltip="{inline: true}">Foo</div>
<div class="uk-tooltip">Bar</div>
```

That would be much nicer for more complicated tooltips involving html and would play much nicer with frameworks allowing for the utilization of bindings etc.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
