### ISSUE TITLE
2.27.1 bug: dropdown buttons

### ISSUE THREAD

**Issue by joomla-ua** [uikit/uikit#2008]
Please see:
https://www.youtube.com/watch?v=mD-mwAf5-_I

**Comment by ericboehs** [comment]
I think I'm seeing this problem in Poltergeist as well. The dropdown's don't activate when I upgraded from 2.26.4 to 2.27.0.

I did a `git bisect` to find out which commit caused the problem in master. It started with https://github.com/uikit/uikit/commit/98f9e72dc. @aheinze do you have any suggestions to fix this?

**Comment by ericboehs** [comment]
Okay I messed around with the commit and if I remove the word `focus` from line 72, it starts working again.

This repo has enough pull requests and I don't know what breaks when removing that, so I'll let @aheinze deal with fixing it.

**Comment by aheinze** [comment]
on which os/browser do you experience this issue?

**Comment by ericboehs** [comment]
PhantomJS 2.1.1 on macOS Sierra and Ubuntu 14.04.

I'm not sure which browser @joomla-ua is seeing it but it looks modern (supported).

If you're a rubyist, here's a Capybara test that fails https://github.com/uikit/uikit/commit/98f9e72dc but not the commit before:

```ruby
 Capybara.current_driver = :poltergeist
 visit "/"
 click_on 'Menu'
 click_on 'Menu Item'
```

Menu being a `uk-dropdown`.

It will fail to find the "Menu Item" as the dropdown will not expand. This can be confirmed by running `save_screenshot`.

**Comment by zzseba** [comment]
Same problem in Android 6 in Chrome browser.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
