### ISSUE TITLE
datepicker doesn't  allow to change minDate based on other events.

### ISSUE THREAD

**Issue by jeetonweb** [uikit/uikit#2009]
I use 2 datepicker fields normally (checkIn) and (checkOut). I could able to hook in to an event for hide.uk.datepicker on checkIn field to change minDate of checkOut field accordingly.

What I do so far : 

```
$("input.checkIn").on("hide.uk.datepicker", function (e) {
        var minCheckOutDate = '<calculated date>'
        var checkOutParam = UIkit.$("input.checkOut").data('uk-datepicker');
        checkOutParam.minDate = minCheckOutDate;

        UIkit.datepicker(UIkit.$("input.checkOut"), checkOutParam);
});
```

It works for the first couple of changes. but for all subsequent changes checkOut datepicker doesn't respect the minDate.

I am sure there must be an way to update/refresh already initialised datepicker. I didn't see an proper documentation.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The DatePicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team

**Comment by collinph** [comment]
Did you ever make it work? Have a legacy app that needs this functionality
