### ISSUE TITLE
Add new grid dimension: 12

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#2010]
It would be nice add grid dimension on 12 part with all size: 1-12, 2-12, 3-12, 4-12, 5-12, ... 11-12
12 its a magic digit that divide on 2, 3, 4, 6 and its more convinion for adaptive coding.

**Comment by jsieler** [comment]
+1

**Comment by nblackburn** [comment]
I agree, i never understood why it was in 10.

**Comment by iozgur** [comment]
Here  @Intiligent with push and pull classes :)
.uk-width-1-1 {
    width: 100%;
}
/* Halves */
.uk-width-1-2,
.uk-width-2-4,
.uk-width-3-6,
.uk-width-4-8,
.uk-width-5-10,
.uk-width-6-12 {
    width: 50%;
}
/* Thirds */
.uk-width-1-3,
.uk-width-2-6,
.uk-width-3-9,
.uk-width-4-12 {
    width: 33.333%;
}
.uk-width-2-3,
.uk-width-4-6,
.uk-width-6-9,
.uk-width-8-12 {
    width: 66.666%;
}
/* Quarters */
.uk-width-1-4,
.uk-width-2-8
.uk-width-3-12 {
    width: 25%;
}
.uk-width-3-4,
.uk-width-6-8,
.uk-width-9-12 {
    width: 75%;
}
/* Fifths */
.uk-width-1-5,
.uk-width-2-10 {
    width: 20%;
}
.uk-width-2-5,
.uk-width-4-10 {
    width: 40%;
}
.uk-width-3-5,
.uk-width-6-10 {
    width: 60%;
}
.uk-width-4-5,
.uk-width-8-10 {
    width: 80%;
}
/* Sixths */
.uk-width-1-6,
.uk-width-2-12 {
    width: 16.666%;
}
.uk-width-5-6,
.uk-width-10-12 {
    width: 83.333%;
}

/* Seven */
.uk-width-1-7 {
    width: 14.285%;
}
.uk-width-2-7 {
    width: 28.571%;
}
.uk-width-3-7 {
    width: 42.857%;
}
.uk-width-4-7 {
    width: 57.142%;
}
.uk-width-5-7 {
    width: 71.428%;
}
.uk-width-6-7 {
    width: 85.714%;
}
/* Eight */
.uk-width-1-8 {
    width: 12.5%;
}
.uk-width-3-8 {
    width: 37.5%;
}
.uk-width-5-8 {
    width: 65.5%;
}
.uk-width-7-8 {
    width: 87.5%;
}
/* Nine */
.uk-width-1-9 {
    width: 11.11%;
}
.uk-width-2-9 {
    width: 22.22%;
}
.uk-width-4-9 {
    width: 44.44%;
}
.uk-width-5-9 {
    width: 55.55%;
}
.uk-width-7-9 {
    width: 77.77%;
}
.uk-width-8-9 {
    width: 88.88%;
}

/* Tenths */
.uk-width-1-10 {
    width: 10%;
}
.uk-width-3-10 {
    width: 30%;
}
.uk-width-7-10 {
    width: 70%;
}
.uk-width-9-10 {
    width: 90%;
}
.uk-width-1-12 {
    width: 8.333%; 
}
.uk-width-5-12 {
    width: 41.666%;
}
.uk-width-7-12 {
    width: 58.333%;
}
.uk-width-11-12 { 
    width: 91.666%; 
}

/* Phone landscape and bigger */
@media (min-width: 480px) {
    /* Whole */
    .uk-width-small-1-1 {
        width: 100%;
    }
    /* Halves */
    .uk-width-small-1-2,
    .uk-width-small-2-4,
    .uk-width-small-3-6,
    .uk-width-small-4-8,
    .uk-width-small-5-10,
    .uk-width-small-6-12 {
        width: 50%;
    }
    /* Thirds */
    .uk-width-small-1-3,
    .uk-width-small-2-6,
    .uk-width-small-3-9,
    .uk-width-small-4-12 {
        width: 33.333%;
    }
    .uk-width-small-2-3,
    .uk-width-small-4-6,
    .uk-width-small-6-9,
    .uk-width-small-8-12 {
        width: 66.666%;
    }
    /* Quarters */
    .uk-width-small-1-4,
    .uk-width-small-2-8,
    .uk-width-small-3-12 {
        width: 25%;
    }
    .uk-width-small-3-4,
    .uk-width-small-6-8,
    .uk-width-small-9-12 {
        width: 75%;
    }
    /* Fifths */
    .uk-width-small-1-5,
    .uk-width-small-2-10 {
        width: 20%;
    }
    .uk-width-small-2-5,
    .uk-width-small-4-10 {
        width: 40%;
    }
    .uk-width-small-3-5,
    .uk-width-small-6-10 {
        width: 60%;
    }
    .uk-width-small-4-5,
    .uk-width-small-8-10 {
        width: 80%;
    }
    /* Sixths */
    .uk-width-small-1-6,
    .uk-width-small-2-12 {
        width: 16.666%;
    }
    .uk-width-small-5-6,
    .uk-width-small-10-12 {
        width: 83.333%;
    }
    /* Seven */
    .uk-width-small-1-7 {
        width: 14.285%;
    }
    .uk-width-small-2-7 {
        width: 28.571%;
    }
    .uk-width-small-3-7 {
        width: 42.857%;
    }
    .uk-width-small-4-7 {
        width: 57.142%;
    }
    .uk-width-small-5-7 {
        width: 71.428%;
    }
    .uk-width-small-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-width-small-1-8 {
        width: 12.5%;
    }
    .uk-width-small-3-8 {
        width: 37.5%;
    }
    .uk-width-small-5-8 {
        width: 65.5%;
    }
    .uk-width-small-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-width-small-1-9 {
        width: 11.11%;
    }
    .uk-width-small-2-9 {
        width: 22.22%;
    }
    .uk-width-small-4-9 {
        width: 44.44%;
    }
    .uk-width-small-5-9 {
        width: 55.55%;
    }
    .uk-width-small-7-9 {
        width: 77.77%;
    }
    .uk-width-small-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-width-small-1-10 {
        width: 10%;
    }
    .uk-width-small-3-10 {
        width: 30%;
    }
    .uk-width-small-7-10 {
        width: 70%;
    }
    .uk-width-small-9-10 {
        width: 90%;
    }
    .uk-width-small-1-12 { 
        width:8.333%; 
    } 
    .uk-width-small-5-12 {
        width: 41.666%; 
    }
    .uk-width-small-7-12 {
        width: 58.333%;
    }
    .uk-width-small-11-12 {
        width: 91.666%;
    }
}
/* Tablet and bigger */
@media (min-width: 768px) {
    /* Whole */
    .uk-width-medium-1-1 {
        width: 100%;
    }
    /* Halves */
    .uk-width-medium-1-2,
    .uk-width-medium-2-4,
    .uk-width-medium-3-6,
    .uk-width-medium-4-8,
    .uk-width-medium-5-10,
    .uk-width-medium-6-12 {
        width: 50%;
    }
    /* Thirds */
    .uk-width-medium-1-3,
    .uk-width-medium-2-6,
    .uk-width-medium-3-9,
    .uk-width-medium-4-12 {
        width: 33.333%;
    }
    .uk-width-medium-2-3,
    .uk-width-medium-4-6,
    .uk-width-medium-6-9,
    .uk-width-medium-8-12 {
        width: 66.666%;
    }
    /* Quarters */
    .uk-width-medium-1-4,
    .uk-width-medium-2-8,
    .uk-width-3-12 {
        width: 25%;
    }
    .uk-width-medium-3-4,
    .uk-width-medium-6-8,
    .uk-width-medium-9-12 {
        width: 75%;
    }
    /* Fifths */
    .uk-width-medium-1-5,
    .uk-width-medium-2-10 {
        width: 20%;
    }
    .uk-width-medium-2-5,
    .uk-width-medium-4-10 {
        width: 40%;
    }
    .uk-width-medium-3-5,
    .uk-width-medium-6-10 {
        width: 60%;
    }
    .uk-width-medium-4-5,
    .uk-width-medium-8-10 {
        width: 80%;
    }
    /* Sixths */
    .uk-width-medium-1-6, 
    .uk-width-medium-2-12 {
        width: 16.666%;
    }
    .uk-width-medium-5-6, 
    .uk-width-medium-10-12 {
        width: 83.333%;
    }
    /* Seven */
    .uk-width-medium-1-7 {
        width: 14.285%;
    }
    .uk-width-medium-2-7 {
        width: 28.571%;
    }
    .uk-width-medium-3-7 {
        width: 42.857%;
    }
    .uk-width-medium-4-7 {
        width: 57.142%;
    }
    .uk-width-medium-5-7 {
        width: 71.428%;
    }
    .uk-width-medium-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-width-medium-1-8 {
        width: 12.5%;
    }
    .uk-width-medium-3-8 {
        width: 37.5%;
    }
    .uk-width-medium-5-8 {
        width: 65.5%;
    }
    .uk-width-medium-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-width-medium-1-9 {
        width: 11.11%;
    }
    .uk-width-medium-2-9 {
        width: 22.22%;
    }
    .uk-width-medium-4-9 {
        width: 44.44%;
    }
    .uk-width-medium-5-9 {
        width: 55.55%;
    }
    .uk-width-medium-7-9 {
        width: 77.77%;
    }
    .uk-width-medium-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-width-medium-1-10 {
        width: 10%;
    }
    .uk-width-medium-3-10 {
        width: 30%;
    }
    .uk-width-medium-7-10 {
        width: 70%;
    }
    .uk-width-medium-9-10 {
        width: 90%;
    }
    .uk-width-medium-1-12 { 
        width:8.333%; 
    } 
    .uk-width-medium-5-12 {
        width: 41.666%; 
    }
    .uk-width-medium-7-12 {
        width: 58.333%;
    }
    .uk-width-medium-11-12 {
        width: 91.666%;
    }
}
/* Desktop and bigger */
@media (min-width: 960px) {
    /* Whole */
    .uk-width-large-1-1 {
        width: 100%;
    }
    /* Halves */
    .uk-width-large-1-2,
    .uk-width-large-2-4,
    .uk-width-large-3-6,
    .uk-width-large-4-8,
    .uk-width-large-5-10,
    .uk-width-large-6-12 {
        width: 50%;
    }
    /* Thirds */
    .uk-width-large-1-3,
    .uk-width-large-2-6,
    .uk-width-large-3-9,
    .uk-width-large-4-12 {
        width: 33.333%;
    }
    .uk-width-large-2-3,
    .uk-width-large-4-6,
    .uk-width-large-6-9,
    .uk-width-large-8-12 {
        width: 66.666%;
    }
    /* Quarters */
    .uk-width-large-1-4,
    .uk-width-large-2-8,
    .uk-width-large-3-12 {
        width: 25%;
    }
    .uk-width-large-3-4,
    .uk-width-large-6-8,
    .uk-width-large-9-12 {
        width: 75%;
    }
    /* Fifths */
    .uk-width-large-1-5,
    .uk-width-large-2-10 {
        width: 20%;
    }
    .uk-width-large-2-5,
    .uk-width-large-4-10 {
        width: 40%;
    }
    .uk-width-large-3-5,
    .uk-width-large-6-10 {
        width: 60%;
    }
    .uk-width-large-4-5,
    .uk-width-large-8-10 {
        width: 80%;
    }
    /* Sixths */
    .uk-width-large-1-6,
    .uk-width-large-2-12 {
        width: 16.666%;
    }
    .uk-width-large-5-6,
    .uk-width-large-10-12 {
        width: 83.333%;
    }
    /* Seven */
    .uk-width-large-1-7 {
        width: 14.285%;
    }
    .uk-width-large-2-7 {
        width: 28.571%;
    }
    .uk-width-large-3-7 {
        width: 42.857%;
    }
    .uk-width-large-4-7 {
        width: 57.142%;
    }
    .uk-width-large-5-7 {
        width: 71.428%;
    }
    .uk-width-large-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-width-large-1-8 {
        width: 12.5%;
    }
    .uk-width-large-3-8 {
        width: 37.5%;
    }
    .uk-width-large-5-8 {
        width: 65.5%;
    }
    .uk-width-large-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-width-large-1-9 {
        width: 11.11%;
    }
    .uk-width-large-2-9 {
        width: 22.22%;
    }
    .uk-width-large-4-9 {
        width: 44.44%;
    }
    .uk-width-large-5-9 {
        width: 55.55%;
    }
    .uk-width-large-7-9 {
        width: 77.77%;
    }
    .uk-width-large-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-width-large-1-10 {
        width: 10%;
    }
    .uk-width-large-3-10 {
        width: 30%;
    }
    .uk-width-large-7-10 {
        width: 70%;
    }
    .uk-width-large-9-10 {
        width: 90%;
    }
    .uk-width-large-1-12 { 
        width:8.333%; 
    } 
    .uk-width-large-5-12 {
        width: 41.666%; 
    }
    .uk-width-large-7-12 {
        width: 58.333%;
    }
    .uk-width-large-11-12 {
        width: 91.666%;
    }
}
/* Large screen and bigger */
@media (min-width: 1220px) {
    /* Whole */
    .uk-width-xlarge-1-1 {
        width: 100%;
    }
    /* Halves */
    .uk-width-xlarge-1-2,
    .uk-width-xlarge-2-4,
    .uk-width-xlarge-3-6,
    .uk-width-xlarge-4-8,
    .uk-width-xlarge-5-10,
    .uk-width-xlarge-6-12 {
        width: 50%;
    }
    /* Thirds */
    .uk-width-xlarge-1-3,
    .uk-width-xlarge-2-6,
    .uk-width-xlarge-3-9,
    .uk-width-xlarge-4-12 {
        width: 33.333%;
    }
    .uk-width-xlarge-2-3,
    .uk-width-xlarge-4-6,
    .uk-width-xlarge-6-9,
    .uk-width-xlarge-8-12 {
        width: 66.666%;
    }
    /* Quarters */
    .uk-width-xlarge-1-4,
    .uk-width-xlarge-2-8,
    .uk-width-xlarge-3-12 {
        width: 25%;
    }
    .uk-width-xlarge-3-4,
    .uk-width-xlarge-6-8,
    .uk-width-xlarge-9-12 {
        width: 75%;
    }
    /* Fifths */
    .uk-width-xlarge-1-5,
    .uk-width-xlarge-2-10 {
        width: 20%;
    }
    .uk-width-xlarge-2-5,
    .uk-width-xlarge-4-10 {
        width: 40%;
    }
    .uk-width-xlarge-3-5,
    .uk-width-xlarge-6-10 {
        width: 60%;
    }
    .uk-width-xlarge-4-5,
    .uk-width-xlarge-8-10 {
        width: 80%;
    }
    /* Sixths */
    .uk-width-xlarge-1-6,
    .uk-width-xlarge-2-12 {
        width: 16.666%;
    }
    .uk-width-xlarge-5-6,
    .uk-width-xlarge-10-12 {
        width: 83.333%;
    }
    /* Seven */
    .uk-width-xlarge-1-7 {
        width: 14.285%;
    }
    .uk-width-xlarge-2-7 {
        width: 28.571%;
    }
    .uk-width-xlarge-3-7 {
        width: 42.857%;
    }
    .uk-width-xlarge-4-7 {
        width: 57.142%;
    }
    .uk-width-xlarge-5-7 {
        width: 71.428%;
    }
    .uk-width-xlarge-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-width-xlarge-1-8 {
        width: 12.5%;
    }
    .uk-width-xlarge-3-8 {
        width: 37.5%;
    }
    .uk-width-xlarge-5-8 {
        width: 65.5%;
    }
    .uk-width-xlarge-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-width-xlarge-1-9 {
        width: 11.11%;
    }
    .uk-width-xlarge-2-9 {
        width: 22.22%;
    }
    .uk-width-xlarge-4-9 {
        width: 44.44%;
    }
    .uk-width-xlarge-5-9 {
        width: 55.55%;
    }
    .uk-width-xlarge-7-9 {
        width: 77.77%;
    }
    .uk-width-xlarge-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-width-xlarge-1-10 {
        width: 10%;
    }
    .uk-width-xlarge-3-10 {
        width: 30%;
    }
    .uk-width-xlarge-7-10 {
        width: 70%;
    }
    .uk-width-xlarge-9-10 {
        width: 90%;
    }
    .uk-width-xlarge-1-12 { 
        width:8.333%; 
    } 
    .uk-width-xlarge-5-12 {
        width: 41.666%; 
    }
    .uk-width-xlarge-7-12 {
        width: 58.333%;
    }
    .uk-width-xlarge-11-12 {
        width: 91.666%;
    }
}
/* Sub-object: `uk-push-*` and `uk-pull-*`
 ========================================================================== */
/*
 * Source ordering
 * Works only with `uk-width-medium-*`
 */
/* Tablet and bigger */
@media (min-width: 768px) {
    [class*='uk-push-'],
    [class*='uk-pull-'] {
        position: relative;
    }
    /*
       * Push
       */
    /* Halves */
    .uk-push-1-2,
    .uk-push-2-4,
    .uk-push-3-6,
    .uk-push-4-8,
    .uk-push-5-10,
    .uk-push-6-12 {
        left: 50%;
    }
    /* Thirds */
    .uk-push-1-3,
    .uk-push-2-6,
    .uk-push-3-9,
    .uk-push-4-12 {
        left: 33.333%;
    }
    .uk-push-2-3,
    .uk-push-4-6,
    .uk-push-6-9,
    .uk-push-8-12 {
        left: 66.666%;
    }
    /* Quarters */
    .uk-push-1-4,
    .uk-push-2-8,
    .uk-push-3-12 {
        left: 25%;
    }
    .uk-push-3-4,
    .uk-push-6-8,
    .uk-push-9-12 {
        left: 75%;
    }
    /* Fifths */
    .uk-push-1-5,
    .uk-push-2-10 {
        left: 20%;
    }
    .uk-push-2-5,
    .uk-push-4-10 {
        left: 40%;
    }
    .uk-push-3-5,
    .uk-push-6-10 {
        left: 60%;
    }
    .uk-push-4-5,
    .uk-push-8-10 {
        left: 80%;
    }
    /* Sixths */
    .uk-push-1-6,
    .uk-push-2-12 {
        left: 16.666%;
    }
    .uk-push-5-6,
    .uk-push-10-12 {
        left: 83.333%;
    }
    /* Seven */
    .uk-push-1-7 {
        width: 14.285%;
    }
    .uk-push-2-7 {
        width: 28.571%;
    }
    .uk-push-3-7 {
        width: 42.857%;
    }
    .uk-push-4-7 {
        width: 57.142%;
    }
    .uk-push-5-7 {
        width: 71.428%;
    }
    .uk-push-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-push-1-8 {
        width: 12.5%;
    }
    .uk-push-3-8 {
        width: 37.5%;
    }
    .uk-push-5-8 {
        width: 65.5%;
    }
    .uk-push-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-push-1-9 {
        width: 11.11%;
    }
    .uk-push-2-9 {
        width: 22.22%;
    }
    .uk-push-4-9 {
        width: 44.44%;
    }
    .uk-push-5-9 {
        width: 55.55%;
    }
    .uk-push-7-9 {
        width: 77.77%;
    }
    .uk-push-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-push-1-10 {
        left: 10%;
    }
    .uk-push-3-10 {
        left: 30%;
    }
    .uk-push-7-10 {
        left: 70%;
    }
    .uk-push-9-10 {
        left: 90%;
    }
    .uk-push-1-12 { 
        width:8.333%; 
    } 
    .uk-push-5-12 {
        width: 41.666%; 
    }
    .uk-push-7-12 {
        width: 58.333%;
    }
    .uk-push-11-12 {
        width: 91.666%;
    }
    /*
       * Pull
       */
    /* Halves */
    .uk-pull-1-2,
    .uk-pull-2-4,
    .uk-pull-3-6,
    .uk-pull-4-8,
    .uk-pull-5-10,
    .uk-pull-6-12 {
        left: -50%;
    }
    /* Thirds */
    .uk-pull-1-3,
    .uk-pull-2-6,
    .uk-pull-3-9,
    .uk-pull-4-12 {
        left: -33.333%;
    }
    .uk-pull-2-3,
    .uk-pull-4-6,
    .uk-pull-6-9,
    .uk-pull-8-12 {
        left: -66.666%;
    }
    /* Quarters */
    .uk-pull-1-4,
    .uk-pull-2-8,
    .uk-pull-3-12 {
        left: -25%;
    }
    .uk-pull-3-4,
    .uk-pull-6-8,
    .uk-pull-9-12 {
        left: -75%;
    }
    /* Fifths */
    .uk-pull-1-5,
    .uk-pull-2-10 {
        left: -20%;
    }
    .uk-pull-2-5,
    .uk-pull-4-10 {
        left: -40%;
    }
    .uk-pull-3-5,
    .uk-pull-6-10 {
        left: -60%;
    }
    .uk-pull-4-5,
    .uk-pull-8-10 {
        left: -80%;
    }
    /* Sixths */
    .uk-pull-1-6,
    .uk-pull-2-6 {
        left: -16.666%;
    }
    .uk-pull-5-6,
    .uk-pull-10-12 {
        left: -83.333%;
    }
    /* Seven */
    .uk-pull-1-7 {
        width: 14.285%;
    }
    .uk-pull-2-7 {
        width: 28.571%;
    }
    .uk-pull-3-7 {
        width: 42.857%;
    }
    .uk-pull-4-7 {
        width: 57.142%;
    }
    .uk-pull-5-7 {
        width: 71.428%;
    }
    .uk-pull-6-7 {
        width: 85.714%;
    }
    /* Eight */
    .uk-pull-1-8 {
        width: 12.5%;
    }
    .uk-pull-3-8 {
        width: 37.5%;
    }
    .uk-pull-5-8 {
        width: 65.5%;
    }
    .uk-pull-7-8 {
        width: 87.5%;
    }
    /* Nine */
    .uk-pull-1-9 {
        width: 11.11%;
    }
    .uk-pull-2-9 {
        width: 22.22%;
    }
    .uk-pull-4-9 {
        width: 44.44%;
    }
    .uk-pull-5-9 {
        width: 55.55%;
    }
    .uk-pull-7-9 {
        width: 77.77%;
    }
    .uk-pull-8-9 {
        width: 88.88%;
    }
    /* Tenths */
    .uk-pull-1-10 {
        left: -10%;
    }
    .uk-pull-3-10 {
        left: -30%;
    }
    .uk-pull-7-10 {
        left: -70%;
    }
    .uk-pull-9-10 {
        left: -90%;
    }
    .uk-pull-1-12 { 
        width:8.333%; 
    } 
    .uk-pull-5-12 {
        width: 41.666%; 
    }
    .uk-pull-7-12 {
        width: 58.333%;
    }
    .uk-pull-11-12 {
        width: 91.666%;
    }
}`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This has not been added to the UIkit3, mostly because of the %-Problems with 1/12, which often cause pixel misscalculations within browsers. 

Thanks for your understanding,
Your UIkit Team
