### ISSUE TITLE
What the different betwen push and reveal mode in off-canvas component?

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#2011]

**Comment by PixelT** [comment]
I had the same impression at beginning, but when you testing it (open and close x100) then you can see the difference:
in push: the offcanvas + the page body animated from left to right
in reveal: the offcanvas stay, only the page body is animated from left to right
it can be hard to explain, but in other words, in push the offcanvas is next to page body (they animated both), in reveal the offcanvas is under the page body (animated is only page body)

**Comment by Intiligent** [comment]
This difference can only distinguish a perfectionist)))
Even can't imagine where you need use "reveal" instead of "push".
The opportunity is there and is already well.

**Comment by zzseba78** [comment]
I would like a swipe animation in offcanvas too :)
