### ISSUE TITLE
slideshow flickering

### ISSUE THREAD

**Issue by yaakib** [uikit/uikit#2012]
hi ,I have a problem with slideshow 'scroll' on click next image button the image is  flickering in Internet Explorer 11, The problem is also on the site examples 'scroll' in chrome its ok
http://getuikit.com/docs/slideshow.html (go down to Transitions=>Example=> 'Scroll')
How can I solve it?
Thanks

**Comment by yaakib** [comment]
look video https://youtu.be/trXFP9aXIpY

**Comment by brianpeat** [comment]
I'm noticing the same issue on a uikit site I just built.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
