### ISSUE TITLE
Jalali(Persian) calendar for date-picker 

### ISSUE THREAD

**Issue by corbacode** [uikit/uikit#2014]
hi guys,
can you guide me, how can convert Gregorian calendar to Jalali calendar ?
I write some code about converting date in Gregorian to Jalali but I'm so confusing about replacement my code into the UIKIT datepicker.js ! please help me. thanks

please check this link : [JalaliJSCalendar](https://github.com/farhadi/JalaliJSCalendar/blob/master/jalali.js)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We are currently working on the DatePicker component for UIkit3 and we will try to add a 'calendar' option which desiced which kind of calendar is used. But from the current state of it we can't promise that this will make it into the final version.

Thanks for your understanding,
Your UIkit Team
