### ISSUE TITLE
bug in sub menu in RTL mode

### ISSUE THREAD

**Issue by sajjad-golchin** [uikit/uikit#2015]
if in enter site and go to section CUSTOMIZER and check it RTL
sub menu bad show in LTR mode

**Comment by corbacode** [comment]
hi Sajjad, I checked Nav & SubNav components in RTL Mode. they work right !!! could you explain more ?

**Comment by sajjadgolchin** [comment]
if you RTL document html and checking "sub nav" you see subnav dropdown in ltr state

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
