### ISSUE TITLE
jQuery 3.0 in Bower

### ISSUE THREAD

**Issue by sandfoxme** [uikit/uikit#2016]
According to  #1959 UIKit works with jQuery 3.0 but when using Bower it blocks its installation
Probably it's good idea to change `"jquery": "~2.1.0"` to `"jquery": "^2.1.0 || ^3.0.0"` to allow updating jQuery to 2.2 and 3.0

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
