### ISSUE TITLE
NPM Import for Meteor?

### ISSUE THREAD

**Issue by granda** [uikit/uikit#2017]
Is there a straightforward to importing `uikit` in a React application? I've found UIkit posted on npm: https://www.npmjs.com/package/uikit however when I attempt to `import 'uikit';` into a Meteor application it doesn't seem to actually import anything. I wouldn't put it past myself that I'm making a mistake with importing such a library though.

I was finally able to get css working by `import 'uikit/dist/css/uikit.gradient.css';` however I noticed the Javascript and webfonts didn't load. 😣

**Comment by florianletsch** [comment]
It might have been broken when you reported this. Now, it should work. Also look at this new section in the docs, even though your setup might look a little different. This should all work now with the current release. We have also added a basic tutorial to the docs: https://getuikit.com/docs/webpack
