### ISSUE TITLE
uikit ver 2.27.1 - problem with dropdown.js on mobile (works well on 2.26.4)

### ISSUE THREAD

**Issue by Siton-Systems** [uikit/uikit#2018]
On **mobile** (I check this on android and iphone6) - if you click on the drop down first "dont work" and only in the second...third....and so on click work well (on mode:click & mode:hover)

I see this bug only when i update to 2.27.1 so the problem is between those versions.

**Comment by Siton-Systems** [comment]
my mistake. it way jquery version issue.

**Comment by thumarmahesh** [comment]
@Siton-Systems : what was the resolution? I'm having the same issue (UIkit Version 2.27.1 and jQuery : v2.1.4)
