### ISSUE TITLE
dynamic content updates

### ISSUE THREAD

**Issue by fbrau** [uikit/uikit#2019]
Hi, I just wanna post a though on developing with uikit.

I'm of the idea that page updating model should be handled from the server so I tend to 
follow a "backend-rules" architecture.

Anyways, I've just took a second take on UiKit documentation. after investigating several other
frameworks or kits, and what I'm starting to like
are the Navigation Components. The idea of presenting a "page" as a set of slides.

On the abstract, from a optimized user experience point, I would like to present the whole
complete set of "Items" but, you know, the whole set is 1000 or more items... who knows?...
I'm thinking uikit documentation should provide tips to handle this (if it dont already supports such feaure,
in which case I would like you to point me to those :)

The idea to load just the first item.. and when the whole base page is already populated, after
that, the server begins to push that "secondary" content in the background, ensuring the whole
initial load gives priority to the content that should be initially shown because, why should I wait
to load the entire whole set of items just to see content. 

How can one handle this? I mean, If I push content to the DOM (from the server) and for example,
I'm using a "slidenav". When I push the ">" button, 
how can I make Uikit to detect in realtime (or trigger that update) that a new item has got added to
the list in the slidenav. Something like a "realtime-items" class or how to catch that event from 
a little js/jquery snippet or an API

UPDATE:
   oh.. excellent am starting to see that the Pagination component has a take on such a feature.. but
   I can't manage to understand how should I use it... somebody? Anyways, for the navs there is no
   tip on that so the whole comment mantains.

**Comment by kelsh** [comment]
This is outside the scope of what uikit does. The Yootheme people like vue.js, which handles things like that.  Its well documented and pretty easy!

https://vuejs.org/

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Thanks for your understanding,
Your UIkit Team
