### ISSUE TITLE
Nested modals and ESC key closes wrong modal

### ISSUE THREAD

**Issue by umphy** [uikit/uikit#2021]
When displaying nested modals, the `ESC` key does not close the nested modal. Instead it closes the first modal.

Here is a jsfiddle: https://jsfiddle.net/8ru5f2rr/

Click on the button in the first modal to open the nested modal then press `ESC` - it will close the first modal. Subsequent presses of `ESC` does not close the nested modal.

**Comment by umphy** [comment]
Actually, I think the ```ESC``` key doesn't work for modals where ```{modal: false}```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
