### ISSUE TITLE
Toggle doesn't change state when trigger is LABEL element

### ISSUE THREAD

**Issue by SuchyTheMaster** [uikit/uikit#2022]
When I add data-uk-toggle to label element, then clicking on this label doesn't change state of target element. Label hasn't any other JS bindings. During clicking Chrome Inspector shows me that there are operation on target element, but final result is the same as at begining.

When I move data-uk-toggle to another element than label, then it works.

Here my code:

```
<label class="stylized" for="invoice" data-uk-toggle="{target: '#invoice-fields'}">
      <input id="invoice" type="checkbox" class="stylized" name="invoice" value="1">
      <span></span>
      <span>I want invoice</span>
</label>
<div id="invoice-fields" class="uk-hidden">
...
</div>
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
