### ISSUE TITLE
Datepicker uses min date as default value 

### ISSUE THREAD

**Issue by orestisioakeimidis** [uikit/uikit#2024]
Hi all,

In the following piece of code, when you `click` or `focus` on the datepicker,

`if (active!==$this) $this.pick(this.value ? this.value:($this.options.minDate ? $this.options.minDate :''));`

the min date is selected as the default visible value, if there is no value yet. In my opinion, this is completely wrong assumption and should only happen when min date is in the future. Otherwise, the today date should always be the default visible value.

Awaiting your response...

Cheers!

**Comment by eduardoportilho** [comment]
@orestisioakeimidis I agree with you, specially because this is the behaviour when `minDate` is set with an integer (p.e. -7). I created a [pull request](https://github.com/uikit/uikit/pull/2062) that fixes this to continue the discussion.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
