### ISSUE TITLE
Is there any option for the slideshow that will programmatically get you to the next slide

### ISSUE THREAD

**Issue by badcoder28** [uikit/uikit#2027]
Slides inside a slide. What i want is unless all the slide items of an `#slide-child-ul` has reach the`li:last-element` the `#slide-parent-ul` will not proceed to its next slide item. Notice that i set the autoplay of the `#slide-parent-ul` to false to handle it programmatically from the script and in order to achieve that i use the `beforeshow.uk.slideshow` event i provide below please take a look.

Here is template structure:

```
// Parent ul 
<ul id="slide-parent-ul" class="uk-slideshow" data-uk-slideshow="{autoplay:false}">
   <li>
       <div class="first-list">
           // Child ul
           <ul id="slide-child-ul" class="uk-slideshow" data-uk-slideshow="{autoplay:true,
                                                        autoplayInterval: 10000}">
               <li>Item 1</li>
               <li>Item 2</li>
               <li>Item 3</li>
           </ul>
       </div>
   </li>
   <li>
       <div class="second-list">
          // Child ul
          <ul id="slide-child-ul" class="uk-slideshow" data-uk-slideshow="{autoplay:true, 
                                                       autoplayInterval: 10000}">
             <li>Item 1</li>
             <li>Item 2</li>
             <li>Item 3</li>
          </ul>
       </div>
   </li>
</ul>
```

Here is my scripts

```
<script>
    $('#slide-child-ul').on('beforeshow.uk.slideshow', function(event, nxt_slide, cur_slide){
        var elem = $(cur_slide);
        if (elem.is(':last-child'))
        {
             // HERE IS THE PROBLEM
            // #slide-parent-ul will get to the next slide item. It is possible? but how??
        }
    });
</script>
```

Hope i made it clear, it is possible right?

**Comment by rknonchalance** [comment]
A terrible workaround would be that you could use a hidden <a> link inside the slider you want to change to move to a different slider by setting the slide's number through _data-uk-slider-item_
```
<div class="uk-slidenav-position" data-uk-slider>
 <a class="moveme" href="" data-uk-slider-item="1"></a>
</div>
```
And then in your script just trigger a click on the link like so, probably in your comment of //HERE IS THE PROBLEM:
`$(".moveme").trigger("click");`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
