### ISSUE TITLE
Pls Add option to lightbox.js....fitToview = false + scroll

### ISSUE THREAD

**Issue by Siton-Systems** [uikit/uikit#2028]
In tall images the light box really "zoom out" the image and its look weird. In other words the lightbox work nice only for "horizontal" images.

Something like this (click on "bswift screenshot").
http://jsfiddle.net/v4jyr/

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Lightbox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
