### ISSUE TITLE
webpack init's uikit twice

### ISSUE THREAD

**Issue by drKnoxy** [uikit/uikit#2029]
https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L3 is replaced with `if (true) {`
and the core method is executed on both:

https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L7
https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L35

am I missing something here?

**Comment by withinboredom** [comment]
+1

**Comment by jrjacobs24** [comment]
+1

**Comment by aheinze** [comment]
Should be fixed now! Thanks for reporting!
