### ISSUE TITLE
modal and registration form

### ISSUE THREAD

**Issue by dimacheck** [uikit/uikit#2030]
There is a modal window, this is a registration form, when the user finishing form filing the modal is closing automatically, i don't need it. How i can make this modal closing just by a separate button without automatically closing?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
