### ISSUE TITLE
uk-modal multiple modals and iframe issue

### ISSUE THREAD

**Issue by powrie** [uikit/uikit#2031]
Hi we're experiencing apparent random behaviour from multiple instances of _**uk-modal**_ when containing iframes. The modal appears to be unable to locate the correct iframe within the DOM and loads random containers despite correct/unique id selectors being targeted.

Please review example http://nga.gov.au/calendar/Default2.cfm.

However, _**data-uk-lightbox**_ performs as expected using exactly the same code as demonstrated in example above. 

In our application we require uk-modal for the uk-modal-header option. 

thankyou

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
