### ISSUE TITLE
Dropdown hover not working, even on http://getuikit.com/docs/dropdown.html

### ISSUE THREAD

**Issue by M201609** [uikit/uikit#2032]
Chrome 52.0.2743.116, Edge 20.10586.0.0 (Win10)
Dropdown hover is not working because of
UI.support.touch in those browsers is true and dropdown switches to "click"-kind of events in this case ( in uikit.js line 2016)

**Comment by rewchelsea** [comment]
I have the same issue - The dropdown doesn't open on hover on Chrome 52.0.2743.116.

**Comment by M201609** [comment]
I'm working on desktop PC and don't have any touch screens. I also didn't change any settings in my system (neither Chrome nor Windows) and "Enable touch events" in my case set to "Automatic".

And anyways, even if people have touch displays, it doesn't mean they are not using mouse. So I think it makes sense to process both events (hover and click) regardless to the touch compatibility. It's a very easy fix - for the hover event you always show the dropdown (if there is one to show of course), for click event you need to check if the dropdown is not visible then show it and prevent default click event, if it is visible then don't do anything and don't prevent default click

**Comment by TomJacobsUK** [comment]
I'm also working on a windows laptop without a touch screen with no modification to system or chrome settings and was receiving same issues. Following @philoest instructions resolved the issue although, I feel the average user may not realise that theses settings need to be changed, thus impairing the user experience with the website.

Chrome 53.0.2785.116

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
