### ISSUE TITLE
Accordion scroll bug on MS Edge

### ISSUE THREAD

**Issue by eladnova** [uikit/uikit#2033]
Client just reported an accordion bug when using MS Edge

If you have accordion 01 expanded and click on accordion 02, the following happens
1. accordion 01 collapses (desired behaviour)
2. accordion 02 expands (desired behaviour)
3. browser scrolls to bottom of accordion 02 contents (not intended)

Normally what would happen in step 3 above is the browser would scroll so that accordion 02s content is at the top of the browser window.

I can replicate this on MS Edge

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
