### ISSUE TITLE
Links in "Slideshow" and "Slider" are not clickable since 2.27.0

### ISSUE THREAD

**Issue by JoomFX** [uikit/uikit#2034]
Hey guys,

There is an issue with the "Slideshow" and "Slider" components. The issue was introduced in 2.27.0 (or 2.27.1) - everything works fine with 2.26.4.

The problem is that none of the links inside the "Slideshow" and "Slider" components are clickable. Probably it is related to the JS responsible for the swipe, I don't know.

The strange thing is that the links work just fine if you right-click and select "Open in New Tab".

**Comment by aheinze** [comment]
@JoomFX could you please provide more details on which browser, os etc do you use?

Thanks!

**Comment by JoomFX** [comment]
@aheinze Hi Artur,

The issue is reproducible in all browsers. The ones I tested with are Firefox, Chrome and IE11.

The issue is easily reproducible, honestly. All you need to do is to add a link to the Slider/Slideshow items and you will notice that it is not clickable - the cursor changes to pointer when you hover over the link but nothing happens when you click. But if you right-click and select "Open in new tab", the correct URL is opened.

The issue is not reproducible in 2.26.4

**Comment by aheinze** [comment]
I guess you use UIkit in a Joomla installation, right? I could experience this issue only in combination with joomla, can you verify this?

**Comment by JoomFX** [comment]
@aheinze Hi Artur,

Yes, I noticed the issue by using UIkit 2.27.1 in Joomla.

It is strange because using UIkit 2.26.4 in Joomla 3.6.2 everything works perfectly fine, but when using UIkit 2.27.1 in Joomla 3.6.2 I get the issue described above when using the Slider and Slideshow component. 
So something has changed in UIkit 2.27.0.

Let me know if you need any other details from my side.

**Comment by aheinze** [comment]
UIkit itself doesn't have the problem, e.g. using it standalone or with WP etc there is no problem, we'll make it work with joomla with the next release.

**Comment by JoomFX** [comment]
Thanks Artur 😉

**Comment by DamirPecnik** [comment]
Is there any fix for this maybe?

**Comment by DamirPecnik** [comment]
https://github.com/uikit/uikit/pull/2042/commits/062d9908f284e95b675277bf6ad55a23204b2c17
