### ISSUE TITLE
UIKit autocomplete Flicker issue

### ISSUE THREAD

**Issue by akash1102** [uikit/uikit#2035]
I am facing a challenge with autocomplete box. For selecting an item from autcomplete, I press enter. Input field flickers and the selections remains incomplete.

Texbox shows items text but in my ItemTemplate I've some hidden spans which hold values that are supposed to be selected on autocomplete select item event but do not get selected because of this flickering.

I am calling like this from document.ready

$('[data-uk-autocomplete]').on('selectitem.uk.autocomplete',
             function() {
               $("#ulServiceList li").each(function() {
![flickeruikit](https://cloud.githubusercontent.com/assets/22223231/18607192/85d0e10c-7ce3-11e6-8271-d8472ad7c75e.jpg)

**Comment by aheinze** [comment]
could you please provide a live exMPLE?

THANKS!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.  
The Autocomplete component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
