### ISSUE TITLE
modal window not opening from top with larger text (only bottom visible)

### ISSUE THREAD

**Issue by sargac** [uikit/uikit#2036]
I've noticed that modal window in the newest UIKit v2.27.1 doesn't position modal window correctly with larger text, as it did before, at least it worked in version v2.26.3.

The problem is the modal opens in that way, the last part of larger text is visible and only the bottom part of modal (footer), while modal header is not visible, and user must scroll all the way to top, to see its beginning. In previous, mentioned release, it opened in that way, so the larger text and the modal was visible from top/beginning.

I found the line in JS code that causes this "malfunction", at least it works as usual as soon as I remove that line -- so please take a look at it. **It is line #2682 of uikit.js file.**

``` js
if (UI.support.transition) {
    this.hasTransitioned = false;
    this.element.one(UI.support.transition.end, function(){
        $this.hasTransitioned = true;
        // UI.Utils.focus($this.dialog, 'a[href]'); <-- THIS LINE IS CAUSING THE PROBLEM
    }).addClass("uk-open");
} else {
    this.element.addClass("uk-open");
    UI.Utils.focus(this.dialog, 'a[href]');
}
```

Best!

**Comment by sargac** [comment]
### A solution

As I stumbled upon the same issue as well in the new version, I went a step further and found a cause for this issue.

It happens only only when using  **Modal header and footer** version of modal dialog in conjunction with **close link**, while it works correctly in conjunction with a **close button**. Maybe that explains, why removing the code ``UI.Utils.focus($this.dialog, 'a[href]');`` works for the **close link** as well.

For me, this case can be closed, but I'll leave it open, in case someone has a solution for both link and button, or would like to update the documentation at https://getuikit.com/docs/modal.html#modal-header-footer.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
