### ISSUE TITLE
UIKIT nestable component + WYSIWYG

### ISSUE THREAD

**Issue by adrianolls** [uikit/uikit#2037]
Hello,
i have a issue with nestable component after using any kind of WYSIWYG.
after move-up a nestable item the textarea freeze and cannot be clicked from any place anymore.
without a WYSIWYG works fine, but i'm developing a contract generator, and a WYSIWYG is important to make output file looks good

**Comment by danielptn** [comment]
i have the same problem with input.. you have fix this bug?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.

Thanks for your understanding,
Your UIkit Team

**Comment by adrianolls** [comment]
There is any chance of Uikit3 has the same issue ?
