### ISSUE TITLE
Dropdown dotted outline

### ISSUE THREAD

**Issue by tanoabeleyra** [uikit/uikit#2038]
Hey guys/gals!,
I just started using UIKit and realized that on Firefox the dropdown has a dotted outline by default when it gets focused, and it doesn't look really cool.

![dropdown](https://cloud.githubusercontent.com/assets/6851095/18634098/f3f59c04-7e55-11e6-92df-2be49656ac54.png)

I know I can simply add `outline: none` but maybe it would be better to be like that by default in the framework itself. Would be fine to create a pull request?

**Comment by doublex** [comment]
Same issue

**Comment by zzseba78** [comment]
Same, not only in the dropdown element... this is happening from version 2.27
