### ISSUE TITLE
cover-background not working

### ISSUE THREAD

**Issue by Samanw** [uikit/uikit#2040]
hello
im trying to use COVER in my pages but its not working 
 whats the issue here ? thx for your reply
http://getuikit.com/docs/cover.html

**Comment by gretzky** [comment]
Could you provide a code snippet?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
