### ISSUE TITLE
Date Range is not being queried correctly

### ISSUE THREAD

**Issue by universe416** [uikit/uikit#2041]
I have an issue with a form that queries a MySQL DB using PHP.  The form consists of numerous number ranges and a date range.  All of the number ranges work, but I cannot seem to get the date range to query correctly and I'm wondering if it has something to do with the common.js file from the uikit plugin.  I was initially using the calendar to select a date range to query from a form; however, in troubleshooting this issue, I removed the calendar to try and isolate the problem.  Now, when input just the date (in MySQL format 'YYYY-MM-DD') it still does not work.  I'm wondering if there is something within the JS file that is removing the dashes from the input.  Any insight would be much appreciated.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
