### ISSUE TITLE
Sticky navbar + scrollspy nav

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2045]
It's possible to add offset to the scrollspy nav?
Now I have sticky navbar and the scrollspy nav show under the sticky...  (the start of content is invisible) :(

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by FrantisekVrab** [comment]
Hello, a little bit later, however I found a solution to overwrite this.

First set the scrollspy smoothscroll with false like this

```
<ul 
   id="nav"
   data-uk-scrollspy-nav="{closest:'li',` smoothscroll:false}"
> 
...
</ul>

```
Then, use this function
```
$("#nav a").click(function() {
     var hashHref = $(this).attr('href');
     $('html, body').animate({scrollTop: $(hashHref).offset().top - 150}, 400);
});
```
_150_ is offset in pixels
_400_ is speed of animation in ms

I hope it will solve your problem.
