### ISSUE TITLE
sticky navbar and images

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#2046]
hello, I have a problem with the sticky navbar, and I don't understand where I go wrong.
All my pages have one or multiple images in the first element under the navbar.
But when I load the page (mostly on firefox all OS, randomly with safari and Chrome) I get the image  on the right side of the page like you can see here www.nurideas.com
Load the page with FF and you'll see the image in the wrong position. Reload it and it is ok now.
any idea ? an FF bug ? thanks
(edited with link to web site)

**Comment by tschuhmacher** [comment]
Have you tried wrapping your image in `<div class="uk-cover-background">` instead of giving it simply a grid space with `<div class="uk-width-1-1">` => [Cover Component | uikit](https://getuikit.com/docs/cover.html)

**Comment by prtome** [comment]
Thanks, did not before so I tried. It breaks the page for Safari and Chrome, so it is not the solution.
I think the problem is the sticky_header. Other pages with images have (sometimes, this is random behaviour, on all browsers) part of the image under the header and I need to reload to get them back where they should.  If I don't use the sticky stuff, I have no problems at all. 
googling a little, it seems i am not the only one with a similar problem.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
