### ISSUE TITLE
UIkit Events and Animationend event 

### ISSUE THREAD

**Issue by piotr-cz** [uikit/uikit#2047]
Dropdown events `show.uk.dropdown` and `hide.uk.dropdown` should be triggered after animation ends.

suggested code:

``` JS
if (UI.support.animation) {
    this.dropdown.one(UI.support.animation.end, this.trigger.bind(this, [this, force]));
} else {
    this.trigger('hide.uk.dropdown', [this, force]);
}
```

Use case
I'm using autocomplete library which binds to input search field which is located inside the dropdown.
Suggestion box is absolutely positioned to match the input field position, but it happens too early: during animation itineration and is being placed over input field.
Using events like `beforeshow.uk.dropdown` or `show.uk.dropdown` doesn't help as these happen in the same moment.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
