### ISSUE TITLE
Type error : this.option is undefined uikit.min.js  UIKIT 2.27.1

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#2048]
Hello, 
I get the following errors 
in Firefox: 
TypeError: this.options is undefined
.init/<()   uikit.min.js:3
n.domObserve/</o<()  uikit.min.js:2
n.Utils.debounce/</a()  uikit.min.js:2

Chrome says 
Uncaught TypeError: Cannot read property 'lists' of undefined uikit.min.js:3

Nothing seems wrong on the page (which is quite simple )
Any idea ? thanks

**Comment by aheinze** [comment]
this is already fixed in the current dev branche. thanks!
