### ISSUE TITLE
commonjs/es6 module style import

### ISSUE THREAD

**Issue by mjbates7** [uikit/uikit#2049]
Hi, Is it possible for uikit to work with commonjs/es6 style coding?

At the moment I need to do this:
`require('uikit/dist/js/uikit');`
`require('uikit/dist/css/uikit.css');`

Then for any sub components I need to do the following:
`require('uikit/dist/js/components/notify.js');`
`require('uikit/dist/css/components/notify.css');`

Is it possible to use `import {notify, componentX } from 'uikit';` which will then import those components and relevant css files or something like: 

`require('uikit/components/notify');`

Thanks :)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
