### ISSUE TITLE
UIKIT modal confirm

### ISSUE THREAD

**Issue by safraga** [uikit/uikit#2050]
Hi,
I'm trying to get a confirm alert with uikit modal but nothing of what I do run correctly.

My code is simple like that

`<form class="uk-form" action="execIncludes/sendprestation.php" onSubmit="return confirme()" method="post">
                        <label>Select a month</label>
                         <select id="mois" class="uk-form-small uk-form-width-small uk-text-left" name="month">
                            <option value="Janvier">Janvier</option>
                            <option value="Février">Février</option>
                            <option value="Mars">Mars</option>
                            <option value="Avril">Avril</option>
                            <option value="Mai">Mai</option>
                            <option value="Juin">Juin</option>
                            <option value="Juillet">Juillet</option>
                            <option value="Août">Août</option>
                            <option value="Septembre">Septembre</option>
                            <option value="Octobre">Octobre</option>
                            <option value="Novembre">Novembre</option>
                            <option value="Décembre">Décembre</option>
                        </select>
                        <button class="uk-button" type="submit">Envoyer les factures</button>              
                    </form>`

The java is

`function confirme()
        {
            var mois = document.getElementById("month").options[document.getElementById("month").selectedIndex].value;
            UIkit.modal.confirm('Etes vous sûre de vouloir envoyer les factures pour '+mois+'?', function()
            {
                return true;
            }, 
            function()
            {
                return false;
            },
            {labels: {'Ok': 'Oui', 'Cancel': 'Annuler'}});
        }`

Thank you for help
Best regards

**Comment by DeMuu** [comment]
Hi,

as far as I can see you're trying to get an element by ID "month" but you don't have that. you only have one with the ID "mois".
Adjusting this should make it work ;)

https://jsfiddle.net/10aejqge/1/

Greets

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 
Thanks for your understanding,
Your UIkit Team
