### ISSUE TITLE
tooltip does not carry the line

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2051]
![default](https://cloud.githubusercontent.com/assets/18468664/19005516/b95bbeae-8763-11e6-8e82-fa83f0f6bd96.png)

Hello! please help, the tooltip does not carry the line! What to do?

**Comment by kirich1368** [comment]
fix word-break: break-all;

**Comment by nblackburn** [comment]
This has since been fixed, fancy closing it?

**Comment by kirich1368** [comment]
+
