### ISSUE TITLE
data-uk-grid-margin

### ISSUE THREAD

**Issue by Yanbo** [uikit/uikit#2058]
Hi everyone,

I am new uikit er , I was learning it by following Tutorials Video. In the third video, everything works out except "data-uk-grid-margin", it doesn't adds space between rows, I've already check codes many times,  I'm using Ubuntu & chromious. 

Can anyone give me some tips to check this out?

Thks

**Comment by Yanbo** [comment]
I just figures it out.

I need load jquery before uikit.js

**Comment by nblackburn** [comment]
@Yanbo If you have solved this, could i ask you to close the issue?
