### ISSUE TITLE
Lightbox Images won't load if they have Timestamps image-1.jpg?57ed752b

### ISSUE THREAD

**Issue by DamirPecnik** [uikit/uikit#2060]
When images have timestamps on them the Lightbox will not open them ...

```
<a href="/images/gallery/image-1.jpg?57ed752b" data-uk-lightbox="{group:'gallery'}" title="Title">
       <img src="/images/gallery/image-1-thumb.jpg?57ed77ee" alt="Title">
</a>
```

**Comment by sureshdsk** [comment]
Created a pull request for this bug 
https://github.com/uikit/uikit/pull/2072

**Comment by idolab** [comment]
meanwhile,
just use data-lightbox-type="image"

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The LightBox component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
