### ISSUE TITLE
Nestable + input = problem

### ISSUE THREAD

**Issue by danielptn** [uikit/uikit#2063]
Hello, when i try to put some input inside the bar of nestable, the input can't be selected.. someone know how can i solve it? 
I already try to put z-index, position:absolute in input, but no success

**Comment by danielptn** [comment]
@faulancer @schinckel @m5o @jbenesch @frio please, someone know? =(

**Comment by danielptn** [comment]
@julianotheiss @websterz @lucil

**Comment by julianotheiss** [comment]
do you have a codepen for this?

**Comment by danielptn** [comment]
@julianotheiss no, but is easy to reproduce..
https://getuikit.com/docs/nestable.html
just try to put a input on some nestable component.. won't work =(
it is as if the nestable override the input, but i already try the z-index and position absolute and don't have success..

**Comment by julianotheiss** [comment]
<input class="uk-nestable-nodrag">

**Comment by danielptn** [comment]
@julianotheiss loool, sounds obvious now!!
work buddy! thanks a lot! i try solve this for 5 hours haha...
