### ISSUE TITLE
background on HTML tag causing issue in IE11

### ISSUE THREAD

**Issue by badpenguin** [uikit/uikit#2065]
Using the gradient theme: having the background-image set on the HTML tag wil cause IE11 flicker when scrolling the page with mouse wheel.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
