### ISSUE TITLE
scss variables declared with !default; is overwritten by included scss-files

### ISSUE THREAD

**Issue by NielsHolt** [uikit/uikit#2074]
Hi
In uikit-variables.scss all the variables are defined with !default; witch means that the user can overwrite the value before including uikit.scss
But in many of the scss-files the variable is set again and now without !default meaning that any changed made by the user is removed
The hole idea of having scss-variables declared with !default is to allow other to overwrite the values before they are used.
Kind Regards
Niels

**Comment by philoest** [comment]
This will come for UIkit3!
