### ISSUE TITLE
search event 'show.uk.autocomplete' doesn't work

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#2075]
HI why this event doesn't work please someone explain.

Many Thanks

**Comment by hmelenok** [comment]
Please provide more details, code snippet or something (any errors?)

**Comment by hmelenok** [comment]
`$('.uk-autocomplete.uk-form:first').on('show.uk.autocomplete', function(e){ 
    //console.log(e); do something here
});`
Works for me

**Comment by philoest** [comment]
We have released the next major version, UIkit3.
The autocomplete component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
