### ISSUE TITLE
Carousel slideset.js to slide only by one item and not the wholse set

### ISSUE THREAD

**Issue by DamirPecnik** [uikit/uikit#2079]
Is it possible to set slideset.js to slide only by one item and not the whole set of items like carousel style?

**Comment by zzseba78** [comment]
I think it´s not. You can use the slider component, but you don´t have the bullet navigation.
https://getuikit.com/docs/slider.html

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2.
The slideset component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
