### ISSUE TITLE
inactive.uk.sticky doesn't fire with boundary: true

### ISSUE THREAD

**Issue by josueadelima** [uikit/uikit#2081]
Sticky element with boundary: true, the inactive.uk.sticky event doesn't fire when wrapper left viewport scrolling up.

Scrolling down works  fine.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
