### ISSUE TITLE
sticky button on offcanvas open

### ISSUE THREAD

**Issue by kickthemooon** [uikit/uikit#2083]
I have sticky button that i am opening and closing the offcanvas sidebar.

I have a top parameter on the sticky button:

data-uk-sticky="{boundary: true, top:60, animation: 'uk-animation-slide-top'}"

I would like to remove the top parameter while the off canvas bar is open.

Any help on how to accomplish this?

**Comment by bariskrdrl** [comment]
@kickthemooon 'uk-animation-slide-top' parameter UIKit "version": "2.27.1" the time has come.versiyon Can you check?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
