### ISSUE TITLE
A slideshow problem

### ISSUE THREAD

**Issue by SoCarbone** [uikit/uikit#2087]
Hi ! I have a problem with my slideshow, i have load slideshow.js, slideshow-fx.js and slideshow.css but my images doesn't display at the good place. There are place in absolute at the top of the site and there is no animation. Have you got an idea ?

Have a good day !

**Comment by zzseba78** [comment]
Can you provide a codepen or uikitplay to check?

**Comment by SoCarbone** [comment]
Yes of course, but when i put my code on uikitplay, the slideshow work....

https://uikitplay.com/plays/FXuj

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
