### ISSUE TITLE
Tooltip doesn't disappear when triggering off-canvas over top of it.

### ISSUE THREAD

**Issue by Hectate** [uikit/uikit#2092]
I'm using UIKit in an Electron app (i.e. Chromium) and loving it, but I noticed that my tooltip isn't disappearing when it ends up underneath an offscreen canvas. Interestingly, it flickers and disappears depending on the mouse cursor position.

I'm fairly certain that I'm not doing anything wrong myself but I'm not experienced enough with HTML/CSS to guarantee it. Perhaps it might be a result of elements I've added to the offscreen-canvas, or maybe how I added the tooltip to the "button". Accordingly, here's a chunk of code showing the related portions. I've also attached a GIF of the issue.
```javascript
...
<li data-uk-tooltip title="Resource Types" >
                <a href="#offcanvas-1" data-uk-offcanvas="{mode:'slide'}">
                  <span class="uk-icon-bars uk-icon-medium uk-icon-hover"/>
                </a>
                <div id="offcanvas-1" class="uk-offcanvas" aria-hidden="true">
                    <div class="uk-offcanvas-bar" mode="slide">
                        <div class="uk-panel"><span class="uk-text-large uk-text-bold">Resources</span><a href="javascript:UIkit.offcanvas.hide(false)" class="uk-close uk-close-alt uk-align-right"></a></div>
                        <ul class="uk-nav uk-nav-offcanvas" data-uk-nav>
                          <li class="uk-active">
                            <a>Actors
...
```
![tooltip-offscreen-issue](https://cloud.githubusercontent.com/assets/4451272/19537270/f450f5a0-9614-11e6-80ba-7dbf3fbb6697.gif)

Based on my search for this issue here, I might be able to force disabling the tooltip by setting the link to inactive when triggering the offscreen-canvas, and by re-enabling it when closing the offscreen-canvas (since inactive elements don't display tooltips, based on other people's issues)? Not sure how I might go about doing that though...

**Comment by Intiligent** [comment]
by default offcanvas has z-index: 1000; tooltip has z-index: 1030;
try change z-index for offcanvas more than z-index tooltip (in your custome css file)

**Comment by Hectate** [comment]
That cleared it up perfectly. Much appreciated; I wouldn't have thought to look for a z-index myself. Thanks!
