### ISSUE TITLE
Cannot read property 'removeClass' of undefined in slideshow.js:368

### ISSUE THREAD

**Issue by AbdallahBedir** [uikit/uikit#2094]
The slideShow working good but there is an error in the console appears every time the slider change to new slide "Cannot read property 'removeClass' of undefined in slideshow.js:368" .
this is my html markup : 

```
<div data-uk-slideshow >
            <ul class="uk-slideshow uk-slideshow-fullscreen">
                 <li>
                    <img src="images/ΚΑΤΟΙΚΙΑ.jpg" width="" height="" alt="">
                 </li>
                <li>
                      <img src="images/slide-banner2.jpg" width="" height="" alt=""> 
                </li>                                                   
                <li>
                    <img src="images/slide-banner3.jpg" width="" height="" alt="">
                 </li>
            </ul>           
                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-                         slideshow-item="previous">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                </a>
                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slideshow-item="next">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>   
                </a>
        </div>
```

and this is the js:
   var slideshow = UIkit.slideshow(".uk-slideshow", {
                animation:'fade',
                duration:500,
                autoplay:true,
                pauseOnHover:false,
                autoplayInterval    :5000
    });
Iam Including all the required : 
        <link rel="stylesheet" href="css/uikit.min.css">
        <link rel="stylesheet" href="css/slideshow.min.css">
        <link rel="stylesheet" href="css/slideshow.almost-flat.min.css">
        <link rel="stylesheet" href="css/slideshow.gradient.min.css">
       <script src="js/uikit.js"></script>
        <script src="js/slideshow.js"></script>
        <script src="js/slideshow-fx.js"></script>

**Comment by dscafati** [comment]
Same problem

**Comment by dscafati** [comment]
My problem was that I was instantiating the slideshow twice, because I had two data-uk-slideshow nested. I think you problem is that you are instantiating it again manually, but the attribute data-uk-slideshow does the same. So the autoplay fails and the buttons works because these are two different instances of the slideshow, and the second one thought the elements were already processed and ignored them. Then $this.tiggers == undefined

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
