### ISSUE TITLE
Reverse Slider / Different positions to start the slide

### ISSUE THREAD

**Issue by BambachWebdesign** [uikit/uikit#2096]
Hello!
Let's say we got 12 elements in a Slider, 4 elements are visible (uk-grid-width-1-4). 
Normaly the Slider will show 1 to 4 and next 2 to 5 and so on.
I want to show the elements 9 to 12 and then going backwards 8 to 11 and further.

Is there a way to change the slider to make this possible?

Thanks for your help!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Regarding your problem, this is not possible by default you would have to change the slider js to your needs to achieve this. 

Thanks for your understanding,
Your UIkit Team
