### ISSUE TITLE
How to align Recaptcha in a modal window?

### ISSUE THREAD

**Issue by Fartuna** [uikit/uikit#2099]
How to align Recaptcha in a modal window? When browsing with the iPhone 4 Recaptcha goes beyond the edge?
![uikit](https://cloud.githubusercontent.com/assets/17340780/19626997/5aa9f980-9946-11e6-8351-591930883c03.PNG)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 
Thanks for your understanding,
Your UIkit Team
