### ISSUE TITLE
offcanvas not scrollable on iOS with uk-nav-sub / mobile Safari

### ISSUE THREAD

**Issue by atomtigerzoo** [uikit/uikit#2100]
I implemented the `uk-offcanvas` with a `uk-nav-sub` menu and it works fine on Windows and Android (Firefox) but not on iOS using mobile Safari. I simply can't scroll on the iPhone when the sub-nav is opened :/

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
