### ISSUE TITLE
Font awesome 4.7.0

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2101]
Please update.

**Comment by garri-ribeiro** [comment]
hey, I'll try to do this

**Comment by mktcode** [comment]
:+1:

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Here FontAwesome no longer is used, instead we created our own fonts that we needed for the components.

Thanks for your understanding,
Your UIkit Team
