### ISSUE TITLE
Dropdown on hover stopping working on Firefox

### ISSUE THREAD

**Issue by Brain8torm** [uikit/uikit#2104]
Some time ago, I saw that stopped working Dropdown on mouse hover, by clicking the mouse all ok. This is a problem in the browser (Firefox 47.0.1) or UIkit, Jguery or even in something? It does not work on all sites, even other developers to design UIkit. Rollback version UIkit, Jguery does nothing .. In Chrome it works fine.
Thanks.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
