### ISSUE TITLE
npm sass package

### ISSUE THREAD

**Issue by Ruto8** [uikit/uikit#2106]
Current npm package includes only less, but https://github.com/uikit/bower-uikit has both, less and sass.

How do you feel about making one for npm also? Or maybe including sass in the current package?

**Comment by rupurt** [comment]
@Ruto8 we added the ability to generate a package.json to the gulp build #2159

**Comment by philoest** [comment]
this will be added within UIkit3 as soon as SASS is ready :)

**Comment by rupurt** [comment]
Oh yeah!!! Thanks @philoest
