### ISSUE TITLE
uk-hidden-small not working on mobile 2.2.27

### ISSUE THREAD

**Issue by prtome** [uikit/uikit#2109]
Hello
I cannot make uk-hidden-small work on mobile. It perfectly work on desktop when decreasing the size of the window, perfectly works on jsfiddle (https://jsfiddle.net/prtome/947dmmmn/)
but if you put this code and access the page on a mobile, or through the developers tools of google, you'll see that it never takes into account the uk-hidden-small (I don't have access to web server where to put the page public)

```
<html>
<head><title></title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.2/css/uikit.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.2/js/uikit.js"></script>
</head>
<body>
<div class="uk-panel uk-panel-box uk-hidden-small">
   <h2>  hahahahah </h2>
</div>
<div class="uk-panel uk-panel-box uk-panel-box-primary uk-visible-small">
    <h2> smaaaaaaaaalllllll</h2>
 </div>
</body>
 </html>
```

What is it that I am doing wrong that makes it not working on mobile ? thanks

(edited to add </head> but does not change anything

**Comment by miladmeidanshahi** [comment]
it is a bug in this version and must be solved

**Comment by mohammad1991** [comment]
i need it ..... please ...... solve it .....

**Comment by llorcasantana** [comment]
Im using the lastet version (2.27.2) and work fine!

**Comment by prtome** [comment]
I am also using 2.27.2 and cannot make it to work. It works if I shrink my window on a desktop, but not from my smartphone. is it possible for you to show me the code that works ? so like that I can see where I am wrong in my code, I really can't find it. 
Thanks

**Comment by llorcasantana** [comment]
what OS and explorer are u using?

**Comment by prtome** [comment]
on the phone is ios10.1.1 and safari
on the mac (10.12.1)  is chrome, Version 54.0.2840.87 (64-bit). I use the developer tools and try to simulate the various mobiles. 
with the code I put at the top of the page, always says "hahahahaha" instead of "smalll"

**Comment by llorcasantana** [comment]
I don't have IOS but check my instagram (vert.prince) there is a pic of my
web that I use notifications on desktop and movile. On movile the
notifications is uk-visible-small and on desktop is uk-hidden-small. Like
your code but other content. Are u download a custom css?

**Comment by prtome** [comment]
no, the example above has no custom nothing, as you see I even use the cdnjs libraries.
if you put my example on you site or computer, does it work correctly ? if it does it means there is something wrong with my computer - it it does not, and your code works, it means there is something wrong with my code.
I am not on instagram, and when I tried to check I could see nothing

**Comment by llorcasantana** [comment]
Try put this in your local css file
@media (max-width: 767px) {
    .uk-hidden-small{
         display: none !important;
    }
}

**Comment by llorcasantana** [comment]
![quickmemo _2016-11-18-10-15-23](https://cloud.githubusercontent.com/assets/10922965/20434971/366dab70-ad78-11e6-9d46-16259474a238.png)
I put this on my code.

**Comment by prtome** [comment]
ok thanks so something is wrong on my side.  Because even adding the code above does not change anything. I wonder what it can be, since the code is simple, I have no local css, and I am using only hosted js and css. Wonder if the problem is mac oriented
Thanks for your help, I'll try to install my piece of code in another machine and check.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
