### ISSUE TITLE
uk-tabs will change from click and dragging mouse inside tab content in IE, Edge, and older Chrome

### ISSUE THREAD

**Issue by EricJammin** [uikit/uikit#2110]
Using the uk-tab functionality, we have run into a major bug that occurs in older versions of Chrome + newest version on older OSX, plus newest versions of Edge and Internet Explorer.

While inside an active uk-tab, if I click and drag to the left or the right, the active tab changes. This is a major issue for us. Here is an example:  http://codepen.io/eroc/pen/NRVJKB

Click next to the h1 inside the tab's content, and drag to the left or right and you will see the tabs change. 

I have observed this behavior on the following operating systems and browsers:
Mac OS X Mavericks v.10.9.5 - Chrome - latest version 54.0.2840.71
Mac OS X El Capitan v.10.11.6 - Chrome version 53.0.2785 (it is working in latest v 54.0.2840.71)
Windows 10 - Microsoft Edge - latest version 38.14393
Windows 10 - Microsoft IE11 - latest versions 11.187.143

*please note the windows machines are NOT touch devices.

**Comment by EricJammin** [comment]
Hi, this is a very critical issue, can someone please take a look?

**Comment by luetn** [comment]
Hi Eric
Can't confirm with Google Chrome Version 54.0.2840.71 / MacOS Sierra 10.12.1
Maybe i am doing wrong?

**Comment by EricJammin** [comment]
Hey Luetn,
The newest version of Chrome (v54.0.284.71), is only affected on older MacOS, like 10.9.5

For  MacOS 10.11 (El Capitan) or 10.12 (Sierra), the issue is resolved with the latest version of Chrome. I did however see the bug in the previous version of Chrome 53.0.2785

If you have access to a Windows machine, could you try with Edge or IE11?

**Comment by luetn** [comment]
I will have a look tomorrow.

**Comment by luetn** [comment]
confirmed with IE11 and WIN 7

**Comment by EricJammin** [comment]
Thanks, appreciate you looking into it.
We've been really thrilled with everything else UIkit has to offer, but the tabs are a central component to our app.

**Comment by EricJammin** [comment]
Hey all, checking in to see if there has been any progress on this issue? Or at least been able to identify the root cause of the issue? Thanks.

**Comment by Orsat** [comment]
This is still not resolved I see...

We have tabs where inside we display long tables, every time the user needs to scroll to the right to see the content of the table... it switches the to the next tab instead...extremely annoying.

Could we please have someone look into this as I see this issue being reported by more and more people

Thank you in advance

**Comment by GreenWisdom** [comment]
I just started experiencing this issue.  I'm running OS X Yosemite 10.10.5 and have the latest version of Chrome installed.

**Comment by GreenWisdom** [comment]
In Google Chrome, when trying to pan a google map on a page that includes tabs, the tabs instantly change.  These issues did not previously exists for me, so I assume they are due to a recent chrome update.  Is anything being done to fix this issue?

**Comment by EricJammin** [comment]
@GreenWisdom that's how I initially discovered the issue, loading a tab with a google map and going to drag the map. Then I realized this behavior would happen without a google map and was indeed a UIkit issue.

Has anyone made any progress?

**Comment by GreenWisdom** [comment]
@EricJammin It only started happening to me within the past couple of weeks (I assume due to a recent Chrome update), prior to that I was not experiencing the problem (been developing this app in one form or another since August); but now its a major problem.  I see you initially created this issue back at the end of October; however, I wasn't experiencing anything like this then (and  Chrome has been set to auto update on my local machine).  Did this problem always exist for you or were your maps working correctly up to a point/chrome update?

**Comment by GreenWisdom** [comment]
@EricJammin I reached out to a developer experienced with UIkit regarding this issue, and this was his response..
"About this "issue" regarding tabs. It's more like feature rather than issue and this feature was there since Jan 2015 https://github.com/uikit/uikit/commit/0e358929ba625ee376acbd46818594021624ce71
On default swipe event is set to true to enable swiping across tabs. Please check options for switcher component (tabs are using this component) https://getuikit.com/docs/switcher.html#javascript-options
You can set swiping option to false: swiping:false to disable swipe events.
Please check second tabs here http://codepen.io/anon/pen/rjawzB"

This fixes the problem for me.  Let me know if it works for you.

**Comment by ambroisemaupate** [comment]
@GreenWisdom @EricJammin  I’ve got the same issue, **but** even using `data-uk-switcher="{connect:'#node-source-form-switcher', swiping: false }"` the swiping effect is still there. 

Especially when I’ve got some textarea or text input in my tabs, tab changes when selecting text, it’s a critical issue for me.

**Comment by GreenWisdom** [comment]
@ambroisemaupate Does it work if you remove `#node-source-form`? I'm not familiar with nodesource, so this is perhaps a wild shot in the dark, but if it works when you remove it, can you include the `node-source-form` is a `<div>` inside a tab instead?

**Comment by EricJammin** [comment]
@GreenWisdom I first noticed in while testing a web app in Internet Explorer and Edge. Then I saw it on my older mac running OSX Mavericks using the latest Chrome build, and noticed it on my newer Mac running El Capitan with a slightly older version of Chrome. Updating to latest Chrome fixed it for me on my new Mac at the time, but now the problem is present again.

Setting swiping: false is an interesting approach, good find! That would be a good solution for us since we wouldn't want the swipe ability even from touch screens as it would interfere with the google map dragging behavior.

I'd still love to see this issue actually solved though, as a click + drag with the mouse should not be handled as a touch swipe.

**Comment by EricJammin** [comment]
@ambroisemaupate Are you using this with the tab structure?

If so, try using `data-uk-tab` instead of `data-uk-switcher`

**Comment by GreenWisdom** [comment]
@EricJammin Thanks.  I agree, but at least this is a work around.  It seems like it would likely be easier to recreate the swipe feature correctly rather than trying to fix something that's obviously broken.

**Comment by ambroisemaupate** [comment]
👍  @EricJammin I switched to tab and issue is gone. 

I’ll try to update to latest UIKit version. It could help too 🤕. But many *class* and HTML structures changed since <=2.18

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team

**Comment by Roeefl** [comment]
Still in version 3

**Comment by Roeefl** [comment]
Thanks.

**Comment by h3786010** [comment]
`data-uk-switcher="{swiping:false}"`
