### ISSUE TITLE
Remove FontAwesome from core?

### ISSUE THREAD

**Issue by jsieler** [uikit/uikit#2111]
Isn't that better to remove it from the core? Uikit is so always behind the actual releases. It has not that much advantages to have it included.

**Comment by lupuxyz** [comment]
remove @import "core/icon.less"; from uikit.less

**Comment by jsieler** [comment]
@lupuxyz i mean not just for me, but globally.

**Comment by zzseba78** [comment]
Good news! https://twitter.com/getuikit

**Comment by jsieler** [comment]
Hm, that is good.... but... more icon packs? Is there some info about how much icons, which, will they be extended and supported by community?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Within UIkit3 we removed FontAwesome and using our own icons as @zzseba78 already mentioned. All the icons can be found [here](https://getuikit.com/docs/icon).

Thanks for your understanding,
Your UIkit Team
