### ISSUE TITLE
UIKit for Gantry5 ScrollSpy Group doesn't work properly!

### ISSUE THREAD

**Issue by Shmell77** [uikit/uikit#2119]
single item works, BUT group (data-uk-scrollspy="{cls:'uk-animation-fade', target:'.my-class', delay:300}") doesn't work properly, so i have to manually setup delay for each item...
Any fixes?

Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
