### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by KiarashS** [uikit/uikit#2120]
Dear,

First thanks for uikit.

I have a question, how we can use material design with uikit framework? is there a official support for material design in uikit?

**Comment by miladmeidanshahi** [comment]
i don't think so.

**Comment by naasking** [comment]
There are material design themes based on uikit. I found at least one good one on theme forest when I looked a few months ago.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
