### ISSUE TITLE
Problem with slideset navigation in Chrome

### ISSUE THREAD

**Issue by inviribus** [uikit/uikit#2121]
Hello to everybody 

I have an issue with uikit slideset component and especialy in navigation 

The website is made with joomla latest version 3.6.4

My website is http://wyndham.hit360.com and as you can see in the home page i have 2 modules the Hotel Highlights and the Special offers where i use the slideset component.

If you text the navigation in Mozilla Firefox and Microsoft Edge everything work fine but if you test it in Chrome when you try to navigate the page reloads and then shows the new

Can you help me why this happens?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideset component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
