### ISSUE TITLE
Notify and modal bug

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2122]
Fix please bug

to notice, too, was obscured

**Comment by kirich1368** [comment]
![default](https://cloud.githubusercontent.com/assets/18468664/19981173/dbfffd8a-a211-11e6-95ee-907c465f7a96.png)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
