### ISSUE TITLE
Datepicker return date

### ISSUE THREAD

**Issue by juaroal** [uikit/uikit#2125]
Hi,

I'm working in an website which needs arrival and return date. My issue is that the minimum date of the return date should be the arrival date. I have made this code:

```
jQuery("#arrival_date").on("change", function (event){
		
	var arrival_date = jQuery(this).val();
	jQuery("#return_date").val("")
	jQuery("#return_date").attr("data-uk-datepicker","{minDate:'"+arrival_date+"'}")
  });
```

But this code only works first time I select the arrival date. Checking the datepicker documentation I don't see anything to connect both calendars and I don't know if exists a way to solve it.

Any help?

Thanks in advance!

**Comment by pcdrivers** [comment]
```
    UIkit.ready(function() {
      var date1 = UIkit.datepicker(UIkit.$('#arrival_date'), { minDate: 0, format:'DD/MM/YYYY' }),
            date2 = UIkit.datepicker(UIkit.$('#return_date'), { format:'DD/MM/YYYY' });
      
      date1.on('change.uk.datepicker', function () {
          date2.options.minDate = date1.current.format('DD/MM/YYYY');
      });
      date2.on('change.uk.datepicker', function () {
          date1.options.maxDate = date2.current.format('DD/MM/YYYY');
      });
    });
```

I think this could use.

**Comment by juaroal** [comment]
Thank you very much! I don't really knew how to make it!

Regards!
