### ISSUE TITLE
Cannot resolve './locale' when i import the datepicker

### ISSUE THREAD

**Issue by DotNetAge** [uikit/uikit#2126]
When i use the webpack to import the uikit into my project i get this error:

WARNING in ./~/uikit/dist/js/components/datepicker.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/Ray/Projects/vue-grid/node_modules/uikit/dist/js/components
 @ ./~/uikit/dist/js/components/datepicker.js 1113:20-47

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Datepicker component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team

**Comment by elasticsteve** [comment]
This is not cool! We are working on a  serious platform using UIkit2 for a year and have this fault. To just abandon everything because you have a (non-working) V3 out is insane!
I really regret I got myself involved with UIkit.

**Comment by hotrush** [comment]
Hi @DotNetAge, have you found any workaroud?

**Comment by pomeo** [comment]
It's not problem of datapicker, it's problem in moment.js which included.
Can be fixed by `new webpack.IgnorePlugin(/^\.\/locale$/)` in webpack config
