### ISSUE TITLE
Add tags component for forms (Like select2) to Uikit 3

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#2127]
Tags is very useful component that enhancement selects with may items for searching, multi selection and custom design.

**Comment by pcdrivers** [comment]
What is your question?

**Comment by philoest** [comment]
What exactly do you mean by a tags component? Tags as something similar to labels or something completely different?

**Comment by philoest** [comment]
Had a talk about this with @saschadube and we don't see this within UIkit, none the less Select2 should work perfectly as an addition to UIkit.
