### ISSUE TITLE
Problem in Safari with uk-navbar

### ISSUE THREAD

**Issue by h3llofr1end** [uikit/uikit#2128]
Hello, guys, we use your sidebar and it works correctly in Chrome and Mozilla, but on Safari we have errors
For example site: http://www.23-15.com/
How can we fix it? In Safari i see next error on load page
![image](https://cloud.githubusercontent.com/assets/19621807/20169625/a3a93a14-a739-11e6-9d10-6cbd644a2cd8.png)

**Comment by h3llofr1end** [comment]
pls help

**Comment by philoest** [comment]
Are you using Safari for Windows? The support for that has been ended by Apple already in 2012...
