### ISSUE TITLE
Uikit.slideshow

### ISSUE THREAD

**Issue by nono1974** [uikit/uikit#2131]
Hi

I am trying to manage the slideshow UIKit object with javascript.

I would like to know which js lines i need to display the next slide ?

<ul id="myslideshow" data...>
<li id="slide1"...
<li id="slide2"...
</ul>

<button id="next"...>

var slideshow = UIkit.slideshow("#myslideshow");

$("#next").click(function() {
slideshow.show(???);
}

**Comment by Jiab77** [comment]
Check the doc, https://getuikit.com/docs/slideshow.html
You may just have to use elements that way:

    <a href="" data-uk-slideshow-item="previous"></a>
    <a href="" data-uk-slideshow-item="next"></a>

But I guess you may replace these links by javascript code. I would advise you to always take a look at their really well done documentation there https://getuikit.com/docs/documentation_get-started.html

For core elements: https://getuikit.com/docs/core.html
For components: https://getuikit.com/docs/components.html

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
