### ISSUE TITLE
Slider (infinite false) jumping from last slide to the first on resize

### ISSUE THREAD

**Issue by oliverschwanz** [uikit/uikit#2132]
Uikit -> Slider -> Disable Infinite Scrolling -> Example
https://getuikit.com/docs/slider.html#scrolling

Navigate to the last slides (you have to see the slides 9-12),
then resize the window or call `$(window).trigger('resize')` in the browser dev tools.

The slider jumps back to the first slide.

This behavior feels strange. Bug or feature?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
