### ISSUE TITLE
accordion visible when page load

### ISSUE THREAD

**Issue by oxananana** [uikit/uikit#2133]
all accordion panels are visible when page load (before init). 
i don't understand why developers decided to do so. 
do you plan to fix it (like bootstrap accordion)?
how to solve this problem now?
thanks.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
