### ISSUE TITLE
Dropdown doesn't respond on first tap

### ISSUE THREAD

**Issue by simonmurdock** [uikit/uikit#2134]
When using Chrome on Android (7.1 / Nexus 6P) and visiting https://getuikit.com/docs/dropdown.html, the first tap of the example "Click Me" does nothing.

The 2nd tap displays as expected.

If you refresh you get the issue again.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
