### ISSUE TITLE
Is UI Kit "dead"?

### ISSUE THREAD

**Issue by lorddonk** [uikit/uikit#2135]
I used to use UIkit and the Warp templates for Wordpress. I see now Yootheme has stopped providing a free widgetkit and warp base template to work off their latest release and is now making you pay for their bloated website builder contraption instead.

Does this mean the UI Kit is no longer going to be updated and provided for free? I would like to know before I place clients onto a system where upgrades are now behind a paywall or it will not be updated any further.

I understand support for it may continue but as far as developing new features, does anyone know what the status of that is?

**Comment by lupuxyz** [comment]
take a look at twitter.com/getuikit or yootheme.com/blog

**Comment by saschadube** [comment]
Dude, where are you living?

**Comment by lorddonk** [comment]
Sascha, no disrespect (assuming you are the same Sascha that replies over at the YT sites) and maybe I'm an idiot but I don't see a clear answer for this anywhere.

Will the UI kit 3 when it comes out be a free offering like in the past? Or is it going to be bundled with the new framework thing and you have to pay for the "package" with the website builder et al?
