### ISSUE TITLE
Modal background in Trigger mode

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#2137]
Hi

In your modal triggering example when switching from one modal to the other, the background is closed then reopened which is a little annoying

It would be nice if we can keep the background and display/hide only modal dialog

Regards

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
