### ISSUE TITLE
Checkbox and radio button custom style

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#2140]
checkbox and radio button show defiance in main browsers, in IE and Edge show native and custom style when checked and in chrome is good and in firefox show custom style but have little problem. 

![checkbox radio](https://cloud.githubusercontent.com/assets/1667525/20456865/62ee0b32-ae94-11e6-83e7-eee02ec8ab84.png)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
