### ISSUE TITLE
Pagination over Dynamic Table

### ISSUE THREAD

**Issue by Apkahym** [uikit/uikit#2142]
I have a php code that generate a table with dynamic raws quanity.
And i need generate pages with 10 items per each.
The table structure is classic

```
<table>
	<thead>...</thead>
       <tbody>
              <tr>
                     <th></th>
                     <th></th>
                     <th></th>
              </tr>
       <tbody>
<table>
```

And the code for `<ul>` pagination is:

`<ul class="uk-pagination" data-uk-pagination="{items:100, itemsOnPage:10}"></ul>`

(copy and paste from a UIKit docs)

This generate `<ul>` element of pages but not cut the table on 10 items and not change to pages.

What is i do bad?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Regarding your problem, the dynamic pagination just gives you the frontend JS part for an AJAX pagination. So you can listen for the next and previous to send a AJAX request to your server to get the next 10 items. The dynamic pagination, doesn't modify your HTML elements or cuts them into peaces on its own.

Thanks for your understanding,
Your UIkit Team
