### ISSUE TITLE
Dynamic grid (data-uk-grid) not working?

### ISSUE THREAD

**Issue by giano574** [uikit/uikit#2143]
I am trying to use the dynamic grid, but I just can't get it to work. It seems that it just adds a margin to the right of each child element and stacking them instead of arranging them.

I am using the latest version.

My code is:

```html
<!DOCTYPE html>
<html>
 <head>
  <meta content="da" http-equiv="Content-Language" />
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
  <meta name="viewport" content="width=device-width" />
  <link type="text/css" rel="stylesheet" href="uikit/css/uikit.min.css" />
  <script type="text/javascript" src="jquery-3.1.1.min.js"></script>
  <script type="text/javascript" src="uikit/js/uikit.min.js"></script>
  
  <style>
   .uk-panel {
    height: 90px;
    background: #ccc;
    border: 1px solid #aaa;
   }
  </style>
 </head>
 
 <body>
  <div class="uk-grid-width-small-1-2 uk-grid-width-medium-1-3 uk-grid-width-large-1-4 tm-grid-heights" data-uk-grid="{gutter: 20}">
   <div data-grid-prepared="true">
    <div class="uk-panel">1</div>
   </div>
   <div data-grid-prepared="true">
    <div class="uk-panel">2</div>
   </div>
   <div data-grid-prepared="true">
    <div class="uk-panel">3</div>
   </div>
   <div data-grid-prepared="true">
    <div class="uk-panel">4</div>
   </div>
  </div>
 </body>
</html>
```
![grid](https://cloud.githubusercontent.com/assets/17013720/20685601/484d5472-b5b5-11e6-9be7-24f8ee178d09.png)

**Comment by WebStation12** [comment]
Hi,
I think you need to load the js for this component
 <script type="text/javascript" src="uikit/js/components/grid.min.js"></script>

**Comment by giano574** [comment]
Thank you so much.
I can't find anything about that in the documentation, but it does make sense.

**Comment by Siton-Systems** [comment]
Her you find the docs about this issue:
https://getuikit.com/docs/documentation_get-started.html#file-structure

load advanced  component js + advanced component css (not always)
