### ISSUE TITLE
Complete Projekt is shrinking 

### ISSUE THREAD

**Issue by FelixKre** [uikit/uikit#2145]
Hi! 

Big issue:

When I navigate throw my menu I notice that by some pages suddenly the whole project is shrinking from the left to the right site of about 1px. I have no idea why this is happening?!?! I am using Php include command for header, navigation and footer. My command structure is for example

<div class=" uk-container uk-container-center">

        <div class="uk-grid">
                <div class="uk-width-1-2></div>
                <div class="uk-width-1-2></div>
        </div>

</div>

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
