### ISSUE TITLE
uk-hidden-* / uk-visible-* still causing top-margin on next element in vertically stacked grid

### ISSUE THREAD

**Issue by alterkater** [uikit/uikit#2146]
If first element in vertically stacked grid is invisible, the following element (now first visible element) still receives a top-margin. To my understanding, grid should ignore invisble elements.
thanks!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
