### ISSUE TITLE
offset for uk-overlay-slide

### ISSUE THREAD

**Issue by alterkater** [uikit/uikit#2147]
Would be awesome if we could set an offset for uk-overlay-slide to use for a permanently visible title + expandable content (via overlay).
thanks!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if this is can be done with the new transition and overlay component, if this is not the case please open a new issue which we can label as a feature request :)

Thanks for your understanding,
Your UIkit Team
