### ISSUE TITLE
actions on "Cancel" button click like "OK" button

### ISSUE THREAD

**Issue by minivetsystem** [uikit/uikit#2148]
can anyone help me how to add some actions on on "Cancel" button click like "OK" button click in prompt modal

thanks

**Comment by eduduardo** [comment]
https://github.com/uikit/uikit/pull/2160 this should work

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
