### ISSUE TITLE
Feature Request: Calendar with multiple months

### ISSUE THREAD

**Issue by Garfield-fr** [uikit/uikit#2149]
Example:

![9ipmm](https://cloud.githubusercontent.com/assets/48578/20850338/e2ea8b4e-b8da-11e6-9eb7-b9832dcbd5e9.png)

Example options:
```
var datepicker = UIkit.datepicker(element, { 'numberOfMonths': 3 });
```

Thanks

Bertrand

**Comment by luetn** [comment]
:+1:

**Comment by jerry1970** [comment]
LOL, I completely missed the datepicker component, so thanks for this question!

**Comment by philoest** [comment]
The Datepicker component will be completely reworked for UIkit3, we are trying to add this feature, but the biggest problem coming with this functionality is the responsiveness, how this works on smaller screens and in smaller areas. We will see if we will find a solution for this that satisfying.
