### ISSUE TITLE
clsactive bug

### ISSUE THREAD

**Issue by bobitza** [uikit/uikit#2150]
When i put clsactive on data-uk-sticky, and add a class to change box-shadow, navbar change index or something because go in back of containers

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
