### ISSUE TITLE
Using dotnav with the slider component

### ISSUE THREAD

**Issue by JayBox325** [uikit/uikit#2151]
I have added the dotnav to a data-uk-slider element and the functionality is there and working, but the JS is not adding the uk-active class.

Could this be added, or could there be a section added to the documentation about using the dotnav component with the slider as there's only an example for it on the slideshow section.

Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slider component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
