### ISSUE TITLE
data-uk-svg Styles Incorrect in IE11

### ISSUE THREAD

**Issue by malcalevak** [uikit/uikit#2152]
I was excited to take advantage of the data-uk-svg capability to inline my SVGs, but was noticing I was getting only black images in IE11.
Turns out it's doing something screwy with the embedded style tags. I'm not sure what exactly, but if I edit it in the dev console, and simply add a space, it suddenly fixes everything.
This doesn't appear to be an issue in other browsers that I tested (Firefox and Chrome).
I tried messing around to fix it, but I'll confess the section in question is above my head.

**Comment by malcalevak** [comment]
Ok, I did find an extremely ugly fix by adding:
```javascript
$($svg).find('style').append(' ');
```
at roughly line 1299, or before the 
```javascript
img.replaceWith($svg);
```
that's at the end of the 
```javascript
cacheSvgs[src].then
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
