### ISSUE TITLE
Meteor JS - Using the data-uk-search="{source:''} 

### ISSUE THREAD

**Issue by GAWKmdk** [uikit/uikit#2154]
Hi there,

I am trying to hook up my database collection to display using the uikit search form and METEOR JS. 

I don't think I have 100% understood the best practice to go about hooking this up (since putting a source ' .json ' file with the collection.js seems like a insecure way to channel insert injections ???? not to mention I haven't been able to find a package that generates .json files to the local directory or source the directory for a /test.json file in the public directory. 

Anyways here is the code I have -- perhaps you can see what is missing to get the source linked up or let me know if there are links for people who have done this already?

Note: I have installed the mrt:JSON package so JSON.parse is managable. 

Cheers xx 

**The HTML form looks like this** 

 ```
<form class="uk-search uk-autocomplete" data-uk-search="{source:'/sample_search.json'}" data-uk-autocomplete="{source:'/sample_search.json'}">

    <input class="uk-search-field" type="search" placeholder="Search...">

    <!-- This is the dropdown, which is injected through JavaScript -->
    <div class="uk-dropdown uk-dropdown-search">
        <ul class="uk-nav uk-nav-search">
        
            <ul class="uk-nav uk-nav-search">...</ul>
            <hr>
            {{#each collection_display}}
            {{#each getData}}
            <a href="/ironrouter_placeholder/{{_id}}"> Found: {{title}} </a>
{{/each}}
      {{/each}}  
        </ul>
    </div>

</form>
```

and the helper to this html looks like this: 
```
```
Template.placeholdertemplate.helpers({
    
  
    getData: function() {
    
        // I am trying to get the search to return in JSON format all matches with the title: field
     
        
   var search = Collection.find({title:""}).fetch();
        
    var getRawData = [];
    for(var q in search) {
      if(search.hasOwnProperty(q)) {
        getRawData.push(JSON.parse(search[q].data));
        console.log(getRawData);
        return getRawData;
      }
    }
    },
    collection_display: function() {    
  
      return Collection.find({}, {sort: {createdOn: -1}});
     
   },  
    
});
```

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
