### ISSUE TITLE
Slideshow Transition Glitch in IE11

### ISSUE THREAD

**Issue by leerjordan** [uikit/uikit#2155]
Hi

There appears to be a glitch with the slideshow component in IE11. When the images transition, they flash and do not change smoothly. Would you be able to look into this please?
Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Slideshow component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
