### ISSUE TITLE
Missing default styles when using SASS

### ISSUE THREAD

**Issue by rhache** [uikit/uikit#2156]
I'm not sure what I'm doing wrong, but for some reason default styling seems to be missing when I using uikit with SASS.  I've download uikit using gulp/bower, and currently I have the following lines in at the top of my main SASS file:

```sass
@import "../bower_components/uikit/scss/uikit-mixins.scss";
@import "../bower_components/uikit/scss/uikit.scss";
```

Some uikit styling does work. For example the responsive grid is fully functional, but a lot of styling seems to be missing for buttons, blocks, etc. Here's what `uk-panel` looks like on my site:

![local-panel](https://cloud.githubusercontent.com/assets/585729/21151842/610cb5ee-c13a-11e6-8727-89bb5836f6e2.png)

As opposed to this (markup is exactly the same in both cases):

![default-panel](https://cloud.githubusercontent.com/assets/585729/21151869/7ddb3704-c13a-11e6-90ff-25649505c1ba.png)

Can anybody let me know what I'm missing? From the documentation I'm including the CSS files that should be included

Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
UIkit3 is not yet available in SASS but we are working on that, please let us know if this issue consist when it is released. 

Thanks for your understanding,
Your UIkit Team
