### ISSUE TITLE
Modal event "show.uk.modal" not fire with UIkit.modal.blockUI

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#2161]
Hi guys. Long time we have not news from you(
UiKit 3 has a good new features and already want to try it.

My question about modal. Not work event trigger **show.uk.modal** for dialog windows (alert, confirm, prompt, BlockUI), but event hide.uk.modal work fine. Maybe i do somthing wrong.

```javascript

var modal = UIkit.modal.blockUI('<a href="" class="uk-modal-close uk-close uk-close-alt"></a> Any content...').on({
    'show.uk.modal': function(){
        console.log("EVENT::SHOW its not work");
    },
    'hide.uk.modal': function(){
        console.log("EVENT::HIDE its work");
    }
});
```
Example: http://codepen.io/Intiligent/pen/yVZLdm

**Comment by philoest** [comment]
Did the new [docs](https://getuikit.com/docs/modal) help you to find the solution for your problem or are there further questions regards this?

**Comment by janschoenherr** [comment]
This has been resolved in the dev branch. Please reopen if issue persists after next Beta release.

**Comment by nodarai** [comment]
Hello!
Do you plan to implement this fix to UiKit 2?
