### ISSUE TITLE
Is't possible a continuous animation?

### ISSUE THREAD

**Issue by biapar** [uikit/uikit#2162]
Is't possible a continuous animation?

**Comment by arysom** [comment]
In animation component I cant see any, only class uk-icon-spin rotates infinite

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
