### ISSUE TITLE
Slideshow autoplay doesn't continue if you click on slidenav

### ISSUE THREAD

**Issue by arrowthemes** [uikit/uikit#2163]
The issue happens with uk-slideshow with autoplay:true. As long as the navigation arrows (slidenav) are not clicked, the autoplay works ok. If you click on any slidenav, the autoplay stops working.

**Comment by Siton-Systems** [comment]
Also in my code i find this issue (on 2.27.2):
https://codepen.io/siton/pen/pRvvEg

**Comment by m0yP** [comment]
Mine does the same! Any workaround?

**Comment by arrowthemes** [comment]
@aheinze any help will be appreciated

**Comment by philoest** [comment]
This is a feature not a bug, if the user wants to see the second image the slideshow shouldn't move image away again. 
But since this is quite often asked we are rethinking this for the UIkit3 Slideshow component.
