### ISSUE TITLE
Can't get scrollspy-nav to work with external anchor links

### ISSUE THREAD

**Issue by lesaff** [uikit/uikit#2165]
Scrollspy works great on this situation
```
<ul class='uk-subnav' data-uk-scrollspy-nav="{closest:'li', smoothscroll:true}">
    <li><a href="#nav1">Nav 1</a></li>
    <li><a href="#nav2">Nav 2</a></li>
</ul>

<div id="nav1"></div>
<div id="nav2"></div>
```
But not when there are external anchor links
```
<ul class='uk-subnav' data-uk-scrollspy-nav="{closest:'li', smoothscroll:true}">
    <li><a href="/another-page/#nav1">Nav 1</a></li>
    <li><a href="/yet-another-page/#nav2">Nav 2</a></li>
</ul>

<div id="nav1"></div>
<div id="nav2"></div>
```
Is there any parameters I should use to accomplish this?

Thanks

**Comment by Siton-Systems** [comment]
"no sense" to use "another-page" because scroll spy is "spy" on "in-page areas" depend on your scroll position (This all the idea of this pattern). You ever seen example like this working?

In your example -- id="nav1" != "/another-page/#nav1"

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
