### ISSUE TITLE
uk-offcanvas gap

### ISSUE THREAD

**Issue by jiexika** [uikit/uikit#2169]
Appears in safari on iPhone at random when I click the uk-navbar-toggle button several times, there is a gap at the edge of screen.
![image](https://cloud.githubusercontent.com/assets/22975621/21516715/aa820acc-cd14-11e6-88fb-47ef546c8ef0.png)
Hope your team can fix it. Thx!

**Comment by canhkieu** [comment]
I thing it's OK. What do you want?

**Comment by jiexika** [comment]
I want to know why this happened

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
