### ISSUE TITLE
12 columns grid ?

### ISSUE THREAD

**Issue by franck34** [uikit/uikit#217]
Hi, thanks for uikit !

Question, i've started a really well designed project with uikit 3 weeks ago. I didn't read all the doc before choose uikit so i didn't see that grid system was limited to 10 columns, compared to most grid system which provide 12 columns.

I'd like to continu to work with uikit, but i really need 12 columns grid. If i need to use a third party grid, i think i'll just abandon uikit. I don't like this idea.

Why this limitation ?

Can it be improved ?

How ?

Thanks a lot
Cheers

**Comment by triooleg** [comment]
[uikit-addon-grid.css.zip](https://github.com/uikit/uikit/files/299009/uikit-addon-grid.css.zip)
i added to grid 1-7 1-8 1-9

**Comment by badpenguin** [comment]
The problem with ```@mixin hook-width-misc(){}``` is that your @s classes are going to override any @m, @l, etc. core classes.

**Comment by ijs77** [comment]
> The problem with `@mixin hook-width-misc(){}` is that your @s classes are going to override any @m, @l, etc. core classes.

use uk-child-width-expand
