### ISSUE TITLE
nestable component serialize for non-integer data

### ISSUE THREAD

**Issue by NikitaUsefi** [uikit/uikit#2175]
Hi,
I'm using nestable component with this pattern:
```
<ul class="uk-nestable" data-uk-nestable="{handleClass:'uk-nestable-handle'}">
    <li class="uk-nestable-item" data-test="1" data-id="4c661d08-a1d2-e611-9fb9-0c5b8f279a64">
        <div class="uk-nestable-panel">
            <div class="uk-nestable-handle"></div>
            ...
        </div>
    </li>
</ul>
```
and I used this line to get the serialized data:
`JSON.stringify($(".uk-nestable").data("nestable").serialize())`
but I get false for the non-integer data:
[{"test":1,"id":false,"children":[{"id":false,"children":[{"id":false}]}]}]
what can I do to fix this?
thanks in advance

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The Nestable component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
