### ISSUE TITLE
Uikit 3 : Update icon.less background-url with a less variable like others

### ISSUE THREAD

**Issue by trk** [uikit/uikit#2178]
For without touching core uikit files: can you update https://github.com/uikit/uikit/blob/develop/src/less/components/icon.less#L44 with a variable like here https://github.com/uikit/uikit/blob/develop/src/less/components/close.less#L26. This way we can replace this variable after file call.

**Comment by saschadube** [comment]
Thanks! Fixed https://github.com/uikit/uikit-site/commit/95a4b1500cab6f366dfae3fc08adc1bbfc81312c

**Comment by saschadube** [comment]
Thanks! Fixed https://github.com/uikit/uikit/commit/8b46c16eed7b69342f8ad86f684335d9e36b8f21
