### ISSUE TITLE
duplicate labels in media tag

### ISSUE THREAD

**Issue by drcobar** [uikit/uikit#2179]
In Documentation you have

.uk-card-media-top	This class indicates that the media element is aligned to the top.
.uk-card-media-top	This class indicates that the media element is aligned to the bottom.

should be 
.uk-card-media-top	         This class indicates that the media element is aligned to the top.
.uk-card-media-bottom	This class indicates that the media element is aligned to the bottom.

**Comment by rowanwins** [comment]
Pull request made [here](https://github.com/uikit/uikit-site/pull/3)

**Comment by janschoenherr** [comment]
Fixed with uikit/uikit-site@7b6a3f7ddf518a288f5ca2192c0394f586697e43
