### ISSUE TITLE
UIkit 3 idea: use semantic <button> instead of <a>

### ISSUE THREAD

**Issue by shrpne** [uikit/uikit#2181]
I think it's better to use `<button type="button">` instead of `<a href="#">` for elements which works like buttons (ex.: tabs, slidenav arrows)

`<button>` for buttons and `<a>` for links

**Comment by nblackburn** [comment]
I think both have their use cases.

**Comment by janschoenherr** [comment]
Closing for now. This does not seem to be an issue. UIKit lets you use buttons or links.

**Comment by shrpne** [comment]
I suggest to use this approach in documentation. So docs snippets will follow best practices and other people can take them.
