### ISSUE TITLE
uk-navbar-right not pushing elements to the right

### ISSUE THREAD

**Issue by alecholmez** [uikit/uikit#2183]
Navbar code:
```html
	<nav class="uk-navbar-container uk-margin" uk-navbar>
	    <div class="uk-navbar-left">
	        <a class="uk-navbar-item uk-logo" href="#">Logo</a>

	        <ul class="uk-navbar-nav">
	            <li>
	                <a href="#">
	                    <span class="uk-icon uk-margin-small-right" href="#" uk-icon="icon: star"></span>
	                    Features
	                </a>
	            </li>
	        </ul>
	    </div>
		
		<div class="uk-navbar-right">
			<div class="uk-navbar-item">
				<form>
					<input class="uk-input uk-form-width-small" type="text" placeholder="Input">
					<button class="uk-button uk-button-default">Button</button>
				</form>
			</div>
		</div>
	</nav>
```

<img width="1946" alt="screen shot 2017-01-09 at 4 53 44 pm" src="https://cloud.githubusercontent.com/assets/5223714/21785131/42ea9b14-d68c-11e6-827d-84d81725de4d.png">

The elements will not float to the right. Tried resizing the browser window to see if it was a media scale issue but it is for all sizes.

## Note
The issue does not appear when you use:
```html
<nav class="uk-navbar uk-margin" uk-navbar>
```
`uk-navbar-container` seems to be the culprit

**Comment by zachkont** [comment]
Are you loading your javascript files in the end of the page? If yes, try doing it in the beginning, that fixed many issues for me.

**Comment by janschoenherr** [comment]
Please create a http://codepen.io/pen/ example of the issue. Thanks.

**Comment by nickstamat** [comment]
Codepen loads scripts just before the `</body>` tag by default. If you try to include them inline first, then the code posted above by @alecholmez works as intended, like @zachkont said.

Proof: http://codepen.io/nstam/pen/dNGPoX

This behaviour is new to v3.0 and I guess that it has to be fixed. With v2.x, I used to load all scripts at the bottom of the page and everything worked properly.

**Comment by alecholmez** [comment]
Interesting... This might cause problems if I'm using `jspm` to load in my CSS or say, using `gulp` to compile everything. In static HTML I guess this isn't a problem. Any recommendations on this?

**Comment by jerry1970** [comment]
Same problem here.

**Comment by nickstamat** [comment]
v3.0.0-beta.2 has fixed this issue.

**Comment by alecholmez** [comment]
Awesome! @nickstamat thanks nick!

**Comment by roja** [comment]
This is occurring again in Beta.40 Unless the javascript runs the left and right navbar elements are pushed onto separate lines. This causes a flash / DOM repaint when the page loads the JS.

**Comment by jameschunger** [comment]
Apologize to comment on a closed issue, but I am seeing this same issue with React and UIKit. (3.0.0-beta.42)

I had been using Ember and UIKit (which did not have this issue) and removing `uk-navbar-container` also prevents this from occurring.

**Comment by williamsb** [comment]
I know this issue is closed but I recently ran into the same problem, where I could not center or align to the right. The code I used came directly from the documentation on the website under 'markup' tab.

I compared the 'markup' code to the the source code for the 'preview' example used and noticed that they were different.

Markup (did not work):

```
<nav class="uk-navbar-container uk-margin" uk-navbar> ... </nav>
```

Preview source code (did work):

```
<nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar> ... </nav>
```
Seems like the markup code is missing the 'uk-navbar' class and I am wondering if this is an error in the markup code in the documentation.

**Comment by iyobo** [comment]
This is still an issue in UIKit 3.0.3

**Comment by aarongerig** [comment]
@iyobo Works fine on the [official documentation page](https://getuikit.com/docs/navbar#multiple-navigations), right?

**Comment by DonkyToM** [comment]
@iyobo I tried to start with UIKit last weekend but ran in the same issue as described here. Hm, maybe this is still a issue and I gave up UIKit to early :/ I will try it again tomorrow.

**Comment by iyobo** [comment]
So it seems the issue is with the "markup" documentation in https://getuikit.com/docs/navbar#multiple-navigations

Looking at source, this is what actually works
```
<nav class="uk-navbar-container uk-navbar" uk-navbar="">

    <div class="uk-navbar-left">

        <ul class="uk-navbar-nav">
            <li class="uk-active"><a href="#">Active</a></li>
            <li>
                <a href="#" aria-expanded="false" class="">Parent</a>
                <div class="uk-navbar-dropdown uk-navbar-dropdown-bottom-left" style="left: 76.6562px; top: 80px;">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        <li class="uk-active"><a href="#">Active</a></li>
                        <li><a href="#">Item</a></li>
                        <li><a href="#">Item</a></li>
                    </ul>
                </div>
            </li>
            <li><a href="#">Item</a></li>
        </ul>

    </div>

    <div class="uk-navbar-right">

        <ul class="uk-navbar-nav">
            <li class="uk-active"><a href="#">Active</a></li>
            <li>
                <a href="#" aria-expanded="false" class="">Parent</a>
                <div class="uk-navbar-dropdown uk-navbar-dropdown-bottom-right" style="left: 389.391px; top: 80px;">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        <li class="uk-active"><a href="#">Active</a></li>
                        <li><a href="#">Item</a></li>
                        <li><a href="#">Item</a></li>
                    </ul>
                </div>
            </li>
            <li><a href="#">Item</a></li>
        </ul>

    </div>

</nav>
```

**Comment by iyobo** [comment]
Issue seems to be that uk-navbar should be used as class and not a custom html attribute.
I agree with this as it is much cleaner. All these custom attribute alts are kinda messy. So in fixing the opening code:

```
<nav class="uk-navbar-container uk-margin uk-navbar" >
	    <div class="uk-navbar-left">
	        <a class="uk-navbar-item uk-logo" href="#">Logo</a>

	        <ul class="uk-navbar-nav">
	            <li>
	                <a href="#">
	                    <span class="uk-icon uk-margin-small-right" href="#" uk-icon="icon: star"></span>
	                    Features
	                </a>
	            </li>
	        </ul>
	    </div>
		
		<div class="uk-navbar-right">
			<div class="uk-navbar-item">
				<form>
					<input class="uk-input uk-form-width-small" type="text" placeholder="Input">
					<button class="uk-button uk-button-default">Button</button>
				</form>
			</div>
		</div>
	</nav>
```

**Comment by aarongerig** [comment]
@iyobo If you want to have a dropbar for example you'll need to add the `uk-navbar` attribute. Have a look at the source code to see what exactly it does: https://github.com/uikit/uikit/blob/develop/src/js/core/navbar.js

**Comment by iyobo** [comment]
@aarongerig either way, the point is that the markup documentation for that page is wrong.
uk-navbar needs to be added as a class to the div for this to work. The markup doc is different from what actually works.

**Comment by aarongerig** [comment]
@iyobo Not true, you don't have to add the class `uk-navbar` to the navbar element. It gets added by the `uk-navbar` attribute, if it hasn't been added yet. See this codepen: https://codepen.io/aarongerig/pen/LqJMYy

**Comment by iyobo** [comment]
@aarongerig I think a good number of people who use UIKit use it in some other frontend framework like e.g React, etc. In that space, uk-navbar does not get added as a class. I imagine that is an exact scenario this issue spawned from. So it is best practice to add the class.

**Comment by aarongerig** [comment]
If you'd like to use UIkit in combination with React, make sure you add the attribute with a `data-` prefix. So `uk-navbar` becomes `data-uk-navbar`, otherwise it won't work.

For further usage questions, please consult the community on Discord. https://discordapp.com/invite/NEt4Pv7

**Comment by chacken** [comment]
> Issue seems to be that uk-navbar should be used as class and not a custom html attribute....even though doc says you can. I agree with this as it is much cleaner to use classes. All these custom attribute alts are kinda messy. So in fixing the opening code:
> 
> ```
> <nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar="">
> 	    <div class="uk-navbar-left">
> 	        <a class="uk-navbar-item uk-logo" href="#">Logo</a>
> 
> 	        <ul class="uk-navbar-nav">
> 	            <li>
> 	                <a href="#">
> 	                    <span class="uk-icon uk-margin-small-right" href="#" uk-icon="icon: star"></span>
> 	                    Features
> 	                </a>
> 	            </li>
> 	        </ul>
> 	    </div>
> 		
> 		<div class="uk-navbar-right">
> 			<div class="uk-navbar-item">
> 				<form>
> 					<input class="uk-input uk-form-width-small" type="text" placeholder="Input">
> 					<button class="uk-button uk-button-default">Button</button>
> 				</form>
> 			</div>
> 		</div>
> 	</nav>
> ```
> 
> EDIT: As per @aarongerig's comment, not adding the custom attribute uk-navbar="" will lead to other problems. But you definitely need to have uk-navbar as a class too.

everything @iyobo seems to hold true still.  Using this with Vue.js i had to add both .uk-navbar and uk-navbar
