### ISSUE TITLE
Notify is not working

### ISSUE THREAD

**Issue by anita-brooks** [uikit/uikit#2184]
I am learning how to use uikit, but when i was reading about the notify functions, the samples doesn't display and the console shows the next issue:
`Uncaught TypeError: UIkit.notify is not a function
at HTMLButtonElement.<anonymous> (notify.html:21)
    at HTMLBodyElement.dispatch (jquery.js:3)
    at HTMLBodyElement.r.handle (jquery.js:3)`

**Comment by janschoenherr** [comment]
If you are using UIkit 3, please see: https://getuikit.com/docs/notification
