### ISSUE TITLE
Documentation Components not working

### ISSUE THREAD

**Issue by mikhailrepka** [uikit/uikit#2187]
Tested on
MacBook Air 13 OS X 10.11.6 El Capitan Safari 9.1.2, Chrome 55.0.2883.95
iMac 21 macOS 10.12 Sierra Safari

All js not working.

**Comment by ghazal** [comment]
On OSX El Capitan, Safari 9.1.1, everything is fine.
(https://getuikit.com/docs/introduction).

**Comment by janschoenherr** [comment]
Please create a http://codepen.io/pen/ example of the issue. Thanks.
