### ISSUE TITLE
Big gap between description terms and description bodies for small screen sizes

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2188]
Looking at https://getuikit.com/docs/description-list#display-as-grid , if you view with small screen width, there is a big gap between description terms and description bodies.

**Comment by saschadube** [comment]
Thanks! I removed it from the docs. It doesn't work https://github.com/uikit/uikit-site/commit/7639d8c9a6ac94157e4804fde7c35236f2f2ce81
