### ISSUE TITLE
Video controls partially obscured in Cover example in docs

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2189]
In the example in https://getuikit.com/docs/cover#video , in Chrome on Linux, the video controls are half-obscured when you mouse over the playing video. Since this is a cover example (rather than a fit-to-size example), this may just be an aspect ratio issue, so the div may simply need to be resized -- however, the docs should probably mention this issue too.

**Comment by saschadube** [comment]
Can you post a screenshot?

**Comment by lukehutch** [comment]
![screenshot_2017-01-10_05-51-39](https://cloud.githubusercontent.com/assets/811305/21808635/fa5ec740-d6f8-11e6-90d7-5373d405c2b3.png)

**Comment by janschoenherr** [comment]
Actually, using _uk-cover_ together with video controls is not recommended, as seen in your example. We've updated the docs accordingly.
