### ISSUE TITLE
Dotnav dots wrapped in docs example

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2190]
Minor issue with example in documentation: in https://getuikit.com/docs/dotnav#dotnav-and-images , the righthand example in the preview (with the horizontal dotnav dots) has the last dot wrapped onto a new text line within the overlay div. (Chrome on Linux)

(Should I be reporting documentation issues here?)

**Comment by janschoenherr** [comment]
Thanks, please report uikit-site issues here: https://github.com/uikit/uikit-site/issues

**Comment by saschadube** [comment]
It's fixed https://github.com/uikit/uikit-site/commit/9ec01c757cf00ff01993db85163d99d79fd2676a

**Comment by lukehutch** [comment]
@saschadube @janschoenherr You guys are fast :-)
