### ISSUE TITLE
Incorrect icons .svg image path in main css file

### ISSUE THREAD

**Issue by mightyvoodoo** [uikit/uikit#2191]
```css
.uk-icon::before {
  background-image: url("../../dist/images/icons.svg");
}
```

**Comment by janschoenherr** [comment]
Why is that an incorrect path? It is relative to the _uikit.css_ file.

**Comment by mightyvoodoo** [comment]
@janschoenherr But according to project structure it have no relation logic, because css, js and images folders are located on the same level... Or am I missing something?

**Comment by mightyvoodoo** [comment]
@janschoenherr Sorry for misunderstanding, forgot to place dist folder. Thank you for reply.

**Comment by janschoenherr** [comment]
This is fixed with beta 2.
