### ISSUE TITLE
Invisibility Does not Work with Offcanvas Toggle

### ISSUE THREAD

**Issue by buddilla** [uikit/uikit#2192]
Does not work as expected. 
`
<a href="#offcanvas" class="uk-invisible@s" uk-navbar-toggle-icon></a>
`
`
<a href="#offcanvas" class="uk-invisible@m" uk-navbar-toggle-icon></a>
`
`
<a href="#offcanvas" class="uk-invisible@l" uk-navbar-toggle-icon></a>
`
Oddly these work as expected.
`
<a href="#offcanvas" class="uk-visible@s" uk-navbar-toggle-icon></a>
`
`
<a href="#offcanvas" class="uk-visible@m" uk-navbar-toggle-icon></a>
`
`
<a href="#offcanvas" class="uk-visible@l" uk-navbar-toggle-icon></a>
`

Tested on latest safari and chrome on latest macOS using uikit3...

All other ways of creating an off canvas toggle produce the same issue with or without icon and with or without text as well. Wrapping in a div with invisibles does not work either.

**Comment by saschadube** [comment]
There are no ```uk-invisible-*``` classes. It's called ```uk-hidden-*``` 😉  https://getuikit.com/docs/visibility#visible

**Comment by buddilla** [comment]
Don't I feel stupid I missunderstood the docs my bad... LOL
