### ISSUE TITLE
v2 docs not working

### ISSUE THREAD

**Issue by klausfischer** [uikit/uikit#2194]
Hey,

seems like the js of https://getuikit.com/v2/docs/sticky.html (and other components) isn't working since the movement to the /v2 subdomain.

Maybe related to #2187, not sure if the v2 docs are meant.

**Expected**:
* sticky bars to stay sticky

**Actual behaviour**:
* sticky bars won't stay sticky

same thing with https://getuikit.com/v2/docs/parallax.html

**Tested Environment**:
OS X El Capitan 10.11.6
Chrome 55.0.2883.95 (64-bit)
Safari 10.0.2 (11602.3.12.0.1)
FF 50.1.0

Thanks for doing a good job with uikit :)

**Comment by CoalaWeb** [comment]
Just confirming that the components in the V2 sub-domain don't appear to be working any more.

**Testing**
Open the Lightbox [demo](https://getuikit.com/v2/docs/lightbox.html) and try the first Open Lightbox button.

Cheers and thanks for all your hard work!

**Comment by CoalaWeb** [comment]
I just checked and they are back up and running ;)

**Comment by imarkdesigns** [comment]
i guess this topic is closed for now...

**Comment by klausfischer** [comment]
Thanks for the quick fix!
