### ISSUE TITLE
Grid divider is added to first element

### ISSUE THREAD

**Issue by RobertoSnap** [uikit/uikit#2195]
I have this grid:

```
<div class="uk-container uk-container-center">
        <div class="uk-grid uk-grid-divider uk-text-center uk-child-width-expand@s">
            <div>One</div>
            <div>Two</div>
            <div>Tree</div>
            <div>four</div>
        </div>
    </div>
```

When view is above 964px i get a divider to the left of the first element.

![image](https://cloud.githubusercontent.com/assets/4772930/21805059/72abfff4-d732-11e6-83ef-9b6891066ae3.png)

**Comment by janschoenherr** [comment]
Please see: https://getuikit.com/docs/grid#divider
