### ISSUE TITLE
Sortable items temporarily have wrong margins while animating object between rows/cols

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2196]
When dragging items on the following page

https://getuikit.com/docs/sortable

if dragging an item causes a non-dragged item to change row/column (e.g. dragging Item 5 from the first row to the second row in the "Usage" example, or dragging Item 1 from Group 1 to Group 2 in the "Group" example), then the vertical height of the container is temporarily increased during the animation, and restored to its correct value at the end of the animation. This causes some visual jank.

In the case of the "Usage" example, it looks like the top margin of all the second row cards is temporarily increased during the drag operation, then reduced back to the correct value at the end of the drag.

(Chrome on Linux.)

**Comment by janschoenherr** [comment]
Thanks, fixed with f98a77cd27c5da5f4d85c8f3e4266af40e202206
