### ISSUE TITLE
Drag of Sortable item to end of group does not work until after dragging over other sort position

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2197]
In the example for Sortable > Group:

https://getuikit.com/docs/sortable#group

When dragging an item from one group to another, if you try to drag directly to the end of a group and drop the item in the final position, the drag is canceled. However, if during the drag you dragged the ghost item over a possible internal insert position within the group (causing items in the target group to be moved around to expose possible insert positions), then dropping the dragged item at the end of the target group succeeds fine.

The drag should succeed whether or not you drag over other items in the group before dropping the dragged item in the target group.

**Comment by janschoenherr** [comment]
There are only two options: If an item is not in the list yet, you can insert it below or above the item hovered. Currently we opted for the _below_ behavior.

**Comment by lukehutch** [comment]
Right, but what I mean is that you cannot drop the button below the last item in another column if you drag it there directly, because there is no invisible element at the end of the list of existing items that can accept a drag-drop. If you drag an item directly to the end of the list to try to drop it below the last item (i.e. drag it to *below* the last item, not on top of it), then when you release the mouse cursor, the drag operation is canceled. *However*, if you drag the item to an *internal* position in the other column first, so that a gap is created, and *then* drag it to the end of the items before dropping it, then the drag-drop does in fact succeed.

What I'm saying is that you need to always create an invisible dropzone at the end of each of the groups as soon as a drag is commenced, so that you can drag and drop on this dropzone without first dragging to an internal position.

It would actually help a lot to show a dashed empty rectangle at the current insert position during a drag operation, so you can see where the dragged item will end up if you release the mouse.

**Comment by performatric** [comment]
Based on @lukehutch response you can fix it with flexbox

See:
https://codepen.io/clemer/full/MvvamY/
