### ISSUE TITLE
Hover mode doesn't do anything on hover, requires click

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2198]
The toggle param "mode: hover" doesn't actually add a working hover toggle to the element, at least in the example in the docs:

https://getuikit.com/docs/toggle#modes

(Chrome on Linux.)

**Comment by janschoenherr** [comment]
I think this has been fixed, if it still an issue please reopen.

**Comment by lukehutch** [comment]
This is not fixed, the button still does nothing on mouseover. (Scroll down to the "Modes" section in the page I linked, and hover over the "HOVER" button.)
I have no way of reopening this bug since I didn't close it. Can you reopen it please?

**Comment by lukehutch** [comment]
@janschoenherr I am not able to reopen this bug, since I wasn't the one who closed it.

**Comment by speakdigital** [comment]
It seems to work in Firefox but not Chrome / IE

**Comment by kadirpace** [comment]
I mentioned about this issue also on #2401
Chrome and Edge running on Windows 10 (no touch screen). All the hover effect only works with Clicks. I have an almost production ready theme but this issue just stands on my way going on live.

**Comment by janschoenherr** [comment]
This has been resolved in Beta 12. Thanks.
