### ISSUE TITLE
Date/time picker gone in v3?

### ISSUE THREAD

**Issue by nblackburn** [uikit/uikit#2201]
Great job on the update but will date/time picker be making a return or has it been pulled from this release?.

**Comment by trk** [comment]
Here is an article about Uikit by YooTheme [http://yootheme.com/blog/2017/01/09/uikit-3-beta-released](http://yootheme.com/blog/2017/01/09/uikit-3-beta-released)

## What's missing

This is a beta release and as such it is to be considered a work in progress. A number of components still need to be reworked and will be added in the future. Our focus for this release has been to create a stable core and provide extensive documentation right from the start. Next on our list are the Slideshow, Slider, Slideset, Parallax, Nestable, Lightbox, Dynamic Grid, HTML editor, Date- and Timepicker components.

[readmore](http://yootheme.com/blog/2017/01/09/uikit-3-beta-released)

**Comment by nblackburn** [comment]
Ah, i was around before this blog post so must have missed it.
