### ISSUE TITLE
v3 modal: cannot create instance via javascript and use show()

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#2204]
In v2 I could do this:
```
var myModal = UIkit.modal('#my-modal');
myModal.show();
```
This does not seem to work in v3, although the migration tool says all code is v3 proof.

**Comment by petermumford** [comment]
Same here. This feature is so helpful

**Comment by petermumford** [comment]
I've just worked out you can do the following instead. Hopefully someone can confirm if this is the correct way of doing it?

`var modal = UIkit.modal("#my-modal");`
`modal[0].toggle();`

**modal** will now return an array so just picking the first item in the array and then you get your normal methods, for example: `show()`, `hide()`, etc

**Comment by BobbyBabes** [comment]
You need to add the `[0]` array index to the assignment :
```JavaScript
var myModal = UIkit.modal('#mymodal')[0];
myModal.show();
```
It's the same as what the official `UIkit.modal.dialog` function does.
There are 4 dialogs documented here under *Modal dialogs* : https://getuikit.com/docs/modal
Their options are doumented below that.

If you want to continue using `UIkit.modal` directly, you can study their code here : https://github.com/uikit/uikit/blob/202d4edc279e1d6753d7a03395f3c376f784f69a/src/js/core/modal.js#L109-L195

**Comment by janschoenherr** [comment]
We are still working on the docs, but there is a more comprehensive section on this now: 

https://getuikit.com/docs/javascript#programmatic-use
