### ISSUE TITLE
Typo and omissions on "Create a theme" docs page.

### ISSUE THREAD

**Issue by BobbyBabes** [uikit/uikit#2205]
**Docs page : https://getuikit.com/docs/theme**

Under the heading **2. Theme file** :
The less @import line : `@import "../../src/less/uikit.less";` is going up one directory too much.
It should be `@import "../src/less/uikit.less";`.
Running `node build/less` ends immediately with :
> [bobbybabes@designbox uikit]# node build/less
themes.json 0.06kb
Error building: dist/css/uikit.test-theme.css  FileError: '../../src/less/uikit.less' wasn't found. Tried - /home/bobbybabes/web-projects/designs/themes/test-theme/src/less/uikit.less,/home/bobbybabes/web-projects/designs/themes/test-theme/src/less/uikit.less,../../src/less/uikit.less in /home/bobbybabes/web-projects/designs/themes/test-theme/uikit/custom/test-theme.less on line 1, column 1:
1 @import "../../src/less/uikit.less";
2 

It is not mentioned on the page that the less compiler needs to be installed with : `npm install -g less`. 
Although I admit that this should be obvious.

It is not mentioned on the page to run `npm install` in the `uikit` folder prior to running `node build/less` (to install the node modules required by UIkit).
Running `node build/less` without first installing the node modules that UIkit requires, ended immediately with:
> [bobbybabes@designbox uikit]# node build/less
module.js:472
    throw err;
    ^
>
> Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bobbybabes/web-projects/designs/themes/test-theme/uikit/build/less.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by janschoenherr** [comment]
This has been fixed in the docs with uikit/uikit-site@3f06e6a1d97799b0063190f66c63031b866e1ee1

**Comment by BobbyBabes** [comment]
Thanks!
