### ISSUE TITLE
Missing datepicker

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#2206]
Will the datepicker return to v3 soon?

**Comment by CoalaWeb** [comment]
Please see [Blog post](https://yootheme.com/blog/2017/01/09/uikit-3-beta-released)

> What's missing
> 
> This is a beta release and as such it is to be considered a work in progress. A number of components still need to be reworked and will be added in the future. Our focus for this release has been to create a stable core and provide extensive documentation right from the start. Next on our list are the Slideshow, Slider, Slideset, Parallax, Nestable, Lightbox, Dynamic Grid, HTML editor, Date- and Timepicker components.

Cheers

**Comment by jerry1970** [comment]
Ouch, completely managed to miss that blog, thanks.
I don't read anything about a roadmap or vague ideas of when those features are going to be implemented. Any ideas? No guarantees necessary, just ideas.

**Comment by CoalaWeb** [comment]
Yeah I missed it at first too ;)

**Comment by philoest** [comment]
These will come step by step, we can't give you a timetable for all the components but we want to keep adding them with constant releases :)
