### ISSUE TITLE
Icons with theme

### ISSUE THREAD

**Issue by RobertoSnap** [uikit/uikit#2210]
Advice needed: Installed uikit3 via Bower. Created a theme. To display icons i had to overwrite this in the theme less icon file and it works. 
```//
// Component: Icon
//
// ========================================================================
.uk-icon::before { background-image: url("bower_components/uikit/dist/images/icons.svg"); }
```

Trying to create pagniation now. But the icons from pagination do not show. So i did the same thing as over. Edited the theme pagniation file with this:

```// Variables
// ========================================================================
@internal-pagination-next-image:                "bower_components/uikit/dist/images/icons.svg";
@internal-pagination-previous-image:            "bower_components/uikit/dist/images/icons.svg";
```

But icons dont show, which is weird because in the source it shows the same as with icons. I guess this has something to do with the overriding. Anyone have some advice for me here?

**Comment by janschoenherr** [comment]
The icon system has been refactored: https://getuikit.com/docs/icons

If the issue persists please reopen.
