### ISSUE TITLE
When will UIkit 3 be added into Pagekit?

### ISSUE THREAD

**Issue by hanlan** [uikit/uikit#2211]
As titled, the UIkit 3 is a fantastic new weapon, since the file structure has been changed a little, manually updated UIkit in a pagekit system will not work unless to do a lot of modification, apparently this is not everyone want.

So, when the Pagekit will be updated and come with the UIkit 3 natively?

Thanks.

**Comment by janschoenherr** [comment]
Thanks, please use our Gitter chat for general discussions.

https://gitter.im/uikit/uikit
