### ISSUE TITLE
UIKit 3: if i use uk-height-match with uk-scrollspy problem with element heights

### ISSUE THREAD

**Issue by trk** [uikit/uikit#2214]
If i apply uk-height-match with uk-scrollspy, there is problem about heights. As you see on screenshots with uk-scrollspy, elements height much bigger.

### Html usage:
```html
<div class="uk-margin-small" uk-grid uk-height-match="target: > div > .uk-card" uk-scrollspy="target: > div; cls:uk-animation-fade; delay: false">
</div>
```
### Result :

![ekran resmi 2017-01-11 17 05 14](https://cloud.githubusercontent.com/assets/455983/21851456/ddf98b7e-d817-11e6-8927-509a124a2751.png)

### Html usage:
```html
<div class="uk-margin-small" uk-grid uk-height-match="target: > div > .uk-card">
</div>
```
### Result

![ekran resmi 2017-01-11 17 06 30](https://cloud.githubusercontent.com/assets/455983/21851514/04709c16-d818-11e6-805d-10dd7a8b14f4.png)

**Edited**

After removed uk-scrollspy, i see uk-height-match only working well for visible sections. If you have scrollable content on page, uk-height-match working well for visible content, but if you scroll down element heights are bigger. When i refresh page (CMD + R on Firefox) element heights are ok.

**Comment by janschoenherr** [comment]
Please show an example of the issue on codepen.io. Thanks.

**Comment by trk** [comment]
I don't see this issue any more, after latest updates
