### ISSUE TITLE
UIKit 3 Icons Not Compatible with React

### ISSUE THREAD

**Issue by thealexbaron** [uikit/uikit#2219]
The Icon stuff used to work with React just fine since it just used classes. I'm trying to migrate a project from UIKit 2 -> 3, but I might not be able to since icons rely on UIKit JavaScript.

Since `uk-icon` isn't a supported HTML attribute, React gets mad if you do `<span uk-icon="icon: more"/>` and won't use the attribute. I'm able to do `<span is uk-icon="icon: more"/>` to get it to work, but then when there are changes to the attribute `uk-icon`, they don't reflect in the nested html generated by UIKit. 

I realize that the goal of UIKit isn't to accommodate React, but could this be fixed or is there a workaround?

**Comment by janschoenherr** [comment]
We'll most likely offer a npm task to build UIkit with a custom prefix. You could use _data-uk-_ or just _data-_ then.

**Comment by janschoenherr** [comment]
We now allow for _data-uk-_ prefixed component attributes.
Added with 49268359de8c75241756effb37ec95942a986e13

**Comment by thealexbaron** [comment]
@janschoenherr Thanks for adding the `data-uk-` stuff. That was very helpful so now I don't have to use the html `is` attribute anymore.

However, even after the change the icons are still not compatible with React. Do you know what lead to the decision for the new icon syntax and behavior? If you try to change the contents of `data-uk-icon` with React the changes are not reflected. See the following example:

https://react-uikit-3-icons-thealexbaron.c9users.io/

(I tried to re-create this in a fiddle but I wasn't able since the cdn doesn't allow the cross origin svg request)

**Comment by stipsan** [comment]
@thealexbaron  There are ways to make it work with React.

On uikit-react we're testing a way that works with the default ones that ship with uikit on npm, we haven't worked on a solution that works with custom icon svgs out of the box (but it shouldn't be too hard to modify this to make it work): https://github.com/stipsan/uikit-react/blob/v3/src/Icon/Default.js

I think the new system is a great improvement. Even though it makes it more work to use it in libraries like React the benefits with the new system compared to sticking to icon fonts are many IMO.
