### ISSUE TITLE
Accordion with Sortable not opening correct after change order sortable

### ISSUE THREAD

**Issue by JKouvakis** [uikit/uikit#2222]
https://jsfiddle.net/0f2axhmq/

I have an accordion wrapping a sortable. when I change sorting position and i click on an accordion title I the primary accordion is opened. (for example I move category 1 after category 2 and I click on category 1 title, the category 2 opens instead of category 1).

I tried also with javascript

categoriesAccordion = UIkit.accordion('.categories-accordion', {
            targets: "> div > .category-wrap"
        });

but there is no update function in the component.

**Comment by janschoenherr** [comment]
This has been resolved with f98a77cd27c5da5f4d85c8f3e4266af40e202206

If your problem persists please reopen.

**Comment by janschoenherr** [comment]
Resolved with be4b81762b49461ea38f12995fc24b46cd6deab8
