### ISSUE TITLE
UIKit uk-visible\@s not work

### ISSUE THREAD

**Issue by romanew91** [uikit/uikit#2225]
uikit-3.0.0-beta.2 
Class `uk-visible\@s` not work in chrome.
Other classes start with `uk-visible\@ `and `uk-hidden\@` not work too.

**Comment by zzseba78** [comment]
Did you type it correctly? it´s **uk-visible@s** , not uk-visible\@s

**Comment by romanew91** [comment]
I download uikit-3.0.0-beta.2
And css class uk-visible\@s not work in chrome

**Comment by romanew91** [comment]
uk-visible\@s

**Comment by philoest** [comment]
Within your HTML code, the class should be named `uk-visible@s` the \@ is only needed within the css files. 
To see how this works take a look into the [width docs](https://getuikit.com/docs/width#responsive-width) example code.
