### ISSUE TITLE
Font color inside Dropdown inside a Section uk-section-primary

### ISSUE THREAD

**Issue by miniMAC** [uikit/uikit#2227]
The font color is not inverted inside the Dropdown inside a section with class uk-section-primary.

Here is the Pen: [http://codepen.io/minimamente/pen/OWNorQ](http://codepen.io/minimamente/pen/OWNorQ)

**Comment by philoest** [comment]
For this case we have the class `uk-preserve-color` https://getuikit.com/docs/section#preserve-color
