### ISSUE TITLE
missing lightbox and dinamic grid

### ISSUE THREAD

**Issue by wireinet** [uikit/uikit#2231]
oh my god!
i add:
`    <div class="uk-grid">
        <div class="uk-width-1-2">lorem100</div>
        <div class="uk-width-1-2">loremm300</div>
    </div>`
and this is not dinamic-why??
also i cant find lightbox...

many bugs i think

**Comment by saschadube** [comment]
The grid is working for me, see [Grid test](https://getuikit.com/assets/uikit/tests/width.html). What's not working for you?

Yes, dynamic grid (sorting effect) and lightbox are not included in the UIkit 3 beta. We are still working on it.

**Comment by wireinet** [comment]
hello! yes, ok. i dont knowed about that you is still working on it!
