### ISSUE TITLE
UIkit 3: uk-table-hover applied on tr instead of td, so hover doesn't work

### ISSUE THREAD

**Issue by jelgervisser** [uikit/uikit#2232]
Line 155 @ table.less:

.uk-table-hover > tr:hover,
.uk-table-hover tbody tr:hover {
    background: @table-hover-row-background;
    .hook-table-hover;
}

Should be:

.uk-table-hover > tr:hover td,
.uk-table-hover tbody tr:hover td {
    background: @table-hover-row-background;
    .hook-table-hover;
}

**Comment by saschadube** [comment]
Thank! Can you elaborate why it should be on the table data element? It's working for me https://getuikit.com/assets/uikit/tests/table.html
