### ISSUE TITLE
uikit3 and slideshow

### ISSUE THREAD

**Issue by Samanw** [uikit/uikit#2233]
i couldnt find anything about slideshow in uikit3 
this component will add in next updates?

**Comment by saschadube** [comment]
Yes, it's not ready for the beta yet. We are working on it.

**Comment by shenst1** [comment]
Would you say under or over a month for the slideshow feature?

**Comment by josueadelima** [comment]
Hello,

I was working on a website with version 3, I'll need to migrate to version 2 :-( so sad this component is not ready, almost all websites will need a slideshow at some point.

Any news on this?

Thanks for the great work your doing with uikit.
