### ISSUE TITLE
Sticky Demo in Docs Header Conflicts 

### ISSUE THREAD

**Issue by davidbwaters** [uikit/uikit#2234]
Hi, I noticed the sticky demo in the (new) docs has some issues with the header.

**Comment by florianletsch** [comment]
What do you mean exactly with "issues"? Of course, the navbar is also sticky, so the examples arent exactly how you would implement it in your own site. But at least it highlights what the sticky looks like without an offset. Hm, what would you suggest instead?

![image](https://cloud.githubusercontent.com/assets/1116784/21962633/ac6b73c2-db2a-11e6-8ce2-c8022fdc3b7a.png)

**Comment by davidbwaters** [comment]
I just think it was a little awkward presentation in the demo.  The 'jumping' of the z-depth when some elements are 'stuck' is probably what makes it seem awkward, IMHO.  The header covers the elements until they are 'stuck' and are rendered on top of the header.  If the z-index of all of the sticky elements and containers was set higher than the header by default, that would help.

Honestly, I just wouldn't use a sticky header on the docs/demo site.  IMO, the links aren't going to be quickly navigated between enough to justify constantly taking up screen real estate, from a UX perspective.  This would also create less confusion by having the demo scaffolding be as basic of implementation possible.  Having an element with the unique (to a new user) 'sticky' behavior being rendered on top of elements before the component's behavior is introduced could confuse the learning process.  If the header wasn't sticky you could see blocks being 'stuck' to the top of the screen, without the confusion of having to figure out that there is another sticky element being rendered on top/in-between the demo elements.

I'm sure you guys could come up with other elegant solutions.  I just wanted to point out an observation of something that could be off-putting for some.

**Comment by janschoenherr** [comment]
The z-index issue has been resolved with uikit/uikit-site@ff041c6bc12c0ddc7770f498daa7742b88591c79

**Comment by davidbwaters** [comment]
Awesome, the demo is much more effective now.  Thanks.
