### ISSUE TITLE
Can I use this framework to design whmcs themes?

### ISSUE THREAD

**Issue by KaisTag** [uikit/uikit#2235]
Hello,
Today i started to use this framework to design whmcs themes but whms use .tpl files for designing, I tried to test but encountered problems using  data-uk-sticky, data-uk-dropdown...

Thank you,
Kais

**Comment by m0yP** [comment]
Are you using v3? Because I did some customizations with v2 without major issues.

**Comment by KaisTag** [comment]
am using UIkit v2... i will use v3 and check again.

**Comment by KaisTag** [comment]
same problem v2 and v3, @m0yP are you used data-uk-dropdown to toggle a dropdown using this framework

**Comment by florianletsch** [comment]
As long as their templateing engine supports the laoding of all required assets (CSS and JS), UIkit can be used for any kind of templating. I guess further discussion should happen on their channels, as it is not directly related to UIkit,
