### ISSUE TITLE
Feature request: Add specific class to show or hide some element only in one size.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2238]
Hi! I think it would be a nice addition to the Visibility component a class to show or hide some element only in one size, for example **uk-visible@s-only**, or **uk-hidden@m-only**.
Of course this can be done with two classes from the Visibility component, but i think it would be cleaner and following the line of simplicity of uikit 3.

Thanks.

**Comment by florianletsch** [comment]
I think we will keep the current options of the visibility component. Special preferences like this can easily be implemented on a per-project basis with some custom Less/Sass/CSS. https://getuikit.com/docs/visibility
