### ISSUE TITLE
Implement Ajax Search on https://getuikit.com/docs/

### ISSUE THREAD

**Issue by jamie-kaushal** [uikit/uikit#2240]
Requesting a search box in the uikit docs website similar to how Bootstrap has one implemented here (above their side menu): https://v4-alpha.getbootstrap.com/getting-started/introduction/

This will make it very easy for folks to switch over to uikit who are not familiar with where certain parts of the documentation are located.

**Comment by kirich1368** [comment]
CTRL + F

**Comment by devtype** [comment]
+1

**Comment by ckidow** [comment]
+1

**Comment by ruchern** [comment]
@kirich1368 Looks like we have a winning comment here.

**Comment by janschoenherr** [comment]
"Moved" the issue to uikit/uikit-site#93
