### ISSUE TITLE
UIkit 3 - Lightbox Component - User interface design proposal and ideas.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2241]
Just a design proposal for the new UIkit v3 Lightbox Component. 
Hope you like it.

![lightbox large](https://cloud.githubusercontent.com/assets/5558563/22002591/073368e4-dc2c-11e6-9538-5353407bd76f.jpg)
![lightbox mobile](https://cloud.githubusercontent.com/assets/5558563/22002594/09677a2e-dc2c-11e6-9f41-b10a123ae718.jpg)
![lightbox mobile - close](https://cloud.githubusercontent.com/assets/5558563/22005796/e1e2a1ae-dc44-11e6-9f36-7f4752d4a61b.jpg)
![lightbox mobile - swipe](https://cloud.githubusercontent.com/assets/5558563/22002600/0dae4446-dc2c-11e6-9c8e-66f60a4e7a14.jpg)
![lightbox large - annotations](https://cloud.githubusercontent.com/assets/5558563/22002612/1c9668ee-dc2c-11e6-94b2-fca229ec53da.jpg)
![lightbox mobile - comments](https://cloud.githubusercontent.com/assets/5558563/22002618/2147c3ec-dc2c-11e6-9d5b-64aed0b6e29c.jpg)

**Comment by reramjiawan** [comment]
I would like to add this: [fancyBox3](https://codepen.io/fancyapps/pen/WjVXyx)

**Comment by macsupport** [comment]
@reramjiawan, 
FYI : fancyBox is licensed under the GPLv3 license for all open source applications, but a commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).

**Comment by reramjiawan** [comment]
I am aware but this is about how the lightbox should function and fancybox3 is a great example to that fact.

**Comment by zzseba78** [comment]
Lightbox it´s out and looks great, so i´m closing this issue.

**Comment by zzseba78** [comment]
Lightbox it´s out and looks great, so i´m closing this issue.
