### ISSUE TITLE
UIKit 3: Where is slideshow component?

### ISSUE THREAD

**Issue by pavlosadovyi** [uikit/uikit#2242]
it seems that **uk-slideshow** isn't exist anymore.
Why that? And what combo should I use to replace this?

**Comment by nstaeger** [comment]
As v3 is in beta right now, it is also not feature-complete. The slideshow does not exist just yet. But it's on YOOtheme's list to implement the slideshow in the near future (no time frame mentioned). For further details see: http://yootheme.com/blog/2017/01/09/uikit-3-beta-released

If this answer already helped you, feel free to close this issue.

**Comment by pavlosadovyi** [comment]
thanks!

**Comment by cholasimmons** [comment]
I panicked, I thought I was doing something wrong! haha
amazing framework you've made, can't wait for the slideshow component,

**Comment by Marjani** [comment]
Please give priority to the implementation Slideshow
Thanks

**Comment by razvanioan** [comment]
Being very excited to implement UIkit in my first project (migrating from Bootstrap), and going directly with v3 (even if its still Beta and not yet complete, all components)

I will probably have to build a small / custom slider using jQuery until the built-in component will be ready, but I would like to point an important detail which in my case will be mandatory: 

the slider / slideshow to work smoothly inside a cover container (with responsive height / viewport height) as well !

Keep up the nice things here ;)

**Comment by ruchern** [comment]
@razvanioan You can make use of Dotnav + Slidenav + Slider.

**Comment by Riddler84** [comment]
@razvanioan The v2 Slideshow has already a fullscreen feature. I'm pretty sure, this will also be possible with the new v3 version of the Slideshow.

**Comment by razvanioan** [comment]
@ruchern there's no `Slider` component in v3 (at least I cannot find it)

@Riddler84 Cool, I hope that not only fullscreen, but maybe in combination with responsive & viewport height (with offsets for header & navbar for example), like `Cover` does

**Comment by ruchern** [comment]
@razvanioan Sorry, it's Switcher, not Slider.

**Comment by razvanioan** [comment]
Because this was a little bit challenging and maybe others will need this, here's a how I've done it (without altering UIkit core JS): [https://codepen.io/qdev/pen/WORarX](https://codepen.io/qdev/pen/WORarX)

And here I've explained the issues & solution above: [https://github.com/uikit/uikit/issues/2247#issuecomment-309264805](https://github.com/uikit/uikit/issues/2247#issuecomment-309264805)

Until official `slider` / `slideshow` ... ;)

**Comment by ruchern** [comment]
@razvanioan Beautiful work! Thanks a lot. And I assume the overlay is just to tell people what it is and is not actually implemented.

**Comment by razvanioan** [comment]
@ruchern Nope, the overlay, cover and height-viewport are already implemented and used accordingly, I just wanted to show what I needed it for and how the complete solution looks like ;)

I only styled a little bit differently the overlay in order to follow design request ...

Thanks !

**Comment by ruchern** [comment]
@razvanioan What I meant is the overlay can be taken out from the codepen that you have just shown.

**Comment by razvanioan** [comment]
@ruchern Oh yes, you can add or not overlays over the pictures, some can have others not, depending on the requirements ...

The only buggy thing which I don't like but I can live with until official / dedicated `slideshare` component, is that using `setIntervals()` for triggering clicks to automatically go to next slide it works (updated the pen), but it's defocusing / closing opened submenus (if opened) ...
