### ISSUE TITLE
responsive table inside a switcher doesn't work on mobile

### ISSUE THREAD

**Issue by DerBeni** [uikit/uikit#2245]
Hi,
...i'm trying to use a responsive table inside of the switcher component but this isn't working on mobile devices. Scrolling through the table causes a change of the active menu item (and switches the content) although i turned turned "swiping" to false...

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The switcher component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
