### ISSUE TITLE
UIkit3 - will be modular

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2246]
It UIkit3 will be modular as UIkit2 was? I mean by now I include uikit.js or uikit.min.js and there is a base + all components.
I want to use base + some components (instead of all) like I can do in v2: base + include file (js / css or both) per each component - It will be possible at (near) future?

**Comment by janschoenherr** [comment]
Please see https://getuikit.com/docs/installation#compile-from-github-source

This will give you the core + components separated.
