### ISSUE TITLE
UIKit 3: How to connect slidenav?

### ISSUE THREAD

**Issue by pavlosadovyi** [uikit/uikit#2247]
Hi, I have used **slidenav** arrows with switcher component, so I can switch next/prev any kind of content.
For now with v3 I can't connect slidenav with switcher or tabs? Am I doing something wrong or it's just in development? I'm not sure can I use dotnav the same way.

**Comment by saschadube** [comment]
Please use ```uk-switcher-item="next"``` and ```uk-switcher-item="previous"```. See [switcher docs](https://getuikit.com/docs/switcher#navigation-controls).

**Comment by razvanioan** [comment]
@saschadube

I don't know what was @pavlosadovyi's reason for asking this, but in my case I'm trying to build kind of a replacement for missing (yet) `slider / slideshow` component using `switcher & slidenav` like I was suggested to.

So basically what I want is a header image rotator, with arrows as nav (no tabs), inside a `height-viewport` `cover`

What I've discovered trying to achieve this:

- switcher can only work connected to some kind of parent / child navigation (ul -> li) where each list item corresponds to a switcher item (maybe this can be configured somehow different using `toggle` option selector which defaults to `> *`), and this is mandatory for passing `animation` options as well
- `uk-switcher-item` works only if defined inside `uk-switcher` component, which means to have them on each switch / panel, which maybe I don't want but only one `slidenav` for all items, and I couldn't connect these like tabs
- I couldn't figure out yet why on UIkit switcher example I could change the items using JS method `show('next')` but on my website it didn't work, even if I copied exact same DOM code from example page ...
- unfortunately there's no way (yet) of passing options to switcher JS show method (like animation)

The only hack I could find to make this work like I wanted without touching UIkit JS code (yet), was to:

- inject dummy (hidden) `uk-switcher-items` buttons on one of the `uk-switcher` items
- inject dummy (hidden) `uk-tab` (actually any parent / child element would do the trick I guess)
- trigger `uk-switcher-items` clicks from a visible `uk-slidenav`

Result: [https://codepen.io/qdev/pen/WORarX](https://codepen.io/qdev/pen/WORarX)

Barely waiting for official `slider / slideshow` components :)
