### ISSUE TITLE
Switch & Animation Issues in Demo (Safari)

### ISSUE THREAD

**Issue by uatrend** [uikit/uikit#2248]
First - Paragraph jumps(flashes) below the tabs. 
Other - On video from 4sec. two labels shows together.

[![Switch & Animation Issue](https://img.youtube.com/vi/xAGBxL0qVm0/0.jpg)](https://www.youtube.com/watch?v=xAGBxL0qVm0)

Thanks for your work!

**Comment by janschoenherr** [comment]
This has resolved itself with Safari 10.1 👍
