### ISSUE TITLE
UIkit 3 - Feature request  uk-width-*-10 missing in the Width Component

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2250]
**Feature request for UIkit 3**

Missing 10th size in the Width Component ( uk-width-*-10 ) , -auto and  -expand are great additions, but if you need more granular ( detailed ) control for the grid, more sizes would be great.

uk-width-*-10( you have addition of **1-10**, **3-10**, **7-10**, **9-10** proportions )
uk-width-*-8 ( you have addition of **1-8**, **3-8**, **5-8**, **7-8** proportions )
uk-width-*-7 ( you have addition of **1-7**, **2-7**, **3-7**, **4-7**, **5-7**, **6-7** proportions )

**Comment by BobbyBabes** [comment]
You can add them yourself in the provided hook or miscellaneous hook.
See under *Use hooks* and *Miscellaneous hooks* here : https://getuikit.com/docs/less
In this case you need to add the "missing" widths to the miscellaneous hook (because no hook was provided)  at the bottom of this file : https://github.com/uikit/uikit/blob/develop/src/less/components/width.less#L398.
And then recompile the less source code to css.

**Comment by zzseba78** [comment]
Hi! thanks for your response, i will try to creat them!
P.S. yes,  11-10 doesn´t seems to be useful size :)

**Comment by saschadube** [comment]
Sorry, we dropped the ``` uk-width-*-10``` classes. If you want to create a grid with equal columns just use ```uk-child-width-expand``` It works with any column number.

```
<div class="uk-child-width-expand" uk-grid>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>
```

You can also mix it with item width classes to get different proportions.

```
<div class="uk-child-width-expand" uk-grid>
    <div></div>
    <div></div>
    <div></div>
    <div class="uk-width-1-3"></div>
    <div></div>
    <div></div>
    <div class="uk-width-1-6"></div>
</div>
```

If that doesn't help you and you really need tenths, you have to add them manually using the Miscellaneous hook as @BobbyBabes said.

**Comment by BobbyBabes** [comment]
@zzseba78 I forgot to add the link to the UIkit 2 `grid.less` file which contains the definition of the `uk-width-*-10` classes : https://github.com/uikit/uikit/blob/v2/master/src/less/core/grid.less
Makes it easier to add and derive the `7` and `8` variants.

Good luck with it. @saschadube method is a lot easier though. And less maintenance and liability too.

**Comment by OwenMelbz** [comment]
As theres no official solution yet, @AlekVolsk created a polyfill so incase anybody uses something like npm/yarn to manage their dependencies, they can use https://www.npmjs.com/package/uikit3-extra-widths to add it back in :)
