### ISSUE TITLE
Icon component - class names

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2253]
1) Icon list in library (https://getuikit.com/docs/icon#library) in alphabetical order in each category - easier and quicker to find (in future maybe some search for it?)

2) Class names in icon modifier:
Link modifier: ```uk-icon-link```
Button modifier: ```uk-icon-button```
Image modifier: why ```uk-icon uk-icon-image``` instead of just ```uk-icon-image``` which will be more logic in this case? especially if we look how the previous have classes :)

**Comment by saschadube** [comment]
Thanks for you feedback!

1. We will consider it in the future

2. The ```uk-icon="icon: NAME"``` attribute sets the uk-icon class automatically. When using the ```uk-icon-image``` class, you don't use the icon component (because you set an image manually) so you have to add the ```uk-icon``` class manually.
