### ISSUE TITLE
Missing Features and Styles in UiKit 3

### ISSUE THREAD

**Issue by stebeg** [uikit/uikit#2254]
Hi,

i just wanted to ask, if there will be an uikit 3 version of all the uikit 2 features at some point, especially the dynamic pagination. 
And will we have more out-of-the-box style variants for uikit 3 like almost-flat and gradient or even an uikit 2 style for uikit 3.
I'd really like to upgrade uikit to version 3 in my web application, but I don't want that huge change of look & feel.

**Comment by florianletsch** [comment]
The features to come are listed in https://github.com/uikit/uikit/issues/560

Right now there is no plan to add more styles to the project itself. If you buy Pro, it will include a large number of additional UIkit styles in the Page builder. https://getuikit.com/pro
