### ISSUE TITLE
Rails and Turbolinks - UIKit 3

### ISSUE THREAD

**Issue by petermumford** [uikit/uikit#2255]
When using Turbolinks the page doesn't refresh when navigating around the website and only the body gets refreshed and because of this the javascript won't re-initialise and none of the javascript works again until you refresh the page.

In UIKit 2 we could use `UIKit.init()` in a `page:reload` callback as mentioned at the bottom of #1612. However, in UIKit 3 `UIKit.init()` doesn't seem to be available, is there an alternative?

**Comment by janschoenherr** [comment]
Thanks, this should work out of the box now. No need for `UIkit.init()`.

**Comment by petermumford** [comment]
I can confirm this worked. Thank you.

**Comment by kinnrot** [comment]
There is also issue with UIKit.modal show , stops working after showing a modal and navigating with turbbolinks

**Comment by dvlpr91** [comment]
navbar, off-canvas too.
