### ISSUE TITLE
Search Functionality in Documentation

### ISSUE THREAD

**Issue by DominikAngerer** [uikit/uikit#2257]
My colleague and I currently were looking for a search field or similar in the new documentation (v3).

[Algolia](https://community.algolia.com/docsearch/) offers a free to use docsearch - we're currently using them for our project [Storyblok](https://www.storyblok.com) should be also working for your documentation

Br,
Dominik

**Comment by florianletsch** [comment]
Thanks, search is a good idea. Has already been suggested by #2240
