### ISSUE TITLE
Sticky Component - width not resizing

### ISSUE THREAD

**Issue by petermumford** [uikit/uikit#2261]
When I resize the window the width attribute in styles is not changing. I can confirm this worked in beta-1 and beta-2 but not the last 2 betas. See screenshot.

![screen shot 2017-01-18 at 10 45 52](https://cloud.githubusercontent.com/assets/331905/22070298/68d4873c-dd93-11e6-918a-28de57fe7a18.png)

**Comment by janschoenherr** [comment]
Fixed with ea91bbf2de8c461035a23566a42e529178ae7c9d

**Comment by petermumford** [comment]
I can confirm this is working. Thank you.

**Comment by KaisTag** [comment]
I still have the same problem in beta-4

**Comment by petermumford** [comment]
@KaisTag beta-4 and beat-3 is where the error is happening. You'll have to wait until @janschoenherr release beta-5 to see the fix.

**Comment by KaisTag** [comment]
@petermumford thank you.
