### ISSUE TITLE
UIKit 3 js part does not work

### ISSUE THREAD

**Issue by Isigiel** [uikit/uikit#2263]
Hello,
trying out uikit 3 beta 4 I'm stuck on the javascript part.
I'm getting `Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined` in line 9 of UIKit.js. It seems that it does not find `$`.

Edit: It seems, that this issue might be connected to me using electron, it seems to work on chrome.

Full file for reference
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.4/css/uikit.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://getuikit.com/assets/uikit/dist/js/uikit.min.js?168" defer></script>
</head>
<body>
<div class="uk-card uk-card-default uk-width-1-2@m">
    <div class="uk-card-body">
        <h3 class="uk-card-title">Labelmaker</h3>
        <p>Bitte einen Namen eingeben</p>
        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="name" id="namefield">
        </div>
    </div>
    <div class="uk-card-footer">
        <button onclick="triggerPrint()" class="uk-button uk-button-text">Drucken!</button>
    </div>
</div>
<script>
    // You can also require other files to run in this process
    //require('./renderer.js')
</script>
<script src="renderer.js"></script>
<!--<script src="assets/jQuery.js"></script>
<script src="assets/uiKit.js"></script>-->
<!--<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.4/js/uikit.js"></script>-->
</body>
</html>

```

**Comment by AlexandreZaytsev** [comment]
```
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script src="js/uikit.min.js"></script>
 <script src="js/uikit.min.js"></script>
```

**Comment by Isigiel** [comment]
I'm sorry, what do you mean with that?

**Comment by AlexandreZaytsev** [comment]
I'm sorry - where exactly is the error? you have not written
? I thought the library is not connected
> in undefined in line 9

**Comment by Isigiel** [comment]
Well i set the above mentioned tasks in my html and it instantly fails, UIKit just throws an exception

**Comment by janschoenherr** [comment]
Are you sure you can place the script tags _after_ the closing body tag? I thought they belong right _before_. But you could also place them in the head section and use the _defer_ attribute.

**Comment by Isigiel** [comment]
I moved them to both locations and it didn't help.
Although @janschoenherr It seems like the issue might be related to me using electron.
On chrome there seems to be no problem.

**Comment by dfpena** [comment]
Same error here. It is indeed electron related uikit displays perfectly outside of my electron app. Turns out this is part of the FAQs:
http://electron.atom.io/docs/faq/

You need to rename the extra symbols electron puts in the DOM
worked for me

```
<head>
<script>
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;
</script>
<script type="text/javascript" src="jquery.js"></script>
</head>

```

**Comment by toby1991** [comment]
beta.5 get the same issue
[https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.5/js/uikit.min.js](https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.5/js/uikit.min.js)

**Comment by toby1991** [comment]
>beta.5 get the same issue
https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.5/js/uikit.min.js

* After I move the uikit.js after jQuery.js, Problem fixed.
----
1. I've downloaded the code not optimized from [https://raw.githubusercontent.com/uikit/uikit/develop/dist/js/uikit.js](https://raw.githubusercontent.com/uikit/uikit/develop/dist/js/uikit.js),

2. got the issue below:
![image](https://cloud.githubusercontent.com/assets/5897356/22199683/f2d36046-e196-11e6-8080-2b521246ad86.png)

3. that's exactly what he said:
![image](https://cloud.githubusercontent.com/assets/5897356/22199721/180060e4-e197-11e6-801c-60126f62aa39.png)

**Comment by dfpena** [comment]
@toby1991 did you try putting at the top of head of your first loaded html file? 

<script>
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;
</script>

**Comment by toby1991** [comment]
@dfpena 
ah... nop.

**Comment by janschoenherr** [comment]
Is this still an issue with the latest Beta 11?

**Comment by janschoenherr** [comment]
Please try the latest beta.

Please open another issue, if the problem persists. There have been quite a few changes.

**Comment by ascii-soup** [comment]
I seem to be getting this error in Chrome on beta 16. Line 9 in dist/uikit.js 

`var $$1__default = 'default' in $$1 ? $$1['default'] : $$1;`

I also seem to be unable to do a fresh build due to the following error:
`Cannot find module 'rollup'`
when it tries to build the icons in compile-js.

**Comment by spencode** [comment]
After downloading from the official site (Version 3.0.0-Beta.18) I received the same error (latest Crome, IE 11).
