### ISSUE TITLE
Sticky width after resize beta 4

### ISSUE THREAD

**Issue by KaisTag** [uikit/uikit#2265]
Sticky width after resize beta 4 
resize it doesn't recalculate (tested on firefox)

![2017-01-18_20-15-10](https://cloud.githubusercontent.com/assets/19313953/22079238/6c877a56-ddbb-11e6-85b4-c3080b4ec3c0.png)

**Comment by janschoenherr** [comment]
Please see https://github.com/uikit/uikit/issues/2261
