### ISSUE TITLE
The lack of analogue class `uk-hidden-medium`

### ISSUE THREAD

**Issue by AlekVolsk** [uikit/uikit#2267]
You cannot hide the block when the width of the screen between `@breakpoint-medium` and `@breakpoint-medium-max`

Also possible to hide the unit when the screen width is less `@breakpoint-xsmall-max`

**Comment by philoest** [comment]
We thought about this while developing the visibility component but we couldn't find a case where it would be helpful to show an element only on medium screens. Because of that we decided to not add such a class. 
If you need this you would need to create this with custom CSS

**Comment by AlekVolsk** [comment]
It should be in the warp to indicate the visibility of modules in the admin panel http://prnt.sc/dvgw1a
