### ISSUE TITLE
sortable breaks any other dynamic plugins when dragging to a new column

### ISSUE THREAD

**Issue by itsmill3rtime** [uikit/uikit#2269]
When using sortable with for example, uk-toggle. if you keep an item within the same column the uk-toggle still works. once you move it to another column (i have all columns using group: sortable-group) the uk-toggle no longer works. it loses its "bindings" i believe.  both ways change the location in the DOM however moving columns changes its parent in the DOM so i'm guessing that is where the problem lies

**Comment by janschoenherr** [comment]
Thanks, could you check if the above commit fixes your issue?
