### ISSUE TITLE
What are the requirements of UIkit?

### ISSUE THREAD

**Issue by beruic** [uikit/uikit#2273]
I'm trying to get started with UIkit 3, but I miss some information. For example I would like to know:

- Should use jQuery 2 or 3?
- Can I move the loading of the JavaScript to the bottom of the body to increase loading speed?
- What HTML elements should I start with? Should I always use a container like with Bootstrap?

**Comment by svjansen** [comment]
1. We use jQuery 3
2. Yes that shouldn't be a problem (I guess)
3. We use a <div> as main container with <div> childs arranged with uk-flex (is that what you want to know?)

**Comment by staleo** [comment]
1. Latest jQuery is better.
2. Of course, that's fine.
3. Depends on what you need, but uk-container was actually designed to make your visual structure neat and clean, why reject it then?

**Comment by beruic** [comment]
1. It would be nice with some documentation on the matters. I forexample doubt that UIkit is 100% compatible with both jQuery 1, 2 and 3.
2. If it's fine it should be recommended by the examples to make people make better sites :)
3. Again, it would be nice with some recommendations on what to use for main container, and when. Forexample when you make a splash page or a page with a menu.

**Comment by florianletsch** [comment]
1. UIkit 3 was developed and tested with jQuery 3.1.1. You are right, we should add that in the docs.
2. Yes, loading at the bottom of the page works. True, we could also update the examples. Good idea.
3. The "old" docs for UIkit 2 included sample layouts that showed how to use the container, etc. https://getuikit.com/v2/docs/documentation_layouts.html We haven't come around to creating new ones for the UIkit 3 docs, but I hope we will be able to some soon. In the meantime, maybe check the the past few yootheme releases and check out some of the page sources. It's pretty much all built with UIkit 3 markup, plus some theme specifics on top. https://demo.yootheme.com/

**Comment by uikid** [comment]
For point number 2, the comments here are incorrect. If you load the JS at the bottom of the page, your `uk-grid` can be show a "stacked" version instead of "side by side" for the elements (until the JS is loaded). This is in a lot of cases visible for a very short period.

Take a look at this isse: #2792

**Comment by zzseba78** [comment]
Yes, true. But if you add the class .uk-grid it you doesn´t get this effect.
`<div class="uk-grid" uk-grid></div>`
I always use it.
