### ISSUE TITLE
tooltip  and Right-click works as Left

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2274]
1. tooltip does not work, but the work title...
site:
![default](https://cloud.githubusercontent.com/assets/18468664/22101532/e6754468-de44-11e6-8c5b-02aef95cf50b.png)
code:
![111](https://cloud.githubusercontent.com/assets/18468664/22101582/1ae25e3e-de45-11e6-8a04-7d941c2522ef.png)

2. Right-click works as Left ([video](https://vk.com/video_ext.php?oid=193829540&id=456239036&hash=f3fdbc058023fb98))
On uikit 2 it worked and there was no problem with the right-click!

please help

**Comment by kirich1368** [comment]
lagg tooltip with php
how to solve?
https://vk.com/video_ext.php?oid=193829540&id=456239037&hash=daab9535b15b9533

**Comment by kirich1368** [comment]
Uncaught TypeError: modal.isActive is not a function

<script type='text/javascript'>
var modal = UIkit.modal('#ourgroup', {center: true});if (modal.isActive()) modal.hide();else modal.show();</script>

**Comment by kirich1368** [comment]
@svjansen

**Comment by kirich1368** [comment]
this.body.css("overflow-y",this.getScroll ......

Uncaught TypeError: Cannot read property 'css' of undefined
    at Modal.beforeshow (index.php?charset=utf-8&g=general&19:86)
    at HTMLDivElement.<anonymous> (index.php?charset=utf-8&g=general&19:86)
    at HTMLDivElement.dispatch (index.php?charset=utf-8&g=general&19:2)
    at HTMLDivElement.r.handle (index.php?charset=utf-8&g=general&19:2)
    at Object.trigger (index.php?charset=utf-8&g=general&19:2)
    at HTMLDivElement.<anonymous> (index.php?charset=utf-8&g=general&19:2)
    at Function.each (index.php?charset=utf-8&g=general&19:2)
    at n.fn.init.each (index.php?charset=utf-8&g=general&19:2)
    at n.fn.init.trigger (index.php?charset=utf-8&g=general&19:2)
    at Modal._toggleElement (index.php?charset=utf-8&g=general&19:86)

**Comment by svjansen** [comment]
@kirich1368 how exactly can I help you?
As far as i understand, right click triggers click event, that's what i've understand. what about the posted errors?

**Comment by kirich1368** [comment]
before:
![default](https://cloud.githubusercontent.com/assets/18468664/22141117/6a014e32-df01-11e6-8bf6-ac82f00ffe1f.png)

and now:
![1](https://cloud.githubusercontent.com/assets/18468664/22141124/736e8dc2-df01-11e6-9daf-ee8972d51720.png)

**Comment by bdthemes** [comment]
Right click problem me too :( don't understand what i wrong?

NOTE: previously i used uikit 2 with my project, I did all migration with UIKIT 3 Migration Bookmark.

**Comment by kirich1368** [comment]
how use confirm modal?

**Comment by kirich1368** [comment]
![default](https://cloud.githubusercontent.com/assets/18468664/22175989/9d502086-e011-11e6-8ee3-2a77f2f426e7.png)
