### ISSUE TITLE
Bower dependency behaviour

### ISSUE THREAD

**Issue by hiperion85** [uikit/uikit#2276]
Hello,

I have a project with uikit as a dependency in bower.json file, pointing to version 2.27.2. Sometimes, when using "bower install" to install dependencies, and try to build the project, I get an error for some missing files (under "src" directory).

I don't know why is this happening since I always point to the same uikit version on my bower file. I found out this issue seems to be happening when you bump version, but don't know if it might be related.

As an abstract, uikit v2.27.2 bower dependency, when installing it with "bower install", sometimes includes "src" directory, and sometimes it does not. Is that something I am missing?

My uikit bower.json entry is:
  "uikit": "2.27.2"

Help would be greatly appreciated, this is driving me crazy :)

**Comment by mktcode** [comment]
I just cleaned my bower cache and since then I always get the uncompiled less source insted of compiled css. I don't know why this is but my workaround is: `bower install https://github.com/uikit/bower-uikit.git`

**Comment by MalteScharenberg** [comment]
This issue is fixed for the latest release.
