### ISSUE TITLE
Animation not working with Angular 2 when passing value as input

### ISSUE THREAD

**Issue by asif633** [uikit/uikit#2279]
I am trying to use Angular 2 with uikit. When I am passing input into `uk-switcher` , the animation is not working. I am trying to create a `ng2-uk-tab` component. The template is shown below.
```
<ul [class]="addedStyle" [attr.uk-switcher]="ukswitcher" uk-tab >
    <li><a href="#">Item1</a></li>
    <li><a href="#">Item2</a></li>
    <li><a href="#">Item3</a></li>
</ul>

<ul class="uk-switcher uk-margin">
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
</ul>
```
The component code
```
import { Component, OnInit, Input } from '@angular/core';

@Component({
    selector: 'ng2-uk-tab',
    templateUrl: './tab.component.html',
    styleUrls: ['./app.component.less']
})
export class TabComponent implements OnInit {
    constructor() { }

    ngOnInit() { }
    @Input()
    addedStyle: string ;
    @Input()
    ukswitcher: string;

}
```
You can see the `<ul>` has `uk-child-width-expand` added by input `addedStyle` working fine. But added `uk-switcher="animation: ...."` added by `ukswitcher` is not working, there is no animation when rendered. What is the reason behind this ?
![uikit](https://cloud.githubusercontent.com/assets/5786091/22157610/5eb9efa4-df5e-11e6-86e7-4b8ecb43243b.png)

**Comment by jakloove** [comment]
This happen not only with the animation, but with all options in any uikit component.

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
