### ISSUE TITLE
Custom prefix in uikit3

### ISSUE THREAD

**Issue by gabyferman** [uikit/uikit#2281]
Is custom prefix still usable on uikit3?

**Comment by nblackburn** [comment]
It is, as far as i am aware it should be exactly the same as it was.

**Comment by philoest** [comment]
This can be done with the following command:

`npm run prefix -- -p myprefix`

Note that this will give also the UIkit Javascript the prefix.

**Comment by gabyferman** [comment]
Hi,
I've tried but something is not working, in which folder should I run the command?

**Comment by nblackburn** [comment]
@gabyferman the one with uikit installed in, if you get an error, drop it in a reply and i can take a look at it for you.

**Comment by gabyferman** [comment]
So I ran it in my node_modules/uikit folder, first I tried `npm install` and `npm run compile` like the installation docs mentioned, and it gave me an error:

[http://goodbadtaste.com/npm-debug.zip](http://goodbadtaste.com/npm-debug.zip)

even with the error I tried to run the command, and it doesn't mark an error but nothing is change, I suppose the prefix change it's made in the dist folder.

Sorry for the download link but I wasn't letting me attach the file.
