### ISSUE TITLE
DOCS: how to style rounded button used in UIKit docs

### ISSUE THREAD

**Issue by keyscores** [uikit/uikit#2282]
In the docs page, the 'download' button is styled differently than the standard UIKit buttons. It uses a selector called 'tm-button-default' . Can you document how this style is achieved?

**Comment by philoest** [comment]
this is done with some theme customization which can be seen in the uikit-site repository ( https://github.com/uikit/uikit-site ) the theme.less stored within the less folder is also added to the theme.css additionally to the UIkit less files.

**Comment by keyscores** [comment]
@philoest   Looks great. Would be nice to have this option in the library.
