### ISSUE TITLE
Document how to use uikit3 with requirejs / AMD loaders

### ISSUE THREAD

**Issue by pscheit** [uikit/uikit#2283]
Hey there,

maybe i'm to blind to see, but is there documentation how to use uikit with requirejs? Is there special config needed? I cannot figure out how to use the modules and files (from which source).

Thank you in advance
Philipp

**Comment by janschoenherr** [comment]
Please try the latest Beta 11.

**Comment by janschoenherr** [comment]
Fixed with Beta 14. Thanks.
