### ISSUE TITLE
Offcanvas w/ nav component that has parent with child navigation not expanding/collapsing

### ISSUE THREAD

**Issue by shenst1** [uikit/uikit#2284]
A navigation bar inside of an offcanvas with child navigation does not expand and collapse.

**Comment by philoest** [comment]
Do you have a codepen example where we can take a look at?

**Comment by shenst1** [comment]
It doesn't work in the uikit example https://getuikit.com/docs/offcanvas. Notice how you can't click on the parent to hide and show the two sub items. 
The nav in v2 https://getuikit.com/v2/docs/offcanvas.html would expand and collapse

**Comment by shenst1** [comment]
I was being an idiot. They don't expand and collapse in the demo because it hasn't been updated to use a uk-nav component yet, only classes. When made a component, all works correctly.
