### ISSUE TITLE
UIKit3 (beta 5):  The problem with the visibility  uk-search-icon and  uk-navbar-toggle-icon

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2286]
os UNIX
https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
**so not is displayed** 
`<span class="uk-search-icon-flip" uk-search-icon></span>`
**so is displayed**
`<span uk-search-icon="" class="uk-search-icon uk-icon">
 <svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ratio="1">
  <circle fill="none" stroke="#000" stroke-width="1.1" cx="9" cy="9" r="7"></circle>
  <path fill="none" stroke="#000" stroke-width="1.1" d="M14,14 L18,18 L14,14 Z"></path>
 </svg>
</span>`

similarly for uk-navbar-toggle-icon
...
what can I do? ))

ps
simple svg  icons are displayed normally
pps
on the local machine under windows html with uk-search-icon and uk-navbar-toggle-icon are displayed normally

**Comment by holictoweb** [comment]
i have same problem uk-icon work well.
but kind of complicated icon like uk-search-icon are not work

**Comment by AlexandreZaytsev** [comment]
in 6 release fixed
