### ISSUE TITLE
Upload File [Broken]?

### ISSUE THREAD

**Issue by residentof254** [uikit/uikit#2287]
I noticed that the #select feature featured on the documentation site doesn't support <input type="file">
` <input type="file" multiple><button class="uk-button uk-button-default" type="button" tabindex="-1"></button>`

I tried this also looked into the CSS folder and there was no support. Instead the default browser interprets it differently (I used Mozilla and Opera) and am going for a clean look.

**Comment by philoest** [comment]
What do you mean by it does support `<input type="file" multiple><button class="uk-button uk-button-default" type="button" tabindex="-1"></button>`??

I tested this in chrome firefox and opera and here selecting multiple files and upload worked as expected.

**Comment by residentof254** [comment]
![screenshot at 2017-01-26 09-44-21](https://cloud.githubusercontent.com/assets/25295828/22322511/94469aca-e3ad-11e6-8b06-13f6b40476e2.png)
![screenshot at 2017-01-26 09-46-43](https://cloud.githubusercontent.com/assets/25295828/22322533/b042baec-e3ad-11e6-800f-40e9b5bf1b5c.png)
![screenshot at 2017-01-26 09-54-41](https://cloud.githubusercontent.com/assets/25295828/22322535/b37a04b8-e3ad-11e6-9079-6ff1d8df0fda.png)

From the upload images. My desired result should reflect from the documentation examples of upload (select feature) instead I get a different result both on Mozilla and Opera. Kindly assist. What am I not doing right?

**Comment by residentof254** [comment]
I think the problem lies with the CSS, I tried using uikit.css it gave me the desired result but if you used uikit.almost-flat.min.css it didn't bring the desired effect. However uikit.css does not give me a clean look... everything is in blocks.

**Comment by philoest** [comment]
Within UIkit3 there is no alsmost-flat theme. You would need to use the default theme.

**Comment by janschoenherr** [comment]
Please check https://getuikit.com/docs/form#custom-controls

If the problem persists, please reopen the issue.
