### ISSUE TITLE
Uncaught Error: Cannot find module "uikit"

### ISSUE THREAD

**Issue by paduwan5** [uikit/uikit#2289]
Upgraded from v.2.27.2 to 3.0.0-beta5 and pulling uikit.js via webpack require.  I am getting the following error.  I did not get this error in v2.27.2.  Any assistance will be appreciated

<img width="1138" alt="screen shot 2017-01-23 at 2 32 38 pm" src="https://cloud.githubusercontent.com/assets/3770085/22225964/4df7f450-e179-11e6-927f-22ccf395f280.png">

**Comment by RapidTransit** [comment]
In uikit/build/build.js, look for 
`  globals,
            format: 'umd',
            banner: util.banner,
            moduleName: 'UIkit'`
add `moduleId: 'UIkit'`

**Comment by paduwan5** [comment]
Thanks for the tip.  I tried adding moduleId: UIkit to build.js as indicated, then ran npm run compile.  I am still getting the same error.

**Comment by RapidTransit** [comment]
I got a weirder error, try going back and doing this: 

```
  externals: {
            "uikit": "UIkit"
        }
```

And just place a UIkit JS in a script tag.

**Comment by janschoenherr** [comment]
Is this still an issue with Beta 11?

**Comment by janschoenherr** [comment]
Fixed with Beta 14.
