### ISSUE TITLE
Prevent offcanvas from closing

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#2290]
Offcanvas if quite nice for small forms, in my case a very basic user account edit form.

On that form there is field that requires user to input date. However since the inline calendar has been removed from v3 I have to utilise some other plugin to achieve this.

It all works fine if the date user needs is in the current month (shown), then a click on the day just populates the required field. The problem is when the desired date is not visible, and I have to move the month or year to find what I need - the very moment I do this, the offcanvas goes away.

Is there a way to prevent canvas from closing until, for example a button on that offcanvas is clicked?
If not is it possible to implement such functionality into v3.

**Comment by janschoenherr** [comment]
Is this still happening with the latest Beta 16?

**Comment by janschoenherr** [comment]
I will close this for now. The Offcanvas component has been refactored with the latest update.

**Comment by dandansoysauce** [comment]
Hi, do you have a workaround for this one?
