### ISSUE TITLE
Can change the background color for the progress component

### ISSUE THREAD

**Issue by randyyaj** [uikit/uikit#2295]
I'm using UIKIT3 and am wanting to change the color of the progress bar similar to https://getuikit.com/v2/docs/progress.html uikit's v2 way of changing it. I tried changing it via CSS but had no luck.

**Comment by philoest** [comment]
Via CSS you can do it that way:

```
.uk-progress::-webkit-progress-value{
  background-color: red;
}
.uk-progress::-moz-progress-bar {
  background-color: red;
}
```

There is also a LESS variable for this if you downloaded the code, which can be found in the progress component.

**Comment by randyyaj** [comment]
Thanks!

**Comment by randyyaj** [comment]
Came back to add what I did to get it working.

```<progress class='uk-progress uk-progress-danger'>```

``` 
  .uk-progress-danger::-ms-fill {
    background-color: #f0506e;
  }

  .uk-progress-danger::-moz-progress-bar{
    background-color: #f0506e;
  }

  .uk-progress-danger::-webkit-progress-value {
    background-color: #f0506e;
  }

  .uk-progress-success::-ms-fill {
    background-color: #32d296;
  }

  .uk-progress-success::-moz-progress-bar{
    background-color: #32d296;
  }

  .uk-progress-success::-webkit-progress-value {
    background-color: #32d296;
  }
```
