### ISSUE TITLE
Image Overlay overshooting container

### ISSUE THREAD

**Issue by cholasimmons** [uikit/uikit#2298]
The overlay div seems to shoot out of the left side of the container div, the one with the class "uk-inline".
`<div class="uk-width-3-4@m uk-inline">
          <img src="./img/art/main01.jpg" alt="" />
          <div class="uk-overlay uk-overlay-primary uk-position-bottom">
              <p>19:00</p>
          </div>
        </div>`

![uikit_issue01](https://cloud.githubusercontent.com/assets/6698741/22292853/fac7250a-e315-11e6-9399-bb60f732e8ad.JPG)

**Comment by viocassel** [comment]
`
<div class="uk-width-3-4@m">
	<div class="uk-inline">
		<img src="./img/art/main01.jpg" alt="" />
		<div class="uk-overlay uk-overlay-primary uk-position-bottom">
			<p>19:00</p>
		</div>
	</div>
</div>
`

**Comment by viocassel** [comment]
```
<div class="uk-width-3-4@m">
  <div class="uk-inline">
    <img src="./img/art/main01.jpg" alt="" />
    <div class="uk-overlay uk-overlay-primary uk-position-bottom">
      <p>19:00</p>
    </div>
  </div>
</div>
