### ISSUE TITLE
modal event

### ISSUE THREAD

**Issue by davidtim** [uikit/uikit#2301]
hello, I have a problem. I try modal beforeShow it's not working, and the modal's event "show" it shows after modal is close

**Comment by drpiou** [comment]
I have the same problem for non working "beforeHide" and "beforeShow" events. Events "show" and "hide" work as expected.

**Comment by davidtim** [comment]
I have not try the hide event, but show event also not working for me.

**Comment by dmitriyermolin** [comment]
These events are actually named in lowercase -  'beforeshow' and 'beforehide' according to source: https://github.com/uikit/uikit/blob/develop/src/js/mixin/modal.js#L81 and https://github.com/uikit/uikit/blob/develop/src/js/mixin/modal.js#L137

**Comment by janschoenherr** [comment]
Thanks, the docs have been updated.
