### ISSUE TITLE
Consider using standard element attributes

### ISSUE THREAD

**Issue by mannyvergel** [uikit/uikit#2302]
I'm trying the example with React js:
```
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
            <li class="uk-active"><a href=""></a></li>
            <li class="uk-parent"><a href=""></a></li>
            <li><a href=""></a></li>
        </ul>
    </div>
</nav>
```
And it gave me a warning that uk-navbar is an unknown prop. Maybe in future versions, consider using standard props like data-* attributes:

Reference: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by viocassel** [comment]
React will work with `data-uk-*` prefixes only.

**Comment by saschadube** [comment]
It is already implemented. You can also use ```data-uk-*``` See [documentation](https://getuikit.com/docs/javascript#component-usage)
