### ISSUE TITLE
Namespacing doesn't work as expected in UIkit3

### ISSUE THREAD

**Issue by dsignr** [uikit/uikit#2303]
When you run the namespace generator:
`npm run compile`
`node build/prefix -p xyz`

The CSS file is generated correctly. However, the JS file prefixes the namespace before the global `UIkit` javascript object. So, if I run `node build/prefix -p xyz`, the global UIKit object is now xyzUIKit. 

The consequence is that the components fail to function correctly - for example, modals. This is only happening in UIKIT3 and not the previous versions.

![blob](https://cloud.githubusercontent.com/assets/5097028/22338273/f2afbb04-e421-11e6-9f84-5aee2bb6b784.png)

**Comment by dsignr** [comment]
@philoest Thanks, that was quick and awesome :)

**Comment by bassmanpaul** [comment]
I am having similar issues with getting the namespaced `js` to work. It would appear that there are quite a lot of un-namespaced `"uk-"` prefixes still in the `js` as opposed to `"xyz-"`.
