### ISSUE TITLE
Accordion Disappears

### ISSUE THREAD

**Issue by nicjohnson145** [uikit/uikit#2305]
I have an accordion nested inside of a modal dialog with the container modifier on it. When the mouse is inside of the modal, everything is fine. However whenever the mouse is outside the modal, the entire accordion disappears.

**Comment by philoest** [comment]
Do you have an example page or a codepen where this problem is visible?

**Comment by nicjohnson145** [comment]
I came back to make a codepen and found the problem. It was my fault, not UIKit.
