### ISSUE TITLE
Add variable for accordion icon path instead of hardcoded it

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2307]
Please add variable @internal-accordion-image like as in other components, instead of hardcoded the path
https://github.com/uikit/uikit/blob/develop/src/less/theme/accordion.less#L41

**Comment by philoest** [comment]
Thanks for reporting changed this https://github.com/uikit/uikit/commit/43ea0270bd71544acd9bc897bacc4548478c3493
