### ISSUE TITLE
Inverse colors on offcanvas are too presumptive

### ISSUE THREAD

**Issue by shenst1** [uikit/uikit#2308]
The css should not assume that an offcanvas will be inverted. In fact, the uikit theme is not inverted itself. If a user wants to invert the offcanvas, they should just add ```uk-light``` to the ```uk-offcanvas-bar``` Overwriting all those styles is a pain.

**Comment by philoest** [comment]
Have you tried changing the offcanvas-bar-color-mode variable within the less file:
https://github.com/uikit/uikit/blob/develop/src/less/components/offcanvas.less#L32

This should do the work :)

**Comment by shenst1** [comment]
I am trying to use  uikit out of the box from a cdn and so far it is going well aside from this. If i want to change that one variable, I will have to set up less compiliation in my rails project which seems like a lot of work to change one variable. I think the correct approach to a dark background on an offcanvas is adding the class ```uk-light```.  I know i should be setting the project up with less variables no matter what, but either way, I would stand by the dark offcanvas being too presumptive especially when the demos don't match.

**Comment by shenst1** [comment]
Now that there is scss, this shouldn't be as much of an issue.
