### ISSUE TITLE
Modal Raw JS handles not working

### ISSUE THREAD

**Issue by ankemp** [uikit/uikit#231]
``` javascript
var modal = new $.UIkit.modal.Modal(".modalSelector");

if ( modal.isActive() ) {
    modal.hide();
} else {
    modal.show();
}
```

This is not working.

Any suggestions?

**Comment by imarkdesigns** [comment]
I would like to confirm this, and it is not working on my code, along with the screenshot.

`<a href="" class="uk-button uk-button-primary uk-width-1-1 open-modal" data-content="<?php echo $post->ID; ?>" data-uk-modal="{target:'#donate-info',bgclose:false,center:true}"><?php echo $donate_button; ?></a>`

```
var modal = UIkit.modal(".uk-modal");

if ( modal.isActive() ) {
    modal.hide();
} else {
    modal.show();

    $.ajax({
      type: 'GET',
      dataType: 'json',
      url: 'dynamic-box.php',
      data: 'data='+postID,
      success: function(data) {
        $('.fetched-data').html(data);
      }
    });
}

```
![screen shot 2017-01-23 at 12 29 55 pm](https://cloud.githubusercontent.com/assets/1100419/22191636/bfced7a4-e167-11e6-8636-f8189eb11053.png)
