### ISSUE TITLE
[UIkit 3, Beta 6] Accordion: Internal elements do not work

### ISSUE THREAD

**Issue by carlos-duran** [uikit/uikit#2315]
I have tried using some elements that make use of javascript inside the accordion and unfortunately do not work.
The same happened when I tried to nest an accordion inside another.

Here is my test: [http://codepen.io/anon/pen/VPrvjV](http://codepen.io/anon/pen/VPrvjV)

I hope this functionality is available soon, thank you very much for this excellent framework.

**Comment by janschoenherr** [comment]
So basically nesting accordions is not working? The editors seem to work fine?

**Comment by janschoenherr** [comment]
Should be resolved with 389851508f00320a396a2f9218387908db491244
