### ISSUE TITLE
[Question] Sass support

### ISSUE THREAD

**Issue by OwenMelbz** [uikit/uikit#2317]
Hi guys, I've seen you've mentioned a few times that you'll eventually be providing sass source files in addition to the less files.

My question is however about when we could expect to see this? Would you guys say its expected within the next few weeks? or maybe within the next month? or maybe in 6 months time?

Just so we can get a grasp on some new projects and how we're going to start them, if its worth waiting or just changing back to less for them?

Thanks :)

**Comment by SaphiLC** [comment]
i prefer sass too, hope they listen to us :D

**Comment by leandroruel** [comment]
yeah, i visited the docs looking for something about sass, but just found Less support (sad) :cry:

**Comment by hoangcuongvn** [comment]
+1 sass support

**Comment by harlet** [comment]
+1 for Sass

**Comment by kadirpace** [comment]
+1 too

**Comment by viviangb** [comment]
+1 for Sass too!

**Comment by alexandesigner** [comment]
I could contribute to this issue .. I think in addition to less and sass we could also support stylus .. I am willing to get this task in a new branch .. just wonder if there is any restriction on this. Do you have a task in progress? @saschadube

**Comment by andrewjdmartin** [comment]
+1 for Sass

**Comment by chromjak** [comment]
+1 for Sass

**Comment by Maybach91** [comment]
+1 for Sass

**Comment by FlyingGekkota** [comment]
+1 for Sass

**Comment by mjbates7** [comment]
+1 for sass

**Comment by j26w** [comment]
I'm interested in this as well. Does anyone know what issues might arise when using an automated tool like [this](https://www.npmjs.com/package/gulp-less-to-scss)? Referenced in [this article (re v2)](https://medium.com/@imikay/how-to-integrate-uikit-with-theme-as-sass-files-into-you-project-60a1263da679#.qouxfx32j).

**Comment by dimitrilongo** [comment]
+1 for sass

**Comment by onefriendaday** [comment]
I was able to adapt the less to sass transformation tasks taken from Uikit 2 to do the same for Uikit 3

Here is the fork: https://github.com/storyblok/uikit/tree/feature/sass_support
All the generated scss files are in src/scss

It uses the less files and transforms it to sass which works pretty well.
The only thing I needed to adapt manually was the uikit-variables.scss file because 9 variables where generated in the wrong order.

**Comment by OwenMelbz** [comment]
Woo :)

https://yootheme.com/blog/2017/04/12/uikit-3-beta-roundup
