### ISSUE TITLE
Grid inside flex-* doesn't work properly

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2318]
```
<div class="uk-background-primary uk-flex uk-flex-center uk-flex-middle" uk-height-viewport>
	<div class="uk-container">
		<div uk-grid>
			<div class="uk-width-1-2">
				Lorem
			</div>
			<div class="uk-width-1-2">
				Lorem
			</div>
		</div>
	</div>
</div>
```
The grid inside the flex-* wrapper should also have 100% width, but haven't :)

// edit:
I can add ```uk-flex-1``` into the ```uk-container``` like this:
```<div class="uk-container uk-flex-1">```
but it is a good solution?

**Comment by philoest** [comment]
Best practice would be a surrounding `<div class="uk-width-1-1">` for the container. You might also want to consider using a section for your parent div. 

http://codepen.io/philoest/pen/OWQXbr/
