### ISSUE TITLE
Uikit 3 (beta 6): Migration Close Icon Navbar?

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2319]
url - https://getuikit.com/docs/search (Firefox 51.0.1 Windows 7)
test Migration - https://getuikit.com/docs/migration#browser-bookmark

message
```
%cNotice: %cTo get the burger menu you need the addition attribute **# uk-navbar-toggle-icon**.%c color:#ffb24e;font-size:13px; font-size:12px; migrate.min.js:3
<a class="uk-navbar-toggle uk-close uk-icon" uk-close="" uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#">  migrate.min.js:3:2599
"More info: http://getuikit.com/docs/navbar"
```

uk-navbar-toggle-icon ->> this error message? or?

**Comment by philoest** [comment]
I am not sure what you mean, but the message is only a Notice which means that you have to decide if you need to take a look at this. In this case you need to take a look if you need the uk-navbar-toggle attribute since the way this is created has changed from UIkit2

**Comment by AlexandreZaytsev** [comment]
just the documentation uikit3 for the # **close component** is not specified use uk-navbar-toggle attribute - and the debugger issues a warning...
that's the question... 
maybe just the documentation forgot to specify the attribute? or the debugger incorrectly warns

**Comment by philoest** [comment]
No this warning is targeting the uk-navbar-toggle-icon when it is used within the navbar. You would need the burger menu to open the offcanvas menu. But this is independet from the uk-close icon :)
https://getuikit.com/docs/navbar#toggle-item

**Comment by AlexandreZaytsev** [comment]
thank you, here is an example from the documentation (uikit3 Search), how to arrange code to avoid warnings migration uikit3?

```
<nav class="uk-navbar-container uk-margin" uk-navbar>
    <div class="nav-overlay uk-navbar-right">
        <a class="uk-navbar-toggle" uk-search-icon uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
    </div>

    <div class="nav-overlay uk-navbar-left uk-flex-1" hidden>
        <div class="uk-navbar-item uk-width-1-1">
            <form class="uk-search uk-search-navbar uk-width-1-1">
                <input class="uk-search-input" type="search" placeholder="Search..." autofocus>
            </form>
        </div>
        <a class="uk-navbar-toggle" uk-close uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
    </div>
</nav>
```

**Comment by philoest** [comment]
If everything is working and the notice still shows up, everything is fine, we are using CSS selectors to check if a warning / notice needs to be shown. There are selectors which will also print out the notice on a warning page

> Notices highlight potential issues that might not break your site. Some notices might not require a change at all. This is caused by the fact that some names from UIkit 2 still exist in UIkit 3, but now belong to a different component or carry different semantics. This can't be detected by the selectors we use to determine if this is a correct markup, so you need to take a look into it and need to decide if you already have changed it or still need to fix it.
(https://getuikit.com/docs/migration#notices)

**Comment by AlexandreZaytsev** [comment]
ok, thanks
