### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#2320]
v2 of UiKit has a lot of javascript components. For example: Lightbox, Autocomplete, Datepicker etc.

Will these features include in v3 as well in the future?

**Comment by jdeheus** [comment]
I believe that they laid out the roadmap in [this](https://yootheme.com/blog/2017/01/09/uikit-3-beta-released) blogpost.

**Comment by papazetis** [comment]
Thank you @jdeheus. The answer is there....

**What's missing**

This is a beta release and as such it is to be considered a work in progress. A number of components still need to be reworked and will be added in the future. Our focus for this release has been to create a stable core and provide extensive documentation right from the start. Next on our list are the Slideshow, Slider, Slideset, Parallax, Nestable, Lightbox, Dynamic Grid, HTML editor, Date- and Timepicker components.

**Comment by scott8803** [comment]
Autocomplete is not on the list of next.  Should clarify if it’s been dropped or add it to the list.
