### ISSUE TITLE
Uikit3 two nested grids next to each other don't align.

### ISSUE THREAD

**Issue by inytar** [uikit/uikit#2327]
When doing the following the text in the nested grids are not aligned. Uncommenting the div in between results in aligned text.
```html
<div uk-grid>
  <div uk-grid>
    <div class="uk-card uk-card-body uk-card-default">1.1</div>
    <div class="uk-card uk-card-body uk-card-default">1.2</div>
  </div>
  <!-- <div> -->
  <!-- </div> -->
  <div uk-grid>
    <div class="uk-card uk-card-body uk-card-default">2.1</div>
    <div class="uk-card uk-card-body uk-card-default">2.2</div>
  </div>
</div>
```
Without div in between: ![screenshot from 2017-01-30 18-14-16](https://cloud.githubusercontent.com/assets/1442084/22445974/3a13d3ba-e718-11e6-85fd-e92a5db6d471.png)
With div in between: ![screenshot from 2017-01-30 18-13-32](https://cloud.githubusercontent.com/assets/1442084/22445975/3a14043e-e718-11e6-81b5-be4f5dc9eb88.png)

I see the same efect in both Firefox and Chrome.

**Comment by inytar** [comment]
Using .uk-grid-collapse in the children grids seems to solve the problem.

**Comment by philoest** [comment]
Please take a look how nested grids work:
https://getuikit.com/docs/grid#nested-grid

Both grids apply CSS changes to the same div in your case which leads to the problem.

**Comment by inytar** [comment]
Thanks, that fixed it!
