### ISSUE TITLE
Some missing semicolons 

### ISSUE THREAD

**Issue by dragonnn** [uikit/uikit#2329]
I am starting a new project witch total.js and it have a really simple js compressor. After uikit.js goes through it i get some errors in the browser console. The are some missing semicolons in it, I created a patch to fix those:

http://pastebin.com/p6zSwPLH

Could you include it in future versions?

**Comment by philoest** [comment]
This can't be fixed since this comes from the build process which puts all the components together. We would recommend to use uglifyjs. You can also use the already compressed uikit.min.js file.
