### ISSUE TITLE
[Question] How to add more colors?

### ISSUE THREAD

**Issue by mohamedsabil83** [uikit/uikit#2333]
It's clear how to change the current color by change the color hex value.

### My question is:
**how to add more color value and let it apply to all components** (text, background, ...etc)
like add variable $color-yellow = yellow then apply it to get (uk-text-yellow, uk-background-yellow, ...etc).

It's very important as almost site I developed need to use more then basic color.

**Comment by philoest** [comment]
When the basic color options are not enough ( default UIkit3 comes with 3 colors when I am not missing one ( primary, secondary, default ) where you can change the colors to your needs ) you have to add the other colors with custom classes. There is no script or auto generation for more color classes in all components.
