### ISSUE TITLE
UIKit 3 - Off-canvas zoom-in on mobile safari

### ISSUE THREAD

**Issue by Kimleang** [uikit/uikit#2334]
I'm using off-canvas it works fine in the computer browser but when I click on mobile, it zoom-in and cannot zoom-out.

Device: Mobile Safari iOS9
UIkit: 3.0.0 beta 6
Demo Video: https://youtu.be/42WiCogyiOg

**Comment by philoest** [comment]
Does this still appear on the newest version? Tried this with the simulator and here everything worked as expected. If there is still a problem please add a link so we can take a look

**Comment by Kimleang** [comment]
@philoest yes, it's still happening in beta8, now I've figured out the problem.
it happens when I set overlay in off-canvas to true. when I remove the overlay from off-canvas the iOS9 device is working fine without the problem.

I'm testing on two devices one running iOS9.0.2 and another device is running on iOS10.2.
The iOS10 is working fine with overlay set to true.
and here is the sample code I've test.
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.8/css/uikit.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.8/js/uikit.min.js"></script>
  </head>

  <body>

    <nav uk-navbar class="sd-border-bottom sd-border-medium">
      <div class="uk-navbar-left">
        <a href="" class="uk-navbar-item uk-logo">LOGO HERE</a>
      </div>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav uk-visible@m">
          <li><a href="">Home</a></li>
	</ul>
	<a class="uk-navbar-toggle uk-hidden@m" uk-navbar-toggle-icon uk-toggle href="#off-canvas"></a>
      </div>
    </nav>
		
    <div id="off-canvas" uk-offcanvas="flip: true; overlay: true;">
      <div class="uk-offcanvas-bar">
        <ul class="uk-nav uk-nav-default">
          <li><a href="">Home</a></li>
        </ul>
      </div>
    </div>

  </body>
</html>
```

**Comment by janschoenherr** [comment]
We have refactored the Offcanvas component. If the issue persists, I will reopen this issue.
