### ISSUE TITLE
Uikit 3 (beta 7): search-in-navbar overlay - increases the height of the component

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2335]
in beta 6 all was good except the Android browser 'Internet' (close icon goes to new line)
in beta 7 close icon goes to new line in all browsers where it was tested (Unix, Windows System)
![search_](https://cloud.githubusercontent.com/assets/16114000/22510927/e8213924-e8a4-11e6-813c-d9208deebc33.jpg)

```
<nav class="uk-navbar-container uk-margin" uk-navbar style="height: 50px;     background: #94e7ff;">
   <div class="nav-overlay uk-navbar-right">
    <a class="uk-navbar-toggle" uk-search-icon uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
   </div>
   <div class="nav-overlay uk-navbar-left uk-flex-1" hidden>
    <div class="uk-navbar-item uk-width-1-1">
     <form class="uk-search uk-search-navbar uk-width-1-1">
      <input class="uk-search-input" type="search" placeholder="Search..." autofocus>
     </form>
    </div>
    <a class="uk-navbar-toggle" uk-close uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
   </div>
  </nav>
```

**Comment by saschadube** [comment]
Thanks! Fixed with this commit. https://github.com/uikit/uikit/commit/fb54e001380654c1a715b9e3aec2002b258bf1b1

Use ```uk-width-expand``` instead of ```uk-width-1-1```

**Comment by Diegopintos** [comment]
`<nav class="uk-navbar-container uk-margin" uk-navbar style="height: 50px;     background: #94e7ff;">
  
	<div class="nav-overlay uk-navbar-right">
    <a class="uk-navbar-toggle" uk-search-icon uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
   </div>
   <div class="nav-overlay uk-navbar-left uk-flex-1" hidden>
    <div class="uk-navbar-item uk-width-1-1">
     <form class="uk-search uk-search-navbar uk-width-expand">
      <input class="uk-search-input" type="search" placeholder="Search..." autofocus>
     </form>
    </div>
    <a class="uk-navbar-toggle uk-float-right uk-position-absolute uk-position-right" uk-close uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
   </div>
</nav>`
