### ISSUE TITLE
bug with icon 

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2336]
[check video](https://vk.com/video_ext.php?oid=168560504&id=456239029&hash=06a499a372b52e70)

`<span class="uk-text-danger" uk-icon="icon: ban"></span>`

**Comment by SaphiLC** [comment]
unless you give more info or post your code... it looks like you didn't close a tag correctly but can't tell since no code

**Comment by kirich1368** [comment]
fix please

**Comment by philoest** [comment]
has been fixed :)

**Comment by kirich1368** [comment]
thanks thanks thanks thanks
