### ISSUE TITLE
Icons not showing (beta7)

### ISSUE THREAD

**Issue by SaphiLC** [uikit/uikit#2337]
I updated the less and js files to the latest beta7 and the icons are not appearing, then i replaced the uikit.js with the beta6 one and they appear again. I get no errors in the console so i have no idea what's wrong

Also i would like to suggest a global variable for the directory of the icons, that way 99.99% of the people will just replace one variable instead of 32457398472398792, thanks

**Comment by zzseba78** [comment]
Same problem here with Beta 7

**Comment by bdthemes** [comment]
It's happening again and again, 
beta 5 = problem 
beta 6 = worked and 
beta 7 = again not working :(

**Comment by bauer01** [comment]
+1

**Comment by alanfm** [comment]
+1

**Comment by arysom** [comment]
I've also have similar problems, althougt I use cdn, setting .uk-icon::before (../images/icon.svg) helped a little, but after 6th beta js file stopped working. Beta 7 and 8 - my icons don't work in firefox 51.0.1 .Using js file from 6th beta - ok. Also spinner is absent.

**Comment by drpiou** [comment]
Icons not working at all on my iOS device (beta 6-8)... What can I do ? Chrome Desktop and Android print the SVG inside the uk-icon, but leave empty on iOS.

**Comment by m-ahmadi** [comment]
Same issue. (icons not showing)
beta 6:  works fine
beta 7: not showing
beta 8: not showing

**Comment by vidhogskole** [comment]
+1

**Comment by franctic-aerobic** [comment]
+1

**Comment by zzseba78** [comment]
Works only if you call the js scripts in the head, if i put them before closing body tag it doesn't work, and if i put the scripts in the head and use **defer** it doesn't work.

**Comment by Rawlings** [comment]
Also if you're using Cloudflare, make sure to disable Rocket Loader

**Comment by danny-englander** [comment]
This seems to be an issue from trying to load from Cloudflare, I'm getting this error in console:

```No 'Access-Control-Allow-Origin' header is present on the requested resource. not allowed access.```

**Key points**

- Putting the script in the head had not effect.
- I tried disabling Rocket loader from cloudflare and that had no effect. 
- I also tried adding in the SRI but that did work not either (`crossorigin="anonymous"`). 
- This seems to be an issue if you're using something like a local Gulp or Jekyll server, e.g. `http://192.168.1.5:3000/...`

I found [this issue](https://github.com/uikit/uikit/issues/2229) which seems a little more specific about the error. 

At any rate, loading JS and CSS locally fixes it for me. In my case with Jekyll, I may just write and if / else to load the CDN or local depending on the environment for now.

**Comment by SaphiLC** [comment]
Danny, i use less and the paths are pointing to my icons folder, i get 0 console errors, the only way the icons show is placing the javascript inside the <head> (and if i add defer it stops working), the other way for the icons to appear is using the beta6 js file... so i'm assuming is a "bug" with the JS (a bug that shows no errors >_> )
(also, not sure what #2229 solves :( )

**Comment by danny-englander** [comment]
@SaphiLC Thanks for the info, maybe you can update the issue title to flag it as related to Less. Sorry, I guess I should have posted my comment in #2229.

**Comment by SaphiLC** [comment]
but i said it is related to JS xD

**Comment by zzseba78** [comment]
> It's happening again and again,

beta 5 = problem
beta 6 = worked and
beta 7 = again not working
beta 8 = again not working
beta 9 = again not working

**Comment by bdthemes** [comment]
@zzseba78 @m-ahmadi @franctic-aerobic  please call uikit.js in head so it will work good 😄

**Comment by m-ahmadi** [comment]
@bdthemes That's something I don't prefer to do, I don't like loading scripts in the head. (and for good reasons)

**Comment by cartz** [comment]
@bdthemes No, icons do not show up using 

`<span uk-icon="icon: check; ratio: 3.5"></span>`

with 

```
<link rel="stylesheet" href="node_modules/uikit/dist/css/uikit.css">
<script src="node_modules/jquery/dist/jquery.min.js"></script>
<script src="node_modules/uikit/dist/js/uikit.min.js"></script>
```

in my header, they do not show up! but they are working inside the menu.

**Comment by bdthemes** [comment]
Hmm, something strange 🤔 

it's working fine for me with beta 9: [http://prntscr.com/e58hdh](http://prntscr.com/e58hdh)

**Comment by andrewrutley** [comment]
+1

**Comment by gingibash** [comment]
when using safari in private mode, beta9 throws an error QuotaExceededError (DOM Exception 22): The quota has been exceeded and does not show the icons. But browsing in normal window it works ok.

**Comment by nor-bu** [comment]
+1

**Comment by wannaco** [comment]
Unless jquery and css files are added to the head, icons won't work. any particular reason why it is required to add those files in the head?

**Comment by Edaks** [comment]
beta 10, icons only work if JQuery and uikit.min.js added to the head.

**Comment by akayaday** [comment]
beta 10, I get an error: `XMLHttpRequest cannot load https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.10/images/icons.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:29210' is therefore not allowed access.`

Does anyone know of a fix to this?

**Comment by AlexandreZaytsev** [comment]
>Edaks beta 10, icons only work if JQuery and uikit.min.js added to the head.

for example I have
icons do not work (not displayed) under Unix server, work under Windows local only Firefox

[https://github.com/uikit/uikit/issues/2229]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
		<link rel="stylesheet" href="css/uikit.min.css"></link>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script src="js/uikit.min.js"></script>
</head>
<body>
    <div class="uk-container">
        <h3>Icon Test</h3>
        <span uk-icon="icon: check" />
        <span uk-icon="icon: cart" />
        <span uk-icon="icon: calendar" />
    </div>

    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/uikit/dist/js/uikit.min.js"></script>

</body>
</html>
```

**Comment by AlexandreZaytsev** [comment]
beta 11  icons not displayed
![image](https://cloud.githubusercontent.com/assets/16114000/22940231/41f322b2-f2f2-11e6-9b94-c6af1b481424.png)
![image](https://cloud.githubusercontent.com/assets/16114000/22940295/722e0334-f2f2-11e6-8345-275dd7f04b6b.png)

**Comment by Edaks** [comment]
beta 11 - fixed

**Comment by AlexandreZaytsev** [comment]
yesterday evening 11 beta did not show the icons... now everything is OK...)))) 
apparently 'overload'

**Comment by janschoenherr** [comment]
The icon system has been refactored: https://getuikit.com/docs/icons

If the issue persists please reopen.

**Comment by lewatt23** [comment]
Hello  Icons still  not working on beta 40 been trying for about 30 mins  now
