### ISSUE TITLE
dropdowns and tablet pcs

### ISSUE THREAD

**Issue by SaphiLC** [uikit/uikit#2338]
Im using a surface pro 2, and the dropdowns become click by default even if you set them to hover, causing them to bug out. When you click them, depending on how fast or from where you access the drop down with your mouse, the dropdown insta-closes, its really annoying. I see you fixed the drag and drop issues on touch pcs, maybe it is related to this bug?

**Comment by philoest** [comment]
I tested this on a surface with a external mouse and here the hover worked the same as click ( which is wished ) but I couldn't see the bug you described. Does this happen on the docs page or do you have a codepen where I can see the problem?

**Comment by janschoenherr** [comment]
Resolved in Beta 12.
