### ISSUE TITLE
UIkit 3 Feature Request : CHIPS

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2339]
I think it would be useful the addition of Chips to show small blocks of information like contacts, categories, tags. This component could be outside the core to keep uikit light.

![chips](https://cloud.githubusercontent.com/assets/5558563/22565604/84a391a8-e967-11e6-9519-180859340406.png)

**Comment by visualcookie** [comment]
👍 is there any update on this? Last update on this issue was a long time ago.

**Comment by NoeFabellon** [comment]
Update please!

**Comment by NoeFabellon** [comment]
check the uikit badge

**Comment by zzseba78** [comment]
@NoeFabellon Not the same...

**Comment by darryloctoberdgtls** [comment]
Any update on this?

**Comment by zzseba78** [comment]
@darryloctoberdgtls Nope.

**Comment by darryloctoberdgtls** [comment]
> @darryloctoberdgtls Nope.

Hahaha! Fair answer!
If anyone is interested, I actually managed to achieve a basic chip extending UIkit's button component. For example:

`<button class="uk-button uk-button-chip">My chip text</button>`
Then I just styled it up...
