### ISSUE TITLE
Lightbox doc

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2340]
The lightbox probably already exist?

Source: https://github.com/uikit/uikit/blob/develop/src/js/components/lightbox.js
Test: https://getuikit.com/assets/uikit/tests/lightbox.html

Please add doc for this :)

**Comment by florianletsch** [comment]
It is currently in development. When it is really finished, the doc will be added ;)

**Comment by ruchern** [comment]
Duplicate of #2637

**Comment by Uranbold** [comment]
ooh Need Lightbox for badly ;)

**Comment by zzseba78** [comment]
@Uranbold It´s coming in next release!
