### ISSUE TITLE
UIkit 3: Dropdown not closing when item clicked.

### ISSUE THREAD

**Issue by samsidx** [uikit/uikit#2341]
In UIKit 2, there is class uk-dropdown-close to close an dropdown when item is clicked. But I don't see any such class in UIkit 3. So can please suggest any other way closing dropdown when an item clicked(selected)?

**Comment by Toccoan** [comment]
I would love to know this as well. I'm building a web app that is all contained on one page and getting the dropmenus to go away when a link is clicked would be great. Animated away would be even cooler.

**Comment by JurgenJocubeit** [comment]
Yes me too. I tried using blur and I can't seem to make it work.

**Comment by JurgenJocubeit** [comment]
I've just been playing around with this and have got it working by removing the `uk-open` classes from the element that triggers the dropdown and the dropdown element itself.

```js
// The link or button that triggers the dropdown:
$("#profile_dropdown_menu_button").removeClass("uk-open");
// the dropdown element (uk-dropdown):
$("#profile_menu_dropdown").removeClass("uk-open");
```

Hope this helps.

**Comment by janschoenherr** [comment]
You can use the Toggle component:

    <a href="#my-dropdown" uk-toggle>Close</a>

**Comment by Kulak** [comment]
you can apply uk-toggle at menu dropdown level.  The following code is react specific:

    <div className="uk-navbar-dropdown" ref="confMenu">

	let confMenu = ReactDOM.findDOMNode(this.refs.confMenu)
	confMenu.setAttribute('uk-toggle', 'true')
