### ISSUE TITLE
UIkit 3: Right Click fires Left Click

### ISSUE THREAD

**Issue by kadirpace** [uikit/uikit#2342]
_I have seen relevant ticket for tooltips (#2274) but I have this issue on all anchors that's why I decided to create a new issue._

Whenever I right click on anchor, left click gets triggered and page follows the url: 
https://www.screencast.com/t/N5t7hx8am6hL

I am running on Windows 10, this happens to me on Chrome and Edge browsers but not on Firefox. I don't have a touch screen.

p.s.: I have migrated the app from uikit2 to 3, and all the migration changes are applied.

**Comment by bdthemes** [comment]
Me too, told before at issue #2274
