### ISSUE TITLE
Tiled Grid

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#2343]
Are there any plans to extend the current grid features by adding a tiled grid feature?

**Comment by gingibash** [comment]
dynamic grid and filters?

**Comment by kiarashi** [comment]
More like this one here: 
https://i.stack.imgur.com/UFcPM.png

**Comment by luxlogica** [comment]
That can possibly already be accomplished with Flex.

I really would like to see something closer to - or perhaps even simpler/easier to use than - the [Tiles in Bulma](http://bulma.io/documentation/grid/tiles/), or ideally, a complete, responsive, flex-based dynamic auto-layout engine, like **[Shuffle.js](https://vestride.github.io/Shuffle/)**.

**Comment by saschadube** [comment]
@kiarashi You can already build the layout shown in the image with the Grid component

@luxlogica With our Grid component you can easily build the Bulma example. Use the Tile or Card component for the cell style.
