### ISSUE TITLE
UIkit/v3 Modal Javascript 

### ISSUE THREAD

**Issue by madhudskumar** [uikit/uikit#2344]
How do I close Modal in v3 ? 
v2 version 
```   
modal = new $.UIkit.modal.Modal('#modal');
modal.hide();
```
not woking.

in v3 ``` UIkit.modal("#x")``` returns Array with [Modal]

**Comment by m-ahmadi** [comment]
I do this:
```
var modal = UIkit.modal('#modal-id')[0]
modal.show()
modal.hide()
modal.isActive()
```

**Comment by masplay** [comment]
modal in V3 not woking !

http://codepen.io/anon/pen/BpVpQw

only works so 
```
var modal = UIkit.modal('#my-id')[0];
requestAnimationFrame(modal.show);
```

**Comment by m-ahmadi** [comment]
The div element that has a `uk-modal` class, misses the `uk-modal` attribute.
So the modal markup looks like this:
```
<div id="my-id" class="uk-modal" uk-modal="center: true; esc-close: true; bg-close: false;">
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title">Modal</h2>
    </div>
</div>
```

**Comment by masplay** [comment]
must add to the documentation!

**Comment by zzseba78** [comment]
It's already in the docs ....

> Add the uk-modal attribute to a <div> element to create the modal container and an overlay that blanks out the page. It is important to add an id to indicate the element for toggling. Use the following classes to define the modal's sections.

**Comment by masplay** [comment]
not a complete description.

not woking.
<div class="uk-modal" id="my-id" uk-modal>

it works
<div class="uk-modal" id="my-id" uk-modal="center: true; esc-close: true; bg-close: false;">

it's not in the documentation...

**Comment by zzseba78** [comment]
And if you try this way?
`$('a').on('click', function (e) {
  UIkit.modal('#my-id')[0].toggle();
  e.preventDefault();
});`

**Comment by masplay** [comment]
I did as advised earlier.
while I wait for the release.  :(

**Comment by janschoenherr** [comment]
This should be resolved in the latest Beta 11.

**Comment by vue-fan** [comment]
how about include ajax?
