### ISSUE TITLE
after beta 9 download icon error

### ISSUE THREAD

**Issue by bioduds** [uikit/uikit#2346]
looks like something went wrong with icons, I don't know. code is below

              <span class="uk-label">PHP 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>
              <span class="uk-label">Web Design 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>
              <span class="uk-label">C# 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>
              <span class="uk-label">Unix 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>
              <span class="uk-label">Model Architecture 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>
              <span class="uk-label">Scripting 
                <a href=""><span style="margin-right:-6px; color:black" uk-icon="icon: close"></span></a></span>

this code above worked on beta 8, works no more on beta 9

Attached a screen with error on display
![captura de pantalla de 2017-02-05 17-24-38](https://cloud.githubusercontent.com/assets/2072730/22629160/08ecdbce-ebc8-11e6-949f-c3febfe6d576.png)

**Comment by janschoenherr** [comment]
This should have been resolved with Beta 11. Please reopen if issue persists.

**Comment by bedewilson** [comment]
I am working on Beta 12 and getting the same issue

**Comment by bioduds** [comment]
Getting a feeling you're too eager to close issues. I'd suggest you work on
them. Plenty of things to do on UIkit3, I have a number of issues. I'm
sponsoring this great framework on Meteor with the package bioduds:uikit3
and building a major project with it.

To remind, bugs I've been experiencing: flips are not working, modals are
out of scope, navbar center is not centralized, scrollspy does not
highlight correct link when page is zoomed, button text link on dark
background shows black line instead of white, I'm having a few problems
getting paddings and margins correct, and I'm sure there's plenty of other
stuff to put working correct.

Keep up the good work. Thanks.

**Comment by bioduds** [comment]
Getting a feeling you're too eager to close issues. I'd suggest you work on them. Plenty of things to do on UIkit3, I have a number of issues. I'm sponsoring this great framework on Meteor with the package bioduds:uikit3 and building a major project with it. 

To remind, bugs I've been experiencing: flips are not working, modals are out of scope, navbar center is not centralized, scrollspy does not highlight correct link when page is zoomed, button text link on dark background shows black line instead of white, I'm having a few problems getting paddings and margins correct, and I'm sure there's plenty of other stuff to put working correct.

Keep up the good work. Thanks.

**Comment by janschoenherr** [comment]
Fixed in Beta 13. The icon system has changed.

https://getuikit.com/docs/icons

**Comment by bioduds** [comment]
That is awesome. Thanks a lot :)
