### ISSUE TITLE
[UIKit3] How to switch to a tab from inside or outside ui-tab?

### ISSUE THREAD

**Issue by JurgenJocubeit** [uikit/uikit#2347]
I tried using `data-uk-switcher-item` and it's not working from inside a tab's content. And I can't find any way to switch to a different tab from outside the tab container. Any clues?

**Comment by janschoenherr** [comment]
Did you try this: https://getuikit.com/docs/switcher#navigation-controls ?

If so please showcase what you have done on http://codepen.io

**Comment by janschoenherr** [comment]
I am closing this for now, if the issue persists please reopen.
