### ISSUE TITLE
Disappeared navbar with off-canvas when the "Upload" element on the page

### ISSUE THREAD

**Issue by petra-svk** [uikit/uikit#2349]
Hi.
I use Uikit3. I added on one page the element "Off-canvas" in navbar and "Upload" with drop effect. When i click on navbar, it disappeared. I don't understand why it happened. There wasn't any error in the console. Help?
[index.txt](https://github.com/uikit/uikit/files/754439/index.txt)

**Comment by janschoenherr** [comment]
Please showcase the issue with http://codepen.io

**Comment by janschoenherr** [comment]
I am closing this for now, if the issue persists please reopen.
