### ISSUE TITLE
ScrollSpy not working correctly when page is zoomed

### ISSUE THREAD

**Issue by bioduds** [uikit/uikit#2350]
ScrollSpy not working correctly when page is zoomed

side menu linked with scrollspy works nice now but if page is zoomed in or out it loses the reference

**Comment by janschoenherr** [comment]
Is this happening on http://getuikit.com?

**Comment by bioduds** [comment]
yes, you may test yourself. I'm on chrome. Take any page with the scrollspy, hold ctrl and zoom page to 80% for instance, you may perhaps see that the link marked on the side menu is not accurate. If you zoom back to 100% it will work properly. If you can't reproduce it, please tell me and I will send a screen record.

**Comment by bioduds** [comment]
sorry, didn't test beta 16 yet. I will now.

**Comment by bioduds** [comment]
On the page http://getuikit.com yes. Make a test, zoom to 80% the page and you may see that the link on side menu marked is incorrect. At least for me it is. I'm on Chrome latest update.

**Comment by florianletsch** [comment]
It seems this has been resolved? I was trying to confirm this on https://getuikit.com/assets/uikit/tests/scrollspy.html but it works for me (latest Chrome on MacOS, trying at 150% zoom)

**Comment by bioduds** [comment]
no, not solved for me. 90% zoom chrome doesn't work.

**Comment by Riddler84** [comment]
Have tested a lot of different zoom states from 50% to 300% on https://getuikit.com/assets/uikit/tests/scrollspy.html and everything looks good to me. (Latest Chrome)

**Comment by bioduds** [comment]
I can make a video and send if you want. Please tell me where to send.

**Comment by florianletsch** [comment]
Can you just upload to YouTube or similar and post the link here? Thanks.
