### ISSUE TITLE
ScrollSpy Nav don't highlight the correct section in Firefox ( this happens in the docs too )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2351]
ScrollSpy Nav don't highlight the correct section in **Firefox**, seems that it's a few pixels error in the calculation, because if you scroll the page a bit it corrects. This happens in the docs too. Works well in Chrome and Safari.
![captura de pantalla 2017-02-06 a las 09 59 33](https://cloud.githubusercontent.com/assets/5558563/22648026/56956d92-ec53-11e6-961c-b8728cfef997.png)

**Comment by janschoenherr** [comment]
Is this still happening in the latest Beta 11 release.

**Comment by mateusfccp** [comment]
Can confirm on beta16, Firefox 51.0.1 (64bits)

**Comment by aarongerig** [comment]
http://codepen.io/aarongerig/pen/XMjxMM

Open this pen in Chrome and Firefox and watch the console closely, while clicking on `Position modifiers`. In Firefox it's like .3 pixels off.

I recommend rounding the offset value with `parseInt()`.

**Comment by zzseba78** [comment]
Still happening in the latest Beta 18

**Comment by CopyJosh** [comment]
As described, error occurs in latest beta 18 on FireFox and iE11.
Works in Chrome, Safari, and Opera.

**Comment by zzseba78** [comment]
Thanks!

**Comment by mateusfccp** [comment]
I'm glad.
