### ISSUE TITLE
Icons in Accordion content

### ISSUE THREAD

**Issue by freitasbruno** [uikit/uikit#2353]
I tried adding a couple of icons inside a accordion component. On every click (expand/contract) these inner icons are duplicated.

**Comment by felixheidecke** [comment]
Same here. Worked around it using jQuery:

`$(document).ready(function() {
    setTimeout(function() {
        $('svg + svg').remove();
    }, 100);
});`

**Comment by freitasbruno** [comment]
Thanks @felixheidecke, 
I'll save that for later.

**Comment by janschoenherr** [comment]
This should be resolved with the latest Beta 11.
