### ISSUE TITLE
Open offcanvas from modal

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#2354]
Hello,
Could you add a feature to open an off-canvas from a modal-window (where the modal remains open)?
Example:
http://doppelbauer.name/uikit/
Thanks a lot!

**Comment by janschoenherr** [comment]
This should be possible with beta 26. Apply the `stack: true` option to the Offcanvas.

**Comment by doublex** [comment]
Thanks a lot.
If I apply `stack: true` to the off-canvas, the off-canvas does not work.
Example (beta 27):
http://doppelbauer.name/uikit-modal/

**Comment by doublex** [comment]
@janschoenherr 
To open an off-canvas from an overlay:
Would it help to remove the animation from the off-canvas (if the backdrop is the issue)?

**Comment by janschoenherr** [comment]
Here is a working codepen: https://codepen.io/aarongerig/pen/QORyRg

**Comment by doublex** [comment]
Excellent work!
I am deeply impressed.
This is not easy.

**Comment by janschoenherr** [comment]
Thank you, can we close the issue than?
