### ISSUE TITLE
Offcanvas bugs on mobile

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2356]
I have tested it on android 4.3*
Open https://getuikit.com/ on mobile:

1) After pen offcanvas - can't scroll to bottom options in menu (the last option which I can see is 'Switcher'
2) After open offcanvas, I can "move" the page to left / right side (try to swipe gestures on mobile screen after open offcanvas)
3) Open offcanvas and next change phone orientation - the site doesn't scale to media query properly

*) I tested also the bugs from list above on v2.27.2 and there this isn't exist :)

**Comment by zzseba78** [comment]
Yes, offcanvas it's buggy on mobile. And the animation performance it's poor.
Needs to be polished.

**Comment by janschoenherr** [comment]
I will close this issue for now, as the component has been refactored quite a bit.
