### ISSUE TITLE
UIKit render icon in VueJs app scope

### ISSUE THREAD

**Issue by blackcatpolice** [uikit/uikit#2357]
There is a issue when uikit render icon, it will append everytime dom element change, but when I use vuejs, the dom elements always change if I "new Vue()", so will it judgment an icon element chilren have a svg element, if true return, don't need append again. 

And this my code:

#line4236 
` if (this$1.$el.children('svg').length >= 1) {
                                return;
                            }`

**Comment by Nayar** [comment]
Having it too in beta 12

![screen shot 2017-02-24 at 9 25 28 am](https://cloud.githubusercontent.com/assets/454815/23291653/54d1a786-fa73-11e6-90ad-14282039ff83.png)

**Comment by janschoenherr** [comment]
Fixed in Beta 13. 

https://getuikit.com/docs/icons

**Comment by Nayar** [comment]
seems to have come back in beta 16 :(

**Comment by janschoenherr** [comment]
Please provide a reproduction link. You could start with this template: http://codepen.io/anon/pen/XMpryM

**Comment by Nayar** [comment]
You can see on my still in dev website here: https://logs.nayarweb.com/shop

**Comment by yiyunzhi** [comment]
come back in beta 20 again :(, unless uikit-icons.min.js defer loaded

**Comment by gtapps** [comment]
+1

**Comment by giordanovi** [comment]
+1

**Comment by illjah42** [comment]
+1
https://codepen.io/illjah42/pen/RQyLob

**Comment by janschoenherr** [comment]
I believe this has since been resolved.
