### ISSUE TITLE
UIkit with angular2 and webpack

### ISSUE THREAD

**Issue by ChaiMinChun** [uikit/uikit#2358]
Hey guys, i encountered a problem while bundle uikit with webpack. The compilation went well until i use `<a href="" class="uk-icon-button" uk-icon="icon: twitter"></a>` or anything invoke the uikit.util function or whatever it is belong to uikit object.The error message shown to me was 
![capture](https://cloud.githubusercontent.com/assets/10117740/22682436/9af63336-ed4d-11e6-9640-5a7446cff371.PNG)

![capture1](https://cloud.githubusercontent.com/assets/10117740/22682481/c9bfce3e-ed4d-11e6-851c-88b0a2368499.PNG)

 my project is built on top of https://github.com/preboot/angular2-webpack , the webpack configuration is slightly different from the original one. I have added 
`config.externals = {
    "uikit":{
      commonjs:"UIkit",
      amd: "UIkit",
      root: "UIkit"
    }
  }`
in vendor.ts i have added 
`import 'uikit/dist/css/uikit.css';
import 'uikit/dist/js/uikit.js';`

anyone have idea what it is going wrong?Any help is appreciated

**Comment by madhudskumar** [comment]
I did This
```
declare var UIkit:any;
export const uikit = UIkit;
```

works fine

**Comment by ChaiMinChun** [comment]
@madhudskumar  May i know where did you declare the UIkit variable? i declared it in vendor.ts but still get the same result.

**Comment by madhudskumar** [comment]
you can declare it anywhere you want,  Its a typescript feature so it does not confuse with a variable, I use in a shared config file and export

**Comment by ChaiMinChun** [comment]
@madhudskumar Could you provide me a working example? I am very new to this.

**Comment by mjbates7** [comment]
How would you go about declaring this variable outside of/not using  typescript?

**Comment by ChaiMinChun** [comment]
@mjbates7 I thought it has to declare in typescript file?

**Comment by RapidTransit** [comment]
Temporary work around:
```
externals: {
            "uikit": "UIkit"
        },
```
then add a script tag in your head for uikit.

**Comment by madhudskumar** [comment]
can refer to this great article [https://www.thepolyglotdeveloper.com/2016/01/include-external-javascript-libraries-in-an-angular-2-typescript-project/](Angular 2 + external js)

**Comment by zonkhonk** [comment]
uikit is depends on jquery. maybe you forgot to inclut it?

**Comment by ChaiMinChun** [comment]
@zonkhonk  nope. I included it using cdn

**Comment by x4vl** [comment]
It's working for me on an  angular-cli based project. It was important to me make my own theme and this is how I did it:

First install / add dependency to jquery and uikit:

`npm install jquery --save`
`npm install uikit --save`

Then edit `.angular-cli.json` file and add the scripts:
```json
...
"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/uikit/dist/js/uikit.min.js",
        "../node_modules/uikit/dist/js/uikit-icons.min.js"
      ],
...
```

Now you can use UIKit wherever

```typescript
import {Component} from "@angular/core";
declare var UIkit: any;

@Component({
  template: `<div (click)="showAlert()">alert</div>`
})
export class OwnerComponent {
  showAlert(): void {
    UIkit.modal.alert('UIkit alert!');
  }
}
``` 

*offtopic: in the next step I explain how to configure the project to use sass / scss to make you own uikit theme*

Rename the `styles.css` to `styles.scss` (**don't forget to rename the file itself!**)

```json
...
"styles": [
        "styles.scss"
      ],
...
```

Then you can edit `style.scss` to compile UIKit and make your own theme

```sass
// 1. Your custom variables and variable overwrites.
$global-link-color: #DA7D02;

// 2. Import default variables and available mixins.
@import "../node_modules/uikit/src/scss/variables-theme.scss";
@import "../node_modules/uikit/src/scss/mixins-theme.scss";

// 3. Your custom mixin overwrites.
@mixin hook-card() { color: #000; }

// 4. Import UIkit.
@import "../node_modules/uikit/src/scss/uikit-theme.scss";
```

**Comment by bukialabi** [comment]
The answer above was a really good start. The only thing I had to change to get it to work for me was changing ` declare var UIkit: any; ` to ` import UIkit from 'uikit' `
within my component. 

I was kinda following this guy: https://stackoverflow.com/questions/42422885/cant-use-uikit-with-webpack
