### ISSUE TITLE
uikit/v3 notification

### ISSUE THREAD

**Issue by madhudskumar** [uikit/uikit#2360]
![image](https://cloud.githubusercontent.com/assets/8987882/22694492/7cb256dc-ed6d-11e6-895e-8bb65e6a3021.png)

even though I do this it always attaches to ```top-center```

![image](https://cloud.githubusercontent.com/assets/8987882/22694529/a2cd09b6-ed6d-11e6-892e-2ee841acd917.png)

solution? using angular 2

**Comment by masplay** [comment]
```
  UIkit.notification({
    message: 'my-message!',
    status: 'primary',
    pos: 'bottom-center',
    timeout: 5000
});
```

**Comment by madhudskumar** [comment]
worked!
