### ISSUE TITLE
Uikit 3 tooltip text flicker.

### ISSUE THREAD

**Issue by Dopings** [uikit/uikit#2361]
macOS chrome and opera.
![tooltip-bug](https://cloud.githubusercontent.com/assets/6884695/22694695/3adda23e-ed59-11e6-9b79-6dd33a812e3f.gif)
With this code problem is solved, but I think it not the best decision.
`.uk-tooltip {
  -webkit-font-smoothing: antialiased !important;
}`

**Comment by janschoenherr** [comment]
Fixed in Beta 12.
