### ISSUE TITLE
[UIkit 3, beta 9] Problem when changing items in switcher

### ISSUE THREAD

**Issue by carlos-duran** [uikit/uikit#2362]
Each time I change the item in the switcher, the scroll bar goes up

Here is my test: [http://codepen.io/carlos-duran/pen/QdBPPe](http://codepen.io/carlos-duran/pen/QdBPPe)

I think it happens because of its height but it does not happen when you switch from right to left.

Thank you.

**Comment by janschoenherr** [comment]
Is this still happening with Beta 11?

**Comment by carlos-duran** [comment]
I've updated my pen to:
- https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.11/css/uikit.min.css
- https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.11/js/uikit.min.js

And the problem remains.
