### ISSUE TITLE
On "show" not firing for modal until modal is clicked

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#2366]
on "show" for the modal isn't firing when the modal is shown, however is fired when the modal is clicked.

**Comment by janschoenherr** [comment]
Please add an example to http://codepen.io/ showcasing the problem.

**Comment by TomS-** [comment]
http://codepen.io/anon/pen/GrLvMe bug seems to be relating to center: true, click the input field to activate show.

**Comment by janschoenherr** [comment]
This has been fixed in the development branch. Thanks.
