### ISSUE TITLE
[Error] mistake with uglify

### ISSUE THREAD

**Issue by mohamedsabil83** [uikit/uikit#2368]
I got error with following message when use `npm run production`  :

```
/js/app.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/uikit/src/js/mixin/class.js:3,0][/js/app.js:11094,8]
```

**Comment by janschoenherr** [comment]
I don't think there is a script by that name?

**Comment by mohamedsabil83** [comment]
I don't sure but It working fine after re-installing uikit and run `npm run production` again
