### ISSUE TITLE
uikit 3 beta toggle fires on click when in hover mode

### ISSUE THREAD

**Issue by speakdigital** [uikit/uikit#2370]
Trying to create an overlay over a div that appears on hover but disappears on exit.
When the overlay is clicked on it opens a modal
```
<div class="uk-card uk-card-default uk-cover-container" uk-toggle="mode: hover; target: #overlay-343"> 				
<div>BOX CONTENTS HERE</div>
<div id="overlay-343" class="uk-overlay uk-position-cover uk-overlay-primary" hidden 
uk-toggle="target: #modal-'+offer.id+'">
<span uk-icon="icon: plus-circle; ratio: 3" class="uk-position-center"></span>
</div>
```
The issue is that when you click on the overlay the toggle that is 'underneath' that is on mode hover is still activated. This means when you then move the mouse out, the overlay is still shown.

Sorry for the bad explanation!

**Comment by janschoenherr** [comment]
Has this been resolved?
