### ISSUE TITLE
Custom theme css' images path (beta-9)

### ISSUE THREAD

**Issue by franctic-aerobic** [uikit/uikit#2371]
Using the guide in the documentation for included build process and less, I created a /custom/ folder, a my-theme.less file in it with recommended content.

After running "npm run compile" i got the newly created uikit.my-theme.css in the dist folder. But in this css file the images path is ../dist/images and not working. In uikit's default css files the path is ../images and working.

Running beta 9. And a fresh git clone of uikit just to locate this issue.

Sidenote: Could there also be a minifying process for the custom theme? Same as used for uikit-core and uikit-theme.

**Comment by mjbates7** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by bassmanpaul** [comment]
+1

My current workaround is to override the offending variable from `src/less/components/icon.less` in my custom theme `custom/my-theme.less` file:

```less
// Remove 'dist' folder
@internal-icon-image : '../../../images/icons.svg';
```

**Comment by janschoenherr** [comment]
This should be resolved in Beta 11. Please reopen if the issue persists.
