### ISSUE TITLE
uk-dark class does not invert component colors 

### ISSUE THREAD

**Issue by shenst1** [uikit/uikit#2373]
When a user adds class ```uk-dark``` to a component that is automagically set to inverted colors (Section, Card, Overlay and Off-canvas), the component should go back to the ```uk-dark``` settings. Instead, the component stays inverted and does not go back to ```uk-dark``` settings.

**Comment by saschadube** [comment]
Sorry, we don't have a CSS solution for this. If inverted is apply once, you can't revert it.
