### ISSUE TITLE
How work with 3 ver?

### ISSUE THREAD

**Issue by freenetwork** [uikit/uikit#2379]
How use component? As Datepicker and other

**Comment by zzseba78** [comment]
Datepicker and other components from uikit 2 are missing.

> Our focus for this release has been to create a stable core and provide extensive documentation right from the start. Next on our list are the Slideshow, Slider, Slideset, Parallax, Nestable, Lightbox, Dynamic Grid, HTML editor, Date- and Timepicker components.

http://yootheme.com/blog/2017/01/09/uikit-3-beta-released

**Comment by florianletsch** [comment]
Thanks zzseba78, this is correct.

**Comment by sarimarton** [comment]
It has been 2 years, since there's no datepicker and autocomplete, 2 essential parts of a UI lib. Is this project abandoned? It should be in a beta!
