### ISSUE TITLE
iOS 10 Safari doesn't display icons. UIkit 3 beta 9

### ISSUE THREAD

**Issue by sumanion** [uikit/uikit#2381]
I used Safari Mobile Web Inspector to see why icons are not displayed and it seems that for some reason SVG elements аrе not added to the `uk-icon` elements, it just adds the `.uk-icon` class and stops. In other browsers all icons are displayed without any problems.

To show the problem, I used as example the UIKit website as it is built using beta-9.

Here is the problem (Inline SVG is not added):
<img src="https://cloud.githubusercontent.com/assets/5844169/22793481/a17acc24-eef8-11e6-8640-1058fdacf411.jpg" width="700">

How it looks:
<img src="https://cloud.githubusercontent.com/assets/5844169/22793123/995f01dc-eef7-11e6-8757-a6359a9caea4.jpg" width="300">

I hope this will be fixed soon :)

**Comment by Toccoan** [comment]
This happens to me too, but only when I'm in 'Private' mode. They are showing up for me when I'm in the standard viewing mode in IOS10 Safari.

**Comment by saschadube** [comment]
@Toccoan This is a Safari bug http://stackoverflow.com/questions/18860098/on-a-browser-sessionstorage-in-safaris-private-browsing-does-not-work-the-same

**Comment by janschoenherr** [comment]
Fixed with 824c7408fff0c7c4f5c36acaa77fbe0c4a8f77e9
