### ISSUE TITLE
Help: when performing bulk action i just want one notify

### ISSUE THREAD

**Issue by atulgirishkumar** [uikit/uikit#2385]
I have an action which triggers "Notify.alert".
When i perform that action multiple times it shows me that many notifications, but my issue is that i just want one notification when my action is performed more than once.
Can you please help me @janschoenherr 

Here an example code:
```
function applyBulkAction(){
     perfomeAction();
}
function perfomeAction(){
      Notify.alert( 'Operation failed,  please try later', { status: 'danger'});
}
```

**Comment by madhudskumar** [comment]
you can try flag method in function
