### ISSUE TITLE
v3 => Name error :  parse error

### ISSUE THREAD

**Issue by madhudskumar** [uikit/uikit#2386]
when I use the name 'menu.svg' I am getting this error

![image](https://cloud.githubusercontent.com/assets/8987882/22828568/0522e830-efc4-11e6-8b35-ccc5b7e62a5b.png)

![image](https://cloud.githubusercontent.com/assets/8987882/22828563/f58f5340-efc3-11e6-96bf-b4bbf2cbc2d9.png)

but if I use any other name it works fine.

Any suggestions?

**Comment by janschoenherr** [comment]
Is this still happening with Beta 11?

**Comment by janschoenherr** [comment]
Fixed in Beta 13. 

https://getuikit.com/docs/icons
