### ISSUE TITLE
Loading UIkit before </body>

### ISSUE THREAD

**Issue by dbonner1987** [uikit/uikit#2389]
Is there anyway in which we can look at loading UIkit in at the bottom of the document. Currently, it requires to be loaded within the header of the document.

**Comment by janschoenherr** [comment]
Could you be more precise as to what is not working? UIkit should work fine if included right before the closing _</body>_ tag. You could also use the _defer_ attribute. 

https://getuikit.com/docs/javascript

If this is still an issue, please reopen.

**Comment by dbonner1987** [comment]
The Icons component fails to load up the icons when the scripts are appended to the body/below the actual content. I've not had a chance to debug the issue entirely and have continued development with the script tags in the head.

I noticed your docs site places the scripts in the head. I'll clone it down and move the location of the tags.

**Comment by dbonner1987** [comment]
So it would appear that if you load uikit in at the bottom of the document (before the closing body tag), the uk-icon attributes start to initialise before `getSvg` is called. 

So no icons are available in `this._svg` within the `write` method of the Svg component.

**Comment by uikid** [comment]
#2792
