### ISSUE TITLE
Question - How to integrate with nuxtjs

### ISSUE THREAD

**Issue by Cengkaruk** [uikit/uikit#2391]
Hi. I'm new using vuejs and uikit. I'm already reading the code of documentation site, but need more solution for Server Rendered. Sorry for this oot question, any ideas/example?

**Comment by WolfDan** [comment]
Just create you'r components based on uikit css, like a normal app, nuxtjs will generate it when compile to make it server side, just follow the folder structure and convenions of nuxtjs and you will be ok

**Comment by Cengkaruk** [comment]
Solved for now. Server side render using nuxtjs something like [this](https://github.com/nuxt/nuxt.js/issues/178) not working properly, will facing [this](https://github.com/uikit/uikit/issues/2345) issue. So we can't use UIKit via webpack, and must load it client side.
