### ISSUE TITLE
Angular ng-repeat uk-switcher issue!

### ISSUE THREAD

**Issue by andykenobi** [uikit/uikit#2397]
Hello there, i'm trying to use angularjs with uikit.
I have made this:

```
    <div uk-switcher="connect: #test;">
        <a href="" ng-repeat="item in [1, 2, 3, 4, 5]">{{item}}</a>
    </div>
    <div class="uk-switcher test">
        <div ng-repeat="item in [1, 2, 3, 4, 5]">{{item}}</div>
    </div>
```

When i run, all switchers are open!
I have used this to fix:
```
        $(document).ready(function() {
            $(".uk-switcher").children().removeClass("uk-active");
        })
```

But i want to know if have another way to make a switcher with angularjs ng-repeat .

**Comment by andykenobi** [comment]
Can i start all the  uk-switcher without class "uk-active"?
Becouse if i use some ajax (with jquery or angularjs) and i change the html, the uk-switcher will have the same bug.

**Comment by janschoenherr** [comment]
Could you please add an example on [codepen](http://codepen.io/)

**Comment by janschoenherr** [comment]
Please try the latest Beta.

**Comment by andykenobi** [comment]
Okay, i will.

**Comment by janschoenherr** [comment]
Does this issue persist?
