### ISSUE TITLE
New global variable for images folder

### ISSUE THREAD

**Issue by marcomontalbano** [uikit/uikit#2398]
At the moment if you want to change the images folder `../../../dist/images` you have to override a lot of variables.

Adding a new global variable (e.g. `@global-image-folder: "../../../dist/images";`) could be a better solution.

What do you think?

**Comment by mjbates7** [comment]
This would be very useful

**Comment by masplay** [comment]
Good idea!
I use gulp-less on windows 10 and I have 
not worked `"../../images/components/close.svg"` and
it works `"./../images/components/close.svg"`
 is necessary in your theme to reassign all

**Comment by janschoenherr** [comment]
The Icon system has been updated with Beta 13. Please check https://getuikit.com/docs/icons.
