### ISSUE TITLE
On Meteor Framework, Modal seems somehow out of scope

### ISSUE THREAD

**Issue by bioduds** [uikit/uikit#2400]
Can't call an event inside a modal using Meteor Framework

**Comment by alexandesigner** [comment]
> What event exactly are you referring to within the modal?

**Comment by bioduds** [comment]
a template button click.

**Comment by janschoenherr** [comment]
Please try the latest Beta version.

**Comment by bioduds** [comment]
Doing it right now and publishing on Atmosphere, thanks :)

**Comment by janschoenherr** [comment]
Is this issue resolved?
