### ISSUE TITLE
WOW, lots of errors on beta-10 guys

### ISSUE THREAD

**Issue by bioduds** [uikit/uikit#2401]
still scrollspy won't work properly with zoomed page
close button on modal appears on the left top
modal seems out of project scope since it wont broadcast events
padding on input text changed
downgrading to beta-9, hope I've helped, I'm sure there is more, just look around

**Comment by janschoenherr** [comment]
What browser are you using?

**Comment by mjbates7** [comment]
Just to add, the drop "hover" doesn't work on this page/codepen: https://getuikit.com/docs/drop. Tested using `Chrome 56.0.2924.87 (Official Build) (64-bit)`

**Comment by janschoenherr** [comment]
@mjbates7 in the first [#usage](https://getuikit.com/docs/drop#usage) example? Seems to work fine for me in Chrome. What OS are you running?

**Comment by bioduds** [comment]
im on chrome

**Comment by bioduds** [comment]
running ubuntu 16.04 LTS 64 bits

**Comment by bioduds** [comment]
Chrome Versión 50.0.2661.102 (64-bit)

**Comment by mjbates7** [comment]
@janschoenherr Tested in Edge too. Running Windows 10 x64

**Comment by kadirpace** [comment]
I think Hover problem is a global problem. I had the same problem on uikit 2 and 3 now, using windows 10 chrome and edge browsers have this issues. 

It only works if I disable touch events on Chrome https://www.screencast.com/t/yjsMM8R8

**Comment by bioduds** [comment]
@mjbates7 in the first #usage example? Seems to work fine for me in Chrome. What OS are you running? not for me, zoom in and out and spy gets confused

**Comment by kadirpace** [comment]
my problem with hover is solved with beta-12 update.

**Comment by janschoenherr** [comment]
The hover issue is resolved. Please open new, separate issues for remaining issues. Thanks.
