### ISSUE TITLE
programatically show/hide accordions

### ISSUE THREAD

**Issue by agreif** [uikit/uikit#2404]
Hi,
I am trying to show/hide accordions but have no luck.
I read the docs at 'https://getuikit.com/docs/javascript#programmatic-use' but no success.

    <ul uk-accordion="multiple: true">
      <li #stammdaten .uk-open>

UIkit.accordion("#stammdaten")[0].hide()
does  not work as expected. It says : UIkit.accordion(...).hide is not a function
The same happens with toggle()

Any ideas?
thanks,
ALex.

**Comment by janschoenherr** [comment]
Currently the Accordion only supports a function _show_. This is really more a _toggle_. We'll rename it.

You'd have to call `UIkit.accordion("#my-accordion")[0].show()` and set the id on the accordion itself. You'll also have to set the classes _.uk-accordion-title_ and _.uk-accordion-content_.

**Comment by nicolasmendoza** [comment]
@janschoenher I know this is an old "issue", but let me ask you if do you know how can I do the same in the UIkit v2.27.5?
I tested this in the console and also other solutions like .toggle(), but it's not working. I read the documentation and I have several hours looking for a solution.

Thanks for considering my request.

**Comment by janschoenherr** [comment]
From looking at the source, there seems to be a `toggleItem` function. I am not sure what the `wrapper` parameter is though.

https://github.com/uikit/uikit/blob/v2/master/src/js/components/accordion.js#L70

**Comment by jlove73071** [comment]
After the dom is updated, you can always .click() the title. That toggles it at least.
