### ISSUE TITLE
Toggle only binding to immediately adjacent object

### ISSUE THREAD

**Issue by terrelltechsup** [uikit/uikit#2405]
I have been testing with the latest release of UIKIT on Wordpress and the toggle component.  It appears that regardless of whether you attempt to target an ID or a class, the button will only bind to it's target if it immediately precedes it, else the toggle attributes apply to the button itself.

**Comment by zzseba78** [comment]
It works fine for me, can  you create a codepen to see the code?

**Comment by terrelltechsup** [comment]
Hello Sebastian,

You can take a look at an implementation here:
http://template2.theinvestmentagents.com/listings/

The map button should hide the DIV containing the map, but itself is
assigned the hidden attribute instead.  If you move the button using
firebug or some other browser console editor to immediately preceding the
div with the target ID(the button will be in between the two columns) it
will function as expected.  Note I do have another button coded the exact
same way(the filter button) that toggles an off-canvas modal and that works
fine.

Thank you,

Josh Terrell

**Comment by terrelltechsup** [comment]
It looks like there are two errors on the console for this page:

Uncaught TypeError: Cannot read property 'css' of null
    at HeightMatch.write (uikit.min.js?ver=1.3.5:3)
    at uikit.min.js?ver=1.3.5:3
    at y (uikit.min.js?ver=1.3.5:3)
    at b (uikit.min.js?ver=1.3.5:3)
write @ uikit.min.js?ver=1.3.5:3
(anonymous) @ uikit.min.js?ver=1.3.5:3
y @ uikit.min.js?ver=1.3.5:3
b @ uikit.min.js?ver=1.3.5:3
uikit.min.js?ver=1.3.5:3 Uncaught TypeError: Cannot read property 'css' of null
    at HeightMatch.write (uikit.min.js?ver=1.3.5:3)
    at uikit.min.js?ver=1.3.5:3
    at y (uikit.min.js?ver=1.3.5:3)
    at b (uikit.min.js?ver=1.3.5:3)
write @ uikit.min.js?ver=1.3.5:3
(anonymous) @ uikit.min.js?ver=1.3.5:3
y @ uikit.min.js?ver=1.3.5:3
b @ uikit.min.js?ver=1.3.5:3

**Comment by terrelltechsup** [comment]
This appears to happen on Chrome and Edge but not Firefox.

**Comment by terrelltechsup** [comment]
So I rewrote the logic from scratch.  It looks like it was either an out of place Div or a misplaced semicolon in the toggle attribute parameters.  It is functioning as expected now.  Thank you for your support.

**Comment by terrelltechsup** [comment]
I got ahead of myself.  It is still only working in firefox.  In Chrome and Edge, the button is toggled instead of the target DIV.

**Comment by janschoenherr** [comment]
@terrelltechsup Please supply a codepen.io example of your issue. Thanks.

**Comment by terrelltechsup** [comment]
It has to do with the sticky placeholder DIV:

`<div class="uk-sticky-placeholder" style="height: 1200px; margin: 0px;"></div>`

http://codepen.io/terrelltechsup/pen/rjEPYG

View the codepen on chrome versus firefox and you should see what I am talking about.  When you click the button labeled MAP.

**Comment by janschoenherr** [comment]
Could you please streamline the codepen, I am seeing lots of errors in the dev tools.

**Comment by janschoenherr** [comment]
Closing this for now, as it seems to be abandoned.
