### ISSUE TITLE
UIkit 3 - The grid and many component doesn´t work in Opera.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2406]
Seems that many component doesn´t work in Opera Browser.
It´s about 1% of the Browser statics, not relevant, but anyone know why is that?

**Comment by nblackburn** [comment]
What version as Opera is using webkit these days.

**Comment by saschadube** [comment]
Everything works fine for me in Opera 43. Which version are you using?

**Comment by zzseba78** [comment]
Mmm, this is strange, using latest version, but uninstall and re install and same problem. The functionality looks  all broken. Check another websites to check, they work fine. I check if javascript is enabled too, and not in turbo mode. I don´t get it...

![captura de pantalla 2017-02-16 a las 14 08 18](https://cloud.githubusercontent.com/assets/5558563/23032109/2cecd668-f452-11e6-947d-51f908a87934.png)
![captura de pantalla 2017-02-16 a las 14 12 04](https://cloud.githubusercontent.com/assets/5558563/23032114/326fe274-f452-11e6-86ab-6296d849551e.png)
![captura de pantalla 2017-02-16 a las 14 08 44](https://cloud.githubusercontent.com/assets/5558563/23032130/3c13c8ea-f452-11e6-95ea-2360e9d2fe54.png)

**Comment by janschoenherr** [comment]
Do you see any Javascript issues? Is http://getuikit.com looking good?

**Comment by zzseba78** [comment]
No, it doesn't look good. It shows some js errors, in uikit site, and in another site that i create with uikit 3, same errors, same files.

![captura de pantalla 2017-02-21 a las 20 24 45](https://cloud.githubusercontent.com/assets/5558563/23189926/0f8f4d32-f874-11e6-9c1b-90bf66f42988.png)
![captura de pantalla 2017-02-21 a las 20 27 17](https://cloud.githubusercontent.com/assets/5558563/23189955/31797aee-f874-11e6-9b28-8e0825ea0bf2.png)

**Comment by janschoenherr** [comment]
Thanks, will be fixed asap.

**Comment by janschoenherr** [comment]
Fixed in Beta 13. Thanks.
