### ISSUE TITLE
report some bugs in chrome

### ISSUE THREAD

**Issue by p30help** [uikit/uikit#2407]
Hi 
I use altair theme that use UIkit as core of structure,
I have some problem that is related to UIKit. also i use Rtl mode.
1- when my page has scroll and open a modal the page jump to left and back (that is not pleasant for users) also if in modal exist checkbox when checked or unchecked modal jump to left and back
2- my monitor is HD and resolution is 1920 x 1080 px but drag and drop in not work in pages (for example for nestable and dashboard cards)

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
