### ISSUE TITLE
uk-spinner with Angular ng-repeat duplicates (Temp Fix Found)

### ISSUE THREAD

**Issue by lvandyk** [uikit/uikit#2408]
When I add the following **INSIDE** an **ng-repeat**:

`<div uk-spinner ng-show="object.isDeleting"></div>` 

then the spinner is duplicated. 

For now I am using the resulting HTML (without uk-spinner property) to fix the issue:

````
<div ng-show="object.isDeleting" class="uk-spinner uk-icon">
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" ratio="1">
        <circle fill="none" stroke="#000" cx="15" cy="15" r="14"></circle>
    </svg>
</div>
````

**Comment by janschoenherr** [comment]
Fixed with beta 13. Thanks.
