### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource in Beta 11

### ISSUE THREAD

**Issue by jimibi** [uikit/uikit#2410]
Hi,

I use CDN to load uikit.js, but now I have this message with Beta 11: "**No 'Access-Control-Allow-Origin' header is present on the requested resource**", I don't have this message with Beta 10.

Browser: Chrome56
OS: Windows 7

**Comment by ConsoleTVs** [comment]
Seems 12 have the same problem. You can either use local files or use another icon set like ionic icons. Cheers!

**Comment by jimibi** [comment]
Thank's it works like a charm, I even found the icons. But I would have liked to know why the CDN was working correctly in the previous version?

**Comment by ConsoleTVs** [comment]
I'm not an admin of UIkit, i stopped by the same problem and just making you know i diceded to go with another icon set. Cheers!
