### ISSUE TITLE
Modal and Tooltip broken in the scope mode

### ISSUE THREAD

**Issue by mvanvu** [uikit/uikit#2412]
Thanks so much, it works great.
Also I have some problems. 

1. For scope mode, modal and tooltip will be a child of the body tag which maybe not a scope so they were broken. Can we change the uk-scope class by another prefix like "xyz-scope" ?

2. uk-table-small seems not work.

3. When I use jQuery to clone a element which has a SVG icon, clone work fine but the SVG was duplicated.

**Comment by janschoenherr** [comment]
Thanks for your input.

1. Use the UIkit.container to set a global container for modals and sortables. We'll update the docs accordingly.
2. https://getuikit.com/docs/table#small-modifier Is it working for you here?
3. First remove the element from the Dom, clone it, insert the old and the new icons.

**Comment by mvanvu** [comment]
Thanks @janschoenherr. Also, how about "container" for tooltip? It doesn't work for me.

**Comment by janschoenherr** [comment]
I believe the tooltip is already appended to the container?

**Comment by mvanvu** [comment]
It doesn't work for me (Beta 12)

Attr: title="tooltip" uk-tooltip="container: #abcXyz"

**Comment by janschoenherr** [comment]
Thanks for reporting!

**Comment by Yiannistaos** [comment]
@janschoenherr thanks for your reply about using the UIkit.container to set a global container for modals and sortables. 

But can you give me us an example how to use the UIkit.container if we are working with scope mode?

For example this does not working for me:

```
<div class="uk-scope">
   <div class="uk-container uk-padding-remove uk-margin-medium-top uk-margin-medium-bottom">
      <button type="button" class="uk-button uk-button-default" title="Submit form text goes here..." uk-tooltip>Submit</button>
   </div>
</div>

```
