### ISSUE TITLE
npm not watching less

### ISSUE THREAD

**Issue by gingibash** [uikit/uikit#2415]
npm run watch only watches src/js for changes. I saw this issue on gitter. Mine is not watching less also.

mac osx 10.11
node 7.5.0
npm 4.1.2.

**Comment by wanze** [comment]
I still have this issue, being on the latest develop branch:

`npm run watch` does initially compile the my less file in the custom folder, and it says at the very end:

`[compile-less] [nodemon] clean exit - waiting for changes before restart`

.. but if I change my less file, nothing happens. Can anyone confirm that it works or what am I missing? Thanks! :)

Node: 6.10.0
npm: 4.3.0
Mac OSX 10.123
