### ISSUE TITLE
modal…toggle() within jQuery event method scope not working (properly)

### ISSUE THREAD

**Issue by felixheidecke** [uikit/uikit#2416]
Trying to open an modal within the scope of a (lets say 'click') method does not open the modal (all the way).

```
$('#button').on('click', function() {
    UIkit.modal('#modal')[0].toggle();
});
```

Clicking the button will in fact apply a `style="display:block;"` on the modal in question, but it does not apply necessary classes like `uk-open` and such. This can be witnessed here: http://codepen.io/fh_me/pen/aprNLR

**Comment by bioduds** [comment]
Having trouble with modals too on Meteor. you may try instead of toggle, show but yet mine interferes with my router routines.

**Comment by masplay** [comment]
Add settings
`uk-modal="center: false; esc-close: true; bg-close: false;"`


`<div id="m1" uk-modal="center: false; esc-close: true; bg-close: false;">`

**Comment by janschoenherr** [comment]
For now, you can simply defaultPrevent the click event.

```
$('#button').on('click', function(e) {
    e.preventDefault();
    UIkit.modal('#modal')[0].toggle();
});
```

What is happening is: you are opening the modal within the click event, after that the event bubbles to the click event listener on the document and immediately closes the modal again.

**Comment by felixheidecke** [comment]
:+1:

**Comment by dbonner1987** [comment]
This issue appears to still be in play in the most recent commit of the develop branch. Modal loads up alright with `bg-close` set to false. When set to true, the modal fails to open as `.uk-open` is not being assigned to it.

**Comment by bioduds** [comment]
Yep. Having many other problems still with beta versions. I am notifying all I get. 

Thanks for sharing :)
