### ISSUE TITLE
UIKit 3: Modal and switcher (uk-toggle) conflict

### ISSUE THREAD

**Issue by bribar** [uikit/uikit#2418]
I imagine this occurs with other components that use uk-toggle. I am using UIKit with Magento < 2. Magento loads other js libraries such as jquery, prototype and scriptalicious. The issue is the modal will not toggle or remove the uk-modal-page class from the html tag. Some DOM changes are happening when trying to use the modal, but looks like the appropriate classes don't get set correctly.

I believe there is a conflict with prototypes hide and show methods and UIKits, I received a error pointing to prototypes script where the hide and show method reside when trying to toggle the modal. Prototype overriding UIKits methods?

I'm using Magento block layout class to get the header and footer which contains the libraries and everything else, then I load UIKit. If i remove the header, UIKit modal and switcher works fine, so I know I have configured them correctly.

With UIKits recent release, I haven't found much using it with Magento.

**Comment by bribar** [comment]
`Uncaught TypeError: Cannot set property 'display' of undefined
    at show (prototype.js:1937)
    at HTMLLIElement._methodized [as show] (prototype.js:438)
    at Object.trigger (jquery.js:4)
    at HTMLLIElement.<anonymous> (jquery.js:4)
    at Function.each (jquery.js:2)
    at n.fn.init.each (jquery.js:2)
    at n.fn.init.trigger (jquery.js:4)
    at Tab._toggleElement (uikit.min.js:4)
    at Tab._toggleElement (uikit.min.js:3)
    at HTMLLIElement.<anonymous> (uikit.min.js:4)`

**Comment by janschoenherr** [comment]
Could check if 60bf05f5d2ea8f1c228e63074ff3ab6d173bfd01 fixes your modal issue?

**Comment by bribar** [comment]
No it doesn't from what I can tell. The modal will open and close once, but then the page will no longer scroll after closing and the modal will not reopen again if I try clicking the button again.

The prototype error above gets posted to the console on modal open and close and initially on page load.

**Comment by janschoenherr** [comment]
Please try the latest beta. Does it fix this?

**Comment by bribar** [comment]
This did fix it with the modals. Switcher tabs do not seem to be working still. Tested setup and works fine without Magento. So I believe it's the same toggle conflict. It will change to another tab but content is blank and then it will not go to another tab.

**Comment by bribar** [comment]
Seems to be an issue with Accordion too. Remove it from Magento in my test environment and it works great. My guess, any component that toggles will have same issue.

**Comment by bribar** [comment]
Anything new on this?

**Comment by janschoenherr** [comment]
Is this still an issue with the latest beta releases? There has been work on the event order that might have caused the issue.
