### ISSUE TITLE
scrollspy and dynamic content

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#242]
Following script works in newest Firefox and Chrome (Mac and Win) and in IE 11 but NOT in Safari Mac and IE 9.
What am I doing wrong?
I would like to listen to uk.scrollspy.inview in a page with dynamic content

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>scrollspy</title>

<script src="../all/jquery/jquery-1.10.2.min.js"></script>

<link id="data-uikit-theme" rel="stylesheet" href="../all/uikit/uikit-2.1.0/css/uikit.gradient.css">

<script src="../all/uikit/uikit-2.1.0/js/uikit.js"></script>

</head>
<body>

<div id="injector"></div>

<div style="border: 10px solid red; height: 2000px;"></div>

<div data-uk-scrollspy="{cls:'meincss', repeat: true}">scrollspy</div>

<div style="border: 10px solid red; height: 2000px;"></div>

<div data-uk-scrollspy="{cls:'meincss', repeat: true}">scrollspy</div>

<script>

$(document).on("uk.scrollspy.inview",'[data-uk-scrollspy]', function(event) {
               $(this).append('<br />inview 1');
               });

$(document).ready(function() {
                  
                  inject_divs = '<div style="border: 10px solid orange; height: 2000px;"></div><div data-uk-scrollspy="{cls:\'meincss\', repeat: true}">scrollspy</div>';
                  $('#injector').append(inject_divs);
                  
                  
                  
                  $(document).on("uk.scrollspy.inview",'[data-uk-scrollspy]', function(event) {
                                  $(this).append('<br />inview 2');
                                 });
                  
                  });

</script>

</body>
</html>

**Comment by austre** [comment]
I have a PHP code that generates this structure:

```
<div class="uk-grid uk-grid-width-1-4" data-uk-scrollspy="{cls:'uk-animation-slide-left', target:'.animateme', delay:900, repeat:true}">
	<div class="animateme"></div>
	.
	.
	.
</div>
```

So, i could have N animateme divs. All this code is a dynamic, i could not make scrollspy works only with the explanations on this topic. Someone can help me?
