### ISSUE TITLE
uikit 3 tooltip

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2420]
Hello! When pointing to an element with a tooltip, it shows tooltip and title. In uikit 2 shows only the tooltip!  More in uikit  2 he updated the text in the tooltip. Now the text is updated only title!

HTML CODE:

`<div id="monitoring-record" title="Сервера пусты!" uk-tooltip="pos: left"></div>`

JS CODE:

`$record.attr('title',getServersPlayers(players));`

It is strange that the standard title works and no tooltip by uikit!

![default](https://cloud.githubusercontent.com/assets/18468664/23080110/ae188fc0-f560-11e6-9919-ea0100b28c14.png)

**Comment by kirich1368** [comment]
FIX PLEASE

**Comment by janschoenherr** [comment]
Please show your issue with an example on codepen.io. Thanks.

**Comment by kirich1368** [comment]
Look, the tooltip has not changed, and changed title(html).
How do JS code to change the tooltip(uikit 3)?

var $record = $('#monitoring-record');
$record.attr('title',getServersPlayers(players));

Can it is necessary as it is done through ??? UIkit.tooltip ();

**Comment by kirich1368** [comment]
why the title is updated, and the tooltip is not?

**Comment by kirich1368** [comment]
HHHEEELLLPPP

**Comment by janschoenherr** [comment]
This has been added with 0cb99de2ac31e208796a16e831b7108e3369bbc8.

**Comment by kirich1368** [comment]
Thanks, earned! But, whether it is possible to make that did not appear title, and only a tooltip??
![2281e54c-05e1-11e7-881c-f8144439bb16](https://cloud.githubusercontent.com/assets/18468664/23854325/05e2a318-0802-11e7-937c-0f721a816782.png)
