### ISSUE TITLE
How to Pass W3C Test?

### ISSUE THREAD

**Issue by Uranbold** [uikit/uikit#2422]
Hello,

First of all this is amazing Framework but if i test it on W3C validator has shown error on Icon and other Scrollspy etc?

How do we resolve this guys?

Thanks.

**Comment by haydnjames** [comment]
Is this because  of the 'uk-icon' JS tags? I found that data-uk-icon passes W3C validation checks :)

**Comment by Uranbold** [comment]
Look at this -> https://validator.w3.org/nu/?doc=http%3A%2F%2Fthemewaves.com%2Fdemo%2Fever%2F

I have used this on our theme demo and W3C didn't pass it.

Reason is the Scrollspy and ik-icon.

**Comment by haydnjames** [comment]
Simply by swapping uk-* for data-uk-* 

The docs state both are fully supported but only data-uk-* seems to pass validation.

I read somewhere (can't recall where!) that W3C validation of custom JS attributes is a little unreliable currently - so even though your code is failing, it is actually valid :)

**Comment by Uranbold** [comment]
@haydnjames Thanks!
