### ISSUE TITLE
Meteor FlowRouter strange behavior

### ISSUE THREAD

**Issue by bioduds** [uikit/uikit#2423]
This may look strange but eversince I upgraded to beta10 or 9 and above, my router system started to behave strangely, throwing an error when I go into one router page and back. I tried to track it every way I thought so far with no luck. Error is as follows:

Exception from Tracker recompute function:
meteor.js?hash=27829e9…:930 Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at Function.DOMRange._insertNodeWithHooks 

I don't know exactly if it is related to UIkit but I do know that it started exactly when I made the upgrade from 8 to 9 or 9 to 10, not quite sure which one was it. I putted on Atmosphere UIkit3 by bioduds, I'm updating everytime a new beta comes up, my current project is built on top of it. If you guys have any hint on what could be the problem I'd appreciate it.

**Comment by bioduds** [comment]
I just tracked the error down right now, it's the modal. And I was having trouble with it before. I was not being able to call an event on a button inside the modal. There is something wrong with the modal I strongly suggest you take a look at it. Heres all the code



  <div id="modal-overflow-terms" uk-modal>
    <div class="uk-modal-dialog">
      <button class="uk-modal-close-default" type="button" uk-close></button>
      <div class="uk-modal-header">
        <h2 class="uk-modal-title">Terms & Conditions</h2>
      </div>
      <div class="uk-modal-body" uk-overflow-auto>

        <p>By accessing and using this website, you ACCEPT and AGREE to be bound by the terms and provision of this AGREEMENT. In addition, when using this websites particular services, you shall be subject to any posted GUIDELINES or RULES applicable to such services, which may be posted and modified from time to time. ALL SUCH GUIDELINES or RULES are hereby incorporated by reference into the Terms of Service (TOS).
        </p>

        <p>ANY PARTICIPATION IN THIS SITE WILL CONSTITUTE ACCEPTANCE OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ABIDE BY THE ABOVE, PLEASE DO NOT USE THIS SITE.
        </p>

        <p>This site and its components are offered for INFORMATIONAL PURPOSES ONLY; this site shall NOT BE RESPONSIBLE or LIABLE for the accuracy, usefulness or availability of any information transmitted or made available via the site, and shall NOT BE RESPONSIBLE or LIABLE for any error or omissions in that information.
        </p>

        <p>
          INTELLECTUAL PROPERTY OF SITE HERE...
        </p>

        <p>ADVERTISING AND PROFITABILITY OF SITE...
        </p>

        <p>
          DATA AND PRIVACY 
        </p>

        <p>GOODS AND DELIVERIES - NOT LIABLE FOR THIRD PARTIES
        </p>

        <p>OTHER MATTERS...
        </p>

      </div>
      <div class="uk-modal-footer uk-text-right">
        <button id="ec-modal-dont-agree"
        class="uk-button uk-button-default uk-modal-close" type="button">
          I DO NOT AGREE 
        </button>
        <a id="ec-modal-agree-button"
        class="uk-button uk-button-primary">I AGREE</a>
      </div>
      <script></script>
    </div>
  </div>
  <div id="modal-full-sent-correctly" class="uk-modal-full" uk-modal>
    <div class="uk-modal-dialog">
      <div class="uk-grid-collapse uk-child-width-1-2@s uk-flex-middle" uk-grid>
        <div class="uk-background-cover" style="background-image: url('{{ROOT}}/img/save_am.png');" uk-height-viewport></div>
        <div class="uk-padding-large">
          <h1>Congratulations!</h1>
          <p>Your Activity has been correctly sent. Please click the button below to see its publication.</p>
          <a href="{{ROOT}}/projects/view/{{publication_link}}" class="uk-button uk-button-primary">Check my Activity Publication</a>
        </div>
      </div>
    </div>
  </div>


This piece of code here was causing my problems, I took it off all went back to normal.

**Comment by bioduds** [comment]
`  <div id="modal-overflow-terms" uk-modal>
    <div class="uk-modal-dialog">
      <button class="uk-modal-close-default" type="button" uk-close></button>
      <div class="uk-modal-header">
        <h2 class="uk-modal-title">Terms & Conditions</h2>
      </div>
      <div class="uk-modal-body" uk-overflow-auto>

        <p>By accessing and using this website, you ACCEPT and AGREE to be bound by the terms and provision of this AGREEMENT. In addition, when using this websites particular services, you shall be subject to any posted GUIDELINES or RULES applicable to such services, which may be posted and modified from time to time. ALL SUCH GUIDELINES or RULES are hereby incorporated by reference into the Terms of Service (TOS).
        </p>

        <p>ANY PARTICIPATION IN THIS SITE WILL CONSTITUTE ACCEPTANCE OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ABIDE BY THE ABOVE, PLEASE DO NOT USE THIS SITE.
        </p>

        <p>This site and its components are offered for INFORMATIONAL PURPOSES ONLY; this site shall NOT BE RESPONSIBLE or LIABLE for the accuracy, usefulness or availability of any information transmitted or made available via the site, and shall NOT BE RESPONSIBLE or LIABLE for any error or omissions in that information.
        </p>

        <p>
          INTELLECTUAL PROPERTY OF SITE HERE...
        </p>

        <p>ADVERTISING AND PROFITABILITY OF SITE...
        </p>

        <p>
          DATA AND PRIVACY 
        </p>

        <p>GOODS AND DELIVERIES - NOT LIABLE FOR THIRD PARTIES
        </p>

        <p>OTHER MATTERS...
        </p>

      </div>
      <div class="uk-modal-footer uk-text-right">
        <button id="ec-modal-dont-agree"
        class="uk-button uk-button-default uk-modal-close" type="button">
          I DO NOT AGREE 
        </button>
        <a id="ec-modal-agree-button"
        class="uk-button uk-button-primary">I AGREE</a>
      </div>
      <script></script>
    </div>
  </div>
  <div id="modal-full-sent-correctly" class="uk-modal-full" uk-modal>
    <div class="uk-modal-dialog">
      <div class="uk-grid-collapse uk-child-width-1-2@s uk-flex-middle" uk-grid>
        <div class="uk-background-cover" style="background-image: url('{{ROOT}}/img/save_am.png');" uk-height-viewport></div>
        <div class="uk-padding-large">
          <h1>Congratulations!</h1>
          <p>Your Activity has been correctly sent. Please click the button below to see its publication.</p>
          <a href="{{ROOT}}/projects/view/{{publication_link}}" class="uk-button uk-button-primary">Check my Activity Publication</a>
        </div>
      </div>
    </div>
  </div>
`

**Comment by bioduds** [comment]
trying to paste raw code it changing into rendered html

**Comment by bioduds** [comment]
I was able to refine it and more specifically, the error is here 

``

**Comment by bioduds** [comment]
to be the most specific I can, happens when I changed id name of modal.

**Comment by bioduds** [comment]
UIkit.modal( "#modal-full" )[0].show();

from my javascript works

if I change to UIkit.modal( "#modal-full-whatever-else" )[0].show();

bug!

hope this helps

**Comment by janschoenherr** [comment]
Fixed in Beta 13. Please note that `UIkit.modal()` will no longer return an array, but the component itself.

**Comment by bioduds** [comment]
great news, testing right away :)

**Comment by bioduds** [comment]
great news, testing right away :)
