### ISSUE TITLE
Built in Javascript functions do not work without preventDefault

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#2427]
Beta 11 (Haven't tested on previous) 

In jQuery do a click event and use it to toggle something like a overlay or off-canvas bar for example:
```
$("div").click(function() {
    UIkit.offcanvas("#offcanvas")[0].toggle();
});
```
Will result in the off-canvas updating to have display block, however it will not show as it doesn't receive the correct classes. 

To fix it you have to do:
```
$("div").click(function(e) {
    e.preventDefault();
    UIkit.offcanvas("#offcanvas")[0].toggle();
});
```
Is this intended functionality? It seems strange to me as clicking a div has no default?

**Comment by janschoenherr** [comment]
Please see #2416. It has been fixed in the develop branch.
