### ISSUE TITLE
disable inverse component

### ISSUE THREAD

**Issue by gingibash** [uikit/uikit#2429]
can it be hooked in some other way so it can be disabled in _import.utilities.less?

it makes the final css 2x bigger, and now inverse has to commented out in all components that use it.

**Comment by masplay** [comment]
+++ !

**Comment by masplay** [comment]
you need this component to make you want to disable

**Comment by PixelT** [comment]
+1

**Comment by saschadube** [comment]
If you want to disable the inverse mode in general just do:

`@inverse-global-color-mode: none;`

You can also disable the inverse mode for specific components:

```
@card-primary-color-mode: none;
@card-secondary-color-mode: none;

@offcanvas-bar-color-mode: none;

@overlay-primary-color-mode: none;

@section-primary-color-mode: none;
@section-secondary-color-mode: none; 
```

**Comment by masplay** [comment]
if, in
 `_import.utilities.less` comment out `//@import "inverse.less";` will pop up the error while compiling css
