### ISSUE TITLE
uikit 3: will there be implemented Slider component?

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2430]
as in uikit 2?

**Comment by SylentNight37** [comment]
Looks like they have this covered in the slidenav component.

[https://getuikit.com/docs/slidenav](url)

**Comment by AlexandreZaytsev** [comment]
no, I'm not talking about navigation (https://getuikit.com/v2/docs/slidenav.html)
I need the slide with the animation... like https://getuikit.com/v2/docs/slider.html
with  autoplay, and so on

**Comment by SylentNight37** [comment]
Ah, you're right. I was thinking that they were going to combine the components with the inclusion of the 'container' in the slidenav for v3. However, it looks like they plan on getting to it based on their release blog post from 09-Jan: [UIkit 3 Beta Released](https://yootheme.com/blog/2017/01/09/uikit-3-beta-released)

**Comment by janschoenherr** [comment]
This is currently being built.

**Comment by saschadube** [comment]
The [Slider component](https://getuikit.com/docs/slider) is now available in UIkit 3.
