### ISSUE TITLE
uikit3 - Lightbox - Loading resource failed!

### ISSUE THREAD

**Issue by xspline** [uikit/uikit#2432]
Why I get this message "Loading resource failed!" when open lightbox?

**Comment by zzseba78** [comment]
It's not finished yet. Look for another alternative, it's under development.

**Comment by xspline** [comment]
> But it working on my PC and on demo page it working good... I temporarily connect lightbox plugin

**Comment by mogholito** [comment]
As I can see in this [demo page](https://getuikit.com/assets/uikit/tests/lightbox.html), although it's still a work in progress, it's not bad, it's works, but only if jquery and uikit.js are loaded from <head>.  If you place them just before the body close tag, it doesn't work and you get the "Loading resource failed!" message.
