### ISSUE TITLE
Cover is not showing with jquery in head

### ISSUE THREAD

**Issue by tuxxy** [uikit/uikit#2435]
I'm trying to use the cover component. It shows when I remove jquery from the script definitions in my head, but not when I add it in.

```
<!DOCTYPE html>
<html>
    <head>
        <title>test</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.12/css/uikit.min.css">
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.12/js/uikit.min.js"></script>
    </head>
    <body>
        <div class="uk-cover-container">
            <img src="https://getuikit.com/assets/uikit/tests/images/photo.jpg" alt="" uk-cover>
        </div>
    </body>
</html>
```

In the above example, the image does not show. What's up?

When I move the jquery definition below the `uikit.min.js` definition, it shows up, but the uikit js doesn't function properly (ie: adding an icon -- icon doesn't appear).

**Comment by tuxxy** [comment]
**Update:**
Copied the cover boilerplate test code into my test application. None of the fixed height cover components are loading. Looks to be a genuine issue. I've run out of ideas here.

**Comment by haydnjames** [comment]
I just tested your HTML and it's throwing an error as it's unable to locate the CSS file. Is the URL in the head correct?

**Comment by tuxxy** [comment]
My mistake, I mispasted the css link. It's updated now.

**Comment by haydnjames** [comment]
And is it working now?

**Comment by tuxxy** [comment]
No.

**Comment by tuxxy** [comment]
This is what I see in my browser. Notice no photo in the cover.

![image](https://cloud.githubusercontent.com/assets/3598318/23157250/9db25d90-f7d7-11e6-82a9-ace6a4f31fcd.png)

**Comment by haydnjames** [comment]
Ah, that's because you haven't set a height on your um-cover-container. You need to add a uk-height-* tag too. This is because once the image is applied as a background via the JS, there is no content inside the cover div so it collapses. 

Try this...

`
<div class="um-cover-container uk-height-medium">
            <img src="https://getuikit.com/assets/uikit/tests/images/photo.jpg" alt="" uk-cover>
</div>
`

**Comment by tuxxy** [comment]
Doh! Nice catch, thanks for your help!

**Comment by haydnjames** [comment]
No worries :)

**Comment by tuxxy** [comment]
Perhaps this issue remain open for a default height if none is provided?
