### ISSUE TITLE
a small error with gantry (5.4.8.)

### ISSUE THREAD

**Issue by cyb3rx** [uikit/uikit#2436]
Hello!

I'm use gantry with uikit
http://www.inspiretheme.com/documentation/gantry5-particles/uikit-for-gantry5

I tested it new version, I change css and js files to beta12.
I look it my test page with mobile and the mobile (toggle) menu is not work perfect.
I press the icon open the menu and close it immediately, not sticky there.
my test page: http://gantry.extazispaintball.hu/

with the Ukit 2.72. version working correct all function
could you fix it this issue?
or what can I do? any idea?

Thanks!

**Comment by janschoenherr** [comment]
Please try the new Beta 16 and reopen the issue if the problem persists.

**Comment by cyb3rx** [comment]
Hello!
I changed the files

It remains the problem in mobile!
I was test is firefox and chrome

please look it my test site.
