### ISSUE TITLE
Is nested modal working ?

### ISSUE THREAD

**Issue by mvanvu** [uikit/uikit#2439]
I got the issue: 
Modal 1 inside modal 2. When modal 2 is hide after that modal 1 is hide too.
Hope It will work fine like a nested modal.

Thanks.

**Comment by janschoenherr** [comment]
There are two modes: Group and Stack

https://getuikit.com/assets/uikit/tests/modal.html

**Comment by janschoenherr** [comment]
Closing this, as it does not seem to be an issue?
