### ISSUE TITLE
UiKit 3.0.beta.12 - dropdowns in navbar closes before mouse over

### ISSUE THREAD

**Issue by gensmann** [uikit/uikit#2443]
It seems that dropdowns in a navbar are loosing the mouse over when activated making it impossible to click on an nav item in the dropdown since it closes before the mouse can reach the menu item.

This isn't a problem in beta 11.

It's testable in the documentation:

https://getuikit.com/docs/navbar#dropdowns

I see the same result in chrome and safari.

**Comment by zzseba78** [comment]
Same here +1

**Comment by imarkdesigns** [comment]
`[class*='uk-navbar-dropdown-bottom']` to work with the dropdown, i use to drop the value of `margin-top: 15px;` to `margin-top: 0;`.

everything works fine. the only part that i think we can open here is the "boundary alignment".

**Comment by rubyandcoffee** [comment]
I'm having the same issue, dropdown in nav bar is almost unusable because of this.

**Comment by sjclark** [comment]
This problem occurs even on the first example within the official docs - although not in the tests.
https://getuikit.com/docs/navbar

**Comment by janschoenherr** [comment]
Fixed in Beta 13.
