### ISSUE TITLE
Spinner - change size

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2444]
Add possibility to change uk-spinner icon size
I change the value of @spinner-size in sources, but without any effect.

**Comment by bukaOK** [comment]
try to change svg size(not wrapper) with css

**Comment by aarongerig** [comment]
Just do it like this: `<div uk-spinner="ratio: 2"></div>`. Works fine for me...

**Comment by liran-co** [comment]
That messes with the animation...

**Comment by janschoenherr** [comment]
This should be resolved with 7de8716bfff9ddacbe324c2b99b3cbf04b888780

You can use the ratio to change the spinner size again.
