### ISSUE TITLE
Tab switching itself when select text in input box

### ISSUE THREAD

**Issue by hiren1610** [uikit/uikit#2445]
I have basically created code like below to generate tabs with some input boxes to get user input and have button to run some script.

```HTML
<ul class="uk-tab" data-uk-tab="{connect:'#subnav-pill-content-1'}">
	<li class="uk-active"><a href="#">Item</a></li>
	<li><a href="#">Item</a></li>
	<li><a href="#">Item</a></li>
</ul>
<ul id="subnav-pill-content-1" class="uk-switcher">
	<li>
		<p>Input 1</p>
		<input type="text" spellcheck="false"/>
		<button>Button 1</button>
	</li>
	<li>
		<p>Input 2</p>
		<input type="text" spellcheck="false"/>
		<button>Button 2</button>
	</li>
	<li>
		<p>Input 3</p>
		<input type="text" spellcheck="false"/>
		<button>Button 3</button>
	</li>
</ul>
```

The issue is as below.
If user have any input in the input box, and if select text in input box using cursor, it changes the tab after selecting the text.
Behavior I have noticed is as below.
1. If you select text from left to right, it will change to previous tab.
2. If you select text from right to left, it will change to next tab.
3. It only occurs when selected more than 2 characters in input element. If select 1 or 2 characters only, it selects text fine and doesn't switch tab.
4. Selection using keyboard works okay.
5. Double click to select all text works okay.
6. Tried in Chrome and Firefox, works okay.
7. Issue only occurs in IE 11.

Let me know if any further information or troubleshooting required. I need help on this issue.

I can generate a video to show behavior if required but it might take some time so let me know if its really required and I can create a sample.

Edit : I am using UIkit 2.27.2 and jQuery 3.1.1

**Comment by carlos-duran** [comment]
That is a feature

To disable use: **swiping: false**

`uk-tab="{connect:'#subnav-pill-content-1', swiping: false}"`

**Comment by hiren1610** [comment]
Thank you for that. I completely missed that part to have a look. That fixed my issue ( not technically an issue ).

**Comment by HongbinZhu** [comment]
Thanks for the tip! I am getting this issue too.
