### ISSUE TITLE
Make it clear in the website that Uikit is the most recent version

### ISSUE THREAD

**Issue by dvriv** [uikit/uikit#2447]
I just discovered Uikit so I go to the wesbite and saw a link to "Uikit 2". My first thought was that Uikit v2 was the most recent version. It took me a while to realize, and only because the 2nd time I come to website I saw the "beta" label aside the logo that I realized that I was mistaken.

I am not sure but maybe other people can make the same mistake, a small text in a side of the version 2 link or in the v2 homepage can eliminate that possibility.

**Comment by masplay** [comment]
below is written Version 3.0.0-Beta

**Comment by gideondsouza** [comment]
However https://getuikit.com/ doesn't say what version it is and there is a button on the bottom right that links to UIKit2 so this is fairly confusing.

**Comment by m0yP** [comment]
I don't agree with this. On mobile, there's no link to v2 even. And it clearly says version 3.x.x beta at the bottom left of the site. Now, we all know that version 3 must be above version 2.

**Comment by janschoenherr** [comment]
Please move this issue over to https://github.com/uikit/uikit-site. Thanks
