### ISSUE TITLE
Icons - CDN

### ISSUE THREAD

**Issue by lukashl** [uikit/uikit#2451]
When link CSS from CDN:

XMLHttpRequest cannot load https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.12/images/icons.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx.app' is therefore not allowed access.

**Comment by carlos-duran** [comment]
I think it's a problem from cloudflare. Maybe we need another cdn option..
I want more answers for this.

**Comment by WannesVandamme** [comment]
i used this other cdn http://www.bootcdn.cn/uikit/ and icons worked.

**Comment by janschoenherr** [comment]
The icons have been moved into JavaScript with Beta 13.

https://getuikit.com/docs/icon#usage
