### ISSUE TITLE
npm (still) not watching less?

### ISSUE THREAD

**Issue by wanze** [uikit/uikit#2452]
I still have the following issue: https://github.com/uikit/uikit/issues/2415
The comitted fix does not seem to work for me.

npm run watch does initially compile my less file from the custom folder, and it says at the very end:

```[compile-less] [nodemon] clean exit - waiting for changes before restart```

But if I change the less file, it is not getting recompiled automatically. Can anyone confirm that it works on the current develop branch or what am I missing? Thanks! :)

Node: 6.10.0
npm: 4.3.0
Mac OSX 10.123

**Comment by janschoenherr** [comment]
Fixed in Beta 13. Thanks.

**Comment by wanze** [comment]
@janschoenherr 
Thanks for the fix, however it does not seem to work for me with beta16. I did pull the latest develop branch and executed `npm install` again, still auto-compiling does not work. Maybe I'm missing something :)

**Comment by gabyferman** [comment]
Hi, 
I'm also having trouble with `npm run watch` 

I have my custom folder with mytheme.less and the folder mytheme, and nothing seems to change when I modify either mytheme.less or the files inside the folder.

Though if I use `npm run compile` I can see the files and changes in the dist folder on the uikit.mytheme.css

node: 6.10.3
npm: 5.3.0
