### ISSUE TITLE
Can't use uk-grid attribute with JSX

### ISSUE THREAD

**Issue by alecholmez** [uikit/uikit#2457]
Special attributes are not allowed in `JSX`. I tried using the `is` key word but the grid padding and margin rules did not evaluate properly

**Comment by gregBerthelot** [comment]
Hi @alecholmez did you manage to fix the issue? Do you have the issue with other attributes?

Thanks

**Comment by janschoenherr** [comment]
You can also use: _data-uk-grid_

See: https://getuikit.com/docs/javascript#component-usage

**Comment by alecholmez** [comment]
I fixed the issue
