### ISSUE TITLE
Visual Studio Code Snippets for UIKit

### ISSUE THREAD

**Issue by dons20** [uikit/uikit#2461]
This one isn't an issue, more of a new thing that I made to contribute to the community.
I've been using Visual Studio Code for a while now, and snippets are super useful for my development. So I decided to make some snippets for UIKit to make it easier to use.

[Check it out on the marketplace](https://marketplace.visualstudio.com/items?itemName=Keno.uikit-3-snippets)

[Github Link](https://github.com/dons20/UIKit-VSCode)

**Comment by florianletsch** [comment]
Great! I have added it to https://github.com/uikit/awesome-uikit that we just started this week.

**Comment by jsieler** [comment]
May you please add autocomplete feature to VSCode aswell?

**Comment by dons20** [comment]
@jsieler Autocomplete is a feature built into VSCode by default. It's called Intellisense, and you can usually manually trigger it with Ctrl+Space.
