### ISSUE TITLE
howto require icons (they are in javascript now)

### ISSUE THREAD

**Issue by filly82** [uikit/uikit#2462]
In the new Beta13 the icons moved to Javascript as the ReleaseNotes say, the official doc says to include "<script src="js/uikit-icons.min.js"></script>" in my "<head>" ... but i included uikit itself via require('uikit'). how can i include the icons now?

this is what I am doing:
var UI = window.UI = UIkit = window.UIkit = require('uikit');

but I also need the Icons now:
var UIkitIcons = window.UIkitIcons = <WHAT_TO_PUT_HERE>

Thanks in Advance

**Comment by filly82** [comment]
I tried following, which seems to be the right way

var UIkitIcons = window.UIkitIcons = require('uikit/dist/js/uikit-icons');

but then I get the following error

Uncaught TypeError: window.UIkit.use is not a function

**Comment by janschoenherr** [comment]
Are you using webpack 2?

window.UIkit = require('uikit');

this will not add UIkit but rather point to an ES module:  ({ __esModule: true, default: UIkit })

**Comment by florianletsch** [comment]
As Jan said, this should now work. Can you confirm this?

For the basic Webpack setup (not including the fonts import, though), we have added a section to the docs. https://getuikit.com/docs/webpack
