### ISSUE TITLE
a small error with gantry, mobile menu issue

### ISSUE THREAD

**Issue by cyb3rx** [uikit/uikit#2467]
#2436 

Hello!
I changed the files to 3.0.0.16

It remains the problem in mobile!
I was test is firefox and chrome
please look it my test site. # @janschoenherr

**Comment by cyb3rx** [comment]
still an error yet, UiKit 3.0.0.18

#2436 
@janschoenherr

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM

**Comment by joseOlivares** [comment]
Hi, coded a tempory JavaScript solution, so if want to use it, download this file (attached on the bottom) and test it.
1. Upload  mobilemenu_fix.js to your JS custom script folder.
2. Add mobilemenu_fix.js URL inside your Gantry5 Theme ( Theme->Page setting->Javascript)
 
The solution works for me. I hope this could help to someone else
[mobilemenu_fix.zip](https://github.com/uikit/uikit/files/2813210/mobilemenu_fix.zip)
