### ISSUE TITLE
Uikit3 (beta16): UIkit.notification HTML  message don't close

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2468]
under  unix server
	` <script>UIkit.notification("<span uk-icon='icon: check'></span> Message");</script>`
the message hangs on the screen the close button does not respond, the timeout does not close

ps
under windows local - all ok

**Comment by janschoenherr** [comment]
This might be a caching issue? It has been fixed in Beta 16.

https://getuikit.com/docs/notification

**Comment by AlexandreZaytsev** [comment]
dumped all cache... unfortunately did not help...

**Comment by florianletsch** [comment]
I think he means the cache of your Browser. Please make sure the browser loads the newest version of the JavaScript, thanks.

**Comment by AlexandreZaytsev** [comment]
for my message #2468 and #2472
used  
  http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js, or
  https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js, or
  https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js
cleaned the browser cache
...
resume
in beta 12 and below, the same code worked fine, and at 13 and above no

**Comment by AlexandreZaytsev** [comment]
working fine... didn't touch a week after cleaning the cache... there must be something somewhere left
...
sorry
