### ISSUE TITLE
Using self-closing tags in SVG

### ISSUE THREAD

**Issue by shur** [uikit/uikit#2470]
Is there a serious reason not to use self-closing tags in SVG? Then the files would be a little bit lighter.

I mean why not using this:
`<polygon points="5 13 10 8 15 13" />`
Instead of the current this:
`<polygon points="5 13 10 8 15 13"></polygon>`

**Comment by masplay** [comment]
Internet Explorer

it is important that the SVG markup was not self-closing tags. You need to explicitly specify the closing tag if there is no content.

**Comment by florianletsch** [comment]
Hm, I found a [source confirming](http://stuntbox.com/blog/2013/06/bulletproof-inline-svg/) that self-closing tags cause troubles with IE8. However, IE8 is not officially supported by UIkit, so I am not sure if this is a valid reason. 

Any source for newer versions of IE?

**Comment by shur** [comment]
I know about some SVG problems only in IE8, but I am not aware of any problems in modern browsers.

It's UIkit 3.x and 2017 year , might worth considering some changes.

**Comment by dasdeck** [comment]
SVGs will be self-closing in the upcoming update.
