### ISSUE TITLE
Unreachable code at line 283

### ISSUE THREAD

**Issue by shur** [uikit/uikit#2471]
When I try to minify uikit.js by ClosureCompiler
[http://closure-compiler.appspot.com/home](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520uikit.min.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fuikit%252Fuikit%252Fdevelop%252Fdist%252Fjs%252Fuikit.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250A)

I get this warning:

> Number of warnings: 1
JSC_UNREACHABLE_CODE: unreachable code at line 283 character 8 in uikit.js
        var obj;
        ^

**Comment by florianletsch** [comment]
Hm, this looks like a non-issue to me, or at least not a UIkit issue.

Here's what I think is happening: The Babel compiler produces that output. The resulting line is actually a variable declaration after a return statement. According to the JS standard, hoisting means that the declaration is equivalent at the bottom than if it would be at the top. Or in other words: It is valid JS.

Looks like the people who build the closure compiler are a little divided about that topic: https://github.com/google/closure-compiler/issues/2240

Either way, I think this is part of the toolchain and nothing we can or need to change.
