### ISSUE TITLE
Uikit3 (beta16): OffCanvas - the sub section <ul> breaks menu

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2472]
under unix
![image](https://cloud.githubusercontent.com/assets/16114000/23500493/5b51d766-ff41-11e6-9ab1-7de7c647d55b.png)
```
<div id="left_offcanvas" uk-offcanvas="mode: push">
	<div class="uk-offcanvas-bar" style="width: 300px;">
		<ul class="uk-nav-default uk-nav-parent-icon" uk-nav="multiple: true">
       		<li class="uk-active"><a href="#">Active</a></li>
       		<li class="uk-parent">
           		<a href="#">Parent</a>
	            <!--ul class="uk-nav-sub">
	                <li><a href="#">Sub item</a></li>
	                <li>
	                    <a href="#">Sub item</a>
	                    <ul>
	                        <li><a href="#">Sub item</a></li>
	                        <li><a href="#">Sub item</a></li>
	                    </ul>
	                </li>
	            </ul-->
	        </li>
	        <li class="uk-parent">
	            <a href="#">Parent</a>
	            <!--ul class="uk-nav-sub">
	                <li><a href="#">Sub item</a></li>
	                <li><a href="#">Sub item</a></li>
	            </ul-->
	        </li>
	    </ul>
	</div>
</div>
```
uncomment section
`<ul class="uk-nav-sub"> ...`
![err](https://cloud.githubusercontent.com/assets/16114000/23500745/2189c8d0-ff42-11e6-8785-c74fa0527c42.png)

no icon, no menu, page - 'floated'

**Comment by florianletsch** [comment]
Could you copy the markup to [Codepen](https://codepen.io/anon/pen/bqEzMW) to show the issue? Thanks.

**Comment by AlexandreZaytsev** [comment]
in Codepen - ok
in my CMS - error....
if the menu contains elements of the first level - everything is fine - if deeper - error
...
what can be done?

**Comment by AlexandreZaytsev** [comment]
if I run the page and remove comments with nested elements in the debugger browser the page does not break
![image](https://cloud.githubusercontent.com/assets/16114000/23506233/45328c70-ff58-11e6-87e5-3e181f1c5b1c.png)
if I run the page with deleted comments - broken page immediately

**Comment by florianletsch** [comment]
If you can reproduce this error on a Codepen, please post the link to the Codepen.

If it does not happen in the Codepen, it is most likely not a UIkit issue.

I am afraid I cannot understand the problem from screenshots alone.

**Comment by AlexandreZaytsev** [comment]
for my message #2468 and #2472
used
http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js, or
https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js, or
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js
cleaned the browser and CMS cache
...
resume
in beta 12 and below, the same code worked fine, and at 13 and above no

**Comment by AlexandreZaytsev** [comment]
working fine... didn't touch a week after cleaning the cache... there must be something somewhere left
...
sorry
