### ISSUE TITLE
responsive cover - dancing margin

### ISSUE THREAD

**Issue by gingibash** [uikit/uikit#2473]
using example from uikit website

`<div class="uk-cover-container">`
`<canvas width="1920" height="1280"></canvas>`
`<img src="......." uk-cover>`
`</div>`

image is also 1920*1280

1px margins appear on top, left side or both on window resize 

take a look at [https://vid.me/7OBG](https://vid.me/7OBG)

**Comment by janschoenherr** [comment]
Please add a reproducible test case from e.g. http://codepen.io.

**Comment by gingibash** [comment]
@janschoenherr I do not use codepen but you can take a look at [staging](https://staging.adventure-driven-vacations.com) site

**Comment by janschoenherr** [comment]
Is this still an issue with the latest beta?
