### ISSUE TITLE
icons in JavaScript

### ISSUE THREAD

**Issue by masplay** [uikit/uikit#2475]
why not moved to java ?
these icons will be in form.less ?

```
form-select.svg
form-radio.svg
form-checkbox.svg
form-checkbox-indeterminate.svg
```

**Comment by florianletsch** [comment]
All icons have been moved to the JavaScript icon library which need to be injected into the DOM dynamically. In total, there are 3 kinds of icons. 2 of these are compiled into JS files.

1. This is true for icons form the "Icon" component which are located in `/src/images/icons`.  These are compiled into `uikit-icons.js`. 
2. Additionally, some components use icons as well. These are located in `/src/images/components` and are compiled into the default `uikit.js`.
3. Some SVGs are just used as background images. These are located in `/src/images/background` and are not compiled into the JavaScript.
