### ISSUE TITLE
Offcanvas Component - Please re-think it.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2478]
**The offcanvas menu is the weak arm of uikit 3.**
It works fine in pc, but in mobile the experience it's not good at all:

- When you open it it's like the width exceeds the viewport, you can scroll vertically.
- The overlay gets over the site content
- If you try to close the offcanvas with gesture, it only scroll vertically, and if you scroll horizontally again everythink get mess out.
- The animation performance it's very bad.
- It doesn't work with gestures.
- The offcanvas closes without animation ( since latest beta ).
- It would be nice to have offcanvas from top and bottom ( feature request ).

This happens on Android 6 ( tested in Chrome, Firefox and Opera-Mini ).

All this items together generate a uncomfortable and disconcerting navigation experience for mobile users, and since Off Canvas menus are used primarily with Mobile and touch devices, that´s why i´m asking you guys to re-think the Offcanvas Component.

Thanks for your work guys, you are awesome.

![screenshot_20170302-191315](https://cloud.githubusercontent.com/assets/5558563/23529634/103310a6-ff7d-11e6-95b7-b811c3feb2dc.png)
![screenshot_20170302-190150](https://cloud.githubusercontent.com/assets/5558563/23529635/11032fb6-ff7d-11e6-888a-53fc3746c9be.png)

**Comment by krisj** [comment]
Completely agreed, off-canvas is the primary mobile menu principle and in beta16 it is pretty much unusable on mobile (tested on iOS 8.4 and 9.3 mobile Chrome and mobile Safari).

In addition to what @zzseba78 mentioned above I am also experiencing a general stickyness and glitches with off-canvas menu. It seems like it doesn't detect short touch events on mobile or something like that. Sometimes it works fine but not every click.

Unfortunately I am currently looking at a stable working alternative and ditching the UiKit's built in component for this reason.

**Comment by blue-eyed-devil** [comment]
offcanvas nav with reveal mode on long page have bg only 100% of visible screen then scroll down transparent, with push mode scrolls at the end of page but at least keeps its own bg, with slide or none works fine. Btw swipe to open and close would be nice

**Comment by zzseba78** [comment]
Yes, me too @krisj , i'm playing with Pushy, nice and simple script to create offcanvas and seems to play nice with uikit ( not sure if Scrollspy works well on mobile ).

Here is an example:
http://research.electricmonkey.co/uk3/offcanvas.html

**Comment by krisj** [comment]
Pushy works fairly well @zzseba78 . did you try any other libs?
It just looks like UiKit does not support touch events at all which is of course a pity as that will make things very bad for mobile users. Maybe it does in some other components (I haven't investigated deeper yet).
Maybe extending UiKit with something like Hammer JS would be straight forward enough?

**Comment by krisj** [comment]
One thing that I tried earlier that seemed to improve things a little bit was calling the toggle component directly like this: href="javascript:void(0);" onclick="UIkit.offcanvas('#offcanvas-nav').toggle();"

But no time to troubleshoot it further right now...

**Comment by blue-eyed-devil** [comment]
I discovered this one today https://github.com/kinglozzer/SwipeMe/ . Just going to test so i will let you know how it goes. works with swipe and even mouse drag. minified its only 2kb

**Comment by zzseba78** [comment]
Hi @blue-eyed-devil !
Good catch! I'm using TouchSwipe, a well known script for touch interactions.
Here is the example with touch swipe ( close on swipe Left ) implemented on overlay and offcanvas bar, some tweaking in the pushy script and when the width is more than 767px the bar get closed.

http://research.electricmonkey.co/uk3/offcanvas.html

**Comment by krisj** [comment]
So it looks like this bit is messing things up big time...  from the uikit.js
`                        // trigger single tap after navbar-togglems of inactivity
                        else {
                            touchTimeout = setTimeout(function () {
                                touchTimeout = null;
                                if (touch.el !== undefined) {
                                    touch.el.trigger('singleTap');

                                    if (!clicked) {
                                        touch.el.trigger('click');
                                    }

                                }
                                touch = {};
                            }, 300);`

**Comment by zzseba78** [comment]
Thanks for label this as a bug, surely you will be able to improve it! 👍

**Comment by imarkdesigns** [comment]
Im not sure if there missing 2 CSS code here, but finally i made the Off-Canvass closing animation back to work... All you have to do is add this 2 CSS:

```
/* this was trigger on and off during offcanvas animation */
.uk-offcanvas { display: block; } 

/* i just add this to my css to support the transform CSS effect */
.uk-offcanvas-bar { transition: all 300ms ease-out; }

**Comment by zzseba78** [comment]
Offcanvas has been reworked, i will close this issue. Thanks!
