### ISSUE TITLE
Uikit 3 (Beta 16) Tooltip not working if scripts call before </body>. Only in <head>.

### ISSUE THREAD

**Issue by spleanter** [uikit/uikit#2479]
http://prntscr.com/efeuhe
http://prntscr.com/efeut9

<script src="https://yastatic.net/jquery/3.1.1/jquery.min.js"></script>
<script src="[[++js]]/uikit.min.js"></script>
<script src="[[++js]]/uikit-icons.min.js"></script>

**Comment by janschoenherr** [comment]
Fixed with f7c6293fc6de9c455a8b40c14795eca826155b33. Thanks.
