### ISSUE TITLE
Component: Upload - v3.0.0-beta.16

### ISSUE THREAD

**Issue by alexandesigner** [uikit/uikit#2482]
Is anyone else having a problem with Component: **Upload**?
![captura de tela 2017-03-03 as 15 17 46](https://cloud.githubusercontent.com/assets/3044907/23563408/541a1032-0025-11e7-8ac7-a11ae9617e03.png)

In case I'm not finding this component in the DOM:

``console.log(window)``

![captura de tela 2017-03-03 as 15 19 40](https://cloud.githubusercontent.com/assets/3044907/23563344/0e5a5ea8-0025-11e7-9ddc-d8d11b29335b.png)

I have not created any reproduce since I am using what is in the [documentation](https://getuikit.com/docs/upload#drop-area).

The previous version that was working was .11 I upgraded my project to .16 and in case this problem came up.

**Comment by janschoenherr** [comment]
You are not loading the components. Are you using the dist version? Or the core version?

**Comment by alexandesigner** [comment]
The version when we download .. I believe it is the version ``dist``

I also noticed that there has been a change in the way you are handling the plugins ..

v3.0.0-beta.11:

``function plugin(UIkit) {...}``

v3.0.0-beta.16:

``function plugin$4(UIkit) {...}``

**Comment by janschoenherr** [comment]
Please try: https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.16/js/uikit.min.js
