### ISSUE TITLE
uikit-3.0.0-beta.16: Toggle Events not firing

### ISSUE THREAD

**Issue by bribar** [uikit/uikit#2483]
`$('#toggle').on('show', function () {
				console.log('HI');
			});`

`<a id="toggle" uk-toggle="target: .toggle-me; animation: uk-animation-fade">Toggle Button</a>`
`<div class="toggle-me">Toggle Content</div>`

This event works fine with Modal component

**Comment by janschoenherr** [comment]
The 'show' is triggered on the _.toggle-me_ element. If it is not, please add an example on codepen.io. Thanks.
