### ISSUE TITLE
Flicker with Switcher tabs on iOS10 when uk animation is used

### ISSUE THREAD

**Issue by danny-englander** [uikit/uikit#2484]
I'm noticing a flicker when I switch tabs on iOS10.

**Codepen here:** 
http://codepen.io/danny_englander/full/OpXyYv/

Note the tab animation is set to:
`uk-switcher="animation: uk-animation-fade"` as per "Animations" on https://getuikit.com/docs/switcher

**Comment by janschoenherr** [comment]
Has this been resolved by one of the latest betas?

**Comment by danny-englander** [comment]
This is all set now. Thanks!
