### ISSUE TITLE
Adaptive feel of the site on tablets

### ISSUE THREAD

**Issue by IvanYar** [uikit/uikit#2488]
There is a site http://ganoderm.ru/produktsiya with two columns. When viewed on a tablet 
![default](https://cloud.githubusercontent.com/assets/26218842/23604399/d1ee7408-0269-11e7-9dee-fb7ee57079d9.jpg)
 columns obtained are very narrow. I want to remove the right column. And to make the central part of the entire width of the screen. Can you please tell how to do it?

**Comment by florianletsch** [comment]
Here is the basic idea:

Add a class from the [visibility component](https://getuikit.com/docs/visibility) to only show the right column on larger screens, e.g. `class="uk-visible@m"`.

Make sure the other two columns expand to 50% width in that case. Use classes from the [width component](https://getuikit.com/docs/width) to accomplish that. For example: `class="uk-width-1-2 uk-width-1-3@m"` for 50% width on small screens and 33% width on larger screens.

**Comment by IvanYar** [comment]
Thank you. I did not quite understand. Used class on the site uk-width-medium.
What do I need to do?
![1](https://cloud.githubusercontent.com/assets/26218842/23606714/00dc46e2-0273-11e7-99b9-61e3618b5839.jpg)
![3](https://cloud.githubusercontent.com/assets/26218842/23606716/00f5718a-0273-11e7-94f2-674e7414ba9f.jpg)

**Comment by florianletsch** [comment]
If you can create a Codepen with your Markup, maybe someone can take the time to look into this and add the appropriate classes for your specific usecase. However, as this is not a UIkit issue, I  am leaving this closed. 

For further usage advice, please refer to the G+ community: https://plus.google.com/communities/114238665434626719878 or join the Gitter chat https://gitter.im/uikit/uikit
