### ISSUE TITLE
Icon duplicate problem in carousel

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#2489]
Hello, i am using owl carousel 2 for carousel my post there i use a read more button with arrow. when carousel slide arrow icon automatically doubled. 

Look here: https://youtu.be/D5_c3lvwliM

NOTE: i am using uikit 3 beta 16

**Comment by janschoenherr** [comment]
Please add a reproducible test case from e.g. codepen.io.

**Comment by bdthemes** [comment]
Hello @janschoenherr i just add an example in codepen look here: [http://codepen.io/bdthemes/pen/ZeBYYV](http://codepen.io/bdthemes/pen/ZeBYYV)

it's not duplicate here but it's changing ratio.

**Comment by lukashl** [comment]
Icons are duplicated for example: where add <span> in another place on page.
