### ISSUE TITLE
Can't get icons to work since beta 16 move to javascript

### ISSUE THREAD

**Issue by mjbates7** [uikit/uikit#2491]
Hi, I've used the following code below, but the icons aren't showing. Do I need to adjust it in anyway to make this work? I'm using react if this changes anything.

```
import` React, { Component } from 'react';

// eslint-disable-next-line
import UIkit from 'uikit'; // this works fine
import 'uikit/dist/js/uikit-icons'; // does this need to be anything different?

class App extends Component {
	render() {
		return (
			<div className="App">
				check: <span data-uk-icon="icon: check"></span>
				<p>heart:<a href="" data-uk-icon="icon: heart"></a></p>
			</div>
		);
	}
}
export default App;
```

All I see on the page is two words and no icons next to them:

![image](https://cloud.githubusercontent.com/assets/4522738/23650406/e4d2dafe-0319-11e7-8b9e-c6a69a951471.png)

:)

**Comment by janschoenherr** [comment]
The icons are a plugin now. You'll have to do

```
import UIkit from 'uikit'; // this works fine
import Icons from 'uikit/dist/js/uikit-icons';

UIkit.use(Icons);

```

**Comment by mjbates7** [comment]
Perfect - thanks for the quick response! Perhaps you need to add this information to the webpack/some part of the documentation :)

**Comment by florianletsch** [comment]
> Perhaps you need to add this information to the webpack/some part of the documentation

[Done](https://getuikit.com/docs/webpack).

**Comment by sebelga** [comment]
@mjbates7 Did you manage to make it work in react importing only once? Or we have to do it in each component? thanks
