### ISSUE TITLE
Invalid JSON warnings

### ISSUE THREAD

**Issue by j26w** [uikit/uikit#2492]
Anyone else getting these warnings? Is it something that I should worry about? I'm using the compiled javascript file from /dist/js/uikit.min.js.

![screen shot 2017-03-07 at 11 46 16 am](https://cloud.githubusercontent.com/assets/1260184/23653142/bea5d194-032b-11e7-8f3a-ef67c5152efb.png)

**Comment by bdthemes** [comment]
Me too: http://prntscr.com/ehg4ig

**Comment by janschoenherr** [comment]
Are you trying to initialize a component with invalid JSON?

Please provide a reproduction link. You could start with this template: http://codepen.io/anon/pen/XMpryM

**Comment by DanielNemanic** [comment]
I get the same error.
After research I receive this error from the uk-nav component.

If I add an option we geht this error:
<ul class="uk-nav uk-nav-default uk-nav-parent-icon" uk-nav="{multiple:true}">

**Comment by janschoenherr** [comment]
@DanielNemanic That's not valid JSON syntax.
https://getuikit.com/docs/javascript#component-configuration

**Comment by DanielNemanic** [comment]
Damn. :)
Have the v2 syntax inside me. :)

You are right.
