### ISSUE TITLE
UIKIT 3 Documentation - Head title: Add component/ section

### ISSUE THREAD

**Issue by Heartfyre** [uikit/uikit#2493]
Hello there,

I am sure, that this isn't your number one concern, but it's something, which I just recognized. On your documentation it would be great and easier to use, if you would add the active component name to the title tag of the head. 

The reason is simple: Sometimes I am having multiple tabs with different components open and all of them are just called "UIkit". Especially now, that some things are just new, I have to check the documentation more often. But if I have multiple tabs open with different components I sometimes have to click through them to find the one I am looking for.

Again, I know that this is not you number one priority and in the end it's just a comfort feature, but still, it would be helpful. 

Thanks for all your work and the amazing UIkit!

**Comment by janschoenherr** [comment]
Has been added, thanks.
