### ISSUE TITLE
UIKit 3: Smooth scroll issue

### ISSUE THREAD

**Issue by bribar** [uikit/uikit#2496]
It might be just me, but programmatically I can't get it to scroll to an element. Is it only meant for clicking an element to activate?

Tried:
`UIkit.scroll('#scroll-to-this');`
`UIkit.scroll('scroll-to-this');`
`UIkit.scroll($('#scroll-to-this'));`

I've used this within a callback and on page load and neither seem to scroll to target...

**Comment by janschoenherr** [comment]
Yes, currently it is, please see: https://getuikit.com/docs/scroll

It is applied to the anchor.

**Comment by SaphiLC** [comment]
not working still...
