### ISSUE TITLE
On uikit update tab switch content without active tab

### ISSUE THREAD

**Issue by drpiou** [uikit/uikit#2498]
When I apply `UIkit.update()`, my tabs inside my modal reset the content to the first tab, but stays on the active tab (let's assume I'm not on the first tab when `update()` is call). The result is I have to switch a tab for an another to switch again to the tab I was on to display the content that switched to the first tab content when `update()` was called.

**Comment by janschoenherr** [comment]
Please provide a reproduction link. You could start with this template: http://codepen.io/anon/pen/XMpryM
