### ISSUE TITLE
uikit 3 beta 16: how to use switch in such a markup?

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2507]
Hi,
I can't configure the Content switch

```
<div uk-switcher="connect: #news-switcher-container; animation: uk-animation-fade">
	<div class="uk-text-center uk-grid-collapse" uk-grid>
	    <div class="uk-width-1-5@m">
		    <button class="uk-button uk-button-default" type="button">News</button>
	    </div>
	    <div class="uk-width-expand@m">
	        <ul id="news-switcher-container" class="uk-switcher uk-margin">  
			    <li>News.......</li>
			    <li>PromoNews..</li>
			</ul>
	    </div>
	    <div class="uk-width-1-5@m">
		    <button class="uk-button uk-button-default" type="button">PromoNews</button>
	    </div>
	</div>
</div>
```
for http://codepen.io/anon/pen/XMpryM

not switched to the second element
![image](https://cloud.githubusercontent.com/assets/16114000/23785482/e832bf3c-0578-11e7-9c21-4af07c5e04cb.png)

how to configure?

**Comment by zzseba78** [comment]
You have to polish it, but works. Floated buttons on left and right, and then a grid with a column centered. In this way you keep the structure that Switcher needs to work.

http://codepen.io/zzseba78/pen/zZZjae

**Comment by AlexandreZaytsev** [comment]
thank you very much
