### ISSUE TITLE
Tooltip doesn't stick to it's element - For example with scroll

### ISSUE THREAD

**Issue by Heartfyre** [uikit/uikit#2508]
Hey there,

I am having a website, where I added two buttons to the lower right hand corner. On to scroll up and one to scroll to a certain position. Their position is fixed and I added a tooltip to both of them.

When I hover the button with the tooltip and press it to scroll up or down, the tooltip remains at the starting position, while the site and my buttons scroll to the designated position.

Not sure if this can be fixed or you even want to fix it, but I wanted to report it anyway.

Here's part of the CSS I am using:

```
.cm-scroll {
    position: fixed;
    bottom:20px;
    right:20px;
}

.cm-scroll__link {
    height: 60px;
    width: 60px;
    display:inline-flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}
```

And here's the html part:

```
        <div class="cm-scroll">
            <a uk-tooltip title="Gallery" uk-tooltip title="14852 notes" class="cm-scroll__link" href="#cm-gallery" uk-scroll><span uk-icon="icon: image; ratio: 2"></span></a>
            <a uk-tooltip title="Back to top" class="cm-scroll__link" href="#top" uk-scroll><span uk-icon="icon: chevron-up; ratio: 2"></span></a>
        </div>
```

Here's a screen snippet of the situation:

![scroll](https://cloud.githubusercontent.com/assets/20871500/23798682/ff81a608-05a5-11e7-928c-c6facc65d1c1.png)

**Comment by janschoenherr** [comment]
Has this been resolved?
