### ISSUE TITLE
Request: Have icon compiler look in /custom/my-theme/images/icons/ too

### ISSUE THREAD

**Issue by haydnjames** [uikit/uikit#2509]
Could the compiler look for icons in:

/custom/my-theme/images/icons

As well as:

/custom/icons/
/custom/my-theme/icons

This is because its likely we'll need an images folder within the theme for the images relating to components or referenced across the design. So this way, all image files can be kept together within a theme folder similar to how they are in the main src folders.

**Comment by dasdeck** [comment]
What is your intent here?
Where should the additional Icons go?
Is it just for organizing things in folders?

**Comment by dasdeck** [comment]
Closed for lack of interaction. Please open new one if issue is still relevant.
