### ISSUE TITLE
repeating uk-scrollspy hides elements at "inconvenient position"

### ISSUE THREAD

**Issue by felixheidecke** [uikit/uikit#2511]
### UIkit version
3.0.0-beta.18

### Reproduction Link
![uikit_bug_2017-03-11 12_43_12](https://cloud.githubusercontent.com/assets/12717530/23823017/20205ed2-0659-11e7-802b-47f19f281929.gif)

### Steps to reproduce
use the following in your DOM:
`uk-scrollspy="cls: uk-animation-slide-bottom-medium; repeat: true"`

### What is Expected?
Element should hide if out of sight

### What is actually happening?
Element hides once it reaches the top of the window

**Comment by zzseba78** [comment]
Have similar problem with a element with Y negative position, it dissapears like your example, maybe there is way to correct this...
