### ISSUE TITLE
Tab and accordion elements inside dynamically created modal and offcanvas disappear

### ISSUE THREAD

**Issue by sqvarek** [uikit/uikit#2513]
### UIkit version
UIkit 3.0.0-beta.18

### Steps to reproduce
Create a modal dialog dynamically from js code. When the modal shows up, click on a tab li element. The connected switcher element changes, but the whole tab ul disappears.

While debugging, I managed to trace the line that couses it (uikit.js : 2140):

el.trigger(show ? 'show' : 'hide', [this$1]);

inside Toggable.methods._toggleElement method. I compared this line execution to statically created dialog with tab inside it's body, and the only difference seems to be the _connected field of this$1. In case of dynamic modal it's false and in case of static modal it's true.

### What is Expected?
Clicking on a tab changes the switcher li element, but tab ul element remains in DOM

### What is actually happening?
Switcher li changes, but tab ul element disapperas from DOM

**Comment by janschoenherr** [comment]
Please add a reproduction link. Thanks.

**Comment by davidsonalencar** [comment]
Sorry, the above PR still not good.

I've fixed your issue by the following example:

```
jQuery('#accordion-element').on('hidden', (event) => {
    event.stopPropagation();
});
```
