### ISSUE TITLE
Feature request: configurable icon in Divider/Overlay

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2518]
### UIkit version

3.0.0

### What is Expected?

It would be great if you could set the (SVG) icon to use for a Divider. I think the same goes for the + icon on `uk-overlay-icon`, which is also limited to the default.

**Comment by luxlogica** [comment]
Configuration should also extend to being able to change the colour of the icon, as described in Issue #2710 .

**Comment by saschadube** [comment]
Just set the divider icon color. To do so add the following code to your custom UIkit theme

```less
@divider-icon-color:                            @global-border;
```
The overlay icon automatically take the text color. But you can also set the overlay icon color directly:

```less
.hook-overlay-icon() { color: blue; }
```

**Comment by luxlogica** [comment]
@saschadube This is very useful to know! It might be a good idea to add it to the docs.

Now, is there already a way to change the actual icon? - that is what this issue was about originally. If there is, it's not clear in the docs - or perhaps it is, and I've missed it...
