### ISSUE TITLE
Overthink "uk-" attribute

### ISSUE THREAD

**Issue by kurtextrem** [uikit/uikit#2521]
### UIkit version
3.0.0

### Steps to reproduce
1. Use React

### What is actually happening?
React strips unknown attributes, which makes working with UIKit complicated. Why isn't UIKit using "data-uk-*"?

See here: https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by viocassel** [comment]
Please read docs https://getuikit.com/docs/javascript#component-usage

**Comment by kurtextrem** [comment]
Thank you very much.
