### ISSUE TITLE
uk-icon is not showing any icon in beta 18

### ISSUE THREAD

**Issue by afboteros** [uikit/uikit#2522]
### UIkit version

3.0.0.beta.18

### Reproduction Link
http://codepen.io/afboteros/pen/xqrBdE

### Steps to reproduce
Create an 'a' or 'span' tag on an HTML file, and add uk-icon="icon: name" to it.

### What is Expected?
The tag should have an icon inside, if uk-icon-button class is added to the 'a' tag, a circle shapped button with an icon should be created.

### What is actually happening?
Button is being created without icon inside.

**Comment by ivaskonyan** [comment]
Same problem! (

**Comment by zzseba78** [comment]
Since Beta 18 the icons are managed with js, did you include the **uikit-icons.min.js** file?

**Comment by afboteros** [comment]
Hi, @zzseba78 that was exactly the problem in the codepen, i will take a look on my project, however i think is important to specifiy that change on documentation in the web page, there, just CDN links have uikit-icons.min.js, and i particullary use bower to fetch the library, so i think it would be impossible to me to know that change. Thanks.

**Comment by afboteros** [comment]
I reviewed on my project, now is working, thanks for your help.
