### ISSUE TITLE
offer: add sound to the components... 

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2523]
for Accordion
for Off-canvas
for Button 
...
etc.
)))
optional of course

**Comment by TomS-** [comment]
What?

**Comment by zzseba78** [comment]
Fortunately everything evolved...No need for unwanted annoying sounds

**Comment by bdthemes** [comment]
Hello @AlexandreZaytsev, I think you searching this script: https://loudlinks.rocks/#examples

**Comment by AlexandreZaytsev** [comment]
Yes!!!!!, something like this

**Comment by TomS-** [comment]
Probably not going to happen Alexandre. However, you can use triggers to do what you need to do using the module above.

**Comment by florianletsch** [comment]
Thanks for the suggestion, but this is not something we are considering, please refer to third party scripts such as linked above.
