### ISSUE TITLE
[UIkit 3 Beta 18] Bug in drop area (Upload)

### ISSUE THREAD

**Issue by carlos-duran** [uikit/uikit#2524]
I updated from the beta 12 to beta 18 and the drop area stopped working in **my project** and in the **UIkit docs**.
I don't know what is the problem because it works fine in the test.

### UIkit version

3.0.0 beta 18

### Steps to reproduce
Open [https://getuikit.com/docs/upload#drop-area](https://getuikit.com/docs/upload#drop-area) and try to drop an image.

### What is Expected?
It should upload the image.

### What is actually happening?
The browser opens the image.

## Additional
I would like you to add a new option to set the "headers" in the ajax request like UIkit v2

Thank you very much

**Comment by janschoenherr** [comment]
I think this is resolved?
