### ISSUE TITLE
Match height js error - Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2526]
### UIkit version

3.0.0 Beta 18

### Reproduction Link

https://getuikit.com/docs/utility

### What is actually happening?
Js errors with the match height component ( Confirmed in Firefox and Chrome latests ).
When you resize the browser, the error repeats.
It happens in the UIkit docs too.

![captura de pantalla 2017-03-14 a las 19 02 26](https://cloud.githubusercontent.com/assets/5558563/23924346/0c61ba66-08e9-11e7-9e74-82afe55d2364.png)

![captura de pantalla 2017-03-14 a las 19 07 12](https://cloud.githubusercontent.com/assets/5558563/23924441/7b710056-08e9-11e7-9585-f0198acc6739.png)

**Comment by rocketpages** [comment]
I've been experiencing this error and can reproduce it when using the `uk-height-match="target: > div > .uk-card"` selector. 

These errors also break icons, etc.

**Comment by trk** [comment]
I have same issue on my side. I am losing icons also. If you view website on mobile and if u have this error all icons not working on website.

**Comment by trk** [comment]
If you need a quick solution : 
use : https://getuikit.com/docs/grid#match-height or https://getuikit.com/docs/grid#match-only-one-cell

**Comment by oohnajra** [comment]
I'm having the same issues when using `uk-height-match` **with or without** the `target: SELECTOR` option:

`TypeError: ref is undefined (uikit.js:3282:29)`

When using the `target: SELECTOR` option I get the error straight away, no matter the viewport width. When using `uk-height-match` without the `target: SELECTOR` option I only get the error when the viewport width is less than the small breakpoint setting. For example:

```
<div class="uk-child-width-1-3@s" uk-grid uk-height-match>
  <div>...</div>
  <div>...</div>
  <div>...</div>
  <div>...</div>
  <div>...</div>
  <div>...</div>
</div>
```

This works fine when the viewport is larger than the small breakpoint. But if I resize the window to something smaller than the small breakpoint the error pops up again.

I've implemented a workaround using `class="uk-grid-match"`, but it's not ideal. Would be great to have uk-height-match working without errors.

**Comment by zzseba78** [comment]
Fixed in Beta 19.
