### ISSUE TITLE
Icons not shown with RequireJS

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2530]
### UIkit version

3.0.0-beta.18

### Reproduction Link

http://codepen.io/anon/pen/aJVjVg

### What is Expected?

The icons should show.

### What is actually happening?

None of the icons actually show up.

**Comment by johncarter-oz** [comment]
I have exactly the same problem and my installation is new and still clean, so I have not broken it (honestly - I break things!)
I was using the markup from the documentation by copy and pasting (I thought I was doing silly typos) and I did many examples and they all came up blank!
THEN I was reading another doc on UIKIT and I had this markup which I copied and pasted.

**<a href=""><i class="uk-icon-cog"></i> ...</a>**

And YES this DOES work.
So, I can work with this. Fabien, maybe you can use <i class> also?

**Comment by fabien** [comment]
@johncarter-oz can you point me to the doc or the code you're using? I'm guessing something disappeared in your post above. Thanks!

**Comment by johncarter-oz** [comment]
Sorry, I should provide a [https://getuikit.com/v2/docs/icon.html] to source.
No... it did not disappear... I realized my mistake and was writing this when you replied.
Hope it helps.
Sorry I am new here...

**Comment by fabien** [comment]
@johncarter-oz looks like you're referring to the v2 documentation. Are aren't you using v3?

**Comment by johncarter-oz** [comment]
Yes, I am using V3 but it works for me.
My mark up here keeps getting removed... but at least you got the URL

**Comment by johncarter-oz** [comment]
just means that V3 is backward compatible.... which one would both hope and expect.
I am new to UIKIT but I am loving it.

**Comment by Joshua-Cody** [comment]
I'm not getting icons, either. Not in chrome, not in IE. Not in V2 and not in V3.

<div>Dude, where's my icon?<span uk-icon="icon: download"></span></div>

<span class="uk-margin-small-right" uk-icon="icon: check">Dude, where's my icon?</span>

<a href="www.lemonde.fr" uk-icon="icon: heart">Dude, where's my icon?</a>

**Comment by davidlb** [comment]
Same probleme here :(

**Comment by janschoenherr** [comment]
A quick solution would be to bundle UIkit + the icons file into a single file. That would probably solve the issue.

**Comment by helixic** [comment]
Same issue. I manually copied the SVGs from uikit-icons.js into uikit.js, then added those to the icons list to get it working. Is there some automated bundling process that should be done instead?

**Comment by diramazioni** [comment]
I have the same issue packing all into one js with webpack

**Comment by fabien** [comment]
Someone (@carlos-duran) on gitter posted this solution, which is supposed to work (haven't tried myself, yet):

```javascript
const UIkit = require('uikit')
const Icons = require('uikit/dist/js/uikit-icons')
UIkit.use(Icons);
```

**Comment by razvanioan** [comment]
It seems that the icons do not initialize if the resource JS file is loaded somehow async !
How can we manually initialize the icons in a callback ?

I have my own custom / optimized JS async loader which works as expected (respects dependency and order), but the icons do not work in this case.

**Comment by razvanioan** [comment]
Here's how I async load UIkit & UIkitIcons for my website.
How can I initialise / render icons after everything is loaded ?

As you can see, the `uk-icon` tagged elements will have injected `uk-icon` class but no SVG !

https://jsfiddle.net/razvanioan/rnrL38gy/3/

**Comment by razvanioan** [comment]
I don't know yet why, but I think that the cause is: `connected()` method of `SVG` component does not fire (properly) ... 

I've struggled to find a working solution / hack which I execute in the UIkitIcons load callback !

```
$("[uk-icon]").each(function(idx, el){
	icon = UIkit.icon(el); 
	icon.$el.append(icon.getIcon().childNodes[0].cloneNode(true))
})
```
https://jsfiddle.net/razvanioan/rnrL38gy/4/

**Comment by itfinally** [comment]
Hello, I have same problem here, using UIKit@3.0.0-beta.27, JQuery@3 and RequireJS.
and loading JQuery, UIKit, UIKit-Icons by RequireJS but icon is not work.

and then I try to load UIKit-Icons when UIKit loading complete, still not work.
so let my guess, is it just scan once for document tree when UIKit core loading complete?

if just scan own tag when component added to UIKit, and UIKit core just provide some tools manager all components. 
it maybe can solve this problem.  ( maybe UIKit does it too now?

**Comment by razvanioan** [comment]
@itfinally I also haven't got the time to investigate it, but only created the `hack` above which is working fine for me: check the fiddle

I will exclude it when / if the core framework will work as expected ;)

**Comment by davidlb** [comment]
Still not working with requirejs --> https://codepen.io/anon/pen/qXJamY

**Comment by fabrice-dresscodes** [comment]
Example in Magento 2 

var config = {
    "paths": {
        "uikit":"js/uikit",
        "uikit-icons":"uikit-icons.min"
    },
    "shim": {
        "uikit": { "exports": "UIkit" },
        "uikit-icons": { "exports": "Icons" },

    }
};

**Comment by fabrice-dresscodes** [comment]
Sous Magento 2, j'ai réussi à intégrer les icônes

Fichier requirejs-config.js

> var config = {
    "paths": {
        "flatpickr": "js/flatpickr",
        "flatpickr-fr": "js/flatpickr-fr",
        "uikit":"js/uikit",
        "uikiticons":"js/uikit-icons"
    },
    "shim": {
        "flatpickr": { "exports": "Flatpickr" },
        "flatpickr.fr": ["flatpickr"],
        "uikit": { "exports": "UIkit" },
        "uikiticons": { "exports": "Icons" }

    }
};

>

**Comment by dimitrilongo** [comment]
@fabrice-dresscodes 
hello i try to load uikit.js in Magento 2 but with no succes, could you paste your requirejs ?

this is mine :  
````
var config = {
    map: {
        '*': {
            'rowBuilder':             'Magento_Theme/js/row-builder',
            'toggleAdvanced':         'mage/toggle',
            'translateInline':        'mage/translate-inline',
            'sticky':                 'mage/sticky',
            'tabs':                   'mage/tabs',
            'zoom':                   'mage/zoom',
            'collapsible':            'mage/collapsible',
            'dropdownDialog':         'mage/dropdown',
            'dropdown':               'mage/dropdowns',
            'accordion':              'mage/accordion',
            'loader':                 'mage/loader',
            'tooltip':                'mage/tooltip',
            'deletableItem':          'mage/deletable-item',
            'itemTable':              'mage/item-table',
            'fieldsetControls':       'mage/fieldset-controls',
            'fieldsetResetControl':   'mage/fieldset-controls',
            'redirectUrl':            'mage/redirect-url',
            'loaderAjax':             'mage/loader',
            'menu':                   'mage/menu',
            'popupWindow':            'mage/popup-window',
            'validation':             'mage/validation/validation',
            'welcome':                'Magento_Theme/js/view/welcome',
            'breadcrumbs':            'Magento_Theme/js/view/breadcrumbs',
            'criticalCssLoader':      'Magento_Theme/js/view/critical-css-loader',
            'jquery/ui':              'jquery/compat',
            'jquerySteps':            'js/jquery.steps.min',
            'pannellum':              'js/pannellum',
            'owl-carousel':           'js/owlcarousel/owl.carousel',
        }
    },
    deps: [
        'jquery/jquery.mobile.custom',
        'mage/common',
        'mage/dataPost',
        'mage/bootstrap'
    ],
    paths: {
        uikit:"js/uikit/uikit",
        uikiticons:"js/uikit/uikit-icons"
        },
    shim: {
        uikit: { 'exports': 'UIkit' },
        uikiticons: { 'exports': 'Icons' }
    },
    config: {
        shim: {
            'bootstrap': {
                deps: ['jquery']
            },
            'jquerySteps': {
                deps: ['jquery']
            },
            'uikit': {
                deps: ['jquery']
            },
        },
        mixins: {
            'Magento_Theme/js/view/breadcrumbs': {
                'Magento_Theme/js/view/add-home-breadcrumb': true
            },
            'jquery/ui-modules/dialog': {
                'jquery/patches/jquery-ui': true
            }
        }
    }
};
````
uikit are in theme folder under web /js/uikit/uikit.js

Thanks
