### ISSUE TITLE
Drop doesn't show after click, on Hover button. 

### ISSUE THREAD

**Issue by bharatpatil** [uikit/uikit#2532]
### UIkit version

3.0.0

### Reproduction Link

https://getuikit.com/docs/drop

### Steps to reproduce

1.  Goto first preview button
2.  hover over Hover button
3.  click on Hover button
4.  move mouse out of Hover button area
5.  hover over Hover button

### What is Expected?
Drop should be shown on hovering over Hover button

### What is actually happening?
Drop doesn't show up on hovering over Hover button after clicking on Hover button.

**Comment by janschoenherr** [comment]
Please see https://github.com/uikit/uikit/issues/2562. Thanks,
