### ISSUE TITLE
Lightbox UIkit Tests - No JavaScript Options

### ISSUE THREAD

**Issue by mike-eason** [uikit/uikit#2535]
### UIkit version

3.0.0

### Reproduction Link

[LightBox Tests](https://getuikit.com/assets/uikit/tests/lightbox.html)

### Steps to reproduce
Just open up the page and scroll to the bottom.

### What is Expected?
**JavaScript Options** is blank, is this intended?

I can't find any documentation for `LightBox`, however whether or not there **are** JavaScript options in v3.0.0 I don't know. I'm expecting that if there are **no** JavaScript options then this table is either omitted or it is noted somewhere before or after the table.

### What is actually happening?
**JavaScript** options is blank.

**Comment by bdthemes** [comment]
Hi @mike-eason , It's still on development queue and not finished yet so you can't use at this time. please wait for it.

**Comment by janschoenherr** [comment]
This still under construction. We'll add them later, once the options are fix.
