### ISSUE TITLE
uk-height-max-large / uk-max-height-large mixed up

### ISSUE THREAD

**Issue by kvnxdev** [uikit/uikit#2538]
**UIkit version**: v3.0.0-beta.18
**Jumplink**: [uikit/src/less/components/utility.less:227](https://github.com/uikit/uikit/blob/develop/src/less/components/utility.less#L227)

## Issue

Today I wanted to use the class `uk-max-height-large` (doc), but I found out the class is named in utility.less:227 `uk-height-max-large`. For me the doc says the correct class name but I am not sure which way you want to go. Anyway, one of them should be fixed.

#### Offtopic

I just wanted to say thank you for this awesome framework and your hard work!

**Comment by florianletsch** [comment]
Thanks, I've fixed it in the docs repository. https://github.com/uikit/uikit-site/commit/0a38094e90342f573bf5cef9d7f2bfc91f79cdaa
