### ISSUE TITLE
PSD file for Mockup

### ISSUE THREAD

**Issue by lukasborawski** [uikit/uikit#2556]
Hey, i'm not sure is this is a issue, but is there any PSD file with all UiKit elements for quick mockups - for graphic designers who want's to use it in their projects? Thanks for help.

**Comment by peterbrinck** [comment]
The only one I know of is this one, made by @Intiligent 
But it's for Uikit2

https://github.com/uikit/uikit/issues/1409

**Comment by florianletsch** [comment]
Correct. We also like to collect such resources here: https://github.com/uikit/awesome-uikit

Maybe someone would like to create a PSD for UIkit 3 and add it to the resources list?

**Comment by lukasborawski** [comment]
OK, thx for the info, if you want you can now close the issue. Or maybe someone will attempt to create that kind of set, file, kit, whatever. Cheers.

**Comment by kubida** [comment]
PSD template - Elements and Grid template in a single Photoshop file (using UIkit 2)
https://www.dropbox.com/s/1957hv6rv21ck6p/Uikit-PSD.zip?dl=0&file_subpath=%2FUikit-PSD
https://www.dropbox.com/sh/nbzg71dtl5d1ba5/AABW5J0KUdWD_GJuZATNMhvVa

I would be very grateful if you will be the same for Version 3.0.0-Rc.14
