### ISSUE TITLE
Upload don't send the file request to server

### ISSUE THREAD

**Issue by mvanvu** [uikit/uikit#2559]
**Upload just send image files to server not any file type such as .zip...**
Thanks for great UIkit framework, I am really love it. The current time I got some issue bellow.
1. I used to Joomla! controller to handle upload file and use JInput->files->get('files'). Any images work fine, but the other of file types like abc.zip nothing to do. Also the UI propgress bar does not the same with test demo, the progress bar is only correct with a single file not multiple files. 

2. I know the beta version was be developing, but I just pull the latest develop branch into local and run with custom prefix and scope mode. It seem the modal doesn't work.

**Comment by janschoenherr** [comment]
Needs reproduction link. By default there is no mime type filtering in the upload component.

**Comment by mvanvu** [comment]
I used allow params like: zip|doc|docx|pdf|xls|txt|gz|gzip|rar|jpg|gif|tar.gz|xlsx|pps|csv|bmp|epg|ico|odg|odp|ods|odt|png|ppt|swf|xcf|wmv|avi|mkv|mp3|ogg|flac|wma|fla|flv|mp4|wav|aac|mov|epub

Sorry the production is still developing on localhost
