### ISSUE TITLE
Grid Divider does not work properly for RTL

### ISSUE THREAD

**Issue by javaheripur** [uikit/uikit#2561]
### UIkit version

3.0.0-Beta 18

### Reproduction Link

https://codepen.io/javaheripur/pen/pexpwJ

**Comment by javaheripur** [comment]
No fix yet?

**Comment by janschoenherr** [comment]
I believe this is fixed in the develop branch. Can you confirm?

**Comment by javaheripur** [comment]
I just checked it again. Bug is still there.

**Comment by javaheripur** [comment]
Still no fix?

**Comment by janschoenherr** [comment]
After revisiting this issue. You'll have to set the documents _dir_ attribute. For UIkit it doesn't suffice to set the direction via css.

It seems to be the recommended way: https://stackoverflow.com/a/5375907
