### ISSUE TITLE
Bug with dropdown menu's when in center

### ISSUE THREAD

**Issue by peteringram0** [uikit/uikit#2562]
If you hover over the title at first it works, if you click on the parent remove the hover then hover over it again the menu appears off canvas. This is happening on the demo page. Its hard to show in the screen grab as you cant see the menu.

<img width="523" alt="screen shot 2017-03-28 at 21 22 49" src="https://cloud.githubusercontent.com/assets/6588942/24425662/e5895448-13fc-11e7-8a08-5df1c1ad721d.png">

<img width="398" alt="screen shot 2017-03-28 at 21 23 15" src="https://cloud.githubusercontent.com/assets/6588942/24425669/e79f500c-13fc-11e7-9c16-8deaaf3dc9e1.png">

**Comment by jbsanto6** [comment]
I just checked and I have the same outcome. I'm going take a shot at this.

**Comment by janschoenherr** [comment]
Fixed with e1e29eb4b9f84893a54be39c3279c4573db1ef40. Thanks.
