### ISSUE TITLE
UiKit 2.27.2: Problem with slider when used .uk-grid + infinite:false

### ISSUE THREAD

**Issue by AlekVolsk** [uikit/uikit#2564]
### UIkit version
2.27.2

### Reproduction Link
https://getuikit.com/v2/docs/slider.html#gutter

### Steps to reproduce, What is Expected, What is actually happening?
In the slider when using uk-grid to separate the slide and the parameter {infinite: false}, when you scroll the slider to the end on the right there is additional scrollable block width equal to the grid gutter. This effect is well demonstrated in the documentation example is available at the link https://getuikit.com/v2/docs/slider.html#gutter

**Comment by AlekVolsk** [comment]
Video demonstrating bug http://arsp-test.ru/slider_bug.webm

**Comment by m0yP** [comment]
Indeed it's there! There were some bugs left on v2 but they closed them all in favor of the still-in-development v3. 

I'm just finishing a site that has to have v2 since it goes directly live and I just see tons of bugs on v3, though.

**Comment by AlekVolsk** [comment]
Unfortunately, v3 is not yet a slider and when the slider appears. you have to use v2. And while the v3 does not have a stable slider really want to have bugfixes v2.

**Comment by saschadube** [comment]
The [Slider component](https://getuikit.com/docs/slider) is now available in UIkit 3.
