### ISSUE TITLE
Uikit 3.18 offcanvas dissmis swipe to close

### ISSUE THREAD

**Issue by Siton-Systems** [uikit/uikit#2568]
### What is Expected?
In uikit2 after you open the off canvas -  now on swipe left on the overlay area close the offcanvas and give more feel of native app

Now only click on the overlay (or close btn) close offcanvas :( little anoying and less mobile freindly ui/x

**Comment by janschoenherr** [comment]
This has been added in beta 19. Thanks.

**Comment by zzseba78** [comment]
The Offcanvas doesn't close on swipe on Android 6 - Chrome and Opera. It works on Firefox.
