### ISSUE TITLE
Beta 19 - Modal fail

### ISSUE THREAD

**Issue by mvanvu** [uikit/uikit#2569]
Javascript: `pfUIkit.modal("#my-modal").show();	`
`<div id="my-modal" class="pf-modal pf-modal-full" pf-modal="container: #page">...</div>`

P/s: I also build UIKIT with custom prefix (pf) and scope mode

![selection_009](https://cloud.githubusercontent.com/assets/5796168/24574549/b4de8150-16be-11e7-9207-9478dce6984f.png)

**Comment by KarolBuchta** [comment]
I had the same problem while using UIkit together with typescript and webpack, and the npm package. The error comes from uikit/dist/js/uikit.js:2256 toJQuery -> toJQuery$1.

I changed this and the error disappeared, but the modal still did not work.

The only method i could make it work in webpack together with TS was to expose jQuery as well as UIkit to the global namespace, like so:

`
  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js"],
    alias:{
      'uikit-icons': path.resolve(__dirname, 'node_modules/uikit/dist/js/uikit-icons.js'),
    }
  },

  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    })
  ],

  module: {
    loaders: [
      // All files with a '.ts' or '.tsx' extension will be handled by 'ts-loader'.
      { test: /\.tsx?$/, loader: "ts-loader" },
      { test: require.resolve('jquery'), loader: 'expose-loader?jQuery!expose-loader?$' },
      { test: require.resolve('uikit'), loader: 'expose-loader?UIkit!expose-loader?UIkit' }
    ]
  }
`

@mvanvu This does probably not solve your problem, as you would like to use everything scoped, but it points into the same direction, as i have seen the exact same error message.

**Comment by mvanvu** [comment]
@janschoenherr when you closed the issue, modal work find now, but lightbox is not. :(
