### ISSUE TITLE
BUG ScrollSpy

### ISSUE THREAD

**Issue by Uranbold** [uikit/uikit#2570]
### Reproduction Link
Codepen Demo -> http://codepen.io/Uranbold/pen/LWqMQN
Also please check the CSS section i have described what's wrong in this section.

### Steps to reproduce
ScrollSpy + Animation need to improve. If it's Added Animation with Delay then whole Elements need to wait and works with Delay and wait for them it's no matter already Viewport.

### What is Expected?
Scrollspy should wait all First or Second or no matter what Prev Row Element Animation and then work with Animation Delay.

### What is actually happening?
Scrollspy is not waiting for First or Second Row Animation finish. If it's in Viewport then it will display animation.

Sorry for the bad English i am low at grammer. But if you have question then i can describe even more understand able.

@saschadube I created the Issue :)

Thanks guys for awesome Framework I love it ;)

**Comment by zzseba78** [comment]
Well, i think that is the desired effect, imagine that you have 10 rows ( two items for row, 20 items  ) and you scroll fast... the content will not show, because it's waiting for the top items to appear. And content not showing it's a problem.

**Comment by Uranbold** [comment]
Hello,

@zzseba78 I think it needs some option or Need tweak Where to Put the Animation. Example:

Imagine i have the 10 Row and i put the Animation on Entire 10 Row Container(Outside div) element with delay then it should wait for them, If i put the Animation on Each 10 Row (Each Row Container div) then animation will not wait for Previous Row.

That's why i am talking about it. I don't think it's user friendly. I think it should work where Animation inserted on Each row or Entire Container for that rows.

Thanks for replying.

**Comment by janschoenherr** [comment]
This is resolved in latest RC.
