### ISSUE TITLE
Preventing a modal from showing by using 'beforeshow' event leaves behind a uk-modal-page class

### ISSUE THREAD

**Issue by Vandaahl** [uikit/uikit#2574]
### UIkit version
Latest 3.0 beta

### Reproduction Link
http://codepen.io/anon/pen/LWaRLV

I'm trying to prevent a particular modal from showing using the 'beforeshow' event as outlined in the docs. However, when I do this, the page can no longer be interacted with (no scrolling or clicking on links). A uk-modal-page class gets added to the html element: if I remove this, the problem goes away. Shouldn't this class NOT be added when preventing the modal from showing? Here's how I do it, maybe I'm doing it wrong?

`
$('#editor-choice').on({
        'beforeshow': function() {
                return false; // prevent modal from opening
        }
    });`

**Comment by janschoenherr** [comment]
Thanks, resolved with 737606d0d2cad4c1aeef97191b50304467f6ece5
