### ISSUE TITLE
distinguish between versions

### ISSUE THREAD

**Issue by diomed** [uikit/uikit#2577]
please comment versions of ui-kit in the start of file,
so people could easily see which one is used.

**Comment by florianletsch** [comment]
You mean as the header of the CSS files? I think that's a good idea, we can consider that.

Note that you can already get the current version on a JS level. It's in the `UIkit.version` object. See screenshot. 

![image](https://cloud.githubusercontent.com/assets/1116784/24802261/9593b7d2-1ba7-11e7-8561-63eab2bc4373.png)

**Comment by diomed** [comment]
I think this already existed in older versions, not sure why is removed at all. 
Since it shouldn't be.

**Comment by dasdeck** [comment]
added version string in:
3c17799f99b54868fc24ab5c85c39eba099a8276
