### ISSUE TITLE
Scroll component not working inside Offcanvas using .uk-offcanvas-content 

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2582]
### UIkit version

3.0.0-beta.20

### Reproduction Link

https://codepen.io/zzseba78/pen/qrGWab
### Steps to reproduce
Open Offcanvas nav clicking in the Click Me button at the navbar.
Then, click on CONTACT US offcanvas menu item, the offcanvas bar closes but it doesn't scroll to the section.
### What is Expected?
That the page scrolls to the Contact us section.
### What is actually happening?
It doesn't scroll to the section. **It seems that the `.uk-offcanvas-content ` affect this functionality**, because **if you remove the `.uk-offcanvas-content ` wrapping tag it works perfect.**

Scroll in Offcanvas it's vital for one page mini sites or Landing pages or specific product page, so the user can navigate it.

Thank you.

**Comment by janschoenherr** [comment]
That currently only works without the overlay.

**Comment by zzseba78** [comment]
Hi! You are right, it's not the `.uk-offcanvas-content`... thanks, i will remove it
