### ISSUE TITLE
*** Feature Request *** Responsive heading sizes.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2583]
Heading on Desktop, Tablet and Mobile are not the same, and almost always we have to adapt the proportions of the headings, mainly on mobiles where the difference is critical.

Maybe it's good to have responsive heading sizes ( like Heading component ) in the Base Component, to be able to create two font variations, one for mobile and one for beyond.

```
@base-h1-font-size:                           @global-xlarge-font-size;
@base-h1-font-size-l:                         @global-xxlarge-font-size;
@base-h1-line-height:                         1.25;
@base-h1-line-height-l:                       1.2;
@base-h2-font-size:                           @global-large-font-size;
@base-h2-font-size-l:                         @global-xlarge-font-size;
@base-h2-line-height:                         1.3;
@base-h2-line-height-l:                       1.25;
....
```
Thanks.

**Comment by askaoru** [comment]
Struggled with this recently myself. It would be really great to have a responsive heading. My idea of what i'd like to have is just something like `.uk-h1-responsive` `.uk-h2-responsive` and so on in addition to the usual `.uk-h1` and the others.

I believe this is something uikit should have at it's core to be a fully mobile-friendly framework

**Comment by zzseba78** [comment]
Nice idea, in order to make optional the header resizing. Agree

**Comment by andreasba** [comment]
Hi there,

I was just wondering if there is any news on this?

Thanks
Andreas

**Comment by BernhardBaumrock** [comment]
I support this request! It would also be great (or maybe better) to have support for responsive headline classes:
```
<h1 class="uk-h3 uk-h2@m uk-h1@l">My awesome headline</h1>
```
I'm using @carlos-duran 's solution now. If anybody also needs it and wants to copy/paste, here you go:
```
/* responsive headlines */
h1, .uk-h1 {font-size: @base-h1-font-size*0.8;}
h2, .uk-h2 {font-size: @base-h2-font-size*0.8;}
h3, .uk-h3 {font-size: @base-h3-font-size*0.8;}
h4, .uk-h4 {font-size: @base-h4-font-size*0.8;}
h5, .uk-h5 {font-size: @base-h5-font-size*0.95;}
h6, .uk-h6 {font-size: @base-h6-font-size;}
@media(min-width: @breakpoint-small) {
  h1, .uk-h1 {font-size: @base-h1-font-size*0.9;}
  h2, .uk-h2 {font-size: @base-h2-font-size*0.9;}
  h3, .uk-h3 {font-size: @base-h3-font-size*0.9;}
  h4, .uk-h4 {font-size: @base-h4-font-size*0.9;}
  h5, .uk-h5 {font-size: @base-h5-font-size;}
  h6, .uk-h6 {font-size: @base-h6-font-size;}
}
@media(min-width: @breakpoint-medium) {
  h1, .uk-h1 {font-size: @base-h1-font-size;}
  h2, .uk-h2 {font-size: @base-h2-font-size;}
  h3, .uk-h3 {font-size: @base-h3-font-size;}
  h4, .uk-h4 {font-size: @base-h4-font-size;}
  h5, .uk-h5 {font-size: @base-h5-font-size;}
  h6, .uk-h6 {font-size: @base-h6-font-size;}
}
```

**Comment by zzseba78** [comment]
Closing this since UIkit rc implement this for h1 and h2.
