### ISSUE TITLE
Layout errors with Sticky and Tab/Switcher on older Browser

### ISSUE THREAD

**Issue by filly82** [uikit/uikit#2584]
### UIkit version

3.0.0-beta.20

on the left side it's a newer browser, on the right side an older one (in this case, android 4 browser)

i have a android emulator for testing purposes, so if there is anything i can check just tell me.
there are no javascript errors in the console

![image 1](https://cloud.githubusercontent.com/assets/4948973/24789276/8accc4fe-1b72-11e7-9c36-529d43632c08.png)

**Comment by Uranbold** [comment]
Switcher seems not working on Horizontal.

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
