### ISSUE TITLE
uk-sticky making navbar width unresponsive

### ISSUE THREAD

**Issue by askaoru** [uikit/uikit#2586]
When using uk-sticky on navbar, the navbar width become unresponsive and unable to adapt to the screen size properly. This will become an issue on a single page apps when switching from page with long content (have scrollbar) to short content page (without scrollbar). 

### UIkit version
3.0.0-beta.21

### Reproduction Link
https://jsfiddle.net/oz4qgehL/6/

### Steps to reproduce
Using uk-sticky on a navbar, switch from a long content page to a short content page without page reload (ajax loaded content / single page app)

### What is Expected?
The navbar width will adapt to the screen size when switching from a page long content page to a short content page (page with scrollbar to page without scrollbar)

### What is actually happening?
The navbar witdh does not adapt and either creating a gap when scrollbar is removed, or covering a part of the navbar when scrollbar is present

**Comment by CoderBrad** [comment]
I'm on 3.0.0-beta.42 and this still seems to be quite an issue, although they way I'm encountering it is different than the OP's situation.

To start, I have a hidden left off-canvas and in the main content page I have a button and call a function to show the off-canvas. In the same function I apply a margin-left: 250px to the main content area. When that happens, the sticky navbar sort of pushes some of the way and resizes some of the way. When I click my button to close the off-canvas and remove the main content (margin-right: 0px), the sticky navbar pulls back to the left side of the browser but doesn't resize back to 100% width.

One interesting observation though... after sizing, and the navbar is still messed up... if I mouse over the navbar for a second or two, it seems to get some sort of event or notification or something, and will snap back to the proper size.

**Comment by phoerious** [comment]
I did not have this problem with 3.0.0rc20, but it seems to be back with the current dev branch.

**Comment by gabyferman** [comment]
Just installed 3.0.0-rc.25 wth yarn, and I'm getting this error.

**Comment by janschoenherr** [comment]
This seems to be resolved. If the issue persists, please comment.
