### ISSUE TITLE
Dropdown Bug

### ISSUE THREAD

**Issue by kultz** [uikit/uikit#2587]
I just installed UIKIT 3 beta20, And i've noticed that everything that has dropdown feature shakes on click or hover i mean it's like open>close>open in a moment.
Here is the gif:
![apr-08-2017 16-08-11](https://cloud.githubusercontent.com/assets/7747199/24828597/a66ab1c2-1c75-11e7-8a57-05e616a9da80.gif)

Browser: Safari Version 10.0 (12602.1.50.0.10)

**Comment by janschoenherr** [comment]
This should be resolved in beta 21. Thanks.
