### ISSUE TITLE
*** Feature Request *** option to omit auto DOM handling

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2588]
Currently, UIKit will observe all DOM elements and apply components accordingly. However, I'd like to prevent certain nodes from automatically being handled by this behavior. So I'm thinking along the lines of a class that can be added to such elements: `uk-ignore`.

More specifically, I'm using RiotJS, which allows parts of a component to be yielded. These yielded segments of HTML will be handled by UIKit twice. Most notably, I'm seeing `uk-icon` embed the `svg` multiple times.

The issue is similar to: https://github.com/uikit/uikit/issues/2519 - however, the suggested workaround is not an option for RiotJS, unless UIKit allows one to manually initialize the DOM observation.

**Comment by fabien** [comment]
Another idea would be to have a specific prefix, which would only be observed after explicitly being enabled. So instead of `uk-*` you'd write `defer-uk-*` and enable it later:

```
UIKit.observe('defer'); // optionally specify the prefix of choice
```

This would be a flexible approach, that is also fully backwards compatible.

**Comment by fabien** [comment]
Also related: https://github.com/uikit/uikit/issues/2357

**Comment by b3taboy** [comment]
Any news on this or workaround ?

**Comment by janschoenherr** [comment]
For VueJs there is a nice workaround by using letting Vue itself set the attribute:

<span :uk-icon="table"></span>

There is most likely something similar for RiotJS?

Other than that, UIkit supports the attribute `uk-no-boot` which will prevent the automatic booting on this element and below.

**Comment by janschoenherr** [comment]
I believe this to be resolved.

**Comment by sly7-7** [comment]
@janschoenherr Sorry to bother you, but if I understand, there is no more this escape-valve (the `uk-no-boot` attribute) ?
I'm working on pretty bug ember.js application, in which I have a large svg table, with no need of ui-kit at all.
I encounter perf bottleneck, and find out in this case, that uikit spends 1 second in the "mutation observer" thing, which represents nearly the half of computation time.

![Capture d’écran 2020-11-19 à 17 01 58](https://user-images.githubusercontent.com/1826661/99690926-f0df0a80-2a88-11eb-87b3-4841733eb58c.png)

How could I mitigate this ?
