### ISSUE TITLE
*** Feature Request *** dynamic uk-icon changes

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2589]
### What is Expected?

Any DOM-level updates to  the`uk-icon` (or `data-uk-icon`) attribute should swap the icon accordingly.

### What is actually happening?

Currently, changing the `uk-icon` attribute value from javascript or a library that manipulates the DOM (RiotJS, ...) does not replace the `<svg>` within.

**Comment by fabien** [comment]
This appears to be fixed: http://codepen.io/anon/pen/mmrEbw

However, I cannot make the js-only approach `UIkit.icon(elem, { icon: 'world' })` work at all.

**Comment by acseven** [comment]
+1 couldn't change the icon using the JS-only approach.

**Comment by janschoenherr** [comment]
Resolved with fa81fee8cf396012805a4c139e891a7d858454fb
