### ISSUE TITLE
UIkit3 docs

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#2590]
Hi guys. Is it possible add docs folder of UIKit 3?
I want create own style guide look like on documentation with code example.
It present in v2/master https://github.com/uikit/uikit/tree/v2/master/docs but not in v3.
Dear UIkit team can you add docs folder to repository or create another branch only for docs or send me to email?)
Thanks.

**Comment by askaoru** [comment]
@Intiligent the getuikit.com site source is available on this repo https://github.com/uikit/uikit-site/ .
I believe this is what you're looking for?

**Comment by Intiligent** [comment]
@askaoru thanks. Yes, that's what I was looking for. Maybe you know how run this puzzle?
Page in md format. How convert md to html and made from its static html page. Isset some instruction for this?

**Comment by Intiligent** [comment]
oh, sorry i was inattentive.
Run `npm run setup` after cloning. Its ok)

**Comment by askaoru** [comment]
Glad that it works out for you. If it is resolved you should close this issue.
