### ISSUE TITLE
flickering on sticky on up + slide-top animation

### ISSUE THREAD

**Issue by darim92** [uikit/uikit#2591]
### UIkit version

3.0.0-beta.20

Browser: Version 57.0.2987.133 (64-bit)

Slide-top animation is flickering on scroll up.

### Reproduction Link

http://codepen.io/anon/pen/RpXPJG

**Comment by askaoru** [comment]
the issue seems possibly related to this https://github.com/uikit/uikit/issues/2587

**Comment by janschoenherr** [comment]
This should be resolved in beta 21. Thanks.

**Comment by dimative** [comment]
Still this bug not fixed.

**Comment by janschoenherr** [comment]
@dimative it is, you'd have to check with a more up to date version.
