### ISSUE TITLE
window scollbar is lost after opening modal 

### ISSUE THREAD

**Issue by michelollivier** [uikit/uikit#2594]
Hi,

It breaks my pages ...

fixed using, on modal hide :
```
document.documentElement.style.overflow = 'auto';  // firefox, chrome
document.body.scroll = "yes";
```

Please fix it;

Regards
Michel

**Comment by uotsumi** [comment]
Hi,
I fixed it using 
`$('html').removeClass('uk-modal-page');`

**Comment by janschoenherr** [comment]
Has this been resolved? If not, please add a reproduction link.
