### ISSUE TITLE
Navbar Component - Navbar layout breaks if only .uk-navbar-center is visible

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2597]
### UIkit version

3.0.0-beta.21

### Reproduction Link

http://codepen.io/zzseba78/pen/EmxXbq
### Steps to reproduce
Resize down the width of the browser window, you will see that if left and right nav are hidden ( center nav is visible ), the navbar breaks.
### What is Expected?
Navbar don't break his layout.
### What is actually happening?
Navbar break his layout.

**Comment by zzseba78** [comment]
Still happens in latest Beta 27.

**Comment by gazley** [comment]
I am having a similar issue. I have a uk-navbar-center and a uk-navbar-left. In this case, I see the same behaviour as OP where the center menu is positioned absolutely at 50%/50%. If I removed the uk-navbar-left definition, the uk-navbar-center behaves as expected.

**Comment by zzseba78** [comment]
@gazley Great!!

**Comment by garethwarry** [comment]
I have the same issue.
`<div class="uk-light uk-preserve-color">
    <nav class="uk-navbar-container comet-nav" uk-navbar>
         <div class="uk-navbar-left uk-visible@m">
            <a class="uk-navbar-toggle" uk-navbar-toggle-icon href=""></a>
        </div>
        <div class="uk-navbar-right">
            @Html.ActionLink(serverName, "Index", "Home", null, new { @class="uk-navbar-item uk-logo" })
        </div>
    </nav>
</div>`
