### ISSUE TITLE
interested in [official] SASS port of uikit

### ISSUE THREAD

**Issue by m5o** [uikit/uikit#260]
Hey uikit!

Are you guys interested in an SASS port for this project?

Originally I am a bootstrapper, but I like the style and structure of uikit.

I am not new to this, previously I was one of the [contributor](https://github.com/jlong/sass-bootstrap/graphs/contributors) of the [jlong/sass-bootstrap](https://github.com/jlong/sass-bootstrap) project. Did the translation for many bootstrap 2.x and 3.x versions. 

I don't know, if a project-fork is the right decision, as the guys did for [twbs/bootstrap-sass](https://github.com/twbs/bootstrap-sass). Maybe a `scss` directory structure inside this repo would be fine. With some smart conversion scripts around. But that is to much detail for the moment.

What are your thoughts..?

Best,
m5o

**Comment by nick-bull** [comment]
Hey guys, would be great if the Sass fork was more accessible - this is the only place I've found a project contributor link to an "official" Sass version of UIKit, and Googling "UIKit Sass | UIKit Scss", while this page is the second link, this page's title/the repo's name doesn't give much away.

Perhaps you could add a link in the markdown, would make it much easier to find!

**Comment by malles** [comment]
http://getuikit.com/docs/documentation_less-sass.html should do, I think

**Comment by nick-bull** [comment]
@malles ahaha... Yes i think a whole page is more than okay... my bad, no idea why that isn't the first result for me.

**Comment by malles** [comment]
My Google is UIkit biased, I have a history there

**Comment by vuchl** [comment]
@malles' Uikit fu is strong :D

**Comment by yhaow** [comment]
+++1

**Comment by florianletsch** [comment]
@yhaow +1 for what? The sass port is available already :) http://getuikit.com/docs/documentation_less-sass.html

**Comment by cho-is** [comment]
+1 for the sass port and another +1 for you guys!   : )
