### ISSUE TITLE
Generate JS files separately

### ISSUE THREAD

**Issue by reardestani** [uikit/uikit#2604]
Is it possible to have a new command to generate the JS files separately like UIkit 2. Currently it compiles the core ones in a uikit-core.js file and the rest in components folder.

We need to have complete control over the files that we want to load.

### UIkit version

3.0.0-beta.21

### What is Expected?
After the running the new command, it's expected to generate following files for JS in dist folder for example.
```
js
  componets
    ...
  core
   ...
  uikit-core.js
  uikit.js
```

**Comment by reardestani** [comment]
### Update
In the `build.js` file, I modified the codes as below and it's generating the files. Wondering if possible, it can be added to the official UIkit? 

```
var fs = require('fs');
var path = require('path');
var glob = require('glob');
var util = require('./util');
var concat = require('concat');

util.write('dist/icons.json', util.icons('{src/images,custom}/icons/*.svg')).then(() =>

    Promise.all([

        util.compile('src/js/uikit-core.js', 'dist/js/uikit-core', ['jquery'], {jquery: 'jQuery'}),
        util.compile('src/js/uikit.js', 'dist/js/uikit', ['jquery'], {jquery: 'jQuery'}, undefined, undefined, true),
        util.compile('src/js/icons.js', 'dist/js/uikit-icons', ['jquery'], {jquery: 'jQuery'}, 'icons', {icons: 'dist/icons'}),
        util.compile('tests/js/index.js', 'tests/js/test', ['jquery'], {jquery: 'jQuery'}, 'test')

    ]
    .concat(glob.sync('src/js/components/**/*.js').map(file => util.compile(
        file,
        `dist/${file.substring(4, file.length - 3)}`,
        ['jquery', 'uikit'],
        {jquery: 'jQuery', uikit: 'UIkit'},
        path.basename(file, '.js')
    )))
    .concat(glob.sync('src/js/core/**/*.js').map(file => util.compile(
        file,
        `dist/${file.substring(4, file.length - 3)}`,
        ['jquery', 'uikit'],
        {jquery: 'jQuery', uikit: 'UIkit'},
        path.basename(file, '.js')
    )))
    )

).then(() => fs.unlink('dist/icons.json', () => {}));
```

**Comment by Almusamim** [comment]
so in version 3 there wont be any separation between the js core and the js  components?

**Comment by dasdeck** [comment]
Hi! I'm not sure I understand you correctly.
Recently I added some options to the build script.
`node ./build/build.js -h` for help.

> We need to have complete control over the files that we want to load

I'm a bit confused here, first you talk about compiling, then you talk about loading.
Do you need more granularity when it comes to modules?

Cheers!

**Comment by dasdeck** [comment]
@reardestani I'm afraid you have to get more specific here :)
UIkit 3 already creates core and components by default. `npm run compile`
Did you even look into the dist folder?
Though the granularity is not perfect yet, some components are part of core, we thought about 

Please close this issue if this is what you meant.

Cheers!

**Comment by reardestani** [comment]
When I opened the issue, it was different. Now it's better.
I hope, UIkit also adds separate files for core in future.
