### ISSUE TITLE
UK 3-beta.21 - Offcanvas scroll jump issue

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#2606]
### UIkit version
3.0.0-beta.21

### Reproduction Link
https://getuikit.com/assets/uikit/tests/offcanvas.html

### Steps to reproduce

Scroll down a little and trigger any Overlay Offcanvas.

### What is Expected?

The page scroll should remain the same

### What is actually happening?
The page scroll jumps when opening and closing.

**Comment by janschoenherr** [comment]
What browser are you using? It seems to work fine in Chrome.

**Comment by miljan-aleksic** [comment]
Yep, Chrome 57. Are you trying out Overlay and scrolling down before opening? Will make a video if you can't reproduce.

**Comment by florianletsch** [comment]
Also works fine for me (UIkit beta 22, Chrome 58).

Is this still an issue for you, Miljan?

**Comment by miljan-aleksic** [comment]
Yes, still an issue. I have recorded it, see how the offcanvas content jumps vertically when toggled.

![offcanvas-jump](https://cloud.githubusercontent.com/assets/513275/25552758/3d674ee6-2ca2-11e7-9e1c-eabaab938e96.gif)

**Comment by janschoenherr** [comment]
Did you clear your browser's cache?

**Comment by miljan-aleksic** [comment]
No, although the used version is clearly the latest. Anyway, it's working
fine on another Mac, must be the cache. Close this ticket please :)

**Comment by kingkevinhtx** [comment]
This might not be a cache issue. I'm experiencing this same bug between multiple browsers after clearing the cache. After switching back to my last pull (beta 18), the issue does not happen.
