### ISSUE TITLE
Animations change the position of positioned elements

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#2610]
### UIkit version

3.0.0-beta.21

### Reproduction Link

https://codepen.io/Riddler84/pen/jmbqro

### Steps to reproduce
Use any of the position classes except the corner classes (top-right, bottom-left etc.) and add an animation to the same element.

### What is Expected?
I expect that the element stay in position.

### What is actually happening?
The element is not centered anymore in the right position, because the `transform: translateX(0)` property from the animations 100% keyframe influence the `transform: translateY(-50%)` property from the position class in any way.

**Comment by b0rski** [comment]
Still happens as of today. Spent about 15 minutes pulling my hair.
https://pastebin.com/gVE4m2dC

**Comment by janschoenherr** [comment]
You can just the text in a second <span> and give that the animation class. As you already found, the css properties conflict otherwise.
