### ISSUE TITLE
uk-tab

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#2611]
UIkit version
3.0.0-beta.21

```
<ul uk-tab>
	<li><a href="http://www.yahoo.com">test</a></li>
	<li><a href=""></a></li>
	<li class="uk-disabled"><a href=""></a></li>
</ul>
```

When I click on "test" I should get redirected to Yahoo.com but that's not the case anymore in UIKit3.

Please delete post, I used _subnav_ instead. :)

**Comment by zzseba78** [comment]
You created the issue, you can close it.
