### ISSUE TITLE
sass/scss navbar toggle item doesn't render 

### ISSUE THREAD

**Issue by mjbates7** [uikit/uikit#2612]
Hi all,

I can't get the navbar icon to render on the navigation bar (could affect other components).

### UIkit version
3.0.0-beta.21

### Reproduction Link
None, see steps below

### Steps to reproduce
1. Create a new react application
2. Add uikit as a dependency/add node-sass
3. Compile scss files
4. Run it with the following code in App.js
```
 <nav className="uk-navbar data-uk-navbar-container uk-margin">
    <div className="uk-navbar-left">
        <a className="uk-navbar-toggle" href="#">
            <span data-uk-navbar-toggle-icon></span> <span className="uk-margin-small-left">Menu</span>
        </a>
    </div>
</nav>
```

5. Add the following import statements in App.scss:
```
// 2. Import default variables and available mixins.
@import "node_modules/uikit/src/scss/variables-theme.scss";
@import "node_modules/uikit/src/scss/mixins-theme.scss";

// 3. Your custom mixin overwrites.
@mixin hook-card() { color: #000; }

// 4. Import UIkit.
@import "node_modules/uikit/src/scss/uikit-theme.scss";
```
Why do I need to use the `node_modules` prefix on the import? Shouldn't I just be able to do `uikit/src/..`?

### What is Expected?
The navbar toggle item to render on the navbar

### What is actually happening?
No icon is showing:
![image](https://cloud.githubusercontent.com/assets/4522738/25129078/65695f5e-2434-11e7-9b2c-a4dffb441ed0.png)

![image](https://cloud.githubusercontent.com/assets/4522738/25129089/7218990e-2434-11e7-9df7-957a513b5b75.png)

**Comment by mjbates7** [comment]
Any update on this?

**Comment by simonhochrein** [comment]
Same problem

**Comment by florianletsch** [comment]
I cannot reproduce this on beta-25. I used your markup example and the CSS compiled from SASS.

However, I used static markup and not React. Might this be related to React evaluating the JS after the icons have been replaced? Does it work if you use static HTML?

Also, make sure to properly inluce uikit.js and uikit-icons.js

**Comment by mjbates7** [comment]
Hi,

This is still happening when used via React - is there anyway we can fix this to work?
I can confirm it works with static html.

Other icons work fine - just this toggle one.

**Comment by musashinm** [comment]
Same problem here.

* `webpack@3.8.1`
* `babel-core@6.26.0`
* `react@16.0.0`
* `uikit@^3.0.0-beta.34`

I've this on my main JS file:

```js
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';

import 'uikit/dist/css/uikit';

document.addEventListener('DOMContentLoaded', () => {
  ...

  UIkit.use(Icons);

  render(
    ...
  );
});
```

And I render `uk-navbar-toggle`:

```jsx
<a href="#" className="uk-navbar-toggle" data-uk-navbar-toggle-icon />
```

Comparing my rendered HTML with yours:

```html
<a href="#offcanvas-toggle" class="uk-navbar-toggle uk-navbar-toggle-icon uk-icon" data-uk-navbar-toggle-icon="true"></a>
```

```html
<a class="uk-navbar-toggle uk-navbar-toggle-icon uk-icon" uk-navbar-toggle-icon="" href="#">
  <svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ratio="1">
    <rect y="9" width="20" height="2"></rect>
    <rect y="3" width="20" height="2"></rect>
    <rect y="15" width="20" height="2"></rect>
  </svg>
</a>
```

Any solution on this?

**Comment by SVAR7BERG** [comment]
Doesn't work with 
`
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/css/uikit.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/js/uikit.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/js/uikit-icons.min.js"></script>
`

either.

**Comment by janschoenherr** [comment]
Is this still an issue? I think I recall fixing the problem with: `data-uk-navbar-toggle-icon="true"`
