### ISSUE TITLE
inview event isn't fired for objects in viewport on load. 

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#2619]
### UIkit version

3.0.0-beta.21

### What browser are you using?
Chrome for Mac (58.0.3029.81)

### What is Expected?
Inview event should be fired even if it's inview on load. 

### What is actually happening?
Inview isn't being fired for objects already inview on load.

**Comment by janschoenherr** [comment]
Please add a reproduction link. Thanks.

**Comment by janschoenherr** [comment]
Has this been resolved?

**Comment by TomS-** [comment]
Hi @janschoenherr I don't know why this one got lost on me. 

This is still a bug in 3.1.6, if you use delay: 10 it will work. 
https://codepen.io/anon/pen/YmNRvv

**Comment by janschoenherr** [comment]
I believe the event has already been fired, by the time you are listening to it. Keep in mind, that codepen defers scripts to the bottom of the <body> tag.

**Comment by TomS-** [comment]
@janschoenherr I just used codepen because I didn't want to link to my development website. But on my development website, I'm using UIKit as a module and my javascript is one file, this still happens.
