### ISSUE TITLE
Multi-Tooltip presists the first instance

### ISSUE THREAD

**Issue by chesedo** [uikit/uikit#2623]
### UIkit version
3.0.0-beta.22

### What browser are you using?
Firefox Developer Version v53

### Reproduction Link
https://codepen.io/chesedo/pen/QvKMZK

### Steps to reproduce
1. Focus on any of the two inputs to have its tooltip shown
2. Hover over the other input to also show its tooltip
3. Now hover over the input that has the focus from step 1 - notice how a new tooltip gets 'created' for it
4. Remove focus from the input in step one

### What is Expected?
That the tooltip for the input of step 1 will be 'destroyed'.

### What is actually happening?
The tooltip is stuck/persistent

**Comment by janschoenherr** [comment]
Fixed with 4a941dd7957dc7149d77796cd4683af089e26950.
