### ISSUE TITLE
uk-height-viewport in modal issue + docs fix

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2628]
### UIkit version

3.0.0-beta.22

### What browser are you using?

Chrome Mac 57.0.2987.133

### Reproduction Link

https://codepen.io/anon/pen/mmOGja

### Steps to reproduce

When clicking on the first button (at `scrollTop = 0`) the `uk-modal-body` is expanded correctly, however, once scrolled down, for example using the last button, the height is no longer correct.

While I assumed a conflict with `uk-overflow-auto` at first, it has no direct effect on it. Both are not correctly updated when the modal is opened. I tried a workaround where `document.body.scrollTop` is set to zero right before the modal opens (in `beforeshow`) and subsequently resets to the original `scrollTop`. 

This works, and proves that it is related to how `uk-height-viewport` calculates the height to use (seen here, https://github.com/uikit/uikit/blob/develop/src/js/core/height-viewport.js, it uses `offsetTop` of the element to determine the height).

The workaround has the undesirable side-effect that you see the scroll offset change before the dialog is opened, so it should really be fixed in UIkit itself. Ideally, the modal should update all contained components when it opens, and use the correct calculations.

On a related note, the documentation shows the `expand` option to default to `true`, however, it is actually `false`. Enabling/disabling this option affects this issue, but the documentation is not clear enough what functionality it actually provides. For a moment I thought the logic was reversed.

### What is Expected?

The `uk-modal-body` part should expand so the full window is filled, leaving the header and footer at the top and bottom of the viewport, respectively.

### What is actually happening?

When scrolled down, the height calculation amounts to less than the full expanded height, leaving a gap at the bottom.

**Comment by janschoenherr** [comment]
Can you not use the [full modifier](https://getuikit.com/docs/modal#full-modifier) to create a fullscreen modal?

**Comment by fabien** [comment]
@janschoenherr I must be missing something, because I am using `uk-modal-full` on the modal in the codepen above. Did you try it for yourself?

**Comment by janschoenherr** [comment]
An easy solution might be:

    <div class="uk-modal-body" style="height: 100vh" uk-overflow-auto>
