### ISSUE TITLE
How to get a light background offcanvas ?

### ISSUE THREAD

**Issue by nixgadget** [uikit/uikit#2630]
### UIkit version

3.0.0-beta.22

### Description of the Issue
Ive tried to implement a simple `nav` on an `offcanvas`. However, as shown by the screenshot below Im unable to get a light background `offcanvas` no matter what I try.

This is what I get by default without overriding anything in scss.

<img width="370" alt="ss" src="https://cloud.githubusercontent.com/assets/2648624/25427779/b8eebd60-2ac7-11e7-94d4-2bc3dfdd962f.png">

HTML is as given below,

```
<nav class="uk-navbar uk-navbar-container uk-margin oa-navbar">
    <div class="oa-logo-container uk-float-right">
        <a class="navbar-brand logo" routerLink="/">
            <span class="logo-img"></span>
        </a>
    </div>
    <div class="uk-navbar-right">
        <a class="uk-navbar-toggle" uk-toggle="target: #main-nav" href="">
            <span uk-navbar-toggle-icon></span> <span class="uk-margin-small-left" onTranslate="global.menu.title">Menu</span>
        </a>
    </div>

    <div id="main-nav" uk-offcanvas="overlay: true; flip: true;" [ngSwitch]="isAuthenticated()">
        <div class="uk-offcanvas-bar uk-flex uk-flex-column">

            <ul class="uk-nav uk-nav-primary uk-nav-center uk-margin-auto-vertical">
                <li class="uk-nav-header" onTranslate="global.menu.title">Menu</li>
                <li class="uk-nav-divider"></li>

                <li routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                    <a routerLink="/" (click)="toggleNavbar()">
                        <span class="uk-margin-small-right" uk-icon="icon: home" onTranslate="global.menu.home">Home</span>
                    </a>
                </li>

                <li *ngSwitchCase="false">
                    <a (click)="login()" id="login">
                        <span class="uk-margin-small-right" uk-icon="icon: sign-in" onTranslate="global.menu.account.login">Sign in</span>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
```

I have also tried setting the inverse mode with `@offcanvas-bar-color-mode: dark` to no avail.

Can someone please help me out with this ?

**Comment by rossity** [comment]
Having this exact same issue now and came here to look for the answer. Adding the "uk-light" class did not help either!

**Comment by nixgadget** [comment]
Did you mean `uk-dark` .. ?? As i believe `uk-light`

**Comment by nixgadget** [comment]
I meant `uk-light` is the default i think

**Comment by rossity** [comment]
Yes I meant `uk-dark`, in fact neither work unfortunately.

**Comment by nixgadget** [comment]
Yup i agree ... hopefully a dev can shed some light on this issue.

**Comment by saschadube** [comment]
Best way to modify the UIkit style is to create and compile your own theme. Here is the doc https://getuikit.com/docs/sass

When done just add 2 lines of code to make the offcanvas white:

```
@offcanvas-bar-background: #fff;
@offcanvas-bar-color-mode: none; 
````

Did it work?

**Comment by nixgadget** [comment]
@saschadube Thanks. I assume you meant,

```
$offcanvas-bar-background: #fff;
$offcanvas-bar-color-mode: none;
```

If so it works :)

**Comment by bretonio** [comment]
I am able to create a sidenav in `background-default` and `background-muted` modes with `uk-darj` but I cannot seem to wrap them in `uk-ioffcanvas-bar`.  Like this in Pug:

```
					#offcanvas-nav.uk-dark.uk-background-muted.uk-padding(uk-offcanvas='')
						.uk-offcanvas-bar
							ul.uk-nav
								li.uk-active
									a(href='#') Cordas
								li.uk-active
									a(href='#') Sopros
								li.uk-parent
									a(href='#') Metais
								li.uk-active
									a(href='#') Percussão	
```

I am reading [this issue](https://github.com/uikit/uikit/issues/3093) and [this other](https://github.com/uikit/uikit/issues/2693) on the subject also. Is true that

>yes, seems that offcanvas doesn´t have the inverse mode, it would be nice to have it, and since nav component have this mode i don´t think it will be a code bloat....

It remains confusing to call light text on a dark background the `uk-light` theme by the way!

I will try editing the semantically awesome files again as suggested if that is `node-sass` is not broken again. I set several light styles that do the job for me on another project.

Show me the error of my ways and thanks.

**Comment by AJULCAB** [comment]
OTHER SOLUTION IS
change the class, replace 'service' for any.
`
.uk-offcanvas-bar-service {
  /* 1 */
  position: absolute;
  top: 0;
  bottom: 0;
  left: -270px;
  /* 2 */
  box-sizing: border-box;
  width: 270px;
  padding: 20px 20px;
  background: #f8f8f8;
  /* 3 */
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}
/* Tablet landscape and bigger */
@media (min-width: 960px) {
  .uk-offcanvas-bar-service {
    left: -350px;
    width: 350px;
    padding: 40px 40px;
  }
}
/* Flip modifier */
.uk-offcanvas-flip .uk-offcanvas-bar-service {
  left: auto;
  right: -270px;
}
/* Tablet landscape and bigger */
@media (min-width: 960px) {
  .uk-offcanvas-flip .uk-offcanvas-bar-service {
    right: -350px;
  }
}
/*
 * Open
 */
.uk-open > .uk-offcanvas-bar-service {
  left: 0;
}
.uk-offcanvas-flip .uk-open > .uk-offcanvas-bar-service {
  left: auto;
  right: 0;
}
/*
 * Slide Animation (Used in slide and push mode)
 */
.uk-offcanvas-bar-animation {
  transition: left 0.3s ease-out;
}
.uk-offcanvas-flip .uk-offcanvas-bar-animation {
  transition-property: right;
}
.uk-offcanvas-reveal .uk-offcanvas-bar-service {
  /* 4 */
  left: 0;
}
.uk-offcanvas-flip .uk-offcanvas-reveal .uk-offcanvas-bar-service {
  /* 4 */
  left: auto;
  right: 0;
}
`

**Comment by AJULCAB** [comment]
Other solution is change the class, change the word 'service' for any.
`
.uk-offcanvas-bar-service {
  /* 1 */
  position: absolute;
  top: 0;
  bottom: 0;
  left: -270px;
  /* 2 */
  box-sizing: border-box;
  width: 270px;
  padding: 20px 20px;
  background: #f8f8f8;
  /* 3 */
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}
/* Tablet landscape and bigger */
@media (min-width: 960px) {
  .uk-offcanvas-bar-service {
    left: -350px;
    width: 350px;
    padding: 40px 40px;
  }
}
/* Flip modifier */
.uk-offcanvas-flip .uk-offcanvas-bar-service {
  left: auto;
  right: -270px;
}
/* Tablet landscape and bigger */
@media (min-width: 960px) {
  .uk-offcanvas-flip .uk-offcanvas-bar-service {
    right: -350px;
  }
}
/*
 * Open
 */
.uk-open > .uk-offcanvas-bar-service {
  left: 0;
}
.uk-offcanvas-flip .uk-open > .uk-offcanvas-bar-service {
  left: auto;
  right: 0;
}
/*
 * Slide Animation (Used in slide and push mode)
 */
.uk-offcanvas-bar-animation {
  transition: left 0.3s ease-out;
}
.uk-offcanvas-flip .uk-offcanvas-bar-animation {
  transition-property: right;
}
.uk-offcanvas-reveal .uk-offcanvas-bar-service {
  /* 4 */
  left: 0;
}
.uk-offcanvas-flip .uk-offcanvas-reveal .uk-offcanvas-bar-service {
  /* 4 */
  left: auto;
  right: 0;
}
`

**Comment by unistudioco** [comment]
### I found a good solution!! no need to compile SASS or LESS
First of all you have to added `selPanel` option to `uk-offcanvas=""` attribute with a custom class for ex:

`data-uk-offcanvas="flip: true; overlay: true; mode: reveal; selPanel: .uk-offcanvas-bar-light;"`

And then change the class `uk-offcanvas-bar` to the custom one `uk-offcanvas-bar-light`

Finally you have to re-style your custom class with the same css that have been used on the dark one but change the colors as you want! for ex:

```
.uk-offcanvas-bar-light {
    position: absolute;
    top: 0;
    bottom: 0;
    left: -270px;
    box-sizing: border-box;
    width: 270px;
    padding: 20px 20px;
    background: #f8f8f8;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
  }
  .uk-offcanvas-bar-animation {
    transition: left 0.3s ease-out;
  }
  @media (min-width: 960px) {
    .uk-offcanvas-bar-light {
      left: -350px;
      width: 350px;
      padding: 40px 40px;
    }
  }
  .uk-offcanvas-flip .uk-offcanvas-bar-light {
    left: auto;
    right: -270px;
  }
  .uk-offcanvas-flip .uk-offcanvas-bar-animation {
    transition-property: right;
  }
  .uk-offcanvas-flip .uk-open > .uk-offcanvas-bar-light {
    left: auto;
    right: 0;
  }
  @media (min-width: 960px) {
    .uk-offcanvas-flip .uk-offcanvas-bar-light {
      right: -350px;
    }
  }
  .uk-offcanvas-flip .uk-offcanvas-reveal .uk-offcanvas-bar-light {
    left: auto;
    right: 0;
  }
  .uk-offcanvas-reveal .uk-offcanvas-bar-light {
    left: 0;
  }
  .uk-open > .uk-offcanvas-bar-light {
    left: 0;
  }
```

_This solution will prevent invert some components styles!! which is the important thing for me as well 🥇_ 

**Hope it helps!**
