### ISSUE TITLE
3.0.0-beta.22. Artefact property uk-background-blend-multiply only Chrome 58.xxx with scroll 

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2631]
winows 8 chrome 58.0.3029.81
`<body class="uk-background-blend-multiply  uk-background-cover uk-background-center uk-background-image@s uk-background-fixed " style="background-image: url(/bitrix/templates/uikit3desktop/images/bg07.jpg);">`

![image](https://cloud.githubusercontent.com/assets/16114000/25437423/fe6e7570-2a9e-11e7-832b-439a9eb01640.png)

if remove uk-background-blend-multiply in class = all ok - without artefact 

off
on IE11.0.9 this backgrоund image is shaking when scrolling

**Comment by zzseba78** [comment]
Background blend it's not fully supported yet in all browsers, for example, it's not supported in IE. or Edge yet. [http://caniuse.com/#feat=css-backgroundblendmode](url)
Another point is it seems to have **issues with performance**, so if i where you i definitly wouldn't use a full background body image blended.

**Comment by AlexandreZaytsev** [comment]
okay, thanks
