### ISSUE TITLE
github changelog and getuitkit changelog doesn't match

### ISSUE THREAD

**Issue by ThaneshR** [uikit/uikit#2633]
In the [github changelog](https://github.com/uikit/uikit/blob/develop/CHANGELOG.md), it mentions the addition of the countdown component.

Meanwhile, in the [getuitkit changelog](https://getuikit.com/changelog), the addition of the countdown component is not listed.

**Comment by florianletsch** [comment]
Good catch. Here is why it happens: The website shows the [changelog from the master branch](https://github.com/uikit/uikit/blob/master/CHANGELOG.md). The one you linked is on the develop branch. When we merge back to master, it will be deployed automatically and it will be fixed on the website.

I think we forgot to include to list the countdown component when we last made a release (it was still included in the release, just not listed in the changelog).
