### ISSUE TITLE
uk-width-auto column collapses to zero with active sticky inside

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#2634]
### UIkit version

3.0.0-beta.22

### What browser are you using?
Google Chrome 57.0.2987.133

### Reproduction Link
https://codepen.io/Riddler84/pen/qmRzjW?editors=1000#0

### Steps to reproduce
1. Create a grid and give one column the `uk-width-auto` class.
2. Now put an element in this column and make it sticky via `uk-sticky`.

### What is Expected?
The Element should be sticky if you scroll down and the layout of the grid shouldn't be affected.

### What is actually happening?
The `uk-width-auto` column collapses to zero width, once you scroll down and the element gets sticky. I think the `uk-sticky-placeholder` div should be adopt the width of the original container in some form. It's not enough for it to be a block element in this situation.

**Comment by mykiimike** [comment]
Hi,

Any update about this issue?

++

**Comment by bdthemes** [comment]
same problem for me 😟 any update?
