### ISSUE TITLE
https://getuikit.com/docs/theme

### ISSUE THREAD

**Issue by blaasvaer** [uikit/uikit#2635]
Page not found – 404!

**Comment by zzseba78** [comment]
Where is this link present in the docs?

**Comment by florianletsch** [comment]
I also could not find which link would cause this. I am closing this. If you can specify which link exactly is borken, please report again in the docs repository: https://github.com/uikit/uikit-site

**Comment by blaasvaer** [comment]
Well, the link in the subject: https://getuikit.com/docs/theme

It loads the »frame« but the content is 404 ...

**Comment by blaasvaer** [comment]
[Screen Shot 2017-05-12 at 17.31.13.pdf](https://github.com/uikit/uikit/files/997219/Screen.Shot.2017-05-12.at.17.31.13.pdf)

**Comment by Riddler84** [comment]
Yes, because this site simply doesn't exist. And like the others, i can't find any link in the docs, which leads to the site you're mentioned. So.. where is the link? ;)

**Comment by florianletsch** [comment]
I have finally found and fixed the link you mentioned. https://github.com/uikit/uikit-site/commit/c0554f9c4ed72658e36f19c29b2f9409310aabad
