### ISSUE TITLE
is jQuery required? 

### ISSUE THREAD

**Issue by wildekin** [uikit/uikit#2636]
Nowhere in the docs is jQuery even mentioned, if it is required, which version?
Is it possible to use this without, if not, please say so somewhere..

**Comment by ruchern** [comment]
https://getuikit.com/docs/javascript

**Comment by wildekin** [comment]
I can do one better.

https://getuikit.com/docs/installation

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.22/css/uikit.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.22/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.22/js/uikit-icons.min.js"></script>

**Comment by danny-englander** [comment]
On https://getuikit.com/docs/introduction#html-markup

> Add the compiled and minified CSS and JavaScript to the header of your HTML5 document. **jQuery is required as well.** Also include the UIkit icon library. For your basic setup, that's it.

**Comment by florianletsch** [comment]
Yes, jQuery is required. Thanks, I will add it to the installation doc.

**Comment by danmondy** [comment]
JQUERY has been removed from every single one of the sources mentioned above. Is this still required?

**Comment by aarongerig** [comment]
Nope, like you said it has been removed.

**Comment by stimpy77** [comment]
So it isn't required and as such isn't included.
Is it still compatible? We are currently using jQuery almost exclusively, and I would like to know if we can transition to UIKit slowly or if it will require rearchitecting.
