### ISSUE TITLE
Disable Inverse

### ISSUE THREAD

**Issue by imdiegoestevez** [uikit/uikit#2638]
Hello,
Is there a way to disable the uk-light or uk-dark from a child whose parent has one of those classes? I tried adding the uk-dark to a child whose parent had a uk-light, but its parent's class overwrote it.

Thanks in advance, Diego.

**Comment by nixgadget** [comment]
Have you seen https://getuikit.com/docs/inverse#customize-using-less ?

**Comment by imdiegoestevez** [comment]
Not really, thank you Kasun
