### ISSUE TITLE
The file can't upload?(v2.27.2)

### ISSUE THREAD

**Issue by king742171** [uikit/uikit#2639]
My UIkit version is 2.27.2

There is my code:
`<head>`
`		<meta charset="utf-8">`
`		<meta name="viewport" content="width=device-width, initial-scale=1">`
`		<title>lightbox</title>`
`		<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />`
`		<link rel="stylesheet" href="css/uikit.min.css" />`
`        <script src="js/jquery-3.2.1.min.js"></script>`
`        <script src="js/uikit.min.js"></script>`
`        <!-- Slidenav CSS -->`
`        <link rel="stylesheet" href="css/components/slidenav.css">`
`        <!-- Upload CSS -->`
`        <link rel="stylesheet" href="css/components/upload.css">`
`        <!-- Upload Javascript -->`
`        <script src="js/components/upload.js"></script>`
`        <!-- Placeholder CSS -->`
`        <link rel="stylesheet" href="css/components/placeholder.css">`
`        <!-- Form-File CSS -->`
`        <link rel="stylesheet" href="css/components/form-file.css">`
`        <!-- Progress CSS -->`
`        <link rel="stylesheet" href="css/components/progress.css">`
`        <!-- Upload Action Javascript -->`
`        <script>`
`		    $(function(){`
`		        var progressbar = $("#progressbar"),`
`		            bar         = progressbar.find('.uk-progress-bar'),`
`		            settings    = {`
`		            action: './images', // 上傳路徑 url`
`		            allow : '*.(jpg|gif|png|docx|pdf)', // 只允許上傳檔案類型`
`		            loadstart: function() {`
`		                bar.css("width", "0%").text("0%");`
`		                progressbar.removeClass("uk-hidden");`
`		            },`
`		            progress: function(percent) {`
`		                percent = Math.ceil(percent);`
`		                bar.css("width", percent+"%").text(percent+"%");`
`		            },`
`		            allcomplete: function(response,xhr) {`
`		                bar.css("width", "100%").text("100%");`
`		                setTimeout(function(){`
`		                    progressbar.addClass("uk-hidden");`
`		                }, 250);`
`		                alert("檔案上傳成功");`
`		            }`
`		        };`
`		        var select = UIkit.uploadSelect($("#upload-select"), settings),`
`		            drop   = UIkit.uploadDrop($("#upload-drop"), settings);`
`		    });`
`		</script>`
`	</head>	`
`	<body>`
`		<div class="uk-block uk-block-muted" style="margin: 5px; padding: 5px;">`
`			<div id="upload-drop" class="uk-placeholder">`
`			    新增圖片<a class="uk-form-file uk-icon-button uk-icon-plus uk-icon-large"><input id="upload-select" type="file"></a>`
`				<div id="progressbar" class="uk-progress uk-hidden">`
`				    <div class="uk-progress-bar" style="width: 0%;"></div>`
`				</div>`
`			</div>`
`		</div>`
`	</body>`
Question:
I click the button, then the proccess run 100% and show the message upload complete.
But, in the folder whitch named "images", I can't see my uploaded file.

**Comment by aheinze** [comment]
Hi,

the action setting is the url where the upload should get procced. so you need a serverside script that handles/moves the uploaded file.

greets,
artur

**Comment by king742171** [comment]
OH!! I'm so silly...
But....
Can you teach me how to write the serverside script ?
I try to write with PHP , because my server is Apache.
here is my code:
`<?php`
`if ($_FILES["file"]["error"] > 0){`
`  echo "Error: " . $_FILES["file"]["error"];`
`}else{`
`  echo "file name: " . $_FILES["file"]["name"]."<br/>";`
`  echo "file type: " . $_FILES["file"]["type"]."<br/>";`
`  echo "file size: " . ($_FILES["file"]["size"] / 1024)." Kb<br />";`
`  echo "tamp name: " . $_FILES["file"]["tmp_name"];`
`  move_uploaded_file($_FILES["file"]["tmp_name"],"../../images/".$_FILES["file"]["name"]);`
`}`
`?>`
I use Chrome Developer tools to see the response.
I can't see any file information . like:
`response: "file name: </br>file type: </br>file size: 0 Kb</br>tamp name: "`
