### ISSUE TITLE
'required' text field with blank does not appeal it.

### ISSUE THREAD

**Issue by nobusugi246** [uikit/uikit#2641]
### UIkit version
3.0.0-beta.22

### Browser
Chrome

### Steps to reproduce
`<input class="uk-input" type="text" required>`

### What is Expected?
'required' text field with blank does not appeal it.

### What is actually happening?
'required' does not affect to the text field.

**Comment by Riddler84** [comment]
What's the matter? Looks good to me.
https://codepen.io/Riddler84/pen/BRdzxN

Did you put the required input inside a form element? That's required ;)

**Comment by zzseba78** [comment]
Works fine for me in all browsers.
 
Chrome screenshot
![captura de pantalla 2017-05-03 a la s 12 40 32](https://cloud.githubusercontent.com/assets/5558563/25668677/c73c5fb8-2ffd-11e7-84e2-5773a6a582a8.png)

**Comment by nobusugi246** [comment]
Thank you. 
Hover messaging is OK, but the coloring of the box is not.

In firefox,

![required_firefox](https://cloud.githubusercontent.com/assets/465395/25687595/94bb050c-30b2-11e7-906d-3190697adb64.png)


In Chrome,

![required_chrome](https://cloud.githubusercontent.com/assets/465395/25687597/9953c39c-30b2-11e7-881e-7ac509b06194.png)

    <form class="uk-grid-small" uk-grid>
        <div class="uk-width-1-2">
            <input class="uk-input uk-form-small" type="text" placeholder="Your Name" id="userName" required>
        </div>
    </form>

**Comment by zzseba78** [comment]
This is not a UIkit issue, it's a browser behavior with html5 validation.
UIkit doesn't deal with it, if you want to validate the form and want to add uikit error classes to form elements use some 3rd party script to do it.
I use this, works great.
https://jqueryvalidation.org/

**Comment by Riddler84** [comment]
The red border is rendered by firefox. It has nothing to do with uikit. Firefox applies the pseudo-class `:-moz-ui-invalid` to the input, which is defined with a red box-shadow. You can overwrite it, if you want.

**Comment by nobusugi246** [comment]
Thank you. I got it.

**Comment by zzseba78** [comment]
Please close this issue to keep things ordered :)
