### ISSUE TITLE
[Important] iOS 9 click is firing twice causing nothing to work

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#2643]
### UIkit version

3.0.0-beta.22

### Reproduction Link

https://getuikit.com/docs/nav#accordion
Click the accordion

https://www.browserstack.com/start#os=iOS&os_version=9.0&device=iPhone+6S&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fgetuikit.com%2Fdocs%2Fnav&speed=1&host_ports=google.com%2C80%2C0

### Steps to reproduce
Tested on iPad - iOS 9.2
Tap is causing click to fire twice.

### What is Expected?
Tap will only fire click once.

### What is actually happening?
Tap 8s

**Comment by TomS-** [comment]
Worth noting that this will apply to every click() used in javascript when uikit is added.

**Comment by duyhung85** [comment]
I am also experiencing this tap fire twice on my iphone when try to bind a click listener. Here is the demo: 

[http://codepen.io/duyhung85/pen/ybowOe](url)

You can open the dialog (as in the docs) and click on Cancel button, the alert() fires twice. Its working fine in desktop though.

**Comment by TomS-** [comment]
@duyhung85 thanks for confirming this. iOS 10 works fine, everything below is broken. Android as always works great :-)

**Comment by TomS-** [comment]
Maybe it's something relating to this? https://github.com/uikit/uikit/blob/develop/dist/js/uikit.js#L1095

UIKit devs can be slow sometimes (as they have so many other projects). I'll see if I can figure something out to help them out.

**Comment by TomS-** [comment]
@duyhung85 found it, comment out line 1110 in UIkit.js it's checking the object is clicked, if not fire a click. However clicked will return false regardless causing click to fire twice on single tap.

**Comment by razvanioan** [comment]
Increasing the timeout interval even further from 350 to 400ms it seems to fix triggering events twice on iOS InAppBrowser (website loaded into an app WebView)
