### ISSUE TITLE
Feature Request: Custom Prefix when migration checking

### ISSUE THREAD

**Issue by stell** [uikit/uikit#2644]
When using the migration script from https://getuikit.com/migrate.min.js it would be great if one could customize it to check via a custom prefixed UIkit2 stylesheet.
At the moment it tells everything is UIkit3 ready ;)

**Comment by florianletsch** [comment]
The migration script is available here: https://github.com/uikit/uikit-migration

I think... that it should be enough to just search and replace "uk-" with your prefix in all files and then run the build script? :thinking: 

Would that do for you? 

Maybe @philoest knows more. I guess we could also extend the migrate script with a custom prefix option, but I'm note sure where the priority for that would lie at the moment. Maybe if there is succicient demand?

**Comment by philoest** [comment]
I think a search and replace either within the created JS itself as well as in the rules within the uikit-migration src it self should do the trick. Since we are using CSS selectors to detect these problems, only these selectors are needed to be changed.

**Comment by florianletsch** [comment]
I think we will recommend that workaround for now, unless someone would like to contribute a custom-prefix option to the migration script. If so, please contribute there: https://github.com/uikit/uikit-migration
