### ISSUE TITLE
Lightbox should support srcset

### ISSUE THREAD

**Issue by jhit** [uikit/uikit#2645]
I would like to get support for srcset in the uikit 3 lightbox component. Currently there is no such thing as you can see in the source https://github.com/uikit/uikit/blob/develop/src/js/components/lightbox.js#L218

This would help mobile devices to only load images appropriate for their display resolution.

### UIkit version
3.0.0-beta.22

**Comment by reramjiawan** [comment]
I would like to add: [fancybox3](https://codepen.io/fancyapps/pen/YQKKYx?editors=1000)

**Comment by razvanioan** [comment]
I've created the following pull request, but who is interested can already patch a custom build

https://github.com/uikit/uikit/pull/3959

**Comment by janschoenherr** [comment]
With the next release you'll be able to add an `attrs` or `data-attrs` attribute, which will allow you to set any attribute on the item.

    <a href="myimage.jpg" attrs="srcset: myimage-800.jpg 800w; sizes: ...">

**Comment by jhit** [comment]
Thanks for adding this.

**Comment by helmutkaufmann** [comment]
> With the next release you'll be able to add an `attrs` or `data-attrs` attribute, which will allow you to set any attribute on the item.
> 
> ```
> <a href="myimage.jpg" attrs="srcset: myimage-800.jpg 800w; sizes: ...">
> ```

Hello. Has this been indeed implemented? If so, would anyone be able to post example code? I cannot get it working, UIKit seems to be always using the image referenced under the href tag.
