### ISSUE TITLE
Hooks Sugested and  Update

### ISSUE THREAD

**Issue by Bernardoow** [uikit/uikit#2646]
Hi

How I customize Uikit using this hook [1] and keep uikit update?

I'm novice with sass. For I use this [1] I put it inside [2]. But How I will update uikit?

[1]https://github.com/uikit/uikit/blob/develop/src/scss/components/table.scss#L275

[2]https://github.com/uikit/uikit/blob/develop/src/less/components/table.less#L71

**Comment by florianletsch** [comment]
Check out the sass docs and set up a sass file where you import the uikit scss files: https://getuikit.com/docs/sass#how-to-build

Change the example hook and add for example the table hook:

````
// 3. Your custom mixin overwrites.
@mixin hook-table() { border: 5px solid lime; }
```

When you compile this file, your styles should then be included. Also, as you only import the uikit scss files and do not change them, these can be updated without problems (for example with npm, bower or manually by replacing the files for a new version)

**Comment by Bernardoow** [comment]
@florianletsch 
My Ask is : The hook-table not is under tag .ui-table. [1]
How I will do third step. Others hooks is under tags.
Look link.

[1]https://github.com/uikit/uikit/blob/develop/src/less/components/table.less#L64

**Comment by florianletsch** [comment]
I think you are right, sorry for closing early. Will need to look into this next week.

**Comment by Bernardoow** [comment]
@florianletsch 

OK!

I was check if the code of less is same. And this is.

If the questions is a problem and you need help, I can code hooks inside the .classses. But How I say.. I'm novice with sass and less...

**Comment by florianletsch** [comment]
You are right, the table-hook was simply missing in the table definition... I fixed it. Will be available with the next release. Thanks for reporting!

**Comment by Bernardoow** [comment]
@florianletsch 
oK Thanks.
I was checked your fix commit and Saw just at less file.
Here have the same problem. 
https://github.com/uikit/uikit/blob/develop/src/scss/components/table.scss#L71

**Comment by florianletsch** [comment]
Thanks, however I think this is already fixed now. The scss is automatically generated from the Less files just before every release, that is why it wasn't part of my original commit.
