### ISSUE TITLE
Are there plans to have a standalone sidebar?

### ISSUE THREAD

**Issue by ruchern** [uikit/uikit#2648]
Something like the one of the left of this: https://v4-alpha.getbootstrap.com/examples/dashboard/

**Comment by Riddler84** [comment]
What you see there is simply a grid with a sticky nav menu in the left column. You can do this easily with uikit too, like in this example: https://codepen.io/Riddler84/pen/JNrqwK

**Comment by ruchern** [comment]
@Riddler84 Thanks bro. I am very new to UIKit and this would be very helpful.
