### ISSUE TITLE
Why offcanvas must be direct under <body> ?

### ISSUE THREAD

**Issue by blb78** [uikit/uikit#2649]
Hi !
 I'am using : 
"uikit": "^3.0.0-beta.22",
"react": "^0.14.7",
"react-router": "^2.0.0",

my initial DOM is like that : 

```
<html>
    <body>
         <div id="my_react_router_app">
             <nav className="uk-navbar-container uk-navbar-transparent" data-uk-navbar="">
                 
                <button className="uk-button uk-button-text uk-padding-small  uk-visible-small" type="button" data-uk-toggle="target: #offcanvas"><span data-uk-icon="icon: menu"></span></button>
                
            </nav>
            <div id="offcanvas" data-uk-offcanvas="mode: push">
                <div className="uk-offcanvas-bar">
                    <button className="uk-offcanvas-close" type="button" data-uk-close></button>
                    <ul className="uk-nav uk-nav-default">
                        <li><Link to="/clients" activeClassName="uk-active">Clients</Link></li>
                        <li><Link to="/devis" activeClassName="uk-active">Devis</Link></li>
                        <li><a href="" onClick={this.handleLogout}>Deconnexion</a></li>
                    </ul>

                </div>
            </div>
        </div>
    </body>
</html>
```
But when i triggered the offcanvas button, UIKIT changes my DOM like that : 

```
<html>
    <body>
         <div id="my_react_router_app">
             <nav className="uk-navbar-container uk-navbar-transparent" data-uk-navbar="">
                 
                <button className="uk-button uk-button-text uk-padding-small  uk-visible-small" type="button" data-uk-toggle="target: #offcanvas"><span data-uk-icon="icon: menu"></span></button>
                
            </nav>
        </div>
        <div id="offcanvas" data-uk-offcanvas="mode: push">
                <div className="uk-offcanvas-bar">
                    <button className="uk-offcanvas-close" type="button" data-uk-close></button>
                    <ul className="uk-nav uk-nav-default">
                        <li><Link to="/clients" activeClassName="uk-active">Clients</Link></li>
                        <li><Link to="/devis" activeClassName="uk-active">Devis</Link></li>
                        <li><a href="" onClick={this.handleLogout}>Deconnexion</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>
```

So React throw an error : 

> Uncaught Invariant Violation: findComponentRoot(..., .0.1.0.1.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``

So Why UIKIT changed my DOM ?

**Comment by florianletsch** [comment]
The offcanvas markup has changed in one of the last few beta releases. You will now need to add a `class="uk-offcanvas-content"` container around the markup. Is it possible that you just need to update your markup to fix this issue? https://getuikit.com/docs/offcanvas

**Comment by blb78** [comment]
I found my issue  in  the show method, the orginal code is : 

```
show: function show() {
            var this$1 = this;
            console.log('toto');
            if (this.container && !this.$el.parent().is(this.container)) {
                this.container.appendChild(this.$el[0]);
                return promise(function (resolve) { return requestAnimationFrame(function () { return resolve(this$1.show()); }
                    ); }
                )
            }

            return this.toggleNow(this.$el, true);
        },
```

and I want to fix my issue I a have to write this : 

```
show: function show() {
            var this$1 = this;
            console.log('toto');
            if (this.container && !this.$el.parent().is(this.container)) {
                this.container = this.$el.parent();
                return promise(function (resolve) { return requestAnimationFrame(function () { return resolve(this$1.show()); }
                    ); }
                )
            }

            return this.toggleNow(this.$el, true);
        },
```

In the original code, this.container is always the body

**Comment by blb78** [comment]
The real issue is the role of `class="uk-offcanvas-content"` , while it is present or not, this.container always returns <body>

If I understand correctly how works your library ...

**Comment by janschoenherr** [comment]
If you initialize the offcanvas with

    <div id="offcanvas" data-uk-offcanvas="mode: push; container: #my_react_router_app">

it should work.

**Comment by MrFragIT** [comment]
Is this workaround still actual? it works but the container attribute is missing in the docs: https://getuikit.com/docs/offcanvas#component-options

**Comment by viewpoint** [comment]
Best workaround to resolve the issue of the off-canvas being moved to just before the closing `</body>` tag is to disable the code in uikit.js. I cannot understand why it should be necessary to mess with the DOM simply to move a div in and out.
In the meantime, the magical fix is to comment out the following script at line 3657:
`            //if (this.container && this.$el.parentNode !== this.container) {
            //    append(this.container, this.$el);
            //    this._callConnected();
            //}
`
