### ISSUE TITLE
Stickys don't work with animation on parent element

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#2650]
### UIkit version

3.0.0-beta.22

### Browser
Chrome & Firefox (and probably any other)

### Reproduction Link
https://codepen.io/Riddler84/pen/jmarOR?editors=1000#0

### What is actually happening?
As you can see, if one of the parent elements of the sticky element has an animation class, the sticky won't work anymore. And if you scroll down (mousewheel) and then up again, you can't reach the top of the site, only the top of the stickied element.

The only exception is the fade animation. Then the sticky works, but the scroll bug remains.

**Comment by janschoenherr** [comment]
If you set `animation-fill-mode: none` on the element with the animation class, it will work again.
