### ISSUE TITLE
Issue uk-modal-page for scope mode

### ISSUE THREAD

**Issue by mvanvu** [uikit/uikit#2651]
I got a issue when I use UIkit in scope mode:
When modal full page is show then HTML tag will been added class "uk-modal-page" but the class was not removed after modal close like the test page https://getuikit.com/assets/uikit/tests/modal.html. So, the scroll bar will be hidden.

**Comment by Riddler84** [comment]
Same problem here, but i'm using not the scope mode. If i close a modal via JavaScript, e.g. `modal.hide()`, then the scollbar will stay disappeared, because of the `uk-modal-page` class, which remains attached to the html element.

**Comment by dasdeck** [comment]
Is this bug still relevant?
Seems to work as expected.
I'll close this for now, feel free to reopen this if the issue remains for you.

Cheers!

**Comment by rvalitov** [comment]
I'm not sure if it's a bug, but I faced a similar problem. In my case I need to destroy the modals manually, i.e. remove them from HTML DOM. If I use `modal.hide()` then the modal is not removed from the DOM. I need to call `modal.$destroy(true)` manually. If I use `destroy` in the `hide` event, then the `uk-modal-page` class is not removed. Adding a timeout helps to avoid this issue.

Example is in [JSBin](https://jsbin.com/yilacijuki/edit?html,js,console).

**Comment by janschoenherr** [comment]
@rvalitov you will want to use the _hidden_ event instead.

**Comment by rvalitov** [comment]
@janschoenherr  Thank you, I did. Code which does not work (`uk-modal-page` stays visible, but the dialog hides itself correctly and is removed from DOM):

```
function displayModalDialog(content, center) {
    var cssClass = "uk-modal-dialog";
    if ((typeof center !== 'undefined') && (center))
        cssClass += " uk-margin-auto-vertical";
    var dialog = UIkit.modal("<div class=\"uk-modal uk-flex-top\"><div class=\"" + cssClass + "\">" +
        "<div class='uk-modal-body uk-modal-static'>" + content + "</div>" + "</div></div>",
        {
            'escClose': false,
            'bgClose': false
        });

    UIkit.util.on(dialog.$el, 'hidden', function (ref) {
            dialog.$destroy(true);
     });
    dialog.show();

    return dialog;
}
```

If I add setTimeout, then it works much better and the `uk-modal-page` is removed:

```
function displayModalDialog(content, center) {
    var cssClass = "uk-modal-dialog";
    if ((typeof center !== 'undefined') && (center))
        cssClass += " uk-margin-auto-vertical";
    var dialog = UIkit.modal("<div class=\"uk-modal uk-flex-top\"><div class=\"" + cssClass + "\">" +
        "<div class='uk-modal-body uk-modal-static'>" + content + "</div>" + "</div></div>",
        {
            'escClose': false,
            'bgClose': false
        });

    UIkit.util.on(dialog.$el, 'hidden', function (ref) {
        //We must set a timeout, otherwise the scrolling can break because the CSS classes are not removed
        //correctly - https://github.com/uikit/uikit/issues/2651
        setTimeout(function () {
            dialog.$destroy(true);
        }, 1000);
    });
    dialog.show();

    return dialog;
}
```

What am I doing wrong?
