### ISSUE TITLE
Offcanvas Anchor Link not working

### ISSUE THREAD

**Issue by Rikachii** [uikit/uikit#2652]
Hello,

I have a questions regarding anchro links in an offcanvas navigation. I am currently using Yoothemes Master theme (Version 1.0.0) in Wordpress and there I have an offcanvas navigation with different points, which are linked to different partes of the onepages. At this point everything works fine. Now I got the problem that I want to include two buttons int this offcanvas navigation which are linked to external pages e.g. Google or Github. But once I click on them first the first time, the offcanvas closes but nothing else happens. Once I open the menu again and click on the button, nothing happens.

Does anybody know why I can not use external links in the offcanvas?

Please find the code, which is used for the two buttons in the Widgets section below offcanvas:

![grafik](https://cloud.githubusercontent.com/assets/28535613/25807375/e7cddd9e-3406-11e7-8354-038e6566f373.png)

I would be thankful for every advise towards this topic. Thank you very much.

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
