### ISSUE TITLE
[Flex] IE Bug

### ISSUE THREAD

**Issue by aarongerig** [uikit/uikit#2653]
### UIkit version
3.0.0-beta.35

### Browser
Internet Explorer

### Reproduction Link
Open [this link](https://codepen.io/aarongerig/pen/JNMdqY) in Internet Explorer and another browser of your choice.

### Steps to reproduce
- Create a vertical list of flex items (add `.uk-flex-column` to the parent container).
- Make sure all child elements have the class `.uk-flex-1`, which expands each child evenly.
- Now open your page in Internet Explorer

### What is Expected?
The list should look something like this:
![view-in-chrome](https://cloud.githubusercontent.com/assets/17384333/25808554/c3343b64-340a-11e7-93fc-6bb16a7aee7a.png)

### What is actually happening?
The list completely collapses height-wise.
![ie-flex-bug](https://cloud.githubusercontent.com/assets/17384333/25808571/d152f4ec-340a-11e7-9056-93f8dbe7d85c.png)

This bug is quite famous ([described here](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items)). The problem is `uk-height-match` setting a `min-height` on the element, which is completely ignored by IE (who would have thought?!).

**BUT**, there's an [easy fix](https://codepen.io/chriswrightdesign/pen/emQNGZ/) to this problem. Instead of `min-height` just use `height` and it works properly.

For the example in my codepen I found another way to solve my problem, but I think this bug should be addressed generally in UIkit. It could happen quite easily. What do you think about that guys?

## EDIT
Updated codepen to latest version, issue still remains.

**Comment by aarongerig** [comment]
@janschoenherr / @saschadube This should be resolved with https://github.com/uikit/uikit/commit/dda8f676a07d497dc922c45893c77e9405c0004d, right?

**Comment by janschoenherr** [comment]
It should be resolved in latest dev build 3.0.0-dev.bdfd330

**Comment by janschoenherr** [comment]
@aarongerig is this resolved in rc.17?

**Comment by aarongerig** [comment]
I will test it asap and will let you know.
