### ISSUE TITLE
UIkit 3.0.0-beta.22 Cover component image height Bug

### ISSUE THREAD

**Issue by Septdir** [uikit/uikit#2655]
UIkit 3.0.0-beta.22
Hello,
When I use the component component for image
`<div class="uk-cover-container"><img src="x.jpg" data-uk-cover></div>`
The image is displayed in a rounded height.
Example
Parent height (.uk-cover-container) = 191.45px
Image Height (img[data-uk-cover]) = 191px
On a dark background, this discrepancy is very noticeable.

**Comment by fabien** [comment]
In believe this issue manifests itself when using jQuery v.3. In v.2 dimensions were rounded to integers, but this is no longer the case.

**Comment by Septdir** [comment]
I use last jQuery version  3.2.1, I I checked on jQuery 2.2.4 - same problem. 
At now to fix this problem I'm using a small script to set min-height to img[data-uk-cover], but I hope this will soon be corrected, because when the kartika is dark and the background is light even 0.2px of the difference is very noticeable

**Comment by bbashy** [comment]
@Septdir Have you got a codepen link to reproduce it? Need to check if it's still an issue in the latest release.

**Comment by Septdir** [comment]
@bbashy I test ;ast version bug still alive.
reproduce (.uk-cover-container {background-color: red;} )
https://codepen.io/Septdir/pen/WjWdPq
