### ISSUE TITLE
Vue interferes with Sticky

### ISSUE THREAD

**Issue by Propaganistas** [uikit/uikit#2657]
### UIkit version
3.0.0-beta.22

### Browser
Chrome, Firefox, Safari

### Reproduction Link
http://codepen.io/anon/pen/VbyJMb

### Steps to reproduce
* Define a Sticky element
* Instantiate a new custom Vue instance on a parent element

### What is Expected?
* Sticky behavior of course :)

### What is actually happening?
UIkit's and Vue are interfering, rendering the following error message to the console:

```
ui.34947c4….js:5145 Uncaught TypeError: Cannot read property 'css' of null
    at Sticky.write (ui.34947c4….js:5145)
    at ui.34947c4….js:1814
    at runTasks (ui.34947c4….js:880)
    at flush (ui.34947c4….js:867)
```

It seems the sticky `placeholder` does not get set.

**Comment by frumbert** [comment]
https://getuikit.com/docs/sticky also shows the sticky on top of the blue header bar as you scroll.

**Comment by Propaganistas** [comment]
@frumbert ...which is exactly what is being showcased and has nothing to do with this issue?

**Comment by Propaganistas** [comment]
Sorry, seemed to have missed this issue: https://github.com/uikit/uikit/issues/2519

Adding `defer` to the script tag appears to be a valid workaround.

**Comment by muhajirframe** [comment]
It seems doesn't works for me, I am on 3.0.0-beta.30
