### ISSUE TITLE
Modal with close-outside clash with uk-overflow-auto

### ISSUE THREAD

**Issue by umphy** [uikit/uikit#2659]
### UIkit version

3.0.0-beta.22

### Browser
Chrome 56.0.2924.76

### Reproduction Link
https://jsfiddle.net/0qbnpp2b/

### Steps to reproduce
Define a dialog with ```uk-overflow-auto``` and modal close button with class ```uk-modal-close-outside```.

### What is Expected?
Scrollable modal content with close button outside of dialog.

### What is actually happening?
Close button is not visible.

**Comment by florianletsch** [comment]
I think the solution is not add the `uk-overflow-auto` attribute on a container inside the modal, not on the modal itself. At least that's the way it is shown in the documentation: https://getuikit.com/docs/modal#overflow

**Comment by umphy** [comment]
Nice example @florianletsch. From the docs, it says "...add the uk-overflow-auto attribute from the Utility component to the **modal dialog** — or the modal body.", emphasis mine.

If it's not supposed to be used on the modal dialog then I think the docs will need to change.

**Comment by florianletsch** [comment]
You're right. I think I'd see this as an error in the docs. 

After all, adding the overflow to the modal itself would cause any control elements inside to scroll out of the container as well (I mean things like _Save_ and _Cancel_ buttons).... and I don't think this would be desired. 

I will change this in the docs. 

I think you can fix your issue by just setting the overflow attribute on a container inside the modal, right?

**Comment by umphy** [comment]
Yes, I agree, it's an error in the docs. Thanks @florianletsch.
