### ISSUE TITLE
How to disable tabs responsiveness

### ISSUE THREAD

**Issue by arrowthemes** [uikit/uikit#266]
In certain cases, you'd want to disable the responsiveness of tabs whereby the tabs change to a trigger button + dropdown. Is there a way to disable this?

**Comment by aglaganov** [comment]
Hi! Can I have tabs with responsiveness but without switching?

**Comment by macliems** [comment]
If I understand it correctly, you want to keep the animation on the tab, but you want to controle the tabs with your script, so that clicking on them does nothing? If so, use
`$('#yourtabscontrol a').on('click', function(e) {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    return false;
                                });`

**Comment by Eduardodmb** [comment]
> please use data-uk-switcher instead of data-uk-tab, with the same settings. example: http://jsfiddle.net/bHCfU/2/

This solutions works perfectly!

**Comment by abo-github** [comment]
well guys ... could some give me a hint, how to solve my problem?

```
<div class="uk-margin-medium-top">
        <ul class="uk-tab-right uk-list-large" uk-tab="connect: #component-tab-right; animation: uk-animation-fade">
            <li><a href="">Long Title</a></li>
            <li><a href="">Longer Title</a></li>
            <li><a href="">Very Long Title</a></li>
            <li><a href="">Longest Title</a></li>
        </ul>
 </div>
```

When my browser window is smaller than 960px, the switcher switches to horizontal view. But I want that the list to be always arranged vertically.
