### ISSUE TITLE
3.0.0-beta.22 Table column width modifier not working in Firefox

### ISSUE THREAD

**Issue by mktcode** [uikit/uikit#2660]
http://codepen.io/anon/pen/wdymvr

Works in Chromium 58
Doesn't work in Firefox 53
(Linux Mint 18)

**Comment by florianletsch** [comment]
It appears that `calc()` fails when used on a `<td>` element or something like that.

Looks like a Firefox bug to me? Haven't found anything specific about this one yet. Any ideas?
