### ISSUE TITLE
UIKit docs website is down

### ISSUE THREAD

**Issue by keeferrourke** [uikit/uikit#2661]
### UIkit version

3.0.0-beta.22

### Browser
All

### Reproduction Link

[getuikit.com/docs](getuikit.com/docs)

### Steps to reproduce
Attempt to visit website.
Check [is it down right now](http://www.isitdownrightnow.com/getuikit.com.html).

### What is Expected?
The website should be online, so that the docs are available for reference.

### What is actually happening?
The website is down.

**Comment by florianletsch** [comment]
Yes, currently running some maintenance. Will be back soon. If you need to access the docs in the meantime, maybe browse the markdown directly: https://github.com/uikit/uikit-site/tree/develop/docs/pages

**Comment by keeferrourke** [comment]
Looks like it's back up! Thanks :) Just wanted to bring this to attention in case it was actually something wrong. Cheers!
