### ISSUE TITLE
3.0.0-beta.22 uk-spinner not working in React

### ISSUE THREAD

**Issue by xanderberkein** [uikit/uikit#2663]
### Version

- **uikit** 3.0.0-beta.22
- **react** 15.4.2
- **jquery** 3.2.1

### Steps to reproduce

1. Setup a React Project 
2. Install uikit and jquery [(see official uikit docs)](https://getuikit.com/docs/webpack)
3. Try to render a spinner: `<div data-uk-spinner></div>`

### What is Expected?
Spinner gets rendered

### What is actually happening?
Spinner doesn't get rendered and following error gets thrown:
`Uncaught (in promise) TypeError: Cannot read property 'setAttribute' of undefined`
refering to
`svg.setAttribute('viewBox', ("0 0 " + (this$1.width) + " " + (this$1.width)));`
at ~/uikit/dist/js/uikit.js?1d73 line 3755

### Screenshot of Console
![image](https://cloud.githubusercontent.com/assets/10937632/25943634/d3440812-3640-11e7-9aaa-6a3d688d74d9.png)

**Comment by sumanion** [comment]
I've used the spinner with react today and it is working fine.

Use it this way:

```js
<span data-uk-spinner={''} />
```

**Comment by xanderberkein** [comment]
This seems to do the trick. Thanks!

**Comment by janwiemers** [comment]
this one just made my day 💯 thanks @sumanion

**Comment by jrlmontejo** [comment]
I think removing the braces makes it cleaner:
```
<span data-uk-spinner="" />
```
