### ISSUE TITLE
UIkit Beta *.scss files complete?

### ISSUE THREAD

**Issue by inseldesign** [uikit/uikit#2664]
### UIkit version

3.0.0-beta.22

Just realised that the "inverse"-sass file is more or less empty. Would be cool to have SASS and LESS version INLINE 💯 

Thanks.

**Comment by stanleyxu2005** [comment]
I have the same feeling. I checkout 3.0.0-beta.27 and build it. I also create a site.scss regarding the official document. However, I think the look and feel are different. Need to know, whether it is still incomplete and when it will be confirmed?
