### ISSUE TITLE
** Icon request ** Phone! :)

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2666]
We know that uikit team it´s super modern and cutting edge :), but it would be nice to have a classic Phone icon... mainly to differentiate telephone number from cell phone number.

Thanks.

**Comment by haydnjames** [comment]
There is one already :)

Receiver - It was added a few versions again, for some reason it doesn't show in the main documentation but it can be seen on the test page :)

https://getuikit.com/assets/uikit/tests/icon.html

**Comment by zzseba78** [comment]
Thanks, closing this.
