### ISSUE TITLE
Icons documentation - add uikit-icons Javascript requirement

### ISSUE THREAD

**Issue by umphy** [uikit/uikit#2667]
### UIkit version

3.0.0-beta.22

### Browser
Any

### What is Expected?
No mention of the required uikit-icons.js in the [Icons doc](https://getuikit.com/docs/icon), only mentioned in the [Javascript doc](https://getuikit.com/docs/javascript).

I think it would be helpful to have that information right there on the Icons doc, as I have wasted time trying to figure out why the icons weren't showing, and I don't think I'm the only one.

**Comment by florianletsch** [comment]
You're right, I'll add to the doc.

**Comment by florianletsch** [comment]
I've added the instructions. Will go online when we next deploy the website. Thanks for pointing this out.
