### ISSUE TITLE
3.0.0.-beta.22 Missing several important classes

### ISSUE THREAD

**Issue by doopingen** [uikit/uikit#2668]
New to your tool and I'm pissed. 

You published version 3.0.0-beta.22 on the front page and it's missing several important classes that you have documented which is killing me. 

Version 2-27-3 of uikit.css has 1764 published rules
Version 3.0.0 beta22 of uikit.css has only 1275 rules

Important classes like **uk-block** are not there any longer. All of your published documentation is based on older versions with those options. 

Someone needs to either update the documentation QUICKLY or get the beta off the site. I can't believe I'm actually having to submit an issue like this. For a tool as powerful and revered as this to be so structurally flawed..

**Comment by Riddler84** [comment]
The "block" component was replaced with the "section" component. You have to change your markup if you want to use the new version. I don't really understand your problem, the v2 documentation is still accessible and downloadable via the uikit frontpage, if you don't want to use the beta.

**Comment by doopingen** [comment]
I'm new to this and wanted to run it through some dev testing. I now realize that there is so much different between the two versions. The site had me on the old docs not the new hence the reason I was confused. Closing
