### ISSUE TITLE
uk-form-custom is setting 2x width in window

### ISSUE THREAD

**Issue by madhudskumar** [uikit/uikit#2672]
### UIkit version

3.0.0-beta.22

### Browser
Microsoft edge

### Reproduction Link

![image](https://cloud.githubusercontent.com/assets/8987882/26037297/0fbb3d5e-390e-11e7-9dd3-f684c5c19345.png)

### Steps to reproduce
uk-form-custom is somehow setting 2x width in Microsoft edge , it works fine on chrome and firefox

### What is Expected?
can I please Get a fix 

### What is actually happening?
No idea !

**Comment by janschoenherr** [comment]
Is this still an issue?

**Comment by madhudskumar** [comment]
Nope! The issue is resolved!
