### ISSUE TITLE
Events not working for Switcher

### ISSUE THREAD

**Issue by germansokolov13** [uikit/uikit#2673]
UIkit 3.0.0-beta.22
### Browser
Google Chrome 51.0.2704.106 (64-bit), Linux
### Reproduction Link
https://codepen.io/anon/pen/EmRWZx
### Steps to reproduce
Click the tabs
### What is Expected?
Each click should trigger a popup message with alert.
### What is actually happening?
Alert won't fire.

**Comment by fabien** [comment]
See: https://codepen.io/anon/pen/MmXRNg - the event is only triggered on the container of the items that are switched. Perhaps the same event should also be triggered on the switcher itself, though. I find it counter-intuitive to not have any events there.

**Comment by germansokolov13** [comment]
There is `uk-switcher` attribute put on the list of options. So the plugin is bound to that tag. So I thought that must be the tag which triggers the event. If not then the docs are incomplete.

**Comment by florianletsch** [comment]
You're right. I think we'll need to update the docs for this.

I will also put it on our list to dicuss if the event should be triggered on both containers.

**Comment by TomJacobsUK** [comment]
Think my issue is partly related to this, returning false on `beforehide` and `beforeshow` for the switcher doesn't stop Subnav or Tabs from activating.

https://codepen.io/anon/pen/LQEbQo

**Comment by AhmadFahmawi** [comment]
the <a> tag return me to the # page, dose not show items,, anyone can help me please !
