### ISSUE TITLE
3.0.0-beta.22 Accordion not working properly on Safari

### ISSUE THREAD

**Issue by danielpigan** [uikit/uikit#2674]
### UIkit version

3.0.0-beta.22

### Browser
Results from http://www.whoishostingthis.com/tools/user-agent/
**Desktop** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
**iOS** Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1

### Reproduction Link
https://getuikit.com/docs/accordion

### Steps to reproduce
1. Use accordion preview available on page.

Same happens on my page when I'm using UIkit accordion too.

### What is Expected?
1. Accordion is easily interactable.
2. Accordion animates well.

### What is actually happening?
[reproduction_footage.zip](https://github.com/uikit/uikit/files/1000276/reproduction_footage.zip)
**Desktop**
Ad 1. (minor) No problems with that.
Ad 2. (minor) Sometimes it jumps like if whole accordion was expanded at the beginning of animation and later on it start to unfold from closed state.
**iOS**
Ad 1.1. (major) Accordion items can be toggled only via long tap.
Ad 1.2. (minor) When interacting with accordion items whole accordion is pressed (visual feedback with grey background).
Ad 2. No problem with that.

**Comment by zzseba78** [comment]
Same problem here with safari 10.1, the accordion jumps.
In IPad (Safari) i see visual feedback with grey background too.

**Comment by janschoenherr** [comment]
Has this been resolved?
