### ISSUE TITLE
Library on cdnjs.com

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#2676]
Latest UIkit 2.27.3 release has not been published on [cdnjs.com](https://cdnjs.com/libraries/uikit).
Any particular reason for this choice or it's simply an oversight?

Thanks.

**Comment by hendrikbehncke** [comment]
Hi, cdnjs.com should update itself normally. We will check it out, thanks.

**Comment by florianletsch** [comment]
They have added in the meantime and 2.27.3 is available now (along with 2.27.4). 

Also, this is kind of a duplicate of #2678, since we are currently discussing the auto-update functionality with them. 

Closing this one now, thanks for reporting.
