### ISSUE TITLE
** Create a Official UIkit Code Blocks Repository**

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2682]
Since UIkit it´s getting better and better, maybe it´s a good idea to create a Code Blocks repository for uikit 3, like it was uikitplay, but official.

Maybe a section in the docs, ordered by categories, or a Official Codepen account for this matter.
So people have a place to publish, or check some code examples made by users, it´s a great way to learn, and to find solutions.

It should be "Self-regulating" by the users, so it doesn´t take the uikit team time, they have enought work already.

**Comment by bbashy** [comment]
This is https://github.com/uikit/uikit-site related, right?

**Comment by zzseba78** [comment]
Yes, i will move it.
