### ISSUE TITLE
3.0.0-beta.23 - uk-height-viewport attribute not working properly in Firefox

### ISSUE THREAD

**Issue by laSyntez** [uikit/uikit#2683]
### UIkit version

3.0.0-beta.23

### Browser
Firefox 53.0.2
### Reproduction Link

https://codepen.io/anon/pen/oWaJqr

### What is Expected?
The container with the "uk-height-viewport" attribute should fill the height of the entire viewport 
### What is actually happening?
The attribute has no effect on the container's height whereas the behaviour is normal in Chromium Version 58.0.3029.96

**Comment by zzseba78** [comment]
If you want the element to fill the viewport, remove `expand: true`, just use `uk-height-viewport`
It works fine.
But, height expand seems to doesn´t work in Firefox...
https://getuikit.com/assets/uikit/tests/height-expand.html

**Comment by laSyntez** [comment]
Fixed in 3.0.0-beta.24 version.
