### ISSUE TITLE
CSS/JS V3 file size vs. V2

### ISSUE THREAD

**Issue by Madebym** [uikit/uikit#2685]
I am currently redesigning one site I did a few years ago. It uses V2 of Uikit, so I was thinking of maybe updating it to V3. To test new features and do the redesign a bit more fun.

But then I saw that both the minified CSS and JS files are much larger for newer version.

CSS: 245kb vs 100kb
JS: 93kb vs 52kb

I know the difference is not that much, but on this particular site page load speed is essential to everything.
I thought that V3 was supposed to be leaner :) 

I know that this is really not an issue, but I am wondering how much benefit would I gain from V3, knowing that the files sizes are more than double, and I would like to avoid that.

**Comment by askaoru** [comment]
Currently the v3 is still under beta and is not yet feature complete. So i guess the file size is not yet completely optimised. If your site is a production site i would suggest to stay with v2 until v3 stable will be released later.

**Comment by saschadube** [comment]
You are comparing apples and oranges 😉 When comparing file sizes of any library make sure both have the same feature set. The CSS and JS files in the UIkit 2 and UIkit 3 have a different feature set. Here is a quick break down of what you have to do to make a fair comparision:

1. Always compare gzipped files sizes. Here is a [tool](http://refresh-sf.com/) to do so.

2. UIkit 2 has 2 themes (Almost Flat or Gradient) while UIkit 3 just has one default one. They are different. So just lets compare the core.

3. The UIkit 3 CSS file includes all components, so it is ready to use for everyone. This has changed compared to UIkit 2 where you had to include additional CSS to get all components. You have to compile a custom version of UIkit 3,  if you don't want all components. This is pretty easy through Less imports. To compare UIkit 2 to Uikit 3 we have to remove the following components: form-range, tile, spinner, totop, marker, accordion, placeholder, progress, sortable, countdown.

4. UIkit 3 is also coloring nearly all components for the inverse color of your theme. This means buttons, forms, etc also look great on black backgrounds. UIkit 2 didn't do that. So you have also to disable the inverse color mode by doing ```@inverse-global-color-mode: none;```

Result
----
So let's have a look:
UIkit 2 (uikit.min.css) is Gzip: **19.63 KB**
UIkit 3 (custom build) is Gzip: **14.20 KB**

So the CSS file of UIkit 3 is 27% smaller than UIkit 2. The feature set is now nearly the same, though UIkit 3 has still some more features on board.

**Comment by zzseba78** [comment]
UIkit sizes, js it´s the latest version Beta 23 and .js icons, and css it´s compiled with the required components and minifed ( from less version ).
It´s good to point that with the v3 don´t have to load the +85kb from FontAwesome.

So, whole site styles are 17.9kb ( gzipped ), the half size of the tiny 200px thumbnail attached at the bottom :)

![captura de pantalla 2017-05-20 a la s 22 21 06](https://cloud.githubusercontent.com/assets/5558563/26280446/cc2aedae-3daa-11e7-967a-0768edfaa580.png)

![captura de pantalla 2017-05-20 a la s 22 20 30](https://cloud.githubusercontent.com/assets/5558563/26280447/cd91666e-3daa-11e7-9bd1-f5cba2950473.png)

![chinchilla_cat_watching ap-auuapp-th](https://cloud.githubusercontent.com/assets/5558563/26280477/9a077c0a-3dac-11e7-9bbb-4ebeb989dccb.jpeg)

**Comment by Madebym** [comment]
@saschadube Thanks for the clarification. Guess I asked the question without doing my homework first:)
