### ISSUE TITLE
How unbind sticky from element?

### ISSUE THREAD

**Issue by yarara** [uikit/uikit#2688]
Hello.
I need unbind sticky from element.

**Comment by aarongerig** [comment]
Please always look at the docs (https://getuikit.com/docs/javascript) before asking such questions: 

If you need to make sure a component is properly destroyed, for example upon removal from the DOM, you can call its `$destroy` function.

```js
// Destroys the component. For example unbind its event listeners.
component.$destroy();

// Also destroys the component, but also removes the element from the DOM.
component.$destroy(true);
```
