### ISSUE TITLE
[Feature request] Provide "ghost buttons" in uikit3

### ISSUE THREAD

**Issue by hrstoyanov** [uikit/uikit#2689]
Can add you "ghost buttons" variation to buttons (Google the term). Ghost buttons are in high demand these days!

**Comment by bbashy** [comment]
Already has it? Just use `uk-button-default` and it will have a transparent background.

```
.uk-button-default {
	background-color: transparent;
	color: #222;
	border: 1px solid #e5e5e5;
}
```

**Comment by zzseba78** [comment]
Yes, the Theme version comes with transparent background by default. the Core version have the muted background.
https://getuikit.com/assets/uikit/tests/button.html

**Comment by hrstoyanov** [comment]
Well ... what I was looking for is something as straightforward as just: 
```
.uk-button-ghost
```

**Comment by bbashy** [comment]
@hrstoyanov There's a few options;

* Hook into the button mixin to add your own styles for a class.
* Create a PR with the proposal and see if it gets merged.

**Comment by saschadube** [comment]
```uk-button-ghost``` has the style in the name. Then we could have ```uk-button-gradient``` or even ```uk-button-blue```. The clue in UIkit is, that the button class does not contain any style related naming. It's ```uk-button-default``` to indicate the standard button or ```uk-button-primary``` to indicate a primary action.

**Comment by hrstoyanov** [comment]
That is a loaded statement . Not sure why you think ghost buttons are are
slight style variations, given how important they are nowadays?

Get a clue from Semantic UI buttons:

 https://semantic-ui.com/elements/button.html


/Hristo Stoyanov

On May 26, 2017 5:55 AM, "Sascha" <notifications@github.com> wrote:

uk-button-ghost has the style in the name. Then we could have
uk-button-gradient or even uk-button-blue. The clue in UIkit is, that the
button class does not contain any style related naming. It's
uk-button-default to indicate the standard button or uk-button-primary to
indicate a primary action.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uikit/uikit/issues/2689#issuecomment-304275530>, or mute
the thread

**Comment by bbashy** [comment]
@hrstoyanov You can get any styling you want by using hooks etc in your theme file.

_Stops every style under the sun added like Semantic UI._

**Comment by ruchern** [comment]
@hrstoyanov Then use Semantic UI?

**Comment by hrstoyanov** [comment]
@bbashy
I will take a look at using the theme files as long as:
- I don't have to deal with saas/less
- I can still download from the public CDN the official artifacts and don't have to deploy my own.

I am actually better off buying one of the PRO themes, but they seem far from complete.

**Comment by bbashy** [comment]
You will have to use sass or less unless you just make your own CSS in a file or HTML tag
