### ISSUE TITLE
v2.27.4 not available on npm

### ISSUE THREAD

**Issue by piotr-cz** [uikit/uikit#2690]
### UIkit version

2.27.3

### Browser
nodejs v6.9.1

### Reproduction Link

none

### Steps to reproduce

```
npm install --save uikit@2.27.4
```

### What is Expected?
Installation of v2.27.3 works properly

### What is actually happening?
I'm getting an npm error `ETARGET`

```
No compatible version found: uikit@2.27.4
Valid install targets:
3.0.0-beta.24, 3.0.0-beta.23, 3.0.0-beta.22, 3.0.0-beta.21, 3.0.0-beta.20, 3.0.0-beta.19, 3.0.0-beta.18, 3.0.0-beta.17, 3.0.0-beta.16, 3.0.0-beta.15, 3.0.0-beta.14, 3.0.0-beta.13, 3.0.0-beta.12, 3.0.0-beta.11, 3.0.0-beta.9, 3.0.0-beta.8, 3.0.0-beta.6, 3.0.0-beta.5, 3.0.0-beta.4, 3.0.0-beta.2, 3.0.0-beta.1, 2.27.3, 2.27.2, 2.27.1, 2.27.0, 2.26.4, 2.26.3, 2.26.2, 2.26.1, 2.26.0, 2.25.0, 2.24.3, 2.24.2, 2.24.1, 2.24.0, 2.23.0, 2.22.0, 2.21.0, 2.18.0
```

**Comment by aarongerig** [comment]
Yeah, you typed `uikit@2.27.4` instead of `uikit@2.27.3`. Please try again...

**Comment by piotr-cz** [comment]
Yes, I'd like to install a [2.27.4](https://github.com/uikit/uikit/releases/tag/v2.27.4-src) release)

**Comment by florianletsch** [comment]
True, the 2.27.4 release is not published on npm yet, we'll fix that.

**Comment by florianletsch** [comment]
2.27.4 is published on npm now, thanks for letting us now.

**Comment by piotr-cz** [comment]
Thanks
