### ISSUE TITLE
OffCanvas only Dark

### ISSUE THREAD

**Issue by AlessioGiacobbe** [uikit/uikit#2693]
I want to use the OffCanvas for Mobile navigation in my website. I have used this code at the moment;
```html
<a href="#menuNav" uk-toggle></a>
        <div id="menuNav" uk-offcanvas="mode: push; overlay: true" class="uk-light">
            <div class="uk-offcanvas-bar">
              <ul class="uk-nav uk-nav-default">
                <li>
                  <a href="">something</a>
                </li>
                <li>
                  <a href="">something else</a>
                </li>
              </ul>
                <button class="uk-offcanvas-close" type="button" uk-close></button>
            </div>
        </div>
```
The problem is that the navbar is always dark, ignoring the uk-light class. Also, the mode push is being ignored and it remains in the default mode. Overlay works.

Thank you guys.

**Comment by zzseba78** [comment]
Did you wrap  your content with `.uk-offcanvas-content`? It´s required if you want to use the push mode ( [docs](https://getuikit.com/docs/offcanvas#off-canvas) ). And yes, seems that offcanvas doesn´t have the inverse mode, it would be nice to have it, and since nav component have this mode i don´t think it will be a code bloat.

**Comment by aarongerig** [comment]
If you're using less or sass for compiling UIkit, adjust the following variables:

```css
// less syntax
@offcanvas-bar-background:                      #fff;
@offcanvas-bar-color-mode:                      dark;

// sass syntax
$offcanvas-bar-background:                      #fff;
$offcanvas-bar-color-mode:                      dark;
```

**Comment by AlessioGiacobbe** [comment]
Can i just modify the precompiled css?

**Comment by Riddler84** [comment]
You can simply overwrite the CSS rule with your own.
```css
.uk-offcanvas-bar {
    background: #fff;
}
```

**Comment by erikjara** [comment]
I have the same problem, some solution?

**Comment by unistudioco** [comment]
### I found a good solution!! no need to compile SASS or LESS
First of all you have to added `selPanel` option to `uk-offcanvas=""` attribute with a custom class for ex:

`data-uk-offcanvas="flip: true; overlay: true; mode: reveal; selPanel: .uk-offcanvas-bar-light;"`

> I am confused as to why they did not mention this useful option in their [documentation](https://getuikit.com/docs/offcanvas#component-options)! 🤔

And then change the class `uk-offcanvas-bar` to the custom one `uk-offcanvas-bar-light`

Finally you have to re-style your custom class with the same css that have been used on the dark one but change the colors as you want! for ex:

```
.uk-offcanvas-bar-light {
    position: absolute;
    top: 0;
    bottom: 0;
    left: -270px;
    box-sizing: border-box;
    width: 270px;
    padding: 20px 20px;
    background: #f8f8f8;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
  }
  .uk-offcanvas-bar-animation {
    transition: left 0.3s ease-out;
  }
  @media (min-width: 960px) {
    .uk-offcanvas-bar-light {
      left: -350px;
      width: 350px;
      padding: 40px 40px;
    }
  }
  .uk-offcanvas-flip .uk-offcanvas-bar-light {
    left: auto;
    right: -270px;
  }
  .uk-offcanvas-flip .uk-offcanvas-bar-animation {
    transition-property: right;
  }
  .uk-offcanvas-flip .uk-open > .uk-offcanvas-bar-light {
    left: auto;
    right: 0;
  }
  @media (min-width: 960px) {
    .uk-offcanvas-flip .uk-offcanvas-bar-light {
      right: -350px;
    }
  }
  .uk-offcanvas-flip .uk-offcanvas-reveal .uk-offcanvas-bar-light {
    left: auto;
    right: 0;
  }
  .uk-offcanvas-reveal .uk-offcanvas-bar-light {
    left: 0;
  }
  .uk-open > .uk-offcanvas-bar-light {
    left: 0;
  }
```

_This solution will prevent invert some components styles!! which is the important thing for me as well 🥇_ 

**Hope it helps!**
