### ISSUE TITLE
404 on theme page

### ISSUE THREAD

**Issue by QuentinWatt** [uikit/uikit#2694]
Hi there

### UIkit Website version 3
https://getuikit.com/docs/theme --> Leads to a 404

**Comment by saschadube** [comment]
Where did you find the link?

**Comment by QuentinWatt** [comment]
On this page: https://getuikit.com/docs/installation
Under the heading: "Compile from Github source"

The linked text is: "custom UIkit theme"

**Comment by florianletsch** [comment]
Thanks. Fixed it, will go up with the next deploy. https://github.com/uikit/uikit-site/commit/c0554f9c4ed72658e36f19c29b2f9409310aabad
