### ISSUE TITLE
Conflict uikit.js and vue.js

### ISSUE THREAD

**Issue by wdda** [uikit/uikit#2697]
### UIkit version

3.0.0-beta.24

### Browser
Chrome

### Reproduction Link
https://jsfiddle.net/mq0ovszo/

### Steps to reproduce
Click the button at the rate of about 1 click per second. Look at the console.
It's not the best example, you need to click at a certain speed and to be careful.

### What is Expected?
One click = one event

### What is actually happening?
One click = two event

**Comment by florianletsch** [comment]
Happened to me as well, when I clicked in the right rhythm.

This... is... weird.

**Comment by janschoenherr** [comment]
Is this resolved with Beta 25?

**Comment by florianletsch** [comment]
Looks like it. Can't reproduce it anymore: https://jsfiddle.net/mq0ovszo/2/

**Comment by wdda** [comment]
Great! Example Florianletsch working correctly.
