### ISSUE TITLE
pulling uikit in from - npm i uikit --save > fonts error

### ISSUE THREAD

**Issue by sononix** [uikit/uikit#2698]
pulling in uikit using npm and calling less from wekpack using 

@import "../node_modules/uikit/src/less/uikit.less";

generates an error
These relative modules were not found:

* ../node_modules/uikit/src/less/fonts/fontawesome-webfont.woff2 in ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/less-loader/dist?{"sourceMap":false}!./custom/theme-site.less
* ../node_modules/uikit/src/less/fonts/fontawesome-webfont.woff in ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/less-loader/dist?{"sourceMap":false}!./custom/theme-site.less
* ../node_modules/uikit/src/less/fonts/fontawesome-webfont.ttf in ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/less-loader/dist?{"sourceMap":false}!./custom/theme-site.less

moving the fonts folder under less folder fixes the issue
is this the correct way of mounting uikit within a less environment - there must be a better way 

tks
M

**Comment by florianletsch** [comment]
I assume your question applies to UIkit 2, as the webfont is not present in UIkit 3 anymore. 

You can use the Less variable `@icon-font-path` to point to the directory with the font files.

Here it is in the core files: https://github.com/uikit/uikit/blob/v2/develop/src/less/core/icon.less#L25

Just overwrite its value in you own Less and then compile.
