### ISSUE TITLE
Icons doesn't work in /test/ folder when opened using a simple static webserver

### ISSUE THREAD

**Issue by gensmann** [uikit/uikit#2699]
### UIkit version

3.0.0-beta.24

### Browser
All

### Steps to reproduce
* compile uikit with custom themes and icons
* start a webserver in uikit folder
* open /test/ in webbrowser
* View console in inspector

### What is Expected?
That the testfiles loads without errors in the browser

### What is actually happening?
The browser cannot find the custom themes icons throwing a 404.

The reason is that the theme.json file has a wrong path to the files:

The CSS file path is starting with: "../dist/css...." the icon path is: "dist/js...." missing the jump to the parent directory.

The line responsible seems to be in build/less.js:

    if (fs.existsSync(`dist/js/uikit-icons-${theme}.js`)) {
        themes[theme].icons = `dist/js/uikit-icons-${theme}.js`;
    }

it should probably be:

    if (fs.existsSync(`dist/js/uikit-icons-${theme}.js`)) {
        themes[theme].icons = `../dist/js/uikit-icons-${theme}.js`;
    }

**Comment by dasdeck** [comment]
This issue seems to have been resolved some time ago as I can not reproduce the behaviour.
1. adding custom icon
2. npm run compile
3. open */test on a local webserver

4. all looks good!

Feel free to reopen this issue if the issue persists.
