### ISSUE TITLE
 parallax bg get incorrect values if reload not in top of page

### ISSUE THREAD

**Issue by RicardoAbad** [uikit/uikit#2702]
### UIkit version

3.0.0-beta.24

### What is Expected?
Sould get the initial values?... i think the plugin gets the suposed values and add again the initial values ... i'm not sure...

### What is actually happening?
If i reload the page at center, or bottom, or in other place than top, the results for the parallax are inexpected. For example, the background initialy is set to "bgx: -1000; bgy: 900;", and if the page loads at top position works well. But if i reload the page in other position (for example at 2000px scrolled) the backgound is translated to -x  too too much as  the y position too

**Comment by RicardoAbad** [comment]
i think  on refresh or reload page, the calculations are based in the actual position on the body scroll, not in the initial values...

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
