### ISSUE TITLE
button icons in vertical navigation lose inline-flex instruction

### ISSUE THREAD

**Issue by timothynott** [uikit/uikit#2704]
### UIkit version
3.0.0-beta.24

### Browser
Mac 10.12.5
Chrome 58.0.3029.110 (64-bit)
Canary Version 61.0.3118.0 (Official Build) canary (64-bit)
Edge 15 on Windows 10

### Reproduction Link
https://codepen.io/timothynott/pen/QgWXre

### Steps to reproduce
Add uk-icon-button class to an a tag inside ul with uk-iconnav classes

### What is Expected?
Icon should be centered in circle as expected in uk-icon-button style

### What is actually happening?
Icon appears in top left of the circle

### Possible fix
```
.uk-iconnav .uk-icon-button {
  display: inline-flex !important;
  display: -ms-inline-flexbox !important;
  display: -webkit-inline-flex !important;
}
```

**Comment by Propaganistas** [comment]
Also happens in regular nav lists:

```html
<ul class="uk-nav uk-nav-default">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
    <li><a href="#" class="uk-icon-button" uk-icon="icon: facebook"></a></li>
</ul>
```

**Comment by Petar-np** [comment]
Same thing here, and solution is what you provided as possible fix

**Comment by janschoenherr** [comment]
Seems to be fixed.
