### ISSUE TITLE
[Flex] IE 10 & 11 (Edge) uk-flex-center right-aligns a contained uk-container

### ISSUE THREAD

**Issue by ratiofu** [uikit/uikit#2706]
### UIkit version
3.0.0-beta.24

### Browser
`navigator.userAgent`:
- *Edge*: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; `[...]` rv:11.0) like Gecko
- *IE 10*: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; `[...]`)

### Reproduction Link
https://codepen.io/anon/pen/vZEvKV
```
<div class="uk-flex uk-flex-center uk-background-secondary">
  <div class="uk-container uk-background-primary">
    <p class="uk-padding uk-text-warning">
      I should be in the center and middle of the page, right?
    </p>
  </div>
</div>
```

### Steps to reproduce
Put a `uk-container` inside a `uk-flex uk-flex-center` parent

### What is Expected?
Container is rendered in the center of the page

### What is actually happening?
Container is right-aligned

### Notes
- removing `uk-flex-center` results in the container to be centered
- in my example, I put the container where it is to get the automatic margin & width adjustment; perhaps there's a better way to accomplish this?

**Comment by zzseba78** [comment]
Yes, this happens to me some time ago, a Slideshow with full width image, and the container inside with some data, the container was centered  vertical and horizontal, and in Edge and IE 10 the content appears at the right...

**Comment by zzseba78** [comment]
Has this been fixed?

**Comment by luxlogica** [comment]
@ratiofu IMHO, the Container component is not really meant to be used as a generic device for centering blocks of content anywhere in your layout. You can actually just use the flex component for that - a container is not needed at all.

The container is meant to be used inside a `<section>` element, as the top-level container of the overall layout content of your page. If you want, you could place a Flex component inside a container - e.g., if you wanted to equally spread items in a gallery image across the entire width of the container, which will automatically change at different breakpoints. 

But placing a container inside a flex is probably not intended usage, and this is likely why you're experiencing issues.

**Comment by ratiofu** [comment]
Agreed. There are many other ways to achieve this and I ended up implementing one of them. I am fine with closing this.

**Comment by saschadube** [comment]
@luxlogica answer is 👍
