### ISSUE TITLE
Can't load icons with webpack

### ISSUE THREAD

**Issue by lukashl** [uikit/uikit#2709]
in docs:

```
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';

// loads the Icon plugin
UIkit.use(Icons);
```

but after install, in nodemodules can't find uikit/dist/js/uikit-icons

**Comment by ruchern** [comment]
Add this below the imports

```javascript
window.UIKit = UIKit
```

**Comment by lukashl** [comment]
after npm install uikit in nodemodules save 2.27.4 version

**Comment by al-liu** [comment]
yes, you should use `npm install --save uikit@3.0.0-beta.24`.

**Comment by lukashl** [comment]
thanks for yours help, now all works !

**Comment by PululuK** [comment]
Hello 
In my case, I'm using TypeScript.
You can fixe that using `require` instead of `import` or just add `esModuleInterop => true` in you` tsconfig.json`
