### ISSUE TITLE
Color uk-divider-icon

### ISSUE THREAD

**Issue by FrancoisDevFrontEnd** [uikit/uikit#2710]
### UIkit version

3.0.0-beta.24

### Browser
Chrome Version 57.0.2987.110 (64-bit)

### What is actually happening?

I have a request, in fact currently we can color the border of uk-divider-icon component but, the circle icon is a background apply, and in fact it can't be change easly.

**Comment by saschadube** [comment]
Just set the divider icon color. To do so add the following code to your custom UIkit theme

```less
@divider-icon-color:                            @global-border;
```
