### ISSUE TITLE
uikit.min.js no longer recompiled by npm/node

### ISSUE THREAD

**Issue by bassmanpaul** [uikit/uikit#2716]
From what I can tell the `build/build.js` no longer minifies the JS files when compiling. This means that if the `dist/uikit.min.js` is removed or modified (e.g. for `prefix` reasons) then the minified files are either not created or updated.

This was working correctly in **3.0.0-beta.23/24**-ish!

### UIkit version
3.0.0-beta.25

### Steps to reproduce

Run `npm run compile` in the command line (as recommended in the [docs](https://github.com/uikit/uikit/blob/develop/README.md))

###  This should compile:
```
dist/uikit.js
dist/uikit.min.js
...
```

### What is actually happening?

```
dist/uikit.js
...
```

**Comment by dasdeck** [comment]
Hi! Is this still an issue for you?
I can not recreate the behavior you are describing.
The whole dist directory gets recreated when I type npm run compile.
Feel free to reopen this if the issue persists with the latest tip.

Cheers!

**Comment by bassmanpaul** [comment]
Hey,

Thanks for getting back to me.

I've just tried updating & re-running the build and the minified JS is still being left out. Are you able to replicate this?

Thanks,

**Comment by dasdeck** [comment]
hmm. can you confirm the version or commit you are on?

Cheers!

**Comment by bassmanpaul** [comment]
Hi,

I'm running: 3.0.0-beta.35 (a52e324c8bb13435357e9e0b43b49cc82d72bab7).

Thanks!
