### ISSUE TITLE
3.0.0-beta.25 - checkboxes and radio buttons appearance are different in Firefox

### ISSUE THREAD

**Issue by laSyntez** [uikit/uikit#2719]
### UIkit version

3.0.0-beta.25

### Browser
Firefox 53.0.3
### Reproduction Link

https://codepen.io/anon/pen/RgRvQJ

### What is Expected?
An appearance similar to that in browsers like Chromium or Opera

### What is actually happening?
UIkit theme has no effect on their appearance

**Comment by janschoenherr** [comment]
Please see https://github.com/uikit/uikit/issues/2853
