### ISSUE TITLE
Prevent components from capitalizing text case.

### ISSUE THREAD

**Issue by randyyaj** [uikit/uikit#2722]
Prevent components from capitalizing text by default or provide a class to turn off text modifiers uk-text-normal.
Seeing this with badges and labels.

<div class="uk-label uk-text-normal">

**Comment by florianletsch** [comment]
This is a custom styling thing, I would not put this in UIkit core. But you can simply achieve this yourself:

If you use the Less sources, you just need to set `@label-text-transform: none` to disable the uppercase for labels. For Badges, the default behavior looks like it doesn't show uppercase anyway: https://codepen.io/anon/pen/YQGpVr
