### ISSUE TITLE
Events not firing on sticky

### ISSUE THREAD

**Issue by rossity** [uikit/uikit#2724]
### UIkit version

3.0.0-beta.25

### Browser
Chrome

### Reproduction Link

[Link showing issue](https://codepen.io/anon/pen/RgRemq?editors=1111)
[Link where expected behavior is produced](https://codepen.io/Riddler84/pen/mwEaMR?editors=1011)

### Steps to reproduce
In the first CodePen, as you scroll you should see the events firing in the console. However, they never do.

In the second CodePen it works, for some reason only after giving it a "top" parameter.

**Comment by janschoenherr** [comment]
I believe this to be resolved.
