### ISSUE TITLE
uk-width-expand-* doesn't work with with any other width class which has a higher breakpoint.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2726]
### UIkit version

3.0.0-beta.25

### Reproduction Link

https://codepen.io/zzseba78/pen/rwNxpv

### Steps to reproduce
Resize the browser window width and see the 3rd column, the column 3 should be uk-width-auto@l on large screen, but it keeps expanding.
### What is Expected?
Column 3 get uk-width-auto
### What is actually happening?
uk-width-expand-* doesn't work with with any other width class which has a higher breakpoint.

**Comment by saschadube** [comment]
Fixed with https://github.com/uikit/uikit/commit/c20ef70204d86bcdcc14a0aff93474e1a5368fd8
