### ISSUE TITLE
Switcher is not working when nav is placed after content

### ISSUE THREAD

**Issue by Darkless012** [uikit/uikit#2727]
### UIkit version
3.0.0-beta.25

### Browser
Latest Chrome

### Reproduction Link
https://jsfiddle.net/13dr9t88/

### Steps to reproduce
Place content before switcher nav (not working even with "connect")
```
<ul class="uk-switcher test-projects">
  <li>Hello!</li>
  <li>Hello again!</li>
  <li>Bazinga!</li>
</ul>

<ul class="uk-dotnav" uk-switcher="connect: test-projects">
  <li><a href="#">Item</a></li>
  <li><a href="#">Item</a></li>
  <li><a href="#">Item</a></li>
</ul>
```

### What is Expected?
It should be switching content.

### What is actually happening?
It is not switching content. See jsfiddle link

**Comment by zzseba78** [comment]
It works, you just forget to add the point to the class selector:
`uk-switcher="connect: .test-projects"`
Your previous example works because it takes the next element with .uk-switcher applied.
If you confirm that it works please close this issue.

**Comment by Darkless012** [comment]
Thanks! Indeed it is working. 
I would suggest editing the example then, because I was looking on example and not on the source-code later. 
https://getuikit.com/docs/switcher#connect-multiple-containers

**Comment by zzseba78** [comment]
Yes, good idea! The clearer the better.
