### ISSUE TITLE
uk-background-norepeat / uk-background-no-repeat classes

### ISSUE THREAD

**Issue by kvnxdev** [uikit/uikit#2732]
**UIkit version**: v3.0.0-beta.25
**Jumplink Code**: [uikit/src/less/components/background.less:59](https://github.com/uikit/uikit/blob/develop/src/less/components/background.less#L59)
**Jumplink Doc**: [uikit-site/blob/develop/docs/pages/background.md:no-repeat](https://github.com/uikit/uikit-site/blob/develop/docs/pages/background.md#no-repeat)

## Issue

It looks like the css class `uk-background-norepeat` is wrong named in the less or in the doc file. In the doc it says `uk-background-no-repeat` and `uk-background-norepeat`. I am not sure which way you want to go. Anyway, one of them should be fixed.

## Offtopic

As always awesome work! UIkit rocks!

**Comment by janschoenherr** [comment]
This seems to have been fixed, thanks.
