### ISSUE TITLE
Icons are not correctly colored in Edge.

### ISSUE THREAD

**Issue by laosb** [uikit/uikit#2734]
![image](https://user-images.githubusercontent.com/2545261/27423389-0e0ed8ba-56f7-11e7-96d9-2b0e53c2726b.png)

Edge version: 40.15063.0.0

**Comment by dandansoysauce** [comment]
I am getting this bug, can someone please provide a fix? 

FYI, when you put an SVG path inside a button with a color fill, it works perfectly well. I don't know what happens when I use UIKit's icons. Thanks

**Comment by saschadube** [comment]
Thanks for reporting. Will be fixed with the next UIkit version
