### ISSUE TITLE
UIkit 3-beta.25 Accordion breaks on multiple clicks

### ISSUE THREAD

**Issue by flyboarder** [uikit/uikit#2735]
### UIkit version
3.0.0-beta.25

### Browser
Chrome

### Reproduction Link
visible on the demo site

### Steps to reproduce
Rapidly click an accordion header

### What is Expected?
Open/close the accordion rapidly

### What is actually happening?
Window freezes and will either eventually respond or crash the browser.

**Comment by florianletsch** [comment]
Hm, I cannot seem to reproduce this...

I tried https://getuikit.com/docs/accordion on macOS and it worked in Chrome, Firefox and Safari.

Which OS are you using? Can you try again with any browser plugins disabled that could interfere?

Does anyone else experience this?

**Comment by zzseba78** [comment]
In macOs Sierra 10.12.
Works fine in Chrome, Firefox and Opera.
In Safari there is a quick "Jump" on the accordion clicked, and as you click the text gets selected.

![captura de pantalla 2017-06-23 a la s 11 43 43](https://user-images.githubusercontent.com/5558563/27487381-fa2c7ff0-5809-11e7-8a92-6ea2f14c9e75.png)

From IPad - Safari there is the quick jump to, and the whole accordion container blinks.

**Comment by Riddler84** [comment]
I cannot confirm this. I'm using Win 10 and Chrome. And i have clicked very rapidly ;)

**Comment by flyboarder** [comment]
Issue seems to be resolved in our app.
