### ISSUE TITLE
Form dropdown not showing correct in MS Edge

### ISSUE THREAD

**Issue by mediafish** [uikit/uikit#2736]
### Browser
Microsoft Edge
### Reproduction Link
[https://getuikit.com/docs/form](url)
### Steps to reproduce
Go to the section: **Legend** and click in Option 01 - the dropdown (option) shows correct below the Option 01 in FF and Chrome but on top of Option 01 in Edge which looks like a bug.
### What is Expected?
The dropdown should show below Option 01
### What is actually happening?
The dropdown shows on top of Option 01

**Comment by su-narthur** [comment]
This seems to be [how browsers do things by default](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select).

**Comment by mediafish** [comment]
Hi, 
Thanks but they seem to work without that white top padding that uikit is adding - check it in the attached image. 
![uikit-dropdown](https://user-images.githubusercontent.com/4153939/30102847-c520eaac-92e8-11e7-883a-ea405ca90753.jpg)
