### ISSUE TITLE
Scrollspy in column is behaving strangely with uk-card in the columns

### ISSUE THREAD

**Issue by ycmjason** [uikit/uikit#2737]
### UIkit version
3.0.0-beta.25

### Browser
Google Chrome on Ubuntu

### Reproduction Link
https://codepen.io/ycmjason/pen/bRawjL

### Steps to reproduce
It's obvious in the reproduction link.

### What is Expected?
The first item of each column should appear with animation.

### What is actually happening?
The first item of each column  just pop up without transitions.

**Comment by zzseba78** [comment]
Hi, do you see this ok?
https://codepen.io/zzseba78/pen/gRogxV

**Comment by ycmjason** [comment]
I need to use column coz each card in my use case might differ, I want a layout similar to google keep.

**Comment by janschoenherr** [comment]
I believe this has already been resolved in the development branch.
