### ISSUE TITLE
CodePen example broken: Uncaught TypeError

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2738]
### UIkit version

3.0.0-beta.25

### Reproduction Link

Any of the Modal examples fail for me on CodePen:

https://getuikit.com/docs/modal#modal-container

### What is actually happening?

```
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at uikit.js:9
    at $__default (uikit.js:6)
    at uikit.js:7
```

**Comment by razvanioan** [comment]
And where's your Pen link ?

Here's my UIkit 3 playground, modals are working just fine

https://codepen.io/qdev/pen/vZJMPj

**Comment by fabien** [comment]
@razvanioan here's one example, simply created from the first Modal example on that page:

https://codepen.io/anon/pen/vZppmL

Strangely, your Pen is working for me.

**Comment by razvanioan** [comment]
@fabien You forgot to load jQuery first (before UIkit)

**Comment by fabien** [comment]
@razvanioan well, in that case, I think the documentation examples should be fixed (Pens used to work straight from the 'Edit in Codepen' buttons in the docs).

**Comment by janschoenherr** [comment]
Thanks, this has been resolved. uikit/uikit-site@2941c2790fb1c4cd27d5eed78e8e2b70298827f7
