### ISSUE TITLE
Modal shown event not working on chrome

### ISSUE THREAD

**Issue by SaphiLC** [uikit/uikit#2742]
### UIkit version
3.0.0-beta.25

### Browser
Chrome v 59.0.3071.115 (Official build) (64 bits)

### Reproduction Link
https://codepen.io/SaphiLC/pen/pwLvpd

### Steps to reproduce
move the mouse to the close modal button 

### What is Expected?
the shown event should happen as soon as the modal finishes appearing

### What is actually happening?
the shown event only triggers when you move the mouse to the close button (and the close button only, other links or buttons won't trigger it)

**Comment by zzseba78** [comment]
Same issue in Safari - macOs Sierra 10.12.5
Works fine in Chrome.

**Comment by SaphiLC** [comment]
well, not in the windows version of chrome then :p

**Comment by fabien** [comment]
@SaphiLC this is a known (and unresolved) bug, when using `center: true`:

https://github.com/uikit/uikit/issues/2626

**Comment by janschoenherr** [comment]
Has this been resolved?
