### ISSUE TITLE
Badge in uk-card

### ISSUE THREAD

**Issue by tirgot** [uikit/uikit#2743]
### UIkit version

3.0.0-beta.25

### Browser
chrome Version 59.0.3071.115

### Reproduction Link

    <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-card-small">
        <h4>TitleTitleTitleTitleTitleTitleTitle</h4>
        <div>ContentContentContentContentContentContentContent</div>
        <div><a class="uk-button uk-button-danger uk-button-small" href="#">Modify</a> <a class="uk-button uk-button-default uk-button-small" href="#">Delete</a></div>
    </div>
### What is Expected?
the badge inhert the uk-small style's margin (20px) to the top and right.

### What is actually happening?
the badge is 30px to the top and right.

**Comment by bbashy** [comment]
Doesn't look like a reproduction link :P

**Comment by florianletsch** [comment]
I copied your example and inserted a badge. Looks alright to me: https://codepen.io/anon/pen/NgEbOW

What am I missing?
