### ISSUE TITLE
Typed definitions file for v3

### ISSUE THREAD

**Issue by collegeimprovements** [uikit/uikit#2746]
We are using it with typescript. Currently typed-definition file is at  [version `2.27.5`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/uikit). 
Is it possible to add Typed definitions file for v3?

**Comment by greenplugin** [comment]
Any news for this feature?

**Comment by evdama** [comment]
same reason... we need v3 Typescript support... what's the plan/status?

**Comment by janschoenherr** [comment]
It seems it has since been updated.

**Comment by Lucasdevmake** [comment]
This problem has been solved?
