### ISSUE TITLE
Missing margin in second grid row - Firefox

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2747]
### UIkit version

3.0.0-beta.25

### Browser
Firefox 54.0.1

### Steps to reproduce
This error happens **randomly** in Firefox, the second row doesn´t have the margin and in the inspector it seems that the `.uk-first-column` is missing too on the first element of the second row.
It only happens in the second row, and it fixes if you resize the browser window, and and happens sometimes, not all the time, in Firefox, but this It's not new, has been happening for some time.
### What is Expected?
Second grid row have margin.
### What is actually happening?
Second grid row don´t have margin.

![captura de pantalla 2017-07-03 a la s 11 56 28](https://user-images.githubusercontent.com/5558563/27799920-89df69c4-5fed-11e7-91f4-72aaafd32e4c.png)

**Comment by florianletsch** [comment]
Can you provide a link to the website where this is happening? We already test on quite a complex grid example (https://getuikit.com/assets/uikit/tests/grid.html), but there might always be edge cases which could cause wrong behaviour.

**Comment by zzseba78** [comment]
Hi @florianletsch , thanks for your response.

This happens on simple or complex grids, only in second row, please check this link in Firefox:


[http://www.seba.adestudio.com/Napoli/menu.html](http://www.seba.adestudio.com/Napoli/menu.html)

Click on the sub menu items ( with switcher ) and check the grid.
In this example there is a uk-switcher implemented, but this happens randomly in any grid structure.
I´m using latest Firefox 54.0.1 in macOS Sierra 10.12.5

![captura de pantalla 2017-07-11 a la s 12 51 46](https://user-images.githubusercontent.com/5558563/28077296-c7724ce8-6637-11e7-830c-af195b1a46dd.png)

**Comment by zzseba78** [comment]
Seems to be fixed in latest release, thanks for your work, closing this issue.
