### ISSUE TITLE
Sticky "show-on-up" does not work when defined in Javascript

### ISSUE THREAD

**Issue by Propaganistas** [uikit/uikit#2749]
### UIkit version
3.0.0-beta.25

### Browser
Chrome, Safari, Firefox

### Reproduction Link
https://codepen.io/anon/pen/ZyRpOp

### Steps to reproduce
Scroll to the bottom.

### What is Expected?
Upon scrolling down the navbar should disappear as defined by Sticky's "show-on-up" option.

### What is actually happening?
The navbar does not disappear and is immediately fixed.

### Additional note
This only happens when defining the `show-on-up` option through Javascript. Setting it in the HTML attribute does work properly.

**Comment by janschoenherr** [comment]
The options names must be in their camel cased representation, e.g. show-on-up becomes showOnUp.

I've updated the docs accordingly uikit/uikit-site@0325542945babdc2d52a41456b5327bdc6e790c3
