### ISSUE TITLE
UIkit 2 : How to save the Htmleditor Preview ?

### ISSUE THREAD

**Issue by king742171** [uikit/uikit#2750]
I want to use htmleditor to edit the HTML file. First , how to load a html file in textarea? Second, how to save the preview to a html file? I found a keyword "htmleditor-save" in htmleditor.js, but I don't know how to use that keyword.

**Comment by florianletsch** [comment]
The HTML editor is just an alternative view on a `<textarea>` element, so you can use it as a regular form element in your web app. 

For example, you can use jQuery to read the content of the textarea and send it somewhere to be stored.

```
var content = jQuery('[data-uk-htmleditor]').val();
```

Alternatively, you can submit the form with a regular post request and validate and store the html on the backend, using PHP or the language of your preference.

**Comment by king742171** [comment]
Thank a lot!
