### ISSUE TITLE
Incorrect function in sass version UiKit 2.7.*

### ISSUE THREAD

**Issue by ghlexx** [uikit/uikit#2752]
Good day!
In the SASS version you are using functions from LESS!?
For example the function "fade"! Therefore, such as the "Contrast" does not work correctly.

**Comment by florianletsch** [comment]
I guess we will have to check which additional replacements we need to do when converting Less -> SASS. 

For "fade", it looks like it is safe to replace with "opacity" from SASS, as they look semantically equivalent: http://sass-lang.com/documentation/Sass/Script/Functions.html#opacify-instance_method

Have you noticed more functions missing?

**Comment by florianletsch** [comment]
Fixed it, will be included in the next release. If you need it right now, clone the the `v2/develop` branch, run `npm install && gulp` and you will find the converted sass files in `dist/scss`

**Comment by ghlexx** [comment]
Thank you, that answered the problem! UiKit framework the best for me! Waiting for fixes version 2.7.* and release v3!
