### ISSUE TITLE
3.0.0-beta.25 don't work Get request from child item for switch and toggle.... in navbar

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#2753]
...maybe I'm wrong, little experience

navbar sort block
1. fist element toggle -  asc/desc - href formed properly - but GET request not generated
2. second element switch - current sort name (not link) + dropdown list select sort name - href from dropdown  formed properly - but GET request not generated
3. third element switch - current sort name (link) + dropdown list select sort name - href for elemet from dropdown  formed properly - and GET request generated normal (for example - h_t_t_p_s://xxxxxxxxxxxxxxxx.php**?sortBy=name**)

ps
sorry for google translation

![image](https://user-images.githubusercontent.com/16114000/27862037-fce6d12e-618b-11e7-8a23-73ce578b3567.png)
```
<div class="uk-position-relative"> 
  <nav class="uk-navbar-container" uk-navbar="dropbar: true; dropbar-mode: push">
    <div class="uk-navbar-left">
      <ul class="uk-navbar-nav">

        <li>
	        <div class="uk-navbar-item uk-link-reset " uk-toggle="target: .toggle" title="Get request Sort from toggle dont't work" uk-tooltip>
	          <a href="?dirBy=asc"><span class="toggle" uk-icon="icon: chevron-up"></span></a>
	          <a href="?dirBy=desc"><span class="toggle" hidden uk-icon="icon: chevron-down"></span></a>
          </div>
        </li>

        <li>
          <div class="uk-navbar-item">
            <ul class="uk-switcher my-first-sort-list" title="Get request Sort from switch DropDown list dont't work" uk-tooltip>
              <li>first sort DATE</li>
              <li>first sort NAME</li>
              <li>first sort PRICE</li>
            </ul>
          </div>

          <div uk-dropdown="mode: hover; ">
            <span>SET Sort by for Get request</span>
            <hr class="uk-divider-small">
            <ul class="uk-nav uk-dropdown-nav" uk-switcher="connect: .my-first-sort-list">
              <li><a href="?sortBy=date">Date</a></li>
              <li class="uk-active"><a href="?sortBy=name">Name</a></li>
              <li><a href="?sortBy=price">Price</a></li>
            </ul>
          </div>
        </li>

        <li>
          <div class="uk-navbar-item">
            <ul class="uk-link-reset uk-switcher my-second-sort-list" title="Get request Sort from this Navbar Item" uk-tooltip>
              <li><a href="?sortBy=date">second sort DATE</a></li>
              <li><a href="?sortBy=name">second sort NAME</a></li>
              <li><a href="?sortBy=price">second sort PRICE</a></li>
            </ul>
          </div>

          <div uk-dropdown="mode: hover; ">
            <span>SET Sort by for Get request</span>
            <hr class="uk-divider-small">
            <ul class="uk-nav uk-dropdown-nav" uk-switcher="connect: .my-second-sort-list">
              <li><a href="#">Date</a></li>
              <li><a href="#">Name</a></li>
              <li><a href="#">Price</a></li>
            </ul>
          </div>
        </li> 

      </ul>

    </div>
  </nav>
</div>
```

**Comment by florianletsch** [comment]
I am not sure I understand you correctly. 

I am assuming that you want your links to lead to a page with your sort criteria attached, so something like `https://example.com/list?sortBy=date`, where the `?sortBy=date` is changed when a user clicks on a link. Is that correct?

The problem with this is that the `uk-toggle` and `uk-switcher` components will prevent the default action of the link, so your URL will not change. This is on purpose! That way, the browser does not navigate to a different site, but instead displays a different item on your page - which is exactly what the switcher an toggle are designed to do.

If you want to link to a different page and have your backend render the frontend differently depending on the `?sortBy=date` arguments, I suggest you do not use the switcher and toggle at all, but instead render plain UIkit components without using these JS functionalities.

Does this help you?

**Comment by AlexandreZaytsev** [comment]
Thank you for the explanation,
using the data of the component I wanted to just update the **current page** using queries to the database with the selected parameters, in this case sort. 

Chose from a list of option - **current page** is refreshed. 

ps 
Looking for a beautiful and economical solution. 
Thanks again!

**Comment by AlexandreZaytsev** [comment]
@florianletsch, but once again
> This is on purpose!
It is possible to optionally allow the generation of the link (Get request) when selecting the child values of the uk-toggle and uk-switcher components (and not just for content switching)?
...
The problem lies in the usability (setting up display criteria), in particular for working with the product catalog on the same page
...
For the code above, when selecting configuration options (for generating links):

First sorting - one click is used (the criterion was chosen - the page was refreshed), but unfortunately it is now forbidden ...

The second sorting is used already two clicks, the first choice of the criterion from the list and the second one - clicking on the modified navbar button

The first option for my outlook is much more convenient

**Comment by AlexandreZaytsev** [comment]
#2768
