### ISSUE TITLE
Modal dialog: wrong options in docs/sources

### ISSUE THREAD

**Issue by xtremespb** [uikit/uikit#2754]
There are the following options in Modal component available (according to the sources):

clsPanel: String,
selClose: String,
escClose: Boolean,
bgClose: Boolean,
stack: Boolean,
container: Boolean 

However, the docs are describing the other options (center, esc-close etc.)

**Comment by florianletsch** [comment]
Note that there is a differerence between "component options" and "JavaScript options", as well call them. The first ones can be used in the attributes directly (`<div uk-modal="center: true">`) while the latter are passed when initializing the component from JavaScript (`UIkit.modal(element, { escClose: true });`).

You are right that the Modal doc currently only includes the component options, not the JavaScript options. We are currently reworking that doc anyway, as the next UIkit release included some changes for the Modal component. I will make sure that we also add the JS options.

**Comment by florianletsch** [comment]
Added https://github.com/uikit/uikit-site/commit/b9d3c23913ab317e24a5fb94bef9f8b6408a5bfe
