### ISSUE TITLE
Sortable enhancement: scroll container option

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2756]
### What is Expected?

Functionally, as well as looking through the source, it appears that the Sortable component is aware of scrolling while dragging. However, this is currently restricted to the window itself.

It would be great to be able to use any element as a scroll container, with a similar behavior as the window currently has while dragging a sortable element near its edges. The appropriate `overflow` could simply be handled by css.

On a related note, a generic `uk-scrollable` container component (with a minimal styled, auto-hiding scrollbar) would be a great addition as well.

**Comment by janschoenherr** [comment]
Fixed in the dev version.
