### ISSUE TITLE
html markup

### ISSUE THREAD

**Issue by SaphiLC** [uikit/uikit#2757]
shouldnt you include
meta name="viewport" content="width=device-width, initial-scale=1"
in the html markup of the docs?

**Comment by florianletsch** [comment]
Yes, but I think it is included. What am I missing here?
 
![image](https://user-images.githubusercontent.com/1116784/27917076-3f96bdec-626b-11e7-8b34-8febbd3ff39f.png)

**Comment by razvanioan** [comment]
Maybe @SaphiLC refers to the user scalability (zoom) option, but that's a non-recommended method as somebody can really want to zoom in ...

**Comment by SaphiLC** [comment]
https://getuikit.com/docs/introduction#html-markup without this:
`<meta name="viewport" content="width=device-width, initial-scale=1">`
uikit doesnt work on phones/tablets

**Comment by florianletsch** [comment]
Ah, you mean the example! Yes, you're right. We will consider adding it, thanks.
