### ISSUE TITLE
How to open Off-canvas from JavaScript

### ISSUE THREAD

**Issue by krosoftware** [uikit/uikit#2760]
Hello all
I need to open Off-canvas from table where I have defined link, like
```
<a href="#" onclick="someFunc(id);">Some text</a>
```
my someFunc() function return HTML declaration from server, like 
```
var myOfCanvasVar = ''+
	'<div id="invoice_sidebar" class="uk-offcanvas-content">'+
	'    <div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true">'+
	'        <div class="uk-offcanvas-bar">'+
	'            <button class="uk-offcanvas-close" type="button" uk-close></button>'+
	'            <h3>Title</h3>'+
	'            <p>Some text ...</p>'+
	'        </div>'+
	'    </div>'+
	'</div>'
```
question is - how to show/open Off-canvas from someFunc() function?
I try
UIkit.offcanvas(UIkit.$('#invoice_sidebar')).show();
and
jQuery.UIkit.offcanvas.show('#invoice_sidebar');
but it does not worked..
Thank you.

**Comment by razvanioan** [comment]
```javascript
UIkit.offcanvas('#invoice_sidebar').toggle();
```

- UIkit is a direct window object, so NO jQuery.UIkit
- the first parameter of the offcanvas function is a string with the element selector, no need to select it with jQuery
- the correct method is toggle()

**Comment by krosoftware** [comment]
Hello
thank you for your help but it doe snot work :(
Here is my complete JS function (modified a bit to show the problem):

```
function	invoice_details(pn_invoice_id)
{
	var myOfCanvasVar = ''+
		'<div id="invoice_sidebar" uk-offcanvas="overlay: true">'+
		'    <div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true">'+
		'        <div class="uk-offcanvas-bar">'+
		'            <button class="uk-offcanvas-close" type="button" uk-close></button>'+
		'            <h3>Title</h3>'+
		'            <p>Some text ...</p>'+
		'        </div>'+
		'    </div>'+
		'</div>'
	  $('#div_temp').html(myOfCanvasVar);
	  UIkit.offcanvas('#invoice_sidebar').toggle();
}
```
This JS function is called on click on table row and I want to display Off-canvas, but it is not displayed.
What I'm doing wrong?
Thank you.

**Comment by zzseba78** [comment]
This is not the right place to ask about how things works.
You can get help here : https://gitter.im/uikit/uikit
Please close this issue.

**Comment by krosoftware** [comment]
OK

**Comment by krosoftware** [comment]
Hello
I posted my question at gitter but nobody can help.. I also created small example here: https://codepen.io/zzseba78/pen/YQOXOo so if anyone can help to how to open Off-anvas from JS I will be grateful.

**Comment by zzseba78** [comment]
https://codepen.io/zzseba78/pen/BZOvYq

**Comment by krosoftware** [comment]
Thank you so much.
