### ISSUE TITLE
Alert close icon left aligned

### ISSUE THREAD

**Issue by kevinfaguiar** [uikit/uikit#2761]
Hello,

I'm trying to use uikit on my Spring Boot + Thymeleaf project, but while the majority of components seems to work, the Alerts close buttons align to the left, and are closable clicking on the right like this (?): 
![capturar](https://user-images.githubusercontent.com/18222497/27931033-277a6908-626f-11e7-9e82-ac2f13c095c7.PNG)

I've used the exactly same code as https://github.com/uikit/uikit/blob/develop/tests/alert.html

Any ideas?

**Comment by florianletsch** [comment]
Looks like an issue with conflicting CSS to me. What CSS do the other parts of your project include? Can you provide a live link please?
