### ISSUE TITLE
Please change default text color to black

### ISSUE THREAD

**Issue by stanleyxu2005** [uikit/uikit#2764]
Default text color of 3.0 beta 25 uses `#666` as default color. This is not readable (including current doc site). Please change it to black and let theme designer to make it fancy.

**Comment by Riddler84** [comment]
What you mean with "not readable"? I can read it very well. But if you want to change the color to black you could simply change the LESS variable or overwrite the CSS.

**Comment by stanleyxu2005** [comment]
Yes. I need to override the value and recompile the style sheet.
```
@global-color:                                  #666;
@global-emphasis-color:                         #333;
@global-muted-color:                            #999;
```

But hey, white background color with some gray text, is it designer killing developer eyes program? When I check the official UIKit document, I need to see gray text on white background. I need to rebuild the doc site as well, to protect my eyes. I really appreciate dev team review the color setting.

**Comment by Riddler84** [comment]
No, it's not hurting my eyes ;) Ok, the muted links at the left could be a bit darker, but the overall text color is totally ok for me.

But it's nothing more than a default theme and you are encouraged to change it to your needs. I don't really see a reason to change it to #000 by default. That would be too much contrast for me. But maybe, i'm a special case ;)

**Comment by zzseba78** [comment]
If you have so much pain reading the uikit docs you can edit the css , for example in Firefox **with the inspector**, since the website doesn´t refresh you can see all the website with your changes.

![captura de pantalla 2017-07-08 a la s 17 00 22](https://user-images.githubusercontent.com/5558563/27988706-211f8336-63ff-11e7-9c79-a678dfe0b4d6.png)

**Comment by stanleyxu2005** [comment]
@zzseba78 Yes. I can tune it a bit to make it work. Just raise a feature request to tell me feeling of the default look and feel.

**Comment by florianletsch** [comment]
I hear you. I am personally also not a huge fan of the low contrast that is considered "en vogue" in webdesign at the moment.

That being said, the contrast of `#666`on white is still [considered adequate](http://webaim.org/resources/contrastchecker/?fcolor=666666&bcolor=ffffff) according to the [W3C accessibility guidelines](https://www.w3.org/TR/WCAG20/).

I think the color on the website will stay that way for now. As the others have mentioned, there are ways to increase contrast for yourself using your browser tools and to use higher contrast when using UIkit for your own projects.

Thanks for your feedback, as accessibility is a central topic we should all care about and probably think about more often.

**Comment by GBH** [comment]
People forget that there are still millions of low-contrast TN panels that have difficulty with shades of gray. So `@global-muted-color` is literally invisible unless you look at it from the side. Those are not great defaults.
