### ISSUE TITLE
How to enable uk-dark

### ISSUE THREAD

**Issue by stanleyxu2005** [uikit/uikit#2766]
I check the test page (https://getuikit.com/assets/uikit/tests/index.html). There is a light/dark switcher. I tried use dark theme by default in my test app. But it does not work. There is also no such css class `.uk-dark` in css file. How to enable uk-dark by default?

```
<body style="background:#000" class="uk-dark" uk-dark>
... contents ...
</body>
```

**Comment by Riddler84** [comment]
There is no `.uk-dark` class, because that's the default. You have to use the `.uk-light` class to lighten text up on dark backgrounds.

https://getuikit.com/docs/inverse

**Comment by stanleyxu2005** [comment]
Thank you so much. Now everything works perfectly.
