### ISSUE TITLE
Applying hidden attribute then unhiding with javascript removes grid styles

### ISSUE THREAD

**Issue by liran-co** [uikit/uikit#2771]
### UIkit version
3.0.0-beta.25

### Browser
All

### Reproduction Link
https://codepen.io/lirancohen/pen/PjXPQw

### Steps to reproduce
Hide element containing grid by default, show on button click.

### What is actually happening?
Grid margins / padding are removed

**Comment by janschoenherr** [comment]
You'll have to call `UIkit.update()` to reset the margins.
