### ISSUE TITLE
Dropbar misbehaves when parent navbar item gets hidden by visibility rules

### ISSUE THREAD

**Issue by mhfs** [uikit/uikit#2772]
I ran into this issue when mixing navbars, dropbars and the visibility utilities to create a mobile version of top navigation. More details below.

### UIkit version

3.0.0-beta.25

### Browser

Chrome 59.0.3071.115 (Official Build) (64-bit) (macOS Sierra - 10.12.5) 

### Reproduction Link

https://jsfiddle.net/mhfs/0720yLax/

### Steps to reproduce

1. Reduce the Output panel width until the 'Menu' navbar item appears to the left of the 'App' title.

![2017-07-11 at 17 11](https://user-images.githubusercontent.com/78422/28088426-02a81080-665c-11e7-85db-6a70eea1605e.png)

2. Trigger the dropbar by clicking the parent 'Menu' item.

![2017-07-11 at 17 03](https://user-images.githubusercontent.com/78422/28088040-dd843758-665a-11e7-81c9-cee9f203f527.png)

3. Increase the Output panel width until the 'Menu' navbar item is gone and the items appear on the right side of the navbar.

![2017-07-11 at 17 04](https://user-images.githubusercontent.com/78422/28088126-169c3ef0-665b-11e7-9458-807b5b2f9952.png)

### What is Expected?

The dropbar to be hidden when the parent navbar item is hidden.

Or at least the dropbar to not go up and behind the navbar hiding the first item.

### What is actually happening?

1. the dropbar is still displayed when the parent navbar item visibility is triggered to hidden.
2. the dropbar bumps up and the first item in it gets hidden behind the navbar.

**Comment by janschoenherr** [comment]
Could you update the fiddle to use the latest UIkit release, thanks.

**Comment by mhfs** [comment]
Works fine with latest version. Closing. Thanks.

https://jsfiddle.net/0720yLax/6/
