### ISSUE TITLE
Opening of Off-canvas move a page up

### ISSUE THREAD

**Issue by krosoftware** [uikit/uikit#2773]
### UIkit version
3.0.0-beta.25

### Browser
Any
### Reproduction Link
https://codepen.io/krosoftware/pen/LLMGOV

### Steps to reproduce
scroll to the bottom (to see "Click me" button) and then scroll a bit up (using scroll bar) and then click on "Click Me", you can see that screen is moved up a bit..
Second issue is that Off-canvas animation works only first time, after second or third click it is gone.

**Comment by krosoftware** [comment]
Anyone, please?

**Comment by janschoenherr** [comment]
Could you update your codepen example? There is nothing to scroll there.
