### ISSUE TITLE
Sticky bottom is not working

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2774]
I am trying to stop sticky from top and scroll up when you reach to footer but its not working
` <div class="userFillContainer" uk-sticky="bottom: #footer"></div><footer id="footer"></footer >`

**Comment by florianletsch** [comment]
Is the footer the last element on the page? Sticky will disappear when you scroll _past_ that element. If it is the last element, you won't be able to scroll past it and it won't disappear. Compare the example at: https://getuikit.com/docs/sticky#bottom

If I misunderstood you, please provide a live example.

**Comment by theromie** [comment]
I did but not working

**Comment by theromie** [comment]
footer is last element of the page after that i don't have anything.

**Comment by florianletsch** [comment]
Please provide an example
