### ISSUE TITLE
Close modal and go to anchor tag

### ISSUE THREAD

**Issue by CarlosUvaSilva** [uikit/uikit#2776]
I'm trying to close a modal and on close go to an anchor tag.
I've tried different solutions but i always end up either closing the tag and staying on the same place or the page "slides down" to the anchor tag but I have to manually close the modal after.

this is the code I'm using (I want to click on state, close the modal and go to #state) : 

     <div id="modal-full" class="uk-modal-full" uk-modal>
          <div class="uk-modal-dialog">
            <button class="uk-modal-close-full uk-close-large" type="button" uk-close></button>
            <div class="uk-grid-collapse uk-child-width-1-2@s uk-flex-middle" uk-grid>
              <div class="uk-background-cover takeoff-modal" uk-height-viewport></div>
              <div class="uk-padding-large">
                  <h1>Headline</h1>

                  <a class="uk-modal-close" href="#state">STATE</a>

                  <p>Lorem ipsum dolor.</p>
              </div>
          </div>
        </div>
      </div>

**Comment by krosoftware** [comment]
Did you solved it? If yes, how?

**Comment by CarlosUvaSilva** [comment]
I solved yes. Used jQuery

**Comment by krosoftware** [comment]
Can you post sample code, please?

**Comment by CarlosUvaSilva** [comment]
i dont have acess to my code at the moment, i'll edit this answer monday morning :)

**Comment by CarlosUvaSilva** [comment]
@krosoftware here's the code:

## this is inside the modal itself

     <p><a class="uk-modal-close" data-url="#modal_presentation_photo" data-target="#presentation">Présentation</a></p>

## this is jQuery

  ```
  jQuery(".uk-modal-close").click(function(){
      jQuery(jQuery(document)).scrollTop( jQuery(jQuery(this).data("target")).offset().top);
    })
```

**Comment by krosoftware** [comment]
OK thank you.
