### ISSUE TITLE
Accordion not working if jQuery is set to noconflict.

### ISSUE THREAD

**Issue by kaiSer007** [uikit/uikit#2777]
I have only experience the issue when using the accordion, some features might also not be working but I haven't explored all components yet. What happens is that I need to use the jQuery no conflict function to avoid conflict with another library . Here is my code structure:

`<link rel="stylesheet" type="text/css" href="css/uikit/uikit.css" media="all" /> 

<script type="text/javascript" src="js/prototype.js"></script> 
<script type="text/javascript" src="js/jquery.js"></script> 
<script type="text/javascript" src="js/uikit.js"></script> 
<script type="text/javascript" src="js/uikit-icons.js"></script> 
<script type="text/javascript">jQuery.noConflict();</script>`

... Acordion element here..

I had to use noConflict to avoid conflict of jQuery and Prototype js

**Comment by janschoenherr** [comment]
This seems to be working fine: https://codepen.io/janschoenherr/pen/dRxoXg

**Comment by kaiSer007** [comment]
Hi, thank you for the reply. Yes its working but when I added prototype.js on the external scripts that's when it started acting weird. So it is just prototype js conflicting with uikit. Well I guess I can't use Uikit on Magento 1 since it is using prototype js.

**Comment by janschoenherr** [comment]
Simply adding prototype does not seem to be triggering any issues either.
