### ISSUE TITLE
Date Picker field with icon + label

### ISSUE THREAD

**Issue by frogydiak** [uikit/uikit#2781]
### UIkit version
3.0.0-beta.25

### Browser
Chrome

### Steps to reproduce
Using DatePicker in a form input with container having a class uk-inline, I added a label before the container and the icon alignment goes off:

https://screencast.com/t/dN00ik4A

### What is Expected?
Icon should be aligned middle

### What is actually happening?
Icon is aligned top of the field

**Comment by florianletsch** [comment]
Can you provide an example of this, or at least the code you are using? UIkit 3 currently does not have a datepicker, so I am not sure what exactly you are referring to.

I have tried to align the icon just using the form component, and it works for me: https://codepen.io/anon/pen/rwXxNN

**Comment by Uranbold** [comment]
![google-chrome](https://user-images.githubusercontent.com/1425854/28452788-3c36d3d8-6e2f-11e7-8dda-809b32517517.jpg)

When we Hover over the Input there has an lot's of additional icons are shown. I think we should fix this ;)

**Comment by frogydiak** [comment]
I simply added a <label> tag on top of input. 

@florianletsch Yes, the icon looks great without the label tag. Try to add a label tag on top of the input.

**Comment by piotr-cz** [comment]
Adding `padding: 8px` to the input makes look browser ui nicer
