### ISSUE TITLE
V3 Customize Prefix + Scope

### ISSUE THREAD

**Issue by frogydiak** [uikit/uikit#2782]
When customizing the prefix  several times, the prefix will be just keep appended to the previous prefix. For example, 

npm run prefix -- -p xyz // first time

Prefix is changed to xyz from ui, that's good, but if you do:

npm run prefix -- -p xyz  again

The prefix becomes xyzxyz... and so on if you keep on changing he prefix.

As for scope, I cannot find a reset or remove scope. Is there a command switch?

### UIkit version
3.0.0-beta.25

### Browser
Chrome

### What is Expected?
Shouldn't there be an idiot proof check for this? Maybe a prompt to remind that the current prefix is "xyz" and if you continue the new prefix would be "...xyz". Or maybe it should override the current prefix instead of appending.

**Comment by dasdeck** [comment]
See changelog ;)
