### ISSUE TITLE
Togglable components API inconsistency

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#2784]
### What is Expected?

All components using the `togglable` mixin should conform to the same interface, and use the container element as the basis for the component.

Below `#element` is the container that should be toggled, `#toggle` is the element that triggers the container to toggle. See how `toggle` vs. `target` make this inconsistent, whereas it could easily be uniform.

```javascript

UIkit.dropdown('#element', { toggle: '#toggle' });

UIkit.toggle('#element', { toggle: '#toggle' });

```

### What is actually happening?

```javascript

UIkit.dropdown('#element', { toggle: '#toggle' });

UIkit.toggle('#toggle', { target: '#element' });

```
It is also confusing when it comes to where events are fired (https://github.com/uikit/uikit/issues/2483).

To preserve the current behavior, where `#toggle` might have its own configuration regarding `animation` etc. I suggest to use the config options from the `#toggle` element over the `#element` base config. This way, multiple toggle elements can be used, even with their own specific options to apply, to vary the behavior per trigger.

**Comment by janschoenherr** [comment]
I leave this open for debate, but currently. The Toggle component _toggles_ a _target_. While the Dropdown component itself is the _target_ that is being _toggled_ by its _toggle_.
