### ISSUE TITLE
Feature Request: Video will Play in Viewport?

### ISSUE THREAD

**Issue by Uranbold** [uikit/uikit#2785]
Look at this section ->

https://getuikit.com/assets/uikit/tests/cover.html

https://getuikit.com/docs/cover

Once the Page has Video inserted then Video will play instantly and I  think it's not user-friendly. If the user has inserted Some Carousel for Video or Video Slideshow then all videos begin at the same time and it's not user-friendly.

Is there are any chance to resolve this or add a Component option?

**Comment by saschadube** [comment]
Should be fixed with the next release

Please take a look at this commit https://github.com/uikit/uikit/commit/60622f85e8b2c504b67ee02b67d79a719a37a68e

There is also a test in the dev branch, see [Utility test](https://github.com/uikit/uikit/blob/develop/tests/utility.html) and uk-cover should also work.

**Comment by Uranbold** [comment]
Thank you @saschadube When will be next version release?

**Comment by saschadube** [comment]
Ah, I misunderstood. Currently, it is not solved for the viewport but if the video is hidden and shows up. But depending on the viewport could be added later.

**Comment by florianletsch** [comment]
Hm, but maybe this will already work if you combine video and scrollspy ("already" meaning with the next release).

So, something like this, I suppose?

```
<video src="" uk-video="automute: true" uk-scrollspy="hidden: true"></video>
```

**Comment by Uranbold** [comment]
Yeah, I hope it will be resolved like @florianletsch. It's much easier ;)

**Comment by janschoenherr** [comment]
The Video component supports play/pause video as it enters/leaves the viewport. 

5fc8f223d8fc9e9ba863cdb5b1f6a349ca8ac824
