### ISSUE TITLE
Where is the Date and Time Picker?

### ISSUE THREAD

**Issue by frogydiak** [uikit/uikit#2789]
Sorry if I'm asking this here but where is the Date and Time Picker? There's no way to customize the current <input type="date" /> I can't find JS and CSS that refers to it also. 

Nothing in the documentation as well. In test, there's only one javascript option for form.

**Comment by florianletsch** [comment]
The datepicker is currently only available in UIkit 2 (https://getuikit.com/v2/docs/datepicker.html), but it has not been ported to UIkit 3 yet.

**Comment by frogydiak** [comment]
Thanks for clarifying that @florianletsch. Can you confirm that UIKit 3 will not use HTML 5 form field?

**Comment by martinapixelwiese** [comment]
hello, i am wondering -  will the datepicker be integrated into uikit 3 - and when? i am really looking forward to integrate it! thank you! :)

**Comment by jelgervisser** [comment]
Hi, any news on this subject?

**Comment by johnclittle** [comment]
+1

**Comment by amaradrys** [comment]
+1

**Comment by lucakuehne** [comment]
+1

**Comment by janschoenherr** [comment]
This seems to be a duplicate of #2789

**Comment by NiteshOswal** [comment]
Isn't this #2789? It's a duplicate of itself?

**Comment by Valexr** [comment]
+1

**Comment by arwy18** [comment]
+1

**Comment by sstarasenko** [comment]
+1

**Comment by mexus** [comment]
+1

**Comment by Sixstep** [comment]
+1

**Comment by Mat-thieu** [comment]
+1

**Comment by pepijnverburg** [comment]
+1

**Comment by Viach** [comment]
+

**Comment by arnvanhoutte** [comment]
+1

**Comment by Viach** [comment]
now I use this picker - https://github.com/colinmcintyre/datetimepicker
but I will be very glad to use picker from UIkit  framework

**Comment by viocassel** [comment]
@Viach better to temporarily use [Flatpicker](https://github.com/chmln/flatpickr) 🤘

**Comment by Viach** [comment]
@viocassel Thank you!

**Comment by samuelkarani** [comment]
me too

**Comment by stell** [comment]
+1
(is this still on your list or is a calendar component not coming for uikit3?)

**Comment by aarongerig** [comment]
I don‘t think Date/Time picker will come to UIkit 3.

**Comment by gam6itko** [comment]
any news @florianletsch ?

**Comment by stell** [comment]
I don't think this will happen. You should consider an alternative...picker.

**Comment by DrYurets** [comment]
Hello from 2022, guys!
