### ISSUE TITLE
Page "jumps" or doesn't show up on using scrollspy on mobile

### ISSUE THREAD

**Issue by Bensji** [uikit/uikit#2790]
### UIkit version

3.0.0-beta.26

### Browser
Google Chrome Android 59.0.3071.125 on Android 6.0.1

### Reproduction Link

https://www.benjaminlierman.be

### Steps to reproduce
Browsing on mobile phone to the page

### What is Expected?
The element slides in when it comes into the viewport, no weird "jumping" occurs.

### What is actually happening?
Some elements have trouble performing the animation / page jumps up when items slide in.

**Comment by janschoenherr** [comment]
This seems to be happening on the _benj_ section. Could you try to separate all of the _flex_, _scrollspy_, _grid_ action a bit. Maybe a use an additional wrapper div?

**Comment by janschoenherr** [comment]
Is this still an issue with the latest Beta 34 release?
