### ISSUE TITLE
Problem with uk-grid when JS doesn't get loaded in the head tag

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#2792]
### UIkit version
3.0.0-beta.27

### Browser
Chrome 59

### Reproduction Link
https://codepen.io/anon/pen/BZXZGJ

Sometimes you can see it better on https://jsfiddle.net/hes23p88/

(Reload/Run a few times until you see the effect)

### Steps to reproduce
```html
<!DOCTYPE html>
<html>
  <head>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.27/css/uikit.min.css" />
  </head>

  <body>
    
    <div class="container">
      <div class="uk-child-width-1-4" uk-grid>
        <div>one</div>
        <div>two</div>
        <div>three</div>
        <div>four</div>
      </div>
    </div>
    
  <!-- jQuery is required -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- UIkit JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.27/js/uikit.min.js"></script>
  </body>
</html>
```
### What is Expected?
The 4 div's should be placed side by side while loading.

If the JS stuff gets loaded in the `<head>` tag, everything is fine, you don't see anything moving from the grid: https://jsfiddle.net/8Lt0by41/

The `uk-grid` attribute should work without JS, to get the correct order of elements while loading.

### What is actually happening?
While loading, the 4 div's are, for a short period of time, shown stacked on each other. This is due to loading UIKit JS before the `</body>` tag.

I think something is missing in the CSS to make sure that the `uk-grid` attribute in the tags is styled correctly without JS.

**Comment by zzseba78** [comment]
The `.uk-grid` class it´s added with js, but you can put this css class yourself to avoid this short transition.
`<div class="uk-grid" uk-grid></div>`

**Comment by uikid** [comment]
@zzseba78 you are right! This should be in the documentation.

> To create the grid container, add the uk-grid attribute to a `<div>` element. _There's no need to add a class_.

Source: https://getuikit.com/docs/grid#usage

That is wrong, **there is definitely a need**! Please update the docs:

> To create the grid container, add the uk-grid attribute to a `<div>` element. This will add the class `uk-grid` via JavaSript to the `<div>` element. It is likely that you will load the UIKit JavaScript before the closing body tag. If this is the case, you should add the class uk-grid class manually to the `<div>` element, to prevent stacking.

**Comment by uikid** [comment]
Actually, if the need for the attribute is eliminated when only the class `uk-grid` gets added, then that would reduce the JS too.

Using a class is for most of the people more common and brings in this case even important benefits/fixes. So the docs should be like:

> To create the grid container, just add the `uk-grid` class to a `<div>` element, e.g. `<div class="uk-grid">`.

That's all you need, no more stacking etc.

**Comment by janschoenherr** [comment]
The JavaScript part of the grid component applies margins between rows, whenever the grid starts to stack and also adds a class to the first column of a grid.

**Comment by uikid** [comment]
> The JavaScript part of the grid component applies margins between rows, whenever the grid starts to stack and also adds a class to the first column of a grid.

Why does JS apply margin? Shouldn't this be a CSS part?

However, the documentation still should be updated like stated above.

**Comment by janschoenherr** [comment]
Only cells below the first row will get a top margin applied. We haven't found a good non JS solution for that.

The documentation should be more precise about that.

**Comment by uikid** [comment]
Yes, plus the class for the wrapper element. I bet there are a lot of people that include the JS before the closing body tag. And you could remove a little bit of logic from JS (adding the class).

**Comment by zzseba78** [comment]
The docs says there is no need to put the class, and they are right. 
Simply add this class and it works fine, if you want it on the docs create a pull request on the UIkit site to get this point clear, there is no need to change the grid. Good luck.

**Comment by zzseba78** [comment]
Good job! :)

**Comment by zzseba78** [comment]
@uikid Good job! 👍

**Comment by janschoenherr** [comment]
Your pull request uikit/uikit-site#70 has been merged, thanks.

**Comment by nitras** [comment]
This issue is still active. I spend the entire day finding out why my website grid stacked... the uk-grid class solved all this frustration.
