### ISSUE TITLE
Scss compile does not seem to work

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#2794]
### UIkit version
3.0.0-beta.25

Having a `main.scss` file with just this (will be expanded but for now it's this):
```
@import "../../bower_components/uikit/src/scss/uikit-theme";
```
gives an error:
```
error ../../bower_components/uikit/src/scss/theme/base.scss
    (Line 16: Undefined variable: "$global-muted-background".)
```

I checked the path (file not found error when I change the name), so it's not that.

The `main.css` now has this results from the scss compiler:
```
Error: Undefined variable: "$global-muted-background".
        on line 16 of ../../bower_components/uikit/src/scss/theme/base.scss
        from line 3 of ../../bower_components/uikit/src/scss/theme/_import.scss
        from line 5 of ../../bower_components/uikit/src/scss/uikit-theme.scss
        from line 7 of main.scss
11: //@import "../../bower_components/uikit/src/scss/components/_import.scss";
Backtrace:
../../bower_components/uikit/src/scss/theme/base.scss:16
../../bower_components/uikit/src/scss/theme/_import.scss:3
../../bower_components/uikit/src/scss/uikit-theme.scss:5
main.scss:7
```

Any ideas?

Thanks!
Jerry

**Comment by jerry1970** [comment]
It works if I add this at the beginning of my `main.scss`:
```
@import "../../bower_components/uikit/src/scss/variables-theme";
@import "../../bower_components/uikit/src/scss/variables";
```

**Comment by aheinze** [comment]
Hi,

we have a detailed sass build instruction: https://getuikit.com/docs/sass#how-to-build

do you still experience any issues after following the instructions?

Greets,
Artur

**Comment by jerry1970** [comment]
How could I have overlooked that page?! I did try and find stuff but apparently not good enough, sorry.

Many thanks, yes, this works!
