### ISSUE TITLE
navbar bug in EDGE

### ISSUE THREAD

**Issue by lukashl** [uikit/uikit#2796]
When i changed navbar height in EDGE and IE, navbar crash:

![edge](https://user-images.githubusercontent.com/12393718/28460425-4e0cc7ba-6e12-11e7-941b-57a1e5d9c5a1.png)

### UIkit version
3.0.0-beta.27

### Browser
EDGE, IE

**Comment by janschoenherr** [comment]
Needs reproduction link.
