### ISSUE TITLE
add different params at time of two upload components

### ISSUE THREAD

**Issue by ziriyan** [uikit/uikit#2798]
my english is poor, hope you can understand,  sorry...

seems uikit upload components only pass one parameter at the same time.

but I have two upload components on the same page:
`var select = UIkit.uploadSelect($("#filename"), settings),
select1 = UIkit.uploadSelect($("#filename1"), settings);`

I want to add different params when each uploadfile button clicked.

for example:
When the $("#filename") button is clicked, the params is "{'sid' : 's_show'}"
When the $("#filename1") button is clicked, the params is "{'hid' : 'h_show'}"

Does someone have an idea?

**Comment by janschoenherr** [comment]
From your code it looks like you are passing the same settings object into both component instances?

**Comment by ziriyan** [comment]
thank you for your quickly response:)
you are right, but I solved the issue now, this article inspired me:
https://github.com/uikit/uikit/issues/1779
