### ISSUE TITLE
uk-form-small with uk-form-icon causing overlapping

### ISSUE THREAD

**Issue by PureDizzi** [uikit/uikit#2800]
### UIkit version

3.0.0-beta.27

### Steps to reproduce
Create form input with icon.
Add uk-form-small on the input field.
### What is Expected?
Left padding should be with uk-form-icon.
### What is actually happening?
Left padding from uk-form-small is used causing text to overlap icon.

**Comment by andy-blum** [comment]
this appears to be fixed.

https://codepen.io/andy-blum/pen/JjPQxEo
