### ISSUE TITLE
** Feature Request **  Enable or Disable Inverse Component for each Component

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2802]
### UIkit version

3.0.0-beta.27

### What is actually happening?
Inverse component it´s great, very useful, but it adds bunch of kb to the final css file.

So, wouldn´t be great to be able to disable this functionality in components where it is not needed?

### Facts:

**You can disable inverse styles completely**: wich it´s great, but sometimes you need some components with the inverse funcionality.

**You can also disable the inverse mode for specific components:** Yes, but this disable some of the components, for example: Accordion, Article, Badges, Buttons, Countdown, Divider, ... , Links,  Marker, List, Nav, Pagination, Search.... etc etc, don´t. So, we load bunch of styles that won´t be used.

It would be great to have in each component ( in less and sass ) a variable where we can enable(default) or disable the inverse funcionality on demand.

What do you think?

Thank for your work!

**Comment by SaphiLC** [comment]
it's really needed

**Comment by aarongerig** [comment]
Guys, have a look at purifyCSS (https://github.com/purifycss/purifycss) or unCSS (https://github.com/giakki/uncss). Great tools to do all this work. 😉

**Comment by Riddler84** [comment]
@aarongerig Wow, nice tip, thank you. Will definitely take a look :)

**Comment by zzseba78** [comment]
Closing this since the difference between disable inverse completly and disable the available components in the final css file it´s very small, ( 107kb vs 123kb without gzip ), and gzipped this difference is even less appreciable, I dont think it's worth the effort. Thanks
