### ISSUE TITLE
Beta 27 can't compile less with NPM

### ISSUE THREAD

**Issue by bertyterty** [uikit/uikit#2803]
### UIkit version
3.0.0-beta.27

### Browser
Chrome - This test server I am running on is on the Cloud 9 IDE with ubuntu 14.04. I have tested beta 25 on the same server and it works fine.

### Steps to reproduce
Running `npm run compile` whilst in the uikit folder

### What is Expected?
The css and javascript files to be compiled from less

### What is actually happening?
Fails at /uikit/build.js at line 117

I can compile beta 25 no problem, but I have just cloned the latest version (beta 27) for a new project, and it always fails there. For now, I will just carry on with b25. It's not obvious from the quoted text below, but the error is pointing to the curly brace on line 117 (see screen shot)
![screen shot 2017-07-23 at 14 50 58](https://user-images.githubusercontent.com/4634700/28499816-7ac6406a-6fb6-11e7-8cc6-ab66c0fca58b.png)

#### Output from terminal
>bertyterty:~/workspace/node_modules/uikit $ npm run compile

> uikit@3.0.0-beta.27 compile /home/ubuntu/workspace/node_modules/uikit
> npm run compile-less && npm run compile-js

> uikit@3.0.0-beta.27 compile-less /home/ubuntu/workspace/node_modules/uikit
> npm run icons && node build/less

> uikit@3.0.0-beta.27 icons /home/ubuntu/workspace/node_modules/uikit
> node build/icons

> /home/ubuntu/workspace/node_modules/uikit/build/util.js:117
        .then(({code}) => exports.write(`${dest}.js`, code.replace(/(>)\\n\s+|\\n\s+(<)/g, '$1$2')))
               ^

> SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/uikit/build/icons.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

> npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "icons"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uikit@3.0.0-beta.27 icons: `node build/icons`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uikit@3.0.0-beta.27 icons script 'node build/icons'.
npm ERR! This is most likely a problem with the uikit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/icons
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uikit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uikit
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/node_modules/uikit/npm-debug.log

> npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "compile-less"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uikit@3.0.0-beta.27 compile-less: `npm run icons && node build/less`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uikit@3.0.0-beta.27 compile-less script 'npm run icons && node build/less'.
npm ERR! This is most likely a problem with the uikit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run icons && node build/less
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uikit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uikit
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/node_modules/uikit/npm-debug.log

> npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "compile"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uikit@3.0.0-beta.27 compile: `npm run compile-less && npm run compile-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uikit@3.0.0-beta.27 compile script 'npm run compile-less && npm run compile-js'.
npm ERR! This is most likely a problem with the uikit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile-less && npm run compile-js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uikit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uikit
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/node_modules/uikit/npm-debug.log

#### Contents of `npm-debug.log`
> 0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@2.15.11
3 info using node@v4.7.3
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info precompile uikit@3.0.0-beta.27
6 info compile uikit@3.0.0-beta.27
7 verbose unsafe-perm in lifecycle true
8 info uikit@3.0.0-beta.27 Failed to exec compile script
9 verbose stack Error: uikit@3.0.0-beta.27 compile: `npm run compile-less && npm run compile-js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:854:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid uikit@3.0.0-beta.27
11 verbose cwd /home/ubuntu/workspace/node_modules/uikit
12 error Linux 4.9.17-c9
13 error argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "compile"
14 error node v4.7.3
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error uikit@3.0.0-beta.27 compile: `npm run compile-less && npm run compile-js`
17 error Exit status 1
18 error Failed at the uikit@3.0.0-beta.27 compile script 'npm run compile-less && npm run compile-js'.
18 error This is most likely a problem with the uikit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run compile-less && npm run compile-js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs uikit
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls uikit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by janschoenherr** [comment]
You are running an outdated _node_ version. 

https://nodejs.org/en/

**Comment by CeeMoo** [comment]
https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version  yeah i update and running node-module
