### ISSUE TITLE
uikit v3b27 Lightbox touch swipe to left goes back a page

### ISSUE THREAD

**Issue by acseven** [uikit/uikit#2806]
### UIkit version
3.0.0-beta.27

### Browser
Chrome Windows (updated) on Microsoft Surface 3 Pro

### Reproduction Link
https://codepen.io/acseven/pen/YxPxrq
(this is just the basic implementation of a lightbox gallery)

### Steps to reproduce
Use a touch enabled device, swipe right for the next photo (ok), swipe left to return the previous photo (NOK, it goes back in the browser's history)

### What is Expected?
Last photo shown on left swipe

### What is actually happening?
Browser goes back to last page

**Comment by janschoenherr** [comment]
Only if you start swiping to close from the edge, right?

**Comment by acseven** [comment]
@janschoenherr Nope, right in the middle of the screen.
