### ISSUE TITLE
Modal of type "confirm" have two buttons without margins

### ISSUE THREAD

**Issue by progreccor** [uikit/uikit#2810]
### UIkit version

3.0.0-beta.27

### Browser
All
### Reproduction Link
You can test it on your test pages https://getuikit.com/docs/modal

### Steps to reproduce
Press "confrim" button and get window with two buttons "cancel" and "ok" without margin between them

### What is Expected?
Expected that two buttons have space between
### What is actually happening?
This two buttons don't have space between

**Comment by florianletsch** [comment]
Line break in markup is lost during JS compilation which causes this bug. We'll fix this.

**Comment by janschoenherr** [comment]
Resolved with 8ef67281018d860a681a5b1a925cb3720046b674. Thanks.
