### ISSUE TITLE
theme\button.scss incorrect value

### ISSUE THREAD

**Issue by stanleyxu2005** [uikit/uikit#2811]
The git master branch (3.0.0-beta.27) in src\theme\button.scss
```
$button-large-font-size:                         $global-small-font-size !default;
```
I think it should be `$global-large-font-size`?

**Comment by aarongerig** [comment]
The official line of code is [here](https://github.com/uikit/uikit/blob/develop/src/scss/components/button.scss#L31). The one you are referring to is inside the `theme` folder, which is a starting point to create custom themes.

**Comment by stanleyxu2005** [comment]
I'm referring from master branch and the theme dir
https://github.com/uikit/uikit/blob/master/src/scss/theme/button.scss#L15

It does look like an error, because normal size button uses global font size, but small button and large button use small font size

**Comment by florianletsch** [comment]
In the default theme the button has the same font size for both button sizes, yes. This improves readability of smaller elements and is correct. If you prefer a different font size, you can change this variable in your own theme.
