### ISSUE TITLE
dropdown doesn't show up on click if it's bigger than viewport

### ISSUE THREAD

**Issue by vaniakosmos** [uikit/uikit#2814]
### UIkit version

3.0.0-beta.27

### Browser
Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Reproduction Link

https://codepen.io/anon/pen/ayvrrd

### Steps to reproduce
- reduce browser window height at least by half
- click 'apps'
- wow
- such bug
- resize window back
- wow, dropdown actually was opened but shows up only now

### What is Expected?
Expected dropdown to be opened and showed

### What is actually happening?
Actually dropdown is opening but not showing up

**Comment by zzseba78** [comment]
Yes, it happens on Chrome, Firefox, Safari and Opera....

**Comment by zzseba78** [comment]
@vaniakosmos Seems that you don´t position the dropdown correctly, you have it to the top-right...

Check this:
https://codepen.io/zzseba78/pen/yoYmgb

If it works now please close the issue.

**Comment by vaniakosmos** [comment]
you are right. The problem was with `pos: top-right;` and i didn't notice it... Thank you
