### ISSUE TITLE
google map load failed within switch tabs

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#2815]
### UIkit version
3.0.0-beta.27

### Browser
Chrome

### Steps to reproduce
google maps (using api method) works fine if placed in the first tab, but if not, the map will not load up.

### What is Expected?
working google map

### What is actually happening?
map doesn't display

**Comment by aarongerig** [comment]
Have you tried initializing Google Maps, when a tab has been switched? You can do so by using the event `show`. This could look something like this:

https://codepen.io/aarongerig/pen/gxPNRe

**Comment by tyler-x** [comment]
thanks~ works really well~!
