### ISSUE TITLE
Iframe is not working in Lightbox

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2818]
I am trying to add Iframe in lightbox but its not showing

**Comment by Riddler84** [comment]
Set `data-type="iframe"`. https://codepen.io/Riddler84/pen/RZGELQ

**Comment by florianletsch** [comment]
Please check your browser console for errors. Is it possible that you try to embed a site which does not allow it? https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe

**Comment by theromie** [comment]
Thanks @Riddler84 its working
