### ISSUE TITLE
[DOCS] Need Example and Test for Section Overlap Modifier

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#2821]
### UIkit version
3.0.0-beta.28

### Browser
Safari, Chrome

### Reproduction Link
Section Docs: https://getuikit.com/docs/section
Section Tests: https://getuikit.com/assets/uikit/tests/section.html

### Steps to reproduce
The 'Section' component docs mention an "overlap" modifier - `uk-section-overlap` - but no usage example is shown on the docs.

Further, the test page contains an 'overlap' button that seemingly does nothing...

### What is Expected?
It would be useful to have an example showing 2 *overlapping* sections with the modifier in actual use.

### What is actually happening?
We only have a single-line code sample showing how the modifier class would be placed inside an HTML element - not useful at all.

**Comment by Riddler84** [comment]
There is no example because there is no `uk-section-overlap` anywhere in the code. There's just a hook in the LESS and SCSS files, but no default CSS markup.

Maybe it will come later or it has been forgotten ;)

**Comment by saschadube** [comment]
Yes, the overlap modifier needs to be implemented by the custom UIkit theme. Here is an example how to do it:

`// Overlap image
@internal-section-default-overlap-image:            ;
@internal-section-muted-overlap-image:              ;
@internal-section-primary-overlap-image:            ;
@internal-section-secondary-overlap-image:          ;
@internal-section-overlap-height:                   0;

.hook-section-overlap() when not (@internal-section-overlap-height = 0) {

    &.uk-section::after,
    & > .uk-section::after { height: @internal-section-overlap-height; }

    & + .uk-section { position: relative; }

    & + .uk-section-default::before,
    & + .uk-section-muted::before,
    & + .uk-section-primary::before,
    & + .uk-section-secondary::before {
        content: '';
        display: block;
        position: absolute;
        top: -(@internal-section-overlap-height);
        left: 0;
        right: 0;
        height: @internal-section-overlap-height;
        background-repeat: repeat-x;
    }

}

.hook-section-overlap() when not (@internal-section-default-overlap-image = ~'') {

    & + .uk-section-default::before {
        .svg-fill(@internal-section-default-overlap-image, "#000", @section-default-background);
    }

}

.hook-section-overlap() when not (@internal-section-muted-overlap-image = ~'') {

    & + .uk-section-muted::before {
        .svg-fill(@internal-section-muted-overlap-image, "#000", @section-muted-background);
    }

}

.hook-section-overlap() when not (@internal-section-primary-overlap-image = ~'') {

    & + .uk-section-primary::before {
        .svg-fill(@internal-section-primary-overlap-image, "#000", @section-primary-background);
    }

}

.hook-section-overlap() when not (@internal-section-secondary-overlap-image = ~'') {

    & + .uk-section-secondary::before {
        .svg-fill(@internal-section-secondary-overlap-image, "#000", @section-secondary-background);
    }

}`

**Comment by luxlogica** [comment]
@saschadube it helps a lot! Is there a way to add it to the docs?

**Comment by Stubenhocker1399** [comment]
I got the example running in SASS syntax, I took needed helper functions from [here](https://codepen.io/Kinaly/pen/OMNQpY).

Here it is:
```sass
///// Helper functions
/* ------------------------------------------------- */
/* ==from https://codepen.io/jakob-e/pen/doMoML       */
/* ------------------------------------------------- */
@function svg-url($svg){
    //    
    //  Chunk up string in order to avoid 
    //  "stack level too deep" error
    //     
    $encoded:'';
    $slice: 2000;
    $index: 0;
    $loops: ceil(str-length($svg)/$slice);
    @for $i from 1 through $loops {
        $chunk: str-slice($svg, $index, $index + $slice - 1); 
        //
        //   Encode (may need a few extra replacements)
        //
        $chunk: str-replace($chunk,'"','\'');
        $chunk: str-replace($chunk,'<','%3C');
        $chunk: str-replace($chunk,'>','%3E');
        $chunk: str-replace($chunk,'&','%26');
        $chunk: str-replace($chunk,'#','%23');       
        $encoded: #{$encoded}#{$chunk};
        $index: $index + $slice; 
    }
    @return url("data:image/svg+xml;charset=utf8,#{$encoded}");   
}

//  Helper function to replace characters in a string
@function str-replace($string, $search, $replace: '') {
    $index: str-index($string, $search); 
    @if $index { 
        @return str-slice($string, 1, $index - 1) + $replace + 
            str-replace(str-slice($string, $index + 
            str-length($search)), $search, $replace); 
    }
    @return $string; 
}

/* ------------- */
/* ==end         */
/* ------------- */

/* custom mixin to replace a defined fill color with another one */
@function svg-url-with-replaced-fill($svg, $fill-to-replace, $new-fill) {
  $replaced-svg: str-replace($svg, $fill-to-replace, $new-fill);
  $replaced-svg-url: svg-url('#{$replaced-svg}');
  @return $replaced-svg-url;
}
///// Helper functions end

$internal-section-default-overlap-image:            '';
$internal-section-muted-overlap-image:              '';
$internal-section-primary-overlap-image:            '';
$internal-section-secondary-overlap-image:          '';
$internal-section-overlap-height:                   0;

@mixin hook-section-overlap() {
    @if ($internal-section-overlap-height != 0) {
        &.uk-section::after,
        & > .uk-section::after { height: $internal-section-overlap-height; }
        
        & + .uk-section { position: relative; }
        
        & + .uk-section-default::before,
        & + .uk-section-muted::before,
        & + .uk-section-primary::before,
        & + .uk-section-secondary::before {
            content: '';
            display: block;
            position: absolute;
            top: -($internal-section-overlap-height);
            left: 0;
            right: 0;
            height: $internal-section-overlap-height;
            background-repeat: repeat-x;
        }
    }
    @if ($internal-section-default-overlap-image != '') {
        & + .uk-section-default::before {
            background-image: svg-url-with-replaced-fill($internal-section-default-overlap-image, "#000", $section-default-background);
        }
    }
    @if ($internal-section-muted-overlap-image != '') {
        & + .uk-section-muted::before {
            background-image: svg-url-with-replaced-fill($internal-section-muted-overlap-image, "#000", $section-muted-background);
        }
    }
    @if ($internal-section-primary-overlap-image != '') {
        & + .uk-section-primary::before {
            background-image: svg-url-with-replaced-fill($internal-section-primary-overlap-image, "#000", $section-primary-background);
        }
    }
    @if ($internal-section-secondary-overlap-image != '') {
        & + .uk-section-secondary::before {
            background-image: svg-url-with-replaced-fill($internal-section-secondary-overlap-image, "#000", $section-secondary-background);
        }
    }
}
```

Just like above, you need to set these variables, here is an example with a (very crude) overlap:
```scss
$internal-section-default-overlap-image:            '<svg xmlns="http://www.w3.org/2000/svg" version="1" viewBox="0 0 329 8" height="30" width="1244"><path d="M0 8c12-5 76-9 91-4 15 4 103 4 110 0s77-4 83 1 29 3 32 0c4-2 11 1 13 3z" style="fill:#000;"/></svg>';
$internal-section-muted-overlap-image:              '<svg xmlns="http://www.w3.org/2000/svg" version="1" viewBox="0 0 329 8" height="30" width="1244"><path d="M0 8c12-5 76-9 91-4 15 4 103 4 110 0s77-4 83 1 29 3 32 0c4-2 11 1 13 3z" style="fill:#000;"/></svg>';
$internal-section-primary-overlap-image:            '<svg xmlns="http://www.w3.org/2000/svg" version="1" viewBox="0 0 329 8" height="30" width="1244"><path d="M0 8c12-5 76-9 91-4 15 4 103 4 110 0s77-4 83 1 29 3 32 0c4-2 11 1 13 3z" style="fill:#000;"/></svg>';
$internal-section-secondary-overlap-image:          '<svg xmlns="http://www.w3.org/2000/svg" version="1" viewBox="0 0 329 8" height="30" width="1244"><path d="M0 8c12-5 76-9 91-4 15 4 103 4 110 0s77-4 83 1 29 3 32 0c4-2 11 1 13 3z" style="fill:#000;"/></svg>';
$internal-section-overlap-height:                   30px;
````

I, too, hope that it helps.

It would be nice if an example for this would be provided in the docs.
