### ISSUE TITLE
[Feature Request] Add More Animation Presets

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#2822]
It would be nice to have a much larger collection of animation effects to be able to use with our components. 

The well-known and highly tested **[Animate CSS](https://daneden.github.io/animate.css/)** offers many more interesting animation effects - such as the flippers, bouncers, zoom and rotating effects - that could be used very effectively as optional animation styles with switchers, the lightbox and slideshow transitions.

**Comment by saschadube** [comment]
We had the same idea when we started but in the end it's more important to keep the framework lightweight and not add to many stuff which is rarely used. Most the time subtile fade and slide animations are perfect.

**Comment by luxlogica** [comment]
@saschadube How about implementing it as an 'optional plugin' - like the 'components' were in v2?...
