### ISSUE TITLE
Add options 'max' for Sticky

### ISSUE THREAD

**Issue by wolfcreative** [uikit/uikit#2824]
### UIkit version
3.0.0-beta.28

### What we expect
The ability to use "min" and "max" in a component.
In version '2' I did like this:
`data-uk-sticky="{ media: '(min-height: 760px)' }"` - for big Sticky
`data-uk-sticky="{ media: '(max-height: 759px)' }"` - for small Sticky

### What is really going on
We are able to use only "min"

P.S. Tell me please how to do reInit/recalculate Sticky. If you use the "update" or "destroy" from the documentation, it causes errors from icons and adaptive

**Comment by janschoenherr** [comment]
With the next release you'll be able to use `media: (max-height: 759px);`

**Comment by wolfcreative** [comment]
Many thanks, you saved me. UiKit forever
