### ISSUE TITLE
calendar component

### ISSUE THREAD

**Issue by flyboarder** [uikit/uikit#2825]
It would be amazing if there was a calendar component within UIKit... just saying.

**Comment by florianletsch** [comment]
A datepicker has already been requested and it's on the list to be added, however we don't have a fixed timeline for that feature yet. https://github.com/uikit/uikit/issues/2740

**Comment by flyboarder** [comment]
date picker would be awesome, thanks for the update!

My thought regarding a calendar component is that this would be a full screen element similar to:
http://pages.revox.io/dashboard/3.0.0/html/condensed/calendar.html

where the component is a full calendar, with event items which can span times/dates.

**Comment by florianletsch** [comment]
Your example is a full calendar application. I don't think something like that will be introduced. Remember that UIkit is a collection of UI elements and components to create your own applications. A full fledged calendar application is a little out of scope I think. 

With the future datepicker and the other components that already exist however, you should be able to build your own calendar application that goes in that direction.

**Comment by shamoh19** [comment]
How to integrate UI Kit Calendar in Angular 5 app?
