### ISSUE TITLE
How to double click on hyphenated class names to select the whole name?  

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#2827]
I am learning UIkit and finding myself playing around with layouts in Chrome developer tools to see how things work - part of this involves adding and removing classes to elements that have multiple classes.

Does anyone know of a tweak to enable hyphenated class names to be selected when double-clicking? eg:

    uk-padding-remove-left // whole name can't be selected by double clicking
    uk_padding_remove_left // whole name can be selected by double-clicking

System is Ubuntu, but I wonder how people generally get around this limitation of hyphenated class names? 

**Edit:** 

For Sublime Text 3, add the following to Preferences > [User] Settings:

    "word_separators": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"

[Source](https://stackoverflow.com/a/41577838)

Not sure how to do it in Chrome developer tools though.

**Comment by aarongerig** [comment]
I don't think this is a UIkit issue at all. Maybe this might help you:
I personally use keyboard shortcuts to select words, even hyphenated one's.

On my mac a useful shortcut is `Shirt + Option + Arrow Right/Left`. It selects whole words. For hyphenated words I have to do click the `Arrow Right/Left` multiple times, but it's much faster than selecting the words with your mouse.
