### ISSUE TITLE
uk-container inside sticky uk-navbar 

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#2828]
Using *UIkit 3.0.0-beta.25*.

The goal is to have a sticky bar at the top over the whole page width and the navbar contents to use the `.uk-container` width, just like here on github: the black bar has the whole width, the navbar contents, left-aligned, have a max-width, same as the page.

When I use this:
```
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-container">
        <div class="uk-navbar-left">
```
the contents of the `.uk-navbar-left` determine the width of the `.uk-container`, which is less than the expected 1200px. The navbar contents are centered.

When I swap the `.uk-container` and `.uk-navbar-container`, the bar is not extended to the whole page width.

The `.uk-container` works fine on the page itself, outside the navbar.

Any ideas?

Thanks!
Jerry

**Comment by zzseba78** [comment]
Hi @jerry1970 , this is not the place to get help using uikit.
Please close this issue and ask in the official chat:
[https://gitter.im/uikit/uikit](https://gitter.im/uikit/uikit)

**Comment by jerry1970** [comment]
What, gitter the only way to get help? No history, no structure, 1300 people talking at the same time. I hate Slack for the office with 70 people, but gitter with so many people is even worse. Damn, this really sucks.

**Comment by jerry1970** [comment]
I was just upgrading from UIkit 2 to 3 and was having problems, but this is a reason serious enough to stop and find a different front-end framework. I hate to say it but I am really considering it right now.

**Comment by zzseba78** [comment]
If you had put your question in Gitter maybe it would already be answered. Stop complaining.
Definitely this isn´t the way to response questions dude.

**Comment by jerry1970** [comment]
OK, bye.

**Comment by saschadube** [comment]
@jerry1970 with the latest release we published some new docs and tests which will help you exactly with your question 😄 

Here are the [sticky navbar docs](https://getuikit.com/docs/navbar#sticky-navbar). They include example for the navbar with the container class.

And here are a lot of [more sticky navbar test cases](https://getuikit.com/assets/uikit/tests/sticky-navbar.html) which will help you.
