### ISSUE TITLE
Close off-canvas on clicking item

### ISSUE THREAD

**Issue by ratshili** [uikit/uikit#2829]
I have recently used UIKit for couple of sites, one thing that still challenging me is the ability to auto close off-canvas menu on clicking the menu item instead of clicking the actual close button

**Comment by janschoenherr** [comment]
Please see https://getuikit.com/assets/uikit/tests/offcanvas.html

The first _Item_ in each test case is an internal anchor and will close the Offcanvas and jump to the location.

If this resolved the issue, please close it.

**Comment by ratshili** [comment]
Thanks for the feedback @janschoenherr 

I am using **AngularJS** `ui-route` for handling pages. How would I close the menu?

My code looks like this:

`<li class="main-item" ng-class="{'uk-active': includes('home')}"><a href="#">Home</a></li>`

**Comment by Garito** [comment]
Hi!
I'm using Vuejs and I have the same problem too
I've tried to add uk-toggle="target: #my_offcanvas_menu" to the ul and to every li without success
Adding .uk-offcanvas-close does the trick but it moves the object with the class to the close button position

Sounds to me that uk-offcanvas-close must be separated in two features: the positioning of the close button and the action of closing the offcanvas

Hope this help!
Thanks

**Comment by ratshili** [comment]
Hi
Here is what worked for me:

HTML
`<li class="uk-parent"><a [routerLink]="['page-name']" (click)="closeMenu($event)">Page Name</a></li>`

Typescript:
`closeMenu(e) {
    UIkit.offcanvas('#offcanvas-usage').hide();
  }`

I hope this helps

**Comment by MateThemes** [comment]
For me worked this on a static website:

`<script>
    var util = UIkit.util;
    util.on(util.$('#tm-mobile-menu'), 'click', function (e) {
        e.preventDefault();
        UIkit.offcanvas('#tm-mobile-menu').hide();
    });
</script>`

**Comment by catedm** [comment]
I am using Next.js and encountering this problem. Is there a straightforward solution to this yet?

**Comment by antonthomas** [comment]
An easier solution is to add `uk-toggle="#offcanvas-nav"` to the items that should close the off-canvas when clicked. This is the same attribute that is used by UIKit on the uk-close buttons.

**Comment by viocassel** [comment]
`selClose` = 🤘😎

```
<div id="offcanvas-overlay-slide" uk-offcanvas="overlay: true; selClose: .uk-nav a, .uk-offcanvas-close">
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <ul class="uk-nav uk-nav-default">
            <li><a href="#">Menu Item</a></li>
            <li><a href="#">Menu Item</a></li>
            <li><a href="#">Menu Item</a></li>
            <li><a href="#">Menu Item</a></li>
            <li><a href="#">Menu Item</a></li>
        </ul>
    </div>
</div>
```

**Comment by MateThemes** [comment]
> An easier solution is to add `uk-toggle="#offcanvas-nav"` to the items that should close the off-canvas when clicked. This is the same attribute that is used by UIKit on the uk-close buttons.

Thanks for that. That works like a charm for my Nuxt 3 App
