### ISSUE TITLE
Issue with svg-fill mixin

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#2830]
### UIkit version
3.0.0-beta.28

### Browser
Microsoft Edge (40.15063.0.0, EdgeHTML 15.15063)

### Steps to reproduce
Pass a HSL or HSLA string as $color-new param to the svg-fill mixin.

### What is Expected?
A valid encoded base64 string is returned as background image.

### What is actually happening?
No background image is visible in Microsoft Edge (Windows 10) because some characters of the HSL or HSLA string aren't replaced.
This may also happend in older Browser versions with RGB or RGBA values.

Works fine on macOS (10.12.6):
Apple Safari (10.1.2)
Google Chrome (60.0)
Mozilla Firefox (54.0.1)

Works fine on Windows 10:
Google Chrome (60.0)
Mozilla Firefox (54.0.1)

### Possible fix
```
@mixin svg-fill($src, $color-default, $color-new) {

    $color-new: quote($color-new);
    $color-new: str-replace($color-new, " ", ""); // Replace spaces
    $color-new: str-replace($color-new, "%", "%25"); // Replace "%" of HSL/HSLA color values
    $color-new: str-replace($color-new, ",", "%2C"); // Replace commas
    $color-new: str-replace($color-new, "(", "%28"); // Replace opening parentheses
    $color-new: str-replace($color-new, ")", "%29"); // Replace closing parentheses
    $color-new: unquote($color-new);

    $replace-src: str-replace($src, $color-default, $color-new) !default;
    $replace-src: str-replace($replace-src, "#", "%23");
    background-image: url(quote($replace-src));

}
```

### Example calls
`@include svg-fill($internal-accordion-close-image, "#000", "#00ff00");`
`@include svg-fill($internal-accordion-close-image, "#000", "rgb(0, 255, 0)");`
`@include svg-fill($internal-accordion-close-image, "#000", "rgba(0, 255, 0, 0.75)");`
`@include svg-fill($internal-accordion-close-image, "#000", "hsl(120, 100%, 50%)");`
`@include svg-fill($internal-accordion-close-image, "#000", "hsla(120, 100%, 50%, 0.75)");`

**Comment by DeligiannisGeorge** [comment]
Hi, 

I tried this solution but i get the following error:

  ERROR in ./src/assets/scss/all.scss (./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/src??ref--4-3!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--4-5!./node_modules/sass-resources-loader/lib/loader.js??ref--4-6!./src/assets/scss/all.scss)
    Module not found: Error: Can't resolve '../../../node_modules/uikit/src/scss/str-replace(str-replace("data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Crect%20fill%3D%22' in 'C:\Code\Pocasport\.Website\web\src\assets\scss'
     @ ./src/assets/scss/all.scss (./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/src??ref--4-3!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--4-5!./node_modules/sass-resources-loader/lib/loader.js??ref--4-6!./src/assets/scss/all.scss) 7:30264-30541

Any recommendations?
