### ISSUE TITLE
Dragging sortable with nested form controls

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#2832]
### UIkit version

3.0.0-beta.28

### Reproduction Link

https://codepen.io/anon/pen/KvWMdM

### Steps to reproduce

Open reproduction link.
Change the value of any of the input form fields.
Start dragging the card with the changed input value.

### What is Expected?

Input shows the current value while dragging the sortable item.

### What is actually happening?

Input shows the initial value while dragging the sortable item.

It is confusing for the user to see a different value of an input he has already changed while dragging.
This is also happening with other form controls e.g. select, textarea, checkbox, radio button, range.

This issue is reproducible in any browser.

**Comment by joagre** [comment]
I have this exact problem as well. Did you find a workaround?

**Comment by JonTDev** [comment]
Hey, not sure if you're still looking for a workaround.

I fixed this by adding a keyup event that updates the actual attribute value with the value itself.  The element does not actually update the value itself just the data inside the object.  So by doing this when moving the object "it uses the attribute, not the data" it will be visible. 

Hope this helps.

**Comment by Lumelomser** [comment]
Thanks for your feedback JonTDev!

I already did it the way you described but the downside of this workaround is, that if you have additional form elements (e.g. checkboxes or radio buttons) the issue is still present.
Or you have to handle each kind of form element in it's own way.
