### ISSUE TITLE
uk-scrollspy-nav change uk-active takes some miliseconds to change class

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2837]
### UIkit version

3.0.0-beta.28

### What is actually happening?
When i am using uk-scrollspy-nav after click of link uk-active class takes some time to change class name and when i click on first link again its works perfect. like next link of<a> has issue.

**Comment by Riddler84** [comment]
Are you using the scroll component in combination? The active status is only applied, if the anchor is in viewport. And if you have a long text, the scrolling could need a moment.

Nevertheless a codepen example is always helpful.

**Comment by theromie** [comment]
`<ul class="uk-tab uk-scrollspy-nav="closest: li; scroll: true; offset:130"></ul>`

**Comment by janschoenherr** [comment]
Please provide a minimal Codepen that can reproduce the bug. You could start with this template: http://codepen.io/anon/pen/XMpryM
