### ISSUE TITLE
Dropdown in dropbar misaligned

### ISSUE THREAD

**Issue by rakr** [uikit/uikit#2838]
Not sure if it is an issue or a misunderstanding on my end, but I posted this issue on Gitter and got no response.

### UIkit version

3.0.0-beta.28

### Browser
Tested on Chrome and Safari

### Reproduction Link

https://codepen.io/rakr/pen/EvWLXJ

### Steps to reproduce
Hover on 'ITEM 4' hover and on the other items to see the difference
![issue_with_uikit_dropbar_and_ _uikit_uikit_-_gitter](https://user-images.githubusercontent.com/110558/29143627-2d597c48-7d99-11e7-8e46-477b542ea88f.png)

### What is Expected?
Items in the 'ITEM 4' dropdown to be aligned with the 'ITEM 4' label
Below the user Is hovering on item 5 (the last one)
![issue_with_uikit_dropbar](https://user-images.githubusercontent.com/110558/29143692-5c6160be-7d99-11e7-9d05-2db93ef925ef.png)

And here the user is hovering on Item 3
![issue_with_uikit_dropbar](https://user-images.githubusercontent.com/110558/29143744-8d33a166-7d99-11e7-96a6-8a88c4d62a12.png)

### What is actually happening?
The dropdown items of the item before the last is misaligned, for instance if the navbar would have had only 4 items, 'ITEM 3' dropdown items would be misaligned.

**Comment by janschoenherr** [comment]
The dropdown from _Item 4_ flips to be bottom-right aligned, because it does not fit. If you adjust the width it should work. You'll have the same issue with _Item 5_

**Comment by rakr** [comment]
Thanks for the explanation, closing the issue down.
