### ISSUE TITLE
Background component and uk-panel

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#2839]
Hi

On [Background component](https://getuikit.com/docs/background) markup you are using `uk-panel` class which was a v2 core class and seems to be removed from v3. 

What is the benefit of still using this additional class in your markup?

BTW I am a little bit confuse about [Tile component](https://getuikit.com/docs/tile). I don’t really understand the benefit of such component as it seems to have the same behavior than a `uk-background-* uk-padding` except that Tile is taking care by itself of dark/light color.

Thanks to clarify

**Comment by Riddler84** [comment]
`uk-panel` is still part of v3. https://getuikit.com/docs/utility#panel
The benefit of tiles is discussable, but it's an easy way to make colored boxes. It combines several components, if you will..
