### ISSUE TITLE
Offset 0 not working inside menu

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#2840]
UIkit version
3.0.0-beta.28

Reproduction Link
https://codepen.io/anon/pen/brRpYK

`Offset 0` isn't working with `uk-navbar-dropdown uk-dropdown`.

**Comment by janschoenherr** [comment]
`<div class="uk-navbar-dropdown uk-dropdown="offset:0;">`

needs to be

`<div class="uk-navbar-dropdown" uk-drop="offset:0;">`

We'll add a check that lets you use both Drop and Dropdown in the future.

**Comment by janschoenherr** [comment]
Resolved with 64d68073f0062c8966c36fd0eb0c3c23913e2e4f
