### ISSUE TITLE
Offcanvas + Scroll link doesn't work

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2842]
Scroll option doesn't work on links which are in offcanvas menu.

**Comment by vc-development** [comment]
+1

**Comment by aarongerig** [comment]
Yes it works, here's an example: https://codepen.io/aarongerig/pen/xLLvOp

**Comment by PixelT** [comment]
https://codepen.io/anon/pen/eEGzoZ ;)

**Comment by aarongerig** [comment]
Yes, but I'm not sure if that's a real issue when you can solve this in other ways. Don't you think my example would work for you?

**Comment by vc-development** [comment]
With `uk-offcanvas` works, but with `uk-offcanvas="overlay: true"` does not work.
