### ISSUE TITLE
Dropdown closes when clicking on next button of flatpicker date

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2843]
### UIkit version

3.0.0-beta.28

### What is actually happening?
I am using flatpicker date plugin and using range option but when i click on next option to go to next month dropdown is getting closed.
here is link to checkout - [https://jsfiddle.net/41m0q5hm/](url)
it should open till i select range

**Comment by janschoenherr** [comment]
You'll have to prevent the _click_ event from reaching the document. That way, UIkit won't close the drop.

`jQuery(document).on('click', '.flatpickr-calendar', function(e) {e.stopPropagation();})`

**Comment by theromie** [comment]
But I am using Vue js to implement date filter

**Comment by janschoenherr** [comment]
No problem you can use the code in your Vue app.
