### ISSUE TITLE
Scrollbar goes missing after switching tabs

### ISSUE THREAD

**Issue by stanleyxu2005** [uikit/uikit#2844]
I'm using the 3.0.0-beta.28. I created two tabs, one tab contains a iframe. The first time it is loaded, it will have scrollbar x and y. But after I have switched to tab 2 and then switched back to tab 1, all scrollbar will be gone (the scroll position will be remembered)

http://jsbin.com/jaxabokuka/1/edit?html,output

It looks most likely a problem of jquery. But this does impact uikit. Do you consider this is a bug? Any hints are highly appreciated. 

Update 1: It happens on my macbook but not happen on my Windows 7. For the time being, I dont use the js implementation, but write my own tab switching using ui-router.

**Comment by aarongerig** [comment]
On what browser(s) does this happen to you? I cannot reproduce your problem on Chrome 60 and Safari 10. The one thing I would change in your code though is the version of jQuery. Please always use the latest (currently v3.2.1) available.

**Comment by stanleyxu2005** [comment]
Oh, it seems to be a problem of Chrome 59. I have now updated to Chrome 60, and the problem is gone.
