### ISSUE TITLE
How to enable cursor:pointer on .uk-form-icon:hover?

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#2845]
Like:  

    .uk-form-icon:hover {cursor: pointer}

I tried on Codepens linked here:

https://getuikit.com/docs/form#form-and-icons

And set `z-index` of `uk-form-icon` to `999999` but pointer still doesn't seem to show.

It is for scenario where icon is a datepicker trigger.

**Comment by Riddler84** [comment]
Try `.uk-form-icon {cursor: pointer}`. The `:hover` makes no sense, because you see the cursor change always only at hovering over the element.

**Comment by oshihirii** [comment]
Unfortunately that doesn't work, it still displays the `cursor: text` style cursor.  

I can apply `cursor:pointer` to the whole input, but it's not an ideal solution.

**Comment by Riddler84** [comment]
It works as i described it. I think, you have forgotten to make it important.
https://codepen.io/Riddler84/pen/WEEBOX?editors=1100#0

**Comment by aarongerig** [comment]
@oshihirii With the following markup `cursor: pointer` will be set automatically, since the icon is a clickable link:

```html
<div class="uk-inline">
    <a class="uk-form-icon uk-form-icon-flip" href="" uk-icon="icon: user"></a>
    <input class="uk-input">
</div>
```

**Comment by oshihirii** [comment]
@Riddler84 - Ah yes, I can see with your implementation (also requires `pointer-events` definition), it works:
```css
.uk-form-icon {
  pointer-events: auto !important;
  cursor: pointer;
}
```

Thanks @aarongerig, will try that too.

**Comment by ruwmapps** [comment]
add class uk-icon-link
