### ISSUE TITLE
dropdown menu doesn't disappear on click when use uk-scroll in a:href

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#2848]
### UIkit version

3.0.0-beta.28

### Browser
only tested in chrome

### Reproduction Link

https://codepen.io/anon/pen/XazLXO

### Steps to reproduce
in one page site, used uk-scroll in ahref links in navbar dropdown

### What is Expected?
when click the sub-item, page should scrolls to the selected id and dropdown menu should disappear.

### What is actually happening?
page scrolls to the selected id but dropdown menu is still open

**Comment by aarongerig** [comment]
For that you'd have to explicitly `hide()` the dropdown on click, since you're not loosing focus on it. https://codepen.io/aarongerig/pen/BdmXmM

**Comment by tyler-x** [comment]
thanks a lot!
