### ISSUE TITLE
Does UIKIT only work with JS enabled?

### ISSUE THREAD

**Issue by suntrop** [uikit/uikit#2849]
Of course some parts like modal windows, tabs lightbox etc. will require JS

But what about the grid? That is the most essential part and when I disabled JS it won't work. The columns are stacked instead of next to each other.

**Comment by aarongerig** [comment]
The grid uses the following syntax:

`<div uk-grid> ... </div>`, which intializes the grid using Javascript. It adds dynamic vertical margin to its children. If you want to use the grid without Javascript, simply use the following syntax:

`<div class="uk-grid"> ... </div>`, but with that you lack the dynamic margin.

Either way, I recommend you using the javascript code provided by UIkit. Makes it so much more powerful. ;)

**Comment by suntrop** [comment]
Thanks and sorry for the delay. 
I couldn't figure out what exactly you mean by "dynamic margin". Actually this post comes first when I google uikit dynamic margin :-)

However, my concern was what happens without JS. Would it be ok to use <div class="uk-grid" uk-grid> ? I don't see any side effects. That way I have the benefits of JS and a fallback for none JS users.

**Comment by zzseba78** [comment]
UIkit applies margin to the previous row in the grid, and this margin depends on the screen size and gutter.
Check this example with js, and then remove the `uk-grid` attribute ( leave the .uk-grid class ) to se the difference.
https://codepen.io/zzseba78/pen/QMmXKK

**Comment by suntrop** [comment]
Thanks, will stick with foundation
