### ISSUE TITLE
uk-dropdown shows initially

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2851]
I am loading uk-dropdown using `<div uk-dropdown></div>` so which will dynamically call dropdown from JS. My JS file is at bottom which make my design unstructured display on site. How can i stop this. When load web page its opens the dropdown after loading js its hide dropdown.

**Comment by janschoenherr** [comment]
You'll have to initially add the _uk-dropdown_ class manually or not defer UIkit all together.
