### ISSUE TITLE
checkbox & radio styling

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#2853]
The styling of the checkboxes & radios is not working in Firefox and working only partially in IE11 (haven't tested on Edge)

**Chrome:**
![image](https://user-images.githubusercontent.com/14207860/29508173-61d8317a-864b-11e7-9e1e-ffcd296cd7f9.png)

**Firefox:**
![image](https://user-images.githubusercontent.com/14207860/29508182-682ada78-864b-11e7-9edd-f87c872bedcc.png)

**IE11:**
![image](https://user-images.githubusercontent.com/14207860/29508192-7143f0ea-864b-11e7-8ab4-9cf6721bb8aa.png)

**Comment by vc-development** [comment]
**Chrome** (latest):
![d1g05jclqiauhan2kunicg](https://user-images.githubusercontent.com/30495232/29508611-d97d5b8a-865d-11e7-9108-eb1e17e6fa26.jpeg)

**Firefox** (latest):
![ksmhxar4r8a3gjbkemgzxw](https://user-images.githubusercontent.com/30495232/29508668-02831e5c-865e-11e7-91d5-49f6347d78bb.jpeg)

**IE11** (latest):
![adoe0peatouaoqzpd2etqw](https://user-images.githubusercontent.com/30495232/29508697-2f9cdec8-865e-11e7-91cb-b163f8f50b35.jpeg)

**Comment by saschadube** [comment]
Unfortunately it's not possible to style checkboxes and radio buttons in Firefox und IE11.

There is also a note in the [form component](https://github.com/uikit/uikit/blob/develop/src/less/components/form.less#L436).

```less
/* Radio and checkbox
 * Note: Only works in Chrome, Safari, Opera and Edge
 ========================================================================== */
```

**Comment by Septdir** [comment]
Add ` -moz-appearance: none;` and radionand checkboxes worn on firefox

**Comment by saschadube** [comment]
@Septdir 😵 🙈  Whut?! I'm pretty sure we tested it and something didn't work. But you are right, looks fine for me! Thanks 😄  If nothing comes up, it will be included in the next release.

https://github.com/uikit/uikit/commit/d67f4a3b7610d862ac722ae84b6c005cad2cd88a
