### ISSUE TITLE
uk-sticky sticks to soon after being repositioned

### ISSUE THREAD

**Issue by pieterwouda** [uikit/uikit#2854]
### UIkit version

3.0.0-beta.28

### Browser

Google Chrome Version 60.0.3112.101

### Reproduction Link

https://codepen.io/anon/pen/LjmGpP

### Steps to reproduce

See reproduction link.
Click on 'Click here to expand!!!' to display the hidden content, so it will reposition the 'sticky' content.

### What is Expected?

It is expected that the 'sticky' content only sticks to the top when it reaches the top.

### What is actually happening?

![](http://i.imgur.com/X5p7msl.jpg)

**Comment by janschoenherr** [comment]
This seems to be resolved. If the issue persists, please open another issue. Thanks.
