### ISSUE TITLE
modal close icon is missing when modal is added dynamically to the page

### ISSUE THREAD

**Issue by pieterwouda** [uikit/uikit#2856]
### UIkit version
3.0.0-beta.30

### Browser
Google Chrome Version 60.0.3112.101 

### Reproduction Link
https://codepen.io/anon/pen/vJjPbo

### Steps to reproduce
See reproduction link.
Click on 'Show Modal with Icon' to see the modal with the close icon.
Click on 'Show Modal without Icon' to see the modal with the missing close icon.

I'm using Vue's 'v-if' to lazy load the modal component.
When the 'v-if' expression is true, then the modal is added to the DOM.

In my Vue application, when the modal is loaded/shown for the first time, the close icon is missing. When it's loaded for the second time, the close icon is visible.

In the codepen example I'm somehow trying to simulate the behaviour by injecting the modal into another div first.

It's probably more related how svg icons are added to the DOM.

### What is Expected?
A visible close icon when the modal is loaded/shown.

### What is actually happening?
![](http://i.imgur.com/iKnNGWQ.jpg)

**Comment by i-am-the-slime** [comment]
I also have a weird problem with the SVG icons in that when I have one in the clickable icon in input it closes the modal. If I click on the `<a>` containing the icon, it works fine.

**Comment by aarongerig** [comment]
@i-am-the-slime Prevent DOM bubbling with:
```js
$('#my-svg').on('click', function(e) {
    e.stopPropagation();
});
```
