### ISSUE TITLE
import uikit 2 in nuxt.js

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#2859]
Hi,

How to import `UIkit 2 javascripts` in nuxt.js project ?

**Comment by lukeroc** [comment]
@janschoenherr - this issue may solve your problem: https://github.com/nuxt/nuxt.js/issues/178

**Comment by vuchl** [comment]
Uikit 3 here: https://github.com/nuxt/nuxt.js/tree/dev/examples/uikit

**Comment by nigeltiany** [comment]
@vuchl the example works great until you use a component that requires JS and some UIKit JS code changes the DOM and because of ```ssr: false``` I get the error 

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. 
This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. 
Bailing hydration and performing full client-side render.
```
setting ```ssr: true``` brings the famous ```window is not defined error```. 
I have tried importing UIKit Js as an array item in the vendor settings but i get the first error.

**Comment by miladmeidanshahi** [comment]
it so bad uikit teams abandon Uikit2 suppuration, i know that they are working on Uikit3 but they should understand most of people use Uikit2 in production.

**Comment by aarongerig** [comment]
@miladmeidanshahi UIkit v2 support is **NOT** abandoned. They still provide bug fixes for it, only new features are not implemented anymore. Also, I highly suggest you guys to use v3, even in production. Our agency is doing it and we absolutely love it! There‘s no need to stick around with v2 when v3 is already production-ready. Go give it a try! ;)

**Comment by gustojs** [comment]
@aarongerig how about the same issue with server side rendering in v3? Uikit tries to use `document` and `window` but there are no `document` and `window` on the server.

**Comment by aarongerig** [comment]
@gustojs That‘s correct, right now UIkit is not optimised for server side rendering. Maybe you could provide a pull request to solve your problems?

**Comment by galaxyblur** [comment]
For what it's worth, I was having trouble learning how to load UIkit in Nuxt and came across this thread. I found a working solution for UIkit 3 here: https://github.com/nuxt/nuxt.js/tree/dev/examples/uikit

**Comment by olegpopovskiy** [comment]
@nigeltiany did you find a solution to solve the problem with markup ? Can you share your nuxt config?  I remarked, that the last version of the uikit that works correctly with nuxt, was beta 12.

**Comment by janschoenherr** [comment]
UIkit 3.4.5 added a check for window and document. Does that solve the issue?

**Comment by eljass** [comment]
@janschoenherr 

Including UIKit v3 in nuxt without `ssr: false` or `mode: 'client`' brings error:

```
ReferenceError:
Element is not defined
```

![UIKit error](https://user-images.githubusercontent.com/7661970/84904628-32bdec00-b0b8-11ea-9439-40528f7894b0.png)
