### ISSUE TITLE
Feature request: Add class .uk-dropdown-close to dropdown container or to item to hide dropdown when user click on item.

### ISSUE THREAD

**Issue by MadeInSwitzerland** [uikit/uikit#2860]
### UIkit version
3.0.0-beta.30

### Feature request
Would it be possible to add to the hide on clicking for dropdowns like in UIKit 2. That is: 
Add class .uk-dropdown-close to dropdown container or to item to hide dropdown when user click on item.

**Comment by aarongerig** [comment]
A little bit of custom javascript and the desired functionality is there.
https://codepen.io/aarongerig/pen/YxJogE

**Comment by MadeInSwitzerland** [comment]
Thanks und Grüsse aus Zürich.

**Comment by aarongerig** [comment]
Please close this issue, since it is resolved. Thanks!
