### ISSUE TITLE
uk-table-shrink issue with images

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#2861]
When applying the class _uk-table-shrink_ to a table cell that contains text, the styling is applied correctly and the width of the cell if set to the cell content. However if the cell contains image the width is set to 1px, essentially hiding the content.

I tried to force it by applying to the image tag:
 _width="40" height="40"_ 
and
_style="width:40px;height:40px;"_ 

but none of this worked.

The only way around this is to apply the style to the table cell itself.

**Comment by zzseba78** [comment]
Maybe it´s intended to use with shrink text... did you try uk-width-auto? I think it will work great with images.

**Comment by psuplat** [comment]
Ah, that explains it. Somehow I missed that part of documentation.
It all works now, thanks.
