### ISSUE TITLE
UIKIT BETA ISSUES: UK-CARD UK-INPUT, Images Not Responsive On Mobile

### ISSUE THREAD

**Issue by chimsgraphic** [uikit/uikit#2862]
I built a new platform entirely on the new beta of UIkit, but I was shocked when I discovered that the uk-card and uk-input are not responsive on mobile. I was kind of disappointed. I started to modify the classes.

**Comment by aarongerig** [comment]
What are you talking about? What about the card and form elements is not responsive in UIkit v3?
https://getuikit.com/assets/uikit/tests/card.html
https://getuikit.com/assets/uikit/tests/form.html

I'm sure you are doing something wrong.

**Comment by chimsgraphic** [comment]
Visit this link on mobile: http://www.vidapple.com/latest_movies

**Comment by chimsgraphic** [comment]
http://www.vidapple.com/signin

**Comment by chimsgraphic** [comment]
Visit this link on mobile: http://www.vidapple.com/signin

I know what am taliking about..

**Comment by chimsgraphic** [comment]
I built everything entirely with UIKIt following this documentation: https://getuikit.com/docs/card

**Comment by psuplat** [comment]
I quick look at the source of your signin page and I can see that you have not use grids at all, only flex.
Lead devs please correct me if I'm wrong, but while flex is nice I think it has to be combined with grid to work fully on mobile devices.

**Comment by chimsgraphic** [comment]
In bootstrap framework, everything is very responsive. I wonder why UIkit should be any different. If I create an exact replica in bootstrap it will be mobile friendly..

**Comment by psuplat** [comment]
@chimsgraphic - point in case. To make Bootstrap page responsive you have to use their grid system (there is no Flex in v3, and not sure how it works in v4).

Redesign your page using UIKit grid ( https://getuikit.com/docs/grid ) combined with Flex ( https://getuikit.com/docs/grid#grid-and-flex ). Shouldn't take you very long

**Comment by psuplat** [comment]
try this:
```
<div class="uk-container uk-container-large uk-position-center">
	<div uk-grid>
    <div class="uk-flex uk-flex-center@s uk-flex-center@m uk-flex-center@l uk-flex-center@xl" >  
         <div class="uk-card uk-card-default">
             <div class="uk-card-header uk-header-signin">
                <h3 class="uk-card-title uk-text-white">Sign In</h3>
             </div>
             
             <div class="uk-card-body">
                 <form id="signin">
            
                    <div class="uk-margin">
                       <input class="uk-input uk-form-width-large@m" id="email" name="email" placeholder="Email Address" type="text">
                    </div>
                    <div class="uk-margin">
                       <input class="uk-input uk-form-width-large@m" id="password" name="password" placeholder="Password" type="password">
                    </div>
                    <div class="uk-margin">
                       <button class="uk-button uk-text-white uk-button-apple-signup" id="btnsignin">Sign In<span uk-icon="icon: sign-in" class="uk-icon"><svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" icon="sign-in" ratio="1"><polygon points="7 2 17 2 17 17 7 17 7 16 16 16 16 3 7 3"></polygon><polygon points="9.1 13.4 8.5 12.8 11.28 10 4 10 4 9 11.28 9 8.5 6.2 9.1 5.62 13 9.5"></polygon></svg></span></button> <div class="login_result" id="login_result"></div>
                    </div>
   
                 </form>
             </div>
		</div>
    </div>
	</div>
</div>
```

notice the `<div uk-grid>` right after the container div and before flex div (don't forget to close it after too). Also on the form inputs I have changed `uk-form-width-large` to `uk-form-width-large@m`

Hopefully this will put you in the right direction.

I was/am moving some of my projects from Boostrap to UIkit v2 and now v3. The two frameworks work quite differently and it took me a while to get used to the way UIkit handled the things, and I still get through a lot of trial & error steps to get what I need.

**Comment by chimsgraphic** [comment]
Thanks alot, psuplat for the help, I appreciate.

I'll give it a try

**Comment by chimsgraphic** [comment]
I tried It still did not work

**Comment by zzseba78** [comment]
Well, some corrections here.
First:  `uk-flex uk-flex-center@s uk-flex-center@m uk-flex-center@l uk-flex-center@xl` This is redundant, no need to do this, you don´t have to declare a property in every breakpoint if it doesn´t change.

Second: no need to use grid in this case since there are no columns involved.
Third: `uk-form-width-large@m` you don´t need this, you want your form elements to take the 100% width available, and this is the default style so you can remove this.

You just need a container ( 100% width and height ) , and a card container to set the desired width. This is centered using flex in the main container.

Check this pen: 
https://codepen.io/zzseba78/pen/wqQzZB

**Comment by chimsgraphic** [comment]
I guess I may have to borrow some classes from almighty bootstrap4. UIkit is nice, but not still very perfect. The really need to do alot in improving responsiveness on all components.

**Comment by zzseba78** [comment]
Sorry, i have to shay this: you don´t know how to use UIkit. So you have two options: learn, or go back to Bootstrap. I used Bootstrap for years, and UIkit it´s far better to me.

**Comment by chimsgraphic** [comment]
Thanks zzseba78. I'll try this

**Comment by zzseba78** [comment]
If you want a fixed size in the card, set the width: value; i just put max-width to it, and flex affect the width of items.

**Comment by zzseba78** [comment]
Please, close this issue, since this isn´t a UIkit issue.
If you need help from other people go here: https://gitter.im/uikit/uikit

**Comment by aarongerig** [comment]
Thanks @zzseba78 for saying it out loud!

**Comment by chimsgraphic** [comment]
@zzseba78 Still did not work as it supposed to. Media query needed.

**Comment by chimsgraphic** [comment]
You guys are just blinded in the Euphoria of the framework. UIKIT IS NOT PERFECT! Interracial marriage between bootstrap and uikit is the way to go. Bye guys...

**Comment by zzseba78** [comment]
@chimsgraphic You have not idea of what you are talking about dude...

**Comment by chimsgraphic** [comment]
@zzseba78 Why all the CSS modifications? If it's a perfect framework. Do I need to do that when am using bootstrap? Or is this my 1st time developing UI.

**Comment by chimsgraphic** [comment]
.login-wrap {
  max-width: 320px;
}
@zzseba78 is that part of UIKIT?

**Comment by zzseba78** [comment]
@chimsgraphic Sorry, the time to help you it´s over, i don´t like your attitude... 
Go and lick Mark Otto´s balls. 🤣

**Comment by viocassel** [comment]
![giphy 2](https://user-images.githubusercontent.com/3341562/29833245-77be9fb6-8cf3-11e7-8e50-96f6737997e8.gif)

**Comment by chimsgraphic** [comment]
The ground will always ur ice cream.
