### ISSUE TITLE
Documentation readability

### ISSUE THREAD

**Issue by pentool** [uikit/uikit#2863]
Hello,

I only have a minor issue with the documentation. Not sure how others feel about it, but I find the v3 documentation giving me an eye strain after 15-20 or so minutes of reading. There's not much contrast between the light gray text and the white background. Was wondering if the text color could be made somewhat darker to increase the contrast - similar to the documentation for v2.

Thanks.

**Comment by bbashy** [comment]
What OS, browser, and DPI are you viewing it on?

**Comment by pentool** [comment]
OS X | Safari, FF, Chrome | 72 PPI (if you meant resolution, it's 2560x1440)
![uikit-docs](https://user-images.githubusercontent.com/1972916/29836216-612b68d2-8ca9-11e7-9b81-270309892a7c.png)

**Comment by bbashy** [comment]
Hmm, to me it looks OK. I am on 220ppi/dpi on 2880x1800, so it could look different to you.

**Comment by pentool** [comment]
I agree, on a MacBook Pro 13" standard resolution, it is ok. But the laptop is also about 14 inches closer to my face than the monitor :-)

**Comment by zzseba78** [comment]
Not the coolest solution, but in few seconds you can change the color and size of the font... and you can navigate the docs because it doesn´t refresh...
I don´t digg it but maybe there is a way that you can store this preference for the website in your browser...

![captura de pantalla 2017-08-29 a la s 15 24 59](https://user-images.githubusercontent.com/5558563/29837446-8500bdc8-8cce-11e7-8664-0ed13b296740.png)

**Comment by pentool** [comment]
Thanks, I think I'll just stick to my Gunnar glasses for now :-) It helps when I view large white areas with light colored text for a long time.

**Comment by su-narthur** [comment]
If you're using [Chrome](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/) there's always [Stylish](https://userstyles.org/)...

**Comment by janschoenherr** [comment]
Please move the issue/discussion to https://github.com/uikit/uikit-site. Thanks.
