### ISSUE TITLE
Dragging a sortable item inside a modal closes modal on release

### ISSUE THREAD

**Issue by su-narthur** [uikit/uikit#2866]
### UIkit version

3.0.0-beta.30

### Browser

Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Reproduction Link

https://codepen.io/narthur/pen/oeQrpx

### Steps to reproduce

1. Create modal with uk-sortable inside
2. Try to drag something in sortable in the open modal

### What is Expected?

Modal should stay open when resorting sortable items.

### What is actually happening?

Modal closes when sortable item dragged to a new location.

**Comment by gregBerthelot** [comment]
@gregBerthelot

**Comment by gregBerthelot** [comment]
It was working on v2 https://jsfiddle.net/Greggg/r2gLpq49/

**Comment by aarongerig** [comment]
Alright, so after a long time trying to prevent the modal from closing, I finally came up with some kind of workaround. It is very ugly, doesn't work properly (`esc-close` and `bg-close` don't work any longer) and should only be used as a temporary hotfix: https://codepen.io/aarongerig/pen/Qqbrmo

Again, this is not a solution to this problem and should be taken care of elsewhere!

**Comment by gregBerthelot** [comment]
Thanks @aarongerig for helping. For sure the UIkit team @saschadube should consider a better fix for this issue.

**Comment by janschoenherr** [comment]
This was fixed with one of the previous releases.
