### ISSUE TITLE
Documentation: uk-background-norepeat vs uk-background-no-repeat

### ISSUE THREAD

**Issue by pentool** [uikit/uikit#2869]
A minor issue on the 3.0 documentation page https://getuikit.com/docs/background, under the "No repeat" section.

The CSS class snippet (in red) once displayed as `uk-background-no-repeat` and right below it with no dash `uk-background-norepeat`.

**Comment by aarongerig** [comment]
Created a PR to fix that (see above). Thanks for reporting it!
