### ISSUE TITLE
[Feature request] All features missing from UIkit v2

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#2872]
Hi,
I'm going to migrate my UIkit v2 projects to v3 version as soon as the library will be stable.

Are you going to add all missing v2 features (mainly JS) to v3?

- Thumbnail
- Autocomplete
- Datepicker
- Slider / Slideset / Slideshow
- Search with auto-enlargement on focus
- Nestable
- Timepicker

Thanks.

**Comment by danny-englander** [comment]
@robertotremonti Please have a look at https://github.com/uikit/uikit/issues/2379#issuecomment-278691968 for more info.

**Comment by robertotremonti** [comment]
Thank you, @danny-englander.
I couldn't find any mentions on autocomplete, but I guess it's already included in the to-do list.
