### ISSUE TITLE
Using dropdown inside a modal triggers events on the modal

### ISSUE THREAD

**Issue by kbredemeier** [uikit/uikit#2876]
### UIkit version

3.0.0-beta.30

### Browser

Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Firefox 55.0.2 (64-bit)

### Reproduction Link

https://codepen.io/piratenpete/pen/mMgzEp

### Steps to reproduce
1. Click open to open the modal. An alert announcing the `show` event on the modal shows.
2. Dismiss the modal
3. Click the Open Dropdown button. Again the `show` event is triggered and an alert shows.

### What is Expected?

None of the modal events are emitted when interacting with the dropdown.

### What is actually happening?

The modal emits the same events as the dropdown on opening/closing

**Comment by janschoenherr** [comment]
Please see https://github.com/uikit/uikit/issues/2975#issuecomment-341706718
