### ISSUE TITLE
SlideSet, Slideshow

### ISSUE THREAD

**Issue by AlteraWeb** [uikit/uikit#2877]
Привет,  очень очень нужен Slideset и slideshow как в uikit2 уже столько времени прошло и не как не выйдет, плз сделайте слайдеры и продолжайте фиксить, я в коде нашел слайдшой,  я так понял он в lightbox работает. Сил моих нет уже ждать,  устал ставить чужие слайдеры и адаптировать их. 

или хоть какой-то туториал как написать плагин я сам напишу... 

---- Google translate ----

Hi, very much needed Slideset and slideshow as in uikit2 it's been so long gone and not how it will not work, plz make sliders and continue to fix, I found the slideshow in the code, I understand it works in lightbox. I have no strength to wait, I'm tired of putting other people's sliders and adapting them.

or at least some tutorial how to write a plugin I myself will write ...

**Comment by AlekVolsk** [comment]
попробуйте использовать повсеместно http://kenwheeler.github.io/slick/ - много эффективнее и быстрее, чем решения uikit2, да и в тройке вы еще долго ждать релиза будете

**Comment by vc-development** [comment]
Я использую [Flickity](https://flickity.metafizzy.co/) как временное решение...

**Comment by viocassel** [comment]
Я использую [Flickity](https://flickity.metafizzy.co/) как временное решение...

**Comment by AlteraWeb** [comment]
AlekVolsk, Спасибо,  его и юзаю,  но хотелось бы чтоб все было в любимом uikit. Осталось тока это, все остальное работает как часики.

Я почти написал плагин, но у меня проблема в том что я не знаю апи,  и почти все на jquery  и не знаю как получить текущее разрешение чтоб показать нужно кол-во элементов (Small, Medium, Large и другие).  

Все же 3-ка мне больше нравится, но слейдеров не хватает,  а подключать все что тока можно найти в интернете не люблю, лучше когда все в одном.

**Comment by bdthemes** [comment]
Really missing SlideSet and Slideshow in uikit3 😟

**Comment by imarkdesigns** [comment]
kens burn also please...

**Comment by eladnova** [comment]
@bdthemes Those two and dynamic masonry grid.

**Comment by kspatz** [comment]
Count me in too.  I've been using V2 because V3 feature parity not quite there yet, but as support for V2 is no longer a priority I don't want to continue doing new projects with it.

As mentioned earlier, it would seem that most of the javascript is already in place but the css needs to be added.  With slideshows being a nearly core component on so many websites this seems like a top of the page feature requirement.  Can you let us know if this is an active priority or should we not expect to see it any time soon.  You've got a great product, but I need to pre-plan three new projects now and have to decide what framework will work best.

**Comment by aarongerig** [comment]
Slideshow, Dynamic Grid and removing the jQuery dependency will be the next tasks.

**Comment by kspatz** [comment]
Possibly in beta .31?

**Comment by viocassel** [comment]
In UIkit 3 Stable.

**Comment by kspatz** [comment]
Is Uikit 3 Stable coming soon?

**Comment by bdthemes** [comment]
uikit development going slow from last month, what happen?

**Comment by Baro82** [comment]
Waiting for the slideshow to be integrated, I've created a version for my needs. I hope to help others, here the complete example:

https://jsfiddle.net/bnwn5t7L/1/

**Comment by janschoenherr** [comment]
Slideshow has been added.

**Comment by eladnova** [comment]
@janschoenherr  Does the slideshow support nested content or just single images?
IE if I wanted to have a background photo as per current functionality but with 2 columns on text on top.
