### ISSUE TITLE
** Feature Request ** Responsive Flex Vertical Alignment

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2878]
### Responsive Flex Vertical Alignment
Since Horizontal alignment it´s already implemented, it would be great to have a responsive Vertical alignment with Flex. This is useful for several layout cases, like this:

![flex](https://user-images.githubusercontent.com/5558563/30212000-7a341694-9479-11e7-82aa-00232b43ba02.png)

**Comment by aarongerig** [comment]
Uummm... https://getuikit.com/assets/uikit/tests/flex.html ?

**Comment by zzseba78** [comment]
@aarongerig Yes, but that you can specify breakpoints, like Horizontal alignment.
For example: `uk-flex-top uk-flex-middle@m`

**Comment by aarongerig** [comment]
Well, you could add responsive classes pretty much everywhere. But I don't like the idea of having this functionality everywhere, because of code bloating. Let's keep UIkit as small as possible, don't you think?

What about some custom CSS? It's fairly easy.

**Comment by zzseba78** [comment]
You are right that it´s good to have UIkit light, but with the fact that there is a responsive horizontal feature, don´t have the same for vertical is seems inconsistent to me, since both are useful and quite used.
But if this is not taken into account, surely  i will extend this functionality in less 😃

**Comment by zzseba78** [comment]
Closing this, i create my own styles for this 👍
