### ISSUE TITLE
$.ajax or xhr + Modal + Conponent

### ISSUE THREAD

**Issue by Papayo85** [uikit/uikit#2879]
Hello everyone ;-)

Here is my problem, I call ajax a fragment of page that includes

https://www.jsfiddle.net/Papayo/6pcqemhe/4/

jQuery(document).on('click', '#testmodal',  function(e) {
jQuery.ajax({
url: "my url",
context: document,
success: function(responseText) {
jQuery("#content").html(responseText);
jQuery("#content").find("script").each(function() {
eval(jQuery(this).html());
});
UIkit.modal('#mymodal').show();
}
});	
});

The problem is that when I make the call in the modal, the conposant are inactive. It's been 7 days that I return the stuff in all directions and the bug serious. Could you put me on the track.

**Comment by janschoenherr** [comment]
Does this issue persist. There has been a lot of change going on in last few releases.
