### ISSUE TITLE
Animation hiding for 'off-canvas' element

### ISSUE THREAD

**Issue by Koziuk-S** [uikit/uikit#2880]
### UIkit version

3.0.0-beta.30

### Browser
Google Chrom version 60.0.3112.113 (x64)

### Reproduction Link

Codepen that can reproduce the bug.
https://codepen.io/Koziuk-S/pen/RLbzpg?editors=1000

### Steps to reproduce
If I clicking to button 'OPEN' and after that DON'T MOVING mouse pointer, I'll click on the 'X', close 'off-canvas' element.
### What is Expected?
animation hiding for 'off-canvas' element is normal.
### What is actually happening?
problem with animation hiding for 'off-canvas' element.

**Comment by Koziuk-S** [comment]
I found how to fix this issue. In button close I removed 'uk-close' attribute and added ' uk-icon="icon: close;" ', and it works so far.

`<button class="uk-offcanvas-close" type="button" **uk-close** ></button>`

`<button class="uk-offcanvas-close" type="button" **uk-icon="icon: close;"** ></button>`

**Comment by janschoenherr** [comment]
I believe this has been resolved in Beta 34.

**Comment by Koziuk-S** [comment]
Thanks for your decision. I update UIKit in my project from version 3.0.0-beta.40 and everything works.
