### ISSUE TITLE
Image alt is not adding when using lightbox

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2881]
I am trying to add alt to image when using lightbox but its not working
```html
<div class="lightBoxContainer" uk-lightbox>
         <a href="abc.png" caption="ABC" title="ABC"></a>
         <a href="abc.png" caption="ABC" title="ABC"></a>
</div>
```

but this title tag is not converting to alt tag for image.

**Comment by dasdeck** [comment]
we decided against title, but the alt attribute will now get passed to the image.
