### ISSUE TITLE
I have lost the menu item in joomla 3

### ISSUE THREAD

**Issue by SanuNak** [uikit/uikit#2883]
Good day! I have lost the menu item in joomla 3 (used uikit2). please take a look. Thank you.

[](http://jm2.sanu-nak.z9291.spectrum.myjino.ru/index.php/glavnaya-stranitsa)

**Comment by zzseba78** [comment]
Sorry, but this is not the channel to receive this kind of issues. Please close it.

**Comment by SanuNak** [comment]
ok. thank you
