### ISSUE TITLE
Feature request: uk-filter

### ISSUE THREAD

**Issue by mattfletcher** [uikit/uikit#2885]
The uk-filter option as used in:
https://getuikit.com/v2/docs/grid-js.html#filtering
is missing from version 3.

**Comment by janschoenherr** [comment]
We will start working on this in a little while.

**Comment by bdthemes** [comment]
Still waiting for it 😄

**Comment by bdthemes** [comment]
Hello YooTheme, Please finish the Unified Grid / Masonry and Grid Filter why it's stuck?

**Comment by Uranbold** [comment]
Is this coming for near? I want to remove the Isotope :) Please let me know if my help need.

**Comment by sonarun** [comment]
The only thing stopping me from upgrading my site to Uikit 3..

**Comment by bdthemes** [comment]
Hi @janschoenherr,

you told: 

> We will start working on this in a little while. 

But still under development please finish it. We are really long waiting for it.

Hi @dasdeck, I saw you are working for the filter: https://github.com/uikit/uikit/tree/feature/filter and when i pull and check it locally it's working fine but i don't understand 5 month gone but still under development can you please finish it soon?

**Comment by aarongerig** [comment]
@bdthemes Dude, relax... It‘s coming, but you can‘t force it.

**Comment by bdthemes** [comment]
Hi @aarongerig, I am apologies if i did any wrong. i don't force it i just remind it. We are always pleased such a great framework.

**Comment by aarongerig** [comment]
The filter component is here: https://getuikit.com/docs/filter
