### ISSUE TITLE
Duplicate Icons when using Vue.js (Again...)

### ISSUE THREAD

**Issue by PureDizzi** [uikit/uikit#2886]
### UIkit version
3.0.0-beta.30

### Browser
Chrome

### Reproduction Link
https://codepen.io/MarcusNardizzi/pen/yzNwKj?editors=1010

### What is Expected?
1 Icon

### What is actually happening?
2 Icons

**Comment by dsignr** [comment]
The only fix [I found](https://github.com/uikit/uikit/issues/2519) that worked was to change your HTML from:
```html
<span uk-icon="icon: contact"></span>
```
to
```html
<span :uk-icon="'icon: contact'"></span> <!-- notice the double quotes -->
```

**Comment by moreirapontocom** [comment]
@dsignr despite your solution worked, that's weird because just a few icons has been duplicated. But thank you! Works fine.
