### ISSUE TITLE
Search field icon is not showing up in React apps

### ISSUE THREAD

**Issue by flurdulis** [uikit/uikit#2889]
Since react works with props, the icon that contains an attribute <span uk-search-icon></span> is not being rendered. Is there a way to use rather CSS classnames like <span class="uk-search-icon"></span>, that way React does not clash with props idea here??

Thanks!

**Comment by flurdulis** [comment]
uk-search-icon is an example.... span contains uk-search-icon prop/attribute. I need is as . a classname.

**Comment by aarongerig** [comment]
Simply use the attributes like `data-uk-*` instead of `uk-*`. That way React will render them correctly.

**Comment by gregBerthelot** [comment]
@aarongerig it depends of what library you use. 'data-uk-*' does not work with hyperscript for ´data-uk-grid' or 'data-uk-icon'

**Comment by szchenghuang** [comment]
@aarongerig, data-uk-search-icon still doesn't work.

```
  <form className="uk-search uk-search-default">
    <span data-uk-search-icon />
    <input className="uk-search-input" type="search" placeholder="Search..." />
  </form>
```
 In React, that snippet will render a search box but the icon is blank.

![image](https://user-images.githubusercontent.com/6309412/41086974-1d63c74a-6a6e-11e8-8d68-29037cd74c45.png)

How am I supposed to get it working?

**Comment by szchenghuang** [comment]
This  alternative works however

```
<div className="uk-inline">
  <button className="uk-form-icon" href="" data-uk-icon="icon: search" />
  <input className="uk-input" />
</div>
```
