### ISSUE TITLE
Where can I download UIkit V2 Documenatation offline copy ?

### ISSUE THREAD

**Issue by hiren1610** [uikit/uikit#2890]
I have tried to google it, tried in stackoverflow and still unable to find out a way to download UIkit V2 documentation offline.

I went to [this page](https://getuikit.com/v2/docs/documentation_project-structure.html) and clicked on the button **Download source** but it downloads latest repo which is V3 Beta.

Can someone please help ?

**Comment by florianletsch** [comment]
Make sure you download the source code of one of the v2 branches (e.g. `v2/master`). For example, click "Download source code" on the latest v2 release: https://github.com/uikit/uikit/releases/tag/v2.27.4-src

That archive contains a `docs` directory with the html documentation for offline use

**Comment by hiren1610** [comment]
Thank you @florianletsch 

That worked.
