### ISSUE TITLE
uk-tooltip cannot hold long text

### ISSUE THREAD

**Issue by stanleyxu2005** [uikit/uikit#2893]
Dear Dev Team,

I'm currently using the 3.0 beta (git master branch). I don't know, whether it is my problem, it seems the tooltip component cannot show long text properly. (see the screenshot)
 
<img width="383" alt="2017-09-22 17 08 51" src="https://user-images.githubusercontent.com/5162687/30737311-bf4773bc-9fb8-11e7-8206-946dcf76c7f8.png">

It'd be great either crop too long text with "..." or wrap long text into multiple line, or allow user to specify the max width of a tooltip. What do you think?

The code is like this
```
<div class="uk-flex uk-flex-middle uk-text-uppercase"
       title="Data Source: http://localhost:5984/workflowhttp://localhost:5984/workflow" uk-tooltip>
    <clr-icon shape="disconnect"></clr-icon>
    Not Connected
  </div>
```

**Comment by zzseba78** [comment]
Hi! Check this example, if it works for you you can create a Pull Request to fix this in Chrome.

https://codepen.io/zzseba78/pen/XejEvR

**Comment by stanleyxu2005** [comment]
It looks good to me. Thank you for your PR. (Looking forward to be merged soon)
