### ISSUE TITLE
tests.js is referenced in test cases, but is missing in downloaded sets

### ISSUE THREAD

**Issue by hlwerschner** [uikit/uikit#2898]
I have directly downloaded uikit.js from the homepage and the archive does contain folders css, js etc. One such folder is tests which does contain all (?) examples I can also see on the homepage. But some of the example ***.html files reference a tests.js script which I can not locate in the downloaded files. I now checked the github and am quite sure that this script is not here also.

Where is it and where is the information about it?

**Comment by janschoenherr** [comment]
There shouldn't be a tests folder in the UIkit dist download. If you downloaded the source from GitHub you'll have to compile it first: https://getuikit.com/docs/installation#compile-from-github-source
