### ISSUE TITLE
Countdown date now tranfser

### ISSUE THREAD

**Issue by rolandverner** [uikit/uikit#2901]
### UIkit version
3.0.0-beta.30
there is a problem with a countdown as he pass the time, not only the end of the reference and the current but to not use the time to your browser

**Comment by janschoenherr** [comment]
Please add a reproduction link. You could start with this template: http://codepen.io/anon/pen/XMpryM

The given date is parsed using Date.parse(). https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

**Comment by RolandVerner** [comment]
The problem is that countdown takes time from the computer as a basis and not from the server, and it turns out that the countdown timer shows different time for different regions of the planet whose time is different
