### ISSUE TITLE
What is the best way to attach events handler to lighgtbox?  

### ISSUE THREAD

**Issue by SlavaAurim** [uikit/uikit#2903]
I use this code now:

$('BODY').on('beforeshow show shown itemshow hide hidden', '.uk-lightbox', function (e) {
//...handler code
})

Is there the best method?

**Comment by janschoenherr** [comment]
Currently that is not optimal, because the events are not triggered on the Lightbox, but the LightboxPanel. There isn't a best method yet.

**Comment by SlavaAurim** [comment]
LightboxPanel is dinamicaly created (so I use .on()) and it  has class .uk-lightbox
Is there another way to attach events handler? May be by UIkit api methods?

**Comment by janschoenherr** [comment]
Yes, you can use:

    UIkit.util.on(document, '.uk-lightbox', listenerFunction)

It basically does the same though.

**Comment by SlavaAurim** [comment]
Thanks!

**Comment by TomS-** [comment]
> Yes, you can use:
> 
> ```
> UIkit.util.on(document, '.uk-lightbox', 'beforeshow show shown itemshow hide hidden', listenerFunction)
> ```
> It basically does the same though.

This should be in the documentation - I had to search for a while to find this.

**Comment by aarongerig** [comment]
For the sake of completeness, this should work:

```js
UIkit.util.on(document, 'shown', '.uk-lightbox.uk-open', function () {
  console.log('Lightbox is displayed!');
});
```

**Comment by TomS-** [comment]
@aarongerig Thanks, it's not quite working as expected: 

```
UIkit.util.on(document, 'shown', '.uk-lightbox.uk-open', function(e) {
	var items = e.target.querySelector('.uk-lightbox-items');
	
	UIkit.util.on(items, 'click', 'li', function() {
		UIkit.lightboxPanel(e.target).show('next');
	});
});
```
Actually does nothing

**Comment by aarongerig** [comment]
@TomS- Please join Discord for usage questions and post a pen, that'll make it way easier to help. Thanks!
