### ISSUE TITLE
Screen Overlay not working(As a side nav)

### ISSUE THREAD

**Issue by neutralboy** [uikit/uikit#2904]
The image overlay nav is not working, using it chrome throws an error to the following [link](https://www.chromestatus.com/feature/5745543795965952). 
Google chrome considers it a bug, do please resolve it.

## Here's the description of the problem that I face
**When the links are used in the side nav, it initially goes to the link, but later when the overlay is closed it leads me back to the place i was before using the overlay**

**Comment by janschoenherr** [comment]
Please add a reproduction link.

You could start with this template: http://codepen.io/anon/pen/XMpryM
