### ISSUE TITLE
Two search icons in search field when using VueJS

### ISSUE THREAD

**Issue by pentool** [uikit/uikit#2907]
It seems that when you use a search input field with a search icon, there are two search icons showing up next to each other. This happens when you are using it with Vue. See link to JSFiddle.

### UIkit version

3.0.0-beta.30

### Browser
Safari 11.0
Firefox 55.0.3

### Reproduction Link
https://jsfiddle.net/pentool/jw13bhyu/1/

### Steps to reproduce
1. Use Safari 11.0 to view the JSFiddle sample.
2. Notice there are two search icons inside the search field.
3. Now select the javascript settings dropdown in the fiddle and try to change the 'load type' of the script to different options (onLoad, noWrap head/body, etc).
4. Notice that in some cases (depending on where the script is loaded) the double icon changes to a single icon. The problem is that in that case Vue will not load. If you look at the console, you get an error that "...element 'app' cannot be found".

### Using the attached code sample
I think it's easier to see in the attached code sample. It's really tiny and contains 2 files: index.html and main.js.

1. Open up the index.html file locally in Safari and Firefox
2. Notice that there is a single search icon in the search field. However, if you open up the browser console, there's a complaint from Vue that it cannot find the element '#app' since the script is loaded too early.
3. In the index.html file, move the line `<script src="main.js"></script>` before the closing body tag and refresh.
4. Notice that Vue can now load correctly in both Safari 11.0 and Firefox 55.0.3 (there's no complaint in the console), but Safari now displays double search icons, while Firefox displays a single one.

### What is Expected?
There should be a single search icon regardless whether I use Vue or not.

### What is actually happening?
Two search icons show up in the search field depending on whether the Vue script is loaded in the header or in the footer.

Attachment: [search-icons.zip](https://github.com/uikit/uikit/files/1352777/search-icons.zip)

**Comment by RALMAZ** [comment]
+

**Comment by pentool** [comment]
This doesn't seem like an issue in Firefox 56.0 any more, but Safari 11.0 is still a culprit.

**Comment by giordanovi** [comment]
++

**Comment by roman-kosov** [comment]
+

**Comment by roman-kosov** [comment]
I replaced the **true** in line 5363
`if (last && el.isEqualNode(last)) {`
with a **false**
`if (last && !el.isEqualNode(last)) {`

it works 😮

**Comment by janschoenherr** [comment]
The jsfiddle does not seem to work anymore. I will close the issue for now. Please let us know if the issue persists.
