### ISSUE TITLE
Sortable & Lightbox combination issue

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#2917]
### UIkit version

3.0.0-beta.30

### Browser

Apple Safari (11.0, macOS 10.12.6)
Google Chrome (61.0, macOS 10.12.6)
Mozilla Firefox (56.0, macOS 10.12.6)

### Reproduction Link

https://codepen.io/anon/pen/dVZgWX

### Steps to reproduce

Variant A:
Open reproduction link.
Open Lightbox by clicking on the Dummy-Link inside the card.
Close the Lightbox, reorder items, click any of the Dummy-Links again.

Variant B:
Open reproduction link.
Reorder items, then click on the Dummy-Link inside the card. (Everything's fine)
Close the Lightbox, reorder items, click any of the Dummy-Links again.

### What is Expected?

Lightbox opens even after it was opened once and the item order of sortable has been changed.

### What is actually happening?

The Lightbox doesn't open again if you opened it once, reorderd the items and click any of the Dummy-Links.

The content inside the anchor tag doesn't matter. It also happened when you have an image (thubmnail etc.) inside.

I haven't tested on Windows yet because it seems to be an UIKit specific, not OS specific issue.

**Comment by janschoenherr** [comment]
Fixed in 5fc8f223d8fc9e9ba863cdb5b1f6a349ca8ac824
