### ISSUE TITLE
uk-cover-container not working properly with uk-sticky uk-navbar-container (develop branch)

### ISSUE THREAD

**Issue by cserfoss** [uikit/uikit#2921]
### UIkit version

develop branch

### Browser
Chrome 61.0.3163.100 / Safari 11604.1.38.1.7

### Reproduction Link

https://codepen.io/cserfoss/pen/xXYRjv

Please note that I am self-hosting the js file as I'm not aware of a CDN for the develop branch files.

### What is Expected?
Behavior should match jQuery version in which the cover image is pushed down the height of the toolbar. It appears that the 'hidden' attribute is being set on the uk-sticky-placeholder erroneously.

### What is actually happening?
The cover image is appearing under the navbar and is getting clipped.

**Comment by janschoenherr** [comment]
This has been resolved with 0d1bc7ea1d3d6dc71f8d49ea93f95a6f2a3aff9d
