### ISSUE TITLE
YouTube Modal Box - https Error

### ISSUE THREAD

**Issue by dazzafact** [uikit/uikit#2922]
### UIkit version

3.0.0-beta.30

### Browser
Chrome latest

 61.0.3163.100 (Offizieller Build) (64-Bit)

Windows 10
### Reproduction Link
https://getuikit.com/docs/modal#modal-media-youtube

### Steps to reproduce
Click on youtube Video on your site:
https://getuikit.com/docs/modal#modal-media-youtube
### What is Expected?
Video to watch. Nothing to watch

### What is actually happening?
Nothing to watch
error with Chrome Browser

_Mixed Content: The page at 'https://getuikit.com/docs/modal#modal-media-youtube' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/YE7VzlLtp-4?enablejsapi=1'. This request has been blocked; the content must be served over HTTPS._

**Comment by janschoenherr** [comment]
Thanks, fixed with uikit/uikit-site@8b14907856310d69b647eb97fc8487ecdb804aa0
