### ISSUE TITLE
UIkit 3 - Firefox: icons are not working on hidden elements like modals

### ISSUE THREAD

**Issue by javierfdezgomez** [uikit/uikit#2926]
UIkit 3.0.0-beta30

### UIkit version

3.0.0-beta.30

### Browser
FIrefox 56

**Comment by zzseba78** [comment]
Do you have a reproduction link? Because i see the icons, and i use Firefox v56.
https://codepen.io/zzseba78/pen/WZJqOd

**Comment by javierfdezgomez** [comment]
Your are right. Not sure what i am doing wrong, because it only happens when I update the modal content using Ajax.

I`ve tried to reproduce it but I can´t... So maybe it is just my problem

**Comment by javierfdezgomez** [comment]
In the end, it seems that the problem is related to the container change: when the final container changes, no icon is displayed. However, I have not yet been able to repeat it in CodePen.

**Comment by javierfdezgomez** [comment]
Finally, I found the solution, I hope someone else will help.

I was importing the polyfills from "core-js" after having obtained UIkit from the CDN. The solution was import core-js polyfills into an extra file, and read it just before UIKit.

BEFORE:
```html
<head>
<!-- We do not want any visual jump, that's why we read UIkit in the header -->
<script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit-icons.min.js"></script>
</head>

<body>
<script src="app-script-with-polyfills"></script>
</body>
```
AFTER:
```html
<head>
<script src="only-polyfills"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit-icons.min.js"></script>
</head>

<body>
<script src="app-script-without-polyfills"></script>
</body>
```

**Comment by janschoenherr** [comment]
Does this issue persist with the latest release? If yes, you might want to open another issue, as the topic does not seem to be the issue anymore. Thanks.
