### ISSUE TITLE
 Modal/Lightbox closes unexpectedly

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#2928]
### UIkit version
Latest one

### Browser
Firefox

### Reproduction Link
https://codepen.io/anon/pen/MEXoKV

### What is Expected?
Modal should only close when clicking on the close button, and other default places, not when I hover over the image with my mouse.

### What is actually happening?
Because lightbox doesn't allow scrollable images (overflow), I started to use the modal instead. But I noticed some odd behaviour occurring in both the lightbox and modal.
When I go over my mouse anywhere on the image, the modal/lightbox automatically closes without me clicking on anything.

[overflow-video.zip](https://github.com/uikit/uikit/files/1375111/overflow-video.zip)

**Comment by vitalyLitvinov** [comment]
I had the same problem as you, by testing I realized that if you remove the uk-modal-dialog class, when you click on the scroll bar, the modal window stops disappearing. this is all that I managed to achieve, I'm Russian and I use google translator

**Comment by janschoenherr** [comment]
This seems to be working fine for me, does this issue persist?
