### ISSUE TITLE
Upload data-type not working

### ISSUE THREAD

**Issue by Bigchefstarys** [uikit/uikit#2930]
### UIkit version

3.0.0-beta.30

### Browser
Chrome
### Reproduction Link
https://jsfiddle.net/Bigchefstarys/715u4hbt/

### Steps to reproduce
data-type not working
`data-type: 'html',`
### What is Expected?
to be included in the data alert function
`completeAll: function (data) {
  alert(data); -> data name example uikit-logo.png
 }`
### What is actually happening?
upload function is not working

**Comment by janschoenherr** [comment]
data-type: 'html'

That is not a valid object key, try:

    'data-type': 'html'
