### ISSUE TITLE
Hamburger Navigation and Transparent Sticky Navigation Bug

### ISSUE THREAD

**Issue by TJMusiitwa** [uikit/uikit#2932]
### UIkit version

3.0.0-beta.30

### Browser
Firefox, Vivaldi(Chrome),Edge

### Reproduction Link
Below is the website to check out the issues:
http://eventarch.azurewebsites.net/

### What is Expected?
The hamburger navigation in mobile mode is supposed to allow switching to a different section and remain there.

### What is actually happening?
When one selects a section from the hamburger menu it returns back to the section pre-current to the user's selection. The sticky transparent navbar has a bug where it will not return to transparent properly when scrolled all the way to the beginning of the page.

**Comment by janschoenherr** [comment]
Please check if the issue persists with the latest UIkit release Beta 34.

**Comment by TJMusiitwa** [comment]
The fix worked perfectly. Thank you
👍
