### ISSUE TITLE
Body scrolls when offcanvas is open

### ISSUE THREAD

**Issue by johnchar** [uikit/uikit#2933]
### Bug Preview
![uikit offcanvas body-scroll issue](https://media.giphy.com/media/l378ies3FcAFYNb32/giphy.gif)

### UIkit version

3.0.0-beta.30

### Browser
Google Chrome for Android
### Reproduction Link
You can check the example on documentation site ( see .gif image ) or here https://johnchar.github.io

### Steps to reproduce
Open offcanvas on a mobile phone and scroll/gesture up and down.
### What is Expected?
The body, "behind" the offcanvas is not supposed to move when offcanvas is open
### What is actually happening?
The body moves when offcanvas is open
### Possible fix
Apply `overflow-y: hidden;` when offcanvas is active/open
### Statement
I would like to get assigned this issue and send in a PR for a fix if that's okay

**Comment by zzseba78** [comment]
Did you include the `<div class="uk-offcanvas-content">` wrapping the content like it´s described in the docs? 
https://getuikit.com/docs/offcanvas

**Comment by johnchar** [comment]
It seems I did not include 
```html
<div class="uk-offcanvas-content">
```
but I added it, emptied cache and hard reloaded and it still doesn't work as intended..

Also, since it's included in the docs, why doesn't the demo in the docs work as intended ( assuming it's included, didn't check )

**Comment by janschoenherr** [comment]
You'll have to use the `overlay` option set to `true`.

**Comment by lidiexy** [comment]
@janschoenherr, @johnchar Hi, I'm having the same issue, same version, I included the wrapper DIV `<div class="uk-offcanvas-content">` and I added `overlay: true` as this `<div id="offcanvas-overlay" uk-offcanvas="overlay: true">`. Any Ideas? Thanks.
