### ISSUE TITLE
Offcanvas event "shown" doesn´t fire correctly.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2935]
### UIkit version

3.0.0-beta.32

### Browsers
Firefox, Safari, Chrome.

### Reproduction Link

https://codepen.io/zzseba78/pen/EwGPMG?editors=1010
### Steps to reproduce
Open the Offcanvas
### What is Expected?
According to the docs: shown -> Fires after the item's show animation has completed 

### What is actually happening?
**First time** the "shown" events triggers immediately and doesn´t wait until animation it´s complete. This happens the first time the offcanvas it´s opened.

**Comment by imarkdesigns** [comment]
Btw, the initiation of closing the offcanvas is different from beta.30... It instantly close the offcanvas instead of sliding-to-hide.

**Comment by janschoenherr** [comment]
Fixed with f1e8725c714942b8f434a72341f95d7bbe7b6409
