### ISSUE TITLE
uk-scrollspy-nav and cls-inactive

### ISSUE THREAD

**Issue by Rover-33** [uikit/uikit#2936]
### UIkit version
3.0.0-beta.30

### Browser
chrome, safari

### Reproduction Link
https://codepen.io/Rover-33/pen/ZXVVVr

### Steps to reproduce
add 'uk-scrollspy-nav="closest: li; scroll: true; offset: 100" ' to 'ul' element, line 6.

### What is Expected?
menu must be transparent

### What is actually happening?
I think uk-sticky="cls-inactive" don't work properly with uk-scrollspy-nav.

**Comment by janschoenherr** [comment]
This seems to be fixed with the latest version Beta 34.

**Comment by yovkov** [comment]
I believe this is again an issue - at least in the latest 3.0.0-beta.40
