### ISSUE TITLE
Full modal window and dorpzone closing issue

### ISSUE THREAD

**Issue by danyvan** [uikit/uikit#2937]
### UIkit version

3.0.0-beta.30

Hi I have a problem with the full page modal window and dropzone. Everytime I click on the dropzone are the modal windows is closing. When I use the general upload option from uikit it workds but I would like to use dropzone for it.
The issue seems in the clickable option of dropzone. 
 Thank you for help
Dany

here is a example
https://jsfiddle.net/vb10x3nq/3/

**Comment by javierfdezgomez** [comment]
It will works ir you set the background close option to false.

```html
<div id="modal-container" class="uk-modal-container" uk-modal="bg-close: false">
<!-- ... -->
</div>
```

**Comment by danyvan** [comment]
great thank you for help working perfect!
