### ISSUE TITLE
Button border radius in Chrome 62.0

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#2939]
### UIkit version

3.0.0-beta.30

### Browser

Google Chrome (62.0, macOS 10.12.6)

### Reproduction Link

https://getuikit.com/docs/button#style-modifiers

### What is Expected?

Button component doesn't have a border radius.

### What is actually happening?

Button component has a border radius.

Since Chrome 62.0 the user agent style sheet has a default border radius on buttons (button, submit, reset ...).
See Screenshot.

![uikit-button](https://user-images.githubusercontent.com/30808076/31813173-baca33a0-b585-11e7-8cda-6223122c5619.jpg)

Please extend button component (.uk-button) by adding border-radius: 0;

**Comment by gregBerthelot** [comment]
Confirmed

**Comment by Riddler84** [comment]
Is there a difference between the user agent stylesheet of Chrome in Windows and Mac? Because i'm using Win10 and here i have no border radius. But a few more other default styles as in your screenshot.

**Comment by Lumelomser** [comment]
Yes, I can confirm this affects only Chrome on macOS, Chrome (62.0) on Windows doesn't have the border-radius in the user agent stylesheet.

**Comment by maximelafarie** [comment]
That's normal. 

> Following an update to native button appearance on macOS, the appearance of <input> buttons and the <button> element have been similarly changed, affecting the default values for the background-color,  border,  border-radius, and padding CSS properties.

More details here : https://tweakers.net/downloads/42517/google-chrome-620320262.html

**Comment by saschadube** [comment]
Thanks for reporting
