### ISSUE TITLE
Change grid elements order on breakpoint

### ISSUE THREAD

**Issue by buric** [uikit/uikit#294]
Hello,
I have an element (1) that comes before another element (2) in html. I want to make that this element (1) comes after that element (2), but only on mobile breakpoint.
Thanks

Desktop and tablet:
![dsfa](https://f.cloud.github.com/assets/1558492/2205647/61380904-9953-11e3-9280-a14b9816b14a.png)

Mobile:
![asdf](https://f.cloud.github.com/assets/1558492/2205646/6134c6d6-9953-11e3-8f5f-c3de1129e97b.png)

``` html
<div class="uk-grid">
    <div class="uk-width-1-1 uk-width-large-1-2" style="border: 1px solid #000000;">
        <p>On mobile this should go to bottom.</p>
        <p>On tablet and desktop this should go right.</p>
    </div>
    <div class="uk-width-1-1 uk-width-large-1-2" style="border: 1px solid #000000;">
        <p>On mobile this should go to top.</p>
        <p>On tablet and desktop this should go left.</p>
    </div>
</div>
```

**Comment by dhrusya** [comment]
could you publish the code here, so that we can understand.

Thank you

**Comment by Erutan409** [comment]
Swap the elements in desktop mode.  Add a push class to the first element (left -> right).  Add a pull class to the second element (right -> right).  Remove the classes at a certain breakpoint and the elements will stack as desired.

For anyone else who is interested and comes across this on a Google search.
