### ISSUE TITLE
How to implement data-uk-tab in tabs?

### ISSUE THREAD

**Issue by viktormoiseev** [uikit/uikit#2941]
How to implement data-uk-tab in tabs?
why tabs do not work in the dropdown menu?

**Comment by Ezra-Siton-UIX** [comment]
Hi. Maybe add codepen. This is the code (with/without data will work the same - this is only W3C validator issue)

```
<ul data-uk-tab>
    <li class="uk-active"><a href=""></a></li>
    <li><a href=""></a></li>
    <li class="uk-disabled"><a href=""></a></li>
</ul>
``` 

> why tabs do not work in the dropdown menu?
add code example
