### ISSUE TITLE
Slideshow (autoplay) don't stop if you leave the browser tab and will complete all animations at once after you came back

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#2943]
### UIkit version
3.0.0-beta.31

### Browser
Google Chrome Version 62.0.3202.62

### Reproduction Link
https://codepen.io/Riddler84/pen/RLOLbv?editors=1000#0

### Steps to reproduce
- Open the Pen and watch the slideshow starts
- Leave the browser tab for at least 10 seconds
- Check back the Pen

### What is actually happening?
The Slideshow moves very fast trough all autoplayed animations that are happened in my absence. If you change the tab and then leave your PC for half an hour, you can only reload the page or wait a long time, till every animation is complete.

**Comment by viocassel** [comment]
Confirm ☝️
