### ISSUE TITLE
Strange SVG image behavior

### ISSUE THREAD

**Issue by mightyvoodoo** [uikit/uikit#2949]
### UIkit version

3.0.0-beta.31

### Browser
Any

### Reproduction Link
https://codepen.io/anon/pen/yzWWJO

### What is Expected?
Normal SVG rendering with "headers" like:
```
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
```
 when using "uk-svg" and when compiling custom svg icons into js

### What is actually happening?
- t.getAttribute is not a function uikit.min.js:3:4922
- element.getAttribute is not a function uikit.js:692:27
- no `<svg></svg>` tag render

### Render and docs
> However you do need to remove XML heading if you are copying the SVG into an HTML file (as inlined SVG). You should also remove any DOCTYPE declaration.

Now I doubt that is the bug because accordingly to docs when we render svg into `<svg></svg>` we must keep clear SVG. May be the proper way is in clearing "heading" manually, or may be to do it before render by uikit

**Comment by wolfcreative** [comment]
I confirm, there is such a mistake in my project

**Comment by aymericpasco** [comment]
I also confirm, same problem.

However, it works on the previous beta version.

**Comment by ladislavsulc** [comment]
Same here with the update to 31.

**Comment by mightyvoodoo** [comment]
@janschoenherr 
Inline SVG now works, but

> when compiling custom svg icons into js

we have "element.getAttribute is not a function uikit.js:702:27"
