### ISSUE TITLE
Lightbox not always work

### ISSUE THREAD

**Issue by maksim-mul** [uikit/uikit#2951]
Hello. Lightbox not work when use so link
/upload/iblock/test.jpg?15085909881317990
Shows always spinner
![screenshot_223](https://user-images.githubusercontent.com/26099127/31939042-e46092ec-b8c1-11e7-9a68-27a573bc04d0.png)

With so link all good
/upload/iblock/test.jpg

**Comment by mightyvoodoo** [comment]
Your first link is incorrect. Probably, you must add the GET-parameter after question mark like "...test.jpg?param=150...".

**Comment by maksim-mul** [comment]
@mightyvoodoo 
It is using in Bitrix CMS when using CDN. I can not turn it off.

**Comment by mightyvoodoo** [comment]
I recommend you to try implement PHP/JS fix for this issue or configure CDN proper. Like link parser or else, which will change all your links into correct view for Lightbox component...

**Comment by zzseba78** [comment]
Use `data-type="image"` in the link.
https://codepen.io/zzseba78/pen/XeLXwK

If it works for your please close this issue. Good Luck

**Comment by maksim-mul** [comment]
Thanks very much.

**Comment by maksim-mul** [comment]
Thanks very much.
