### ISSUE TITLE
Upload component does not send cookies

### ISSUE THREAD

**Issue by x4vl** [uikit/uikit#2952]
### UIkit version

3.0.0-beta.31

### Browser
Any

### Steps to reproduce
Upload any file with upload component. 

### What is Expected?
The cookies should be sent or must exist an option to force it.

### What is actually happening?
No cookies are sent.

**Comment by janschoenherr** [comment]
You'll have to initialize the component [manually](https://getuikit.com/docs/upload#javascript) and modify the xhr in the beforeSend callback

```
{
    beforeSend: function (env) {
        env.xhr.withCredentials = true;
    }
}
```

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
