### ISSUE TITLE
[fixed] slideshow autoplay flush problem

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#2953]
### UIkit version

3.0.0-beta.31

### Browser
chrome

### Reproduction Link

https://codepen.io/anon/pen/JrQOrz

### Steps to reproduce
when setup the autoplay and then switch to other window/tab (block the slideshow view sight), wait a little bit then switch back, the slideshow plays like a flush.

### What is Expected?
normal play of the slideshow

### What is actually happening?
flip very fast

**Comment by Riddler84** [comment]
Already fixed.
#2943 
https://github.com/uikit/uikit/commit/583037ca1d835b2555152c88c864509f30ba1425

**Comment by tyler-x** [comment]
Thanks, missed the closed topic, just a question, where can i get the fixed version? I pulled the master copy and it's still not working well.

**Comment by Riddler84** [comment]
It's fixed in the develop branch and will merged into master when they released the next beta version. I'm sure it will be soon.
https://github.com/uikit/uikit/blob/develop/CHANGELOG.md
https://github.com/uikit/uikit/commit/583037ca1d835b2555152c88c864509f30ba1425
