### ISSUE TITLE
UPLOAD - xhr.setRequestHeader is not a function

### ISSUE THREAD

**Issue by timrasche** [uikit/uikit#2957]
### UIkit version
3.0.0-beta.31

### Browser
Any

**Comment by janschoenherr** [comment]
Is this a function you are calling from custom code? It does not seem to be part of UIkit in Beta 31

**Comment by timrasche** [comment]
Nope, xhr is the returned object by 'beforeSend' function (to customize header fields in xhr requests e.g. Authorization token or some stuff)

**Comment by janschoenherr** [comment]
The `beforeSend` callback gets an `env` object. Attached to that is the xhr. 

`env.hxr`

**Comment by timrasche** [comment]
Exactly, on update from beta29 this object is different.
There's some 'headers' object on 'env', manipulation has also no effect on sended headers.
Finally, there is no function in beta31 anymore to set xhr headers. :-/

**Comment by janschoenherr** [comment]
Thanks, resolved with c636f10d44af0efda0bc79b4d40e197c0a291e12
