### ISSUE TITLE
Custom Icons js-file is not loaded within tests

### ISSUE THREAD

**Issue by nstaeger** [uikit/uikit#2958]
### UIkit version
3.0.0-beta.31 and earlier

### Steps to reproduce
- Using Windows 10
- `npm run icons`

### What is Expected?
- Icons can be used within tests, e.g. by modifying the icon.html test file

### What is actually happening?
- Icons .js file is not being loaded by the tests, as the path is not correctly set within the themes.json. Misses leading `../`. Example:

```
{
    "mytheme": {
        "css": "../dist/css/uikit.mytheme.css",
        "icons": "dist/js/uikit-icons-mytheme.js"
    },
    // ...
}
```

**Comment by haydnjames** [comment]
Sorry to jump on this, but I'm seeing similar (and more issues with the test files in 31. Should there also be a test.js file included? Most of the test html files reference it, but it doesn't exist in the tests/js folder.

**Comment by viocassel** [comment]
Confirm 👆

**Comment by nstaeger** [comment]
@haydnjames see https://github.com/uikit/uikit/issues/2898

**Comment by dasdeck** [comment]
I think this has been fixed in 2a3e9a0c188bb3fb98c835e4ea467ad0eea25759
can you confirm and close please?

Cheers!

**Comment by dasdeck** [comment]
@haydnjames did you run `npm test`?

**Comment by dasdeck** [comment]
Closed for lack of interaction. Please open new one if issue persists.
