### ISSUE TITLE
version 3.0.0 beta.31 breaks SEVERAL components!

### ISSUE THREAD

**Issue by pcout** [uikit/uikit#2960]
[UPDATE]
I can confirm several bugs in many of the components !
Going back to 3.0.0 beta 30 (August 18, 2017).

What's happening ?

<hr>
The new release breaks some components, like NAV or FORM SELECT, for instance.
Anyone notice any other issues ?

After further testing I would say it has something to do with the classes uk-overflow-auto and uk-height-max-medium for some reason.

I read other users are reporting some bugs and errors with this new release.
Any news on these issues ?

**Comment by janschoenherr** [comment]
Please use the issue template and provide a codepen or check the tests e.g. here: https://getuikit.com/assets/uikit/tests/form.html
