### ISSUE TITLE
`data-uk-dropdown="true"` incorrectly positions dropdown

### ISSUE THREAD

**Issue by su-narthur** [uikit/uikit#2961]
### UIkit version

3.0.0-beta.31

### Browser

Chrome Version 62.0.3202.62 (Official Build) (64-bit)

### Reproduction Link

[Codepen](https://codepen.io/narthur/pen/WXevvY?editors=1000)

### Steps to reproduce

1. Initialize a dropdown using `data-uk-dropdown="true"` (as results from using `data-uk-dropdown` in a React component).
2. Observe that dropdown placement breaks.

![result](http://g.recordit.co/elxi8dVEiv.gif)

### What is Expected?

`data-uk-dropdown="true"` should result in the same dropdown placement as any other value (no value, or `"{}"`, for example).

### What is actually happening?

Dropdown is positioned incorrectly.

**Comment by su-narthur** [comment]
Setting the property to an empty string in React is a workaround.

**Comment by janschoenherr** [comment]
You are trying to position the dropdown at _true-center_ which is invalid and defaults to _center-center_.

_Pos_ is the primary option for the _Dropdown_ component: https://getuikit.com/docs/javascript#component-configuration
