### ISSUE TITLE
`data-uk-toggle="true"` breaks modal, deletes link on-click

### ISSUE THREAD

**Issue by su-narthur** [uikit/uikit#2962]
### UIkit version

3.0.0-beta.31

### Browser

Chrome Version 62.0.3202.62 (Official Build) (64-bit)

### Reproduction Link

[Codepen](https://codepen.io/narthur/pen/yPBNEy?editors=1000)

### Steps to reproduce

1. Use a link to open a modal, using `data-uk-toggle="true"` (as results when using `data-uk-toggle` in a React component).
2. Observe that the modal isn't triggered, and the link is deleted on-click.

![result](http://g.recordit.co/hsX27pTtaV.gif)

### What is Expected?

Link should trigger modal as it does when no value is provided.

### What is actually happening?

Modal is not triggered, link is deleted on-click.

**Comment by su-narthur** [comment]
Setting the property to an empty string in React is a workaround.

**Comment by janschoenherr** [comment]
Internally UIkit would be looking for a tag with the name _true_.

As an alternative you could use the value you've put into the _href_ attribute.
