### ISSUE TITLE
Slideshow inside a modal

### ISSUE THREAD

**Issue by kiarashi** [uikit/uikit#2965]
Does anyone know how to make a slideshow work inside a hidden element such as a modal (once the modal becomes active)?

I created a fiddle here:
http://jsfiddle.net/kiarashi/hse6bf1d/1/

**Comment by carlos-duran** [comment]
Add a fixed width to the slideshow element (e.g. uk-width-medium)
http://jsfiddle.net/hse6bf1d/2/

**Comment by zzseba78** [comment]
@kiarashi And why don´t you use the Lightbox component? I think that gives better results for what you want.

**Comment by kiarashi** [comment]
I've some issues with the lighbox. For instance, it doesn't allow scrolling of (larger) images. Plus, I notice that when I hover over the image, it sometimes closes the lightbox without me clicking on the mouse.

**Comment by zzseba78** [comment]
Strange, working fine for me. By scrolling you mean to be able to zoom in the image?

**Comment by kiarashi** [comment]
I reported the issue previously:
https://github.com/uikit/uikit/issues/2928

**Comment by janschoenherr** [comment]
You'll have to give the slideshow div a width or remove the uk-width-auto class.

Currently the slideshow will close the modal after dragging, this is resolved with 6ad630aaec17b83496d80703a6a942531fa47a24

**Comment by mbriney** [comment]
We're having this issue too.  We were able to get the slideshow to open in the modal window by adding some supporting classes but the controls don't seem to be responding:

Example:
http://gwmv.fyi/explorer/plants.php
- Click on the first plant
- Controls don't function in the slideshow

**Comment by viocassel** [comment]
@mbriney update to **UIkit 3.0.0 beta 34**. You have now used the **UIkit 3 beta 30**.
