### ISSUE TITLE
Feature Request: Mobile stacking order customization.

### ISSUE THREAD

**Issue by sciku1** [uikit/uikit#2967]
I scoured the documentation, but to no avail. I would like to be able to customize the stacking order of a grid, ie: 

```
<div class="uk-grid" data-uk-grid>
    <div class="uk-width-1-3">1</div>
    <div class="uk-width-1-3 {insert-classname-push-to-top}">2</div>
    <div class="uk-width-1-3">3</div>
</div>
```

Should look like 3 equal width column, 1, 2, and 3, on mobile, it should be 2, 1, 3 from top to bottom. 

Is this in scope?

**Comment by aarongerig** [comment]
UIkit‘s grid is based on flex, which means you can use it in combination with the flex component: https://getuikit.com/docs/flex#item-order

If this resolves your case, please close this issue. Thanks!
