### ISSUE TITLE
Modal component closing when click dropdown inside modal 

### ISSUE THREAD

**Issue by Alymbek** [uikit/uikit#2968]
### UIkit version

3.0.0-beta.32

### Browser
Chrome, FF

### Steps to reproduce
dropdown (by click) component  inside modal component  
### What is Expected?
dropdown open its content
### What is actually happening?
when click on dropdown its close modal component

**Comment by viocassel** [comment]
It was [fixed](https://github.com/uikit/uikit/commit/9b4c9932e9ed39d9f15bcce7e62456f20b5d3f1c).

**Comment by Alymbek** [comment]
fixed in develop branch 3.0.32

did you fix in drop and subnav components?

there was same problem in that comp's

**Comment by Alymbek** [comment]
all was fixed!
thanks a lot!

**Comment by Sharipkanov** [comment]
Where i must preventDefault the event? UIkit.modalt(this.modalRoot, {bgClose: false});
