### ISSUE TITLE
data-uk-slideshow-item does not work

### ISSUE THREAD

**Issue by pedall** [uikit/uikit#2972]
### UIkit version

3.0.0-beta.32

### Browser
Chrome 61.0.3163.100 
### Reproduction Link

https://www.hastebin.com/bicopaqunu.xml

![image](https://user-images.githubusercontent.com/20089354/32140007-338c5160-bc52-11e7-81be-e2c80dbc8fe1.png)

### Steps to reproduce

Clicking on the nav items (e.g. data-uk-slidenav-next) and no reaction. Same with the dotnav example from the website.

### What is Expected?

clicking the respective nav items (arrows or dotnavs) leads to a switch to the next or previous content

### What is actually happening?

 No reaction when clicking the nav items and dotnavs. Sliding via holding and swiping the images with the mouse works.

**Comment by bdthemes** [comment]
Hi @pedall,

Please remove the **data-** so i hope your all things will work correctly. bacause jQuery dependency was removed from **3.0.0 beta 31**.

check your example code here: https://codepen.io/bdthemes/pen/pdoMge

**Comment by aarongerig** [comment]
@bdthemes Why remove all `data-` stuff? Has nothing to do with jQuery. It‘s a valid HTML 5 attribute for HTML elements and is required by for example React.

**Comment by pedall** [comment]
And im making a React website. So i cant drop the data- stuff ;-)

**Comment by ruchern** [comment]
@bdthemes `data-` does not have anything to do with it. In fact, it is working in my project on beta 32.

**Comment by bdthemes** [comment]
@pedall @aarongerig  I don't mean it's not valid or remove all from your project just remove from slideshow things. i tested with your code please check here: https://codepen.io/bdthemes/pen/pdoMge

with data- it's not working but without data it's working fine.

**Comment by pedall** [comment]
@bdthemes your example is not a React example.

With React you **have** to use `data-`. 

@ruchern is your project a React project? maybe you can help me get my project running

**Comment by ruchern** [comment]
@pedall No. My project is Vuejs.

**Comment by pedall** [comment]
@ruchern then how can you say that `data-` does not have anything to do with it if you are not using React at all?

**Comment by ruchern** [comment]
@pedall Because @bdthemes was just making a general statement.
