### ISSUE TITLE
Viewport height error in beta 31

### ISSUE THREAD

**Issue by mattgaspar** [uikit/uikit#2974]
Viewport Height is not working in beta 31+ in scenerios were it worked previously.

### UIkit version

3.0.0-beta.32

### Browser
Chrome

### Reproduction Link

Beta 31 - https://codepen.io/anon/pen/yPLRjr
Beta 30 - https://codepen.io/anon/pen/pdoxOB

### Steps to reproduce
uk-height-viewport="offset-bottom: true;" causes exception when no next sibling element

### What is Expected?
Previously the page would render as if offset-bottom was false

### What is actually happening?
Height doesn't expand and exception is thrown

Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at HeightViewport.write (uikit.js:4809)
    at uikit.js:2777
    at runTasks (uikit.js:1583)
    at Object.flush (uikit.js:1561)

Error occurs at line 49 of height-viewport.js, nextElementSibling is null

`offsetTop += this.$el.nextElementSibling.offsetHeight || 0;`

**Comment by fabien** [comment]
@janschoenherr There's a similar issue I'm encountering in Off-canvas (current version from GH):

```
uikit.js:5784 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at Offcanvas.write (uikit.js:5784)
```
For some reason, `content` is not available, and this is not accounted for gracefully. Fix would be similar: check for a valid `content` element first.
