### ISSUE TITLE
Nav inside Offcanvas trigger offcanvas events several times.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2975]
### UIkit version

3.0.0-beta.32

### Browser
Chrome, Safari, FF

### Reproduction Link

 https://codepen.io/zzseba78/pen/eemyve
### Steps to reproduce
Open the offcanvas
### What is Expected?
Offcanvas events triggers only depending on the offcanvas.
### What is actually happening?
Nav trigger offcanvas events several times, when the accordion shows more items, and when open and close the offcanvas. **If you remove `uk-nav` this doesn´t happen.

**Comment by Ezra-Siton-UIX** [comment]
Hi. I also test this - i find the event not synchronize with what really **happen** on the screen.
https://codepen.io/ezra_siton/pen/dRVpPX/

Also i think `beforehide`  & `hidden`" & `hide` should run only if the user **close** open-"offCanvas". For now its run every time i refresh the page! :(

**Comment by janschoenherr** [comment]
You need to check for the event target. In UIkit 3 togglable components fire `beforeshow`, `show`, `shown`, `beforehide`, `hide` and `hidden` events.

The tab component initially fires the show events, true. That is also intended, you might want to react on the initial state too.

**Comment by zzseba78** [comment]
Thank for your response. Closed.
