### ISSUE TITLE
Add javascript options for Modal component

### ISSUE THREAD

**Issue by AlekVolsk** [uikit/uikit#2979]
### UIkit version
3.0.0-beta.33

### What is Expected?
Add two javascript options `UIkit.modal.[dialog|alert|confirm|prompt]`:
`center: false | true` default: false; to center the window vertically
`autoclosed: false | Nsec` default: false; to automatically close the window after the specified number of seconds after opening

Ideally, also add the ability to specify a unique `id` for binding to a specific alert-dialog narrow functionality and design

**Comment by aarongerig** [comment]
What about Notifications? There you can define a „autoclose“ option. To me a modal has to be controlable by the user. By that I mean, the user has to interact with the modal to close/open it...

**Comment by AlekVolsk** [comment]
Sometimes the whim of the client makes perverted with auto closing, with the notification do not fit the design

**Comment by AlekVolsk** [comment]
It costs me nothing to put a timer to auto-close the alert, but then it must be me, given the option a unique id

**Comment by AlekVolsk** [comment]
Hint, is it worth the wait?

**Comment by janschoenherr** [comment]
With the next release the promise object returned by Modal Dialogs holds a reference to the Modal component itself. Does this help you?

https://github.com/uikit/uikit-site/commit/058dd17e7f654596317816ed5822cab071606c7f
