### ISSUE TITLE
Form Select Custom Control is broken since Version 3.0.0 beta.30

### ISSUE THREAD

**Issue by pcout** [uikit/uikit#2980]
### UIkit version

3.0.0-beta.32

### Browser
ALL
### Reproduction Link
The docs.
https://getuikit.com/docs/form#custom-controls
### Steps to reproduce
See Select. None of the examples shows the text. Click and select an option.
### What is Expected?
The Select options should be visible and when one is chosen it should replace the option previously selected.
### What is actually happening?
The Select options aren´t visible before or after being selected.

**Comment by janschoenherr** [comment]
Thanks, the selectors were no longer valid, fixed with uikit/uikit-site@b0264be7a1d11b2ba4209bf3b75295ee8f5233ba
