### ISSUE TITLE
UIkit 3.0.0-beta.32: Grid is not working in React Component

### ISSUE THREAD

**Issue by zeckdude** [uikit/uikit#2981]
### UIkit version
3.0.0-beta.32

### Browser
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction Link
https://stackblitz.com/edit/uikit-grid-example

### Steps to reproduce
Load the demo and look at the grid. 

### What is Expected?
According to https://getuikit.com/docs/javascript#uikit-and-reactive-javascript-frameworks, UIkit should be listening for DOM manipulations and will automatically initialize, connect and disconnect components as they are inserted or removed from the DOM

### What is actually happening?
It is not doing anything out of the box, and I need to initialize the Grid component in the React component's `componentDidUpdate()` method.

**Comment by janschoenherr** [comment]
This seems to be working fine for me. Even without the lines

```
  componentDidUpdate() {
    UIkit.grid('#search-results-grid');
  }
```

Is this an issue only after updating the search results?
