### ISSUE TITLE
Uikit3 tooltip + vue = empty tooltip

### ISSUE THREAD

**Issue by falur** [uikit/uikit#2984]
Uikit3 tooltip + vue = empty tooltip

### UIkit version
3.0.0-beta.32

### Browser
Firefox and Google Chrome

### Reproduction Link
https://codepen.io/falur/pen/RjWjNo

**Comment by falur** [comment]
o. understand
uikit should connect after connecting vue

**Comment by netbka** [comment]
@falur Can you please provide a code with a working example?
Thank you
