### ISSUE TITLE
Switcher "uk-switcher-item" not working

### ISSUE THREAD

**Issue by wolfcreative** [uikit/uikit#2985]
The "swtcher-item" does not work. When clicking, nothing happens

### UIkit version
3.0.0-beta.31 or 32

### Browser
FF 57beta.13, Chrome 61, IE11

### Reproduction Link
https://getuikit.com/docs/switcher#navigation-controls

### What is actually happening?
Fix it

**Comment by zzseba78** [comment]
It doesn´t work in the docs, but it works in the test and you can use it.
https://codepen.io/zzseba78/pen/ZaQbBw

Maybe change the title to "... not working in the docs.".

**Comment by wolfcreative** [comment]
@zzseba78 The problem is that in my project does not work too.

**Comment by alesvaupotic** [comment]
Works for me in both the docs and the test. Chrome latest, Edge.

**Comment by zzseba78** [comment]
@wolfcreative Did the Codepen works for you? Can you crete a codepen to check your code?

**Comment by janschoenherr** [comment]
Thanks, will be resolved with the next release.
