### ISSUE TITLE
The docs for the alert component are missing the JavaScript options

### ISSUE THREAD

**Issue by zeckdude** [uikit/uikit#2987]
### UIkit version
3.0.0-beta.32

### Reproduction Link
https://getuikit.com/docs/alert

### Steps to reproduce
Go to the docs for alert.

### What is Expected?
An explanation of the options that can be added along with a code sample. It is not apparent how to programmatically set the alert to be primary, success, warning, or danger. 

### What is actually happening?
The docs only show `UIkit.alert(element, options);`

**Comment by janschoenherr** [comment]
The options can be found right above the JavaScript section: https://getuikit.com/docs/alert#component-options

**Comment by zeckdude** [comment]
It is not apparent how to programmatically set the alert to be primary, success, warning, or danger though. Is it even possible or are they only classes that can be added to elements that are added to the DOM through other means?
