### ISSUE TITLE
Incorrect position calculation for headers/navigation links.

### ISSUE THREAD

**Issue by algo99** [uikit/uikit#2989]
### UIkit Documentation 
Online version

### Browser
Linux Firefox-52.4.1/Chrome-62.0.3202.75 

### Reproduction Link
https://getuikit.com/docs/

### Steps to reproduce
Click *# Package contents* header/link on the page (page content, **not** the TOC on the right side).

### What is Expected?
*# Package contents* line is directly underneath the top blue navigation bar.

### What is actually happening?
The uk-navbar height is not taken into account by calculation of the current content position and the *# Package contents* line is hidden behind the top navigation/menu bar.

**Comment by janschoenherr** [comment]
Thanks, fixed with uikit/uikit-site@5a3d9f0656cf86b80c58e1298710c57e6f5d4da1
