### ISSUE TITLE
slideshow

### ISSUE THREAD

**Issue by HassaN0152** [uikit/uikit#2990]
### UIkit version

3.0.0-beta.32

### Browser
All browsers
### Reproduction Link

https://getuikit.com/docs/slideshow
### What is actually happening?
I used the auto-start slider code, but when I switch the slider manually, the slider is no longer automatically changed.
Translate by Google

**Comment by Riddler84** [comment]
I think this is intended behaviour.

https://github.com/uikit/uikit/issues/2163
https://github.com/uikit/uikit/issues/1414
https://github.com/uikit/uikit/issues/1290

**Comment by janschoenherr** [comment]
Currently, this is indeed intended. We are open for discussion though ;-)

**Comment by HassaN0152** [comment]
@Riddler84  I read the topics, but, unfortunately, no problems were solved.
Does anyone know the solution to this problem?

**Comment by zzseba78** [comment]
It´s not a problem, it works this way, if you take control on the navigation ( interacting with it ) the autoplay should stop, it´s confusing if not.

**Comment by Riddler84** [comment]
@HassaN0152 I've linked these topics because of the statements of the devs in them, not because of a possible solution. Like @janschoenherr mentioned, it's not officially a "problem" ;)

**Comment by HassaN0152** [comment]
@Riddler84 Thanks, I was wrong now I realized.
