### ISSUE TITLE
Lightbox not firing events.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2991]
### UIkit version

3.0.0-beta.32

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/xPZvqR
### Steps to reproduce
Open the Lightbox
### What is Expected?
Events fire
### What is actually happening?
They doesn´t fire.

**Comment by janschoenherr** [comment]
The events are triggered on the Lightbox Panel, not the Lightbox _trigger_. That is not optimal to be honest.

Also:

```
UIkit.util.on('$element', 'show', function () {
   alert("Show");
});
```

That will not work, instead try:

```
UIkit.util.on('#box', 'show', function () {
   alert("Show");
});
```

**Comment by zzseba78** [comment]
Perfect, thanks for the explanation! 👍

**Comment by zzseba78** [comment]
@janschoenherr And how can i reference to the Lightbox Panel in order to use events?
https://codepen.io/zzseba78/pen/YEqaRW

Sorry, i didn´t found an example on the docs.
Thanks.

**Comment by ivanherczeg** [comment]
Hi, 
I would like to use the 'showitem' event, but the example below, return with 'not a function'

UIkit.util.on('element', 'itemshow', function () {
   //do something
});

Could you please reveal, which object has the event listeners for the Lighbox component, and how the UIKit can access it? Very thanks.

**Comment by TomS-** [comment]
@zzseba78 did you manage to figure this one out? I've seen another example of 
```
UIkit.util.on(document, '.uk-lightbox', 'beforeshow show shown itemshow hide hidden', listenerFunction)
```

Which doesn't work either

**Comment by zzseba78** [comment]
@TomS- Hi! Try this:
```
UIkit.util.on(document, 'shown', '.uk-lightbox.uk-open', function () {
  console.log('Lightbox is displayed!');
});
```

**Comment by TomS-** [comment]
@zzseba78 

I can not for the life of me get these to work. 
```
UIkit.util.on(document, 'beforeshow', '.uk-lightbox', function(e) {
	var items = e.target.querySelector('.uk-lightbox-items');
	
	UIkit.util.on(items, 'click', 'li', function() {
		UIkit.lightboxPanel(e.target).show('next');
	});
});
```

Any ideas?
