### ISSUE TITLE
https://getuikit.com/download is redirecting to 404

### ISSUE THREAD

**Issue by 5argon** [uikit/uikit#2992]
### UIkit version

3.0.0-beta.33

It redirects to :
https://github.com/uikit/uikit/releases/download/v3.0.0-beta.33/uikit-3.0.0-beta.33.zip

The correct ones should be (the dot behind "v") :
https://github.com/uikit/uikit/releases/download/v.3.0.0-beta.33/uikit-3.0.0-beta.33.zip

**Comment by janschoenherr** [comment]
Thanks, fixed
