### ISSUE TITLE
uk-tab-left inside modal crashing

### ISSUE THREAD

**Issue by Bloemendaal** [uikit/uikit#2996]
### UIkit version

3.0.0-beta.33

### Browser
Chrome latest (PC and Mobile)

### Reproduction Link

https://codepen.io/Bloemendaal/pen/MOydNE

### Steps to reproduce
Create a uk-switcher using uk-tab="connect: #switcher-tab-left; animation: uk-animation-fade; swipe: false;" that has class="uk-tab-left" inside a modal

### What is Expected?
A switcher working as showed on the switcher page.

### What is actually happening?
Once you resize the window < 960px the modal starts glitching. Uk-open seems to be no longer working properly. Inside the codepen is an example for an uk-tab without the class uk-tab-left which seems to work fine (if you remove the uk-tab-left ofcourse).

**Comment by wolfcreative** [comment]
I confirm. In my project there is such a bug. Only if the size is 960 and below
