### ISSUE TITLE
UiKit Offcanvas errors when "uk-offcanvas-content" class is not set

### ISSUE THREAD

**Issue by deifh1118** [uikit/uikit#2997]
### UIkit version
3.0.0-beta.33 and previous version (tested also with 2.27.4)

### Browser
Google Chrome

### Reproduction Link
[https://jsfiddle.net/deifh1118/w99yt3ek/4/](https://jsfiddle.net/deifh1118/w99yt3ek/4/)

### Steps to reproduce
1. Open offcanvas and the Chrome console shows:
```
uikit.js:5774 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at Offcanvas.write (uikit.js:5774)
    at uikit.js:2797
    at runTasks (uikit.js:1591)
    at Object.flush (uikit.js:1569)
```

2. If there is an stacked offcanvas (button "Stack" of the jsfiddle offcanvas), this error appears in the Chrome console and when the offcanvas is closed the offcanvas does not work anymore:
```
uikit.js:5880 Uncaught TypeError: Cannot read property 'scrollLeft' of null
    at Offcanvas.handler (uikit.js:5880)
    at Function.<anonymous> (uikit.js:190)
    at uikit.js:3115
    at HTMLDivElement.selfHandler (uikit.js:3105)
    at uikit.js:1469
    at Array.reduce (<anonymous>)
    at trigger (uikit.js:1469)
    at uikit.js:3470
    at <anonymous>
```

### What is Expected?
The body "behind" the offcanvas is supposed to open without errors.

### Note
If the class "uk-offcanvas-content" is set on the wrapper div element the content behind is not scrollable but the errors in the Chrome console do not appear and the stack offcanvas works properly.

**Comment by janschoenherr** [comment]
Currently it is required to set that class: https://getuikit.com/docs/offcanvas#usage

Technically it would not be needed, if the page content is not transitioned and the overlay is not enabled.
