### ISSUE TITLE
uk-tab issue in 3.0.0-Beta.34

### ISSUE THREAD

**Issue by ryancramerdesign** [uikit/uikit#3001]
### UIkit version

3.0.0-beta.34

### Browser

Current Chrome Version (61.0.3163.100) in OS X Sierra, but I think this issue likely affects other browsers/platforms. 

### Reproduction Link

https://getuikit.com/docs/tab  
(all tabs except the "Preview" and "Markup" tabs)

### Steps to reproduce

Click on any tab other than the first, then click back to the first. It won't let you click the first tab anymore, rendering it non functional. 

For instance, in the "Usage" section of the Uikit tab documentation page, there are tabs labeled: Left, Item, Item, Disabled. When the page loads "Left" is active. Click either of the "Item" tabs. Now attempt to click the "Left" tab again, which no longer works. 

### What is Expected?

It should be possible to click the first tab again. 

### What is actually happening?

The first tab (or maybe whatever is the uk-active tab) is no longer functional. 

### Additional notes

I noticed the issue after upgrading from beta 30 to beta 34, so issue likely introduced between these versions. 

If I comment out the "return" on line 127 of js/core/switcher.js, I no longer experience the issue:
~~~~~
if (!toggle || prev >= 0 && hasClass(toggle, this.cls) || prev === next) {
  // return;
}
~~~~~
Another related issue observed is that uk-tab now requires an `li.uk-active` tab at initialization. Previously it assumed the first tab in the list was the uk-active tab, if there was not already a uk-active tab. I'm guessing this is another manifestation of the same issue reported here.

**Comment by janschoenherr** [comment]
Thanks, resolved with 8054930d445b810d6cee10bc849903056f2e2df1
