### ISSUE TITLE
uk-height-match for switcher

### ISSUE THREAD

**Issue by miprogrammer** [uikit/uikit#3002]
uk-height-match does not work for switcher content.

**Comment by janschoenherr** [comment]
Please add a reproduction link.

**Comment by miprogrammer** [comment]
Here you go:
https://codepen.io/anon/pen/NwbPQL

I was thinking the black border around the uk-switcher (content area) should stay the same if I added the "uk-height-match", but it doesn't appear to do so.

Thank you for taking a look at it.

**Comment by janschoenherr** [comment]
You'll have to set the _row_ option to false:

    uk-height-match="row: false"

The docs were missing the option table, it is now updated: https://getuikit.com/docs/utility#match-height

**Comment by miprogrammer** [comment]
Worked perfectly, thank you!
