### ISSUE TITLE
text-shadow property for button elements

### ISSUE THREAD

**Issue by getimo** [uikit/uikit#3006]
### UIkit version

3.0.0-beta.34

### What is actually happening?

You can't set the text-shadow property for button elements. It would be nice to extend the list of the supported properties so it does work with the inverse component.

**Comment by zzseba78** [comment]
Hi, well i can see the text shadow in all browsers.
https://codepen.io/zzseba78/pen/RjoyBG

Do you see it in the codepen?

**Comment by getimo** [comment]
Ok, maybe I'm at the wrong place :) What I meant: in Yootheme Pro there is no dedicated property for the attribute text-shadow. I'll post into the forums, sorry!
