### ISSUE TITLE
UIKit v3 - Drop Area Upload not receiving file data

### ISSUE THREAD

**Issue by Xen0F0rm** [uikit/uikit#3008]
### UIkit version
3.0.0-beta.34

### Browser
Chrome

### Reproduction Link
[Codepen Reproduction Link](https://codepen.io/Xen0F0rm/pen/qVqQeL)

### Steps to reproduce
1. Go to codepen link above
2. Try to drag and drop a file in the drop zone.
3. Console log shows 0 files attached.
4. Try the select option upload "selecting one".
5. Choose file(s) to upload.
6. Console log shows correct amount of files attached and I show on screen the name of the first file attached.

### What is Expected?
When I drag and drop a file or multiple files it should function the same as selecting a file. When I'm done dragging and dropping my console log should show X amount of files attached where X is the amount of files I dragged.

### What is actually happening?
What is actually happening is there are no files being attached to the underlying input that is supposed to be holding all the files. The underlying input tag does hold files when you do the "select" option, but the "drop zone" option does not attach any files to the input.

**Comment by janschoenherr** [comment]
No, with drag and drop the files are taken from the _drop_ events _dataTransfer_

However, you can simply listen for the 'upload' event.

```
  UIkit.util.on('.js-upload', 'upload', function (e, files) {
    console.log(files);
  });
```
