### ISSUE TITLE
[UK-3] The component leader is not working in accordion

### ISSUE THREAD

**Issue by cefiro** [uikit/uikit#3009]
The component leader is not working in accordion.
The component leader is not working in the accordion. To see the bug, you need to click on the headers of the accordion.

Example: https://codepen.io/cefiro/pen/POWjOv

**Comment by janschoenherr** [comment]
Thanks, fixed with 48b9dbade8963cbe7df211158944544f33779b6f

**Comment by cefiro** [comment]
Thanks!!!
