### ISSUE TITLE
Slideshow mouse drag triggers all slideshow events even when slide not changing

### ISSUE THREAD

**Issue by m0n0mind** [uikit/uikit#3012]
### UIkit version
3.0.0-beta.34

### Browser
Chrome 61.0.3163.100 (64-Bit), OS X 10.11.6

### Reproduction Link
https://codepen.io/anon/pen/QOpGqB

### Steps to reproduce
Just drag a slide with the mouse and release it before it triggers the slide to change.

### What is Expected?
Only relevant events are triggered, maybe even none except "dragstart".

### What is actually happening?
All events attached to the slidehow component are triggered:
beforeitemshow itemshow itemshown beforeitemhide itemhide itemhidden dragstart

**Comment by m0n0mind** [comment]
Nobody else noticed this behaviour?
This is an issue because I connected two sliders (one for content overlay, one for the images) in order to be more flexible in the way the slideshow elements are transitioned.

might be resolved, if slidehows could be connected like requested here #2970

**Comment by m0n0mind** [comment]
Disable drag completely as an component option would help, too.

**Comment by janschoenherr** [comment]
I believe this is resolved? I will reopen the issue if not.
