### ISSUE TITLE
3.0.0-beta.31 and higher, child elements in .uk-accordion-title does not trigger accordion toggle anymore

### ISSUE THREAD

**Issue by gingebaker** [uikit/uikit#3014]
### UIkit version
3.0.0-beta.31 to 3.0.0-beta.34

### Reproduction Link
https://codepen.io/gingebaker/pen/BmWWWo

### Steps to reproduce
Just add a html tag inside a .uk-accordion-title element like a span/div with content in it

### What is Expected?
before beta31 every click inside the uk-accordion-title triggered the toggle.

### What is actually happening?
after beta31 child tags do not trigger the toggle anymore.

Is this intentional behaviour? This is breaking some stuff in my current websites?

Thank you...

**Comment by viocassel** [comment]
Confirm 👆
