### ISSUE TITLE
Drop positioning issue since 3.0.0 beta 34

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#3016]
### UIkit version

3.0.0-beta.34

I'm using the `drop` component with `pos: bottom-justify` and `offset: 0`.

I believe this issue is related to removing the jQuery dependency, and using a home-made solution to detect the width to justify to. I think jQuery correctly handled the border width of the related element in the calculation, whereas the new implementation does not take the `box-sizing` into account or something like that.

Still, this doesn't explain why the top offset is different, too. In order to align it correctly, I need to set `offset: 1` in version 3.0.0-beta.34. 

### What is Expected?

<img width="465" alt="before" src="https://user-images.githubusercontent.com/2749/32671003-038a08f6-c646-11e7-9ca7-544528886ed4.png">

### What is actually happening?

<img width="453" alt="after" src="https://user-images.githubusercontent.com/2749/32671010-080f6d8a-c646-11e7-9c69-585501b7864a.png">

(nevermind the blue edge on the right, which appears thicker - there's a blue element below that now appears due to the shrinking)

**Comment by ruchern** [comment]
Off topic, what is that text editor that you are using?

**Comment by fabien** [comment]
@ruchern it’s a customized Woofmark editor (https://github.com/bevacqua/woofmark)

**Comment by ruchern** [comment]
@fabien Thanks!

**Comment by janschoenherr** [comment]
Please provide a minimal reproduction link.

You could start with this template: http://codepen.io/anon/pen/XMpryM

**Comment by fabien** [comment]
@janschoenherr I've found the issue. For some reason, the `toggle` parameter (which was pointing to a specific jQuery element) was not taken into account anymore. Due to the nesting of the tags, the width of the wrong element was being used, hence the issue I was seeing. It was indeed the border, but this was applied to the parent, causing both child nodes to be smaller.

Is there a reason the `toggle` parameter stopped working, perhaps?
