### ISSUE TITLE
Sortable Doesn't work on iOS Safari

### ISSUE THREAD

**Issue by DanielDarrenJones** [uikit/uikit#3017]
### UIkit version

3.0.0-beta.34

### Browser
iOS Safari (iOS 11.0)
### Reproduction Link

https://getuikit.com/assets/uikit/tests/sortable.html

### Steps to reproduce
Attempt to drag sortable list and nothing happens, the sortable list from v2 works as expected.

### What is Expected?
The items should move list on desktop.

### What is actually happening?
No movement occurs.

**Comment by janschoenherr** [comment]
Sure, it's fixed in https://github.com/uikit/uikit/commit/6b73f10e339cec2293704045fa560fa1a0b4297d
