### ISSUE TITLE
feature request: uk-toggle reverse effect

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#3026]
### UIkit version

3.0.0-beta.35

### Steps to reproduce
for example, an archer to the search form which was hidden at the beginning, when click the link, the search form pushes down, like the push in navbar or the accordion but only one element.

**Comment by aarongerig** [comment]
This is already possible. Simply add the `hidden` attribute to the element to be toggled. Finally, configure your desired animation and it will "animate in" your element.

**Comment by aarongerig** [comment]
Could look something like this...

```html
<button href="#toggle-animation" class="uk-button uk-button-default" type="button" uk-toggle="target: #toggle-animation; animation: uk-animation-fade">Toggle</button>
<div id="toggle-animation" class="uk-card uk-card-default uk-card-body uk-margin-small" hidden>Animation</div>
```

**Comment by janschoenherr** [comment]
Has this been resolved?
