### ISSUE TITLE
Wrong content position with transition classes in Slideshow

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3027]
### UIkit version

3.0.0-beta.35

### Browser
All browsers

### Reproduction Link

https://jsfiddle.net/viocassel/zp1qk6ku/

### What is actually happening?
The content blocks are not positioned correctly in Slideshow if they have  `uk-transition-*` class.

**Comment by JohannesBraaksma** [comment]
In my opinion there isn't anything wrong. 
try:

 `<div class="uk-position-center-left">
                <div class="uk-overlay uk-overlay-primary uk-transition-slide-left">
                    <h3 class="uk-margin-remove">Center Left</h3>
                    <p class="uk-margin-remove">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>`

instead of:

 `<div class="uk-overlay uk-overlay-primary uk-position-center-left uk-transition-slide-left">
                    <h3 class="uk-margin-remove">Center Left</h3>
                    <p class="uk-margin-remove">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>`

**Comment by viocassel** [comment]
@JohannesBraaksma  you're right.
Thank you!
