### ISSUE TITLE
Slideshow and <picture>?

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3028]
Hi,
Someone is using `<picture>` in [Slideshow](https://getuikit.com/docs/slideshow) component? Images are not displayed... 😔

### UIkit version

3.0.0-beta.35

### Reproduction Link
https://jsfiddle.net/viocassel/a61kxtrc/

**Comment by janschoenherr** [comment]
The uk-cover attribute needs to be set on the _picture_ element.

**Comment by viocassel** [comment]
Thanks @janschoenherr !
