### ISSUE TITLE
create a custom Sass RTL theme

### ISSUE THREAD

**Issue by samanmohamadi** [uikit/uikit#3032]
As I have found out there is no way to create custom RTL theme in sass version, right?

**Comment by dasdeck** [comment]
Hi!
Can you elaborate on what you are trying to do?
As for know, the RTL css is generated from the css that is generated by less.
http://rtlcss.com/
You should be able to do the same with the css you generate from the generated scss.
Are you looking for a command to convert your scss to css?
As far as I'm aware we are only generating css from less.

Cheers!

**Comment by dasdeck** [comment]
I'll close this for now.
