### ISSUE TITLE
Modal bgClose && escClose options not working

### ISSUE THREAD

**Issue by gola99** [uikit/uikit#3035]
Moin ;)

I'm trying to add a modal and disable the esc and background close. Within the docs i need to use 'bg-close' and 'esc-close' but it's not working:

`UIkit.modal('#my-modal', { 'esc-close': false, 'bg-close': false }).show();`

I've tried also this approach, but it's also not working:

`UIkit.modal('#my-modal', { escClose: false, bgClose: false }).show();`

**Comment by aarongerig** [comment]
First, instantiate your component, then call methods on it.
```js
var modal = UIkit.modal('#my-modal', {
    escClose: false,
    bgClose: false
});

modal.show();
```

Hope that helps. :)

**Comment by gola99** [comment]
thanks, but that's not working.

**Comment by aarongerig** [comment]
Works fine for me...

https://codepen.io/aarongerig/pen/pdaLaR

**Comment by gola99** [comment]
strange :/ I'm using the exact same markup. Anyway, thanks for you help 👍

**Comment by haizbp** [comment]
Remove 'uk-modal' on your element :)
