### ISSUE TITLE
Events not working on Tooltip Component

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3036]
### UIkit version

3.0.0-beta.35

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/EbowbW?editors=1010
### Steps to reproduce
Hover the button
### What is Expected?
Tooltip events should fire
### What is actually happening?
Events doesn´t fire.

**Comment by aarongerig** [comment]
Actually they **do** fire: https://codepen.io/aarongerig/pen/dZjKmb
The only event it's not reacting to is `hidden`. 

BTW, if you want to find out, which element triggers an event, you can use this:
```js
document.addEventListener('someevent', function(e) {
  console.log(e.target);
});
```
This adds an event listener on the whole document and logs the element on which the element was triggered on in the console.

Hope this was helpful! ;)

**Comment by zzseba78** [comment]
I see, i was targeting the button. Thank you, and your code will be very useful to deal with events! Thanks Aaron! Closing this.

**Comment by algo99** [comment]
From https://getuikit.com/docs/tooltip
> ### Events
> The following events will be triggered on elements with this component attached:

Should it be then corrected ?

**Comment by aarongerig** [comment]
@algo99 You're right, should probably be fixed. @janschoenherr What do you think? ;)

**Comment by jyjunyz** [comment]
@aarongerig switcher has the same problem,
use `UIkit.util.on('#switcher-id', 'show', function(){})` not work

**Comment by janschoenherr** [comment]
@aarongerig that'd be good, I don't see that changing anytime soon. Would you update the docs?

**Comment by aarongerig** [comment]
For reference: https://getuikit.com/docs/tooltip#example
