### ISSUE TITLE
Can not to setup my theme entry point for less compiler on uikit

### ISSUE THREAD

**Issue by footballman17** [uikit/uikit#3038]
Hi, guys-) I try to configure npm run watch command for less. On uikit documentatiton
write that i can create folder "custom" and less file with my code, example my-theme.less. So, i create: **src/custom/my-theme.les**s file and import uikit theme - @import "../src/less/uikit.theme.less";
now question - how npm watcher will know about this file?)
and how can I make my file entry point for less compiler?

**Comment by dasdeck** [comment]
The watcher should already watch your custom less, aka. `glob('**/*.less')` will find all less files inside the UIkit folder.
I'm not sure I understand your second question. Wouldn't the `./custom/my-theme.less` (no 'src' in the beginning) be your entry? You are basically including the original entry and extending it.

Cheers!

**Comment by dasdeck** [comment]
Ok, I'll close this. Feel free to open a new one if this is still an issue.
