### ISSUE TITLE
slideshow, get actual slide (index) in uikit 3

### ISSUE THREAD

**Issue by rosibabystiupida** [uikit/uikit#3042]
Hi,
I need the script for get actual slide (index) in uikit 3:

With uikit 2 the script was:
`$( _selector_ ).on( 'show.uk.slideshow', function( event, next, current ) {`

I read the documentation of uikit 3 but i can't get "next" and "current" slide. In the documentation of uikit 3 there isn't the description of how to use event and relative parameters as the documentation of uikit 2 do.

Example of uikit 2 documentation description:
Name: beforeshow.uk.slideshow
Parameter: event, next slide, current slide
Description: Before showing a new slide (before animation is finished)

This if my old code that work for uikit 2.
```
    $(".slideshowevento").on('beforeshow.uk.slideshow', function(event, nxt_slide, cur_slide){
    $(nxt_slide).children('video')[0].currentTime = 0;
    });
```

This is my try to covert for uikit 3:
```
    $(".slideshowevento").on('beforeitemshow', function(event, nxt_slide, cur_slide){
    $(nxt_slide).children('video')[0].currentTime = 0;
    });
```
It doesn't work. Maybe the parameter "event, nxt_slide, cur_slide" now need a different name:

Any ideas?
thank you very much

**Comment by aarongerig** [comment]
Could be achieved like this:
https://codepen.io/aarongerig/pen/qVyKWJ

With jQuery it's even easier ...

**Comment by rosibabystiupida** [comment]
Thank you aarongerig!
It works great!

**Comment by janschoenherr** [comment]
There is also an `index` property on the slideshow instance itself.

`UIkit.getComponent($0, 'slideshow').index;`

**Comment by ikabod** [comment]
I can not get this work with current version 3.1.5. What is $0? My event function never returns a valid index:

`cardSwitched: function (event, item){
        
        // get the target
        var target = event.target;
        
        console.log(UIkit.getComponent($0, 'slideshow').index);
        console.log(UIkit.getComponent(target, 'slideshow').index);
        console.log(UIkit.getComponent(item, 'slideshow').index);
        console.log(UIkit.getComponent(this.ulSlideshow, 'slideshow').index);
        
        // this.ulSlideshow = my slideshow element
        
    }`

This always shows "undefined"

**Comment by janschoenherr** [comment]
`$0` is the slideshow element. 

    UIkit.getComponent(document.querySelector('[uk-slideshow]'), 'slideshow').index

**Comment by ikabod** [comment]
Thank you for your reply.

this.ulSlideshow was not my slideshow element, but my slideshow items. After I changed this, it works fine.

**Comment by OlehMaistrenko** [comment]
UIkit.util.on(document, 'itemshow', '.slideshow', function(e){
	console.log(e.current.__uikit__.slideshow.index);
});

**Comment by elabx** [comment]
This seems to be working for me: 

```
 UIkit.util.on(' .slideshow ', 'itemshown' , function(e){
                console.log(e.detail[0].index);
});
```
Not sure when detail is filled with more items.
