### ISSUE TITLE
UglifyJs ERROR and broken Tests

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3043]
OS: Windows 10
Node version: 8.9.1
NPM version: 5.5.1
webpack version: 3.8.1
webpack-dev-server version: 2.9.4

### UIkit version

3.0.0-beta.35 + dev

### Steps to reproduce
Run `npm run test`

### What is actually happening?
```
ERROR in dist/js/uikit.min.js from UglifyJs
Unexpected token: name (urlParts) [dist/js/uikit.min.js:3448,4]
```
![](https://image.prntscr.com/image/G7UAHPn7QPKSKfv39-KurQ.png)
Maybe [UglifyjsWebpackPlugin](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) will be useful? Using `uglifyjs-webpack-plugin` instead of `uglify-js`.
A little [discussion](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/132#issuecomment-336230478).

In the console of Tests (http://localhost:8080/tests/) we see that 

![](https://image.prntscr.com/image/J986-6PJSzOAzy8cwhvrKw.png)

**Comment by dasdeck** [comment]
Hi!
Thank you for your report!
Can you verify that:
f57cd8e74df113940993bacafc27b399092d4a6d
fixes this issue?

Cheers!

**Comment by viocassel** [comment]
Hi @dasdeck !
Thanks for the fix. It works well.
