### ISSUE TITLE
Sticky not sticking after off-canvas has been opened

### ISSUE THREAD

**Issue by mechanic22** [uikit/uikit#3045]
### UIkit version

3.0.0-beta.35

### Browser

Chrome

### Reproduction Link

https://codepen.io/mechanic22/pen/qVorNg

### Steps to reproduce

Open the off canvas then the sticky doesn't work anymore

### What is Expected?

The sticky to stick after the off canvas is closed or when scrolling occurs when the off canvas is open

### What is actually happening?

sticky bar is disappearing

**Comment by aarongerig** [comment]
For that you have to set: `uk-offcanvas="overlay: false"`

**Comment by mechanic22** [comment]
What if I want an overlay?

**Comment by janschoenherr** [comment]
That is currently not possible. To prevent scrolling the body, it is shrunk to the viewport height. That'll in turn mess with the sticky component.

We haven't found a better way (consistent across browsers and systems) to prevent scrolling.

**Comment by janschoenherr** [comment]
This has been resolved.
