### ISSUE TITLE
Modal is hiding when the Prev/Next of jquery UI datepicker is clicked

### ISSUE THREAD

**Issue by Yiannistaos** [uikit/uikit#3046]
### UIkit version
3.0.0-beta.35

### Browser
Google Chrome
Version 62.0.3202.94 (Official Build) (64-bit)

### Steps to reproduce
I use the jQuery datepicker https://jqueryui.com/datepicker/ and the UIkit.

### What is Expected?
I want to use the datepicker in my form, inside the modal window.

### Bug
The problem is that the modal window is hiding after clicking the Prev/Next of jquery UI datepicker.

### Demo at jsfiddle.net
Here is the demo https://jsfiddle.net/Yiannistaos/03ss4u43/1/

Thanks in advance.

**Comment by aarongerig** [comment]
Prevent DOM bubbling and it should be fine:
```js
$('#ui-datepicker-div').on('click', function(e) {
  	e.stopPropagation();
  });
```

**Comment by Yiannistaos** [comment]
@aarongerig thanks for your reply but still not working...Did you tried it?

**Comment by aarongerig** [comment]
@Yiannistaos Yes I did: https://codepen.io/aarongerig/pen/JOaxaw

**Comment by Yiannistaos** [comment]
It works now!

Thank you very much @aarongerig!

**Comment by aarongerig** [comment]
Great, then you can close this issue. Thanks!
