### ISSUE TITLE
'global' is undefined

### ISSUE THREAD

**Issue by Vortelf** [uikit/uikit#3047]
### UIkit version

3.0.0-beta.35

### Browser
Firefox Quantum 57.0

### Steps to reproduce
Error occurs in both `uikit.js` and `uikit-icons.js`
`8:2 'global' is undefined`
This works like a charm
```html
<a class="uk-navbar-toggle" uk-navbar-toggle-icon href=""></a>
```
This doesn't
```html
<a href="" class="uk-icon-button" uk-icon="icon: twitter"></a>
<a href="" uk-icon="icon: heart"></a>
```

**Comment by zzseba78** [comment]
I´m using Quantum in OS Hight Sierra, and don´t having any problems with icons.

**Comment by wolfcreative** [comment]
I´m using Quantum in Win10, and don´t having any problems with icons.

**Comment by dasdeck** [comment]
Hi @Vortelf ! Seems nobody can replicate your issue, can you elaborate on your setup?

**Comment by Vortelf** [comment]
Sure thing. Here's my setup:

- **Node 8.9.0 LTS**
- **Express 4.16.2**
- **ejs 2.5.7**

My template looks like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Начало</title>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/uikit.js"></script>
    <script src="/js/uikit-icons.js"></script>
    <!-- Viewport mobile tag for sensible mobile support -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/styles/mix.min.css">
  </head>

  <body>
        <nav class="uk-navbar-container uk-margin" uk-navbar>
            <div class="uk-navbar-left">
                <div class="uk-navbar-left">
                    <a class="uk-navbar-toggle" uk-navbar-toggle-icon href="#offcanvas-slide" uk-toggle></a>
                </div>
            </div>
        </nav>

      <div id="offcanvas-slide" uk-offcanvas>
          <div class="uk-offcanvas-bar">
              <button class="uk-offcanvas-close" type="button" uk-close></button>
              <ul class="uk-nav uk-nav-default">
                  <li class="uk-nav-divider"></li>
                  <li class="uk-nav-header">Галерия</li>
                  <li><a href="/client/list">Клиенти</a></li>
                  <li><a href="/vehicles/list">Автомобили</a></li>
                  <li class="uk-nav-divider"></li>
              </ul>
          </div>
      </div>
    <%- body %>
  </body>
</html>
```

**Comment by dasdeck** [comment]
Thanks @Vortelf !
Unfortunately this does not help me much.
Runs flawlessly in every system here.
I can give it another try if you provide more info, judging by the nature of the error (the 'this' variable is somehow incorrect, this 'global' is undefined in the AMD wrapper) it really points to an outside error source in the first place though.
Where did you obtain the source for UIkit? Website? Or did you build the source yourself?

**Comment by Vortelf** [comment]
Tried with both Yarn and from the site, but the result was the same.

**Comment by dasdeck** [comment]
Thanks @Vortelf unfortunately this issue still has not been replicated.
Maybe the next update will fix this for you.
