### ISSUE TITLE
Custom icons are not compiled into the .min file

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3049]
### UIkit version

3.0.0-WIP (develop).

### Steps to reproduce
Add `my-icon.svg` to the folder `custom/mytheme/icons` and run `npm run compile`.

### What is Expected?
Icons will be compiled in a `dist/js/uikit-icons-mytheme.js` and `dist/js/uikit-icons-mytheme.min.js` files.

### What is actually happening?
Icons are compiled only into the `dist/js/uikit-icons-mytheme.js` file, but not into the `dist/js/uikit-icons-mytheme.min.js` to. This file is not created...

**Comment by erasare** [comment]
We have a similar problem:

The angle brackets from html comments in custom icons () are transformed
in hex code (x3c, x3e) through the minifier into the *.min.js file .
So displaying of the icons is not possible.

**Comment by dasdeck** [comment]
@viocassel Thanks for reporting this!
It has just been fixed in b9795211d04fca5d653f03a95d2011def5f6521d
Cheers!
@erasare not sure this is related to your issue though. Can you please open a new one if the issue persists? Thanks!

**Comment by viocassel** [comment]
🤘 Thanks @dasdeck !

**Comment by viocassel** [comment]
Hi @janschoenherr  

After [this](https://github.com/uikit/uikit/commit/8c739cb79964e67843466ce2e52e007e15c3b6f3) changes icons does not compile to the `uikit-icons-mytheme.min.js` file. 

In the `uikit-icons-mytheme.js` file compiles fine.

**Comment by janschoenherr** [comment]
It seems to be working for me, you'll have to use a NodeJs version 8 and above.

**Comment by viocassel** [comment]
My colleagues has the same problem...

I use NodeJS 8.9.4

![ylkzeraetgejpskzitjh1g](https://user-images.githubusercontent.com/3341562/34768154-1b011f7a-f60b-11e7-8e28-2fa8f025620c.png)

**Comment by janschoenherr** [comment]
Thanks, fixed with 6ff72faa04c2e816d7702babcaf54de3b7047024

**Comment by viocassel** [comment]
Thanks @janschoenherr !
