### ISSUE TITLE
npm run watch ?

### ISSUE THREAD

**Issue by vc-development** [uikit/uikit#3050]
### UIkit version

3.0.0-WIP

---

When run `npm run watch` and change something in the Less files, the changes on the page are not visible. To see changes, we need to manually refresh the page. Is it possible to configure this so that changes were visible without any manual page reload?

@dasdeck can you help?

**Comment by dasdeck** [comment]
the npm run watch has no hot code swapping, this is only available in the webpack-dev-server (npm run test). However, this is not yet configured to include less files. I'll see what I can do!
