### ISSUE TITLE
Sortable not work for table

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#3052]
Sortabl not work for table, in console is some error. Now it work only for `div`

### UIkit version

3.0.0-beta.35

### Browser

Chrome 62

### Reproduction Link

https://codepen.io/Intiligent/pen/ZajORE?editors=1000

### Steps to reproduce

Apply `uk-sortable="handle: .uk-sortable-handle"` for tbody

### What is Expected?

Expect replace table row.

### What is actually happening?
On click on handler and start move in console pour down errors:

``` javascript

Uncaught TypeError: Cannot set property 'box-sizing' of undefined
    at uikit.js:1185
    at Array.map (<anonymous>)
    at css (uikit.js:1174)
    at String.<anonymous> (uikit.js:1198)
    at each (uikit.js:389)
    at uikit.js:1198
    at Array.map (<anonymous>)
    at css (uikit.js:1174)
    at Sortable.start (uikit.js:9907)
    at uikit.js:190
uikit.js:2064

Uncaught TypeError: Cannot read property 'display' of undefined
    at getDimensions (uikit.js:2064)
    at offset (uikit.js:2036)
    at offset (uikit.js:2022)
    at Sortable.write (uikit.js:9851)
    at uikit.js:2812
    at runTasks (uikit.js:1594)
    at Object.flush (uikit.js:1572)
```

**Comment by dasdeck** [comment]
Hey! 
Thanks for the report!
We thinking about adding table support. In the meantime, why not use divs instead?
Cheers!

**Comment by Intiligent** [comment]
it is necessary to use the table with all its properties (column data, vertical alignment, ...)

**Comment by meatpaste** [comment]
+1

**Comment by enrikaskv** [comment]
+1

**Comment by pcmanik** [comment]
@Intiligent Something new in this area?

**Comment by solisoft** [comment]
up

**Comment by SPQRInc** [comment]
Still nothing new here...? Too bad :-(

**Comment by patrickojeh** [comment]
+1

**Comment by LukasVaculcik** [comment]
we really could use sortable table rows
