### ISSUE TITLE
Extra Small Grids

### ISSUE THREAD

**Issue by tusharmangle** [uikit/uikit#3053]
Why does UIkit doesn't support extra small grid ?

**Comment by aarongerig** [comment]
With Less/Sass you can adjust the grid-size yourself:
https://github.com/uikit/uikit/blob/develop/src/less/components/grid.less#L34-L43
https://github.com/uikit/uikit/blob/develop/src/scss/components/grid.scss#L34-L43

Please close this issue. Thanks :)

**Comment by tusharmangle** [comment]
Thanks 😊
