### ISSUE TITLE
Accordion option active is broken

### ISSUE THREAD

**Issue by jayronimo76** [uikit/uikit#3059]
### UIkit version

3.0.0-beta.35

### Browser
Chrome, Firefox, Edge (all lastest), IE11

### Reproduction Link

https://getuikit.com/assets/uikit/tests/accordion.html
Example: Not animated

https://codepen.io/zzseba78/pen/rYqVQv?editors=1010

### What is Expected?
This example has set the option active to 0;
so first item should be open!

### What is actually happening?
last item is open (also does not matter if active is set to 0,1 or 2)!

**Comment by dasdeck** [comment]
Thanks for the report!
