### ISSUE TITLE
Custom icons with html comments inside are not usable

### ISSUE THREAD

**Issue by erasare** [uikit/uikit#3060]
### UIkit version
3.0.0-beta.35

### Steps to reproduce
npm run compile.
custom icons in /custom/icons with html-comment inside the svg.

### What is Expected?
Icon is usable via uk-icon="icon: XXX"

### What is actually happening?
The angle brackets from html comments in custom icons (`<!-- xyz -->`) are transformed
in hex code (x3c, x3e) through the minifier into the *.min.js file .
Displaying of these icons is not possible.

**Comment by aarongerig** [comment]
That's why you have to edit the icons before you compile them. It's the same when you place a SVG with invalid markup in your website, it will break as well. Have a look at UIkit's examples:
https://github.com/uikit/uikit/tree/develop/src/images/icons

The SVG markup should look like this:
```html
<svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <polyline fill="none" stroke="#000" stroke-width="1.03" points="13 16 7 10 13 4"></polyline>
</svg>
```

**Comment by erasare** [comment]
Sorry, but i don't think that comments inside svg's are invalid,
because it's just a piece of XML.
But you can convince me ;-)

My icons are from icomoon, a html comment is inside every downloaded svg.
I don't really want to modify each one of them :-/

**Comment by viocassel** [comment]
@erasare try SVGO.

**Comment by mightyvoodoo** [comment]
#2949

**Comment by erasare** [comment]
Thanks @mightyvoodoo  👍

**Comment by dasdeck** [comment]
I tested this in chrome, firefox and IE11. Can you tell me an instance where \x3c && \x3e are actually causing a problem? I can view my SVGs with comments just fine, as the browsers seem to just accept both. We might just put SVGO into the compile chain. We'll see. 

Cheers!

**Comment by dasdeck** [comment]
Ok, I'll close this. Feel free to open a new one if this is still an issue.
