### ISSUE TITLE
UIKit Calendar Component

### ISSUE THREAD

**Issue by Vortelf** [uikit/uikit#3061]
### UIkit version
3.0.0-beta.35

I needed a calendar, so I made one, but I'm sure that it can be improved so I'll just paste it here in case anyone is interested:
https://codepen.io/anon/pen/oodQqp

**Comment by staleo** [comment]
Thank you for it, Vortelf!
By the way, have you probably seen any good-looking solution of a datepicker for UiKit3? A kit itself runs in a beta cycle for almost a year, but, sadly, there's still nothing like a beautiful Datepicker from UiKit2.

**Comment by janschoenherr** [comment]
Thanks Vortelf, we don't have a place for stuff like this yet. Maybe add it to Stackoverflow for now?

**Comment by janschoenherr** [comment]
I just remembered, that there's also the Google Plus community: https://plus.google.com/communities/114238665434626719878
