### ISSUE TITLE
[Feature request] Screenreader-only utility class

### ISSUE THREAD

**Issue by Propaganistas** [uikit/uikit#3063]
It would be awesome to have a screenreader-only utility class as in [Bootstrap](https://github.com/twbs/bootstrap-sass/blob/5d6b2ebba0c2a5885ce2f0e01e9218db3d3b5e47/assets/stylesheets/bootstrap/_scaffolding.scss#L121).

This way situations where only icons are used can be made accessible, e.g.:
```html
<span uk-icon="icon: pencil"></span>
<span class="uk-sr-only">Edit</span>
```

**Comment by hyshka** [comment]
This would be a nice addition to UIkitv3. https://getuikit.com/docs/visibility

**Comment by hrvojegolcic** [comment]
+1

Important and very useful.
I would also add .sr-only-focusable for hidden links that become visible only when focused e.g. "jump to main content" or "skip block" etc.

**Comment by Acccent** [comment]
Hi, this was closed but I don't think the feature was added? Does the feature request exist somewhere else?

**Comment by jlahijani** [comment]
@Acccent I don't think this was ever added.  @janschoenherr Can this be considered?  I feel like it's crucial (and easy to add).
