### ISSUE TITLE
Uikit PHP Upload problem

### ISSUE THREAD

**Issue by hansamars** [uikit/uikit#3068]
This is the code I'm using for upload:
HTML:

> <form action="upload.php" method="POST" enctype="multipart?form-data">
        <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Pseidonīms:</label>
        <div class="uk-form-controls">
            <input class="uk-input uk-form-width-medium" id="form-horizontal-text" type="text" placeholder="Ievadiet pseidonīmu" name="nickname" id="nickname">
        </div>
    </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-horizontal-select">Izvēlies uzdevumu:</label>
          <div class="uk-form-controls">
            <div uk-form-custom="target: true">
          <select class="uk-select" id="form-horizontal-select" name="select">
		         <option selected = "selected"></option>
		           <?php
		             if (($handle = fopen("archive.csv", "r")) !== FALSE) {
		                 while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
			                    foreach($data as $task)
			         ?>

				           <option value="<?php echo strtolower($task); ?>"><?php echo $task; ?></option>

				               <?php
			                  }

                        fclose($handle);
		                    }?>
                      </select>
                    <input class="uk-input uk-form-width-medium" type="text" placeholder="Izvēlies uzdevumu"  enabled>
                  <br></div></div></div>

</script>
<div class="uk-margin" uk-margin>
<div uk-form-custom="target: true">
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input class="uk-input uk-form-width-medium" type="text" placeholder="Select file"  disabled>
  </div>
<button class="uk-button uk-button-default" value="Upload file" name="submit">Submit</button>
</div>
</form>

PHP:

> <?php
if(isset($_FILES["fileToUpload"]["name"])){
if(isset($_REQUEST['submit']))
{
    $nickname = (isset($_REQUEST['nickname']) ? $_REQUEST['nickname'] : null);
    $selected_key = (isset($_REQUEST['select']) ? $_REQUEST['select'] : null);
}

$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);

$uploadOk = 1;
$imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);

include 'header.php';
$filename = 'uploads/' . $nickname . '_' . trim($selected_key) . '.' . $imageFileType;
#session_write_close(); session_regenerate_id(true);
echo $filename. '<br>';
// Check if image file is a actual image or fake image
if(isset($_POST["submit"])) {
    $check = filesize($_FILES["fileToUpload"]["tmp_name"]);
    if($check !== false) {
        echo "File is an - " . $check["mime"] . ".";
        $uploadOk = 1;
    } else {
        echo "File is not an source file.";
        $uploadOk = 0;
    }
}
// Check if file already exists
if (file_exists($target_file)) {
    echo "Sorry, file already exists.";
    $uploadOk = 0;
}
// Check file size
if ($_FILES["fileToUpload"]["size"] > 500000) {
    echo "Sorry, your file is too large.";
    $uploadOk = 0;
}
// Allow certain file formats
$path_parts = pathinfo($_FILES["fileToUpload"]["name"]);
if(($path_parts['extension'] === '.cpp') || $path_parts['extension'] === '.pas') {
    echo "Sorry, only CPP and PAS files are allowed.";
    $uploadOk = 0;
}

// Check if $uploadOk is set to 0 by an error
if ($uploadOk == 0) {
    echo "Sorry, your file was not uploaded.";
// if everything is ok, try to upload file
} else {
    if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $filename)) {
        echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
    } else {
        echo "Sorry, there was an error uploading your file.";
    }
}
}
else {
  echo "No file detected";
}
?>

When ever I try to upload a file, the php script returns 'no file detected'. I have no clue what is going on.
### UIkit version
3.0.0-beta.35

### Browser
Google Chrome

**Comment by hansamars** [comment]
No matter, I screwed up, I miswrote '/' with '?'

**Comment by zzseba78** [comment]
Please clost it then. 👍
