### ISSUE TITLE
Sortable with handles disables swiping/scrolling

### ISSUE THREAD

**Issue by joagre** [uikit/uikit#3069]
## UIkit version
The latest version used on https://getuikit.com/docs/sortable#handle

### Browser
Android/Chrome

### Reproduction Link
https://getuikit.com/docs/sortable#handle

### Steps to reproduce
Go to https://getuikit.com/docs/sortable#handle using Android/Chrome. You can as expected perform drag an drop sorting using the handles but the areas around the handles do not respond to swipe/scrolling of the complete page. They are touch dead. That was unexpected. I tried to overrule this with touch-action settings in my css files but I could not get it to work.

### What is Expected?
The sortable drag and drop should only be active for the handles. The area around the handles should be sensitive to browser touch events, e.g. scrolling of the complete browser page up and down.

**Comment by dasdeck** [comment]
@saschadube 
sortable.less
.uk-sortable > * { touch-action: none; }
 ?

**Comment by joagre** [comment]
Ah! So to enable swiping/scrolling on the the areas around the sortable handle I must set its touch-action to auto.

Example:

```
<div class="uk-grid-small" uk-sortable="handle: .uk-sortable-handle" uk-grid>
  <div class="uk-width-1-1">
    <div class="uk-grid-small touch-action-auto" uk-grid>
      <div class="uk-width-expand">
        <input class="uk-input" type="text"  placeholder="Regex pattern"></input>
      </div>
      <div class="uk-sortable-handle uk-flex uk-flex-middle">
        <span class="uk-icon-button" uk-icon="icon: move"></span>
      </div>
      <div class="uk-width-expand">
        <input class="uk-input" type="text" placeholder="Replacement text"></input>
      </div>
    </div>
  </div>
  ...
</div>
```

and then have this in my css file:

```
.touch-action-auto {
    touch-action: auto;
}
```

It works. Thanks!

**Comment by dasdeck** [comment]
@joagre I'm glad it works for you! Can we consider this closed?

**Comment by joagre** [comment]
Yes, please close. Thanks!
