### ISSUE TITLE
[feature request] close off canvas with nav item click

### ISSUE THREAD

**Issue by jsnoriegam** [uikit/uikit#307]
Not sure if this is already implemented, i haven't found it yet.

I have an off canvas menu, and it's working normally but i need that when i click on one of the menu options it closes.

I did a workaround using javascript, but it would be nice a native process.

**Comment by juminoz** [comment]
There seems to be a bug in latest 2.x version if ".uk-offcanvas-close" is supposed to work.

**Comment by ratshili** [comment]
I have found a solution here: https://github.com/uikit/uikit/issues/2829
