### ISSUE TITLE
Errors in Test

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3071]
### UIkit version

3.0.0-WIP

### Browser
All

### Reproduction Link

http://localhost:8080/tests

### Steps to reproduce
Run `npm run test`

### What is Expected?
😎 All works "like a boss"

### What is actually happening?
🤔 Errors in console...

![UIkit errors in console](https://user-images.githubusercontent.com/3341562/33656188-5429fdc6-da86-11e7-9f3d-b61b6c1e4ce3.png)

🤓 Call for help from @dasdeck

**Comment by dasdeck** [comment]
yep broken and fixed again. 
Thanks for the report!
e614f59c670905a17118332f1cb09193438eab4e
