### ISSUE TITLE
Sticky creating too tall of uk-sticky-placeholder on refresh when css is loaded after sticky component intitialized

### ISSUE THREAD

**Issue by mechanic22** [uikit/uikit#3072]
### UIkit version
3.0.0-beta.35

### Browser
Chrome

### Reproduction Link
I am not sure how to put this in a code pen as the code pen doesn't have a refresh. But here is the html
https://codepen.io/mechanic22/pen/GOavLJ

### Steps to reproduce
Add a sticky navigation inside an off canvas. Scroll down so the sticky "sticks". Hit F5 (Refresh) the page and the browser will scroll down where you were. Scroll back up and you will see extra space. 

### What is Expected?

The uk-sticky-placeholder to have the correct placeholder height

### What is actually happening?

The uk-sticky-placeholder has too tall of height

**Comment by mechanic22** [comment]
Sorry everyone. I think I may have found my issue was with webpack loading my css. It looks like the script was running before the css was loaded, so the height of the navbar was determined before css was established. Not sure if that can or should be fixed.

**Comment by janschoenherr** [comment]
Is this resolved? If not, please comment.
