### ISSUE TITLE
Feature Request *** Fixed Sidebar component ***

### ISSUE THREAD

**Issue by tusharmangle** [uikit/uikit#3074]
Please add fixed sidebar component to UIKIT.
Thanks 😊

**Comment by aarongerig** [comment]
IMHO, this is unnecessary. It's easy CSS you can add yourself.
Have a look at this pen: https://codepen.io/zzseba78/pen/YEMrvZ (Thanks to @zzseba78)

Not a lot you have to do in order to make it possible.

**Comment by tusharmangle** [comment]
Thanks a lot 😊
