### ISSUE TITLE
Accordion component option of 'targets' not functioning

### ISSUE THREAD

**Issue by dajaffe** [uikit/uikit#3078]
### UIkit version

3.0.0-beta.35

### Browser
Chrome Version 62.0.3202.94 (Official Build) (32-bit)
### Reproduction Link
https://codepen.io/anon/pen/LOwNmo
### Steps to reproduce
Set the 'targets' key for the 'uk-accordion' attribute to an element type. Click something other than that element.
### What is Expected?
Only clicking the span element triggers opening and closing of the accordion section.
### What is actually happening?
If I use '**target**' - the accordion renders but ignores the value. If I use '**targets**' per the accordion documentation, the accordion fails to render properly.

https://getuikit.com/docs/accordion#component-options

**Comment by janschoenherr** [comment]
Thanks, the docs are missing the option you were looking for `toggle`. Will be fixed.

**Comment by janschoenherr** [comment]
5a5d69f3915bb1ea5c54e80496d69bdf623043e4

**Comment by dajaffe** [comment]
Thanks!
