### ISSUE TITLE
Modal / Switcher & UIKit.toggle issue

### ISSUE THREAD

**Issue by AfricanSwift** [uikit/uikit#3082]
### UIkit version
3.0.0-beta.35 (tested with this version, problem still exists)

### Browser
Tested on:
Safari Version 10.1.2
Google Chrome Version 62.0.3202.94
Firefox Version 57.0.1

Note: Same outcome on all 3 of the above browsers

### Reproduction Link
https://codepen.io/codefunc/pen/LePyKv

### Steps to reproduce
Steps follow using the above codepen:

1. Click on "open", and the modal is shown, and we can switch between the tabs to access either the "notes" or the "download"; important to note, the modal remains open when we switch to either: back or forth.
2. Now click on the download icon button in the "download" tab; the onclick event calls UIkit.toggle to dismiss the modal.
3. Click on open to reopen the modal; now try to read the text  on "notes" tab.  Modal immediately is dismissed, yet there is no onclick action for the "notes" tab.
4. This behaviour keeps repeating until the page is refreshed.

### What is Expected?
The modal should not be dismissed when switching between tabs; neither should the onclick event from the previous action keep repeating?

### What is actually happening?
The UIkit.toggle from the last onclick event appears to keep firing?

**Comment by aarongerig** [comment]
Instead of `UIkit.toggle('#bug-modal').toggle();` use `UIkit.modal('#bug-modal').hide();`.

**Comment by AfricanSwift** [comment]
Perfect, problem solved. Thank you.
