### ISSUE TITLE
sortable component broken in Android/Chrome

### ISSUE THREAD

**Issue by joagre** [uikit/uikit#3083]
### UIkit version
3.0.0-beta.35

### Browser
Android/Chrome

### Reproduction Link
https://codepen.io/jockeg/full/JMPJxY/

### Steps to reproduce
Open the codepen in an Android/Chrome browser. The sortable works. Then scroll down half of the "Lorem ipsum" text and after that sortable is broken/misaligned.

### What is Expected?
It works as expected in OSX/Chrome and OSX/Safari

### What is actually happening?
?

**Comment by joagre** [comment]
The exact same problem happens on Android/Firefox but not on OSX/Firefox.  A touch related problem that shows itself the same way on Android/Chrome and Android/Firefox then. Strange.

**Comment by PacQ** [comment]
### UIkit version

3.0.0-beta.35

### Browser
Chrome 63.0.3239.111
### Reproduction Link
https://drive.google.com/file/d/0B2pQtFQU9g_uWmR5TXdrUUxJX3M4VUUzU0FFb3lHTDVucVhJ/view

### What is actually happening?
I have a similar problem where these cards don't drop when dragging them in Chrome on Android.

**Comment by janschoenherr** [comment]
I will close this for now. If this issue persists, please comment.
