### ISSUE TITLE
BuildScript with custom Icons Font Awesome 5 Error

### ISSUE THREAD

**Issue by marcelgeratsch** [uikit/uikit#3085]
Hi There,

i have just build the uikit with a package of custom icons from fontawesome 5 pro. That worked just fine, but when i used the icons i noticed that the buildscript did not work correct. about 80% of the icons have no width and height set and a huge viewarea. That resulsts in > 400px icons. Could you adjust the buildscript so every icon has the same size? 

For example:
"500px": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\"......
"arrow-down": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\....

**Comment by dasdeck** [comment]
We thought about normalizing sizes for custom icons, though last time I did just that, with the libraries available at that time, It did not turn out to be as trivial as it sounds.

**Comment by marcelgeratsch** [comment]
Ok. i'll hope you'll mange to implement that. So for now i will replace it manually or by regex.

**Comment by dasdeck** [comment]
@marcelgeratsch Maybe I'm mistaken, but wouldn't size normalization involve checking the actual paths, which then leads to the whole relative vs. absolute thing etc.? As far as I know, adjusting the bounding box will nut suffice in many cases. If it works for you, very good!
