### ISSUE TITLE
UIKit + Video.js strange behaviour

### ISSUE THREAD

**Issue by antonsegerkvist** [uikit/uikit#3086]
### 3.0.0-beta.32
Not really a uikit bug.

There is an issue using uikit togethet with video.js version 5.x.x. The resulting issue makes the play button call pause directly on play. It also makes the volume control behave in a strange way.

### Browser
Tested on safari and chrome.

### Reproduction Link
Will try to make one once i'm off work.

**Comment by antonsegerkvist** [comment]
Here comes the link i promised: --> https://jsfiddle.net/c0249wtj/5/ <--

**Comment by antonsegerkvist** [comment]
Very well.

For my sake it does not matter since I just happened to have uikit included in the project I was working on. As long as people are aware :)

Thanks for quick feedback.
Cheers 👍

**Comment by janschoenherr** [comment]
UIkit no longer uses the `tap` event.
