### ISSUE TITLE
Off-Canvas: make closing behaviour configurable

### ISSUE THREAD

**Issue by UteV** [uikit/uikit#3088]
It would be nice to have a way to prevent the closing of off-canvas bars when clicking outside.

**Comment by janschoenherr** [comment]
If you defaultPrevent the `beforehide` event, the Offcanvas will not close.

**Comment by standby929** [comment]
I tried the above method to prevent auto closing like this:
`UIkit.util.on('#settings', 'beforehide', function() {
    event.preventDefault();
});`

But now I can't close this at all. Is there any way to close the off-canvas?

**Comment by janschoenherr** [comment]
For that you can use the _bg-close_ option. I've just updated the docs:

https://getuikit.com/docs/offcanvas#component-options

**Comment by standby929** [comment]
Thanks, in the meantime I solved it by using preventDefault on the click event, but I will keep in mind this bg-close option.
