### ISSUE TITLE
Modal event triggered by dropdown inside it

### ISSUE THREAD

**Issue by qaharmdz** [uikit/uikit#3089]
### UIkit version

3.0.0-beta.35

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/BJNYOM

### Steps to reproduce
Open console
Open modal
Hover dropdown

### What is Expected?
Modal event shouldn't be triggered

### What is actually happening?
All modal event is triggered when dropdown show and hide

**Comment by janschoenherr** [comment]
Yes, you need to check for the event target to determine what tries to show/hide itself. 

https://developer.mozilla.org/en-US/docs/Web/API/Event/target
