### ISSUE TITLE
excluding unnecessary java script files 

### ISSUE THREAD

**Issue by Alymbek** [uikit/uikit#3094]
how to exclude unnecessary javascript files while compiling?

I tried to delete unnecessary javascript files in the SRC  folder, but as a result I did not receive any correct javascript file in DIST folder.

how to exclude unnecessary components in the main core javascript file?

I use some basic components in my project, other components are redundant.
I want to delete them to reduce the size of files.

is there a manual how to properly compile javascript files?

**Comment by qaharmdz** [comment]
You can comment out unused `import` and `UIkit.use` at **src/js/uikit.js**

note: I'm not sure if excluding component can cause side effect.

**Comment by Alymbek** [comment]
@qaharmdz , thank you.
you are right!

I habitually delete the files as in the case of icons.

     so, if you want to exclude icons to reduce size of 'uikit-icons.min.js' - just delete unnessesary svg icon files from 'uikit/src/images/icons'.

     if you want to exclude some js files, use @qaharmdz's method.

**Comment by Alymbek** [comment]
after excluding components from **src/js/core/index.js**, some components working not as expected.

for example, when I exclude `video` or `gif` components my nav components is broken.

I guess, components linked in some way?
