### ISSUE TITLE
Drop nav errors

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3097]
@dasdeck @janschoenherr need help.

### UIkit version

3.0.0-WIP

### Browser

All

### Steps to reproduce

Use [this code](https://codepen.io/viocassel/pen/VymEMq) with lates 3.0.0-WIP

### What is Expected?

All works "like a boss"

### What is actually happening?

![hqudezhjq-2liuwia6-wya](https://user-images.githubusercontent.com/3341562/34337755-322af094-e973-11e7-9b26-35c65d9349d7.png)

**Comment by Alymbek** [comment]
I also confirm.

I guess it's problem from dependency component, not from uikit itself.

because I got same error after compile, but with old backups with same version is working.

**Comment by Uelii** [comment]
Same problem here. I hope they fix this asap.

**Comment by Alymbek** [comment]
I got my error when I tried remove unnecessary javascript component from uikit-core.js file like here [https://github.com/uikit/uikit/wiki/excluding-unnecessary-java-script-files](https://github.com/uikit/uikit/wiki/excluding-unnecessary-java-script-files). 

I have fixed my issue.

**Comment by janschoenherr** [comment]
I believe this has been resolved with d875a1e53b902b127aa770cb8e2d916d1e88363b. Thanks.

**Comment by viocassel** [comment]
Hi @janschoenherr 
Thanks! Yes, there are no more errors. 
But there is this...
![](https://user-images.githubusercontent.com/3341562/34503910-260791d6-f02c-11e7-9781-146a9f0d90c2.png)
