### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in null

### ISSUE THREAD

**Issue by arnvanhoutte** [uikit/uikit#3101]
### UIkit version
3.0.0-beta.35

### Steps to reproduce
Open Visual Studio and create new ASP.NET Core + Angular template. Throw out Bootstrap and install UIkit. Configure UIkit like this:
```
import * as UIkit from "uikit";
import * as Icons from "uikit/dist/js/uikit-icons.js"

(<any>UIkit).use(Icons);
(<any>UIkit).notification('Hello world.');
```
Add a uk-sticky on your page. Launch browser and open the console.

### What is Expected?
Sticky works, 0 errors in console

### What is actually happening?

For each sticky, this error appears in console

> Uncaught TypeError: Cannot use 'in' operator to search for 'length' in null
>     at insertNodes (uikit.js:837)
>     at after (uikit.js:829)
>     at Sticky.write (uikit.js:6458)
>     at uikit.js:2812
>     at runTasks (uikit.js:1594)
>     at Object.flush (uikit.js:1572)
>     at ZoneDelegate.invokeTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86798)
>     at Zone.runTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86565)
>     at ZoneTask.invokeTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86872)
>     at ZoneTask.invoke (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86861)

Similiar issues also happen when using a uk-parallax, but the error looks a bit different then.

> Uncaught TypeError: Cannot read property 'match' of undefined
>     at uikit.js:9188
>     at Array.forEach (<anonymous>)
>     at Parallax.write (uikit.js:9179)
>     at uikit.js:2812
>     at runTasks (uikit.js:1594)
>     at Object.flush (uikit.js:1572)
>     at ZoneDelegate.invokeTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86798)
>     at Zone.runTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86565)
>     at ZoneTask.invokeTask (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86872)
>     at ZoneTask.invoke (vendor.js?v=mECULoN-uRuiW6bjK3a5BA3y8IELOfsNtS9TbkJX_58:86861)

**Comment by lidiexy** [comment]
I'm having this issue, with plain project using uk-sticky alone.

**Comment by michael-alade** [comment]
I am having this same issue with `uk-sticky`

**Comment by arnvanhoutte** [comment]
In beta.39 I am getting a `this.widthElement is null` error instead

**Comment by ramiroazar** [comment]
Also getting `Cannot read property 'offsetWidth' of null` error in line **6656** of **uikit.js** with **v3.0.0-beta.39**.

**Comment by BloomBoy** [comment]
Having same issue with uk-sticky

**Comment by bbashy** [comment]
Same issues. I'm on 3.0.0-beta.39 as well.

**Comment by janschoenherr** [comment]
Could someone setup a codepen? Thanks.

**Comment by ramiroazar** [comment]
I was still getting the same error after updating to v3.0.0-beta.40. However, I was not able to reproduce this issue in CodePen. Upon further inspection, this seems to be related to issue #2519 and the suggestion by @Imperyall is working, at least in my case.

**Comment by bbashy** [comment]
So an issue with using vue.js as well?

**Comment by ramiroazar** [comment]
That's correct, this issue was a result of using `uk-sticky` within a root Vue instance. Using the `uk-sticky` attribute in combination with the [v-bind shorthand](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand) resolved the error.

**Comment by bbashy** [comment]
@ramiroazar Thanks! Changing the `uk-sticky` one to `:uk-sticky="'contents'"` works. That single change also fixed the other things not working on the page.
