### ISSUE TITLE
Modal RTL scrollbar position

### ISSUE THREAD

**Issue by leonidx86** [uikit/uikit#3114]
### UIkit version
3.0.0-beta.35

### Browser
Firefox 57 / Chromium 63 - Those browsers show scrollbar on the same side for both RTL and LTR content.
In IE11 this is not reproducable, since for RTL content the scrollbar is on the left.

### Reproduction Link
[https://codepen.io/anon/pen/MrEPxx](https://codepen.io/anon/pen/MrEPxx)

### Steps to reproduce
1. Create RTL page with `uikit-rtl.min.css` and `dir="rtl"` on `<html>`.
2. Add enough content to make vertical scrollbar appear, or just use `overflow-y: scroll;` for `<body>`.
3. Add modal component.
4. Open modal.

### What is Expected?
Content and scrollbar do not move.

### What is actually happening?
After opening the modal, the scrollbar moves to the left side, and the content "jumps" right.
This is not reproducable on IE, since it shows scrollbar on the left for RTL content. Unlike Firefox and Chrome, that show scrollbar on the right for both RTL and LTR content.

### Note
Same for dialogs.

**Comment by janschoenherr** [comment]
This seems to be fixed in Chrome, it's still an issue in FF.

**Comment by janschoenherr** [comment]
Fixed in Firefox too.
