### ISSUE TITLE
Unable to use UIkit with CSP without allowing unsafe-eval

### ISSUE THREAD

**Issue by zer0lik** [uikit/uikit#3115]
### UIkit version
3.0.0-beta.35

### Browser
Firefox 57 / Chromium 63

### Steps to reproduce
Add CSP header in web server configuration. Set script-src directive to 'self', and don't add 'unsafe-eval'.
Example nginx directive:
`add_header Content-Security-Policy "default-src 'self'; script-src 'self';";`

### What is Expected?
No CSP errors.

### What is actually happening?
UIkit library fails to load.
**Firefox error:** Source: call to eval() or related function blocked by CSP.
```
Error: call to Function() blocked by CSP
createClass
```
**Chromium error:** Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
`at new Function (<anonymous>)`

The culprit is on line 2655:
```
function createClass(name) {
    return new Function(("return function " + (classify(name)) + " (options) { this._init(options); }"))();
}
```

Adding 'unsafe-eval' to script-src fixes the issue.

If it's possible, probably better to rewrite that function in order to be able to use the library on websites with tight security settings.

**Comment by djkiwe** [comment]
Guess not?
