### ISSUE TITLE
Form disabled

### ISSUE THREAD

**Issue by RolandVerner** [uikit/uikit#3116]
All browsers do not should not submit the disabled inputs, as they are read-only.

> Attribute definitions
> 
> disabled [CI] When set for a form control, this boolean attribute disables the control for user input. When set, the disabled attribute has the following effects on an element:
> 
> Disabled controls do not receive focus.
> Disabled controls are skipped in tabbing navigation.
> Disabled controls cannot be successful.
> The following elements support the disabled attribute: BUTTON, INPUT, OPTGROUP, OPTION, SELECT, and TEXTAREA.
> 
> This attribute is inherited but local declarations override the inherited value.
> 
> How disabled elements are rendered depends on the user agent. For example, some user agents "gray out" disabled menu items, button labels, etc.
> 
> In this example, the INPUT element is disabled. Therefore, it cannot receive user input nor will its value be submitted with the form.
> 
> <INPUT disabled name="fred" value="stone">
> Note. The only way to modify dynamically the value of the disabled attribute is through a script.

[Read More](https://www.w3.org/TR/html401/interact/forms.html#disabled)

Can you add attribute readonly and do it similar to disabeled

**Comment by aarongerig** [comment]
The attributes `disabled` and `readonly` do not behave the same.
```html
<!— Disabled: The value is not editable and will not be submitted —>
<input class="uk-input" disabled>
```

```html
<!— Read only: The value is not editable, but will be submitted —>
<input class="uk-input" readonly>
```

You can add the class `uk-disabled` to the desired element and style it accordingly.

```html
<!— UIkit disabled: The same as read only, but with custom styles —>
<input class="uk-input uk-disabled" readonly>
```

Hope this helps!
