### ISSUE TITLE
Switcher function breaking on smaller screens

### ISSUE THREAD

**Issue by acollins1991** [uikit/uikit#3118]
### UIkit version

3.0.0-beta.35

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/vppJoP

### Steps to reproduce
Set up switcher with the markup from the Codepen link, and load the page under 960px width.

### What is Expected?
The switcher should change the three content areas (the image, slider number, and text) using the navigation tabs.

### What is actually happening?
The switcher isn't applying the active classes correctly, so more of the tabs are visible than should be. I've created a quick video: 

https://drive.google.com/file/d/1HUWcdWlmMkGAOG9dkqeKeuVvlUK0dbQV/view?usp=sharing

I think it could be to do with the markup being a bit more complicated.

**Comment by aarongerig** [comment]
The problem here is that the `div` surrounding the images is hidden when your viewport is smaller than `960px` (`uk-visible@m`). Once you remove that class, it works fine even on smaller screens.

Hope this helps!

**Comment by acollins1991** [comment]
Thanks @aarongerig that's done it! 

I've applied the uk-visible@m class to the individual items within the image slider component now.

Thanks!
