### ISSUE TITLE
What is px size of gutters and column for designing in 10 columns grid

### ISSUE THREAD

**Issue by Lenchezzz** [uikit/uikit#3119]
### UIkit version

3.0.0-beta.35

### Browser
Firefox 57

Hello everyone! My question is about how to start designing smartly for UIkit 3? Since it has 10 columns how to set up a new project in Sketch for example. 
I'm trying this, is this good? I would also like to know what the the PX sizes of gutters and a column?

![image](https://user-images.githubusercontent.com/15661431/34689182-a877e062-f482-11e7-93c3-2668fc8691b9.png)

**Comment by Alymbek** [comment]
I recommend you use UIkit itself, instead of different crutches.

UIkit more flexible and powerful in itself.
you can do more with original codes than using third-party tools.

Just forget about Sketch and use `less `for UIkit, because most of us use native less-file for UIkit to customise.
It's more professional.

for example, you can change size for gutters in `variables.less` file, and for collumn in `collumn.less`.
I don't know how do it in your tool.

**Comment by aarongerig** [comment]
@Alymbek Sketch and Less are not quite the same. ;) One is for compiling Less syntax to CSS and the other is for designing websites, mobile apps, etc. But your answer is helpful as well, let me explain.

## Grid

@Lenchezzz [UIkit's grid](https://getuikit.com/docs/grid) isn't based on conventional column grid. The grid works together with the [Width component](https://getuikit.com/docs/width), which allows the following widths to be combined with each other:

- `1/1 (=100%)`
- `1/2 (=50%)`
- `1/3 (~33.333%)`
- `1/4 (=25%)`
- `1/5 (=20%)`
- `1/6 (~16.667%)`
- `auto (according to content)`
- `expand (takes up the left over space)`

Those widths can be nested and therefore are not limited in any way. One level of nesting extends the column amount by times 6 (`1 level:` 6<sup>1</sup> = 6, `2 levels:` 6<sup>2</sup> = 36)

- `1st level = 6 possible columns (+ auto / expand options)`
- `2nd level = 36 possible columns (+ auto / expand options)`
- `3rd level = 216 possible columns (+ auto / expand options)`
- `and so on...`

So let's make a small example. This grid contains up to 2 sub grids (3 levels of nesting).
https://codepen.io/aarongerig/pen/zpRBjg

## Gutters

By default UIkit's grid allow five [gutter modifiers](https://getuikit.com/docs/grid#gutter-modifiers): `collapse`, `small`, `default`, `medium` and `large`. Translated to pixels, the values of those are:

**Screens wider than 1200px**
- `collapse (=0px)`
- `small (=15px)`
- `medium (=30px)`
- `default (=40px)`
- `large (=70px)`

**Screens narrower than 1200px**
- `collapse (=0px)`
- `small (=15px)`
- `medium (=30px)`
- `default (=30px)`
- `large (=40px)`

_**Note:** These gutters also apply vertically!_

## Custom gutters

As every other component in UIkit, the grid is also customizable. Like @Alymbek pointed out, those gutters above are default UIkit settings and can be adapted to your needs. Best you do that with either Less or Sass. More on that topic [here](https://getuikit.com/docs/less) and [here](https://getuikit.com/docs/sass).

Hope this brief explanation of the grid helps you! If not, let me know what else you want to know.
Cheers!

**Comment by Alymbek** [comment]
@aarongerig , thanks for examples!

I meant exactly what you can do more with original UIkit `less` or `sass` code to customise, than when using 'wrappers' over it, with limited configurations and options.

under 'wrappers' I mean any third-party template generator.

**Comment by Lenchezzz** [comment]
@aarongerig Thank you very much for your answer!
You can close the issue now.

I was thinking maybe you can add info that you pointed out for me to the docs? Or somewhere so just googling it will lead to find the needed info? Because writing here to you was my last attempt, i tried to google and tried UIkit room in Gitter, but i couldn't find the answer.
Thank you again!

Have a great day!
