### ISSUE TITLE
[Feature request] Lightbox Exclusion

### ISSUE THREAD

**Issue by pmedia** [uikit/uikit#3122]
I have an use case where I span a lightbox over a wide set of DOM elements, where not every anchor element references an image but also references to for example the source html page of the image. Think of it like an image directory.

Unfortunately, the lightbox doesn't distinguish between content types it can show (images, videos and so on), and "other" content types (like a html page) - and, totally as expected, shows up the loading indicator forever, as the content obviously couldn't be processed in any way.

But I even don't want uikit to try processing this content, wherefore I want to have a possibility to exclude anchor tags from getting inserted into the lightbox source set. This could be achived via a class name in the excluded anchor tags (like `uk-lightbox-exclude`) or via a data attribute (like `uk-lightbox="exclude"`).

### UIkit version

3.0.0-beta.36

### Browser
Google Chrome 63.0.3239.132 (64-Bit) under Ubuntu 16.04.3 LTS, but probably not browser-depending

### Reproduction Link

[Simplified example](https://codepen.io/xi-intersection/pen/GydELj)

### Steps to reproduce
Click any of the anchor tags

### What is Expected?
Only show up anchor tags in the lightbox which actually represent images

### What is actually happening?
Every anchor tag is included into the lightbox

**Comment by beloi** [comment]
You need to set the selector. From https://getuikit.com/docs/lightbox#component-options

> Toggle selector - triggers the lightbox.

`<div uk-lightbox="toggle: .js-lightbox"></div>`

https://jsfiddle.net/0yb8czqb/

**Comment by pmedia** [comment]
Whoops, thanks for pointing that out.
I actually didn't understood what that toggle thingy would do before.

In that case, issue and merge request are pointless, as this solution is way more elegant. :+1:
