### ISSUE TITLE
How to set the tooltip's container?

### ISSUE THREAD

**Issue by beloi** [uikit/uikit#3124]
Hello,

Seems like the `container` option has been removed in `v3.0.0-beta.36`?

If yes, then how can I use this with `UIkit.container` even if I'm not using the scoped version?

Thanks

**Comment by janschoenherr** [comment]
Fix in the development branch. For now you could use the UIkit.container option, by setting it programmatically

    UIkit.container = 'myselector'

or 

    UIkit.container = myElement;
