### ISSUE TITLE
uikit 3/36 The slider component does not work with ../js/uikit.min.js from the package beta36 ...

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#3126]
with 'https://getuikit.com/assets/uikit/dist/js/uikit.js' ...
this works but the slider is located in several rows ... maybe the css for slider is not the one in the delivery
... 
ps
on https://codepen.io - all ok

```
test
<div class="uk-position-relative uk-visible-toggle uk-light" uk-slider>
    <ul class="uk-slider-items uk-child-width-1-2@s uk-child-width-1-5@m uk-grid">
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
        <li><img src="https://getuikit.com/images/favicon.png" alt=""></li>
    </ul>
    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>
</div>
test
```
![default](https://user-images.githubusercontent.com/16114000/34874164-f444db98-f7a8-11e7-9d25-a6554372db77.png)

**Comment by TomS-** [comment]
Care to illiterate? If it works on CodePen then it should work for you. Also you'll find that if the bug exists in UIKit you'll also experience it in "https://getuikit.com/docs/slider" - make sure you are following the documentation correctly.

**Comment by AlexandreZaytsev** [comment]
everything according to the manual... just (I think) version js different in the installation package (beta 3.36) in the debugger (CodePen)

**Comment by AlexandreZaytsev** [comment]
ops, it seems that the Christmas holidays lasted a very long time...
...
cleared the cache
rebooted the faramework
...
all OK
