### ISSUE TITLE
getuikit.com documentation not working on iOS 9.3.5

### ISSUE THREAD

**Issue by ChrisLandowski** [uikit/uikit#3130]
### UIkit version
3.0.0-beta.36

### Browser
Safari 9.3.5

### Reproduction Link
https://getuikit.com/docs/introduction

### Steps to reproduce
Using an iPad mini running iOS 9.3.5, navigate to any of the UIkit documentation urls.

### What is Expected?
Content should appear

### What is actually happening?
The banner and side bar appear and work fine, but no content ever appears.
Other sites i've developed using UIkit run fine on iOS 9.3.5, just not the UIkit docs.

**Comment by TomS-** [comment]
Recently UIkit dropped support for iOS < 9.1, however as yours is 9.3 I believe this maybe an oversight. There are possible prefixes or JavaScript differences that haven't been accounted for.

**Comment by aarongerig** [comment]
They dropped support for Safari < 9.1, has nothing to do with iOS. Check your Safari version. 😉

**Comment by janschoenherr** [comment]
Fixed in uikit/uikit-site@636577ee2f4249213b5abc1bc136f214701c6bf3
