### ISSUE TITLE
Adding title attribute kills uk-icon usage

### ISSUE THREAD

**Issue by hyanwong** [uikit/uikit#3136]
### UIkit version

3.0.0-beta.36

### Browser
Chrome, Safari
### Reproduction Link

https://codepen.io/hyanwong/pen/BJVPLB
### Steps to reproduce
Adding a `title` attribute to a tag (e.g. an anchor) with tooltip and uk-icon set stops the uk-icon being shown. This used to work in beta.35
### What is Expected?
The specified UIkit icon should be shown
### What is actually happening?
The icon is missing. This also affects et.g if uk-icon is applied to a &lt;button&gt; tag

**Comment by beloi** [comment]
If adding an extra markup is okay with you:

`<a title="Happy" uk-tooltip="pos: bottom"><span uk-icon="icon: happy"></span></a>`

`<button class="uk-button uk-button-default" type="button" title="Happy" uk-tooltip="pos: bottom"><span uk-icon="icon: happy"></span></button>`

**Comment by hyanwong** [comment]
Indeed. But surely this should work within a single tag? Generally I try to avoid creating new tags for display purposes, and try to keep the tag structure semantic, rather than dependent on any UI requirements.

It *used* to work in the previous beta version...

**Comment by janschoenherr** [comment]
Is this resolved with beta 38?

**Comment by hyanwong** [comment]
Yes, fixed now. Thanks!
