### ISSUE TITLE
Bring the arrows to the outside of the slider 

### ISSUE THREAD

**Issue by dalenguyen** [uikit/uikit#3141]
It's great the UiKit updates the slider in version 36. I wonder if we can bring the arrow from inside of the uk-slider to the outside? 

https://getuikit.com/assets/uikit/tests/slider.html

![image](https://user-images.githubusercontent.com/14116156/34957896-8f8b90c8-f9fd-11e7-8313-09dd91827a4f.png)

Thanks,

**Comment by saschadube** [comment]
It will be included in the next release. See d175d1c04aba3f5b8f6bdec705bb8c7bf1d5098e

Docs will also be updated.
