### ISSUE TITLE
uk-tooltip empty when loading vue last

### ISSUE THREAD

**Issue by HDsign** [uikit/uikit#3151]
### UIkit version
3.0.0-beta.38

### Browser
Chrome,Firefox,Safari

### Reproduction Link
http://jsbin.com/kojopu/1/edit?html,output

### What is Expected?
The title should be displayed by the tooltip component

### What is actually happening?
The tooltip title disappears when instantiating vue later then UIkit.
When loading UIkit in the lowest part of the body the whole layout glitches because of some missing calculations within UIKit. For example when using the `uk-height` attribute.

**Comment by janschoenherr** [comment]
That is the same issue as with the icons. UIkit is manipulating the DOM (removing the _title_ attribute) prior to Vue reading its template from the DOM. If you prepend the title with a colon you should be fine.

    :title="mytitlte"

**Comment by janschoenherr** [comment]
Please try 

    uk-tooltip="title: my title text"

**Comment by HDsign** [comment]
Thank you. That does the trick!
