### ISSUE TITLE
Can I replace the icons in the accordion? 

### ISSUE THREAD

**Issue by dalenguyen** [uikit/uikit#3152]
Hi, The default accordion use + and - for open and close the accordion. Can I replace that with something else like arrow up and down? 

![image](https://user-images.githubusercontent.com/14116156/35118058-a26b5652-fc5e-11e7-927e-ed84827ec1b2.png)

https://getuikit.com/docs/accordion

Thanks,

**Comment by aarongerig** [comment]
Yes you can: https://github.com/uikit/uikit/blob/develop/src/less/theme/accordion.less#L15-L16

**Comment by dalenguyen** [comment]
@aarongerig Thanks for giving me the ideas. I am afraid that it could be lost when I update UiKit to next version. So did better version by using CSS. It also works.

`.uk-accordion-title:after{
            background-image: url('../../bower_components/uikit/src/images/icons/chevron-down.svg');
          }
          .uk-open{
            .uk-accordion-title:after{
              background-image: url('../../bower_components/uikit/src/images/icons/chevron-up.svg');
            }
          }`

**Comment by pioneersingh321** [comment]
hi you can use something like this .. hope its will be help full to someone 

.uk-accordion li.uk-open .uk-accordion-title:before {  
    /* up arrow icon */  
    content: url('data:image/svg+xml; utf8, <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ><path d="M4 12C4 11.4477 4.44772 11 5 11H19C19.5523 11 20 11.4477 20 12C20 12.5523 19.5523 13 19 13H5C4.44772 13 4 12.5523 4 12Z" fill="currentColor" /></svg>');
 }

 .uk-accordion li .uk-accordion-title:before{
  content: url('data:image/svg+xml; utf8, <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ><path d="M12 4C11.4477 4 11 4.44772 11 5V11H5C4.44772 11 4 11.4477 4 12C4 12.5523 4.44772 13 5 13H11V19C11 19.5523 11.4477 20 12 20C12.5523 20 13 19.5523 13 19V13H19C19.5523 13 20 12.5523 20 12C20 11.4477 19.5523 11 19 11H13V5C13 4.44772 12.5523 4 12 4Z" fill="currentColor"/></svg>');
 }

and for the svg  
https://css.gg/app

you can find signal svg code
