### ISSUE TITLE
Download link for latest v2 is broken

### ISSUE THREAD

**Issue by m0yP** [uikit/uikit#3156]
### UIkit version
2.27.5

### Browser
N/A

### Reproduction Link
Uikit v2 [website](https://getuikit.com/v2/)

### Steps to reproduce
Link in v2 website points [here](https://github.com/uikit/uikit/releases/download/v2.27.5-src/uikit-2.27.5.zip) when should be pointing [here](https://github.com/uikit/uikit/archive/2.27.5.zip) or some other file.

### What is Expected?
v2.27.5 zip file

### What is actually happening?
404 error

**Comment by saschadube** [comment]
Thanks! It's fixed now.
