### ISSUE TITLE
Icons not showing up - beta 38

### ISSUE THREAD

**Issue by CoderJason123** [uikit/uikit#3158]
### UIkit version

3.0.0-beta.38

### Browser
chrome
### Steps to reproduce
 span data-uk-icon="icon: arrow-down"
### What is Expected?
visible icon
### What is actually happening?
For the life of me i can not get the icons to show up.  I've also included the icon js file directly in my resulting html page.

I am using the data-uk-* syntax.  All of the other components show, but an icon is not.  I've spent a few hours on it, trouble is -- getting together a code pen is not ideal.  I've tried different icons to the same effect.  any suggestions?  i realize i am not giving too many details but all the pieces appear to be there.

**Comment by CoderJason123** [comment]
I have not received a reply to this.  I have a bit more detail to present.  In a new project without REACTjs and typescript, i can get the icons to show.  I am not using babel, but feel like i'm the only person who is not.  Just regular typescript and web pack.  

in web pack i've even tried to add a pointed to the icons js file.  does this mean the icons js is not a module and thus not recognized by typescript?  is there a typescript solution i can use?  require does not seem to work.  There is probably some simple solution but i'm about to give up.

**Comment by davidlb** [comment]
Have a look to the solution provided in #3127

**Comment by CoderJason123** [comment]
Thanks for the response.  I am not using requirejs but found a link to migrating requirejs to web pack, which used an alias.  I tried that to no avail.  What is it that is different about the icons that requires special treatment ?  maybe if i understood that i'd know what to do.  is it because they are packaged under the uikit node module as a sub item?

**Comment by CoderJason123** [comment]
The issue has been resolved.  I've converted everything to babel.  The final solution was to make sure i called UIkit.use(Icons);.  It's kind of a subtle point in the docs and seems kind of odd.  Would love an explanation of what is going on if someone can provide.  Appreciated.

**Comment by pakanyizi** [comment]
I cant get my icons to show.. kindly assist on how to?

**Comment by IvanMladenov** [comment]
Change the order of scripts!
