### ISSUE TITLE
Scrollspy considers top = 0 in viewport

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3163]
### UIkit version

3.0.0-beta.38

### Browser
Chrome

### Steps to reproduce
Create a div at 100vh
Animate the div after it
The div will animate straight away even though it isn't inview

### What is Expected?
The div should animate when it comes in view

### What is actually happening?
If the top of the element meets the viewport height it's considered inview, however it should be less than the viewport height.

**Comment by janschoenherr** [comment]
As a workaround, you can use:

    uk-scrollspy="offset-top: -1"

**Comment by janschoenherr** [comment]
I believe this issue is resolved. Please comment if the issue persists.
