### ISSUE TITLE
[Feature Request] Progress Pie Component

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#3164]
Thanks for such a great framework. Can you please add Progress Pie component? Please look here for example of progress pie: https://bdthemes.net/demo/wordpress/element-pack/elements/progress-pie/

### What is Expected?
https://bdthemes.net/demo/wordpress/element-pack/elements/progress-pie/

**Comment by saschadube** [comment]
Thanks for you suggestion! Progress pies have a very low priority for us at the moment. May be some else can step in and create one?
