### ISSUE TITLE
[Feature Request] Disabled Drag on slider and slideshow elements

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3169]
drag: false; would be good, meanwhile I'm setting pointer-events: false. I have a block which is a link in which products fade behind using slideshow. If you accidentally drag, it glitches the slideshow element. However drag isn't needed in this instance.

**Comment by wesimy** [comment]
any update on this ?

**Comment by johnpitchers** [comment]
I'm nesting small image galleries using slideshows in sliders. Dragging is causing issues because it affects both elements. The ability to turn off dragging on one element would be perfect.

**Comment by TomS-** [comment]
This is such an easy thing to implement. I have no idea why the YooTheme team aren't doing anything about it. I'm just going to do a PR so those who need this functionality can have it.

**Comment by TomS-** [comment]
@johnpitchers use my PR and you can use uk-slideshow="draggable: false" if you don't know how to compile, here is the compiled version: https://github.com/TomS-/uikit/blob/develop/dist/js/uikit.min.js

**Comment by Blinks44** [comment]
If i use npm package, how to disable dragging in slideshow?

**Comment by TomS-** [comment]
@Blinks44 if you don't need to interact with the slideshow at all you can use CSS pointer-events: none on the slider. Otherwise use my code change. No idea why my push request hasn't been looked at.

**Comment by janschoenherr** [comment]
Thanks, this is available in 3.0.0-dev.e02d1d6 now.
