### ISSUE TITLE
Tooltip disappear quickly when attached to SVG

### ISSUE THREAD

**Issue by ajrdesign** [uikit/uikit#3172]
### UIkit version

3.0.0-beta.38

### Browser
Chrome, Safari, Firefox
### Reproduction Link

https://codepen.io/ajrdesign/pen/KZYJed

### Steps to reproduce
Hover over text element in Codepen, see expected behavior of tooltip.

Hover over SVG element in Codepen and see unexpected behavior.

### What is Expected?
Tooltip should remain until mouse leaves the element

### What is actually happening?
Tooltip is appearing briefly and then disappearing before mouse leaves element.

**Comment by christianparker1** [comment]
did you ever fix this?

**Comment by janschoenherr** [comment]
Yes, it was fixed with b7bc40f
