### ISSUE TITLE
Range on slider results in sliding

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#3174]
### UIkit version

3.0.0-beta.38

### Browser
Chrome Version 63.0.3239.132 (32-Bit)
FireFox Version 56.0b1 (64-Bit) Developer Edition

### Reproduction Link

https://codepen.io/anon/pen/mpYVPr

### Steps to reproduce
Click with the mouse on the range button and move to the left or the right

### What is Expected?
Change the value of the range input element

### What is actually happening?
The slider slides

**Comment by aaronpeterson** [comment]
Ran into this same thing.  Anyone have any ideas?

**Comment by ikabod** [comment]
I use this workaround until it is fixed:

uikit.js:

replace
`var SliderDrag = {
        data: {
            threshold: 10,
            preventCatch: false
        },`

with
`var SliderDrag = {
        data: {
            threshold: 10,
            preventCatch: true
        },`


uikit.min.js:

replace
`{data:{threshold:10,preventCatch:!1}`

with
`{data:{threshold:10,preventCatch:1}`

**Comment by ikabod** [comment]
You are welcome
