### ISSUE TITLE
Suggestion: Index property for switcher too

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#3176]
### UIkit version

3.0.0-beta.38

### Browser
Google Chrome Version 63.0.3239.132 (Offizieller Build) (32-Bit)

### Reproduction Link

https://codepen.io/anon/pen/goNMVp

### Steps to reproduce
Open the link above

### What is Expected?
Set the index of the switcher to open an ui with the last selected item

### What is actually happening?
You have to use the show method to achieve this which runs the defined animation.

Same wise versa: Currently it is not possible to read and save the active index and save it for the next opening.

For the slideshow you can set and read the index property. Please add this to the switcher too.

**Comment by janschoenherr** [comment]
There is a method `index` on the Switcher component.

In your example: 

     UIkit.switcher(switcher).index()
