### ISSUE TITLE
No uk-width for *Sixths*

### ISSUE THREAD

**Issue by spleanter** [uikit/uikit#3177]
### UIkit version
3.0.0-beta.38
### Browser
any
### Reproduction Link
uikit.css
### What is Expected?
from 6507
`/* Sixths */
.uk-width-1-6 {
  width: calc(100% * 1 / 6.001);
}
.uk-width-5-6 {
  width: calc(100% * 5 / 6.001);
}`

### What is actually happening?
no .uk-width-2-6 to .uk-width-4-6

**Comment by TomS-** [comment]
This is because you use .uk-width-1-3 and .uk-width-2-3. It's all about minimising the CSS used.
