### ISSUE TITLE
'Sticky on scroll up' are disappearing when scroll is finished in IE 11.

### ISSUE THREAD

**Issue by thesergeev** [uikit/uikit#3179]
### UIkit version

3.0.0-beta.38

### Browser
Internet Explorer 11

### Reproduction Link

https://getuikit.com/assets/uikit/tests/sticky.html
https://getuikit.com/docs/sticky#sticky-on-scroll-up

### Steps to reproduce
Open links above in IE 11.
Scroll page down and after scroll page up.

### What is Expected?
'Sticky on scroll up' should be visible until page scroll down.

### What is actually happening?
While you scroll page up – sticky navbar is appear, but when scroll is finished it disappear momentarily.

**Comment by janschoenherr** [comment]
This issue seems to be resolved. If the issue persists, please comment.
