### ISSUE TITLE
Animated dropdown - wrong starting position

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3180]
### UIkit version

3.0.0-beta.38

### Browser
Any

### Reproduction Link

https://codepen.io/qdev/pen/aqbbGB

### Steps to reproduce
Hover on the button

### What is Expected?
Dropdown to appear animated (from bottom) until it's final position under the button

### What is actually happening?
Dropdown goes first very high up and then back down to it's normal position

I see that the top position of the dropdown is first calculated wrong and then corrected
Maybe the starting point of the animation is calculated wrong

This is happening also on `uk-animation-slide-bottom-small` only the flicker is smaller but still visible

**Comment by zzseba78** [comment]
Working fine with latest versions, check this:
https://codepen.io/zzseba78/pen/XZWxrE

**Comment by razvanioan** [comment]
@zzseba78 You've used beta35 in your pen, the latest is beta38

I know it was working fine in beta35, I suspect the bug was introduced in the latest changes of the position calculation module

**Comment by zzseba78** [comment]
Your are right, it´s not working fine on beta38.
