### ISSUE TITLE
Tooltip not copied 

### ISSUE THREAD

**Issue by nodarai** [uikit/uikit#3181]
When copying element (for example with jquery's *clone()*) with attribute *uk-tooltip* and *title="Title"* 
newly created element have an empty title.

### UIkit version

Tested on:
3.0.0-beta.38
3.0.0-beta.31

### Browser
Chrome 63, Firefox 37

### Reproduction Link
[https://codepen.io/anon/pen/OQJjgK](https://codepen.io/anon/pen/OQJjgK)

### Steps to reproduce
Copy element with *uk-tooltip* attribute.
For example, if we have two tables with ids *table1* and *table2* and *table1* have *thead* which contains 2 *th* with *uk-tooltip* attributes each.
When we copy the *'table1 > thead'* to *'table2 > thead'*  then the copied *th* has an empty title.

### What is Expected?
The correct tooltip for new elements.
*title="Title"* and *title="Second Title"*

### What is actually happening?
*title=""* in both cases

**Comment by janschoenherr** [comment]
Please initialize you component like this:

    uk-tooltip="title: Hello World"
