### ISSUE TITLE
Inview Video - Should the video keep autoplay if the user already paused it?

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3182]
### UIkit version

3.0.0-beta.38

### Reproduction Link
http://research.byhumans.works/video.html

### Steps to reproduce
Scroll down, the video autoplays, perfect. Pause it, and keep scrolling.
### What is Expected?
The video should remains in pause, the user's interaction should be taken into account.
### What is actually happening?
The video re-start if you keep scrolling, the user's interaction should be taken into account, also if the video has sound it can be **very annoying**, if the user paused the video this action should be respected.
So, it would be great to have an option to specify if the video autoplay even if the user paused it.

**Comment by Ethan-Newthink** [comment]
This is still an issue on 3.0.3..

**Comment by fire2** [comment]
Over 2,5 years later this is still an issue :(
