### ISSUE TITLE
no .uk-width-2-4  in 3.0.0-beta.38

### ISSUE THREAD

**Issue by yolinekz** [uikit/uikit#3183]
UIkit version
3.0.0-beta.38

Browser
any

Reproduction Link
uikit.min.css

Steps to reproduce
```
<div uk-grid>
	<div class="uk-width-1-4">1</div>
	<div class="uk-width-2-4">2</div>
	<div class="uk-width-1-4">3</div>
</div>
```

What is Expected?
1 row and 3 column

What is actually happening?
3 row
First 25%
Second 100%
Third 25%
no .uk-width-2-4

**Comment by zzseba78** [comment]
UIkit 3 removed redundant sizes, instead of `uk-width-2-4` use `uk-width-1-2`
