### ISSUE TITLE
Vue + Uikit and use model dialog with v-bind, model dialog can't show

### ISSUE THREAD

**Issue by netflixfans** [uikit/uikit#3186]
### UIkit version

3.0.0-beta.38 + Vue2.x

### Browser
Chrome
### Steps to reproduce
below is the code I write:

```
<a v-bind:href="g.gold_type == 0 ? '/detail/' + g.id : '#' + g.id">  
                      
                        </a>

                        <div v-bind:id="g.id" class="uk-flex-top" uk-modal>

                            <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">

                                <button class="uk-modal-close-default" type="button" uk-close></button>

                                <p>{{ g.id }}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
                                    in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                                    cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                            </div>
                        </div>

```
### What is Expected?
click a element, dialog g.id should display

### What is actually happening?
click a element, dialog g.id is not displayed

**Comment by fazykn** [comment]
#UIkit modal component not working if created using Vuejs Template literal Component!
same kind of problem with me.
Trying to solve it but no solution working. 

Modal code of UIkit works fine without Vuejs
but within Vuejs, it doesn't show up on click of a button!

**Comment by sebastiandittrich** [comment]
I have the same issue, the problem is that UIkit appends the pure html-code from the uk-modal to the body of the page which is not inside the vue.js container. So the Vue instance can't insert the value of g.id and intstead of a value there will be displayed`{{ g.id }}`

**Comment by janschoenherr** [comment]
If you don't want UIkit to append the modal to the body of the document, set the Modal's container option to _false_

**Comment by koreal6803** [comment]
A workaround method is to bind a toggle variable `open` to control the modal(s):
`
<button @click="open=true">click to open</button>
<div :class="{'uk-open':open, 'uk-modal':true}" :style="open ? 'display: block;':''" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title">Headline</h2>
        <p>test</p>
        <p class="uk-text-right">
            <button class="uk-button uk-button-default uk-modal-close" @click="open=false" type="button">Cancel</button>
            <button class="uk-button uk-button-primary" type="button">Save</button>
        </p>
    </div>
</div>
`
