### ISSUE TITLE
Code best practices and style guides improvements

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#3187]
My request here is to help developers to read, understand and work better on the UIkit js code. I have seen huge improvements over the time, but there is plenty of room for improvement.

Instead of just pointing them out, I would like to start with a simple one and offer a solution. If of a like and implemented I could iterate with the next one.

# Stronger var rules

One of the most important ES6 features is the introduction of `const` and `let` variables and yet, none of those are used in UIkit, not even when refactoring. Perhaps is simple fear of breaking something or not knowing when to use them, or why.

There a many reasons why, but mostly to avoid those tricky to find bugs when a variable get out of the intended scope. When using `var` is like using globals and thanks to ES6 we don't have to. As a simple rule ALWAYS use `const` (even for object and arrays that are being edited), replace by `let` only when the variable must be reassigned (for example in loops), and forget about `var` or almost (there could be edge situations where it is useful but is rare).

Beside using ES6 vars, there is one related code style that is really annoying. I will point out an example.

```js
// quick, tell me the amount of declared variables
var placeholder = this.placeholder,
    outerHeight = (this.isActive ? placeholder : this.$el).offsetHeight, el;

// 2? wrong, there are 3

// now tell again
var el
var placeholder = this.placeholder
var outerHeight = (this.isActive ? placeholder : this.$el).offsetHeight

// better, right? even better using ES6 vars
let el
const placeholder = this.placeholder
const outerHeight = (this.isActive ? placeholder : this.$el).offsetHeight
```

This particular code was extracted from Sticky [source](https://github.com/uikit/uikit/blob/develop/src/js/core/sticky.js#L131-L132) but it's all over the place. I would like to open a PR with a new lint rule enforcing the one-var per line and replacing the vars with ES6 vars. It's not a simple work, but I believe it's the first step toward a better code for everyone.

Before doing that, I must know your thoughts on the matter.

**Comment by TomS-** [comment]
ES6 let and const are not full supported by slightly older browsers yet. It would mean bumping the Safari/iOS to 10+. There are many people reluctant to update their OS due to performance issues. Why browsers that update when the OS is updates exist is beyond me. Safari and IE should be dead.

iOS 9 is still at 10% of iPhone users.

Also shouldn't it be
```
var el;
var placeholder = this.placeholder;
var outerHeight = (this.isActive ? placeholder : this.$el).offsetHeight;
```

I agree there should be a move to let and const, but I'm not sure if now is the time.

**Comment by miljan-aleksic** [comment]
@TomS-, ES6 code is compiled to ES5 on build, so there is nothing to worry about that or the missing commas ;)

**Comment by janschoenherr** [comment]
Good call Miljan, we'll probably abide to these rules:

https://github.com/airbnb/javascript#variables

**Comment by TomS-** [comment]
@miljan-aleksic apologies, didn't know that was the case. Yup, I'm all for this change to.

**Comment by miljan-aleksic** [comment]
@janschoenherr, awesome!

**Comment by janschoenherr** [comment]
That was fun 7fc1e52328f318a9dd13e56a51f952615c47d075 :stuck_out_tongue_closed_eyes:

**Comment by TomS-** [comment]
@janschoenherr Amazing, I would say that only answers 1/2 though. 

There is still:
```
let fs = require('fs'),
     exec = require('child_process').exec,
     path = require('path'),
     util = require('./util'),
     glob = require('glob');
```

Which doesn't follow the airbnb guidelines (https://github.com/airbnb/javascript#variables)
```
let fs = require('fs');
let exec = require('child_process').exec;
let path = require('path');
let util = require('./util');
let glob = require('glob');
```
