### ISSUE TITLE
Tab - Switcher - Dropdown: prevent switiching

### ISSUE THREAD

**Issue by f-r3d** [uikit/uikit#3188]
Hi' all,
I've a problem to prevent switch using dropdown, when clicking on "tab 3" it opens the dropdown menu but at the same time it switches to an element that doesn't exist.

I'm using the new 3 beta version.

It would be useful a solution without javascript, I'm thinking about an attribute that could prevent the switch option.

This is my code:
```
<ul uk-tab uk-switcher="animation: uk-animation-slide-left-medium, uk-animation-slide-right-edium">
   <li class="uk-active"><a href="#">tab 1</a></li>
   <li><a href="#">tab 2</a></li>
   <li>
   <a href="#">tab 3 <span class="uk-margin-small-left" uk-icon="icon: triangle-down"></span></a>
   <div uk-dropdown="mode: click">
     <ul class="uk-nav uk-dropdown-nav">
     <li><a href="#">Sub 1</a></li>
     <li><a href="#">Sub 2</a></li>
     </ul>
   </div>
   </li>
   </ul>
 
   <ul id="data" class="uk-switcher uk-flex-wrap-stretch uk-width-1-1">
     <li>
       <div class="uk-margin">
       <h1>tit</h1>
       <p>text</p>
       </div>
     </li>
     <li>Hello again!</li>
   </ul>
``` 

UPDATE 1:
It seems that "toggle" param doesn't work in the default settings

UPDATE 2:
Using this:
```
UIkit.switcher('.uk-tab', {
  connect: '#data',
  toggle: '> li:not(.noswitch)',
});
``` 
or using inline:
```
uk-switcher="toggle: >li:not(.noswitch)
``` 
and adding the class "noswitch" to the element i don't want to switch it seems working, but the default settings ha already the problem

Thanks

**Comment by janschoenherr** [comment]
Yes, you'll have to use the custom `toggle`.
