### ISSUE TITLE
scrollspy: won't initialise if UIkit loaded async & animation missing on programmatic use

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3191]
### UIkit version

3.0.0-beta.39

### Browser
* Safari 11
* Firefox 58

### Reproduction Link
https://codepen.io/qdev/pen/aqvRvw

### Steps to reproduce
* __Bug 1:__ Nothing ! The `scrollspy` elements should start animating without scroll
* Click (close) the first __notification__ in order to manually / programmatic initialise of `scrollspy`

### What is Expected?
* __Bug 1:__ To automatically animate elements in the view without scroll (on top of page) after async loading of the framework
* __Bug 2:__ It should show elements using the specified animation

### What is actually happening?
* __Bug 1:__ `scrollspy` it's not starting to show elements immediately (without scroll) if the framework is loaded async
* __Bug 2:__ the animation parameter is not taken into effect when `scrollspy` is initialised manually / programmatic

For __Bug 2__ I see that for each element it's adding as `animation class` only __n<sup>th</sup>__ character from the `cls` parameter, where `n` is the position of the element in the `target` list !

Until these will get fixed, I will just use fake scroll on UIkit loaded event (not very elegant, but effective):

```javascript
window.scrollTo(0,1);
window.scrollTo(0,0);
```

**Comment by csaggo** [comment]
@janschoenherr i am seeing this behaviour again in firefox 78. when there is no scrolling or other interaction, the scrollspy animations wont fire i.e. the content stays invisible

**Comment by janschoenherr** [comment]
The above example works for me in Firefox 78. Please open a separate issue with a codepen. Thanks.

**Comment by csaggo** [comment]
HI @janschoenherr thank you for your reply.
it seems to be a broader issue with initialization on ff. Probably just me doing something wrong.
On FF i have issues with uk-cover, height-mathching grids, sliders with ratio and so on. 

I do load uikit.min.js with defer which should be fine i suppose. I have a live-page where we are seeing this behaviour.
https://escapediem.de
if i navigate around to escaperooms the grid with the images is not in line for example (the first image is a little above the others). same for the image-grid on room-details. if i reload the page it goes away. its also not happening everytime.
not having this issue on chrome and safari. not sure what i am doing wrong :-(
is there a way to force-initialize through js ? i would do that on load then?
