### ISSUE TITLE
uk-height-viewport with .uk-overflow-auto fails

### ISSUE THREAD

**Issue by networkimprov** [uikit/uikit#3196]
### UIkit version
3.0.0-beta.39

### Browser
Firefox 57

### Steps to reproduce
    Preceding content
    <div uk-height-viewport="offset-top:true; offset-bottom:true" class="uk-overflow-auto">
          <div class="uk-text-break">Scrolling content (must exceed viewport height)</div>
          ...
    </div>
    Following content

### Workaround
    <style>.firefox-minheight-fix {height:0}</style>
    ...class="uk-overflow-auto firefox-minheight-fix"

### What is Expected?
Scrollbar appears for scrolling content when it exceeds the viewport.

### What is actually happening?
No scrollbar appears unless the workaround is applied. This seems like a bug in Firefox.

**Comment by janschoenherr** [comment]
For uk-overflow-auto to work outside of a Modal component, you'll have to specify `selContainer` and `selContent` selectors.

**Comment by networkimprov** [comment]
The issue isn't uk-overflow-auto or overflow:auto.

It's that uk-height-viewport requires height:0 in order for overflow:;auto to work.

**Comment by janschoenherr** [comment]
Yes, the Height Viewport component only sets a min-height. It does not force the exact height, but rather allows the element to grow.

**Comment by networkimprov** [comment]
That's not the issue either.

Did you try the code I provided to reproduce the problem?
