### ISSUE TITLE
uk-slidenav-previous uk-slidenav-next not working in Meteor/React. Importing UIKit Components in 3.0 Beta

### ISSUE THREAD

**Issue by brahmaforces** [uikit/uikit#3197]
Hello All:

I am using UIKit 3.0 Beta with Meteor/React. While everything seems to be working allright, the slidenavs are just not showing. uk-slidenav-previous, uk-slidenav-next classes do appear if I inspect, in the browser but the icons are not showing. I have not imported these components, is this necessary, given the node install? Further I dont see these in the dist directory. Another issue could be that in meteor I am putting all images in /public/ from where they are accessible. It could be that the icons for previous next are not accessible.

In any case, what is the correct way to use this in Meteor, or a node install with React.

This is a simple component, it should work. Online I have found no documentation as to whether components are to be imported in 3.0 I know they had to be imported in the 2 version. However in a node install it is not clear whether this is necessary and if it is then where are they to be imported from, or is it the image accessiblity issue. There should be a standard way to do UIKit in React/Meteor.

Any help would be appreciated. By the way there is no response on Gitter and no documentation on how to integrate UIkit 3 with React online, have searched extensively.

**Comment by zzseba78** [comment]
Did you check this? https://getuikit.com/docs/javascript#component-usage

> Note React will work with data-uk-* prefixes only.

So try `data-uk-slidenav-previous`

**Comment by brahmaforces** [comment]
I was already using the data prefix. I solved the problem as follows. The code shown in UIkit is as follows 

`<a href="" uk-slidenav-next></a>`

The above even with the data prefix does not work in React. However when I inspect the element in the UIkit website its self, the following code appears. 

`<a href="#" uk-slidenav-next="" class="uk-slidenav-next uk-icon uk-slidenav"></a>`

The above has the an extra 2 classes uk-icon and uk-slidenav, when these are included the slidenav icon appears in React. 

I have used the code that appeared in the inspect to make the sidenav appear in a Meteor/React situation, but still the question remains as to why the code shown in the Uikit page for slidenav 

https://getuikit.com/docs/slidenav

does not work out of the box and why inspecting it yields extra classes which when supplied to React work.

**Comment by janschoenherr** [comment]
Please add a codepen with your setup, so that we can inspect the issue

**Comment by Kesholabs** [comment]
How does one integrate UIkit with react. The slider doesn't work .. i have spent  hours researching. Anyone know how to use UIKit with create-react-app?

**Comment by zzseba78** [comment]
Did you try using `data-uk-slider` instead of `uk-slider`?

**Comment by mturnbo** [comment]
I'm unable to get the nav icons to show up in a React component as well.  Using `data-uk-slidenav-next` and `data-uk-slider-item="next"`.  Even manually adding `uk-slidenav-next uk-icon uk-slidenav` to the className doesn't work.

**Comment by zzseba78** [comment]
@mturnbo Can you create a codepen to see your code in action?

**Comment by ahmedfouzan** [comment]
I'm facing similar issue with pagination in React. Icons do not show up even with `data-uk-pagination-next` and `data-uk-pagination-previous`.

https://codepen.io/ahmedfouzan/pen/gJWQmB

**Comment by janschoenherr** [comment]
@ahmedfouzan Thanks for the codepen. In this case you are currently using:

    { "data-uk-pagination-previous": true }

This tells UIkit to use the Icon `true`. That obviously makes no sense, we'll fix this with the next release. For now you can use:

    { "data-uk-pagination-previous":'' }

That solves the issue.
