### ISSUE TITLE
[Beta 39] Bug Slider center mode

### ISSUE THREAD

**Issue by carlos-duran** [uikit/uikit#3198]
### UIkit version

3.0.0-beta.39

### Browser
Chrome 64

### Reproduction Link

Here a video (8 seconds)
https://drive.google.com/open?id=1abNik1Jz64MtaLsCvXXpGUnkR0SY808t

### Steps to reproduce
Open link https://getuikit.com/docs/slider#content-transitions
Refresh and play
Edit: It happens in all examples using center mode.

### What is Expected?
Starting correctly

### What is actually happening?
Shows the incorrect slide

**Comment by TomS-** [comment]
Yup, I noticed this too.
