### ISSUE TITLE
Modal issue with dynamic content

### ISSUE THREAD

**Issue by szoto** [uikit/uikit#3199]
### UIkit version

3.0.0-beta.39

### Browser
I think all

### Steps to reproduce
I use a dynamic container, that i fill with dynamic data (page), sometimes with the same modal.

### What is actually happening?
The modals always moved from original container to body container.
The next time, when the earlier used modal appear again in the dynamic content, i got a non-unique id error message.

The body container will be full with never used, same id's modals.

After i deleted these lines, the issue gone:
from 3847:
```
if (this.container && this.$el.parentNode !== this.container) {
                append(this.container, this.$el);
                this._callConnected();
            }
```

Can you fix it in the next version?

Thanks

**Comment by janschoenherr** [comment]
If you want the modal to remain in place, you can simply set _container: false_

    uk-modal="container: false"

**Comment by szoto** [comment]
It's great!!
Thanks!
