### ISSUE TITLE
Strange behavior of the Sticky component when its width (or its container width) changes through JavaScript.

### ISSUE THREAD

**Issue by m-ahmadi** [uikit/uikit#3200]
Here's the thing:
There's a sticky sidebar and a sticky nav.
The width of the sticky sidebar (the width of its parent) toggles between two width sizes when the menu button in the nav is clicked.

Everything is fine. (If you don't scroll down)
When you scroll down and you reach the offset that sticky becomes active, the width of the sticky that was set previously is in effect and not the latest width that was set via JavaScript.

In order to update the sticky width you have to resize the window manually (by hand) and then again everything becomes fine.

Everything explained above is in the following pen:
https://codepen.io/mohammad-ahmadi/pen/XVOjMd

Then I tried just to change the width of the sticky in simpler way and that did not work as well,
In the following pen I tried to just change the width of the sticky when a button is clicked:
https://codepen.io/mohammad-ahmadi/pen/rpPMyx

Consider that I'm not entirely sure that this is a bug or not. so I posted in the Gitter, but since I got no response, I decided to try it here.

### UIkit version
3.0.0-beta.39

### Browser
Chrome Latest, FF Latest

### Steps to reproduce
Go to this pen: https://codepen.io/mohammad-ahmadi/pen/rpPMyx
Click the button.
Clicking the button changes the sticky width, but you have to resize the window manually to see it.

### What is Expected?
Width of the sticky get's updated without resizing the window by hand.

### What is actually happening?
Width of the sticky does not get updated until you resize the window by hand. `$(window).resize()` also does not make any differences.

**Comment by TomS-** [comment]
https://codepen.io/anon/pen/mXEbjK You should be able to re-instance the sticky component, however, I've tried every single component update and that hasn't worked. The only thing that has is completely re-instancing UIkit. 

I think there may be a bug in the actual component update.

**Comment by janschoenherr** [comment]
UIkit does not react to attribute changes. As TomS pointed out, you can call `UIkit.update()` after changing the classes.
