### ISSUE TITLE
.uk-width-2-4 is full width

### ISSUE THREAD

**Issue by acollins1991** [uikit/uikit#3201]
### UIkit version

3.0.0-beta.39

### Browser
Chrome

### Reproduction Link

https://codepen.io/anon/pen/vdKYqB

### Steps to reproduce
Install UIKit and setup a grid, one 2-4 column and two 1-4 columns.

### What is Expected?
The 2-4 column should only take up 2 quarters of the space.

### What is actually happening?
The 2-4 column is taking up 100% of the grid, pushing the other columns onto the next line. The uk-first-column class is also being applied to the second column as well as the first.

**Comment by m-ahmadi** [comment]
AFAIK, in https://getuikit.com/docs/width says:

> We remove redundancy into each set of unit classes, so that for instance instead of .uk-width-3-6 you should use .uk-width-1-2.

So there is no `uk-width-2-4` anymore.

**Comment by aarongerig** [comment]
@acollins1991 It's exactly how @m-ahmadi described it. Instead of `uk-width-2-4` you'd have to use `uk-width-1-2`, because mathematically `2/4` is the same as `1/2`.

Closing this as it should be clear from here on.
