### ISSUE TITLE
Dropdown in Navbar not working in 3.0.0-beta.39 WIP

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3202]
### UIkit version

3.0.0-beta.39 WIP

### Browser
All

### Reproduction Link

http://localhost:8080/tests/navbar.html

### Steps to reproduce
Run `npm run test`
Hover to a menu item with dropdown in Navbar.

### What is Expected?
Dropdown in Navbar works just as it should work.

### What is actually happening?
Dropdown in Navbar not working.

**Comment by TomS-** [comment]
Your link is to localhost, will you be able to put it on CodePen? localhost is a host local to you (not online).

**Comment by mightyvoodoo** [comment]
Confirm, reproducable on "develop" branch. Issue appeared after beta 39 at WIP section.

**Comment by janschoenherr** [comment]
Has been resolved this morning. Thanks.

**Comment by viocassel** [comment]
Thanks @janschoenherr !

**Comment by Tinypadfoot** [comment]
I am new to both Django and UIKit, and to coding in general. The dropdown isn't working for me, same issue as above. I have the latest version, 3 Beta 47. Is there another bug? Could you point me to discussions with possible fixes? Thanks!
