### ISSUE TITLE
Open a link from within a lightbox

### ISSUE THREAD

**Issue by freefri** [uikit/uikit#3203]
I'm looking for a way of open a link in a new tab from inside a uk-lightbox element.

I've just made this codepen to ilustrate:

https://codepen.io/anon/pen/rJLMKP

As a requirement I need to have a lightbox with different elements (images, youtube videos, etc). This elements should be displayed as a slider (when the lightbox is opened). I also need to display some text for each element when the lightbox is not opened. Some of this text may contain links that should work as normal links (not opening a lightbox, even if they are placed inside the uk-lightbox element).

I could not find an answer for this in the docs (maybe I'm blind):
1. So this issue is a bug report for the docs (if the documentation for this feature is missing [here](https://getuikit.com/docs/lightbox) ) 
2. or a feature request, if this is not existing (maybe you could implement it with something like `data-type="link"`, so we can force to open the link as a normal link, or use the  `target="_blank"` attribute)
3. or it is a request for help (in case I'm blind and I cannot read the docs better than a monkey, in which case I'm sorry for opening an issue)

**Comment by aarongerig** [comment]
@freefri It's described in the docs under [Component options](https://getuikit.com/docs/lightbox#component-options).
Here's an example: https://codepen.io/aarongerig/pen/LQZxaM

**Comment by freefri** [comment]
Thx, just as a comment, I don't think I could understand how does `toggle` work without your codepen.
