### ISSUE TITLE
Switcher navigation links not working on Tabs

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3205]
### UIkit version

3.0.0-beta.39

### Browser
All

### Reproduction Link
https://codepen.io/zzseba78/pen/KQgggq

### Steps to reproduce
Try to change the switcher with navigation links

### What is Expected?
Switcher changes
### What is actually happening?
Switcher navigation links not working if Tab is implemented.

If you implement `uk-switcher` with subnav for example, it works.

And it works if you do it programmatically:
```
// Go to next switch item
var $tabElement = $("ul.login-tab");
var $buttonNext = $("#next-switch");

$buttonNext.on("click", function(e){
	UIkit.tab($tabElement).show(1);
	e.preventDefault();
});
```

**Comment by janschoenherr** [comment]
Use _uk-tab-item_. We'll have to add a note to the docs.

**Comment by zzseba78** [comment]
Great, thanks.

**Comment by oshihirii** [comment]
FYI, it seems using `uk-tab-item` will control multiple switcher instances, whereas `uk-switcher-item` will only control one instance, see:

https://codepen.io/oshihirii/pen/oNerbPL
