### ISSUE TITLE
Global component options not working.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3206]
### UIkit version

3.0.0-beta.39

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/XZjaQO
### Steps to reproduce
Check the animation delay time.
### What is Expected?
Scrollspy should have a delay of 3s
### What is actually happening?
Seems that Global options doesn´t work. I check that it isn´t working on Sticky and other components either. 

Thanks !

**Comment by janschoenherr** [comment]
I believe this to be an issue with codepen, as it injects your custom Javascript in the _footer_ of the document. By the time of its evaluation, UIkit components are already instantiated. If you do this in the _head_ of the document, you should be fine.

**Comment by zzseba78** [comment]
Thanks for your response @janschoenherr , i didn´t know that only work with scripts in the head. Closing this.
