### ISSUE TITLE
Actioning next/previous cancels autoplay in Slideshow

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3210]
### UIkit version

3.0.0-beta.39

Sorry to delete out the template, this one is pretty self explanatory - Slideshow with autoplay, press next or previous stops the autoplay. Which isn't bad and I was going to do it this way, however is this intended behaviour?

**Comment by janschoenherr** [comment]
Yes, currently, interacting with the Slideshow will stop it.
