### ISSUE TITLE
Dropdown hide event propagating to modal

### ISSUE THREAD

**Issue by dulongc** [uikit/uikit#3213]
### UIkit version

3.0.0-beta.39

### Browser
FF Quantam 58.0.1 (64-bit)
IE 11.0.96
Chrome 64.0.3282.140

### Reproduction Link

https://codepen.io/dulongc/pen/QQGxdQ

### Steps to reproduce
1) Click to open the modal
2) Hover over the button to open the drop down
3) Move mouse away to have the drop down close

### What is Expected?
Drop down should close while the modal remains unaffected. The event listener for the modal hide is to clear the contents of the modal in order to prep it for the next AJAX load

### What is actually happening?
The hide event on the drop down is propagating up to the modal, which causes the modal hide event to trigger, despite it not having been closed yet.

**Comment by janschoenherr** [comment]
You need to check for the [event target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target). 

Your code listens for a _hide_ event. Both drop and modal trigger a _hide_ event.
```
$(function() {
  
  	$("#modal-example").on({
  	'hide.uk.modal': function(){
  	$('#modal-example').html(" ");
  	}     
  	});
  
});
```
