### ISSUE TITLE
Modal close behavior

### ISSUE THREAD

**Issue by nla-brandonjames** [uikit/uikit#3215]
### UIkit version
3.0.0-beta.40

### Browser
Mozilla Firefox (likely all browsers)

### Reproduction Link
https://codepen.io/nla-brandonjames/pen/RQKxMO

### Steps to reproduce
Create a form and embed a modal window in the form. When the modal window is closed, the contents of whatever is input is moved outside of the form even if the modal was originally placed inside the form. This makes it so you would need to write some additional JavaScript to capture the input from whatever is in the modal window and put it into a hidden field in the form instead.

### What is Expected?
Put the modal form back where it was or somehow automatically keep the input of the form inside the form if the modal started off in the form.

### What is actually happening?
The modal is moving to outside the form when closed.

**Comment by janschoenherr** [comment]
Use _container: false_

    uk-modal="container: false"

**Comment by nla-brandonjames** [comment]
Thanks. I wasn't able to find this until you pointed it out!
