### ISSUE TITLE
JavaScript option "clsPanel" for modal not working

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#3219]
### UIkit version

3.0.0-beta.39

### Reproduction Link

https://codepen.io/anon/pen/rJyyeL

### Steps to reproduce
Click the link above

### What is Expected?
Applying the defined class "tt-dialog-class" by the option "clsPanel" ("cls-panel" in the docs is wrong)

### What is actually happening?
Nothing

**Comment by janschoenherr** [comment]
Currently _clsPanel_ is just a selector and should be named _selPanel_. It does not apply any classes at the moment.
