### ISSUE TITLE
Feature: add ability to define custom icons via additional JS file

### ISSUE THREAD

**Issue by picov** [uikit/uikit#3226]
Custom icons can be already added with build tools or by directly editing the 'uikit-icons.js' file.
A nice feature could be the ability to define additional custom icons by simply loading an extra JS file (ie leaving all UIkit dist files unchanged).

I could be wrong, but with the actual Icons initialization code it seems that there is no way to add items to **Icons** object before the call **UIkit.icon.add(Icons)** (from an extra JS file).

**Comment by janschoenherr** [comment]
You can, just call `UIkit.icon.add(YourIcons)` from your JS file.

**Comment by picov** [comment]
Great, just tested it's and working perfectly.
Sorry for my needless request, but before I've searched for something like this in 3.x docs with no luck.
