### ISSUE TITLE
uk-height-viewport="expand: true" does not work

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3228]
### UIkit version

3.0.0 WIP

### Browser
All

### Reproduction Link
http://localhost:8080/tests/height-expand.html

### Steps to reproduce
Run `npm run test`
Go to http://localhost:8080/tests/height-expand.html

### What is actually happening?
`uk-height-viewport="expand: true"` does not work

![screenshot_13](https://user-images.githubusercontent.com/3341562/36198656-3a70d2cc-1188-11e8-8fc8-dbc642300cf8.png)

**Comment by wolfcreative** [comment]
Please re-open. `uk-height-viewport="expand: true"` works through time. If you press "f5" (refresh) then it does not work.
