### ISSUE TITLE
[Bug] Slider Component Center Option fails on responsive sizing

### ISSUE THREAD

**Issue by DanielDarrenJones** [uikit/uikit#3235]
### UIkit version

3.0.0-beta.40

### Browser
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Safari Version 11.0.1 (13604.3.5)

### Reproduction Link
https://codepen.io/DanielDarrenJones/pen/ZrXwQz?editors=1000

### Steps to reproduce
Add responsive widths to the items in the slider list, while enabling the  center: true option.

### What is Expected?
Items should all be centered like in the example codepen: https://codepen.io/DanielDarrenJones/pen/gvGqwz

### What is actually happening?
The items become left aligned and leave a large gap on the left hand side of the slider.

**Comment by janschoenherr** [comment]
Seems to work fine with the official UIkit release

https://codepen.io/janschoenherr/pen/xYmjae

**Comment by DanielDarrenJones** [comment]
<img width="1679" alt="screen shot 2018-03-01 at 01 34 19" src="https://user-images.githubusercontent.com/8768709/36822600-bf496f7c-1cf0-11e8-84cb-9af47729310e.png">

As far as I can tell, this is not intended behavior, im running on mac OS 10.13.1 with same browser settings as before.

**Comment by janschoenherr** [comment]
That is actually intended behavior. Two things are happening here. The _infinite_ mode is automatically disabled, as soon as the slides aren't covering enough space to scroll infinite (Unlike other sliders we are not cloning DOM elements). 

In _finite_ mode the slides do center the slide, that's why there is white space left of the first slide.

**Comment by DanielDarrenJones** [comment]
It seems really odd the behaviour is different between mobile and desktop for example on mobile the slider looks great like:
![image](https://user-images.githubusercontent.com/8768709/36843714-ad98602e-1d47-11e8-9fc3-d49ca4dff5a8.png)

however on desktop it drops all of the nice centring and the infinite scroll and looks like this:
![image](https://user-images.githubusercontent.com/8768709/36843765-d45dea26-1d47-11e8-85fb-cd65bbcf4d66.png)

Is there a work around I can use to get the desktop version to match the mobile version? I can't see anybody intending to use the slider on desktop in its current state it looks really visually un-appealing and goes against the config set with centring and infinite scroll.

**Comment by schwaaab** [comment]
@DanielDarrenJones I have the same opinion, the center option right now is problematic to use.

I worked around the problem with this solution:
At first I add up the images widths and check it against the desired design viewport (ie 1920px) with php. If the images combined widths do not add up to that number, I use the UIKit Slideshow with bigger variations of the images. 
If the images have enough width, I use the Slider with the Center option and print every image twice, just in case, to have the infinite scrolling working properly. 

This is a workaround, not a solution.

A solution has to go in the direction of cloning the items to fill out the container like slick js does.
