### ISSUE TITLE
[Bug] Scroll component is attaching a click event to the element

### ISSUE THREAD

**Issue by SaphiLC** [uikit/uikit#3241]
### UIkit version

3.0.0-beta.40
### Browser
Opera 50
### Reproduction Link
https://codepen.io/SaphiLC/pen/oEoRdW
### Steps to reproduce
Load the pen, let it scroll down, click on the blue area
### What is Expected?
Nothing should happen
### What is actually happening?
The page scrolls to the top, for some reason the javascript code attaches a click event to the target

**Comment by janschoenherr** [comment]
You are attaching the scroll component to the target. Currently there is no utility function for smooth scrolling.

https://getuikit.com/docs/scroll
