### ISSUE TITLE
Calling multiple actions in one call

### ISSUE THREAD

**Issue by wolfcreative** [uikit/uikit#3243]
### UIkit version

3.0.0-beta.40

### Browser
All

### What is Expected?
Is there such an opportunity?
`UIkit.util.on('.class1', 'moved,added,removed', function() {
    console.log(1)
});
`

### What is actually happening?
`    UIkit.util.on('.class1', 'moved', function() {
      console.log(1)
    });`
`UIkit.util.on('.class1', 'added', function() {
      console.log(1)
    });`
`UIkit.util.on('.class1', 'removed', function() {
      console.log(1)
    });`

**Comment by janschoenherr** [comment]
Simply space separate the event names.
