### ISSUE TITLE
build/prefix.js bugginess

### ISSUE THREAD

**Issue by benjmnanderson** [uikit/uikit#3248]
### UIkit version
3.0.0-beta.40

### Browser
N/A

### Reproduction Link

N/A

### Steps to reproduce
Run the prefix build with a prefix like `node build/prefix -p uk-foo`
Run the prefix build again with a prefix like `node build/prefix -p uk-bar`

### What is Expected?
The resulting prefix should be `uk-bar`

### What is actually happening?
The prefix is actually `uk-uk-bar-`

The problem is with this function:
https://github.com/uikit/uikit/blob/075faf708aa9ebd4ef42ef23c6d6b6c147dc1560/build/prefix.js#L38-L51

The way this function is built assumes a lot. Line 44 will clearly result in buggy behavior, and has the potential of not working correctly at all. From what I can infer, the regex is intended to find the first instance of `uk-grid` (some better commit messages and code comments would help here). This is woefully error prone; for instance, there are grid classes such as `.uk-dropdown-grid` which, if encountered first, would cause prefixing to fail, e.g.:
```javascript
".uk-dropdown-grid".match(new RegExp(`([a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*)-grid`))
> [ "dropdown-grid", "dropdown" ]
```
That's a valid match, but then the prefix script will replace `dropdown`, with the supplied prefix.

Some things could be done to make this better, but for every case I thought of, it could be defeated in similarly naive ways as the example above. As useful as it is to be able to "update" prefixes from previously set ones, it's probably a bad idea to "find" a prefix like this. Likely the best solution would be to only support prefixing as part of a normal build (e.g. not a standalone script).

**Comment by dasdeck** [comment]
true, this approach is very simplistic and assumes a lot, it worked in most cases and is a little sugar on top anyways. you really should rebuild and prefix from scratch. I'll remove or update the feature now.
Thanks for your input!

Cheers!
