### ISSUE TITLE
How can I make a slider or slideshow RTL?

### ISSUE THREAD

**Issue by bariskrdrl** [uikit/uikit#3251]
### UIkit version

3.0.0-beta.40

### What is Expected?
How can I make a slider or slideshow RTL?
I have css for rtl but I do not want to rtl the entire site. I want to apply it to the slider or slideshow I want.
I did not see such a thing on the site. 
Thanks for the help.

**Comment by janschoenherr** [comment]
UIkit reacts to the whole page being RTL. There currently is no setting that makes the slider or slideshow behave in RTL mode separately.
