### ISSUE TITLE
[Bug] 'uk-height-viewport: expand' does not recalculate height

### ISSUE THREAD

**Issue by wolfcreative** [uikit/uikit#3257]
### UIkit version
3.0.0-beta.40

### Browser
All

### Steps to reproduce
1. Create main container and footer 
2. Add 'uk-height-viewport:expand' to the main-container
3. For example, use a 'uk-switcher' in main-container and increase the size of the block from the inside

### What is Expected?
Clear inline 'height' or recalculate

### What is actually happening?
'uk-height-viewport: expand' does not recalculate the height

**Comment by wolfcreative** [comment]
I did a little experiment. If you remove elements from DOM, then the 'uk-height-viewport:expand' is triggered. If you use a 'uk-switcher' or 'uk-tab', then the 'uk-height-viewport:expand' does not work.

**Comment by janschoenherr** [comment]
Resolved with 91499d0a22ce3a10c85532236e87f43467013b9c
