### ISSUE TITLE
Lightbox iframe content continues playing in background

### ISSUE THREAD

**Issue by noelboss** [uikit/uikit#3260]
### UIkit version

3.0.0-beta.40

### Browser

Any…

### Reproduction Link
https://codepen.io/anon/pen/ddwjbV

### Steps to reproduce

- Create a lightboxlink with an iframe of a youtube or Vimeo link. 
- Open the Lightbox
- Play the video
- close the lightbox.
 Video keeps playing in the background

### What is Expected?

Lightbox closing should remove iframe

### What is actually happening?

iframe states in the background…

**Comment by janschoenherr** [comment]
Please don't use the data-type="iframe" for videos.

https://getuikit.com/docs/lightbox#content-sources

**Comment by noelboss** [comment]
Please do not close the issue with a simple response like this. There are reasons for using an iframe. We have content where we can not use the data-type video but need an iframe. Please consider my solution – you can not simply assume that there is no rich media playing in an iframe at any moment.

**Comment by janschoenherr** [comment]
Is this about the extra params passed to the Vimeo url? Yes, UIkit's URL matching needs to be smarter here.

**Comment by noelboss** [comment]
No, it is because the iframe is not removed from DOM after the lightbox closes.
Videos playing in the lightbox keep playing after the lightbox is closed, even on the documentation page:

1. [Go to the docks](https://getuikit.com/docs/lightbox#content-sources), click on youtube button, start video, close lightbox
2. [Go to the docks](https://getuikit.com/docs/lightbox#content-sources), click on vimeo button, start video, close lightbox

### What is Expected?
Videos and other media resources inside iframes should be removed from DOM to stop playback.

### What is actually happening?
Media continues playback in background with sound on.

### Solution
I have prepared a solution: https://codepen.io/anon/pen/ddwjbV

**Comment by Lumelomser** [comment]
Video playback issue after closing the lightbox was fixed in v3.0.0-rc.1.
