### ISSUE TITLE
Icon SVG should use SVG width/height if available

### ISSUE THREAD

**Issue by joshwils82** [uikit/uikit#3263]
### UIkit version
3.0.0-beta.40

It appears that currently the icon svgs are setting width and height based on the viewbox dimensions of the svg element.  This causes issues when trying to integrate fontawesome icons.  They were created at a much larger dimension and because of this they render much larger than expected in uikit.

Would it be possible to use the width and height on the svg if present and then fallback to the viewbox dimensions?

**Comment by janschoenherr** [comment]
I think the viewbox dimensions are a fallback. Could you please provide a reproduction link? Thanks.
