### ISSUE TITLE
Slideshow autoplay-interval option in docs not recognised, autoplayInterval is

### ISSUE THREAD

**Issue by mthomsonnz** [uikit/uikit#3264]
In the docs:
https://getuikit.com/docs/slideshow
'autoplay-interval' is listed in the component options. this term doesn't exist doing a text search of beta 40 javascript. The 'autoplayInterval' option does exist in the AutoplayMixin and works for the slideshow.

**Comment by janschoenherr** [comment]
It gets converted from _autoplay-interval_ to _autoplayInterval_ on component initialization.
