### ISSUE TITLE
Hello how to center modal via call UIkit.modal.dialog v3.0.0-beta.40

### ISSUE THREAD

**Issue by freenetwork** [uikit/uikit#3265]
var modal = UIkit.modal.dialog()
$target = $(modal.$el)
$target.addClass("uk-margin-auto-vertical") not working

**Comment by toniluong** [comment]
you could archieve that with the uk-flex and uk-flex-middle css class. Additionally you have to remove the style attribute programatically after the modal is loaded.  since it is added by the UIkit modal component.

**Comment by janschoenherr** [comment]
Try something like `modal.$el.firstElementChild.classList.add('uk-margin-auto-vertical');`

**Comment by makeitaboldmove** [comment]
@freenetwork I know I'm a year late, but I figure out a solution as I was dealing with finding a solution for this too. If you have jQuery included on your page you can use the snippet below:

```
if($app.notification.message){
	UIkit.modal.alert($app.notification.message).then(function(){
		// Do stuff after
	});	
	UIkit.util.on(document, 'beforeshow', function($e){
		if(typeof $e.detail[0].$options.name !== 'undefined' && $e.detail[0].$options.name == 'modal'){
			$('.uk-modal').removeAttr('style').addClass('uk-flex-top uk-flex uk-open');
			$('.uk-modal-dialog').addClass('uk-margin-auto-vertical');
		}
	});
}
```

If you're not using jQuery you can replace the "$" selector and manipulation functions with native JavaScript.

**Comment by rvalitov** [comment]
The solution provided by @janschoenherr works like a charm!
