### ISSUE TITLE
Modal Youtube + Ajax

### ISSUE THREAD

**Issue by Uranbold** [uikit/uikit#3269]
Hi guys, I have question for Modal opening Youtube contents.

I have 20+ Youtube Iframe video in 1 HTML and those are opened with Modal and if i reload the Page All Youtube Videos will load and it takes some times for opening.

I think i need some Ajax Calling solution and i have found the some plugins for another library and however i have included it and Autoplay seems not working Because that third party doesn't support it.

Are you planning to Add Ajax method on Modal element in near future?

Thanks.

**Comment by TomS-** [comment]
Hey,
You don't really need Ajax for this. You can do this simply by adding the class `.open-video` to the button you want to open a Modal and give it the attribute `data-id="youtube-id"`.
HTML:
```
<div class="open-video" data-id="2UByqalCfnk"></div>
```
JS:
```
UIkit.util.on(".open-video", "click", function (e) {
    e.preventDefault();
    e.target.blur();
    UIkit.modal.dialog('<iframe width="560" height="315" src="https://www.youtube.com/embed/' + e.target.getAttribute("data-id") + '?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>');
});
```

**Comment by Uranbold** [comment]
`e.target needs` to append with following `e.target.nodeName`

**Comment by Uranbold** [comment]
@TomS-  Sorry for that. It only open first Element and others are not working.

Thanks.

**Comment by Uranbold** [comment]
It seems selecting Class is the Problem. Modal is not firing with Class selector. It only works on first element.

**Comment by Uranbold** [comment]
@saschadube How to open the Multiple Modals with Class selector?

```
UIkit.util.on(".open-video", "click", function (e) {
        e.preventDefault();
        e.target.blur();
        console.log(e.target);
        UIkit.modal.dialog('<iframe width="860" height="484" src="https://www.youtube.com/embed/' + e.target.parentNode.getAttribute("data-id") + '?autoplay=1&amp;rel=0"></iframe>');
    });
```

**Comment by aarongerig** [comment]
@Uranbold This is a usage question and should be asked in the Gitter chat. https://gitter.im/uikit/uikit

Here's an example on how you can listen to events on multiple HTML elements.
https://codepen.io/aarongerig/pen/geYbdo
