### ISSUE TITLE
uk-switcher doesn't work with slider

### ISSUE THREAD

**Issue by toniluong** [uikit/uikit#3272]
### UIkit version
3.0.0-beta.40 
(used to work in a previous version. probably -beta.38)

### Browser
tested only in Chrome (latest)

### Reproduction Link / Steps to reproduce
uk-switcher toggles == slider items
related content -> inside or outside of uk-slider (doesn't matter)

### What is Expected?
that the switcher is working: click on a slider item (toggle) should display the related content

### What is actually happening?
nothing. clicking on slideritems / toogle seems to have no impact. (developer tools shows some dom activity but for a user nothing seems to be happening)
content of first switcher item is displayed all the time and doesn't change.

**Comment by toniluong** [comment]
Simple codepen example
https://codepen.io/titime/pen/LmPpEE

**Comment by wdac-davy** [comment]
I'm experiencing the same issue as linked in the codepen example and there doesn't appear to be a way to set a different active class for the switcher or slider to remedy it. Any updates?

**Comment by janschoenherr** [comment]
This commit might work for you: 28a5abf4bd8720d0d3fbb79cbb1482d217d3eee0

Please checkout the latest dev version. https://www.npmjs.com/package/uikit
