### ISSUE TITLE
uk-svg and vue.js causes double "icons" / svg images again - race condition!!

### ISSUE THREAD

**Issue by toniluong** [uikit/uikit#3273]
### UIkit version
3.0.0-beta.40
vuejs (2.5.13)

### Browser
Chrome

### Reproduction Link
either use uikit-icons or create your own svgs 

### Steps to reproduce
easier to reproduce if you use multiple inline-svgs on one page. 
add uk-svg attribute to img tag.
turn of caching of the libs

### What is Expected?
no double icons / svg images

### What is actually happening?
There seems to be a race condition when loading uikit.js and vue.js  causing the uk-svg connected method of the UIkit-svg component is executed twice. Therefore the svg is added (append(root, el) / after(root, el)) twice. 
imo it is hard to avoid this race condition. Maybe marking the root element with something (attribute, css class. ...) that is has been handled and check for that before adding the element to the DOM would solve the problem. Or abuse the hidden attribute since it is set before the svg is appended. (see screenshot 2 line 6961)

![image](https://user-images.githubusercontent.com/33172862/37019922-5f9eb3b0-211a-11e8-9dfb-c45368ab8bd9.png)
![image](https://user-images.githubusercontent.com/33172862/37020276-893eedd8-211b-11e8-99e6-10f91cfec934.png)

**Comment by janschoenherr** [comment]
The "easy" solution to this is to use Vue's [bind](https://vuejs.org/v2/api/#v-bind) directive. We are working on having something better in the foreseeable future.

    <span :uk-icon="heart"></span>
