### ISSUE TITLE
modal.confirm without reject callback throws error

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3274]
### UIkit version

3.0.0-beta.40

### Browser
Any

### Reproduction Link
https://codepen.io/qdev/pen/mXNLVW

### Steps to reproduce
* open console
* open confirm
* cancel it

### What is Expected?
Close the modal

### What is actually happening?
It closes, but it's throwing en error: `Unhandled Promise Rejection: undefined`

In 99.99% of the usage, nothing should happen on cancel a prompt (besides closing it's modal), so no need to define an empty reject callback just to avoid this error

**Comment by janschoenherr** [comment]
How would you prefer to react to the _cancel_?

**Comment by razvanioan** [comment]
If there's no reject callback defined, at least not throw an error or to catch it, at least that's what I'm thinking ;)

**Comment by janschoenherr** [comment]
Unfortunately that's not how promises work. For now you'll have to handle both cases.

**Comment by KpjComp** [comment]
Hit this one too, for me this is not logical at all,.. Cancelling a dialog is not an error..

What I would have expected is,  when you click confirm you `resolve(true)`, when you click cancel you `resolve(false)`..

Save the the reject for when there is an error, that's how promises work.. :)
