### ISSUE TITLE
Upload: 'data-type' doesn't fire error when response type is text/html

### ISSUE THREAD

**Issue by Draio** [uikit/uikit#3275]
### UIkit version
3.0.0-beta.40

### Browser
latest Chrome, Firefox and Edge

### Reproduction Link
https://jsfiddle.net/draio/nh40qg6d/

### Steps to reproduce
**Setting 'data-type' to "json" upload doesn't fire callback error when response type is text/html**

The example link use the jsfiddle Async requests. 
Switching the url from '/echo/json/' to '/echo/html/' (therefore the answer between _Content-Type:application/json_ and _Content-Type:text/html_)  doesn't generate any error.

### What is Expected?
A call to the "_error_" callback

### What is actually happening?
A call to "_complete_" and "_completeAll_" callback

**Comment by janschoenherr** [comment]
Hi,

there is no _data-type_ option, that I know of. You can set the _responseType_ to 'json'

        beforeSend: function(env) {

            env.responseType = 'json';

        }

**Comment by draio** [comment]
Thank you, I will set the responseType. 

However, I may have misinterpreted, but in the component options of upload page (https://getuikit.com/docs/upload) there is the  data-type option  

`data-type | String |  | The expected response data type: xml, json, script, or html`

Thank you again

**Comment by janschoenherr** [comment]
I am sorry, you are right. It sets the http request method (POST) and should probably be renamed to _method_. Thanks.

**Comment by janschoenherr** [comment]
Thanks, you are right, it should be fixed now.
