### ISSUE TITLE
Feature requests (website): search

### ISSUE THREAD

**Issue by drpiou** [uikit/uikit#3277]
Hi, this will probably be deleted but I don't know where to ask this, so I just need this message to be read by an admin: can you please add a search function on your website ? It's a pain to find what we need. I have in mind a search function like ReactNative docs, but anything should do the trick and can be better than anything ;) Many thanks :)

**Comment by zzseba78** [comment]
Seems like it is a very demanded feature, so there it goes my finger pointing up :)

**Comment by Grawl** [comment]
Sphinx is wery good feature, but we can add more simple search using only components names and descriptions

**Comment by janschoenherr** [comment]
https://github.com/uikit/uikit-site/issues/93
