### ISSUE TITLE
manually-set uk-tab-left and uk-tab-right were unexpectedly removed

### ISSUE THREAD

**Issue by hismichael** [uikit/uikit#3278]
manually-set `uk-tab-left` and `uk-tab-right` were unexpectedly removed by the framework.

I created a uk-tab component in a off-canvas sidebar, while I failed to set the `uk-tab-left` or `uk-tab-right` class to the tab component, the class was unexpectedly removed by the framework during its every time running.

Please help me out!

Thank you

**Comment by abo-github** [comment]
i think it's because the viewport is below 960px
