### ISSUE TITLE
get current switcher / tab index

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3279]
### UIkit version

3.0.0-beta.40

### Reproduction Link
https://codepen.io/qdev/pen/xWGmGY?editors=1011

### Steps to reproduce
change tabs

### What is Expected?
obtain the index of the current shown item (in the console)

### What is actually happening?
I thought that `active` would return the current / active item in the switcher
But I've just read in the docs that this is only to establish the default item to be shown on mount

How can I obtain the index or item of the current shown tab on change event ?

In the meantime, I guess I will just use plain JS to look for the `li.uk-active` but it would have been nice to have a parameter or method for this

**Comment by razvanioan** [comment]
So actually in the case of `show(n)` events, the `event.target` points to the current item / li (in the switcher).

But it would have been nice also to have an easy parameter or method callable independently (not as a result of en event) to get the current item / index.

**Comment by martinlyder** [comment]
I agree it would me nice just to write "e.index"
Here's a simple jQuery, to get the index, for those who, as me end up here and cant wait for an update :)
```
UIkit.util.on('#switcher_id', 'shown', function () {
   var index = $('#switcher_id li.uk-active').index();
});
```

**Comment by razvanioan** [comment]
@martinlyder one of the strong points of UIkit (that I like) is that it is NOT dependent of jQuery, thus, I've removed the dependency to it completely in my projects too.

There's also a helper / util `index` function in the library, so you can something like:

```javascript
UIkit.util.on('#switcher_id', 'shown', function () {
  var index = UIkit.util.index(UIkit.util.$('li.uk-active', this))
})
```

**Comment by martinlyder** [comment]
Thats cool could not find that in the doc.
I was just lazy writing the document.getElementById(elementID) with jQuery... :)

**Comment by razvanioan** [comment]
The team is busy in developing the framework itself, and keeping the basics in the docs for now.

If you take a look on the framework's source code (very clean & easy to understand or extend), you'll figure it out everything you need, at least this is what I do ;)

**Comment by balashovka** [comment]
> @martinlyder one of the strong points of UIkit (that I like) is that it is NOT dependent of jQuery, thus, I've removed the dependency to it completely in my projects too.
> 
> There's also a helper / util `index` function in the library, so you can something like:
> 
> ```js
> UIkit.util.on('#switcher_id', 'shown', function () {
>   var index = UIkit.util.index(UIkit.util.$('li.uk-active', this))
> })
> ```

it's still not working - https://codepen.io/anon/pen/mgbXLw?editors=1111#anon-login

**Comment by razvanioan** [comment]
@balashovka 

It is not working anymore because in the meantime UIkit has been changed ;)

If you take a look on the `li.uk-active` on the switcher content on `shown` event, you'll notice that both items are active (previous and current / new).

This is also the reason why when you select a higher index you get the old one, and if you select a lower you get the correct index, just because that's the way `UIkit.util.$` (or `document.querySelector`) does (matches the first element).

This is because the element is updated after the `shown` event is triggered, you can see this on  [togglable mixin line 141](https://github.com/uikit/uikit/blob/develop/src/js/mixin/togglable.js#L141)

In my personal opinion, I would've triggered the `shown` event after the element was updated ;)

Now, a quick / dirty solution would be to check for the index of the `tab` element which is controlling the `switcher` view, this can be achieved very simply in you example, where `uk-tab` is immediate before the switcher (like in majority of the cases), just by changing the `ul` element you're getting the .uk-active index on.

This can be a little bit more problematic / harder to find in case thy are manually connected on some selector using `connect` option (but it can be done in that case as well)


```javascript
UIkit.util.on('#switcher_id', 'shown', function () {
  var index = UIkit.util.index(UIkit.util.$('li.uk-active', this.previousElementSibling))
})
```

[https://codepen.io/anon/pen/dLbQoR?editors=1111](https://codepen.io/anon/pen/dLbQoR?editors=1111)

**Comment by janschoenherr** [comment]
@balashovka 
Try
```
UIkit.util.on('#switcher_id', 'shown', function (e) {
  var index = UIkit.util.index(e.target)
  console.log(index)
})
```
