### ISSUE TITLE
Conflict between sticky navbar and toggle menu.

### ISSUE THREAD

**Issue by rvanosnabrugge** [uikit/uikit#3280]
### UIkit version
3.0.0-beta.40

### Browser
Chrome and Safari on OSX

### Reproduction Link
https://codepen.io/anon/pen/LdVwJq

### Steps to reproduce
Scroll down and click the toggle menu. You can see that the navbar becomes transparent again.

### What is Expected?
I expect the navbar to remain its class, based on the position of the page.

### What is actually happening?
- Initially, the '.uk-navbar-container' has classes '.uk-navbar-transparent .uk-light', coming from the cls-inactive;
- When scrolling down, the classes '.uk-navbar-transparent .uk-light' are replaced by '.uk-navbar-sticky', coming from cls-active;
- When the side menu is toggled, the sticky classes are swithed.

**Comment by arminmon** [comment]
Kinda same issue happens when uk-sticky="show-on-up: true;".
Navbar disappears with no animation on menu toggle.

**Comment by rvanosnabrugge** [comment]
Any updates on this issue?

**Comment by rvanosnabrugge** [comment]
When the overlay property of uk-offcanvas is set to false, it does not happen. However, the overlay is preferable :-)

**Comment by janschoenherr** [comment]
There is currently no way to prevent this behavior. The Offcanvas gets a fixed height when active to prevent scrolling on mobile. That causes the issues with the sticky navbar.

**Comment by rvanosnabrugge** [comment]
Thanks for your reply @janschoenherr ! Is it on the planning to have a solution for it?

**Comment by janschoenherr** [comment]
We are currently not actively working on that, but we do have it in mind, then stumble upon a better implementation or another solution comes up.

**Comment by janschoenherr** [comment]
This seems to be resolved.
