### ISSUE TITLE
Extending Lightbox event 'itemload' with new content type

### ISSUE THREAD

**Issue by crowincage** [uikit/uikit#3281]
Hi and first thanks for your great work!

I want to extend the UiKit Lightbox to include Vue PDF (https://github.com/FranckFreiburger/vue-pdf). I already found the 'itemload' event in the lightbox panel file where lightbox decides which content type to use.

Is it possible to extend this without touching the source?

Thanks for any hints on that :-)

/c

### UIkit version
3.0.0-beta.40

**Comment by janschoenherr** [comment]
That's the idea, you listen for the _itemload_ event and then call the _setItem_ method of the LightboxPanel component from the event handler.

    UIkit.util.on(document, 'itemload', '.uk-lightbox', function (e, item) {
        if (item.type === 'vue-pdf') {
            UIkit.lightboxPanel(e.target).setItem(item, '<my-markup>');
        }
    }
