### ISSUE TITLE
Regex error on svg.js

### ISSUE THREAD

**Issue by mathisloge** [uikit/uikit#3285]
### UIkit version

3.0.0-beta.40

### Error:
Maybe there is a regex error is [svg.js on line 174](https://github.com/uikit/uikit/blob/develop/src/js/core/svg.js#L173) .

You can check it out under [https://regex101.com/r/QqiwWy/1/](https://regex101.com/r/QqiwWy/1/)

### The Error occured:
I´m starting a new project with ASP.NET Core 2.0. The bundler & minifier complains about it.

**Comment by janschoenherr** [comment]
You'll have to set the regex flavor to Javascript.

I will change it with the next release to not use _[^]_
