### ISSUE TITLE
uk-width-auto issue

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3286]
uk-width-auto@  classes needs to flex resetting values at certain breakpoints.
Uikit only sets width: auto but this not helps if set expand small breakpoint.

uk-width-auto@l {
 flex: 0 0 auto;
 width: auto;
 max-width: none;
}

https://codepen.io/anon/pen/BrzdYG

**Comment by saschadube** [comment]
Thanks for reporting! Fixed with https://github.com/uikit/uikit/commit/c20ef70204d86bcdcc14a0aff93474e1a5368fd8
