### ISSUE TITLE
Using with Meteor

### ISSUE THREAD

**Issue by cmeethree** [uikit/uikit#329]
Hi I'd love to use this with Meteor and wondered if someone had tried this or ideas of how to make this work. Love ui kit and combining it with Meteor would be a super powerful combination.

**Comment by zachariahtimothy** [comment]
@cmeethree That package has been flagged in Atmosphere as not working. I have little confidence it is up to day. Can we re-open this so UIKit devs can package UIKit for Meteor?  I have grown to love it over Bootstrap by a large amount.

**Comment by cmeethree** [comment]
Hi zack not sure if you meant to email me? I used ui kit for one of my projects - I too don't use bootstrap.

But my prototype still works. Although I have noticed issues on mobile with modals (they seem to break).

**Comment by zachariahtimothy** [comment]
I went ahead and forked uikit and added meteor support. I have it working
on one of my projects wonderfully. Thanks!

_____________________________________
Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis <https://twitter.com/#!/@zachariahCurtis>
B: http://zachariahtimothy.wordpress.com/

**Comment by cmeethree** [comment]
Haven't yet done the full process of taking a uikit web app native. But yeah np.
