### ISSUE TITLE
UK-WIDTH

### ISSUE THREAD

**Issue by sebbio** [uikit/uikit#3290]
Not exists class uk-width-2-6, uk-width-3-6, uk-width-4-6. Maybe need alias to uk-width-1-3,uk-width-1-2,uk-width-2-3 ????

**Comment by aarongerig** [comment]
That's totally intentional, because `2/6` is the same as `1/3` and so on. So instead of `.uk-width-2-6` simply use `.uk-width-1-3`.

**Comment by sebbio** [comment]
I understand, but maybe need alias?

**Comment by aarongerig** [comment]
No, that‘d be redundant code, which is unnecessary.

**Comment by sebbio** [comment]
How can I do width 1-12 or 1-10 ?

**Comment by badpenguin** [comment]
@sebbio you have to defined your own width but currently grid.css does not allow that

**Comment by aarongerig** [comment]
@badpenguin Please, do not spread information that is **wrong**. You can extend the grid!

**Comment by badpenguin** [comment]
@aarongerig yes but if you do using that only mixin you'll end up with your \@s going to override the other \@m, \@l, classes. Actually i'm forced to copy lots of content from width.css inside that mixin.

**Comment by aarongerig** [comment]
@badpenguin As I mentioned in the Gitter chat, the order of your media-queries matter. Pay attention to that!

**Comment by badpenguin** [comment]
For reference: https://github.com/uikit/uikit/issues/3267

My current implementation: 
```
@mixin hook-width-misc() {

	.uk-width-1-10 {
		width: 10%
	}
	.uk-width-3-10 {
		width: 30%
	}
	.uk-width-7-10 {
		width: 70%
	}
	.uk-width-9-10 {
		width: 90%
	}

	/* Phone landscape and bigger */
	@media (min-width: $breakpoint-small) {

		/* Whole */
		.uk-width-1-1\@s {
			width: 100%;
		}

		/* Halves */
		.uk-width-1-2\@s {
			width: 50%;
		}

		/* Thirds */
		.uk-width-1-3\@s {
			width: unquote('calc(100% * 1 / 3.001)');
		}
		.uk-width-2-3\@s {
			width: unquote('calc(100% * 2 / 3.001)');
		}

		/* Quarters */
		.uk-width-1-4\@s {
			width: 25%;
		}
		.uk-width-3-4\@s {
			width: 75%;
		}

		/* Fifths */
		.uk-width-1-5\@s {
			width: 20%;
		}
		.uk-width-2-5\@s {
			width: 40%;
		}
		.uk-width-3-5\@s {
			width: 60%;
		}
		.uk-width-4-5\@s {
			width: 80%;
		}

		/* Sixths */
		.uk-width-1-6\@s {
			width: unquote('calc(100% * 1 / 6.001)');
		}
		.uk-width-5-6\@s {
			width: unquote('calc(100% * 5 / 6.001)');
		}

		.uk-width-1-10\@s {
			width: 10%
		}
		.uk-width-3-10\@s {
			width: 30%
		}
		.uk-width-7-10\@s {
			width: 70%
		}
		.uk-width-9-10\@s {
			width: 90%
		}

	}
[...]
```
and so on for the remaining media queries.

**Comment by aarongerig** [comment]
Why would you copy and paste the already existing implementation into that mixin? You‘re not gonna overwrite the whole width component by just that mixin, just so you know...
