### ISSUE TITLE
[BUG] Dropbar Triggers JS Error in Safari & Firefox

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#3291]
### UIkit version
3.0.0-beta.40

### Browser
Bug reproducible in the latest versions of Safari & Firefox. Unable to reproduce in Chrome. Unable to test on Edge.

### Reproduction Link
The Official Navbar Test Page:
https://getuikit.com/assets/uikit/tests/navbar.html

### Steps to reproduce
  1. Access the official Navbar Test page, using either Safari or Firefox. 
  2. Open the Developer Tools. 
  3. Scroll down the page, until you see the 'Dropbar' test section
  4. Move cursor over one of the dropdown menus to activate the dropbar. You will see a javascript error popup in the error log.
  5. Move cursor out of the dropbar dropdown, to close it. You will see another error popup in the console.

<img width="748" alt="screen shot 2018-03-18 at 6 50 20 pm" src="https://user-images.githubusercontent.com/2994472/37563911-3dc03d6c-2adf-11e8-85b9-be7518e97662.png">

### What is Expected?
The dropbar should function without triggering javascript errors on major browsers. 

### What is actually happening?
The dropbar seems to be triggering javascript errors on Safari & Firefox.

**Comment by janschoenherr** [comment]
Thanks, this is resolved in the development branch.
