### ISSUE TITLE
Switcher 'shown' event erroneously fired for parent Modal

### ISSUE THREAD

**Issue by aaronpeterson** [uikit/uikit#3293]
### UIkit version
3.0.0-beta.40

### Reproduction Link
[https://codepen.io/anon/pen/YapmgZ](https://codepen.io/anon/pen/YapmgZ)

### Steps to reproduce

1. Show Codepen Console
2. Click "Open" to open the modal
3. Change Switcher tab within modal

### What is Expected?
Observation of switcher events to be independent of modal events.

### What is actually happening?
Modal 'shown' event is being fired erroneously when its child Switcher 'shown' event is fired.

**Comment by TomS-** [comment]
https://codepen.io/anon/pen/WzRWQp

Make sure you stop propagation

**Comment by aaronpeterson** [comment]
[https://getuikit.com/docs/slider#events](https://getuikit.com/docs/slider#events)

I thought about that but then noticed that Slider sort of got its events namespaced.  item* etc

**Comment by janschoenherr** [comment]
Please check out https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Bubbling_and_capturing_explained

Both, modal and switcher trigger the same events, you'll have to check for the event target.

**Comment by Cumbalin** [comment]
I don't think the `e.stopPropagation()` worked for me.
I have a tab switcher in a modal, and the modal kept executing as if it was hidding whenever I used the tabs.

This is what i ended up using when I first initiate the modal:
`UIkit.util.on('#mymodal','hidden',(e)=>{
  e.stopPropagation();
  if (e.srcElement===this) {
    stuff here if the modal is closed
  }
});`
