### ISSUE TITLE
Lack of quick start examples

### ISSUE THREAD

**Issue by hrstoyanov** [uikit/uikit#3295]
Here is what uikit sorely lacks - a library of ready- made blocks, like this one for bootstrap:

https://github.com/froala/design-blocks/blob/dev/README.md

The uikit docs are very good, but to dry and not helpful for quick start and productivity.

**Comment by klor** [comment]
Bootstrap 4 has an [Examples](https://getbootstrap.com/docs/4.0/examples/) section to help users get started and demonstrate best practices. Creating a getting started section could be done by showing 4-5 common use cases such as:

* Starter template - the "official" getting started template
* Grid - demonstrate how it works
* Navbar (static or fixed) - a simple navbar with a H1 heading a some lorem ipsum text
* Article page - a more advanced example with navbar, left menu, heading, article text and a photo.
* Blog

**Comment by zzseba78** [comment]
@hrstoyanov Hi!ç

- You have the test section, there you have all the functionality of uikit with many exampleshttps://getuikit.com/assets/uikit/tests/navbar.html

- KickOff it´s a project i´m working on, have some starter layouts to get you quickly started quickly, all layouts are html5 validated and have no additional css ( only dashboard ), more to come soon: https://zzseba78.github.io/Kick-Off/

**Comment by hrstoyanov** [comment]
Thnaks @zzseba78
