### ISSUE TITLE
Pagination style not set after compiling!

### ISSUE THREAD

**Issue by Renkert** [uikit/uikit#3298]
UIkit version 3.0.0-beta.40

Safari/Chrome

### This is my code in my _import.less file for pagination:

@pagination-margin-horizontal: 10px;
@pagination-item-border: rgba(58, 63, 75, 0.5);
@pagination-item-border-width: 1px;
@pagination-item-color: #3a3f4b;
@pagination-item-min-width: 41px;
@pagination-item-padding-horizontal: 10px;
@pagination-item-padding-vertical: 8px;
@pagination-item-hover-background: #3a3f4b;
@pagination-item-hover-color: #ffffff;
@pagination-item-active-background: #62a8ea;
@pagination-item-active-color: #ffffff;

### What I want to see!

Is a pagination with borders... but borders are not shown I css. Is there a trick?

OK, what I checked: When I @import the pagination.less file, all data are not compiled.. possible?

**Comment by zzseba78** [comment]
These variables doesn´t exist in UIKit, use hooks.
```
.hook-pagination-item() {
    // your styles here
}
```
