### ISSUE TITLE
Switcher events don't effect Tab nav

### ISSUE THREAD

**Issue by paul-muckypuddle** [uikit/uikit#3300]
### UIkit version
3.0.0-beta.40

### Browser
Chrome Latest

### Reproduction Link
https://codepen.io/anon/pen/BrmNeL

### Steps to reproduce
1. Click 'Next Tab'

### What is Expected?
Neither Switcher pane nor Tab tab change (because of 'return false' from 'beforehide' event

### What is actually happening?
Switcher stays the same, but Tab moves to next one and makes it active

Looks like the Tab and the Switcher events aren't properly connected.

**Comment by Renkert** [comment]
Hi Paul,

keep in mind, that UIKit has no jQuery on board. Have a look at my forked pen and try out your tabs, is that what you expected? Don't use  the $ sign as selector, you have to learn pure javascript now...
https://codepen.io/Archidomus/pen/LdeZXY

Greetings from Germany

**Comment by paul-muckypuddle** [comment]
No. Returning false should prevent the tab changing, whether vanilla JS or jQuery. Your Codepen exhibits the exact same problem.

**Comment by Renkert** [comment]
ok, I understand, you don*t want the tab to have in class "uk-active". In my opinion you only prevent the show/hide function of the <ul class="uk-switcher">, this is working. To achieve your wanted effect, you have to implement a second eventListener for the <ul class="uk-tab"> to avoid the "uk-active" setting. So, it seems you are right, they are not connected, should they?

**Comment by paul-muckypuddle** [comment]
They should absolutely be connected. Looks like @janschoenherr has assigned this to himself, so hoping might get a fix in a future release 😀

**Comment by paul-muckypuddle** [comment]
Still an issue in v3.0.0-beta.42

**Comment by paul-muckypuddle** [comment]
And remains in RC2

**Comment by janschoenherr** [comment]
With 3.3.5 you can now correctly defaultPrevent the `beforehide` and `beforeshow` events.
