### ISSUE TITLE
Flexbox Fallback

### ISSUE THREAD

**Issue by skolhustick** [uikit/uikit#3302]
I am trying my luck here. 
We have been religiously using UIKIT2, and now we have migrated to UIKIT3. 

Poor thing, some of our users are using iOS8 and below. 
We were wondering if there are plans to include fallbacks for these old browsers especially for the Flexbox grids?

**Comment by zzseba78** [comment]
Flexbox works with prefix `-webkit-` from v 7.1 https://caniuse.com/#feat=flexbox
Maybe you can use some tool to compile the css with vendor prefixes, like Autoprefixer.

**Comment by skolhustick** [comment]
Okay, this means, I autoprefix the UIKIT css files, no?
