### ISSUE TITLE
Responsive tabs

### ISSUE THREAD

**Issue by abartier** [uikit/uikit#3303]
Hello, 

Any plan for responsive tabs on V3? I read that it was done on V2 but nothing 'yet' on V3.

### UIkit version
3.0.0-beta.40

**Comment by abartier** [comment]
Closing because it can be achieved with a dropdown inside the uk-tab and a visibility/hidden class

Maybe it worth mentioning it in the docs ?

**Comment by janschoenherr** [comment]
There are plans to implement this in the "nearer" future.

**Comment by abartier** [comment]
You mean in the docs or to the uk-nav it self? I'm looking forward to this in both cases ;)
