### ISSUE TITLE
Dropdown boundary and animation on Chrome

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#3304]
### UIkit version
3.0.0-beta.40

### Browser
Chrome Version 65.0.3325.181(Latest)
### Reproduction Link
https://jsfiddle.net/papazetis/w35Lowng/15/

### What is actually happening?
When you fast hover on each button, the dropdown looses the normal slide animation. That happens only on Chrome and on slide animations.

On chrome inspector I can see that the normal top value is 121px. Sometime that goes to 171px and the animation seems to brake for a while.

**Comment by janschoenherr** [comment]
This should be fixed with 85f071270dbe6eeea5236650dff9a05fa9e6f6ba
