### ISSUE TITLE
Form icons didn't work properly with uk-form-small

### ISSUE THREAD

**Issue by abartier** [uikit/uikit#3305]
### UIkit version
3.0.0-beta.40

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/MVVepm

### Steps to reproduce
Try to add simple input with label and icon

```
Ruby/Slim


div(uk-grid class="uk-margin")
        div(class="uk-width-1-3@m uk-width-1-1@s")
          = f.label :cell_phone, class: "uk-form-label"
          .uk-inline
            span class="uk-form-icon" uk-icon="icon: receiver"
            = f.text_field :cell_phone, class:"uk-input uk-form-small"
```

### What is actually happening?

The width of the input is incorrect. 
The icon is override by the text enter by the user

But it's working without the `.uk-form-small` class

**Comment by janschoenherr** [comment]
This seems to have been fixed.
