### ISSUE TITLE
Bug: Dropdown element - can't prevent hiding by returning false

### ISSUE THREAD

**Issue by ericfrank** [uikit/uikit#3306]
### UIkit version
3.0.0-beta.40

### Browser
Chrome - latest

### Reproduction Link
https://codepen.io/ericfrank/pen/yKKKzg

### Steps to reproduce
Add an event listener for `beforehide` and return false.

### What is Expected?
The dropdown element should be prevented form hiding, as per the docs: https://getuikit.com/docs/dropdown#javascript

### What is actually happening?
The dropdown element hides.

Thank you so much for making UIkit a great framework! I love it!

**Comment by janschoenherr** [comment]
I believe `return false` is used by jQuery.

UIkit 3 no longer uses jQuery. You'll now have to defaultPrevent the event.

```
dropdown.addEventListener('beforehide', function (e) {
  e.preventDefault();
});
```

**Comment by ericfrank** [comment]
@janschoenherr Thanks!
