### ISSUE TITLE
[Feature Request] Scroll, Scrollspy & Parallax Scoped to Arbitrary Containers

### ISSUE THREAD

**Issue by luxlogica** [uikit/uikit#3307]
## Issue
The Scroll, Scrollspy and Parallax components of UIKit3 function by measuring and moving the scrolling of the **body** of the page. There are many use cases, however, when we need to have these components working with elements inside an arbitrary (overflowing) container instead - e.g., applying a parallax effect to elements inside an auto-overflowed modal window, inside a tab component, or triggering scrollspy as the user scrolls up and down the lengthy contents of an off-canvas sidebar. In these cases, the components should work by measuring the position of the targeted elements inside their parent container, not the viewport, and should be scrolled inside that container.

## Example Use-Case
Here we have a modal window that contains a long CASE STUDY. The content in the window is going to be extensive - divided into at least 4 sections. The modal was setup as a standard UIKit3 modal, containing a `uk-modal-header` that has been specially styled, and a `uk-modal-body` set to auto overflow (with `uk-overflow-auto`).

<img width="638" alt="screen shot 2018-03-31 at 11 10 34 am" src="https://user-images.githubusercontent.com/2994472/38157829-636d6e1c-34d6-11e8-9963-1994d1d2374d.png">

Although the modal header is 'fixed', we would like to be able to use the Parallax component to make the title disappear from view as the visitor scrolls up - leaving only the mini-navbar in the header, like this:

<img width="631" alt="screen shot 2018-03-31 at 11 14 27 am" src="https://user-images.githubusercontent.com/2994472/38157896-1f885a76-34d7-11e8-87ab-4fc3181c5009.png">

We also would like to use the Scrollspy component to actively highlight the currently viewed section of the modal, as the user scrolls up:

<img width="633" alt="screen shot 2018-03-31 at 11 15 21 am" src="https://user-images.githubusercontent.com/2994472/38157902-3cbf5112-34d7-11e8-9e32-ad35af3a7827.png">

Last of all, we'd also like to use the Scroll component to make the modal scroll smoothly to the appropriate section _within the modal_, when clicked.

Right now, none of this is possible - because these components work only with the 'body' of the page, and are not able to measure the position or scroll into view elements that are inside overflowing containers - as in the example of our modal above.

## Feature Request
What we need is an extra configuration option in all 3 components, that allows us to specify an arbitrary element, to which the  `scope`  of the scroll/scrollspy/parallax effect will apply/be based on - e.g. `scope: #container`. This would be an optional setting, with the default being `scope: body`, reflecting the functionality we have now.

Example:

```
// scrolls element #my-id into view inside element #container (instead of inside viewport):
<a href="#my-id" uk-scrol="scope: #container">...</a>

// applies 'uk-animation-fade' class as div scrolls into view inside #container (not viewport):
<div uk-scrollspy="cls:uk-animation-fade; scope: #container">...</div>

// updates items in scrollnav as they scroll into view inside #container (not viewport):
<ul class="uk-nav uk-nav-default" uk-scrollspy-nav="closest: li; scroll: true; scope: #container">
...
</ul>

// this div applies parallax effect to element #target as it's scrolled inside element #container:
<div uk-parallax="target: #target; scope: #container">...</div>
```

This may relate/overlap with Issue #2865 and #3100.

**Comment by jayvarner** [comment]
Yes please!

Would this be a matter of providing a way to pass a container element to the isInView function? So that it scopes to the element but fallback to window if no element is provided? https://github.com/uikit/uikit/blob/827f8f0b33a08a543184e0b59c8ee1f404eec756/src/js/util/dimensions.js#L297-L308

I could try to dig into this, but I'm generally unfamiliar with UIkit's internals and can't really gauge right off how complex this would be.

**Comment by kevingrabher** [comment]
+1 here, top priority for more complex page layouts

**Comment by janschoenherr** [comment]
This should work with 3.2.4
