### ISSUE TITLE
Use calc() in your variable definitions

### ISSUE THREAD

**Issue by andreibarbuta** [uikit/uikit#3309]
I am using sass to compile UiKit and I get errors of "Undefined variables". The reason is that I have defined some core variables with values other than pixels. The solution is to use calc() everywhere there is variable defined or a hook that contains a formula, like adding/subtracting,multiplying etc. other variables or with px values.

It is really tedious to import every file that has this issue and add calc() myself. Also I am forced to do it even if I don't use the component.

Thank you for everything you have done! UiKit is awesome!

**Comment by andreibarbuta** [comment]
Has anyone seen this?

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
