### ISSUE TITLE
Offcanvas is broken on 3.0.0-beta.41

### ISSUE THREAD

**Issue by ritzywhiz** [uikit/uikit#3313]
### Steps to reproduce
It's happening on the official documentation too,

https://getuikit.com/docs/offcanvas

### What is Expected?
It will break after closing the offcanvas.

### What is actually happening?
Broken layout as seen below,

![uikit-3 0 0-beta 41-offcanvas-bug](https://user-images.githubusercontent.com/30728059/38339611-b09a924a-38a1-11e8-9e39-2c6315da00f0.jpg)

Edit:
Windows 1709 (16299.309)
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299

**Comment by zzseba78** [comment]
Confirmed in Safari, Chrome and Firefox, latest.

**Comment by janschoenherr** [comment]
Fixed with 03680270919c29d997350e5f68ea278b6dafb852

We'll release an update soon
