### ISSUE TITLE
Modal Confirm width

### ISSUE THREAD

**Issue by rodolfobubb** [uikit/uikit#3316]
Hi, is there any way to change modal confirm width? 

My code:
```

     UIkit.modal.confirm('Are you sure?', {
        labels: {
          ok: 'Yes',
          cancel: 'No'
        }
      }).then(function() {

      }, function() {

      });
```

I need to add a class to uk-modal dialog, it's possible? because i need to change the width only for this modal.

**Comment by zzseba78** [comment]
Hi! To get help from the community to here, this is for other purpose.
https://github.com/uikit
