### ISSUE TITLE
Placeholder text and input value when adding small or large form to inputs with icon is not padded

### ISSUE THREAD

**Issue by mechanic22** [uikit/uikit#3318]
### UIkit version
3.0.0-beta.40

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/mxzNrx

### Steps to reproduce
Add uk-small or uk-large-form to input with icon
### What is Expected?
padding to exist correctly

### What is actually happening?
no padding

**Comment by mechanic22** [comment]
Shoot sorry, just noticed this was fixed in beta41

**Comment by zzseba78** [comment]
@mechanic22 Why don´t you close it?

**Comment by mechanic22** [comment]
Sorry didn't know I could
