### ISSUE TITLE
Slideshow UL tag is controlled by js default height

### ISSUE THREAD

**Issue by yinge-huyinghuan** [uikit/uikit#3321]
### UIkit version

3.0.0-beta.42

### Steps to reproduce
The slideshow UL tag is controlled by js by default with css:height. The uk-height-viewport directive is invalid! Thank you,UiKit is awesome!

**Comment by zzseba78** [comment]
Did you check the test page of Slideshow, because seems to work fine for me.
https://getuikit.com/assets/uikit/tests/slideshow.html

**Comment by zzseba78** [comment]
Did you check the Test page for Slideshow?
Seems to work fine for me, see the code in the inspector of the Viewport Height example:
```
<ul class="uk-slideshow-items" uk-height-viewport="min-height: 300" style="box-sizing: border-box; min-height: 100vh;">
```
It takes the height in vh units.

**Comment by yinge-huyinghuan** [comment]
Thank you very much for your answer. I added ratio:false in uk-slideshow and it is now normal. This is not a problem when upgrading to 3.0.0-beta.42 because it is not necessary to do so in the 3.0.0-beta.40 version. Thanks again! !

**Comment by zzseba78** [comment]
You are welcome, if it´s resolved please close this issue 👍
