### ISSUE TITLE
uk-widths 2-4, 2-6, 3-6, 4-6 fail in uk-grid #bug

### ISSUE THREAD

**Issue by klor** [uikit/uikit#3322]
### UIkit version
3.0.0-beta.42

### Browser
Firefox 59.0.2

### Reproduction Link
https://codepen.io/klor/pen/GxPVzx

### Steps to reproduce
Load the codepen page and inspect the resulting page.

### What is Expected?
Correct width of uk-widths 2-4, 2-6, 3-6, 4-6 when placed inside `<div uk-grid>` tags.

### What is actually happening?

Visual inspection of the rendered page shows that these widths are failing in the [grid](https://getuikit.com/docs/grid) (that is, uk-widths are failing in the uk-grid). I see the condition when 1) adding background color to each grid, in this situation the background color is not shown correctly and 2) adding text which is also not shown correctly (failing in the same uk-width's as background-color).

* `.uk-width-2-4`
* `.uk-width-2-6`
* `.uk-width-3-6`
* `.uk-width-4-6`

### Screenshot

![image](https://user-images.githubusercontent.com/129573/38517839-87ce03b8-3c3b-11e8-9736-48994770a349.png)

**Comment by aarongerig** [comment]
That‘s intentional behaviour. Mathematically `2/4` equals `1/2` (`.uk-width-1-2`), `2/6` equals `1/3` (`.uk-width-1-3`) and so on ...

Hope this helps!

**Comment by zzseba78** [comment]
UIkit remove redundancy into each set of unit classes, so that for instance instead of .uk-width-3-6 you should use .uk-width-1-2.
https://getuikit.com/docs/width

**Comment by klor** [comment]
Noted. Thanks.

**Comment by GBH** [comment]
`1-6`, `2-6`, `3-6` adds up to `6-6` so it's 100% width.
`1-6`, `1-3`, `1-2` adds up to... let me get my calculator.
