### ISSUE TITLE
Input does not respect Responsive Alignment

### ISSUE THREAD

**Issue by garethwarry** [uikit/uikit#3323]
### UIkit version
3.0.0-beta.42

### Browser
Chrome 65

### Reproduction Link
https://codepen.io/anon/pen/PRVNqd

### Steps to reproduce
1. Place an input checkbox with uk-align-right@m in a table column.
2. Resize the screen

### What is Expected?
Alignment only works on input text boxes according to its responsive @ tag. For example uk-align-right@m should only align right for screens larger than 960px. It should also be aligned correctly with the space it occupies. 

### What is actually happening?
Alignment doesn't take the @ tag into consideration at all, and always aligns right. On small enough screens when the responsive table changes over to a grid like presentation, the alignment also creates a new line rather than aligning to the right of the row.

Edit: See clarification here https://github.com/uikit/uikit/issues/3323#issuecomment-380170409

**Comment by zzseba78** [comment]
Do you know exaclty what you are doing?
I mean: 

- uikit classes works as expected, you have uk-align-right, uk-align-right@s and uk-align-right@m in each element, and they get the desired result in each breakpoint
- uk-align-* **float** elements, why don´t you use text align in the td to align the checkbox?
https://getuikit.com/docs/text#text-alignment

**Comment by garethwarry** [comment]
My apologies, I probably don't know exactly what I'm doing. I replaced the uk-align-right references with uk-text-right, and that seems to make them not align at all. Combining them did produce the result I wanted (the checkboxes on the right side), but it doesn't account for responsiveness. I tried both orders: "uk-text-right@s uk-align-right@s" and "uk-align-right@s uk-text-right@s". Thoughts?

Thanks for the reply!

**Comment by zzseba78** [comment]
Did you apply `uk-text-right@m` to the parent element of the checkbox? ( td )
Do you want to achieve someting like this ( checkbox at the right )?
https://codepen.io/zzseba78/pen/jzdVRq

**Comment by garethwarry** [comment]
Not quite. I was aiming for the checkbox to be on the right with a responsive table on mobile screens, and a normal table with the checkbox on the left for desktop screens. I tried adding the alignments to the rows as well, but to no avail.

**Comment by zzseba78** [comment]
Ok, since this is more a usage questions than an issue, you can close this issue and ask the uikit community for help.
https://gitter.im/uikit/uikit

**Comment by garethwarry** [comment]
I appreciate your advice and I'll check out that link. I do feel like this might be a bug though. It definitely tries to align right but carries over to the next line instead. That doesn't seem like the right behavior. Maybe I am doing something wrong, but it doesn't feel like I am. I'll keep things open for more discussion, if that's okay. Thanks!

**Comment by garethwarry** [comment]
**Clarification:** Just a follow up, it appears to be two bugs with responsive tables. 
1. Right alignment in the table header row will always be wrong with just a simple "uk-align-right" tag. The auto-add margins feature is adding too much margin. (https://codepen.io/anon/pen/zWeQYv)
2. All other fields work as long as a responsive @ tag isn't used with uk-align. (same as first posted)

**Comment by zzseba78** [comment]
Hi! Seems that you are a bit lost.
uk-align-* works fine, no problem with it: https://codepen.io/zzseba78/pen/GxzaMB
It´s used to float an element and create some space with , for example, some sourrounding text...
In your case you should alight with `uk-text-right` ( or left, center ), on the th or td element, that´s it.

https://codepen.io/zzseba78/pen/VXgOxX

If the only way it´s to float elements, you can create custom css in media queries, floating things left or right on each breakpoint without margin.

**Comment by garethwarry** [comment]
Right, but you're not using inputs... I'll add that to my clarification post.

**Comment by zzseba78** [comment]
Same thing :)
Please close this since it´s a implementation question, not a bug.
https://codepen.io/zzseba78/pen/VXgOxX

**Comment by garethwarry** [comment]
It is a bug: https://codepen.io/anon/pen/JLxgXQ
The bug is adding a responsive tag.

**Comment by zzseba78** [comment]
¿What do you mean? by adding this? uk-text-right@m?
What do you expect when adding it? the text or child element aligns to the right from medium site and ahead... that´s what happen... i don´t get your point.

**Comment by garethwarry** [comment]
Thank you thank you thank you.
I understand now. I was trying to do this: "uk-text-right uk-text-left@m"

**Comment by zzseba78** [comment]
ok
