### ISSUE TITLE
found bugs version 3.0.0 beta 36-42 about <nav class="uk-navbar-container" uk-navbar="dropbar: true;">

### ISSUE THREAD

**Issue by teraponR** [uikit/uikit#3325]
found bugs version 3.0.0 beta 36-42 about use  class="uk-navbar-container" uk-navbar="dropbar: true;

### UIkit version

3.0.0-beta.42

**Comment by aarongerig** [comment]
Closing this, because of lack of information. Please describe your problem in a new issue with more detail!
