### ISSUE TITLE
Stacking Table Responsiveness Modifier

### ISSUE THREAD

**Issue by garethwarry** [uikit/uikit#3328]
### UIkit version
3.0.0-beta.42

### Browser
Chrome 65

### Reproduction Link
https://getuikit.com/docs/table#stack-on-small-viewports

### Steps to reproduce
1. Create a table using the example above.
2. Unable to tell the table when to start stacking.

### What is Expected?
Able to modify when the table stacks using responsive at tags (such as @m)

### What is actually happening?
Unable to modify when the table stacks. Unfortunately, makes it unusable for large tables.

**Comment by garethwarry** [comment]
Ahhh! Thank you!

**Comment by zzseba78** [comment]
You are welcome
