### ISSUE TITLE
How to stop Sticky at the bottom?

### ISSUE THREAD

**Issue by Surbma** [uikit/uikit#333]
Hi,

I'm using the sticky js to stick a sidebar widget. My problem is, that I can not stop it at the bottom and it goes through the comments, footer widgets and the footer.

It should have an option to stop the sticky behavior somewhere. Twitter Bootstrap has this option, but it has only pixel option. I want an option to set a class and if the sticky block reaches the bottom of this class' block, it changes back to normal.

See a live, working example here on the right sidebar, that's exactly, what I want to have: http://www.smartpassiveincome.com/hangouts-on-air-for-webinars/

**Comment by Uranbold** [comment]
+1 for Bottom Oriented. Sticky Sidebar need to Stick with Top and once Scroll down then Stick at bottom.
[https://i.stack.imgur.com/VAVaP.png](url)
