### ISSUE TITLE
npm install uikit - do we need Jquery? 

### ISSUE THREAD

**Issue by eshwarenm** [uikit/uikit#3331]
Trying to use UIkit with React via create-react-app. 

I noticed, Jquery is not needed. Tried Offcanvas, Notifications and some other components, all doesn't need Jquery. Checked the package.json for UIkit, no Jquery there as well. 

Looked at the VueJS example for UIkit docs, the last commit for package.json, was to remove Jquery dependency. 

So, to Jquery or not Jquery, that is the question.

**Comment by lupuxyz** [comment]
Jquery is not needed.

**Comment by aarongerig** [comment]
As @lupuxyz said, you don't have to use jQuery in order to make UIkit work.
