### ISSUE TITLE
Viewport Height Incorrect on Mobile: uk-height-viewport

### ISSUE THREAD

**Issue by garethjensen** [uikit/uikit#3339]
### UIkit version
3.0.0-beta.42

### Browser
Chrome 65

### Reproduction Link
https://codepen.io/anon/pen/oqrvJz

(Not reproducable in codepen - must be a standalone file)
```
<!doctype html>
<html style="height: 100%">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	
	<title>UIkit Example</title>
	<link rel="manifest" href="appmanifest.json">
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" href="lib/uikit-3.0.0-beta.42/css/uikit.min.css" />
	
	<!-- Script Imports -->
	<script src="lib/uikit-3.0.0-beta.42/js/uikit.min.js"></script>
	<script src="lib/uikit-3.0.0-beta.42/js/uikit-icons.min.js"></script>
</head>

<body>
<div class="uk-offcanvas-content">
  <nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left uk-margin-small-left">
      <a class="uk-navbar-toggle uk-hidden@m" uk-toggle="target: #offcanvas-overlay" href="#">
        <span uk-navbar-toggle-icon></span>
      </a>
      <a href="#" class="uk-navbar-item uk-logo">
        Test App
      </a>
    </div>
  </nav>
  
  <main id="contentarea" class="uk-text-small">
    <div uk-height-viewport="offset-top: true">
      Test
    </div>
  <main>
</div>

<div id="offcanvas-overlay" uk-offcanvas="mode: push; overlay: true">
  <div class="uk-offcanvas-bar uk-padding-remove">
    <button class="uk-offcanvas-close uk-text-right" type="button" uk-close></button>

    <div class="uk-padding uk-text-left">
      <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
        <li><a href="#">Test</a></li>
        <li><a href="#">Test</a></li>
        <li><a href="#">Test</a></li>
      </ul>
    </div>
  </div>
</div>
</body>
</html>
```

### Steps to reproduce
1. Save code as index.html
2. Host the file somewhere that can be accessed by a phone
3. Open the file in Chrome on a mobile device

### What is Expected?
`uk-height-viewport="offset-top: true"` uses the available screen viewport on load and the content area is not scrollable.

### What is actually happening?
`uk-height-viewport="offset-top: true"` does not account for the collapsible navigation bar in mobile versions of Chrome (a bug caused by using 100vh, which uk-height-viewport does). The content area scrolls due to the height being calculated incorrectly.

**Comment by zzseba78** [comment]
Works perfectly fine for me in Chrome from OSX 11.

In your case you have a **bad implementation**, uk-height-viewport="offset-top: true" should be applied to `<main id="contentarea" class="uk-text-small">`, so it could know what´s the the element that precedes it.

So, as a recommendation ( take it or leave it ), **before you create a new issue**:

- Check the docs , maybe you are doing something wrong, and more likely if you are new with uikit.

- Ask the community for help, there are people that can help you. https://github.com/uikit

Good luck.

**Comment by zzseba78** [comment]
What you mean by aggressive?
I´m just telling you that check before creating an issue, you already create about 4 issues that where bad implementations.
```
<main id="contentarea" class="uk-text-small" uk-height-viewport="offset-top: true">
    Test
  <main>
```
For example, you don´t want to close the main tag?

**Comment by garethwarry** [comment]
Just saying, I don't post a solution to a problem and demand the person closes an issue and reviews posting guidelines on how to post an issue without testing my solution first. I appreciate your willingness to help, really - but I'm not here to defend my code. Tag is closed now, but I'm still experiencing the same issue. I found the following resource: https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser. It appears to be their use of 100vh that's causing the behaviour.

```
<!doctype html>
<html style="height: 100%">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	
	<title>UIkit Example</title>
	<link rel="manifest" href="appmanifest.json">
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" href="lib/uikit-3.0.0-beta.42/css/uikit.min.css" />
	
	<!-- Script Imports -->
	<script src="lib/uikit-3.0.0-beta.42/js/uikit.min.js"></script>
	<script src="lib/uikit-3.0.0-beta.42/js/uikit-icons.min.js"></script>
</head>

<body>
<div class="uk-offcanvas-content">
  <nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left uk-margin-small-left">
      <a class="uk-navbar-toggle uk-hidden@m" uk-toggle="target: #offcanvas-overlay" href="#">
        <span uk-navbar-toggle-icon></span>
      </a>
      <a href="#" class="uk-navbar-item uk-logo">
        Test App
      </a>
    </div>
  </nav>
  
  <main id="contentarea" class="uk-text-small" uk-height-viewport="offset-top: true">
    Test
  </main>
</div>

<div id="offcanvas-overlay" uk-offcanvas="mode: push; overlay: true">
  <div class="uk-offcanvas-bar uk-padding-remove">
    <button class="uk-offcanvas-close uk-text-right" type="button" uk-close></button>

    <div class="uk-padding uk-text-left">
      <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
        <li><a href="#">Test</a></li>
        <li><a href="#">Test</a></li>
        <li><a href="#">Test</a></li>
      </ul>
    </div>
  </div>
</div>
</body>
</html>
```

**Comment by zzseba78** [comment]
I test my solution, i tell you that i see it fine in Chrome from OSX.
Did you see this fine?
http://test.byhumans.works/viewport.html

**Comment by jzachary** [comment]
Having the same issue, what did you do to resolve it?

**Comment by janschoenherr** [comment]
I will close this issue for now. If the issue persists and is a bug on our side, please comment.

**Comment by adrianbj** [comment]
I really don't understand why this was closed. The issue still remains on mobile browsers (I am testing on Chrome / Android). Even the https://getuikit.com/assets/uikit/tests/height-viewport.html shows the problem. It effectively makes this feature useless.

Not sure if you guys would prefer a new issue posted for this - I know some teams prefer it and others would rather follow ups to the original so all info is in the same place, so apologies if I am not following local protocol.

Thanks.

**Comment by kimamil** [comment]
+1
