### ISSUE TITLE
Feature Request: Add targets option to Slider and Slideshow

### ISSUE THREAD

**Issue by shenst1** [uikit/uikit#3342]
Right now the Slideshow and Slider components do not have a `targets` option. It seems like the slides have to be the direct children of the `uk-slideshow-items`. I would be great if there was a `targets` option that worked just like the `uk-accordion` component. 

targets | String | > * | CSS selector of the element(s) to toggle.

**Comment by janschoenherr** [comment]
Could you provide a use case for changing the slides selector?
