### ISSUE TITLE
Cannot get UIkit Icons to display in create-react-app

### ISSUE THREAD

**Issue by damey2011** [uikit/uikit#3346]
I cant seem to get the UIkit icons to display in my create-react-app. I've followed the configuration on the official site, but they still dont display
Here is my index.js

`import React from 'react';`
`import ReactDOM from 'react-dom';`
`import registerServiceWorker from './registerServiceWorker';`
`import './assets/uikit/css/uikit.min.css'`
`import './assets/css/style.css'`
`import './assets/css/card-styles.css'`
`import './assets/css/follow-card-styles.css'`
`import 'uikit/dist/js/uikit-core.min'`
`import {Provider} from "react-redux";`
`import store from './store'`
`import {routes} from "./routes/index";`
`import UIkit from 'uikit';`
`import Icons from 'uikit/dist/js/uikit-icons';`
``
`// loads the Icon plugin`
`UIkit.use(Icons);`
``
`ReactDOM.render(`
`    <Provider store={store}>`
`        {routes}`
`  </Provider>`
`   , document.getElementById('root'));`
`registerServiceWorker();`
`

**Comment by AnanlaTech** [comment]
Found any solution?

**Comment by janschoenherr** [comment]
```
import React from 'react';
import './App.css';
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';
UIkit.use(Icons);

function App() {
  return (
    <div className="App">
      <span uk-icon="home"></span>
    </div>
  );
}

export default App;
```

That seems to work fine for me. If the issue persists, please comment.
