### ISSUE TITLE
Dropdown Toggle doesn't work in table cell with truncated text 

### ISSUE THREAD

**Issue by shawjak3** [uikit/uikit#3347]
### UIkit version

3.0.0-beta.42

### Browser
Chrome

### Reproduction Link

https://codepen.io/shawjak3/pen/gzOZXK
### Steps to reproduce
Hover over column 5 to see dropdown and then column 3 to see its not working

### What is Expected?
Column 3 dropdown should work

### What is actually happening?
Hey guys I am having a weird issue, if I truncate text in a table the dropdown toggle doesn't work but if its not truncated the dropdown works correctly. See codepen above

**Comment by shawjak3** [comment]
Removing the `overflow: hidden` solves the issue but breaks the text truncate.

**Comment by happilymarrieddad** [comment]
+1. I am having this problem as well. @saschadube @janschoenherr

**Comment by Sam-Gram** [comment]
I figured out a hack workaround. I'm just not familiar enough with uikit. Hopefully this helps.

https://codepen.io/sam-gram/pen/PemLjw

**Comment by janschoenherr** [comment]
You can use the `container` option, to let UIkit append the drop outside the text-truncated table cell.
