### ISSUE TITLE
None of my dropdowns are working.

### ISSUE THREAD

**Issue by Tinypadfoot** [uikit/uikit#3349]
### UIkit version

3.0.0-beta.42

### Browser
Safari, Chrome
### What is Expected?
Dropdown working
### What is actually happening?
Dropdown not working

Hi, I can't seem to get any dropdown to work with UIKit, whether it's in a navbar or a button. I've tried testing it by copying the exact same code and it still doesn't work. I'm using the latest version. I made sure I included the cdn and js calls on my html. 

I'm new to Django, Python, and UIKit. I decided to try UIKit because Bootstrap was confusing for me. 

I tried this very simple example copied and pasted the exact code:
<div class="boundary uk-panel uk-placeholder uk-width-2-3@s">

    <button class="uk-button uk-button-default uk-float-left" type="button">Hover</button>
    <div uk-dropdown="boundary: .boundary">
        <ul class="uk-nav uk-dropdown-nav">
            <li class="uk-active"><a href="#">Active</a></li>
            <li><a href="#">Item</a></li>
            <li class="uk-nav-header">Header</li>
            <li><a href="#">Item</a></li>
            <li><a href="#">Item</a></li>
            <li class="uk-nav-divider"></li>
            <li><a href="#">Item</a></li>
        </ul>
    </div>

It doesn't work. Instead, it displays all the list items instead of it being hidden and dropping down.

Thanks.

**Comment by m0yP** [comment]
Have you tried to use the Uikit files locally? Dropdowns are working fine here, though.

**Comment by Tinypadfoot** [comment]
@m0yP I have downloaded Uikit in my system and saved it in the same directory as my projects, if that's what you mean. But I still put the link in my html file.

**Comment by Tinypadfoot** [comment]
@m0yP I realized I haven't linked the correct JS call to my html file. I'm sorry. It's working now. But you gave me the idea on how to fix it and where to look. Thanks!

**Comment by m0yP** [comment]
Glad it worked! You may now close this one ;)
