### ISSUE TITLE
uk-active ignored when combined with a striped table

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#3351]
### UIkit version
3.0.0-rc5

### Browser
Tested in Chrome, FF, Safari

### Reproduction Link
https://codepen.io/miljan/pen/Ryodxp

### What is Expected?
The active row to be visible in both tables.

### What is actually happening?
Is only visible when the table is not striped.

**Comment by saschadube** [comment]
Fixed a8936702620142baeb9af078e859107c9e584e40
