### ISSUE TITLE
Slideshow jitters when hover over parent nav new issue in Version 3.0.0-Beta.42

### ISSUE THREAD

**Issue by brahmaforces** [uikit/uikit#3354]
I used Beta .39 and this issue was not there, but in .42 it is there. If you have a parent nav with children in the header and a slideshow below it, just hovering over the parent nav, will cause the slideshow to jitter in a very prominent way. 

### UIkit version

3.0.0-beta.42

**Comment by zzseba78** [comment]
I experience this issue, try using `ratio:false`

**Comment by janschoenherr** [comment]
Is this still an issue? I will reopen the issue if so.
