### ISSUE TITLE
[Feature Request] Inverted Navigation Hover (animation)

### ISSUE THREAD

**Issue by shiftgeist** [uikit/uikit#3356]
I like it when the nav are all active at the start and when hovering the siblings decrease their opacity. I would love to use some uk-navbar-nav-inverted or uk-navbar-nav-alt (playing around for naming)

[Demo](https://codepen.io/fxmt/pen/aYPYqX)

**Comment by zzseba78** [comment]
Hi @fxmountain , i don´t think this feature it´s needed on the core uikit, it´s a quite specific implementation, you can achieve it easy with some css lines.

https://codepen.io/zzseba78/pen/zjzXpb

If it helps you please close this issue.

**Comment by fxmountain** [comment]
Understandable, have a nice day :+1:

**Comment by zzseba78** [comment]
Thanks! Did you check the codepen?

**Comment by fxmountain** [comment]
Yes this absolutly works for me, thanks!

**Comment by shiftgeist** [comment]
*can be close*
