### ISSUE TITLE
Modal closing doesn't work on 2nd call

### ISSUE THREAD

**Issue by gzamb** [uikit/uikit#3362]
### UIkit version

3.0.0-beta.42

### Steps to reproduce
I'm using modals to create/edit db objects.  I open all my modals through with the anchor tag:
`<a (click)="openNewModal()"  uk-icon="icon: plus-circle" uk-toggle="target: #new-open-modal"></a>`
All my modals have a `Cancel` and `Save` button:
`<button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
   <button class="uk-button uk-button-primary" (click)="save()" type="button">Save</button>`

When you click the cancel button, the `uk-modal-close` is used.  But when I save something, I want the JS code inside the `save()` function to close the modal (`UIkit.modal('#new-open-modal').hide()`) so that if there are errors on saving it will display them to the user.  This code works fine if I just start it fresh, but if I save something, navigate to another part of the webpage and come back to edit again the `save()` does not close the modal. Everything else works fine, I update the object in the backend and receive a success but for some reason it will no longer close the modal and it enters a weird state where the only thing I can do is refresh the page.

The only thing I can find that seems to be different when I print out the modal object is that the 2nd time around it no longer has the `.uk-open` class attached to it even though the modal is open.  Is there anything I'm doing wrong or is this just a bug?

**Comment by gzamb** [comment]
@seonixx I did, what I ended up doing was declaring the model variable `myModal = UIkit.modal('#new-open-modal')` in my ngOnInit() function (I'm using Angular 5) and then using click functions to show/hide the modal rather than relying on the classes in the html tags.  It works fine now.

**Comment by jsiwek11** [comment]
Was having the same problem. The first time the modal is shown, the html elements of the modal are rendered in the browser. If the user hides the modal, hits another component and comes back to the component with the modal, re-showing the modal actually renders duplicate html elements for the modal, and the hide() method tries to hide the 1st instance of the modal with the now duplicated id, which is of course is already hidden. The 2nd (or more) instance remains shown.

The work around that @gzamb proposes above also worked to fix this for me. Doing it this way avoids duplicate modal html blocks.

**Comment by janschoenherr** [comment]
Is this still an issue with the latest UIkit version 3.2.1? There has been some work on refactoring the opening/closing of modals. If so, please comment with a minimal Codepen.
