### ISSUE TITLE
When switcher is manually instantiated links inside it do not work

### ISSUE THREAD

**Issue by LSDD** [uikit/uikit#3364]
Hi when i instantiate a switcher component using javascript the links inside stop working. 

### UIkit version
3.0.0-beta.42

### Browser
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/lsdd/pen/NMXgYe

### Steps to reproduce
Click on the link inside the switcher

### What is Expected?
visit the link

### What is actually happening?
nothing

**Comment by aarongerig** [comment]
Works fine: https://codepen.io/aarongerig/pen/zjpdRP

**Comment by LSDD** [comment]
hmm must be something to do with manually triggering the switcher.

https://codepen.io/lsdd/pen/LmezGa

**Comment by aarongerig** [comment]
Nope, you're setting the switcher on the wrong element. Check this pen again: https://codepen.io/aarongerig/pen/pVpdzx

Also, you don't event have to trigger the `show` function in that scenario.

**Comment by LSDD** [comment]
Thanks for the clarification @aarongerig
