### ISSUE TITLE
uk-grid-match not working for nested child

### ISSUE THREAD

**Issue by badpenguin** [uikit/uikit#3365]
### UIkit version
3.0.0-beta.42

### Browser
Chromium

### Steps to reproduce
The uk-height-match DOES work if i use the class ".corso" that is my "card" class.
Instead it does NOT work if i use ".content", the class of the body of the card.
On uikit2 the same code was working.
I also tried removing the scrollspy+animation just to check that if that was the problem but no luck.
I need to achieve a fixed header and footer but a dynamic height body.

UPDATE:
The problem only happen using the pre-build downloaded from github's release page.
If i build the JS locally then it works! O.o

```	
<div uk-height-match="target: .content" uk-grid uk-scrollspy="target: .corso;cls:uk-animation-fade; delay:300">
<div class="uk-width-1-1 uk-width-1-3@s">
<div class="corso" >
<img src="img/corso-ionic-base.png" alt="Ionic BootCampo - corso Base">
<div class="content">
<h3>Ionic BootCamp 2</h3>
...
```

**Comment by janschoenherr** [comment]
I will close this for now. If the issue persists please comment.
