### ISSUE TITLE
Icons double-painted in latest Firefox (FF60)

### ISSUE THREAD

**Issue by networkimprov** [uikit/uikit#3368]
### UIkit version
3.0.0-beta.42

### Browser
Firefox 60 on Win7 64bit (not an issue in FF59)
With Vue.js 2.5.16

### Reproduction Link
https://jsfiddle.net/eecd7bqd/

### What is Expected?
1 SVG icon

### What is actually happening?
2 SVG icons
```
<span uk-icon="copy" class="uk-icon">
<svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ratio="1">...</svg>
<svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ratio="1">...</svg>
</span>
```

**Comment by networkimprov** [comment]
Added reproduction link. Thanks for your attention...

**Comment by janschoenherr** [comment]
For now, the easiest workaround would be to use Vue's _v-bind_ directive:

https://jsfiddle.net/t75vumcr/

I am closing this issue as it has come up multiple times and we are aware of the situation.
