### ISSUE TITLE
Slideshow init twice on document ready

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3369]
### UIkit version
3.0.0-beta.42

### Browser
All browsers

### Reproduction Link
https://codepen.io/anon/pen/RyyPjd

**Comment by flihub** [comment]
Any suggestion on this ?

itemshow, itemshows events also trigger on browser resize. 

Maybe we need "change" event that only trigger on index change ?

**Comment by Jdeboysere** [comment]
Did you fix your problem?
If not, do you use Google Maps API in your page?

**Comment by razvanioan** [comment]
It still happens on 3.0.0-RC11

Slideshow `itemshown` event is triggered multiple times (for first slide item) on initialization.
On future browse between slides, it's working as expected

Check browser console on the following pen: https://codepen.io/qdev/pen/yxNBYO

**Comment by janschoenherr** [comment]
This should be resolved with the latest dev version. Can somebody confirm that it's working as expected?

**Comment by flihub** [comment]
tested with dev version : https://codepen.io/anon/pen/YoxLEy

initial load first item event not fired.

**Comment by janschoenherr** [comment]
@flihub I believe the event has already fired, when your code is executed.

**Comment by flihub** [comment]
so how we catch 0 index ?

if init slideshow via js first event item fired : https://codepen.io/anon/pen/mZMNQO

**Comment by janschoenherr** [comment]
@flihub Thanks, it should be possible with the latest dev build now. Just listen for the event outside the `ready` callback.

**Comment by flihub** [comment]
with latest dev fixed: thanks.

https://codepen.io/anon/pen/jjvpwq
