### ISSUE TITLE
Slider next slide disappears

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3370]
### UIkit version

3.0.0-beta.42

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/jxKoBg

### Steps to reproduce
Drag the slide to the right, you will see the "Hello how are you?" disappear, if you move to the next slide the slide that should becoming after doesn't show.

### What is Expected?
It should be shown

### What is actually happening?
It's disappearing. 

Strangely this isn't happening on your live site, however, I can replicate it. 

Edit: 
The slider just breaks down if there is 3 elements. The infinite repeat doesn't work and you get this bug.

**Comment by janschoenherr** [comment]
Yes, the `center` option is currently not supported for 3 items. This is due to how and when the reordering is happening at the beginning of the "switch". The "missing" slide is actually sorted to the left of the active slide, because part of it is visible at the beginning of the transition.

**Comment by janschoenherr** [comment]
Seems to be fixed.
