### ISSUE TITLE
Navbar does not collapse on mobile view.

### ISSUE THREAD

**Issue by elroychibex** [uikit/uikit#3371]
### UIkit version

3.0.0-beta.42

**Comment by zzseba78** [comment]
This isn´t how UIkit works. You can use the Visibility component to show or hide elements, and offcanvas for mobile navigation.

Here you have some examples:
https://github.com/zzseba78/Kick-Off

Plase close this since it´s not an issue.

**Comment by elroychibex** [comment]
Thank you for the clarification
