### ISSUE TITLE
Tooltip doesn't work on programmatic use

### ISSUE THREAD

**Issue by imarkdesigns** [uikit/uikit#3372]
### UIkit version

3.0.0-beta.40 (i tried beta.39 same issue, or even beta.42)

### Browser
Safari (mac), Chrome (mac)

### What is Expected?
When document load, it should default show the Tooltip with option of `pos: bottom`. As related to that without the programmatic use of the script, it default to show on top.

### What is actually happening?
I have default attribute from the html code (see code fig.1), but we would like to make the tooltip show-up as default when the content/document loads. Unfortunately, console throw an error stating that the `bottom` position is undefined or undefined variable.

Code fig.1
```
<button uk-toggle="target: #video-introduction" type="button" class="playButton" uk-tooltip="pos: bottom" title="Watch our Video">
  <span uk-icon="icon: play-circle; ratio: 7;"></span>
</button>
```

Here's the actual code.
```
var showTip = UIkit.tooltip('.playButton', {
  pos: bottom
});
showTip.show();
```

Error Log.
```
ReferenceError: Can't find variable: bottom
```

**Comment by aarongerig** [comment]
https://codepen.io/aarongerig/pen/zjLygY?editors=1010#0

Works fine, hope this helps!

**Comment by imarkdesigns** [comment]
Ok, this was solved my issue. Appreciate your help Aaron!
