### ISSUE TITLE
Scrollspy not working on IE11

### ISSUE THREAD

**Issue by akcreation** [uikit/uikit#3378]
### UIkit version
3.0.0-rc.1

### Browser
IE11 (on windows 8 and Windows 10)

### Steps to reproduce
As soon as I add the 'uk-scrollspy' attribute to any div in my code, it stops appearing in IE11 browser. If I remove the uk-scrollspy attribute it works perfectly.

### What is Expected?
It is expected for the scrollspy to load my div block with whatever animation class I choose to add (in this case 'uk-animation-fade')

### What is actually happening?
Blank content, div is not 'loading' on pageload as it should be

### UPDATE - Have just checked the actual uikit website (to see if the problem was unique to my page) and the scrollspy page (https://getuikit.com/docs/scrollspy) gets the same result in IE11, none of the scrollspy elements appear on the page, so this is defintely a bug

**Comment by janschoenherr** [comment]
Resolved with dd75ce6b5ab143b7aa586238d1c6f7f0fb7bf6e1
