### ISSUE TITLE
Error when building custom CSS with node-sass

### ISSUE THREAD

**Issue by wanze** [uikit/uikit#3380]
### UIkit version

3.0.0-rc.1

### What is Expected?

Custom build with node-sass works as with previous beta version.

### What is actually happening?

node-sass produces the following error message:

`expected ':' after $-moz-document in assignment statement`

The error is thrown in the `utility.scss` component on the following line: https://github.com/uikit/uikit/blob/develop/src/scss/components/utility.scss#L355

### Solution
Rename `$-moz-document` to `@-moz-document`.

**Comment by aarongerig** [comment]
Thanks for reporting, will be fixed with the next release: f25ed57
