### ISSUE TITLE
tab with dropdown; icon generates vertical alignment imperfection of bottom border

### ISSUE THREAD

**Issue by aaronpeterson** [uikit/uikit#3381]
### UIkit version
3.0.0-rc.1

### Browser
Chrome/Firefox

### Reproduction Link
https://codepen.io/anon/pen/VxGBRg

### Steps to reproduce
Create a uk-tab instance and include one or more li with a dropdown and one or more without a dropdown [as illustrated in the docs](https://getuikit.com/docs/tab#tabs-and-dropdown)

### What is Expected?
The ::before bottom border should be precisely vertically aligned with the bottom of the tabs so that the active tab's highlighted (blue, etc) bottom border does not appear above or below the light grey line created by the ::before selector

### What is actually happening?
With the drop down icon ratio set to 1 (default) the height of the drop down item is increased creating an increase in vertical height and pushing down the ::before element's generated line.  The down arrow icon ratio can be reduced to .85 to avoid affecting the drop down tab height

**Comment by janschoenherr** [comment]
Seems to be fixed.
