### ISSUE TITLE
Gulp-sass error

### ISSUE THREAD

**Issue by harebuus** [uikit/uikit#3382]
### UIkit version

3.0.0-rc.1

### Browser

No Browser, in command panel

### Steps to reproduce
Uikit file imported my scss file in my project. I tried gulp to compile scss and then i recived this error:
```
Error in plugin 'gulp-sass'
Message:
    node_modules\uikit\src\scss\components\utility.scss
Error: expected ':' after $-moz-document in assignment statement
        on line 355 of node_modules/uikit/src/scss/components/utility.scss
        from line 84 of node_modules/uikit/src/scss/components/_import.scss
        from line 5 of node_modules/uikit/src/scss/uikit.scss
        from line 25 of src/theme/uikit.scss
        from line 1 of src/theme/theme.scss
>> $-moz-document url-prefix() {
```
I changed "$-moz-document" to "@-moz-document" then gulp-sass worked without errors

### What is Expected?
gulp-sass work without errors

### What is actually happening?
gulp-sass work with errors

**Comment by janschoenherr** [comment]
Duplicate https://github.com/uikit/uikit/issues/3380
