### ISSUE TITLE
Can't set default options for dropdown component in rc version, beta version is ok

### ISSUE THREAD

**Issue by tzd** [uikit/uikit#3388]
Hello,
could someone tell me how to set global options for components in rc version.
I was using beta version (42) and evertything was ok, when I updated UIkit version to latest rc I got error message saying `Cannot read property 'dropdown' of undefined`

Here is my code for setting global options.
`UIkit.components.dropdown.options.defaults.animation = ['sc-animation-scale-up']`

And also could someone tell me where to put this code if I want to also use this options for automatically initialized components. I was using this code for that:
`$.each(UIkit.instances, function( index, component ) {
    if (component.$options.name === 'dropdown' || component.$options.name === 'drop') {
        component.animation = ['sc-animation-scale-up'];
    }
});`

Thank you for all your help.

### UIkit version

3.0.0-rc.2

**Comment by janschoenherr** [comment]
Please use `UIkit.components.dropdown.options.data.animation` instead.

The docs will be updated.

**Comment by tzd** [comment]
Hi, thank you for your answer.
It doesn't help because `UIkit.components` are undefined.
Please check https://codepen.io/anon/pen/xjByKP
Maybe I don't understand how it works in rc but in beta `UIkit.components` returned all components.

**Comment by janschoenherr** [comment]
Thanks, I've updated the docs: uikit/uikit-site@bcbf9d1fca045d2ee0cc95d5b623fe803a748381
