### ISSUE TITLE
Jumping grid

### ISSUE THREAD

**Issue by croffasia** [uikit/uikit#3389]
Just a grid 😕

### UIkit version
3.0.0-rc.2

### Browser
Chrome v.66.0.3359.181, Firefox 60.0.1 (64-bit), Opera 51.0.2830.55

### Reproduction Link
https://coinsignals-dev.herokuapp.com/test

### Steps to reproduce
Enter something to input

### What is Expected?
Each element remains in its place

### What is actually happening?

Something crazy 
https://www.useloom.com/share/f74fa9bbcae54c22934bdcda3a9874d1

**Comment by PoluosmakAndrew** [comment]
**Reproduction Link**
https://coinsignals-dev.herokuapp.com/test

**Comment by zzseba78** [comment]
I don´t think this is uikit related, seems that nux it´s interacting with the dom when you type something in the input.

Check a isolated code example in codepen.
https://codepen.io/zzseba78/pen/erXXyb

**Comment by PoluosmakAndrew** [comment]
@zzseba78 i think its is not  Nuxt. How can NuxtJS changed UIKit classes? I'm don't understand :-)

From official site:
https://getuikit.com/docs/javascript

> Sometimes, components like Grid or Tab are hidden in the markup. This may happen when used in combination with the Switcher, Modal or Dropdown. Once they become visible, they need to adjust or fix their height and other dimensions.

When user enter some text to INPUT field VueJS rerendered this block.

**Comment by janschoenherr** [comment]
This might happen when Vue "redraws" the DOM. If you let Vue set classes on an element and UIkit does too, those classes, set by UIkit, will be reset by Vue. Calling `UIkit.update` might solve this in some cases or setting e.g. the `uk-grid` manually.
We are aware of the issue and are working on a better solution.

**Comment by manuel-di-iorio** [comment]
Also happens with icons and navbars, as janschoenher said, when something happens, Vue removes the "uk-icon" class set by UIKit (check with Inspect element of your browser). 
The workaround is to manually manually write "uk-icon" in the class attribute of the element, same for navbars and grids.
