### ISSUE TITLE
image component not lazy loading background images

### ISSUE THREAD

**Issue by schwaaab** [uikit/uikit#3392]
### UIkit version

3.0.0-rc.2

Chrome & Firefox

The lazy loading on img tags works great. Thanks for that!

The lazy loading for background images though, not so much.
I just tested out the simple version below:

`<div data-src="" uk-img>...</div>`

You can see on your test page https://getuikit.com/assets/uikit/tests/image.html that all the background images are loaded on page load.

**Comment by janschoenherr** [comment]
Thanks, this has been fixed with: 3422862c39f8ba5b1606afec1000b2d3134dd2e0
