### ISSUE TITLE
When slideshow parent is hidden, and then the parent switches to display:block, the slideshow will not show  

### ISSUE THREAD

**Issue by mthomsonnz** [uikit/uikit#3393]
The slideshow will show inside the uikit switcher tabs:
https://codepen.io/matt_nz/pen/JvxOoP

But in other set ups like jquery ui tabs, the slideshow will not show when the tab is displayed:
https://codepen.io/matt_nz/pen/VxgrNz

If the window is resized a little, then the slideshow will show in the tab.
*3.0.0 rc 2

**Comment by violinxsc** [comment]
I found it, do you solve this problem?

**Comment by mthomsonnz** [comment]
Hi I haven't found a solution to this yet

**Comment by aarongerig** [comment]
@mthomsonnz Why not use UIkit's switcher component then? ;)

**Comment by violinxsc** [comment]
With respect, I hardly think that's the point @aarongerig

**Comment by aarongerig** [comment]
@violinxsc To be fair, that's true. But you could solve this problem with some custom JS code. Simply listen for the tabs to "switch" and initialize the slideshow programmatically `UIkit.slideshow()`.

**Comment by violinxsc** [comment]
You're right,but I really don't know how to listen for the tabs to "switch" and initialize the slideshow programmatically.
 I tried it actually and failed.：）

**Comment by mthomsonnz** [comment]
@aarongerig I'm developing a Joomla gallery extension that is listed on the Joomla extensions directory, UIkit is one of the libraries that I'm using. My extension has to work in any website using bootstrap etc..

**Comment by aarongerig** [comment]
@mthomsonnz Ok, then use the switcher if the user wants to use UIkit. If the user wants to use Bootstrap use another switcher / slideshow. No biggie, right?

**Comment by mthomsonnz** [comment]
@aarongerig For the gallery extension, it will be downloaded as a plugin, as used (hopefully) in hundreds of joomla websites and in the future wordpress sites. So the plugin needs to be installed through the joomla/wordpress installer and work out of the box in the sites current website. I'm not doing custom work on single website, I'm making a package that is intended to work on hundreds of websites.

I'm using the build tasks to only use some parts of uikit, so I'm not using it as a framework, just some components for some parts of the gallery.

**Comment by aarongerig** [comment]
TBH, I would never install a plugin that comes with jQuery UI and another framework (even only partially) on top. I think you should let the user choose, which framework he wants to use. Either UIkit or Bootstrap or any other framework out there. Plus, do you really need jQuery / jQuery UI? I mean only for those tabs, it seems like an overkill to me.

**Comment by mthomsonnz** [comment]
with my extension I am packaging some uikit components with a unique prefix, so it is not an extra framework, just some javascript to do a gallery. If I used another library like slick or owl carousel it would be the same amount of javascript. With the jquery ui tabs, this is just a working example, there are many ways that elements are hidden on page load and shown later, ideally the slideshow will display in all of these cases. This is the core issue, my code pen is just an example.

**Comment by aarongerig** [comment]
Alright, then use JavaScript events to initialize the slideshow on "show". UIkit style would look something like this https://codepen.io/aarongerig/pen/XqLeQM?editors=1010

**Comment by mthomsonnz** [comment]
I think we are misunderstanding each other here :) I don't use jquery tabs at all, this is not the issue. I just used jquery tabs for my code pen example. My gallery script could go into any number of tabs, or sliders, or parts of the page that appear or disappear on some kind of click. There could be 100 different situations where this happens (eg every joomla and wordpress template developer have there or own way of implementing show/hide). Writing custom code (like your example) for every type of tab/slider extension isn't a solution in this case. I have been looking over the uikit code to try and see where/how it could detect that its parent has gone display:block, but I can't see the solution yet.

**Comment by aarongerig** [comment]
I see. This [line of code](https://github.com/uikit/uikit/blob/develop/src/js/components/slideshow.js#L50) here defines on what events the slideshow should update. As you can see the slideshow updates on `load` and `resize`. I don't even know if it's possible to detect whether the slideshow element or one of its parents becomes `display: block;` or even `visibility: visible;`, without knowing what event you have to listen to.

**Comment by mthomsonnz** [comment]
Yes I was looking at that exact line too :) The only workaround I can think of is polling the slideshow div for style changes, but that is a last resort. It seems a display:block change doesn't fire a resize event. Maybe one of the other uikit developers knows a way around this. If I have to I will poll, but I hate resorting to that kind of solution.

**Comment by mthomsonnz** [comment]
This is the best workaround I could find. I don't like doing ugly solutions like polling, but I can't see any other way in this situation. Hopefully someone else can suggest something better, in the short term this works for me:

`$('.slideshow-wrapper').each(function(index,el)
{
	var lastVisible = $(el).is(':visible');
	if(!lastVisible)
	{
		//hide any hidden tab slideshows so they don't show with no image on tab show event
		$(el).css('visibility','hidden');
	}

	function checkIfVisibleChanged()
	{
		var visibleNow = $(el).is(':visible');

		if(visibleNow != lastVisible)
		{
			//event: the tab with this slideshow has been shown
			if(visibleNow)
			{
				$(el).resize();
				iguiUIkit.update($(el));
				//show the slideshow now that the tab is shown and the update is done 
				setTimeout(function(){$(el).css('visibility','visible');}, 200);
			}
			//event: the tab wiith this slideshow has been hidden
			else
			{
				$(el).css('visibility','hidden');
			}

			lastVisible = visibleNow;
		}
	}

	//check to see if the elements visibility has changed every 1/4 of a second, nooooo polling sucks!
	setInterval(checkIfVisibleChanged, 250);
});`

**Comment by janschoenherr** [comment]
This has most likely been resolved.
