### ISSUE TITLE
Image component does not render images when loaded by ajax

### ISSUE THREAD

**Issue by szabeszg** [uikit/uikit#3395]
### UIkit version
3.0.0-rc.2

### Browser
Tested on macOS: Chrome 64.0.3282.140, Firefox 60.0.1, Safari 11.0.1

### Steps to reproduce
I use ajax to inject HTML partials into the DOM. I happen to use Intercoolerjs to do that but probably it does not matter.

### What is Expected?
I expect the images of the image component to show up on the page after the HTML partial has been successfully injected into the page.

### What is actually happening?
On the successful ajax request the partial is injected into the page but the images do not show up because they are not requested by UIkit 3, so only the placeholders can bee seen instead (gray boxes in my attached screen-grab).

If I open the developer tool or scroll the page or resize the browser window then the images get downloaded and displayed. 

All this happens in all three browsers I used to test. **Important**: this issue only happens in a NEW browser page, that is for the "very first time". When a browser page which has already succesfully displayed the images is used, then the images do show up as expected.

Here is a screen-grab to show what happens:

![uikit3-image-component-issue](https://user-images.githubusercontent.com/7194945/40487454-7a0f63f6-5f64-11e8-959c-95f87cae2c3e.gif)

**Comment by janschoenherr** [comment]
> Important: this issue only happens in a NEW browser page, that is for the "very first time". When a browser page which has already succesfully displayed the images is used, then the images do show up as expected.

That is happening because UIkit stores information about the image probably being in the cache in the session storage.

**Comment by szabeszg** [comment]
Seems to have been fixed by some underlying changes as upgrading to the latest RC the issue is gone. Therefore I close this.
