### ISSUE TITLE
UglifyJS: Production builds fail

### ISSUE THREAD

**Issue by aarongerig** [uikit/uikit#3396]
### UIkit version
3.0.0-rc.2

### Steps to reproduce
1. Create a webpack config with following alias: `'uikit-util': '/node_modules/uikit/src/js/util'`
2. Add the UglifyJS webpack plugin `uglifyjs-webpack-plugin@0.4.6 // webpack < v4.0.0`
3. Let webpack do its things in production mode
4. Build will fail with an error (see below)

This is because with `uikit-util` being written in ES6 syntax and BabelJS explicitly excluding anything inside `/node_modules/` (which is good), the "uglification" cannot be done since this version of UglifyJS doesn't support ES2015+ code yet.

### What is Expected?
Build was successful. This was the case before the RC releases, because the utils were compiled and transpiled into the files inside `dist` already.

### What is actually happening?
Error message when compiling with UglifyJS: `Unexpected token: punc (()`.

**Comment by oshihirii** [comment]
Newbie question, does `webpack` apply `uglify` in `production mode` by default (ie without specifying the `uglify` plugin)?

https://github.com/webpack/webpack/issues/6075
