### ISSUE TITLE
rc.3 form background changed to muted background?

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3400]
### UIkit version
3.0.0-rc.3

### What is Expected?
3.0.0-rc.2
https://github.com/uikit/uikit/blob/ef8703f04ad55030fb4398efb20a64641509eded/src/scss/variables-theme.scss
$form-background: $global-background !default;

### What is actually happening?
https://github.com/uikit/uikit/blob/develop/src/scss/variables-theme.scss
$form-background: $global-muted-background !default;

**Comment by bbashy** [comment]
Same as https://github.com/uikit/uikit/issues/3402

**Comment by janschoenherr** [comment]
Fixed in rc4. Thanks.
