### ISSUE TITLE
New default background color in RC version

### ISSUE THREAD

**Issue by pdipasqua** [uikit/uikit#3402]
Hi guys,
in the last release rc2 and rc3 the color of default is set to #f8f8f8 but in old previous release the color is #fff. Is this a bug or new style for all component?
To verify this issue check card default color backgroud or form input. For the last component the backgrounf #f8f8f8 is set to focus too.

Thanks in advance.
Best regards.
Paolo

**Comment by bbashy** [comment]
Seeing this too on my local copy while upgrading to RC3.

![](https://d.pr/i/wVqoQ8/An8DcQm9B3.jpg)

**Comment by janschoenherr** [comment]
Fixed in rc4. Thanks.
