### ISSUE TITLE
Slideshow + uk-thumbnav (very high cpu usage from 3.0.0rc2)

### ISSUE THREAD

**Issue by picov** [uikit/uikit#3403]
### UIkit version
3.0.0-rc.2
3.0.0-rc.4

### Browser
Tested on Safari and Chrome (desktop)

I've a slideshow with linked imgs thumbnav items that worked without any problems with 3.0.0-b42 with an average 5-10% CPU usage.

The same code loaded with UiKit version 3.0.0-rc.2 and 3.0.0-rc.4 exhibit these problems:
- browser cpu usage jump to 80-100%
- the uk-thumbnav imgs blink fast (on chrome)
- there is the need to click twice on uk-thumbnav items to make slideshow set the corresponding image
- the mouse drag event over the main slideshow image non work well and often the first image is displayed instead of the next one

Nota that if i remove the HTML block related to the uk-thumbnav, the slideshow behavior back to normal.

**Comment by erwinyusrizal** [comment]
![selection_888](https://user-images.githubusercontent.com/3752374/40820550-6507a928-658b-11e8-8c7e-21252d3c2198.png)

**Comment by janschoenherr** [comment]
Yes, would be great if you could post a minimal Codepen that can reproduce the bug.

**Comment by erwinyusrizal** [comment]
https://codepen.io/erwinyusrizal/pen/PaqMXg

**Comment by erwinyusrizal** [comment]
Hi @janschoenherr thanks for the update, I see another bug the navigation not appear when I hover the navigation it has has uk-hidden and uk-invisible

![selection_890](https://user-images.githubusercontent.com/3752374/40852433-9b40083c-65f4-11e8-92a4-63ae50797b0a.png)

**Comment by erwinyusrizal** [comment]
Sorry my mistake, forgot the uk-position-relative

**Comment by erwinyusrizal** [comment]
I got the problem, in my case if image less than 6 items and I use margin between navigation item, the navigation not appear and the last nav item not appear as well

Updated Codepen:
https://codepen.io/erwinyusrizal/pen/PaqMXg
