### ISSUE TITLE
Global configuration (using JS) stopped working

### ISSUE THREAD

**Issue by fabien** [uikit/uikit#3406]
### UIkit version

3.0.0-rc.4

### Reproduction Link

https://codepen.io/anon/pen/xzGZzY

### Steps to reproduce

Click open to open the offcanvas pane.

### What is Expected?

The offcanvas should use the 'push' mode animation.

### What is actually happening?

It is using the default mode anyway. `UIkit.component('offcanvas').options.data` is actually a function now, which seems odd. A plain object would've been the expected type for configuration. In previous releases, `data` was called `defaults`.

**Comment by fabien** [comment]
@tzd I think they were a bit quick to dismiss this as a documentation issue. 

It's still a blocking issue for me as well.

**Comment by tzd** [comment]
Hello, any news about this issue?
Is there a way (in current version) to  change component options globally?

**Comment by janschoenherr** [comment]
The documentation has been updated, thanks.

https://getuikit.com/docs/javascript#globally
