### ISSUE TITLE
Bug with Sortable Height

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [uikit/uikit#3409]
### UIkit version
3.0.0-rc.4

### Browser
All Browsers

### Steps to reproduce
Create a Sortable element with fixed height

### What is Expected?
We have a page using the sortable component with a fixed height for each uk-sortable component. The height is calculated dynamically and set in the element "style" attribute. But, after updating the project to the last Uikit version, our component is not working as expected.

### What is actually happening?
Now, after dragging the element, the uk-sortable is automatically setting the height, but this is not the expected behavior.

I see that this behavior was added on version: v3.0.0-beta.41

Is there a way to avoid this behavior?

Thanks!

**Comment by janschoenherr** [comment]
Resolved with 8e9d00a2e9e9bed35b0e6183f56056abc982f91a

**Comment by TiagoSilvaPereira** [comment]
Hi @janschoenherr we need a fixed height. If the sortable element has more elements that exceed your height, we want a scroll with overflow-y: auto; The problem is that, with the thew features, our inline style is even replaced by uikit.

At this moment we are resizing it applying a style after the item moved with a setTimeout to prevent uikit resizing it after setting the style, but it is failing sometimes (because the time is fixed) and is strange because first uikit resizes the element, then we set the height.

Is there a way to set a fixed height and prevent uikit to replace the inline styles?

Thanks very much!

**Comment by janschoenherr** [comment]
Yes, but can't you wrap the sortable like this?

```
<div class="uk-overflow-auto" style="height: 200px">
    <ul uk-sortable></ul>
</div>
```

**Comment by janschoenherr** [comment]
This should be resolved in latest dev version.
