### ISSUE TITLE
Slider and Slideshow bug

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3410]
### UIkit version
3.0.0-rc.4

### Browser
chrome 66

video :  https://streamable.com/hnbwk

**Comment by zzseba78** [comment]
Works fine for me in Chrome 66.0.3359.181, High Sierra.

**Comment by flihub** [comment]
recorded again with code preview, maybe this helps more: 

<div style="width:100%;height:0px;position:relative;padding-bottom:30.244%;"><iframe src="https://streamable.com/s/2z96l/fvwzhl" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by janschoenherr** [comment]
Has this been resolved? Please try the latest dev version.
