### ISSUE TITLE
icons are not working i dont know whether there is something else i need to add or ? please review the following screen shots

### ISSUE THREAD

**Issue by simphiwehlabisa** [uikit/uikit#3414]
### UIkit version

3.0.0-rc.4

**Comment by sshlabisa** [comment]
![screenshot 88](https://user-images.githubusercontent.com/12032477/40883418-ad9b0e24-66fc-11e8-8479-8babce683a53.png)
![screenshot 87](https://user-images.githubusercontent.com/12032477/40883419-ae03821a-66fc-11e8-9f50-1d1ed368cbfa.png)

**Comment by m0yP** [comment]
Take a closer look to the docs: https://getuikit.com/docs/icon 

Also, you are double importing the files. Either use the minified version or don't, but you shouldn't add them twice.

**Comment by asifm** [comment]
@m0yP I'm not sure what you mean by taking a closer look at the doc. Could you be more specific please? What exactly is missing here?

(I understand the double importing part; but that's not relevant to the problem.)

I can't get the icons to show up either. I'm using rc5.

**Comment by asifm** [comment]
It shouldn't make any difference. Here's what the doc says (in the same page that you linked to earlier):

---
If icon is the only option in the attribute value, you can also use uk-icon="NAME"

`<span uk-icon="heart"></span>`

---

In any case, I've tried both but haven't been successful.

**Comment by asifm** [comment]
If anyone stumbles on this issue, this is how I solved it. (Found the solution here https://github.com/uikit/uikit/issues/2530.) I wish it was documented properly in the official doc.

```
const Uikit = require('uikit/dist/js/uikit')
const Icons = require('uikit/dist/js/uikit-icons')
Uikit.use(Icons);
```
or 
```
import Uikit from 'uikit/dist/js/uikit';
import Icons from 'uikit/dist/js/uikit-icons';
Uikit.use(Icons);
```

**Comment by aarongerig** [comment]
@asifm Fun fact, it is documented properly: https://getuikit.com/docs/webpack

**Comment by asifm** [comment]
@aarongerig Properly indeed. My bad. No idea how I missed it. Thanks for pointing out.

**Comment by simphiwehlabisa** [comment]
worked thankx bro
