### ISSUE TITLE
Filtering multiple elements with one filter control only filters the first element

### ISSUE THREAD

**Issue by Bloemendaal** [uikit/uikit#3416]
### UIkit version

3.0.0-rc.5

### Browser
Chrome latest

### Reproduction Link
https://codepen.io/Bloemendaal/pen/qKbvXG

### Steps to reproduce
Create a filter with 2 .js-filter classes. If you select a filter it will only filter the first .js-filter class instead of both of them. Even `uk-filter="target: .js-filter-1, .js-filter-2` is not working.

### What is Expected?
2 elements being filtered with one filter control.

### What is actually happening?
Only the first element is being filtered.

**Comment by tbba** [comment]
even targeting with one  class doest not work
Test:
http://special-space.de/uikit/filter-text.html

Use example:
I need this because I have 2 staff table (doctors and scientists) I want to apply the same filter to (the location where they work)

**Comment by tbba** [comment]
found a workaround (if intentional it could be mentioned in the docs)

<div uk-filter="target: .js-filter1">
<div uk-filter="target: .js-filter2">

    
    <ul>
        <li><a href="#"></a></li>
    </ul>

    
    <ul class="js-filter1">
        <li></li>
    </ul>
    
    <ul class="js-filter2">
        <li></li>
    </ul>1

</div>
</div>


tested in UIKIT 3.1.4

**Comment by robmcfadden** [comment]
+1! I need this too.

**Comment by mariuspana** [comment]
+1

**Comment by bohdanp44** [comment]
+1

**Comment by fildum** [comment]
Still not solved in July 2020!? 
I'm using v.3.5.4 in summer of 2020 and wondering why such an issue stayed unsolved for nearly 2 years...!
I guess many developers out there would like to filter content in more complicated structure then in a single UL>LI.

Too petty.. will have to implement my own solution :)

Like UiKit though, 
still one of the best out there!

**Comment by tbba** [comment]
a fix would be pretty awesome. We are also working with own solutions for now.
