### ISSUE TITLE
Uncaught ReferenceError: UIkit is not defined when updating from rc4 to rc5

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3419]
### UIkit version
3.0.0-rc.5

### Steps to reproduce

I was on 3.0.0-rc4 and did this:

```
cd Documents/my_repo
npm update uikit --save-dev
cd node_modules/uikit
npm install
npm install yarn
npm run compile

cd Documents/my_repo
npm run webpack
```

Build completes with no problems.  

**src/js/uikit.js**

```
import UIkit from 'uikit/dist/js/uikit-core';
import Sortable from 'uikit/dist/js/components/sortable';

import Icons from 'uikit/dist/js/uikit-icons';

UIkit.use(Icons);

UIkit.component('sortable', Sortable);

export default UIkit;
```

**src/js/my_entry_file.js**

```
// custom uikit less theme
import '../css/custom_uikit_theme/my-theme.less';

import UIkit from './uikit';
```

**webpack.config.js**

```
const path = require('path');
const UglifyJsPlugin = require("uglifyjs-webpack-plugin"); 

var webpack = require("webpack");

module.exports = {
    entry: "./src/js/my_entry_file.js",
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "dist/js")
    },
    // mode: "development",
    module: {
        rules: [{
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["env", "stage-0"]
                    }
                }
            },
            {
                test: /\.css$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" }
                ]
            },
            {
                test: /\.less$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" },
                    { loader: "less-loader" }
                ]
            },
            {
                test: /\.jpg$/,
                use: [
                    { loader: "url-loader" }
                ]
            },
            // to enable dev tools usage of jQuery
            // see: https://www.npmjs.com/package/expose-loader
            {
            test: path.resolve(__dirname, 'src/js/jquery-3.3.1'),
            use: [{
            loader: 'expose-loader',
            options: '$'
            }]
            }
        ]
    },
    plugins: [
       new UglifyJsPlugin(),
       new webpack.ProvidePlugin({
            $: "./jquery-3.3.1",
            jQuery: "./jquery-3.3.1"
        })
    ],
    resolve: {
    alias: {
        'uikit-util': path.resolve(__dirname, 'node_modules/uikit/src/js/util')
    }
    }
}
```

### What is Expected?

Behavior as normal, just wanted to update UIkit to latest version.  

### What is actually happening?

Frontend error in chrome dev tools:

> Uncaught ReferenceError: UIkit is not defined
>     at bundle.js:5

**Comment by oshihirii** [comment]
I have completely uninstalled UIkit and then installed again, and still get this error message on the frontend.  Help appreciated!

**Comment by oshihirii** [comment]
Update:

I specifically re-installed `rc4` and I don't get that error on the frontend, something in `rc5` is different and is breaking for me:

    npm install --save-dev uikit@3.0.0-rc.4

**Comment by dasdeck** [comment]
Thanks for the report! This will be fixed in the next release!

Cheers!

**Comment by oshihirii** [comment]
@dasdeck 

I uninstalled and then re-installed uikit (now at rc6) and custom icons aren't showing on the frontend.

There are no build errors or front end errors.

All configuration is the same as displayed in original post.

**Comment by oshihirii** [comment]
I resolved this by adjusting the following in `src/js/uikit.js` from:

    import Icons from 'uikit/dist/js/uikit-icons';

to:

    import Icons from 'uikit/dist/js/uikit-icons-my-theme';

I'm not sure why previously the custom icons were available in `uikit/dist/js/uikit-icons` and now they are not.

**Comment by oshihirii** [comment]
Actually, my bad, I forgot this:

https://getuikit.com/docs/custom-icons#add-and-overwrite-icons

> The build process will check two places for additional icon files:
> 
> The custom folder: /custom/icons/*.svg
> Any custom theme: /custom/mytheme/icons/*.svg

and had copied in an old `custom` folder with a nested theme folder, whereas it just should have contained an `icons` folder.
