### ISSUE TITLE
Request: Bordered tables

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#342]
I'm missing the bordered table style, present in Bootstrap for example. It should apply only if **uk-table-bordered** or similar class present.

**Comment by ivanhalen** [comment]
@miljan-aleksic, the "we'll consider for the next releases" is exactly the answer I got almost one year before your issue: https://github.com/uikit/uikit/issues/15 (we were at the beginning of UIKit)
From my experience, don't expect this feature to come soon or really in the next 3.x release: I still don't understand why a so popular feature is still ignored
At the moment, this is the only thing that kept me away from switching to UIKit: 'til that day, I'll go on with Bootstrap
