### ISSUE TITLE
Multiple navbar (right and left) in RTL 

### ISSUE THREAD

**Issue by freefri** [uikit/uikit#3427]
Hi, 
I think uk-navbar-left and uk-navbar-right are not working as expected with RTL

### UIkit version
3.0.0-rc.5

### Reproduction Link
https://codepen.io/anon/pen/NzbEPo
In this codepen you can see both links on the left (try to remove the css direction to see the normal left-to-right with active-left link on the left and active-right link on the right)

### What is Expected?
Adding this css, I get what I think it should be the expected result (active-left link on the right and active-right link on the left)
https://codepen.io/anon/pen/JZbmwK

**Comment by fxmountain** [comment]
Adding `flex-direction: row-reverse;` to .uk-navbar is fixing it: [Fix](https://codepen.io/fxmt/pen/yEzJjK)

**Comment by MohamedSallam-VG** [comment]
I'm having a similar issue to this when using RTL. When doing navbar-left & navbar-right. The Divs are inverted, but the content of navbar-right doesn't invert and keeps floating right. This is on version 3.0.0-rc.17

**Comment by idesignzone** [comment]
Add this class and it will fix .uk-navbar-right alignment for RTL
```
[dir="rtl"] .uk-navbar-right {
  margin-left: 0;
  margin-right: auto;
}
```
