### ISSUE TITLE
Suggestion: Do not use anchors in components

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#3428]
### UIkit version

3.0.0-rc.5

### Browser
Google Chrome

Some (most?) components use an anchor for navigation / handling items (e. g. Lightbox). This has a great disadvantage on small screens:

If the user hovers over a next/previous button (e. g. in an open Lightbox), the browser shows up the address on the left bottom corner. In the example with the lightbox this hides the caption and is no longer visible. Besides that, it is very anoying that the address (which is not a real address) will be displayed at all:

![anchorproblem](https://user-images.githubusercontent.com/12196222/41176321-40f234d8-6b60-11e8-898f-11732cdb512d.jpg)

My suggestion is to use a data attribute instead of href attribute (e. g. data-src), so we can use any other element instead an anchor (e. g. span, div etc). Example:

Current with the described disadvantage:

https://codepen.io/anon/pen/VdmJwz

Instead:

https://codepen.io/anon/pen/wXoLBQ

Note: The link above only shows the suggested html code, since I do not know how to insert html code here.

**Comment by ikabod** [comment]
I found a workaround for the lightbox now but would be glad if the behaviour can be changed generally:

`UIkit.lightbox(divLightbox, {template: '<div class=\"uk-lightbox uk-overflow-hidden\"> <ul class=\"uk-lightbox-items\"></ul> <div class=\"uk-lightbox-toolbar uk-position-top uk-text-right uk-transition-slide-top uk-transition-opaque\"> <button class=\"uk-lightbox-toolbar-icon uk-close-large\" type=\"button\" uk-close></button> </div> <span class=\"uk-lightbox-button uk-position-center-left uk-position-medium uk-transition-fade uk-link\" uk-slidenav-previous uk-lightbox-item=\"previous\"></span> <span class=\"uk-lightbox-button uk-position-center-right uk-position-medium uk-transition-fade uk-link\" uk-slidenav-next uk-lightbox-item=\"next\"></span> <div class=\"uk-lightbox-toolbar uk-lightbox-caption uk-position-bottom uk-text-center uk-transition-slide-bottom uk-transition-opaque\"></div></div>'});`

**Comment by ikabod** [comment]
I use the UIkit for the popup of a browser extension and it took me much time to get rid of all the used anchors.

**Comment by janschoenherr** [comment]
This is yet another reason to use `<button>` instead of `<a>`. I will close the issue for now, it is on out todo list.
