### ISSUE TITLE
Lazy loader html img markup, validation and SEO

### ISSUE THREAD

**Issue by picov** [uikit/uikit#3429]
### UIkit version
3.0.0-rc.5

### Actual behavior
In order to use uk-img for lazyload there is the need to replace src attribute with data-src, but:
-  this not allow the document to pass HTML validator ("Element img is missing required attribute src", or "Bad value  for attribute src on element img: Must be non-empty").
- there is no fallback for unsupported browsers/screen readers or JS unsupported/disabled
- I'm not sure if the code will remain SEO friendly

### Potential improvement
Before the UIKit support for lazy loading images I used the popular lazysizes.js that support several html markups. An interesting markup that is SEO friendly and has a fallback for unsupported browsers/screen readers, JS unsupported/disabled (due to the fact that the src attribute is not being omitted) is that they call the "modern transparent srcset pattern" that also work for a single image (https://github.com/aFarkas/lazysizes).
That same markup actually not works with UIKit and all images are loaded normally (probably due to the presence of src attribute).
It could be useful to have a way that allow the use of the the lazy loader without the the needs to remove the default src tag.

**Comment by zzseba78** [comment]
Yes, it throws html5 validation errors because img src attribute it´s not set. The set attribute it´s created by js after load. I agree with your thoughts, also, I think it would be nice to add or change a css class name when image have loaded ( like Lazysizes does for example, makes life easier 😄 ).

https://validator.w3.org/nu/?doc=https%3A%2F%2Fzzseba78.github.io%2FKick-Off%2FnewsBlog.html

**Comment by stell** [comment]
Can we have some info about this important SEO point from the devs? Is UIkit lazy loading hiding images from Google?

**Comment by zzseba78** [comment]
@AlekVolsk Yes, i know what lazyloading is.
Check this article:
http://www.thesempost.com/lazy-loading-images-likely-will-indexed-google/

**Comment by zzseba78** [comment]
@AlekVolsk First part, true, then: wrong.
https://developers.google.com/search/docs/guides/lazy-loading

**Comment by AlekVolsk** [comment]
Sorry, there is a misunderstanding due to the translation (English is not my native), it was meant precisely in the context of the question raised, although perhaps I am not right

**Comment by picov** [comment]
It seems that these days Google are able to parse an execute javascript, thus (probably) the images  are still indexed by Google even if the standard src tag is missing (you can read lazysizes docs for more info about this).

The key point here is to have the opportunity to use this feature WHILE KEEPING the standard src tag in place because of the reasons of the first post and because Google is not the only player into the scene.

I'm currently using lazysizes (with a markup that allow to keep the src tag) but I've verified that in a complex layout, using the build-in UIkit lazy loading will speed-up rendering by reducing page redraw/reflow (also reducing the need of an extra lib).

**Comment by zzseba78** [comment]
@picov the src attribute it´s to place a light placeholder image only, you can put it yourself... i don´t know if i´m following you...

**Comment by AlekVolsk** [comment]
I do not quite understand how you can connect the uk-img here to chrome used webp, and in firefox jpg:
```
<picture>
    <source srcset="examples/images/large.webp" type="image/webp">
    <img srcset="examples/images/large.jpg" alt="…">
</picture>```

**Comment by stell** [comment]
Can we please have a dev response if uk-img can or will reveal all images to google search bot instantly?
This is a serous ranking factor that should be of value for all of Yootheme Pro customers.

**Comment by janschoenherr** [comment]
I am no SEO expert but it seems to me, that Google does scroll the page while crawling. Thus it will index the images.

Regarding crawlers that do not support Javascript. There is this quote from the "amp-img" component help page that hints at a possible solution: 

> If you want to ensure that users with JavaScript disabled can see your images, you can add an additional img element inside a noscript tag. This also makes it possible for webcrawlers without JavaScript runtime to discover your images.

**Comment by picov** [comment]
The noscript solution still don't address code validation (and also need extra works and markup).
Almost all the amazing UIKit components can be used in W3C validation savvy way using the data-* for custom attributes and this is a great features for developers who cares/needs such kind of things.
I think that the lazy loader support for the "modern transparent pattern" could be a great solution.

**Comment by zzseba78** [comment]
@picov Question: this pattern should work in uikit right? I mean, it works... or not?

```
<img
    src="https://picsum.photos/600/600/?image=100"
    srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
	  data-srcset="https://picsum.photos/600/600/?image=100 500w,
		             https://picsum.photos/900/900/?image=101 900w,
	               https://picsum.photos/1500/1500/?image=102 1500w"
	  sizes="(max-width: 1100px) 100vw,
            1100px"
	  data-uk-img />
```

**Comment by zzseba78** [comment]
I made some test here with both UIkit Image and Lazysizes with modern transparent pattern applied on both. Clear session storage and run. Both works like a charm, see network results.

Left: UIKit
Right: Lazysizes.

Leave links at bottom to do you own test.

## Without scrolling

![captura de pantalla 2019-01-23 a la s 15 15 51](https://user-images.githubusercontent.com/5558563/51627837-1e58dc80-1f22-11e9-80a7-7462fb2e941d.png)

## After Scrolling

![captura de pantalla 2019-01-23 a la s 15 16 11](https://user-images.githubusercontent.com/5558563/51627849-26188100-1f22-11e9-9733-1936bbb8b8de.png)

UIkit: https://byhumans.works/area/test/lazyload/uikit-test.html
Lazysizes: https://byhumans.works/area/test/lazyload/lazysizes-test.html

**Comment by picov** [comment]
@zzseba78
If "works" means "displayed" then the answer is yes.
If "works" means "displayed and lazy loaded by uikit" then the answer seems no:
try to add some content before your container (even a div with a fixed height) in order to push the image offscreen at initial page render. Using the browser dev tools on the bottom frame, you will see the the image is loaded immediately, even if you not scroll the page to make it visible.

@zzseba78 Are you sure?
I've just tested the pages with Safari 12, Chrome 71 and Firefox 64 on Mac and the uikit version load all images without scroll (about 2,3 MB of data).

**Comment by zzseba78** [comment]
Did you empty the session storage?

**Comment by picov** [comment]
> @picov Did you empty the session storage? Forks like a charm to me ( add a topspacer div )> 

Oh no, I didn't!
My test with lazysizes works because it not rely on session storage and I've just realised that the Safari keyboard shortcut for empty history NOT also clear session storage and that Firefox need the cookie option checked in browser history clear panel to do that.

I'll make some test with this markup in complex pages that use slider and slideshow.

**Comment by zzseba78** [comment]
@picov Nice! I fix some markups problems and test now validates. Let me know how your test goes, and seems that we have the best possible markup for lazyloading.

https://html5.validator.nu/?doc=https%3A%2F%2Fbyhumans.works%2Farea%2Ftest%2Flazyload%2Fuikit-test.html

**Comment by picov** [comment]
I can confirm that uk-slider and uk-slideshow works well with this markup (that obviously can be used even with a single image in data-srcset).
I think that the official docs should report this at least as an option for users that prefer to keep the standard src tag.

PS:
in some pages with slider and slideshow I realised that in order to obtain a fast UI response I still need to use lazysizes because it support the combination class="lazyload lazypreload" that delay the image load after all the other items of the page.
This allow to implement a fast initial page load and a fast subsequent slide show interaction because the browser will not wait that the required image "enter the stage" to load it.

That said, I'm sure I'm not the only one thinking about an "uk-img-preload" ;-)

**Comment by janschoenherr** [comment]
With UIkit 3.0.3 we started using IntersectionObservers where possible. The crawler no longer needs to scroll.

According to these two links, this is what Goggle recommends:
https://developers.google.com/search/docs/guides/lazy-loading
https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/
