### ISSUE TITLE
Should we pass query string vars through on youtube/vimeo lightbox links?

### ISSUE THREAD

**Issue by aaronpeterson** [uikit/uikit#3430]
They don't seem to pass through.  Haven't looked at src but would be willing to submit a PR if there is support.

### UIkit version
3.0.0-rc.5

### Browser
All

### Reproduction Link
https://codepen.io/anon/pen/qKRPmB

### What is Expected?
Query string vars are passed through to embed url...

### What is actually happening?
Query string vars are *not* being passed through

**Comment by janschoenherr** [comment]
You can now (current dev version) use an `attrs` or `data-attrs` attribute on the item which lets you override any attributes on the parsed item.
