### ISSUE TITLE
Height issue with the new Masonry Grid on UIKIT 3.0.0-rc.5

### ISSUE THREAD

**Issue by infinyteam** [uikit/uikit#3434]
The calculated height is not correct, So, I have created a JSFIDDLE document to see what's going on:
https://jsfiddle.net/af1uvotr/16/
There is an unneeded height how I can resolve this? I think is an issue from UIKIT!

**Comment by infinyteam** [comment]
I have used Desandro Masonry Plugin and it works fine, see this: https://jsfiddle.net/egwjba74/5/
This confirms that the problem is on UIKIT3 masonry grid, and I hope you guys take this into consideration in the next update!
Thanks in advance!

**Comment by janschoenherr** [comment]
This has been fixed with 7fa2039a9cdb239b5b365d1d923d4a4235268eee and will be released with the next update.
