### ISSUE TITLE
Bug with 2 or more Switchers on same Page

### ISSUE THREAD

**Issue by Thisisjuke** [uikit/uikit#3435]
### UIkit version
3.0.0-rc.5

### Browser
Google Chrome

### Reproduction Link
https://codepen.io/Jukeboy/full/WypqKP

### Steps to reproduce
Just Copy and past the exemple from the documentation 2 times.

### What is Expected?
Each one working by its own. They have to work like 2 differents switchers. I have cards, each one with its own Switcher, to see an abstract and then more informations. When I click "Information" on the first cards, I have informations and the other Switchers don't move.

### What is actually happening?
When I click one, all Switchers move and it brakes other Switchers.

**Comment by Bloemendaal** [comment]
`<ul class="uk-subnav uk-subnav-pill" uk-switcher="connect: #switcher1">
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
</ul>

<ul class="uk-switcher uk-margin" id="switcher1">
    <li>Hello!</li>
    <li>Hello again!</li>
    <li>Bazinga!</li>
</ul>

<ul class="uk-subnav uk-subnav-pill" uk-switcher="connect: #switcher2">
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
</ul>

<ul class="uk-switcher uk-margin" id="switcher2">
    <li>Hello!</li>
    <li>Hello again!</li>
    <li>Bazinga!</li>
</ul>`

**Comment by Bloemendaal** [comment]
`<ul class="uk-subnav uk-subnav-pill" uk-switcher="connect: #switcher1">`
`    <li><a href="#">Item</a></li>`
`    <li><a href="#">Item</a></li>`
`    <li><a href="#">Item</a></li>`
`</ul>`

`<ul class="uk-switcher uk-margin" id="switcher1">`
`    <li>Hello!</li>`
`    <li>Hello again!</li>`
`    <li>Bazinga!</li>`
`</ul>`

`<ul class="uk-subnav uk-subnav-pill" uk-switcher="connect: #switcher2">`
`    <li><a href="#">Item</a></li>`
`    <li><a href="#">Item</a></li>`
`    <li><a href="#">Item</a></li>`
`</ul>`

`<ul class="uk-switcher uk-margin" id="switcher2">`
`    <li>Hello!</li>`
`    <li>Hello again!</li>`
`    <li>Bazinga!</li>`
`</ul>`

**Comment by Thisisjuke** [comment]
Hello and thanks for taking time.
I tried this solution, but when I append it with Jquery, it doesn't work at all.
There is a solution to append many Switchers ?

Html : 
```
<ul class="tab-selector" uk-switcher="connect: #switcher">
    <li class="project-tab"><a class="nav-link" href="#">Project</a></li>
    <li class="project-tab"><a class="nav-link" href="#">Informations</a></li>
    <li class="project-tab"><a class="nav-link" href="#">Report</a></li>
</ul>
<ul id="" class="uk-switcher">
    <li class="switch-one">Content</li>
    <li class="switch-two">Content</li>
    <li class="switch-three">Content</li>
</ul>
```

Jquery : 
```
template.find('.tab-selector').attr('uk-switcher','connect: #switcher'+1)

template.find('.uk-switcher').attr('id','switcher'+1)
$('#project-list').append(template);
```

Browser output :
```
<div class="card" style="padding:0;">              
    <ul class="tab-selector nav-tabs uk-subnav" uk-switcher="connect: #switcher1">
        <li class="project-tab uk-active" aria-expanded="true"><a class="nav-link" href="#">Project</a></li>
        <li class="project-tab" aria-expanded="false"><a class="nav-link" href="#">Informations</a></li>
        <li class="project-tab" aria-expanded="false"><a class="nav-link" href="#">Report</a></li>
    </ul>
    <ul id="switcher1" class="uk-switcher">
        <li class="switch-one uk-active" style="">Content</li>
        <li class="switch-two" style="height: 270px;">Content</li>
        <li class="switch-three" style="height: 270px;">Content</li>
    </ul>
</div>
<div class="card" style="padding:0;">              
    <ul class="tab-selector nav-tabs uk-subnav" uk-switcher="connect: #switcher2">
        <li class="project-tab uk-active" aria-expanded="true"><a class="nav-link" href="#">Project</a></li>
        <li class="project-tab" aria-expanded="false"><a class="nav-link" href="#">Informations</a></li>
        <li class="project-tab" aria-expanded="false"><a class="nav-link" href="#">Report</a></li>
    </ul>
    <ul id="switcher2" class="uk-switcher">
        <li class="switch-one uk-active" style="">Content</li>
        <li class="switch-two" style="height: 270px;">Content</li>
        <li class="switch-three" style="height: 270px;">Content</li>
    </ul>
</div>
```
It continues to act as one Switcher. Do you have more informations ?

**Comment by Bloemendaal** [comment]
Check out this page [Switcher](https://getuikit.com/docs/switcher#javascript).

You can use `UIkit.switcher(element, options);`

**Comment by Thisisjuke** [comment]
I used it.
Not really the best way, but it works.
Once HTML generated, I used :
```
cpt = '0';
$('.tab-selector').each(function(){
    UIkit.switcher('.selector'+cpt, {connect: '#switcher'+cpt});
    cpt++;
})
```
Thx for Help !

**Comment by janschoenherr** [comment]
This should only select the adjacent one:

    <ul class="uk-subnav uk-subnav-pill" uk-switcher="connect: +.uk-switcher">
