### ISSUE TITLE
lightbox issue

### ISSUE THREAD

**Issue by Rover-33** [uikit/uikit#3438]
### UIkit version

3.0.0-rc.5

### Browser
chrome, safari

### Reproduction Link

https://codepen.io/anon/pen/LrjxNo

### Steps to reproduce
1) click first button "LIGHTBOX 1"
2) list 5 slides with swipe (do not use arrows or keyboard)
3) close lightbox
4) try click second button "LIGHTBOX 2"

### What is Expected?
The second lightbox should open

### What is actually happening?
The second lightbox does not open. 
It cause when swiping slides with mouse or fingers on screen.

**Comment by fxmountain** [comment]
Can you describe your issue a little more?

For me it is working and opening. (Firefox ESR + Latest Chrome)

What browser do you use?

**Comment by Rover-33** [comment]
Sorry for my English.
I use Safari and Chrome latest.
Open first lighbox and scroll through the images, but do not use the arrows on the sides or keyboard. Scroll images by dragging them with mouse.
Close lightbox frame and try to open any other lighbox.

Also, if you swipe the images on your smartphone's screen, you will see this issue.

**Comment by zzseba78** [comment]
Why don´t you use Dynamic lightbox to open a group of images instead?
https://getuikit.com/docs/lightbox#lightbox-panel-options
https://getuikit.com/assets/uikit/tests/lightbox.html

**Comment by Rover-33** [comment]
Because it is not suitable for my design, and besides does not solve the problem.
Go through your second link and click on the first picture in the first row, then scroll through several images without using the arrows.
After that, try to open the lightbox in the second row
