### ISSUE TITLE
uk-form-icon padding issue

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#344]
When using **uk-form-icon** the wrapped input padding-left is increased making the whole input width grow artificially. This become an issue when placing inputs.uk-width1-1 inside a modal, as those will stop respecting the modal padding and go over it.

Using text-indent instead solves it but there is not an equivalent when using **uk-form-icon-flip**.

**Comment by sumiitmalik** [comment]
Is there any way to put icon inside input box, i have tried uk-form-icon and uk-form-icon-flip but not able to achieve it. my code is 
<div class="uk-width-medium-1-2">
    <div class="uk-form-row">
        <label for="unit_name" class="uk-form-label">Unit</label>
        <div class="uk-form-controls uk-form-icon-flip">
            
            <input name="unit_id" value="51" id="unit_id" type="hidden">
<input tabindex="2" name="unit_name" value="NOS" id="unit_name" required="required" placeholder="Unit" class="uk-form-width-large" addentry="{localhost}" myautocomplete="{&quot;target&quot;:&quot;http:\/\/localhost&quot;,&quot;displayfields&quot;:{&quot;unit_name&quot;:&quot;unit_name&quot;},&quot;selectfields&quot;:{&quot;unit_id&quot;:&quot;unit_id&quot;,&quot;unit_name&quot;:&quot;unit_name&quot;}}" type="text">
            
                <a href="" data-toggle="modal" data-target="#myModal" mysearch="{&quot;target&quot;:&quot;http:\/\/10.0.0.138\/uikit\/venus\/index.php\/material\/unit_master\/help?d=a.2&amp;r=1&amp;f=1&quot;,&quot;mysearchparam&quot;:{&quot;unit_name&quot;:&quot;unit_name&quot;},&quot;mysearchopr&quot;:{&quot;unit_name&quot;:&quot;like&quot;}}" class="uk-icon-search"><i class="uk-icon-search"></i></a>
            
    </div>
    </div>
</div>
