### ISSUE TITLE
lightboxpanel option delay-controls not working, delayControls does

### ISSUE THREAD

**Issue by mthomsonnz** [uikit/uikit#3441]
*3.0.0 rc 6

Codepen with example: 

https://codepen.io/matt_nz/pen/GGOQpQ?editors=1010

change the 'delay-controls' to delayControls to have controls shown for 10 second instead of 3

**Comment by janschoenherr** [comment]
There is a separate section on "Programmatic Use" in the docs: https://getuikit.com/docs/javascript#programmatic-use

**Comment by janschoenherr** [comment]
Yes, that's true. Could you open a separate issue at https://github.com/uikit/uikit-site/issues? Thanks.
