### ISSUE TITLE
navbar dropdown boundary issue when placed in uk-container

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#3453]
### UIkit version
3.0.0-rc.6

### Browser
chrome

### Reproduction Link

https://codepen.io/anon/pen/BVqOEO

### Steps to reproduce
resize window to near the container size then move courser to the menu link on the right side of the navbar

### What is Expected?
dropdown should have the proper boundary

### What is actually happening?
dropdown is outside the container area

**Comment by tyler-x** [comment]
any update on this bug? rc-16 still has it.

**Comment by janschoenherr** [comment]
Please check the latest UIkit version, this has been greatly refactored.
