### ISSUE TITLE
Loading with Webpack Doesn't seem to Work

### ISSUE THREAD

**Issue by methodbox** [uikit/uikit#3454]
### UIkit version

3.0.0-rc.6

The docs indicate to use an import to us UIKit in things like Vue:

```javascript
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';
```
I was unable to get CSS to be recognized without putting the uikit.min.css in a ./static directory importing it directly:

```javascript
import '../static/uikit.min.css'
```
This is using a very straight-forward Vue/Webpack configuration.

I received no errors regarding UIKit missing, etc. It found the node_module. It simply didn't load the CSS.

You indicate to load the CSS in the index.html and then run webpack, which doesn't work and even if it did, appears that it would just run what's compiled in ./dist, which isn't the same as precompiled templates with Webpack.

Not sure how this is supposed to work with real Webpack setups, but this isn't it.

**Comment by aarongerig** [comment]
The line `import UIkit from 'uikit';` only imports UIkit's JavaScript. There was never told anything different, see the [docs](https://getuikit.com/docs/webpack). If you want to load the CSS of UIkit via webpack as well, I suggest you to use either a [less](https://github.com/webpack-contrib/less-loader) or [sass](https://github.com/webpack-contrib/sass-loader) loader, which compiles your Less/Sass to regular CSS.

Does this answer your question?
