### ISSUE TITLE
[Feature Request] Convert uk-nav to inline menu with dividers on small screen

### ISSUE THREAD

**Issue by Jdeboysere** [uikit/uikit#3455]
Hi there,

Suggestion: add a uikit class that converts an .uk-nav to an inline menu with dividers on small screen.

See my example:
Here, a menu on large screens (note: there are 2 menus on this screenshot)
![uk-nav](https://user-images.githubusercontent.com/15907265/42079279-87d84caa-7b7f-11e8-8643-982c4e3a5fb0.png)

Here, the same menus on a small screens
![uk-nav2](https://user-images.githubusercontent.com/15907265/42079278-87bcb652-7b7f-11e8-9763-f1e661178bc6.png)

According to our UX responsible, this inline display is optimized for small screens.

What do you think?

**Comment by drmzio** [comment]
You can easily do this with a few CSS. https://codepen.io/drmzio/pen/Vdqqga

**Comment by aarongerig** [comment]
This exists already: https://getuikit.com/docs/subnav#divider-modifier
And if you want to display something different on different viewports, simply use the visibility component: https://getuikit.com/docs/visibility#responsive
