### ISSUE TITLE
Request: Complete UI components example

### ISSUE THREAD

**Issue by akshaybabloo** [uikit/uikit#3456]
It would be great to have complete UI components in one page so that if anyone wants to add or make to the less/scss they could see the changes. Something like - https://semantic-ui.com/examples/theming.html

**Comment by mattfletcher** [comment]
https://getuikit.com/assets/uikit/tests/index.html

**Comment by akshaybabloo** [comment]
Thanks @mattfletcher the is not there in the documentation so didn't know about it.

**Comment by mattfletcher** [comment]
It could be a bit more obvious - if I recall correctly the v2 site linked to it with the name "kitchen sink".

**Comment by akshaybabloo** [comment]
Under components (in UiKit documentation) `open test` takes you to the test index
