### ISSUE TITLE
uk-leader not working inside of modal

### ISSUE THREAD

**Issue by philryan** [uikit/uikit#3457]
### UIkit version

3.0.0-rc.6

### What is actually happening?

uk-leader works fine on a regular page, but not inside the modal. The "data-fill" remains blank and we do not see ........... as we should
<span class="uk-leader-fill" data-fill="">Shipping &amp; Handling</span>

The code i'm using inside the modal is:
<div class="uk-grid-small uk-text-small" uk-grid>
<div class="uk-width-expand" uk-leader>Teeth Whitening Kit</div>
<div>$37</div>
</div>

**Comment by peterbrinck** [comment]
I have been playing around with it a bit now, and the only way I can reproduce it, is when I have class `uk-width-expand` (as in the docs) on the `uk-leader` element without it being in a grid

**Comment by philryan** [comment]
Thanks Peter, so you removed uk-grid class and it worked? When I put that code outside of the modal, everything works fine. So I'm thinking that the data attribute isn't working with that uk-modal or there is some sort of conflict. Thanks for checking this.

**Comment by peterbrinck** [comment]
No, it worked when inside a `uk-grid`.
Code: https://codepen.io/peterbrinck/pen/vroXLJ
