### ISSUE TITLE
Scrolling stops functioning after using Lightbox with Dribbble API

### ISSUE THREAD

**Issue by SweetJD** [uikit/uikit#3458]
### UIkit version

3.0.0-rc.6

### Browser
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/anon/pen/GGPawG

### Steps to reproduce
Click on a Lightbox when using Dribbble API.

### What is Expected?
Scrolling should not be affected, but it becomes disabled after using the lightbox.

**Comment by janschoenherr** [comment]
Fixed with 866b0e3d95a07c0079ee199dc639c13d9f961554

You can pull the latest dev version from https://cdn.jsdelivr.net/npm/uikit@dev

**Comment by SweetJD** [comment]
It doesn't appear to have fixed this issue.

**Comment by SweetJD** [comment]
Never mind, I was pulling the code from cloud flare instead of the dev version.
