### ISSUE TITLE
Missing ';' in icon.less file

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3464]
### UIkit version

3.0.0-rc.6

### Reproduction Link
https://github.com/uikit/uikit/blob/d712f0b9e6892e1a4a675fa57b6a4987aa32d242/src/less/theme/icon.less#L28-L31

### What is Expected?
`;` at the end of the css property
### What is actually happening?
Missing

**Comment by saschadube** [comment]
Thanks, fixed 6f768b746cd4d222865e524c283830eb7201f0bc
