### ISSUE TITLE
RC 7 Bug

### ISSUE THREAD

**Issue by Bloemendaal** [uikit/uikit#3465]
### UIkit version

3.0.0-rc.7

### Browser
Chrome latest
### Steps to reproduce
I don't know what the bug is, but while running my latest project I encountered these errors. It does not load the switcher and does not toggle the offcanvas bar.

### What is actually happening?
![image](https://user-images.githubusercontent.com/1348606/42326627-f175daee-8069-11e8-9955-ed1b5662e0a2.png)

**Comment by zzseba78** [comment]
Confirmed.

**Comment by janschoenherr** [comment]
Thanks, fixed in rc8.
