### ISSUE TITLE
uk-sticky Flickering on Internet Explorer

### ISSUE THREAD

**Issue by eyes8** [uikit/uikit#3471]
### UIkit version

3.0.0-rc.8

### Browser
Internet Explorer (latest v.11)
### Steps to reproduce
1.Browser Internet Explorer
2.You see it https://www.yootheme.com/themes   click Preview (Nioh Studio)
### What is Expected?
no flickering
### What is actually happening?
uk-sticky flickering
https://www.youtube.com/watch?v=X9NRsK71TdU

**Comment by janschoenherr** [comment]
This seems to be happening within the iframe only.

**Comment by janschoenherr** [comment]
This seems to be no longer an issue.
