### ISSUE TITLE
data-uk-grid-margin attribute is not working in 2.x and 3.0

### ISSUE THREAD

**Issue by MenaiAla** [uikit/uikit#3473]
I'm trying to create a grid of elements using UIkit Front-End Framework.The problem is when I add data-uk-grid-margin to set margin between elements it does not give me any change.I don't know exactly where is my mistake,but I think a UIkit javascript file is missed in my code.
<html>
    <head>
        <title>Title</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="uikit-2.27.5/css/uikit.min.css" />
        <script src="uikit-2.27.5/js/uikit.min.js"></script>
        <script src="uikit-2.27.5/js/uikit.js"></script>
        <script src="uikit-2.27.5/js/uikit-icons.min.js"></script>
    </head>
    <body>
    <div >
      <ul class="uk-grid" data-uk-grid-margin>
        <li class="uk-width-1-3">
          <div class="uk-panel uk-panel-box">
              <div class="uk-panel "></div>
              <h3 class="uk-panel">Title</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div></li>
            <li class="uk-width-1-3">    <div class="uk-panel uk-panel-box">
                  <div class="uk-panel "></div>
                  <h3 class="uk-panel">Title</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div></li>
                <li class="uk-width-1-3">    <div class="uk-panel uk-panel-box">
                      <div class="uk-panel "></div>
                      <h3 class="uk-panel">Title</h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div></li>
                    <li class="uk-width-1-3">    <div class="uk-panel uk-panel-box">
                          <div class="uk-panel "></div>
                          <h3 class="uk-panel">Title</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                        </div></li>
      </ul>
    </div>
    </body>
</html>
In addition ,I'm using Atom plugin for UIkit to help me with autocomplete ,but the suggestions of javascript attributes are missed too.

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
