### ISSUE TITLE
ScrollTo with sticky elements

### ISSUE THREAD

**Issue by danioo** [uikit/uikit#3474]
I have view when I defined 2 elements with uk-sticky, first one have about 60px of height and the second one under also about 60px.
Somewhere on page I have a div with id = "test" and div with id = "scroller". I want to scroll to "#test" div so I'm using javascript: UIkit.scroll("#test").scrollTo("#test");
The result is that the content is scrolled to "#test" div but it's covered by sticky elements. Is it possible to set an offset to scrollTo?
I want to scroll to element but it must be visible for user - not under sticky elements.

**Comment by freefri** [comment]
Yep, I'm getting this same problem in my current project

**Comment by aarongerig** [comment]
There is a `offset` option: https://getuikit.com/docs/scroll#component-options

Please close this issue, if that resolves your problem.

**Comment by freefri** [comment]
Great, thx @aarongerig . 
To add it globally to the whole project https://getuikit.com/docs/javascript#globally
