### ISSUE TITLE
Dotnav first element always selected

### ISSUE THREAD

**Issue by shersh** [uikit/uikit#3477]
### UIkit version
3.0.0-rc.8

### Browser
Google Chrome 67.0.3396.99

### Reproduction Link
https://getuikit.com/docs/dotnav

### Steps to reproduce
Try to select any dots

### What is Expected?
First dot is not selected after select another.

### What is actually happening?
First dot will be selected always.

**Comment by janschoenherr** [comment]
Yes, this is just for demonstration purposes. It shows the active state. It would require JavaScript otherwise to de/-select the initial active state.

**Comment by ikabod** [comment]
For me as a user it is confusing and looks like a bug. Please change this behavior.
