### ISSUE TITLE
[Feature Request] uk-sticky with long content

### ISSUE THREAD

**Issue by natty-plus** [uikit/uikit#3478]
### UIkit version
3.0.0-rc.8

### Browser
All

### What is actually happening?
I have long sticky content that is larger than the view-port as a sidebar. And when i scroll down, the sticky is always stuck showing only the top part until scrolling to the next element. This behavior makes it difficult to see content that can't fit on-screen inside the sticky element without navigating all the way to the bottom.

### What is Expected?
 It should have a feature to scroll down and stuck showing the bottom part and when scroll up it should scroll up and stuck showing the top part of the sticky element.

**Comment by zzseba78** [comment]
You mean like this example right? Colum **Long Stuck Content**
https://semantic-ui.com/modules/sticky.html

**Comment by natty-plus** [comment]
Yes, exactly like "Sematic UI" sticky.

**Comment by janschoenherr** [comment]
The upcoming release will contain this feature. Please check with the current dev version

https://www.jsdelivr.com/package/npm/uikit?version=3.11.2-dev.fb043abc2
