### ISSUE TITLE
Internet Explorer 11 (Invalid operand to 'in': Object expected)

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#3480]
### UIkit version

3.0.0-rc.8

### Browser
Internet Explorer 11

### Steps to reproduce
I am running this function

`UIkit.util.on( '[id^=menu-main-menu]', 'show', function () {
code here
})`

and I am getting this error on uikit.js

> Invalid operand to 'in': Object expected
> uikit.js (637,9)`

Am I doing something wrong or is it an issue on IE 11?

**Comment by reinerluke** [comment]
Searched for this for so long. This implementing 3.0.0-rc10 did the magic for me 👍
