### ISSUE TITLE
[Feature Request] Sticky Div - bottom of page

### ISSUE THREAD

**Issue by eladnova** [uikit/uikit#3491]
I'm looking through the Sticky docs and I don't think the following is covered

A sticky element which:

- displays after a scroll down of X pixels (starts off hidden)
- OR displays after a certain amount of seconds
- is sticky to the bottom of the browser window
- width is responsive 

Here's an example. In the screen grab here my Newsletter box would only appear after X seconds and follow the user down the screen.
![slice](https://user-images.githubusercontent.com/1786476/42870770-9bff23f2-8a70-11e8-8d20-e259e9d186ea.png)

**Comment by aarongerig** [comment]
I wouldn't solve that with the Sticky component. I would use a fixed `div` and some plain ol' JavaScript:

```js
setTimeout(function() {
    // wait for 3 seconds, then fade in the div
}, 3000);
```

**Comment by zzseba78** [comment]
Or you can use Waypoints for example, for execute a function whenever you scroll to an element, in this case show a bottom fixed form.
