### ISSUE TITLE
Question: Style discrepancies scss vs actual

### ISSUE THREAD

**Issue by andrispraulitis** [uikit/uikit#3492]
Hi I've noticed few discrepancies in scss source files with the actual style. Am I missing somthing or scss source is simply not updated?

Button text is uppercase but not here:
https://github.com/uikit/uikit/blob/develop/src/scss/components/button.scss#L111

Default nav is small font size but not here:
https://github.com/uikit/uikit/blob/develop/src/scss/components/nav.scss#L175

**Comment by andrispraulitis** [comment]
Just found another one:
https://github.com/uikit/uikit/blob/develop/src/scss/components/form.scss#L239

**Comment by aarongerig** [comment]
There are not discrepancies. The final compiled CSS contains the default theme of UIkit.

Button text uppercase:
https://github.com/uikit/uikit/blob/268d90cb39993395313121fb2908ae235c7d6cfc/src/scss/theme/button.scss#L30

Default nav small font-size:
https://github.com/uikit/uikit/blob/268d90cb39993395313121fb2908ae235c7d6cfc/src/scss/theme/nav.scss#L14

Form borders:
https://github.com/uikit/uikit/blob/268d90cb39993395313121fb2908ae235c7d6cfc/src/scss/mixins-theme.scss#L793

**Comment by andrispraulitis** [comment]
Ok thanks
