### ISSUE TITLE
Update icon ratio programmatically

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3493]
In previous versions of UIkit we were able to resize an icon by updating the ratio programmatically.
Now only icons without a default ratio property update their size.

Latest version where this was possible is v3.0.0-beta.42.

### Reproduction Link

https://codepen.io/anon/pen/KBaXBp

### Steps to reproduce

Open reproduction link.
Click on the "Update ratio" button.

### What is Expected?

Both icons update their size to the new ratio.

### What is actually happening?

Only the icon without a default ratio property updates it's size.

**Comment by aarongerig** [comment]
If you read [this section](https://getuikit.com/docs/javascript#precedence) carefully, you'll see this part:

> Options passed via the component attribute will have the highest precedence, followed by single attributes and then JavaScript.

In your example you have set the ratio of the second icon inside the HTML attribute, which has the highest precedence. Therefore it not change the size, when changing it with JavaScript.

**Comment by Lumelomser** [comment]
@aarongerig, sorry for the late response and thanks for clarification!
I'm a little bit confused about the fact JS has the lowest precedence but this may have its reasons.
Maybe one of the core developers can explain this design decision in more detail.
