### ISSUE TITLE
Adding .uk-nav-parent-icon to nav adds SVG as background image, which means the SVG cannot be styled

### ISSUE THREAD

**Issue by paulisloud** [uikit/uikit#3495]
### UIkit version
3.0.0-rc.9

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/XMpryM

### What is Expected?

The standard way to use icons in UI Kit _does_ allow for easily changing colors / styles of the icon via, for example `color: red;`

### What is actually happening?

Since the icon for navs using `.uk-nav-parent-icon` is implemented as a background image, there is no easy way to change the color of the icon.

Without the ability to style this icon, it is nearly useless for a huge number of use cases.

### Suggested fix

Change the implementation to use an inline icon, changing it out or rotating it via Javascript when the accordion is open.

This will maintain the appearance / functionality of the existing component, while allowing for styling.

**Comment by aarongerig** [comment]
Actually it's quite easy. Simply change the value of this variable and the icon adapts to that color.

For SCSS:
https://github.com/uikit/uikit/blob/develop/src/scss/components/nav.scss#L36

For Less:
https://github.com/uikit/uikit/blob/develop/src/less/components/nav.less#L36

**Comment by paulisloud** [comment]
This is still a different pattern than nearly all other icons that are part of UI Kit (only applies to those in src/images/backgrounds).

The icons in src/images/icons can be changed with user-edited (vs. build time) css, which for my application is important.

Why are these icons treated differently from others?

**Comment by aarongerig** [comment]
I suppose it's for the following reason. If someone doesn't include the additional icons plugin, UIkit wouldn't have any icons to work with. Instead UIkit implements those icons it needs (navigation parent, accordion, etc.) directly into its core as CSS background images. That way, it's guaranteed that those icons display, even without the additional `uikit-icons.js` library. Hope this makes sense.

**Comment by paulisloud** [comment]
Makes sense.

I'm fairly new to UI Kit, so given my need to have user-editable css on these omnipresent, core icons, would the best option be to simply insert the `chevron-left` and `chevron-down` icons in to the markup, and then use something akin to:

    UIkit.nav.on('.uk-parent', 'click', () => {
      // switch the icons
    })

**Comment by janschoenherr** [comment]
The icons are inlined now.
