### ISSUE TITLE
UK-Sticky doesn't take margin into concideration

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3498]
### UIkit version

3.0.0-rc.9

### Steps to reproduce
1. Create a sticky div, add h1 inside with margin on the bottom.
2. The sticky placeholder doesn't to margin into count. 

### What is Expected?
Margin will be considered so content doesn't jump when it becomes sticky.

### What is actually happening?
Content jumps when sticky becomes active.

**Comment by janschoenherr** [comment]
I believe, that would be quite tricky. Is it possible to solve this with other markup?

**Comment by TomS-** [comment]
Yeah I could use padding for now.
