### ISSUE TITLE
Animation Fade with JS

### ISSUE THREAD

**Issue by hennesohg** [uikit/uikit#3499]
Hey,

I have a div object to be fade in/out via class giving from JS. `div class = "uk-card uk-card-default uk-animation-fade uk-animation-reverse"`
I try it via add / remove class, and there is no animation, but the object is simply dulled / hidden.
You can only see the right faded-animation when loading the page.
```
<div class = "uk-card uk-card-default uk-animation-fade uk-animation-reverse">
const $rjPanel = $('.uk-animation-fade');
if (lotVar === 'myValue') {
             if (result === 0) {
               $ RjPanel.addClass ('uk-animation-reverse');
             }
             else if (result> 0) {
               $ RjPanel.removeClass ('uk-animation-reverse');
             }
}
```
How can I animate a DIV object through JS?
Many Thanks

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
