### ISSUE TITLE
Support hardware accelerated animations?

### ISSUE THREAD

**Issue by nvanh** [uikit/uikit#35]
Hi, I just found uikit some hours ago and I felt in love with it immediately. It works like a champ in desktop browsers but I got some problems about delaying and unsmoothly animation in webkit mobile browsers.

I've checked the code and saw that the animations was done by using the css() method. In my knowledge, it's not hardware accelerated so it'll better if we could replace it with translate3d ?

**Comment by nblackburn** [comment]
+1 for this and would bring us one step closer to decoupling from jQuery.
