### ISSUE TITLE
Can't change components options globally.

### ISSUE THREAD

**Issue by tzd** [uikit/uikit#3501]
In your documentation you have `UIkit.component('sticky').options.data.offset = 50;`
and it's ok because `UIkit.component('sticky').options.data` returns object and you can change this offset.
But it's not possible to change js options globally for most components.

For this components data returns  plain object
formCustom
heightMatch
heightViewport
img
leader
margin
navbar
overflowAuto
scroll
scrollspyNav
sticky
svg
video
countdown
lightbox
notification
upload

For this data returns function 
accordion
alert
cover
drop
dropdown
grid
icon
modal
nav
offcanvas
scrollspy
switcher
tab
toggle
close
marker
navbarToggleIcon
overlayIcon
paginationNext
paginationPrevious
searchIcon
slidenavNext
slidenavPrevious
spinner
totop
filter
lightboxPanel
parallax
slider
sliderParallax
slideshow
slideshowParallax
sortable
tooltip

Is this done by purpose? If yes please tell me how to change options globally for components where data returns function.

**Comment by janschoenherr** [comment]
Yes, we need to update the documentation.

```
UIkit.component('sticky', UIkit.component('sticky').extend({
    data: {
        offset: 50
    }
}));
```

**Comment by tzd** [comment]
It works ok now for all the components, thank you very much for the clarification.
