### ISSUE TITLE
uk-sticky doesn't resize on window resize

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3502]
### UIkit version

3.0.0-rc.10

### Browser
Chrome

**Comment by TomS-** [comment]
This is when you set the uk-sticky-placeholder to display none. I have a uk-sticky that will sometimes overlap. This is use-case and used max-height 0 instead.

**Comment by SaphiLC** [comment]
this still happens in RC 16, i have a sticky navbar and a side area that can be hidden, but if i hide it, the sticky navbar wont get updated and take full width, im pretty sure its a bug
