### ISSUE TITLE
Too few icons

### ISSUE THREAD

**Issue by horoscop** [uikit/uikit#3504]
Hello!

Thank you for this amazing framework! Good job! I like all except the amount of available icons, could you please create more icons? If you need help, I will try to create them in the spirit of UiKit. 

Thank you!

Have a great one!

**Comment by Taimurian** [comment]
Hi,

You can add your own custom icons and include them in the build process.
https://getuikit.com/docs/custom-icons

I already added all the Font Awesome 5 icons using the same way. You can check them here
https://github.com/Taimurian/fa5-icons-for-uikit-3
