### ISSUE TITLE
uikit 3 - slider is flickering

### ISSUE THREAD

**Issue by sunfree-lighting** [uikit/uikit#3506]
I have 3 sliders in the home page, the first and third one works well, but the second slider is flickering when slideshow-nav at the second and the rest.

The URL is http://23.110.48.169/1-home/home.html

Is it something wrong about my html code or the bug ?

**Comment by zzseba78** [comment]
The url doesn´t work.

**Comment by sunfree-lighting** [comment]
Sorry, i correct my html code just follow the tutorial documents.
