### ISSUE TITLE
Destroying an off-canvas component with overlay leaves the body non clickable

### ISSUE THREAD

**Issue by vFragosop** [uikit/uikit#3510]
### UIkit version

3.0.0-rc.10

### Browser

Any browser.

### Reproduction Link

https://jsfiddle.net/vFragosop/2k63w9cy/

### Steps to reproduce

1. Click on `Open off-canvas`
2. Click outside the off-canvas
3. Click on the `<input>` to focus.
4. It should work
5. Click on `Open off-canvas` again
6. Now click on `Destroy component`
7. Try to focus the input
8. It doesn't work.

### What is Expected?

The body should clickable again.

### What is actually happening?

When the off-canvas opens, the following classes are added to `document.body`:

- `uk-offcanvas-container`
- `uk-offcanvas-flip`
- `uk-offcanvas-overlay`

These classes should be removed when the component is destroyed, but they are not. I've added a red background to `uk-offcanvas-overlay` so you can see it staying on the body.

**Comment by janschoenherr** [comment]
Yes, that's buggy at the moment.

    function destroy() {
        UIkit.offcanvas('#offcanvas').hide().then(function () {UIkit.offcanvas('#offcanvas').$destroy(true)});
    }

This is probably not the workaround you are looking for, as the hiding animation needs to finish first.

**Comment by vFragosop** [comment]
I didn't know component methods return promises. Maybe we should also add it to the docs? It may come in hand for a lot of different reasons.

**Comment by janschoenherr** [comment]
I believe this to be fixed. Please comment if not.

**Comment by vFragosop** [comment]
Fixed indeed :+1:
