### ISSUE TITLE
Sticky Navbar Dropbar not working

### ISSUE THREAD

**Issue by Igor-AZ** [uikit/uikit#3516]
Dropbar is opening, but the content inside of it is not showing.
When i inspect element, i can see new div under nav tag: `<div class="uk-navbar-dropbar uk-navbar-dropbar-slide" style="height: 0px;"></div>` , this is the div that is activated instead of `<div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">...`
The same thing is in your example on the webpage.

### UIkit version

3.0.0-rc.10

**Comment by janschoenherr** [comment]
Your reproduction link seems to be broken.

**Comment by janschoenherr** [comment]
It seems to work fine here: https://getuikit.com/docs/navbar#dropbar

You are having custom styling applied

     style="position: relative; z-index: 980;"

After removing that, it works fine too.

**Comment by Igor-AZ** [comment]
https://getuikit.com/docs/navbar#sticky-navbar second example

Here you can see the problem: https://imgur.com/jDaDG2X

**Comment by Igor-AZ** [comment]
I have removed that Style and it works now, but it needs to be fixed on the document page.

**Comment by artdive** [comment]
I have the same problem.
Error:
`Uncaught TypeError: Cannot read property 'parentNode' of null`
I have this structure:
```
<div uk-sticky>
  <div uk-navbar="dropbar: true"></div>
  <div class="uk-navbar-dropbar"></div>
</div>
```
