### ISSUE TITLE
ScrollSpy doesn't work with Angular Material on 100% height or auto overflow.

### ISSUE THREAD

**Issue by ivanherczeg** [uikit/uikit#3520]
The problem comes in, when we use Angular-Material for Angular 1. 
_Note: It is enough to include the angular-material.css, to trigger the issue._

Please check this six box [CodePen example](https://codepen.io/ivanherczeg/pen/rrKavo), and scroll down.

You can correct the situation, by disabling **height: 100%** or **oveflow:auto** in the scss, or removing **angular-material**.

_Tested with latest version 3.0.0-rc.1_

Thanks.

**Comment by janschoenherr** [comment]
Fixed with 3.2.4
