### ISSUE TITLE
Masonry Grid doesnot update the layout when content is hidden/changed dynamically

### ISSUE THREAD

**Issue by dobaniashish** [uikit/uikit#3523]
### UIkit version
3.0.0-rc.10

### Browser
All (Checked on latest Firefox and Google Chrome)

### Reproduction Link
https://codepen.io/anon/pen/zLaVYB

### Steps to reproduce
1. Create a masonry attribute.
2. Change content dynamically such as Changing the height or hiding one of the grid element after Dom is loaded. (Probably after 3 seconds)
3. See Codepan Javascript for more info.

### What is Expected?
The masonry is expected to update the Translate css and reset the layout

### What is actually happening?
The masonry does not update or reset the layout until window is resized.

### Description
I have to change hide/show some elements when user clicks on filter some grid out when user searches some text in an input. I tried multiple ways of hiding element which includes Jquery removeAttr/attr hidden, Jquery removeClass/addClass uk-hidden, UIkit.util.css display none. **UIkit.update still fixes layout properly.**

**Comment by TomS-** [comment]
From what I can see, it's working correctly? It just doesn't look right because you have the height of the card at "100px" but you are setting the first li to "50px".

https://codepen.io/anon/pen/rrZaBm
