### ISSUE TITLE
Opening multiple modals, causes browser/tab crash

### ISSUE THREAD

**Issue by edemircan** [uikit/uikit#3531]
### UIkit version

3.0.0-rc.11 or 3.0.0-Rc.10

### Browser
Chrome, Firefox

### Reproduction Link

https://codepen.io/ErolD/pen/ZjVYOE

### Steps to reproduce
Open multiple modals at same time
`
UIkit.modal.dialog('<p>UIkit dialog!</p>');
UIkit.modal.dialog('<p>UIkit dialog!</p>');
UIkit.modal.dialog('<p>UIkit dialog!</p>');
UIkit.modal.dialog('<p>UIkit dialog!</p>');
`
### What is Expected?
Something like modals showing beneath each other.

### What is actually happening?
Crashing website

**Comment by ruitalia** [comment]
Same here...

**Comment by janschoenherr** [comment]
This has been resolved.
