### ISSUE TITLE
Tooltip breaks on colon character

### ISSUE THREAD

**Issue by imaykutyalcin** [uikit/uikit#3532]
### UIkit version

3.0.0-rc.11

### Browser
Chrome on Windows x64 latest

### Reproduction Link
https://codepen.io/anon/pen/LBMjER

### Steps to reproduce
Hover over a tooltip which includes the : character, using the HTML Code works though: &#58;

### What is Expected?
Tooltip to display the full text from the data tooltip attribute

### What is actually happening?
Tooltip is empty

**Comment by janschoenherr** [comment]
<div uk-tooltip="title: broken tooltip :">I'm broken</div>

or 

    <div uk-tooltip data-title="broken tooltip :">I'm broken</div>
