### ISSUE TITLE
Lightbox animations are all the same

### ISSUE THREAD

**Issue by mattfletcher** [uikit/uikit#3534]
### UIkit version
3.0.0-rc.10

### Browser
Vivaldi | 1.15.1147.64 (Stable channel) (64-bit)
OS | Linux

### Reproduction Link
https://getuikit.com/assets/uikit/tests/lightbox.html

### Steps to reproduce
Visit test page

### What is Expected?
Different animations on each item from the Animations selector

### What is actually happening?
All seem to be the same animation to me

**Comment by janschoenherr** [comment]
Try clearing the browser cache. There has been an issue in the past and that has since been resolved.
