### ISSUE TITLE
Sortable Handle cancel scrolling on the whole element on Android

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3536]
### UIkit version

3.0.0-rc.11

### Browser
Works perfect on Safari and Chrome IOS.
Doesn´t works on Chrome - Android.

### Reproduction Link

Here you can see it clearly
https://zzseba78.github.io/Kick-Off/cards.html
Happens in the doc too.
https://getuikit.com/docs/sortable#handle
### Steps to reproduce
Try to scroll the page.
### What is Expected?
You can scroll the page, unless you position over the Sortable handle.
### What is actually happening?
You can´t scroll the page unless you avoid the whole Sortable element ( in the cards example, the whole card ).

**Comment by mohsenkhanpour** [comment]
@aarongerig  This is the same issue I told you about in Gitter. Seems like it's happening in the UI Kit docs too.

**Comment by janschoenherr** [comment]
We tried on Android here and it worked fine. What version of Chrome - Android are you using?

**Comment by psuplat** [comment]
I just tried on Android (6.0.1) with Chrome (68.0.3440.91) and Firefox (61.0.2). I am unable to scroll the content in both browsers if my finger is over the card and its content. I am ably to continue scrolling if I mange to "grab" the space between the card or either side of them (highlighted red in picture below).

![thumbnail](https://user-images.githubusercontent.com/14207860/44591565-f5d38780-a7b5-11e8-9634-20436144c439.jpeg)

**Comment by mohsenkhanpour** [comment]
@janschoenherr I am using Android 7.1, Firefox 61.0.2 and Chrome 68.0.3440.91.

**Comment by mohsenkhanpour** [comment]
@janschoenherr Steps to reproduce:
1. Open https://getuikit.com/docs/sortable#handle on an Android browser.
2. Move to `#handle` section.
3. Wait for scrolling to stop.

What happens:
1. Now you are unable to scroll by grabbing an area outside of the handle.
2. You are unable to sort Items by grabbing the handle. (The item is grabbed but moving it doesn't change anything and after releasing the drag the item moves back to its original position.)

**Comment by mohsenkhanpour** [comment]
The same thing happens in the tests page:
https://getuikit.com/assets/uikit/tests/sortable.html

I guess this bug is affecting the whole sortable component as I am not able to sort items properly in the tests page on Android.
