### ISSUE TITLE
offcanvas container & uk-svg

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3542]
### UIkit version

3.0.0-rc.11

### Browser
- Firefox
- Safari
- Chrome

### Reproduction Link
https://codepen.io/qdev/pen/PdqVpV?editors=1011

### Steps to reproduce
- wait until the SVG's are dynamically loaded (uk-svg) and icons colored
- the offcanvas Open button will show
- check console messages
- open offcanvas

### What is Expected?
- the icon inside offcanvas to be green

### What is actually happening?
- it is black (default), although previously altered on custom load handler

Curious is that if you check the console message of the `beforeshow` listener of the offcanvas (only first time it is opened) the color is fine, but then when showed, not anymore

I've found out that by moving the offcanvas container to body (default behaviour) is causing this
Somehow on [this line](https://github.com/uikit/uikit/blob/develop/src/js/mixin/modal.js#L192) I guess the original SVG is cloned

I couldn't find (yet) the reason, as before opening `UIkit.offcanvas('[uk-offcanvas]').$el` reports correct color

Thus, by simply disabling `container` offcanvas option, it works as expected (at least from this bug perspective) but in combination with `overlay: true` it introduces another bug (only on Safari this time) 

In this case, the offcanvas content is NOT visible at all, due to `.uk-offcanvas-overlay .uk-offcanvas-content { overflow-y: hidden }` CSS rule

**Comment by janschoenherr** [comment]
For me - using Chrome - it's working fine in your codepen. In general, as you suspected, if the offcanvas is taken out of the DOM and reinserted. The SVG is also being reset. You'd have to reapply the coloring.

**Comment by razvanioan** [comment]
I've double checked, Chrome (at least for Mac) doesn't work, like on all the other browsers I've tested.
Bellow there's a screenshot.

I've changed the Pen in order to automatically open the offcanvas & flipped it on the right side to see both icons.

Yeah, I've seen that it is moved in DOM the entire offcanvas content, but why all the HTML it's correct (final state, I've tested with AJAX data table too and that's fine) but the SVG not the latest state before the move, that's what intrigues me.

So you say that's better to reapply the SVG changes only on the first `shown` event, in order to make it right, I'll try that, but I'm still curious why is that.

![qdev 2018-08-25 09 42 21](https://user-images.githubusercontent.com/2914226/44615849-501f2780-a84c-11e8-9267-e6581eaefcb1.png)

**Comment by janschoenherr** [comment]
The SVG component removes the SVG element from the DOM the moment it is disconnected from the DOM and adds a new SVG element once it's connected again. Changes done to the element manually are lost.

You could use CSS to achieve the result you want though:

    [data-color="green"] svg * {stroke: green}

**Comment by razvanioan** [comment]
Yeah, I know I can use CSS.

But unfortunately my real cases are not that simple as the pen, I'm inserting complex custom animations on the SVG on the fly, because I want to use the same external file but acting differently on parts of the page.

Thanks
