### ISSUE TITLE
What is the feature of UIkit?

### ISSUE THREAD

**Issue by jsieler** [uikit/uikit#3544]
We (me and my friend) started using UIkit long time ago, since early versions of UIkit2. We were really happy to use it in all our projects instead ob bulky Bootstrap. UIkit gave us good possibility to style all our websites, projects the way we liked, easy way not to look all websites the same. We moved then to UIkit3 almost after first release and liked it too, just only we missed a lot of things from old v2.

There are already a lot of open issues about missing components, which are open since 2017 and those are still not resolved. I also understand that there is a company behind UIkit which has another things to do, other jobs and families, but a lot of questions about UIkit are still open. Everyone see new releases with only few fixes in new RC. Is that how it will be done now all the time? When is that so far that we will see RC 296 or RC 317 with only few CSS/JS changes? Probably not that long...

It there any ROADMAP for the project? What will be done, which components will be added when, estimated time for releases?

It would be also good to know which ideas are behind whole framework. There are a lot of good suggestions/contributions from members, which are left behind.

Right now it looks like UIkit ist slowly dying, but with every new release with small changes you let it do another breath, so it not die completely...

**Comment by saschadube** [comment]
Hi Jan, UIkit is far from dying. I'm a little shocked you got this impression. Active development never slowed down since we started UIkit 5 years ago. Let's take a look at [the stats](https://github.com/uikit/uikit/graphs/contributors):

Since the first UIkit 3 release – 20 month ago, there is nearly one commit every day and we released a new UIkit version every 12 days. That's pretty active, right? There were also some great feature releases:

- May 2018: [Masonry, Filter and Lazy Loading Image components](https://yootheme.com/blog/2018/05/14/uikit-3-rc-1-release)
- January 2018: [Slider component](https://yootheme.com/blog/2018/01/11/uikit-3-beta-36-released)
- October 2017: [Slideshow component and remove of jQuery](https://yootheme.com/blog/2017/10/20/uikit-3-beta-31-released)
- and so on ...

With the latest big release in May, UIkit got feature complete and RC status. Internally, the UIkit code is stable over a year. We just wanted to wait to get all the features in before we release a stable version. This will happen in the near future. Please follow [our blog posts about UIkit](https://yootheme.com/blog/tag/UIkit), to see what's coming next.

If you want to help the project, you are more than welcome. Please let us know which suggestions you think are left behind and what you got in mind for UIkit.

**Comment by jsieler** [comment]
Thanks for your reply, Sascha! We following UIkit development long time, and in meantime UIkit changed its status to RC some other frameworks were released, which got more popular from start than Uikit (see Bulma for example). And that is very sad.

What is sad also, that you're adding new features and removed old which were on v2 (autocomplete, calender,...). As for now there is always need to load third party libraries to got same functionality as one was with v2 out of the box. A lot of months passed and those are still not there. Core functionality was wiped in flavor of new features (which are also good too).

We also regulary check your blog, but... last post from "January 11, 2018". So, what should new users see there? Nothing new since over half a year. What will user think while seeing that? Dead.

If you check the stats yourself, you will notice that contributions amount is decreasing from month to month. That is also not a good sign.

Your mentioned "really big feature releases" are also not that big if you compare them with v2. They were already there, got rewritten to fit v3 requirements. So, are those really that big? May be, but nothing new.

> We just wanted to wait till all the features are on board before we release a stable version.
So, and there is the good point. No one know what are those features. How to contribute if we don't know what are you trying to build?

I'm not trying to shit-post or to blame anyone, just want to know what will happen to uikit next time.

**Comment by zzseba78** [comment]
@jsieler Some thoughts...

> ...some other frameworks were released, which got more popular from start than Uikit (see Bulma for example).

Bulma it´s not released yet, it´s v 0.7.1, you can say you can use it already, well, in that case you get my point... 
https://github.com/jgthms/bulma/issues/1857
Q: v1.0 release date?
Answer from author of Bulma: I can't provide a timescale, but know that Bulma is already usable as is.

> Right now it looks like UIkit ist slowly dying, but with every new release with small changes you let it do another breath, so it not die completely..

Well, you have to be very ungrateful to make an appreciation like this, for a frameworks that is offered for free, that has taken tons of work (you know if you have followed the whole process as you say) and that it is even a beautiful and healthy newborn baby.

Sorry for the intervention @jsieler , but I preferred to give this return to give you a well deserved 👎

**Comment by saschadube** [comment]
PS: Regarding the Date- and Timepicker. Why not use the native browser implementations? Here is the [Datepicker](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) and here the [Timepicker](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)

**Comment by jsieler** [comment]
Native Date- Timepicked are only good if you don't need styling. That was nice part on v2.

Btw, last Uikit blog post is not listed under Uikit tag. See yourself:  https://yootheme.com/blog/tag/UIkit

**Comment by cookmscott** [comment]
Sasche, I just want to jump on this thread and praise all the hard work you and the team put into UIKit. It is one of the cleanest and most complete UI frameworks that I use _all_ the time. I don't use Wordpress or Joomla so I have no need for Yootheme pro, but if there's any way I can support or contribute, please let me (us) know. 

Thanks again :)

**Comment by saschadube** [comment]
@cookmscott Thanks 😊

**Comment by andy-blum** [comment]
Late to the party here, but I'd also like to commend the uikit team for a fantastic product. I'm one of the maintainers for the [Drupal theme implementation of UIKit](https://www.drupal.org/project/uikit) and we LOVE the theme.

I am curious if there is any rough idea when v3 will be upgraded from RC to a full release. Any ballpark dates there?

**Comment by forrestkirby** [comment]
> Btw, last Uikit blog post is not listed under Uikit tag. See yourself: https://yootheme.com/blog/tag/UIkit

It is listed at the very top (above the tag filter).
