### ISSUE TITLE
Not a bug, just wanted to ask how can i import individual component in react without importing the entire js and css file

### ISSUE THREAD

**Issue by vikas091** [uikit/uikit#3548]
I want to import some uikit components in my existing react app but dont want to import the entire uikit js and css files as i am using chunking in my app and importing the entire js file will unnecessarily in crease the size of chunk and most of its i wont even be using. Is there is any way to do that, if not is there is any way i could rewrite the uikit component in react using most of the code that is already there.

Thanks

**Comment by Alymbek** [comment]
see #3094
