### ISSUE TITLE
height: auto problem with SVG elements in IE11

### ISSUE THREAD

**Issue by JeremieD** [uikit/uikit#3553]
### UIkit version
Introduced in 3.0.0-rc.12, I suppose with the "responsive SVGs" feature.

### Browser
Internet Explorer 11
### Explanation
If you go to www.jeremiedupuis.com/test, in the top right corner of the `nav` bar you will see the language selector. In all browsers this looks completely fine, but in IE 11, if you open it, you'll see that the height of each `li `element is completely messed up.
From the information I could gather, it seems to be a problem with IE's interpretation of the `height: auto` property that is set on `svg `elements by UIKit. Disabling it in IE seems to be working just fine, as it resolves to using the inline value, which I think is what hapenns in other browsers.
Now I don't know what was the exact purpose of the property to begin with, but if someone could enlighten me on the matter I would greatly appreciate it. From what I can see, removing the property for `svg `elements seems to solve everything and doesn't mess with other icons.

EDIT: I fixed it on my website by regressing to rc.11, so I add a test page to demonstrate the problem.

**Comment by andrispraulitis** [comment]
#3547

**Comment by piotr-cz** [comment]
IMO this issue may be closed thanks to https://github.com/uikit/uikit/commit/a2bbfc83b392401ba0e22370c2e7990a3993312f

**Comment by saschadube** [comment]
@piotr-cz Yes, should be fixed with the mentioned commit.

@JeremieD Please reopen if not
