### ISSUE TITLE
[BUG] Flip style offcanvas moves to left if show is called during hiding animation of another offcanvas

### ISSUE THREAD

**Issue by brendonwai** [uikit/uikit#3554]
### UIkit version
3.0.0-rc.12

### Browser
Chrome, Firefox, Edge

### Reproduction Link
https://codepen.io/brendonwai/pen/pORJmK

### Steps to reproduce
With sidebar 1 already showing, click "open sidebar1" button then IMMEDIATELY click "open sidebar2" button

### What is Expected?
Sidebar one should hide, then sidebar 2 should show on the right side.

### What is actually happening?
Sidebar 2 got bounced to the left side even when its flip attribute is true.

**Comment by rangka-kacang** [comment]
I think this has something to do with the animation timing/queue. I wonder who click "sidebar 2" as soon (milliseconds) as they click on "sidebar 1". Nevertheless, it's a cool bug. Let's see what the contributors say about this. It will happen the other way around to if "sidebar 2" already showing and click "sidebard 2 + sidebar 1" soon after.

**Comment by brendonwai** [comment]
Just a little more background on how I ran into this bug:
The bug actually shows up as well if we call the offcanvas.show function while another offcanvas is going through its hiding animation. That was how I originally came across the bug. The demo is for a more visual representation, but the root cause (as I suspect it) should be the same in both repro cases.

**Comment by brendonwai** [comment]
Just found out that double-clicking the other button while the first off-canvas is open will trigger the same bug.
