### ISSUE TITLE
Scrollspy in Modal is not working as expected

### ISSUE THREAD

**Issue by dobaniashish** [uikit/uikit#3557]
Scrollspy in Modal is not working as expected. If we put the Scrollspy (Scrollspy in a grid) inside of a modal and open it, The scrollspy is triggered only for the upper visible elements and not for the elements that are below the fold. Scroll a little and the elements aren't visible and even the event isn't fired.

### UIkit version
3.0.0-rc.12

### Browser
Checked on Firefox 61.0.2 (64-bit) / Chrome 68.0.3440.106 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/anon/pen/QVpVoL

### Steps to reproduce
Open the modal and scroll a little bit.

### What is Expected?
The lower elements to be visible.

### What is actually happening?
The lower elements aren't being visible.

**Comment by BranquinhodSouza** [comment]
<a class="uk-button uk-button-default" href="#modal-example" uk-toggle>Open</a>
<div id="modal-example" class="uk-modal" uk-modal="" style="">

  <div id="div" class="uk-modal-dialog uk-modal-body" uk-overflow-auto>

    <h2 class="uk-modal-title">Test</h2>

    <div class="uk-child-width-1-1 uk-grid-small" uk-grid uk-scrollspy="target:  #div;">

**Comment by BranquinhodSouza** [comment]
i think the problem is in "uk-scrollspy", he is not identifying the right div. Use "id" for this

<div id="div" class="uk-modal-dialog uk-modal-body" uk-overflow-auto>

<div class="uk-child-width-1-1 uk-grid-small" uk-grid uk-scrollspy="target:  #div;">

**Comment by BranquinhodSouza** [comment]
i think the problem is in "uk-scrollspy", he is not identifying the right div. Use "id" for this
<div id="div" class="uk-modal-dialog uk-modal-body" uk-overflow-auto>
<div class="uk-child-width-1-1 uk-grid-small" uk-grid uk-scrollspy="target:  #div;">

**Comment by BranquinhodSouza** [comment]
`<div id="div"class="uk-modal-dialog uk-modal-body" uk-overflow-auto> <div class="uk-child-width-1-1 uk-grid-small" uk-grid uk-scrollspy="target:  #div;">`

**Comment by dobaniashish** [comment]
I am targeting the elements as a group https://getuikit.com/docs/scrollspy#groups

Tries this:
`uk-scrollspy="target: > div;"`

as well as this
`uk-scrollspy="target: > div > .uk-card;"`

both doesn't work.

I think the Scrollspy component is only hooked to window scroll event and not the modal scroll event.

**Comment by janschoenherr** [comment]
This has been resolved.
