### ISSUE TITLE
uk-width-1-1@s uk-width-expand is expanding at all screen widths

### ISSUE THREAD

**Issue by Bloemendaal** [uikit/uikit#3559]
### UIkit version

3.0.0-rc.13

### Browser
Chrome 68 (latest)
### Reproduction Link

[https://codepen.io/Bloemendaal/pen/jvmzOB](https://codepen.io/Bloemendaal/pen/jvmzOB)
### Steps to reproduce
Create a grid with 2 children, one with a random width, let's say `uk-width-1-3`, and one with a full width at devices `@s` and expand (`uk-width-1-1@s uk-width-expand`). 
### What is Expected?
A full width at devices with a width larger than 639px and an expanded width at mobile devices.
### What is actually happening?
An expanded width at all sizes. It seems to be the css `flex: 1`.

**Comment by zzseba78** [comment]
Related to https://github.com/uikit/uikit/issues/2858

**Comment by Bloemendaal** [comment]
Oh, oops, didn't find that issue because it is closed

**Comment by zzseba78** [comment]
@Bloemendaal Sorry, I do not mean that it's repeated, I mean I published the same thing a while back.

**Comment by saschadube** [comment]
Thanks for reporting! Fixed with https://github.com/uikit/uikit/commit/c20ef70204d86bcdcc14a0aff93474e1a5368fd8
