### ISSUE TITLE
Drop, Dropdown and Tooltip component elements causes flickering in UIkit 3.0.0-rc.13

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3560]
### UIkit version

3.0.0-rc.13

### Browser
Chrome 68.0.3440.106

### Reproduction Link

[Drop](https://getuikit.com/docs/drop), [Dropdown](https://getuikit.com/docs/dropdown), [Tooltip](https://getuikit.com/docs/tooltip)
### Steps to reproduce
Just click or hover on **Drop**, **Dropdown** or **Tooltip** component elements.

### What is Expected?
😎 All works "like a boss".

### What is actually happening?
Click or hover on **Drop**, **Dropdown** or **Tooltip** component elements causes flickering.

**Comment by psuplat** [comment]
Flickers on Chrome, Firefox & Opera.
Works fine on Safari, Edge & IE11.

**Comment by zzseba78** [comment]
Confirmed :point_up:

**Comment by Bloemendaal** [comment]
uk-switcher with animations started flickering as well. It even breaks the complete switcher.
[https://getuikit.com/docs/switcher#animations](https://getuikit.com/docs/switcher#animations)

**Comment by janschoenherr** [comment]
Thanks, fixed with rc 14

**Comment by viocassel** [comment]
Thanks @janschoenherr !
