### ISSUE TITLE
Modal events triggered by child components as well (eg: dropdown)

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3561]
### UIkit version
3.0.0-rc.14

### Browser
Any

### Reproduction Link
https://codepen.io/qdev/pen/NLwZWE?editors=1011

### Steps to reproduce (check console)
- open modal (modal `beforeshow` event triggers correctly)
- hover on dropdown (same event is triggered for containing dropdown)
- close dropdown (modal `beforehide` event triggers wrongly)
- close modal (same event triggers as expected)

### What is Expected?
- child components not to trigger parent components events

### What is actually happening?
- it seems that they do

### Temporary workaround
I just check event target object to see if it's what desired or not ...

**Comment by janschoenherr** [comment]
Most components fire the same events - the events then bubble up the DOM. Yes, you'll need to check for the event target to determine what is firing `beforeshow` etc.
