### ISSUE TITLE
Changing the src of images inside a slideshow makes the slideshow events fire

### ISSUE THREAD

**Issue by mthomsonnz** [uikit/uikit#3564]
UIkit version: 3.0.0-rc.14
Browser: All
Reproduction Link: https://codepen.io/matt_nz/pen/NLvEWK?editors=1111

If Images are lazy loaded inside the slideshow, then the slideshow events fire a lot, and any behaviors added to these events fire too. Ideally these events should not fire when html inside the slideshow is changed.

**Comment by janschoenherr** [comment]
This has been resolved. Thanks.
