### ISSUE TITLE
Discouraged export pattern.

### ISSUE THREAD

**Issue by atilkan** [uikit/uikit#3565]
This pattern is discouraged. Because "JS engine cannot statically analyze the contents of plain object".
**Refering book ->** https://goo.gl/5bfwdb

https://github.com/uikit/uikit/blob/de76a0925c8dd1042778eea13d081f5af4ad1565/src/js/core/drop.js#L7

**Comment by janschoenherr** [comment]
The link to the book does not seem to work. I will close this for now.

**Comment by atilkan** [comment]
It has been over 1 year. Do whatever you want.
