### ISSUE TITLE
uk-sortable removes element height whilst dragging

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3568]
### UIkit version

3.0.0-rc.16

### Browser

Chrome Version 69.0.3497.81 (Official Build) (64-bit)

I have a container div with height that is calculated with javascript, so it just appears like this:

```
<div class="uk-width-1-1 my_container uk-sortable" uk-sortable="handle: .editable_content .sortable_grabber" style="height: calc(100vh - 184px);">

<!-- content here -->

</div>
```

When i drag a child div within the container to resort it, the height element of `.my_container` is removed (so it collapses to the height of the content).  

If i set the `min-height` on the element, however, this doesn't occur.  

I thought I had resolved the issue by making the javascript set `height` AND `min-height`.  

But actually, because height is still removed by `uikit`, the problem persists where there is overflow content but no scrollbars appear because there is no height on the element (`overflow-y: auto` is defined).

**Comment by oshihirii** [comment]
"uikit": "^3.1.6"
    Chrome Version 75.0.3770.100 (Official Build) (64-bit)

One year later I have a reproducible codepen (and animated gif) :)

https://codepen.io/oshihirii/pen/zVLMYE

Steps to reproduce:

- Scroll to the end of the container
- Try and move the bottom div up a few places
-  You will see that it shoots to the top of the container div 
- (you can't just move it a few positions upwards)  

Animated GIF:

![sortable_woes](https://user-images.githubusercontent.com/5090307/60695751-33e91e00-9f26-11e9-8477-3dfa82af9d28.gif)

I think the problems are due to the container having `overflow-y: auto` and `height` values being set, ie:  

```css
.container {
  background: green;
  height: calc(100vh - 134px);
  min-height: calc(100vh - 134px);
  overflow-y: auto; 
}
```
How can I stop the div from "shooting to the top" and make it move in a controlled manner like the official UIkit sortable demo on codepen:

https://getuikit.com/docs/sortable

**Comment by janschoenherr** [comment]
Yes, for the animation of the sortable items, a `height` is placed on the sortable itself. It works fine, if you wrap the ```<div class="container"``` around the sortable.

**Comment by oshihirii** [comment]
Thanks for information @janschoenherr .

I'm not sure if I understood correctly, but I tried wrapping the `sortable` in a `.container` div and changed the structure from this:
```html
<div class=" container uk-grid-small uk-child-width-1-1 uk-text-center" uk-sortable="handle: .uk-card" uk-grid>
    <div>
        <div class='uk-card uk-card-default uk-card-body'>Item 0</div>
    </div>
    <div>
        <div class='uk-card uk-card-default uk-card-body'>Item 1</div>
    </div>
    <!-- etc -->
</div>
```
to this:
```html
<div class="container">
    <div uk-sortable="handle: .uk-card" class="uk-grid-small uk-child-width-1-1 uk-text-center" uk-grid>
        <div>
            <div class='uk-card uk-card-default uk-card-body'>Item 0</div>
        </div>
        <div>
            <div class='uk-card uk-card-default uk-card-body'>Item 1</div>
        </div>
        <!-- etc -->
    </div>
</div>
```
But that solution prevents the ability to drag anywhere beyond the viewable area:

Original codepen:  https://codepen.io/oshihirii/pen/zVLMYE  
Forked codepen with wrapper suggestion:  https://codepen.io/oshihirii/pen/dBjEMR

![sortable_woes_wrapper](https://user-images.githubusercontent.com/5090307/60705568-cac7d180-9f4a-11e9-9999-3310c8965d36.gif)

**Comment by janschoenherr** [comment]
Sorry, I understand, yes, currently Sortable scrolls the page only. It does not scroll within containers.

**Comment by oshihirii** [comment]
For reference, it *does* seem to work in containers, just as long as a height is not assigned to them.  

Forked codepen without height on container:  https://codepen.io/oshihirii/pen/ydxNwe

[ 01 ]  The first scenario below shows undesired behaviour when container has a height.

[ 02 ]  The second scenario shows desired behaviour when container does not have a height.  

![sortable_woes - container proof](https://user-images.githubusercontent.com/5090307/60718778-fe195900-9f68-11e9-8b3b-6e13d19e9ca5.gif)

**Comment by oshihirii** [comment]
hi @janschoenherr - sorry to bother you.

just to be clear, i take it as you haven't suggested a solution there isn't one?

i'd really like to be able to use sortable inside a container as shown above.  

i've found most things in programming are possible - so a bit reluctant to just give up.

from the 'outside' it seems such a minor constraint.  

what do you think it would take to get sortable working on scrollable containers with set heights?  

money?  fiddling around with how the animation works?

thank you :pray:

**Comment by janschoenherr** [comment]
I believe it should be solved. Can you test with the latest dev release?

**Comment by oshihirii** [comment]
very grateful, thanks.  

i'm getting mixed results.  

**codepen:** 

i linked to:  https://cdn.jsdelivr.net/npm/uikit@dev

which delivers `UIkit 3.1.7-dev.0a71b2dd7`

it doesn't seem to work when either:

- setting `animation: false` on the sortable, see:  https://codepen.io/oshihirii/pen/xombqj  

- wrapping sortable in a container AND setting `animation: false` on the sortable, see:  https://codepen.io/oshihirii/pen/QXzwog  

**locally:** 

it seems to work most of the time - below is a successful attempt dragging the last div to the top and bottom multiple times.  

on other attempts, it sometimes got 'stuck' when moving to the top, then the bottom, then to the top again.  

![sortable_woes - dev v1 kind of working v3](https://user-images.githubusercontent.com/5090307/60885646-63d05280-a293-11e9-97bb-4ee66f37ea73.gif)

**Comment by oshihirii** [comment]
...still, it is a lot better than before, so i'm pushing it to production hehe :).

**Comment by janschoenherr** [comment]
You can check the versions here: https://www.npmjs.com/package/uikit

UIkit 3.1.7-dev.0a71b2dd7 is an older dev build. It takes a while for jsDelivr to pick up the new version.

With the new version, I think wrapping the container will be enough. No need to set `animation: false`

**Comment by oshihirii** [comment]
fantastic.  

`jsdelivr` is serving the latest version now i think (`UIkit 3.1.7-dev.8168f1f61`).

i have updated the codepens which demonstrate functionality is working:  

- setting `animation: false` on the sortable, see: https://codepen.io/oshihirii/pen/xombqj

- wrapping sortable in a container, see: https://codepen.io/oshihirii/pen/QXzwog

thank you very much again :pray:
