### ISSUE TITLE
Problem with SCSS svg-fill mixin in default theme

### ISSUE THREAD

**Issue by danbrellis** [uikit/uikit#3569]
Following the instructions for creating your own theme (https://getuikit.com/docs/sass#create-a-uikit-theme), if you copy the contents of uikit/scss/mixins-theme.scss and use that as your mixins file, the `@mixin svg-fill()` will not output a valid data-url for the background image of an icon.

I'm compiling with brunch (2.10.12) and plugin sass-brunch (2.10.4). UIkit (3.0.0-rc.6).

It's possible this is a brunch or sass-brunch issue, but I thought I'd bring it to attention here first.

**Steps to reproduce:**

1. Create a new theme folder and copy uikit's mixins-theme.scss as a new file: app/my-theme/mixins.scss
2. Import your new mixin file along with other files in your theme.
3. Create a accordion nav

```
    <ul class="uk-nav uk-nav-default uk-nav-parent-icon" uk-nav>
        <li class="uk-parent">
            <a href="#">Parent Item</a>
            <ul class="uk-nav-sub"><li><a href="#">Child Item</a></li></ul>
        </li>
    </ul>
```

**Expected:**
SVG icon placed in the .uk-parent::after element as a data url, like on the docs `background-image: url("data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2214%22%20height%3D%2214%22%20viewBox%3D%220%200%2014%2014%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Cpolyline%20fill%3D%22none%22%20stroke%3D%22%23666%22%20stroke-width%3D%221.1%22%20points%3D%2210%201%204%207%2010%2013%22%20%2F%3E%0A%3C%2Fsvg%3E")`

**Actual:**
An incorrectly formatted background-image property:
`background-image: replace('data-uri("image/svg+xml;charset=UTF-8", "data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2214%22%20height%3D%2214%22%20viewBox%3D%220%200%2014%2014%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Cpolyline%20fill%3D%22none%22%20stroke%3D%22#000%22%20stroke-width%3D%221.1%22%20points%3D%224%201%2010%207%204%2013%22%20%2F%3E%0A%3C%2Fsvg%3E")', 'escape("#000")', 'escape("#FFF")', "g")`

https://github.com/uikit/uikit/blob/6d30eb1a4b31c67301f8b3fa9e75e79098cd9759/src/scss/mixins-theme.scss#L711-L720

**Comment by bryce-gilhome-cp** [comment]
I've found the mixin in components/mixin.scss works - as a workaround, if you import it after importing scss/mixins-theme.scss, it should work.

**Comment by dalepgrant** [comment]
Also found this issue - thanks for the workaround!

**Comment by janschoenherr** [comment]
The next release will no longer contain the broken svg-fill mixins
