### ISSUE TITLE
uk modal bug with coverd and fixed bgImg

### ISSUE THREAD

**Issue by larssonsun** [uikit/uikit#3577]
### UIkit version

3.0.0-rc.16

### Browser
ie11, chrome v69.0.3497.100
### Reproduction Link

codepen can not reproduce this bug，this is the html:

```html
<!DOCTYPE html>
<html lang="zh-CN" class="uk-background-cover uk-background-fixed">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>modal bug</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.16/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.16/js/uikit.min.js"></script>
    <style>
           html { background:#fff url(http://yanshi.sucaihuo.com/modals/39/3978/demo/img/header.jpg);}
    </style>
</head>
<body>
    <a href="#modal1" uk-toggle>open</a>
    <div style="height:2000px"></div>
    <div id="modal1" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">content</div>
        </div>
</body>
</html>
```

### Steps to reproduce
just push open button 
### What is Expected?
open the modal dialog only, nothing else.
### What is actually happening?
background-img width converd and fixed style will change its size automaticaly

**Comment by larssonsun** [comment]
Thanks for replying, using a 2000px height div is to let the scrollbar display.
and now i upload the gif To show it.
![1](https://user-images.githubusercontent.com/26155353/45750416-95632900-bc41-11e8-90f8-fc5fff75315a.gif)
![2](https://user-images.githubusercontent.com/26155353/45750417-95fbbf80-bc41-11e8-8ecd-473498d60e99.gif)
top one is under ie11
another is under chrome

**Comment by psuplat** [comment]
LOL, in my case IE11 just shoved the modal to the bottom of the page 🤣 

Anyway, if you remove the 2000px style all is fine, and on OSX everything is fine in both cases. Something tells me that you are looking at OS/browser behaviour. If you look closely, you will see that when you open the modal, both browser are disabling the scrollbar. Maybe this has an effect on how the browser renders the content of the page, but that's just a guess.

**Comment by psuplat** [comment]
I'm pretty sure now it's the browser behaviour.

Test the below code in Chrome:

```
<!DOCTYPE html>
<html lang="zh-CN" class="uk-background-cover uk-background-fixed">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>modal bug</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.16/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.16/js/uikit.min.js"></script>
    <style>
	html { background:#fff url(http://yanshi.sucaihuo.com/modals/39/3978/demo/img/header.jpg);}
	::-webkit-scrollbar{display:none;}
   </style>

</head>
<body>
    <a href="#modal1" uk-toggle>open</a>
    <div style="height:2000px"></div>
    <div style="background-color:#fff">Hi! I should be at the bottom</div>

    <div id="modal1" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">content</div>
    </div>
</body>
</html>
```

I added a css that hides the scroll bars, while still allowing the user to scroll through the document.
Now calling the modal does not resize the background, while still allowing user to scroll to the bottom of the page (I added extra div with white background for visibility)

Keep in mind the added css will work for webkit browser only, so you need to research solution for FF, IE & Edge.

**Comment by larssonsun** [comment]
thanks for reply. maybe uikit will fix this problem？

**Comment by janschoenherr** [comment]
This seems to be resolved.
