### ISSUE TITLE
Image Component: data-srcset not working for background-image

### ISSUE THREAD

**Issue by danbrellis** [uikit/uikit#3579]
### UIkit version
3.0.0-rc.16

### Browser
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/danbrellis/pen/GXPXzg/?editors=1000 as well as the UIkit test page (about 2/3 down where the responsive background images start) https://getuikit.com/assets/uikit/tests/image.html

### Steps to reproduce
Create a background image with a srcset as per the documentation from UIkit:
```
<div class="uk-height-large uk-background-cover uk-margin-medium uk-flex uk-flex-center uk-flex-middle"
       data-src="https://via.placeholder.com/1200x450"
       data-srcset="https://via.placeholder.com/800x300 800w,
                    https://via.placeholder.com/1200x450 1200w,
                    https://via.placeholder.com/2400x900 2400w"
       data-sizes="(min-width: 1200px) 1200px, 100vw"
       uk-img>
    <h1>Background Image</h1>
  </div>
```

### What is Expected?
If the page is loaded and the screen size is ~800px wide, the 800x300 image should be shown. If the page is resized, the appropriately sized image should be swapped in.

### What is actually happening?
A (seemingly random) image from the srcset urls is assigned to the background-image url prop and then it will not change regardless of resize. Even on a fresh page load the incorrect image is often shown.

**Comment by zzseba78** [comment]
@danbrellis The responsive background works fine, when the page loads put the right background image according to the size to cover.
https://byhumans.works/area/test/responsive-bg.html

>If the page is resized, the appropriately sized image should be swapped in.

It´s true, the background image doesn´t change, you have to reload the page to see the change.

**Comment by danbrellis** [comment]
@zzseba78 when i go to that page I only ever got the 2000 x 700 (large) image displaying even when i would have the page load (no browser cache) to a smaller screen sizes. Here are screenshots of the screen at 320px, 639px, and 959px after a hard refresh:

![image](https://user-images.githubusercontent.com/7229803/45886270-bf723380-bd86-11e8-95bf-011f8aaffc34.png)

![image](https://user-images.githubusercontent.com/7229803/45886276-c305ba80-bd86-11e8-9430-1e3a05378623.png)

![image](https://user-images.githubusercontent.com/7229803/45886282-c5681480-bd86-11e8-860d-b93eeb6707dc.png)

**Comment by aarongerig** [comment]
@danbrellis You always have to clear the session storage. So in order to see the `500px` image do the following:

1. Go to the desired webpage, in this case [this one](https://byhumans.works/area/test/responsive-bg.html)
2. Resize your browser to less than `500px` width
3. Open your dev tools and navigate to `Application > Storage > Session Storage` and clear that cache
4. Reload your browser

Then you should see the `500px` image.

**Comment by danbrellis** [comment]
Welp, that did work. Thank you for pointing that out.
