### ISSUE TITLE
uk-flex not working in safari on iPhone (reproducable codepen and browserstack screenshots)

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3580]
### UIkit version

3.0.0-rc.16

### Browser
Safari/Chrome, iPhone 5S iOSv7
Safari/Chrome, iPhone 6 iOSv8
Safari/Chrome, iPhone 6 Plus iOSv8

### Reproduction Link

Live View:
https://codepen.io/oshihirii/live/mGvJaW

Live View at browserstack.com
![uk-flex-not-working-in-safari](https://user-images.githubusercontent.com/5090307/45800408-314d6d00-bcf4-11e8-96a4-9a15af26a8e9.png)

Pen View:
https://codepen.io/oshihirii/pen/mGvJaW  

### What is Expected?

Flex items will display inline.  

### What is actually happening?

Flex is not being recognised and flex items are stacked as block elements.

**Comment by oshihirii** [comment]
I've tested further on browserstack.com and the above behaviour occurs in:

iPhone 5S (Safari, Chrome)
iPhone 6 (Safari, Chrome)
iPhone 6 Plus (Safari, Chrome)

It displays as desired from iPhone 6S and up.  

I've googled `flex not working in safari iphone` and come across this answer:

https://stackoverflow.com/a/41425528

> I used [Autoprefixer](https://autoprefixer.github.io/) as suggested in the answers.
> 
> I use gulp to handle this when I write SASS. Here is a [guide](https://www.sitepoint.com/simple-gulpy-workflow-sass/).
> 
> Answers here are suggesting to use a prefixed property before the non prefixed one. I agree with a small correction.
> 
>     .container {
>         display: -webkit-flex;
>         -webkit-flex-wrap: wrap;
>         display: flex;   
>         flex-wrap: wrap;
>     }
>     
> Ideally, you need to list all of the prefixed properties before you start using the non prefixed ones. 


What is the solution to have `UIKit` working in iOS versions less than iPhone 6S (i use `LESS`)?  

(I am still using iPhone 4!)

**Comment by saschadube** [comment]
Which iOS and Safari version are you using?

**Comment by oshihirii** [comment]
@saschadube 

Below are results for Safari in:

iPhone 5S iOSv7
iPhone 6 iOSv8
iPhone 6 Plus iOSv8

The same behaviour occurs in Chrome browser.  

![iphone_5s_iosv7_safari](https://user-images.githubusercontent.com/5090307/45802418-1bdb4180-bcfa-11e8-9aad-db0fe4ff7e8e.png)

![iphone_6_iosv8_safari](https://user-images.githubusercontent.com/5090307/45802430-27c70380-bcfa-11e8-8c4e-eb41a3a27df2.png)

![iphone_6plus_iosv8_safari](https://user-images.githubusercontent.com/5090307/45802435-31506b80-bcfa-11e8-91cd-90dc61041c44.png)

**Comment by oshihirii** [comment]
Is the only way to handle it, to display a message if they are not using a modern browser?  eg:  

> It appears you are not using a modern browser.     
> 
> The application is supported on all modern browsers.  
> 
> The following list specifies the versions this application is supported on. 
> 
> "Latest" means that it works just fine on all recent versions of that browser. 
> 
> Chrome: Latest
> Firefox: Latest
> Edge: Latest
> IE:  11+  
> Safari:  9.1+  
> Opera: Latest

If so, how would that be accomplished?

**Comment by aarongerig** [comment]
@oshihirii Your browser / OS version is not supported by UIkit: https://getuikit.com/docs/introduction#browser-support

You could use a browser and/or OS version detection service to display that message. I'm sure the framework you are using is capable of such thing.

**Comment by oshihirii** [comment]
I am finding the earliest version on browserstack that seems to support flexbox, and other "random" things like the display of an absolutely positioned, z-index'ed div on jQuery click, is `iPhone 6` with `iOS 11`.  Anything lower just "doesn't work".    I don't even know how to begin applying the same sort of logic tests for Android etc.  I don't know how you guys do it, it's doing my head in :(.

**Comment by oshihirii** [comment]
I tried using Modernizr with the `Flexbox` and `Flex Line Wrapping` detects, but it seems it returns a `true ` result if browser supports `-webkit-` prefix  (which is not used in Uikit).  

For example, I tried the following at browserstack on `iPhone 5S`, `iOS, v7` and console logs `flexbox is supported`.   

https://codepen.io/oshihirii/live/mGvJaW

So i will have to try something else.  

**index.html**

```
<script src="/js/modernizr_flex_check.js"></script>
<script src="/js/bundle.js"></script>
```

**JS**
```
$(document).ready(function() {
    if (Modernizr.flexbox && Modernizr.flexwrap) {
        console.log("flexbox is supported");
    } else {
        console.log("flexbox is not supported");

        var no_content = `
        <div class="no_content">
        <p>It appears you are not using a modern browser.</p>
        <p>The application is only supported on modern browsers.</p>
        <p>The following list specifies the versions this application is supported on.</p>
        <p>"Latest" means it works fine on all recent versions of that browser.</p>
        <ul>
        <li>Chrome: Latest</li>
        <li>Firefox: Latest</li>
        <li>Edge: Latest</li>
        <li>IE: 11+</li>
        <li>Safari: 9.1+</li>
        <li>Opera: Latest</li>
        </ul>
        </div>
        `;

        $("body").html(no_content);
        return;
    }
});
```

**CSS**

```
.no_content {
    width: 80%;
    margin: auto;
    border: 1px solid #000;
    height: calc(100vh - 80px);
    margin-top: 20px;
    padding: 20px;
}
```

**Comment by oshihirii** [comment]
I also tried a CSS only solution which seems to be working ([based on this post](https://stackoverflow.com/questions/33359157/instead-of-using-prefixes-i-want-to-ask-site-visitors-to-upgrade-their-browser)):

**CSS**
```
.no_content_container {
    width: 100%;
    height: 100vh;
    position: absolute;
    z-index: 1;
    background: #fff;
    display: block;
}

.no_content_inner {
    width: 80%;
    margin: auto;
    margin-top: 10px;
    padding: 10px;
}

_:-ms-fullscreen, :root .no_content_container { display: none; }
:-o-prefocus, .no_content_container { display: none; }
@supports (display: flex) { .no_content_container { display: none; }}
```
**HTML**
```
<body>
    <div class="no_content_container">
        <div class="no_content_inner">
            <p>It appears you are not using a modern browser.</p>
            <p>The application is only supported on modern browsers.</p>
            <p>The following list specifies the versions this application is supported on.</p>
            <p>"Latest" means it works fine on all recent versions of that browser.</p>
            <ul>
                <li>Chrome: Latest</li>
                <li>Firefox: Latest</li>
                <li>Edge: Latest</li>
                <li>IE: 11+</li>
                <li>Safari: 9.1+</li>
                <li>Opera: Latest</li>
            </ul>
        </div>
    </div>
```

**Comment by oshihirii** [comment]
That's not even working completely - it seems Safari in iOSv9 is still handling `uk-flex`, `uk-width-auto` and `uk-width-expand` weirdly.  Nothing erroneous shows up in console or elements view in dev tools, but it just doesn't behave.

**Comment by oshihirii** [comment]
Can anyone recommend or otherwise using UIkit with https://autoprefixer.github.io?
