### ISSUE TITLE
Firefox uk-animation-kenburns not smooth at all

### ISSUE THREAD

**Issue by christianschley** [uikit/uikit#3581]
i built a slideshow with the slideshow component and gave the image in the slideshow the "uk-animation-kenburns" class for that nice smooth ken-burns-animation.

That works all fine in each browser except **Firefox Quantum 62.0 on Windows 10**.

The animation is there not smooth at all, it's jiggeling quite a lot.

Could this be fixed somehow?

**Comment by lareusmedia** [comment]
Edit: after pushing down the filesize of the images under ~100kb its getting way better.

But sometimes bigger filesizes are necessary...

**Comment by zzseba78** [comment]
Ken burns are css animations, using transform scale and a long duration...
By the way, i see them perfectly in Firefox Quantum OS Hight Sierra.
