### ISSUE TITLE
Icons Shrinking in Tables

### ISSUE THREAD

**Issue by ostannick** [uikit/uikit#3583]
### UIkit version
Most recent cdn link (3.0.0-rc.16)

3.0.0-rc.16

### Browser
Google Chrome

###JS Fiddle Link:
https://jsfiddle.net/sb0vzt69/6/

### Steps to reproduce
1. Make a table
2. Put an icon in the left hand cell
3. Put a long sentence in the right-hand cell, that covers the length of the container.

### What is Expected?
Icons should have a minimum width

### What is actually happening?
Instead, they shrink to be 1 pixel in size, in order to accomodate the adjacent cell.
Started happening roughly 2 hours ago

**Comment by zzseba78** [comment]
Add `.uk-preserve-width` css class to the icon span.
> Since images are responsive by default in UIkit, using an image inside a table cell with the .uk-table-shrink class would reduce the image width to 0. To prevent this behavior, add the .uk-preserve-width class from the Base component to the <img> element.

https://getuikit.com/docs/table#utilities
If your problem it´s solved please close this issue. Good luck.
