### ISSUE TITLE
yarn scope fails

### ISSUE THREAD

**Issue by stell** [uikit/uikit#3584]
I'm trying to scope an uikit build.
using latest uikit 3.0.0-rc.16, yarn 1.9.4, node 8.11.1

```
yarn scope

$ node build/scope
{ [Error: Unrecognised input]
  type: 'Parse',
  filename: 'input',
  index: 27,
  line: 3,
  callLine: NaN,
  callExtract: undefined,
  column: 2,
  extract: [ '/* scoped:*/', ' */', '  /*' ],
  message: 'Unrecognised input',
  stack: undefined }
Done in 1.33s.
```

All dependencies are fresh and should not be the problem.
Prefixing however works.

**Update:**
I found out that if i delete the compiled files inside the dist/css directory, then start a new compile and then the first run of `yarn scope -s "my"` works.
If doing a cleanup and trying again it fails.

**Comment by dasdeck** [comment]
hey @stell !
I recommend to only use the scope script on clean builds. I'll add a compilation step in the yarn scripts section and remove the clean options to make that clear.

**Comment by stell** [comment]
It would be great if scoping would be part of the compiling workflow if needed. We need to update everything in realtime.

**Comment by dasdeck** [comment]
I just found a way to fix the issue while keeping the "clear/change" functionality, it will be released soon. What is currently missing for your workflow?

**Comment by stell** [comment]
Thanks, i will check it out. We just want to edit less files and get the results updated in realtime inside the browser.
We solved that by creating our own Uikit3 buildprocess with gulp and creating a scope routine ourselves. Now we can see changes on our Uikit theme less files in realtime, but it would be better if this would work using the uikit own build and watch processes.
