### ISSUE TITLE
Don't inherit color from section-primary/section-secondary in card headings 

### ISSUE THREAD

**Issue by ecksite** [uikit/uikit#3587]
### UIkit version

3.0.0-rc.16

### Browser
Safari 11.1.2, Chrome 69.0.3497.100 and so on

### Reproduction Link

https://codepen.io/jannisr/full/YOoqrj/

### Steps to reproduce
Just set a primary or secondary section, set a card inside it and use headings

### What is Expected?
The colors of uk-card should NOT become inherited if uk-section-primary/uk-section-secondary AND card-default were used at the same time.
Default colors are actually correct, but headings are not.

### What is actually happening?
The colors become inherited -> white on white, so they are not visible.

**Comment by aarongerig** [comment]
@ecksite You have to add the class `uk-preserve-color` to your section and it works.

**Comment by ecksite** [comment]
@aarongerig Thank you, that works. But I don't really understand why this is not the default behavior.

plus this is not working if I use a default-card within a secondar-card (using uk-drop in this example) 
https://codepen.io/jannisr/pen/QVXEyd

**Comment by saschadube** [comment]
You can also deactivate the inherited color by setting the color mode for each card to dark.

```css
@card-primary-color-mode:                      dark;
@card-secondary-color-mode:                 dark;
```

Now you don't need to use `uk-preserve-color`.

Learn more about it (the inverse component) here https://getuikit.com/docs/less#disable-inverse-component

**Comment by johannesrusch** [comment]
@saschadube Is it at all possible, to have a default tile, with all the right colors, in a light section?

I'm trying to build something similar to this example:
https://codepen.io/johannesrusch/full/QWbJrXd

And I don't want to disable the inverse component.
