### ISSUE TITLE
Global Tooltip default options cannot be overwritten

### ISSUE THREAD

**Issue by drmzio** [uikit/uikit#3589]
### UIkit version

3.0.0-rc.16

### Browser

Chrome

### Reproduction Link

https://codepen.io/drmzio/pen/OoKVMo

### Steps to reproduce

1. Follow [documentation](https://getuikit.com/docs/javascript#globally) on setting global defaults
2. Try with the `tooltip` component.

### What is Expected?

Default options should be overwritten

### What is actually happening?

Nothing

**Comment by janschoenherr** [comment]
This has been fixed in rc.17.

There are two issues with your codepen though. Firstly the JS code is executed too late. By then, the tooltip has already been initialized. You'd have to reinitialize the tooltip. Secondly, the animation property needs to be an Array.
