### ISSUE TITLE
Vertical drag over a slider not scroll the page (previous iOS)

### ISSUE THREAD

**Issue by picov** [uikit/uikit#3591]
### UIkit version
3.0.0-rc.8
3.0.0-rc.12
3.0.0-rc.17

### Browser
Latest version of mobile Safari and Chrome for  iOS 9.x, 10.x 

### What is Expected?
A tap with vertical drag over a slider should scroll the page not the slider items. 

### What is actually happening?
The slider intercept the tap and use finger position for scrolling items thus is not possible to scroll the page vertically is there isn't other areas to touch (for example if the slider take the  full page)

I know that the browsers aren't the most recent versions but probably this could be a bug not to hard to fix.

**Comment by janschoenherr** [comment]
It seems to work fine for me on iOS 9.3.

**Comment by picov** [comment]
Sorry, my mistake: the problem was related to an additional JS code that disable right click on images used by the uk-slider. For some reasons that will need further investigation, this happen only on iOS 9.3 and not on 11 and latest 12 versions.
