### ISSUE TITLE
uk-dropdown extends past left: 0px if parent elements have padding or margin

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3595]
### UIkit version
3.0.0-rc.17

### Browser

Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Windows 10 Professional  

### Reproduction Link

https://codepen.io/oshihirii/pen/NOxgEz

### Steps to reproduce

01.  Visit codepen:  https://codepen.io/oshihirii/pen/NOxgEz

02.  Adjust browser width until `left` property of `uk-dropdown` is `0px` (and then keep going).

03.  You will see that the `left` property of `uk-dropdown` can extend up to `-30px` - the padding of the parent element - which means the leftmost content of the dropdown is not visible.  The problem goes away if the padding from the parent element is removed (however, the parent element needs padding).    

### What is Expected?

I expect dropdown not to extend beyond left side of screen.

**Comment by oshihirii** [comment]
If I move the div outside of parent container, to a next sibling position, then the desired behaviour occurs:

https://codepen.io/oshihirii/pen/LgGzEr

But then the whole previous div becomes the toggle element.  

If a specify a toggle element, it inherits the padding of the specified toggle element.  

I am using the javascript options now to show the dropdown - is there a way to disable the default event being triggered when hovering over the previous div?

**Comment by janschoenherr** [comment]
This seems to be fixed
