### ISSUE TITLE
Slider Bug Won't Infinite

### ISSUE THREAD

**Issue by kleur-id** [uikit/uikit#3598]
### UIkit version
3.0.0-rc.17

### Browser
Any

### Reproduction Link
https://streamable.com/uch9p

### Steps to reproduce
Slider with only 4 slides

### What is Expected?
Infinite slide back to 1st slide

### What is actually happening?
finite: false won't work

**Comment by janschoenherr** [comment]
The infinite mode is automatically disabled, as soon as the slides aren't covering enough space to scroll infinite (Unlike other sliders we are not cloning DOM elements).
