### ISSUE TITLE
uk-dropdown is beneath following siblings when used in masonry grid

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3604]
### UIkit version
3.0.0-rc.19

### Browser
Windows 10 Pro, Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/oshihirii/pen/LgjGYW

### Steps to reproduce

Click on buttons.  

### What is Expected?

Dropdown to appear above all other divs.  

### What is actually happening?

Dropdown is beneath other divs.  

Problem goes away if `masonry` is removed from:  `uk-grid="masonry:true"`.

**Comment by oshihirii** [comment]
**Update:**  

I've implemented another solution to get around this dynamic, which essentially:

- mimics the `uk-tooltip` functionality (an `on click, mouseover` to show and `mouseleave` to hide content)
- mimics the `uk-dropdown` styling.  

I append the dynamically generated div to `body` and then destroy it on `mouseleave`.  Because the div is outside of the container that has had the `transform` applied, its z-index is preserved and above other content as desired.

**Comment by zzseba78** [comment]
@oshihirii Hi!
This is not a UIkit issue, it´s how CSS works. Elements with transform ( used by UIkit masonry ) create their own stacking contexts, so if you apply zindex on card or dropdowns it works only for each columm, but other columns have his own stacking context.
Note: i saw this issue when making the Card Layout for Kick-Off, each card have his own dropdown, then i removed them to avoid confusion.
I don´t know if you can change this, but a possible solution is: place dropdowns outside of the stacking context. So, at the end of the page you can put all the dropdowns and target the reference element with toggle, each button should have a unique class or id. Example:
https://codepen.io/zzseba78/pen/dgVbXq

Read the first answer: https://stackoverflow.com/questions/20851452/z-index-is-canceled-by-setting-transformrotate

And here an article about the Stacking Context: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

It it works for you, please close the issue. Good luck.

**Comment by oshihirii** [comment]
@zzseba78 thanks for your comments, yes the only issue I kept coming up against was there was no way to maintain absolute position of dropdown to relative uk-card (to maintain position when scrolling content).  So I just went with solution in my last comment which appends div to body, outside of stacking context, but is destroyed on mouseleave.  It works ok for this scenario.

**Comment by oshihirii** [comment]
@zzseba78 - feel free to ignore but, in my scenario, masonry is applied to a container div that is scrollable - ie it has `height` and `overflow-y: auto` defined.

i forked your solution, and added `height` and `overflow-y` to the container, and now the dropdown "stays in place" whilst the rest of the content scrolls.  do you know how i can make it scroll in line with the rest of the content in the scrollable area?  

here is demonstration:

https://codepen.io/oshihirii/pen/GYMMNe
