### ISSUE TITLE
Slideshow Items ignoring custom CSS min/max height.

### ISSUE THREAD

**Issue by dpuffenberger** [uikit/uikit#3605]
### UIkit version

3.0.0-rc.19
3.0.0-rc.18
3.0.0-rc.17

### Browser
Edge (Latest), Safari (Latest), Chrome (Latest), Firefox (Latest)

### Reproduction Link

https://codepen.io/anon/pen/GYvxRZ

### Steps to reproduce
See CodePen.

### What is Expected?
In versions prior to 3.0.0-rc.17 we had the ability to set min/max height limits for slideshows using CSS without having one or the other overwritten by the auto-generated inline CSS injected by the JS. This made it really easy to create full-width, large responsive slideshows.

### What is actually happening?
Since 3.0.0-rc.17, the auto-generated CSS is setting the min-height parameter based upon window height instead of the CSS height parameter thus overwriting any min/max heights defined within custom CSS.

I was able to fix the issue by changing this section of the uikit.js file.

`

var Slideshow$1 = {

        mixins: [Class, Slideshow, SliderReactive],

        props: {
            ratio: String,
            minHeight: Boolean,
            maxHeight: Boolean,
        },

        data: {
            ratio: '16:9',
            minHeight: false,
            maxHeight: false,
            selList: '.uk-slideshow-items',
            attrItem: 'uk-slideshow-item',
            selNav: '.uk-slideshow-nav',
            Animations: Animations$2
        },

        update: {

            read: function() {

                var ref = this.ratio.split(':').map(Number);
                var width$$1 = ref[0];
                var height$$1 = ref[1];

                height$$1 = height$$1 * this.list.offsetWidth / width$$1;

                if (this.minHeight) {
                    height$$1 = Math.max(this.minHeight, height$$1);
                }

                if (this.maxHeight) {
                    height$$1 = Math.min(this.maxHeight, height$$1);
                }

                return {height: height$$1 - boxModelAdjust(this.list, 'content-box')};
            },

            write: function(ref) {
                var height$$1 = ref.height;

                css(this.list, 'Height', height$$1);) /* Original: css(this.list, 'minHeight', height$$1);) */
            },

            events: ['load', 'resize']

        }

`

**Comment by zzseba78** [comment]
@dpuffenberger Add this to uk-slideshow: `ratio: false;` and you are done. If works, please close this issue.

**Comment by dpuffenberger** [comment]
That worked. Thanks.

**Comment by zzseba78** [comment]
@dpuffenberger Great!
