### ISSUE TITLE
** Question ** Why UIkit3 doesn´t use css position:sticky in Position utility classes?

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3608]
### UIkit version

3.0.0-rc.19

### Browser
https://caniuse.com/#feat=css-sticky

### See it working
https://codepen.io/zzseba78/pen/jeGOaz

### What is actually happening?
I don´t know what´s  happening 😄 
Css sticky positioning it´s great to become elements sticky relative to their parent, and browser support it´s quite nice, performance of course it´s great...

Why don´t add it? For IE 11? You could put a note about it and support issues, linked to Can i use, and some basic info about partial support on Chrome and Edge ( at the moment ).

As you know, Bootstrap 4 already use it: https://getbootstrap.com/docs/4.0/utilities/position/#sticky-top

UIkit already have this feature? True, but with a native css solution performance it´s better, and can be applied in some cases where js Sticky doesn´t work well.

And if you want more control ( Change styling on sticky, choose parent, etc ) use the UIkit js version of course.

I think it could be a nice addition to the Utility classes, at a very low cost.

Thanks for your work

**Comment by atilkan** [comment]
It doesn't well supported. And it doesn't always work great.
