### ISSUE TITLE
Sticky bottom does not calculate when bottom is in view

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3609]
### UIkit version

3.0.0-rc.19

### Browser
Chrome

### Steps to reproduce
1. Create a sticky with bottom: true. 
2. Refresh the page when the bottom is in viewport.
3. Sticky will no longer respect the 'bottom' and break out. 

### What is Expected?
Should respect the parents bounds.

### What is actually happening?
Doesn't respect the parents bounds/

**Comment by zzseba78** [comment]
@TomS- Can you create a reproduction link?

**Comment by TomS-** [comment]
@zzseba78 

Trying to reproduce - I came across another bug - uk-sticky-placeholder does not take the height until the browser is resized: https://codepen.io/anon/pen/XxVRoM

The code that I'm using that causes sticky - bottom: true; to fail when bottom is in viewport: 
https://codepen.io/anon/pen/aREwyK (Again resizing this fixes it. The issue with Codepen is it always defaults to scrollTop(0, 0). So it's hard to demonstrate).

**Comment by TomS-** [comment]
I believe part of the issue is placeholders in uk-img are generated after uk-sticky is calculated. From what I can tell. Because I have placeholders set up correctly, but sometimes it still displays as 0 height while the image is loading.

**Comment by TomS-** [comment]
While not documented this has been fixed in RC 20.
