### ISSUE TITLE
Slider with 4 images: Finite not working

### ISSUE THREAD

**Issue by helmutkaufmann** [uikit/uikit#3610]
### UIkit version

3.0.0-rc.19

### Browser

Safari

### Steps to reproduce

Craete a slider with 4 images and set finite: false

### What is Expected?

The slider should start with the first image again aper image 4 has been shown.

### What is actually happening?

The slider stops as if finite:true were set

**Comment by velrest** [comment]
I can also reproduce this. It happens if the amount of images is >5.

**Comment by janschoenherr** [comment]
The infinite mode is automatically disabled, as soon as the slides aren't covering enough space to scroll infinite (Unlike other sliders we are not cloning DOM elements).

**Comment by lukeb** [comment]
The slider should be able to infinite scrolling if the item count is columns+1. However, it currently is only working with columns+2.

**Comment by janschoenherr** [comment]
@lukeb That is only true, if all the slides have the same width.

**Comment by lukeb** [comment]
Why would having the same width make the issue invalid? Can you please re-open?

**Comment by janschoenherr** [comment]
I was referring to:

> The slider should be able to have infinite scrolling if the item count is columns+1

It's not about the amount of slides, but if you would see any whitespace when scrolling infinite.

**Comment by lukeb** [comment]
You should not see any white space if there are columns + 1.
