### ISSUE TITLE
uk-img placeholder doesn't work correctly.

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3612]
This bug also breaks uk-sticky overall sticky seems to be more reliable on RC 16. 

### UIkit version

3.0.0-rc.19

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/VEQQVy/ (Use refresh + clear cache CMD + SHIFT + R on Mac)

### Steps to reproduce
1. If the image exists, placeholder will not work until the image is loaded. 
2. If the image doesn't exist a placeholder is correctly loaded. 

### What is Expected?
The image area should hold it's width / height until the image is loaded.

### What is actually happening?
The svg isn't generated.

**Comment by janschoenherr** [comment]
UIkit tries to determine if an image is already cached or not. It does that by storing information about loaded images in the sessionStorage. If you clear the browser's cache, it will not clear the sessionStorage. In that case UIkit still thinks the image is cached and therefore does not use a placeholder.

Calling `sessionStorage.clear()` will clear that Storage.

**Comment by TomS-** [comment]
@janschoenherr because of this, sometimes if the image isn't loaded instantly, even if cached. It causes undesired effects with things such as scrollspy in terms of appearing in the viewport before it's actually moving into the correct place. So in some cases the animation isn't played when the object comes into viewport as technically it's already been in the viewport.

Is there any reason why you just don't load in the svg placeholder until image on load? It seems to me like that would make more sense right? Is it a performance thing?

**Comment by TomS-** [comment]
@janschoenherr it's actually becoming a problem when using this with scrollspy. The images do not always load right away, even if javascripts assumes they are cached. Scrollspy will fire because on DOM load element are in viewport as the image hasn't pushed it down. 

This is completely opposite to what is expected from placeholders.

**Comment by janschoenherr** [comment]
I understand the problem you are facing. I am just not sure what to do about it. I wonder why - if cached - the images do not load right away? However, i will further investigate and try to come up with a better solution.

**Comment by TomS-** [comment]
@janschoenherr 
I'm unsure. Refreshing the same page will be fine. However, if you visit another page and re-visit the previous page (not using the back button but clicking a link) sometimes you will see the images not load in instantly, regardless of the fact that they are "cached".

I appreciate you looking into this, for now I've just removed the check here and always make it generate the svg placeholder. https://github.com/uikit/uikit/blob/develop/src/js/core/img.js#L68

This has a better appearance when loading as the placeholder will always be present and prevent the content jump you see. Even though width and height is defined. It could be the case that isn't getting the width and height of "cached" images correctly. I know it also caused other issues in UIKit for example  (https://github.com/uikit/uikit/issues/3629)

**Comment by TomS-** [comment]
This is still an issue in RC 26 sadly. I will apply my fix to the new version also.

**Comment by TomS-** [comment]
Hi @janschoenherr 

I can't seem to replicate this in 3.0.1, has this been fixed?
