### ISSUE TITLE
uk-navbar-toggle-icon does not work with the uk-navbar-center class (left or right) in Chrome. 

### ISSUE THREAD

**Issue by nsbzezzi** [uikit/uikit#3613]
uk-navbar-toggle-icon does not work with the uk-navbar-center-(left or right) class in Chrome. In firefox works correctly.
In chrome , the icon (uk-navbar-toggle-icon) does NOT APPEAR in mobile! Only in Firefox browser

### UIkit version

3.0.0-rc.19

### Browser
Chrome and Firefox
### Reproduction Link
https://codepen.io/alexandro-josi-zezzi/pen/xyYjox

### Steps to reproduce
    <div id="offcanvas-flip" uk-offcanvas="overlay:true">
        <div class="uk-offcanvas-bar">
            <button class="uk-offcanvas-close" type="button" uk-close></button>

        </div>
    </div>
    <div class="uk-offcanvas-content">    
        <div class="uk-navbar-container" uk-navbar>
            <nav class="uk-navbar-center">
                <div class="uk-navbar-center-left">
                    <div>
                        <ul class="uk-navbar-nav uk-visible@s">
                            <li><a class="uk-link-reset" href="#0">Home</a></li>
                            <li><a class="uk-link-reset" href="#0">Laripara</a></li>
                            <li><a class="uk-link-reset" href="#0">Pararapere</a></li>
                        </ul>
                    </div>
                </div>
                <a href="#0" class="uk-navbar-item uk-logo"><img src="https://dummyimage.com/150x50/f35/fff" height="50" alt=""></a>
                <div class="uk-navbar-center-right">
                    <div>
                        <ul class="uk-navbar-nav uk-visible@s">
                            <li><a class="uk-link-reset" href="#0">Larilara</a></li>
                            <li><a class="uk-link-reset" href="#0">Cherempere</a></li>
                            <li><a class="uk-link-reset" href="#0">Marapara</a></li>
                        </ul>
                        <a class="uk-navbar-toggle uk-hidden@s"  uk-toggle="target: #offcanvas-flip">
                            <span uk-navbar-toggle-icon></span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>

**Comment by semenyakNik** [comment]
#https://github.com/uikit/uikit/pull/3614

**Comment by janschoenherr** [comment]
This seems to be fixed.
