### ISSUE TITLE
Dynamically created Lightbox not destroyed on hide

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3623]
### UIkit version

3.0.0-rc.19

### Browser
Chrome

### Steps to reproduce
1. Dynamically create a lightbox. 
2. Close it. 

### What is Expected?
Lightbox should be destroyed until generated again. 

### What is actually happening?
You will see multiple lightboxes being created based on how many times it's been opened.

**Comment by janschoenherr** [comment]
Resolved in `develop` version.
