### ISSUE TITLE
Can't hook to events on dynamically created Lightbox

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3624]
### UIkit version

3.0.0-rc.19

### Browser
Chrome

### Steps to reproduce
1. Dynamically create a lightbox:
```
var lightbox = UIkit.lightboxPanel({
    items: [{source: link}]
}).show();
```
2. Try to do something when it's closed (for example destroy it because of the non-destroy bug): 
```
UIkit.util.on(lightbox, 'hide', function() {
    alert('hello');
})
```

### What is Expected?
Alert should be fired when lightbox is hidden

### What is actually happening?
You can not hook lightbox events to lightboxPanel. There is no way to dynamically create a lightbox using the lightbox utility.

**Comment by janschoenherr** [comment]
```
UIkit.util.on(lightbox.$el, 'hide', function() {
    alert('hello');
})
```

**Comment by TomS-** [comment]
Actually, tested this. It does not work.

**Comment by janschoenherr** [comment]
None of the snippets above?

**Comment by TomS-** [comment]
The second one works, however, I'd like it to be specific to the dynamically created lightbox, not all.
