### ISSUE TITLE
UK Sticky `bottom: true` does not recalculate in conjunction with uk-img & uk-img placeholder not working

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3629]
### UIkit version

3.0.0-rc.20

### Browser
Chrome

### Reproduction Link
http://dev.peterandpaul.co.uk/uikit/
http://dev.peterandpaul.co.uk/uikit/download.zip (To check source code)

### Steps to reproduce
1. Add a sticky element.
2. Add an image that loads using uk-img. 
3. Add `bottom: true`. 

### What is Expected?
The sticky element should stop when it reaches the bottom of the parent. This shouldn't happen as uk-img with the width and height should have a placeholder. However, the placeholder doesn't happen before uk-sticky is calculated? 

### What is actually happening?
It doesn't do this due to not being recalculated when the images are loaded.

**Comment by aarongerig** [comment]
Did you add `width` and `height` attributes to your image?

**Comment by TomS-** [comment]
@aarongerig Yes I did. I'm providing a reproduction link atm

**Comment by TomS-** [comment]
@aarongerig added reproduction link, had to use my server as UIKit seems to be better at putting a placeholder there while an image is loading if it's external. As you can see there is NO place holder while the image is loading. The background is red so you should clearly see it.

**Comment by TomS-** [comment]
This is still an issue in .23 but works in .16 

Is there going to be any update on this bug?

**Comment by janschoenherr** [comment]
This seems to be fixed with 3.0.0-dev.f1300ce

**Comment by TomS-** [comment]
@janschoenherr This is broken again in 3.2.0 - See: https://www.brent2020.co.uk/programmes/a-mile-long-street-party/
