### ISSUE TITLE
Modal / Tab: Wrong event trigger actions

### ISSUE THREAD

**Issue by timrasche** [uikit/uikit#3630]
In modal context and injected "tab" component, some click on tab element triggers an "hide / show" event for the modal.

### UIkit version
3.0.0-rc.20

### Browser
any

**Comment by janschoenherr** [comment]
Please make sure to check the event target. Both, modal and tab fire `hide` / `show` events.

https://developer.mozilla.org/en-US/docs/Web/API/Event/target
