### ISSUE TITLE
Animation does not play when using .show() on Switcher

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3631]
3.0.0-rc.20

### Browser
Chrome

### Steps to reproduce
1. Create a switcher using UIkit.switcher() 
2. Define the animation
3. After a setInterval show next. 

### What is Expected?
The animation should play

### What is actually happening?
It cuts between

The option to autoplay would be great. It was doing this to get around it, but animation does not work.

EDIT: 
You have to have the buttons to use the switcher for the animation to work. I do not need it in this case as I'm using it as a text slideshow. I would use slideshow, but it doesn't work well with just text.

**Comment by zzseba78** [comment]
Why don´t you hide the buttons?

**Comment by TomS-** [comment]
@zzseba78 That's what I ended up doing haha. I might keep this open for autoplay however.
