### ISSUE TITLE
Combination Sticky and Parallax not working

### ISSUE THREAD

**Issue by mark118** [uikit/uikit#3633]
When I use both sticky header and parallax on the same page it stops working.

**Comment by e-b-c** [comment]
I'm having a similar issue—i think.

Using UIKit parallax to apply filters to my images. Using UIKit Sticky to stick the project titles to top.

There is a noticeable jump-up of the containers following the sticky element. I suspect it has something to do with the height of the page being calculated for parallax, and the sticky element being removed from that height.

[See what i mean?](http://www.ebc-d.com/new)

I'm clearly not a developer, so please bear with any misuse of nomenclature and n00b-erey.

**Comment by janschoenherr** [comment]
The upcoming release will contain several fixes for the Sticky component. Please check with the current dev version

https://www.jsdelivr.com/package/npm/uikit?version=3.11.2-dev.fb043abc2
