### ISSUE TITLE
event not being recognised when moving sortable items between sortable groups

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3634]
### UIkit version
3.0.0-rc.20

### Browser

Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### Reproduction Link
https://codepen.io/oshihirii/pen/QZoyQq

### Steps to reproduce

01.  Drag an item within its group, and console logs data.

02.  Drag an item to another group and console logs no data.  

### What is Expected?

I expect data to be logged when moving an item between groups.  

### What is actually happening?

Data is not being logged when moving an item between groups.

**Comment by oshihirii** [comment]
Interestingly, moving between groups is recognised with the `added` event, so maybe i can use that.

**Comment by janschoenherr** [comment]
Please checkout the console output on https://getuikit.com/assets/uikit/tests/sortable.html for intended behavior.
