### ISSUE TITLE
Firefox showing div with wrong width when using uk-position-center or uk-position-x-center

### ISSUE THREAD

**Issue by edemircan** [uikit/uikit#3642]
### UIkit version

3.0.0-rc.20

### Browser
Firefox

### Reproduction Link

[https://codepen.io/ErolD/pen/ePqjVX](https://codepen.io/ErolD/pen/ePqjVX)

### Steps to reproduce
Use uk-width in combination with a uk-position-center, uk-position-top-center or  uk-position-bottom-center

### What is Expected?
The div to have the specified width by using one of the uk-width-x-x

### What is actually happening?
The style property "width: -moz-max-content;" for classes  uk-position-center, uk-position-top-center or  uk-position-bottom-center is preventing the div from being  displayed at the right size

**Comment by normanfrancis** [comment]
I'm experiencing the same issue.

**Comment by saschadube** [comment]
Unfortunately, the `width` is needed in Firefox to fix text wrapping if the content is larger than 50% of the container ([See UIkit test to the right](https://getuikit.com/assets/uikit/tests/position.html)). 

Just nest a child element and add the needed width there.
