### ISSUE TITLE
uikit rc.20 - flip: true;mode: push;overlay: true- scrollbar bug

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [uikit/uikit#3643]
On desktop

```
uk-offcanvas="mode:push; flip: true; overlay: true"
```
![image](https://user-images.githubusercontent.com/16711871/47853613-f0af3c00-dde7-11e8-97f0-6572094a5335.png)

Codepen:
https://codepen.io/ezra_siton/pen/PyMdeX?editors=1100

**Comment by janschoenherr** [comment]
This is intentional. The scrollbar gets pushed too.
