### ISSUE TITLE
Sticky not working properly when the parent or body has at least a CSS transform!

### ISSUE THREAD

**Issue by infinyteam** [uikit/uikit#3646]
### UIkit version
3.0.0-rc.20

### Browser
Chrome

### Reproduction Link
https://codepen.io/uikithemes/pen/XyWWxO

### Steps to reproduce
I want to make an animation to my website "body" tag or a "wrapper" div then I found that Sticky no longer work.
Then I realized that the reason was when I added a CSS transform because when I deleted it the sticky back to work that's mean is a bug or an issue from the framework itself.

### What is Expected?
I want it to work normally even if I added a CSS transform to a "body" tag or a "wrapper" div.

### What is actually happening?
Sticky not working properly when the parent or body has at least a CSS transform!
When I've added a CSS transform for example "transform: translateY(10px) or transform: scaleY(1.5)", the sticky functionality became broken and not working as well!

**Comment by janschoenherr** [comment]
That is most likely not going to work. The transform makes the body act as the sticky's containing block instead of the viewport.

https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed

**Comment by tobaco** [comment]
@infinyteam 
You could remove the class/property, which animates your body or wrapper after your animation to "re-enable" the sticky behavior.
see: https://jonsuh.com/blog/detect-the-end-of-css-animations-and-transitions-with-javascript/
