### ISSUE TITLE
Cannot get Slidenav working

### ISSUE THREAD

**Issue by flyboarder** [uikit/uikit#3647]
### UIkit version
3.0.0-rc.20

### Browser
Chrome 70
### Reproduction Link
https://codepen.io/anon/pen/GwRjJm

### Steps to reproduce
Press nav next/previous

### What is Expected?
Navigate between images

### What is actually happening?
nothing.

**Comment by aarongerig** [comment]
You have to add `uk-slider-item="previous"` and `uk-slider-item="next"` to the nav elements.

**Comment by flyboarder** [comment]
@aarongerig I have updated the pen, still not working.
