### ISSUE TITLE
Center the entire page not working

### ISSUE THREAD

**Issue by Tisooa** [uikit/uikit#365]
Center the entire page is not working when i testing this with this example from the doc.

```
<html class="uk-height-1-1">   

import uikit jquery and uikit js

    <body class="uk-height-1-1">
        <div class="uk-vertical-align">
            <div class="um-vertical-align-middle">
             some text or div
           </div>
        </div>
    </body>
</html>
```

What is the problem?

Thanks for help

**Comment by rubn-g** [comment]
There's a typo in the class name of the last div

<div class="um-vertical-align-middle">

should be

<div class="uk-vertical-align-middle">
