### ISSUE TITLE
Modal Dialogs is not working

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3651]
### UIkit version

3.0.0-rc.21

### Browser
All

### Reproduction Link

https://getuikit.com/docs/modal#modal-dialogs

### Steps to reproduce
1. For example, click on the Dialog button.
2. Close Dialog
3. Try click again on the Dialog button.
4. Try to scroll the page.

### What is Expected?
😎 All works "like a boss".

### What is actually happening?
1. Modal Dialogs does not open after first opening.
2. Page cannot be scrolled.

**Comment by andriar** [comment]
confirm :+1:

**Comment by AlekVolsk** [comment]
I confirm the bug, it is observed not only on the documentation page, but also on working projects

**Comment by evolvens** [comment]
Confirm

**Comment by Kevin-at-Navigram** [comment]
Confirmed. Also happens when second modal triggers the closing event of the first modal.

**Comment by zzseba78** [comment]
Seems to be fixed in rc 22

**Comment by janschoenherr** [comment]
Thanks, should be fixed in rc 22.
