### ISSUE TITLE
CKEditor 4 not  usable inside accordion

### ISSUE THREAD

**Issue by juergenweb** [uikit/uikit#3653]
### UIkit version

3.0.0-rc.22

### Browser
Latest Firefox
### Reproduction Link
<a href ="https://jsfiddle.net/juergenk/49hxzon8/26/">Reproduction Link</a>

### What is actually happening?
CKEditor will be loaded but you are not able to focus the editor and write something.

**Comment by juergenweb** [comment]
Reproduction link is added

**Comment by izachros** [comment]
@janschoenherr I have the same problem with TinyMCE editor in WordPress. Is there any solution?

**Comment by janschoenherr** [comment]
Currently the accordion is wrapping the content in another div during opening/closing. This causes the editor to misbehave. You'd probably have to reinitialize it after the `itemshown` event is triggered on the accordion.

We will probably refactor this behavior with UIkit 4.
