### ISSUE TITLE
Aria Label for dotnav

### ISSUE THREAD

**Issue by fulvioromanin** [uikit/uikit#3657]
hi everybody
i was wondering if there was a way to add to dotnav links a custom aria-label tag per dot for improved accessibility.

Thanks a lot.

**Comment by AndZyk** [comment]
Hello @fulvioromanin,

you could build yourself the dotnav list items with aria-labels:

`<li data-uk-slider-item="0"><a href="#" aria-label="Lorem Ipsum"></a></li>`

But it would be great if UIkit would offer a default aria-label for the shortcut dotnav:

`<ul class="uk-slider-nav uk-dotnav"></ul>`

Regards, Andreas

**Comment by fulvioromanin** [comment]
hi Andreas, 
thanks for your reply. I found out a workaround myself to have 0 errors on Wave.
Here it is for future reference:

var dotnavFix = document.querySelectorAll(".uk-dotnav li a");
dotnavFix.forEach(function(el){
  el.setAttribute("aria-label", "dotnav link");
})

Regards, Fulvio

**Comment by m4507366063** [comment]
var dotnavFix = document.querySelectorAll(".uk-dotnav li a");
dotnavFix.forEach(function(el){
el.setAttribute("aria-label", "dotnav link");
})

do not work... 3.5.4?

**Comment by janschoenherr** [comment]
Thanks, version 3.16.0 comes with built in accessibility.
