### ISSUE TITLE
There is a bug in the offcanvas

### ISSUE THREAD

**Issue by citrucn** [uikit/uikit#3659]
### UIkit version

3.0.0-rc.22

### Browser
Chrome
### Steps to reproduce
Open Offcanvas will invalidate the adaptive layout on some devices, such as chrome analog Iphone6/7/8 or other devices with a height of 667. The same problem exists in the official website. I already know this because of this sentence: 

                    if (window.visualViewport && height(window) !== Math.ceil(window.visualViewport.height)) {
                        this._viewport = append(document.head, '<meta name="viewport" content="user-scalable=0">');
                    }
but I don't know how to Improve it.

**Comment by janschoenherr** [comment]
This has been fixed with rc 23. Thanks.
