### ISSUE TITLE
How to add dynamic css classes to an element

### ISSUE THREAD

**Issue by jmliz** [uikit/uikit#3666]
### UIkit version

3.0.0-rc.23

### Browser
Chromium Version 70.0.3538.77 (Official Build)

### Reproduction Link

https://codepen.io/anon/pen/PxJbLO

### Steps to reproduce

Try applying a class dynamically with AngularJS ng-class.

### What is Expected?

The class should be applied.

### What is actually happening?

The class is not applied.

**Comment by arunrreddy** [comment]
@jmliz Just saw your code snippet on codepen. Seems like you are missing an '=' sign after ng-class in the html.

**Comment by jmliz** [comment]
@arunrreddy sorry for that mistake. It works f you fix that, but playing with it I think my problem is when  load a dynamic view.

I updated the code and the ng-model value is applied, but not the ng-class:

https://codepen.io/anon/pen/PxJbLO

**Comment by janschoenherr** [comment]
You got the quotes messed up. 

    data-ng-class="{invisible: invisible}"

will fix your issue

**Comment by jmliz** [comment]
omg I'm so sorry.
