### ISSUE TITLE
Slider adds a text animation and then loses motion or does not display text when swiping left and right.

### ISSUE THREAD

**Issue by ziselive** [uikit/uikit#3668]
Slider adds a text animation and then loses motion or does not display text when swiping left and right.

### UIkit version

3.0.0-rc.23

### Browser
firefox developer edition 64.
### Steps to reproduce
Swipe left and right to switch more than 5 times
### What is Expected?
.uk-transition-active.uk-active [class*="uk-transition-slide"]... {
    opacity: 1;
    transform: translateX(0) translateY(0);
### What is actually happening?
[class*="uk-transition-slide"] {
    opacity: 0;
}

**Comment by ziselive** [comment]
Multiple tests have found that text loss occurs only with 2 images.
3 or more will not be lost.
Local testing, the site has not yet been online.Unable to provide link.

**Comment by janschoenherr** [comment]
I will close this for now, as it does not seem to be reproducible with codepen? Please comment if issue persists.
