### ISSUE TITLE
Media Toggle not working (but does work with UIkit CDN)

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#3669]
UIkit has the Toggle component, which can toggle media based on the breakpoint / browser width:
https://getuikit.com/docs/toggle#media

I've used this feature without any issues.  However sometime after UIkit 3.0-rc12 (not sure which release exactly), this feature doesn't work correctly anymore **if I compile UIkit 3 with Laravel Mix**.  It does continue to work with UIkit CDN however, which is weird.

Not sure what I am doing wrong or if this is a bug.  I'm using the example straight out of the documentation as well.

### UIkit version
3.0.0-rc.23

### Browser
Chrome v70, Firefox latest, etc.

### Reproduction Link
The big green box at the top has toggle media enabled.  Making the browser mobile width should remove the green background, but it does not work.
https://bit.ly/2QR9UmF

It would work if using UIkit CDN.

**Comment by janschoenherr** [comment]
The breakpoint variables are not correctly compiled:

    --uk-breakpoint-s: $breakpoint-small;
    --uk-breakpoint-m: $breakpoint-medium;
    --uk-breakpoint-l: $breakpoint-large;
    --uk-breakpoint-xl: $breakpoint-xlarge;

should be

    --uk-breakpoint-s: 640px;
    --uk-breakpoint-m: 960px;
    --uk-breakpoint-l: 1200px;
    --uk-breakpoint-xl: 1600px;

**Comment by jlahijani** [comment]
Thanks for pointing this out.

For some reason, Node Sass, at least within a default setup of Laravel Mix, is not transforming the variables to their values in that specific instance.  Perhaps it's because each of those lines are prefixed with "--"?

After some testing, I've noticed that wrapping each of the variables with #{} will fix it, like this:

```
:root {
  --uk-breakpoint-s: #{$breakpoint-small};
  --uk-breakpoint-m: #{$breakpoint-medium};
  --uk-breakpoint-l: #{$breakpoint-large};
  --uk-breakpoint-xl: #{$breakpoint-xlarge};
}
```

Would you guys be open to making this change in the actual repo?
