### ISSUE TITLE
Filter+ Sort at the same time not working

### ISSUE THREAD

**Issue by ftc26** [uikit/uikit#3670]
### UIkit version

3.0.0-rc.23

### Browser
Chrome

### Reproduction Link

https://codepen.io/anon/pen/jQYNva

### Steps to reproduce
Create a uk-filter control and apply filter and sort at the same time

### What is Expected?
Sorting AND filtering a list by data attributes at the same time. 

### What is actually happening?
Strange Filter-Menu behavior. All are active.

**Comment by janschoenherr** [comment]
Give the `all` filter the following options.

    filter: [data-color]; sort: data-date
