### ISSUE TITLE
[BUG]After uikit-3.0.0-rc.19,uk-overlay,uk-offcanvas-slide can't touchemove

### ISSUE THREAD

**Issue by romy2012** [uikit/uikit#3672]
![qq 20181124144041](https://user-images.githubusercontent.com/10843381/48965395-51045880-eff7-11e8-99d8-f2ae0c197e3d.png)

on mobile,uk-overlay open, uk-offcanvas-slide can't touchemove.

![qq 20181124144609](https://user-images.githubusercontent.com/10843381/48965424-b9533a00-eff7-11e8-9531-3e784ce7bf73.png)

no consideration for the possible influence of the scroll?

handler: function(e, scroll, target) {

**Comment by romy2012** [comment]
row 6896  return this.panel;?

            {
                name: 'touchmove',

                el: function() {
                    //return this.panel;
                },

**Comment by romy2012** [comment]
![qq 20181124150836](https://user-images.githubusercontent.com/10843381/48965577-e3f2c200-effa-11e8-9523-ecfc3f6e5cc4.png)


two functions

**Comment by janschoenherr** [comment]
I will close this for now, if the issue persists please comment.
