### ISSUE TITLE
Issues with isPlainObject(obj)

### ISSUE THREAD

**Issue by hrstoyanov** [uikit/uikit#3676]
### UIkit version
3.0.0-rc.24

### Browser
Chrome latest 

### What is actually happening?
I have issue with the this code:
```
  function isPlainObject(obj) {
        return isObject(obj) && Object.getPrototypeOf(obj) === objPrototype;
    }
```

As seen in the attached screenshot, the below expression evaluates to false for pretty normal plain object I pass in to ```Uikit.notification({...}); ``` :

 ```
... Object.getPrototypeOf(obj) === objPrototype
```
<img width="1218" alt="screen shot 2018-11-29 at 9 40 43 am" src="https://user-images.githubusercontent.com/5327044/49206688-7f00e880-f3bb-11e8-9d9e-6ca6473d01b5.png">

**Comment by hrstoyanov** [comment]
Anyone has any suggestion? I cannot use the UIKit JS API without fixing this. See attached yet another screenshot example where ```Object.getPrototypeOf(obj) === objPrototype``` gives me ```false``` and breaks  the ```isPlainObject(obj)``` for a perfectly normal JS object I pass into the ```UIkit.notification({...})``` API:

<img width="1434" alt="screen shot 2018-11-30 at 9 36 51 am" src="https://user-images.githubusercontent.com/5327044/49275459-06199380-f484-11e8-84b8-a5fa0f976dee.png">

**Comment by janschoenherr** [comment]
Are you trying to trigger a notification within an iframe?

**Comment by hrstoyanov** [comment]
Yes, I think so ..

**Comment by hrstoyanov** [comment]
@janschoenherr 
Any suggestions? I am trying to release a [GWT wrapper for UIKit](https://github.com/peruncs/gwt)

**Comment by hrstoyanov** [comment]
@janschoenherr 
Why can't do just this:

```
function isPlainObject(obj) {
        return isObject(obj) ;
}
```

This would be less brittle and work across frames?

https://stackoverflow.com/questions/22391858/when-are-javascripts-native-prototype-shared-among-same-origin-frames

https://stackoverflow.com/questions/29152342/equality-operator-and-properties-in-prototype-chain-from-different-frames

**Comment by hrstoyanov** [comment]
can we have a resolution on this issue?
