### ISSUE TITLE
Lightbox video preview image is blurry when shown second time

### ISSUE THREAD

**Issue by mthomsonnz** [uikit/uikit#3678]
UIkit version 3.0.0-rc.24

Browser: firefox 63, Safari 12

Reproduction Link:
https://getuikit.com/docs/lightbox#content-sources

Open the youtube lightbox link, the bunny is clear, change the lightbox slide, slide back to the youtube vid, the bunny images is blurry

**Comment by janschoenherr** [comment]
This seems to be resolved.
