### ISSUE TITLE
Feature request: scroll to element function

### ISSUE THREAD

**Issue by edguar** [uikit/uikit#3679]
### UIkit version
3.0.0-rc.24

### Browser
Google Chrome 70.0.3538.110

### Reproduction Link
https://codepen.io/edguar/pen/aQQWbj

### Steps to reproduce
Scroll to element from different events

### What is Expected?
Use scroll function without Scroll component

**Comment by janschoenherr** [comment]
Version 3.2.4 exposes `UIkit.util.scrollIntoView`
