### ISSUE TITLE
Links in a uk-tab element do not navigate

### ISSUE THREAD

**Issue by paulisloud** [uikit/uikit#3680]
### Browser

Chrome (current)

### Reproduction Link
https://codepen.io/anon/pen/KrbZdj

### Steps to reproduce

Use the codepen above

### What is Expected?

Clicking a link navigates to the clicked link

### What is actually happening?

Only the 'active' status of the link clicked changes, but navigation is prevented.

**Comment by janschoenherr** [comment]
Basically, the tab component is a switcher component. 

https://getuikit.com/docs/tab

You can use its styling though. Just add the classes `uk-tab uk-tab-left` and remove the `uk-tab` attribute.
