### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by hrstoyanov** [uikit/uikit#3682]
### UIkit version
3.0.0-rc.25

The [documentation for the Modal component](https://getuikit.com/docs/modal#modal-full) seems to be wrong, or can benefit from some review:

1. The modal options should be (as seen in UIkit.js sources):
```
            selPanel: String,
            selClose: String,
            escClose: Boolean,
            bgClose: Boolean,
            stack: Boolean
```
and not: ```sel_panel, sel_close, esc_close ....```

2. For the ```sel-close```(which is wrong) , do we need to put "." for the possible class value or not? See the other - they dont have a "." in the docs

3. There is confusion between "Component options" and "JavaScript options" documentation sections - why are they different? Again, in the code:

```
       props: {
            selPanel: String,
            selClose: String,
            escClose: Boolean,
            bgClose: Boolean,
            stack: Boolean
        },

        data: {
            cls: 'uk-open',
            escClose: true,
            bgClose: true,
            overlay: true,
            stack: false
        },
```
4. Is there ```toggle``` method on the Modal component, in addtion to ```show/hide```? The code sys yes, the docs does not mention it?

**Comment by zzseba78** [comment]
It´s not wrong, in deed it´s specified in the docs.
> The options names must be in their camel cased representation, e.g. show-on-up becomes showOnUp.
https://getuikit.com/docs/javascript#programmatic-use

**Comment by janschoenherr** [comment]
Thanks, the options are now shown in the `Component options` section.
