### ISSUE TITLE
rc.25 has sass bug on components default background

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3683]
3.0.0-rc.25 sass version  button-default and card-default background changed to $global-muted-background !default; 

https://github.com/uikit/uikit/blob/cd68c4d47678afbe99d7bd7f15ffe3093808cfb7/src/scss/variables-theme.scss#L567

### UIkit version

3.0.0-rc.25

**Comment by Gargamil** [comment]
Workaround might be:

```
$card-default-background: $global-background;
```

place it in a file after `mixins-theme.scss` / `variables-theme.scss`

**Comment by dariusbakunas** [comment]
For inpu background:
`$form-background: $global-background;`
but I see more places where muted-background is used instead of default

**Comment by dasdeck** [comment]
This should be fixed in the next dev-version/release.

Cheers!

**Comment by flihub** [comment]
rc.26 dropdown bg still has bug

https://github.com/uikit/uikit/blob/426c1295c9552f1078c7554e0584627f6c402f6f/src/scss/variables-theme.scss#L171

**Comment by dasdeck** [comment]
Can you elaborate on how this is a bug? The '!default' flags behind all our variables are intentional, it is due to the nature of how our conversion script works. The resulting CSS looks identical on a manual comparison.

Cheers!

JM

**Comment by flihub** [comment]
less : https://github.com/uikit/uikit/blob/426c1295c9552f1078c7554e0584627f6c402f6f/src/less/theme/dropdown.less#L11
sass : https://github.com/uikit/uikit/blob/426c1295c9552f1078c7554e0584627f6c402f6f/src/scss/theme/dropdown.scss#L11

this is same but in variables-theme background changed. 

compiled less : 
https://github.com/uikit/uikit/blob/426c1295c9552f1078c7554e0584627f6c402f6f/dist/css/uikit.css#L4039

compiled scss
/* ========================================================================
   Component: Dropdown
 ========================================================================== */
/*
 * 1. Hide by default
 * 2. Set position
 * 3. Set a default width
 * 4. Style
 */
.uk-dropdown {
  /* 1 */
  display: none;
  /* 2 */
  position: absolute;
  z-index: 1020;
  /* 3 */
  box-sizing: border-box;
  min-width: 200px;
  /* 4 */
  padding: 15px;
  background: #ebebeb;
  color: #666;
  box-shadow: 0 5px 12px rgba(0, 0, 0, 0.15);
}

**Comment by dasdeck** [comment]
Can it be that you are comparing the wrong builds? the "theme" build in scss is the uikit.css, 
the other one is the "uikit-core.css" build.

I just did the same :blush:

Cheers!

**Comment by flihub** [comment]
im not compare wrong builds:)

my app.css 

// 1. Your custom variables and variable overwrites.
// @import "theme/variables.scss";

// 2. Import default variables and available mixins.
@import "~uikit/src/scss/variables-theme.scss";
@import "~uikit/src/scss/mixins-theme.scss";

// 3. Your custom mixin overwrites.
// @import "theme/mixins.scss";

// 4. Import UIkit.
@import "~uikit/src/scss/uikit-theme.scss";

and screenshot 

![capture](https://user-images.githubusercontent.com/16720735/50763699-987e3580-1281-11e9-8a43-a2b9ea2cdba8.PNG)

https://github.com/uikit/uikit/blob/426c1295c9552f1078c7554e0584627f6c402f6f/src/scss/variables-theme.scss#L171

this must be $global-background

**Comment by dasdeck** [comment]
Ah! Yes sorry, I was working on an already fixed version. Your version still has a "random" bug.
This should be fixed (again) in the upcoming release!

Cheers!

JM
