### ISSUE TITLE
inview isn't triggered for objects in viewport on load unless a delay is added

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3686]
### UIkit version

3.0.0-rc.25

### Browser
Chrome

### Reproduction Link
I'm going to have to create this on my server as it isn't an issue on codepen (probably to how it's loading). Should be fairly easy to reproduce though. 

### Steps to reproduce
1. uk-scrollspy for object already in viewport on load
2. use javascript to listen on inview. 

### What is Expected?
inview should fire.

### What is actually happening?
inview isn't being fired.

**Comment by neokio** [comment]
I'd love to see your workaround, could you post your JS?

**Comment by TomS-** [comment]
@neokio just put something like delay: 50; and that  will fix it. I opted for 200 but I should imagine any number greater than 0 would work

**Comment by janschoenherr** [comment]
I can't reproduce this issue. However, if the element behaves normally, e.g. fades in, it might be that your event listener hasn't been attached at the time the event is triggered?

**Comment by TomS-** [comment]
@janschoenherr That could be the issue. What would be the solution in that aspect? I'm using `UIkit.util.on` in which I need UIKit for, however, if inview is triggered right at that time is there a way that I can load UIKit after my script but not fire until UIKit has loaded?

**Comment by aarongerig** [comment]
I'm loading UIkit's JavaScript in the head, but with the `defer` attribute. This ensures to not block any HTML rendering and therefore increases the site's performance. This approach makes content jump, once the JavaScript gets initialized and because of that I add the basic classes manually. So for example for the grid I code my HTML like so:

```
<div class="uk-grid" uk-grid>...</div>
```

Or a dropdown:

```
<div class="uk-dropdown" uk-dropdown>...</div>
```

If you don't want to code like that, you could also add a site loading animation to cover the content "jumping" and remove it once the page has fully loaded.

**Comment by Jdeboysere** [comment]
I have the same problem on UIkit 3.1.7.

```
    UIkit.util.on('#loadmore', 'inview', (e) => {
      blabla()
    })
```

blabla() is executed when #loadmore appears in the viewport. But blabla() is not executed if #loadmore is already in the viewport when the page is loaded...

Any fix?

**Comment by janschoenherr** [comment]
@Jdeboysere Are you loading UIkit deferred?

**Comment by Jdeboysere** [comment]
Not really!
I use UIkit with ES6 and webpack.mix, so I have only `import UIkit from 'uikit'` in my js file.

**Comment by janschoenherr** [comment]
If you paste the above code right after your import, it does not work?
