### ISSUE TITLE
All Tab items active using Vue js.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3693]
### UIkit version

3.0.0-rc.25

### Browser
All
### Reproduction Link
https://codepen.io/zzseba78/pen/dwoGQm

### What is Expected?
Just first tab item active
### What is actually happening?
All tab items are active

**Comment by janschoenherr** [comment]
This issue is similar to the "duplicate icons". UIkit applies the `uk-active` class before Vue takes the `app` out of the DOM. For Vue, the markup looks like this: 

    <li v-for="tab in tabs" class="uk-active">

You can easily solve this by using Vue's bind directive: https://vuejs.org/v2/api/#v-bind

    <ul class="uk-child-width-expand" :uk-tab="''">

**Comment by zzseba78** [comment]
Thank you!
