### ISSUE TITLE
Modal hash

### ISSUE THREAD

**Issue by tofanelli** [uikit/uikit#3698]
### UIkit version

3.0.0-rc.25

### Browser
Any
### What is actually happening?
- when you enter in [UIKIT Modal Docs](https://getuikit.com/docs/modal), any modal you open for the first time, its hash is ""fixed"" on address bar... the only way to remove this hash is deleting... is there a way to remove the modal hash after is closed??

- on modal Open Test, any modal creates the hash url... is that right?? if yes, how to add the hash on open and how to remove the hash after closed?

Cheers =)

**Comment by janschoenherr** [comment]
Thanks, this has been fixed on getuikit.com.

**Comment by tofanelli** [comment]
Thanks @janschoenherr .... its great now =)

but, quick question, and what if I really want the hash on the modals? in case i want to send that particular link to someone? is it possible to enable/disable this?
