### ISSUE TITLE
Safary uk-image lazy double load 

### ISSUE THREAD

**Issue by mira-kovar** [uikit/uikit#3700]
Safari loads images doule. I think safari load `src` and `srcset` at the same time, which double load on server and data trasnfered between server and clinet. This happens even on mobile (iPhone).

### UIkit version
3.0.0-rc.25

### Browser
Safari 12, iOS Safari and Safari TP

### Reproduction Link
https://getuikit.com/assets/uikit/tests/image.html

### Steps to reproduce
Open Safari and load reproductin link and open devtools and look into network panel. Same for iOS Safari connect iPhone and open devtools of iPhone. And scroll til the end of page.

### What is Expected?
Total network traffic: 52 request with ~ 3.6 Mb (Chrome, Firefox)

### What is actually happening?
Total network traffic: 223 requests with ~ 9.8 Mb

**Comment by zzseba78** [comment]
Works fine for me: Safari 12.0.2 OS High Sierra 10.13.6

![captura de pantalla 2018-12-20 a la s 14 55 43](https://user-images.githubusercontent.com/5558563/50301986-7bff9200-0467-11e9-84c2-6deac3008c5f.png)

**Comment by janschoenherr** [comment]
Please see #3612

You'll have to clear the sessionStorage between your tests.
