### ISSUE TITLE
Why UIkit inconsistency in Status styles modifiers?

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3702]
### UIkit version

3.0.0-rc.25

### What is actually happening?
The status styling in UIKit 3 it´s not consistent, this doesn´t happen **in any other framework** ( top class like UIkit ) that have status styles. I mean Bootstrap, Foundation, Semantic UI, Bulma, Spectre. 

Why is this way? Because of final file size? Please somebody can explain this? This consistency it´s a must when working on GUI.

Don´t get me wrong, **I LOVE UIkit**, using it for years, but this is a topic that I can´t understand why it is done in this way. I´m not saying that every component should have all status, this is nonsense, but component like buttons, badges, forms... this is needed!

I leave a graph that shows what i´m talking about.

_I know this can de added by the users in no time, but i think this should be delivered "out of the box" by the framework, for those that use less or sass, css or cdn files._

Thank you.

![status](https://user-images.githubusercontent.com/5558563/50317040-48892b80-0498-11e9-9727-d3aa40865869.png)

**Comment by AlekVolsk** [comment]
Hi @zzseba78 ;) Perhaps "secondary" is identified with "success", but this is not accurate )))

Do not forget about the style of "muted" which is more like a dormant state, but also has weight, I would have added it as a separate column.

_( Sorry for the English curve )_

**Comment by jsieler** [comment]
I just leave it here: https://github.com/uikit/uikit/issues/2680
