### ISSUE TITLE
No bullet for list element

### ISSUE THREAD

**Issue by PavelNSH** [uikit/uikit#3704]
### UIkit version

3.0.0-rc.25

### Browser
Mozilla Firefox 64.0 on fedora 29 (in chrome ok)
### Steps to reproduce
`<body data-interface-name="hint">
        <main class="hint">
            <div uk-grid>
                <div class="uk-width-2-3@m uk-grid-item-match">
                    <ul class="uk-column-1-2@s uk-list uk-list-bullet">
                        <li>
                            bla-bla-bla
                        </li>
                        <li>
                            bla-bla-bla
                        </li>
                        <li>
                            bla-bla-bla
                        </li>
                        <li>
                            bla-bla-bla
                        </li>
                    </ul>
                </div>
                <div class="uk-width-1-3@m uk-grid-item-match">
                    &nbsp;
                </div>
            </div>
        </main>
    </body>
`

css:

main {
    li {
        @extend .uk-margin-remove-top;
    }
}
@import "uikit/src/scss/variables-theme.scss";
@import "uikit/src/scss/uikit-theme.scss";

### What is Expected?
Bullets before list elements

### What is actually happening?
No bullet before top element in right column
![report-001](https://user-images.githubusercontent.com/24734964/50392632-d94e5880-0771-11e9-8b53-832d3e85dc82.png)

**Comment by bdthemes** [comment]
It's working fine for me: http://prntscr.com/m1ydyn

Tested in Chrome v71 + Firefox v64 on win 10 pc

**Comment by PavelNSH** [comment]
> It's working fine for me: http://prntscr.com/m1ydyn
> 
> Tested in Chrome v71 + Firefox v64 on win 10 pc

https://codepen.io/pavelnsh/pen/zyWOqm?&editable=true
Try please by firefox. In linux, if you can

**Comment by PavelNSH** [comment]
> It's working fine for me: http://prntscr.com/m1ydyn
> 
> Tested in Chrome v71 + Firefox v64 on win 10 pc

![bullet](https://user-images.githubusercontent.com/24734964/50689991-9d5aa380-104d-11e9-9fbb-6179377f7e10.jpg)
windows 8.1 firefox 64
