### ISSUE TITLE
uk-sticky issue with latest chrome 

### ISSUE THREAD

**Issue by solisoft** [uikit/uikit#3707]
### UIkit version

3.0.0-rc.25

### Browser
latest chrome
### Reproduction Link
https://jsfiddle.net/solisoft/xh4p9uL3/7/
https://vimeo.com/308393842

### Steps to reproduce
Scroll down and then go to the top ... 
### What is Expected?
Should change background within a transition
### What is actually happening?
Text looks weird

**Comment by solisoft** [comment]
To fix it I had to add 
`-webkit-transform: translateZ(0);`

**Comment by solisoft** [comment]
https://www.binarymoon.co.uk/2014/02/fixing-css-transitions-in-google-chrome/

**Comment by solisoft** [comment]
hmm Finaly it didn't help that much

**Comment by janschoenherr** [comment]
Seems to be working now.
