### ISSUE TITLE
slideshow height attribute changes when navigating with slider

### ISSUE THREAD

**Issue by caravanpetrol** [uikit/uikit#3708]
### UIkit version

3.0.0-rc.26

### Browser
Firefox 64 / Chromium 71 (ubuntu)

### Reproduction Link
[https://codepen.io/caravanpetrol/pen/REMayR](https://codepen.io/caravanpetrol/pen/REMayR)

### Steps to reproduce
Drag or click previous/next navigation slide of bottom thumbs

### What is Expected?
Slider just move and the window keeps a full height

### What is actually happening?
Navigator window height moves. 
The viewport height attribute of the slideshow seems to change

**Comment by janschoenherr** [comment]
With the next version, you'll be able to set `ratio` to false, which will prevent the Slideshow and Height-Viewport component from competing with each other.

**Comment by janschoenherr** [comment]
Is this resolved with 3.0.3?

**Comment by caravanpetrol** [comment]
Yeah it's ok now, thanks fot that ! 
I updated the codepen if some folks need it
