### ISSUE TITLE
Unable to trigger modal with JS

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#3721]
Hi.

I while ago, when UIkit was at rc16 I used it to add a simple modal to one of the sites I am working with,  with a bit of JS that checks for existence of a certain cookie and show the modal if it can't find it.

Now that the UIkit went into 3.0.0 I thought I update the files. But when I did that the bit of code that triggered the modal popup is not working

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/css/uikit.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.2/js/uikit.min.js"></script>

<div id="hpc-check" class="uk-modal-container uk-flex-top" uk-modal="esc-close:false; bg-close:false" style="background: rgba(0,0,0,.8);">
    <div class="uk-modal-dialog uk-modal-body" style="padding-top:150px;">
        <!-- lengthy body content goes here -->
    </div>
</div>
<script>
    if (document.cookie.indexOf("hpc_check")  >= 0 ) {
        console.log("got cookie");
    }
    else {
        console.log("no cookie");
        UIkit.modal('#hpc-check').show();
   }
</script>
```

The validation is ok, because i get "no cookie" message in console, but the `UIkit.modal('#hpc-check').show();` does not seem to work.
When I revert the sources back to 3.0.0-rc.16 it all works fine. According to the docs the method hasn't changed.

Any ideas?

**Comment by janschoenherr** [comment]
That seems to be working fine for me. Do you have a reproduction link?

**Comment by psuplat** [comment]
Sadly not really, as the site is live and I need to keep that thing working.

The only other thing that comes to my mind is that the site is based on a CMS system that is using Bootstrap 3 as the main theme. However I do not get any errors or even warnings in the console, I don't think scoping of uikit would do any good, and as mention everything works fine on rc16.

Maybe I should start slowly incrementing the version of the uikit starting from rc17 until 3.0.0 and see on which it breaks :unamused:

**Comment by janschoenherr** [comment]
Does it work if you delay the `UIkit.modal('#hpc-check').show();` with a `setTimeout`?

**Comment by timrasche** [comment]
It seems that the view was not fully initialized or you're right some bootstrap thing breaks it. Have you tried to use some ready function for the js snippet?
