### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by tonypartridge** [uikit/uikit#3724]
see:

.uk-leader-fill-content::before {
  content: '.';
}
:root {
  --uk-leader-fill-content: .;
}

:root has . as it's value. Should this not be: '.' ?

**Comment by janschoenherr** [comment]
I believe that would yield `'.'`as value.

You'd get: ```"." "." "." "." "." "." "." "." "." "."```

**Comment by tonypartridge** [comment]
Did you try? Given the one above is encoded and usually you need to enclose
text within CSS content?
