### ISSUE TITLE
Sticky fixed main nav and offcanvas push on Firefox

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#3726]
### UIkit version

3.0.2

### Browser
Firefox Mobile 64.0.2

### Reproduction Link
https://new.papazetis.com

### Steps to reproduce
Try to view the website on firefox mobile browser or on Firefox desktop but in mobile view.

### What is Expected?
The fixed nav must be pushed to the left with the rest of the content.
Reveal mode is working fine.

### What is actually happening?
The fixed stays fixed and the contents below nav is pushed to the left.

**Comment by janschoenherr** [comment]
I will close this for now, as the link does no longer seem to work.
