### ISSUE TITLE
Tooltip bug (with wordpress)

### ISSUE THREAD

**Issue by stylethemes** [uikit/uikit#3728]
### UIkit version
3.0.2

### Browser
chrome

### Reproduction Link
https://codepen.io/infuzzione/pen/aPrOgX
pen credit to CodeAlb from the discord chat

### Steps to reproduce
If the html tag have a margin top it will break the tooltip. or just use the tooltip in WordPress

**Comment by papazetis** [comment]
You are right. When the admin bar is on. When you are logged out from backend, it works fine.
Wordpress adds margin-top: 32px on html tag when the admin bar is on.

**Comment by CodeAlb** [comment]
I tested it with only `padding-top: 32px` and works fine. Only margins breaks it.

**Comment by stylethemes** [comment]
Yeah cuz the WordPress admin bar uses margin and not padding so is there any fix in an update yet or not

**Comment by CodeAlb** [comment]
I found a solution with CSS.
Demo: https://codepen.io/infuzzione/pen/KJqYgp

```
// Generated by WordPress when admin bar is active.
html { margin-top: 32px !important; }
* html body { margin-top: 32px !important; }
@media screen and ( max-width: 782px ) {
  html { margin-top: 46px !important; }
  * html body { margin-top: 46px !important; }
}

// Fix tooltip only when admin bar is active.
.admin-bar .uk-tooltip { top: 32px }
@media screen and ( max-width: 782px ) {
   .admin-bar .uk-tooltip { top: 46px; }
}
```

**Comment by janschoenherr** [comment]
This is probably no longer the case as drop positioning has been largely refactored.
