### ISSUE TITLE
Orange color for buttons

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#373]
Blue, green, orange and red colors are available for badges and alerts.
Buttons have no orange modifier.

Like `.uk-badge-warning` color modifier for badges, a `.uk-button-warning` class should be added to buttons to make them orange.

**Comment by robertotremonti** [comment]
Any news on it?
I guess it's a small and useful addition, ten lines of code in CSS.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We decided not to add a 'warning' colored button into the default UIkit3. This needs to be added via your custom style or additional CSS.

Thanks for your understanding,
Your UIkit Team
