### ISSUE TITLE
Scoped UIKit3 - Lightbox not working

### ISSUE THREAD

**Issue by helmutkaufmann** [uikit/uikit#3732]
### UIkit version

3.0.2

### Browser
Chrome
Safari

### What is Expected?
UIKit3 documentation reads regarding scoped versions of UIKit3: Now you need to tell uk-modal, uk-tooltip and uk-lightbox where to append themselves into the DOM when they do not have the container option set, e.g. the default container for said components. To do so, set the following parameter:
//simply pass the selector
UIkit.container = '.uk-scope';

Created a scoped version of UIKit3, call it uik3 and as I wanted to use it along with version 2 on the same web page, I produced a prefixed version uik3.

Included the the following code on the page:
uik3UIkit.container = '.uik3-scope';

I can now use the scoped version for Sliders, which works perfectly. But Lighboxes don't show.

### What is actually happening?
Lighbox is not shown in scoped version.

**Comment by helmutkaufmann** [comment]
Closed by accident

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
