### ISSUE TITLE
Search overlay: Input not focussed

### ISSUE THREAD

**Issue by ahoiroman** [uikit/uikit#3736]
### UIkit version
3.0.2

### Browser
Safari 12.0.2

### Reproduction Link
https://getuikit.com/docs/search#overlay

### Steps to reproduce
Click "Search" icon 

### What is Expected?
Search input appears and the input is focussed.

### What is actually happening?
Search input appears and the input is **not** focussed.

**Comment by joeyslack** [comment]
I'm on UIKit 3.0.2 and Safari 12.1 (latest), and it works properly.

On UIKit < 3.01 I was having this issue (on Chrome), and I had to call focus() on the callback manually, but as of 3.0.2, I cannot replicate this issue on Safari or Chrome. It's working as intended as I test it here.

**Comment by SPQRInc** [comment]
Hmmm... 

On my mac it does not work on macOS `10.14.2 (18C54)` with Safari `Version 12.0.2 (14606.3.4)`. It's not working on the examples on getuikit.com, too.

According to apple, the latest release of Safari is `12.0.2`. Are you using a beta?

On mobile (iOS), it does not auto focus on Safari and Firefox.

**Comment by sahilNR** [comment]
They have this in place because it's annoying to users when the keyboard keeps coming up on touchscreen devices. They only allow the `element.focus()` top work if the user clicks on the element. 
I was able to solve this problem by using `window.requestAnimationFrame`
```js
window.requestAnimationFrame(function(){
    element.focus()
})
```

**Comment by janschoenherr** [comment]
This seems to be fixed.
