### ISSUE TITLE
accordion beforeshow returning false doesn't seem to work

### ISSUE THREAD

**Issue by abhayjatindoshi** [uikit/uikit#3737]
### UIkit version

3.0.2

### Browser
Chrome 71.0.3578.98 (Official Build) (64-bit)

### Reproduction Link
https://jsfiddle.net/p2uo9bw7/20/

### What is actually happening?
I have created an accordion and implemented beforeshow and returning false. as stated in the doc it is not supposed to toggle the item but it is actually toggling the item on click. I do get a callback to the custom function where I have returned false as stated in your doc here. https://getuikit.com/docs/accordion#events

**Comment by joeyslack** [comment]
Looks like you might have interpreted the docs incorrectly.

I got it to work: https://jsfiddle.net/vuxfywmd/

You'll notice, you have to set collapsible false inside of the uk-accordian property on the component, ie: <ul uk-accordion="collapsible: false">...</ul>

**Comment by joeyslack** [comment]
There's definitely nothing stopping you from doing that... but it will be up to you to manage the states. The example I provided shows how the collapsible setting works, by keeping 1 open at all times (as per the docs). You can set uk-open on an item to have it open, so it should be very easy for you to implement your own logic, then manipulate accordingly.

**Comment by abhayjatindoshi** [comment]
1. Even if I handle it all on my own, I'll still want to atleast block the default toggling effect. Maybe this below example will make it more clearer 
https://jsfiddle.net/nj3o9sqg/20/

2. What is the actual purpose for return false for the event listener - `beforeshow`then ?

@joeyslack

**Comment by abhayjatindoshi** [comment]
Got a fix. I gave `uk-accordion='toggle:false'` which worked for my use case. Still I don't get the usage of return false. 
What difference does it make if i return false on `beforeshow` event of an accordion

**Comment by vaclavhlobil** [comment]
Same with toggle in UIkit v3.0.3

**Comment by janschoenherr** [comment]
Sorry, the docs were not up to date. You'll have to call `preventDefault` on the event.

    event.preventDefault();

https://getuikit.com/docs/accordion#events
