### ISSUE TITLE
UIKIT 3.0.2 close lightbox bug

### ISSUE THREAD

**Issue by evolvens** [uikit/uikit#3739]
### UIkit version
3.0.2

### Browser
Firefox

### Reproduction Link
https://getuikit.com/docs/lightbox

### Steps to reproduce
https://www.youtube.com/watch?v=jW8LWLdc1Ac

**Comment by AlekVolsk** [comment]
This is not a bug, this behavior has always been normal: a click outside the content displayed in the lightbox closes the lightbox

**Comment by evolvens** [comment]
Maybe. But not very well for user experience!

**Comment by TomS-** [comment]
@evolvens I would argue it's much better for user experience as it's widely adapted.
