### ISSUE TITLE
[IE11] search focus issue

### ISSUE THREAD

**Issue by domschmidt** [uikit/uikit#3740]
### UIkit version
3.0.2

### Browser
IE11.253.17763.0

### Reproduction Link
https://codepen.io/domschmidt-the-decoder/pen/mvEJmg

### Steps to reproduce
enable "hover" mode for search bar dropdown:
uk-drop="mode: hover" 
- open the dropdown menu
- set the focus to the input field
- close the menu by moving the mouse pointer outside

### What is Expected?
- cursor no longer shown

### What is actually happening?
- curser shown next to the search icon

![search dropdown](https://user-images.githubusercontent.com/5794467/51827117-ec13fa00-22e8-11e9-8ec6-3c256b57d95a.gif)

**Comment by janschoenherr** [comment]
This should be fixed in 3.0.3
