### ISSUE TITLE
Off-Canvas JSON format not working

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#3742]
Hi, Offcanvas json format (`uk-offcanvas="{'mode':'push', 'overlay':true, flip: true}"`) option not working, please check my example codepen demo. But regular uikit style option (`uk-offcanvas="mode: push; overlay: true; flip: true"`) working fine.

This json format was working previously.

### UIkit version

3.0.2

### Reproduction Link

https://codepen.io/bdthemes/pen/BMLooj

### Steps to reproduce
Just use option as json format, such as: `uk-offcanvas="{'mode':'push', 'overlay':true, flip: true}"`

### What is actually happening?

Option not working as i expected

**Comment by janschoenherr** [comment]
It's not valid JSON, use e.g.: `uk-offcanvas='{"mode":"push", "overlay":true, "flip": true}'`
