### ISSUE TITLE
Forms fields and buttons don´t same height if zoom applied in Firefox ( latest )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3744]
### UIkit version

3.0.3 - Cdn 

### Browser
Firefox Quantum 65
### Reproduction Link
https://codepen.io/zzseba78/pen/BMpBqM
### Steps to reproduce
Open link in Firefox, apply zoom ( other than 100% )

### What is Expected?
Form input select should have same height than buttons
### What is actually happening?
They don´t

Works fine in Chrome, Safari.
![captura de pantalla 2019-01-30 a la s 19 04 23](https://user-images.githubusercontent.com/5558563/52015941-f4735d00-24c1-11e9-997d-110edd0c199a.png)
![captura de pantalla 2019-01-30 a la s 19 04 31](https://user-images.githubusercontent.com/5558563/52015944-f63d2080-24c1-11e9-9e21-62f37f4d5c5c.png)

**Comment by saschadube** [comment]
Works for me in Firefox 65 on macOS
