### ISSUE TITLE
Search Toggle defective

### ISSUE THREAD

**Issue by wortkrieg** [uikit/uikit#3748]
Hi Guys,
In UIkit version: 3.0.3 the Search Toggle "uk-search-toggle" doesn't work. It's also broken on the documentation and test page. 
Tested in Chrome & Firefox.

**Comment by aarongerig** [comment]
@wortkrieg It works as expected for me. Adds the hover state to the search icon, just as described in the documentation. What exactly doesn't work for you?

**Comment by wortkrieg** [comment]
Ack. Works perfectly fine here now, too. I have no clue, why It didn't work out for me half an hour ago. Sorry for that.
