### ISSUE TITLE
[Request] Prefix using "ui-" instead of "uk-"

### ISSUE THREAD

**Issue by drmzio** [uikit/uikit#3750]
## Introduction
Ok so first off, AMAZING work on this frontend CSS framework! 👏I've been using it for about a year now and it totally beats the competition in terms of simplicity and ease of customization.

## Problem
However, my only issue is the ugly **"uk-"** prefix (no offense) and it drives me AND my clients crazy. They always ask why it has that "UK" name, which obviously reminds people of the United Kingdom.

## Solution
My current solution is creating a fork and doing a mass find + replace on "uk-". Check it out the fork repo here: https://github.com/akosweb/uikit . But that's not what this issue is for, I'm hoping that UIkit maintainers are willing to use the new **"ui-"** prefix everywhere. It looks much cleaner and straightforward. "UI" meaning "User Interface" which makes perfect sense; not to mention that it's also in the "UIkit" name itself. The JavaScript side could keep the **"UIkit"** class name, as it looks fine the way it is. Below I've provided some examples of how it would look. Thanks!

### Examples
```html
<div class="ui-grid" ui-grid>...</div>
```
```html
<span class="ui-icon" ui-icon="icon: home; ratio: 2"></span>
```
```html
<img data-src="" width="" height="" alt="" ui-img>
```

**Comment by aarongerig** [comment]
You can customize the prefix to whatever you want: https://getuikit.com/docs/avoiding-conflicts#custom-prefix

No need for mass search and replace.

**Comment by saschadube** [comment]
To add a little history: When we started UIkit, we also thought about the `ui-` prefix but it was already taken by [jQuery UI](https://jqueryui.com/). See the [buttons component](https://github.com/jquery/jquery-ui/blob/master/themes/base/button.css). And most likely, they are not the only ones using it. Overall, `uk-` does the better job being conflict free, which is the main reason for the prefix...

But as @aarongerig said, you can change it to what ever you want 😉

**Comment by jsieler** [comment]
Changing prefix is okay, but please add possibility to remove it as well.
