### ISSUE TITLE
Slideshow inside a slider's slide incompatibility 

### ISSUE THREAD

**Issue by sandros87** [uikit/uikit#3752]
### UIkit version
3.0.3

### Browser
Chrome 72 and Firefox 64

### Reproduction Link
https://codepen.io/anon/pen/ErbeXV

### Steps to reproduce
at page loading just swipe with the mouse or slidenavs

### What is Expected?
should just swipe through slides

### What is actually happening?
At first swipe/change of a slide (inside the slider) UIKIT applies the class uk-active to the li active in the slider and to the lis inside the slideshows non stop (you can see that in Chrome Dev Tools). The CPU usage goes to the roof and in Chrome you can see you can't actually change slides.

There must be some incompatibility with something that happens with the slider that afflicts also the slideshows.

It seems it has nothing to do with draggable false/none or pointer-events reported [here](https://github.com/uikit/uikit/issues/3169) since those settings don't change the results. The problem occurs with slidenavs when no dragging is performed.

**Comment by TomS-** [comment]
Also experiencing this

**Comment by janschoenherr** [comment]
This seems to be resolved.
