### ISSUE TITLE
uk-column-span don't work in Firefoz

### ISSUE THREAD

**Issue by PavelNSH** [uikit/uikit#3753]
### UIkit version

3.0.3

### Browser
Firefox 65.0
### Steps to reproduce
Copy example from https://getuikit.com/docs/column#span-all-columns or open this link in Firefox
### What is Expected?
Element span the whole width of the columns
### What is actually happening?
Element not span the whole width of the columns

**Comment by saschadube** [comment]
[We are aware](https://github.com/uikit/uikit/blob/develop/src/less/components/column.less#L120) of this. It's currently not supported by Firefox. Here is the [filed bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=616436).
