### ISSUE TITLE
Slideshow autoplay stops working on tap mobile/iPad

### ISSUE THREAD

**Issue by bivish** [uikit/uikit#3757]
Hey Guys, slideshow autoplay is working fine in the browser but, on mobile initially, it's working but it stops working once scrolled. Simply saying, on tap, it's stopped working. Anyone, please help me on this?

**Comment by joeyslack** [comment]
If I'm understanding you, it might be related to another bug here, related to "Draggable". Although draggable might be disabled, it will still stop the slideshow related to a bug in the check not resuming the original timer.

**Comment by janschoenherr** [comment]
Is this still an issue with latest dev release?
