### ISSUE TITLE
Italic text is apparently dangerous?

### ISSUE THREAD

**Issue by yratof** [uikit/uikit#3762]
Italic text should not be red, should not be danger colour. A paragraph of text that just highlights quotes suddenly become red highlighted thoughout by default.

I would suggest that we change:

```
$base-em-color:                                  $global-danger-background !default;
```

to 

```
$base-em-color:                                  $global-color !default;
```

in order to not cause out of place errors. if then there are places where you have actual danger messages, they should be self contained within a form of danger class.

**Comment by aarongerig** [comment]
The `<em>` tag is for emphasizing a certain part of a text, therefore it is not explicitly meant to display text in italic. I would suggest you to do this with plain CSS:

```css
.uk-text-italic { font-style: italic; }
```

**Comment by yratof** [comment]
In the context of Wordpress, their "Italic" wraps content with <em>, which is what brought the issue to my attention

**Comment by aarongerig** [comment]
Well, then that's where the issue is. Also see: https://www.w3schools.com/tags/tag_em.asp

**Comment by yratof** [comment]
Ok, i'll se if I can raise the issue with Wordpress and the gutenberg team, but of course, it still stands that an `<em>` might not be best suited to a "danger" colour

**Comment by aarongerig** [comment]
If you don't like the default `danger` color for the `<em>` element, you could create your own theme with a custom color for it.
