### ISSUE TITLE
Are component Global options working?

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3763]
### UIkit version

3.0.3

### Browser
All
### Reproduction Link
https://codepen.io/zzseba78/pen/VgxWYy

### What is Expected?
Components should take global options.

### What is actually happening?
They don´t. 
Maybe it´s not the way it should be implemented, any guidelines are welcome.

**Comment by janschoenherr** [comment]
The problem here seems to be, that codepen inserts the javascript at the bottom of the page. By the time it gets executed, UIkit has already initialized its components.

**Comment by zzseba78** [comment]
@janschoenherr Thanks for your response! I will check it out locally then, and close this issue it it works.

**Comment by zzseba78** [comment]
Doesn´t work for me. If i put script before uikit.js throws an error "UIkit it´s not defined", if i put it after, the component doesn´t take the global option.

Before uikit.js
test.byhumans.works/uikit/before.html
After uikit.js
https://byhumans.works/area/test/uikit/after.html

**Comment by janschoenherr** [comment]
Yes, you'd have to do your own UIkit build, if you'd want to defer UIkit and change the global options.
