### ISSUE TITLE
Include composer.json for Composer/Packagist

### ISSUE THREAD

**Issue by 8ig8** [uikit/uikit#3768]
Please include a composer.json file to support [Composer](https://getcomposer.org) installation via [Packagist](https://packagist.org).

- [composer.json in UIkit v2](https://github.com/uikit/uikit/blob/v2/master/composer.json)
- [UIkit listing in Packagist (terminated at v2.27.5)](https://packagist.org/packages/uikit/uikit)

Thank you very much.

**Comment by aarongerig** [comment]
This doesn't make sense. I don't know why version 2 had a `composer.json` in the first place. UIkit is not a PHP package and Packagist is for PHP packages only.

**Comment by 8ig8** [comment]
I filed the bug because I tried to install UIKit via composer today and realized I didn't get v3.

As of today, there have been [16,701 installs](https://packagist.org/packages/uikit/uikit) of UIKit via Packagist. But now there is no knowledge of v3 due to missing this 1 file.

composer.json has been included in both v1 and v2 ([history](https://github.com/uikit/uikit/commits/6f7d7723e274b2eacb1d3301e92b0d32fcd83d28/composer.json)). The file has been in the repo since the [initial commit](https://github.com/uikit/uikit/blob/c8a8d96c3d7827bace8a0ee95b453d737cdd71e2/composer.json).

I understand this isn't a PHP package, but UIKit is a potential dependency for PHP projects. There are other non-PHP projects in the directory, for example:

- [Bootstrap](https://packagist.org/packages/twitter/bootstrap)
- [Pure](https://github.com/pure-css/pure)
- [Zurb Foundation](https://packagist.org/packages/zurb/foundation)

Thanks, again.
