### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by prfardin** [uikit/uikit#3771]
i use toggle to collapse and open a side bar
i use a custom animation in css like this:
tm-sidebar {
width:  20%;
transition: width 0.2s ease-in-out;
}
.tm-collapse .tm-sidebar {
width: 0;
}
when i click on toggle to open sidebar its work good but its content ( have uk-grid leave margin top in each of element) and when i resize windows its going fix but its have bug.
how update content after toggle show! just this
sry for my bad English!

**Comment by timrasche** [comment]
Have you tried to use offcanvas for this behavior? It has already an slide animation and works great with css width. Next, please add some test scenarios (e.g. browser, version, uikit version) and at least do you use the css class selector for the margin or the attribute?

**Comment by prfardin** [comment]
> Have you tried to use offcanvas for this behavior? It has already an slide animation and works great with css width. Next, please add some test scenarios (e.g. browser, version, uikit version) and at least do you use the css class selector for the margin or the attribute?

dud ty i use offcanvas! its work great, ok i will that another time !
