### ISSUE TITLE
Events trigger multiple times

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3777]
### UIkit version

3.0.3

### Browser
Chrome

### Reproduction Link

https://codepen.io/anon/pen/YBbxXd

### Steps to reproduce
1. Listen for events on Slideshow (may happen on others)
2. Check when it fires

### What is Expected?
Should only fire once

### What is actually happening?
Fires multiple times depending. 
`beforeitemshow` fires 2 times
`itemshow` fires 2 times
`itemshown` once (correct)

**Comment by janschoenherr** [comment]
This should be resolved with the latest dev version.
