### ISSUE TITLE
iPhone - Tooltip is not working

### ISSUE THREAD

**Issue by TomNaegele** [uikit/uikit#3778]
### UIkit version

3.0.3

### Browser
iphone Safari , iOS 12.1.4
### Reproduction Link
https://getuikit.com/docs/tooltip

### What is Expected?
Tooltip should open
### What is actually happening?
Nothing, Android works

**Comment by janschoenherr** [comment]
Thanks, fixed with 65541ba5790aee618d92e19bca3269fc889fb492
