### ISSUE TITLE
Fields on Modal are not submitted

### ISSUE THREAD

**Issue by austre** [uikit/uikit#3779]
### UIkit version
3.0.3

### Browser
Chrome 72.0.3626.109 64 bits, Firefox 65.0.1 64 bits
### Reproduction Link
Think i can't do a submit with codepen.

### Steps to reproduce
So, i have one page with form and inside that, code attached. When i click at submit button outside modal area, without open Modal, submit get fields from Modal Area and others.

If i open Modal Area, put some value at fields and click at submit button inside Modal Area, form are not submitted. If i click at submit button outside Modal Area, form are submitted, but fields from Modal Area are not posted.

### What is Expected?
Like UIKit 2, submit button inside Modal Area should submit form and post all fields: inside or not Modal Area.

### What is actually happening?
Submit button inside Modal Area do not submit form.
[uikit_modal_code.txt](https://github.com/uikit/uikit/files/2889689/uikit_modal_code.txt)

**Comment by aarongerig** [comment]
By default a modal gets appended to the DOM. In your case it removes itself out of the form context. Therefore you have to either set a specific `container` for the modal to attach to or set it to `false` to prevent this behaviour: https://getuikit.com/docs/modal#component-options

In your case `<div uk-modal="container: false">...</div>` should be enough.
