### ISSUE TITLE
[Documentation] List available Javascript UIKit utility functions

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3781]
With jQuery becoming less and less needed, it would be a shame to double up the work you have done with the utility functions for those who need it. I can see UIkit.util.on is documented but nothing other than that, I was wondering what other is available through the API. UIkit.util.closest for example. It would be good to have a list of helper functions that are available in the JavaScript section. 

Useful things such as UIkit.util.ready(function() { }) aren't even listed.

**Comment by aarongerig** [comment]
That is already being worked on, see https://github.com/uikit/uikit-site/blob/feature/js-utils/docs/pages/javascript-utilities.md

Since it is a side project of mine and I can only work on it in my free time, you are more than welcome to contribute. Thanks!

**Comment by Ulrich-Mbouna** [comment]
Is There update of this librairy ?
