### ISSUE TITLE
Toggle in hover-mode is not toggleable on touch devices

### ISSUE THREAD

**Issue by nstaeger** [uikit/uikit#3782]
### UIkit version
3.0.3

### Browser
Safari/Firefox on iOS, Ipad Mini, latest versions
Firefox on Windows 10 with touch input, latest versions

### Reproduction Link
Official Hover-example on https://getuikit.com/docs/toggle#modes

### Steps to reproduce
Use one of the above mentioned browsers and touch input to toggle the button that is in mode _hover_.

### What is Expected?
When using touch I would expect the toggle to trigger on a click, as touch does not have a hover state. At least this was how it worked on `3.0.0-rc.16`.

### What is actually happening?
Nothing.

If the by me suggested exepcted behaviour is not the desired behaviour, how do I make a toggle react to hover on non-touch and to click on toch devices?

**Comment by janschoenherr** [comment]
Thanks, fixed with e9a07e6182d024b597028545f62375baa01268a5

**Comment by nstaeger** [comment]
Thanks for acting that quick! Is there already a relasedate for this fix?

**Comment by nstaeger** [comment]
@janschoenherr Was this tested properly? I am pretty sure it was, but it is not working for me when installing from the develop branch and I cannot find the problem on my end. So I just wanted to double check.

**Comment by janschoenherr** [comment]
Did you build the JS after using the code from develop branch? You can also pull the latest dev release from npm. They are tagged with 'dev'

    yarn upgrade uikit@dev

**Comment by nstaeger** [comment]
@janschoenherr The `uikit@dev` is definitly something, that should be mentioned in the docs. Super helpful. At the end it was indeed a mistake on my side. Not exactly sure what I missed, but using your provided dependency worked out well. Now everything works as expected. Thanks again!
