### ISSUE TITLE
Lightbox - Vimeo autoplay not working in Chrome

### ISSUE THREAD

**Issue by gola99** [uikit/uikit#3783]
### UIkit version
3.0.3

### Browser
Chrome 72.0.3626.109

### Reproduction Link
https://codepen.io/anon/pen/XOvvQa

### What is Expected?
Video should autoplay. 

### What is actually happening?
Video is not playing automatically

Chrome 72.0.3626.109 on MacOS 10.14.3 - Not working
Safari on iOS 12.1.4 - Not working
Firefox on MacOS - Working 
Safari on MacOS - Working 

### Here is why
Maybe this helps
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by AlekVolsk** [comment]
Firefox on Windows 10 - Working
Chrome on Windows 10 - **Not working**

**Comment by eladnova** [comment]
I thought autoplay only worked if videos were muted?

**Comment by janschoenherr** [comment]
Yes, autoplay for YouTube and Vimeo seems to work on muted videos only. We are aware of the issue, but have yet to find a solution.

**Comment by eladnova** [comment]
Policies like these are set by Chrome browser developers themselves. I don't think there can be over-rides so I wouldn't call this a bug per se.

**Comment by gola99** [comment]
The Chrome Autoplay Policy also says:

Autoplay with sound is allowed if:
- User has interacted with the domain (click, tap, etc.).

Is there some quick fix you can provide?

**Comment by janschoenherr** [comment]
Yes, we already use that. It works fine for videos with the `<video>` tag. But it seems to no longer work for iframe embedded videos.

**Comment by ivcreative** [comment]
Any news on the status of this?

**Comment by janschoenherr** [comment]
Autoplay on Chrome has been fixed in the current dev version. On mobile this still does not work.

**Comment by janschoenherr** [comment]
Closing for now.
