### ISSUE TITLE
Delay option is not working for dropbar

### ISSUE THREAD

**Issue by Surbma** [uikit/uikit#3784]
### UIkit version
3.0.3

### Browser
Chrome, Safari, Firefox

### Reproduction Link
https://ravatherm.com/uk/en/

### Steps to reproduce
I have set dropbar on the Applications menu item. All menu items have delay, but the Application menu item with dropbar is not delayed.

### What is Expected?
Dropbar should be delayed too.

### What is actually happening?
Dropbar is not delayed, all other menu items are delayed.

**Comment by janschoenherr** [comment]
You'll need to apply the `delay-show` to the custom drop components too.

**Comment by Surbma** [comment]
@janschoenherr Yes, you are right, I put the option on the wrong element. Thank you!
