### ISSUE TITLE
Off-canvas with flip:true makes the page unresponsive

### ISSUE THREAD

**Issue by quatronic** [uikit/uikit#3786]
### UIkit version
3.0.0 and above (latest r.c. is working)

### Reproduction Link:
- [Codepen](https://codepen.io/anon/pen/wOwyNo) - plain html seems to work. Is the uitkit framework already included in the codepen provided?
- [Working example with off-canvas](https://test.quatronic.nl/issue/issue.php)
- [Non-working example with off-canvas and flip:true](https://test.quatronic.nl/issue/issue-flip.php)

### Steps to reproduce
For the non-working example, click on the menu, close the menu, the page becomes unresponsive.

### What is Expected?
That the body is not unresponsive.

### What is actually happening?
When closing the off-canvas menu, the classes "uk-offcanvas-container" and "uk-offcanvas-flip" are not removed from the body.

**Comment by zzseba78** [comment]
You should create a separate and simplified Codepen with your code.

**Comment by quatronic** [comment]
Yes, as mentioned in the instructions. However, I was not able to isolate the issue yet, so just posted it here to see if anyone else has the same issue.

The plain flip:true (as shown in the CodePen) is also working, so it much be a combination of the flip and another element.

Will post an update as soon as I've located the issue.

**Comment by quatronic** [comment]
I've located the issue.

In the theme.css, there was the following:

```
.uk-offcanvas-flip .uk-offcanvas-bar {
  left: auto;
  right: 0;
  transform: translateX(100%)
}
```

I've updated it to

```
.uk-offcanvas-flip .uk-offcanvas-bar {
  /* left: auto; */
  left: 100%;
  /* right: 0; */
  transform: translateX(100%)
}
```

and now it is working again.

So conclusion, no issue in the UIKit, but a conflict with the theme.
