### ISSUE TITLE
Make buttons with rounded angles ?

### ISSUE THREAD

**Issue by Diaskhan** [uikit/uikit#3789]
Feature Request
===============
Its possible to make buttons not with flat style!
Make buttons with rounded angles ?
![image](https://user-images.githubusercontent.com/15046677/53504405-18838780-3adc-11e9-8d50-8a98ac091c24.png)

### UIkit version

3.0.3

**Comment by flihub** [comment]
use .uk-border-rounded

https://getuikit.com/docs/utility#border-radius
