### ISSUE TITLE
Parallax calculates wrong

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3792]
### UIkit version

3.0.3

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/eXpjQe

### Steps to reproduce
1. Create a parallax element going from one position to another

### What is Expected?
You would expect that when the element is in the center of the screen it would be at the half way point, however it isn't until it's at the top. Causing a quicker 'out' animation than 'in'. 

### What is actually happening?
The center point doesn't seem to be calculating correctly.

**Comment by TomS-** [comment]
Found easing 0 is linear. Is this intended? If so this is not correct: 
`Lower values will cause a faster transition in the beginning, higher values will cause a faster transition in the end of the animation.`

Default is 1, to be faster in the beginning you need negative values. Makes sense to me. Wouldn't it make sense if the default was 0?

**Comment by janschoenherr** [comment]
The docs have been updated: https://getuikit.com/docs/parallax#easing
