### ISSUE TITLE
Date, Month, Week, Time picker sth wrong

### ISSUE THREAD

**Issue by ngya** [uikit/uikit#3793]
### UIkit version

3.0.3

### Browser
firefox:  
Date picker is ok
Month, Week, Time doesn't work.

chrome:
Date, Month, Week, Time have something wrong...

### Reproduction Link
https://getuikit.com/assets/uikit/tests/form.html

![datep](https://user-images.githubusercontent.com/3828979/53615647-dfe9c800-3c19-11e9-9f1c-074f3c623fbc.jpg)

**Comment by dansr** [comment]
> 
> ### UIkit version
> 
> 3.0.3
> ### Browser
> 
> firefox:
> Date picker is ok
> Month, Week, Time doesn't work.
> 
> chrome:
> Date, Month, Week, Time have something wrong...
> ### Reproduction Link
> 
> https://getuikit.com/assets/uikit/tests/form.html
> 
> ![datep](https://user-images.githubusercontent.com/3828979/53615647-dfe9c800-3c19-11e9-9f1c-074f3c623fbc.jpg)

in chrome you can hyde the spin buttons with css
`input::-webkit-outer-spin-button, input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}`
