### ISSUE TITLE
Is tooltip not disappear on touch devices?

### ISSUE THREAD

**Issue by hungi** [uikit/uikit#3794]
### UIkit version
3.0.3

### Browser
Android Chrome, Android Firefox, Xiaomi Browser

### Reproduction Link
https://codepen.io/lukacsp/pen/PLzqoz

### Steps to reproduce
Click on the CLICK button.

### What is Expected?
Tooltip disappear when clicked, just like on PC browsers.

### What is actually happening?
Tooltip isnt disappear.

**Comment by YakovL** [comment]
Yes, currently tooltip is opened on `mouseenter` and closed on `mouseleave`. Presumably `pointerleave` event should be handled as well

**Comment by janschoenherr** [comment]
The tooltip hides, after the button looses focus.
