### ISSUE TITLE
Offcanvas Push on Firefox

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#3797]
### UIkit version

3.0.3

### Browser
Firefox 65.0.1

### Reproduction Link
https://getuikit.com/docs/offcanvas#animation-modes

### Steps to reproduce
Click on Push Button

### What is Expected?
The whole page to go right

### What is actually happening?
The header stays still.

**Comment by janschoenherr** [comment]
This seems to have resolved itself.
