### ISSUE TITLE
Drop/Dropdown closing issue

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3798]
### UIkit version

3.0.3

### Reproduction Link

https://codepen.io/anon/pen/EMZjvE
https://codepen.io/anon/pen/gEgpGY

### Steps to reproduce

Open reproduction link.
Click the button.
Click any link inside the dropdown.

### What is Expected?

Modal opens and dropdown closes automatically.

### What is actually happening?

The first reproduction link works as expected using UIkit Version 3.0.0-rc.25.

In the second example the modal opens but the dropdown is still open.

The issue started by UIkit Version v3.0.0.-rc.26 and is still present in v3.0.3.

I tested different Desktop Browsers, haven't tested on mobile yet.

**Comment by wtfdanny** [comment]
Confirmed on mobile (Firefox, Safari, Chrome) —

**Example 1** - menu hides when modal is displayed
**Example 2** - menu remains visible when modal is displayed

**Comment by Lumelomser** [comment]
Fixed with [#fce3249](https://github.com/uikit/uikit/commit/fce324969c05e70fdcd0c5f07577582b5b3d5d98) which was released in v3.1.4
