### ISSUE TITLE
Filter blocks page scroll permanently if Scrollspy with Dynamic content is present.

### ISSUE THREAD

**Issue by Flicksie** [uikit/uikit#3800]
### UIkit version
3.0.3

### Browser 
All

### Reproduction Link
https://codepen.io/anon/pen/ywXxEx

### Steps to reproduce
Click in any filter
Scroll to bottom

### What is Expected?
You should be able to scroll back up

### What is actually happening?
Scroll is blocked and you can't even drag the scrollbar. A page refresh is needed.

**Comment by janschoenherr** [comment]
This seems to be resolved. If the issue persists, please comment.
