### ISSUE TITLE
[Feature Request] .uk-column and responsive

### ISSUE THREAD

**Issue by Jdeboysere** [uikit/uikit#3802]
### UIkit version

3.0.3

### Browser
All

### Reproduction Link
No need

### Steps to reproduce
`<div class="uk-column-1-2@s">...</div>`

### What is Expected?
To be allowed to use the columns only on specific screens.

### What is actually happening?
It is not possible yet.

**Comment by aarongerig** [comment]
Responsive columns are available, see https://getuikit.com/docs/column#responsive

**Comment by Jdeboysere** [comment]
Sweet Jesus. I am really blind. Thanks you.
