### ISSUE TITLE
Modal is not accessible

### ISSUE THREAD

**Issue by wanze** [uikit/uikit#3806]
### UIkit version

3.0.3

### Browser

Any

### Reproduction Link

https://getuikit.com/assets/uikit/tests/modal.html

### Steps to reproduce

* Navigate to a button toggling a modal with the `tab` key
* Open the modal by pressing the `enter` key

### What is Expected?

* The focus should automatically be given to an element inside the modal, probably the close button.
* After closing the modal, the focus should be set back to the element having triggered the modal.

### What is actually happening?

* After opening the modal, the focus stays on the triggering element. This makes the modal not accessible for keyboard users or screenreaders.

See also this related issue for Uikit 2: https://github.com/uikit/uikit/issues/1420

**Comment by janschoenherr** [comment]
This can already be achieved with giving the button the `autofocus` attribute.
