### ISSUE TITLE
Slider arrow not showing even after adding data-* in react

### ISSUE THREAD

**Issue by pakanyizi** [uikit/uikit#3808]
### UIkit version

3.0.3

**Comment by pakanyizi** [comment]
UIkit version 3.0.3. The slider is missing the arrows even after adding data-uk* prefix in React but works perfectly on normal HTML file.  Any idea of what i am doing wrong?

**Comment by TomS-** [comment]
Since you've provided absolutely no reproduction link or steps. I guess not.
