### ISSUE TITLE
[Feature Request] Switcher and Toggle to support animation when toggled through the JS API

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3816]
It would be good to allow animation to happen when toggling through the Javascript API. Using things like `.show()` and `.toggle()` will only do it's core swapping. While these components support animation, it would be good to have something like: 

`.show(1, 'uk-animation-slide-left-medium, uk-animation-slide-right-medium')` or the same with toggle.

**Comment by TomS-** [comment]
In the mean time I'm simulating clicks to achieve this.

**Comment by janschoenherr** [comment]
This is somewhat component specific. What component are you trying to show or toggle?

**Comment by TomS-** [comment]
@janschoenherr As per the title - Switcher and Toggle component.

**Comment by TomS-** [comment]
@janschoenherr I believe you may be getting confused. To better explain myself. 

The Switcher and Toggle components allow for animation when activated as a component. 
```
<button type="button" uk-toggle="target: #my-id; **animation: uk-animation-slide-left, uk-animation-slide-bottom**"></button>
<p id="my-id"></p>
```
For example. However, doing:
```
UIkit.toggle('#my-id').toggle();
```
Will not animate using the animation set. I understand this is because you can have multiple toggles target the same element and define different animations depending on what you click. So:
```
UIkit.toggle('#my-id').toggle('uk-animation-slide-left, uk-animation-slide-bottom');
```
Could be good. I've tried:
```
var _ = UIkit.util;

_.animate( _.$('#my-id'), 'uk-animation-slide-left', 300, false, true).then(function() {
    UIkit.toggle('#my-id').toggle();
});
```

However, this is very glitchy for whatever reason.

**Comment by janschoenherr** [comment]
Okay, I see. You could give the button an id and do: 

```
<button id="my-toggle" type="button" uk-toggle="target: #my-id; animation: uk-animation-slide-left, uk-animation-slide-bottom"></button>
<p id="my-id"></p>
```

`UIkit.toggle('#my-toggle').toggle();`

that would use the instantiated toggle component.

**Comment by TomS-** [comment]
@janschoenherr 

Oh wow, okay, I have no idea why I didn't think of that haha! Thanks.
