### ISSUE TITLE
uk-img & slideshow - loads all images from the beginning

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#3818]
### UIkit version

- 3.0.3

### Browser
- firefox, chrome, safari (all latest for Mac)

### Reproduction Link
- Used example from documentation, just added 5 more images in order to see this behaviour
- Pen: https://codepen.io/qdev/full/ROWpEY

### Steps to reproduce
- open browser's developer console on network tab (disable cache)
- run the pen

### What is Expected?
- initially load only 3 images (first, second and last)
- load others on slideshow navigation on next items, one at a time
- don't have `src` (and `srcset`) attributes just yet on all the images

### What is actually happening?
- it loads all images from the beginning
- all the images have `src` (and `srcset`) attributes set

### Extra thoughts
- it happens even without `target` option, which means that somehow the images are considered to be in the viewport at the beginning
- I suspect it's from the new IntersectionObserver recently introduced for image component
- [here's the same pen using v3.0.2](https://codepen.io/qdev/full/JVYyzr) where it seems to work a little bit better (at least on Chrome & Firefox, I see Safari it's not working, not even with 3.0.0-rc26), meaning that it still loads two extra images, but not all
- I've found this trying to implement `picture` element with support for webp & jpg fallback on a uk-viewport-height (cover) slideshow

**Comment by razvanioan** [comment]
This is still happening on v3.1.8, so I still have to skip `uk-img` functionality and place custom code on slide show events ...

**Comment by janschoenherr** [comment]
Please see https://github.com/uikit/uikit/issues/3612

You'll have to clear the sessionStorage between your tests.

**Comment by razvanioan** [comment]
Perfect, now it seems ok !

This should be mentioned in the docs ;)
