### ISSUE TITLE
Manual callback to trigger Grid match with ajax loaded content 

### ISSUE THREAD

**Issue by akselhenriksen** [uikit/uikit#3820]
Is there any way to manually call grid match? We have an issue where our content is loaded through ajax. Sometimes the content seems to be loaded after the grid match functionality has been run, ending up with items not being the same height.

**Comment by flihub** [comment]
try

// Calls the update hook on components registered on the element itself, it's parents and children.
UIkit.update(element = document.body, type = 'update');

https://getuikit.com/docs/javascript#programmatic-use

**Comment by akselhenriksen** [comment]
I tried this but no effect it seems. The ajax functionallity is within a custom Vue component if that makes any difference?

**Comment by flihub** [comment]
in your component you should call like this after ajax success,

Vue.nextTick(function () {
  // DOM updated
  UIkit.update(element = document.body, type = 'update');
})

https://vuejs.org/v2/api/#Vue-nextTick

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
