### ISSUE TITLE
uk-sticky does not recalculate during uk-height-match

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3821]
### UIkit version

3.0.3

### Browser
Chrome

### Reproduction Link
As soon as I'm not busy.

### Steps to reproduce
1. Create div elements that use uk-sticky
2. Try to use uk-match-height to match the items inside the uk-sticky
3. The uk-sticky-placeholder does not update and calculated incorrectly. 

### What is Expected?
Should update and recalculate based on element inside increasing/decreasing in height. 

### What is actually happening?
Items break out when using bottom: true;

**Comment by mohamedhamad** [comment]
I have the same issue with a grid with one side an accordion, and the other side an image which is sticky. if the accordion is closed, the sticky image on the right assumes the old height and doesn't unstick at the right point.

**Comment by janschoenherr** [comment]
The upcoming release will contain several fixes for the Sticky component. Please check with the current dev version

https://www.jsdelivr.com/package/npm/uikit?version=3.11.2-dev.fb043abc2
