### ISSUE TITLE
What is the intended workflow with UIkit when creating a custom theme with Webpack?

### ISSUE THREAD

**Issue by hdodov** [uikit/uikit#3822]
We have Webpack for our project and we need to customize a great amount of things. I.E. we need to create our own theme. According to [the docs](https://getuikit.com/docs/sass#how-to-structure-your-theme), I should have:

```
@import 'theme/_import';

@import '~uikit/src/scss/variables';
@import '~uikit/src/scss/mixins';

@import "~uikit/src/scss/uikit";
```

Where the `theme` folder is a copy of `uikit/src/scss/theme`. However, I get an error:

>Undefined variable: "$global-muted-background".

So what should I do in this situation?

- Did I rightfully copy that `theme` folder? Is it meant for copy-paste and then modification? If yes, what do I import before that folder so that the necessary variables are declared?
- Should I copy the whole `variables-theme.scss` file and modify _it_ instead? In that case, what's the purpose of splitting each component's variables into files, as the docs suggest? Also, everything would be a mess.
- Where should I put my custom global variables? In `theme/variables` and then import them in `theme/_import`?

**Comment by hdodov** [comment]
Asked on [StackOverflow](https://stackoverflow.com/questions/55614015). Sorry for posting here.

**Comment by mechanic22** [comment]
@aarongerig Thanks! I do realize this is how to use it properly. What I am saying is I have no way of using something like $global-background inside my own themes variables (IE Your uikit/uikit-variables.scss' file) unless I define it myself (so i would have to copy and paste the values from the uikit src director into my own and if they ever change, I have to copy them again) - i have no way of using the uikit default variables in my variables file.

For example if I have some custom situation where I need to do something like

`$my-cutsom-control-background: $global-background`

I am required to manually define $global-background in my variable files also, just to use it.

I hope this makes sense :) as "I think" I know the proper way but i feel like the limitation is how scss uses the !default keyword - I think what i want is to be able to set all the default uikit variables, then overwrite the ones I want where I can use other uikit variables to define them. In the case where I must define the variables I want to overwrite first, I am unable to use other uikit variables to define them. I appreciate the repo though. 👍
