### ISSUE TITLE
How to change a UIkit variable to another default UIkit variable?

### ISSUE THREAD

**Issue by hdodov** [uikit/uikit#3823]
The default value of `$button-large-font-size` is `$global-small-font-size`. I want to change it to `$base-h5-font-size` or `$global-font-size`, which are the same. I have the following setup, as suggested by [the docs](https://getuikit.com/docs/sass#how-to-structure-your-theme):

```scss
@import 'theme/button.scss';

@import '~uikit/src/scss/variables';
@import '~uikit/src/scss/mixins';

@import "~uikit/src/scss/uikit";
```

And inside button.scss I have:
```scss
$button-large-font-size: $base-h5-font-size;
```

But that doesn't work since `$base-h5-font-size` is not defined, and neither is `$global-font-size`. Should I move the import below `uikit/src/scss/variables` against the docs' advice?

What's the correct approach in this situation?

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
