### ISSUE TITLE
Question! Focusable List, and filter 

### ISSUE THREAD

**Issue by Diaskhan** [uikit/uikit#3824]
1.It possible to make Focusable list box ? 
with single selection ?

2. And Filtering the list  ?

![image](https://user-images.githubusercontent.com/15046677/55903968-92855100-5bf0-11e9-8ba0-06d02a3613df.png)

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
