### ISSUE TITLE
uk-cover autoplay: true starts autoplay when video is paused on scroll

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3830]
Much like autoplay: inview, however, autoplay: true should only fire once allowing user to pause. 

### UIkit version

3.0.3

### Browser
Chrome

### Steps to reproduce
1. Create a video with autoplay: true
2. Pause the video
3. Scroll

### What is Expected?
Should remain paused

### What is actually happening?
Starts to play

**Comment by Ethan-Newthink** [comment]
Also having this issue.

**Comment by ayarsava** [comment]
Same here

**Comment by fire2** [comment]
Same here
