### ISSUE TITLE
uk-height-viewport and uk-slideshow doesn't calculate correctly in 3.1.0

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3831]
I have updated a website to 3.1.0 and now uk-height-viewport doesn't calculate correctly, sometimes setting min-height: 0 rather than the viewport value.

https://getuikit.com/docs/slideshow#viewport-height

### UIkit version

3.1.0

### Browser
Chrome

### Reproduction Link

http://dev.peterandpaul.co.uk/eizoawards/gallery/

### Steps to reproduce
1. Load a uk-slideshow with uk-height-viewport via ajax
2. Sometimes loads with min-height: 0;

### What is Expected?
Should load with viewport: 70vh

### What is actually happening?
Sometimes loading with min-height: 0;

**Comment by janschoenherr** [comment]
I can't seem to find the slideshow on your reproduction link.

**Comment by TomS-** [comment]
@janschoenherr if you click on the images it opens up a slideshow in a modal. Sometimes it will display, sometimes it will not because of the min-height bug.

**Comment by janschoenherr** [comment]
This has hopefully been resolved. If not, I will reopen the issue.
