### ISSUE TITLE
UIkit docs and download are 404

### ISSUE THREAD

**Issue by megler** [uikit/uikit#3834]
On the main website https://getuikit.com/- the download generates a 404 and the docs do the same for anything beyond the introduction.

EDIT:  specific to the docs - the Get Started link is 404.  If you click the documentation link at the top of the page everything works.  None of the download uikit links seem to be working, however.

**Comment by bdthemes** [comment]
Same for me 😟 nothing loading there: http://prntscr.com/ndiflw

**Comment by janschoenherr** [comment]
Thanks, it's fixed now.
