### ISSUE TITLE
'Icon' section of the documentation website rendering issue

### ISSUE THREAD

**Issue by loganwishartcraig** [uikit/uikit#3835]
### UIkit version

N/A - Documentation site issue

### Browser
Chrome 73.0.3683.103 (Official Build) (64-bit)
Firefox 66.0.3 (64-bit)

### Reproduction Link
https://getuikit.com/docs/icon

### Steps to reproduce
Navigate to the webpage

### What is Expected?
Correct rendering, with icons displayed

### What is actually happening?
See image below
![Capture](https://user-images.githubusercontent.com/7434537/56316663-bd4f3800-610f-11e9-8ea4-9c0dd272afd6.JPG)

Is anyone else experiencing this? Doesn't appear to be happening in any other sections.

**Comment by loganwishartcraig** [comment]
Might be related to #3834 ?

**Comment by janschoenherr** [comment]
Thanks, it's fixed now.
