### ISSUE TITLE
UIKIT 3 Filter uk-active bug since UIkit 3.0.0-rc.17

### ISSUE THREAD

**Issue by Hurmeli** [uikit/uikit#3838]
### UIkit version
3.1.0

### Browser
All

### Reproduction Link
https://codepen.io/Hurme/pen/MRVrpm

### Steps to reproduce
See the demo in codepen.

### What is Expected?
When you click ALL (color) or ALL (size), it should filter accordingly and mark the button active.

### What is actually happening?
Filter itself works fine, but the button will not get the uk-active class.

This used to work fine at least in UIkit 3.0.0-rc.17. As a sidenote, the filter also used to work with DIV's instead of only UL and LI as it does now. 

You can see it in action and working properly on a real website here:
http://www.jousiteos.fi/en/product-photos/

This website uses the UIkit 3.0.0-rc.17

I know it's not a critical bug, but it would be nice if it worked none the less. I'd imagine it should be fairly easy to fix as well (but perhaps I'm just imagining, not being a real coder myself).

**Comment by janschoenherr** [comment]
This should be resolved with 3.1.2. Thanks.
