### ISSUE TITLE
Scrollspy nav no longer working

### ISSUE THREAD

**Issue by mrockwood** [uikit/uikit#3841]
Scrollspy-nav no longer highlights active item.

### UIkit version
3.1.2

### Browser
All

### Reproduction Link
https://getuikit.com/assets/uikit/tests/scrollspy.html

### Steps to reproduce
Scroll down the page

### What is Expected?
Items in navigation should have class `uk-active` toggled depending on the scroll position.

### What is actually happening?
Classes are not being added.

---

I was able to trace the problem back to this commit: https://github.com/uikit/uikit/commit/998e66ffe7963afc1598f65614e35e9020cb61ae#diff-efa9abc3724351e77005b8da8e4f235f

**Comment by janschoenherr** [comment]
Fixed with 3.1.3

**Comment by mrockwood** [comment]
Thanks!

**Comment by Hurmeli** [comment]
Seems to be broken in 3.1.4. again.
