### ISSUE TITLE
Classname issue

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3844]
https://github.com/uikit/uikit/blob/c6bc10780ef9337d785bbfc146a8eff3173a5ad6/src/less/components/lightbox.less#L139

https://github.com/uikit/uikit/blob/c6bc10780ef9337d785bbfc146a8eff3173a5ad6/src/scss/components/lightbox.scss#L139

Maybe a copy & paste issue:
".uk-slideshow-items" should be ".uk-lightbox-items".

**Comment by janschoenherr** [comment]
Thanks
