### ISSUE TITLE
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted/

### ISSUE THREAD

**Issue by mechanic22** [uikit/uikit#3853]
### UIkit version
3.1.4

### Browser
Chrome

### Reproduction Link
https://codepen.io/mechanic22/pen/JVxQRW

### Steps to reproduce

Add a long nav list to an offcanvas item, and browse the page in chrome using a touch device. Then try and scroll using the touch device. You will get the following error:

> [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

This occurs at: https://github.com/uikit/uikit/blob/21be97753bc0922e6529087e854870d15dd6a3f1/src/js/core/offcanvas.js#L134

The fix for this is checking if(e.cancelable) before calling e.preventDefault(). 

```
if(e.cancelable)
    e.preventDefault();
```

I made the changes in pull request: https://github.com/uikit/uikit/pull/3854

I haven't checked but I am assuming this will occur in slider-drag also:

https://github.com/uikit/uikit/blob/ea09144c8c0a88c03e393248ef7a99625bece073/src/js/mixin/slider-drag.js#L75

### What is Expected?
No error

### What is actually happening?
Get the following error:

> [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by janschoenherr** [comment]
#3854 has been merged.
