### ISSUE TITLE
pointInRect does not work on sticky elements

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3857]
pointInRect works only elements that do not move. Sticky elements will fail. 

https://github.com/uikit/uikit-site/blob/feature/js-utils/docs/pages/javascript-utilities.md#pointinrect should use clientX and clientY in example, not pageX and pageY.

**Comment by janschoenherr** [comment]
Fixed with uikit/uikit-site@cd666829d13959020d692bda09e66837b1e73817
