### ISSUE TITLE
Pagination - Add first and last ( the icons were created already )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3858]
### UIkit version

3.1.4

### What is actually happening?
UIkit added chevron-double-left and right, this is the standart of first and last, why pagination doesn´t have this implemented like `<li><a href="#"><span uk-pagination-first></span></a></li>` and `<li><a href="#"><span uk-pagination-last></span></a></li>`?

**Comment by AlekVolsk** [comment]
#3617
