### ISSUE TITLE
Heading Line does not centered vertically in IE 11

### ISSUE THREAD

**Issue by thesergeev** [uikit/uikit#3859]
### UIkit version

3.1.4

### Browser
IE 11 

### Reproduction Link
https://getuikit.com/docs/heading#line-modifier

### Steps to reproduce
Open Reproduction Link in Internet Explorer 11. 

### What is Expected?
Heading should vertically centered like in other modern browsers.

### What is actually happening?
Heading doesn't vertically centered.
![screen_5764](https://user-images.githubusercontent.com/1877740/57354229-aa121400-7173-11e9-84e6-7cfaea2b52c8.png)

**Comment by janschoenherr** [comment]
We have dropped support for IE 11.
