### ISSUE TITLE
Several icons in the input form

### ISSUE THREAD

**Issue by dios-oleg** [uikit/uikit#3860]
It would be nice to have standard features for displaying several icons in the input field. 

The ability to display them from different sides and open a list of icons or buttons by clicking on the icons.

![Screenshot_2019-05-08 Диалоги](https://user-images.githubusercontent.com/19969187/57436937-67bb0680-7249-11e9-9144-f01b755dc226.png)

**Comment by m0yP** [comment]
But you can. Check out the forms documentation: https://getuikit.com/docs/form

**Comment by dios-oleg** [comment]
Thank. Maybe I missed something, but I did not find how to put several icons next to the input field. So now it implemented as in the screenshot.

![Screenshot_2019-05-08 Dios System Dios CMS](https://user-images.githubusercontent.com/19969187/57477903-5baf6300-72a2-11e9-9ebc-a22d30880fb0.png)

When using Iconnav, icons are incorrectly shifted (https://getuikit.com/docs/iconnav).

**Comment by sudoranger** [comment]
While I strongly agree with you, we should have a native support for multiple icons in the input element but bare in mind that UIkit is also a starter framework, where relying 100% on it without basic CSS skills could also minimize the creativity among users.

I made a simple hack/trick to embed those icons:

## HTML:
```
<div class="uk-section uk-section-primary">
   <div class="uk-text-center">
      <div class="uk-margin">
         <input class="uk-input uk-form-width-large today" type="text" placeholder="Where do you want to go today?">
         <a href="#camera"><span class="magic uk-margin-small-right" uk-icon="camera"></span></a>
         <a href="#pencil"><span uk-icon="happy"></span></a>
      </div>
   </div>
</div>
```

## CSS:
```
.today {
    padding-right: 80px;
}

.magic {
   margin-left: -70px;
}
```

## Result:
![Screenshot from 2019-05-17 15-01-47](https://user-images.githubusercontent.com/46080678/57909492-8195c280-78b5-11e9-8358-e81af30028a0.png)

**Comment by sudoranger** [comment]
While I strongly agree with you, we should have a native support for multiple icons in the input element. This could save a lot of code repetition on a large scale application. However, bare in mind that UIkit is also a starter framework, which means some people are relying on it too much by limiting their own creativity. The beautiful thing about UI/UX is, we are not limited to a certain/typical design. Try something new or start a new front-end movement if you may.

I made a simple hack/trick to solve the problem above but someone else might have other solutions. Good luck!

## HTML:
```
<div class="uk-section uk-section-primary uk-margin uk-text-center">
      <input class="uk-input uk-form-width-large today" type="text" placeholder="Where do you want to go today?">
      <a href="#camera"><span class="magic uk-margin-small-right" uk-icon="camera"></span></a>
      <a href="#pencil"><span uk-icon="happy"></span></a>
</div>
```

## CSS:
```
.today {  padding-right: 80px;} 
.magic { margin-left: -70px; }
```

## Result:
![Screenshot from 2019-05-17 15-14-43](https://user-images.githubusercontent.com/46080678/57910053-e3a2f780-78b6-11e9-8825-1544504b806a.png)

**Comment by sudoranger** [comment]
While I strongly agree with you, we should have a native support for multiple icons in the input element. This could save a lot of code repetition on a large scale application. However, bare in mind that UIkit is also a starter framework, which means some people are relying on it too much by limiting their own creativity. The beautiful thing about UI/UX is, we are not limited to a certain/typical design. Try something new or start a new front-end movement if you may.

I made a simple hack/trick to solve the problem above but someone else might have other solutions. Good luck!

## HTML:
```
<div class="uk-section uk-section-primary uk-margin uk-text-center">
      <input class="uk-input uk-form-width-large today" type="text" placeholder="Where do you want to go today?">
      <a href="#camera"><span class="magic uk-margin-small-right" uk-icon="camera"></span></a>
      <a href="#pencil"><span uk-icon="happy"></span></a>
</div>
```

## CSS:
```
.today { padding-right: 80px; }
.magic { margin-left: -70px; }
```

## Result:
![Screenshot from 2019-05-17 15-24-14](https://user-images.githubusercontent.com/46080678/57910501-097ccc00-78b8-11e9-86c9-707d205a83a1.png)

**Comment by dios-oleg** [comment]
> While I strongly agree with you, we should have a native support for multiple icons in the input element. This could save a lot of code repetition on a large scale application. However, bare in mind that UIkit is also a starter framework, which means some people are relying on it too much by limiting their own creativity. The beautiful thing about UI/UX is, we are not limited to a certain/typical design. Try something new or start a new front-end movement if you may.
> 
> I made a simple hack/trick to solve the problem above but someone else might have other solutions. Good luck!
> ## HTML:
> 
> ```
> <div class="uk-section uk-section-primary uk-margin uk-text-center">
>       <input class="uk-input uk-form-width-large today" type="text" placeholder="Where do you want to go today?">
>       <a href="#camera"><span class="magic uk-margin-small-right" uk-icon="camera"></span></a>
>       <a href="#pencil"><span uk-icon="happy"></span></a>
> </div>
> ```
> 
> ## CSS:
> 
> ```
> .today { padding-right: 80px; }
> .magic { margin-left: -70px; }
> ```
> 
> ## Result:
> 
> ![Screenshot from 2019-05-17 15-24-14](https://user-images.githubusercontent.com/46080678/57910501-097ccc00-78b8-11e9-86c9-707d205a83a1.png)
I also agree with you.
Thank you for your reply.
I made a proposal about the icons, as they, in my opinion, have not full implementation in the input fields.
