### ISSUE TITLE
Spinner within Vue v-if causes next element to spin after condition changes

### ISSUE THREAD

**Issue by jtc42** [uikit/uikit#3862]
### UIkit version

\>=3.1.2

Checked with 3.0.3, 3.1.0, 3.1.1, 3.1.2, 3.1.3 and 3.1.4. All versions after (and including) 3.1.2 cause this issue. All versions before work as expected.

### Browser
Chrome (+Electron), Firefox

### Reproduction Link
https://codepen.io/jtc42/pen/eazmvJ

### Steps to reproduce
Wrap a uk-spinner in a Vue v-if, which evaluates to False initially, and True when a button in the v-else statement is clicked.

Then, have the v-if evaluate back to False. 

### What is Expected?
Spinner div should unload, and v-else div should load normally, like it was at the very start.

### What is actually happening?
Spinner stays loaded, and all elements in the v-else start spinning too.

[Gif of issue](https://drive.google.com/file/d/1fA5NgS6VCXvDvMU2c6PrxIBF5lxx6-0_/view?usp=sharing).

[Codepen demoing issue.](https://codepen.io/jtc42/pen/eazmvJ)

**Comment by jtc42** [comment]
Also worth noting, the bug seems to be related to grids. If you take the v-else elements out of a grid, they behave as expected. See https://codepen.io/jtc42/pen/VOjLZE

**Comment by hjudt** [comment]
I can unfortunately confirm this.

**Comment by janschoenherr** [comment]
You can give the `<div>` with the spinner a `key="spinner"` attribute. That should solve it.
