### ISSUE TITLE
Slideshow option typo: finite => infinite

### ISSUE THREAD

**Issue by httplife** [uikit/uikit#3864]
UIkit 3.1.4 
slideshow option on page:
https://getuikit.com/docs/slideshow

slideshow="finite: true;"  #doesn't work
slideshow="infinite: true;" #working

typo?

**Comment by TomS-** [comment]
This isn't a typo. finite: true; will prevent looping. finite is false by default as sliders loop be default. I guess it could be called loop and be true by default. But this is the angle they have taken. Hope this clears it up.
