### ISSUE TITLE
** CSS ** Text overlapped by select arrow with uk-form-small modifier.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3867]
### UIkit version

3.1.4

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/OYmRgX?editors=1010
### What is Expected?
Text and right select arrow have some distance.
### What is actually happening?
Small Text overlapped by select arrow with `uk-form-small` modifier, set right padding to 8px overwriting the default 20px.

**Comment by sudoranger** [comment]
Nice catch.

Can you check line 309-338? https://github.com/uikit/uikit/blob/develop/src/scss/components/form.scss

Try to add some extra padding-right for uk-form-small and uk-form-large then recompile the sass?

**Comment by sudoranger** [comment]
I think might find the answer here. I changed the values to 20px.

## Line 55 & 60:
https://github.com/uikit/uikit/blob/develop/src/scss/components/form.scss

## Line 390 & 394:
https://github.com/uikit/uikit/blob/develop/src/scss/variables-theme.scss

## Line 388 & 392:
https://github.com/uikit/uikit/blob/develop/src/scss/variables.scss

Here are the results:

## Chrome:
![chrome](https://user-images.githubusercontent.com/46080678/57913211-b22e2a00-78be-11e9-8add-f9bcaf30c2a8.png)

## Firefox:
![firefox](https://user-images.githubusercontent.com/46080678/57913219-b65a4780-78be-11e9-8afe-cb4604ee32c0.png)

**Comment by sudoranger** [comment]
Nice catch! I think we might find the answer here. I changed the values to 20px and recompiled the sass.

## Line 55 & 60:
https://github.com/uikit/uikit/blob/develop/src/scss/components/form.scss

## Line 390 & 394:
https://github.com/uikit/uikit/blob/develop/src/scss/variables-theme.scss

## Line 388 & 392:
https://github.com/uikit/uikit/blob/develop/src/scss/variables.scss

Here are the results:

## Chrome:
![chrome](https://user-images.githubusercontent.com/46080678/57913211-b22e2a00-78be-11e9-8add-f9bcaf30c2a8.png)

## Firefox:
![firefox](https://user-images.githubusercontent.com/46080678/57913219-b65a4780-78be-11e9-8afe-cb4604ee32c0.png)

## Opera:
![opera](https://user-images.githubusercontent.com/46080678/57914416-2e297180-78c1-11e9-824b-ef8407f69db5.png)

**Comment by sudoranger** [comment]
Hello.

I think this might solve the problem. Feel free to submit a pull request.

https://github.com/uikit/uikit/blob/develop/src/less/components/form.less
https://github.com/uikit/uikit/blob/develop/src/scss/components/form.scss

**Line 321:**
```
- padding-right: $form-small-padding-horizontal;
+ padding-right: $form-small-padding-horizontal*2.5;
```

**Line 335:**
```
- padding-right: $form-large-padding-horizontal;
+ padding-right: $form-large-padding-horizontal*2;
```
## Results:
![Screenshot from 2019-05-17 17-13-11](https://user-images.githubusercontent.com/46080678/57917528-7350a200-78c7-11e9-92b4-a1c2ffeca6be.png)
