### ISSUE TITLE
Opening two or more modals at once makes the website unresponsive

### ISSUE THREAD

**Issue by mgray-lab4motion** [uikit/uikit#3870]
### UIkit version

3.1.5

### Browser
Chrome, Vivaldi, Firefox, electron
Couldn't test on other browsers

### Reproduction Link
https://codepen.io/mgray-lab4motion/pen/ZNJdEw

### Steps to reproduce
Try to open two or more modals at once using javascript.

### What is Expected?
The first modal to show and then the second modal to pop over the first one, probably closing the first one as well.

### What is actually happening?
The site freezes and becomes unresponsive.

**Comment by artpol** [comment]
Fast click on OPEN modal button [here](https://getuikit.com/docs/modal) show this issue.
Actual in 1.3.6

**Comment by janschoenherr** [comment]
This is fixed with the latest dev version.

https://codepen.io/anon/pen/xvZgew
