### ISSUE TITLE
[Discussion] Slidershow-Animations should use Translate3d

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3873]
Animations are not smooth on Mac OSX (Mostly because Mac rarely ships with a dedicated graphics card), I have a slider that is really smooth on my computer but far from 60FPS on Mac OSX and more 10FPS-15FPS. It stutters. I know currently you can't use translate3d because of limit of IE11, but I feel more should be done to try hit it.

I'm struggling to see at what point a translate3d will be inside translate3d? If this is a rare case, is it possible to check against it and use translate where applicable?

I've had a good look through the code and I've used UIkit for a very long time. Years and years and years. I feel like translate3d inside translate3d will be a rare occurrence?

**Comment by janschoenherr** [comment]
Did changing `translateX` to `translate3d` in #3876 have an impact on performance?

If so, we could easily revert to translate3d and use translateX on IE only.

**Comment by TomS-** [comment]
@janschoenherr Sorry about that - I have been trying the Github desktop app and accidentally pushed to origin rather than my folk. I should imagine that hardware accelerating does have better performance. The designers are complaining about jittering on their Mac. On my windows machine the animations are buttery smooth. I'm having a look to see if there is anything I can do to improve rendering performance. I can see will-change is in place and now I'm using translate3d which does improve it. I'm checking against flickity (which they referenced in an example of it working without lagging) to see if any more optimisations can be made.

**Comment by janschoenherr** [comment]
Okay, we'll change it to translate3d. Let's hope it does not affect font rendering. 🙃
