### ISSUE TITLE
form-custom elements: on reset form bug

### ISSUE THREAD

**Issue by spleanter** [uikit/uikit#3879]
When you reset the form, the "uk-form-custom" fields are not changed (select).
there is a solution:
<pre><code>$ ('form').on ('reset', function () {
	let customized = $ (this) .find ('*[data-uk-form-custom], *[uk-form-custom]');
	UIkit.formCustom (customized, {
		update: true
	});
});
</code></pre>
but I would like it to be in the main package

**Comment by janschoenherr** [comment]
Thanks, fixed with: https://github.com/uikit/uikit/commit/f300eb9ad96d89b172e5026d5533405fca007649
