### ISSUE TITLE
uikit tab component not working

### ISSUE THREAD

**Issue by johnzeus14** [uikit/uikit#3882]
i tried using the tab component to switch between my login view and my register view but it does not work. any help.

here is the code

  <div class="uk-margin-medium-top">
                        <ul class="uk-tab uk-flex-center ">
                           
                            <li data-uk-tab="{toggle:'#login-form'}"><a href="#login-form" >Login</a></li>
                            <li data-uk-tab="{toggle:'#register-form'}"><a href="#register-form" >Sign Up</a></li>
                        </ul>
                    </div>

                  
            <div class="uk-width-large uk-padding-large uk-align-center"  id="login-form">

        <form action="" class=" uk-form-stacked">
          <fieldset class="uk-fieldset">
          
            <div class="uk-margin">
              <div class="uk-inline uk-width-1-1">
                <span class="uk-form-icon uk-form-icon-flip" data-uk-icon="icon: user"></span>
                <input class="uk-input uk-form-xlarge" required placeholder="Email" type="email" v-model="signIn.email">
              </div>
            </div>
            <div class="uk-margin">
              <div class="uk-inline uk-width-1-1">
                <span class="uk-form-icon uk-form-icon-flip" data-uk-icon="icon: lock"></span>
                <input class="uk-input uk-form-xlarge" required placeholder="Password" type="password" v-model="signIn.password">
              </div>
            </div>
            
            <div class="uk-margin">
              <label><input class="uk-checkbox" type="checkbox" > Keep Me logged In</label>
            </div>
            <div class="uk-margin">
              <button type="submit" class="uk-button uk-button-primary uk-button-medium uk-width-1-1 uk-box-shadow-xlarge" v-on:click.prevent="userLogin" >Sign In</button>
            </div>
            
          </fieldset>
        </form>
        <div class="uk-margin">
              <button type="submit" class="uk-button uk-button-danger uk-button-medium uk-width-1-1 uk-box-shadow-xlarge">Login With Google</button>
            </div>
        <div>
          <div class="uk-text-center">
            <a class="uk-link-reset uk-text-small" data-uk-toggle="target: #recover;animation: uk-animation-slide-top-small">Forgot Your Password?</a>
          </div>
          <div class="uk-margin-small-top" id="recover" hidden>
            <form action="">
              
              <div class="uk-margin-small">
                <div class="uk-inline uk-width-1-1">
                  <span class="uk-form-icon uk-form-icon-flip" data-uk-icon="icon: mail"></span>
                  <input class="uk-input" placeholder="E-mail" required type="text">
                </div>
              </div>
              <div class="uk-margin-small">
                <button type="submit" class="uk-button uk-button-primary uk-button-medium uk-width-1-1 uk-box-shadow-xlarge">Send Password</button>
              </div>
              
            </form>
        </div>

      </div>

**Comment by zzseba78** [comment]
Hi @johnzeus14 Please ask for help in the Discord uikit channel, create a codepen with your code and you will get help there, and close this since it´s not a uikit issue. Thanks!
