### ISSUE TITLE
Offcanvas nav returning to top on close

### ISSUE THREAD

**Issue by chicoesqueleto** [uikit/uikit#3886]
Hi, I'm using the offcanvas nav with links to anchors inside the same page. The links works, but when the offcanvas nav closes, it returns to the top of the page.

**Comment by chicoesqueleto** [comment]
https://www.loom.com/share/7d0c75fa3cce442c805d49f33a1fa967

**Comment by chicoesqueleto** [comment]
Guys, if you can please check if it's an issue with the framework. It's not the first time I use Uikit, and everything worked fine. But it's the first time I use the last version. I couldn't make two components work properly: Offcanvas and Toggle. Those are pretty easy to use, and I checked the documentation many times. I'm asking a developer to find a way to build the offcanvas whithout using uikit, and praying for my client to not notice the elements that were supposed to toggle.

**Comment by janschoenherr** [comment]
Please add a minimal codepen to this issue. It makes it easier to understand the problem.
