### ISSUE TITLE
Bug with switcher and links

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#3891]
### UIkit version

3.1.5

### Browser
Latest Chrome

### Reproduction Link

https://codepen.io/anon/pen/pXjJgz?&editable=true

### Steps to reproduce
Click on the link above to open codepen. The Javascript will choose the second item of the switcher component.

### What is Expected?
After clicking on the link "Click me" in the second item of the switcher, the link to UIkit docs should open.

### What is actually happening?
Nothing

It only works with a present switcher navigation. Switching with pure Javascript results in disabling links. I guess there is an "event.preventDefault()" in the code where it not should be.

**Comment by zzseba78** [comment]
@ikabod Hi! You are using the component in a wrong way, check this example i create for you: https://codepen.io/zzseba78/pen/QXpgyM

If works for you, please close this issue.

**Comment by ikabod** [comment]
Thank you. This means I have to use a navigation, regardless if I need it or not. Ok, I can hide it, but it should work without it I guess.
