### ISSUE TITLE
Missing deployment of 3.1.6 to cloudflare

### ISSUE THREAD

**Issue by pkkummermo** [uikit/uikit#3893]
### UIkit version

3.1.6

The [docs](https://getuikit.com/docs/installation) refers to the cloudflare installation but it hasn't been deployed yet.

### Browser
N/A

### Steps to reproduce
Try to access the newest version through cloudflare

```
--2019-06-22 20:06:50--  https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css
Resolving cdnjs.cloudflare.com (cdnjs.cloudflare.com)... 104.19.198.151, 104.19.196.151, 104.19.197.151, ...
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.19.198.151|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-22 20:06:50 ERROR 404: Not Found.
``` 

### What is Expected?
The file to exist

### What is actually happening?
Returns 404

**Comment by janschoenherr** [comment]
I believe this is resolved.
