### ISSUE TITLE
Scrollspy Issue on Mac Laptops on resolutions around 1280x960

### ISSUE THREAD

**Issue by ivcreative** [uikit/uikit#3897]
### UIkit version

3.1.6

### Browser
Chrome / Safari / Firefox

### Steps to reproduce
Only happens on Mac system that is 13 inches screens, also tested it on browserstack lowering resolution to 1280x960 and was able to reproduce it there as well.
### What is Expected?
Images or Divs to show with the uikit animations

### What is actually happening?
Where there are animations it just simply not loads and browser crashes the pages that I have added those animations get later a message that they become unresponsive.

Testing on macs with bigger screens things work as intended.

**Comment by yazzbe** [comment]
got te same issues from version 3.1.6 and up.
Removing the "repeat: true" option from the html keeps the browser from crashing in my case.

**Comment by yazzbe** [comment]
Could this issue be related?
#3972 

I've created a test on codepen.
https://codepen.io/yazzy008/pen/yLBKbZg

NB: scroll the uikit example up and down (with the scrollbar, not the mouse wheel) to trigger a browser crash.

**Comment by janschoenherr** [comment]
Resolved with bf2d7d7a06de8e2d0ae62eda6b1a5d3e71c3d5f6
