### ISSUE TITLE
Feature request: uk-sticky set media height

### ISSUE THREAD

**Issue by Bloemendaal** [uikit/uikit#3898]
### Feature request
Could you please add an option to enable uk-sticky when the height of the page is larger than x, similar to what `uk-sticky="media:640"` does.
A feature like this would also do the job: When the sticky content is larger than x, the content is no longer sticky.

Thanks a lot :)

### UIkit version
3.1.6

### Browser
Chrome latest

**Comment by aarongerig** [comment]
Hi @Bloemendaal,

This is already possible, see the [documentation](https://getuikit.com/docs/sticky#component-options) for reference. You can use the `media` option with any valid CSS media query, e.g. `(max-width: 960px)`. Is this what you were looking for?

**Comment by Bloemendaal** [comment]
Wow! I didn't know that! That's indeed the solution!
