### ISSUE TITLE
uk-sticky bottom doesn't always work

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3902]
### UIkit version

3.1.6

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/PrEKoL

### What is Expected?
It should stop when it reaches the ID #end 

### What is actually happening?
It continues

**Comment by janschoenherr** [comment]
It sticks to the bottom of the element selected with the `CSS Selector`

**Comment by TomS-** [comment]
Maybe I'm getting the wrong but isn't #end a CSS selector? How would you select #end in this example?
