### ISSUE TITLE
Adding a link in Slideshow component

### ISSUE THREAD

**Issue by franklin-vidal** [uikit/uikit#3904]
Hello,

I tried to insert a link in a slideshow but it did not work, it appears blank. See the example below, in second slide.

https://codepen.io/franklinvieira/pen/Wqzrqr

**Comment by flihub** [comment]
a is a inline element and img has uk-cover attr, so img has "position: absolute;" and a has not width and height.

add ".uk-position-cover" OR "uk-display-block uk-height-1-1" to a

**Comment by franklin-vidal** [comment]
Thanks for the solution!
