### ISSUE TITLE
Plugin.Call() is not a function

### ISSUE THREAD

**Issue by Zedonboy** [uikit/uikit#3913]
### UIkit version

3.1.6

### Steps to reproduce
create a js file
```
import UIkit from "uikit/dist/js/uikit-core"
import notification from "uikit/src/js/components/notification"

UIkit.use(notification);

export default UIkit;
```
add this file in your entry file in webpack 4,

### What is Expected?
Expect my app to run
### What is actually happening?
but crashes with runtime error
Am seeing error plugin.call() is not a function @Uikit.use

**Comment by aarongerig** [comment]
@Zedonboy Correct would be:

```js
import UIkit from 'uikit/dist/js/uikit-core';
import Notification from 'uikit/src/js/components/notification';

UIkit.component('notification', Notification);
```

**Comment by Zedonboy** [comment]
It works thanks, it would have been better if the doc specify how to add UIKIT components individually....
