### ISSUE TITLE
lightbox won't show image when the image is stored on cloudinary

### ISSUE THREAD

**Issue by fischimglas** [uikit/uikit#3915]
using lightbox with an image coming from cloudinary, the lightbox won't show the picture, instead, i permanently see the spinner. if i use the same code for an image which is stored on my server, there is no problem, the picture will show up. here is my test:

https://codepen.io/fischimglas/pen/VJNvxj

researching in the issues, i found that a maybe solution would be to add "data-lightbox-type="image"  to the link, but it won't work anyway. i also tried to preload the image before the lightbox is triggered, without effect.

Using: UIKIT 3.1.6

**Comment by aarongerig** [comment]
@fischimglas The lightbox tries to guess the file type by its extension. Since the link from cloudinary doesn't provide any file extension, the lightbox doesn't know what type it should display.

You almost got the correct solution, but it's `data-type="image"` and not `data-lightbox-type="image"`.

**Comment by fischimglas** [comment]
awesome, thanks a lot!
