### ISSUE TITLE
Bottom doesn't work if bottom element is in viewport on load

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3927]
### UIkit version

3.1.6

### Browser
Chrome

### Reproduction Link
https://codepen.io/anon/pen/NQRZMx

### Steps to reproduce
1. Created a sticky element with a bottom div.
2. Have bottom div in viewport on load. 
3. Sticky doesn't respect bottom.

### What is Expected?
Sticky should be in the position of bottom.

### What is actually happening?
It ignores bottom.

**Comment by janschoenherr** [comment]
This seems to be working as expected for me. The sticky element will stick with its bottom to the bottom of the referenced element.

**Comment by TomS-** [comment]
@janschoenherr on every browser I have tried, the first "Hello" does not respect it's bounds and follows you down the page. It should in fact stay where it is.
