### ISSUE TITLE
Outdated installation document or invalid cdnjs links, shows error 404 instead.

### ISSUE THREAD

**Issue by sudoranger** [uikit/uikit#3930]
Visit https://getuikit.com/docs/installation

All links mentioned below are not working (as of the time of this writing) and redirected to a 404 error page instead.

https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.7/css/uikit.min.css
https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.7/js/uikit.min.js
https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.7/js/uikit-icons.min.js

**Comment by Christian1998** [comment]
Seems to be a temporary issue. All three links are working.
