### ISSUE TITLE
DOM ready issue since UIkit v3.1.7

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3931]
### UIkit version

3.1.7

### Browser

Apple Safari (macOS)
Google Chrome (macOS)
Mozilla Firefox (macOS)

### Steps to reproduce

Due to the fact that the latest version of UIkit doesn't work on cdnjs yet, I created this little test case.
Copy following code from CodePen and save as HTML-File for local testing and ensure UIkit-Files (CSS, JS) are correctly linked by it's version.
Open in Webbrowser.
If the issue doesn't occur on first page load, try to click the link inside the cards and navigate back.

#### v3.1.6

https://codepen.io/anon/pen/PMKGyV

#### v3.1.7

https://codepen.io/anon/pen/aeymQw

### What is Expected?

Grid has a blue background.

### What is actually happening?

With v3.1.6 everything works as expected.

Since v3.1.7 'elGrid' will return null mostly.

Issue is commit:
https://github.com/uikit/uikit/commit/0a71b2dd72ce4d7df87e2ea75f6c1f5e90d5aabe

**Comment by janschoenherr** [comment]
Not sure I understand the issue. For demonstration, you can also use jsdelivr.net

https://cdn.jsdelivr.net/npm/uikit
https://cdn.jsdelivr.net/npm/uikit/dist/js/uikit.js
https://cdn.jsdelivr.net/npm/uikit@3.1.7/dist/js/uikit.js
