### ISSUE TITLE
Use custom content type in Lightbox component

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3932]
I'd like to use custom content types to create custom HTML inside the Lightbox component in different scenarios.

So I stumble upon this:
https://github.com/uikit/uikit/issues/3281

Problem is, there is no 'type' object ("Cannot read property 'type' of undefined").

I created this CodePen to illustrate it as an example, where a link refers to a file, which isn't supported by default:
https://codepen.io/anon/pen/WVEozo

What is the ideal way to create custom markup in this case?

**Comment by Lumelomser** [comment]
Hi Jan,

thanks in a million for your quick fix!
I tried your fix in a local version and now have access to the item object as expected.
But sadly there's now an error when calling the 'setItem'-Method.

"Uncaught TypeError: Cannot read property 'hasChildNodes' of null"

The issue occurs in line:
https://github.com/uikit/uikit/blob/a0b33cb0945468d20726bbd9f118072dc36c6261/dist/js/uikit.js#L10103

When logging 'this.slides' it's an empty array at this point but the list item is still present in the DOM.

**Comment by janschoenherr** [comment]
LightboxPanel is a functional component. By calling ```UIkit.lightboxPanel(el)``` it is being reinitialized.

Try
```
UIkit.util.on(document, 'itemload', '.uk-lightbox', function (e, item) {
    if (item.type === 'my-example-type') {
        UIkit.getComponent(e.target, 'lightboxPanel').setItem(item, '<div><p>My example type markup</p></div>');
    }
});
```

**Comment by Lumelomser** [comment]
Hi Jan,
sorry for my late response!

I had time to try your example these days and now it works like a charm.

THX again!
