### ISSUE TITLE
Modal events conflict with nested Drop component

### ISSUE THREAD

**Issue by drmzio** [uikit/uikit#3933]
### UIkit version

3.1.7

### Browser
- Latest Chrome
- Latest Safari

### Reproduction Link

https://codepen.io/drmzio/full/PMKpex

### Steps to reproduce
1. Open the modal
2. Hover over button to reveal Drop component
3. Move mouse outside boundry to hide the drop

### What is Expected?
The modal "hide" event should not be fired.

### What is actually happening?
The modal "hide" event is fired when the Drop component hides.

**Comment by janschoenherr** [comment]
Please see: https://github.com/uikit/uikit/issues/3089#issuecomment-354795567
