### ISSUE TITLE
3.1.6 > hang/loop with bigger data

### ISSUE THREAD

**Issue by tonypartridge** [uikit/uikit#3934]
### UIkit version
3.1.6 > 

### Browser
Any

### What is Expected?
Page loads without issue

### What is actually happening?
Page goes into infinite loop, or extremely long loop depending on page assets / content.

Since these changes: https://github.com/uikit/uikit/commit/44e304157432283949556f685470a1bf5a6f2dca

We have noticed a big issue in our 'YourSites' component, it appears to cause an infinite loop or certainly a very long time. Initially we assumed the issue was our side, until we realised our phing script updates UiKit on build. 

Having debugged it, it has come down to be caused by:

src/util/fastdom.js 

by adding this condition and promise:

```
        if (microtask) {
            Promise.resolve().then(flush);
        } else {
            requestAnimationFrame(flush);
        }

```

reverting this to remove the promise and use requestAnimationFrame(flush) resolves all issues. 

Can we get a revert on this given it's causing regression?

**Comment by janschoenherr** [comment]
Could you give version 3.1.7 a try? Also, do you have link, where we can inspect the issue?

**Comment by tonypartridge** [comment]
Tried 3.1.7 too. It’s caused by that commit.

We can try to setup a dev site for you, given our component managed sites
it’s a little more time consuming to setup 👍

**Comment by janschoenherr** [comment]
Thanks, that'd be great.

**Comment by janschoenherr** [comment]
@tonypartridge Did you have a chance to setup the dev site?

**Comment by janschoenherr** [comment]
@tonypartridge Are you using the scrollspy component on your page? If so, could you checkout the latest UIkit version? Thanks.
