### ISSUE TITLE
Multiple navbars and overlapping

### ISSUE THREAD

**Issue by sylvaincaillot** [uikit/uikit#3937]
### UIkit version
3.1.7

### Browser
Chrome, IE, Firefox

### Reproduction Link
Overlap of the menu items between 2 navbars: https://codepen.io/springrider77/pen/QeqdpM

### Steps to reproduce
I am trying to set up a big menu on my site with 2 navbars on top of each other but elements of the bottom navbar seem to impact the display of the element of the top navbar. Click on Drop 1 or Drop 2 of my link above and you will see the overlap.

### What is Expected?
I would expect the 2 navbars to display independently from each other in the following design:
```
____________________________________________________
|       |                    Top navbar              |
|       |____________________________________________|
| Logo  |                 Bottom navbar              |
|_______|____________________________________________|
```

Something similar to https://codepen.io/springrider77/pen/mNBRmV but with the uk-navbar-right of the bottom navbar being correctly displayed.

I am probably not using uikit in the good way for displaying the 2 navbars on top of each other with a logo on the left side. Your suggestions will be welcome.

### What is actually happening?
When I try to add a uk-navbar-right on the bottom navbar, the dropdown of the top menu get mixed with the items of the bottom menu.
When I don't use a uk-navbar-right for the bottom navbar, it works fine: https://codepen.io/springrider77/pen/mNBRmV

**Comment by flihub** [comment]
because of uk-navbar-center how works. uk-navbar center has pos: absolute; so if you have multiple navbar, you might add z-index each navbar like this:

https://codepen.io/anon/pen/xvXdNa
