### ISSUE TITLE
Update from version 3.1.6 to 3.1.7 breaking offcanvas overlay, no longer works when the show() function is called.

### ISSUE THREAD

**Issue by joshuastewart-durban** [uikit/uikit#3939]
### UIkit version

3.1.7

**Comment by joshuastewart-durban** [comment]
Our previous implementation required the "container: true" option which was set as a default I assume, now that its set to false initially we had to specify it as **uk-offcanvas="overlay: true; container: true"**

**Comment by janschoenherr** [comment]
Sorry for that. In what scenario do you need the `container: true` option?
