### ISSUE TITLE
Flex Bug not considering attribute settings

### ISSUE THREAD

**Issue by DanielKulbe** [uikit/uikit#3940]
### UIkit version 
3.1.7

### Browser
IE11

### Steps to reproduce
* I have extended the navbar-nav item styles to allow span elements like link elements:
  `.uk-navbar-nav > li > span`
  which work as dropdown trigger
* I changed the selector of the Flex-Bug JavaScript component via attribute to check for span children as well

### What is Expected?
* the span elements should be the same height as the link elements in the navigation bar

### What is actually happening?
* the Flex-Bug component ignores that attribute setting and uses the default from the navbar component definition

### Proposed solution
Add property definition for `selMinHeight` to the Flex Bug component.
`props: {
    selMinHeight: String
},`

**Comment by janschoenherr** [comment]
Resolved with: c5ddbf1ba3c9d587f3c097d8469076743360532d
