### ISSUE TITLE
Everything is white

### ISSUE THREAD

**Issue by ArtMin96** [uikit/uikit#3944]
Hi guys. I'm new here. I have a problem with colors, borders, backgrounds etc. In my project everything is white. I can't see anything when the background color is white. I don't switch any other css. Version 3.1.5

**Comment by TomS-** [comment]
Do you have anything like uk-light applied anywhere? Is everything white because of a PHP error? Have you checked what is being output to the browser?

**Comment by joeyslack** [comment]
Share a jsfiddle

**Comment by ArtMin96** [comment]
> Do you have anything like uk-light applied anywhere? Is everything white because of a PHP error? Have you checked what is being output to the browser?

Hi. Thanks for your replay!
Already fixed.

**Comment by ArtMin96** [comment]
> Share a jsfiddle

Hi. Thanks for your replay!
