### ISSUE TITLE
Parsed Icon is null

### ISSUE THREAD

**Issue by manuelkleinert** [uikit/uikit#3946]
### UIkit version

3.1.7

### Browser
Chrome, FireFox

### Problem
Variable  **$(icons[icon].trim())** in document **uikit/src/js/core/icon.js**  is empty and throws an error in the function parsed[icon].**cloneNode(true)**.

### I fixed it this way:
 
`
function getIcon(icon) {

    if (!icons[icon]) {
        return null;
    }

    if (!parsed[icon]) {
        parsed[icon] = $(icons[icon].trim());
    }
    
    if (!parsed[icon]) {
        return null;
    }

    return parsed[icon].cloneNode(true);
}
`

**Comment by janschoenherr** [comment]
Did you add an icon with wrong markup?
