### ISSUE TITLE
Why Slideshow ratio: false set `min-height: 0px` ?

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3947]
### UIkit version

3.1.7

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/OJLXoWr
### Steps to reproduce
Resize browser window, css min-height doesn´t have effect.
### What is Expected?
With `ratio: false`, you have more control on the slideshow height using css and media queries, be able to set height, min-height and max-height if needed.
### What is actually happening?
Slideshow sets inline style `min-height: 0px` to the slideshow, it can be override with `!important `but why is this?

**Comment by janschoenherr** [comment]
Fixed in cb6ac638096f17a2c2de0805b2f6101b2da2a741

**Comment by zzseba78** [comment]
Great, thanks!

**Comment by outerlooper** [comment]
This is still broken for me v3.5.8
