### ISSUE TITLE
Errors when dragging slides.

### ISSUE THREAD

**Issue by viocassel** [uikit/uikit#3950]
### UIkit version

WIP

### Browser
Chrome 76.0.3809.100

### Reproduction Link

http://localhost:8080/tests/lightbox.html
http://localhost:8080/tests/slider.html
http://localhost:8080/tests/slideshow.html

### Steps to reproduce
Run `yarn test`
Go to http://localhost:8080/tests/lightbox.html 
or http://localhost:8080/tests/slider.html 
or http://localhost:8080/tests/slideshow.html
When you try to drag slides, they do not drag. Errors in the console.

### What is Expected?
Slides should be able to be dragged.

### What is actually happening?
![photo_2019-08-21_10-36-08](https://user-images.githubusercontent.com/3341562/63413446-62ea1f00-c402-11e9-99e2-a6601882c87c.jpg)

**Comment by janschoenherr** [comment]
Resolved with 7a3046d24494787dbc6d6f0bb5601ac819201e39
