### ISSUE TITLE
Dropdown accordion broken

### ISSUE THREAD

**Issue by Morrison52** [uikit/uikit#3952]
### UIkit version

3.1.4 - 3.1.7

### Browser
All

### Reproduction Link

Bad 3.1.4 - https://jsfiddle.net/vup4dfta/
Good 3.1.3 https://jsfiddle.net/vup4dfta/1/

### Steps to reproduce
Add accordion in dropdown than open the accordion, you will see the the dropdown close and the accordion open

### What is Expected?
Keep dropdown open while opening the accordion

### What is actually happening?
Dropdown close while opening the accordion

**Comment by janschoenherr** [comment]
Fixed in 709ffeb9198cee795a4248d8552e0d1be2619c94
