### ISSUE TITLE
Offcanvas element displaces sticky element in push mode (mobile devices)

### ISSUE THREAD

**Issue by eddiej** [uikit/uikit#3953]
On some mobile browsers, an offcanvas element that contains a form input will displace a sticky element after the offcanvas is hidden when push mode is used.

### UIkit version
3.1.7

### Browser
Safari 12 / Chrome 76 (on iPhone X, iOS 12.4)

### Reproduction Link
http://naughty-hodgkin-358a2f.netlify.com

### Steps to reproduce
1. On a mobile device, visit the url above. Note the sticky header placement:

<img src='https://user-images.githubusercontent.com/465769/63521851-1f211380-c4ef-11e9-936c-20d3bc0bf836.PNG' width='50%' />

2. Click on the open link to reveal the offcanvas element.

<img src='https://user-images.githubusercontent.com/465769/63521866-25af8b00-c4ef-11e9-8690-76965b0bd969.PNG' width='50%' />

3. Click on the form input within the offcanvas element.

<img src='https://user-images.githubusercontent.com/465769/63521898-39f38800-c4ef-11e9-994f-36124a057d97.PNG' width='50%' />

4. Click the 'done' button
5. Note the sticky header has moved position:

<img src='https://user-images.githubusercontent.com/465769/63521913-424bc300-c4ef-11e9-9331-ca7c426584be.PNG' width='50%' />

6. Hide the offcanvas element by clicking the 'x' or on the content outside of it.
7. Note the position and width of the sticky header:

<img src='https://user-images.githubusercontent.com/465769/63521926-47a90d80-c4ef-11e9-994b-19b29ba65108.PNG' width='50%' />

### What is Expected?
The header position should be consistent.

### What is actually happening?
The position of the header is not being reset when the offcanvas closes.

**Comment by janschoenherr** [comment]
This seems to be resolved.
