### ISSUE TITLE
Bug: Uikit Promise rejected when loading icons

### ISSUE THREAD

**Issue by FVolral** [uikit/uikit#3955]
Hi, 
I updated uikit from 3.0.0-beta.27 to 3.1.7. Now when I reload a page of my project, I get exception from uikit : a Promise is rejected because `Icon not found`.

it's here in uikit.js
```
 methods: {

            getSvg: function() {

                var icon = getIcon(applyRtl(this.icon));

                if (!icon) {
                    return Promise.reject('Icon not found.');
                }

                return Promise.resolve(icon);
            }

        }
```

`getIcon `cannot get the icon requested, probably because at this time `icons` is empty. Note that when I close my Chrome Dev tool, icons load will be correctly loaded.

**Comment by janschoenherr** [comment]
The icons must be present at the time, the component gets initialized.
