### ISSUE TITLE
UIkit.modal.dialog and extra classes

### ISSUE THREAD

**Issue by sylvaincaillot** [uikit/uikit#3961]
To open my modal, in my Ajax success section, I am opening it with the method: `UIkit.modal.dialog(...)` with works fine.
However, I would like to apply the `class="uk-modal-container"` to my modal in order to expand its width to the container.

How can I do that?

Thank you

Sylvain

**Comment by janschoenherr** [comment]
With the next release the promise object returned by Modal Dialogs holds a reference to the Modal component itself. Does this help you?

https://github.com/uikit/uikit-site/commit/058dd17e7f654596317816ed5822cab071606c7f

**Comment by sylvaincaillot** [comment]
The reference to the Modal would probably make it. Looking forward for the next release and the related documentation.
