### ISSUE TITLE
Compile Sass error

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#3962]
### UIkit version
3.1.8

I am new to Sass.
I am trying to compile `uikit.scss` and I am getting the following error.

```
D:\laragon\www\uikit\uikit\src\scss (develop)
λ sass uikit.scss style.css
Error: Undefined variable.
    ╷
606 │ $inverse-base-color:                            $inverse-global-color !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^
    ╵
  components\base.scss 606:49  @import
  components\_import.scss 4:9  @import
  uikit.scss 5:9               root stylesheet
```

**Comment by Hurmeli** [comment]
Same problem exists with 3.2.0

**Comment by Hurmeli** [comment]
Few versions back if you downloaded the source scss, it compiled just fine. So this is something they should fix.

**Comment by ruwmapps** [comment]
Same problem exists with 3.3.*
все еще не отремонтировали

**Comment by anhkhoi** [comment]
I have the same issue with version 3.3.7

**Comment by AlekVolsk** [comment]
And will not be changed. Use Less.

**Comment by janschoenherr** [comment]
Please checkout https://getuikit.com/docs/sass#how-to-build

You'll have to include the src/scss/variables.scss file
