### ISSUE TITLE
Opening modal scrolls page to the top

### ISSUE THREAD

**Issue by sylvaincaillot** [uikit/uikit#3964]
Hello,
Each time, using the latest version of UIkit, I am opening a modal, it scrolls automatically to the top of my page. 
I would like to remain on the current position in my page.
How can i do that?

Thank you
Sylvain

**Comment by joeyslack** [comment]
What does your "open" button look like? If you're doing it like <a href="#"> of course it will scroll to the top.

**Comment by DustinGT** [comment]
If 

> Hello,
> Each time, using the latest version of UIkit, I am opening a modal, it scrolls automatically to the top of my page.
> I would like to remain on the current position in my page.
> How can i do that?
> 
> Thank you
> Sylvain

In your primary CSS check if you have **height: 100%** on **body** or **html**, if you have this, comment those lines and check if works.

**Comment by sapiocoded** [comment]
Having the same issue.@DustinGT solution fixed it, but I need that functionality to push footer to bottom. I might switch to another solution.

**Comment by sylvaincaillot** [comment]
As @sapiocoded mentioned, the solution of @DustinGT works. The modal is correctly displayed when I comment height:100% on html but I need it to push my footer to the bottom so I can not use this solution...
Any workarounds to fix this issue?
