### ISSUE TITLE
div-based Accordions not accessible via keyboard

### ISSUE THREAD

**Issue by andy-blum** [uikit/uikit#3965]
### UIkit version

3.1.9

### Browser
Chrome/FF

### Reproduction Link
https://s.codepen.io/andy-blum/debug/KKPybjg/mWAoNLNObBPr

### Steps to reproduce
Create an accordion using elements other than ul/li elements

### What is Expected?
Accordion keyboard navigation shouldn't depend on the elements 

### What is actually happening?
Accordions won't open via keyboard interaction

**Comment by janschoenherr** [comment]
The reproduction link does not seem to work for me.

**Comment by andy-blum** [comment]
https://codepen.io/andy-blum/pen/KKPybjg

**Comment by janschoenherr** [comment]
Unfortunately the codepens no longer work. If the issue persist, please update the codepen.
