### ISSUE TITLE
CDN link returning  404

### ISSUE THREAD

**Issue by george-assan** [uikit/uikit#3966]
CDN CSS links returned
https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/css/uikit.min.css
...
404 Not Found

**Comment by janschoenherr** [comment]
Yeah, lately it takes them a while to update.

**Comment by george-assan** [comment]
Oh ok thanks @janschoenherr . Just went ahead to download the resources

**Comment by george-assan** [comment]
The UI kit site itself is very slow...
they maded need to check out whats going on with their servers'

**Comment by andy-blum** [comment]
@janschoenherr is there any specific benefit or partnership with cdnjs? Is there a reason not to use jsdelivr?

**Comment by janschoenherr** [comment]
@andy-blum No, that might indeed be easier.

**Comment by janschoenherr** [comment]
Let's continue here: https://github.com/uikit/uikit/issues/2678
