### ISSUE TITLE
Scrollspy (with option repeat) chrashes browser

### ISSUE THREAD

**Issue by yazzbe** [uikit/uikit#3972]
### UIkit version
3.2.0 (>3.1.6)

### Browser
Chrome (v76) (also tested in firefox) on Mac and PC.

### Scrollspy without repeat - OK
On a page with uk-scrollspy without the option repeat:true on sections.
You can scroll the page up and down multiple times, using the browser scrollbar. No problem.

### Scrollspy with repeat - Crashes browser!
On a page that uses uk-scrollspy with the option: repeat:true on sections.
https://codepen.io/yazzy008/pen/yLBKbZg

If you scroll the page up and down multiple times, by clicking and dragging the browsers scrollbar, then scroll all the way up and down a few times ... the browser crashes.

This problem occurs since uikit 3.1.6

**Comment by yazzbe** [comment]
Work around; 
Adding option delay to uk-scrollspy  with repeagt, prevents the browser from crashing.
http://www.artmania.net/test-uikit3-tris.html

**Comment by zzseba78** [comment]
Confirmed ☝️

**Comment by zzseba78** [comment]
This issue will be fixed soon? Is crashing several websites that has this feature

**Comment by janschoenherr** [comment]
Resolved with bf2d7d7a06de8e2d0ae62eda6b1a5d3e71c3d5f6
