### ISSUE TITLE
Is getuikit.net is yours?

### ISSUE THREAD

**Issue by meceway** [uikit/uikit#3979]
the website: getuikit.net is yours?

http://www.getuikit.net/v3/docs
this page can not view. for a long time

**Comment by meceway** [comment]
true link is http://getuikit.net/v3/docs/introduction

**Comment by AlekVolsk** [comment]
this is a chinese craft, someone "sculpted" for his

**Comment by lupuxyz** [comment]
我的站，V3 文档没空翻译了，你们直接看英文官方站就是了，开个网页翻译就行。

**Comment by lupuxyz** [comment]
@meceway http://www.getuikit.net/v3 全部v3文档已完成翻译，需要的话可以随时查阅，目前还有不足的地方，欢迎从中文网首页加QQ群反馈。

**Comment by janschoenherr** [comment]
That page does not belong to us.
