### ISSUE TITLE
Problem with submenu an dropdown

### ISSUE THREAD

**Issue by ThomasKresnicka** [uikit/uikit#398]
I have a navbar with a submenu with "uk-parent" and on the side I have also a drop down box. 

When I open the drop down, it automatically opens the submenu.

**Comment by Uranbold** [comment]
Hello,

Same issue.

How do i insert the Main Menu (Dropdown + Dropdown)

I mean I want to insert Dropdown menu inside the one more Dropdown?

How do i do that?

**Comment by Uranbold** [comment]
https://ibb.co/fV0RAa
