### ISSUE TITLE
how can i make "slider" or "slidershow" scroll vertically

### ISSUE THREAD

**Issue by rewalax** [uikit/uikit#3982]
how can i make a "slider" or "slidershow" scroll vertically?
I dont find it in the doc, hope for your answer,thank you.

**Comment by rewalax** [comment]
anyone can help me? thx very much

**Comment by Jdeboysere** [comment]
I asked for this a year ago. They told me "lol, if you want a vertical scroll, script it yourself or go on google, but Uikit will not add it". So it will maybe exist in Uikit 4 or maybe never.

**Comment by rewalax** [comment]
> I asked for this a year ago. They told me "lol, if you want a vertical scroll, script it yourself or go on google, but Uikit will not add it". So it will maybe exist in Uikit 4 or maybe never.

that's so sad,i just dont understand why they dont add this feature?
