### ISSUE TITLE
Break long text in dropdown

### ISSUE THREAD

**Issue by sylvaincaillot** [uikit/uikit#3985]
Use the latest version Uikit 3, I am trying to break long text in my dropdown.
Here an example: [https://codepen.io/springrider77/pen/qBWLWYv](https://codepen.io/springrider77/pen/qBWLWYv).
I tried several css trickssuch as overflow-wrap or word-break but had no success. 
Your feedback would be really useful.

Thank you
S.

**Comment by flihub** [comment]
.uk-dropdown-nav class has "white-space: nowrap"


add 

.uk-dropdown-nav {
  white-space: normal;
}
