### ISSUE TITLE
uk-img doesn't support multiple image types in background

### ISSUE THREAD

**Issue by JeremieD** [uikit/uikit#3989]
### UIkit version
3.2.0

### Browser
Firefox, Safari, Chrome.

### Reproduction Link
https://codepen.io/jeremied/pen/dybrKQq

### Steps to reproduce
Use the `uk-img` attribute on a tag like `a` to put images in the background based on the `data-src` or `data-srcset` attributes. If you put more than one image format in the data-srcset, UIKit will always pick the first one.

### What is Expected?
If I were to put the same `srcset `attribute on an `img `tag, I would expect the browser to pick the format it prefers automatically.

### What is actually happening?
UIKit doesn't reimplement the format choosing behaviour, so it picks the first one in the list.

This looks like a deliberate choice to not reimplement all the browser preferences. I just think it would be an amazing feature to have. If not then maybe just specifying it in the doc would be nice. (I could do that)

Thanks

**Comment by janschoenherr** [comment]
There is a new `sources` option: https://getuikit.com/docs/image#picture-sources
