### ISSUE TITLE
uk-sticky does not calculate correctly with uk-img

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3993]
I've posted this issue a few times and the issue gets closed without the issue being fixed.

### UIkit version

3.2.1

### Browser
Chrome / Firefox

### Reproduction Link
https://www.brent2020.co.uk/programmes/a-mile-long-street-party/

### Steps to reproduce
1. Click reproduction link
2. Does not always happen, refresh a few times
3. You'll see the sticky sidebar calculates incorrectly it will overlap the image and not finish where it needs too.

### What is Expected?
It should recalculate, uk-img is causing reflow (which it shouldn't)

### What is actually happening?
uk-sticky is being calulcated incorrectly because of uk-img.

**Comment by janschoenherr** [comment]
The top value is calculated before the above image has a height. The sticky component has currently no way of determining that its top offset has changed.

Does the issue persist, if you do not load UIkit deferred?

**Comment by TomS-** [comment]
That does seem to make it load more consistantly, though I prefer not to have render blocking js.

**Comment by janschoenherr** [comment]
This will be fixed with the upcoming refactoring of the Image component.
