### ISSUE TITLE
[3.2.1] Incorrect documentation?

### ISSUE THREAD

**Issue by hrstoyanov** [uikit/uikit#4002]
The 3.2.1 Changelog states:
```Add selSlides option to Slider/Slideshow component```

.. but looking at the latest documentation for Slider/Slideshow there is no mention of such option?

**Comment by eladnova** [comment]
+1 Was just reporting the same thing

**Comment by janschoenherr** [comment]
It's not yet documented. In theory you can define a selector for the slides within the `.uk-slideshow-items` element. However you'll also have to update the css for this to work.
