### ISSUE TITLE
Custom Upload no longer works

### ISSUE THREAD

**Issue by pixelbart** [uikit/uikit#4004]
### UIkit version
tested on 3.2.1
runs on 3.1.X

### Browser
Firefox 70.0b14 (64-Bit)
Google Chrome 77.0.3865.90 (64-Bit)
MS Edge (latest; non chrome)

### Reproduction Link
Source: https://getuikit.com/docs/upload

### Steps to reproduce
Since the last update, the custom file upload no longer works.

### What is Expected?
The upload should take place. It also doesn't work anymore to show or hide the loading bar.

### What is actually happening?
I can't give you any debugging information, because the browser console doesn't throw anything either. The upload doesn't work anymore.

**Comment by joeyslack** [comment]
I cannot duplicate your issue. Works without flaw here.

Which extensions are you running? Try running it in incognito.
