### ISSUE TITLE
Lightbox no longer closing by clicking on the black background

### ISSUE THREAD

**Issue by q107** [uikit/uikit#4007]
Since 3.1.8 it is impossible to close Lightbox, by simply clicking anywhere on the black background.
I'm no expert. but version 3.1.8 introduced a fix which may be related to this issue:
> - Fix Modal close on bgClick behaviour

Or was this change intentional?

### Browser
Latest Firefox and Chromium based browsers

### Reproduction Link
https://getuikit.com/docs/lightbox#animations

### Steps to reproduce
1. Open Lightbox
2. Click anywhere on the black background surrounding the images

### What is Expected?
Be able to close Lightbox

### What is actually happening?
Nothing

**Comment by janschoenherr** [comment]
Thanks, should be fixed with d7a4acccddf7013015bf4e1450bd509673373319
