### ISSUE TITLE
Icons do not render when UIKit is loaded inside a Shadow Dom element.

### ISSUE THREAD

**Issue by hoIIer** [uikit/uikit#4008]
I'm loading UIKit inside of a shadow root node in my dom, and while it is loading UIKit, and `UIKitIcons.installed` is true, the icons do not render.

How can I render the icons inside a shadow dom root node/tree? Is it possible to rerun the icon initialization and explicitly pass it the html shadow dom element I want to parse for icons?

![image](https://user-images.githubusercontent.com/230757/66975731-3ba37d00-f054-11e9-80ae-e94855a2af3d.png)

(aqkit uses uikit)

**Comment by joeyslack** [comment]
There are a couple of out-dated uikit-react libraries that may do it, but I had to solve it with a custom solution. Alternatively, you can put the uikit-icons.js file in your public index.html and it will resolve icons in the shadowdom.

**Comment by KhardungLa** [comment]
@joeyslack How did you solve it in your custom solution?
