### ISSUE TITLE
uk-sticky="show-on-up: true" not responsive

### ISSUE THREAD

**Issue by Morrison52** [uikit/uikit#4009]
### UIkit version

3.2.1

### Browser
All

### Reproduction Link
https://jsfiddle.net/wzoxk93g/

### Steps to reproduce
Add uk-sticky="show-on-up: true" to navbar
Scoll down the page and up to trigger the navbar
Open inspector and close inspector
See the navbar not updating the width

### What is Expected?
Update the width value or remove the hardcoded width by js and have `width:100%` css

### What is actually happening?
The width of navbar doesn't update after closing the inspector

**Comment by janschoenherr** [comment]
This has been resolved.

**Comment by dvlpr91** [comment]
@janschoenherr resolved? not resolved on ^3.5.3 version.
