### ISSUE TITLE
UIKit 3.2.1/3.2.2 breaks the execution on Firefox because node is null

### ISSUE THREAD

**Issue by juanparati** [uikit/uikit#4015]
### UIkit 3.2.1 and 3.2.2

This bug was introduced in 3.2.1 and it's still present in 3.2.2.

It was tested with 3.2.0 and the bug is not present.

### Actual Behavior

The execution breaks due the following exception:

```
TypeError: node is null
    apply uikit.js:2897
    init uikit.js:2825
    runTasks uikit.js:2086
    flush uikit.js:2059
    scheduleFlush uikit.js:2078
```

The "apply" method:

```
 function apply(node, fn) {

            if (node.nodeType !== 1 || hasAttr(node, 'uk-no-boot')) {
                return;
            }

            fn(node);
            node = node.firstElementChild;
            while (node) {
                var next = node.nextElementSibling;
                apply(node, fn);
                node = next;
            }
        }
```

The execution breaks so execution thread is altered hereby the error described on https://github.com/uikit/uikit/issues/4013 matched with the described behaviour.

### Expected Behavior

UIKit is to run on Firefox 69.0.3 (on Mac OS Catalina) without raise any exceptions.

### Steps to reproduce

UIKit 3.2.1/3.2.2 is loaded using the following bootstrap:
```
/**
 * UIKit Loader
 */
window.UIkit = require("uikit");
window.Icons = require("uikit/dist/js/uikit-icons");

UIkit.use(window.Icons);
```

**Comment by janschoenherr** [comment]
Resolved with b844c38bd37903c02132fe4721483b1b0d9f315c

Please try the latest develop version from npm. Thanks.
