### ISSUE TITLE
Dropdown doesn't close, when Modal is created

### ISSUE THREAD

**Issue by spgonejoker** [uikit/uikit#4018]
### UIkit Version 
3.2.2

### Actual Behavior
If you click on a list entry (with an event listener, which creates a modal) in Dropdown, the DropDown doesn't close. 

### Expected Behavior
If a Modal is created, the Dropdown should be closed.

### Reproduction Link
https://codepen.io/spgonejoker/pen/abbLRRp

**Comment by Lumelomser** [comment]
In your example, try adding the class "uk-dropdown-close" to your "menu-option" list items.
