### ISSUE TITLE
TypeError: t is null in uikit.min.js:3:134205 - NOTHING WORKS AFTER

### ISSUE THREAD

**Issue by funkkyclouds** [uikit/uikit#4019]
Hello, i had i problem with the new uikit update V 3.2.2, when i implement the scripts as shown in the documentation it says TypeError: t is null in uikit.min.js:3:134205. i already found the solution, it will be really helpful if you can fix em in the online version because am using it instead of the local one.

_**Problem**_:
fresh installation of UIKit, showing TypeError: t is null. and then nothing works after (many similar cases in discord conversation).

_**Solution**_:
if you format the JS file, in the line 7 you should use ";" instad of ",".
Or add
`<script type="text/javascript">t = Object.prototype</script>` (For lazy peoples :) )

_**Screen shots**_:
_**Problem**_: 
**1-**
![image](https://user-images.githubusercontent.com/36214361/68078956-04b5c100-fde1-11e9-82fb-d2bcb8216f5e.png)
**2-** 
![image](https://user-images.githubusercontent.com/36214361/68078953-f23b8780-fde0-11e9-9223-1905ddd02643.png)

_**Solution**_
**1-** 
![image](https://user-images.githubusercontent.com/36214361/68078978-7db51880-fde1-11e9-93f3-606ccd8c9b2f.png)

**Comment by rauwebieten** [comment]
I have the same problem, but only in firefox

TypeError: node is nulluikit.js:2897:17
    apply https://cdn.jsdelivr.net/npm/uikit@3.2.2/dist/js/uikit.js:2897
    init https://cdn.jsdelivr.net/npm/uikit@3.2.2/dist/js/uikit.js:2825
    runTasks https://cdn.jsdelivr.net/npm/uikit@3.2.2/dist/js/uikit.js:2086
    flush https://cdn.jsdelivr.net/npm/uikit@3.2.2/dist/js/uikit.js:2059
    scheduleFlush https://cdn.jsdelivr.net/npm/uikit@3.2.2/dist/js/uikit.js:2078

**Comment by funkkyclouds** [comment]
Hello @rauwebieten i ve already solved the problem, check our the end of my first message its right there ...
