### ISSUE TITLE
Divider missing icon

### ISSUE THREAD

**Issue by gradec1999** [uikit/uikit#4022]
### UIkit Version
3.2.2

### Chrome Version
77.0.3865.120 (Official Build) (64-bit)

### Actual Behavior

Divider missing icon

![Capture 1](https://user-images.githubusercontent.com/10957637/68163767-8fbac680-ff5b-11e9-8328-0e3a9c9f316c.PNG)

![Capture 2](https://user-images.githubusercontent.com/10957637/68163789-96e1d480-ff5b-11e9-93c7-670de59f7bc0.PNG)

### Expected Behavior

Divider should have icon

### Steps to Reproduce the Problem

1. add `<div className="uk-divider-icon"></div>` (React.js)

**Comment by gradec1999** [comment]
Can I get some help for this problem? I'm on 3.30 now, but bug still exist.

**Comment by janschoenherr** [comment]
I believe your css isn't compiled correctly? Try using the default uikit.css.
