### ISSUE TITLE
uk-tab switch subsequent and multiple uk-switcher

### ISSUE THREAD

**Issue by rudolfgrauberger** [uikit/uikit#4028]
### UIkit Version

3.2.3

### Actual Behavior

If you have several tabs and switchers on one page, then all subsequent switchers change. And this although they all have different IDs. The previous uk-switcher do not change. It seems as if the ID set at 'connect' is not considered.

### Expected Behavior

Only the uk-switcher with the ID given in ui-tab 'connect' should change.

### Reproduction Link

jsfiddle
https://jsfiddle.net/ar68h4e3/2/

### Steps to Reproduce the Problem

1. Click on English or Deutsch tab (id: 1) -> The content of uk-switcher with id 1, 2 and 3 changed
2. Click on A or B tab (id: 2) -> The content of ui-switcher with id 2 and 3 changed
3. Click on X or Z tab (id: 3) -> The content of ui-switcher with id 3 changed

**Comment by viocassel** [comment]
Try this
```html
<!-- This is the tabbed navigation containing the toggling elements -->
<ul class="uk-tab" data-uk-tab="connect: #test-1">
    <li class="uk-active"><a href="">English</a></li>
    <li><a href="">Deutsch</a></li>
</ul>

<!-- This is the container of the content items -->
<ul id="test-1" class="uk-switcher uk-margin ">
    <li>Hello</li>
    <li>Hallo</li>
</ul>

<!-- This is the tabbed navigation containing the toggling elements -->
<ul class="uk-tab" data-uk-tab="connect: #test-2">
    <li><a href="">A</a></li>
    <li class="uk-active"><a href="">B</a></li>
</ul>

<!-- This is the container of the content items -->
<ul id="test-2" class="uk-switcher uk-margin">
    <li>ABCDEFGH</li>
    <li>BCDEFGHI</li>
</ul>

<!-- This is the tabbed navigation containing the toggling elements -->
<ul class="uk-tab" data-uk-tab="connect: #test-3">
    <li><a href="">X</a></li>
    <li class="uk-active"><a href="">Y</a></li>
</ul>

<!-- This is the container of the content items -->
<ul id="test-3" class="uk-switcher uk-margin">
    <li>XYZ</li>
    <li>YZ</li>
</ul>```

**Comment by rudolfgrauberger** [comment]
@viocassel Thank you very much. Your example works correctly.

I have taken the syntax with the {} around the `connect` from the documentation ([here](https://getuikit.com/v2/docs/switcher.html#switcher-with-tabs)). Then it is wrong in the documentation, or do I misunderstand the syntax?

**Comment by flihub** [comment]
you are using 3.2.3 but your documentation link is uikit v2:

v3 documentation: https://getuikit.com/docs/switcher

**Comment by rudolfgrauberger** [comment]
My fault. I'm sorry :see_no_evil:
