### ISSUE TITLE
UK Slider with uk-dotnav generates empty a tags

### ISSUE THREAD

**Issue by misterboe** [uikit/uikit#4032]
https://getuikit.com/docs/slider#navigation

`<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>`

As you can see in the CodePen from the example the uk-dotnav generates empty links without aria-label.  
This causes errors in Lighthouse Audit: Links do not have a discernible name

**Comment by joeyslack** [comment]
FYI: that codepen link isn't valid.

**Comment by misterboe** [comment]
Thanks for the Info

**Comment by janschoenherr** [comment]
Thanks, version 3.16.0 comes with built in accessibility.
