### ISSUE TITLE
How to listen to Sortable events in Angular?

### ISSUE THREAD

**Issue by directcuteo** [uikit/uikit#4038]
I have an Angular project and I configured UIkit as it is shown on this link: 
[https://stackoverflow.com/questions/41845812/angular-uikit-npm-installation](url)

Now I can see a modal on click. Good.
What I want to use from UIKit now is the Sortable. I have my simple sortable list configured in HTML using the attributes from the documentation:

`<div data-uk-sortable="group: SECTION">`
    `<div *ngFor="let section of sections; let i=index">`
         `I am section {{i}}`
    `</div>`
  `</div>`

Elements are being sorted using drag, but even if the view is updated, the JavaScript list named `sections` is never updated and it doesn't reflect the view anymore after a drag.

This JS moving operations should be made by myself on drop event? 
If yes, then how do I listen to that event using this Angular approach? What's the definition of these functions?
I tried something like this but it didn't work:
`UIkit.sortable( 'start', function (e) {
      console.log('Drag started');
    });`

**Comment by joeyslack** [comment]
You want:

```
UIkit.util.on('#my_dragable_element', 'show', function () {
    // do something
});
```

**Comment by directcuteo** [comment]
Not working.

**Comment by joeyslack** [comment]
If you can share a repository, would be easier to debug. No idea if your element is getting a proper ID, or if there are errors on the JS, etc etc

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
