### ISSUE TITLE
Responsive Widths broken when mixing uk-width-expand 

### ISSUE THREAD

**Issue by btknorr** [uikit/uikit#4039]
### UIkit Version

3.2.3

### Actual Behavior

I am trying to have an item be uk-width-expand when smaller than 640px and when over 640px to be uk-width-medium.  Setting "uk-width-expand uk-width-medium@s" doesn't work.  The uk-width-expand overrides the uk-width-medium with flex:1.

### Expected Behavior

uk-width-medium@s should display as uk-width-medium

### Reproduction Link

https://codepen.io/btknorr/pen/YzzJJrr

As you can see in the code pen the two examples should line up, but they don't.  Seems a below small responsive width is what is missing in uikit.  To cover all cases maybe even have something like -\*@\*-[below,up,only] where up is the default to be backwards compatible.

**Comment by joeyslack** [comment]
Hey.

Best way I can think of the top of my head is to use visibility filters with flex items:

```
<div class="uk-flex uk-margin-top">
  <div class="uk-flex-1">#</div>
  <div class="uk-flex-1">Name</div>
  <div class="uk-flex-1">State</div>
  <div class="uk-flex-1">Division</div>
  <div class="uk-flex-1 uk-hidden@s">Summary1</div>
  <div class="uk-width-medium uk-visible@s">Summary2</div>
</div>
```

**Comment by saschadube** [comment]
Thanks for reporting! Fixed with https://github.com/uikit/uikit/commit/c20ef70204d86bcdcc14a0aff93474e1a5368fd8
