### ISSUE TITLE
Tabs with dropdown nav bug if the content of the tabs are inputs linked to external js lib

### ISSUE THREAD

**Issue by abartier** [uikit/uikit#4044]
UIkit Version: 3.2.3

### Actual Behavior

Tab element with a dropdown at the end of the nav visible on @s only. 
If one of the tabs includes form content like inputs that are linked to some js (html editor, select2 .... ) on click inside on the input your tab content changed. You get a mix of the input with the content of the first tab. The class uk-active also changed at that point.

If you get rid of the dropdown the bug is gone.

Tested with Froala, select2 and flatpickr.

As mentioned on discord, is it uikit to blame ? Not 100% sure. 

### Expected Behavior

The nested dropdown should stay nested in the ul tag of the tab navigation. 
The content of the tab shouldn't display the content of tab 1 when clicking on inputs from the other tabs. 

### Reproduction Link

https://codepen.io/abartier/pen/dyywjxq?editors=1010

**Comment by janschoenherr** [comment]
Not sure what fixed this issue, but it seems to be resolved with latest version 3.3.3.
