### ISSUE TITLE
Slider - Content Parallax - Doesn't work on page load

### ISSUE THREAD

**Issue by FlinkQc** [uikit/uikit#4045]
### UIkit Version
3.2.3

### Actual Behavior
The parallax feature in the slider components of UIKit is actually not working. In page load, the components have the final value of the parallax but it should be the middle value. I try to put the middle value myself `data-uk-slider-parallax="x: 300,0,-300"` but it's the same result then `data-uk-slider-parallax="x: 300,-300"`

It's working fine after the slide change.

### Reproduction Link
It is also broken on the UIKit documentation for a better exemple : https://getuikit.com/docs/slider#content-parallax

**Comment by victor-gabou** [comment]
Some news about this issue?

**Comment by janschoenherr** [comment]
This will be fixed asap.

**Comment by FlinkQc** [comment]
I updated UiKit to 3.2.4 in my project and everything is working fine now, thank you @janschoenherr !
