### ISSUE TITLE
Switcher and tabs connected

### ISSUE THREAD

**Issue by f-r3d** [uikit/uikit#4049]
Hi' guys I've a problem migrating from 3.0.0 to 3.2.3 uikit version.
I use a tab component connected to a switcher component in this way:
```
UIkit.switcher('#ds-tabs', {
    connect: '#ds-content',
    toggle: '> li:not(.ds-no-switch)',
    active: 0
});

```
and then in HTML:
```
<div>
<ul id="ds-tabs" hidden="" class="uk-tab">
    <li class="ds-no-switch">Operation</li>
    <li>This must be active</li>
    <li>Second tab</li>
</ul>
</div>
...
<div>
<ul class="uk-switcher" id="ds-content">
    <li>Content of the first no "ds-no-switch" tab.</li>
    <li>Content of the second no "ds-no-switch" tab.</li>
</ul>
</div>
```
With version 3.0.0 "active: 0" is correctly the first tab with no "ds-no-switch" class (according to the "toggle" rules) and the first "li" inside the switcher is open.
Migrating to 3.2.3 the active tab is the first element without considering the "ds-no-switch" class.

It's a bug or something is changed?

**Comment by janschoenherr** [comment]
Resolved with c1d5720b01e735c17b5d1536856552f070040b60
