### ISSUE TITLE
Help: Notify Add-On to remember it is closed

### ISSUE THREAD

**Issue by Surbma** [uikit/uikit#405]
Hi,

I want to use the Notify Add-On to display an important message on my site on every page. But I want to set it to remember if once it is closed, so the notification won't show again to that user.

Is it possible? Can somebody show me how to do it? Thank you very much!

**Comment by GetYooWoo** [comment]
I have tried all thing above but my javascript knowledge is too bad so I couldn't get it to work.

I would love to have a few lines of javascript that will display the **Uikit 3 notification message** but (when clicked/closed) this message will never again appear for the same user unless the user refreshed browser cookies.

Anyone willing to paste the code below?

Many many thanks in advance.
