### ISSUE TITLE
two uk-sticky nav having conflict on mobile responsive 

### ISSUE THREAD

**Issue by incohe** [uikit/uikit#4054]
i have a 2 uk-sticky in my page when i make the screen smaller to the point of mobile nav is showing and going back to desktop view the width of the uk-sticky is the width of the container. This only happens when 2 or more uk-sticky exist in the page.

Thanks,

uikit v3.2.4

**Comment by incohe** [comment]
this has been resolve in uikit v3.2.6

**Comment by dvlpr91** [comment]
@incohe on ^3.5.3 version.

**Comment by dvlpr91** [comment]
I think the bug has been revived. Like a zombie.
