### ISSUE TITLE
sometimes Icons (svg) not showing/loading

### ISSUE THREAD

**Issue by cemfirat** [uikit/uikit#4060]
### Browser

Safari, Version 13.0.2 (14608.2.40.1.3)
OS: macOS Mojave, 10.14.6

### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.2.4

### Actual Behavior

*What happened? Screenshots please, if relevant!*
if you reload the page sometimes the icons are not displayed. The svg code is not generated / added. see image
![Screen Shot 2019-12-11 um 11 21 41](https://user-images.githubusercontent.com/5923877/70613339-bf1ebc00-1c08-11ea-8620-0096be6cb15f.jpg)

### Expected Behavior

*What should have happened?*

![Screen Shot 2019-12-11 um 11 25 29](https://user-images.githubusercontent.com/5923877/70613500-04db8480-1c09-11ea-9668-a215bef03364.jpg)

**Comment by FrantisekPostl** [comment]
I have same issue.

Browser: 70.0.3538.77
OS: 70.0.3538.77
UIKit version: 3.2.6

**Comment by 3eles** [comment]
Hi,

I'm having a similar issue. Most of the times SVG code is not generated / added to icons. As an example, please load https://www.altrinews.pt/ and check the footer icons. 

We're using UI Kit version 3.5.4, loaded from cdn.jsdelivr.net (as described in the installation section). We've tested in Chrome (Win + Mac), Safari, Firefox (Win + Mac), Edge (Mac). The only consistently showing icons is Safari on Mac. All the other browsers have the behavior.

**Comment by cemfirat** [comment]
I think I found the bug:
if you include the javascript file with '**async**' it happens that the icons are not always produced.

Without the **AsyncFunction**, I no longer have the problem.

**Comment by 3eles** [comment]
@cemfirat I're absolutely right. After removing the async parameter all icons load correctly again. Thank you for your time.
