### ISSUE TITLE
Accordion component triggers scroll on page load

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4061]
### UIkit Version

3.2.4

### Actual Behavior

On page load, the active accordion item is scrolled to.

### Expected Behavior

It shouldn't scroll on page load!

### Reproduction Link

https://getuikit.com/docs/accordion

When I go to this page I get scrolled down to #no-collapsing - Item 1 in preview.

**Comment by TrilipuT** [comment]
I have the same problem. How can I fix it if it's closed?

**Comment by chriswthomson** [comment]
Hi @TrilipuT - I suspect we'll get the fix in the next master release. In the meantime the fix is here: https://github.com/uikit/uikit/commit/94efa220e94a2bf542fa81e5241507be8a80a2c5
