### ISSUE TITLE
Scroll / Scroll down feature - "To top" Icon not working in MS EDGE

### ISSUE THREAD

**Issue by wcomgithub** [uikit/uikit#4063]
a href="#my-id" uk-scroll /a

Smooth scrolling NOT working in MS EDGE and IE 11 Browsers.
However working in FF, Chrome, Opera,...

Seems to be a bug with 3.2.4.?
UiKit 3.2.0 (on another Website however) working.
=> Also doc sample at
https://getuikit.com/docs/scroll
not working in the Microsoft Edge and IE 11
(Win 10 64-bit)

Unfortunately so far no reason/solution found.

**Comment by SuperKrevette** [comment]
Yes. Please fix that regression as soon as possible!
Temporary fix I have found: use the native scrollTo() with the polyfill (support for IE and Edge) from http://iamdustan.com/smoothscroll/.

**Comment by janschoenherr** [comment]
Fixed with 3.2.5
