### ISSUE TITLE
Nonexistence of removeChild property of eliminated element causes "TypeError: Cannot read property"

### ISSUE THREAD

**Issue by LaniJW** [uikit/uikit#4064]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.2.4

### Actual Behavior

If an alert component is closed before it's completely removed from the DOM it will produce a TypeError.

### Expected Behavior

The element should have been removed from the DOM quietly without raising any errors.

### Reproduction Link

[A minimal Codepen that can reproduce the bug.]( https://codepen.io/JulienW_/pen/wvBzoWN?editors=1010)

### Steps to Reproduce the Problem

1. Create an alert component in a page.
2. Close the alert component with the `uk-alert-close` link utility.
3. Remove the alert component from the DOM.

**Comment by janschoenherr** [comment]
The error is thrown because the element no longer has a parent. You need to check for `elem.parentNode` in your codepen.
