### ISSUE TITLE
beforescroll does not work

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#4065]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.2.4

### Actual Behavior

data-uk-scroll scrolls even if event "beforescroll" returns "false"

### Expected Behavior

do not scroll

### Steps to Reproduce the Problem

This code should prevent scrolling:
`UIkit.util.on(document, 'beforescroll', function(){
     return false;
});
`

Bit of you click on any link with a data-uk-scroll attribute, it scrolls nevertheless.

**Comment by janschoenherr** [comment]
You'll need to `preventDefault()`  the event. The docs will be fixed asap.

https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

**Comment by ikabod** [comment]
Thanks for your answer. This works, but now the scrolled event will also never fire:

`UIkit.util.on(document, 'scrolled', function(){ console.log('scrolled'); });`

**Comment by janschoenherr** [comment]
`scrolled` is only fired if you actually let the scroll happen
