### ISSUE TITLE
Nav dropdown does not hide after click on item

### ISSUE THREAD

**Issue by agreif** [uikit/uikit#4070]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.2.6

### Actual Behavior

in a nav with a dropdown after clicking on a dropdownitem the dropdown does not hide.
It only hides if I do an extraclick outside the dropdown area. This is a problem, because there other click sensitive stuff can be.

### Expected Behavior

As in former versions after clicking the menu item in the dropdown, the dropdown should hide.
in this version it still worked (dropdown disappearead after click): uikit-3.0.0-rc26

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

1. open https://getuikit.com/docs/nav#nav-in-navbar
2. in the 'preview' tab hover over 'parent'
3. the dropdown appears
4. click on any 'Item'
5. the dropdown does not hide ... thats the problem

**Comment by blakjak44** [comment]
I just realized noticed this behavior as well. The last version I used where the dropdown would hide on click is 3.1.6. 

It may have broken in version 3.2.4: "Fix show/hide behaviour in Drop component"

**Comment by janschoenherr** [comment]
If you want an empty link to "hide" the dropdown, you'll need to give it the `uk-navbar-dropdown-close' class. 

In UIkit 4 we will have to be more concise on what closes/hides things like Modals and Dropdowns.

**Comment by samsam1414** [comment]
Yeah. It is quite a bummer that clicking on a link inside a nav dropdown doesn't automatically close the dropdown :(
