### ISSUE TITLE
Slider/Slideshow get stuck on Chrome due to lack of 'pointerup' being fired

### ISSUE THREAD

**Issue by 64bits** [uikit/uikit#4071]
### UIkit Version
3.2.6

### Actual Behavior
The slideshow gets stuck halfway between elements, likely because Chrome is firing touchend and mouseup but not pointerup. This issue may or may not be related: https://stackoverflow.com/questions/52292780/pointerup-event-does-not-fire-for-mouse-actions-on-a-link-when-pointermove-has-b

### Expected Behavior
The transition should finish.

### Reproduction Link
I have no repro link, but I fixed it using the following code in React:
```
  useEffect(() => {
    const handleTouchEnd = () => {
      document.dispatchEvent(new Event('pointerup'));
    };
    document.addEventListener('touchend', handleTouchEnd, false);
    document.addEventListener('mouseup', handleTouchEnd, false);
    return () => {
      document.removeEventListener('touchend', handleTouchEnd);
      document.removeEventListener('mouseup', handleTouchEnd);
    }
  }, []);
```

### Steps to Reproduce the Problem

1. Open a slider/slideshow built in UIKit on Chrome (preferably with a scrollable element within)
2. Drag the slideshow to the left using a mouse stroke that is slightly to the left but mostly going downwards
3. Observe that the slideshow or slider will get stuck

**Comment by caki0915** [comment]
+1 for this one. It's almost unusable on Chrome for Mobile phones.

**Comment by janschoenherr** [comment]
This is probably resolved, if it still persists, please comment.
