### ISSUE TITLE
Wrong Tile padding documentation 

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#4077]
The Tile padding documentation is wrong. It refers to padding component instead of tile padding variables https://github.com/uikit/uikit/blob/develop/src/less/components/tile.less#L6-L10

```
// Modifiers:       `uk-tile-xsmall`
//                  `uk-tile-small`
//                  `uk-tile-large`
//                  `uk-tile-xlarge`
//                  `uk-tile-default`
```

**Comment by janschoenherr** [comment]
This seems to be resolved?

**Comment by gregBerthelot** [comment]
Hi @janschoenherr seems not. 

https://getuikit.com/docs/tile#tile-and-padding is using https://getuikit.com/docs/padding instead of uk-tile-* padding modifier
