### ISSUE TITLE
Drop regression in 3.2.4 continually fires events after clicking a menu item with Vue Router, freezing browser

### ISSUE THREAD

**Issue by timchambers** [uikit/uikit#4081]
### UIkit Version

Does not occur in 3.2.3
Does occur in 3.2.4
Does occur in current 3.2.6

### Actual Behavior

I have a uk-navbar, and when clicking on an item inside a dropdown to navigate to another page, it seems that it gets stuck in a loop of firing all the Drop events which freezes the browser. This is happening in a Vue SPA with Vue Router. The link is navigating to another route, and the page is set up so that the uk-navbar should be destroyed when navigating to the next route.

The reproduction case I've created is a @vue/cli created boilerplate using Vue Router, with the addition of a uk-navbar on the Home and About pages.

Note: If I moved the Navbar in to App.vue outside of the router-view slot so that it does not get destroyed between route changes, the bug does not happen, but in the setup I'm trying to build, the particular uk-navbar (and Drop components) are in parts of the view that will be destroyed between route changes.

### Expected Behavior

As in 3.2.3 and prior, the browser should not freeze when clicking on a menu item to navigate to a new route.

### Reproduction Link

https://sad-nightingale-d174a2.netlify.com/

Repo: https://github.com/timchambers/uikit-drop-bug-repro

### Steps to Reproduce the Problem

1. Hover over "Menu" at the top of the page
2. Click on "About"
3. Attempt to hover over Menu again (browser is unresponsive)

**Comment by janschoenherr** [comment]
This seems to be resolved with https://github.com/uikit/uikit/commit/70f94c06d0d0249e7504f28b89ab6d84a5f5495d

**Comment by timchambers** [comment]
Thanks, @janschoenherr !

**Comment by kingroho** [comment]
Hi @timchambers! How can I fix this? I'm using 3.2.6 and having the same issue on vue-router inside dropdowns.
