### ISSUE TITLE
Height match breaks wrapping left floating divs in IE 11

### ISSUE THREAD

**Issue by AndrewHoldaway** [uikit/uikit#4083]
I'm currently using UIKit's height matcher utility that matches all divs in a container to be the height of the maximum card. It works great except when using it in IE 11 with left floated elements with match all (row: false).

Since UIKit doesn't set the height of the base element (the one it's setting the height of all other elements to equal) IE 11 considers it to be (taller?) or something and causes the wrapped elements to be pushed across. Is there a way around this?
 
Would a pull request to have the base item also have its height set work or is the premise that UIKit would like to be able to handle the base element changing height and causing all the other element's heights too? Maybe an option?
here's a diagram of what I mean

![image](https://user-images.githubusercontent.com/33679961/72028421-90af0200-32d6-11ea-9002-f96d85c1182a.png)

UIKit does **not** set the height of the blue card since it's the tallest card in the set. Setting the height of the blue square manually to what uikit sets the heights of all other squares fixes the issue and allows the red card to slot back to the left where it should be.

Cheers

**Comment by janschoenherr** [comment]
We have dropped support for IE 11.
