### ISSUE TITLE
Lazy Images requested 2 times in chrome

### ISSUE THREAD

**Issue by cynegmbh** [uikit/uikit#4089]
### UIkit Version

3.3.0

### Actual Behavior

Lazy Images (with uk-img) are requested twice in google chrome on windows.

In my local sandbox, I can see that there are 2 request Initiators coming from UIkit.js

![image](https://user-images.githubusercontent.com/60259883/73070175-f4792380-3eaf-11ea-9e1b-6f57f4fd6cc5.png)

First Initiator is triggered here:
![image](https://user-images.githubusercontent.com/60259883/73070501-bd574200-3eb0-11ea-92fe-1ff88fc88165.png)

..and second one here:
![image](https://user-images.githubusercontent.com/60259883/73070557-e546a580-3eb0-11ea-9df0-9ba90e020b37.png)

### Expected Behavior

Lazy Image should only load 1 time

### Reproduction Link

https://jsfiddle.net/cynegmbh/zakhfg8j/2/

### Steps to Reproduce the Problem

1. Open Google Chrome browser in private mode
2. Open JSFiddle link from above
3. Open Developer-Tools
4. Slowly scroll down the page

**Comment by cynegmbh** [comment]
Update - seems that the deactivated cache (within developer tools) caused the double-requests.

With enabled cache in developer tools, the request ist only triggered once.

Sorry for that - bug can be closed

**Comment by thanos** [comment]
Why was this closed as I still see it in uikit@3.5.5 ?
