### ISSUE TITLE
performance issue uikit v3 and C3js 

### ISSUE THREAD

**Issue by viseth** [uikit/uikit#4090]
Hi !

### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.3.0

yes happening with the latest version 3.3.0

### Actual Behavior

*What happened? Screenshots please, if relevant!*
The console log of Chrome is cluttered with verbose message of this type:
**[Violation] 'focus' handler took 519ms c3.js:2311**
**[Violation] 'focus' handler took 537ms uikit.js:3658**
Which makes the navigation on the page very bad. The clicks responsiveness is totally bad at some point.
This makes Uikit and C3js usuable together.
It happen whether the C3js graph is opened in a modal widows or inside a page.

![image](https://user-images.githubusercontent.com/1708388/73091242-5058a200-3eda-11ea-8d1e-def3efbe74b1.png)

### Expected Behavior

*What should have happened?*
Not poor browsing experience

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*
JSfiddle: https://jsfiddle.net/Viseth7/ad19b7s6/10

### Steps to Reproduce the Problem

1. open the console.log
2. click on the icon at the top left corner
3. waiting for some time, the graph will show up at least... this should be quick and not taking that longs 7 sec...
3. move the subchart aera back and forth and navigate to another tab of your browser

Does anyone else experience the same ?
Please could you consider that bug ?
Thanks

**Comment by janschoenherr** [comment]
Running your codepen, I get a`(index):92 Uncaught ReferenceError: test is not defined` error.

**Comment by viseth** [comment]
Hi Jan,
@janschoenherr, please here's the codepen :
https://codepen.io/viseth-the-flexboxer/pen/jOERbqN

Thanks for having a look !

**Comment by janschoenherr** [comment]
The graph still does not show for me? Only when I switch Tabs? Anyway, removing the Modal.confirm seems to render the Graph immediately.

**Comment by viseth** [comment]
does it have to do with the chrome browser version as it does work on my side ?
I'm runing the lastest stable version one.

![image](https://user-images.githubusercontent.com/1708388/73171603-6c8a5800-4101-11ea-90a2-e1e9a1b83a4d.png)

Anyway I'll have a with the latest dev uikit version, thanks !

**Comment by viseth** [comment]
humm, I still have the issue with modal not rendering well. When I set to display the graph outside of a modal, it does display but after that all the interaction with any button is sluggish.
As long as I don't display the graph, interaction is fine. It looks like some C3.js is not working well with Uikit unfortunetly...

**Comment by janschoenherr** [comment]
I believe this issue is no longer related to UIkit (latest dev version) itself. Please comment if you think otherwise.
