### ISSUE TITLE
Sticky navbar is shown, but state is inactive

### ISSUE THREAD

**Issue by iam-peter** [uikit/uikit#4092]
### UIkit Version

latest version 3.3.0

### Actual Behavior

When scrolling all the way up, the sticky navbar is visible and its state is inactive.

### Expected Behavior

When scrolling all the way up, the sticky navbar should be visible and its state should be active.

### Reproduction Link

https://jsfiddle.net/iam_peter/8tvn4x2f/

### Steps to Reproduce the Problem

1. Scroll down
2. Scroll all the way up to the top

If it's not reproducible at first, try to scroll up faster.

**Comment by zzseba78** [comment]
Make sense to me... 

> Inactive: Fires after the element is no longer sticky.
When you reach the top again, the element is no longer sticky, it have his original positioning, uk-active class is removed, so state is `inactive`
