### ISSUE TITLE
Dokuwiki with css Uikit 3.x.x  

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#4096]
Hi, possible error???
configuring the dokuwiki (2018-04-22b "Greebo") template on uikit3
[https://www.dokuwiki.org/dokuwiki](https://www.dokuwiki.org/dokuwiki)
my config
- nginx 1.16.1
- PHP 7.3.13
- MariaDB 10.4.11

I get a css compilation error
`A fatal error occured during compilation of the CSS files. If you recently installed a new plugin or template it might be broken and you should try disabling it again. [parse error: failed at `--uk-leader-fill-content: .;`  in /lib/tpl/dokuwiki_ric/css/uikit.css at line 5891]'`

> :root {
>   --uk-leader-fill-content: .;
> }

if change to
> :root {
>   --uk-leader-fill-content: '.';
> }
there is no error

ps
this may not apply to uikit, I have no experience in css

**Comment by janschoenherr** [comment]
I believe this to be valid syntax, this most likely is not a UIkit bug.
