### ISSUE TITLE
uikit error: maximum recursion limit reached. Sporadic behavior 

### ISSUE THREAD

**Issue by kinnrot** [uikit/uikit#4097]
### UIkit Version
3.3.0

### Actual Behavior
While testing my app (manually and with ui automation) 
Sometimes, (didn't find a reproducible script) I get a 
uikit error: maximum recursion limit reached.

I have a uk-height-viewport="offset-top: true; offset-bottom:false;" which seem to be responsible for this issue

### Expected Behavior

No error is expected

### Reproduction Link

Sorry... Will try my best. Previus version I used was 3.2.0 didn't happen there.

### Logs

> application.js:57 
sockjs.js:1796 XHR finished loading: GET "http://localhost:3035/sockjs-node/info?t=1580393790508".
AbstractXHRObject._start @ sockjs.js:1796
(anonymous) @ sockjs.js:1672
setTimeout (async)
AbstractXHRObject @ sockjs.js:1671
XHRCorsObject @ sockjs.js:3212
InfoAjax @ sockjs.js:449
InfoReceiver._getReceiver @ sockjs.js:654
InfoReceiver.doXhr @ sockjs.js:672
(anonymous) @ sockjs.js:641
setTimeout (async)
InfoReceiver @ sockjs.js:640
SockJS @ sockjs.js:859
SockJSClient @ SockJSClient.js:106
initSocket @ socket.js:20
(anonymous) @ client:176
./node_modules/webpack-dev-server/client/index.js?http://localhost:3035 @ client:176
__webpack_require__ @ bootstrap:19
0 @ log.js:56
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
uikit.js:1827 Uncaught (in promise) Error: Maximum recursion limit reached.
    at scheduleFlush (uikit.js:1827)
    at flush (uikit.js:1816)
    at uikit.js:1830
scheduleFlush @ uikit.js:1827
flush @ uikit.js:1816
(anonymous) @ uikit.js:1830
Promise.then (async)
scheduleFlush @ uikit.js:1829
flush @ uikit.js:1816
(anonymous) @ uikit.js:1830
Promise.then (async)
scheduleFlush @ uikit.js:1829
flush @ uikit.js:1816
(anonymous) @ uikit.js:1830
Promise.then (async)
scheduleFlush @ uikit.js:1829
flush @ uikit.js:1816
(anonymous) @ uikit.js:1830
Promise.then (async)
scheduleFlush @ uikit.js:1829
flush @ uikit.js:1816
(anonymous) @ uikit.js:1834
requestAnimationFrame (async)
scheduleFlush @ uikit.js:1833
read @ uikit.js:1795
boot @ uikit.js:3344
(anonymous) @ uikit.js:10020
(anonymous) @ uikit.js:5
(anonymous) @ uikit.js:6
./node_modules/uikit/dist/js/uikit.js @ uikit.js:10027
__webpack_require__ @ bootstrap:19
(anonymous) @ il-es-fans-insights.png:1
./app/javascript/packs/application.js @ application.js:57
__webpack_require__ @ bootstrap:19
0 @ log.js:56
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
sockjs.js:1796 XHR finished loading: GET "http://localhost:3035/sockjs-node/info?t=1580393790840".
AbstractXHRObject._start @ sockjs.js:1796
(anonymous) @ sockjs.js:1672
setTimeout (async)
AbstractXHRObject @ sockjs.js:1671
XHRCorsObject @ sockjs.js:3212
InfoAjax @ sockjs.js:449
InfoReceiver._getReceiver @ sockjs.js:654
InfoReceiver.doXhr @ sockjs.js:672
(anonymous) @ sockjs.js:641
setTimeout (async)
InfoReceiver @ sockjs.js:640
SockJS @ sockjs.js:859
SockJSClient @ SockJSClient.js:106
initSocket @ socket.js:20
(anonymous) @ client:176
./node_modules/webpack-dev-server/client/index.js?http://localhost:3035 @ client:176
__webpack_require__ @ bootstrap:19
1 @ log.js:56
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
content.js:52 XHR finished loading: GET "chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/css/content.css".
(anonymous) @ content.js:52
(anonymous) @ content.js:112
e.exports @ content.js:112
Promise.then (async)
e.exports @ content.js:112
Promise.then (async)
c.request @ content.js:112
c.<computed> @ content.js:112
(anonymous) @ content.js:112
(anonymous) @ content.js:112
(anonymous) @ content.js:112
(anonymous) @ content.js:117
(anonymous) @ content.js:117
(anonymous) @ content.js:112
value @ content.js:112
value @ content.js:112
(anonymous) @ content.js:68
t.unstable_runWithPriority @ content.js:76
co @ content.js:68
Hu @ content.js:68
Pu @ content.js:68
as @ content.js:68
us @ content.js:68
(anonymous) @ content.js:68
Iu @ content.js:68
hs @ content.js:68
render @ content.js:68
(anonymous) @ content.js:134
c @ content.js:47
(anonymous) @ content.js:47
e.<computed> @ content.js:47
n @ content.js:1
u @ content.js:1
Promise.then (async)
n @ content.js:1
u @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:134
Promise.then (async)
(anonymous) @ content.js:134
n @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1

**Comment by janschoenherr** [comment]
It would be good to have a reproduction link. You could send one to me via Discord. The username is Jan#0565.

**Comment by kinnrot** [comment]
I think it was an issue with the webpack dev server.... stopped after restart

**Comment by HamedSalameh** [comment]
Facing the same issue again:
Unhandled Promise rejection: Maximum recursion limit reached. ; Zone: <root> ; Task: Promise.then ; Value: Error: Maximum recursion limit reached.
    at $i (uikit.min.js:3)
    at yi (uikit.min.js:3)
    at uikit.min.js:3
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at invokeTask (zone-evergreen.js:484) Error: Maximum recursion limit reached.
    at $i (http://localhost:4200/scripts.js:3:20818)
    at yi (http://localhost:4200/scripts.js:3:20738)
    at http://localhost:4200/scripts.js:3:20902
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:377:30)
    at Zone.run (http://localhost:4200/polyfills.js:136:47)
    at http://localhost:4200/polyfills.js:870:40
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:412:35)
    at Zone.runTask (http://localhost:4200/polyfills.js:180:51)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:582:39)
    at invokeTask (http://localhost:4200/polyfills.js:497:25)

Multiple time already.
