### ISSUE TITLE
Remove UIKit "uk" class prefix.

### ISSUE THREAD

**Issue by rakibwebdev** [uikit/uikit#4101]
UIKit was great library. But it is confusing when there is many "uk-" class prefix on code. Can it be removed. Removing this class will take UIKit a new level.

**Comment by SuperKrevette** [comment]
You can not be serious? Are you really a front-end developer?

**Comment by rakibwebdev** [comment]
In Bootstrap to create a primary button you write:
`<button class="btn btn-primary">Primary</button>`

But in UIKit you have to write:
`<button class="uk-button uk-button-primary">Primary</button>`

When you write many code lines using UIKit, everything will look messed up with "uk",

**Comment by lupuxyz** [comment]
This issue is really confusing.  Read the [doc](https://getuikit.com/docs/avoiding-conflicts) or use Bootstrap.

**Comment by RussW** [comment]
Seriously?
This is a framework identifier, specifically needed in mixed environments,
removing it would not only be pretty pointless but also cause multiple
problems across the board.

I bet you use browser-specific designations, such as -moz or -webkit in
your CSS?

--
Regards,
Russ Winter

**Comment by hismichael** [comment]
As I know both Bootstrap and Foundation are without prefix.
