### ISSUE TITLE
Lightbox Bug

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#4110]
https://getuikit.com/docs/lightbox

Lightbox does not open for the second time. 

### UIkit Version
3.3.1

**Comment by viocassel** [comment]
Confirm!

**Comment by papazetis** [comment]
#4103

**Comment by flihub** [comment]
fixed.

**Comment by andrispraulitis** [comment]
@flihub I'm on 3.3.6 and same issue, lightbox does open but will not load image for the second open..

**Comment by janschoenherr** [comment]
@andrispraulitis If you are seeing a similar issue, please post a reproduction link.
