### ISSUE TITLE
UIKit.notification won't work if container removed from page

### ISSUE THREAD

**Issue by kinnrot** [uikit/uikit#4112]
### UIkit Version

3.3.1

### Actual Behavior

When showing 1 notification, it's container reference is saved in 
>const containers = {};
hash.

If I have a script that replace entire page body (Like turbolinks)
And then I try to show the notification, the element reference is still hold on the containers hash, so no error, but notification won't be visible cause it's parent is not attached to the document.

### Expected Behavior

When element reference is hold, make sure it's still attached to document when trying to display a notification

### Reproduction Link

The following code will reproduce the errror
```
$(function(){
  UIkit.notification('- shown -');  
  setTimeout(function(){
    $('.uk-notification').remove();
    UIkit.notification('Not shown');    
  },1000)
  
});

```

**Comment by janschoenherr** [comment]
Does ea03beca6f8752a5631f1129eed76a5df506b5d3 solve your issue?

**Comment by kinnrot** [comment]
Looks like it will, if the $ method does not cache anything. is there any link to get a build with this commit so I can check ?

**Comment by janschoenherr** [comment]
Yes, you can get the latest dev version from npm or jsdelivr.

https://www.npmjs.com/package/uikit
https://www.jsdelivr.com/package/npm/uikit?version=3.3.3-dev.515061299

**Comment by kinnrot** [comment]
Fixed!
