### ISSUE TITLE
Accordion wont work when dynamically added with JS

### ISSUE THREAD

**Issue by tunapiq** [uikit/uikit#4113]
The new watch mechanism in v3.3.1 is breaking stuff.

When I add an empty accordion 'ul uk-accordion' to a page and try to add the 'li' dynamically with JS, the accordion script does not detect it unless I resize the window of the browser which somehow triggers the 'ul uk-accordion' to start acting like an accordion? (this used to work and still works in v3.3.0) 

I looked at the code for v3.3.1 and realized the way events are being handled for accordion was changed.

**Comment by janschoenherr** [comment]
This should be resolved in the latest dev version. If the issue persists, please comment.
