### ISSUE TITLE
Sticky bottom not working with parent div but working in child div

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#4115]
Please check my reproduction link so you understand all. Left example not working but with right example child div ID working fine.

### UIkit Version

3.3.1

### Actual Behavior

Parent div selector not working but when i set it with child div that working fine

### Expected Behavior

It should work with parent and child both div

### Reproduction Link

https://codepen.io/bdthemes/pen/GRJJBMV

**Comment by janschoenherr** [comment]
If bottom is an element, its bottom offset will be used.

The docs have been updated.
