### ISSUE TITLE
Breadcrumb does not work correctly with a long item

### ISSUE THREAD

**Issue by kos0760** [uikit/uikit#4116]
### UIkit Version

3.3.1

If the item is too long, it wraps to the next line and goes beyond the container
![1a](https://user-images.githubusercontent.com/25278076/74225450-c5deb380-4ccb-11ea-9070-f5efabd774a8.jpg)
It is solved if for example in css to register:
```
.uk-breadcrumb {
    display: block;
}
.uk-breadcrumb > * {
    display: inline;
}
.uk-breadcrumb > * > *{
    display: inline;
}
```

![2a](https://user-images.githubusercontent.com/25278076/74225688-3be31a80-4ccc-11ea-8c6e-e8569aa14334.jpg)

**Comment by janschoenherr** [comment]
Fixed with one of the latest versions.
