### ISSUE TITLE
RTL links have icons on the wrong side with no margin 

### ISSUE THREAD

**Issue by mokhosh** [uikit/uikit#4118]
### UIkit Version
3.3.1

### Actual Behavior
RTL links with icons have their Icons on the left side with no margin.
<img width="458" alt="Screen Shot 2020-02-12 at 4 09 06 PM" src="https://user-images.githubusercontent.com/6499685/74336004-b38b7500-4db2-11ea-85b6-3f7ba54b1e20.png">

### Expected Behavior
RTL links should have their icons on the right side (at the beginning of their text) with some margin.

### Steps to Reproduce the Problem

1. Setup RTL
2. Put something like `<a uk-icon="home" href="#">داشبورد</a>` in your page

**Comment by exwhyz** [comment]
Same issue observed with LTR text where the icon is appearing on the right side instead of left of text. Steps to reproduce:
`<a href="#" uk-icon="icon: database;">Database</a>`

**Comment by janschoenherr** [comment]
I think in cases like this it might be best to wrap the icon in a span.

    <a href><span uk-icon="home"></span> Home</a>
