### ISSUE TITLE
Lightbox - Issue

### ISSUE THREAD

**Issue by AntoninJarolim** [uikit/uikit#4120]
### UIkit and Browser Version
Tested on both Chrome and Opera and latest Uikit.

### Actual Behavior

I have a _little_ problem with lightbox. 
First time opening lightbox works fine, but when I reopen same lightbox, image does not appear.

I have to reaload page when I want to see image again.

This issue can be seen in the uikit documentation.
### Expected Behavior

*Possibility to reopen lightbox endlessly.*

### Reproduction Link

https://codepen.io/Fadolamxd/pen/mdJeQBv
https://getuikit.com/docs/lightbox

### Steps to Reproduce the Problem

1. Open Reproduction Link.
2. Click on 1. image.
3. Close the 1. image.
4. Click on 1. image again.
(5.) Reload page if want to see image again.

**Comment by carnevaledesign** [comment]
Same here with 3.3.1.  Went back to 3.3.0 where this issue does not appear to be.

**Comment by AntoninJarolim** [comment]
Thanks. On  3.3.0 works also for me. 
Leaving issue open because bug is not fixed.

**Comment by kevingrabher** [comment]
Same issue: #4103, #4110
