### ISSUE TITLE
Icons don't work with Livewire

### ISSUE THREAD

**Issue by mokhosh** [uikit/uikit#4124]
### UIkit Version
3.3.1

### Actual Behavior
Icons disappear after Livewire changes dom

### Expected Behavior
Since the documentation said UIkit monitors Dom changes and works with vue and react, I assumed it should work with Laravel Livewire as well.

### Steps to Reproduce the Problem
1. Create a simple livewire component
2. put a UIkit icon button inside it
3. set a property or something so that livewire makes a dom change

**Comment by arthurwhite** [comment]
As a temporary workaround, we can redraw icons.

In the Livewire's component view:

```html
<script>
    document.addEventListener("livewire:load", function () {
        window.livewire.hook('afterDomUpdate', function () {
            var iconEls = document.querySelectorAll('[uk-icon]');
            for (let i = 0; i < iconEls.length; i++) {
                var iconEl = iconEls[i];
                UIkit.icon(iconEl, {icon: iconEl.getAttribute('uk-icon')});
            }
        });
    });
</script>
```

**Comment by ollyollyollyltd** [comment]
The above workaround did not work for me (using Livewire 3.x).

I had to do this, in my main JS file:

```
Livewire.hook('morph.updated', ({el}) => {
    if (el.matches('[uk-icon]')) {
        UIkit.icon(el, {icon: el.getAttribute('uk-icon')});
    }
})

```

**Comment by schinckel** [comment]
Yeah, I hit the same problem when using idiomorph (via HTMX).

It seems that using `html.onLoad(...)` to fix the missing icons (which I did notice would appear when hiding/showing the inserted content because it was in an accordion).

I was able to get it to work with:

```javascript
document.body.addEventListener('htmx:beforeSwap', function(evt) {
  // Workaround UIkit's icon loading.
  evt.target.querySelectorAll('[uk-icon]').forEach(
    (element) => UIkit.icon(element, element.getAttribute('uk-icon'))
  );
});
```
