### ISSUE TITLE
yarn watch error

### ISSUE THREAD

**Issue by Bundara123** [uikit/uikit#4126]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.3.2

### Steps to Reproduce the Problem

1. I clone the project from the repository of uikit.
2. yarn install
3. yarn watch

![image](https://user-images.githubusercontent.com/13432086/74666802-bf24d480-51d4-11ea-8cfb-0b16e22f3f46.png)

**Comment by sahilNR** [comment]
@Bundara123 what is the error?

**Comment by Bundara123** [comment]
@sahilNR I clone project UIKIT to a custom theme. when I run yarn watch meet this error.
Have you been meeting this error?

**Comment by sahilNR** [comment]
@Bundara123 There is no error. That is just the log. Everything seems OK to me
