### ISSUE TITLE
Feature: Slideshow ratio: responsive

### ISSUE THREAD

**Issue by skerbis** [uikit/uikit#4127]
On mobile devices the slideshow has the same ratio as on desktop resolutions. 
It would be good to define the ratio by breakpoints. 

(or is it actually possible and i cannot find any information?)

**Comment by flihub** [comment]
with slider possible:

```html
<div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1" uk-slider>

    <ul class="uk-slider-items uk-child-width-1-1">
        <li>
            <div class="uk-cover-container">
              <canvas width="640" height="500" class="uk-hidden@m"></canvas>
              <canvas width="1280" height="720" class="uk-visible@m"></canvas>
              <img src="https://getuikit.com/docs/images/slider1.jpg" alt="" uk-cover>
            </div>            
        </li>
        <li>
            <div class="uk-cover-container">
              <canvas width="640" height="500" class="uk-hidden@m"></canvas>
              <canvas width="1280" height="720" class="uk-visible@m"></canvas>
              <img src="https://getuikit.com/docs/images/slider2.jpg" alt="" uk-cover>
            </div>            
        </li>
        <li>
            <div class="uk-cover-container">
              <canvas width="640" height="500" class="uk-hidden@m"></canvas>
              <canvas width="1280" height="720" class="uk-visible@m"></canvas>
              <img src="https://getuikit.com/docs/images/slider3.jpg" alt="" uk-cover>
            </div>            
        </li>
        <li>
            <div class="uk-cover-container">
              <canvas width="640" height="500" class="uk-hidden@m"></canvas>
              <canvas width="1280" height="720" class="uk-visible@m"></canvas>
              <img src="https://getuikit.com/docs/images/slider4.jpg" alt="" uk-cover>
            </div>            
        </li>
    </ul>

    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>

</div>
```

**Comment by skerbis** [comment]
Thanks @flihub for that. (excuse me for late answering) But when I use this solution its  only possible the slide animation

**Comment by skerbis** [comment]
this can help: 

```css
   @media (max-width: 960px) {     
    .uk-slideshow-items {
    min-height: 450px !important;
    font-size: 1rem;    
    }
```
to change the height of the items responsive

**Comment by Whizfactor** [comment]
Is there a more detailed documentation on how UIkit responsiveness works? Cause i can't seem to get a hang of it in anyway.

**Comment by Whizfactor** [comment]
Been battling with slide show controls, 

`
{# slideshow #}
<div>
    <div class="uk-container uk-position-relative uk-visible-toggle uk-light uk-margin-large-top" tabindex="-1" uk-slideshow="animation: fade; autoplay: true;">

    <ul class="uk-slideshow-items slide-show">
        <li>
            <div class="uk-overflow-hidden">
                <img src="{% static 'images/....webp' %}" alt="" uk-cover class="uk-animation-reverse uk-transform-origin-top-right" uk-scrollspy="cls: uk-animation-kenburns; repeat: true">   
            </div>
            
        </li>
        <li>
            <div class="uk-overflow-hidden">
                <img src="{% static 'images/....webp' %}" alt="" uk-cover class="uk-animation-reverse uk-transform-origin-top-right" uk-scrollspy="cls: uk-animation-kenburns; repeat: true">   
            </div>
            
        </li>
        <li>
            <div class="uk-overflow-hidden">
                <img src="{% static 'images/.....webp' %}" alt="" uk-cover class="uk-animation-reverse uk-transform-origin-top-right" uk-scrollspy="cls: uk-animation-kenburns; repeat: true">   
            </div>
            
        </li>
    </ul>

    {# mobile slide show controls #}
    <a class="uk-visible@s uk-position-center-left uk-position-small uk-hidden-hover" href uk-slideshow-item="previous">
        <span class="uk-align-center red-color " uk-icon="icon: chevron-left; ratio: 2;"></span>
    </a>
    <a class="uk-visible@s uk-position-center-right uk-position-small uk-hidden-hover" href uk-slideshow-item="next">
        <span class="uk-align-right red-color " uk-icon="icon: chevron-right; ratio: 2;"></span>
    </a>
    {# mobile slide show controls ends #}


    {# tablet slide show controls #}
    <a class="uk-hidden@m uk-position-center-left uk-position-small uk-hidden-hover" href uk-slideshow-item="previous">
        <span class="uk-align-right red-color " uk-icon="icon: chevron-left; ratio: 3;"></span>
    </a>
    <a class="uk-hidden@m uk-position-center-right uk-position-small uk-hidden-hover" href uk-slideshow-item="next">
        <span class="uk-align-left red-color " uk-icon="icon: chevron-right; ratio: 3;"></span>
    </a>
    {# tablet slide show controls ends #}


    {# large tablets slide show controls #}
    <a class="uk-visible@l uk-hidden@m uk-position-center-left uk-position-small uk-hidden-hover" href uk-slideshow-item="previous">
        <span class="uk-align-right red-color " uk-icon="icon: chevron-left; ratio: 4;"></span>
    </a>
    <a class="uk-visible@l uk-hidden@m uk-position-center-right uk-position-small uk-hidden-hover" href uk-slideshow-item="next">
        <span class="uk-align-left red-color " uk-icon="icon: chevron-right; ratio: 4;"></span>
    </a>
    {# large tablet slide show controls ends #}


    {# desktop slide show controls #}
    <a class="uk-visible@xl uk-position-center-left uk-position-small uk-hidden-hover" href uk-slideshow-item="previous">
        <span class="uk-align-right red-color " uk-icon="icon: chevron-left; ratio: 5;"></span>
    </a>
    <a class="uk-visible@xl uk-position-center-right uk-position-small uk-hidden-hover" href uk-slideshow-item="next">
        <span class="uk-align-left red-color " uk-icon="icon: chevron-right; ratio: 5;"></span>
    </a>
    {# desktop slide show controls ends #}
`

The above is just one of the experiments i stopped at after trying various things. I haven't looked into how your breakpoint works but when i tried using breakpoint instead of s, m, l i didn't get the desired results. How does the responsive work cause the visibility doc is nowhere near convincing.
