### ISSUE TITLE
uk-switcher toggle working not correctly

### ISSUE THREAD

**Issue by m49n** [uikit/uikit#4130]
1.uk-active class choosing not correctly  when use toggle in uk-switcher
https://codepen.io/m49nn/pen/PoqGbGP
uk-active must be on <a> tag in this example
![image](https://user-images.githubusercontent.com/15114737/74883202-7c542f80-5381-11ea-87b3-1246c62c58e7.png)
upd: it works in uikit.js UIkit 3.0.0-rc.26
upd 2.0. 
change 

in var uk-switcher methods
```
                removeClass(children, this.cls);
                addClass(active, this.cls);
                attr(this.toggles, 'aria-expanded', false);
                attr(toggle, 'aria-expanded', true);
```
to
```
                removeClass(this.toggles, this.cls);
                addClass(toggle, this.cls);
                attr(this.toggles, 'aria-expanded', false);
                attr(toggle, 'aria-expanded', true);
```
and all work fine

**Comment by janschoenherr** [comment]
This is currently intended behavior but will most likely be refactored with UIkit 4.
