### ISSUE TITLE
Navbar width in Edge between 3.1.5 and 3.3.2

### ISSUE THREAD

**Issue by sylvaincaillot** [uikit/uikit#4131]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.3.2

### Actual Behavior

In Edge, the menu items with several words are piled. It worked correctly with 3.1.5 which was my previous version.

### Expected Behavior

The menu should appear on one line.

### Reproduction Link

Version 3.3.2 which doesn't work: https://jsfiddle.net/vq7bz46f/6/
Version 3.1.5 which works: https://jsfiddle.net/uvq79x3t/2/

### Steps to Reproduce the Problem

1.Open Edge
2.Open the above links
3.Extend the results tile to see the full menu
4. You will see the composed menu items being piled in 3.3.2 while they are not in 3.1.5.

**Comment by sahilNR** [comment]
@sylvaincaillot I was unable to reproduce this issue. Which version of Edge are you using ? Are you on Windows or Mac ?

**Comment by sylvaincaillot** [comment]
Thank you @sahilNR. I am using Edge on Windows 10. I tried 3 different machines under Windows 10 and had the same issue with Edge after I switched to this new version of Uikit.

**Comment by sylvaincaillot** [comment]
Hi, 
I just try with the latest 3.3.7 version , and I still have the same issue with Edge. My menu items are pilled when the menu items contained several words.
Please see an example with the 3.3.7 version: [https://jsfiddle.net/zaqbyLpt/](https://jsfiddle.net/zaqbyLpt/)
