### ISSUE TITLE
Button group is not responsive

### ISSUE THREAD

**Issue by Flimm** [uikit/uikit#4134]
Take the example of the button group found [in the documentation](https://getuikit.com/docs/button):

```
<div>
    <div class="uk-button-group">
        <button class="uk-button uk-button-secondary">Button</button>
        <button class="uk-button uk-button-secondary">Button</button>
        <button class="uk-button uk-button-secondary">Button</button>
    </div>
</div>
```

Click "edit in codepen", and resize the window to simulate the small screen of a mobile device. You will notice that it simply cuts off later buttons.

I expected the buttons to shrink, or for the buttons to wrap into a new line.

**Comment by flihub** [comment]
add uk-flex-wrap.

`<div class='uk-button-group uk-flex-wrap'>`

**Comment by Flimm** [comment]
That is helpful @flihub , thank you.

**Comment by zzseba78** [comment]
@Flimm Check this way: https://codepen.io/zzseba78/pen/OJyMXPy
If it works for you, please close this issue 😉

**Comment by Flimm** [comment]
These solutions do work for me. I guess I was just surprised that the button group was not responsive by default.
