### ISSUE TITLE
Add a search bar in your documentation

### ISSUE THREAD

**Issue by SuperKrevette** [uikit/uikit#4136]
### Summary

*What feature are you requesting? What problem does it solve?*
A search bar for your documentation to find easily what we want.

### Priority

*On a scale of 1-5, how important is this feature to you? Please explain.*
6. Not need to explain how important is this feature.

**Comment by marchershey** [comment]
Still not added?

**Comment by SuperKrevette** [comment]
Nope... It's stunning.

**Comment by dustin555** [comment]
Priority: 6.
Has someone built a browser plugin or something to search documentation? I end up doing a site:getuikit.com parameter in Google, but you have to be careful not to accidentally click on the /v2/ documentation.

Please add a search feature to the documentation. Please.

**Comment by janschoenherr** [comment]
We are using Algolia now.
