### ISSUE TITLE
Toggle not working within Dropdown 

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4143]
### UIkit Version

3.3.1 and above

### Actual Behavior

Clicking on a uk-toggle button within a dropdown, that targets that dropdown, appears to toggle twice e.g. dropdown closes then opens again.

### Expected Behavior

Dropdown should close.

### Reproduction Link

3.3.0 works - https://codepen.io/chriswthomson/pen/XWbeVNz
3.3.1 does not - https://codepen.io/chriswthomson/pen/XWbeVzZ

(Has Dropdown > Child Has Dropdown > Back button)

**Comment by chriswthomson** [comment]
I think it is probably to do with nested dropdowns? The Close Menu button on the top-level dropdown works correctly.

I've also noticed that the 2nd-level dropdown in the pen (with the Back button), opens on click as it should, but is hidden if not active (no mouseover) which is more like the hover mode.

**Comment by janschoenherr** [comment]
Instead of giving the Back button a toggle component, you could add the class `uk-dropdown-close`.  Does that solve the issue?

**Comment by chriswthomson** [comment]
Hi, thanks yes it does.
