### ISSUE TITLE
Sortable performance

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4144]
I stumbled upon a performance issue related to the "Sortable"-Component.
When having a lot of sortable items within a page, the performance while dragging items is dropping.
I tested multiple browsers (see below) and the performance is dropping dramatically using Google Chrome.
The performance in Firefox is as expected, Safari is largely okay.
So, the issue may be Webkit/Blink related.

I also tried adding the "will-change"-Property to the list items, which doesn't result in any improvement.

`will-change: left, top, height, width;`

I created a CodePen, so you're able to test different quantities of lists and list items.

### UIkit Version
3.3.3

### Actual Behavior
When having a lot of sortable items, the performance while dragging items is dropping.

### Expected Behavior
Performance while dragging is acceptable, even if there are a lot of draggable items.

### Reproduction Link
https://codepen.io/lumelomser/full/VwLMEpv

### Steps to Reproduce the Problem
1. Open reproduction link
2. Drag items around

### Testet Browsers
Chrome (80.0.3987.132, macOS 10.12.6)
Firefox (73.0.1, macOS 10.12.6)
Safari (12.1.2, macOS 10.12.6)

**Comment by janschoenherr** [comment]
Thanks, resolved with bfb6a9360941addceb4c7cfb49dcff7764db4586
