### ISSUE TITLE
Yarn doesn't include latest files

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4145]
Hello

I installed UIKIt with both Yarn and Git.

When I compile it, I am getting different files.

I think Yarn version is not up-to-date

![image](https://user-images.githubusercontent.com/3592665/76071668-83d52480-5f8e-11ea-9008-309cc425be3d.png)

**Comment by janschoenherr** [comment]
Is this resolved?

**Comment by papazetis** [comment]
Yes it seems it is resolved!
