### ISSUE TITLE
Hiding a drop from JS takes a lot of time

### ISSUE THREAD

**Issue by SimonChaumet** [uikit/uikit#4147]
### UIkit Version
3.3.3

### Actual Behavior

When hiding a drop component from JavaScript code the drop takes a lot of time to hide (~2 seconds).

### Expected Behavior

The component should hide quickly.

(In my use case I open a modal from a dropdown, the modal is opened before the drop hides)

### Reproduction Link
https://codepen.io/scarex/pen/NWqXrPy

### Steps to Reproduce the Problem

1. Create a drop component from javascript
2. Call a function from a component inside this drop (others components could do the job maybe)
3. Inside this function call .hide()

**Comment by janschoenherr** [comment]
By default, it delays for 800ms. If you want to close immediately, call `hide(false)`. 

I have updated the docs, thanks. uikit/uikit-site@95d392625dcd903a928809e2b6b313c6887e6068
