### ISSUE TITLE
uk-grid dosn't observe their children dispaly change ?

### ISSUE THREAD

**Issue by dyingsunlight** [uikit/uikit#4148]
Seems `uk-grid` component are only listening to `resize` and `scroll` event to update their children grid class ( like `.uk-grid-margin.uk-first-column` ).  Which means the `uk-grid` component can't detect changes when turns an element from `display:none`  to `display:block`  during the runtime.

https://github.com/uikit/uikit/blob/eadd6210aac881cfb9975a0b81db5c2947b33bd1/src/js/core/grid.js#L134

Demo:
https://codepen.io/dyingsunlight/pen/LYVQNvK

Is this was a bug or intentionally designed like this behaviors ? 

Thanks

**Comment by janschoenherr** [comment]
Yes, UIkit does not detect attribute changes, except for new components being added.

You can always call `UIkit.update(element)` though.

https://getuikit.com/docs/javascript#programmatic-use
