### ISSUE TITLE
Cannot preventDefault () on uk-tooltip

### ISSUE THREAD

**Issue by tsurugi** [uikit/uikit#4149]
### UIkit Version
3.3.3

### Actual Behavior

uk-tooltip should be able to cancel by preventDefault() at the timing of beforeshow.

### Expected Behavior

Can't cancel.

But the code shown below seems to work. "Hello" is output to the console.

```js
UIkit.util.on(document, 'beforeshow', '.uk-tooltip.uk-active', function(e) {
  console.log("Hello")
  e.preventDefault()
});
```

### Reproduction Link

[https://codepen.io/jp_tsurugi/full/NWqyBZL](https://codepen.io/jp_tsurugi/full/NWqyBZL)

### Steps to Reproduce the Problem

1. Open reproduction link
2. hover over input.  
tooltip is displayed.
3. But scroll events can be canceled with a similar syntax.

Please attention to the Developer Console.

### Reference

- [Tooltip - UIKit](https://getuikit.com/docs/tooltip#javascript)

**Comment by janschoenherr** [comment]
Thanks, resolved with cc56231014cececd550f44a4510f8d89833cb621
