### ISSUE TITLE
Please delete @base-heading-color;

### ISSUE THREAD

**Issue by skerbis** [uikit/uikit#4150]
Our headings have different colors. Because of 
https://github.com/uikit/uikit/blob/73dd2a2ab18ce45d21321a53242559b2546b4df9/src/less/components/base.less#L355
i'm not able to define other colors to this styles. (or is there a way)
Trying to set it inherit doesn't help.

**Comment by Lumelomser** [comment]
Hi skerbis!

Just use hooks as explained here:
https://getuikit.com/docs/less#use-hooks
https://getuikit.com/docs/sass#use-hooks

**Example**
```
@mixin hook-base-h1() {
    color: #cc0000;
}

@mixin hook-base-h2() {
    color: #00cc00;
}

@mixin hook-base-h3() {
    color: #0000cc;
}
```

**Comment by skerbis** [comment]
thx
