### ISSUE TITLE
UIKit lazyloading features do not work with React 

### ISSUE THREAD

**Issue by samuelkarani** [uikit/uikit#4155]
Does lazy-loading and placeholder backgrounds work with React? I've tried using **uk-img** or **data-uk-img** with **src** or **data-src** and the lazy loading doesn't work

Heres a link: https://codesandbox.io/s/compassionate-sky-gor96

**Comment by janschoenherr** [comment]
The link seems to be broken

**Comment by samuelkarani** [comment]
Is it working now? Just tried in chrome Incognito

**Comment by janschoenherr** [comment]
Yes, the issue is, that you are rendering a "true" into the component's attribute. 

```data-uk-img="true"```

Try putting the data-src into the data-uk-img attribute.

**Comment by samuelkarani** [comment]
thanks so much!!
