### ISSUE TITLE
A blue layer will appear on the "uikit.min.js" file when used on a mobile phone page

### ISSUE THREAD

**Issue by iosmall** [uikit/uikit#4156]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.3.6

### Actual Behavior

*What happened? Screenshots please, if relevant!*

### Expected Behavior

*What should have happened?*

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

A blue layer will appear on the "uikit.min.js" file when used on a mobile phone page. Clicking anywhere on the mobile phone will cause a blue layer to appear! Similar to long press to copy the situation, it will affect the experience

![31d0df2b5efc8cdaf2bbcaf6ef11c7fd](https://user-images.githubusercontent.com/34939681/77012936-f17b4a80-69a9-11ea-9ab5-d170c084cadc.gif)

**Comment by zzseba78** [comment]
I don´t see this happens in any project using uikit, maybe you could bring more information, browser, os, live code to check, maybe it´s something you are doing wrong...
