### ISSUE TITLE
UIKit seems to be the bottleneck for my website

### ISSUE THREAD

**Issue by SweetJD** [uikit/uikit#4157]
I'm building my portfolio website with UIKit, and according to Chrome Dev Tools, UIKit's CSS and JS files are mostly unused, but are the major reason my website is slowing down. It can take past ten seconds at times. Is there something I can do to speed this up? Am I doing something wrong here?

I am also using Packery.js and Isotope.js, which don't seem to be creating issues but I'm not the most savvy with code.

<img width="1290" alt="Screen Shot 2020-03-19 at 11 57 37 AM" src="https://user-images.githubusercontent.com/5109705/77104372-2a7ee380-69d9-11ea-83fe-3f946f5da8b4.png">

**Comment by hotmango** [comment]
if you look at your source code you'll find that you are loading uikit.min.css twice and that some of your JS like jquery or typekit could be loaded at the bottom of the page or deferred and if you then also look at a "waterfall" of your pageload you might find that the largest blocking items, as would be expected, are images.

As for the usage of the uikit css, well unless you are ustilising every single feature of uikit layouts, then this is going to differ from page to page and is very unlikely to have a huge utilisation anyway. This is always a slight downside to using a pre-packaged framework against purely having CSS that matches only the features being used.

**Comment by SweetJD** [comment]
I will check that out. Thanks for the heads up!

**Comment by BernhardBaumrock** [comment]
@SweetJD can you please close this issue?

**Comment by thetestcoder** [comment]
still same issue, Uikit js taking alot time to evaluate
