### ISSUE TITLE
uk-scrollspy-nav triggering not right

### ISSUE THREAD

**Issue by neeltjechanterie** [uikit/uikit#4159]
Hi,

Scrollspy-nav is still nog working right.
When clicking on the nav item, it highlights the nav item before the clicked one.
Version: 3.3.7

**Comment by zzseba78** [comment]
☝️Confirmed in Firefox  , works fine on Chrome and Safari ( all latest - MacOS Catalina ).
Reproduction: https://getuikit.com/assets/uikit/tests/scrollspy.html
Screenvideo: https://byhumans.works/area/test/screen.mp4

**Comment by zzseba78** [comment]
Amazing, thanks!
