### ISSUE TITLE
Issue with uk-sortable (screencast)

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4161]
Thx for creating this awesome framework! I've been using it for years now and it's absolutely great! Could you please have a look to fix this bug which is quite important for a now project:

### Actual Behavior

Items with a larger height than the one dragged are jumping around like crazy. Items with the same height work as expected:

![sortablebug](https://user-images.githubusercontent.com/8488586/77518712-871d4b00-6e7e-11ea-8902-e48a9f3ff84d.gif)

### Reproduction Link

https://codepen.io/baumrock/pen/rNVqRON

**Comment by BernhardBaumrock** [comment]
@janschoenherr thx for adding support for uk-sortable on table rows so quickly :) Is there any estimate for fixing this issue? Just curious! Thx in advance.

**Comment by janschoenherr** [comment]
Sorry, no. We are aware of it though.

**Comment by BernhardBaumrock** [comment]
@janschoenherr ok thx for letting me know :) FYI just realized that increasing the animation duration helps a little while not completely solving the issue!

**Comment by Lumelomser** [comment]
Maybe it would be possible to check if the user has changed the direction his cursor/pointer is moving to?
So, if the item "Active" has already been initiated to move to its new position and the user is still moving the "Item" (red border) in the same direction as before, don't try to apply a new positions to item "Active".
