### ISSUE TITLE
Problem with uk-width-expand and uk-width-auto

### ISSUE THREAD

**Issue by JeromeDeBoysere** [uikit/uikit#4162]
Hello,

I think I found a problem in UIkit 3.3.7 (and probably all the versions) when I use with uk-width-expand in combination with uk-width-auto.

**Example inside a grid:**
```
<div uk-grid>
...
<div class="uk-width-expand uk-width-auto@m">Lorem ipsum</div>
</div>
```

As you know, uk-width-expand applies the styles flex: 1. But if I want to use uk-width-auto@m (in this case) with .uk-width-expand, I think that the flex: 1 should become flex: none if the screen is larger than @m.

**Current styles applies (copied from the devtools in Chrome):**
```
@media (min-width: 960px)
   .uk-width-auto\@m {
       width: auto;
   }
.uk-width-expand {
    flex: 1;
    min-width: 1px;
}
```

**Basic example of fix (only tested for my case)**
```

.uk-width-expand {
    flex: 1;
    min-width: 1px;
    @media (min-width: 960px)
        .uk-width-auto\@m {
           flex: none;
           width: auto;
       }
}
```

**Screenshots:**
Current render on screens larger than @m: https://ibb.co/61w0tsC
Current render on screens smaller than @m: https://ibb.co/HG77TK6
What it should look like on screens larger than @m: https://ibb.co/bbP3nht
What it should look like on screens smaller than @m: https://ibb.co/HG77TK6 (does not change)

**Live example:**
https://codepen.io/jdeboysere/pen/NWqeGzE

**Comment by zzseba78** [comment]
Yes, this happen since uikit 3 release, check this issue:
https://github.com/uikit/uikit/issues/2858

**Comment by saschadube** [comment]
The combination of expand classes of lower breakpoints with auto classes of higher breakpoints will be fixed in the next release.

**Comment by JeromeDeBoysere** [comment]
Hello,

I just received notification of this ticket and wanted to share how I felt...

I'm glad the fix is finally here... but in all honesty, it makes me sick to see that it took 4 years to fix this... This is clearly not normal. Tracking problems or suggestions is so slow that I've moved on to another framework. As a front-end developer, it's unacceptable to wait that long.... In 4 years, the web has evolved insanely, and support for this kind of patch should go much faster.

I've received several notifications on the same day about reported bugs or suggestions that have been pending for 4-5 years (or more) and will be implemented in the next update. What's going on? Is a revolution underway?

**Comment by saschadube** [comment]
Thanks for reporting! Fixed with https://github.com/uikit/uikit/commit/c20ef70204d86bcdcc14a0aff93474e1a5368fd8
