### ISSUE TITLE
uk-sortable not working on table rows?

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4163]
Please see this pen and try to sort the table rows: https://codepen.io/baumrock/pen/NWqJGaw

![image](https://user-images.githubusercontent.com/8488586/78031151-6dd73b80-7363-11ea-90e1-2030bcddd023.png)

Is sortable not intended to work on table rows? This would be a huge drawback!

Thx in advance!

**Comment by janschoenherr** [comment]
This will work with the next dev release. Make sure to put the uk-sortable component on the `<tbody>` tag.

**Comment by BernhardBaumrock** [comment]
This is great news, thank you very much @janschoenherr  👍 :)
