### ISSUE TITLE
Toggle/Switcher components in offcanvas trigger offcanvas Events

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#4165]
### UIkit Version
3.3.7

### Reproduction Link
https://codepen.io/flihub/pen/dyoLZNE

**Comment by janschoenherr** [comment]
What's the bug here?

**Comment by flihub** [comment]
open offcanvas and click tabs, offcanvas "hide" event trigger on tabs change.

**Comment by janschoenherr** [comment]
You'll have to check for the event target, or specifically listen for the event on the offcanvas only.
```
UIkit.util.on('#offcanvas', 'hide', function () {
	console.log("test")
}, {self: true});
```

**Comment by flihub** [comment]
why not documented?

also not here: https://github.com/uikit/uikit-site/blob/feature/js-utils/docs/pages/javascript-utilities.md
