### ISSUE TITLE
uk-tab is not working

### ISSUE THREAD

**Issue by STsaruk** [uikit/uikit#4166]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.3.7

### Actual Behavior

When you click on the tab - nothing happens.

### Reproduction Link
https://getuikit.com/assets/uikit/tests/tab.html

### Steps to Reproduce the Problem

1. Click to tab

**Comment by janschoenherr** [comment]
The tabs test are css only. No Javascript components are used here.

See the switcher tests: https://getuikit.com/assets/uikit/tests/switcher.html
