### ISSUE TITLE
Hi all, How to vertical center modal via call UIkit.modal.alert?

### ISSUE THREAD

**Issue by jodeca** [uikit/uikit#4172]
UIkit.modal.alert('UIkit alert!').

Thanks

**Comment by flihub** [comment]
`const modal = UIkit.modal.alert('UIkit alert!').dialog;
const el = modal.$el;
el.querySelector('.uk-modal-dialog').classList.add('uk-margin-auto-vertical');`

or one line:
`UIkit.modal.alert('UIkit alert!').dialog.$el.querySelector('.uk-modal-dialog').classList.add('uk-margin-auto-vertical');`

**Comment by jodeca** [comment]
thank you very much
