### ISSUE TITLE
unable to apply uk-sortable options via javascript

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4173]
### UIkit Version

3.4.0

### Actual Behavior

Please see this pen: https://codepen.io/baumrock/pen/abvbGWE

While the duration setting is applied correctly, the `cls-custom` setting is not applied! Via html attributes it works properly, but I'm using uk-sortable from JavaScript and need to set the custom class there.

**Comment by janschoenherr** [comment]
The option names must be in their camelCased representation.

https://getuikit.com/docs/javascript#programmatic-use

**Comment by BernhardBaumrock** [comment]
Sorry for that! Thx @janschoenherr
