### ISSUE TITLE
Modal - Prevent close outside

### ISSUE THREAD

**Issue by ShiruJan** [uikit/uikit#4174]
Hi,
i have some problems with the modal, How can I prevent all modal from closing when clicking outside the same modal?

An apology if this is an inappropriate question.
Thank you.

**Comment by janschoenherr** [comment]
You can set `bg-close` to `false`.

See https://getuikit.com/docs/modal

**Comment by fab6696** [comment]
> 

With bg-close="false", for example <div id="MyModal" uk-modal bg-close="false">
Documentation: https://getuikit.com/docs/modal
