### ISSUE TITLE
Invalid class behavior Margin

### ISSUE THREAD

**Issue by definer** [uikit/uikit#4175]
https://github.com/uikit/uikit/blob/b2142046eec0b16a85a0442fd220fdf8e4d8f53d/src/scss/components/margin.scss#L39

Hi, I came across this line, is this the correct behavior? And shouldn't it look like this:

.uk-margin { margin: $margin-margin; }

**Comment by janschoenherr** [comment]
That is intended, please see https://getuikit.com/docs/margin#usage
