### ISSUE TITLE
Modal component, Lightbox component and Youtube video

### ISSUE THREAD

**Issue by SuperKrevette** [uikit/uikit#4177]
Hi,

The Youtube video in your modal component is larger than the window. Can you fix that ?
Bug visible directly in your documentation: https://getuikit.com/docs/modal#media

Moreover, why there are 2 ways to open media (video, youtube, media) : lightbox and modal ? This is really confusing. And they have different appareance, why?!  The lightbox component shows a black overlay. The modal component shows a transparent overlay. The modal component also shows a smaller video player than the lightbox component. And why the vimeo video are not 1920x1080 like Youtube in both components?

**Comment by janschoenherr** [comment]
Thanks, the docs have been updated.
