### ISSUE TITLE
Question: uk-height-match attribute

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4179]
I don't know if it's a bug or you don't support it but I am trying to add several classes on uk-height-match like this
```uk-height-match="target: > div > .uk-card > .thumbnail, > div > .uk-card > .title, > div > .uk-card > .excerpt"```

It seems it's working but the height on `.title` class is big enough

![image](https://user-images.githubusercontent.com/3592665/79332042-0cdb6600-7f14-11ea-84c4-ef6fdd8e26b6.png)

**Comment by janschoenherr** [comment]
Yes, that should work. Please add a reproduction link if it does not.
