### ISSUE TITLE
Link Button With Icon - Icon will disappear if button in table

### ISSUE THREAD

**Issue by eSilverStrike** [uikit/uikit#4182]
### UIkit Version
3.4.1

### Actual Behavior
When you put a link button that has an icon in a table with more than 1 column the icon is not visible.

Example link button with icon:
```
<a class="uk-button uk-button-danger uk-button-small">
<span uk-icon="icon: trash"></span></a>
```

### Expected Behavior
A white Icon should be visible in a red button.

### Reproduction Link
https://codepen.io/esilverstrike/pen/XWmdRJm

### Steps to Reproduce the Problem

See codepen for examples of the issue and how to reproduce

**Comment by Lumelomser** [comment]
Hey @eSilverStrike !

Try adding `uk-preserve-width` to the parent `td` or the `a`-Button itself.

**Comment by eSilverStrike** [comment]
Thanks that worked. I missed that class when I reviewed everything on the UiKit website.

When I first converted the theme to use Uikit 3 (back when the version was new) everything worked so I assumed something under the hood must have changed since to require that particular class.

**Comment by zzseba78** [comment]
@eSilverStrike If you figure it out, please close this issue 😉

**Comment by eSilverStrike** [comment]
Didn't know if I was suppose to or not. Maybe the docs should mention icons specifically as well when referring to uk-preserve-width.
