### ISSUE TITLE
small icon for uk-search-large

### ISSUE THREAD

**Issue by Notebit** [uikit/uikit#4184]
uk-search-large sets the size of the search input to a larger size but the icon is small.
https://getuikit.com/docs/search#large-modifier
I kind of remember it was 40px before but now it is a standard 20px.
I know I can resize it by css, but if it is a bug, I would prefer to get a bugfix instead adding 1 css rule

**Comment by zzseba78** [comment]
Change the icon size with ratio, as always:
`<span uk-search-icon="ratio: 1.5"></span>`
If solve your problem, please close this issue.

**Comment by Notebit** [comment]
hi Seba, nice to read you and thanks for all your help on uikit channels.
I am almost sure it is not a matter of ratio, but there is some bug related to **uk-search-large**. If I follow your suggestion and  add ratio: 1 to <span uk-search-icon=""></span> **with code inspector**, I get the correct size of 40by40, but ratio 1 should be the standard ratio, so why that icon goes at 20by20. 
Same if I replace uk-search-icon with data-uk-search-icon with code inspector.
It seems like the javascript still sets that icon to 40by40 by default (which matches the uk-search-large) but it is not able to set it to 40by40 when the page is first loaded
I am doing my experiments directly on https://getuikit.com/docs/search#large-modifier
