### ISSUE TITLE
Precision Firefox 75.0 (64) dropbar more...

### ISSUE THREAD

**Issue by delry** [uikit/uikit#4188]
Uikit Documentation page freezes
![uikit-dropbar-firefox](https://user-images.githubusercontent.com/64007492/79965050-d65d9800-848b-11ea-9e3c-616b21f198ff.png)
 after a little time playing with nav menu in dropbar example. I do a proper new install of Firefox, same thing ...

JS console displays :

Script terminated by timeout at:
e@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:37097
toggleElement/<@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:37210
toggleElement@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:37047
i@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:46431
hide@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:46753
show@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:46243
handler@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:44452
h@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:7308
h@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:7441
Kt/<@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:8231
Kt@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:8198
toggle@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:87068
handler@https://getuikit.com/assets/uikit/dist/js/uikit.min.js?1287:3:86469

**Comment by delry** [comment]
OK,
On Trend Micro i have to disable "Virus & Spyware Controls" then I can't reproduce. But i saw you comment your code line 1287, perhaps in some contexts this seems to be problematic. Maybe there are improvements to be made, I don't know. Thanks for your help.

**Comment by janschoenherr** [comment]
Sorry, this does not seem to be an issue with UIkit itself.
