### ISSUE TITLE
Don't override CSS outline property to none

### ISSUE THREAD

**Issue by jesscee** [uikit/uikit#4191]
### Summary

*What feature are you requesting? What problem does it solve?*
There is a specific override of the browser default for all buttons to have the outline removed on focus:

/* Focus */
.uk-button:focus {
    outline: none;
}

This makes a website extremely difficult to navigate for keyboard users - they have no idea if the button is focused. A subtle background/text colour change isn't good enough. 

### Priority

*On a scale of 1-5, how important is this feature to you? Please explain.*
5. If you are supplying a framework for people to use in web development, it is your responsibility to make this framework inclusive and accessible.

**Comment by dougfelton** [comment]
100% agree

**Comment by janschoenherr** [comment]
We now use `:focus-visible` to highlight keyboard navigation.
