### ISSUE TITLE
Firefox navbar-dropbar true - page freezes

### ISSUE THREAD

**Issue by delry** [uikit/uikit#4193]
Same bug as the one you closed
When you use Navbar with dropbar attribute set tu true,
on your documentation page, if you hover over a few seconds the menu with Firefox 75 (64) w10 (tested on 2 different PCs with w10 up to date, with and without antivirus), Firefox quantum 68.7.0 Debian.
https://getuikit.com/docs/navbar#dropbar
Easy to verify and reproduce....

**Comment by delry** [comment]
Trying to reproduce with browserstack : same bug . After a little time playing with the navbar /dropbar example on your documentation page, the page freezes.
![bug-dropbar](https://user-images.githubusercontent.com/64007492/81497030-16aa7c00-92bc-11ea-955e-4bc4812238ff.png)

**Comment by VEDA95** [comment]
I'm having a similar issue to this in Google Chrome. Everytime I click on a dropdown button after running a http request the whole page freezes.

**Comment by delry** [comment]
it's a pretty severe bug since it crashes the browser.
It just means that a site developed with this framework, in the current version, is not viewable on Firefox.
 Firefox's market share is not that of chrome OK. I would still like to have some visibility on this bug. I guess the fix must involve a real refactoring work.

**Comment by janschoenherr** [comment]
I can reproduce the issue. I am working on a fix.

**Comment by VEDA95** [comment]
@delry Wasn't making it about marketshares but OK. My point was that this issue is severe enough that it effects more than one browser. Haven't seen whether this issue also affects opera or safari, but I imagine it would if it's already affecting chrome and firefox

**Comment by delry** [comment]
I can't reproduce exactly the same with Chrome, but in console script seems to take too much time. However, Chrome doesn't crash. It has to handle this better than Firefox...
