### ISSUE TITLE
ik-hidden@s not correct act

### ISSUE THREAD

**Issue by hamzehparsi** [uikit/uikit#4195]
i use uk-hidden@s for hidden element in mobile but his class is not correct acting

<div class="uk-flex-between" uk-grid>
            <div class="uk-width-1-6 uk-alert uk-alert-success">logo</div>
            <div class="uk-width-1-6 uk-hidden@s">menu</div>
            <div class="uk-width-1-6">user</div>
</div>

**Comment by zzseba78** [comment]
@hamzehparsi Can you create a reproduction codepen?
