### ISSUE TITLE
Wrong positioning on Masonry Grid (3.4.4)

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4197]
### UIkit Version

3.4.4

### Actual Behavior

![Captura de Pantalla 2020-05-08 a la(s) 12 28 17](https://user-images.githubusercontent.com/5558563/81421179-6c99eb00-9127-11ea-892c-33723b65011d.png)

![Captura de Pantalla 2020-05-08 a la(s) 12 24 23](https://user-images.githubusercontent.com/5558563/81421312-ad91ff80-9127-11ea-8ce0-91c2fca267ae.png)

### Expected Behavior

Correct positioning

### Reproduction Link

You can see it in the docs also:
https://getuikit.com/docs/filter

Confirmed in Firefox, Chrome and Safari.

### Steps to Reproduce the Problem

Enter the docs for example.

**Comment by janschoenherr** [comment]
Please check again, this was a bug in 3.4.3 and should actually be fixed in 3.4.4

**Comment by zzseba78** [comment]
Chrome:
![Captura de Pantalla 2020-05-08 a la(s) 13 01 40](https://user-images.githubusercontent.com/5558563/81424360-33b04500-912c-11ea-8b70-f9b845d348f8.png)

Firefox:
![Captura de Pantalla 2020-05-08 a la(s) 13 02 04](https://user-images.githubusercontent.com/5558563/81424375-390d8f80-912c-11ea-9078-794c27faba8c.png)

Safari:
![Captura de Pantalla 2020-05-08 a la(s) 13 02 25](https://user-images.githubusercontent.com/5558563/81424383-3dd24380-912c-11ea-93b0-cd621bb74d4d.png)

**Comment by zzseba78** [comment]
I create a codepen with same docs code, works fine in all browsers.
https://codepen.io/zzseba78/pen/MWaVzgx
