### ISSUE TITLE
Window and Document not found during Server Side Rendering

### ISSUE THREAD

**Issue by isabellachen** [uikit/uikit#4198]
Hi! Am using UIKit with Gatsby.

In development, everything runs fine, but I can't do a build because there are some checks missing.

in `uikit/dist/js/uikit.js`, at line 406 there is the code for global Document Touch. 
It expects window and document to be defined, but they are not available at build time.

```js
var isIE = /msie|trident/i.test(window.navigator.userAgent);
    var isRtl = attr(document.documentElement, 'dir') === 'rtl';

    var hasTouchEvents = 'ontouchstart' in window;
    var hasPointerEvents = window.PointerEvent;
    var hasTouch = hasTouchEvents
        || window.DocumentTouch && document instanceof DocumentTouch
        || navigator.maxTouchPoints; // IE >=11

```

Maybe something like this to do the checks?

```js
    var isIE = typeof window !== `undefined` ? /msie|trident/i.test(window.navigator.userAgent) : false;
    var isRtl = typeof document !== `undefined` ? (document.documentElement, 'dir') === 'rtl' : false;

    var hasTouchEvents = 'ontouchstart' in window;
    var hasPointerEvents = window.PointerEvent;

    if (typeof window !== `undefined` && typeof document !== `undefined`) {
      var hasTouch = hasTouchEvents
        || window.DocumentTouch && document instanceof DocumentTouch
        || navigator.maxTouchPoints; // IE >=11
    } else {
      var hasTouch = false;
    }
```
### UIkit Version
Using 3.4.4

**Comment by janschoenherr** [comment]
Did you try the suggested solution here: https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

We'd have to change quite many code occurrences for this to work.

**Comment by isabellachen** [comment]
@janschoenherr  Yes I did. My app is building fine now, thanks for getting back to me.

**Comment by isabellachen** [comment]
@janschoenherr It does result in some strange behaviour relating to the sticky navbar though. In the dev environment the navbar is working fine, but in prod, something in the nav bar is causing the content to disappear after load. 

When I removed lines 6 & 7, I can go to a page via url (e.g. https://isachen.com/portfolio) and everything works fine. But with those lines, when I go to a page via url the content appears for a split second and then disappears. This only happens in prod and with the navbar. (The js for the parallax is working just fine)

```jsx
  1 const Navigation = ({ location }) => {
  2   const currentPath = (location && location.pathname) || ""
  3   return (
  4     <nav
  5       className="uk-navbar-container"
  6       uk-sticky="show-on-up: true; animation: uk-animation-slide-top; bottom: #bottom"
  7       uk-navbar
  8     >
  9       <div className="uk-navbar-center">
 10         <ul className="uk-navbar-nav">
 11           <li className={`${currentPath === "/blog" ? "uk-active" : ""}`}>
 12             <Link to="/blog">blog</Link>
 13           </li>
 14           <li className={`${currentPath === "/portfolio" ? "uk-active" : "    "}`}>
 15             <Link to="/portfolio">portfolio</Link>
 16           </li>
 17         </ul>
 18       </div>
 19     </nav>
 20   )
 21 }
```

**Comment by janschoenherr** [comment]
Could you setup a test page, where we can inspect the issue? Thanks.

**Comment by isabellachen** [comment]
Ok, I'll set up a test page with the Gatsby Starter :) Thanks for getting back

**Comment by isabellachen** [comment]
@janschoenherr You can check it out here: https://pensive-bhabha-d018c3.netlify.app/

- On load, there is not content on the homepage (or content loads and then disappears). 
- When click on page-2 and then click on the Gatsby Default Starter title to get back to the home page, you see there is content there. 
- When refreshing the homepage, the same disappearing content behaviour happens again.

It was the same behaviour as my website. When I removed the uikit sticky nav bar, I did not have this problem anymore. 

You can check out the github repo for this example here: https://github.com/isabellachen/my-gatsby-uikit

Thanks for getting back to me! I hope this helps you solve the issue :)

**Comment by janschoenherr** [comment]
If you place a `<div class="uk-sticky-placeholder"></div>` right after the sticky navbar, does that solve the issue?

**Comment by isabellachen** [comment]
It does, but there's some UI janking when the page loads:

![uikit](https://user-images.githubusercontent.com/9280665/81944801-89d62a00-95fd-11ea-81c4-38c8f81c501f.gif)

**Comment by janschoenherr** [comment]
Yes, the CSS is lazy loaded. You'd have to inline it or prevent lazy loading the css all together.
