### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by joyouscob** [uikit/uikit#42]
It wuld be good if your documentation is revisited...a step by step on to how to build a simple uikit template (at least just a basis)....was stress trying to understand where to start...thanks

**Comment by naasking** [comment]
Actually I too would like to know what versions of jquery are supported. It seems this still isn't documented anywhere. For instance, when I create a new project in my usual web framework, it automatically includes jquery 1.10.2, but I don't know if UI kit actually supports that version, or needs jquery 2 or later.
