### ISSUE TITLE
move away from jQuery?

### ISSUE THREAD

**Issue by trymeouteh** [uikit/uikit#4201]
Will UIKit move away from jQuery? I know it is useful but I think it is better if UIKit had no dependencies and JavaScript has come a long ways, making it so jQuery is not needed for developing JS quickly.

Or even to have UIKit not require jQuery and have a optional jQuery integration JS script to allow people to use jQuery with UIKit if they wish.

**Comment by aarongerig** [comment]
The dependency to jQuery has been removed already.
