### ISSUE TITLE
Question about uk-visible@*

### ISSUE THREAD

**Issue by ayhid** [uikit/uikit#4207]
I have hard time understanding the `uk-visible@*` classes. For example if I use `uk-visible@s` on some element I am expecting this element to be visible on small devices only, instead it is hidden.
Can someone explain me how is these classes should be used ? It's a bit confusing

**Comment by SuperKrevette** [comment]
It does work like this! With Uikit, @s means "from small". So uk-visible@s means visible on small (s), medium (m), large (l) and xlarge (xl) device.

It's the same as all other components. Responsive first.

**Comment by ayhid** [comment]
@SuperKrevette thanks for your reply, understood so in order to have something visible only on  small device i'ave added the `uk-hidden@m` class. 
it's still confusing though.
