### ISSUE TITLE
Nested lists regression?

### ISSUE THREAD

**Issue by david-fanin** [uikit/uikit#4213]
### UIkit Version

3.5.3

### Actual Behavior

The nested lists are at the same level.
![Capture d’écran 2020-05-29 à 17 34 03](https://user-images.githubusercontent.com/9631150/83277853-f4c55a80-a1d2-11ea-924f-8c28665b1101.png)

### Expected Behavior

Margin left for nested lists.
![Capture d’écran 2020-05-29 à 17 33 38](https://user-images.githubusercontent.com/9631150/83277885-ff7fef80-a1d2-11ea-95be-643de716c4a1.png)

### My simplified code
```
<ul class="tree uk-list">
	<li class="node">
		TEST

		<ul class="tree uk-list">
			<li class="node">
				TEST 2
    			</li>
		</ul>
	</li>
</ul>
```

The following code disappeared between version 3.4.4 and the latest version :
```
/*
 * Nested lists
 */

.uk-list ul {
  margin: 0;
  padding-left: 30px;
  list-style: none;
}
```

Is it a regression?

**Comment by janschoenherr** [comment]
Yes, that was intentional as the previous selector was way too unspecific.
