### ISSUE TITLE
scroll up sticky

### ISSUE THREAD

**Issue by dvlpr91** [uikit/uikit#4219]
1. set scroll up sticky
2. window size down
3. scroll down, scroll up
4. window size up

sticky navbar is broken.

**Comment by dvlpr91** [comment]
version: 3.5.3

**Comment by dvlpr91** [comment]
without custom styile. (ex: width: 100%)

**Comment by dvlpr91** [comment]
Even, you can see it here. https://getuikit.com/docs/sticky#sticky-on-scroll-up

**Comment by janschoenherr** [comment]
This seems to be resolved?
