### ISSUE TITLE
Autoscroll to Accordion after click

### ISSUE THREAD

**Issue by demlak** [uikit/uikit#4230]
Hey.. since i don't know, if this is already possible or not, just a feature request:

It would be nice to autoscroll to accoirdion after it opens. 

thx a lot

**Comment by fromCharCode-git** [comment]
I also think this is missing feature aspecially on longer content or accordion close to the bottom of the page this feature is needed.

**Comment by janschoenherr** [comment]
This has been added quite some time ago.

**Comment by keev-studio** [comment]
Hi, sorry to reopen this but I dont see it working in official website codepen.
This codepen 
https://codepen.io/keev/pen/bGMvWMr
is included in UiKit page https://getuikit.com/docs/accordion , I just added more items so accordeon fill whole page.
If you click on the last item (by the end of the screen) the accordion item opens but do not scroll to the opened item content. 
Am I missing something?
