### ISSUE TITLE
modals don't seem to be modal

### ISSUE THREAD

**Issue by mehgcap** [uikit/uikit#4231]
### UIkit Version
3.5

### Actual Behavior
When a modal dialog is rendered, a dialog appears, as expected. However, the user can tab, arrow, or mouse out of it and interact with the page content behind the dialog without the dialog closing. This isn't the user clicking outside the inner div to close the dialog, it's regular interaction with background content while the dialog is still on the screen.

### Expected Behavior
My understanding of modal dialogs, compared to non-modal dialogs, is that modals should never allow this interaction. After all, if something went wrong, the user shouldn't be able to carry on doing what they were doing, or re-submit the same data, etc.

### Reproduction Link
https://codepen.io/Ramwoods/pen/jOWBoQR

### Steps to Reproduce the Problem

1. Paste the below HTML into a basic page that also includes UIKit.
2. You'll want a bit of JS to enable the dialog. We use Jquery, but you don't have to, I shouldn't think. Wherever you do it, call
```
UIkit.modal("#error-dialog").toggle();
```
3. Here's the HTML for the actual dialog:

```
<div class='uk-modal-container' id='error-dialog' uk-modal>
<div class='uk-modal-dialog'>
<div class='uk-modal-dialog-header'>Server Error</div>
<p>{$message}</p>
</div>
<button class='uk-modal-close uk-close' uk-toggle='target: #error-dialog' type='button'>Dismiss</button>
</div>
```

**Comment by janschoenherr** [comment]
Please check out the latest dev release https://www.npmjs.com/package/uikit/v/3.14.4-dev.838f092aa
