### ISSUE TITLE
Sortable issue when used with Highcharts (it somehow blocks the chart interactions)

### ISSUE THREAD

**Issue by m-ahmadi** [uikit/uikit#4233]
### UIkit Version
3.5.4

### Actual Behavior
When using the `Sortable` component with `Highcharts` library, the chart does not respond to any interactions on it.

### Expected Behavior
The `Highchart` should not have been unresponsive.
### Reproduction Link

https://jsfiddle.net/m_ahmadi/hd7p1g25/
### Steps to Reproduce the Problem

1. Try to interact with the chart that is inside the Sortable.

**Comment by janschoenherr** [comment]
This is caused by `.uk-sortable svg { pointer-events: none; } `. 

As a quick workaround add `.uk-sortable svg { pointer-events: auto; } 

We'll check if this rule is still needed.
