### ISSUE TITLE
how to prevent scoll component from closing dropdown component?  

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#4242]
### UIkit Version

3.5.4

### Expected Behavior

When I click on an anchor link in a dropdown, the link uses `Scroll` to scroll to the link, and the dropdown stays open.  

### Actual Behavior

When I click on an anchor link in a dropdown, and it scrolls to the link, the dropdown closes.  

### Reproduction Link

https://codepen.io/oshihirii/pen/oNbqReW

### Steps to Reproduce the Problem

1.  Go to codepen
2.  Click on button
3.  Click on anchor link (the dropdown will hide, and then i am programmatically showing it again)
4. (I want the dropdown not to hide in the first place)  

**Edits:**  

_Edit 1:_  

I have tried `e.stopPropagation()` on click event, as suggested in answer below, but it didn't work:

https://github.com/uikit/uikit/issues/2843  

_Edit 2:_

The code below gets the desired behaviour *except* the dropdown does not close when clicking *off* the dropdown afterwards. 
 
You have to click on the button to close the dropdown.  

It's like there is some sort of 'internal state' registered that prevents the click from closing the dropdown.  

```js
$(document).on("click","ol li a", function(e) {
  $(".my_dropdown").toggleClass("uk-open"); 
  $("button").attr("aria-expanded","true");  
}); 
```

**Comment by janschoenherr** [comment]
This is more difficult than it should be:

```
UIkit.util.on('body', 'beforescroll', '.uk-dropdown', function () {
    UIkit.util.once('body', 'beforehide', '.uk-dropdown', function (e) {
        e.preventDefault()
    });
}, true);
```
