### ISSUE TITLE
DatePicker does not work with MacOS Catalina/Safari

### ISSUE THREAD

**Issue by rmiklautz** [uikit/uikit#4243]
### UIkit Version

3.5.4

### Actual Behavior

Datepicker icon does not appear when using Safari on macOS resp. it is not possible to pick a date

![datepicker](https://user-images.githubusercontent.com/8298223/87302228-49b5f980-c511-11ea-9642-5db03d62e4ef.png)

### Expected Behavior

Overlay for datepicker should appear in order to select a date

![datepicker-correct](https://user-images.githubusercontent.com/8298223/87302412-a5808280-c511-11ea-8af1-f0e83a98940c.png)

### Reproduction Link

https://getuikit.com/assets/uikit/tests/form.html

### Steps to Reproduce the Problem

1. Go to Form - Uikit Test page with Safari running on latest macOS
2. Try to click on Date form on the right section
3. Works fine with Chrome, etc.

**Comment by Lumelomser** [comment]
This isn't UIkit related.

Safari on macOS doesn't support a native date-picker at all, see:
https://caniuse.com/#feat=input-datetime

So, please close this issue.

**Comment by rmiklautz** [comment]
Thank you for that hint!
