### ISSUE TITLE
UIkit.util.on() gets unexpected event

### ISSUE THREAD

**Issue by tsurugi** [uikit/uikit#4244]
### UIkit Version

3.5.5

### Actual Behavior

The following code should get an event about uk-modal.

```
UIkit.util.on(document, "beforeshow", ".uk-modal", function (e) {
  // do anything
}
```

But in reality, it also captures non uk-modal events that are children of uk-modal.

For example, the event of uk-accordion in uk-modal is also acquired.

This happened with the accordion, but not when the tooltip was hidden. Event behavior is inconsistent and it seems strange to fire beforehide in uk-accordion.

### Expected Behavior

I don't think this should get any event other than uk-modal.

### Reproduction Link

[https://codepen.io/jp_tsurugi/pen/KKVxZJa](https://codepen.io/jp_tsurugi/pen/KKVxZJa)

### Steps to Reproduce the Problem

1.  Click the button to see the modal
2. Expand the accordion
3. Event fired when a modal is hidden. Pay attention to the console.

**Comment by janschoenherr** [comment]
You'll have to check for the event target.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture
