### ISSUE TITLE
Wrong display of ul nested in uk-list.

### ISSUE THREAD

**Issue by tsurugi** [uikit/uikit#4245]
### UIkit Version

3.5.5

NOTE: *This issue does not occur in 3.5.4.*

### Actual Behavior
"item 1" has two dots (like Infiniti).

```
<ul class="uk-list">
  <li>item list</li>
  <ul>
    <li>item1</li>
    <li>item2</li>
    <li>item3</li>
  </ul>
</ul>
```

### Expected Behavior

Only one dot should be displayed for item 1.

The above code will give different results in v3.5.5 and v3.5.4.

But I couldn't find such a change in the release notes.

### Reproduction Link

[https://codepen.io/jp_tsurugi/pen/vYLzreO](https://codepen.io/jp_tsurugi/pen/vYLzreO)

### Reference image
![uikit_ul](https://user-images.githubusercontent.com/32333468/87520111-77d83c80-c6bd-11ea-8f65-7d33e1a10d97.png)

**Comment by viocassel** [comment]
```
<ul class="uk-list">
  <li>item list
    <ul>
      <li>item1</li>
      <li>item2</li>
      <li>item3</li>
    </ul>
  </li>
</ul>
```

**Comment by tsurugi** [comment]
Yes, I was wrong.
There are actual differences between versions, but it's a good story if you don't get the rules wrong.
I will close this issue.
