### ISSUE TITLE
Vuejs form with icon bug

### ISSUE THREAD

**Issue by jamols09** [uikit/uikit#4247]
I have used Vuejs with Vuikit it says that I can use html to replicate the icon inside the input but it does not work correctly on vuejs. It only display's me a blank space inside the input

**Comment by jamols09** [comment]
I have fixed it with this but it looks clumsy because it looks like you are calling the image twice. I also notice there is a bug when using class "uk-form-#size". The icon becomes transparent and you can type behind the icon.

**Comment by janschoenherr** [comment]
Please open an issue at https://github.com/vuikit/vuikit, thanks.
