### ISSUE TITLE
How to reduce Navbar Size?

### ISSUE THREAD

**Issue by jamols09** [uikit/uikit#4253]
![image](https://user-images.githubusercontent.com/20100579/88375748-b7dea400-cdce-11ea-887c-1d918c43d447.png)

I found a navbar style under the documentation but for me it looks like big. Is there anyway to reduce the navbar size? I have found none on the documentation to reduce its size or do I have to make my own css header?

**Comment by lucaspmarra** [comment]
edit your css like this:
`.uk-navbar-container {
  height: 60px; 
}`
