### ISSUE TITLE
<div uk-grid> doesn't validate

### ISSUE THREAD

**Issue by mynameiskemai** [uikit/uikit#4256]
Hi,

I started using uikit for a accessbility wordpress theme project today and was really astonished to learn that there is code that doesn't validate: div uk-grid.  I'm using the class name now, but I'm sure I'll bump into other issues with that? I was wondering what you think about this.

Best regards,
Kerstin

**Comment by dobaniashish** [comment]
Hi,

It is not a bug. All of the components can be initialized using the data attribute. https://getuikit.com/docs/javascript#component-usage

You can use grid components like this.

`<div data-uk-grid></div>`

**Comment by mynameiskemai** [comment]
Yes, but it doesn't validate with the W3C HTML Validator. I can't use the framework, since I'm trying to build an accessible website. If I could use it with classes, it would be fine, but I think that's not really possible? For example, could I build a masonry with classes instead of using the uk-grid attribute?
