### ISSUE TITLE
Switcher (Tab) firing events twice after set a tab index programmatically

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#4260]
When i have a button to change the index of a tab used with the switcher component, all events of the switcher triggers twice. This doesn't happen, when i use the switcher with any other component.

Also there is the general problem, that the event also fires when i click on an already opened tab. I want to load data dynamically into the tabs, whenever one is opening, so if the event is triggered twice, the data will also load twice. And the data will reload after clicking on the tab pane again, despite it's already open and the data is loaded.

### UIkit Version

3.5.5

### Actual Behavior

After clicking the button to change the active tab, all events are triggering twice. Before using the button all events are triggering only once, but also if you click on an already active tab.

### Expected Behavior

Events should only firing once after switching and also not at all when clicking on an already opened tab

### Reproduction Link

https://codepen.io/Riddler84/pen/GRZJNZX
(look at the console output)

**Comment by Riddler84** [comment]
Nevermind. Have to use `UIkit.tab("#tab").show()` instead of `UIkit.switcher("#tab").show()`.
But the problem persists that an already active tab also triggers the event.

**Comment by janschoenherr** [comment]
> After clicking the button to change the active tab, all events are triggering twice.

This is not happening for me, what browser are you using?
