### ISSUE TITLE
Drop doesn't flip when expected

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4264]
### UIkit Version

Since v3.5.0

### Actual Behavior

In some situations the Drop isn't flipping when expected.

### Expected Behavior

Drop should automatically flip when e.g. reaching window boundary.

### Issue

https://github.com/uikit/uikit/blob/4d6c949b4d497d1b7a47e297d4dd1c97e2a0e087/src/js/util/dimensions.js#L80-L82

`toFixed()` is returning a string, so condition in line 82 fails.

### Fix

`const newVal = toFloat((position[align] + elemOffset + targetOffset - elOffset[dir] * 2).toFixed(4));`

**Comment by janschoenherr** [comment]
Thanks! 🙋‍♂️👌
