### ISSUE TITLE
Please add Telegram icon to icons

### ISSUE THREAD

**Issue by dsancheznet** [uikit/uikit#4266]
### Summary

Please add Telegram icon to the icon component.

### Priority

Telegram is growing very quickly on the IM market and considering that the latest iconset does even include a G+ icon which isn't available for individuals anymore, Telegram should really be included asap. The icon does exist in the fontawesome font.

Thanks in advance

**Comment by AmirNzh** [comment]
yes, It's very good suggestion.  👍

**Comment by gitingwar** [comment]
The Tg icon is very necessary. Please add it

**Comment by janschoenherr** [comment]
Duplicate of #3350
