### ISSUE TITLE
Tooltip Bug - when contain ":" character 

### ISSUE THREAD

**Issue by AmirNzh** [uikit/uikit#4267]
I'm using uikit ver 3.5.6, and when i use tooltip message with contain ":" character , it's not show in popup.

**Comment by bornova** [comment]
Hi @AmirNzh , I am not able to reproduce the issue: [https://jsfiddle.net/rg1jq7w3/](https://jsfiddle.net/rg1jq7w3/)

Can you provide an example of your implementation?

**Comment by AmirNzh** [comment]
Hi @bornova , yes , please check this : [https://jsfiddle.net/1m6urLv3/](https://jsfiddle.net/1m6urLv3/)

**Comment by janschoenherr** [comment]
<a uk-tooltip="title: UIKit : Tooltip : Example">Tooltip</a>

Everything preceding the first colon is interpreted as key.
https://getuikit.com/docs/javascript#instance
