### ISSUE TITLE
Overlay is unusable on touch devices.

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#427]
I confirm overlay now works on touch devices with UIkit 2.7.0, but it's quite unusable.
You can't interact with overlay content, i.e. buttons and links.
Overlay should be a two-step operation, first step to activate (show) overlay, second step to interact with overlay content.

**Comment by sommarbar** [comment]
robertotremonti is right, it should be as he is descibing it 2 steps for mobile devices
