### ISSUE TITLE
Modal property "z-index" is incorrect.

### ISSUE THREAD

**Issue by uatrend** [uikit/uikit#4270]
### UIkit Version

3.5.6 (Chrome 84.0.4147.125)

### Actual Behavior

The computed value "z-index" of the element "uk-modal" is incorrect.
For example, If the value in the style file is "z-index: 1030", then the calculated value is "z-index: 10301".

### Temporary fix

Change:
```
this.stack && css(this.$el, 'zIndex', css(this.$el, 'zIndex') + active$1.length);
```
To
```
this.stack && css(this.$el, 'zIndex', parseInt(css(this.$el, 'zIndex')) + active$1.length);
```

**Comment by janschoenherr** [comment]
Thanks!
