### ISSUE TITLE
[Modal] Manipulating confirm dialogs is not possible

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#4273]
### UIkit Version
3.5.6

### Problem
"_The returned promise has a property dialog, which holds a reference to the modal itself. This lets you manipulate e.g. the markup of the modal's element._" (https://getuikit.com/docs/modal)

Example:
```
var promise = UIkit.modal.confirm('UIkit confirm!').then(function() {
    console.log('Confirmed.')
}, function () {
    console.log('Rejected.')
});
console.log(promise)
```

The promise var does not contain the dialog property and thus you are not able to manipulate the dialog.

**Comment by janschoenherr** [comment]
```
var promise = UIkit.modal.confirm('UIkit confirm!');

promise.then(function() {
    console.log('Confirmed.')
}, function () {
    console.log('Rejected.')
});

console.log(promise.dialog)
```

**Comment by ikabod** [comment]
Thank you very much!
