### ISSUE TITLE
tabs with sticky not working properly.

### ISSUE THREAD

**Issue by Elkaroui** [uikit/uikit#4275]
### UIkit Version 3.5.7

The sticky not working properly when I change the tab that doesn't have the same heigh.

Exmaple:
https://codepen.io/Elkazi/pen/oNxWZrw

### Expected Behavior

the sticky nav should stop to when it reach the target ID, it's working well for first tabs but soon as we move to the next tab the height of the first tab still calculated for all rest of tabs.

Should update the height of each tab.

**Comment by zzseba78** [comment]
Hi @Elkaroui. You should update the component when document height changes. You can trigger and update on the component on the tab event `shown` for example.
https://getuikit.com/docs/javascript#programmatic-use

**Comment by Elkaroui** [comment]
Thank you @zzseba78 I didn't see it for the first time when I was using Uikit, it's working perfectly!
