### ISSUE TITLE
Dropdown visible on Breadcrumb since 3.5.5

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4278]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
From 3.5.5 to 3.5.7 ( css file )

### Actual Behavior
Dropdown is visible and doesn't hide when mouse out
https://codepen.io/zzseba78/pen/YzqrjNa

### Expected Behavior

It should be hidden and work as expected, like before 3.5.5

### Reproduction Link

https://codepen.io/zzseba78/pen/YzqrjNa

### Steps to Reproduce the Problem
Hover the item with dropdown.

**Comment by janschoenherr** [comment]
Fixed in 3.6.13
