### ISSUE TITLE
uikit switcher not working with reactjs

### ISSUE THREAD

**Issue by samyc1201** [uikit/uikit#4280]
### UIkit Version
3.5.7

### Actual Behavior
While using Switcher, the content is not showing.

### Expected Behavior
The switcher content should show.

### Reproduction Link

https://codesandbox.io/s/sleepy-smoke-s4wkz?file=/src/App.js

### Steps to Reproduce the Problem

1. add below script in React project `index.html`

```
<!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit-icons.min.js"></script>
```

2. add below html in one of the react `js` file.
```
<ul className="uk-subnav uk-subnav-pill" data-uk-switcher>
        <li>
          <a href="#">Item</a>
        </li>
        <li>
          <a href="#">Item</a>
        </li>
        <li>
          <a href="#">Item</a>
        </li>
      </ul>

      <ul className="uk-switcher uk-margin">
        <li>Hello!</li>
        <li>Hello again!</li>
        <li>Bazinga!</li>
      </ul>
```
3. Check the result

**Comment by janschoenherr** [comment]
The component's attribute is rendered with a value of "true".

data-uk-switcher="true"

This will fix it:

    <ul className="uk-subnav uk-subnav-pill" data-uk-switcher="">

**Comment by samyc1201** [comment]
alright it is working. Why switcher is special which have to do like this `data-uk-switcher=""`? Most of the component I can just add `data-` in front to get it works in reactjs, for example like `data-uk-grid` and `data-uk-navbar`.
