### ISSUE TITLE
Documentation - separate component options with comma or semicolon?  

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#4282]
See:  https://getuikit.com/docs/javascript#component-configuration  (it uses **commas** to separate properties) 
> You can also pass options to the component constructor programmatically.
```js
// Passing an options object.
UIkit.sticky('.sticky', {
    offset: 50,
    top: 100
});
```

See:  https://getuikit.com/docs/modal#component-options  (it suggests **semicolon** to separate properties) 
> Any of these options can be applied to the component attribute. Separate multiple options with a semicolon.

**Comment by aarongerig** [comment]
@oshihirii Within JavaScript use commas to separate options, in HTML use semicolons (or commas when using the JSON format).

**Comment by oshihirii** [comment]
And a note to others who might have missed it, [as stated in docs](https://getuikit.com/docs/javascript#programmatic-use):

> NOTE The options names [ when defined in JavaScript ] must be in their camel cased representation, e.g. `show-on-up` becomes `showOnUp`.
