### ISSUE TITLE
Offcanvas scroll issue on mobile touch devices

### ISSUE THREAD

**Issue by t3ch-team** [uikit/uikit#4283]
On this page, https://vkovic.github.io/uikit-computer-store-template/subcategory.html on mobile view, click on "Filters" button to open the Filters Offcanvas, then try to scroll the filters using your touchscreen and see if it will work. 

I got this working when "uk-offcanvas-bar" is not present on first element load, then adding this class using "beforeShow" event of offcanvas.

**Comment by vanling** [comment]
@janschoenherr i dont have exact code for you, we put a lot of wrappers around uikit code
This issue occurs when you have something like this with flexbox columns
```
<uk-offcanvas-component class="uk-flex uk-flex-column">
    <div class="header">
        some small height header 
    </div>
    <div class="header uk-flex-1 uk-overflow-auto">
        a big chunk of content which is higher as page.
        this area is scrollable with scroll-wheel
        This area is NOT scrollable with touch

        When i Disable a touch move event in inspect tools it works as expected

    </div>
    <div class="footer">
        some small height footer
    </div>
</uk-offcanvas-component>
```

**When i Disable a touch move event in inspect tools it works as expected**
Touch event i disabled: 
```
{
    name: 'touchmove',

    passive: false,

    el: function() {
        return this.panel;
    },

    handler: function(e) {

        if (e.targetTouches.length !== 1) {
            return;
        }

        var clientY = event.targetTouches[0].clientY - this.clientY;
        var ref = this.panel;
        var scrollTop = ref.scrollTop;
        var scrollHeight = ref.scrollHeight;
        var clientHeight = ref.clientHeight;

        if (clientHeight >= scrollHeight
            || scrollTop === 0 && clientY > 0
            || scrollHeight - scrollTop <= clientHeight && clientY < 0
        ) {
            e.cancelable && e.preventDefault();
        }

    }

},
```

I suspect this comes from the height check `if (clientHeight >= scrollHeight || scrollTop === 0 && clientY > 0 || scrollHeight - scrollTop <= clientHeight && clientY < 0)`

**Comment by mira-kovar** [comment]
If you stuck here as I am. You could disable / bypass this basic functionality by adding this snippet code.

```js
UIkit.component('offcanvas', UIkit.component('offcanvas').extend({
    events: UIkit.component('offcanvas').options.events.forEach(event => {
        if (event.name === 'touchmove' && !event.self) {
            event.handler = () => {};
        }
    })
}));
```

**Comment by janschoenherr** [comment]
This is most likely no longer an issue, as we use `overscroll-behavior: contain` now.
