### ISSUE TITLE
Slider unexpected behavior on iOS

### ISSUE THREAD

**Issue by lucianoghione** [uikit/uikit#4287]
### UIkit Version

3.5.7

### Actual Behavior

The slider doesn't slide smoothly, I thought it was a swipe problem but I tested with autoplay and it behaves the same.

I've also tested it on multiple other operative systems like Windows, MacOS and Android and the problem only occurs on iOS.

### Reproduction Link

You can check this behavior on the documentation website itself. Link to it: [https://getuikit.com/docs/slider](url).

This is also a gif to show the problem: [https://ibb.co/3mPGJ4W](url)

Also, I want to thank you guys for this amazing framework, I love it!

**Comment by janschoenherr** [comment]
Fixed with a4512dc
