### ISSUE TITLE
Video can't be unmuted

### ISSUE THREAD

**Issue by directcuteo** [uikit/uikit#4288]
Hi!
I am using the Uikit Video component and I want at some point to mute/unmute the video (by clicking on an external button, so this is done using the code, not the video controls).

Making the video muted works fine with the following code: 
`this.htmlVideoItem.setAttribute('uk-video', 'automute: true');`

This will add a new attribute to the `<video>` tag called `muted`. 

Unfortunately, unmuting the video seems to be broken.
What I tried is: 
```
 this.htmlVideoItem.setAttribute('uk-video', '');
 this.htmlVideoItem.removeAttribute('muted');
```

The video remains muted even if the `muted` attribute is successfully removed.
I am testing with a non-youtube video link: https://yootheme.com/site/images/media/yootheme-pro.mp4

**Comment by janschoenherr** [comment]
As long as `automute: true` is set, UIkit will automute the element. Set an attribute `automute="false"` and then call `video.muted = false`.
