### ISSUE TITLE
Automatic scrolling of Sortable-Component

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4292]
### Summary
Until Version 3.1.6 automatic scrolling starts when the sortable item has reached the bounding area while dragging.
Since Version 3.1.7 the user has to move the cursor nearly the bounding area till automatic scrolling will be initiated.

I created two examples with the mentioned versions to show the difference.
To make it more obvious, I set the card header to act as the sortable handle.

### Reproduction
Start dragging "Item 1" by click and hold the card header and slowly move it downwards.
As you'll see in Version 3.1.7, the item get's stuck at the bottom of the screen so the user is forced to move the mouse/pointer all the way down until the cursor is nearly the edge of the browser window till automatic scrolling starts.

So, my question is:
Why has the behaviour change in Version 3.17?
Personally, I think the behaviour in Version 3.1.6 is the expected one:
As soon as the draggable item hits the bounding area, the automatic scrolling will be initiated.

### URLs
Example v3.1.6
https://codepen.io/lumelomser/pen/PoNvRzq

Example v3.1.7
https://codepen.io/lumelomser/pen/MWydVpr

**Comment by janschoenherr** [comment]
I just compared it to the Finder on Mac and Explorer on Windows. Here, if you are in the thumbnail view and drag a file/folder it's also the mouse pointer that initiates the scrolling. That's just an observation, I am sure we'll find references for both behaviors.

**Comment by janschoenherr** [comment]
Sounds good, will you add a Pull Request?

**Comment by Lumelomser** [comment]
Hey Jan!
Sorry for my late response, I had a day off.
Thank you for already applying the changes!
