### ISSUE TITLE
hook-inverse-component-table not used in sass

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4293]
### UIkit Version
3.5.8

### Description

[When compiling a sass theme](https://getuikit.com/docs/sass), the Table Inverse component isn't being added. From what I can see, [@mixin hook-inverse-component-table()](https://github.com/uikit/uikit/blob/69993e267f7278201d3944000c6eeb4a4a91410a/src/scss/mixins-theme.scss#L2005) should be getting called in [@mixin hook-inverse()](https://github.com/uikit/uikit/blob/69993e267f7278201d3944000c6eeb4a4a91410a/src/scss/mixins-theme.scss#L1552), but isn't.

Perhaps this is intended?

**Comment by flyboarder** [comment]
seems many inverse components are missing across different elements
