### ISSUE TITLE
Sticky mode

### ISSUE THREAD

**Issue by Bozhkov85** [uikit/uikit#4295]
Sticky to the dottom

**Comment by janschoenherr** [comment]
The upcoming release will contain a new option `position: bottom`. Please check with the current dev version

https://www.jsdelivr.com/package/npm/uikit?version=3.11.2-dev.fb043abc2

**Comment by Bozhkov85** [comment]
That's not what I meant. If the height of the block is greater than the height of the screen, then when it reaches its bottom edge when scrolling down the page, this block should stick with the bottom edge to the bottom of the screen. Can be applied to the sidebar so that there is no empty space on the side of the content when the sidebar is left at the top.

**Comment by Bozhkov85** [comment]
The boundary doesn't work or I,m doing something wrong?
