### ISSUE TITLE
problem with https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js and above version

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#4296]
Hi
https://codepen.io/ef1/pen/mdPZoMZ
with 
https://cdn.jsdelivr.net/npm/uikit@3.5.6/dist/js/uikit.min.js - and below - correct
with
https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js - and below - not correct
https://cdn.jsdelivr.net/npm/uikit@3.5.8/dist/js/uikit.min.js - and below - not correct

please tell me what could be the error

**Comment by janschoenherr** [comment]
This seems to be resolved?
