### ISSUE TITLE
When using Turbolinks, off-canvas malfunction

### ISSUE THREAD

**Issue by dvlpr91** [uikit/uikit#4297]
### UIkit Version

3.5.8

### Actual Behavior

```
...
<a class="uk-navbar-toggle uk-hidden@m" uk-navbar-toggle-icon uk-toggle="target: #offcanvas-nav"></a>
...
<div id="offcanvas-nav" uk-offcanvas="overlay: true; flip: true">
  <div class="uk-offcanvas-bar">
    <ul class="uk-nav uk-nav-default uk-nav-parent-icon" uk-nav>
      <li><a href="/foo">FOO</a></li>
    </ul>
  </div>
</div>
...
```

After the site is first loaded, the first click works.

However, the toggle does not work after moving the page.

**Comment by dvlpr91** [comment]
@janschoenherr Thanks for the very quick feedback.

**Comment by johanns** [comment]
You should disable Turbolinks on non-navigation links and buttons (off-canvas link, dropdown buttons, etc.) by adding `data-turbolinks="false"` attribute:

```
<a 
  class="uk-navbar-toggle uk-hidden@m" 
  data-turbolinks="false"
  uk-navbar-toggle-icon 
  uk-toggle="target: #offcanvas-nav"
/>
```

**Comment by dvlpr91** [comment]
@johanns 

This is not just a problem with turbolinks.
The same happens when rendering the DOM like vue.js.

**Comment by johanns** [comment]
> @johanns
> 
> This is not just a problem with turbolinks.
> The same happens when rendering the DOM like vue.js.

I see. I’ve been using UIkit with Turbolinks and

**Comment by johanns** [comment]
> @johanns
> 
> This is not just a problem with turbolinks.
> The same happens when rendering the DOM like vue.js.

I don’t think you mentioned that in your first post. ;) 

I’ve been using UIkit with Turbolinks and React without any issues as long I remember to disable Turbolinks on non-navigational link/buttons, and in some cases Turbolinks cache for specific pages (non-issue especially when rendering page in front-end).

**Comment by dvlpr91** [comment]
> > @johanns
> > This is not just a problem with turbolinks.
> > The same happens when rendering the DOM like vue.js.
> 
> I don’t think you mentioned that in your first post. ;)
> 
> I’ve been using UIkit with Turbolinks and React without any issues as long I remember to disable Turbolinks on non-navigational link/buttons, and in some cases Turbolinks cache for specific pages (non-issue especially when rendering page in front-end).

Ok, at first I thought it was a problem with turbolinks.

So I dropped the turbolinks and implemented it in vue.js. However, the same problem arises.

Did you do it?

**Comment by johanns** [comment]
I see. No, I use a combination of Turbolinks and React. I will say this though, I think it would be beneficial for UIkit to allow some sort of re-initialization for virtual and non-standard DOM events (like Turbolinks) — the current observer method doesn’t work in some cases. 

If you decide to revisit Turbolinks, try disabling its cache by adding the following meta header:

`<meta name="turbolinks-cache-control" content="no-cache">`
