### ISSUE TITLE
Close Modal on Back-Button

### ISSUE THREAD

**Issue by demlak** [uikit/uikit#4300]
Hi,
is there an Option to close Modal on Back Button?
Or is this more a feature-whish?

regards

**Comment by aarongerig** [comment]
Could be implemented yourself. Add a #hash to your URL or something similar, after the modal has opened. Use event listener to do this. https://getuikit.com/docs/modal#events

**Comment by demlak** [comment]
If anyone got a working solution on this, please let me know. i tried several things and nothing worked
