### ISSUE TITLE
on modal, unwanted block in ff

### ISSUE THREAD

**Issue by demlak** [uikit/uikit#4301]
### UIkit Version
3.5.8

### Actual Behavior
On modal, there is an unwanted block in ff on android at the bottom of the screen
(ff 81.1.2)
![Screenshot_20201010-002815](https://user-images.githubusercontent.com/11285006/95637381-ed239580-0a91-11eb-89c7-8d12b6a9d5bd.png)

### Expected Behavior
no block..

### Reproduction Link
https://getuikit.com/docs/modal

### Steps to Reproduce the Problem
open link on ff 81 on android, open modal preview

**Comment by demlak** [comment]
still on 3.6.13

**Comment by janschoenherr** [comment]
Will close this due to inactivity. If the issue persists, please comment.
