### ISSUE TITLE
scrollIntoView duration setting not working?

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4303]
### UIkit Version

3.5.8

### Actual Behavior

```
  // scroll next section into view
  util.on(document, 'click', '.tm-scroll-to-next', function (e) {
    e.preventDefault();
    let current = e.target.closest('section');
    util.scrollIntoView(current.nextSibling, { duration: 10000, offset: 0 });
  });
```
The duration setting seems to have no effect?!

### Expected Behavior

The scroll duration should be controllable via the setting. https://github.com/uikit/uikit-site/blob/feature/js-utils/docs/pages/javascript-utilities.md#scrollintoview

### Reproduction Link

https://jsfiddle.net/qj8ckze3/

**Comment by janschoenherr** [comment]
The docs seem to be old here. There is no longer a duration option. The function tries to mimic the browser behavior for `element.scrollIntoView({behavior: 'smooth'})` now.

**Comment by BernhardBaumrock** [comment]
Thx @janschoenherr for clarification.
I glanced into the code and it seemed the speed depends on the vertical distance where to scroll to? That means that the duration is longer for wide scrolls and shorter for short scrolls? Shouldn't it be quite easy to make the speed of the scroll configurable via a setting? eg. speed: slow/medium/fast or speed: 100, 200, 300 ?

**Comment by janschoenherr** [comment]
Sure it would be a matter of changing the getDuration function. Is it currently too slow for your use case?

**Comment by BernhardBaumrock** [comment]
No, on the contrary. For my taste it's a little too fast :) But that's really nothing big. I'm already getting used to it. But if it's a small thing to add, I think it would be helpful to get a setting for that again.
