### ISSUE TITLE
Missing headers on .uk-table-responsive

### ISSUE THREAD

**Issue by skerbis** [uikit/uikit#4304]
The responsive view (stacked) of Tables does not show the table headers. 
You can test it on your own documentation site.

**Comment by janschoenherr** [comment]
Seems to be resolved.

**Comment by skerbis** [comment]
As i can see here, it's not.
Or is it an older build? 
 
@janschoenherr 

Headers are missing: 

<img width="559" alt="Bildschirmfoto 2021-02-11 um 09 52 19" src="https://user-images.githubusercontent.com/791247/107616687-ddd67380-6c4e-11eb-97d8-84556a9bb2a5.png">

**Comment by janschoenherr** [comment]
What device and browser is that?

**Comment by skerbis** [comment]
It's 
- Safari 14 Desktop Version 14.0.3 and 
- Chrome: Version 88.0.4324.150 
Both on macOS

**Comment by Lumelomser** [comment]
This is the expected the behavior on responsive stacked table columns, as the table head will be hidden when viewport is lower than "Medium" viewport.

https://github.com/uikit/uikit/blob/develop/src/less/components/table.less#L251

**Comment by skerbis** [comment]
hmm 
I thought it would be more like this: https://johnpolacek.github.io/stacktable.js/

**Comment by Lumelomser** [comment]
@skerbis 
If your tables aren't that much complex, you can extend your HTML and CSS using this approach.
https://codepen.io/AllThingsSmitty/pen/MyqmdM

**Comment by skerbis** [comment]
@Lumelomser sure thx. That's good for generated Tables not for Tables the editors make for example with cke5 or other wysiwyg editors in CMS. 
When I saw that here is also a solution, I thought it might have been intended that way. Unfortunately, this does not seem to be the case, so I will continue to rely on the external solution. 

Nevertheless, thank you for your attention and this great framework.
