### ISSUE TITLE
Scrollspy animations on elements with nested links appear on page briefly, hide, then animate in.

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#4305]
This doesn't animate correctly. On page load, it will very briefly appear, then hide, then animate in:

```
<p uk-scrollspy="cls: uk-animation-fade; delay: 2000">
  <a href="#">Test.</a>
</p>
```

This works correctly however.  The "visibility:hidden" essentially fixes the issue:
```
<p uk-scrollspy="cls: uk-animation-fade; delay: 2000" style="visibility: hidden">
  <a href="#">Test.</a>
</p>
```

This only happens when there is a nested link.  If you remove the link, you don't need to have style="visibility:hidden".

Tested on UIkit v3.5.9.

**Comment by janschoenherr** [comment]
Are you lazy loading UIkit?

**Comment by jlahijani** [comment]
To be honest, I'm not sure because I don't really understand how Webpack works on a deep level.  I am using Laravel Mix (Webpack) to bundle everything in a simple, uncomplicated way.  The final app.js file is placed in `<head>`.

My app.js file:
```
// import external dependencies
import $ from 'jquery';
window.jQuery = $;
window.$ = $;

// ...

import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';
UIkit.use(Icons);
window.UIkit = UIkit;

// Load Events
jQuery(document).ready(() => routes.loadEvents());
```

My webpack.mix.js file:
```
let mix = require('laravel-mix');

mix.setPublicPath('./dist')
  .setResourceRoot('../dist/')
  .js('src/app.js', 'dist/')
  .sass('src/app.scss', 'dist/')
  .copyDirectory('images', 'dist/images')
  .copyDirectory('fonts', 'dist/fonts')
  .version();
```

The following is an example of my app.js file:
https://jonathanlahijani.com/temp/app-example.js

Note: if I use UIkit from CDN, the issue does not occur.
