### ISSUE TITLE
Error in state switch of accordion component

### ISSUE THREAD

**Issue by zhoumo310** [uikit/uikit#4306]
When you click the accordion component with the mouse to make it switch between expansion and contraction, it will cause the web page to move downward.

**Comment by zzseba78** [comment]
@zhoumo310 Do you have a code example of what you mean?

**Comment by zhoumo310** [comment]
> @ zhoumo310您是否有代表您意思的代码示例？

Use Google browser to open the accordion component page（https://getuikit.com/docs/accordion） and repeatedly click item 1, item 2 or item 3 in any accordion component to see the whole page scroll down. But this doesn't happen when you're browsing a page with Firefox.

**Comment by janschoenherr** [comment]
I believe this to be resolved.
