### ISSUE TITLE
Countdown end callback

### ISSUE THREAD

**Issue by parruc** [uikit/uikit#4307]
It would be great to have a countdown callback when the countdown reaches 00:00:00

### Priority

3, It is an easy fix and allows a lot of interactions, making the countdown component an active component rather than an aesthetic one as it is now

**Comment by riccardopiras87** [comment]
I did it on my project. (I'm using UIkit 3.6.9)

just add this:

`
callback: function(ref) {
     return ref.callback;
},
`
at line 8261

And change

```
if (timespan.total <= 0) {

        this.stop();

        timespan.days
            = timespan.hours
            = timespan.minutes
            = timespan.seconds
            = 0;
    }
```

to

```
if (timespan.total <= 0) {

    this.stop();

    timespan.days
        = timespan.hours
        = timespan.minutes
        = timespan.seconds
        = 0;

    this.callback();
}
```

**Comment by janschoenherr** [comment]
UIkit 3.16.0 adds `countdownstart`, `countdownstop` and `countdownend` events to Countdown component.
