### ISSUE TITLE
UIkit 3 -  Datepicker 

### ISSUE THREAD

**Issue by ghost** [uikit/uikit#4312]
Hi,
Datepicker - no or I can't find it on the site?

**Comment by Yeehawlerz101** [comment]
I agree, a Date Picker would be awesome especially for YOOTheme.

**Comment by cvyankatesh** [comment]
Please add datepicker asap

**Comment by ke11** [comment]
datepicker +1

**Comment by AlekVolsk** [comment]
I cannot use UIkit in large corporate projects due to the lack of only two components: datatimepicker and select with options search and ajax-loading options

**Comment by LaScheggia** [comment]
It's 2021 and we still need datepicker.

**Comment by ikabod** [comment]
It's 2022 and we still need datepicker.

**Comment by timrasche** [comment]
will this feature ever come or how is it?

**Comment by ikabod** [comment]
I now use the Litepicker (not easypick since it has not so much features):

https://litepicker.com/

**Comment by fatherofinvention** [comment]
Why was this included in UIKit 2 but now it is gone in UIKit 3?

**Comment by iambumblehead** [comment]
related https://github.com/uikit/uikit/issues/2740#issuecomment-1477124461 

at the link I describe how "pikaday" can be used

**Comment by janschoenherr** [comment]
Duplicate #2740
