### ISSUE TITLE
Navbar with RTL direction

### ISSUE THREAD

**Issue by MGyahia** [uikit/uikit#4313]
Hello, Navbar left and right is not working properly with RTL direction :

**LTR :** 
![image](https://user-images.githubusercontent.com/71601531/98272198-1cde9400-1f91-11eb-8069-3e7d1967e41b.png)

**RTL :**
![image](https://user-images.githubusercontent.com/71601531/98272311-3ed81680-1f91-11eb-9bce-bab9f42f6081.png)

**Comment by janschoenherr** [comment]
We are not auto switching `uk-navbar-left` and `uk-navbar-right`. You'll need to swap those classes manually.

For UIkit 4, we'll rethink this.
