### ISSUE TITLE
what components do i fetch when i want to use only toggle,filter,uk-scrollspy and uk-animation

### ISSUE THREAD

**Issue by picarica** [uikit/uikit#4314]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
not sure i fetch source stuff

### Actual Behavior

*What happened? Screenshots please, if relevant!*
it just stopped working after fetching needed components

### Expected Behavior

*What should have happened?*
work

so i need those components needed above i found these 
```
<script src="https://raw.githubusercontent.com/uikit/uikit/develop/src/js/components/filter.js"></script>
<script src="https://raw.githubusercontent.com/uikit/uikit/develop/src/js/core/toggle.js"></script>
```
i fetched them yet filter and toggle didnt work, doi fetch them from some other folder? i found toggle in api too i think

**Comment by janschoenherr** [comment]
Please ask questions on our discord servers. https://discord.gg/NEt4Pv7
