### ISSUE TITLE
[Doc] navbar the `class` attribute value is missing `uk-navbar`.

### ISSUE THREAD

**Issue by wang1212** [uikit/uikit#4326]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.5.9

### Actual Behavior

The sample code of the [navbar component documentation](https://getuikit.com/docs/navbar), the `class` attribute value is missing `uk-navbar`.

**Comment by ke11** [comment]
All the uk-* components go wrong with missing class attribute, when link is clicked, it didn't load it properly unless reload manually.

**Comment by janschoenherr** [comment]
This seems to be resolved. If not please comment.
