### ISSUE TITLE
How to deal with VERSION variable in /src/js/api/index.js

### ISSUE THREAD

**Issue by bezgodov** [uikit/uikit#4331]
package.json
```
"uikit": "^3.4.1"
```

If I use `/src/js/uikit-core.js` then I get an error `Variable VERSION is undefined`. I customised webpack to replace `VERSION` to version from package.json, but as for me it's a bit weird way
![image](https://user-images.githubusercontent.com/9131239/100678464-ec83ed00-33b8-11eb-86e2-3af31f9bfd8b.png)

Question is: how to use `src/js/uikit-core.js` without getting error?

**Comment by janschoenherr** [comment]
Yes, the version is replaced during the build process. Probably similar to what you've done.
