### ISSUE TITLE
UIkit 3.5.10 : uk-width-2-6 to uk-width-4-6 missing in the Width Component

### ISSUE THREAD

**Issue by aldoexpert** [uikit/uikit#4336]
Hi uikit,

I got missing component in version 3.5.10
I see the document [https://getuikit.com/docs/width](https://getuikit.com/docs/width) that say have .uk-width-1-6 to .uk-width-5-6
but in version 3.5.10 .uk-width-2-6 to .uk-width-4-6 is missing

Please bug fixed
Thanks

**Comment by viocassel** [comment]
Hi @aldoexpert ,

`.uk-width-2-6` = `.uk-width-1-3`
`.uk-width-4-6` = `.uk-width-2-3`

**Comment by aldoexpert** [comment]
ow.. I see
I think this style is provided according to the code

**Comment by aldoexpert** [comment]
ok thanks
