### ISSUE TITLE
Feature for Lightbox

### ISSUE THREAD

**Issue by DZ8540** [uikit/uikit#4346]
### Summary

Take a gradual increase in the photo by clicking in Lightbox.
How there -----------> [Fancybox](https://fancyapps.com/fancybox/3/)

### Priority
10 (i know the maximum is 5), very important!!!!

**Comment by lbreza** [comment]
I think you can achieve pretty much that with [UIkit Lightbox](https://getuikit.com/docs/lightbox) (responsive lightbox gallery with images and videos + captions)
