### ISSUE TITLE
Toggle component onhover

### ISSUE THREAD

**Issue by jellygnite** [uikit/uikit#4349]
### UIkit Version
v3.5.16

### Actual Behavior

In FireFox on the toggle test page, https://getuikit.com/assets/uikit/tests/toggle.html, when I hover over the test button the content flickers on and off.

IT continues to switch classes long after I have moved cursor away from button.

**Comment by janschoenherr** [comment]
I can't reproduce this. What's your Firefox version? Have you cleared your browser cache?

**Comment by jellygnite** [comment]
I have cleared cache. Firefox V83.0 (64 bit)

 

It is a strange one. Works fine in other browsers.

**Comment by janschoenherr** [comment]
Does the browser tab freeze or is it still interactive?

**Comment by jellygnite** [comment]
Ok. I figured out the problem. It only happens when I hover using my Wacom tablet. It seems as though firefox/uikit is treating that differently somehow. I’ve not seen this happen before.

**Comment by janschoenherr** [comment]
Will close this due to inactivity. Please comment if the issue persists.
