### ISSUE TITLE
Wrongly documented options

### ISSUE THREAD

**Issue by jorgoncalves** [uikit/uikit#4354]
Hi,

On the documentation for the [modal ](https://getuikit.com/docs/modal) component options, the options seem to be wrongly documented.
For instance, I was trying to use **esc-close** to prevent the modal from being closed when pressing **esc**, but the option is really, **escClose**. Found the solution in [here](https://stackoverflow.com/questions/35942337/ukit-modal-prevent-close-on-escape-button).

I'm using version 3.5.9 and this is also on @types.

I could fix this but don't really know how...

Best regards to you all

**Comment by aarongerig** [comment]
No, they are correctly documented. See the explanation here: https://getuikit.com/docs/javascript#programmatic-use

**Comment by jorgoncalves** [comment]
I see. Thank you.

Shouldn't this be refleted on types also? I keep getting the "wrong" option on TypeScript (I'm using v 3.3.1 of @types/uikit)
![image](https://user-images.githubusercontent.com/35938194/102612468-a2289d00-4128-11eb-8187-6e7b6527fe6a.png)
