### ISSUE TITLE
Grid component invalid html5 syntax documentation

### ISSUE THREAD

**Issue by barsan-md** [uikit/uikit#4355]
The issue https://github.com/uikit/uikit/issues/4256, suggests that UIkit components support a double syntax (one that uses attributes and one that uses data-attributes) in order to be initialized. The syntax that uses plain attributes however seems to be invalid by the html5 standard.
![Cattura](https://user-images.githubusercontent.com/14260975/102646858-1123e700-4165-11eb-8c77-24d8c26bf36e.PNG)

I'm wondering what is the rational between the invalid syntax? Maybe some old browser support? Also should the documentation suggest the use of the invalid syntax instead of valid one?
Other thoughts?

**Comment by bdthemes** [comment]
Hello @barsan-md, Your answer is here: [https://getuikit.com/docs/javascript#component-usage](https://getuikit.com/docs/javascript#component-usage)
