### ISSUE TITLE
[3.6.3 Offanvas] Parent item's icon triggering wrong expand/collapse

### ISSUE THREAD

**Issue by Hrishikesh-K** [uikit/uikit#4356]
### UIkit Version

3.6.3

### Actual Behavior

Clicking on the icon of a parent in offcanvas always triggers the expansion and collapse of the last parent in the offcanvas.

![image](https://user-images.githubusercontent.com/11403551/102688617-de89f500-421d-11eb-96b4-3631c0763e69.png)

According to the image above, if you click near the icon as indicated by the red arrow, the parent near the orange arrow is the one that expands/collapses.

However, if I click near the area marked by orange in the following image:

![image](https://user-images.githubusercontent.com/11403551/102688676-3fb1c880-421e-11eb-8dfc-90f88d85faf6.png)

it works perfectly.

### Expected Behavior

The correct `<li>` should be expanded regardless of where the user clicked.

### Reproduction Link

The one with problem (3.6.3): https://5fdcf45a120da90008e8bc66--hrishikeshk.netlify.app/
The one that worked fine (3.5.16): https://5fdcf2b6caf3bd0007a56b48--hrishikeshk.netlify.app/ 

### Steps to Reproduce the Problem

1. Visit the links above.
2. Click on the menu button to trigger the off-canvas: 

![image](https://user-images.githubusercontent.com/11403551/102688728-96b79d80-421e-11eb-8d15-0756eb8d6493.png)

Apologies if it's some issue on my end, but I haven't touched that area of my code except update UIkit.

**Comment by janschoenherr** [comment]
Thanks, fixed with https://github.com/uikit/uikit/commit/e29b9d138c24fa5bd89a67055b0f89a9eff3a1c4
