### ISSUE TITLE
Media definitions require block statements after any features -  .hook-print;

### ISSUE THREAD

**Issue by Alymbek** [uikit/uikit#4357]
### UIkit Version
3.6.3

### Actual Behavior
Hi, I just update to latest Uikit 3.6.3  and less 4.0.0 versions and getting error while compiling in webpack:

*What happened? Screenshots please, if relevant!*
```
ERROR in ./frontend/style.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):



   .hook-print;
 ^
Media definitions require block statements after any features
      Error in C:\node_modules\uikit\src\less\components\print.less (line 54, column 3)
```
and other:

```
ERROR in ./frontend/style.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


    color: @base-body-color;
    .hook-base-body;
                 ^
Unrecognized input. Possibly missing '(' in mixin call.
      Error in C:\node_modules\uikit\src\less\components\base.less (line 105, column 19)
```

**AND ALL .hook IN THIS FILE(59 RECORDS).**

and other error:
```
Also define the standard property 'text-decoration-style' for compatibility
in 
abbr[title] {
    /* 1 */
    text-decoration: underline dotted;
    /* 2 */
    **-webkit-text-decoration-style: dotted;**
}
```
![Capture](https://user-images.githubusercontent.com/2016702/102708083-b51ea700-42b9-11eb-9975-e49d1ca2dd66.PNG)
### Expected Behavior
should successfully compile *.less file
*What should have happened?*

### Reproduction Link
standard steps with npm installation
*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

**Comment by Alymbek** [comment]
I just downgrade to` "less": "^3.13.1"` and it is compiling withour errors.

seems problem with `"less": "4.0.0"`

**Comment by matthew-dean** [comment]
This is expected. Less 4.0.0 is a breaking change, hence the major version increment. This is due to parentheses being required for mixin calls. Please see the release notes: https://github.com/less/less.js/releases/tag/v4.0.0

**Comment by Alymbek** [comment]
so, will wait for Uikit changes in this case

**Comment by matthew-dean** [comment]
Note: you can make UIKit backwards compatible with multiple Less versions by changing lines like `.hook-print;` to `.hook-print()`.

**Comment by Alymbek** [comment]
hi, dear @matthew-dean.
I try to do so, but getting more same errors in other files.

better to fix it in original release.

**Comment by matthew-dean** [comment]
Not sure what you mean, but I think that's up to maintainers of UIKit.

**Comment by anveno** [comment]
I have a similar problem: I use prepros to compile the LESS files from UIKit. Prepros has now also raised the LESS version to 4, so I can no longer compile UIKit.

Error message with all .hook-sample;
"Unrecognized input. Possibly missung '(' in mixin call."

@janschoenherr Are there any plans to update the LESS files to the new LESS version 4 in the near future?
Is help with this wanted?

**Comment by matthew-dean** [comment]
@anveno Yes, I rolled back that change, partly because of this UIKit issue.

**Comment by janschoenherr** [comment]
Thanks, with 3.9.1 we now use parentheses for mixin calls 🥳
