### ISSUE TITLE
Smooth scroll does not work on elements with IDs starting with integers

### ISSUE THREAD

**Issue by DavidMagero** [uikit/uikit#4359]
### UIkit Version

3.6.5

### Actual Behavior

When an anchor hash starts with a number, the scroll function does not scroll to the target element.

### Expected Behavior

Clicking on the anchor link should smooth scroll to the desired element

### Reproduction Link

https://codepen.io/DavidMagero/pen/LYRzWdB

### Steps to Reproduce the Problem

1. Add an anchor link in your content with uk-scroll and an `id` that starts with an integer eg: `<a href="#2020-best-moments">2020 best moments</a>`
2. Clicking on the link scrolls to the` top of the page instead of the corresponding element
3. Remove the uk-scroll attribute and the link works as usual

Looking at the UIKit scroll script it seems there is a css selector validator function running on the anchor hash which escapes values starting with integers. CSS selectors cannot start with integers, but an ID starting with an integer is perfectly valid HTML. The anchor should not be validated as a CSS selector.

**Comment by thnii957** [comment]
How?
