### ISSUE TITLE
Add icon component

### ISSUE THREAD

**Issue by thientu995** [uikit/uikit#4360]
Version 2: https://getuikit.com/v2/docs/icon.html It supports a lot of icons for me to choose from!
But, version 3: https://getuikit.com/docs/icon very little support.

Example: version 3 has: play-circle and play, but there is not pause-circle and pause

I look forward to adding Uikit in the future!!! version 3 I am using it very well, but only the icon problem

**Comment by viocassel** [comment]
Hi @thientu995 

You can add your own icons (for example from [here](https://materialdesignicons.com)), like this
```
UIkit.icon.add({
    'pause-circle-outline': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M13,16V8H15V16H13M9,16V8H11V16H9M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20A8,8 0 0,0 20,12A8,8 0 0,0 12,4Z" /></svg>',
});
```
and use as usual `<span uk-icon="icon: pause-circle-outline"></span>`

**Comment by flihub** [comment]
material-icons package
https://github.com/asuikit/asuikit-material-icons

**Comment by thientu995** [comment]
> icons

Thank you! I use Angular

**Comment by thientu995** [comment]
> Hi @thientu995
> 
> You can add your own icons (for example from [here](https://materialdesignicons.com)), like this
> 
> ```
> UIkit.icon.add({
>     'pause-circle-outline': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M13,16V8H15V16H13M9,16V8H11V16H9M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20A8,8 0 0,0 20,12A8,8 0 0,0 12,4Z" /></svg>',
> });
> ```
> 
> and use as usual `<span uk-icon="icon: pause-circle-outline"></span>`

Thank you, a very good solution!
