### ISSUE TITLE
onClick (ReactJS) function does not work in buttons or <a> tags that are in modals (UIkit)

### ISSUE THREAD

**Issue by osbale** [uikit/uikit#4363]
### UIkit Version

3.6.5

### Actual Behavior

"I'm using UIkit in a react project and trying to show a modal window with an action button. The button in the modal window is supposed to call a function defined in the component itself, but apparently it's not calling it, I'm not sure if for some reason UIkit is intercepting the call and preventing react to consume the event or something like that." 
Post is not mine, it's taken from SO, but I have the same issue. None of the onClick events in buttons or a tags works. Tried to addEventListener, but that has many issue e.g. I need to check if it exists in DOM and it executes multiple times because of re-renders. 

### Expected Behavior

onClick is expected to execute functions e.g. onClick = { () => console.log('hello') }

### Reproduction Link

[https://codesandbox.io/s/hidden-frog-swlky?file=/src/App.js:0-1482](url)

### Steps to Reproduce the Problem

1. create-react-app
2. add UIkit cdn
3. create modal
4. create button in modal
5. attach onClick event to a button

Original link: [https://stackoverflow.com/questions/65249300/unable-to-call-react-component-function-from-uikit-modal](url)

**Comment by janschoenherr** [comment]
The eventlisteners are lost, then UIkit moves the modal to its container. You can use ``` data-uk-modal="container: false"``` to prevent this behavior.
