### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4368]
### UIkit Version

3.5.11

### Actual Behavior

A tooltip which is appended to the body-Element (default behavior) is aligned on closest element with overflow set to e.g. "hidden" or "auto".

### Expected Behavior

A tooltip which is appended to the body-Element (default behavior) is aligned on body-Element.

### Reproduction Link

UIkit v3.5.10
https://codepen.io/lumelomser/pen/rNMvJzO

UIkit latest version
https://codepen.io/lumelomser/pen/ZEporXG

### Steps to Reproduce the Problem

1. Open reproduction link
2. Hover over "Copy" or "Trash" icon

### Description

As you may notice, in versions prior to v3.5.11, each tooltip of the icon buttons is aligned horizontally centered to the button.
This is the expected behavior because the tooltip is appended to the body-Element and there is enough space around the button to show the tooltip horizontally centered.

Since v3.5.11 the tooltip is aligned to "top-right" position.

The commit which introduced the issue:
https://github.com/uikit/uikit/commit/3e218450131543007174bdd0409af1c54d071e72

Maybe a check should be added if the given "container"-property of the tooltip is something different than the body-Element.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/c3c6697e78e3485106a2144de326157cd17409ba
