### ISSUE TITLE
Tooltip not showing on Touch-Devices

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4369]
### UIkit Version

Since 3.5.17

### Actual Behavior

Tooltip is not showing on Touch-Devices.

### Expected Behavior

Tooltip is showing on Touch-Devices.

### Reproduction Link

https://getuikit.com/docs/tooltip

### Steps to Reproduce the Problem

1. Open reproduction link
2. Klick on any of the example buttons

### Description

Testet
Apple Safari (Version 14, iOS 14.3) (iPhone)
Apple Safari (Version 14, iOS 14.3) (iOS Simulator)

While testing with iOS Simulator I recognized that the DOM of the tooltip won't be appended to the body-Element at all.
I couldn't test on Android due to lack of a device.

**Comment by designconcepts** [comment]
Hello @janschoenherr,

the tooltips don't seem to work on iOS with the latest Version 3.18.3.
Tested on Simulator iPhone 15 with iOS 17 and iPhone 7 with iOS 15.8.3.
Should I open an new issue?

Regards, Andreas

**Comment by janschoenherr** [comment]
Thanks, fixed with https://github.com/uikit/uikit/commit/01a468d2e744a0153c7b64ff463fc6b822ef5647
