### ISSUE TITLE
Sticky bottom issues sometimes

### ISSUE THREAD

**Issue by razvanioan** [uikit/uikit#4371]
### UIkit Version

3.6.8

### Browsers

- very often on Firefox Developer Edition 85
- sometimes on Chrome 87

### What happened

- on UIkit documentation page load, both bottom example elements were fixed at the top of page on bot of browsers
- on Chrome there was also the offset example element

### Video: Firefox

https://user-images.githubusercontent.com/2914226/103785049-699f2380-5043-11eb-9249-51fc38338d56.mp4

### Video: Chrome

https://user-images.githubusercontent.com/2914226/103785080-73c12200-5043-11eb-89d3-1a0a2199f79b.mp4

**Comment by janschoenherr** [comment]
I believe this to be resolved with latest versions. If the issue persist, please comment.
