### ISSUE TITLE
Sortable crashes while rearranging elements in a masonry grid.

### ISSUE THREAD

**Issue by VictorWilvert** [uikit/uikit#4373]
### UIkit Version

3.6.9

### Actual Behavior

The web page stops working while rearranging the order of the elements on the sortable grid. The bug seems to happen only on masonry grids.

![Unbenannt](https://user-images.githubusercontent.com/26912460/104001401-e21af700-519f-11eb-89d7-b7dea0ee837f.PNG)

### Expected Behavior

Rearranging elements in the uk-sortable component should work normally, without crashing the web page.

### Reproduction Link

*A minimal Codepen that can reproduce the bug. [uk-sortable bug](https://codepen.io/victorw_/pen/YzGjKNN)*

### Steps to Reproduce the Problem

1. Move the element with the text "Item 3" to the position of the element with the text "Item 4".
2. Again, Move the element with the text "Item 3" to the position of the element with the text "Item 4". This should crash the pen.

It can also be done rearranging other elements, normally rearranging elements in the same row doesn't cause the bug, it only seems to happen when moving between different rows.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/fc7a20e7381c87e31704b8ab8b785dfde60d33ba
