### ISSUE TITLE
Breadcrumb doesnt show correctly in IE11

### ISSUE THREAD

**Issue by rewalax** [uikit/uikit#4376]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.10

### Actual Behavior

Breadcrumb doesnt show correctly in IE11. 
![image](https://user-images.githubusercontent.com/4311332/104463284-8b248000-55ec-11eb-979f-8b399879cbe1.png)

### Expected Behavior

it should be displayed horizontally but not in IE11.

### Reproduction Link

https://getuikit.com/docs/breadcrumb

### Steps to Reproduce the Problem
open link https://getuikit.com/docs/breadcrumb with IE11 will reproduce the bug

**Comment by lbreza** [comment]
Replace `.uk-breadcrumb > * {
  display: contents;
}` with `.uk-breadcrumb > * {
  display: inline-block;
}`

**Comment by ikabod** [comment]
Please update to latest version, since there was a change in version 3.6.12 (see https://getuikit.com/changelog)

**Comment by janschoenherr** [comment]
We have dropped support for IE 11.
