### ISSUE TITLE
Prompt text needs to change to "placeholder"

### ISSUE THREAD

**Issue by joshgilson** [uikit/uikit#4377]
The default text field in the modal is set to value and should be a placeholder so the user doesn't have to delete it.
Example (click the prompt button) https://getuikit.com/docs/modal#modal-dialogs

On line 104 it should be placeholder="${value || ''}" instead of value="${value || ''}": 
https://github.com/uikit/uikit/blob/develop/src/js/core/modal.js#L104

**Comment by janschoenherr** [comment]
With the next release, the value text in input will be selected. The user can immediately start typing. That's what Chrome seems to be doing for `window.prompt(message, defaultValue)`.
