### ISSUE TITLE
"Totop" component throw an error after version 3.6.6

### ISSUE THREAD

**Issue by rewalax** [uikit/uikit#4381]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.11

### Actual Behavior
"Totop" component throw an error when clicked: 
![image](https://user-images.githubusercontent.com/4311332/104845425-642dbd00-5910-11eb-9b1b-e6e7a8d086b2.png)
This bug occured from version 3.6.6

### Expected Behavior

It was OK before version 3.6.5

**Comment by janschoenherr** [comment]
What does the link look like?

**Comment by rewalax** [comment]
it's been fixed in version 4.3.13.
closed.
