### ISSUE TITLE
uk-img not working for background images with data-srcset

### ISSUE THREAD

**Issue by dramspro** [uikit/uikit#4383]
### UIkit Version

3.6.11

### Actual Behavior

only first image link in srcset added into style attr image url

### Expected Behavior

Image URL in style attr changes depending on screen width

### Reproduction Link

https://getuikit.com/assets/uikit/tests/image.html

### Steps to Reproduce the Problem

1. just open uikit's test page (i have drawed arrows in screenshot attached)
![2021-01-18_15-16-55](https://user-images.githubusercontent.com/5102558/104916006-8243fd80-59a2-11eb-8906-8c8d8cb22a47.png)

**Comment by dramspro** [comment]
Mabe related with #3989

**Comment by adleviton** [comment]
I'm also experiencing this issue.

**Comment by rewalax** [comment]
it's been fixed in version 4.3.13. 
closed.

**Comment by viocassel** [comment]
Confirm 👆

**Comment by adleviton** [comment]
On second thought .... I think it is working. If you see the note all the way at the bottom of the [documentation for the image component](https://getuikit.com/docs/image), that will shed some light.

Basically UIKit is keeping track of images via session storage, so if a larger image size has already been downloaded, that is the one it will select.

Testing this in Chrome, I made my browser narrow like a mobile device, empty the cache and hard reload, **AND do a sessionStorage.clear()** (I think this is what's tripping people up).

As I expanded my browser window, I can see that the URL for my background image changes as the browser gets wider.

**Comment by dramspro** [comment]
@adleviton you are right, it is works perfect. Thank you for the tip.
I am apologize, my tests were wrong because i used display with 1.5x density and Uikit like a charm provide me hi-res picture!

Tested at v3.6.13 with [official Uikit test page](https://getuikit.com/assets/uikit/tests/image.html)

**Comment by thnii957** [comment]
Closed
