### ISSUE TITLE
Not hidden modal dialog inside uk-grid-match

### ISSUE THREAD

**Issue by strepon** [uikit/uikit#4384]
If a modal dialog (`uk-modal`) is placed as an item of `uk-grid` with the `uk-grid-match` class, then that dialog's style `display:none` is overridden by `display:flex` defined for `.uk-grid-match > *`.

Demonstrated here: https://codepen.io/strepon/pen/oNzVgmW
The two cards are shown as expected, however the dialog stays in background, preventing to click the link on the second card.
(When `uk-grid-match` class is removed, the link gets active.)

Experienced in UIkit 3.6.11 and seems to be a regression - it did not happen at least in 3.2.3.

**Comment by janschoenherr** [comment]
I would file this under "works as expected". Just place the modal somewhere else.
