### ISSUE TITLE
Drop/Dropdown - 'uk-open' class no longer applied to toggle/button

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4385]
When a Drop or Dropdown component was opened, the element that opened it used to get a 'uk-open' class. This is no longer the case. I've started to target css using [aria-expanded=true] instead of .uk-open but it would be good to be backwards compatible. From what I can see in the code, toggleClass() has been omitted in Drop when the update aria change was made around 3.5.17. I'm still getting uk-open on the Accordion component for example.

**Comment by janschoenherr** [comment]
Sorry, if this was a breaking change. 🙋‍♂️
