### ISSUE TITLE
Slider and Lightbox navigation /uk-slidenav-previous and uk-slidenav-next/ lost the chevron icons.

### ISSUE THREAD

**Issue by malawebmanufaktura** [uikit/uikit#4386]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.12

### Actual Behavior

*What happened? Screenshots please, if relevant!*

### Expected Behavior

*What should have happened?*

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

1.
2.
3.

**Comment by malawebmanufaktura** [comment]
Slider and Lightbox navigation /uk-slidenav-previous and uk-slidenav-next/ lost the chevron icons.

**Comment by neophron** [comment]
UIkit Version
**3.6.12**
In Firefox – the blue one, 85.0b8 (64-Bit) – the chevron icons are now bigger then usual.
![Bildschirmfoto 2021-01-20 um 22 12 14](https://user-images.githubusercontent.com/11855980/105238210-d4387f00-5b6c-11eb-9efe-7b9c8a5e2e73.jpg)

**Comment by janschoenherr** [comment]
Thanks, fixed with 3.6.13

**Comment by malawebmanufaktura** [comment]
Cheers, that was fast :)
