### ISSUE TITLE
Lightbox closing unexpectedly on swipe gesture

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4387]
### UIkit Version

Since 3.6.4

### Actual Behavior

Lightbox is closing unexpectedly on mouse-/pointer-up after start dragging right/left on the black background layer.

### Expected Behavior

Lightbox is moving to previous/next item by dragging the black background layer right/left without closing on mouse-/pointer-up.
A single click (without swiping) on the black background layer will close the lightbox.

### Reproduction Link

https://getuikit.com/docs/lightbox#animations

(e.g. see "Slide" example)

### Note

The issue already occured in a previous version and was fixed in version 3.1.0.
Since version 3.6.4, the issue is occurring again.

Is working as expected on iOS 14.3.
I couldn't test on Android due to lack of a device.
Seems to be a Desktop (non touch device) related issue.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/d8b732c644c9ae22c3e5e857f6e491053a4d481d
