### ISSUE TITLE
Scrollspy - dynamic changes are not working - solution needs approval

### ISSUE THREAD

**Issue by directcuteo** [uikit/uikit#4388]
Hi, I am using the scrollspy component to animate my components through the app.
At some point, I can change the scrollspy's `cls ` animation value for example from `uk-animation-slide-left` to `uk-animation-fade` (`uk-scrollspy="cls: uk-animation-slide-left"` => `uk-scrollspy="cls: uk-animation-fade"`)

For some reason this is not working, scrollspy component doesn't know about the change and it still applies the class `uk-animation-slide-left` even if the HTML element has the new value set to `uk-scrollspy="cls: uk-animation-fade"`.

I came up with a solution by changing the source code of the scrollspy component inside `uikit.js` and now the scrollspy it's actually updating accordingly after it realizes the new `cls` value is not the same as before.

I would ask you to change this inside the code so I can get the new updates of uikit and not get frozen with my own version.

I added next `if` statement inside `/dist/js/uikit.js`, line 7348:

```
   if (el[stateKey$1].cls !== this$1.cls) {
         el.classList.remove(el[stateKey$1].cls);
         el[stateKey$1].cls = this$1.cls;

         var state = el[stateKey$1];
       
         var toggle = function (inview) {
            css(el, 'visibility', !inview && this$1.hidden ? 'hidden' : '');

            toggleClass(el, this$1.inViewClass, inview);
            toggleClass(el, state.cls);

            trigger(el, inview ? 'inview' : 'outview');

            state.inview = inview;

            this$1.$update(el);
        };
     
        if (state.show) {
            toggle(true);
        }
  }
```

The code would go in the forEach function between 
```
 if (!el[stateKey$1]) {
      el[stateKey$1] = {cls: data(el, 'uk-scrollspy-class') || this$1.cls};
 }
```

and 

``` el[stateKey$1].show = isInView(el, this$1.offsetTop, this$1.offsetLeft);```

Photo:
![image](https://user-images.githubusercontent.com/37619567/105342538-27501780-5be9-11eb-93cd-ff1f0d3db295.png)

Let me know your feedback. Thank you!

**Comment by janschoenherr** [comment]
Changing the `cls` option is working fine for me. Are you using the latest UIkit version?

**Comment by directcuteo** [comment]
Indeed, the version was the problem. Thank you !
