### ISSUE TITLE
Disc, Circle and Square styles in list component not visible in IE 11

### ISSUE THREAD

**Issue by ikabod** [uikit/uikit#4389]
### UIkit Version

Version:
3.6.13

The styles, mentioned in the topic, does not show up in IE 11 (https://getuikit.com/docs/list)

Besides that: Internet Explorer was always and will be to the end of this world a pain for developers. I support it, because UIkit does. But don't you have plans to drop support for this ugly and outdated browser? A lot of things could be done more easily.

**Comment by rewalax** [comment]
uikit seems have abandoned supporting IE11:
https://github.com/uikit/uikit/issues/4376

**Comment by ikabod** [comment]
No they have not, see my answer in your request.

**Comment by ikabod** [comment]
> I support it, because UIkit does.

Since Microsoft itself started to drop Support for IE, I will now follow them and make my coding life much easier: [Microsoft 365 apps say farewell to Internet Explorer 11](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)

see also: [Should you support Internet Explorer?](https://blog.logrocket.com/should-you-support-internet-explorer/)

**Comment by janschoenherr** [comment]
We have dropped support for IE 11.
