### ISSUE TITLE
LESS version 4.0.0 requires parentheses after mixin calls

### ISSUE THREAD

**Issue by billhemsley** [uikit/uikit#4391]
### UIkit Version

3.6.13

### Actual Behavior

Errors when compiling with LESS 4.0.0 for lines where mixins are called and don't have parentheses.

Most errors are in the form "Unrecognized input. Possibly missing '(' in mixin call.", e.g. for heading.less line 64.

Also get "media definitions require block statements after any features" for print.less line 54 (a somewhat confusing message, but fixed by adding parentheses).

### Steps to Reproduce the Problem

Compile to CSS using LESS 4.0.0

### Comments

The change to parentheses being required is documented at:
https://github.com/less/less.js/pull/3573

Presumably the fix is to add parentheses on all relevant lines, which I believe is backwardly compatible.

**Comment by matthew-dean** [comment]
This is no longer relevant, as Less 4.1.0 reverts the paren requirement.

**Comment by billhemsley** [comment]
That's good to know - I'll upgrade straight away!

It might be worth noting that mixins without the parens are deprecated and "will be required in a future release" (http://lesscss.org/features/#mixins-feature), and the removal of the requirement in 4.1.0 is "for this version" (https://github.com/less/less.js/releases). So it's possible the issue will return. And it might be good practice to use the parens anyway.

**Comment by matthew-dean** [comment]
@billhemsley Well I wrote both that piece of documentation and released both versions lol. It was true at the time, and for _consistency_, it's good to use parens, but I think it's looking increasingly unlikely that we'll ever enforce that change again, because too many libraries break.

**Comment by matthew-dean** [comment]
@billhemsley It's actually a good reminder that I should re-write that line in the documentation! ^_^

**Comment by janschoenherr** [comment]
Thanks, guys, we've updated less to version 4 in v3.9.0

**Comment by janschoenherr** [comment]
With 3.9.1 it uses parentheses now
