### ISSUE TITLE
slide top and slide bottom animations fail for midpage stickynavs with height of 0.

### ISSUE THREAD

**Issue by solonmedia** [uikit/uikit#4395]
### UIkit Version

3.6.14

### Actual Behavior

For certain designs - on a home page, for example, it is helpful to have a separate sticky navigation below a headliner hero unit that may include a front page logo and navigation.

Say you have a home page with a full viewport image with a logo/nav/search overlay at the top, and you want to set up the design so that once the viewport image at the top of the page is cleared a navigation sticky slides from the top reflecting the logo/nav/search functionality as you read further down the page.

Right now that initial sticky div needs to be placed beneath the viewport div, set to visibility: hidden and height: 0 so that the placeholder space does not appear.

When this stickynav is enabled, it fades in without any sliding translation. Slide left and slide right work as expected - because they rely on the width for calculation. Slide top and slide bottom do not, because the slide function uses the height of the on-page element to determine the distance of the slide. The stickynav fades in, so the design still works, but the slide effect doesn't happen.

### Expected Behavior

The uk-animation-slide functions should check for respective height and width for 0 values and I guess try setting the height of the element back to auto before performing the slide so that the full length of the slide will engage.

**Comment by janschoenherr** [comment]
Check out the line-gallery theme here: https://getuikit.com/pro

Is that what you are looking for?

**Comment by solonmedia** [comment]
Yes, looking at the code for that segment of the page I can see a method to achieve the desired result.

I had not used this technique because the menu at the top of the main page was larger than the pop-down menu, but I believe I can use the same container for both and conditionally show different content in that container. I will look into it further.
