### ISSUE TITLE
Switcher and tab connected

### ISSUE THREAD

**Issue by f-r3d** [uikit/uikit#4396]
Hi' guys I've a problem migrating from 3.5.8 to 3.6.14 uikit version.
I use a tab component connected to a switcher component in this way:

```
UIkit.switcher('#ds-tabs', {
    connect: '#ds-content',
    toggle: '> li:not(.ds-no-switch)',
    active: 0
});
```
and then in HTML:
```
<div>
<ul id="ds-tabs" hidden="" class="uk-tab">
    <li class="ds-no-switch">Operation</li>
    <li>This must be active</li>
    <li>Second tab</li>
    <li>Third tab</li>
</ul>
</div>
...
<div>
<ul class="uk-switcher" id="ds-content">
    <li>Content of the first no "ds-no-switch" tab.</li>
    <li>Content of the second tab.</li>
    <li>Content of the third tab.</li>
</ul>
</div>
```
If I set as active the tab 0 it seems that it actually sets as active the tab 0 + the number of no clickable tab.
In this example the "Second tab" instead of "This must be active".
If I add a second "ds-no-switch" tab element it sets as active the "Third tab".
If I have no clickable tab it all works fine.

**Comment by f-r3d** [comment]
Hi', there are news about this issue?

**Comment by f-r3d** [comment]
Hi' @janschoenherr ,
More than 9 months as passed, so I try myself to resolve this issue.
I found this commit in version 3.6.0
https://github.com/uikit/uikit/commit/0154e49109445db45e7c39ebe26b3a14eeccb184

Row 126 introduces the issue, if I replace the getIndex function with the oldest one all seems to works fine.
Hope this helps.

Bye, Federico

**Comment by janschoenherr** [comment]
Currently, the number of <li>s in both lists must match. That's not to say, that this is good behavior. We'll put it on the todo list for UIkit 4. As a workaround, if you add an empty <li> tag to the second list, it should behave normally.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/d4aecc3e68573ed1bda9ed125de63e8da2a9650a
