### ISSUE TITLE
Spinner appearing twice inside Vue 2

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#4398]
If using Vue v2 and you have the spinner somewhere inside of the Vue2 binded main div, then the spinner will appear twice.

I remember there being a similar issue with icons appearing twice a couple years ago.

Using UIkit 3.6.14

**Comment by janschoenherr** [comment]
Hi, could you add a minimal codepen to reproduce the issue? In general it seems to mitigate the problem if you use Vue's attribute binding `v-bind` . e.g. `<span :uk-component>`
