### ISSUE TITLE
Slidenav accessibility needs improvement

### ISSUE THREAD

**Issue by Flimm** [uikit/uikit#4400]
The documentation provides this example under the Slidenav page:

```
<a href="" uk-slidenav-next></a>
<a href="" uk-slidenav-previous></a>
```

However, these links are not accessible:

- the links behave as buttons, but aren't marked with that expectation
- there is no text indicating to the user what the buttons do, for those with difficulty seeing or understanding the icon.

Instead, I suggest changing the documentation to look like this:

```
<a href="" uk-slidenav-next role="button" aria-label="Go to next"></a>
```

# References:

- https://www.sarasoueidan.com/blog/accessible-icon-buttons/
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

**Comment by janschoenherr** [comment]
Thanks, version 3.16.0 comes with built in accessibility.
