### ISSUE TITLE
Release 3.6.15 broken?

### ISSUE THREAD

**Issue by czosel** [uikit/uikit#4403]
I'm seeing some oddities with the latest release: I'm using uikit through the ember addon ember-uikit and upgrading to 3.6.15 causes the consuming apps to throw with obscure error messages like `define is not defined`, hinting a broken build. I wasn't able to isolate the issue further, but after several hours of analysis noticed that upgrading uglify-js to the latest release `3.12.6` (currently `3.12.1` in the lockfile) fixes the issue. I analyzed the changes when building with the updated uglify-js and saw that some unneeded variable declarations were removed. I can't tell how that broke my build, though.

Here is an example of the broken build pipeline: https://github.com/adfinis-sygroup/ember-uikit/runs/1810755674?check_suite_focus=true

Downgrading to uikit `3.6.14` also fixes the issue. AFAICT, no uglify-js related changes were made in 3.6.15 - so the issue might occur because uglify-js handles some of code changes introduced in 3.6.15 differently between `3.12.1` and `3.12.6`?

Sorry about the fuzzy description - I'm really stumped by this issue ...

If you like, I can send a PR that upgrade uglify-js.

**Comment by janschoenherr** [comment]
Is this resolved in 3.6.16?

**Comment by czosel** [comment]
Thanks for your quick and most of all effective response - it seems that the upgrade of uglify-js did the trick, `3.6.16` builds correctly :tada: 

On a side note, did you already consider switching from uglify-js to [terser](https://github.com/terser/terser)? If you're interested, me or one of my colleagues might be able to send a PR.
