### ISSUE TITLE
Slider doesn´t drag, instead text is selected.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4412]
### UIkit Version

3.6.16

### Actual Behavior

You can´t swipe the slider when text is on it, instead text is selected.

### Expected Behavior

Prevent text selection and drag.

### Reproduction Link

https://codepen.io/zzseba78/pen/zYoKjma

### Steps to Reproduce the Problem

Drag the slider.

**Comment by flihub** [comment]
add uk-disabled to uk-card

**Comment by zzseba78** [comment]
@flihub Yes, good hack it works, but in case of need buttons, links inside slider card it disable them.

**Comment by janschoenherr** [comment]
You can also give the text `pointer-events: none;`

https://developer.mozilla.org/de/docs/Web/CSS/pointer-events

**Comment by janschoenherr** [comment]
You can either use `uk-disabled` or specifically set `pointer-events: none` on areas you do want to be draggable.
