### ISSUE TITLE
'a' element within uk-switcher not working as expected

### ISSUE THREAD

**Issue by Kloen** [uikit/uikit#4417]
### UIkit Version

3.6.16

### Actual Behavior

I have a link within a uk-switcher, the link doesn't navigate.

### Expected Behavior

The link should open as any other link.

### Reproduction Link

https://codepen.io/kloen/pen/yLVgWEp

### Steps to Reproduce the Problem

Use the codepen above.

**Comment by janschoenherr** [comment]
Please check the documentation. There is no need to apply the switcher component to the connected list.
