### ISSUE TITLE
Lightbox videos can not change playback time but instead swipes to the other video (iOS Safari Only)

### ISSUE THREAD

**Issue by Mac000** [uikit/uikit#4418]
When a video is opened, user is not able to change playback time, if they try to drag the seeker, it will swipes toward the other video. If tapped on anywhere in playback timeline, video does not go to that timestamp.

###Note: This is happening only on Safari iOS

### UIkit Version
3.6.16

*Issue reproducible in latest version*

### Expected Behavior
Video playback time should have changed normally

### Reproduction Link
Not available, Please try in iOS Safari

### Steps to Reproduce the Problem
Create a lightbox.
Add videos to it
play video and try to change playback time in iOS Safari

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/58a6cbaf4e35b3a169e019ef09842cf29c057ebe
