### ISSUE TITLE
Dragging items in sortable group with space available

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4423]
### UIkit Version

Since 3.5.14

### Actual Behavior

When dragging an item over a sortable group with one or more existing items and there is still space available to drop another item, the user has to scroll all the way up to an existing item until the drag event is recognized and the "uk-sortable-placeholder" element is going to be added.

(see Reproduction link A)

### Expected Behavior

Dragging an item over a sortable group with space available should always be recognized without the user being forced to scroll to already existing items.

(see Reproduction link B)

### Reproduction Link

Reproduction link A (Latest version)
https://codepen.io/lumelomser/pen/Vwmraqz

Reproduction link B (Version 3.5.13)
https://codepen.io/lumelomser/pen/zYoPqbq

### Steps to Reproduce the Problem

1. Open reproduction link
2. Scroll down to the end of sortable items
3. For example, drag "Item 18" over the second column and drop it into (works as expected)
4. Now, try to drag and drop "Item 19" into second column

As you may notice, in both versions the drag event is recognized correctly when a sortable group is empty.
But since Version 3.5.14, the user is forced to scroll to the top of the sortable group to drop an item when the group isn't currently empty.

**Comment by janschoenherr** [comment]
Seems to be fixed.
