### ISSUE TITLE
Dragginga sortable item in off-canvas triggers off-canvas' events

### ISSUE THREAD

**Issue by Hrishikesh-K** [uikit/uikit#4426]
### UIkit Version:

3.6.17

### Actual Behavior

I have a `<div>` appended to the `uk-sortable` element dynamically via JavaScript. This is inside a off-canvas. Whenever the sortable element is dragged, for some reason, the off-canvas' events are fired. I came to this conclusion by adding a breakpoint in developer's tools to body's attribute changes. It took me to my off-canvas' toggle event handler.

If you visit the link mentioned below, and add any audio to playlist by clicking the icon in its card, a `<div>` will be appended to the off-canvas. Whenever it is dragged, body's width is changed (as mentioned in my event handler).

![image](https://user-images.githubusercontent.com/11403551/109428990-91957c80-7a1f-11eb-8663-baf1eca9b658.png)

### Expected Behavior

Off-canvas' toggle event should not be fired.

### Reproduction Link

https://goofy-heisenberg-cdfc6b.netlify.app/

### Steps to Reproduce the Problem

1. Visit the link.
2. Click on the add to playlist icon in any songs' card.
3. Try dragging the appended `<div>` in the off-canvas. The width of the body changes.
4. (optional) Add a breakpoint to body's attribute modifications and then drag the element, just to be sure.

**Comment by janschoenherr** [comment]
I think the tooltip is triggering that event. In your event listener you can use `{self: true}` as fourth parameter to ensure the event is triggered by the offcanvas.
