### ISSUE TITLE
Example pages seem to reference a build that includes custom css

### ISSUE THREAD

**Issue by steveraden** [uikit/uikit#4427]
Hello,  I'm a backend dev looking at CSS frameworks for a new product and I was taking UIKIT for a spin. 

 I was looking at some of your layout examples.  I was having having a hard time getting  your login [page](https://getuikit.com/v2/docs/layouts_login.html) to work well , and couldn't get it to a matching layout even with identical markup.  After some digging I noticed that at least one class `uk-panel-box` was not in uikit-3.6.17.css, but was in the example pages, uikit.docs.min.css.  

Was this class a custom class for an example?  If so, my suggestion would be to highlight customization for example in a separate CSS file because otherwise new learners may have a hard time figuring out why examples don't work.

**Comment by janschoenherr** [comment]
Thanks, we have removed the reference.
