### ISSUE TITLE
UIKIT isn't working when imported from static folder

### ISSUE THREAD

**Issue by cheak1974** [uikit/uikit#4428]
Hi Everybody,
maybe I am to dumb but I try to get UIKIT3 running with a local install. I am using uvicorn and python but importing UIKIT from the CDN works just fine, when I do like in the docs:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/css/uikit.min.css" />
<script src="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/js/uikit-icons.min.js"></script>
```

but when I download the ZIP package and place the files in the static folder like

```html
<script src="static/uikit-3.6.17/css/uikit.min.css"></script>
<script src="static/uikit-3.6.17/js/uikit.min.js"></script>
<script src="static/uikit-3.6.17/js/uikit-icons.min.js"></script>
```
UIKIT stops working. I have no clue why.

uvicorn reports that all 3 files are loaded properly so something is holding back UIKIT from working.

```
INFO:     127.0.0.1:56178 - "GET /user/static/uikit-3.6.17/css/uikit.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:56177 - "GET /user/static/uikit-3.6.17/js/uikit-icons.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56179 - "GET /user/static/uikit-3.6.17/js/uikit.min.js HTTP/1.1" 200 OK
```

Is this a known issue or just a personal problem ;-)

regards
Chris

**Comment by kms0219kms** [comment]
static/ -> /static/ plz edit them
