### ISSUE TITLE
First accordion items doesn´t take styling using .hook-accordion-item

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4429]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.17

### Actual Behavior

When you style accordion items via hook, firt accordion item doesn´t take the changes.

### Expected Behavior

All accordion items should take the changes.

### Reproduction Link
Bacause of this line:
```
.uk-accordion > :nth-child(n+2) {
    margin-top: @accordion-item-margin-top;
    .hook-accordion-item;
}
```
In order to not apply margin to first item, firt item doesn´t take the changes.

https://github.com/uikit/uikit/blob/df8658aa013b398e8323379bbbdbe26b7a7e0dad/src/less/components/accordion.less#L41-L44

**Comment by olivercastle** [comment]
I also experience this issue in v3.10.1

Need to create a new block for all accordion items.

(scss)
`.uk-accordion > * {
    @if(mixin-exists(hook-accordion-item)) {@include hook-accordion-item();}
}

.uk-accordion > :nth-child(n+2) {
    margin-top: $accordion-item-margin-top;
}`
