### ISSUE TITLE
Idea - PineGrow Web Designer - framework plugin

### ISSUE THREAD

**Issue by pepperstreet** [uikit/uikit#443]
Just wanted to raise the idea/request for a **PineGrow** framework plugin. Would be cool to have UIkit in the editor's sidebar ;)

PineGrow Web Designer - http://pinegrow.com
_"… a desktop app for Mac, Windows & Linux that lets you mockup & design webpages faster with multi-page editing, CSS & LESS styling and smart components for Bootstrap, Foundation and other frameworks."_

Download 7-day trial desktop app…
**or** try online version - http://pinegrow.com/edit.html

Just found minor infos about plugin development:
- https://github.com/matjaztrontelj/PinegrowCommunity/wiki
- https://github.com/matjaztrontelj/Pinegrow960Grid

Thanks for listening.

---

Related topic in PineGrow Community project:
https://github.com/matjaztrontelj/PinegrowCommunity/issues/59

**Comment by gornycreative** [comment]
I will look at the docs and pull something together. I am not generally big on html editors, but this one (with the ability to view breakpoint preview that zoom to fit all on the screen at once) and easily insert properly classed elements has sold me on time saved (though for style troubleshooting I still like the compactness of Stylizer).

**Comment by pepperstreet** [comment]
@gornycreative 
Cool! Thank you for your interest. Thought I am on my own ;)

**Comment by gornycreative** [comment]
Nope. Not sure as to an ETA as I have a ton of Feb projects for some reason - but along with fixing a few abandoned wp plugins this is on the list.

**Comment by pepperstreet** [comment]
@gornycreative Any news or still plans on this? Maybe with UIKIT v3 ;)

**Comment by gornycreative** [comment]
Hi, yes. Sadly, I lost both of my parents this year and hope to have time and resources to put back into coding in the spring.
