### ISSUE TITLE
 uk-dotnav element and accessibility

### ISSUE THREAD

**Issue by Sulpher** [uikit/uikit#4430]
Lighthouse shows a problem with uk-dotnav element:

`<ul class="uk-slider-nav uk-dotnav"></ul>`
<img width="816" alt="Снимок экрана 2021-03-07 в 08 23 42" src="https://user-images.githubusercontent.com/3432048/110230271-dbe79380-7f20-11eb-8308-6448cc26a2d0.png">

In source code we see this:
`<a href></a>`
<img width="594" alt="Снимок экрана 2021-03-07 в 08 42 50" src="https://user-images.githubusercontent.com/3432048/110230315-2c5ef100-7f21-11eb-9e61-aaf972fc49f5.png">

<img width="619" alt="Снимок экрана 2021-03-07 в 08 38 47" src="https://user-images.githubusercontent.com/3432048/110230276-e144de00-7f20-11eb-873f-78459f30355b.png">

My proposal is to add **href="#"** attribute to pass the accessibility audition in Lighthouse.

**Comment by groundnation** [comment]
Agree - would be great to see these links made accessible something like;

<a href="#" aria-label="Next"></a>

or

<a href="#"><span class="sr-only>Next</span></a>

**Comment by viocassel** [comment]
@groundnation [accessibility feature](https://github.com/uikit/uikit/tree/feature/accessibility) coming soon...

**Comment by groundnation** [comment]
🙌

**Comment by janschoenherr** [comment]
Thanks, version 3.16.0 comes with built in accessibility.
