### ISSUE TITLE
Switcher and tab - tab links (ul>li) flicker when are rendered

### ISSUE THREAD

**Issue by tHesTx** [uikit/uikit#4432]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.17

### Actual Behavior
```
<ul uk-tab>
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
    <li><a href="#">Item</a></li>
</ul>

<ul class="uk-switcher uk-margin">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
    <li>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
    <li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, sed do eiusmod.</li>
</ul>
```
When page renders tab heads `<ul uk-tab><li>` all `<li>` are showed with bullets in front for a second (like normal list items), then style is applied

### Expected Behavior

Tabs heads should be rendered with styles already applied.

### My fix
    <ul class="uk-tab" uk-switcher>
        <li><a href="#">Item</a></li>
        <li><a href="#">Item</a></li>
         <li><a href="#">Item</a></li>
    </ul>

    <ul class="uk-switcher uk-margin">
        <li>Lorem ipsum dolor sit amet.</li>
        <li>Ut enim ad minim veniam, </li>
        <li>Duis aute irure dolor in reprehender</li>
    </ul>

**Comment by janschoenherr** [comment]
This is probably due to UIkit being loaded deferred.
