### ISSUE TITLE
Modal and bg-close: true - We shouldn't be able to close the modal if we dont click on the background itself

### ISSUE THREAD

**Issue by SuperKrevette** [uikit/uikit#4436]
### UIkit Version

3.6.18 and probably all the versions

### Actual Behavior

When we open a modal with the option bg-close: true (default value) then click somewhere on an element (ex: a cookie banner) outside the modal, the modal will close. This is not what we and the user want.

### Expected Behavior

We should be able to close the modal if we click DIRECTLY on the background around the modal (so the black background with the opacity), not if we click on an element outside the modal. For example, if we have another div element OVER the modal with a higher z-index and we click on it, it will close the modal. This is not logical.

Concrete example from a live website:
- A modal is opened when the user arrives on the website.
- Then GTM is loaded, which will load other scripts like a cookie banner for the GDPR.
- The cookie banner has an higher priority, so we must display it over the modal.
- If the user clicks on the Accept or Reject button, or even just on the content of the cookie banner, UiKit will close the modal without the user being able to read it.

Obviously, I can set bg-close: false but this only gets around the problem. In our case, the client want to preserve the bg-close: true. Also, we have no way of knowing when the cookie banner is shown. That's why I post this. I hope this will be fixed.

### Steps to Reproduce the Problem

- Open a modal with bg-close: true
- Display a div over the modal with a higher z-index to simulate a cookie banner
- Click somewhere on the cookie banner (button, text, content...) and the modal will close!

Demo: https://youtu.be/JpB40DgZP0A

**Comment by bornova** [comment]
Hi @SuperKrevette,
I was not able to reproduce the issue on my end.  Works as expected in this example: [https://jsfiddle.net/exp2ocgr/](https://jsfiddle.net/exp2ocgr/)

Would you be able to share your code so we can try to troubleshoot?
