### ISSUE TITLE
in offcanavas, touch scroll not working

### ISSUE THREAD

**Issue by csteri** [uikit/uikit#4438]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.18

### Actual Behavior

*In offcanvas in Chrome and Safari touch scroll does not work, but in Firefox it works.
I have attached a video.*

### Reproduction Link

*https://www.loom.com/share/1a417b33581b4b2987790d4fbd987711*

### Steps to Reproduce the Problem

1. https://getuikit.com/docs/offcanvas
2. click on the button OPEN
3. right click on the text *Lorem ipsum dolor sit amet,....* choose Inspect
4. add in element.style in <p>: max-height: 100px; overflow: scroll;
5. choose mobile mode
6. and try scroll touch

**Comment by mira-kovar** [comment]
Maybe this could help:

https://github.com/uikit/uikit/issues/4283#issuecomment-1090137990
