### ISSUE TITLE
Combine datepicker and timepicker in to a single addon (datetimepicker)

### ISSUE THREAD

**Issue by ghost** [uikit/uikit#444]
Oftentimes you need both date and time in the same field. Providing a same plugin may be a better idea because the backend code doesn't need to concatenate the two fields to parse the exact date time. This scenario is not very unusual so it'd be a good idea if somehow this functionality could be achieved via single add-on.

**Comment by BrunoKinoshita** [comment]
:+1:

**Comment by trojkat** [comment]
Why this feature was closed?

**Comment by avanmose** [comment]
I also wondered why this feature was closed.
It is obviously something that is needed by many developers.
I'm migrating my internal apps to use uikit, yet this is one of these features that is needed when creating a publishing workflow.
Currently using "jquery-ui-timepicker-addon.js".

:+1:

**Comment by srscott** [comment]
Time and date picker in one would be great.

**Comment by luetn** [comment]
+3 :-)

**Comment by csakis** [comment]
Any news on this?
+1

**Comment by brigneld** [comment]
+1

**Comment by adaniello** [comment]
👍

**Comment by vrusua** [comment]
+1 please!

**Comment by badpenguin** [comment]
+1

**Comment by petrknap** [comment]
:+1:

**Comment by vrusua** [comment]
+1 please

**Comment by Auronmatrix** [comment]
+1

**Comment by songlineboy** [comment]
did anything come of this? seems a really obvious basic need?
