### ISSUE TITLE
[Tooltip] this._unbind() is not a function during "first" tooltip hide on "uk-active" element

### ISSUE THREAD

**Issue by sly7-7** [uikit/uikit#4443]
### UIkit Version

starting from 3.5.17, still present in 3.6.18

### Actual Behavior

Say I have two button with tooltip: 
![Capture d’écran 2021-03-31 à 12 30 55](https://user-images.githubusercontent.com/1826661/113131078-075a5700-921d-11eb-808d-1fec0e366612.png)
When the non selected is hovered, its tooltip is shown/hidden correctly.
But if I hover the active one (which has a `uk-active` class), then this error is thrown: 
![Capture d’écran 2021-03-31 à 12 33 10](https://user-images.githubusercontent.com/1826661/113131269-4a1c2f00-921d-11eb-8b78-5f9cebeea9c8.png)

I'm not sure what's going on, but it seems like, during show(), it exits the function [here](https://github.com/uikit/uikit/blob/develop/src/js/components/tooltip.js#L44) before the _unbind() function is defined, 
but during hide(), the escape hatch [isToggled](https://github.com/uikit/uikit/blob/develop/src/js/components/tooltip.js#L65) is not hit, and then is trying to call the undefined `unbind()` method.
Not sure is that simply the condition should be inversed ?

### Expected Behavior

The tooltip should show and no error thrown

### Reproduction Link

https://codepen.io/sly7-7/pen/eYgBqwX

It's happening here, in this simple codepen, when you "switch" from the active to the other. (open the developer tools to see the error)

Without the 'uk-active' class there is no error, and seems to work well

**Comment by janschoenherr** [comment]
Resolved with https://github.com/uikit/uikit/commit/836b329b85ee020550c90fbb13c79a7e15a6192d in 3.6.19.

**Comment by sly7-7** [comment]
@janschoenherr Nice, thank you :)
