### ISSUE TITLE
Modal tab navigation issue

### ISSUE THREAD

**Issue by Marinnnnce8** [uikit/uikit#4446]
### Actual Behavior

When e.g. Lightbox is opened and if I try to navigate through modal close, previous and next buttons it's not possible to do that using tab key and tab is navigating through the page 'ignoring' modal's focusable elements. I can go through slides using left and right key and close it using esc key, but it's not the best for accessibility because users should have focus inside the modal and they should know where the current focus is.

### Expected Behavior

*What should have happened?*

 It would be good for accessibility if you're able to add tab focus on modal's focusable elements when the modal is opened and restrict tab navigation for the rest of the page.

Thanks in advance.

**Comment by janschoenherr** [comment]
I believe this to be fixed. If the issue persists, please comment.
