### ISSUE TITLE
Click/input events inside accordion title

### ISSUE THREAD

**Issue by Pashted** [uikit/uikit#4450]
Hi. I have an issue with click/input events on checkboxes and radio buttons. I cant change state of this inputs when i place them inside accordion title. Currently im using custom accordion script in my projects cause of this bug.

### UIkit Version
Chrome 89.0.4389.114
Empty page + base markup + uikit 3.6.19

### Actual Behavior
1. If i directly click input nested in accordion title related accordion content just open/collapse and it doesnt change input states (input event not fires).
2. Click on label tags doesnt fire click/input events on nested inputs in 1st case. But It happens without accordion script (2nd case).

### Expected Behavior
1. Mouse click or pressing space key over focused input should change state of checkboxes and radio buttons.
2. Clicks over label tag should fire click event on nested inputs.

### Reproduction Link
https://codepen.io/Pashted/pen/wvgpXoR

### Steps to Reproduce the Problem

1. Open codepen.
2. Open console (dev tools)
2. Click inputs.

**Comment by janschoenherr** [comment]
You can set the `toggle` option to a different selector.

https://getuikit.com/docs/accordion

An `<input>` within an `<a>` isn't valid. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#properties
