### ISSUE TITLE
W3C CSS validation errors

### ISSUE THREAD

**Issue by Dale08** [uikit/uikit#4451]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.19

### Actual Behavior

Checking on W3C validator has this error when using your code from an example https://getuikit.com/docs/navbar
"Attribute uk-navbar not allowed on element nav at this point."
https://prnt.sc/11e4fgp

### Expected Behavior

There aren't W3C validator errors using your library, you should jus add "data-" for all custom HTML data attributes 

### Steps to Reproduce the Problem

1. Go to W3C validator https://validator.w3.org/#validate_by_input
2. Paste correct HTML5 page content with your code, for example in body tag
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
            <li class="uk-active"><a href=""></a></li>
            <li class="uk-parent"><a href=""></a></li>
            <li><a href=""></a></li>
        </ul>
    </div>
</nav>
3. Check.

Thanks and regards

**Comment by mattfletcher** [comment]
If you add data- to any uk- attribute, it will work as expected, and validate. But they work with or without data- so it's up to you as a developer whether brevity and readability, or W3C validation is more important to you.

**Comment by Dale08** [comment]
Hello!
Many thanks for your answer.
Why don't your team use this "data-"? Because developers of the plugin from
the Codecanyon use your library and tell me that if you don't use "data-"
that means that this is standard.

Thanks and regards

ср, 14 апр. 2021 г. в 19:58, Matt Fletcher ***@***.***>:

**Comment by mattfletcher** [comment]
I'm not a UIkit developer, so I can't speak for them, just a happy user. Personally, I always add the data- prefix, purely because my IDE highlights the attributes otherwise. But it's your choice, add them, or don't, whichever works best for you.

**Comment by mattfletcher** [comment]
Both options are documented here: https://getuikit.com/docs/javascript#component-usage
