### ISSUE TITLE
Autoplay Inview video showing nothing on iOS

### ISSUE THREAD

**Issue by Tschipp** [uikit/uikit#4453]
### UIkit Version
3.6.20

### Actual Behavior
A video set to autoplay inview doesn't show up at all on iOS:
This is from the docs site:
![image](https://user-images.githubusercontent.com/11649893/116154974-bccbdd80-a6e9-11eb-9b36-ca74a549a610.png)

### Expected Behavior
The video should show up, if possible

### Steps to Reproduce the Problem

1. Add 
```html
<video src="https://yootheme.com/site/images/media/yootheme-pro.mp4" loop muted playsinline uk-video="autoplay: inview"></video>
```
2. View site on iOS

**Comment by janschoenherr** [comment]
This will be fixed with next release.
