### ISSUE TITLE
Lightbox does not recognize images with the extension .jfif

### ISSUE THREAD

**Issue by ph-woz** [uikit/uikit#4456]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.21

### Actual Behavior

*What happened? Screenshots please, if relevant!*

### Expected Behavior

*What should have happened?*

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

1.
2.
3.

**Comment by dramspro** [comment]
Hi. I checked docs and its look like .jfif extesinon is mistake. Image file with JFIF metadata must have .jpg (or .jpeg) extension.
Se this [quora.com/What-is-a-JFIF-file](https://www.quora.com/What-is-a-JFIF-file) answer or official standart: https://www.itu.int/rec/T-REC-T.871-201105-I/en

I think uikit lightbox do not need to recognize .jfif as image, but [.avif](https://caniuse.com/avif) it must (if it not yet).

@ph-woz, please explain your case with .jfif

**Comment by tiomanisland** [comment]
Solution is simple. Edit /dist/js/glightbox.js

Line 2006, add "jfif":

        if (url.match(/\.(jpeg|**jfif**|jpg|jpe|gif|png|apn|webp|avif|svg)/) !== null) {

Now it will work!

**Comment by meilechwieder** [comment]
@tiomanisland can you make a pull request?

**Comment by tiomanisland** [comment]
I have no idea how to do that. I fixed it and I added .jfif to the original
code - now it works!

**Comment by tiomanisland** [comment]
> @tiomanisland can you make a pull request?

I don't know how to use that. I have never done pull request :-(

**Comment by janschoenherr** [comment]
Added with https://github.com/uikit/uikit/commit/9cb7293e5adc9f0bc2a617bf664b7ca4dfe5d200
