### ISSUE TITLE
UIkit.util.off does not appear to work

### ISSUE THREAD

**Issue by raf66** [uikit/uikit#4463]
### UIkit Version

3.6.21

### Actual Behavior

Documentation for "UIkit.util.on" exists and the feature works.  There is no documentation on "UIkit.util.off".  Does the feature exists?  I tried:

`UIkit.util.off('#my-modal', 'shown');`

But the event still fires.  

### Expected Behavior

Need the ability to turn off the callback for an event.  This is especially important for SPAs.

**Comment by janschoenherr** [comment]
UIkit.util.off has to be called with the same listener function, its `on` function was called with.

Also see: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

The `UIkit.util.on` function returns an `off` function.
