### ISSUE TITLE
Using / for division is deprecated in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by lesaff** [uikit/uikit#4467]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.22

### Actual Behavior

When compiling, Dart Sass threw a warning. I am showing one of many below:
```
: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($global-gutter, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

247 │ $card-header-padding-vertical: round($global-gutter / 2) !default;
```

### Expected Behavior

*What should have happened?*

### Reproduction Link
https://sass-lang.com/d/slash-div

**Comment by shirakomamu** [comment]
I'm also getting this issue, using `sass` as a dependency.

It seems the deprecation warning was added in version `1.33.0`, which was just [released a few days ago](https://github.com/sass/dart-sass/releases/tag/1.33.0).

**Comment by giraffekey** [comment]
Doesn't work with libsass sadly, which apparently millions are still using. Shame considering [libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated).

Should uikit make a move and drop support for libsass or should it continue to support a deprecated package indefinitely?
