### ISSUE TITLE
Animation + Scrollspy doesn't work the first time visible

### ISSUE THREAD

**Issue by andreadip** [uikit/uikit#447]
Hallo,
I'm experiencing a strange problem (an all browser i tested - chrome, opera, firefox) : the animations called by scrollspy are showing just after the second time the element appears on the monitor. That apllies to everything is not shown when you load the page.
That means that the first time the elements (images mainly) are shown without animation, but the second time that i visualize them without refresh they are animated. 
I installed latest uikit .js (not css yet because i did some change).

The problem it's to be seen here: http://helius-monitoraggio-fotovoltaico.it/2/interfaccia.php . That's the code i used: 
`<img src="img/dashboard.png" alt="dashboard impianti fotovoltaici" title="dashboard impianti fotovoltaici" class="uk-animation-slide-left  uk-scrollspy-init-inview uk-scrollspy-inview" data-uk-scrollspy="{cls:'uk-animation-slide-left',  delay:200,  repeat: true}" >`

**Comment by mattmagi** [comment]
Hi,

I am having this issue as well, but its due to the way my page is loading, I'm using a preloader and the animation is being triggered behind it. 

Is there anyway to set it to only repeat X amount of times? Such as twice? 

Thanks!
