### ISSUE TITLE
Scrollspy getting stuck in loop - continually animating elements not in viewport

### ISSUE THREAD

**Issue by maccyd10** [uikit/uikit#4470]
To replicate, initialize scrollspy after dom load:

- `UIkit.scrollspy(selector, options)`
- Scroll element out of viewport.
- Check element in inspector.
- Check cpu usage of browser.

I also noticed partial classes remaining on element when scrolling back into viewport. 

eg with `{ cls : 'uk-animation-slide-bottom-medium' }`

element is left with `<div class="-bottom-medium uk-scrollspy-inview -bottom-medium">`

Looks like potentially an issue with this commit:

https://github.com/uikit/uikit/commit/12c0049b824d892a5c83ded211f8821551422e6b#diff-81eb5c729f78e246932dcff8970ac7dbf309b1ec93bfa5f2c1a62fbaa7ad0cec

**Comment by janschoenherr** [comment]
Sorry for the late reply. Could you add a codepen where the issue can be replicated?
