### ISSUE TITLE
Notifications: Refused to apply inline style because it violates the following Content Security Policy directive: ...

### ISSUE THREAD

**Issue by itsHusky** [uikit/uikit#4473]
### UIkit Version
3.6.22

### Actual Behavior
Using a Content Security Policy, I am getting the error 
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src cdn.jsdelivr.net". Either the 'unsafe-inline' keyword, a hash ('sha256-gGKtWVlwtb9dj1Sa7K4ybKpqUOE61nkachaCJ1LfmFY='), or a nonce ('nonce-...') is required to enable inline execution.` when creating a notification using js.

### Expected Behavior
Not getting an error from the Content Security Policy used. The notification does work as expected, though.

### Reproduction Link
https://codepen.io/itsHusky/pen/oNZawNB?editors=1111
(You will have to open the console via Inspect Element, as the console in codepen itself does not show the error.) Also, the codepen shows a lot of errors due to the inline resources in the html file. Even without these errors, the inline style error still exists.

### Steps to Reproduce the Problem

1. Click the button `Show Notification` (in the codepen).
2. Open up the console via Inspect Element from that codepen.

**Comment by janschoenherr** [comment]
I don't think this has to do with UIkit itself?
