### ISSUE TITLE
Tab: Left and right tab title align bug. (v3.7.0)

### ISSUE THREAD

**Issue by gonenli** [uikit/uikit#4477]
As seen on the [official page](https://getuikit.com/docs/tab), left and right tab titles are centered. 
`.uk-tab>*>a { 
justify-content: center;
}`

**Comment by AlekVolsk** [comment]
It's about aligning tabs relative to the switcher, not aligning the titles of the tabs themselves

**Comment by gonenli** [comment]
Fixed [v.3.7.2](https://getuikit.com/changelog)
