### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by nzimas** [uikit/uikit#4483]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.7.0

### Actual Behavior

*What happened? Screenshots please, if relevant!*

Uikit for Gantry 5 is a Gantry 5 atom that loads the Uikit library upon request from different Gantry partices 
Several Gantry particles that rely on Uikit do not display properly.

Chrome's JS console is throwing the following error:

```
Cannot read property 'offsetWidth' of undefined
uikit.min.js:3 TypeError: Cannot read property 'offsetWidth' of undefined
    at e.read (uikit.min.js:3)
    at uikit.min.js:3
    at e.<anonymous> (uikit.min.js:3)
    at uikit.min.js:3
    at xn (uikit.min.js:3)
    at vn (uikit.min.js:3)
    at uikit.min.js:3
xn @ uikit.min.js:3
vn @ uikit.min.js:3
(anonymous) @ uikit.min.js:3
requestAnimationFrame (async)
bn @ uikit.min.js:3
read @ uikit.min.js:3
(anonymous) @ uikit.min.js:3
(anonymous) @ uikit.min.js:3
(anonymous) @ uikit.min.js:3`

```

### Expected Behavior

*What should have happened?*

The different Gantry 5 particles that load Uikit (slideshow, image rotator) should load without visual glitches.

### Reproduction Link

https://codepen.io/nzimas/pen/BaRpxmB

### Steps to Reproduce the Problem

1. Install Joomla + Gantry 5 + Hydrogen theme

2. Install Uikit for Gantry 5 [https://www.inspiretheme.com/downloads/freebies](https://www.inspiretheme.com/downloads/freebies)

3.  Replace templates/g5_hydrogen/custom/uikit/uikit.min.js with the 3.7.0 version of the file.

**Comment by janschoenherr** [comment]
your codepen triggers a password request

**Comment by nzimas** [comment]
Do you mean the codepen URL itself or the code I’ve pasted there?

**Comment by janschoenherr** [comment]
This one: https://codepen.io/nzimas/pen/BaRpxmB

**Comment by nzimas** [comment]
Weird. I can access https://codepen.io/nzimas/pen/BaRpxmB <https://codepen.io/nzimas/pen/BaRpxmB> even without being logged in,

**Comment by mattfletcher** [comment]
I get an .htpasswd-style login prompt for https://webdev.semantyca.com

**Comment by nzimas** [comment]
That’s expected behaviour if you try to navigate.
This isn’t needed to verify the report, however.
The issue happens right on the homepage when it loads.
I’ve merely dumped the rendered source of the homepage onto codepen.

**Comment by mattfletcher** [comment]
No, that login appears as soon as you try to follow the codepen link.

**Comment by nzimas** [comment]
I see. The rendered source is invoking protected resources.
Will disable .htaccess and revert when it’s done.
