### ISSUE TITLE
A search bar in documentation of UIKIT

### ISSUE THREAD

**Issue by hihabib** [uikit/uikit#4488]
I want to use uikit for my business project but it will helps me a lot if you add a searchbar on official documentation to get the components easily. 

add a searchbar here please. https://getuikit.com/docs/introduction

**Comment by mxmissile** [comment]
Google with this filter works perfect, no need for a search.

`site:getuikit.com/docs`

**Comment by janschoenherr** [comment]
We are using Algolia now.

**Comment by hihabib** [comment]
Thanks for integrating algolia.
