### ISSUE TITLE
Scrollspy reverse animation fade becomes visible again after fade

### ISSUE THREAD

**Issue by AversaConsulting** [uikit/uikit#4491]
### UIkit Version

3.7.2

### Actual Behavior

With a scrollspy initiated reverse animation, the element re-displays at the end. This used to work ok.

### Expected Behavior

The element should fade out and then stay hidden.

### Reproduction Link

```
<div id="notavail" class="uk-position-center uk-overlay uk-overlay-default uk-position-medium uk-scrollspy-inview  " uk-scrollspy="cls: uk-animation-reverse uk-animation-fade; delay: 5000; hidden:false;">
                <div class="uk-card uk-card-default uk-card-body uk-overlay uk-overlay-default">
                    <div class="uk-card-title">Sorry!</div>
                    <p><strong>We have no start dates for your chosen month and duration.</strong></p>

                </div>
            </div>
```

**Comment by janschoenherr** [comment]
We are removing the animation classes after the animation because those are causing other issues (e.g. stacking context). Unfortunately this breaks the above example.
