### ISSUE TITLE
Switcher and disabled controls

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4494]
### UIkit Version

3.7.2

### Actual Behavior

When using the switcher component and some of the controls (tabs, subnav ...) are disabled, the toggling of the `uk-active` class of these associated controls is getting messed up.

The expected content is toggled correctly.

### Expected Behavior

The `uk-active` class of the corresponding control is set according to the displayed content.

### Reproduction Link

https://codepen.io/lumelomser/pen/yLbwBME

### Steps to Reproduce the Problem

1. Open reproduction link.
2. Click through tab/subnav items.

**Comment by Bar-Rabbas** [comment]
Hello! I believe in such complex cases you should use component options like "connect" and "toggle" to separate different widgets.

**Comment by Bar-Rabbas** [comment]
I believe  #4396 is relevant to this one.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/d4aecc3e68573ed1bda9ed125de63e8da2a9650a
