### ISSUE TITLE
Trigger event when countdown stops and possibly starts

### ISSUE THREAD

**Issue by Bar-Rabbas** [uikit/uikit#4500]
Hello! It would be nice to have an opportunity to listen for a "stop" event (and probably "start" for some other cases) when countdown reaches its target so I could hide it or make an ajax call.

Right now I have to modify uikit sources in order to use this feature.

**Comment by marcorensch** [comment]
+1

**Comment by janschoenherr** [comment]
UIkit 3.16.0 adds `countdownstart`, `countdownstop` and `countdownend` events to Countdown component.
