### ISSUE TITLE
Toggle Modal button onClick not working

### ISSUE THREAD

**Issue by JYOTIPARASHAR** [uikit/uikit#4502]
Building a react application . The application have a data-uk-modal whch triggers on uk-toggle . I want to open a file uploader on click of a button inside the modal but the onClick event isn't working & the function isn't callled . Kindly provide the solution. 

Codepen link -
https://codepen.io/Jyoti-18/pen/gOWNyYR

**Comment by Bar-Rabbas** [comment]
Hello! I do not see onClick events in your code. May be you could reduce your code. Try to follow examples from this page: https://getuikit.com/docs/upload
