### ISSUE TITLE
uk-form-custom="target: true" for <input type="file"> overrides default value of next input sibling

### ISSUE THREAD

**Issue by tHesTx** [uikit/uikit#4504]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.7.2

### Actual Behavior

*If I try to insert a default value for an upload input sibling of `<input type="file">`, that value is overridden with nothing*

### Expected Behavior

*I would expect to be able to have a default value with fileName (not file itself), if no upload is added*
What I'm trying to achieve is to have jQuery validation on that second input field

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem
    <div class="uk-margin" uk-margin>
        <div uk-form-custom="target: true">
            <input type="file">
            <input class="uk-input uk-form-width-medium" type="text" placeholder="Select file" disabled>
        </div>
        <button class="uk-button uk-button-default">Submit</button>
    </div>
1. If I try to put a value on `<input class="uk-input uk-form-width-medium" type="text" placeholder="Select file" disabled value="some text here">` it will not be showed, also `$('input').val()` will show `""`
2. Value is overridden by uikit, because when I upload a file, input have a value

**Comment by Bar-Rabbas** [comment]
I'm afraid you can not do it for security reasons. The only way to set the value of a file input is by the user to select a file.
Otherwise you would be able to create a js that automatically uploads a specific file from the users's computer.
