### ISSUE TITLE
beforeshow event doesn't fire on tooltip

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4508]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.7.3

### Actual Behavior

`beforeshow` event doesn't fire

### Reproduction Link

https://codepen.io/papazetis/pen/JjJWQap

**Comment by Bar-Rabbas** [comment]
Hello! You use selector ".uk-tooltip.uk-active" and .uk-active class has not been added to the button before this event. Try to use selector "button.uk-tooltip" to catch the beforeshow event.

**Comment by papazetis** [comment]
@Bar-Rabbas 

Ohhh I missed that. That worked.

Thanks.
