### ISSUE TITLE
Incompatibility issue when using uk-accordion and custom JS

### ISSUE THREAD

**Issue by keev-studio** [uikit/uikit#4509]
### UIkit Version

last version of UiKit 3.7.3 (tested also vith v2.x same behavior)

### Actual Behavior

My JS players behaves strangely (play button is stuck and progress bar not working), when uk-accordion is used.

By removing uk-accordion from `<ul>` makes my JS working normaly.

### Expected Behavior

If uk-accordion is not used or removed from `<ul>` tag JS players behave normally.

### Reproduction Link

https://codepen.io/keev/pen/MWmxRWa

### Steps to Reproduce the Problem
1. codepen: https://codepen.io/keev/pen/MWmxRWa
2. click on first accordion, media player appears. By clicking on Play button, audio starts playing but play button is stuck and progress bar not working. The same behavior in others accordions/players.
3. By removing uk-accordion from `<ul>`tag, we can see all players and they all work as expected

To me looks as some incompatibility with UiKit. Can someone tell me if there is a way to debug/fix this ? thank you

**Comment by Bar-Rabbas** [comment]
Hello! Try to remove preload="None" from your code.

**Comment by keev-studio** [comment]
> 
> 
> Hello! Try to remove preload="None" from your code.

Hi, thanks for reply. This does not help. I also tried to change into "auto" with no effect.

**Comment by Bar-Rabbas** [comment]
You have also changed "video"  to "audio" and now it does not play even with disabled uk-accordion. preload="metadata" also helps. Change it back to video and it will work. Any way it's not UIKIT's problem but mediaelements' or the way youtube works. Try other audio sources.

**Comment by Bar-Rabbas** [comment]
Here is a working example for you https://codepen.io/Appolinariy/pen/MWovNJa

**Comment by keev-studio** [comment]
> 
> 
> You have also changed "video" to "audio" and now it does not play even with disabled uk-accordion. preload="metadata" also helps. Change it back to video and it will work. Any way it's not UIKIT's problem but mediaelements' or the way youtube works. Try other audio sources.

Hi Bar-Rabbas, thanks again for your input
If you ONLY remove uk-accordion in `ul ` tag and leave everything else as it is in my original codepen (https://codepen.io/keev/pen/MWmxRWa) everything works. This means that uk-accordion (JS from Uikit) makes mediaelements not working as supposed if accordion applied.

I choose to use mediaelements and `<audio>` tag by purpose as by using this solution I can play youtube videos without showing the video( basically using it as audioplayer) + looks like I am skipping all the adverts.

If there is another option to play audio from YT videos without using 3rd party I will be happy to know.

thanks again

**Comment by keev-studio** [comment]
> 
> 
> Here is a working example for you https://codepen.io/Appolinariy/pen/MWovNJa

yes, if I want to play YT video I will be using `video` html5 tag or UiKit own component (https://getuikit.com/docs/video) but for me is important to do not show video or any of YT branding/controls (excuse YT ))

**Comment by Bar-Rabbas** [comment]
Well, I've tested it more thoroughly and it really seems to have some glitches. But it works just fine if you use uk-accordion="animation: false". Let me know if it works for you.

**Comment by keev-studio** [comment]
> 
> 
> Well, I've tested it more thoroughly and it really seems to have some glitches. But it works just fine if you use uk-accordion="animation: false". Let me know if it works for you.

Hi Bar-Rabbas,

your solution is exactly what I was looking for. I really appreciate you time helping me with my issues. Lets sun shine on your head.

Have a nice day.
