### ISSUE TITLE
Filter event afterFilter not working

### ISSUE THREAD

**Issue by bdthemes** [uikit/uikit#4510]
Hi, Filter event afterFilter not working since 3.3.7 please fix this issue. 

### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.7.3

### Actual Behavior

Please check version 3.3.6: https://codepen.io/InnovantTech/pen/qBdKVBY

### Expected Behavior

The same feature not working when I using version 3.7.x: https://codepen.io/bdthemes/pen/abwWrdM

### Reproduction Link

https://codepen.io/bdthemes/pen/abwWrdM

**Comment by bdkoder** [comment]
Yes, this is a bug on the newer version of UIKIT. I am facing this same issue with my application. I am waiting for the solution.

**Comment by janschoenherr** [comment]
@bdthemes seems to work fine in your installation

I did a `console.log()` in your event handler.

**Comment by bdthemes** [comment]
Hi @janschoenherr, 

Filter Click working fine (all, filter 1, filter 2, etc)

But Search not working (that working fine until 3.3.6 version https://codepen.io/InnovantTech/pen/qBdKVBY) 

Please try to search with item name (Div 1, Div 2, etc)  it's not working, even look at `console.log()` it's not calling the second time.

**Comment by Bar-Rabbas** [comment]
It seems to me that this issue is a duplicate of #4421 At least it mentions the same codepen example. Am I right?

**Comment by bdthemes** [comment]
Thanks @Bar-Rabbas, it's working after added that line as you told 😀

**Comment by Bar-Rabbas** [comment]
I'm glad to help you! Best regards!

**Comment by bdkoder** [comment]
Again the same issue facing with 3.16.3
Anyone can help?

https://codepen.io/bdthemes/pen/abwWrdM?editors=0011
