### ISSUE TITLE
Animation delay feature not documented: https://getuikit.com/docs/animation

### ISSUE THREAD

**Issue by studio-sixtyeight** [uikit/uikit#4518]
Animation delay feature not documented: https://getuikit.com/docs/animation

_Originally posted by @nitras in https://github.com/uikit/uikit/issues/3703#issuecomment-822852102_

**Comment by Bar-Rabbas** [comment]
I think its not a UIKIT feature but a part of standard css https://www.w3schools.com/cssref/css3_pr_animation-delay.asp and of course you may use it in conjunction with UIKIT.
