### ISSUE TITLE
Offcanvas + scrollspy animation flickering and not working

### ISSUE THREAD

**Issue by kuwts** [uikit/uikit#4532]
### UIkit Version

3.8.0

### Actual Behavior

When using the Scrollspy component in an off-canvas with the repeat set to true (e.g. uk-scrollspy="target: > .fade-me; cls: uk-animation-slide-bottom-small; repeat: true;"). It will add the animation on the first open, but in subsequent opens of the off-canvas the animation will only flicker. 

### Expected Behavior

The animation should repeat on each offcanvas open.

**Comment by mynameisfreedom** [comment]
I can confirm this is true.

**Comment by janschoenherr** [comment]
Will close this for now, as the scrollspy has been refactored. If the issue persists, please comment.
