### ISSUE TITLE
dotted rect around clicked links

### ISSUE THREAD

**Issue by agreif** [uikit/uikit#4539]
### UIkit Version

3.9.2

### Actual Behavior

just updated from 3.6.15 to 3.9.2 and clicking a link <a> tag a dotted rect appears around the link. In former version this did not happen. How can I disable the dotted rect? I could not find a hint in the doct to hide it. 
Problem occures on Firefox 78.15.0esr (64-bit) Mac OS X
But **not** on Chrome 87.0.4280.88
And does **not** occur on FIrefox 93

### Expected Behavior

CLicking a link <a> tag should not show a dotted rect around the link area

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

1. go to https://getuikit.com/docs/link
2. click on some link
3. the dotted rect appears

**Comment by janschoenherr** [comment]
Could you check again, it seems current Firefox version is 74.

**Comment by agreif** [comment]
Hi,

my "About Firefox" Menu has this version:

https://www.mozilla.org/en-US/firefox/78.15.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=whatsnew



Alex.

**Comment by janschoenherr** [comment]
Sorry, got the version number wrong in my previous reply. There seems to be a new ESR (Firefox 91.3) release, does that solve the issue?

**Comment by agreif** [comment]
on Firefox 93 it works fine. I think I only use an old browser on an old laptop. It seems that somethink changes in uikit that now draws this rect on old browsers. I think it wont be investigated further on your side?

**Comment by janschoenherr** [comment]
We refactored the focus states with one of the last releases. As it seems to work with ESR (Firefox 91.3) I will close the issue.
