### ISSUE TITLE
Deprecated IE browser detection method

### ISSUE THREAD

**Issue by meatpaste** [uikit/uikit#4542]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.9.2

### Actual Behavior

IE Browser detection triggers a console issue in Google Chrome, this negatively impacts the Lighthouse Best Practice score of web pages.
[Description of new requirements at the Chromium Blog](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html)

/src/js/util/env.js - Line 5

### Expected Behavior

No console issue triggered

### Reproduction Link

https://getuikit.com/

### Steps to Reproduce the Problem

1. Open dev tools
2. Visit the page

**Comment by janschoenherr** [comment]
We no longer detect IE :-)
