### ISSUE TITLE
Watch does not work on changes made to the custom folder

### ISSUE THREAD

**Issue by bariskrdrl** [uikit/uikit#4544]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.9.3

Hi, as always I created my project and yarn watch didn't work. I noticed that yarn has been updated to watch-less. But it doesn't compile the changes made in the custom folder as before.

Thank you for your help.

**Comment by janschoenherr** [comment]
Will be fixed with next release. For now you can use `yarn watch-less`

**Comment by bariskrdrl** [comment]
My problem is that the watch feature is not listening to the files. When I change the variables, no compilation occurs. @janschoenherr
