### ISSUE TITLE
Scroll handling of Sortable component

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#4552]
### UIkit Version

v3.5.11

### Actual Behavior

Elements with `overflow: hidden` start scrolling when a sortable item is dragged over.

### Expected Behavior

Elements with `overflow: hidden` should not scroll when a sortable item is dragged over.

### Description

Details of the issue are described here:
[Unexpected scrolling of elements when dragging items of Sortable component](https://github.com/uikit/uikit/discussions/4495)

So, is the described behaviour the expected behaviour?

Or, as already mentioned in the description, was it just forgotten to pass the `/auto|scroll/` parameter when calling `scrollParents()` when refactoring the Sortable compontent?

Would it be possible to add an option which variant should be used ("include" or "exclude" elements with `overflow: hidden`) when initializing the Sortable component?

**Comment by yu-yang-halo** [comment]
您好，已收到您的邮件。我将在假期结束后，尽快给您回复。
