### ISSUE TITLE
Error since v3.9.3 using Parcel 2 + Vue 3

### ISSUE THREAD

**Issue by KaKi87** [uikit/uikit#4561]
### UIkit Version

- v3.9.2 tested with no issue
- v3.9.3 & v3.9.4 tested with issue

### Actual Behavior

The following error is thrown from both `uikit.min.js` & `uikit-icons.min.js`

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function
```

Which, among other things, prevent icons & tooltips from working.

### Expected Behavior

No error is thrown.

### Reproduction Link

https://git.kaki87.net/playsearch.kaki87.net/v2-web

### Steps to Reproduce the Problem

1. Clone
2. Install dependencies
3. Run start script
4. See absence of issue
5. Kill start script
6. Change `uikit` dependency version to `3.9.4`
7. Run start script
8. See issue

---

Thanks

**Comment by mischnic** [comment]
It seems to be fixed after upgrading Parcel to the latest version:
```json
  "devDependencies": {
    "@parcel/transformer-image": "2.2.1",
    "@parcel/transformer-vue": "2.2.1",
    "parcel": "2.2.1"
  },
```
