### ISSUE TITLE
uk-slider issue in RTL layout.

### ISSUE THREAD

**Issue by sonvnn** [uikit/uikit#4562]
### Actual Behavior

- uk-slider does not work in RTL layout. Please check my url https://lefala.jollyany.co/index.php/ar/
- It's good in LTR layout https://lefala.jollyany.co/index.php/en/

May you give me some advise about it?

Thanks & Best Regards,
Sonny

**Comment by Cornershot-el** [comment]
Yes, You are Right
Actually My problem with Uikit Slider is that not working in RTL

**Comment by janschoenherr** [comment]
Please use the latest version.
