### ISSUE TITLE
Height issue with uk-cover

### ISSUE THREAD

**Issue by Marinnnnce8** [uikit/uikit#4564]
UIkit Version
3.10.0

Actual Behavior
just updated from 3.9.4 to 3.10.0 and after running the project I got [this](https://prnt.sc/26f5izz) issue with 'uk-cover' width the combination of min-height in CSS.

The problem occurs on:

Chrome Version 97.0.4692.71 (Official Build) (64-bit) Windows 10
Opera Version 82.0.4227.58
Firefox Version 96.0.1
Edge Version 97.0.1072.62

Expected Behavior
The image should render as the cover image - https://prnt.sc/26f5kni.

Reproduction Link
[A minimal Codepen that can reproduce the bug. Start with this Codepen template](https://codepen.io/Midzuchi/pen/wvrZgPQ)

**Comment by janschoenherr** [comment]
Thanks, fixed with https://github.com/uikit/uikit/commit/44e702be43029133a3e608d1911d97710276a6e2.
