### ISSUE TITLE
'inview' event not firing on uk-scrollspy element

### ISSUE THREAD

**Issue by danielfeather** [uikit/uikit#4565]
I am using ```uk-scrollspy``` for infinite loading of posts on a blog and we have been using this fine ever since we recently upgraded the version past ```uikit@3.5.12```.

We used to be running version ```uikit@3.1.9``` until fairly recently when I updated our front-end to use the latest version of uikit which at the time of writing is ```uikit@3.10.1```

From initial investigations it seems to be down to a fix in the ```uikit@3.5.13``` release that has caused this. I suspect 19b39086d0d480f0960ad80bfb85f701a0f5614e

If anyone could shed any light on the problem it would be most appreciated.

### UIkit Version

This issue occurs on the latest stable release of 3.10.1

### Actual Behavior

When a post element with ```data-uk-scrollspy``` scrolls into view, the ```inview``` event does not fire and therefore the event listener does not run the ```loadMore``` Vue method causing the infinite loader in the example below to stop loading more post pages.

### Expected Behavior

The 'inview' event should fire when one of the post scrollspy elements scrolls into view and trigger the eventListener to load more post pages.

### Reproduction Link

I have used CodeSandbox to reproduce the issue instead of CodePen. Hope this is ok. Under dependencies you can change between the different uikit versions. I have set the version to ```uikit@3.10.1``` but if you change the version to anything lower than ```uikit@3.5.13``` e.g ```uikit@3.5.12``` the example works fine.

https://codesandbox.io/s/condescending-framework-tbuz0?file=/src/components/InfinitePosts.vue

### Steps to Reproduce the Problem

1. Open the CodeSandbox link above.
2. In the preview pane, scroll to bottom of posts where you can see the loading spinner.

**Comment by janschoenherr** [comment]
The div you've put uk-scrollspy on has a width and height of 0. Because of that, it's never in view. If you give it a height and width of 1px it works again.

**Comment by danielfeather** [comment]
Thanks @janschoenherr that makes sense, really appreciate the help. I have updated my example with a solution to the problem.
