### ISSUE TITLE
Update (3.10.0) broke sticky again

### ISSUE THREAD

**Issue by Hurmeli** [uikit/uikit#4568]
A simple sticky element in sidepanel on site I'm working on stopped working with 3.10.1. If I downgrade back to 3.9.4 version it starts working again.

I updated from 3.9.4 so it seems 3.10.0 fix on sticky broke it

Unfortunately I can't give more details right now, but I'll update / post here once I can digg into it.

**Comment by janschoenherr** [comment]
The upcoming release will contain several fixes for the Sticky component. Please check with the current dev version

https://www.jsdelivr.com/package/npm/uikit?version=3.11.2-dev.fb043abc2
