### ISSUE TITLE
Scss compiler error

### ISSUE THREAD

**Issue by t3touch** [uikit/uikit#4576]
I'm struggling to use the uikit SCSS. Following this docs https://getuikit.com/docs/sass I got the following error compiling with scssphp

(1/2) ScssPhp\ScssPhp\Exception\CompilerException
`
$amount: Expected 5% to be within 0% and 1%: my-project/Resources/Public/Scss/uikit/src/scss/variables-theme.scss on line 452, at column 1 Call Stack: #0 import my-project/Resources/Public/Scss/uikit/src/scss/variables-theme.scss my-project/Resources/Public/Scss/layout.scss on line 12 #1 import my-project/Resources/Public/Scss/layout.scss (unknown file) on line 1`

It seems that the fadein() function produces this error.

`$inverse-form-focus-background: fadein($inverse-form-background, 5%) !default;`

**Comment by chriswthomson** [comment]
I'm also getting this when compiling the SCSS. The fadein function isn't getting translated. This is dart sass inside a gulp pipeline.

**Comment by mcakircali** [comment]
The SCSS versions are still not fixed/updated.

Could someone please build and update the SCSS with the current fixe(s)?
