### ISSUE TITLE
Easier color overrides

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#458]
As UIkit grows and I've began to really dig into it, I've noticed the duplication of color variables where creating color schemes becomes quite a mess. For example, the "base" color that comes with UIkit is `#07D` which is mentioned 13 times across multiple components. If I want to override that color, I need to replace that variable reference that may times as well. I think it would be IMMENSELY easier to come up with more sane color variables, like:
- `@primary-color`
- `@secondary-color`
- `@alert-color`
- `@success-color`
- `@danger-color`

etc..

I'd definitely be up for the task if all find this useful, just seems like a huge opportunity missed that wouldn't' add convolution, it'd add the ability for easier overrides while still allowing for further customization. Thanks!

**Comment by amine-louni** [comment]
i can not find that file
