### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'naturalWidth')

### ISSUE THREAD

**Issue by designconcepts** [uikit/uikit#4584]
### UIkit Version

3.11.1

### Actual Behavior

I have added a hero div with following code:

`<div id="hero" class="uk-background-cover" data-src="path/to/image.jpg" data-uk-img data-uk-height-viewport="offset-top: true; min-height: 450" data-uk-parallax="bgy: -100"></div>`

I get on the initial load this JavaScript error in the console

_TypeError: Cannot read properties of undefined (reading 'naturalWidth')_

The parallax effect doesn't work because of this JavaScript error.
If I visit the page again I get no error.

### Expected Behavior

No JavaScript error on the initial load.

### Reproduction Link

Codepen: https://codepen.io/designconcepts/pen/QWOXpXO

### Steps to Reproduce the Problem

1. Insert HTML
2. Load page
3. Open dev tools

Regards, Andreas

**Comment by janschoenherr** [comment]
Should be fixed with 3.12.0

**Comment by designconcepts** [comment]
Thank you, that fixed it.
