### ISSUE TITLE
Upload component with "multiple: false" fails

### ISSUE THREAD

**Issue by salsaandi** [uikit/uikit#4587]
### UIkit Version

3.12.2
It works well in previous versions.

### Browser

All browsers

### Actual Behavior

Error in Upload component with "multiple: false" initialisation.

The script fails at beginning of uploading a file, because it tries to slice the list of uploaded files but it is not slicable. 

It gives:
 **Uncaught (in promise) TypeError: t.slice is not a function**

### Workaround

It works with a single file input 
```
<input type="file">
```
and a multi file initialization
```
multiple: true
```
but should be fixed or the parameter removed.

**Comment by janschoenherr** [comment]
Should be fixed with v3.13.0

**Comment by timrasche** [comment]
Sorry its not fixed... Whole component broken

**Comment by janschoenherr** [comment]
Please be a bit more specific, is it the same error as above?

`Uncaught (in promise) TypeError: t.slice is not a function`

**Comment by timrasche** [comment]
> Please be a bit more specific, is it the same error as above?
> 
> `Uncaught (in promise) TypeError: t.slice is not a function`

Yes it is

**Comment by janschoenherr** [comment]
I can't reproduce the error. It seems to be working here: https://getuikit.com/assets/uikit/tests/upload.html

**Comment by timrasche** [comment]
Remove the "multiple" attribute, that produces the error.
