### ISSUE TITLE
Image bullet modifier bug

### ISSUE THREAD

**Issue by exscorp** [uikit/uikit#4588]
### UIkit Version

3.12.1

### Actual Behavior

by changing/removing `[class*='uk-list'] > ::before` the **Image bullet modifier** won't display the bullet-image.

`display: list-item;` is missing

### Reproduction Link

https://getuikit.com/docs/list#image-bullet-modifier

**Comment by viocassel** [comment]
See https://github.com/uikit/uikit/commit/d19bf42ea19c531d1c0878b43416bfcb0d9dc2d9

**Comment by janschoenherr** [comment]
Should be fixed with v3.13.0
