### ISSUE TITLE
Switcher / tabs. uk-active is removed if uk-disabled it set on the first tab

### ISSUE THREAD

**Issue by Nicero** [uikit/uikit#4590]
### UIkit Version

3.13.0

### Actual Behavior

If the first tab is set to `uk-disabled` the tab set as `uk-active` is not underlined with the blue line because `uk-active` is removed.

    <div class="uk-container">

        <ul uk-tab>
            <li class="uk-disabled"><a>One (disabled)</a></li>
            <li class="uk-disabled"><a>Two (disabled)</a></li>
            <li class="uk-disabled"><a>Three (disabled)</a></li>
            <li class="uk-active"><a href="#">Four (active)</a></li>
        </ul>

        <ul class="uk-switcher">
            <li>One</li>
            <li>Two</li>
            <li>Three</li>
            <li>Four</li>
        </ul>

    </div>

### Reproduction Link

[https://codepen.io/Nicero/pen/xxpVbyv](https://codepen.io/Nicero/pen/xxpVbyv)

### Workaround

Use this instead of `uk-disabled` but not sure if it can fully replace `uk-disabled`:

    .my-disabled {
        color: #999;
        pointer-events: none;
    }

**Comment by Lumelomser** [comment]
Nearly, but still faulty.

### Template

```
<div class="uk-container">

    <ul uk-tab>
        <li class="uk-disabled"><a>One (disabled)</a></li>
        <li class="uk-disabled"><a>Two (disabled)</a></li>
        <li class="uk-disabled"><a>Three (disabled)</a></li>
        <li class="uk-active"><a href="#">Four</a></li>
        <li><a href="#">Five</a></li>
        <li><a href="#">Six</a></li>
        <li><a href="#">Seven</a></li>
        <li><a href="#">Eight</a></li>
    </ul>

    <ul class="uk-switcher">
        <li>One</li>
        <li>Two</li>
        <li>Three</li>
        <li>Four</li>
        <li>Five</li>
        <li>Six</li>
        <li>Seven</li>
        <li>Eight</li>
    </ul>

</div>
```

### Reproduction A

1. Click tab "Seven".
2. Click tab "Four".
3. Neither tab "Four" nor content "Four" will become active.

### Reproduction B

1. Click tab "Eight".
2. Click tab "Four".
3. Tab "Four" and "Four" will become active.
4. Click tab "Eight".
5. Click tab "Five".
6. Now neither tab "Five" nor content "Five" will become active.

Related Issue
[#4494](https://github.com/uikit/uikit/issues/4494)
