### ISSUE TITLE
Implement in Xamarin project(IOS) 

### ISSUE THREAD

**Issue by devmegaminds** [uikit/uikit#4593]
I am creating a project in Xamarin and in that, I want to use [MobilePay](https://mobilepaydev.github.io/MobilePay-Payments-API/docs/introduction) as a payment option. I'll complete the android version(with the deep link) but I can't able to do it for the IOS version
For the deep linking in IOS  I am using UIKit (deep link MobilePay) it's also working fine but when app-center build APK for the android version it's getting me below error 

https://i.stack.imgur.com/8MWn7.png

Means it's the effect on the android building process. can you please provide me some guide line about this issue

**Comment by mattfletcher** [comment]
I think you might have the wrong project. This is a CSS framework, not the iOS package
