### ISSUE TITLE
Sticky position issue

### ISSUE THREAD

**Issue by tnpcs** [uikit/uikit#4600]
I noticed an issue with sticky and my Uikit template.
The sticky position changed from fixed to absolute if the html is set to 100% height. The issue not effected with Uikit version 3.11, I guess that something changed that refer to new sticky parallax animation that added recently.

https://github.com/uikit/uikit/blob/aeb60a5aa55414e1002f852f49806dbd2980eaca/src/js/core/sticky.js#L324

### UIkit Version 
3.13.7

### Actual Behavior
Sticky position assigned to absolute and top property changed randomly based on scroll position on page layout.

### Expected Behavior

Position assigned to Fixed instead Absolute and Top property is assigned to 0px

### Reproduction Link

Dropbox video issue: https://www.dropbox.com/s/v7pxmgrlbk7ji45/Sticky.mov?dl=0

**Comment by janschoenherr** [comment]
Yes, we are setting position absolute, as to not having to update the position with each scroll event. If this causes you trouble a reproduction link would probably help.
