### ISSUE TITLE
No more animation since uikit 3.13.0

### ISSUE THREAD

**Issue by Joomlaplates** [uikit/uikit#4603]
Hello, 
the "cls" animation in the slideshow is not working right anymore, only if you scroll a bit down.

If you open the site, the animation is shown on first slide, but if you switch to another slide the animation comes only if you scroll the site a bit down. And in version 3.13 the animation is not even comes on the first slide anymore. YOu need to scroll a bit to see the overlay.

Is this a feature or a bug?
**No Animation at all only if you scoll **
http://grafiknet.de/uikit-3.13.0/

**Animation only on first slide **
http://grafiknet.de/uikit-3.12.2/

**With animation, everything is working like expect**
http://grafiknet.de/uikit-3.11.1/

Regards, Peter

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/128538499ec22c8a8866a99f00a1c41ea5bb9f74

**Comment by Joomlaplates** [comment]
Sorry,
its not working in 3.13.7
http://grafiknet.de/uikit-3.13.7/

**Comment by janschoenherr** [comment]
The fix hasn't been released yet, if you want to try it you can get the dev build here: https://www.jsdelivr.com/package/npm/uikit?version=3.13.8-dev.efe195e41
