### ISSUE TITLE
close in drops doesn't work

### ISSUE THREAD

**Issue by alexandrelapoux** [uikit/uikit#4606]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.13.7

### Actual Behavior

close in drops doesn't work

### Expected Behavior

close in drops doesn't work

### Reproduction Link

[_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_](https://getuikit.com/docs/close)

### Steps to Reproduce the Problem

1. Same thing on FF, Chrome, Safari
2. Work on UIkit 3.7.6
3. Doens't work on UIkit 3.13.7

**Comment by janschoenherr** [comment]
Please try the latest release 3.13.8
