### ISSUE TITLE
Lightbox is black screen.

### ISSUE THREAD

**Issue by danilpyregov** [uikit/uikit#4610]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.14.1

### Actual Behavior

_What happened? Screenshots please, if relevant!_

### Expected Behavior

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1. When open a lightbox in console has error: TypeError: _$[fn] is not a function. (In '_$[fn](...nodes)', '_$[fn]' is undefined). This error occurs on the main website in the documentation section.

**Comment by janschoenherr** [comment]
What browser are you using?

**Comment by danilpyregov** [comment]
The problem is solved, for some reason after rebooting the PC everything worked.
