### ISSUE TITLE
Problem when using older versions of safari and .min compressed CDN including versions 3.13.2 and onwards.

### ISSUE THREAD

**Issue by Thomas-Haiku** [uikit/uikit#4614]
When using older apple devices, which use older versions of safari the following issues occurs: 

1. Versions 3.13.2 and above, CDN links containing .min,  cause a console error of "unexpected token".
2. This stop the whole UIkit from loading.
3. When using versions 3.13.2 and above CDN's without .min within the address, everything works as it should.
4. Version 3.13.1 works absolutely fine regardless of using the compressed or uncompressed links.

**Comment by aarongerig** [comment]
@Thomas-Haiku AFAIK older versions of Safari are not supported with UIkit. See https://getuikit.com/docs/introduction#browser-support

**Comment by Thomas-Haiku** [comment]
Sure, that's fine if the browser limitations cause a headache to maintain functionality within the UIKit library - but we are talking about the difference between a using compressed version of the library versus the non-compressed version. The issue appears to be being introduced as a result of the "minification" process.
