### ISSUE TITLE
Dropdown position

### ISSUE THREAD

**Issue by timrasche** [uikit/uikit#4616]
Since 3.14.0 the position of dropdown is not calculated correctly. In my case (without provide any options except "mode") its out of view or specially out of parent container (Calculated expand to top but needs to bottom - yes there is enough space available).

**Comment by janschoenherr** [comment]
The drop component will be largely refactored with the next release. Please try the latest dev release: https://www.npmjs.com/package/uikit/v/3.14.4-dev.e8873dd80
