### ISSUE TITLE
`fragment` util function does not work for `tr` ,`td` tags

### ISSUE THREAD

**Issue by dobaniashish** [uikit/uikit#4617]
### UIkit Version

3.14.1

### Actual Behavior

`util.fragment('<tr><td>td element</td></tr>')` returns `#text "td element"`

### Expected Behavior

`util.fragment('<tr><td>td element</td></tr>')` should return html element `<tr>`

### Reproduction Link

https://jsfiddle.net/4mdL6pn5/

### More Info

The problem occurs because tags like tr, td etc are parsed properly only in table element and not in div elements

Update: It works if we add only single and empty tags that to without extra spaces, tabs, newline before or after. Example link: https://jsfiddle.net/cz1uqvfs/

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/b1b90c5708845c20afd05879e5d704b1b653c098

Will be added in 3.17
