### ISSUE TITLE
Parallax issue

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#4619]
### UIkit Version

3.14.1

### Actual Behavior

When using `background-cover` with both `bgx; bgy` the `background-size` and `background-position` are wrong as you can see on the following Pen https://codepen.io/ZeGregg/pen/GRQvajL

If we set on only `bgy` it works fine

### Expected Behavior

With both `bgx; bgy` and `background-cover` we should not have blank area as image should cover the entire section. Here is a working Pen with 3.10.0 https://codepen.io/ZeGregg/pen/xxYLNrj

**Comment by janschoenherr** [comment]
Please give it a try with the latest dev build [3.14.2-dev.c7c85455d](https://www.npmjs.com/package/uikit/v/3.14.2-dev.c7c85455d)

**Comment by gregBerthelot** [comment]
Works fine now 👍
