### ISSUE TITLE
Vertical grid divider not working

### ISSUE THREAD

**Issue by aarongerig** [uikit/uikit#4620]
### UIkit Version

3.14.1

### Actual Behavior

The vertical grid divider is not working.

### Expected Behavior

The grid should have vertical divider lines, just like the horizontal one's.

### Reproduction Link

https://codepen.io/aarongerig/pen/GRQMxpJ?editors=1000

### Steps to Reproduce the Problem

1. Create a grid container with the class "uk-grid-divider"
2. Add enough items to have a multi-row grid
3. Now the grid should have divider lines between the items (horizontally as well as vertically)

### Why does this happen?

This issue occurs because the internal UIkit API changed recently. It does not trigger the resize event automatically anymore, you have to register the resize mixin manually. Here are the affected lines of code: https://github.com/uikit/uikit/blob/develop/src/js/core/grid.js#L39-L45

Because of that behavior the class "uk-grid-stack" does not get applied to the grid anymore.

**Comment by janschoenherr** [comment]
I believe the `uk-grid-stack` class is applied to single column grids only. Yours seems to always have three columns. Did the behavior change?

**Comment by aarongerig** [comment]
Ah I see. No the behavior did not change, I simply assumed that the class `uk-grid-stack` should get applied on multi-row grids.

Nevermind then, I'll close the issue. Thanks for the quick response!
