### ISSUE TITLE
Lightbox images not appearing in Safari

### ISSUE THREAD

**Issue by dougfelton** [uikit/uikit#4621]
### UIkit Version

3.14.1

### Actual Behavior

In Safari 13.1 on a Mac laptop, when a lightbox slideshow opens to full screen, the images do not appear.  Works in Chrome, Edge, etc, but not Safari.  You can trigger this issue by by going to the lightbox docs page in Safari and trying one of the previews:

https://getuikit.com/docs/lightbox#animations

### Expected Behavior

Images should appear in lightbox

### Other Information

Here is the error's stack trace and user agent when the error triggered on our website when lightbox pops up in Safari:
https://flareapp.io/share/V7jLoznm#F14

Interestingly, according to the stack trace, the error is triggered in utils/dom.js at the very line which was changed in the most recent commit of dom.js

**Comment by janschoenherr** [comment]
What version of Safari are you using?

**Comment by janschoenherr** [comment]
This is probably related: https://github.com/uikit/uikit/issues/4614

**Comment by dougfelton** [comment]
Safari 13.1 (released in March 2020).  The compressed vs. uncompressed doesn't seem to apply in my  case.  When I build for my local development server, the UIkit library is not compressed and the error still appears.

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/5325d42a0f2be0deaad0277669c2e57949f6c4e0
