### ISSUE TITLE
Cannot read property '_init' of null

### ISSUE THREAD

**Issue by 1694182179** [uikit/uikit#4622]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.14.1

### Actual Behavior

_What happened? Screenshots please, if relevant!_

### Expected Behavior

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1.   camelize(attribute.replace('data-uk-', '').replace('uk-', '')) :
      false;
    });

    const UIkit = function (options) {
      this._init(options);
    };

    UIkit.util = util;
    UIkit.data = '__uikit__';
    UIkit.prefix = 'uk-';
2.
3.

**Comment by janschoenherr** [comment]
Please provide more information.
