### ISSUE TITLE
Sticky Overflow Flip example in documentation seems to be broken

### ISSUE THREAD

**Issue by dvelguru** [uikit/uikit#4624]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.14.3

### Actual Behavior

<img width="391" alt="Bildschirmfoto 2022-06-01 um 09 43 27" src="https://user-images.githubusercontent.com/3622712/171353553-8c111293-653e-42b6-be1c-c5993b91a08f.png">

Tested in multiple browsers and from different machines.

### Expected Behavior

Unfortunately, I expect the example to be functioning.

### Reproduction Link

https://getuikit.com/docs/sticky#overflow-flip

**Comment by janschoenherr** [comment]
Thanks, will be fixed with next release.
