### ISSUE TITLE
Error: node.attributes is not iterable

### ISSUE THREAD

**Issue by sami-addami** [uikit/uikit#4627]
### UIkit Version
3.14.3
### Actual Behavior
![error](https://user-images.githubusercontent.com/79273141/172843095-4f4d2466-7c29-44bd-9fdc-0c4cd3c6c702.png)
### Expected Behavior
Work without the error
### More Info
Just by changing the uikit version (3.7.2 to 3.14.3) on the same site.
The error appears on the pages where there is a form.

**Comment by janschoenherr** [comment]
Sorry, we'll need more details to help. A reproduction link would help. Will close this for now.
