### ISSUE TITLE
Links in dropdown of tab headers don't switch tab content

### ISSUE THREAD

**Issue by gaxweb** [uikit/uikit#4632]
### UIkit Version

3.14.3

### Actual Behavior

The switcher part of the tab component doesn't work right, if used with the dropdown component. The links in the dropdown do not switch the tab content.

### Expected Behavior

If you add a dropdown to a tab header, the additional links inside the dropdown should work like all the other tab headers.

### Reproduction Link

https://codepen.io/hey-codep3n/pen/QWmjboR

### Steps to Reproduce the Problem

1. Click on the links
2. See how the ones in the dropdown are basically ignored but still trigger the animation

**Comment by gaxweb** [comment]
The `toggle` option doesn't seem to be respected either. It always seems to use the immediate children of the `uk-tab` element.

**Comment by janschoenherr** [comment]
Currently that is not possible, but we'll keep this in mind for UIkit 4. Thanks.
