### ISSUE TITLE
js error uk-offcanvas + uk-lightbox

### ISSUE THREAD

**Issue by geo903** [uikit/uikit#4634]
Use UIkit Version 3.14.3
Error occurs when trying to re-click on a lightbox element

`    <div id="offcanvas-file" uk-offcanvas="overlay: true">
        <div class="uk-offcanvas-bar">

            <button class="uk-offcanvas-close" type="button" uk-close></button>

            <p id="title-images" data-file_id="0"></p>
                <div uk-lightbox="animation: slide" id="file-images">
                   <a href="/storage/reports/20/6210be276914e_1.jpg?time=1657138909"> <img data-angle="0" data-img_page_src="813_1" class="mini-file-image" src="/storage/reports/20/6210be276914e_1.jpg?time=1657138909"></a>
                </div>
        </div>
    </div>
`

![Снимок экрана 2022-07-06 в 23 17 26](https://user-images.githubusercontent.com/12372695/177635862-ae72d10e-7d17-4314-b35c-e237b32046d2.png)
![Снимок экрана 2022-07-06 в 23 18 45](https://user-images.githubusercontent.com/12372695/177635865-d8622480-761f-4db6-a6c3-42061535cff4.png)

**Comment by janschoenherr** [comment]
Is this fixed with 3.15.0?

**Comment by geo903** [comment]
on 3.15 the error also occurs (

**Comment by janschoenherr** [comment]
This seems to be working fine for me. Please provide a Codepen where we can inspect the issue.
