### ISSUE TITLE
3.15.1 master - uk-scroll="offset:200"

### ISSUE THREAD

**Issue by wcomgithub** [uikit/uikit#4645]
uk-scroll="offset:200"" is ignored / does not work.

IN DETAIL:
Included /dist/js/ files from 3.15.1 master in my environment, always working together with my compiled less files. 
uk-scroll="offset:200" inside the <a> tag as usual however is ignored / does not work.
It works when I take my old /dist/js/ files from e.g. 3.14.0
Seemingly no feature or syntax change?
Seen the scroll listener notes in current development version... Maybe just fixed? 
Thank you!

**Comment by papazetis** [comment]
https://getuikit.com/docs/scroll
It doesn't work on latest uikit version

**Comment by janschoenherr** [comment]
This seems to be working fine for me, what browser are you using?

**Comment by wcomgithub** [comment]
Thank you! I will try it out in my production environment, soon. If anyone could try and report earlier, please feel free to do so and let us know.

Browsers: 
All/many tested browsers have been affected. 
(If I am not wrong... as far as I remember ist also did not work with the slightly modified test files).
