### ISSUE TITLE
uk-modal-full not working correctly / should include uk-height-viewport attribute?

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#4646]
UIkit 3.15.1

The modal full modifier documentation states to add `uk-modal-full` on the main modal div.  However it does not make the modal full height (but it does make it full width).  The only way it becomes full height is if `uk-height-viewport` attribute is added to the div containing the class `uk-modal-dialog`.  In the past, it wasn't required to add `uk-height-viewport`.

So either the documentation should state to add `uk-height-viewport` or the `uk-modal-full` class is not properly working.

https://getuikit.com/docs/modal#full-modifier

**Comment by janschoenherr** [comment]
Is this still valid? For me the modal covers the whole screen.
