### ISSUE TITLE
git clone git://github.com/uikit/uikit.git causes error fatal: unable to connect to github.com:

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#4647]
Just wondering if this command mentioned in the [Getting Started](https://github.com/uikit/uikit#getting-started) section of the `README` is still the correct way to clone UIkit?

    git clone git://github.com/uikit/uikit.git
   
It is giving me this error:  

```
$ git clone git://github.com/uikit/uikit.git
Cloning into 'uikit'...
fatal: unable to connect to github.com:
github.com[0: **.***.***.**]: errno=Unknown error
```

**Comment by oshihirii** [comment]
This seems to work:

    git clone https://github.com/uikit/uikit.git

Are there any undesired consequences caused by using this?

Thank you.

**Comment by janschoenherr** [comment]
Thanks, will be fixed in docs. https://github.blog/2021-09-01-improving-git-protocol-security-github/
