### ISSUE TITLE
Uikit Drop Component boundary option doesn't work!

### ISSUE THREAD

**Issue by abutalib4599** [uikit/uikit#4650]
👋 Hi There, I have found an issue with Drop Component!
_I tried this example [Code](https://codepen.io/talib4590/pen/BarJpdm)_ from the documentation using the boundary option, but it looks like the boundary option doesn't work properly. please check it & fix it as soon as possible.
**_Thanks_**

**Comment by janschoenherr** [comment]
Please use the new target option. https://getuikit.com/docs/drop#target
