### ISSUE TITLE
uk-switcher event are not fired

### ISSUE THREAD

**Issue by MB116** [uikit/uikit#4653]
### UIkit Version

3.15.2

### Actual Behavior

Events are not fired (for example: UIkit.util.on(element, 'shown', callback()) when using the following method:
UIkit.switcher(element).show(index);

### Expected Behavior

Any of the events for uk-switcher should be triggered

### Reproduction Link

[https://codepen.io/MB116/pen/eYMKxrN](https://codepen.io/MB116/pen/eYMKxrN)

### Steps to Reproduce the Problem

1. Click on button "Switch to 3"
2. See console for logs

**Comment by janschoenherr** [comment]
```function switchButton() {
  UIkit.switcher('#my-switcher').show(2);
}```
This does not select the switcher, but its collected list, initializing a new switcher component. 

Try: 

```function switchButton() {
  UIkit.switcher('[uk-switcher]').show(2);
}```
