### ISSUE TITLE
iOS Crash : UIKitCore -[UIInputWindowController changeChild:toAppearState:animated:]

### ISSUE THREAD

**Issue by Nehacdew** [uikit/uikit#4661]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.15.5

### Actual Behavior
NA

### Expected Behavior

_What should have happened?_
NA

### Reproduction Link

Not reproduce  

### Steps to Reproduce the Problem

Crashlytics : iOS Crash : UIKitCore -[UIInputWindowController changeChild:toAppearState:animated:]

Crash Item	:	Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1f40 objc_msgSend + 32
1  UIKitCore                      0x5bc1b4 -[UIInputWindowController changeChild:toAppearState:animated:] + 124
2  UIKitCore                      0x601d7c -[UIInputWindowController updateAppearStatesForPlacement:start:animated:] + 124
3  UIKitCore                      0xd3ef38 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.1045 + 1448
4  UIKitCore                      0x12a8cdc UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK + 36
5  UIKitCore                      0x2c2ca4 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 728
6  UIKitCore                      0x18eb3c -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 248
7  UIKitCore                      0x1a333c -[UIViewAnimationState animationDidStop:finished:] + 244
8  UIKit                          0xd305c -[UIViewAnimationStateAccessibility animationDidStop:finished:] + 212
9  QuartzCore                     0xcb320 CA::Layer::run_animation_callbacks(void*) + 280
10 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
11 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
12 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
13 CoreFoundation                 0x51800 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 16
14 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
15 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
16 GraphicsServices               0x1374 GSEventRunModal + 164
17 UIKitCore                      0x514648 -[UIApplication _run] + 1100
18 UIKitCore                      0x295d90 UIApplicationMain + 364
19 TCPApp                         0xbad894 main + 39 (AppDelegate.swift:39)
20 ???                            0x106979ce4 (Missing)
Crash Events	:	This issue has 3 crash events affecting 3 users

Device For Max count	: iPhone 13 Pro

OS for Max count	:	15.5.0

**Comment by mattfletcher** [comment]
This is not the UIkit you are looking for, my friend

**Comment by Nehacdew** [comment]
@mattfletcher  Could you please suggest which link i will use.
