### ISSUE TITLE
Accessiblity by default

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [uikit/uikit#4666]
# Discussion
I am looking to use UIkit for a new project. UIkit looks very good on paper, the only disadvantage is accessibility. This is no dealbreaker for me, as the project is for internal use, it would be, however, if it would be a public website. By default, UIkit has a very low accessibility score compared to other frameworks, as was mentioned in [this thread.](https://github.com/uikit/uikit/issues/3967). It also doesn't mention accessibility, as opposed to most other frameworks. One especially noticable problem, is that, by default, the contrast on text is too low. Another problem is that the documentation [scores very low on accessibility](https://accessibilitytest.org/results/sK3OvlDSBBxR). All other frameworks have accessibility built in and have a dedicated page for it in the docs: is there anything being done to improve accessibility?

**Comment by janschoenherr** [comment]
Thanks, version 3.16.0 comes with built in accessibility.
