### ISSUE TITLE
Lightbox broken in Safari upon any fullscreen-video attempt.

### ISSUE THREAD

**Issue by promyvion** [uikit/uikit#4667]
### UIkit Version
3.15.12

### Tested Environments
macOS 12.6 + Safari 16.0: **Fails**
iPad Pro 12.9" 5th gen + iPadOS 15.7: **Fails**
iPhone 12 Pro + iOS 16.0: **No issue**

### Actual Behavior
If a lightbox contains a Youtube, Vimeo, or MP4 file, attempting to fullscreen that video fails in Safari on both macOS and iPadOS.

To the user, it appears as if the lightbox and video simply close while the underlying website then goes fullscreen. If the video happened to be playing upon the fullscreen attempt, the user is left with the very confusing experience of watching the lightbox close as audio continues to play.

On a technical level, Safari appears to be interpreting the uikit.js implementation of the allowfullscreen attribute incorrectly.

### Video demonstration
[Screen recording](https://imgur.com/a/FoEdjyy)

### Expected Behavior
The lightbox video should expand as expected when clicking a video's fullscreen button, as it does within Chrome or Firefox.

### Reproduction Link
You can preview the bug within the UIKit documentation itself:
[Lightbox documentation](https://getuikit.com/docs/lightbox)
[Lightbox documentation test](https://getuikit.com/assets/uikit/tests/lightbox.html)

### Steps to Reproduce the Problem
1. Open Safari and navigate to the UIKit lightbox docs.
2. Click any lightbox demonstration video.
3. Click the fullscreen icon within that video.

Edits:
11/1/22 - Re-tested in UIKit 3.15.11, problem persists.
11/10/22 - Re-tested in UIKit 3.15.12, problem persists.

**Comment by janschoenherr** [comment]
Seems to be fine with latest Safari versions.
