### ISSUE TITLE
Regression: Nav accordion issue

### ISSUE THREAD

**Issue by gregBerthelot** [uikit/uikit#4672]
### UIkit Version

3.15.10 on React app

### Actual Behavior

Accordion does not open on Safari and return error in console for react-dom.production while it is working fine on Chrome and Firefox. (Have not the chance to test on Edge). You can test Nav in offcanvas on https://jjjqxsxpe.ipaoo.dev by clicking burger icon then _Solutions_ item in Safari browser.

### Expected Behavior

https://codepen.io/ZeGregg/pen/xxjamVv?editors=1010 working fine on Safari

Please note that there was no issue on 3.14.3 when uk-nav-parent-icon was a class and not an attribute. Seems that issue arises from uikit side for react production build

**Comment by janschoenherr** [comment]
Both tests seem to be working fine in Safari. What version of Safari causes the error?

**Comment by gregBerthelot** [comment]
Testing on Safari Version 15.6.1 and 15.5. Please see https://share.cleanshot.com/sKJxIL It is live [here](https://jjjqxsxpe.ipaoo.dev) 

The issue arises from uikit side for react production build

**Comment by janschoenherr** [comment]
I think you are using a modified/transpiled version of UIkit. It seems to work fine with the original uikit.min.js.
