### ISSUE TITLE
Tab component sporadically fails to initialize on Chrome

### ISSUE THREAD

**Issue by csaboka** [uikit/uikit#4674]
### UIkit Version

3.15.10

### Actual Behavior

We have a tab control on our page marked with a "uk-tab" attribute and a tab content container marked with the "uk-switcher" class as its next sibling. On Chrome, the first tab content doesn't become visible most of the time. The tab controller starts working as expected once the user tries to switch to another tab. We could only reproduce this reliably on one page of our website, so its trigger conditions seem to be very specific even in Chrome.

### Expected Behavior

The contents of the first tab should be visible after page load, without having to interact with the component.

### Reproduction Link

[repro.zip](https://github.com/uikit/uikit/files/9763701/repro.zip)
(Apologies for the format. As the issue seems to depend on the amount of markup before the tab component and even on the structure of the elements, I couldn't minimize it very well. I have replaced the actual content and the irrelevant classes with padding values to narrow the scope and anonymize the data.)

### Steps to Reproduce the Problem

1. Extract the attached file repro.zip into an empty folder.
2. Open repro.html in Chrome (tested with version 106.0.5249.119)
3. The very bottom of the page should show "Tab 1 content comes here", but it doesn't always show up.
4. If the expected content does show up, try refreshing the page a few times. (The issue shows up pretty consistently on our production page, but the minimized versions I could build only show the issue sporadically.)

**Comment by csaboka** [comment]
I did some debugging on this issue on my own. The issue seems to be that not all of the necessary DOM elements are available when Switcher.show() is called on the tab control. As the control relies on the element directly after it, it can fail to find that element when it's not present in the DOM yet. The code will assume that no content needs to be shown, and when the sibling shows up in the DOM, it's too late and all switcher elements stay hidden.

The best way to see this is to set a breakpoint on Switcher.show(), then switch to the Elements tab of the developer toolbar once the breakpoint is triggered. When the issue happens, you will see an incomplete DOM tree.

All the padding in the reproduction page seems to delay things enough so that the next animation frame comes before the DOM is fully constructed, so the requestAnimationFrame() isn't enough to see a "stable" DOM.

**Comment by bogdancondorachi** [comment]
We've noticed that we got the same issue where in some cases the switcher container does not appear. I'm adding a demonstration video to show exactly what's happening.

https://watch.screencastify.com/v/C5R0xpt6WbuVvpM2PZbR
