### ISSUE TITLE
Images break after close Lightbox

### ISSUE THREAD

**Issue by mixahlos** [uikit/uikit#4676]
The image breaks and almost the whole image turns to green.
![image](https://user-images.githubusercontent.com/13023353/196027534-3ccdc86f-74a0-48d3-960d-73240e6cc3e4.png)
![image](https://user-images.githubusercontent.com/13023353/196027866-0e0b7eca-789b-445e-b4f3-3a515b96b676.png)
Hover:
![image](https://user-images.githubusercontent.com/13023353/196027606-695fe9dd-e4da-43ea-a8bd-52f9d86a5e82.png)

You can also check a video.
https://imgur.com/a/2co6fYc

Tested on ubuntu chrome
In ubuntu Firefox there is NO issue.

### UIkit Version

Tested in every version from 3.14.0 til 3.15.10 
In versions 3.14.x there is a different color, maybe ping.

**Reproduction Link**
https://getuikit.com/assets/uikit/tests/lightbox.html

### Steps to Reproduce the Problem

1. Click on the image "1800x1200" or on "Video"
2. Close Lightbox
3. Hover a few times on the images (Some times, all the images -or most- become green directly when returning from lightobox, without hover).
4. Resize Window randomly

**Comment by janschoenherr** [comment]
I can't reproduce this. Have you tested on other devices too?

**Comment by mixahlos** [comment]
Well,
In another laptop using ubuntu the problem remains,
but when I boot to windows (I usually don't)  I cannot reproduce too.

So I am closing the Issue as it looks is something with the Chrome release in Ubuntu...
Thanx @janschoenherr
