### ISSUE TITLE
Modal dialog prompt bug (only Safari)

### ISSUE THREAD

**Issue by uatrend** [uikit/uikit#4677]
### UIkit Version
3.15.10

### Actual Behavior
![modal_prompt_bug](https://user-images.githubusercontent.com/24713453/196143246-84058d6e-27f5-44fb-a3fe-63646813ace6.gif)

### Expected Behavior

Current window scroll position changed to top after <code>UIkit.modal.prompt</code> closed.
This happens only in Safari (16.0).

**Comment by janschoenherr** [comment]
Sorry, this does not seem to happen for me in Safari 16.0.
