### ISSUE TITLE
uk-sticky sometimes work and sometimes not

### ISSUE THREAD

**Issue by keev-studio** [uikit/uikit#4679]
### UIkit Version

present even in last UiKit version
3.15.10

### Actual Behavior

<div uk-sticky="show-on-up: true"> sometimes work sometimes not, looks like random behavior. Observed in both last Chrome and Brave browser

### Expected Behavior

should work always when scrolling up

### Reproduction Link

[_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_](https://codepen.io/keev/pen/jOKONeg)
[uk-sticky.webm](https://user-images.githubusercontent.com/24513480/197622584-d0d8caf2-4da3-4d28-a39a-ca47d91ee87f.webm)

### Steps to Reproduce the Problem

1.  Codepen https://codepen.io/keev/pen/jOKONeg
2. scroll down more than half page down
[uk-sticky.webm](https://user-images.githubusercontent.com/24513480/197622069-9c82ed2c-a1fb-447f-b425-09af1e729a5b.webm)
 and later up
3. if top menu appear try to reload the page or access the Codepen in incognito mode

attached video when sticky working in the Codepen but stops working after reloading the page
https://we.tl/t-G2KApyQOrz

**Comment by janschoenherr** [comment]
Sticky does not work if within a `position: absolute` container.
