### ISSUE TITLE
Dynamic Buttons Without Margin

### ISSUE THREAD

**Issue by dday9** [uikit/uikit#4680]
### UIkit Version
3.15.10

### Actual Behavior
![Screenshot](https://www.vbforums.com/attachment.php?attachmentid=186058&stc=1&d=1666755044)
Creating buttons dynamically do not retain their margin.

### Expected Behavior
The buttons should have their margin retained.

### Reproduction Link
https://jsfiddle.net/1opathk3/

### Steps to Reproduce the Problem
1. Create a function that returns a dynamic button element
2. Call the method and store the result in a variable
3. Append the variable to the existing DOM (e.g. the body)
4. Repeat step 2 and 3 a couple of times

### Update
It appears that it isn't just isolated to buttons, in the screenshot you will notice that the same thing happens to icons.

**Comment by janschoenherr** [comment]
There is no whitespace between your dynamically created buttons.

https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by dday9** [comment]
In case anyone finds this bug ticket, following @janschoenherr advice it was just a matter of adding a newline character after creating the button. It's gross, but it works.
