### ISSUE TITLE
Uncaught TypeError: i.hide is not a function - Tab key click in 3.15.12  version

### ISSUE THREAD

**Issue by mnagaraju55555** [uikit/uikit#4684]
Hi,

UIkit Version 3.15.2 above version facing the console issue like i.hide is not a function while clicking the tab key.
this issue not getting on below versions. Upto version 3.14.0 we don't have any issue.

chrome browser -> open developer toolbar -> and click the tab key continuously -> in console you will see the error

Thanks,
NagaRaju M

**Comment by miczh** [comment]
The issue is replicable eg. here: 

https://getuikit.com/assets/uikit/tests/navbar.html

when tabbing over navbar items.

BR Michael

**Comment by janschoenherr** [comment]
Fixed with 3.5.14
