### ISSUE TITLE
<a> links don't work from modal dialog in 3.15.12

### ISSUE THREAD

**Issue by pdomzal** [uikit/uikit#4685]
It works in 3.14.3 but stops working in 3.15.0 and on.

The HTML:
                              
                                <div id="pd-offcanvas" class="" uk-modal>
					<div class="uk-modal-dialog uk-modal-body">
						<button class="uk-modal-close uk-close-large" type="button" uk-close></button><br>
						<a class="uk-modal-close" href="#pd-about" uk-scroll>About Us</a>
						<a class="uk-modal-close" href="#pd-projects" uk-scroll>Projects</a>
						<a class="uk-modal-close" href="#pd-in-progress" uk-scroll>In Progress</a>
						<a class="uk-modal-close" href="#pd-press" uk-scroll>Press</a>
						<a class="uk-modal-close" href="#pd-contact" uk-scroll>Contact Us</a>
						<br>
						<div class="pd-inline">
							<a href="" target="_blank" uk-icon="icon: instagram; ratio: 2"></a>
							<a href="" target="_blank" uk-icon="icon: facebook; ratio: 2"></a>
							<a href="" target="_blank" uk-icon="icon: twitter; ratio: 2"></a>
							
						</div>
					</div>
				</div>

**Comment by pdomzal** [comment]
> The empty href links?

Not on the empty ones, on the ones with the hashtag hrefs

**Comment by janschoenherr** [comment]
You can just remove the `uk-modal-close` class. Clicking a same site href will automatically close the modal.

**Comment by pdomzal** [comment]
> You can just remove the `uk-modal-close` class. Clicking a same site href will automatically close the modal.

That works. Thanks Jan!
