### ISSUE TITLE
UIkit.upload  : Mutiple file error

### ISSUE THREAD

**Issue by mootoo007** [uikit/uikit#4686]
please help. 

```
<div class="uk-padding-small frm-upload">
    <div >
        <input type="file" multiple='multiple'>
        <input class="uk-input uk-form-width-medium" type="text" aria-label="Custom controls" disabled>
    </div>
</div>
```
------------------------------------------------------------------------------------

`UIkit.upload('.frm-upload', {
  url: '../fn_upload.php',
  multiple: true,
  name: "mootoo[]",
  params:{da1:1},
  
  beforeAll: function () {
      console.log(arguments[1]);
  },
  completeAll: function (e) {
     
      console.log(e.response);
      console.log('completeAll', arguments);
  }

});`

when the end of process,  and print_r($_FILES) (php)   just one file not multiple file

![error_issue](https://user-images.githubusercontent.com/17922303/201592692-910a755f-7d9e-404c-a019-54329f2a9136.JPG)

**Comment by janschoenherr** [comment]
Please ask usage question on our Discord channel: https://discord.gg/NEt4Pv7
