### ISSUE TITLE
When should I install UIkit via package manager versus cloning to local repo?  

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#4691]
Hello,

It's been a while, but I've come back to use my very favorite CSS framework.  

I am very glad UIkit exists :).    

But, I've kind of forgotten how to set it up :/.  

I've looked at previous repositories when I've used UIkit, and it seems I have used two approaches:

 - installed it via npm, so uikit is within `/node_modules`

OR:     

 - `uikit` has a folder in my app's root directory (so I think I must have cloned it)  

I can't remember why I made the choice to use one method over the other.    

Is there any difference in the functionality available when installing UIkit via npm versus cloning UIkit?  

I am using custom icons and custom .less theme (so I have a `custom` folder in the `uikit` folder), and I rebuild uikit with these steps:

 - In the uikit folder, run `yarn` and then `yarn compile` 
 - Go back into app folder and run a gulp file that copies uikit js and css files into my app  
 - (and I also make the `custom` folder a repo itself, so that it is not overridden by uikit updates)  

I am reading these articles but getting a bit lost:

https://getuikit.com/docs/installation
https://getuikit.com/docs/custom-icons

I also found a previous issue of mine, that seemed to favor the approach of cloning the repo:

https://github.com/uikit/uikit/issues/4203    

But I'm not sure why I made that choice.  

So, to reiterate the question:

Is there any difference in the functionality available when installing UIkit via npm versus cloning UIkit?  

Which approach is considered 'best practice'?

Thank You.

**Comment by janschoenherr** [comment]
Hi, there should be no difference in both approaches, except for the location of the resulting folder.

**Comment by oshihirii** [comment]
Thank you very much for the confirmation, one less thing to worry about 🙂.
