### ISSUE TITLE
Issue on nav menu dropdown

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4700]
### UIkit Version
3.15.18

### Actual Behavior

![image](https://user-images.githubusercontent.com/3592665/207303412-b98ffe0b-67e9-4748-9575-632ff71c7fad.png)

After updating to 3.15.18 from 3.15.14, the navbar dropdown goes behind the bottom elements. I tried to increase the z-index but it didn't work either.

**Comment by janschoenherr** [comment]
Could you post a link to your site?

**Comment by papazetis** [comment]
@janschoenherr 
This change is causing the issue
![image](https://user-images.githubusercontent.com/3592665/207564303-9d9e4166-8518-4408-a0d6-b78618d7dd5f.png)

**Comment by janschoenherr** [comment]
Fixed with d68f40509505f0ee0ed1a6c9a6cadf317e044993
