### ISSUE TITLE
no aria-expanded for toggle modal-dialogs

### ISSUE THREAD

**Issue by MoppieMop** [uikit/uikit#4702]
### UIkit Version

3.15.18

### Actual Behavior

The recommend markup to open a modal-dialog is with uk-toggle. BUT uk-toggle adds aria-expanded="false" to the HTML-element. This is wrong behaviour for modal-dialogs (see WCAG).

### Expected Behavior

If I use uk-toggle AND the target is a uk-modal THEN there should not be an automatic aria-expanded on the uk-toggle.

**Comment by janschoenherr** [comment]
This has been fixed with 3.16.0.
