### ISSUE TITLE
all uk-scroll and uk-totop funcionality not working with <base> tag

### ISSUE THREAD

**Issue by olivergrosche** [uikit/uikit#4710]
hi there. 

i found a prett annoying bug, which started in version 3.15.15:

i´m using uikit with contao which defaultly writes a html base tag in the head, which points to the root-page.
since uikit 3.15.15 all scrolling and totop elements arent working anymore, when this base-tag is active.

in version 3.15.14 it was all ok.

please can you tell me if this is intended?

### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.15.20

### Actual Behavior

_What happened? Screenshots please, if relevant!_

### Expected Behavior

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1.
2.
3.

**Comment by janschoenherr** [comment]
If you have a link e.g. `<a href="#foo">Link</a>` and a base tag `<base href="https://mydomain.com/">`. The resulting link points a `https://mydomain.com/#foo`. In that sense UIkit behaves correctly, I think.

That being said, it does seem to be a somewhat breaking change. Your links need to be relative to the base tag, including those that are just a hash link.

**Comment by olivergrosche** [comment]
ok i updated the link with a contao insert-tag. {{page::alias}}.html generates the current page-link. that before the # makes scrolling work again. thanks man!

**Comment by janschoenherr** [comment]
> that makes sense. but why did it work up to version 3.15.14?

The scroll component checks the link and only activates, if it is a same site link now. That way you can apply the scroll component in your menu, whether the target is on the current site or not.
