### ISSUE TITLE
Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4711]
### UIkit Version
3.15.21

### Actual Behavior
On old browsers like safari and chrome on iPhone 8 Plus (checked it on BrowserStack) I get the following error and off-canvas menu is not working
![image](https://user-images.githubusercontent.com/3592665/212690572-3a87d097-1888-4a9d-93d5-8ffc0d686d50.png)

**Comment by janschoenherr** [comment]
Yes, the JavaScript needs to have Safari 12.1+ and above. iPhone 8 Plus can be updated to latest Safari version.
