### ISSUE TITLE
Google PageSpeed ​​Fails Dots

### ISSUE THREAD

**Issue by HenriqueBatista** [uikit/uikit#4724]
When passing the site developed with UIKIT, the dots are pointed in the negative metrics.
Can we improve it?

![Screenshot 2023-02-22 at 14 16 07](https://user-images.githubusercontent.com/25299137/220705548-d8806dfb-b0d6-4325-884c-afae2ed060f9.png)

![Screenshot 2023-02-22 at 14 07 50](https://user-images.githubusercontent.com/25299137/220704870-47140b30-8e34-468c-897b-741db49bb0ef.png)

recommended
https://developers.google.com/search/docs/crawling-indexing/links-crawlable?visit_id=638126828853830998-686710530&rd=1&hl=pt-br

**Comment by HenriqueBatista** [comment]
It would be interesting if instead of using a link tag <a href=""> we could use a span tag <span>

**Comment by janschoenherr** [comment]
This should be fixed with 3.16.0.
