### ISSUE TITLE
Latest update 3.16.1 breaks dropdowns

### ISSUE THREAD

**Issue by mineralizeus** [uikit/uikit#4729]
Any traditional dropdown using `uk-dropdown` are broken as of latest release.  Tests on UIKIT documentation pages are also broken as a result of the change.  Reverting to 3.16.0 fixes this for now.

**Comment by janschoenherr** [comment]
Could you be a little more precise on what broke?

**Comment by mineralizeus** [comment]
> Could you be a little more precise on what broke?

See for yourself at https://getuikit.com/assets/uikit/tests/dropdown.html

All dropdown divs are visible and aren't dropdowns at all.

**Comment by mineralizeus** [comment]
Never mind, the problem seemed to have solved itself.  I think it was just an issue with the new version propagating to CDN.  Closing.
