### ISSUE TITLE
uk-nav-parent-icon offcanvas breaks nav

### ISSUE THREAD

**Issue by m0yP** [uikit/uikit#4730]
Using `uk-nav-parent-icon` on a `<li>` item in an Offcanvas menu, when you expand the item and click or tap back it will escape the offcanvas and you won't be able to open it again.

**Comment by david-fanin** [comment]
For my part, I tried removing uk-nav-parent-icon and the problem remains. It seems to be a more general bug. I have opened a more complete issue here: https://github.com/uikit/uikit/issues/4731

**Comment by janschoenherr** [comment]
Thanks, this has been fixed with 3.16.2.
