### ISSUE TITLE
Off-canvas close unexpectedly when close a parent menu

### ISSUE THREAD

**Issue by david-fanin** [uikit/uikit#4731]
Hello,

When you click to close a parent menu in off-canvas, the off-canvas disappears and it is not possible to reopen it.

I have reproduced the problem here: https://jsfiddle.net/tac0zske/

- Click on the "primary nav" button;
- Click on "parent" to open the sub-menu;
- Click on "parent" to close the sub-menu;
- The off-canvas disappears and it is not possible anymore to open it by clicking on the "primary nav" button.

The bug is present in the version: 3.16.1. I do not know if it is older.

With kind regards.

**Comment by janschoenherr** [comment]
Thanks, this has been fixed with 3.16.2.
