### ISSUE TITLE
Offcanvas with overlay should disable the scroll on the page ( Firefox )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4734]
### UIkit Version

3.16.3

### Actual Behavior

When offcanvas open with overlay option enabled, the page still is scrollable. 
**This happens only on Firefox**, using latest 110.0.1 (64-bit) For MacOs Ventura. 

https://user-images.githubusercontent.com/5558563/221901471-4b908043-edc0-4566-af34-18b4256e1e09.mov

In Safari and Chrome works fine.

### Expected Behavior

Scroll should be disabled.

### Reproduction Link

**In the test, the page scrolls**
https://getuikit.com/assets/uikit/tests/offcanvas.html

**In the docs, it works as expected**
https://getuikit.com/docs/offcanvas#overlay

### Steps to Reproduce the Problem

Open the offcanvas menu. Scroll the page.

**Comment by janschoenherr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1819563 🤞

**Comment by zzseba78** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1819563 🤞

Thanks @janschoenherr. Let´s hope they fix this.
