### ISSUE TITLE
Sticky on mobile: turning off

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#474]
Hi all,
Was wondering if anyone had found a way to stick or unstick a `data-uk-sticky` element based on screen-size. I didn't see any type of kill method; but think it'd be useful if you wouldn't want certain elements sticky depending on screen size. Thanks!

**Comment by ikabod** [comment]
> // match media string
> data-uk-sticky="{media: '(min-width: 640px) and (orientation: landscape)'}"

Please add media queries to the current and next UIkit version again.

It makes sense to have a sticky menu on a smartphone in portrait orientation with e. g. 360x640 pixel but not in landscape mode with e. g. 640x360 pixel.

Currently there is only the possibility to add a breakpoint at a certain width, regardless of the height of the screen.

**Comment by dogpixels** [comment]
I'm super late to the party, but I just wanted to voice my appreciation for all your work and attention to detail. <3
