### ISSUE TITLE
UIkit.util.parseOptions removed?

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4740]
The parseOptions() util method seems to have been removed in 3.16.4. Can this please be reinstated? It is very useful!

**Comment by janschoenherr** [comment]
The method wasn't meant to be part of the API. What are you using it for?

**Comment by chriswthomson** [comment]
Hi @janschoenherr,

The `key: value;` options format is useful for `data-*` attributes generally and the parseOptions() method is the way to turn an attribute value in that format into an Object. I've been using it for years now.

If it is to remain unavailable, I'll implement it another way. It would be good to have this and any other removed methods noted in the changelog if possible, I use a lot of the UIkit.util methods while developing!

Cheers,

Chris

**Comment by janschoenherr** [comment]
Could you just import the method from the source?

`import {parseOptions} from `uikit/src/js/api/options`

**Comment by chriswthomson** [comment]
Hi @janschoenherr,

Thanks yes that works!

Cheers,

Chris
