### ISSUE TITLE
 Cannot read properties of undefined (reading '__uikit__')

### ISSUE THREAD

**Issue by Ulrich15** [uikit/uikit#4743]
### UIkit Version

Uikit version : 3.16.5

### Actual Behavior
I was using uikit with CDN in my Laravel projet + Vue3 + Inertia, but this morning, my website in production (even in local) show me this error in the console:

![image](https://user-images.githubusercontent.com/60409730/224332674-57353547-7b08-4708-afb0-cbbdc4e927a1.png)

### Expected Behavior

It was working the previous days, and when i downgrade the version of UIKit to version 3.5.8 all things work fine.

Some Ideas ? 

Thanks

**Comment by janschoenherr** [comment]
Could you share a link for us to inspect?

**Comment by Ulrich15** [comment]
> Could you share a link for us to inspect?

The projet is in production, and it's in admin session of the website, i don't really know how to share it. 🤔

**Comment by janschoenherr** [comment]
If you have any Drop components, e.g. in the Navbar. Could you temporarily disable those? Does that fix the error?

**Comment by Ulrich15** [comment]
> Drop

I have checked my projet files and i don't have `Drop components` but only `Dropdown components` in navbar and elsewhere.
