### ISSUE TITLE
Slider Pause on Hover is working but not starting anymore

### ISSUE THREAD

**Issue by pkEwando** [uikit/uikit#4744]
Hello,
in uikit 3.16.6 the `slider pause on hover` is fixed but the slider is not starting again. Is this a bug or a feature?
Here is a demo
https://www.ewando.de/uikit_3166/

Thanks Peter

**Comment by janschoenherr** [comment]
It seems to be working for me. What browser and input are you using?

**Comment by pkEwando** [comment]
Hello Jan, oh yes youre right, sorry I´ve forgotten!
Its working with Windows and IOS with Edge, Chrome but not with Firefox ( even without add ons and private mod)
Thanks, Peter
