### ISSUE TITLE
Update sticky state on height change

### ISSUE THREAD

**Issue by artemvyshnevskiy** [uikit/uikit#4750]
### UIkit Version

3.16.6

### Actual Behavior

A sticky component doesn't update its state when its own height changes. I tried trigger an update event manually with $emit or update function but that didn't work either.

### Expected Behavior

The sticky should update its state when its own height changes.

### Reproduction Link

https://codepen.io/artemvyshnevskiy/pen/wvEXgop

### Steps to Reproduce the Problem

1. Scroll down a bit to make the sidebar stick
2. Expand all items starting with the last one so that they go outside the viewport
3. Now the last items will stay hidden outside the viewport until they reach the end of the container on scroll

**Comment by janschoenherr** [comment]
Should be fixed with 223b81aee5572f829214f015612a6684877d96b9
