### ISSUE TITLE
Uikit.min.js [3.16.7] load with https://cdn.jsdelivr.net causes a shift in the design and backgrounds images doesn't load anymore

### ISSUE THREAD

**Issue by coteo** [uikit/uikit#4752]
The last version of uikit.min.js that we use on more than 300 websites causes a shift in the design and backgrounds images doesn't load anymore. Menu and sub-menus are not displayed correctly.

https://cdn.jsdelivr.net/npm/uikit@3.16.6/dist/js/uikit.min.js work fine !

but https://cdn.jsdelivr.net/npm/uikit@3.16.7/dist/js/uikit.min.js is buggy.

Examples :
https://www.coteoweb.com/
https://www.cadn.fr/
https://www.flandria-loisirs.com/
https://www.cotedargent.com/

We have contacted cdn.jsdelivr.net and the problems does not seems to be from the file.

**Comment by janschoenherr** [comment]
In what browser are you having issues? With Chrome on Mac it looks good.

**Comment by zzseba78** [comment]
Chek if is related to this: https://github.com/uikit/uikit/issues/4757

**Comment by coteo** [comment]
It seems to work perfectly now. Thank you !
