### ISSUE TITLE
[3.16.8] Slideshow/slider don't autoplay/initialize

### ISSUE THREAD

**Issue by WebStation12** [uikit/uikit#4754]
version 3.16.6 works fine, but version 3.16.7 and 3.16.8 both are not working, also some styling issues when using the uk-cover attribute on images to cover it's parent in slider/slideshow, but also in a normal div.

**Comment by WebStation12** [comment]
You can find a reproduction here on a test environment: 
[https://staging.iwnederland.nl/leren-en-werken/noord-holland/amsterdam/]
Header image should be a slideshow...

**Comment by janschoenherr** [comment]
What browser are you using? For me there is a slideshow which autostarts.

**Comment by WebStation12** [comment]
I have it in all browsers, also after deleting the local browser cache en updates to the newest versions. I have a new MacBookPro M1 Pro with Chrome (111.0.5563.64), FireFox (111.0) and Safari (15.4), all the latest versions. On my iPhone the site breaks completely...

Uikit 3.16.6 works fine, .7, .8 and .9 do not work strangely enough.

Another thing I noticed was that some example code pasted into an elementor page is working, even with 3.16.9 
The link I sent is using a custom page template, but then again it worked fine with 3.16.6…?

There are no errors in the console, thought it had something to do with the order of loading wordpress’ jQuery 

Webstation
Arjan Versteeg
Webdesigner  |  Wordpress webdeveloper  | Graphic designer

Zijkanaal F West 12
1165 MZ Halfweg
Nederland
E 	***@***.***
T	+31 (0) 6 4825 5209

**Comment by zzseba78** [comment]
Check if related to this: https://github.com/uikit/uikit/issues/4757

**Comment by WebStation12** [comment]
@zzseba78 Thank you. I tested this and seems to work with the scripts loading in the header.
Sometimes it is working when loading the scripts at the end, the two url's above are using the same single-{post_type}.php template, only the first link is an elementor page, the second is custom php code within the theme...

**Comment by zzseba78** [comment]
> @zzseba78 Thank you. I tested this and seems to work with the scripts loading in the header. Sometimes it is working when loading the scripts at the end, the two url's above are using the same single-{post_type}.php template, only the first link is an elementor page, the second is custom php code within the theme...

@WebStation12 It´s fixed now `3.16.10 (March 20, 2023) Fix including UIkit scripts at the end of body element`

**Comment by WebStation12** [comment]
@zzseba78 Thanks again! I've noticed it and the issue is solved!

**Comment by WebStation12** [comment]
@janschoenherr Thank you for solving the issue so quickly!
I've been using Uikit since early 2015, tried a few other frameworks like Bootstrap, Foundation, etc. but Uikit is the best lightweight framework I've come accross. Takes only 15ms to load and I'm getting even 100-scores! Keep up the excellent work!
