### ISSUE TITLE
Error in icon display

### ISSUE THREAD

**Issue by hrjsoft** [uikit/uikit#4756]
After setting the icon in the appearance view, it is not displayed

![image](https://user-images.githubusercontent.com/100397052/226205785-10bf9ce0-3bb4-40f0-9dd1-576d39c4c78f.png)

**Comment by zzseba78** [comment]
@hrjsoft Check if it's related to this: https://github.com/uikit/uikit/issues/4757

**Comment by hrjsoft** [comment]
🙏🙏🙏🙏🙏

‫‪Sebastian‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۲۰ مارس ۲۰۲۳
ساعت ۱:۵۵ نوشت:‬
