### ISSUE TITLE
uk-scrollspy-nav not apply uk-active class in menu in off-canvas

### ISSUE THREAD

**Issue by samuelesantoni** [uikit/uikit#4759]
### UIkit Version

Latest stable version.

### Actual Behavior

 uk-active class is not applied to nav menu in off-canvas or is applied casually.

### Expected Behavior

uk-active class should be applied to menu item when i'm in the relative section.

### Steps to Reproduce the Problem

1. Go to https://www.gimapulizie.com
2. Simply use the site and check the class uk-active in menu. In off-canvas (from mobile) the uk-active class is not applied or is applied casually.

_If i scroll the page the class uk-active is applied correctly but if i click on menu item the class is not applied or is applied casually._

**Comment by janschoenherr** [comment]
Seems to be working fine on iOS

**Comment by samuelesantoni** [comment]
Thanks for reply @janschoenherr.

I have the latest versione of iOS and Safari. 
I have cleared all data on Safari. After, i recorded this video.

> Seems to be working fine on iOS
Are you sure? https://drive.google.com/file/d/1xj-gDtOiYI6HfsRwL_iwRZT8w7L83AF8/view?usp=share_link

When i'm in home uk-active is for example on service (in italian Servizi)...if i go on contact uk-active is for example on Company (in italian Azienda). The class uk-active is applied, seems, casually.

**Comment by samuelesantoni** [comment]
I have update my site with the latest version of UIkit ma the issue is not solve. Any news about it?
