### ISSUE TITLE
Sass-loader error after last uikit upd;

### ISSUE THREAD

**Issue by bohdanp44** [uikit/uikit#4762]
Hi there!

From today I started to receive a such error. I use the latest uikit and sass-loader
reference to the line where this error is -  https://github.com/uikit/uikit/blob/34f31c3b0aa6db42e00a11ce87ed7c4461fcb8b5/src/scss/components/navbar.scss#L405

When I rewrite "when not"  to @if not it works just fine.

**UPD**
Even @when not works fine. Like that:
`@when not ($navbar-dropdown-color-mode = $inverse-global-color-mode) {
  .uk-navbar-dropdown :focus-visible {
	outline-color: $navbar-dropdown-focus-outline !important;
  }
}`

Any advice would be very appreciated!

**Comment by oliversigllimet** [comment]
Hi everyone! I get the exact same error from the dropbar component of uikit:

`Error in plugin "sass"
Message:
    node_modules/uikit/src/scss/components/dropbar.scss
Error: Invalid CSS after "...isible when not": expected selector, was "($dropbar-color-mod"
        on line 86 of node_modules/uikit/src/scss/components/dropbar.scss
`

**Comment by janschoenherr** [comment]
Thanks, will be fixed asap.
