### ISSUE TITLE
Uk-accordion duration doesn't work?

### ISSUE THREAD

**Issue by nreilly-voyou** [uikit/uikit#4767]
Hi,

I have a lot of content inside my accordion and i want it to open faster using the duration component but the open/close speed stays the same. Could be a bug. Here's how i wrote it : 
data-uk-accordion="animation: true; duration: 100;"

Any clue on what's the problem?

**Comment by janschoenherr** [comment]
There is a new, not yet documented, `velocity` option. Currently the formula is `velocity * height + duration`. Setting velocity to a lower value will decrease the duration. The default is `0.2`.

While writing this, it seems to me, that `velocity` isn't a good option name 😏
