### ISSUE TITLE
Uncaught ReferenceError: VERSION is not defined

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#4770]
### UIkit Version
3.16.14

### Steps to Reproduce the Problem

I would like to use a single component on the page, instead of connecting the whole UIkit (JS & CSS files)
I have code in my .js file:

```
import UIkit from '../../node_modules/uikit/src/js/uikit-core';
import Countdown from '../../node_modules/uikit/src/js/components/countdown';
UIkit.component('countdown', Countdown);
```

It's compiled properly, but when I open the page in browser, in dev tools I have an error:
```
Uncaught ReferenceError: VERSION is not defined
```
I tried to use other components, and always the same error appears.

**Comment by janschoenherr** [comment]
If you want to include the sources directly, you'll have to use replace the `VERSION` manually. UIkit uses '@rollup/plugin-replace' to compile with rollup.
