### ISSUE TITLE
Grid sometimes not applying margin

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4774]
On some page loads - appears to be those where the file is cached - the margin is not applied to the grid and the uk-grid-stack class is applied instead. 

When I log columns.length (where the stack class is applied), it says it is 1 when it is actually 3. When the margin is applied (no stack class used) the value is 3.

I suspect this may be to do with the boot behaviour change in 3.16.7? It does seem to happen when the page loads really quickly, perhaps UIkit is booting before it can actually count all the columns? In the case of this HTML file, there are a lot of preceding nodes (large navigation). Is there another reason why it might incorrectly count the columns?

I'm currently solving the issue with:
```
setTimeout(() => UIkit.update(), 128);
```

### UIkit Version

3.16.14, also tested to 3.16.11

**Comment by janschoenherr** [comment]
Do you have link for us to inspect? Thanks.
