### ISSUE TITLE
Dropdown (and other components) doesn't work after replacing the DOM with AJAX response

### ISSUE THREAD

**Issue by matronator** [uikit/uikit#4778]
### UIkit Version

3.16.15

### Actual Behavior

I have some dropdowns with `uk-dropdown` attribute on them and they work when the page loads. But then I send a request to update the page with AJAX and after the DOM is updated, the dropdowns no longer work. Also, every time I hover over them with my cursor, these errors appear in the console (on every `mouseenter`):

<img width="1470" alt="Snímek obrazovky 2023-04-25 v 2 21 05" src="https://user-images.githubusercontent.com/5470780/234143580-6d725ba3-460e-4f28-9581-671653dba853.png">

<img width="1470" alt="Snímek obrazovky 2023-04-25 v 2 21 15" src="https://user-images.githubusercontent.com/5470780/234143557-8f52cedf-47be-4001-b8ca-6b351d22f5ee.png">

### Expected Behavior

The dropdowns would work normally even after updating the page with AJAX.

### Reproduction Link

It's dependent upon PHP framework, so I can't put it on codepen.

### Steps to Reproduce the Problem

1. Create `uk-dropdown`s on the page somewhere.
2. Replace that part of the page with the dropdowns with the exact same HTML, sent via AJAX
3. Try hovering over the dropdowns.

I tried initializing them again with a `afterAjax` hook from the library I'm using, but that didn't help either.

**Comment by janschoenherr** [comment]
It would still be good to have a Codepen that shows that replacing parts of the DOM causes this behavior. You are not replacing the whole document, are you?

**Comment by matronator** [comment]
> It would still be good to have a Codepen that shows that replacing parts of the DOM causes this behavior. You are not replacing the whole document, are you?

Okay, I will try to make something when I get back from work. And no, it's just parts of the document specified by IDs.
