### ISSUE TITLE
Positions not working when building from sass (might be sass-bug)

### ISSUE THREAD

**Issue by csaggo** [uikit/uikit#4779]
### UIkit Version

3.16.15

### Actual Behavior

uk-position-top-center (and others) not working with theme from sass.
the reason is :

/* ========================================================================
   Component: Position
 ========================================================================== */

:root { --uk-position-margin-offset: 0px; }

this becomes 
:root { --uk-position-margin-offset: 0 } 
when compiled with sass (this should probably be fixed in sass. ) 
now 
.uk-position-top-center, .uk-position-bottom-center {
    left: calc(50% - var(--uk-position-margin-offset));
wont work and result in left: 0; in the browser
while it works with a unit (works with 0px in the css-var, this is also what is distributed in uikit.min.css)

 sass removes px when the value is 0. when i do 0.0001px it works.

### Expected Behavior

should also incluce a unit when building with sass. maybe it can be interpolated or something. i will also post in sass as i would expect a unit to stay there if it is put there.

### Steps to Reproduce the Problem

use position center when compiled with sass

**Comment by janschoenherr** [comment]
This is not happening for me, are you using the latest https://sass-lang.com/ version?

**Comment by csaggo** [comment]
Oh i should have mentioned i used latest node-sass. Also just found out that is only maintained but will not get new features in the future.

they say it should be replaced with dart-sass if still used, so i will try with dart-sass and report if that resolves it.

**Comment by csaggo** [comment]
@janschoenherr it is solved, the actual reason was the css minifyer i used. the unit actually is still there after sass compile but gone after my minifaction .sorry for bothering. Thank you for the greatest frontend-framework :-)
