### ISSUE TITLE
Styles Content-Security-Policy (CSP) issue

### ISSUE THREAD

**Issue by rvalitov** [uikit/uikit#4792]
### UIkit Version

3.16.19

### Actual Behavior

I have CSP activated, and get the following error in browser console:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-GMBNFJnWK7S6UQi887SppZEhbje63pl5wP7/8bxw93s='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

The error link leads to UIkit JS file to line:
```
i.insertAdjacentHTML("beforeend", t.trim()) : i.textContent = t
```
![image](https://github.com/uikit/uikit/assets/16267156/b34d876d-8b39-48f1-b243-5fb0cfea0ee0)

### Expected Behavior

Inline styling should be avoided.

### Reproduction Link

No links, sorry

### Steps to Reproduce the Problem

I use a simple UIKit page with switcher and `uk-filter` for `grid`.

**Comment by janschoenherr** [comment]
I don't think that can or will be changed anytime soon. You can work around the issue by allowing inline styles: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
