### ISSUE TITLE
Drop items stop opening when clicked while they're open

### ISSUE THREAD

**Issue by falfituri** [uikit/uikit#4797]
### UIkit Version

3.16.19

### Actual Behavior

Drop item opens the first time correctly. When clicked while it's open it will break the next time it should open

### Expected Behavior

It should open regardless.

### Reproduction Link

https://codepen.io/fahmifitu/pen/xxQxYeM

### Steps to Reproduce the Problem

Open the reproduction link and follow the steps:

1. Hover over Parent # 1
2. Click Parent # 1
3. Hover over Parent # 2
4. Hover or click Parent # 1 multiple times (it won't open)

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/8a382829ddf60a7f159f8322cb663ba3bd4c0c67
