### ISSUE TITLE
Sass compiling error 3.16.20

### ISSUE THREAD

**Issue by bogdancondorachi** [uikit/uikit#4807]
Hi there, from version 3.16.20 I get the following compiling error. Also, what's the reason behind removing the component's sass variables?

`[plugin:vite:css] [sass] Undefined mixin.
    ╷
129 │     @include svg-fill($internal-list-bullet-image, "#000", $list-bullet-icon-color);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\uikit\src\scss\components\list.scss 129:5  @import
  src\theme\_import.scss 10:9                             @import
  src\main.scss 51:9                                      root stylesheet
C:\Users\bogda\OneDrive\Projects\htdocs\double-check\node_modules\uikit\src\scss\components\list.scss:129:5`

### UIkit Version
3.16.21

**Comment by janschoenherr** [comment]
Are you using this guide? https://getuikit.com/docs/sass#how-to-build

**Comment by bogdancondorachi** [comment]
Yes, I follow been following that guide in several projects and everything worked fine until I've tried to update to =>3.16.20

If I choose a version =<3.16.19 the compiling problem does not show anymore, so I figure it's something regarding the latest version but can't find nothing related in the last release that might cause the problem.

I've tryied to update the package on a different project but with same results

**Comment by janschoenherr** [comment]
And you do include the file `@import "uikit/src/scss/uikit-theme.scss";´ last, right? Because the error message seems to suggest, that the `src/scss/components/mixin.scss` file is missing.

3.16.19 and 3.16.20 are basically identically, but the changelog was messed up in 3.16.19. The last working version should probably be 3.16.18 then.

**Comment by bogdancondorachi** [comment]
Ok, I think I know where might be an issue here (though I had no problem till this release with this setup)

I'm using a custom _import.scss (instead of uikit-theme.scss) so I don't import components that I don't need. Here I didn't add mixin.scss resulting in the undefined mixin error. I've added the mixin.scss file but now I get a new error that was the reason for removing the mixin.scss file in the first place:

`[plugin:vite:css] [sass] expected ")".
   ╷
31 │     background-image: url(../node_modules/uikit/src/scss/components/quote($replace-src));
   │                           ^
   ╵
  node_modules\uikit\src\scss\components\mixin.scss 31:27  @import
  src\theme\_import.scss 3:9                               @import
  src\main.scss 51:9                                       root stylesheet`

**Comment by janschoenherr** [comment]
That seems like a bug in the vite sass plugin?

If you replace the `svg-fill` mixin in `scss\components\mixin.scss` with 

```
@mixin svg-fill($src, $color-default, $color-new){
    $replace-src: str-replace($src, $color-default, $color-new) !default;
    $replace-src: str-replace($replace-src, "#", "%23");
    $replace-src: quote($replace-src);
    background-image: url($replace-src);
}
```

Does that work?

**Comment by janschoenherr** [comment]
Thanks, I've included the workaround here: https://github.com/uikit/uikit/commit/39ef5b96b1aa011a6ee71982c7480a43d008f86b
