### ISSUE TITLE
LOG in hooks.js is not defined

### ISSUE THREAD

**Issue by manuelkleinert** [uikit/uikit#4829]
### UIkit Version
3.16.22

### Actual Behavior

LOG in hooks.js is not defined

### Steps to Reproduce the Problem

https://github.com/uikit/uikit/blob/develop/src/js/api/hooks.js

if I write the LOG lowercase it works.
`log && log(instance, hook);`

**Comment by aarongerig** [comment]
@manuelkleinert If you're trying to compile UIkit from source in a build process (e.g. webpack), then you should globally define that variable. For example with webpack you could use the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/):

```js
new webpack.DefinePlugin({
  LOG: false
});
```

UIkit does the same in their builds, see: https://github.com/uikit/uikit/blob/develop/build/util.js#L88
If that helps, let me know and I'll close the ticket!

**Comment by manuelkleinert** [comment]
Thank you so works with Webpack.
