### ISSUE TITLE
I want to have something like Carousel using uikit !

### ISSUE THREAD

**Issue by lyquocphong** [uikit/uikit#483]
Hi !
I am new to uikit and know that slidenav add-on is used to make something like Carousel but when I apply it does not work at all. Have anyone can show me the way the make Carousel with uikit ?

THank you so much !

**Comment by connectr** [comment]
@aheinze

Any update on the core carousel? or would it be better to go with another jquery plugin in the mean time? Just don't want to go ahead if you guys are planning on releasing something in the near future ;)

Thanks!
Chris

**Comment by aheinze** [comment]
https://github.com/uikit/uikit/tree/feature/slideset ;-)

**Comment by connectr** [comment]
@aheinze Awesome, thanks Artur! 

I ended up going with Slick (that @zslabs mentioned) and it works really well. 

That said, I'm excited to give the new Slideset component a try :)
