### ISSUE TITLE
Eye Icon is not working

### ISSUE THREAD

**Issue by m-brandao** [uikit/uikit#4843]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.16.22

### Actual Behavior

_What happened? Screenshots please, if relevant!_

### Expected Behavior

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1. Use span class="uk-margin-small-right" uk-icon="check" /span, this will show the check icon
2. Then replace it by: span class="uk-margin-small-right" uk-icon="eye" /span and it will show nothing
3.

**Comment by janschoenherr** [comment]
Please provide more information. How do you replace the icon?
