### ISSUE TITLE
Syntax error in regular expression

### ISSUE THREAD

**Issue by arafat-amin** [uikit/uikit#4858]
/*! UIkit 3.6.18 | https://www.getuikit.com | (c) 2014 - 2021 YOOtheme | MIT License */

Syntax error in regular expression: /<symbol([^]*?id=(['"])(.+?)\2[^]*?<\/)symbol>/g

at line 5445: var symbolRe = /<symbol([^]*?id=(['"])(.+?)\2[^]*?<\/)symbol>/g;

The error occurs after running Bundler & Minify Extension on VS community.

**Comment by janschoenherr** [comment]
Hi, this seems to be more of a bug with the minify extension?
