### ISSUE TITLE
Programmatic Dropdown Closure Not Working in UIkit 3.16.x

### ISSUE THREAD

**Issue by YassineGherbi** [uikit/uikit#4875]
### UIkit Version

3.16.11

### Actual Behavior

In previous versions of UIkit, I was able to programmatically close the Dropdown element using Vue.js 2 by toggling the `uk-open` class. My implementation looked like this:

```vue
<div class="uk-dropdown" :aria-expanded="open" :class="{ 'uk-open': open }">
  <a uk-icon="close" class="uk-align-right" @click="open = false" />
  <p>Just some content</p>
</div>
```

Since newer versions have shifted to `uk-dropdown="mode: click;"`, I can't find a way to programmatically close the dropdown.

### Expected Behavior

I expect to be able to programmatically close the Dropdown element using Vue.js 2, similar to how it worked in previous versions of UIkit.

### Reproduction Link

[CodeSandBox](https://codesandbox.io/s/kind-shaw-nsv964?file=/src/components/AlsoNotWorkingDropdown.vue)

### Steps to Reproduce the Problem

1. Create a Dropdown element in Vue.js 2 using UIkit 3.16.11
2. Attempt to programmatically close it using Vue.js 2 methods.
3. Observe that the dropdown does not close as expected.

### Comment

If there's a new way of programmatically closing the dropdown that I am not aware of, please inform me. Thanks in advance!

**Comment by janschoenherr** [comment]
Why do you need Vue to close the dropdown? You can simply use https://getuikit.com/docs/close#close-in-drops

If that does not work, try to add the class `uk-drop` to the `div` with `uk-dropdown`.
