### ISSUE TITLE
Update X(Twitter) name and logo

### ISSUE THREAD

**Issue by oldcastlehq** [uikit/uikit#4886]
### UIkit Version

3.16.26

### Actual Behavior

Twitter(X) changed name and logo

### Expected Behavior

It should reflect the new name and logo.

**Comment by harshit-ostwal** [comment]
Yeah! I have updated the logo of X(twitter) and Name also . This was my First Contribution

**Comment by oldcastlehq** [comment]
I will tell my boss that the blame for not having the X logo on our website is because UIKIT is not in a hurry to update it :smile:

**Comment by Surbma** [comment]
+1 for this, we need the new logo! :)

**Comment by nathanp** [comment]
+1 for wanting the new X logo

**Comment by mikeviele** [comment]
Bumping this as we have clients using this icon library that need to update to the new "X" logo to stay current.

**Comment by Bar-Rabbas** [comment]
I need it too for social share buttons.

**Comment by janschoenherr** [comment]
Resolved with 3.18.0
