### ISSUE TITLE
scrollspyNav incorrect scrolling to an element with a fixed element in the window

### ISSUE THREAD

**Issue by uatrend** [uikit/uikit#4894]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.17.1

### Actual Behavior

incorrect scrolling to an element
_In UIkit 3.16.26 everything works_

### Steps to Reproduce the Problem

On UIkit site change the following properties in class `.tm-sidebar-left` and click another sidebar right menu item.

Before:

```
.tm-sidebar-left {
    position: fixed;
    top: 80px;
    bottom: 0;
    box-sizing: border-box;
    width: 240px!important;
    padding: 40px 40px 60px 40px;
    border-right: 1px #e5e5e5 solid;
    overflow: auto;
}
```

After:

```
.tm-sidebar-left {
    position: fixed;
    top: 0; // Changed
    bottom: 0;
    box-sizing: border-box;
    width: 240px!important;
    padding: 40px 40px 60px 40px;
    border-right: 1px #e5e5e5 solid;
    overflow: auto;
    z-index: 1001; // Added
}
```

**Comment by janschoenherr** [comment]
Fixed with 681c7ab34157ffc1dc3646c558945bb9dcd49fb5
