### ISSUE TITLE
Add Telegram Icon

### ISSUE THREAD

**Issue by geshov** [uikit/uikit#4895]
Please, add icon for Telegram Messenger in icon set of UIkit.

Thanks!

**Comment by Sulpher** [comment]
@geshov, 
It's definitely would be better to have Telegram icon in core icon set.

Btw, in Russian speaking area we usually add some icons like Telegram and VK as custom icons.
Here you can read more how to do it:
https://jpath.ru/uikit-icons-compiler

**Comment by alex-revo** [comment]
Added.
