### ISSUE TITLE
Build fails when custom icons folder included under the theme (custom/mytheme/icons)

### ISSUE THREAD

**Issue by asbothe** [uikit/uikit#4922]
### UIkit Version

3.17.11 and previous versions since approxemately 3.15

### Actual Behavior

**Creating a theme with own icons works, if the icons are in a global folder:**
uikit/custom/mytheme
uikit/custom/icons

**Creating a theme with own icons fails, if the icons are under the theme folder:**
uikit/custom/mytheme
uikit/custom/mytheme/icons

**Error message:**
```
pnpm compile
file: ... uikit/node_modules/.pnpm/uikit@3.17.11/node_modules/uikit/build/icons.js:28
    const [, name] = folder.toString().match(new RegExp(match, 'i'));
                     ^
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
```

### Expected Behavior

Icons should be compiled like it is written in the documentation:
https://getuikit.com/docs/custom-icons

It worked previously, but fails since some months.

### Reproduction Link

Not available (build error).

### Steps to Reproduce the Problem

1. Create a theme with own icon folder under the theme folder:
uikit/custom/mytheme
uikit/custom/mytheme/icons
2. pnpm compile
3. fails with error "TypeError: object null is not iterable"

**Comment by MQ-J** [comment]
I´ve face the same bug.

![image](https://github.com/uikit/uikit/assets/61765516/729175cb-eaa9-4dd8-ab05-95ec9d7c6a12)

**Steps to Reproduce the Problem**
1. Create a theme with own icon folder under the theme folder:
uikit/custom/mytheme
uikit/custom/mytheme/icons
2. npm run compile
3. fails with error "TypeError: object null is not iterable"
