### ISSUE TITLE
Slideshow Component: ARIA validation error - Values assigned to role="" are not valid ARIA roles.

### ISSUE THREAD

**Issue by WebWorkingMan** [uikit/uikit#4927]
### Actual Behavior

When using Chromes "Lighthouse" tool, I get a warning: 

`Values assigned to role="" are not valid ARIA roles`

![2023-11-29 11_24_33-Slideshow - UIkit tests](https://github.com/uikit/uikit/assets/3637410/e532bc47-1d47-45be-9587-31f0cbbdd44f)

### Expected Behavior

Valid ARIA roles - don't know exactly what have to be done.

### Reproduction Link

https://getuikit.com/assets/uikit/tests/slideshow.html and use the Lighthouse.

**Comment by strizhakovanatalya** [comment]
UIkit Version 3.18.3 still the same problem in UIkit 3 Slider and UIkit 3 Stripes.
![aria](https://github.com/uikit/uikit/assets/49317308/b9b0fe27-5fc6-4ab5-a3fa-3c83e6af124e)

**Comment by denysdesign** [comment]
Please fix it👍

**Comment by jlahijani** [comment]
Can confirm this is still an issue in 3.19.2.

**Comment by janschoenherr** [comment]
Fixed with latest release. You'll need to update the markup though.
