### ISSUE TITLE
*tlester

### ISSUE THREAD

**Issue by hunar88** [uikit/uikit#4945]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.17.11

### Actual Behavior

_What happened? Screenshots please, if relevant!_

### Expected Behavior

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1.
2.
3.

**Comment by romy2012** [comment]
?

**Comment by romy2012** [comment]
Looking forward to v3.17.12
