### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by slabcloud** [uikit/uikit#4949]
Steps to reproduce:
1. Created a folder c:\uikit
2. In CMD typed cd c:\uikit
3. ran following commands:
pnpm add uikit
pnpm install
pnpm compile
I'm getting the following error: 
**'compile' is not recognized as an internal or external command,
operable program or batch file.
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "compile" not found**
 
Tried on three windows machines, one of them had a fresh install of Windows 10, Node, and PNPM

**Comment by wiredprairie** [comment]
There wouldn't be a `compile` script defined in `package.json` given the steps you performed. 

If there were a script defined as `compile`, using `pnpm` you'd need to use this syntax to `run` it:
```
pnpm run compile
```

**Comment by janschoenherr** [comment]
Hi, unfortunately, currently we don't have a CLI for UIkit. You'll need to run `pnpm install` and `pnpm compile` from within the UIkit folder.
