### ISSUE TITLE
Cannot scroll horizontally overflowing elements in modals on touch devices

### ISSUE THREAD

**Issue by msimmer** [uikit/uikit#4957]
### UIkit Version

3.17.11

### Hardware Version

iPhone 13 v17.2.1

### Actual Behavior

When an element overflows horizontally inside of a modal, it is not possible to scroll left/right on touch devices. 

### Expected Behavior

That the user is able to scroll horizontally inside of overflowing elements on touch devices. This is especially useful if a table is included inside of a modal, as the table's width may be larger than the modal/screen width to accommodate several columns.   

### Reproduction Link

https://codepen.io/msimmer/pen/OJqxoBg

### Steps to Reproduce the Problem

1. Visit link on iPhone (I've only tested on an iPhone)
2. Click "Open" button to toggle modal
3. Attempt scrolling text horizontally in modal body

### Possible Resolution

It appears that scroll behaviour via `touchmove` is being prevented in the `preventBackgroundScroll` method [here](https://github.com/uikit/uikit/blob/develop/src/js/mixin/internal/scroll.js#L4). It seems like there could be an additional check against the width of the `scrollParent` that would then allow horizontal scrolling. 

I'm opening a PR to submit to address this issue

**Comment by janschoenherr** [comment]
Should be fixed with: be8fddf582963bff9304696431de679c6f33e817
