### ISSUE TITLE
Autocomplete: How to get the datasource with callback function to work?

### ISSUE THREAD

**Issue by Kauppi** [uikit/uikit#496]
In the documentation for the Autocomplete addon it should be possible to set a callback function as source. I don't get it to work. Can someone provide me with an example?

Option: Source
Options: url, array, callback function

Documentation:
http://getuikit.com/docs/addons_autocomplete.html

**Comment by khanduras** [comment]
Hello @aheinze, I'm using this code and I get the proper json in the console but the drop down still says there's no results. Through my findings, if I set ```cache: false``` it doesn't show results through console. Any suggestions?

```
var input = $('#searchInput');

var searchdown = $.UIkit.search($('#dropSource'), { 
    source: function(release) {
        var json = "";

        $.when($.ajax({
            type: 'GET',
            url: '{{ base_url }}/search.json/query:' + input.val(),
            dataType: 'html',
            async: false,
            timeout: 30000
        })).done(function(data) { 
            json = data;
            if (json) {
                release(json.html);    
            }
        });

        console.log(json); 
        
    },
    delay: 500,
    minLength: 4 
});
```

**Comment by malles** [comment]
Here are some examples: http://codepen.io/malles/pen/qEyEZr
I can't see why you use dataType `html` for your json call.. Try the console where it matters, just before release.
For codehelp it's often easier to try the [UIkit Gitter](https://gitter.im/uikit/uikit)
