### ISSUE TITLE
uk-grid inside uk-section

### ISSUE THREAD

**Issue by ps73** [uikit/uikit#4980]
When using a uk-grid inside uk-container-expand the first item expands out of the container box.

```
<div data-id="page#6" class="uk-section-default uk-section uk-padding-remove-vertical">
  <div data-id="page#6-0" class="uk-grid tm-grid-expand uk-margin-remove-vertical" uk-grid>
     <div class="uk-light uk-width-1-2@s uk-width-1-4@l" data-id="page#6-0-0" id="page#5">
        <div class="uk-panel uk-margin-remove-first-child uk-margin" data-id="page#6-0-0-0" data-element>
        ...
        </div>
        ...
    </div>
  </div>
</div>
```
When adding `uk-grid-collapse` to `uk-grid` everything works fine.

### UIkit Version

YooTheme 4.3.4

### Actual Behavior

<img width="1780" alt="image" src="https://github.com/uikit/uikit/assets/17291660/99b8f684-2925-41af-8c22-ad1c92ddd307">

### Expected Behavior

<img width="1819" alt="image" src="https://github.com/uikit/uikit/assets/17291660/14df6ab1-8219-41d6-840e-01a1187e2ffd">

**Comment by saschadube** [comment]
Please post this in the YOOtheme Support Center https://yootheme.com/support
