### ISSUE TITLE
Slider with Lightbox

### ISSUE THREAD

**Issue by jagisx** [uikit/uikit#4985]
I'm using the slider component along with the lightbox. Version >= 3.17.11 works but latest versions do not. On the later versions, when you slide the images, once you release the mouse button, it launches the lightbox, every time. The older version works great, allows you to slide the images and only launches the lightbox when you actually click the single image you want to pop up.

Thank you.

**Comment by viocassel** [comment]
Confirm ☝️

**Comment by viocassel** [comment]
@janschoenherr could you look at this problem?
