### ISSUE TITLE
lightboxPanel not work with data-image

### ISSUE THREAD

**Issue by prfardin** [uikit/uikit#4987]
Its simple, when we try to add data:image type like source to lightbox panel its not working, like:

<pre>
UIkit.lightboxPanel({
    items: [{
      source: images['data:image/jpeg;base64,/9j/4AAQ.....'],
      caption: 'Data Image Not Working'
    }]
}).show()
</pre>

**Comment by janschoenherr** [comment]
Please try with `type: 'image'` .
