### ISSUE TITLE
This trying to access undefined in Firefox raising exception

### ISSUE THREAD

**Issue by dlmiles** [uikit/uikit#4994]
https://github.com/uikit/uikit/blob/f5339774616964ea6f893616544e97457556da2f/src/js/util/viewport.js#L193

<img width="1052" alt="Screenshot 2024-03-13 155935 UKIt_3_17_9" src="https://github.com/uikit/uikit/assets/293087/6d15d3d4-b652-4b76-aef5-b8647d5e93e1">

Here is a screenshot showing the situation.

I think some kind of defensive coding is required here.

**Comment by janschoenherr** [comment]
Hi, could you provide a minimal codepen example reproducing the error?

**Comment by dlmiles** [comment]
Confirmation: The release of UIKit made since this was issue closed and today, does seem to have resolved the issue.
