### ISSUE TITLE
ERROR: No matching export in "node_modules/uikit/dist/js/uikit.js" for import "default"

### ISSUE THREAD

**Issue by bornova** [uikit/uikit#5002]
### UIkit Version
\>=3.20.0

### Actual Behavior
When UIkit is loaded using `import UIkit from 'uikit'` and try bundling with `esbuild`, following error is thrown:

`ERROR: No matching export in "node_modules/uikit/dist/js/uikit.js" for import "default"`

There were no issues with with v3.19.4.

### Expected Behavior
No error

**Comment by viocassel** [comment]
Confirm ☝️

**Comment by janschoenherr** [comment]
Sorry for the hiccup, the changes are reverted now with 3.20.7
