### ISSUE TITLE
uk-slider animation in safari is buggy when scrolling quickly or with the sets:true parameter

### ISSUE THREAD

**Issue by awkirin** [uikit/uikit#5006]
I recorded a video with a glitch:
https://www.youtube.com/watch?v=PFS7HWtignY

link to the documentation:
https://getuikit.com/docs/slider#slide-sets

My configuration
iMac: Retina 5K, 27-inch, 2017
Processor: 3,4 GHz Quad-Core Intel Core i5
Graphics: Radeon Pro 570 4 GB
Memory: 32 GB 2400 MHz DDR4
macOS: Ventura 13.6.6

Safari: Version 17.4.1 (18618.1.15.111.8, 18618)

**Comment by janschoenherr** [comment]
Fixed with https://github.com/uikit/uikit/commit/8e8f67f8b5ccbd1092b3e324c949a289dcf1c815
