### ISSUE TITLE
uk-sortable: - quick sorting of tables (<tbody) breaks the markup (freezes)

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#5007]
Hi!
UIkit Version 3.20.8 (April 26, 2024)

1. `<tbody id="body-table" class="uk-text-small" uk-sortable>`
2. if you drag the lines slowly with the mouse, it works
3. if you quickly drag the lines with the mouse, it freezes

https://github.com/uikit/uikit/assets/16114000/25b167e3-0bce-4115-b5fa-d357d74cc285
https://github.com/uikit/uikit/assets/16114000/2470d7c6-3393-4b3d-82df-7b173d8b28cf

https://codepen.io/ef1/pen/qBGBMPa

please tell me if this can be fixed

**Comment by awkirin** [comment]
There is an html error in your example. unnecessary div tag

<img width="874" alt="image" src="https://github.com/uikit/uikit/assets/15372364/e61794b2-6665-44a6-96d7-465ce430eaa4">

**Comment by AlexandreZaytsev** [comment]
OK, I corrected it in the text, but that's not the point...

during quick sorting, it still freezes, sometimes until the page is forced to reload...

will probably have to abandon this type of sorting for now and add the sort column to the table ...
although your sorting is clearer and there is less code))

**Comment by awkirin** [comment]
I am not a framework developer. I just saw an error in the example and reported it.
It's a pity that it didn't help solve your problem.

**Comment by janschoenherr** [comment]
Hi, what browser are you using?

**Comment by AlexandreZaytsev** [comment]
Chrome Версия 124.0.6367.203 (Официальная сборка), (64 бит)
https://github.com/uikit/uikit/assets/16114000/e334a604-b07f-496f-9687-c8a8a7b88fee

Microsoft Edge Версия 124.0.2478.97 (Официальная сборка) (64-разрядная версия)
https://github.com/uikit/uikit/assets/16114000/dfd3d4e4-9ff2-4d89-971d-f1b489f3d2ce

Chedot Версия 9.3.2 (Chromium 86.0.4240.198) (Официальная сборка), (32 бит)
https://github.com/uikit/uikit/assets/16114000/aa3feae3-3ae2-4e7f-88bd-bb446b80a569

The picture is the same everywhere
1. When moving fast, it freezes
2. after that
3.  click on the area uk-sortable  the table is being restored
