### ISSUE TITLE
Switcher component inside a Modal triggers modal events

### ISSUE THREAD

**Issue by bornova** [uikit/uikit#5012]
### UIkit Version
3.21.0

### Actual Behavior
With a switcher component placed inside a modal, when the page loads and also when interacting with the switcher items, modal events are triggered.

### Expected Behavior
Modal events should only be triggered when an interaction with the modal occurs, not with other components inside it.

### Reproduction Link
https://codesandbox.io/p/sandbox/smoosh-leftpad-7vys4m

### Steps to Reproduce the Problem
1. Go to codesandbox link above.
2. Open console.
3. See that modal shown event has been triggered even though the modal has not been shown.
4. Open the modal and toggle between the switcher items.
5. See that every time a switcher item is clicked, the modal shown event is fired.

**Comment by janschoenherr** [comment]
Please see: https://github.com/uikit/uikit/issues/4186#issuecomment-617250516
