### ISSUE TITLE
Landscape to portrait not update properly (iPad M1 - uikit 3.21.3)

### ISSUE THREAD

**Issue by picov** [uikit/uikit#5014]
I've updated a website from uikit 3.14.3 to latest 3.21.3

With the old uikit version the page layout update automatically when I rotate the device based on the device width change.

With the 3.21.3 version only portrait to landscape update the layout while  landscape to portrait keep the exsisting one and there is the need to manually refresh the page to see the "real" layout.

**Comment by janschoenherr** [comment]
We need more information. What component does not update exactly?
