### ISSUE TITLE
Toggle close when toggle item click used javascript trigger

### ISSUE THREAD

**Issue by jimmy123j** [uikit/uikit#5022]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._

3.21.3

### Actual Behavior

Click toggle item close the toggle

### Expected Behavior

Click toggle item should not close

### Reproduction Link

[Code Sample](https://codepen.io/jimmy123j/pen/xxNpZLX)

### Steps to Reproduce the Problem

1. Click toggle trigger Link
2. Toggle Item show
3. Click toggle item then hide

**Comment by janschoenherr** [comment]
Yes, you are actually binding the toggle component to your toggle target. You'd have to unbind it, after toggling.

**Comment by jimmy123j** [comment]
does any sample for "unbind" it ?
can't find in doc
