### ISSUE TITLE
UIkit toggle inside modal (but trigger outside) not working

### ISSUE THREAD

**Issue by juanrpop** [uikit/uikit#5035]
Hi, here is a short explanation:

Inside `uk-modal` is not passing the `hidden` attribute to the multiples elements `<p>`.
The `<a>` with `uk-toggle` attribute is outside the `modal`.

You can view the case here:

https://codepen.io/juanrpop/pen/VwJeVbO

Thanks.

**Comment by dobaniashish** [comment]
The `togglable` mixin uses `isVisible` util function to check if element should be toggled if `cls` option is not set (toggle with `hidden` attribute).

`isVisible` returns false for elements whose parents are hidden. Check `Element.checkVisibility()` on mdn.

If you use the `cls` option with `uk-hidden` class, it will work properly for your case.

Example:

```html
<a href="#" uk-toggle="target: .toggle; cls: uk-hidden">TOGGLE</a>
```

**Comment by juanrpop** [comment]
Hi @dobaniashish, if I add `cls: uk-hidden` it only hides the four `<p>` elements. 

If I remove the `uk-modal` attribute, `hidden` works fine for the four `<p>` elements with `class:"toggle"`, but I lose the `modal` functionality.

This is a print screen that displays the HTML as it is loaded:
![image](https://github.com/user-attachments/assets/6edfe9be-a5f3-4966-a6f8-d121d672c8b3)

Here you can see that the `hidden` attribute does not change (gets lost) between the `<p>` elements inside the `modal` (this is the problem I am having) (the `hidden` attribute for the `<p>` outside of the modal works just well):
![image](https://github.com/user-attachments/assets/b68557b0-7a14-4dd1-b7fd-1683a3fad2a7)

**Comment by dobaniashish** [comment]
Hello @juanrpop, 

Check this codepen demo, it might help. [https://codepen.io/dobaniashish/pen/OJeNbxr](https://codepen.io/dobaniashish/pen/OJeNbxr)

**Comment by juanrpop** [comment]
Hi @dobaniashish, you were right from your first comment. Thank you very much.

Your solution was to add `cls:uk-hidden` to the `uk-toggle` component attribute, as well as the `uk-hidden` class to the `<p>` toggle element (instead of the `hidden` atribute).
