### ISSUE TITLE
UIkit 3.21.9 breaks navbar toggle if a modal exists with JavaScript embed

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#5048]
### UIkit Version
3.21.9

### Actual Behavior

I have a modal on a page that embeds a Formstack form in it using JS embed code.  For some reason, this causes my navbar offcanvas toggle to not work anymore.  This started occurring in 3.21.9, but 3.21.8 doesn't have this issue.  (This wasn't a problem for many years.)

### Expected Behavior

The navbar toggle should show the offcanvas menu correctly, regardless if a completely separate modal has JS embedded code.

### Reproduction Link

I made a completely minimal example here:
https://jonathanlahijani.com/temp/a90fxdkj208.html

If you want to make it work correctly, simply modify the code to use UIkit 3.21.8, ***or*** keep it at 3.21.9 and remove the Formstack embed code in the modal.

**Comment by janschoenherr** [comment]
This seems to be fixed with 3.21.11?
