### ISSUE TITLE
form-range.less has ; instead of ,

### ISSUE THREAD

**Issue by helmutkaufmann** [uikit/uikit#5093]
<!--

### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.21.16

### Actual Behavior

_What happened? Screenshots please, if relevant!_
@inverse-form-range-track-background:          darken(@inverse-global-muted-background; 5%);
 the ; should be a ,

### Expected Behavior
@inverse-form-range-track-background:          darken(@inverse-global-muted-background;,5%);

_What should have happened?_

### Reproduction Link

_A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)_

### Steps to Reproduce the Problem

1.
2.
3.

**Comment by saschadube** [comment]
Thanks! It's fixed here https://github.com/uikit/uikit/commit/0504ccdadee3e0bc325901feb6652382b43cc1c8
