### ISSUE TITLE
The file does not actually go the directory after completion of upload

### ISSUE THREAD

**Issue by kim2235** [uikit/uikit#517]
Hi I'm currently trying out the upload add-on  found on the addon tab on uikit's site but I'm having an issue on transferring the file that I'm uploading..  I changed the action found on the script that was provided and still no good 
I have attached an image to show you the current setting I have.. Am I doing something wrong here? or do I still need to add an html "form"? pls help
![capture2](https://cloud.githubusercontent.com/assets/6710436/3639393/82cd248e-107a-11e4-813a-a61c7dae970a.JPG)

**Comment by bernieschulenburg** [comment]
I have a very similar problem. I've set up a response servlet (Java) server-side, with an url `"/upload-response"` 
which currently just delivers back to client "upload confirmed". It's live, which I've tested just to make sure.

But it seems that on the client side the action parameter is simply ignored. I've tried 
```
action: "/upload-response"
action: "upload-response"
action: "https://full-domain-name.com/upload-response"
```
the documents <head> contains all the neccessary scripts I believe:
```
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.25.0/js/uikit.js"></script>
<script src="/uikit-2.25.0/js/components/autocomplete.js"></script> <!-- not quite sure I need this -->
<script src="/uikit-2.25.0/js/components/upload.js"></script>
```

nothing seems to work. 

btw: when I use a standard form with action="upload-response" and a submit button, then it works just fine.
Anyone know what I'm missing? Thanks for any help.
