### ISSUE TITLE
Nav (Accordion)

### ISSUE THREAD

**Issue by AndrewMarkUK** [uikit/uikit#534]
Copied this code for testing to my page...

<div class="uk-panel uk-panel-box">

                                    <h3 class="uk-panel-title">Nav side in panel</h3>

                                    <ul class="uk-nav uk-nav-side uk-nav-parent-icon" data-uk-nav="">
                                        <li class="uk-active"><a href="">Active</a></li>

                                        <li class="uk-parent">
                                            <a href="#">Parent</a>
                                            <div style="overflow: hidden; height: 0px; position: relative;"><ul class="uk-nav-sub">
                                                <li><a href="">Sub item</a></li>
                                                <li><a href="">Sub item</a>
                                                    <ul>
                                                        <li><a href="">Sub item</a></li>
                                                        <li><a href="">Sub item</a></li>
                                                    </ul>
                                                </li>
                                            </ul></div>

```
                                    </li>

                                    <li class="uk-parent">
                                        <a href="#">Parent</a>
                                        <div style="overflow: hidden; height: 0px; position: relative;"><ul class="uk-nav-sub">
                                            <li><a href="">Sub item</a></li>
                                            <li><a href="">Sub item</a></li>
                                        </ul></div>
                                    </li>

                                    <li><a href="">Item</a></li>

                                    <li class="uk-nav-header">Header</li>
                                    <li class="uk-parent"><a href=""><i class="uk-icon-star"></i> Parent</a></li>
                                    <li><a href=""><i class="uk-icon-twitter"></i> Item</a></li>
                                    <li class="uk-nav-divider"></li>
                                    <li><a href=""><i class="uk-icon-rss"></i> Item</a></li>
                                </ul>

                            </div>
```

However, on my page it does not work, though it works in your demos. Is there a required file to make the LI slidedown?  From my reading of the documentation its a simple case of adding data-uk-nav="" to the UL but it changes nothing.

Any ideas?

**Comment by developer99** [comment]
Still not working for me.
