### ISSUE TITLE
Include code snippets to show which files to include for components

### ISSUE THREAD

**Issue by florianletsch** [uikit/uikit#554]
Apparently people get confused which files to include when they want to use a certain component. There could be snippets in the docs do show which files need to be included.

https://plus.google.com/112304215949878536328/posts/dJ12xRPQvm7

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Within the UIkit3 docs we build the examples that way that the users can directly see the exact HTML code that has been used. We think that this will make it much easier for the users to understand how to achieve the same result without needing to take a look into the DevTools of the browser. 

Thanks for your understanding,
Your UIkit Team
