### ISSUE TITLE
Wordpress Walker Nav

### ISSUE THREAD

**Issue by ghost** [uikit/uikit#570]
Has anyone had success integrating UI kit into Wordpress? It seems you need a custom nav walker class of some sort but I'm not able to figure it out.

Just wondering if anyone has any success in getting this to work. I found a bootstrap nav walker but it is quite overly in-depth for UI Kit's simple menu structure!

**Comment by yhaow** [comment]
@zslabs 多谢，非常实用！

**Comment by lexsemenenko** [comment]
Simply amazing!
