### ISSUE TITLE
Sticky - Need to revert height and recalculate

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#587]
If the sticky item has items that either wrap or have grids within it, the system doesn't recalculate the height. When there is the "media" attribute on the sticky element, it also needs to take the explicit height off so the default static content isn't contained within what the height "expects" it to be.

**Comment by zslabs** [comment]
@aheinze I don't think the height should be calculated on page-load until the item is "stickied" and should be re-checked based on resize; since an elements content can wrap based on how wide the screen is.

**Comment by zslabs** [comment]
This is what I currently have to do on resize to make sure text doesn't wrap and change width calculations of the `uk-sticky-placeholder`:

	// Recalculate UIkit sticky component placeholder on resize (doesn't do this in the core... yet)
	function reCheckSticky() {
		$('.uk-sticky-placeholder').css('height', $('.uk-sticky-placeholder > [data-uk-sticky]').outerHeight());
	}
	win.on('resize', UIkit.Utils.debounce(reCheckSticky, 200));

**Comment by zslabs** [comment]
Actually it'd need to be more like this because you could have multiple instances on a page:

	function reCheckSticky() {
		$.each($('.uk-sticky-placeholder'), function(index, val) {
			var $instance = $(val);

			$instance.css('height', $instance.children().outerHeight());
		});
	}
	win.on('resize', UIkit.Utils.debounce(reCheckSticky, 200));

**Comment by aheinze** [comment]
Fixed https://github.com/uikit/uikit/commit/1617f4d19c546e8908051e5a141d29b9a42f0fc9

**Comment by zslabs** [comment]
Thanks man!

**Comment by TomS-** [comment]
This has returned in the latest UiKit

**Comment by kleinermann** [comment]
Awesome, this worked for me.
