### ISSUE TITLE
autocomplete callback

### ISSUE THREAD

**Issue by creativesprite** [uikit/uikit#588]
Hi all,

is there an example of using a callback e.g. alert a specific column from the returned record ?

thanks

**Comment by khanduras** [comment]
I'm using this: 
```
var input = $('#searchInput');

var searchdown = $.UIkit.search($('#dropSource'), { 
    source: function(release) {
        var json = "";

        $.when($.ajax({
            type: 'GET',
            url: '{{ base_url }}/search.json/query:' + input.val(),
            dataType: 'html',
            async: false,
            timeout: 30000
        })).done(function(data) { 
            json = data;
        });

        console.log(json); 
        
        if (json) {
            release(json);    
        }
```
Which saves appropriate JSON to the console but doesn't work with the dropdown for the search. The same code works fine if implemented manually but I'm trying to filter by URL. Note that I'm using $.UIkit.search instead - perhaps I need a different return ??

**Comment by malles** [comment]
Here are some autocomplete examples: http://codepen.io/malles/pen/qEyEZr
