### ISSUE TITLE
Off-canvas resize bug

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#589]
1. Resize window to small size
2. Open off-canvas component
3. Maximize the window

**Comment by jeffbetts** [comment]
I have a client that absolutely claims this behavior as a flaw. I know it's a minor detail and not normal for someone to expand their screen after expanding the offcanvas position. Can someone share the jQuery script that will close the offcanvas position when/if screen-width becomes greater than 960px? I know it's not as efficient and brings some overhead, but I'm faced with building a new theme on another framework if I can't get this behavior. Please help.

**Comment by zzseba78** [comment]
try this:
`$(window).resize(function () {
	var pageWidth = $(window).width();
        if (pageWidth > 960) {
        UIkit.offcanvas.hide('#offcanvas');
     };
});`

**Comment by jeffbetts** [comment]
Yes! Perfect! and does that really add that much overhead that it would be an issue with implementing this on any site build on the UIKit? Thanks zzseba78!

**Comment by zzseba78** [comment]
Hi Jeff, i´m glad it helps... I don´t know, surely this code can be better, js it´s not my strong point :), test how it works on mobile and if it don´t affect performance.
Ask in this place: https://gitter.im/uikit/uikit
It´s the UIkit developer community, you have Google + too.
