### ISSUE TITLE
Scroll position jumps to top when opening modal with height=100% on both html and body

### ISSUE THREAD

**Issue by john052** [uikit/uikit#590]
This is related to issue #310. I commented there but the issue was already closed.

When I have a height of **100% set on both the html and body** elements, opening a modal causes the the page to scroll to the top.

In Firefox, the scroll position is restored once the modal is closed, but so far this doesn't happen in other browsers.

At the moment, I change the modal.show() function to manually save the position when opened. Then in modal._hide() I just restore the saved position.

**Comment by vyscond** [comment]
I've replaced the `uk-height-1-1` for `uk-height-viewport` but the modal open event triggers the scroll up on the page :/

**Comment by fluctusz** [comment]
me too.

**Comment by 0xbaadf00d** [comment]
issue still persist (using last revision of the "develop" branch). I think the issue must be fixed on the modal JS code, not by using another CSS class.

**Comment by ikeedo** [comment]
Setting body and html to 100vh height didn't work for me as well. 

This worked:

`$('#modal-button').on('click', function () {
	return false;
});`

**Comment by geagoir** [comment]
this can also be fixed by CSS:
add 
 .uk-modal-page { overflow: visible !important; }
.uk-modal-page > body { overflow: hidden !important; }

**Comment by BernhardBaumrock** [comment]
@janschoenherr I hit that issue today and the fix by @geagoir worked!
Is there any reason why this is not part of uikit and the issue is closed?
