### ISSUE TITLE
Links don't work inside the uk-switcher

### ISSUE THREAD

**Issue by 5410ik34lk** [uikit/uikit#606]
Hello! I'm using tm-switcher form from the Unity theme (customer section in menu):  
http://yootheme.com/demo/joomla/unity
I want to find a solution which allows to work links placed inside the UL in this example:

</code>
&lt;div data-uk-grid-match=&quot;{target:'ul'}&quot;&gt;
&lt;div class=&quot;uk-float-left uk-width-medium-1-2&quot;&gt;
&lt;ul id=&quot;home-switcher&quot; class=&quot;uk-switcher tm-switcher-target&quot;&gt;
&lt;li&gt;&lt;img src=&quot;#&quot; alt=&quot;1&quot; height=&quot;600&quot; width=&quot;540&quot;&gt;&lt;/li&gt;
&lt;li&gt;&lt;img src=&quot;#&quot; alt=&quot;2&quot; height=&quot;600&quot; width=&quot;540&quot;&gt;&lt;/li&gt;
&lt;li&gt;&lt;img src=&quot;#&quot; alt=&quot;3&quot; height=&quot;600&quot; width=&quot;540&quot;&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;div class=&quot;uk-float-right uk-width-medium-1-2 tm-switcher&quot;&gt;
&lt;ul data-uk-switcher=&quot;{connect:'#home-switcher'}&quot;&gt;
&lt;li&gt;
&lt;p class=&quot;uk-margin-small-bottom uk-text-danger uk-h3&quot;&gt;
&lt;i class=&quot;uk-icon-child uk-h4 uk-text-primary&quot;&gt;&lt;/i&gt;Name 1&lt;/p&gt;
&lt;p class=&quot;uk-h4 uk-text-left uk-text-success&quot;&gt;Text 1&lt;/p&gt;
&lt;p class=&quot;uk-margin-small-top&quot;&gt; &lt;a class=&quot;uk-icon-button uk-icon-facebook&quot; target=&quot;_blank&quot; href=&quot;#&quot;&gt;&lt;/a&gt;
&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p class=&quot;uk-margin-small-bottom uk-text-danger uk-h3&quot;&gt;
&lt;i class=&quot;uk-icon-child uk-h4 uk-text-primary&quot;&gt;&lt;/i&gt;Name 2&lt;/p&gt;
&lt;p class=&quot;uk-h4 uk-text-left uk-text-success&quot;&gt;Text 2&lt;/p&gt;
&lt;p class=&quot;uk-margin-small-top&quot;&gt; &lt;a class=&quot;uk-icon-button uk-icon-facebook&quot; target=&quot;_blank&quot; href=&quot;#&quot;&gt;&lt;/a&gt;
&lt;/p&gt;
&lt;/li&gt;
&lt;/ul&gt;
</code>

Here is the same problem with no solution:
http://yootheme.com/support/question/68677

Best regards

**Comment by Flicksie** [comment]
This issue still happens in latest UIkit. Not using themes whatsoever. just plain UIkit. Whenever <a> is inside a uk-switcher links won't work . Inspector shows the click action was actually delegated to the switcher itself

```js
defaultPrevented: true​
delegate: <ul class="store-main uk-width-1-1…ab-content uk-switcher" uk-switcher="active:0" style="touch-action: pan-y pinch-zoom;">
```

**Comment by mattfletcher** [comment]
I've solved similar issues in the past with `uk-switcher` using `style="pointer-events: none"` on various elements.

**Comment by Flicksie** [comment]
good, we'll keep that in mind too as an option. our current workaround was ditch `active: X` in the `uk-switcher` attribute to determine an active index and instead opt to manually add the class `.uk-active` in the switcher itself and the target.

I still believe this issue should be reopened because such workarounds aren't the way the lib is intended to work. especially when a 1:1 copy of the example in their docs is enough to reproduce this error when the `uk-switcher` attribute is added to the target element

**Comment by janschoenherr** [comment]
There is also a `toggle` option that might help: https://getuikit.com/docs/switcher#component-options
