### ISSUE TITLE
Disable sortable | nestable

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#609]
Is it possible to disable sortable or nestable by javascript according to the manual
var sortable = $.UIkit.sortable(element, { /\* options _/ });
var nestable = $.UIkit.nestable(element, { /_ options */ });

Are there handlers like onstartdrag, onstopdrag, ondrop....?

Thanks

**Comment by metaine** [comment]
you can use noDragClass option and add this class to the grid thus disabling sorting interaction
