### ISSUE TITLE
autocomplete - how to bind a select handler?

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#611]
how is it possible to execute a select handler not only for click but also for keyboard select events?
Example Code from uikit page with additional data-id value

``` code
<div class="uk-autocomplete uk-form" data-uk-autocomplete="{source:'my-autocomplete.json'}">
    <input type="text">
    <script type="text/autocomplete">
        <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
            {{~items}}
            <li class="clicked" data-value="{{ $item.value }}"  data-id="{{ $item.id }}">
                <a>
                    {{ $item.title }}
                    <div>{{{ $item.text }}}</div>
                </a>
            </li>
            {{/items}}
        </ul>
    </script>
</div>
```

``` javascript
<script>
$(document).ready(function() {
$(document).on( "click", "li.clicked", function(  ) {
   alert($(this).attr('data-id'));
});
// The question here: how to bind this handler when a value 
// has been selected by keyboard and return key?
});
</script>
```

my-autocomplete.json like

[
    {"value":"Hamburg", "title":"Hamburg title", "url":"#", "text":"Lorem ipsum dolor sit amet, consectetur ...","id":"444"},
    {"value":"New York", "title":"New York", "url":"#", "text":"Ut enim ad minim veniam, quis nostrud ...","id":"4344"},
    {"value":"Moscow", "title":"Moscow", "url":"#", "text":"Duis aute irure dolor in reprehenderit ...","id":4444},
    {"value":"Amsterdam", "title":"Amsterdam", "url":"#", "text":"Excepteur sint occaecat cupidatat non ...","id":4454}
]

**Comment by jkrassman** [comment]
Hmmm, I am having problems getting the other values and id's....

My result looks like this: [{"value":"Staffan Larsson","id":125},{"value":"Stall Crypto","id":123}]

and when I am trying to get the id in the event handler, i am getting undefinied?

alert(data.value+' '+data.id);

Any suggestions?

Kind regards Joakim

**Comment by luetn** [comment]
Maybe just a missing item data-id="{{ $item.id }} in your template?
```
......<li data-value="{{ $item.value }}"  data-id="{{ $item.id }}">....

**Comment by jkrassman** [comment]
Aha, i do need an template - but wont it show up in the result then? I want the id to be hidden?

**Comment by luetn** [comment]
you can define (in the template) which data should be presented in the search results
```
...
{{ $item.title }}
<div>{{{ $item.text }}}</div>
</a>

**Comment by jkrassman** [comment]
Okey, i got it to work so big thanks for that. But the layout is looking strange in the dropdown now. Everything is aligned tight to the left and looks strange. And I cant select the items? My template looks like this

```
<script type="text/autocomplete">
        <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
		 {{~items}}
			<li data-value="{{ $item.value }}"  data-id="{{ $item.id }}">{{ $item.value }}</li>
		 {{/items}}
	 </ul>
</script>
```

**Comment by luetn** [comment]
take something like
```
<ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
	{{~items}}
	<li data-value="{{ $item.value }}"  data-id="{{ $item.id }}">
	<a>
	{{ $item.value }}
	</a>
	</li>
	{{/items}}
	</ul>

**Comment by jkrassman** [comment]
Thanks, you are  worth a golden star for today!

Best regards, Joakim

**Comment by luetn** [comment]
Thanks
Happy new year :-)

**Comment by rockymontana** [comment]
And now to ```'selectitem.uk.autocomplete'```?
When I console.log that event it's run 4 times. Isn't that odd?

/Jonas

**Comment by w0nderw0man** [comment]
update : 
    $('[data-uk-autocomplete]').on('selectitem.uk.autocomplete', function (event, data) {
        alert(data.value + ' ' + data.id);
    });

**Comment by alejoar** [comment]
For some reason when the event is triggered, when I read the data I only get the `value` field, even though there's more fields in each object (such as`id`). But these fields are not present in the data parameter when the event is triggered. Help?

**Comment by abuzant** [comment]
This is one and probably the worst documented feature of the whole UIKIt library. Guys here wrote long great docs for the uk-icon and uk-grid for example which are basic things leaving complex components like this poorly documented. I couch for a complete rewrite for it's docs.
