### ISSUE TITLE
Timepicker addon feature request: provide option to choose a range between hours

### ISSUE THREAD

**Issue by webketje** [uikit/uikit#650]
Hi there, 

**Concerning:** Timepicker add-on
**File:** timepicker.js
**Request:** Add choice of time range to available JS options<br>
Wouldn't it be nice to include the option to choose a range between two given times to allow the developer to choose from/ and the user to restrict to. Eg, suppose I used the timepicker for a dentist appointment and would only want to display times from 10:00 to 18:00.

In **timepicker.js**, lines 21-46. For now I have what I need by modifying line 23 from:

     for(var i = 0, h=''; i<24; i++) {  

to: 

     for(var i = 7, h=''; i<22; i++) {

Going even further would be allowing multiple timeranges (eg from 8:30 to 12 [lunch break] & 13 to 18

**Comment by pcout** [comment]
+1

**Comment by nstaeger** [comment]
Has been implemented here https://github.com/uikit/uikit/commit/f49340037e07051fee7f2d751d62acfebe43dcb2
