### ISSUE TITLE
Closing Dropdown Programatically 

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#656]
Hi all,
I thought this would close a dropdown after looking in `dropdown.js`:

```
$(document).on('click', '.js-close-more-dropdown', function(event) {
    event.preventDefault();

    $.UIkit.dropdown.registerOuterClick();
});
```

but it complains about that not being a function. I realize it just removes the `.uk-open` class, but surely we should be able to call an internal UIkit function just like we do for most others. Thanks.

**Comment by sommarbar** [comment]
and where do i change this code, using stage theme

**Comment by malles** [comment]
No need to change any code.
If you want to close a dropdown via JS, use `UIkit.dropdown($('#yourdropdown')).hide()` when you need it.
