### ISSUE TITLE
Height calc sticky wrapper in Firefox is off

### ISSUE THREAD

**Issue by malles** [uikit/uikit#661]
Weird case in newest YOOtheme template's sticky menu in FF.  
On navigating the page `this.element.outerHeight()` returns 439 (logged in console)
![image](https://cloud.githubusercontent.com/assets/5442402/4499979/0670a286-4a8a-11e4-9d1c-ef3d5cdfcfbd.png)
When I hit F5, it logs 100, which is correct.
![image](https://cloud.githubusercontent.com/assets/5442402/4500007/478eed04-4a8a-11e4-8939-e21f6d27a571.png)
This happens every time. navigate->439, refresh->100.

Chrome always logs the correct 100.
![image](https://cloud.githubusercontent.com/assets/5442402/4500013/5c281330-4a8a-11e4-9fea-73b6ed4c0af4.png)

The template is a clean install. Any ideas? http://nzd.bixieprintshop.nl/

**Comment by addept** [comment]
Also observe the same problem on all pages with a slideshow (or slideset) and sticky
