### ISSUE TITLE
Nestable change does not trigger if you drag a node to the first place of its grand-parent

### ISSUE THREAD

**Issue by ambroisemaupate** [uikit/uikit#685]
Does this weird condition https://github.com/uikit/uikit/blob/master/src/js/components/nestable.js#L372 is guilty ?

```
- node 1
    - node 2
        - node 3
```

If you try to move node-3 inside node-1 just before node-2, no change will be triggered.

**Comment by lbain** [comment]
We're experiencing this issue too. We're on 2.15.0 and have the fix @aheinze merged in. But we're still not able to reorder the nodes 3 levels in, exactly as @ambroisemaupate described. Any other suggestions for fixes?
