### ISSUE TITLE
Missing $global-* variables in SASS variables list

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#693]
So far I've generated the LESS file in customizer, then convert the variables to SASS (convert all @ to $)

Now, when UIkit support SASS, I use the SASS list variables from:
https://github.com/uikit/bower-uikit/blob/master/scss/uikit-variables.scss

But on the list, they missing 'groups' of variables: $global-* (which is on LESS)...

**Comment by aheinze** [comment]
theme less files are not conerted to sass, so there are no $global-* variables.
