### ISSUE TITLE
Nav Component: Sharing Offcanvas variables

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#695]
Hi all,
When using a pre-built theme, the nav component is using variables only included in the off-canvas component, which makes it unusable to only use nav by itself. Think these should be made global if both would share to keep things modular.

**Comment by zslabs** [comment]
Any progress on this one? Happy to do this myself if we can get it in soon.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
