### ISSUE TITLE
Toggle the Sticky component via JavaScript

### ISSUE THREAD

**Issue by breda** [uikit/uikit#706]
It would be awesome, to be able to toggle the Sticky component on some element.
maybe like: 

``` javascript
$.UIkit.toggleSticky(element, { /* options */ });
```

As a usage example...
We can make the navbar sticky when the user scrolls to the bottom of the page,
and get it back when the user reaches the top of the viewport.

**Comment by janschoenherr** [comment]
This is already part of UIkit 3.
