### ISSUE TITLE
Remove Moment.js from datepicker

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#718]
We're using Moment.Js elsewhere in our app and aside from being redundant, it seems to go against the very nature of why Bower is such a great tool. Pulling this in as a dependency would be a much better path forward.

**Comment by zslabs** [comment]
Hey @aheinze want me to separate this out? The amount of 3rd party libraries used in UIkit is obviously pretty slim, but feel this is something we could introduce bower_components into if necessary.

**Comment by aheinze** [comment]
thanks, but this will be issued for UIkit 3.0
