### ISSUE TITLE
Rework Off-canvas

### ISSUE THREAD

**Issue by saschadube** [uikit/uikit#72]
Smoother animation using CSS3 transform and transition
Different transition effects

**Comment by trevorhreed** [comment]
It would be nice to allow the off-canvas to always be visible on large enough screens.

**Comment by ekaradon** [comment]
+1 with trevorhreed for the possibility to define the off-canvas as always visible when on large screens. 

I would just add that for mobile side I love this implementation of off-canvas: http://mgcrea.github.io/angular-strap/#/asides
In this implementation, you have the off-canvas which take full width on small devices (more usable) and which is closable through a cross a the top right. 
It seems more natural and convenient from a mobile perspective view. You can use as a menu bar but also as a full new page binded to the previous one. 

I do not really understand why it has been chose to set a partial width for this kind of component, and I do not see how to change this with the current version.

**Comment by pcout** [comment]
+1 to "It would be nice to allow the off-canvas to always be visible on large enough screens."

**Comment by christianmagill** [comment]
Working properly with fixed navigation would also be awesome.

**Comment by Nickiam7** [comment]
I agree with both trevorhreed and christianmagill.

The offcanvas is already great, but these additions would really take it to the next level!

**Comment by Pandahisham** [comment]
+1 with trevorhreed

**Comment by Pandahisham** [comment]
http://ahmedrad.github.io/sliiide/ is a nice example of a versatile offcanvas menu @saschadube

**Comment by PixelT** [comment]
When you will be rework offcanvas, please consider the expansion of this component which i described / proposal here: https://github.com/uikit/uikit/issues/646 :)

**Comment by TomS-** [comment]
+1

**Comment by zzseba78** [comment]
+1 to all !! :)

**Comment by regisaih** [comment]
+1!

Content options would be useful (push, shrink, overlay).

**Comment by yaelduckwen** [comment]
+1 <3

**Comment by dumitru05** [comment]
+1

**Comment by yaelduckwen** [comment]
+1

**Comment by webchun** [comment]
+1
Off Canvas is the only UIKit component that I've never use because it's too jaggy on mobile devices. You should do this for 2.x
