### ISSUE TITLE
Smooth scroll only scrolls to top of page

### ISSUE THREAD

**Issue by ghost** [uikit/uikit#720]
Hi, I got the same issue as this guy has:
https://github.com/uikit/uikit/issues/628

But the solution doesn't work for me.

URL:
http://www.wildeboer-net.de

You can scroll down a bit, then klick a button in the navigation and you will see it is scrolling to the top.
Dont know what i'm doing wrong!

**Comment by Lariveg** [comment]
Hi! I also have the same problem and I can't figure out why. Why is this a closed topic?
