### ISSUE TITLE
Datepicker not working correctly on mobile

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#722]
When I focus on a datepicker element (demo site) it does not show as it should and brings up the keyboard. Very janky at the moment and leaves the component useless for the time being.

**Comment by zslabs** [comment]
Datepicker is unfortunately still failing horribly on the [demo site](http://getuikit.com/docs/addons_datepicker.html)

**Comment by nstaeger** [comment]
The demo-site will be updated with a new release.
