### ISSUE TITLE
scrollspy not working on dynamic content

### ISSUE THREAD

**Issue by pewsheen** [uikit/uikit#73]
scrollspy not working on dynamic generated contents, may needs API to call it?

If scroll hidden in body but shows in a sub div, scrollspy can't work in the sub div too.

**Comment by austre** [comment]
I have a PHP code that generates this structure:

```
<div class="uk-grid uk-grid-width-1-4" data-uk-scrollspy="{cls:'uk-animation-slide-left', target:'.animateme', delay:900, repeat:true}">
	<div class="animateme"></div>
	.
	.
	.
</div>
```

So, i could have N animateme divs. All this code is a dynamic, i could not make scrollspy works only with the explanations on this topic. Someone can help me?
