### ISSUE TITLE
Sass compilation issues

### ISSUE THREAD

**Issue by udayms** [uikit/uikit#731]
Hi,

I just cloned the bower-uikit project and ran gulp-sass on it and it threw up a bunch of errors/warnings. Anybody else having this issue? I am using gulp v3.3.10.

[16:17:50] Using gulpfile ~/matrix/test/bower-uikit-master/gulpfile.js
[16:17:50] Starting 'go'...
/Users/udayms/matrix/test/bower-uikit-master/scss/components/autocomplete.scss:57: error: no mixin named hook-nav-autocomplete
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/autocomplete.scss:57

/Users/udayms/matrix/test/bower-uikit-master/scss/components/caption.scss:51: error: no mixin named hook-caption
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/caption.scss:51

/Users/udayms/matrix/test/bower-uikit-master/scss/components/cover.scss:68: error: no mixin named hook-cover-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/cover.scss:68

/Users/udayms/matrix/test/bower-uikit-master/scss/components/datepicker.scss:76: error: no mixin named hook-datepicker-nav
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/datepicker.scss:76

/Users/udayms/matrix/test/bower-uikit-master/scss/components/dotnav.scss:92: error: no mixin named hook-dotnav-item
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/dotnav.scss:92

/Users/udayms/matrix/test/bower-uikit-master/scss/components/flex.scss:233: error: no mixin named hook-flex-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/flex.scss:233

/Users/udayms/matrix/test/bower-uikit-master/scss/components/form-file.scss:61: error: no mixin named hook-form-file-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/form-file.scss:61

/Users/udayms/matrix/test/bower-uikit-master/scss/components/form-advanced.scss:60: error: no mixin named hook-form-advanced
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/form-advanced.scss:60

/Users/udayms/matrix/test/bower-uikit-master/scss/components/form-password.scss:72: error: no mixin named hook-form-password-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/form-password.scss:72

/Users/udayms/matrix/test/bower-uikit-master/scss/components/form-select.scss:64: error: no mixin named hook-form-select-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/form-select.scss:64

/Users/udayms/matrix/test/bower-uikit-master/scss/components/nestable.scss:66: error: no mixin named hook-nestable
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/nestable.scss:66

/Users/udayms/matrix/test/bower-uikit-master/scss/components/notify.scss:66: error: no mixin named hook-notify
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/notify.scss:66

/Users/udayms/matrix/test/bower-uikit-master/scss/components/htmleditor.scss:57: error: no mixin named hook-htmleditor
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/htmleditor.scss:57

/Users/udayms/matrix/test/bower-uikit-master/scss/components/placeholder.scss:33: error: no mixin named hook-placeholder
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/placeholder.scss:33

/Users/udayms/matrix/test/bower-uikit-master/scss/components/slidenav.scss:71: error: no mixin named hook-slidenav
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/slidenav.scss:71

/Users/udayms/matrix/test/bower-uikit-master/scss/components/search.scss:90: error: no mixin named hook-search
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/search.scss:90

/Users/udayms/matrix/test/bower-uikit-master/scss/components/slideshow.scss:194: error: no mixin named hook-slideshow-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/slideshow.scss:194

/Users/udayms/matrix/test/bower-uikit-master/scss/components/sticky.scss:50: error: no mixin named hook-sticky-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/sticky.scss:50

/Users/udayms/matrix/test/bower-uikit-master/scss/components/sortable.scss:39: error: no mixin named hook-sortable
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/sortable.scss:39

/Users/udayms/matrix/test/bower-uikit-master/scss/components/upload.scss:32: error: no mixin named hook-upload-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/components/upload.scss:32

/Users/udayms/matrix/test/bower-uikit-master/scss/core/alert.scss:55: error: no mixin named hook-alert
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/alert.scss:55

/Users/udayms/matrix/test/bower-uikit-master/scss/core/article.scss:86: error: no mixin named hook-article-title
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/article.scss:86

/Users/udayms/matrix/test/bower-uikit-master/scss/core/badge.scss:48: error: no mixin named hook-badge
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/badge.scss:48

/Users/udayms/matrix/test/bower-uikit-master/scss/core/breadcrumb.scss:45: error: no mixin named hook-breadcrumb
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/breadcrumb.scss:45

/Users/udayms/matrix/test/bower-uikit-master/scss/core/animation.scss:597: error: no mixin named hook-animation-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/animation.scss:597

/Users/udayms/matrix/test/bower-uikit-master/scss/core/base.scss:99: error: no mixin named hook-base-body
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/base.scss:99

/Users/udayms/matrix/test/bower-uikit-master/scss/core/button.scss:157: error: no mixin named hook-button
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/button.scss:157

/Users/udayms/matrix/test/bower-uikit-master/scss/core/close.scss:75: error: no mixin named hook-close
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/close.scss:75

/Users/udayms/matrix/test/bower-uikit-master/scss/core/description-list.scss:33: error: unbound variable $breakpoint-medium

/Users/udayms/matrix/test/bower-uikit-master/scss/core/comment.scss:56: error: no mixin named hook-comment
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/comment.scss:56

/Users/udayms/matrix/test/bower-uikit-master/scss/core/dropdown.scss:87: error: no mixin named hook-dropdown
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/dropdown.scss:87

/Users/udayms/matrix/test/bower-uikit-master/scss/core/form.scss:303: error: no mixin named hook-form
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/form.scss:303

/Users/udayms/matrix/test/bower-uikit-master/scss/core/grid.scss:135: error: unbound variable $breakpoint-xlarge

/Users/udayms/matrix/test/bower-uikit-master/scss/core/list.scss:74: error: no mixin named hook-list-line
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/list.scss:74

/Users/udayms/matrix/test/bower-uikit-master/scss/core/modal.scss:77: error: no mixin named hook-modal
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/modal.scss:77

/Users/udayms/matrix/test/bower-uikit-master/scss/core/navbar.scss:78: error: no mixin named hook-navbar
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/navbar.scss:78

/Users/udayms/matrix/test/bower-uikit-master/scss/core/offcanvas.scss:69: error: no mixin named hook-offcanvas
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/offcanvas.scss:69

/Users/udayms/matrix/test/bower-uikit-master/scss/core/nav.scss:159: error: no mixin named hook-nav-header
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/nav.scss:159

/Users/udayms/matrix/test/bower-uikit-master/scss/core/overlay.scss:98: error: no mixin named hook-overlay-area
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/overlay.scss:98

/Users/udayms/matrix/test/bower-uikit-master/scss/core/icon.scss:116: error: no mixin named hook-icon-button
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/icon.scss:116

/Users/udayms/matrix/test/bower-uikit-master/scss/core/base.scss:99: error: no mixin named hook-base-body
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/base.scss:99

/Users/udayms/matrix/test/bower-uikit-master/scss/core/pagination.scss:117: error: no mixin named hook-pagination-item
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/pagination.scss:117

/Users/udayms/matrix/test/bower-uikit-master/scss/core/panel.scss:121: error: no mixin named hook-panel-title
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/panel.scss:121

/Users/udayms/matrix/test/bower-uikit-master/scss/core/progress.scss:63: error: no mixin named hook-progress
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/progress.scss:63

/Users/udayms/matrix/test/bower-uikit-master/scss/core/subnav.scss:88: error: no mixin named hook-subnav-item
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/subnav.scss:88

/Users/udayms/matrix/test/bower-uikit-master/scss/core/switcher.scss:31: error: no mixin named hook-switcher-misc
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/switcher.scss:31

/Users/udayms/matrix/test/bower-uikit-master/scss/core/table.scss:61: error: no mixin named hook-table
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/table.scss:61

/Users/udayms/matrix/test/bower-uikit-master/scss/core/thumbnail.scss:70: error: no mixin named hook-thumbnail
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/thumbnail.scss:70

/Users/udayms/matrix/test/bower-uikit-master/scss/core/text.scss:73: error: unbound variable $breakpoint-medium-max

/Users/udayms/matrix/test/bower-uikit-master/scss/core/tab.scss:91: error: no mixin named hook-tab
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/tab.scss:91

/Users/udayms/matrix/test/bower-uikit-master/scss/core/tooltip.scss:63: error: no mixin named hook-tooltip
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/tooltip.scss:63

/Users/udayms/matrix/test/bower-uikit-master/scss/core/utility.scss:73: error: no mixin named hook-container
Backtrace:
    /Users/udayms/matrix/test/bower-uikit-master/scss/core/utility.scss:73

[16:17:50] Finished 'go' after 115 ms

**Comment by LeslieMeneses** [comment]
@aheinze Hello, i just have the same problem. You resolve this fix?
