### ISSUE TITLE
A big bug in pagination add-on !

### ISSUE THREAD

**Issue by v2up** [uikit/uikit#733]
http://getuikit.com/docs/addons_pagination.html
$('[data-uk-pagination]').on('uk-select-page', function(e, pageIndex){
    alert('You have selected page: ' + (pageIndex+1));
});
you can't find any charachers "uk-select-page" in corresponding JS file , but only "uk.select.page"

Hey,Notice.

**Comment by leighquince** [comment]
the docs say the event emitted is `select.uk.pagination` but it seems to actually be `uk.pagination.select`
