### ISSUE TITLE
global-image-path

### ISSUE THREAD

**Issue by callerc1** [uikit/uikit#736]
Hi Guys,

Just wanted to ask how best to make use out of the modifyVars global-image-path? Currently the path to images you might need to declare in your stylesheets is set to eg ```{ 'global-image-path': '"../themes/default/images"' }``` which when compiled to ```dist/css``` points to folders that don't exist within the distro. I can't seem to find a gulp task that copy's over any theme specific images to ```dist```. Its seems as tho this feature isn't quite right/or incomplete but please correct me if i'm wrong. 

Many Thanks

**Comment by aheinze** [comment]
thanks, we'll consider this for future releases.
