### ISSUE TITLE
AngularJs ng-repeat and data-uk-grid-margin / data-uk-grid-match

### ISSUE THREAD

**Issue by orestisioakeimidis** [uikit/uikit#737]
Hello all,

I am using angular ng-repeat to populate elements inside a grid. I am trying to use `data-uk-grid-margin` and `data-uk-grid-match`, but without success. It just does not work!

I do not know if this is really a UIkit issue or an angular issue, but until it is fixed here is a workaround for anyone else trying to do the same.

    <div class="uk-grid uk-grid-width-1-2" data-uk-grid-match data-uk-grid-margin>
        <div ng-repeat="item in items">
            {{item}}
        </div>
        <div class="uk-hidden"></div>
    </div>

It seems that using a hidden element inside the grid, UIkit can initialize the grid margin and the grid match height functionality.

**Comment by chisholmd** [comment]
How can this be closed without a resolution?  Either there is a solution or there is a statement that you can't use UiKit with Angular...right?

**Comment by chisholmd** [comment]
How can this whole thread be closed?  It still doesn't work.  Is it some issue tracker somewhere?
