### ISSUE TITLE
Dropdown component: add uk-active

### ISSUE THREAD

**Issue by adaniello** [uikit/uikit#738]
HI,
in my opinion should be useful if you add class 'uk-active' to dropdown list item, to select active/current item (as in nav).
Why not?
Thanks

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The dropdown nav now also should have a uk-active modifier as it can be seen [here](https://getuikit.com/docs/nav#nav-in-dropdown).

Thanks for your understanding,
Your UIkit Team
