### ISSUE TITLE
Disable Scrollspy Animations on Mobile Devices

### ISSUE THREAD

**Issue by CinKon** [uikit/uikit#740]
Is there any way to disable Scrollspy Animations for Mobile Devices?

**Comment by attenchin** [comment]
I added some css to disable the animations on mobile in the uikit.css file. 

Added "and (min-device-width: 768px)" and wrapped the scroll spy animations section with the same media query. 

In uikit.css line 5400
/* Hide animated element if scrollspy is used */
@media screen and (min-device-width: 768px) {
[data-uk-scrollspy*='uk-animation-'] {
    opacity: 0;
  }
}
