### ISSUE TITLE
uikit npm

### ISSUE THREAD

**Issue by callerc1** [uikit/uikit#742]
Would be great if uikit was available via npm so you can just require() it in a CommonJS environment.

**Comment by ciconia** [comment]
+1, via jspm would also be cool.

**Comment by nicolindemann** [comment]
+1

**Comment by vnen** [comment]
:+1: 
Since it already has a `package.json`, I think it's just a matter of packing up a main file and publishing this to [npm](http://npmjs.com).

**Comment by pavankumarlpersonal** [comment]
+1

**Comment by AlexanderOMara** [comment]
+1

Looks like [someone added it to npm](https://www.npmjs.com/package/uikit), but it's outdated and does not include the compiled files like those you get from bower.

**Comment by frio** [comment]
+1!  I've raised #1504, which incorporates #1434 but includes a `main`.

**Comment by frio** [comment]
2.23.0 should now support NPM, but hasn't been published.  I've mailed the owner of the NPM variant, but had no response.  Is there anyone I can speak to about publishing to NPM?

**Comment by dteirney** [comment]
@aheinze is there anything that the community can do to help get the 2.23.0 release published into the NPM registry?

**Comment by saschadube** [comment]
Hi, it is already on [npm](https://www.npmjs.com/package/uikit)
