### ISSUE TITLE
Selector Prefixes

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#743]
I saw [this commit](https://github.com/uikit/uikit/commit/5c75488399d955e34b79c79c94b5688c887ad385)  that introduced JS prefixes - which is immensely useful. It had me thinking about the possibilities of doing this throughout the LESS files for the actual prefix attached to all components. With the improvements made to removing `normalize.css` and integrating it into the specific components, variable prefixing would allow a bit more flexibility in the overall build of large-scale applications that need that sort of customization.

Something like this would do the trick:

	@prefix: ~"bt-";

	.@{prefix}test {
	  color: red;
	}

[CodePen](http://codepen.io/zslabs/pen/wBBbbq) showing this a bit more.

**Comment by aheinze** [comment]
I think this will always be a custom solution
