### ISSUE TITLE
uk-grid-divider on custom uk-width

### ISSUE THREAD

**Issue by shrpne** [uikit/uikit#745]
UIkit 2.12
uk-grid-divider don't add border to custom uk-width or uk-width-custom cells.
Here is workaround, we can use uk-width-1- , uk-width-2- class on cells with custom width, but it is not showed in docs.

Currently border applies by this less:
.uk-grid-divider > [class*='uk-width-1-']:not(.uk-width-1-1):nth-child(n+2),
.uk-grid-divider > [class*='uk-width-2-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-3-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-4-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-5-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-6-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-7-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-8-']:nth-child(n+2),
.uk-grid-divider > [class*='uk-width-9-']:nth-child(n+2) { border-left: @grid-divider-border-width solid @grid-divider-border; }
@media (min-width: @breakpoint-medium) {
    .uk-grid-divider > [class*='uk-width-medium-']:not(.uk-width-medium-1-1):nth-child(n+2) { border-left: @grid-divider-border-width solid @grid-divider-border; }
}
@media (min-width: @breakpoint-large) {
    .uk-grid-divider > [class*='uk-width-large-']:not(.uk-width-large-1-1):nth-child(n+2) { border-left: @grid-divider-border-width solid @grid-divider-border; }
}

How about change it to next:
.uk-grid-divider > [class*='uk-width']:not(.uk-width-1-1):nth-child(n+2) { border-left: @grid-divider-border-width solid @grid-divider-border; }
@media (min-width: @breakpoint-medium) {
    .uk-grid-divider > .uk-width-medium-1-1 { border-left: none; }
}
@media (min-width: @breakpoint-large) {
    .uk-grid-divider > .uk-width-large-1-1 { border-left: none; }
}

I think it looks simpler and covers more cases

**Comment by saschadube** [comment]
We will consider this issue for UIkit 3 when we rework the grid component.
