### ISSUE TITLE
Slide-Nav issue in RTL mode

### ISSUE THREAD

**Issue by saeedesmaeili** [uikit/uikit#746]
Hey Dude 

Wrong Direction Of (Slide Nav) Component in RTL Mode

in change My rtl.css File and Problem Solved

Orginal Css is :
.uk-slidenav-position .uk-slidenav-previous{right:20px}
.uk-slidenav-position .uk-slidenav-next{left:20px}

i Changed it To :
.uk-slidenav-position .uk-slidenav-previous{left:20px}
.uk-slidenav-position .uk-slidenav-next{right:20px}

**Comment by florianletsch** [comment]
This has been fixed a while ago.
