### ISSUE TITLE
Slide-horizontal animation in Switcher-component

### ISSUE THREAD

**Issue by sebomoto** [uikit/uikit#751]
When using the Switcher component for tabs and using the "slide-horizontal" animation the direction of the animation feels to be goind into the wrong direction.

Example code:
```
<div class="section-tabs">
    <ul class="uk-tab" data-uk-tab="{connect:'#tab-contents', animation: 'slide-horizontal'}">
        <li class="tab-active"><a href="">A</a></li>
        <li><a href="">B<a></li>
        <li><a href="">C</a></li>
    </ul>

    <!-- This is the container of the content items -->
    <ul id="tab-contents">
        <li>Tab1</li>
        <li>Tab2</li>
        <li>Tab3</li>
    </ul>
...
</div>
```

Expected behaviour:
On Tab1, clicking on Link "B", Tab1 moves to the left, Tab2 enters from the right.

Actual behaviour:
On Tab1, clicking on Link "B", Tab1 moves to the right, Tab2 enters from the left.

**Comment by aheinze** [comment]
the develop branch is where the current development is going on. so you you want the latest and greatest you should checkout the develop branch.
