### ISSUE TITLE
RequireJS error by using the r.js optimizer

### ISSUE THREAD

**Issue by hschaeidt** [uikit/uikit#759]
Hi,

just noticed that the requireJS version works well except when I try to use the r.js optimizer. In order to reproduce I have pushed a minimalistic repository showing the issue:

https://github.com/hschaeidt/demo-uikit-error

Following error appears by running the grunt build (r.js minifier):

>  originalError: 
>    { [ReferenceError: window is not defined]
>      fileName: '/Users/hendrikschaeidt/PhpstormProjects/demo-uikit-error/bower_components/uikit/js/uikit.min.js',
>      moduleTree: [ 'app' ] } }

The error comes from the module/component loading part of UIKit (in the above repository: https://github.com/hschaeidt/demo-uikit-error/blob/master/src/js/app.js#L19

If we remove from `require(["uikit!slideshow"]` the `!slideshow` the whole build process works well.

The issue seems very clear, the module loading the uikit plugins seems to work only properly in the browser as it has the `window` variable as dependency. Do you guys think there is an easy way to also take care of the r.js optimizer?

Regards
Hendrik

**Comment by malles** [comment]
Confirmed this.

**Comment by leighquince** [comment]
just ran into this issue as well

**Comment by liverbool** [comment]
How about this?

**Comment by nstaeger** [comment]
Just my first thought. Should it not be

```
require.config({
    paths: {
        requirejs: "../../bower_components/requirejs/require",
        jquery: "../../bower_components/jquery/dist/jquery",
        uikit: "../../bower_components/uikit/js/",
        uikitSlideshow: "../../bower_components/uikit/js/components/slideshow.min"
    },
    shim: {
        uikit: {
            deps: [
                "jquery"
            ]
        }
    },
    packages: [

    ]
});

require(["uikitSlideshow"], function(UI) {

});
```

in app.js?

**Comment by hschaeidt** [comment]
Following the documentation for AMD everything works fine, what don't work is the minify through r.js

http://getuikit.com/docs/documentation_javascript.html

**Comment by devlux** [comment]
I can confirm this issue; problem is that it cannot be used with r.js!

**Comment by polonel** [comment]
Is this not fixed yet?

**Comment by alienbeing** [comment]
Confirmed. r.js fails to optimize. This is my config file.

`main.js`
`requirejs.config({
  paths: {
    uikit: 'vendor/uikit/js/uikit'
  },
  config: {
    uikit: {
      base: '../../static/vendor/uikit/js'
    }
  },
  shim: {
    uikit: {
      deps: ['jquery']
    }
  }
});`

`a.js`
`define(['uikit!tooltip,notify'], function (UI) {
  // Do some stuff with UI.notify, UI.tooltip, etc...
});
`

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
