### ISSUE TITLE
Markdown Editor Enhancements: Content Builder

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#766]
While I do love the idea of the [HTML/Markdown Editor](http://getuikit.com/docs/addons_htmleditor.html) I think one of the pain-points we've all seen is that at the end of the day, WYSIWYG editors are terrible. And while this isn't necessarily that, the issue here is that for clients using it, they're still faced with editing  their content in an HTML/Markdown view, which isn't very intuitive. I think a better option would be something more like [Barley](http://getbarley.com/) or [Sir Trevor](http://madebymany.github.io/sir-trevor-js/) -- Sir Trevor actually being my favorite, because what's returned is JSON objects of the options you've chosen. Think that a "UIkit" version of this would fall-in perfectly with all the components you guys have available now. Would love everyone's thoughts on this.

![SirTrevor Example](https://camo.githubusercontent.com/e69959d4b25f0ada1a04046bfa38ef3a14e4e442/68747470733a2f2f7261772e6769746875622e636f6d2f6d61646562796d616e792f7369722d747265766f722d6a732f6d61737465722f6578616d706c65732f7369722d747265766f722e676966)

**Comment by zslabs** [comment]
Also thinking about this for Widgetkit. Think if you didn't have to choose between a type of widget --> everything is a "combo" widget and you build what you want your Widgetkit instance to be. So if you want a gallery, twitter box and slideshow in one, you've got it.

**Comment by saschadube** [comment]
We already done some prototyping and it's on our todo list :wink:

**Comment by zslabs** [comment]
Very cool! Let me know if you need any help testing.

**Comment by iliaznk** [comment]
Wow! Sir Trevor is awesome! Would love to see it as a UIKit component!

**Comment by aheinze** [comment]
thanks for the suggestion, but this should be provided as a third party add-on
