### ISSUE TITLE
Pagination url setting

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#767]
Please add to pagination settings param to change url view.
Now it possible use only hash pagination page, for example: site.com/#page3.
Also need to use GET param to pagination page, for example: site.com?page=3.
I did it so like that:
to param add option "url" : '#page'
"<-li><-a href="'+this.options.url + (pageIndex+1)+'" data-page="'+pageIndex+'">'+options.text+'</a><-/li>"
I'm only suggesting to add it into official code.

**Comment by aheinze** [comment]
I think this needs to be implemented by the app/script utilizing the pagination component. if we we would do this, code for other libraries (angular etc) will break. thanks for the suggestion.

**Comment by Intiligent** [comment]
i mean only add setting param, not change core.
so, by default was pagination by hash, but if necessary change pagination pattern on init component.
For example:

<-ul class="uk-pagination" data-uk-pagination="{items:80, itemsOnPage:4, currentPage:3, url: '?'}"></ul->

if not set "url" param then nothing will change and by default was hash pagination.
not understand how this param can affect by other libraries.
it would be appreciated PHP developer.

but you and your team are developer and i full trust your opinion.
thanks for you work, we doing a good job)
