### ISSUE TITLE
Highlighted today day on datepicker

### ISSUE THREAD

**Issue by Intiligent** [uikit/uikit#768]
When select other day on datepicker highlighted only selected day but no today.
Please add some css class to td tag for today day.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The DatePicker component hasn't been released for UIkit3 yet, but we are working on it and I think that this feature will be available within the new version.

Thanks for your understanding,
Your UIkit Team

**Comment by Intiligent** [comment]
v2 already not be support. Will be develop only v3?
