### ISSUE TITLE
Offcanvas and Angular routing

### ISSUE THREAD

**Issue by tstavinoha** [uikit/uikit#775]
Angular's hashbang URLs cause a problem in offcanvas navigation by failing a Sizzle selector in attempt to hide the offcanvas on anchor click:

offcanvas.js -> _initElement

```
UI.$doc.one('hide.uk.offcanvas', function() {

	var target = $(href);

	if (!target.length) {
		target = UI.$('[name="'+href.replace('#','')+'"]');
	}

	if (UI.Utils.scrollToElement && target.length) {
		UI.Utils.scrollToElement(target);
	} else {
		window.location.href = href;
	}
});
```
An ugly exception pops out in the browser console while performing `var target = $(href);`, for example if the offcanvas item points to '#/login', you get an `Error: Syntax error, unrecognized expression: #/login`.

Fixable by introducing:
```
UI.$doc.one('hide.uk.offcanvas', function() {

	var target = !href.startsWith('#/') ? $(href) : [];

	if (!target.length) {
		target = UI.$('[name="'+href.replace('#','')+'"]');
	}

	if (UI.Utils.scrollToElement && target.length) {
		UI.Utils.scrollToElement(target);
	} else {
		window.location.href = href;
	}
});
```

Comments please :)

**Comment by aheinze** [comment]
this is pretty app specific, some do ```#/``` other do ```#!/``` I think you should try to use and implement  the new html5 url route, also supported by angular.
