### ISSUE TITLE
Color of a:visited overrules uk-button class

### ISSUE THREAD

**Issue by p3k** [uikit/uikit#777]
If I define something like this in my stylesheet:

```
a:visited {
  color: yellow;
}
```

…buttons like this one suddenly have a yellow text:

```
<a href='#' class='uk-button'>Foobar</a>
```

You can easily reproduce this even on [this UIKit.com page](http://getuikit.com/docs/button.html) by using DevTools to add the `a:visited`definition to the `<head><style>`element; the text of the first example button will become yellow.

I consider it would be desired that the buttons look like UIKIt buttons no matter what – as long as their own classes are not redefined.

**Comment by saschadube** [comment]
Please use 

```css
a:visited:not(.uk-button) {
  color: yellow;
}
```
