### ISSUE TITLE
Editing text area's value from database

### ISSUE THREAD

**Issue by 123bbuingbbuing** [uikit/uikit#782]
i added data-uk-htmleditor in my text area tag and included code-mirror and marked in my plugins and add-ons, i can save the texts i typed inside the editor i can view it the way i formatted it in my editor, but i am having a hard time retrieving the value when i try to edit it. i don't know how to call it in my javascript, i know this is not an issue but i just find the right answer to my question in other forums, can you please help me ? still a newbie XD Thanks!

**Comment by aheinze** [comment]
the editor writes back the value to the textarea on change. so just get the texarea value if yo need it
