### ISSUE TITLE
Unstick option for Sticky component

### ISSUE THREAD

**Issue by maccovey** [uikit/uikit#784]
HI,

It would be wonderful if Sticky component be able to unstick at certain conditions. For example, when user scrolls to the bottom of the page or some div becomes visible.
Thanks for your awesome framework!

**Comment by aheinze** [comment]
this should be possible with the ```boundary``` option. http://getuikit.com/docs/sticky.html#sticky-boundary

**Comment by maccovey** [comment]
Thanks! Awesome work
