### ISSUE TITLE
Tab component with responsive behaviour but without switcher 

### ISSUE THREAD

**Issue by stell** [uikit/uikit#789]
Yeah thats about it. Would like to have the responsive feature of the tab component, but without switcher behaviour, just simple links.

**Comment by schinckel** [comment]
You can get this behaviour by listening for the `uk.tab.change` event, and handling that. I'm using it to load content via AJAX.

**Comment by stell** [comment]
Is this implemented yet?

**Comment by aheinze** [comment]
hi,

as @schinckel suggested you can build custom behavior with the ```change.uk.tab``` event without connecting to a switcher.
