### ISSUE TITLE
datepicker: defaultDate option is missing

### ISSUE THREAD

**Issue by toursim** [uikit/uikit#794]
It would be nice to have the defaultDate option when initializing datepicker. Thanks!

**Comment by aheinze** [comment]
why don't you just use the value attribute of the input field for init value?

**Comment by toursim** [comment]
@aheinze I need the field to be blank when it renders.

**Comment by adaddeo** [comment]
+1, a default value without having to actually set the value would be ideal

**Comment by aheinze** [comment]
could you please shed some light why you need the field to be blank in initial state?

**Comment by toursim** [comment]
I am the developer of a travel booking engine.
All the fields have to be left blank, because I can't predict what the customer wants.
As for the defaultDate option, it provides better UX (e.g. when the user sets the start date of a trip in the future and then goes to the end date and it takes him back to today's date - it's really annoying having to click 'next month' again and again in order to set a proper interval)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The DatePicker component hasn't been released for UIkit3 yet, but we are working on it and I think that this feature will be available within the new version.

Thanks for your understanding,
Your UIkit Team
