### ISSUE TITLE
Copyright lines in compiled CSS.

### ISSUE THREAD

**Issue by RobertinoValue** [uikit/uikit#802]
**1.**
Running just ```gulp``` the copyright line ```/*! UIkit 2.14.0 | http://www.getuikit.com | (c) 2014 YOOtheme | MIT License */``` is included at the top of all the compiled CSS files. (Including the components CSS files.)

Running just ```gulp``` again, and again, etc, that same copyright line is **pre-pended** to all the compiled CSS files of just my  **custom theme**. But not to the compiled CSS of the  3 shipped/default themes.
So the compiled custom CSS ends up with umpteen copyright lines at the top. While the compiled CSS of the 3 shipped/default themes remains at 1 copyright line.

Running ```gulp -t custome-theme-name``` does the opposite.
The compiled CSS of the 3 shipped/default themes gets a growing number of copyright lines. And the compiled CSS of my custom themes not.

**2.**
Is it possible to extend gulp to add a custom copyright banner (from a text file in the ```custom``` directory) to the compiled CSS of custom themes. In ```addition``` to the YooTheme copyright message.
(Couldn't determine whether this is already possible.)
**EDIT:** À la [grunt-banner](https://github.com/mattstyles/grunt-banner).

**Comment by RobertinoValue** [comment]
Is this not going to be implemented anymore?

**Comment by aheinze** [comment]
please run gulp with a -c parameter e.g. ```gulp -t custome-theme-name -c```

**Comment by RobertinoValue** [comment]
Cleaning wipes all style sheets first.
I need the original style sheets as a reference to compare against my style guides.
(All my style guides also have a version which pulls in the stock style sheet.)
So when I recreate the stock style sheets the issue occurs again in my custom style sheets.

Let's leave this as is. I'll fix it here with a changed Gulp script.
