### ISSUE TITLE
Prepare CSS for Shadow DOM

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#804]
Current CSS selectors are not working inside Shadow DOM.

To make it working, `.uk-button` selector should be replaced by `html /deep/ .uk-button`.

This will allow selector to work in browsers without native support for Shadow DOM, as well as anywhere inside nested shadow roots.

Currently I'm modifying CSS file manually, but it would be great to have additional checkbox in customizer to enable Shadow DOM support.

**Comment by saschadube** [comment]
Thanks! We will keep it in mind for the future :smile:

**Comment by cajoy** [comment]
Can we re-open an issue.

Seems like UIKit is incpompatible with latest Angular 2 - what is the issue

**Comment by nazar-pc** [comment]
@cajoy, use the script I've mentioned, it works in CleverStyle CMS which extensively uses Web Components.

**Comment by cajoy** [comment]
Yes it may work. But I prefer some solution from UiKit developers. What if I don't have PHP installed or new version of UiKit comes up? 

I don't want to use "hacks" to make it work. It should work or no out of the box...

**Comment by nazar-pc** [comment]
@cajoy, now you have "or no")
In fact, solution might be to have 2 css files, because if you have Shadow DOM-specific css constructions it will broke whole css file all in browsers that doesn't support it (majority right now).
In my system polyfills are bundled and third party libraries are patched if necessary to provide the best possible Web Components experience out of the box (I didn't hear about any other system that have such level of support currently).

If you don't have PHP you can rewrite that code in any other language and use it, for example, in your build system.

I do not expect UIkit developers to implement this anytime soon, so I wrote it myself and shared what works for me (it is not like "may work", it does actually work with any possible kind of CSS including any imports and media queries, including already processed, so that you can safely apply it twice and more times to the same file).

At least developers know this issue and hopefully have some checkbox not very far in TODO list.

**Comment by matepaiva** [comment]
Does it have already any straightforward solution at this time? :)

**Comment by erichonkanen** [comment]
Im not sure if related but I just tried rendering my app as a component inside a shadow dom node and now UIKit does not render the icons. I tried importing the css/js directly inside the shadow dom node itself and still it won't render... Is it compatible with shadow dom?

**Comment by michael-speed-elder** [comment]
Does UIKit work with Shadow DOM?
