### ISSUE TITLE
Button text color when using <input type="submit"> instead of <button>

### ISSUE THREAD

**Issue by ankemp** [uikit/uikit#805]
Having a bit of an issue (since ~2.13) when it comes to the color of the text in a button when using 

``` html
<input class="uk-button uk-button-primary" type="submit" value="Click Me" />
```

The text of the button is black where as if I use:

``` html
<button class="uk-button uk-button-primary">Click me</button>
```

The button text is white.

Looked through inspector, looks like the styles are getting over written, I just can't figure out where.
This seems to happen on a fresh UIkit download (no customization)

**Comment by andrewkdesigns** [comment]
This is broken again.
