### ISSUE TITLE
UIkit.ready fires twice in 2.13

### ISSUE THREAD

**Issue by malles** [uikit/uikit#806]
I noticed from UIkit 2.13 the UIkit.ready function fires twice. Is that supposed to be that way, and why so?

Codepen UIkit 2.12: http://codepen.io/anon/pen/NPrEvG

Codepen UIkit. 2.13: http://codepen.io/anon/pen/MYezop

**Comment by malles** [comment]
Still in 2.16.2. http://codepen.io/anon/pen/JoLNJP
I'm not sure if this is an issue, since all components are protected from initializing twice.
I'm just curious if this is done deliberately, and if so, why?

**Comment by aheinze** [comment]
thanks for the hint. this is fixed now.
