### ISSUE TITLE
Empty value or colon in options breaks Utils.options

### ISSUE THREAD

**Issue by malles** [uikit/uikit#808]
When options passed to a component via a data-attribute contain an empty value, Utils.options returns an empty object because JSON.parse [(src)](https://github.com/uikit/uikit/blob/master/src/js/core/core.js#L292) encounters an syntax error.
I think the pain is in the [str2json ](https://github.com/uikit/uikit/blame/master/src/js/core/core.js#L178) function.

Codepens:
Uikit 2.12.0: http://codepen.io/anon/pen/qENvXK
Uikit 2.13.1: http://codepen.io/anon/pen/yyJwPM
Same behaviour is still in 2.14.0

Edit: Same problem occurs with a colon `:` in a value.

**Comment by aheinze** [comment]
Old json parse function is back
