### ISSUE TITLE
Animations in modal

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#811]
Add animations show to modal component.

**Comment by nblackburn** [comment]
Agree with this, it would make for a welcome addition and would compliment #1769.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. This works with the Modal in UIkit3, here you can add a transition class to the `uk-modal-dialog` container, to change the way the modal is animated into the screen. 

Thanks for your understanding,
Your UIkit Team

**Comment by Flimm** [comment]
For the lurkers, looking for a workaround, I have used this CSS to disable the modal animations altogether (in UIKit 3.5):

```
.uk-modal-dialog, .uk-modal {
  transition-duration: 0s;
}
```

**Comment by herculezs** [comment]
How to add animation for the Closing modal?
