### ISSUE TITLE
Reset uk-grid-width-* on larger screens

### ISSUE THREAD

**Issue by uundh** [uikit/uikit#813]
I've come across the issue, that there doesn't seem to be a CSS rule to reset the uk-grid-width-* children to 100% on larger screens. 

In my case I have a sidebar, which drops under the main content on small screens. And there I set the sidebar items in a uk-grid-width-1-2 container. So far so good. But when I scale up, the sidebar switches back next to the main content, being thinner then and there I want to show all items underneath each other. But in the main CSS there are only classes for 1-2, 1-3, etc to overwrite the previous rules. Shouldn't there be a rule for 1-1 also? Or how do I produce this result?

**Comment by saschadube** [comment]
Sorry, this is not possible with the current grid. But if you find in any other existing CSS framework a solution for this, please let me know and I will take a look at it. :smile:

**Comment by uundh** [comment]
But can't there just be the addition of a 100% class in the media queries htat would fix that?
Am I thinking too short here?
![2015-02-19_screen_001](https://cloud.githubusercontent.com/assets/862447/6268234/9a2c5036-b84b-11e4-8161-b57b86d88ad5.png)

**Comment by uundh** [comment]
For my purposes it was perfectly solving just adding the .uk-grid-width-*-1-1 classes in the media queries.

**Comment by uundh** [comment]
I have to open this again, for I don't understand why there are no 
.uk-grid-width-small-1-1
.uk-grid-width-medium-1-1
...
classes. We often have the case, where the appearance on mobile would have to be wider than on a bigger screen, wehere the element is for example nested in a sidebar and thus smaller.
