### ISSUE TITLE
uk-grid + uk-grid-divider + uk-grid-width-*

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#814]
```html
<div class="uk-grid uk-grid-divider uk-grid-width-1-2">
  <div>123</div>
  <div>123</div>
</div>
```
In this example divider is not working. It is applied only if child elements have specified `uk-width-*` class, but should be also applied when using `uk-grid-width-*` on container.

**Comment by saschadube** [comment]
Yes, this is a known issue. It will not be fixed in UIkit 2.x because we would have to change the grid and that would break too much in existing pages. But we will tackle this in UIkit 3 :smile:
