### ISSUE TITLE
uk-switcher problem on Meteor

### ISSUE THREAD

**Issue by payner35** [uikit/uikit#820]
Having some problems with data-uk-switcher on Meteor.js.   Have tried to solve by adding data-uk-observe. Im using the latest 2.15 build

  <div>

            <h5 class="uk-h4">Fade</h5>

            <ul class="uk-subnav uk-subnav-pill" data-uk-switcher="{connect:'#switcher-content-a-fade', animation: 'fade'}">
                <li class="uk-active"><a href="#">Item</a></li>
                <li><a href="#">Item</a></li>
                <li><a href="#">Item</a></li>
            </ul>

            <ul id="switcher-content-a-fade" class="uk-switcher uk-margin" data-uk-observe>
                <li>Hello!</li>
                <li>Hello again!</li>
                <li>Bazinga!</li>
            </ul>

**Comment by aheinze** [comment]
should work with the next release and data-uk-observe
