### ISSUE TITLE
UI.Utils.str2json fails when str has URL 

### ISSUE THREAD

**Issue by rajanvenkataguru** [uikit/uikit#821]
The UI.Utils.str2json is based on Regular expression and relies on word boundaries followed by a colon.
So when the str has URL like  {"source": "http://example.com"}, with a ":", the str2json creates a malformed JSON. 

One example is in UIkit search, where we need to pass a JSON source to data-uk-search. If the data-uk-search value is an object with one of the property being a URL, the str2json fails at JSON.parse. 

One example is within Warp framework for Wordpress, where data-uk-search is passed an object which is resolved to a json by Ajax. But the object becomes undefined when the JSONed admin-ajax.php?action=warp_search URL becomes an invalid JSON. So Ajax doesn't work in the 2.15 uikit in wordpress version of Warp

**Comment by aheinze** [comment]
close because of duplicate issue
