### ISSUE TITLE
sortable.js handleClass option is not working with UIkit older than 2.12.0

### ISSUE THREAD

**Issue by xtremespb** [uikit/uikit#822]
I have a lot of code that uses the sortable.js addon, and it's working very well even with the latest version of UIkit, but when I specify handleClass option, it doesn't work anymore. I'm using the latest Firefox for tests.

Code:

UIkit.sortable($('#warehouseconf_curs_tb'), {
        dragCustomClass: 'uk-form',
        handleClass: 'taracot-btn-curs-sort'
    });

In Chrome, it works *sometimes*, but not always.
When I did fallback for 2.12.0 version, it still works as it should.

**Comment by aheinze** [comment]
Sorry, I can't confirm this issue. could you please provide a code example on jsfiddle?
