### ISSUE TITLE
Missing Slider option

### ISSUE THREAD

**Issue by hikernl** [uikit/uikit#825]
Missing (range) slider option in uikit.
Almost like switcher, but draggable.

**Comment by hikernl** [comment]
I am not sure what you ment with the link, but it would be nice to have something like 
<a href="http://refreshless.com/nouislider/examples/">this</a> in uikit !

**Comment by adaniello** [comment]
The "range" input type is now an html5 standard (as you can see on http://caniuse.com/#feat=input-range), so we can use it with some css customizations (i.e. http://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/) to make it UIKIT like.

**Comment by aheinze** [comment]
Please add feature requests here: https://github.com/uikit/uikit/issues/560. thanks!
