### ISSUE TITLE
Help with autocomplete

### ISSUE THREAD

**Issue by jkrassman** [uikit/uikit#827]
Hi, I just love the UIkit and it is really delivering!

I have a small problem that I can't overcome, with the autocomplete function.

My server is returning a json result and it looks like this:

```[{"value":"Staffan Larsson","data":125},{"value":"Stall Crypto","data":123}]```

And then in my javascript, i am trying to get hold of the data value, and i am missing something here...
```
$('[data-uk-autocomplete]').on('autocomplete-select', function(event, data){
			alert(data.value+' '+data.data);
			});
```
Best regards, Joakim

**Comment by luetn** [comment]
see #611
