### ISSUE TITLE
uk-modal not firing!

### ISSUE THREAD

**Issue by jkrassman** [uikit/uikit#829]
Hi,

I am having huge problems, to get the modal to fire events?

If i return the object to the console, it is really there?
```
$('#modal').on({

    	'uk.modal.show': function(){
        console.log("Modal is visible.");
    	},

    	'uk.modal.hide': function(){
        console.log("Element is not visible.");
   	 }
});
  console.log( $('#modal'));
```
What am I doing wrong?

Regards, Joakim

**Comment by malles** [comment]
If you have the latest version of UIkit installed, it should be `show.uk.modal` and `hide.uk.modal`.

**Comment by malles** [comment]
If you have other versions, try every combination of the terms, or just bind them all :)

**Comment by jkrassman** [comment]
Dohhh, that did solve it :)

**Comment by jkrassman** [comment]
https://github.com/uikit/uikit/issues/829

**Comment by TheWolfNL** [comment]
Example on [modal docs] should be modified to reflect current version.

[modal docs]:http://getuikit.com/docs/modal.html

**Comment by aheinze** [comment]
docs will be updated for the next release.
