### ISSUE TITLE
Your site (http://getuikit.com/docs/components.html) displays incorrectly in Opera.

### ISSUE THREAD

**Issue by ankoch** [uikit/uikit#831]
Your site (http://getuikit.com/docs/components.html) displays incorrectly in Opera.
![- -2](https://cloud.githubusercontent.com/assets/9210043/5602244/1cbca64a-9353-11e4-8e12-991013004e2d.png)
![- -1](https://cloud.githubusercontent.com/assets/9210043/5602241/f484c752-9352-11e4-9fc8-d2076d6f00d0.png)

Version Opera - 2.16

P.S. And in Opera 2.17 too:
![-1](https://cloud.githubusercontent.com/assets/9210043/5606260/637780fc-9437-11e4-99ce-5f70fd1dddf4.png)

**Comment by aheinze** [comment]
sorry, we support only the latest two browser versions
