### ISSUE TITLE
img {height:auto} is overriding height attribute in <img />

### ISSUE THREAD

**Issue by p3k** [uikit/uikit#833]
It seems UIKit has the same issue as Bootstrap had once upon a time.

https://github.com/twbs/bootstrap/issues/1899

E.g. I could not find a way to make this image work with UIKit (yes, it’s an outdated way to create margins using a 1x1 pixel.gif… but I am maintaining such user-generated HTML from 13 years ago and there is no way of updating it.)

    <img height="138" width="778" src="https://antville.org/static/pixel.gif" border="0">

**Comment by aheinze** [comment]
use style="width:778px;height:138px" if you don't want responsive behaviour of images

**Comment by Flimm** [comment]
I agree that setting `height: auto` on all `img` elements is problematic, because there is no way to undo that with CSS, you have to use the ugly `style="height: 100px"` in the HTML.

If you don't have access to the HTML, you can't undo the `img { height: auto }` using just CSS.
