### ISSUE TITLE
Slideshow in Modal dialog not showing

### ISSUE THREAD

**Issue by aberman** [uikit/uikit#834]
If I create a modal where inside the modal dialog box there is a uk-slideshow, the slideshow does not show.  If I move the slideshow out of the modal, it works as expected.

```html
<a href="#ec-slideshow" class="uk-thumbnail uk-overlay-toggle" data-uk-modal>

<div id="ec-slideshow" class="uk-modal">
            <div class="uk-modal-dialog">
                <ul class="uk-slideshow" data-uk-slideshow="{autoplay: true}">
                    <li>
                        <img src="img/small1.jpg">
                    </li>
                    <li>
                        <img src="img/small2.jpg">
                    </li>
                    <li>
                        <img src="img/small3.jpg">
                    </li>
                    <li>
                        <img src="img/small4.jpg">
                    </li>
                </ul>
                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-slideshow-item="previous"></a>
                <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slideshow-item="next"></a>
            </div>
        </div>
```

**Comment by aberman** [comment]
It shows up only once you resize the browser window, but not after the initial click.

**Comment by vuchl** [comment]
I think you need [this](http://getuikit.com/docs/documentation_javascript.html#data-check-display). Sorry, can't test right now.

**Comment by aberman** [comment]
I hadn't seen that doc before, thanks, but unfortunately it still doesn't work.  The event never fires on either the <ul> which defines the slideshow or an outer <div>.

**Comment by aheinze** [comment]
this will be fixed width next release and the hint provided by @vuchl

**Comment by danielsolosyatov** [comment]
Can you advise me? Is this issue solved? I updated the Uikit, but can't find this problem fixed.

**Comment by aheinze** [comment]
```<ul class="uk-slideshow" data-uk-slideshow="{autoplay: true}" data-uk-check-display>```

**Comment by danielsolosyatov** [comment]
Thank you for the feedback. Solved my issue.

**Comment by zeckdude** [comment]
Does this still apply to v3? I can't get the switcher to work within a modal. Once I move it outside of the modal, it works.
