### ISSUE TITLE
Nav not opening on page load when given uk-active OR uk-open

### ISSUE THREAD

**Issue by andrewkdesigns** [uikit/uikit#837]
Trying to get a nav with children to auto open (expand) on page load and it doesn't seem to want to happen.

I did some debugging and this JS seems to be running:
```javascript
this.find(this.options.lists).each(function() {
                var $ele   = UI.$(this),
                    parent = $ele.parent(),
                    active = parent.hasClass("@-active");

                $ele.wrap('<div style="overflow:hidden;height:0;position:relative;"></div>');
                parent.data("list-container", $ele.parent());

                if (active) $this.open(parent, true);
            });
```

but it the ````$this.open(parent, true);```` doesn't want to actually run.

Any ideas?

**Comment by andrewkdesigns** [comment]
So, I figured it out (I'm a dummy), only use ````uk-active```` on the element, not ````uk-open```` and ````uk-active```` or just ````uk-open```` only ````uk-active```` triggers the event.

**Comment by hansnolte** [comment]
Thank you published the solution.
