### ISSUE TITLE
Overlay buttons active on mobile

### ISSUE THREAD

**Issue by bodhimind** [uikit/uikit#838]
Sorry if this is a noob problem and not a bug, but it appears that (at least on iOS) when you tap a panel with overlay, if you tap an area where a link/button exists on the overlay, it clicks the button.  Is there any way to delay when the links become active?

**Comment by sommarbar** [comment]
Yes need same help

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?

**Comment by sommarbar** [comment]
??

**Comment by PixelT** [comment]
+1
This is not only in iOS (I have this same situation on Android)
