### ISSUE TITLE
Datepicker does not add value attr when a date is selected

### ISSUE THREAD

**Issue by andrewkdesigns** [uikit/uikit#839]
Just noticed that the datepicker addon does not add a value field (or change the current one) yet its still readable by jQuery (as the correctly selected date) but for anyone doing a normal POST to their server, this might be an issue.

**Comment by jerry1970** [comment]
I am using the datetimepicker plugin instead of the UIkit add-on and that doesn't change the value attribute of the input either, but when I do a regular POST, the selected value is posted. I can only assume the datepicker add-on will work the same as well.

**Comment by aheinze** [comment]
the value attribute is just for initialization on dom-ready and won't change during an update of the field. to get the current value via jQuery: ```var value = $('#my-text').val()```
