### ISSUE TITLE
Content in <td> elements are not truncated

### ISSUE THREAD

**Issue by p3k** [uikit/uikit#841]
I am trying to prevent `<td>` elements which contain long strings (no whitespace, e.g. URLs) from pushing the width of a `.uk-table` out of bounds.

Here is my current markup:

```html
<table class="uk-table uk-table-condensed">
   <thead>
      <tr>
         <td class="uk-text-right"><i class="uk-icon-bar-chart"></i></td>
         <td>Referrer</td>
         <td></td>
      </tr>
   </thead>
   <tbody>
      <tr class="av-referrer-row">
         <td class="uk-text-right av-referrer-count">21</td>
         <td class="av-referrer uk-text-truncate">http://localhost:8080/path/to/enlightenment</td>
         <td class="av-referrer-control uk-text-right">
            <a href="javascript:"><i class="uk-icon uk-icon-filter"></i></a>
         </td>
      </tr>
   </tbody>
</table>
```

In the best case the table looks like this:

![screen shot 2015-01-10 at 12 08 22](https://cloud.githubusercontent.com/assets/16631/5691334/6c751000-98c1-11e4-8eb9-649157d3d7f5.png)

If the content of the `.av-referrer` element increases, the table is overflowing into the right navigation (vertical gray line):

![screen shot 2015-01-10 at 12 11 50](https://cloud.githubusercontent.com/assets/16631/5691341/dc770c32-98c1-11e4-8639-d68be31aeed4.png)

How could I prevent this overflow? I know I could use `table.uk-overflow-container` but I would prefer to truncate or hide just the overflowing content in the `<td>` element instead of horizontally scrolling the whole table…

**Comment by aheinze** [comment]
wrap the text in a div within the td and add the class ```uk-text-truncate``` to the div

**Comment by p3k** [comment]
Nope, that does not change anything. And the `uk-text-truncate` class is already in the `<td>` element, anyway.

**Comment by malles** [comment]
You should apply some width to the cell, or css wil never now where to truncate..
Try `<td class="uk-width-1-2">Referrer</td>` in the header.

**Comment by p3k** [comment]
Thanks for your input, @malles – but alas, also this does not change the behaviour.

I even added the `uk-width-1-2` class to the `<td>` elements containing the referrers to no avail.

Bonus questions: how can I protect the table width and show multiple lines in the referrer column and only one line might contain such a troublesome long URL…?

**Comment by piotr-cz** [comment]
Only thing that seems to workis to set fixed width in pixels to the div with the `uk-text-truncate` class.

**Comment by piotr-cz** [comment]
Another workaround is to use `table-layout: fixed;` on the `<table>`
