### ISSUE TITLE
Modification for future releases - Font-sizing using rem

### ISSUE THREAD

**Issue by webketje** [uikit/uikit#842]
Currently there doesn't seem to be any way to quickly modify font-sizes for all `uk` classes in one fell swoop. This is important because different fonts have different readability in the same size, and [not everyone](http://www.smashingmagazine.com/2011/10/07/16-pixels-body-copy-anything-less-costly-mistake/) agrees that the default should be 14px (as is now). Especially with increasing resolutions (1600x900px and up) 14px looks pretty small.. <br><br>The use of `rem` units instead of fixed `font-size`'s could solve this. According to [caniuse](http://caniuse.com/#search=rem), except for some minor bugs, `rem` units work on all browsers but IE8- and Opera Mini. For those a fallback can be used by placing an alternate style rule above it (the currently used one):

`````
font-size: 14px;
font-size: 1rem;
``````
So my suggestion would be to give people the ability to control the base size by setting it on `body`, and uikit to control the relative `font-size` differences between components (which is well-done already imo).

**Comment by saschadube** [comment]
We won't introduce this to UIkit 2. But please suggest it for UIkit 3. https://github.com/uikit/uikit/issues/560

**Comment by gervet** [comment]
Hi, @saschadube This request was added in 2015; we are now on February 27, 2023 version (3.16.3 ) and still not using rem.
Do you have any idea of when are you going to implement it or if you are going to?
Please let me know. Thanks
