### ISSUE TITLE
Localstorage on simple uikit tab switcher

### ISSUE THREAD

**Issue by sommarbar** [uikit/uikit#843]
Hi i have a normal tab and got different information on every tab witch i want to stick when someone comes back to the webpage,

I am using joomla with yootheme uikit

I have for example 4 different  cities i want the city that was last visited as active, i am a beginner so i will really appreciate every help 

this is the module code

<pre>
<tt><ul class="uk-tab" data-uk-tab="{connect:'#tab-content'}"></tt></pre>
	<li class="uk-active"><a href="#">Stockholm</a></li>
	<li><a href="#">Malmö</a></li>
	<li><a href="#">Göteborg</a></li>
	<li><a href="#">Uppsala</a></li>
</ul>
<pre><ul id="tab-content" class="uk-switcher uk-margin"></pre>
	<li class="uk-active">{loadposition stock}</li>
	<li>{loadposition malm}</li>
	<li>{loadposition göte}</li>
	<li>{loadposition upps}</li>
</ul>

**Comment by sommarbar** [comment]
Thank you for answering but i am sorry did not get your answer?

**Comment by malles** [comment]
I think the point about localstorage has been missed.
maybe add it to #560

**Comment by vuchl** [comment]
@sommarbar you could implement a simple cookie with Javascript that listens to the ```change.uk.tab``` event and stores the current tab.

The event gets fired when you click on a tab. See [here](https://github.com/uikit/uikit/blob/master/src/js/core/tab.js#L39)

**Comment by sommarbar** [comment]
you know where i could get that cookie java script

**Comment by vuchl** [comment]
from http://www.w3schools.com/js/js_cookies.asp:
if your HTML looks kind of like this:
```html
<ul id="city-tabs" class="uk-tab" data-uk-tab>
    <li class="uk-active">{loadposition stock}</li>
    <li>{loadposition malm}</li>
    <li>{loadposition göte}</li>
    <li>{loadposition upps}</li>
</ul>
```
You could doo something like this:
```javascript
function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+d.toUTCString();
    document.cookie = cname + "=" + cvalue + "; " + expires;
} 

$("#city-tabs").on("change.uk.tab", function() {
	var cityName = $(".uk-tab > .uk-active > a").html()
	if(cityName != "")
	{
		setCookie("cityName", cityName, 7);
	}
});
```

**Comment by vuchl** [comment]
Also take a look at that:: https://developer.mozilla.org/en-US/docs/Web/API/document.cookie#A_little_framework.3A_a_complete_cookies_reader.2Fwriter_with_full_unicode_support

**Comment by sommarbar** [comment]
Great help vuchl thank you for responding, what file should i add this code?

Using for example stage theme yootheme

**Comment by sommarbar** [comment]
??

**Comment by vuchl** [comment]
Come on. This isn't about me making it all work for you. I don't have that much time. You can put this code in your template or stuff it into an external JavaScript file and reference it in your template.

**Comment by Pandahisham** [comment]
can it be fixed using history.js ?
