### ISSUE TITLE
Add separated class that styled controls without uk-form

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#846]
by default controls(input, select and others) not styled and must in form with uk-form class that changed styles. please add separated class (uk-form-control or uk-control-*) that easy use anywhere needs.  
[Update] maybe not in your policies but can styled controls by default.

**Comment by jerry1970** [comment]
Doesn't this work then?
```
<div class="uk-form">
    <input ... />
</div>
```

**Comment by aheinze** [comment]
@jerry1970 provided the right solution
