### ISSUE TITLE
ico be turned code

### ISSUE THREAD

**Issue by bolosmile** [uikit/uikit#847]
uk-nav uk-nav-side uk-nav-parent-icon

right ico turned code  like "f104" in firefox,
but normaly in chrome

**Comment by aheinze** [comment]
Sorry, I can't confirm this issue. could you please provide a code example on jsfiddle?

**Comment by bolosmile** [comment]
Hi,

my login page's whole code like this:

<%@ Page Language="C#" AutoEventWireup="true" CodeFile="login.aspx.cs"
Inherits="admin_login" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>

    <link href="uikit/css/uikit.min.css" rel="stylesheet" />
    <link href="uikit/css/uikit.docs.min.css" rel="stylesheet" />
    <script src="js/jQuery_v1.11.1.js"></script>
    <script src="uikit/js/uikit.min.js"></script>

</head>
<body style="background-color: #eeeeee;">
    <form id="form1" runat="server" class="uk-form">
        <div class="uk-align-center" style="width: 1001px; height: 150px;">
            <img src="" alt="" />
        </div>
        <div style="width: 1001px;" class="uk-align-center">
            <div class="uk-grid">
                <div class="uk-width-1-2">
                    <article class="uk-article">
                        <h4 class="uk-article-title">提示</h4>
                        <p class="uk-article-lead">1.请牢记账户和密码</p>
                        <p class="uk-article-lead">2.如若遗忘账户和密码请联系管理员</p>
                        <p class="uk-article-lead">3.本工作室承接各种中小型网站建设</p>
                        <hr class="uk-article-divider" />
                        <p class="uk-article-meta">联系电话：13308132169，王先生</p>
                        <p class="uk-article-meta">版权所有：大王工作室</p>
                    </article>
                </div>
                <div class="uk-width-2-5 uk-margin-large">

                    <fieldset>
                        <legend>欢迎登录</legend>

                        <div class="uk-form-row">
                            <div class="uk-form-icon">
                                <i class="uk-icon-user"></i>
                                <asp:TextBox ID="txtName" runat="server"
 placeholder="请输入用户名" ></asp:TextBox>
                            </div>
                        </div>
                        <div class="uk-form-row">
                            <div class="uk-form-icon">
                                <i class="uk-icon-key"></i>
                                <asp:TextBox ID="txtPwd" runat="server"
 placeholder="请输入密码" TextMode="Password"  ></asp:TextBox>
                            </div>
                        </div>
                        <div class="uk-form-row">
                            <input id="cbRemember" type="checkbox"
class="uk-margin-left" runat="server" /><label
class="uk-margin-left">记住用户名</label>
                        </div>
                        <div class="uk-form-row uk-text-center">
                            <asp:Button ID="btnOK" runat="server" Text="确定"
CssClass="uk-button uk-button-primary" OnClick="btnOK_Click" />
                        </div>
                    </fieldset>
                    <div id="msg" runat="server" class="uk-text-warning">
                    </div>

                </div>
            </div>
        </div>
    </form>
</body>
</html>



2015-01-13 17:25 GMT+08:00 Artur <notifications@github.com>:
