### ISSUE TITLE
Lightbox close not stop video stream

### ISSUE THREAD

**Issue by proweb** [uikit/uikit#848]
http://getuikit.com/docs/addons_lightbox.html
- going to Different content sources
- click youtube or vimeo or anithing else
- opens modal
- click play video
- click close modal

video stream and sounds still play

**Comment by aheinze** [comment]
Fixed: https://github.com/uikit/uikit/commit/eb281f559bf195cf49ff3e29da92b7520d59bc33 . Thanks.
