### ISSUE TITLE
Input elements issue in 2.16.0

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#853]
In latest 2.16.0 input elements graphic is broken.
No more round borders and wrong alignment.
Take a look at http://getuikit.com/docs/addons_form-advanced.html

**Comment by saschadube** [comment]
Thanks, we fixed it 6e2e6a2be410e1070215a0198954a2ac59d65bfe

**Comment by malles** [comment]
That solution seems to undo the https://github.com/uikit/uikit/commit/a4781cfcd2a3b06d132eb8368e275b576ce7c87f fix for submit en resetbuttons. (https://github.com/uikit/uikit/issues/805)
