### ISSUE TITLE
topoffset scroll spy

### ISSUE THREAD

**Issue by budsemporium** [uikit/uikit#854]
How to apply so that the element dont show untill i scroll down 47px?

**Comment by vuchl** [comment]
from the docs it looks like you need to add the ```data-uk-scrollspy="{topoffset: 47}"``` attribute  to the scrollspy element.

**Comment by budsemporium** [comment]
<div data-uk-sticky="{top:1}">
<div class="uk-scrollspy-outview" data-uk-scrollspy="{topoffset: 47}"><a href="#to-top" class="to-top-button uk-icon-arrow-up" data-uk-smooth-scroll></a></div>
</div>

that is my code. did i do it wrong it still shows as soon as the page loads

**Comment by budsemporium** [comment]
Thats not working still shows as soon as page loads

**Comment by arysom** [comment]
topoffset doesnt work for me also

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?

**Comment by arysom** [comment]
I've used it with sticky, but in jsfiddle my sticky doesnt work, anyway, i made http://jsfiddle.net/pm0urtc7/2/, hope it helps.

**Comment by arysom** [comment]
I think you can close this issue
