### ISSUE TITLE
Scrollspy + animation right = horizontal scroll

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#855]
http://getuikit.com/tests/core/scrollspy.html

When scroll up / down and have animation (problaly slide right), the appears horizontal scroll for a moment

**Comment by vuchl** [comment]
I can't ssee the scrollbar on my screen (24" FullHD)

**Comment by PixelT** [comment]
Tested on 1400 x 1050 resolution :)

**Comment by vuchl** [comment]
Yepp on 1400x1050 in Firefox ESR 31.4.0 I can see it too.

**Comment by PixelT** [comment]
I found another bug in scrollspy / animation-slide right or left
I have sticky navbar at the top and I scroll down using mouse wheel
I scroll to the section when the data-uk-scrollspy uk-animation-slide-left / right will be started
Next I try to scroll site up using mouse wheel - the sticky element don't stay at the top - you can see a small 'jump' effect

**Comment by aheinze** [comment]
this is an overflow "issue" during the animation. try ```body {overflow-y:hidden;}``` ;-)
