### ISSUE TITLE
Lightbox - Thumbnails

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#858]
Any thoughts on adding thumbnail helpers like [this example on AirBnb](https://www.airbnb.com/rooms/2791932?checkin=03%2F07%2F2015&checkout=03%2F14%2F2015&guests=2&s=hy72) (click on the big image at the to launch the gallery)? Would be a great addition as another navigation element. Thanks!

**Comment by saschadube** [comment]
We also need something like that for Widgetkit. At the moment we use the subnav or just inline elments in a row.

**Comment by saschadube** [comment]
We added a new thumbnav component :smile: It uses flexbox and can be aligned using the flex component. We also refactored the subnav and dotnav to use flexbox.

https://github.com/uikit/uikit/blob/develop/src/less/core/thumbnav.less

**Comment by zslabs** [comment]
Great to hear! Maybe an example of the thumbnav working inside of a lightbox would be a good addition to the docs. I don't see anything in that commit that would sync up their selections in the thumbnav component to lightbox attributes, so I think that's the part that's missing still. Either manually setting a thumbnail nav to match the amount of items that are available in the lightbox, or by passing a `data-uk-thumbnail` attribute onto each lightbox item (to manually create the thumbnav) would be pretty sweet.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. The Lightbox has not been released yet but we are already working on the component.

Thanks for your understanding,
Your UIkit Team

**Comment by arminmon** [comment]
Seems to be a good time to re-open.
A combination of Thumbnav and Slider inside Lightbox could be a rich feature.
