### ISSUE TITLE
Feature request: show/hide element on scroll

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#859]
Where the scrollspy script reacts to scrolling and an element getting into the viewport, I was thinking it would be cool to have an element react just to scrolling. In mobile sites, especially on smaller screens, the sticky nav is hidden when scrolling down and shown when scrolling up. Or when scrolling up a bit, a link appears that will send you back to the top of the page. Likewise, when scrolling down a bit, a link appears to send you to the bottom of the page.
So it is a show/hide with animation effect just reacting on scrolling the page and probably only useful for sticky or absolutely placed elements.

**Comment by adaniello** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by MacWordPress** [comment]
+1

**Comment by jerry1970** [comment]
I hope there will be screen size modifiers for this... On large screens the sticky nav can be visible at all times, on small screens not, etc.

**Comment by tbba** [comment]
+1

**Comment by aheinze** [comment]
thanks for the suggestion, we'll consider it for future releases.

**Comment by yaelduckwen** [comment]
+1

**Comment by muzafferkoluman** [comment]
+1
