### ISSUE TITLE
Search Component on Uncaught TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by Quatoor** [uikit/uikit#860]
select text in input then >

ln: 80 >
this.on('select.uk.autocomplete', function(e, data) {
&nbsp;&nbsp;&nbsp;&nbsp;if (data.url) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;location.href = data.url;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(data.moreresults) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this.autocomplete.input.closest('form').submit();
&nbsp;&nbsp;&nbsp;&nbsp;}
});

Basic solve
this.on('select.uk.autocomplete', function(e, data) {
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;if (data.url) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;location.href = data.url;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(data.moreresults) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this.autocomplete.input.closest('form').submit();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;} catch(e) { }
});

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?
