### ISSUE TITLE
Lightbox - Dynamic Images/Content

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#861]
Would be nice if we could bind an array of images [like you can with Fancybox](http://jsfiddle.net/wg4MD/) -- so you can trigger the lightbox on any element and feed in whatever type of data you want.

**Comment by jlzuri** [comment]
Not sure if this is exactly what you are looking for but I use the uk-hidden attribute to achieve something similar:

    <div>
	    <a href="my-image1.jpg" data-uk-lightbox="{group:'my-group'}">
		    <img class="" src="my-image.jpg">
	    </a>
	    <a class="uk-hidden" href="my-image2.jpg" data-uk-lightbox="{group:'my-group'}"></a>
	    <a class="uk-hidden" href="my-image3.jpg" data-uk-lightbox="{group:'my-group'}"></a>
	    <a class="uk-hidden" href="my-image4.jpg" data-uk-lightbox="{group:'my-group'}"></a>
    </div>

Hope it helps.

**Comment by malles** [comment]
Nice!

**Comment by zslabs** [comment]
Awesome, thanks @aheinze !

**Comment by ootek** [comment]
group[] has 4 items but I can not see the navigation arrows

**Comment by ootek** [comment]
yep! --"Make sure to include the CSS from the Slidenav component, so you can navigate between the items."

**Comment by john68-code** [comment]
Hi,

need help to combine a set of related images.

I have a group of related images that i would like to combine into a set, i use the same data-lightbox attribute value for all images i want to include in that set, so the visitor can easily browse them with "prev" and "next" arrows.

BUT it's not working, am able to see allimages out of this set.

HERE my codes 👍

                            <div class="carousel-item active">
                                <a href="images\marketing\diapo\2\01.jpg" class="lightbox d-inline-block" title="" data-lightbox="roadtrip">
                                    <img src="images\marketing\diapo\2\01.jpg" class="img-fluid rounded" alt=""></a>
                            </div>
                            <div class="carousel-item">
                                <a href="images\marketing\diapo\2\03.jpg" class="lightbox d-inline-block" title="" data-lightbox="roadtrip">
                                    <img src="images\marketing\diapo\2\03.jpg" class="img-fluid rounded" alt=""></a>
                            </div>


                              <div class="carousel-item active">
                                <a href="images\marketing\diapo\3\01.jpg" class="lightbox d-inline-block" title="" data-lightbox="roadtrip2">
                                    <img src="images\marketing\diapo\2\01.jpg" class="img-fluid rounded" alt=""></a>
                            </div>
                            <div class="carousel-item">
                                <a href="images\marketing\diapo\3\02.jpg" class="lightbox d-inline-block" title="" data-lightbox="roadtrip2">
                                    <img src="images\marketing\diapo\2\03.jpg" class="img-fluid rounded" alt=""></a>
                            </div>
HELP pls
