### ISSUE TITLE
Customizer: new themes not loading (404 on the less and json files)

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#864]
This error was submitted a few weeks ago, then the new themes were taken offline, then put back online with the note they were working, but I still get 404s on these files when selecting the Aurora default theme (Aurora default is an example, none of the new themes work):
```
http://getuikit.com/custom/aurora/uikit-customizer.less
http://getuikit.com/custom/aurora/styles/default/style.less
http://getuikit.com/custom/aurora/customizer.json
```

**Comment by saschadube** [comment]
Sorry, this was just an upload issue. There are only 3 official UIkit themes: default, gradient, almost-flat

**Comment by jerry1970** [comment]
Would be nice to see some more variations, though.

**Comment by malles** [comment]
@jerry1970 http://yootheme.com/demo/ would be the place to be :)

**Comment by jerry1970** [comment]
But that's complete yoothemes, right?
I am not using Joomla not yootheme, I am only looking for uikit CSS styles.

**Comment by malles** [comment]
But that _is_ basically what they do. Their themes are a less-layer over the UIkit LESS, just as the UIkit themes are.
I think it's up to the community to create different themes. I think the combination of these three, and the millions of styles that can be created in the customizer should be enough for a framework to deliver.
