### ISSUE TITLE
[ADD] Panel with heading

### ISSUE THREAD

**Issue by MySt1k** [uikit/uikit#865]
Hello please add classes for panels: .panel-heading and .panel-footer.
Here are screenshots of what I would like to differentiate amongst: 

![1](http://dl1.joxi.net/drive/0003/3256/208056/150117/1e5f4a94f4.jpg)
 ![2](http://dl2.joxi.net/drive/0003/3256/208056/150117/f853ab1733.jpg)
 ![3](http://dl1.joxi.net/drive/0003/3256/208056/150117/82249b8a16.jpg)

**Comment by jerry1970** [comment]
Nice idea. +1

**Comment by saschadube** [comment]
There is already a class ```uk-panel-title```. You can use it to style the panel title of the panel box like in your screenshot ```.uk-panel-box .uk-panel-title```. We don't think you often need a panel footer and we don't want to bloat the code with it.

**Comment by PixelT** [comment]
+1
