### ISSUE TITLE
UIkit.$ differs from jQuery and breaks selectors

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#867]
data-uk-toggle="{target:'body > aside:first > :not(:first)', cls:'uk-display-block'}" worked fine in older version, but not working in latest. Simpler selectors in target like #body works fine.
Looks like because of this commit: uikit/uikit@f71e6a7
Where you've started to use UIkit.$ instead of $
Any thoughts?

**Comment by aheinze** [comment]
should be fixed wit this commit: https://github.com/uikit/uikit/commit/27d2e1cdb0f081bfacbbbf30287ce7b36c121936
