### ISSUE TITLE
Responsive tab control filter with grid add-on 

### ISSUE THREAD

**Issue by JerryCipriano** [uikit/uikit#869]
When the tab control switches to a drop-down in response to narrow widths, it no longer controls filtering/sorting with the grid add-on.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
