### ISSUE TITLE
Hidden button in uk-button-group is regarded as button for style

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#870]
To style a radio button group, I use a uk-button-group. A hidden element is the form element, the buttons inside the group are the options. Clicking a buttion will set its value in the hidden element. I placed the hidden element inside the uk-button-group, so the javascript is a little easier: ```$(this).parents('[data-uk-button-radio]').find('input[type="hidden"]').val($(this).attr('value'));```.

So the HTML is like this:
```
<div class="uk-button-group" data-uk-button-radio>
    <input type="hidden" name="status">
    <button class="uk-button" type="button" value="1"> open </button>
    <button class="uk-button" type="button" value="2"> closed </button>
</div>
```

But the first visible button is styled like it's not the first. When using a style sheet that gives the first and last button rounded corners, the first button does not have rounded corners.

I know this is quite easy to fix (hidden element outside the uk-button-group, data attribute on the buttons to give the name of the element), but since this is all about styling, I think it's the right thing to check for hidden elements when counting the first element to style.

Jerry

**Comment by saschadube** [comment]
Please put the hidden element outside of the button group. We want to keep things simple and not bloat the code.

**Comment by jerry1970** [comment]
Good reply, but it would be a good thing to add to the documentation.
