### ISSUE TITLE
uk-button-warning?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#871]
There's a *-warning class for several elements, but the buttons do not have one. I've added it to my uikit-override, but this is more of an addition. Wouldn't it make sense to include a warning colour for buttons as well?

**Comment by zslabs** [comment]
This was already submitted as a PR and rejected https://github.com/uikit/uikit/pull/539

**Comment by jerry1970** [comment]
Was there a reason for the rejection? To me it sounds like something's missing - having those colours to text and badges but not buttons. I can add it, no problem, but I can't see a good reason why this should not be included in the main package.

**Comment by saschadube** [comment]
We think a warning button is a rare use case and we don't want to add too much stuff to not bloat the code. But sure, it is open for discussion.

**Comment by jerry1970** [comment]
It would be more consistent to include it, I think.

Or maybe the colours should be disconnected from the elements completely, so no uk-button-warning but just uk-warning.
