### ISSUE TITLE
Event on timepicker?

### ISSUE THREAD

**Issue by jkrassman** [uikit/uikit#872]
Hi, I am maybe tired - but shouldn't this work for the timepicker?

 $(document).ready(function() {
      	
			 $('#time').on({
       		 'onChange':function(){alert("Monkey");}
				});
		
            });

**Comment by vuchl** [comment]
The event you are looking for is ```change``` not ```onChange```. Anyway you should maybe listen to the ```select.uk.autocomplete``` inside the date picker (the datepicker uses the autocomplete component).

**Comment by aheinze** [comment]
@vuchl thanks!
