### ISSUE TITLE
Full URL in Autocomplete source not being handled correctly

### ISSUE THREAD

**Issue by john052** [uikit/uikit#873]
For UIKit 2.16.2
When providing a full URL for the source option of Autocomplete (i.e http://www.___.com),
after the call to UI.Utils.options(ele.attr("data-@-autocomplete")) in boot, the return object is empty.

Specifically it seems the ":" character in the url causes the options parsing to fail and return an empty object.

My autocompletes worked in UIKit 2.12, so I assume it handled the url correctly before. The options parsing seems to be the same as in UIKit 2.12, so not sure what changed.

On a related note, I can't get the select.uk.autocomplete event to fire. It fires when I physically highlight the already selected text in the input, but not when I select from the dropdown. Since my autocompletes or all non-functional now, I can't confirm the behaviour for UIKit 2.16.

**Comment by malles** [comment]
See #808

**Comment by john052** [comment]
Ok, close because of duplicate.
