### ISSUE TITLE
Combination uk-grid-small and uk-grid-divider

### ISSUE THREAD

**Issue by malles** [uikit/uikit#877]
I'm not sure if this is supposed to work, but combining `uk-grid-small` and `uk-grid-divider` messes up the right-margin:
http://jsfiddle.net/3yL1yqzL/

**Comment by saschadube** [comment]
Sorry, it doesn't work. It could, but we didn't want to bloat the code.

``` CSS
/*
 * Horizontal divider
 * Only works with the default gutter. Does not work with gutter collapse, small or large.
 * Does not work with `uk-push-*`, `uk-pull-*` and not if the columns float into the next row.
 */```

**Comment by malles** [comment]
Fair enough :)

**Comment by saschadube** [comment]
We will tackle this in UIkit 3 when we rework the grid :wink:
