### ISSUE TITLE
Feature request: Lightbox with swf or iframe

### ISSUE THREAD

**Issue by shrpne** [uikit/uikit#878]
Would be great if you make lightbox to work with swf and iframe.
Also they don't work in widgetkit examples https://yootheme.com/widgetkit/examples/lightbox

**Comment by saschadube** [comment]
The link you are referencing is to Widgetkit 1. It doesn't use UIkit.

Why would you need to open an iframe with the lightbox? You can just use the modal component. The lightbox just helps to easily generate modal dialogs for galleries with images and videos. I don't think you need this for iframes or do you? I'm sorry but we also won't add swf support.
