### ISSUE TITLE
add timer for switcher

### ISSUE THREAD

**Issue by Samanw** [uikit/uikit#879]
Hi
i want to know is there a attr or script that can add time between active li of SWITCHER
so it can change in every slide or li with time
thx for developing uikit

**Comment by jerry1970** [comment]
Sounds like you are trying to make a lightbox slideslow but with tab contents.

If you have a 'next' element inside the tabs (see documentation, page http://getuikit.com/docs/switcher.html, search for the text ```Switch to the next content section```), you can trigger that from javascript using this: ```$('next_selector').trigger('click');```.

There's probably a full-javascript way to do this, though.

**Comment by Samanw** [comment]
thx for answer
but i need something like slideshow , that automatic go to next content for switcher
is it possible?

**Comment by jerry1970** [comment]
Shouldn't be too hard. Take a look here:
http://www.w3schools.com/jsref/met_win_settimeout.asp

It will look something like this:
```
function nextTab() {
    // here comes the function to click the next tab
    $('next_selector').trigger('click');

    // and here you call this function again
    setTimeout(nextTab, 1000);
}
// this is to call the function for the first time
setTimeout(nextTab, 1000);
```

**Comment by Samanw** [comment]
thx for your help
but have problem in this 
it jump to last slide and stuck on it
```javascript
<ul class="uk-tab uk-tab-bottom siamaslidericons uk-width-1-1 uk-container uk-container-center uk-push-1-10" data-uk-tab="{connect:'#tab-bottom-content', animation: 'slide-horizontal'}" >
<li class="uk-active firstli"><a href="#">
<img src="images/slide1/small/1.png" /><br/><br/>
اسلاید اول
</a></li>
<li><a href="#">
<img src="images/slide1/small/2.png" /><br/><br/>
اسلاید دوم
</a></li>
<li><a href="#">
<img src="images/slide1/small/3.png" /><br/><br/>
اسلایت سوم
</a></li>
<li><a href="#">
<img src="images/slide1/small/4.png" /><br/><br/>
اسلاید چهارم
</a></li>
<li><a href="#">
<img src="images/slide1/small/5.png" /><br/><br/>
اسلاید پنجم
</a></li>
</ul>
```

**Comment by jerry1970** [comment]
Seeing your javascript as well would be useful, but if it is too hard to find out that after the last one you need to find a way to go back to the first, maybe it's a bit too far-reached for now? Also, now I see you really are making a slideshow and there are way better ways to do that. Try google...
