### ISSUE TITLE
Form element width uk-form-width-max does not acknowlegde mx-width of 100%

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#880]
I have a text input with class="input-text uk-form-width-large". Although it has a max-width of 100% which should overrule the width of 500px, the input remains 500 when I make the viewport smaller than 500 pixels. Even the body is less than 500, it's just the input that remains 500. Firebug tells me the max-width is above the width (so should be overruling), but the input remains 500 pixels.

Any ideas?

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?

**Comment by jerry1970** [comment]
Can't reproduce the error anymore, I guess it's fixed.
