### ISSUE TITLE
Subnav elements misaligned when text is centered

### ISSUE THREAD

**Issue by andrewkdesigns** [uikit/uikit#881]
So, this is an interesting issue... (Tested in Chrome 40.x)

When a subnav is text-align: center and using uk-subnav-line all elements but 1st nth-child(n+2)
 ``` .uk-subnav-line>li:nth-child(n+2):before ```
the text is a bit lower, and it seems to be coming from the display tag ``` display: inline-block ```
I'm not sure what the fix would be as its such a specific issue, but I figured I post it incase anyone else ever comes across this issue.

I'm not even sure if the ```display: inline-block``` is needed, I took it out on my project and everything else seems to look fine. Could this possibly be the fix?

![screenshot 2015-01-19 at 6 10 26 pm](https://cloud.githubusercontent.com/assets/3876981/5809444/84ab28f2-a006-11e4-9984-30d69b34ca61.png)

**Comment by saschadube** [comment]
We updated the subnav to use flexbox in next UIkit version. This issue should be fixed then. Also instead of ```uk-text-center``` you have to use ```uk-flex-center```
