### ISSUE TITLE
Applying styles through Less for a more semantic HTML

### ISSUE THREAD

**Issue by kismet010** [uikit/uikit#883]
In Bootstrap, I can:
```
footer {
  > nav,
  .my-custom-nav {
    .nav;
    .nav-tabs;
  }
}
```
To apply specific styles to those HTML tags or my own classes.

How can I achieve the same with UIKit?
I'm getting errors like:
```
 Error in plugin 'gulp-less'
Message:
    .uk-nav-pills is undefined in file...
```

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?
