### ISSUE TITLE
Cloning support for uk-nestable?

### ISSUE THREAD

**Issue by sathish274** [uikit/uikit#886]
Hi,

I am working on an UI which requires the dragged out item to remain in the source list. Is there a way to do cloning on the uk-nestable-item?

Also, how do i parse out the data value from the uk-nestable-item when the item is dropped onto another list? I see that dragStop function (defined in nestable.js) is invoked on drop. Is that what I should be modifying to extract the value? 

Thanks
Sathish

**Comment by aheinze** [comment]
hi, you have to implement this on your own by listening on ```change.uk.nestable``` on the list.
