### ISSUE TITLE
Gulp task to build complete JS and CSS (both core and components)

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#887]
This would be very useful, or, alternatively, to generate `uikit.min.js` and `uikit.components.min.js` (+ similarly for CSS).
Your components are good, but it is not very convenient to have all of them in separate files if I want them all.

**Comment by nazar-pc** [comment]
What about this? I can make pull request if you would like to merge it.

**Comment by philoest** [comment]
Hi this has been added to UIkit3 here you can run `npm run compile`.
