### ISSUE TITLE
Long title overlaps lightbox image

### ISSUE THREAD

**Issue by jlzuri** [uikit/uikit#889]
When a long text is used as title of a lightbox element, the text overlaps the displayed image. Example:

![untitled](https://cloud.githubusercontent.com/assets/589448/5835713/07e46b78-a16c-11e4-94cd-4d712f9ed149.jpg)

**Comment by saschadube** [comment]
Fixed ed697b9294aa2d4935fe3c407e115b7dd2c5afca
