### ISSUE TITLE
How to stop uploading using the Upload add-on?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#891]
Using the ```before``` event I check some things before I want people to be able to upload. How can I stop the uploading during this (or any other) event?

I know as a workaround I could disable the Upload until all other requirements are met...

Thanks

**Comment by malles** [comment]
just returning false in the before function works for me.
```
                    before: function (settings, files) {
                        if ($this.options.uploader.sizelimit > 0 && files[0].size > $this.options.uploader.sizelimit) {
                            var msg = UI.bixLang._('fileTooLarge')
                                .replace('{file}', files[0].name)
                                .replace('{sizeLimit}', UI.bixTools.formatFileSize($this.options.uploader.sizelimit));
                            UI.notify(msg, {status: 'warning'});
                            return false;
                        }
                    },
```

**Comment by malles** [comment]
You do need to use the `option` before and put your function there, an event won't return anything:
https://github.com/uikit/uikit/blob/master/src/js/components/upload.js#L171

**Comment by jerry1970** [comment]
I believe I tried returning false from the ```before```, but I'll try again, probably something else I forgot.
I said "```before``` event", but I meant the same as you: the ```before``` option.

Thanks
