### ISSUE TITLE
navbar with fixed position doesnt fill the full width of its container

### ISSUE THREAD

**Issue by cocodrino** [uikit/uikit#892]
Hi..maybe it's a dumb question but I don't get how make than my fixed navbar fill my container width...am I doing something wrong??

here is an example
http://jsfiddle.net/TYVta/16/

thanks!!

**Comment by malles** [comment]
Try using the sticky-component:
http://jsfiddle.net/tpmauyqw/1/

**Comment by malles** [comment]
Sidenote: `uikit.gradient.min.css` is a full css file. You don't need to load the `uikit.min.css` file before that.

**Comment by cocodrino** [comment]
thanks for the reply, the problem is than my sticky component seems not works as expected...

I've a HTML component  
       ```html <div id="articleBox" class="uk-width-1-1 "> .... </div> ```

with this css

```css
            #articleBox {
              height: 100px;
              overflow: hidden;
             overflow-y: auto;
            }

```



my sticky component lives inside this "#articleBox"



```HTML
<nav id="smallBar" class="uk-navbar" data-uk-sticky>
            <ul class="uk-navbar-nav">
                        <li class="uk-active"><a href="">All</a></li>
                        <li><a href="">Articles</a></li>
                        <li class="uk-parent"><a href="">Videos</a></li>
           </ul>
</nav>

```


but it seems not works
![errorui](https://cloud.githubusercontent.com/assets/616412/5911803/b9fcbe8a-a59c-11e4-812e-e732471d148d.png)

notice than if I remove the overflow inside #articleBox and if is the body which has the overflow, it works!

![error1](https://cloud.githubusercontent.com/assets/616412/5911814/e3334274-a59c-11e4-8aa4-f858c4655283.png)


seems than the sticky component is not detecting the correct parent scroll...please let me know if you need more details, I can upload a jsfiddle although my html code right now is really ugly and I'd prefer doesnt share it yet :D ....

**Comment by cocodrino** [comment]
I did a demo http://jsfiddle.net/a0sfd7fj/

if the sticky component has other html elements before seems not works...

**Comment by malles** [comment]
It's the overflow: y in the red div that gives the trouble.
I'm not sure if this is possible this way...

**Comment by cocodrino** [comment]
ehh..I suppose than you refer to the blue one (which is the one with the overflow :D) ...I could write the sticky, the code is  not hard but when I did it my uk-navbar-nav lost its format and change its size...so I'm really stuck with it....

**Comment by aheinze** [comment]
add the class ```uk-width-1-1``` or  ```uk-width-1-2``` to the navbar
