### ISSUE TITLE
Radiobox / checkbox switch(er)

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#893]
Small feature to form component / add-ons
Radiobox / checkbox animation switch

Demos:
https://rawgit.com/djanix/jquery.switcher/master/index.html
https://ghinda.net/css-toggle-switch/index.html

**Comment by saschadube** [comment]
Thanks for your suggestion. Maybe in the future

**Comment by likeweb** [comment]
@saschadube the future is one year ago ;-) but there is still no animation switch in uikit :-(
I think in 2016 radio- / checkbox toggle switches should be a standard in uikit.

**Comment by rvalitov** [comment]
It's 2017, and the UIKit 3 is here. Still the checkbox toggles are missing...

**Comment by zzseba78** [comment]
https://github.com/uikit/uikit/issues/2531

**Comment by Olajumoke** [comment]
hmmm

**Comment by itsromack** [comment]
I also would love to have that switcher in this UIkit framework. Thanks

**Comment by decodercc** [comment]
@saschadube and in 2022 we dont see it in uikit :)
