### ISSUE TITLE
Upload Add-on: Dropzone callbacks

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#895]
[DropzoneJS](http://www.dropzonejs.com/bootstrap.html) gives a number of good callbacks and interactions for starting uploads, canceling, deleting, etc. Would love to see a lot of these added to make this a more viable complete gallery solution. Coupled with the sortable add-on, this would be great.

**Comment by aheinze** [comment]
I think this is too special and case related. but thanks for the suggestion.
