### ISSUE TITLE
Include more context on uk.tab.change events.

### ISSUE THREAD

**Issue by schinckel** [uikit/uikit#896]
I'd like to know, for instance, what the previously selected tab was.

I'm currently doing this by patching the tab click handler function, and adding a new item to the arguments array in the call to trigger.

    $this.trigger("uk.tab.change", [$(this).addClass("uk-active"), {previous: <previous-elemement>}]);

I'm also doing something similar on the initial trigger of this event: indicating that it is the first firing of the event (which happens during the init function): allowing me to ignore the first fire of this function per-tab set (since I already have the content loaded).

Is this something you might consider including?

**Comment by aheinze** [comment]
I think this can be easily done by custom code and 2 helper variables in your code. But we'll consider it it for UIkit 3. thanks!

**Comment by schinckel** [comment]
That's a fairly dismissive comment: care to share how you think it could be done? I'm currently having to run a patched version of UIkit, it would be nice to run vanilla.

**Comment by aheinze** [comment]
I didn't want to be dismissive, sorry if you felt so...I hope this commit helps you:  https://github.com/uikit/uikit/commit/34854d469007b604a3d90274e580eeddebdd71fb
