### ISSUE TITLE
datepicker onselect event

### ISSUE THREAD

**Issue by MangaRed** [uikit/uikit#898]
When a user clicks a day number I want to execute a function but there is no onSelect event in datepicker, just show, hide and update, I tried with hide.uk.datepicker. It works when I click outside of the datepicker but not when select a day number, it hides but doesn't trigger the event.

**Comment by vuchl** [comment]
you need to listen to the `change`event of the underlying autocomplete component. See https://github.com/uikit/uikit/issues/884 and https://github.com/uikit/uikit/issues/872

**Comment by MangaRed** [comment]
With `change` event it worked. now this is my code:
`$('#date').on('change', checkResults)`;
I tried before with the `change` event but with pure javascript. That only worked when the input was lost focus

**Comment by wwwizzarrdry** [comment]
Strangely enough, this wasn't working for me. The change event only fires on the first date selection, and never again for subsequent changes. 

My date pickers are inside a modal.confirm dialog, and are auto intialized with the data-uk-datepicker attribute.

I got it working only listening for both the change.uk.datepicker, and the update.uk.datepicker events. Hope this alleviates some head scratching for someone else down the road.

$(document).on("change.uk.datepicker update.uk.datepicker", ".datepicker", function(){
   var date_selected = $(this).val();
   UIkit.notify(date_selected);
})
