### ISSUE TITLE
off-canvas close - residual margin

### ISSUE THREAD

**Issue by zakir2k** [uikit/uikit#899]
When I use UIkit.offcanvas.hide() Javascript to close my active off-canvas. 

The off-canvas sidepanel closes correctly with animation.

But the result leaves a  class  "uk-offcanvas-page" and a  "style="width: 1151px; height: 622px; margin-left: 270px;" attribute in my html tag.   (which I believe is the size of the canvas that has just been removed).

Which I need to remove manually myself.  Is this correct behaviour?

**Comment by vuchl** [comment]
From the source at https://github.com/uikit/uikit/blob/master/src/js/core/offcanvas.js#L46 the `.css()` should do that. The implementation according to the jQuery [docs](http://api.jquery.com/css/#example-1-3) for multiple css properties looks fine.

**Comment by zakir2k** [comment]
Oh - thank you for pointing me in the right direction.
Yes the body tag addition/removal of css styles is working smoothly.

However line 49 is not sufficient in my project as the css style of margin-left, width and height remain within the html tag.  But I can adjust that myself. 

Cheers vuchl.
