### ISSUE TITLE
Nested data-uk-grid-margin not working after update 2.11 > 2.16.2

### ISSUE THREAD

**Issue by roterkater** [uikit/uikit#902]
Hi,

After upgrading Uikit my nested uk-grid won't apply uk-grid-margin properly. In 2.11 all worked fine. Bug or do i miss something?
Please see attached screenshots version 2.11 and 2.16.2.
thanks!
![2-11](https://cloud.githubusercontent.com/assets/9219820/5876475/bdd5cf4c-a317-11e4-8820-68599a0f7d86.png)
![2-16-2](https://cloud.githubusercontent.com/assets/9219820/5876476/bdea0af2-a317-11e4-87ec-6374408ef96b.png)
![screen](https://cloud.githubusercontent.com/assets/9219820/5876474/bdb23514-a317-11e4-9bac-fcc4c14ae17f.png)

**Comment by aheinze** [comment]
could you please provide a jsfiddle - http://jsfiddle.net ?

**Comment by roterkater** [comment]
Hi aheinze,
I failed to replicate the exact issue but there's another problem.
http://jsfiddle.net/roterkater/fLmzyfkn/
thanks!

**Comment by saschadube** [comment]
Looks correct to me. If you want a dynamic grid take a look [here](http://getuikit.com/docs/addons_grid.html)
