### ISSUE TITLE
Include Font Awesome 4.3.0

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#903]
Font Awesome 4.3.0 has just been released.
Please include them in next UIkit update.

**Comment by luetn** [comment]
you are fast :-)

**Comment by nstaeger** [comment]
Dublicate #900

**Comment by jerry1970** [comment]
Also possible: keep FontAwesome as it is (so we would have to use ```fa``` classes) so anybody can use any version of FA without needing a new version of UIkit.

**Comment by robertotremonti** [comment]
Please move font awesome functionality from core to a separated additional component so one can choose to use uikit version or original one without duplicated resources.

**Comment by jerry1970** [comment]
Ah, @robertotremonti has the best solution.

**Comment by saschadube** [comment]
#900

**Comment by zslabs** [comment]
There was talk about SVG icons (as a sprite possibly) replacing the icon fonts for better rendering, I've personally got an SVG set working within my app -- will see if I can get with them on ways they can also integrate.

**Comment by robertotremonti** [comment]
@zslabs What's the problem in using icon fonts? Aren't they rendered properly?

**Comment by zslabs** [comment]
@robertotremonti Since icon fonts are rendered as just that, "fonts" -- you'll always deal with aliasing issues across different browsers. SVGs have a consistent rendering appearance among others. [CSS Tricks has a good comparison article](http://css-tricks.com/icon-fonts-vs-svg/).

**Comment by robertotremonti** [comment]
@zslabs Thanks for the clarification.

**Comment by aheinze** [comment]
will be included in the upcoming release.
