### ISSUE TITLE
[ADD] Sticky bottom

### ISSUE THREAD

**Issue by MySt1k** [uikit/uikit#905]
Hello. Add an option similar to "top" only from the bottom of the page.
For what? In some cases, block overlaps the footer, which is not very nice. If you configure the option botton on 200px, then when the full visibility footer, the unit will not go to the bottom and remain on the 200px above.

OR

How to stop Sticky at the bottom?

**Comment by jerry1970** [comment]
Not sure what you mean by your explanation, but a +1 for the Stick To Bottom (which sounds only marginally better than Sticky Bottom ;))

**Comment by MySt1k** [comment]
I'm just hard to explain it in English, I'm from another country.

**Comment by malles** [comment]
I think this is about a offset from the bottom. For example a sticky sidebar that stops x pixels from the bottom, not to overlap the footer. For example https://www.boekenbrochures.nl/. In this example not a fixed offset from the bottom is used, but the sticky module is constricted by the container it's in.

**Comment by MySt1k** [comment]
@malles , yes

**Comment by malles** [comment]
This is my adjustment for this behavior: https://github.com/malles/uikit/commit/e74e15a1dae899cbf19e18aae03a90d036678eaa
I'm not sure if this is worth a PR, it is up to UIkit to see if it is a wanted addition.

**Comment by MySt1k** [comment]
Thank you very much! You can not imagine how you helped me.
I hope this addition will be included in the official version of a developer.

**Comment by aheinze** [comment]
@malles feel invited to create a pull request ;-)

**Comment by aheinze** [comment]
@malles pull request is merged for the upcoming release
