### ISSUE TITLE
Scrollspy Events

### ISSUE THREAD

**Issue by Shtier** [uikit/uikit#906]
Hi, 
If the item is already visible (in a prominent position). Classes is added (uk-scrollspy-init-inview uk-scrollspy-inview), but the event does not fire. How to make it work?
Example:
http://jsfiddle.net/wj3h3c25/1/

**Comment by Shtier** [comment]
Is there anything better than this solution?

 	function checkReadyScrollspy()
{

    if ($('[data-my-item]').hasClass('uk-scrollspy-inview'))
	{

		$( "[data-my-item]" ).each(function( index ) {
			alert( 'Ready' );
		});

	}
          
    else
	{
		setTimeout( checkReadyScrollspy, 500 );
	}
        
}
	checkReadyScrollspy();

Example here - http://jsfiddle.net/wj3h3c25/2

**Comment by Shtier** [comment]
Hi,
The events is working if rearrange line:

	if (inview && !inviewstate) {

		if(idle) clearTimeout(idle);

		if(!initinview) {
			$this.element.addClass($this.options.initcls);
			$this.offset = $this.element.offset();
			initinview = true;

			$this.trigger("init.uk.scrollspy");
		}

		idle = setTimeout(function(){

			if(inview) {
				$this.element.addClass("@-scrollspy-inview").addClass($this.options.cls).width();
				$this.trigger("inview.uk.scrollspy"); // this way
			}
		}, $this.options.delay);

		inviewstate = true;
		// $this.trigger("inview.uk.scrollspy"); from here
	}

**Comment by aheinze** [comment]
thanks for reporting, this will be included with the upcoming release.
