### ISSUE TITLE
tooltip options per site possible?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#908]
It seems I have to set the tooltip options every time I have an element with a tooltip.

Is it possible to set the tooltip options (especially the pos, animation and delay) per site, so all tooltips on the site have the same behaviour? I know I can use a string like
``` php
$tooltipOptions = '{pos: \'top\', delay: 500, animation: true }';
```
set in one file and included on every tooltip instance, but if it's already possible I would love to know and use what's already there.

Thanks

**Comment by malles** [comment]
+1
Same goes for i18n settings for datepicker and other default-options.

**Comment by aheinze** [comment]
you can already do that for each component. e.g. for the tooltip:

```javascript 
$.extend(UIkit.components.tooltip.prototype.defaults, {
    pos: 'top', 
    delay: 500, 
    animation: true
});
```

**Comment by malles** [comment]
Nice! I knew there would be something like that!
Maybe put this snippet in the javascript-docs?

**Comment by jerry1970** [comment]
Thanks, @aheinze ! Didn't know this, and I am not the only one. Seems like a good idea to spend a chapter in the documentation on this...

**Comment by pniaps** [comment]
I was looking for a way to change any component default options.
Thanks, @aheinze
