### ISSUE TITLE
Modal Lightbox cut off in Chrome at the bottom

### ISSUE THREAD

**Issue by theother1** [uikit/uikit#910]
I have this annoying problem that the modal lighbox is cut off in Chrome. How much is cut off at the bottom depends on how far up in the window the link was before I clicked on it. The higher it is up the more the modal is cut off at the bottom. It's is completely broken when I work on an iphone with Chrome and the whole screen goes dark with no modal at all.

Works perfect on Firefox. I tried other people/computers, they all have the same problem with Chrome. Mac or Windows makes no difference. This happens with all modal lightboxes I use from uikit.

I copied the code in the example from here fro the Lightbox Modifier:
http://getuikit.com/docs/modal.html

This is my code:
<a href="#my-id2" data-uk-modal="{center:true}"><img src="images/SteveBodygraph.svg" alt="Steve Rhodes' Human Design Chart" class="pull-center" title="Steve Rhodes' Human Design Chart" /></a>
</div>

<div id="my-id2" class="uk-modal" >
   <div class="uk-modal-dialog uk-modal-dialog-lightbox">
       <a href="" class="uk-modal-close uk-close uk-close-alt"></a>
        <img src="images/SteveBodygraph.svg"  alt="">
    </div>
</div>

You can test it at: http://indiarhodes.com/en/home/about/steve-rhodes
I used an svg in this example, but the problem is the same with a jpg.

![modal](https://cloud.githubusercontent.com/assets/10718044/5912135/f5397e64-a5c6-11e4-876d-ca3d705520eb.jpg)

I would appreciate a solution, because I can't go out with the website like this.
Thanks!

**Comment by aheinze** [comment]
could you please try, to give the image width and height attributes?

**Comment by theother1** [comment]
I did. makes no difference. I also changed the svg to jpg to be sure this is not an issue.
Check again: http://indiarhodes.com/en/home/about/steve-rhodes
BTW it also happens with the modal in the page counter that says "80 countries". But here the browser windows has to be really small in order for the problem to be here.

When the browser window is really small the modal disappears totally. I see it very briefly flash up and the it's gone with only the dimmed background. Also the cut-off picture. For a little moment I see the full picture before it gets cut off at the bottom. What gets cut off changes from the position the link was before I clicked it. If it's high up on the browser window almost everything gets cut off. If the link is very low down in the window before I click, there is chance I see everything. Try it yourself.

I didn't know how to paste the code in here... But you can see it from the link within console anyway I guess...

thanks for any help

**Comment by aheinze** [comment]
please try to use the following snippet:

```.uk-modal { transform: translateZ(0); }```

**Comment by theother1** [comment]
I wasn't sure where to add this. I think I did it right, but it still doesn't work. You can check here:
http://indiarhodes.com/en/home/about/steve-rhodes


How can I paste HTML into this window? Doesn't work... Can you take it out of the console from the above link and try it and then post a working solution?
Many thanks! I must go live with the site in a few days and I need working modals. Let's hope this can be solved until then. I'm using Yootheme for the site and don't want to use other modals if it can be avoided.

**Comment by theother1** [comment]
I think I figured out where to place it and it seems to work now. Thanks!
