### ISSUE TITLE
lightbox with youtube or vimeo not working in firefox with enabled screensize emulator

### ISSUE THREAD

**Issue by sba** [uikit/uikit#912]
Lightboxe with youtube- or vimeo-content is flickering / infinite reloading.

How to reproduce: 
-Open http://getuikit.com/docs/addons_lightbox.html
-Switch Screensize emulator on ([Ctrl]+[Shift]+[M])
-Click to the vimeo or youtube examle-button 

tested with uikit 2.16.2  and FF 35.0.1 and 37.0 on windows 8

**Comment by aheinze** [comment]
can't confirm this for current develop branch + FF 35.0.1.
