### ISSUE TITLE
Upload add-on: first example shows styling error

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#918]
See the Upload add-on page:
http://getuikit.com/docs/addons_upload.html
![screenshot-getuikit com 2015-01-29 19-33-52](https://cloud.githubusercontent.com/assets/5627407/5963584/de11716e-a7ed-11e4-824a-3d0cdb6cc22b.png)
The text ```selecting one``` is a few pixels below the first part of the sentence. Screenshot taken in Firefox, but it looks the same in Chrome.

**Comment by saschadube** [comment]
Thanks for reporting. We are aware of this issue but we don't have a fix at the moment without doing too much custom code.
