### ISSUE TITLE
File component: cannot get it to work

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#919]
Does anybody have a good example of how to get this to work?
http://getuikit.com/docs/addons_upload.html

The Form File element (Common section) works, but this one is ugly so I'd like to use the Upload instead: a placeholder for dropping files and a text to click for the File Open dialog.

The documentation is very unclear on which JS files I have to include. I'll open a different ticket for this.

**Comment by malles** [comment]
I have implemented the uploader, but that is not live yet. Here is a Gist of my upload-file, maybe it can help you https://gist.github.com/malles/5a2ef0dee6d6889acb13

**Comment by aheinze** [comment]
@malles thanks
