### ISSUE TITLE
Documentation unclear on which files to include

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#920]
The documentation website mentions Components and Add-ons. CSS and JS files are stored in ```core``` and ```components```. Slightly confusing.

The documentation for Add-ons mentions a structure using ```components``` but then uses an example with a different include folder. Confusing.

Then it's unclear which JS and CSS files are required for which add-on / component.

It's also unclear which files are used by which add-on. Most of the times the file names are much like the add-on / component name, but I can't see the JS file for component Form File.

The ```core``` folder also has a lot of files, but I don't need to include ```switcher.js``` because it was already loaded. Confusing.

It would be wonderful if someone could spend a little time on this for those as confused as I am...

Thanks!

**Comment by tijj** [comment]
I agree - I want to implement customizer on an html page and I have no idea which files to include and what is the directory structure. Thanks

**Comment by saschadube** [comment]
There are core components which usually consit of a CSS and JS source file. All core components are bundled in UIkit. So you only need to load ```uikit.css``` and ```uikit.js```

And there are additional components called add-ons. They require UIkit. Just load their CSS and JS file after UIkit if you need one of the additional components.

**Comment by jerry1970** [comment]
So the site has "core components" under `components` and "add-on components" under `add-ons`.  
But the files for "core components" are stored under "core" and the files for "add-on components" are stored under `components`.

That is confusing.

**Comment by saschadube** [comment]
We will update it with the next release :smile:

**Comment by jerry1970** [comment]
OK, good to know, thanks
