### ISSUE TITLE
uikit-slider-bug

### ISSUE THREAD

**Issue by shakilaiub** [uikit/uikit#921]
a bug found in uikit slider. 
in slider uk-button doesn't work. 
i test this & have to done with in-line js.... 
i am attached also an example...
plz check...
also not found any clear documentation of uikit.....
i think good & well-planed documentation increase usability. 
let me know if i can help uikit team for their development or documentation....
i will try my best....Thank u 
here is a gitHub link....

https://github.com/shakilaiub/uikit-slider-bug

plz download this & let me know how to fix this bug or any other way to use button in slider
Thank U

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?
