### ISSUE TITLE
[ADD] Double Tooltip

### ISSUE THREAD

**Issue by MySt1k** [uikit/uikit#922]
Please add Tooltip to do so: (To show I used Photoshop)
![9ae2633909](https://cloud.githubusercontent.com/assets/5097581/5987504/57df2594-a957-11e4-8dbc-97e72eac14e3.png)

**Comment by zslabs** [comment]
Could you expand on a real-world application for something like this? I have never seen anything like this used...

**Comment by MySt1k** [comment]
Sorry, but I lost the site where it was

**Comment by vuchl** [comment]
Useless feature I think

**Comment by jerry1970** [comment]
Useless, I think. If I'd ever need this, I think adding a transparent element with tooltip center bottom on top of the button with tooltip center top could do the trick, if the mouseover was delegated properly.

**Comment by aheinze** [comment]
I don't really see a real world scenario for this, sorry.
