### ISSUE TITLE
when I set the base...

### ISSUE THREAD

**Issue by cos800** [uikit/uikit#923]
```js
require.config({
    baseUrl: 'static/lib',
    paths: {
        jquery: 'jquery/dist/jquery',
        uikit: 'uikit/js/uikit'
    },
    config: {
        uikit: {
            base: 'a' // <-- look this
        }
    }
});
require(['jquery','uikit!notify,sortable'], function($,UI){

});
```
then requirejs load like this:
http://localhost/static/lib/**a**/components/notify.js
http://localhost/static/lib/**a**/components/sortable.js

when I change base to '**uikit**', no change other.
and requirejs load like this:
http://localhost/static/lib/**uikit/js/uikit**/components/notify.js
http://localhost/static/lib/**uikit/js/uikit**/components/sortable.js

**Comment by cos800** [comment]
and I change base to '**/a/**'
requirejs load url like this:
http://localhost**/a/**components/notify
http://localhost**/a/**components/sortable
it lose “**.js**”

**Comment by malles** [comment]
When you make your base `uikit`, it refers to you path `uikit`, and replaces it with `uikit/js/uikit`.
