### ISSUE TITLE
Grid display flex breaks when running headless specs

### ISSUE THREAD

**Issue by colindresj** [uikit/uikit#925]
While it's great that UIkit is looking forwards and dropping support for older browsers, we've run into problems when trying to run feature tests against UIs built with the grid component because it is set to `display: flex`. Most webdrivers don't support `flexbox`, so we have to manually redeclare `.uk-grid` and set it's display to `block`.

It might be nice to wrap the `flexbox` part of the grid component inside an `if/else` statement that can be controlled by a variable, that way we can dynamically control whenever we can't rely on `flexbox`.

**Comment by aheinze** [comment]
which browser is your target of concern?

**Comment by colindresj** [comment]
@aheinze Really just headless browsers like PhantomJS

**Comment by saschadube** [comment]
UIkit is moving slowly to use flexbox in all components. Sorry, but only browsers with flexbox are supported.
