### ISSUE TITLE
Add Wizard Component

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#926]
please add wizard component with steps ,vertical and horizontal mode and complete, current status with numbers or icons. so can go to before and next step with linked buttons(with javascript) and have slide steps effect such as scroll up/down, fade and compatible with other components.

**Comment by jerry1970** [comment]
I've made a wizard with only elements that are available now. A form with inputs that have a ```data-wizard-step-target="X"```, X being 1 to 5. The steps are in a button group with ```data-wizard-step="X"```.

Of course you can style the wizard steps any way you like.

A JS function of a few lines listens to the ```click``` event of the elements in the button group and hides all form elements except those with the data-wizard-step-target the same as the button's data-wizard-step.

You can add anything you want in this function: animation for showing and hiding the inputs (you might want to group input elements inside a div and show/hide the whole div at once), change the colour of the radio button elements (that's what I did, using primary, warning, and danger), add an icon to the buttons.

**Comment by aheinze** [comment]
Thanks for the suggestion, but this is too special

**Comment by mojtabakaviani** [comment]
Ok, but very useful and not in any frameworks. so usually in the every website have wizard

**Comment by miladmeidanshahi** [comment]
+1

**Comment by fursid** [comment]
+1

**Comment by sureshHARDIYA** [comment]
+1

**Comment by Uhelliton** [comment]
+1

**Comment by KadenLNelson** [comment]
I want to +1 this, but I feel like you could accomplish this task by utilizing other components within the UIKIt framework.
