### ISSUE TITLE
input[type=submit] styles overriden by .uk-form input normalization

### ISSUE THREAD

**Issue by shrpne** [uikit/uikit#929]
It was fixed by PR c84576a4fc069995b43cedac3fa6f5c31318b9f2
But after 2.16.1 this issue appear again.

Why this normalization applies to .uk-form elements? Why not to normalize simple inputs, selects, etc. like it was in normalize.css?

**Comment by saschadube** [comment]
The fix broke the form component. Unfortunately we don't have another one at the moment. We moved the normalization into the components to cause less conflicts with 3rd party CSS.
