### ISSUE TITLE
How to show datepicker on focus?

### ISSUE THREAD

**Issue by MangaRed** [uikit/uikit#930]
How to show the datepicker when the input is focused?

**Comment by jerry1970** [comment]
That is default behaviour. If the datepicker does not show, it could be that the input has no datepicker or the datepicker on that input has not been initialized properly. If you do get a datepicker when you click on the input but not when the input gets focus, maybe you've removed the focus listener for that input.

**Comment by MangaRed** [comment]
The datepicker appears when I click on the input, but not when it runs `$input.focus()`, neither when focus with the tab key. And I didn't change anything in the datepicker.min.js. 
By the way is there a way to use a variable in the data-uk-datepicker attribute, because I have many inputs with datepicker, and all use the same options? 
Like this:

    <input id="fecha1" type="text" data-uk-datepicker="options">
    <input id="fecha2" type="text" data-uk-datepicker="options">
    <input id="fecha3" type="text" data-uk-datepicker="options">
    <input id="fecha4" type="text" data-uk-datepicker="options">
    <script>
        var options = {format:'DD/MM/YYYY',i18n:{ months:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'], weekdays:['Dom','Lun','Mar','Mie','Jue','Vie','Sab'] }}
    </script>
    ...
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/uikit.min.js"></script>
    <script src="assets/js/datepicker.min.js"></script>

**Comment by MangaRed** [comment]
I tested with the example from the uikit website
http://getuikit.com/docs/addons_datepicker.html

I switched tab, I went through all the links, and when reached the input datepicker it doesn't open it

**Comment by jerry1970** [comment]
Can you show us some console logs?

**Comment by saschadube** [comment]
Could you please provide a [JSFiddle](http://jsfiddle.net/)?

**Comment by MangaRed** [comment]
Sorry, I can't, the proyect using the addon is done. Now I'm focusing in other things
