### ISSUE TITLE
uk-sticky and uk-nav accordion not working on angular directive

### ISSUE THREAD

**Issue by abarcenas29** [uikit/uikit#931]
I have a block of html (header menu) that is enclosed in a `<admin-header data-uk-observe></admin-header>` tag. It has a off-canvas (working) and it has a data-uk-sticky attribute included. The sticky part is not working.

The page where the `<admin-header>` tag is also generated via ngRoute.

**Comment by aheinze** [comment]
I think the best way would be to build custom directives.
