### ISSUE TITLE
Accordion Component - height

### ISSUE THREAD

**Issue by ivangfr** [uikit/uikit#932]
Hi,

I'm trying to use accordion + tab components.
However I have the following problem that you can see on this link: http://jsfiddle.net/coc86bwn/

Just open **Acc2**. On **Tab1** click (twince is enough) on button **"Add Text"**.
You will see that accordion component does not increase its height!

Is it a bug?

Thanks!

**Comment by aheinze** [comment]
Fixed in the develop branch
