### ISSUE TITLE
How to add uikit customizer to a new html template?

### ISSUE THREAD

**Issue by tijj** [uikit/uikit#935]
Hello,

How can I integrate customizer to html template or a new uikit based template? - Use customizer to preview the changes and also add, remove, delete styles created using customizer?

 I am looking to do this on a html site just like you did on yoo_master.

Thanks

**Comment by zslabs** [comment]
This isn't really a UIkit question as much as it is a YooTheme/Joomla question -- you may want to ask on their support forum.

**Comment by tijj** [comment]
Zach -  I have modified the question to be specific to just an html template -  No joomla or anything - Just the steps to implement uikit customizer to an html web page. Thanks

**Comment by zslabs** [comment]
If you look in the [Developers](https://github.com/uikit/uikit#developers) part of the README, it tells you how to download the UIkit repo locally and run it. Inside of those folders, is a working Customizer page; which is obviously great for you, since it's a working example you can build off of.

**Comment by tijj** [comment]
Thanks - BUT -  Why doesn't the zip file downloaded from github load the uikit customiser iframe? I click the "Customiser" menu but it just shows a blank iframe?
Thanks
