### ISSUE TITLE
Improvement: Overflow: visible for active Accordion Elements

### ISSUE THREAD

**Issue by CinKon** [uikit/uikit#936]
Hi, 

I got a little improvement-wish: "overflow: visible" for .uk-active Accordion Element.

Right now, i've got a Dropdown-Element (selectric.js) inside the .uk-accordion-content, and of course, most of the select-options are hidden because of the "overflow: hidden".

Best would be to remove this attribute when the Accordion Element is open.

Best regards

**Comment by aheinze** [comment]
this should be fixed in the upcoming release
