### ISSUE TITLE
Unable to get property 'trigger' of undefined or null reference error

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#937]
when I right click and open Developer Tools in ie11 get this error in touch.el.trigger(event) line 875 in uikit.js file. maybe raise for other reasons.

**Comment by nstaeger** [comment]
Hi,

on which page does this appear? Is this still an issue with 2.17? For me, it's fine running the [touch test](https://github.com/uikit/uikit/blob/master/tests/core/touch.html) on the latest developer build.

**Comment by seanpoulter** [comment]
I get the same bug from v2.14 on Chrome and Safari running on an iPhone, which is thrown from `[touch.el.trigger('swipe')](https://github.com/uikit/uikit/blob/c42867ba9c79519e92436502ef764ed32159388b/src/js/core/touch.js#L117).

@nstaeger, do you remember what changes resolved this bug? I've got to hotfix something in prod while I try to reproduce it in 2.17 or later.

**Comment by seanpoulter** [comment]
@mojtabakaviani, did you figure it out? This is still a problem for me.

@nstaeger, I continue to get the same error using v2.14 as well as after updating to v2.21. I tried the test pages for both tonight and haven't had the same error alert. Colleagues have confirmed we can't reproduce it on Android, and we're looking into using [Vorlon.js](https://github.com/microsoftdx/vorlonjs) to remote debug while we find a working Mac we can tinker with.
