### ISSUE TITLE
UIKit 2.16.2: vertical middle doesn't work on grid-match

### ISSUE THREAD

**Issue by CinKon** [uikit/uikit#939]
Hi,

in the newest Version (installed via bower), the "data-uk-grid-match" utility gives the containers a "MIN-height", instead of a regular height (which is generally good because of dynamical content), but the ".uk-height-1-1" and the ".uk-vertical-align-middle" Classes only work with normal height-style-attributes...

Is there any workaround to get it to work?

Best regards!

**Comment by malles** [comment]
Try using the flex component for these kind of layouts. http://getuikit.com/tests/components/flex.html

**Comment by saschadube** [comment]
I don't know of any CSS work around for the min-height/height 100% issue. But maybe build it different like @malles suggested...
