### ISSUE TITLE
Please add style for lists with icon

### ISSUE THREAD

**Issue by nevigen** [uikit/uikit#940]
I mean make new styles for list like

<_ul class="uk-list uk-icon-check-square-o">
<_li> <_/li>
<_li> <_/li>
<_li> <_/li>
<_ /ul>

will show like list with checkbox icons.
It will very good for styling lists with any icon.

**Comment by MacWordPress** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by malles** [comment]
+1
I tried this with a icon in the `:after` of the `li`. Works fine everywhere.... But not in IE.
```
/*list-checked*/
.hook-list-misc() {
  .uk-list-checked > li {
    position: relative;
    padding-left: 20px;
    &:before {
      position: absolute;
      left: 0;
      content: "\f00c";
      font-family: "FontAwesome";
      font-size: 14px;
      line-height: 23px;
      color: @list-checked-check-color;
    }
  }
  > li:nth-child(n+2) {
    margin-top: @list-line-margin-top;
  }

}
```

**Comment by saschadube** [comment]
Mhh, since there are 593 icons it would bloat the code a little :grin:

**Comment by malles** [comment]
I don't it is meant for every icon. Just the checked, and maybe some other list-bullet type of icons

**Comment by nevigen** [comment]
I think 3-7 main types of icons will be more than enough.
rest will be similar in custom.css

**Comment by MacWordPress** [comment]
What about incorporate this solution to UIkit:
http://fortawesome.github.io/Font-Awesome/examples/#list

It uses absolute icon positioning, so it has the right indentation, when the text wraps into several lines.

**Comment by malles** [comment]
@MacWordPress That is how the UIkit docs suggest it now, and is fine. But HTML-editors for instance strip out empty elements, so this can't be done easily in an editor for an enduser. Styling a regular `ul` markup makes that possible.

**Comment by saschadube** [comment]
What about a ```uk-list-bullet``` class?
