### ISSUE TITLE
Call to Action: Default theme

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#942]
Hi all,
I'm sure this has been brought up before - but what was the reasoning behind not making the "Default" theme the actual "core" stuff that is sent with UIkit? You need a theme in all sanity to interact with the UIkit framework, so normally my project structure is:

* Core
    * Theme
        * Theme Overrides and custom styles 

If the core of UIkit included the default theme; which in essence just variabalizes all of the static colors in the core -- then it would take out an unnecessary complexity step of setting up. Themes could more easily interact with the core and would actually have simpler logic overall. Would really appreciate some eyes and ears on this subject. Thanks as always.

**Comment by saschadube** [comment]
In the first UIkit releases the global variables were bundled with the core but at one point we decoupled them from the core to be more flexible and modular. I get what you are saying and it is definitely something to rethink but I would wait for UIkit 3 to do so. We have a lot of ideas for UIkit 3 especially cleaning everything up ;-) Maybe we will create a branch in the near future to put the first ideas there.
