### ISSUE TITLE
Gulp compile uikit.css instead uikit.THEME.css when tweaking the customizer

### ISSUE THREAD

**Issue by dagatsoin** [uikit/uikit#945]
When tweaking a custom theme into the customizer, Gulp will compile a dist/uikit.css but not the uikit.THEME.css

It is not just a naming glitch. It does not care about any modification in tjhe custom/*less.file

Context:
- I have a custom/playertheme
- I added custom/playertheme/theme.less and import it in custom/playertheme/uikit.less

When I tweak the customizer, it compiles a dist/uikit.less without including custom/playertheme/theme.less

When I go to the /test it compiles a uikit.playertheme.less including custom/playertheme/theme.less

**Comment by aheinze** [comment]
try to run ```gulp -a```
