### ISSUE TITLE
Issue with uk-grid in Safari 5.0.3

### ISSUE THREAD

**Issue by Tuning-Soft** [uikit/uikit#949]
Hello! It's error in two my sites((((
![2015-02-08_01 17 20](https://cloud.githubusercontent.com/assets/1108013/6093615/ca76e982-af30-11e4-861d-aebef8b956df.png)

**Comment by jerry1970** [comment]
This has nothing to do with uk-grid, your JS is incorrect.

**Comment by Tuning-Soft** [comment]
Error in file "grid.min.js"

**Comment by Tuning-Soft** [comment]
Updated Safari to 5.1.7 and the problem disappeared.
