### ISSUE TITLE
Autoprefixer: Gulp File

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#950]
I know this has been added and removed a few times in UIkit's history, but any thoughts on cleaning up the src files a bit and using Autoprefixer to do the prefixing for you? I use it regardless in my projects, but would be nice to make this initial offering easier to consume. More than happy to submit a PR for this. Thanks cc @aheinze

**Comment by aheinze** [comment]
Hi Zach,

we plan to (maybe) introduce the Autoprefixer in the next version. Thanks for the suggestion.
