### ISSUE TITLE
data-uk-grid-match="{target:'.uk-panel'}" don't work with uk-panel

### ISSUE THREAD

**Issue by Tuning-Soft** [uikit/uikit#952]
Uikit 2.6.12
Latest Firefox 35.0.1 
latest Safari  5.1.7
Page: http://lundenilonansk.ru/

why not calculated height? Thank's!
![2015-02-08_16 13 15](https://cloud.githubusercontent.com/assets/1108013/6096166/903107bc-afad-11e4-9df5-1b974b2ff7e0.png)

![2015-02-08_15 40 55](https://cloud.githubusercontent.com/assets/1108013/6096168/98763082-afad-11e4-96b3-bf3af5073b83.png)

**Comment by Tuning-Soft** [comment]
.uk-panel  don't have padding & margin

**Comment by malles** [comment]
I think we crossed here :) I guess this is the same issue as #954.
Try this UIkit version with the proposed patch: http://www.bixie.nl/uikit.gridfix.js. 
Hope it solves this as well.

**Comment by Tuning-Soft** [comment]
malles, thank you! But now with patch in Safary bug with data-uk-grid-margin
![2015-02-08_17 31 28](https://cloud.githubusercontent.com/assets/1108013/6096394/e406bc0a-afb8-11e4-8ad2-50756008300e.png)

**Comment by malles** [comment]
I don't see a `min-height` attribute on the uk-panels either...

**Comment by malles** [comment]
Seems that the bugs are not related after all.
The grid with `ul` as you use it, works fine on UIkit 2.16 (http://jsfiddle.net/h42Lgutb/1/) and 2.15 (http://jsfiddle.net/46o2pea2/1/)
You might have a different problem..

**Comment by malles** [comment]
Page is fine on my end: (newest Chrome on windows)
![screenshot_20](https://cloud.githubusercontent.com/assets/5442402/6096795/bf97e3f8-afa4-11e4-94c1-32fb09b42e9e.png)

**Comment by malles** [comment]
I think I found the problem. This is related to #920.
![screenshot_21](https://cloud.githubusercontent.com/assets/5442402/6096808/25c5ea44-afa5-11e4-8a85-1e63ed58074b.png)
This is the clearest example: http://getuikit.com/docs/addons.html#usage
Just include `uikit(.min).js` and the `uikit(.theme).css` file if you don't use any add-ons. If you do, add the css and js of the addon seperatly

**Comment by Tuning-Soft** [comment]
Yes, in Crome and Firefox it's work, bug only in Apple Safari, here
http://jsfiddle.net/h42Lgutb/3/

![2015-02-08_20 36 08](https://cloud.githubusercontent.com/assets/1108013/6096903/34a63ea6-afd2-11e4-8a31-2d353a375154.png)

**Comment by Tuning-Soft** [comment]
Now I include uikit.min.js instead core.js and other files, but the problem remains in Safari
I don't know what to do with it, this bad

![2015-02-08_20 39 37](https://cloud.githubusercontent.com/assets/1108013/6096922/a9c3de1e-afd2-11e4-816a-107f847ed943.png)

**Comment by malles** [comment]
That's weird behavior. That fiddle looks fine in my Chrome indeed. So now the problem only seems to be the grid-matching and grid-margin are not working properly in Safari.
Maybe change the title of this issue, or close it and start a new, focussing on this issue.
Is your sites js behaving better with the correct script included?

**Comment by Tuning-Soft** [comment]
Nothing has changed, same problem.
Yes, new screen in Safari with included only uikit.min.js

My girlfriend is crying, her website is broken))

**Comment by malles** [comment]
You still have different issues.. `data-uk-grid-match` is still not adding style to your panels.
![screenshot_22](https://cloud.githubusercontent.com/assets/5442402/6096974/0c7f2162-afab-11e4-9644-00da669ff8cc.png)
`data-uk-grid-margin` is working though... In Chrome and FF the flex is keeping your grid up better (I guess) and the problem is less visible.
This is beyond my scope now..
Crying women is never good.. This is getting serious.

**Comment by Tuning-Soft** [comment]
I add new issue, will have to include the old version of the Uikit
Thank for your help, malles!
https://github.com/uikit/uikit/issues/957

**Comment by Tuning-Soft** [comment]
with the patch height is considered and apply a style to .uk-panel, but then there is a problem with the indentation uk-margin.
With a standard script is not considered height and does not apply the style min-height to .uk-panel

**Comment by aheinze** [comment]
please check against the current develop branch. should be fixed now

**Comment by Tuning-Soft** [comment]
@aheinze , Thank you very much, everything works! ;)
