### ISSUE TITLE
Grid match inside panel content broken

### ISSUE THREAD

**Issue by malles** [uikit/uikit#954]
I use the `grid-match` component often to match the widths of some dynamic content in a panel. This way the bottom content (eg buttons) is aligned with each other.
Which has this effect on UIkit 2.15: http://jsfiddle.net/5m3mvm67/3/

This is now 'broken' because the first parent of the target element has the same width as the target and is flagged as `stacked`. (https://github.com/uikit/uikit/blob/master/src/js/core/grid.js#L118)
So the same markup in UIkit 2.16.2: http://jsfiddle.net/7aj61puj/5/

Maybe `firstvisible.closest('[data-uk-grid-match]')` would locate the parent better, but I wouldn't like that in the generic function `Utils.matchHeights`. I think the only solution is to pass the parent into the `Utils.matchHeights` function to compare it for `stacked`. I'll attach a PR for that.

**Comment by malles** [comment]
Added example with this patch: http://jsfiddle.net/23x21pcy/1/

**Comment by aheinze** [comment]
Fixed with this commit: https://github.com/uikit/uikit/commit/74d26410ce0ee25730f857b20655b5ac858845e4

**Comment by malles** [comment]
Took me a while to get this one! I now see the reasoning behind the columns and elements. Nice.
