### ISSUE TITLE
Nestable Events Don't Give Moved Element

### ISSUE THREAD

**Issue by NeonMonk** [uikit/uikit#956]
When a move has finished on a Nestable object there is no information as to what exactly has been moved.

The 'stop.uk.nestable' event only gives you the event object & the nestable object. This is not very useful.

**Comment by NeonMonk** [comment]
Discovered undocumented 'change.uk.nestable' event - very strange leaving this event undocumented.

Please add this to the Nestable documentation!

**Comment by aheinze** [comment]
this is already fixed in the develop branch, thanks!
