### ISSUE TITLE
data-uk-grid-match bug in Apple Safari

### ISSUE THREAD

**Issue by Tuning-Soft** [uikit/uikit#957]
Uikit 2.6.12
Latest Safari 5.1.7
Page: http://lundenilonansk.ru/
For example: http://jsfiddle.net/h42Lgutb/4/

The height of panels not correct match in uk-grid only in Safari with included one file uikit.min.js
![2015-02-08_20 39 37](https://cloud.githubusercontent.com/assets/1108013/6096985/50e59406-afd5-11e4-8916-b47c4aabc731.png)

**Comment by aheinze** [comment]
should be fixed with this commit: https://github.com/uikit/uikit/commit/74d26410ce0ee25730f857b20655b5ac858845e4

**Comment by Tuning-Soft** [comment]
cool, thank you!
