### ISSUE TITLE
Add triggered event for Notify component closed by user

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#959]
Notify component accepts a `onClose` parameter to execute custom code when the element is closed (by user or automatically by browser).

A triggered event (like `close.uk.alert` for alerts) should be added when the element is actually closed by user.

**Comment by aheinze** [comment]
Added with this commit: https://github.com/uikit/uikit/commit/375ff4e0caff33553dfa7690c2d680a2db023367

**Comment by robertotremonti** [comment]
That was fast!
Thank you.

**Comment by Intiligent** [comment]
How use event?
event trigger "on" not work, function on is undefined

```javascript
var notify = UIkit.notify(item.text, {pos: 'top-center', timeout: 0});
notify.on("close.uk.notify", function() {
    // do it
});
```
but work:

```javascript
var notify = UIkit.notify(item.text, {pos: 'top-center', timeout: 0, onClose: function() {
     // its work but not wonderfull
    // better be used notify.on('close.uk.notify', ...);
}});
```
