### ISSUE TITLE
Add Timeline Component

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#961]
please add timeline component like github, facebook and twitter for historical articles

**Comment by mojtabakaviani** [comment]
thanks a lot! and l will hope add wizard component.

**Comment by jerry1970** [comment]
Your wizard request was rejected as it was too specific, see #926 .

**Comment by aheinze** [comment]
Sorry, but I think this is also to specific, but we keep it on our watch list. thank you for the suggestion.

**Comment by malles** [comment]
I think both features are a combination of existing components that are coupled in a javascript script. That is what UIkit is made for in my opinion, to give these tools (buttons, tabs, navigation, badges, animation) to a developer to turn them into a page like a timeline or wizard.
Maybe open-source that combo to the community so there can be a UIkit-timeline for everyone.

**Comment by jerry1970** [comment]
Personally, I wouldn't want a toolkit like UIKit prescribe how a wizard or timeline looks like. I want it to give me the basic elements, which I can use to build the rest of the site with.

A timeline or wizard is too specific. Let me explain. I have three different looking wizards in a single project. Making those using the basic UIKit elements is easier than to use a predefined wizard and changing two of them to get what we want. Of course, the three wizards are used throughout the project and I only had to define them once. I don't have a timeline, but the same logic applies to timelines. Build one yourself using the basic elements.

**Comment by flyboarder** [comment]
Has anyone built a timeline component that they are willing to share?

**Comment by evdama** [comment]
I've been looking for one, something along the lines of https://picturepan2.github.io/spectre/experimentals/timelines.html

I didn't really find one for uikit though. Has anyone build something and is willing to share please?
@aheinze You're not wrong saying that it's to specific but a lot has changed in four years to these days I think it's pretty much a standard component and the internet has gotten used to timelines. UIkit should have one, folks would love it a lot :)

**Comment by KaitaniLabs** [comment]
Essentially ripped from the Spectre experimental with some minor conversions into **UIkit-speak**. Could reduce the CSS with some uk-flex classes. Feel free to do what you want with it. Also added some much needed variable colours for **uk-badge**.
````
    .timeline .timeline-item {
    display: flex;
    display: -ms-flexbox;
    margin-bottom: 1.2rem;
    position: relative;
}
.timeline .timeline-item::before {
    background: #dadee4;
    content: "";
    height: 100%;
    left: 14px;
    position: absolute;
    top: 30px;
    width: 2px;
}
.timeline .timeline-item .timeline-left {
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
}
.timeline .timeline-item .timeline-left .uk-badge {
    padding: 0;
    margin: 0;
    width: 30px;
    height: 30px;
}
.timeline .timeline-item .timeline-left .uk-badge.uk-badge-danger {
  background: #f0506e;
}
.timeline .timeline-item .timeline-left .uk-badge.uk-badge-success {
  background: #32d296;
}
.timeline .timeline-item .timeline-left .uk-badge.uk-badge-warning {
  background: #faa05a;
}
.timeline .timeline-item .timeline-left .uk-icon {
    color: #fff;
}
.timeline .timeline-item .timeline-content {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 0 0 0 1rem;
}
````

````
    <div class="timeline">
        <div class="timeline-item">
            <div class="timeline-left">
                <span class="uk-badge"><span uk-icon="bolt"></span></span>
            </div>
             <div class="timeline-content">
                 <div class="uk-card uk-card-default">
                     <div class="uk-card-header uk-flex-middle uk-grid-small" uk-grid>
                         <h3 class="uk-card-title">Title</h3>
                         <span class="uk-label uk-margin-auto-left">Label</span>
                     </div>
                     <div class="uk-card-body">
                         <p>Content here</p>
                      </div>
                  </div>
              </div>
          </div>
         <div class="timeline-item">
            <div class="timeline-left">
                <span class="uk-badge uk-badge-danger"><span uk-icon="heart"></span></span>
            </div>
             <div class="timeline-content">
                 <div class="uk-card uk-card-default">
                     <div class="uk-card-header uk-flex-middle uk-grid-small" uk-grid>
                         <h3 class="uk-card-title">Title</h3>
                         <span class="uk-label uk-margin-auto-left">Label</span>
                     </div>
                     <div class="uk-card-body">
                         <p>Content here</p>
                      </div>
                  </div>
              </div>
          </div>
    </div>
````
