### ISSUE TITLE
Action Move Sortable

### ISSUE THREAD

**Issue by robertotaiko** [uikit/uikit#962]
Hi:
I'm making a list so you can sort through the add-on, but do not know how to pick the new order when the user has moved one of the items on the list, could you help me? thanks.

**Comment by malles** [comment]
I use something like this:
```
       (function ($) {
		$(document).on('ready', function () {
			var sortable = $('[data-uk-sortable]');
			sortable.on('stop.uk.sortable', function (e, el, type) {
				setOrdering(sortable, el);
			});
			setOrdering(sortable);
		});
		function setOrdering(sortable, activeEl) {
			var formordering = 1;
			sortable.find('>li').each(function () {
				var ele = $(this);
				ele.find('input').val(formordering);
				ele.find('div.uk-badge').text(formordering);
				formordering++;
			});
			if (activeEl) {
				activeEl.find('div.uk-badge').addClass('uk-animation-scale-down');
			}
		}
	})(jQuery);
```
This script presumes you have one input in the `li` that holds the ordering, and a `div.uk-badge` to display it to the user.
```
<li>
<div class="uk-panel uk-panel-box">
	<div class="uk-badge uk-badge-notification uk-panel-badge">0</div>
	<input type="hidden" name="formordering" value="0" />
	<strong>Title</strong>
</div>
</li>
```
Should look like this:
![screenshot_23](https://cloud.githubusercontent.com/assets/5442402/6110533/a911b71a-b082-11e4-86ce-a02d3a52cef4.png)

**Comment by robertotaiko** [comment]
Ok, I try this code, but not working, in  $('[data-uk-sortable]'); I put Id of the <ul>  $('#listtest'); It's correct?

**Comment by malles** [comment]
Your `ul` should have the attribute `data-uk-sortable`, but you could select it by it's id.

**Comment by aheinze** [comment]
thanks @malles
