### ISSUE TITLE
Disable behaviour in input  uk-accordion-title

### ISSUE THREAD

**Issue by thinkink** [uikit/uikit#970]
<h3 class="uk-accordion-title"> <input type="text">Title of accordion </h3>
    <div class="uk-accordion-content"> 
.....
</div>	

is possible to disable the behavior (onClick) of an input in the title of the uk-accordion

**Comment by malles** [comment]
You can setup your accordion to trigger on another element than the default `.uk-accordion-title` [docs](http://getuikit.com/docs/addons_accordion.html#javascript-options). That way you can place your input inside the title, and have another element/button act as the trigger.

**Comment by aheinze** [comment]
thanks @malles
