### ISSUE TITLE
javascript function for data-uk-toggle inside uk-form triggers submit event

### ISSUE THREAD

**Issue by manfredk** [uikit/uikit#971]
Probably event.preventDefault() is missing

**Comment by malles** [comment]
You should always make your buttons `type="button"`. For good practice, but especially in forms to prevent submitting. A `button` as itself should not fire a event to prevent.

**Comment by manfredk** [comment]
Thanks. That works. To solve the problem I would have suggested to change line 47 of toggle.js to
               	
    if ($this.element.is('a[href="#"]') || $this.element.is('button')) e.preventDefault();

That works too and would make UIkit a little bit more foolproof (sigh) - especially since there is no hint pointing to your solution anywhere ... but probably I'm just not the html/css wiz ... :(

**Comment by aheinze** [comment]
as @malles said ```type="button"``` is always required for "normal" buttons. I don't want to bloat the code with an unneeded extra check.
