### ISSUE TITLE
uk-navbar-attached, data-uk-sticky, and uk-navbar-flip

### ISSUE THREAD

**Issue by dstasinski** [uikit/uikit#975]
When using data-uk-sticky on a navbar attached with uk-navbar-attached, when clicking on the uk-navbar-toggle, the navbar does not slide over with the content.

Also, when using uk-navbar-flip on a navbar with uk-navbar-attached, the content covers the navbar.  Had to add style="z-index:1;" to the [nav] to make it look correct.

**Comment by saschadube** [comment]
Please provide a [JSFiddle](http://jsfiddle.net/).
