### ISSUE TITLE
Write customizer generated css to a folder on server instead of downloading

### ISSUE THREAD

**Issue by tijj** [uikit/uikit#977]
Hello,

The customizer currently provides an option to download the updated css file. How to write the css file to a path such as /style/css/theme.css ?

In other words how to modify the download=uikit.css attribute to a functionality to write that css file to a path?

Thanks

**Comment by saschadube** [comment]
Since this is not an UIkit issue, I closed it.

**Comment by tijj** [comment]
Hi Sacha  -  I asked the question in stackoverflow and no one has any idea because of how you have done it in the uikit package. Any clues or ideas would be appreciated as to how the uikit css can be written to a file because that will be the whole purpose of the css file -  Just like you did in yoo_master theme. 
Thanks
