### ISSUE TITLE
Sticky: No Destroy Method

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#983]
Hey @aheinze,
We had discussed some of this on https://github.com/uikit/uikit/issues/474 but I have a Backbone application that's stateless, with two different "stickied" items on a page based on the view, one of which needs to be turned off (that was previously stickied) when that view is changed. I don't see any type of `destroy()` method in the sticky component. Is there a way I can revert that? Thanks!

**Comment by orestisioakeimidis** [comment]
A `destroy()` method for every component would be very useful! It can be used also in angular directives, when the scope is destroyed, destroy also the component that is bind to the element. Extremely useful for performance reasons. Thanks!

**Comment by aheinze** [comment]
@zslabs done: https://github.com/uikit/uikit/commit/d7670ca0887652d8f1f2005e117e1113cb10ed52

**Comment by zslabs** [comment]
Badass! Thanks man!

**Comment by oknoorap** [comment]
agree with @orestisioakeimidis
