### ISSUE TITLE
Check display documentation not clear on grid addon

### ISSUE THREAD

**Issue by malles** [uikit/uikit#985]
[This section](http://getuikit.com/docs/documentation_javascript.html#data-check-display) of the Javascript docs on `data-uk-check-display` starts with mentioning that problems can occur with the _component_ grid can give trouble when hidden in the markup.
A few lines later it mentions "This is not needed for the Grid, it's triggered by default.". Which applies to [`data-uk-grid-match` and `data-uk-grid-margin`](https://github.com/uikit/uikit/blob/master/src/js/core/core.js#L254), the javascript parts of the core grid _component_.
This in itself is an ambiguity.
It gets more confusing since the new _add-on_ grid does need the  `data-uk-check-display` attribute to be triggered when coming into display.
I think that that part of the doc need to be more clear on the grid-situation. Perhaps including `[data-uk-grid]` to the default checkDisplay selectors would be wise, that's up to the UIkit team.

**Comment by aheinze** [comment]
docs are updated now, thanks.
