### ISSUE TITLE
Reset Scroll to top in modal

### ISSUE THREAD

**Issue by thinkink** [uikit/uikit#991]
I'm reusing a modal with angular with uk-overflow-container.

When i scroll to view a list of items and close, after when reopen the modal for display another list of items the position of uk-overflow-container is the last. 
I would to reset container to the top every open or close this.

Thanks on advance

**Comment by saschadube** [comment]
Try to get help in the [UIkit Google+ community](https://plus.google.com/communities/114238665434626719878)

**Comment by xthukuh** [comment]
Just in case anyone else goes through what I went through, just set the css as follows:

```
body {
	overflow: hidden;
}
html {
	overflow-y: auto;
}
```

**Comment by xthukuh** [comment]
and use css `height: 100vh;` instead of `uk-height-1-1`
