### ISSUE TITLE
Flex component in core - IE9?

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#993]
I see in changelog (develop):
IMPORTANT: Moved flex and cover component into the core
What about IE9? Does this mean the end of support for IE9?
http://caniuse.com/flexbox

**Comment by saschadube** [comment]
UIkit is still working fine in IE9 but we are moving flexbox slowly into the core. Sure, the flex classes won't work in IE9, but you know that and don't have to use them if you don't want to.
