### ISSUE TITLE
Notifications Dropdown

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#994]
please add dropdown notification mode `uk-dropdown-notification` for show dropdown  as notifications
![01_nab_notifications_1x](https://cloud.githubusercontent.com/assets/1667525/6273221/c87c501c-b882-11e4-8bcc-d57102647949.png)

**Comment by zslabs** [comment]
Could you not just append on whatever notification you need to that dropdown list and then just call dropdown's `show()` method?

**Comment by mojtabakaviani** [comment]
good idea!
if can add item to dropdown list very good, but now just show dropdown as notification mode design

**Comment by aheinze** [comment]
thanks for the suggestion, but this is too specific and should be easily created with existing components.

**Comment by mojtabakaviani** [comment]
why always closed suggestions, just add `uk-dropdown-notification` change design to notification and not very specific.

**Comment by malles** [comment]
Because it van be easily created adding a `uk-dropdown-notification` and some minor design. Hence, use the framework to create this specific need. A framework gives you article titles, subtitles and text-styling, but you won't expect them to create an article for you. Kind of the same I think.
