### ISSUE TITLE
Add '.uk-visible' for toggling elements on hover

### ISSUE THREAD

**Issue by robertotremonti** [uikit/uikit#996]
As [documented](http://getuikit.com/docs/utility.html#visibility-utilities), `.uk-visible-hover` and `.uk-hidden` classes can be used to show an element on hover.
A `.uk-visible` (or something opposite to `.uk-hidden`) should be added to make elements toggling possible on hover.

For example, a secondary button `X` that's replaced by a primary button `Y` hovering on a panel.

**Comment by malles** [comment]
+1
For revealing a hidden object with scrollspy, for instance.

**Comment by malles** [comment]
Problem is to revert `uk-hidden`, `uk-display-block` does not do the trick because `uk-hidden` also sets  `visibility: none !important;`.
Classes `uk-visible` and `uk-visible-inline`, similar to `uk-visible-hover-inline` classes would be highly appreciated.

**Comment by aheinze** [comment]
thanks for the suggestion, we'll consider it for future releases.
