### ISSUE TITLE
Slideshow container height

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#999]
I have a slideshow with content (something like here: http://getuikit.com/docs/addons_slideshow.html#content ). Each content have different height.
It be good, when the height will have dynamically value (default or by parameter), based on each content - now they based on the biggest content from all - if I have e.g. 2 slides - first with long content, second with short content - the second slide have much empty space :(

Demo: http://www.owlcarousel.owlgraphic.com/demos/autoheight.html

**Comment by aheinze** [comment]
can't you just center the content with the minor height?

**Comment by alexdevine** [comment]
@aheinze I think what he means is is slider is not dynamic. If you have one image with 600px in height and then a image at 1000px in height the slider takes its biggest container and displays at 1000px.

**Comment by aheinze** [comment]
this is the behaviour by design dynamic height bring way more issues, especially in autoplay mode and jumping content below the slideshow for example
